### ISSUE TITLE
JSON Bug if Memory >=8000MB?

### ISSUE THREAD

**Issue by TheOneWhoKnocks** [pterodactyl/panel#1002]
Hey folks,

after updating my panel to 0.7.x and all my daemons to 0.5.x I discover a rather strange behaviour when creating a server that hast 8196MB of of memory resource allocated.
As soon as I try to create, for example a Minecraft Forge Server, with that amount of RAM I get the following json errors in wings.log:

`"pid":6010,"level":60,"err":{"message":"(HTTP code 500) server error - json: cannot unmarshal number 8589407999.999999 into Go struct field HostConfig.Memory of type int64 ","name":"Error","stack":"Error: (HTTP code 500) server error - json: cannot unmarshal number 8589407999.999999 into Go struct field HostConfig.Memory of type int64 \n    at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17\n    at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)\n    at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)\n    at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"msg":"A fatal error was encountered while attempting to create a server.","time":"2018-02-27T15:45:49.597Z","v":0}`

After that, the installation process in the panel isn't aborted, it just runs forever and you need to delete the server again. As soon as I install the server with less than 8196MB of RAM, everything just works fine.

As I'm a total noob with json I can't really do anything about it by myself except giving the log output,  maybe there are more people out there who also experience this behaviour and can confirm that this is a bug and not something in my installation that's just wrong. 

* Version of Panel/Daemon: Panel 0.7.3 Daemon: 0.5.3
* Server's OS: Debian 9
* Your Computer's OS & Browser: Firefox/Chrome - Manjaro Linux

------------------------
php -v:
`PHP 7.2.2-1+0~20180205160742.18+stretch~1.gbpb78b58 (cli) (built: Feb  5 2018 16:07:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2-1+0~20180205160742.18+stretch~1.gbpb78b58, Copyright (c) 1999-2018, by Zend Technologies
`
uname -a:

`Linux <censored hostname> 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) x86_64 GNU/Linux`

docker info:

`Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 15
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.54GiB
Name:
ID: KIM3:PDEO:BG7G:75EO:RE7I:363C:XAE4:QSXL:2J36:4D3P:ABOI:ZXQ4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
`

--->

**Comment by TheOneWhoKnocks** [comment]
Actually this problem occurs as soon as the memory is more than 8000MB. 8001MB allocated will end up in the same behaviour. Also updating the build configuration above 8GB is impossible, the panel will just refresh the site and no changes will be made.

**Comment by parkervcp** [comment]
I have added servers with over 8000M of ram on my own systems. I have had at least 2 at 8192M and now I have one at 16 gigs (16384M) and it started and is running fine.

**Comment by TheOneWhoKnocks** [comment]
Well it also works when installed on a new node I added, any suggestion what could cause this 8Gb Limit?

**Comment by parkervcp** [comment]
If this is an issue on an older node have you completely reinstalled the daemon it?

**Comment by GwtLabs** [comment]
You do not use the kernel in the generic version. Maybe this is the reason?

**Comment by parkervcp** [comment]
You should be backing up the config folder in the `/srv/daemon/` folder.

**Comment by TheOneWhoKnocks** [comment]
I fixed the issue by updating to docker 18.02.0~ce-0~debian from the edge repository, with docker 18.01.0~ce-0~debian It somehow doesn't seem to work.

**Comment by parkervcp** [comment]
I have Cent OS 17.12.0-ce

I woun't recommend running edge builds ever. I will be closing this now.
