### ISSUE TITLE
ARK server cant start,I

### ISSUE THREAD

**Issue by WintopPVP** [pterodactyl/panel#1004]
I have same problem to ark in this site
https://github.com/pterodactyl/panel/issues/899
i ask question dont have solve it
If can solve it ，thank you very much！！
* Panel or Daemon: 7.3
* Version of Panel/Daemon: 
* Server's OS: centos7.4
* Your Computer's OS & Browser: centos7.4

Please provide additional information, depending on what you have issues with:
Panel: `php 7.2
Daemon: `5.2
--->

**Comment by DaneEveritt** [comment]
As was said in the previous issue, this is a problem with the egg not seeing anything to trigger a server started event on, not a bug in the software.

**Comment by WintopPVP** [comment]
thank you
