### ISSUE TITLE
SFTP Host Key Issue

### ISSUE THREAD

**Issue by x-Josh** [pterodactyl/panel#1011]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v0.5
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows Server 2016 & Firefox

------------------------

Hello,

I have been having issues with uploading files bigger than 1GB via SFTP. Every time it hits 1GB, FileZillow shows this: 

Error:	Server's host key did not match the signature supplied
Error:	File transfer failed after transferring 1,070,071,808 bytes in 39 seconds

If you need any information from my dedicated server, let me know. 
Just incase, here is my "docker info"

> root@ubuntu:~# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.3GiB
Name: widowhosting
ID: 4PH5:TRA5:JVWM:JYC6:5EZJ:CXFY:V7NF:P4UK:B5BJ:R3RU:OXZG:JML2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by DaneEveritt** [comment]
Can you provide the daemon logs as well?

**Comment by x-Josh** [comment]
>Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.3GiB
Name: widowhosting
ID: 4PH5:TRA5:JVWM:JYC6:5EZJ:CXFY:V7NF:P4UK:B5BJ:R3RU:OXZG:JML2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

{ pteronode: '0.5.2',
  npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.4',
  openssl: '1.0.2n',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.50',
  zlib: '1.2.11' }
00:02:36.839Z  WARN wings: Received an unknown OPEN flag during SFTP operation. (server=b9ade65a-20a7-4abc-9378-ff4e2c1cfceb, flag_id=2, flag=null)
    path: /garrysmod/addons/en_windows_7_home_basic_with_sp1_x86_dvd_u_676470.iso
    --
    identifier: YArXD8JvbdOpsXsjttmBxN0dDYAgSPknGbeFwUZmrcgcAbWHn9nQaiJEcCILuJ7U
00:24:50.259Z  WARN wings: Received an unknown OPEN flag during SFTP operation. (server=b9ade65a-20a7-4abc-9378-ff4e2c1cfceb, flag_id=2, flag=null)
    path: /garrysmod/addons/en_windows_7_home_basic_with_sp1_x86_dvd_u_676470.iso
    --
    identifier: ZcpD65994xUinVjKat3V86WR035rRnCC0ZAEx4oeF9UVY0GFZrsS3KcFUo9oMbIU

**Comment by DaneEveritt** [comment]
closed in f92646e

**Comment by x-Josh** [comment]
https://a.pomf.space/jljoyghoycch.png

That happens for WinSCP.
