### ISSUE TITLE
API Endpoint for predicting automatic deployements node + allocation

### ISSUE THREAD

**Issue by TrixterTheTux** [pterodactyl/panel#1012]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.4

Would there be any chance you could implement API endpoint to find suitable nodes using the auto-deployment? It would allow manually to get suitable node + allocation, which allows deploying more allocations on the server creation. Currently, this is impossible due to the server not being installed yet on daemon (not allowing to update build configuration) and the only way is to use the allocation field instead of the deploy field.

**Comment by Edbtvplays** [comment]
Will this happened to be released at 0.8?

**Comment by buracat** [comment]
yes very necessary
