### ISSUE TITLE
Problem upgrade panel to latest version ;(

### ISSUE THREAD

**Issue by Ronnon78** [pterodactyl/panel#1014]
* Panel or Daemon: 
* Version of Panel/Daemon: 
* Server's OS: Ubuntu 16.04 LTS
* Your Computer's OS & Browser: MBP, Safari 

------------------------
php -v:
```
PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  6 2018 16:11:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2-3+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

uname:
`inux mc 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

When a try upgrade panel to latest version, command: `composer install --no-dev `

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for aws/aws-sdk-php 3.52.6 -> satisfiable by aws/aws-sdk-php[3.52.6].
    - aws/aws-sdk-php 3.52.6 requires ext-simplexml * -> the requested PHP extension simplexml is missing from your system.
  Problem 2
    - s1lentium/iptools v1.1.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - s1lentium/iptools v1.1.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - Installation request for s1lentium/iptools v1.1.0 -> satisfiable by s1lentium/iptools[v1.1.0].`

how to fix this ?

**Comment by Ronnon78** [comment]
ok - please delete this issue

**Comment by Nols1000** [comment]
You can close this issue yourself ;)
