### ISSUE TITLE
Application API - Upon Creating redirects to Account API

### ISSUE THREAD

**Issue by Yomanz** [pterodactyl/panel#1016]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.4-h1
* Server's OS: Ubuntu 17.10
* Your Computer's OS & Browser: Ubuntu 17.10 Firefox

------------------------
PHP 7.2.2-3+ubuntu17.10.1+deb.sury.org+1 (cli) (built: Feb  6 2018 16:11:55) ( NTS )

I can confirm it happens for another installation also.

**Comment by Yomanz** [comment]
To expand on it: It doesn't seem to create it as an Application API as I am getting 403 errors when trying to suspend

**Comment by WrenAdler** [comment]
I can confirm this issue as well.

**Comment by DaneEveritt** [comment]
Please provide actual details and steps to reproduce, I don't understand what you're even saying is broken.

**Comment by Yomanz** [comment]
If you goto make an application API Key, you can choose the perms you want etc and name it but upon clicking create it redirects you to the Account API page with the same name you put into the application api part and i believe it is making them as Account APIs

**Comment by WrenAdler** [comment]
^

**Comment by WrenAdler** [comment]
Making it impossible to implement your API key for the WHMCS module.

**Comment by Yomanz** [comment]
Or anything else for that matter
