### ISSUE TITLE
Starting Mod Manager | Future Request

### ISSUE THREAD

**Issue by WrenAdler** [pterodactyl/panel#1017]
Hello, I will try to not take up much of your time. I used TCAdmin a couple of months ago, I was able to create a mod manager quickly and efficiently. I feel adding a way to create a mod manager that can be configured in a way that is similar to the TCAdmin one would be great. There are many of people who would love to have a mod manager for easy access to mods, gamemodes, scripts, and mounts. If you could make a simple mod manager and have it be able to simply add more things inside a .zip file would be great and much appreciated. I thank you for your time and I hope someday this can become a reality.

An example of this would be:
http://www.tcadmin.com/onlinehelp/admin/mods/index.html?introduction.htm

**Comment by DaneEveritt** [comment]
A mod manager will not be a core component of this software, but I welcome the community to create an addon module for the Panel that can do this.

**Comment by WrenAdler** [comment]
Ok
