### ISSUE TITLE
Change theme color to new color

### ISSUE THREAD

**Issue by Derkades** [pterodactyl/panel#1018]
With the recent color updates (which look a lot better) the theme color should be changed too.

![Screenshot](https://image.ibb.co/d60TV7/Screenshot_20180304_005529.png)

**Comment by DaneEveritt** [comment]
Not really sure what you're asking for here.

**Comment by schrej** [comment]
He mean's the color of the browser bar.

**Comment by DaneEveritt** [comment]
Is that even controllable?

**Comment by Derkades** [comment]
Yes, with a meta tag https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android
