### ISSUE TITLE
Better/more Administrative Management Options

### ISSUE THREAD

**Issue by vipesz** [pterodactyl/panel#1024]
* Panel or Daemon: v0.7.x & v0.5.x
* Version of Panel/Daemon: Daemon & Panel
* Server's OS: CentOS 7.4
* Your Computer's OS & Browser: Firefox Quantum, Windows 10 Professional

# Additional Details

- [x] - Ability to disable end-user access to start/kill/stop servers to avoid any issues that may arise, still allow user to view console output
- [ ] Perhaps some sort of node maintenance mode - prompt the user with a orange prompt that the node is under maintenance. 

This would disable any user input including access to FTP, stop/start/kill commands, and prompt the user with a message similar to XHR Poll Error explaining the node in under maintenance mode, and have a new status that would say [MANT] or [MNT] that would be orange. This can be enabled either CLI or via the admin panel, and enables features that would aid in administrative actions (including what has been said below) 

- [x] - Ability to rebuild server configuration in /srv/daemon/config/servers
- [x] - Easy ability to mass-rebuild containers
- [x] - Easy ability to mass reimage containers (Useful in pre-existing large deployments to change the images to custom ones)

**Comment by DaneEveritt** [comment]
Mass rebuilding is already possible, you had to use the mass rebuild command when you updated.

**Comment by DaneEveritt** [comment]
The first bullet point should go with issue #142, the second can be this issue, the third one already exists, and the fourth is a very specialized function that can be accomplished with a little bit of SQL query work and the rebuild command from the 3rd bullet.

Please adjust this issue to be specifically about the second bullet, or create a new issue and close this one. Thanks!

**Comment by DaneEveritt** [comment]
Your remaining issue here is still covered by #142, so I'm closing this. Feel free to move some of these comments over to that issue.
