### ISSUE TITLE
Updating the new Mail/Advanced option it stop the queue worker service

### ISSUE THREAD

**Issue by xion87** [pterodactyl/panel#1026]
* Panel or Daemon:  Both?
* Version of Panel/Daemon:  0.7.3/0.5.4
* Server's OS: Ubuntu 16 LTS
* Your Computer's OS & Browser:  Chrome/Windows 10

------------------------
When i update something of the option in "Mail and Advanced" setting and poppup the message "Advanced settings have been updated successfully and the queue worker was restarted to apply these changes." it will stop the queue worker instead restart it

**Comment by DaneEveritt** [comment]
Are you using the service provided by our documentation, or some custom one. I ask because it fires a `queue:restart` which should end the process and have it auto-started by the service.

**Comment by xion87** [comment]
i used mailjet SMTP

Il mar 6 mar 2018, 20:46 Dane Everitt <notifications@github.com> ha scritto:

**Comment by DaneEveritt** [comment]
I mean what system service are you using the run the queue worker.

**Comment by DaneEveritt** [comment]
I just noticed the documentation is actually wrong here, and that would explain the amount of people having issues with the queue worker. Thanks for reporting this, I've changed `Restart=on-failure` to `Restart=always` for the systemd file.
