### ISSUE TITLE
Wrong daemon configuration generated (ssl)

### ISSUE THREAD

**Issue by xion87** [pterodactyl/panel#1029]
Panel or Daemon: Panel
Version of Panel/Daemon: 0.7.3/0.5.4
Server's OS: Ubuntu 16 LTS
Your Computer's OS & Browser: Chrome/Windows 10

I noticed when i installed the panel (since my panel is in different macchine and both are under cloudflare)
I got these setting on panel
![image](https://user-images.githubusercontent.com/3611852/37099333-52d820e2-2220-11e8-8464-913a800b34f2.png)

And the generated configuration is this
![image](https://user-images.githubusercontent.com/3611852/37099372-679dfc54-2220-11e8-8078-300733d8d350.png)

The correct configuration should be this
        "ssl": {
            "enabled": true,
            "certificate": "/etc/letsencrypt/live/mc.trollandia.it/fullchain.pem",
            "key": "/etc/letsencrypt/live/mc.trollandia.it/privkey.pem"

Since i turned the ssl on on first screenshot, otherwise, the panel can't comunicate correctly with the daemon

**Comment by DaneEveritt** [comment]
This is not a bug, you have it set to be behind a proxy, so the daemon does not try to use SSL by default.

**Comment by xion87** [comment]
if i use Not behind proxy,  panel can't connect to daemon

**Comment by DaneEveritt** [comment]
Then just edit that file. This is still not a bug and was designed to work correctly with the way a lot of people use Cloudflare.

Proxies are an area that the panel can only make so many assumptions about.
