### ISSUE TITLE
Per-server customized commands

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#103]
Was looking at a project recently ([ScriptServer](https://github.com/garrettjoecox/scriptserver)) and thought it might be interesting to allow users to specify custom command aliases in the panel that can then be used on the server or through the console.

Example, from ScriptServer, giving teleport style commands and such to a vanilla MC server.

**Comment by ET-Bent** [comment]
Looks interesting. You want **specific** users to be able to execute panel actions?

**Comment by DaneEveritt** [comment]
Not necessarily panel actions, but make it so entering (from ScriptServer example) `~tphere <player>` would execute `/tpa <player> <sender>` or something similar.

**Comment by ET-Bent** [comment]
okay would be reasonable for pure vanilla servers without any kind of plugins or modifications.
