### ISSUE TITLE
Swap reCAPTCHA "Secret Key" position with "Website Key"

### ISSUE THREAD

**Issue by Pixelhash** [pterodactyl/panel#1030]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.5

------------------------

In my opinion the position of the reCAPTCHA "Secret Key" should be swapped with the reCAPTCHA "Website Key" in the panel's advanced settings. Why?
If you compare the position of both keys with the position of the keys at Google's reCAPTCHA dashboard, you'll notice that they are positioned the other way round.

_Pterodactyl Panel:_
![recaptcha_pterodactyl](https://user-images.githubusercontent.com/3688417/37100911-8a37298a-2224-11e8-86eb-00c9efcde2fd.png)

_Google reCAPTCHA Dashboard:_
![recaptcha_google](https://user-images.githubusercontent.com/3688417/37100923-90521064-2224-11e8-88fe-e0606c3e444c.png)

I know this is only a minor point of difference, but I think it's important to be consistent with Google here (even because many people are just copy-pasting the keys without looking which one belongs where).

**Comment by schrej** [comment]
It should rather be "Site Key" then, should it not?

**Comment by Pixelhash** [comment]
Sure. But I think the internal name can stay the same.
