### ISSUE TITLE
Changing theme results in css and js not being linked

### ISSUE THREAD

**Issue by stanjg** [pterodactyl/panel#1031]
* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.7.5
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10, Chrome

# Issue
Creating a seperate theme folder results in the css and js not being linked properly.
![Result](http://this-picture.is-really.cool/i/RGZ.png)
![Result](http://this-picture.is-really.cool/i/Jt5.png)

# Steps to recreate
Duplicate the pterodactyl folder in both `/resources/themes` and `/public/themes`, and give the folders a new name. Then change the `APP_THEME` option in the `.env` file to the same name as the folders.

**Comment by Bl4ckSpr4y** [comment]
Can confirm, same issue.

**Comment by DaneEveritt** [comment]
Did you add a new theme to `config/themes.php`?

**Comment by stanjg** [comment]
Oh, I am sorry. I did not know that was needed. Issue closed.
