### ISSUE TITLE
File Manager error on editing files more than 1 directory deep

### ISSUE THREAD

**Issue by OrangeJuiced** [Pterodactyl/Panel#104]
I ran into an issue using the File Manager.  It gives this error:
```
Not Found

The requested URL /server/31049689/files/edit/logs/test/latest.log was not found on this server.
```

This happens when going more than 1 folder deep and trying to edit a file. If I put latest.log directly in /logs it works fine.

**Comment by DaneEveritt** [comment]
I cannot reproduce this on my system. I can load the files fine, even when nested.

File browser is URL encoding the end of the URLs, which could potentially be the issue, but shouldn't be.

```
Work fine:
/server/b5e6b8ce/files/edit/logs%2Ftest/newfile.txt
/server/b5e6b8ce/files/edit/logs/test/newfile.txt
```

**Comment by DaneEveritt** [comment]
After further investigation it appears to be something with apache not liking URL encodes.

`/server/31049689/files/edit/logs/test/latest.log` works
`/server/31049689/files/edit/logs%2Ftest/latest.log` doesn't

Rewriting the file manager right now, so going to hold off on any hotfixes until `v0.5.0`.
