### ISSUE TITLE
Console formatting broken?

### ISSUE THREAD

**Issue by StealWonders** [pterodactyl/panel#1040]
* Panel & Daemon: 0.7.5 / 0.5.4 
* Server's OS: Ubuntu 16.04 LTS
* Your Computer's OS & Browser: Windows 10 / Firefox 

------------------------

The console formatting seems broken as in the following image:
[https://i.gyazo.com/cf45576a5f2e6e96f8205a8d2db0e550.png](url)
Also commands that are being typed get destroyed over multiple lines sometimes.

**Comment by vipesz** [comment]
this also seems to be an issue in our deployment

**Comment by TheTrueColonel** [comment]
I noticed when running vanilla Minecraft server it's fine, but forge has this issue.

**Comment by DaneEveritt** [comment]
closed in b73ec6b
