### ISSUE TITLE
SFTP BUG

### ISSUE THREAD

**Issue by LeCanadienOP** [pterodactyl/panel#1042]
* Daemon
* Version of Panel/Daemon: Lasted
* Server's OS: Ubuntu 16.04 TLS Server
* Your Computer's OS & Browser: Google Chrome (Lasted) & Windows 10 Familial

My SFTP server is completly bug. When my clients want to read a files or drop a files / folder, it's doesnt work.

**LOG OF DAEMON**
`
20:10:22.965Z ERROR wings: An exception was encountered while handling the SFTP subsystem. (server=631ac225-12e3-4d23-bfa6-efb62365baac)
    exception: {
      "code": "ECONNRESET",
      "errno": "ECONNRESET",
      "syscall": "read"
    }
    --
    identifier: 0QVP1LK3xStF5gvxDWOr6AZsuR2Tv87043mSwX41R4wQAW1hy5Nixq0sCqlqvYNQ

20:19:10.705Z  WARN wings: Panel reported an invalid set of SFTP credentials or a malformed request. (responseCode=404, requestUrl=MY_URL_WEBSITE username=darklord.aa0a0dd8)

20:20:30.097Z ERROR wings: An exception was encountered while handling the SFTP subsystem. (server=631ac225-12e3-4d23-bfa6-efb62365baac)
    exception: {
      "code": "ECONNRESET",
      "errno": "ECONNRESET",
      "syscall": "read"
    }

`

**Comment by DaneEveritt** [comment]
ECONNRESET means the connection is being reset, thats not an issue caused by the software itself. In addition the credentials warning means there is no user with that username, belonging to that server that was found, or the password being provided is invalid (or, potentially, your URL is wrong).

**Comment by LeCanadienOP** [comment]
And do you know somes things i can do for correct it ?

**Comment by DaneEveritt** [comment]
Check your network setup and make sure you're using the correct credentials.
