### ISSUE TITLE
No serverstatus

### ISSUE THREAD

**Issue by SjakeCraft** [pterodactyl/panel#1043]
Hello Pterodactyl,

My servers on my panel doesn't have a server status and I can't start or stop them.
https://prnt.sc/ipbrcc On this picture it is online.
But when I click on it I can't do anything: http://prntscr.com/ipbrtk

* Panel or Daemon: http://panel.superhamster.nl
* Version of Panel/Daemon: 0.7.5
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Google Chrome

------------------------

**Comment by 14developing** [comment]
I can start them but i can't see the status: http://prntscr.com/ip0fj5

**Comment by SjakeCraft** [comment]
Added: Console also not working

**Comment by fabri2000779** [comment]
i imagine that tried clear your browser cache

**Comment by 14developing** [comment]
Ups, clearing cache fix it.

**Comment by SjakeCraft** [comment]
Thanks it worked!
