### ISSUE TITLE
Mail (SMTP, PHP) not working

### ISSUE THREAD

**Issue by Hysangaming** [pterodactyl/panel#1045]
I found that the mail function does NOT work, there is NO LOG when I typed the command, also things seem working fine, but the SMTP, PHP, MailGun is not working even I have entered the correct credentials. 

* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.6 panel, 0.5.5 daemon
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Chrome, Windows 10

------------------------

**Comment by Hysangaming** [comment]
Note that I have restarted pteroq

**Comment by DaneEveritt** [comment]
Are there any records in the `jobs` or `failed_jobs` tables in MySQL?

**Comment by Hysangaming** [comment]
Yes there is.
https://imgur.com/gallery/OCsuH

**Comment by DaneEveritt** [comment]
Can you check the exceptions column, and provide an actual text output, not a screenshot of a popup on a phone.

**Comment by Valiantiam** [comment]
also, what does your system log say? /var/log/system

regardign the service.
