### ISSUE TITLE
Trying to download files

### ISSUE THREAD

**Issue by Hysangaming** [pterodactyl/panel#1046]
When I am trying to download file from a server, it shows me 

> {
    "error": "An unhandled exception occured while attempting to process this request."
}

**Comment by DaneEveritt** [comment]
The giant wall of text that you ignored when making this issue is required, feel free to edit this issue and press the 'Re-Open' button below once you've added that required information.

**Comment by Hysangaming** [comment]
Reopen

**Comment by schrej** [comment]
Especially the logs are important. Also you are supposed to click the button, not comment reopen.
