### ISSUE TITLE
Minor stylesheet error with navbar title

### ISSUE THREAD

**Issue by TheTrueColonel** [pterodactyl/panel#1047]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.6
* Server's OS: Ubuntu 16.04 LTS
* Your Computer's OS & Browser: Windows 10 / Firefox

Minor stylesheet issue where "Pterodactyl" does not disappear like it should when minimizing the navbar. A good fix would be to instead of trying to hide it behind the top bar, to use `text-indent: -999999;`.

Image:
![image](https://user-images.githubusercontent.com/19292389/37254856-bf252a6c-2511-11e8-90de-ea48362793c0.png)

**Comment by stanjg** [comment]
Why are you not actually using the natively adminLTE support classes?

An example would be:
```html
<a href="{{ route('index') }}" class="logo">
    <span class="logo-lg">Pterodactyl</span>
    <span class="logo-mini"><!-- small logo --></span>
</a>
```

I think that would be a much better way to do this.
