### ISSUE TITLE
Trying to download files

### ISSUE THREAD

**Issue by Hysangaming** [pterodactyl/panel#1049]
When I am trying to download file from a server, it shows me 

> {
    "error": "An unhandled exception occured while attempting to process this request."
}

Panel: 0.7.5
Daemon: 0.5.5
Ubuntu 16.04 , MySQL, Nginx
I'm using Chrome

**Comment by DaneEveritt** [comment]
Please check your Daemon and Panel error logs.

**Comment by Hysangaming** [comment]
There is no panel error.

**Comment by DaneEveritt** [comment]
Then check the daemon error logs as I asked, thanks 👍

**Comment by Hysangaming** [comment]
https://hastebin.com/ucetorocup

**Comment by parkervcp** [comment]
That looks a lot like you have no logs.

**Comment by Hysangaming** [comment]
But it has error

**Comment by parkervcp** [comment]
I don't see any errors on that log you shared.

**Comment by lancepioch** [comment]
We need either the relevant error posted or a step by step in order to help reproduce and identify the issue. Otherwise we just will be unable to help.

**Comment by Hysangaming** [comment]
Tell me what I should do please

**Comment by DaneEveritt** [comment]
You should cause that error to happen again, and then check both the panel and daemon error logs to see whats going on, it should be logged in one of them.

**Comment by DaneEveritt** [comment]
Due to a lack of activity I am closing this issue. If you are able to provide accurate logs please comment on this issue and reopen _this_ issue, do not create a new one.
