### ISSUE TITLE
More restrictions on disk usage

### ISSUE THREAD

**Issue by vipesz** [pterodactyl/panel#1050]
* Panel or Daemon:  Daemon
* Version of Panel/Daemon: v0.5.x
* Server's OS: CentOS 7.4
* Your Computer's OS & Browser: Firefox Quantum 

Below are some features that may be useful in some deployments regarding disk usage and a few issues that arise currently.

# Disk Restrictions

- Restrict amount of files within the container 
[ Aids in chowning all files, alternative option is to verify if the permissions are correct on a server before just setting the permissions upon daemon boot. ] 
- Restrict I/O time before the server is killed
[ Prevents users from bogging down the daemon with I/O intensive plugins ] 
- Restricted file type
[ Restrict file types from being used/created, for an example, png files may not be recreated or limited to x amount and x size ] 
- Restricted file size (This can be done without a feature addition, but I would like to see it natively supported)
[ Restrict file size of large log files ]

**Comment by parkervcp** [comment]
First is near impossible to actually control as many games/servers have tons of small files for stupid reasons.  

Second is on the panel already as the blockIO weight. Default all users get a weight of 500 so they are evenly spread. (5 servers with 500 all get 1/n x servers io time)  

Restricting file type is difficult.  

File size will be part of the disk space issue already.

**Comment by rouing** [comment]
I wouldn't call the first impossible, maybe just not viable. You could count the files after install and then set a number "orignial file count" and then from there on, stop the addition of files after a specific number is reach.

**Comment by parkervcp** [comment]
I said it was nearly impossible. Also nowhere near feasible. It's a waste of resources to do the counts constantly. The disk usage check only gets run on server startup. I assume that counting files would be done the same way.

You should have monitoring up for all of these things. The panel offers "basic" monitoring. I don't think it should fall on the panel to manage this kind of thing.

**Comment by DaneEveritt** [comment]
I agree with @parkervcp here, the daemon already checks disk use on start, and every 30 seconds there out, and we've already seen that doesn't play nicely with large servers, especially not on HDD based systems. Trying to maintain counts of files and file-sizes is just going to result in more issues, and cause a lot of performance slowdowns.

Proper monitoring from a tool designed to do this, or the use of cgroup limits on disk usage per folder would be a better approach for these types of problems.
