### ISSUE TITLE
Teamspeak autorestart sometimes get stucked/fail to restart

### ISSUE THREAD

**Issue by xion87** [pterodactyl/panel#1052]
Panel or Daemon: Both?
Version of Panel/Daemon: 0.7.6/0.5.5
Server's OS: Ubuntu 16 LTS
Your Computer's OS & Browser: Chrome/Windows 10

I scheduled a daily restart on teamspeak server using "restart" at server power state
When it execute it, it don't restart the server (it stuck at restarting) and the panel trow this error on logs: https://hastebin.com/uyugaqolob.tex

**Comment by schrej** [comment]
It looks like your daemon is not running. Please check [this](https://guides.pterodactyl.io/docs/debugging-transferexception-and-socketio-issues), then you can ask on Discord for help.
If it is an actual bug feel free to reopen this issue.

**Comment by xion87** [comment]
the daemon is working fine and running, i can stop/restart the server using buttons, and teamspeak log work fine, but only the schedule part is not working for teamspeak

**Comment by DaneEveritt** [comment]
Please install `php-curl` as required in the documentation so we can get better error reporting happening, and also provide the daemon error logs.

**Comment by xion87** [comment]
Here there are the logs from daemon, the schedule was programed to restart teamspeak at hour 4.00 AM
https://hastebin.com/lonimayafa.json

Btw on panel i missed php7.2-gd and php7.2-curl, and moved on redis.

**Comment by xion87** [comment]
The issue seem to fixed for now by installing  these stuff

**Comment by xion87** [comment]
Problem is not fixed after 2 days of sucesfull restart i noticed today that teamspeak server was offline, on panel logs i got these:
https://hastebin.com/ukaperejob.tex
(same errors also 2 days ago but it restarted)
On daemon logs instead
https://hastebin.com/ulupuwedec.json

**Comment by DaneEveritt** [comment]
```
Operation timed out after 5001 milliseconds with 0 bytes received
```

That error is not caused by the software, it is indicative of a networking issue or an offline daemon at the time.
