### ISSUE TITLE
[Daemon] Error while connecting to SFTP with compression enabled

### ISSUE THREAD

**Issue by BrainStone** [pterodactyl/panel#1053]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.5.5
* Server's OS: Debian 9
* Your Computer's OS & SFTP Client: Windows 10 & Filezilla 3.31.0

------------------------

When I enable Compression in FileZilla for the SFTP connection the following error occurs and I cannot connect to the SFTP, unless I disable compression.

Log:

```
12:37:32.907Z FATAL wings: A fatal error occured during an operation. (err.code=Z_DATA_ERROR)
    Error: invalid distance too far back
        at Zlib._handle.onerror (zlib.js:371:17)
12:37:53.411Z FATAL wings: A fatal error occured during an operation.
    TypeError: Cannot read property 'server' of undefined
        at Client.client.on.on.on.err (/srv/daemon/src/http/sftp.js:496:30)
        at emitOne (events.js:96:13)
        at Client.emit (events.js:188:7)
        at SSH2Stream.<anonymous> (/srv/daemon/node_modules/ssh2/lib/server.js:311:10)
        at emitOne (events.js:101:20)
        at SSH2Stream.emit (events.js:188:7)
        at Socket.<anonymous> (/srv/daemon/node_modules/ssh2/lib/server.js:211:17)
        at emitOne (events.js:101:20)
        at Socket.emit (events.js:188:7)
        at emitErrorNT (net.js:1296:8)
```

(First error on first connection attempt, second error when FileZilla attempts to connect a second time)

`uname -a`: `Linux root.project-creative.de 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux`

`docker info`:

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.29GiB
Name: root.project-creative.de
ID: IL5K:73ZW:SX6A:ABLN:XJZZ:GUAF:V3IL:JTLN:CFJY:BPLF:BQ3O:X76A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by DaneEveritt** [comment]
Makes sense, don't think I ever designed it to work with compression enabled (nor did I ever test that, since most SFTP clients I've tested with don't even make that option visible).

**Comment by BrainStone** [comment]
Would be apprechiated if you implemented that. Or at least make sure it doesn't just error and refuse the connection.

**Comment by BrainStone** [comment]
Any updates?

**Comment by lancepioch** [comment]
This issue is not currently a priority for development, however we will accept any PR's for it.

If this issue is important to you, please have others thumbs up this issue so that it can move up in priority, thank you.

**Comment by DaneEveritt** [comment]
I'm unable to reproduce this, I have compression enabled and things are working fine on my end. Can you show me exactly what you have checked?

**Comment by ismail0234** [comment]
Any updates?

**Comment by DaneEveritt** [comment]
Looks like this might be solved by updating the SSH2 library:

https://github.com/mscdex/ssh2/wiki/Changes-from-0.4.x-to-0.5.x

**Comment by DaneEveritt** [comment]
Bumped versions more, guess we will see what happens.

https://github.com/pterodactyl/daemon/commit/fac93e17c0032120655e8c0c0997a68e1899e490
