### ISSUE TITLE
my panel is very slow

### ISSUE THREAD

**Issue by AlexLeGamer** [pterodactyl/panel#1056]
Panel or Daemon: Panel
Version of Panel/Daemon: Panel(v0.7.6) Daemon(v0.5.5)
Server's OS: Ubuntu Server 16.04 "Xenial Xerus" LTS
Your Computer's OS & Browser: Windows 10 64bit/Google Chrome

---------------------------------------

hi,
there is my problem my panel is very slow and sometimes it even doesn't load and when it doesn't load i get this error: 504 Gateway Time-out.
here is the link to my panel: http://panel.zone-network.ca/

------------------------------------------

Additional information
Php Version: PHP 7.2.3-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  6 2018 11:18:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies with Zend OPcache 
v7.2.3-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies.

Daemon: Linux ns517764 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux.
Docker info: Kernel Version: 4.4.0-72-generic.

**Comment by stanjg** [comment]
This happens for us too sometimes, it seems to happen on the admin side more often than the user side.

**Comment by parkervcp** [comment]
A gateway timeout error is not the panel being slow. It's a networking issue.

**Comment by AlexLeGamer** [comment]
yes i know. i just fixed the networking issue but i still get the problem that the panel is very slow

**Comment by schrej** [comment]
The gateway timeout can also happen when nginx isn't able to contact php-fpm. What are the specs of the servers you are running the panel on? Is there anything else running?

**Comment by AlexLeGamer** [comment]
Server Specs:
Intel i7-6700K
4c / 8t - 4GHz /4.2GHz
32GB DDR4 2133 MHz
SoftRaid 2x480Go SSD
250 Mbps bandwidth
other things running on the server:
teamspeak3 server

**Comment by DaneEveritt** [comment]
This is not a software issue unless you can provide Panel specific error logs demonstrating such either from the panel, fpm, or MySQL. Until there is data backing this, you're simply stating a broad problem that can be cause by a huge number of (most likely) non-panel-specific factors.

If you are able to provide logs showing that this slowness is indeed the result of poor code in the Panel, please feel free to reopen _this_ issue and provide those logs.

**Comment by parkervcp** [comment]
@schrej the php-fpm error is regularly a 502 not a 504 error.

**Comment by AlexLeGamer** [comment]
where can i find this logs

**Comment by xion87** [comment]
I having the same issue, but it only happen the first-two times when i load my server list, and after i click it it trow 504 error, i dont' have this issue on other pages

**Comment by lancepioch** [comment]
@xion87 Interesting, it looks like we use Cloudflare's CDN for a couple of the resources. I'm going to see if we can replace that with local copies. Thanks.

For any other issues, please create a new one, thanks.
