### ISSUE TITLE
Ark server don't start

### ISSUE THREAD

**Issue by SjakeCraft** [pterodactyl/panel#1057]
Hi,

I've installed an ARK server on Pterodactyl. The installation took 2 days and the server don't want to start: http://prntscr.com/ir2i0r

* Panel or Daemon: Daemon
* Version of Panel/Daemon: Newest
* Server's OS: Ubuntu 14.4
* Your Computer's OS & Browser: Chrome

------------------------

**Comment by parkervcp** [comment]
@SjakeCraft Can you giver actual logs here? This screenshot is basically useless.

**Comment by SjakeCraft** [comment]
I have this: https://hastebin.com/lacekuxuka
And this: 

12:56:17.828Z  INFO wings: Checking if we need to update image quay.io/pterodact                                                                                                                               yl/core:source, if so it will happen now.
12:56:49.597Z  INFO wings: Pulling image quay.io/pterodactyl/core:source ... thi                                                                                                                               s could take a few minutes.
12:56:49.714Z  INFO wings: Completed rebuild process for server container. (serv                                                                                                                               er=64025d75-093d-45d3-98ed-5f93a3a5aa15)
12:56:49.714Z  INFO wings: Server status has been changed to OFF (server=64025d7                                                                                                                               5-093d-45d3-98ed-5f93a3a5aa15)
12:56:49.715Z  INFO wings: Server status has been changed to STARTING (server=64                                                                                                                               025d75-093d-45d3-98ed-5f93a3a5aa15)
12:56:51.188Z  INFO wings: Server status has been changed to OFF (server=64025d7                                                                                                                               5-093d-45d3-98ed-5f93a3a5aa15)
12:56:51.188Z  WARN wings: Server detected as crashed! Attempting server reboot.                                                                                                                                (server=64025d75-093d-45d3-98ed-5f93a3a5aa15, ExitCode=127, OOMKilled=false, Er                                                                                                                               ror="")
12:56:51.188Z  INFO wings: Server status has been changed to STARTING (server=64                                                                                                                               025d75-093d-45d3-98ed-5f93a3a5aa15)
12:56:54.270Z  INFO wings: Server status has been changed to STOPPING (server=64                                                                                                                               025d75-093d-45d3-98ed-5f93a3a5aa15)
12:56:54.271Z  INFO wings: Server status has been changed to OFF (server=64025d7                                                                                                                               5-093d-45d3-98ed-5f93a3a5aa15)

**Comment by SjakeCraft** [comment]
I don't know other log commands

**Comment by DaneEveritt** [comment]
Code 127 means the process is exiting as "command not found", which leads me to believe you do not have the correct startup arguments for the process. There is nothing in the log provided indicating there is a bug with this software.
