### ISSUE TITLE
Creation of user error (php artisan pterodactyl:user)

### ISSUE THREAD

**Issue by SwiftyPlaysMC** [pterodactyl/panel#1059]
When i try to go through the process of creating an admin account for pterodactyl i get to the end of the account creation and i get the error:

In UserRepository.php line 52:
 Undefined class constant 'USERNAME_RULES'

* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.6.4
* Server's OS: Redhat 7
* Your Computer's OS & Browser: Windows 10/Chrome

------------------------

**Comment by DaneEveritt** [comment]
In the future please post the actual error, and not your take on the error, it helps.

However, I know that this is caused by not running PHP 7.2 on your webserver, and no the output of `php -v` showing 7.2 does not mean your webserver is using it. :)
