### ISSUE TITLE
i alter the httpd's port ,but when i start dream

### ISSUE THREAD

**Issue by WintopPVP** [pterodactyl/panel#1063]
i alter the httpd's port ,but when i start dream
07:13:30.680Z FATAL wings: A fatal error caused the daemon to abort the startup. (err.code=ECONNREFUSED)
    Error: connect ECONNREFUSED 103.91.208.35:80
        at Object.exports._errnoException (util.js:1020:11)
        at exports._exceptionWithHostPort (util.js:1043:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1105:14)
    --
    additional: {
      "code": "ECONNREFUSED",
      "errno": "ECONNREFUSED",
      "syscall": "connect",
      "address": "103.91.208.35",
      "port": 80
    }
07:13:30.680Z FATAL wings: + ------------------------------------ +
07:13:30.680Z FATAL wings: |  Docker is not running!              |
07:13:30.681Z FATAL wings: |                                      |
07:13:30.681Z FATAL wings: |  Unable to locate a suitable socket  |
07:13:30.681Z FATAL wings: |  at path specified in configuration. |
07:13:30.681Z FATAL wings: + ------------------------------------ +
07:13:30.681Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.
how to sovle it
thank you very much。

* Panel or Daemon: 
* Version of Panel/Daemon:7.6/5.6 
* Server's OS: centos7.4
* Your Computer's OS & Browser:win10 

------------------------

**Comment by parkervcp** [comment]
It says pretty clearly that docker isn't running. Also the daemon shouldn't run port 80.

**Comment by WintopPVP** [comment]
I kown ,but how to sovle this problem

**Comment by parkervcp** [comment]
@WintopPVP  did you start docker?

**Comment by DaneEveritt** [comment]
This is not an issue with this software, it is an issue with your configuration of it. Please use our Discord server for further assistance.

This issue tracker is for feature requests and bug reports only.
