### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by SjakeCraft** [pterodactyl/panel#1068]
Hi,
My servers don't  have a status in the serverlist and I can't change settings or get in the file manager.
http://prntscr.com/isrdi9
http://prntscr.com/isrdd7
The server logs are normal of docker and wings.

* Panel or Daemon: I don't know
* Version of Panel/Daemon: Newest
* Server's OS: Ubuntu 14.4
* Your Computer's OS & Browser: Chrome

**Comment by SjakeCraft** [comment]
When I turned off the ssl connection it worked again. But I want to use it with ssl.

**Comment by parkervcp** [comment]
It looks like you didn't set the daemon to use ssl.

**Comment by parkervcp** [comment]
@SjakeCraft This is more suited for Discord for support and I will be closing the issue.
