### ISSUE TITLE
Translations don't seem to work at all

### ISSUE THREAD

**Issue by KewaiiGamer** [pterodactyl/panel#1070]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.5
* Server's OS: Ubuntu 14.04
* Your Computer's OS & Browser: Windows 10 & Google Chrome

Whenever I try to change the user language the language never seems to change in the front end. It does update on the DB
PHP Version is  7.2.3-1+ubuntu14.04.1+deb.sury.org+1

**Comment by DaneEveritt** [comment]
What language are you trying to change it to?

**Comment by DaneEveritt** [comment]
I am unable to reproduce this issue.
