### ISSUE TITLE
Empty error in crash console

### ISSUE THREAD

**Issue by Doc94** [pterodactyl/panel#1071]
* Panel or Daemon: 0.5.5
* Version of Panel/Daemon: 0.7.6
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 Firefox

------------------------

In any cases the console not show a correctly reason for crash, (in this case the error is a missing permission of run into a shell file of server.

![imagen](https://user-images.githubusercontent.com/3602279/37573377-fb9b4b0e-2af5-11e8-9582-7b705d39322a.png)

**Comment by parkervcp** [comment]
@Doc94 You want to tell us what service this is that crashed here? It's an error for that server specifically.

**Comment by Doc94** [comment]
Minecraft->Bungeecord
But in my case i use a .sh in Bungeecord service for upgrade server.jar and upgrade plugins. in my mistake i remove perms into .sh but the console not advise about error in permissions (in previous versions show a message for access denied in this cases), i dont know if this its a issue o suggest for more detail in errors.

**Comment by parkervcp** [comment]
This sound s a whole lot like "not the panels" issue and you need to figure out what exit code 126 is on bungeecord.

**Comment by parkervcp** [comment]
A quick look with google though shows code 126 to be "Command invoked cannot execute" which is a bad in your .sh

**Comment by DaneEveritt** [comment]
The crash is unrelated to the software, but I think we need to figure out what we can do to make those errors show up in the console. Its clearly crashing for a reason, why it isn't showing up though is a problem.

**Comment by Doc94** [comment]
@parkervcp i thinks this code error are internal of PT me mistake.
This issue is only for require more details (not only the code) because in this case the error message not exits.

**Comment by parkervcp** [comment]
@Doc94 You will need to share your shell script to have us look into this more. You changed the startup command and permissions on files. The error code is a standard error code.

**Comment by JustTijn** [comment]
@Doc94 Did you set the file permissions correctly?
