### ISSUE TITLE
my garry's mod server is not working and because of that my panel is very slow

### ISSUE THREAD

**Issue by AlexLeGamer** [pterodactyl/panel#1072]
Panel or Daemon: Panel and Daemon
Version of Panel/Daemon: Panel(v0.7.6) Daemon(v0.5.5)
Server's OS: Ubuntu Server 16.04 "Xenial Xerus" LTS
Your Computer's OS & Browser: Windows 10(64bit) Google Chrome
-------------------------------------------------------------------------------------------------------------------
Hi,
I just installed the panel on my server and everything was working properly before I decided to install a garry's mod server and then I started having a lot of problems with the slowdown of the whole panel and I also had this error with the server garry's mod (http://prntscr.com/itfbfo)

**Comment by parkervcp** [comment]
This appears to be a bad daemon connection and not the gmod server itself. Unless the gmod server is causing issues on the daemon. I don't see how that could happen though.

**Comment by schrej** [comment]
Even though I know the French really do like their language there still won't be many helping you if you don't write in english. It's pretty obvious that this whole repository is in english and writing in french is rather ignorant. Also this is more of a support request and probably caused due to mistakes while installing. If that's not the case feel free to reopen this.
For help visit our [discord server](https://pterodactyl.io/discord), that's english only as well though.

**Comment by AlexLeGamer** [comment]
sorry for this it was a missclick i was using google traduction for another forum and i just copy paste the same post but i can't reopen this thread can you do it for me please

**Comment by DoNotSpamPls** [comment]
The `this error` image just shows that there was an error, but it doesn't show us what it is. Without the console output and/or panel/daemon logs we can't really help.

**Comment by AlexLeGamer** [comment]
this probleme was fix theres the fix.
execute those command:
service php-fpm restart
service nginx restart
service mysql restart
service redis restart
----------------------------------------------------------------------------------------------
switch move the /srv/daemon-data folder to /home
thanks to pterodactyl support team for helping me out with this issues

**Comment by schrej** [comment]
Just to clarify: In this case the hard drive was full, `/home` was on another drive with free space available.

**Comment by AlexLeGamer** [comment]
yes
