### ISSUE TITLE
Allow ability to disallow user allocations and databases

### ISSUE THREAD

**Issue by xyeLz** [pterodactyl/panel#1073]
With every other feature there's a way to "disable" a setting, but in this case setting it to 0 supposedly sets it to unlimited. Please change this to the way swap is configured:

"If you do not want to assign swap space to a server simply put 0 for the value, or -1 to allow unlimited swap space."

**Comment by DaneEveritt** [comment]
`0` is `0`, blank is unlimited.

**Comment by lancepioch** [comment]
While this is an easy change, unfortunately this would switch everybody's options from unlimited to none and vice-versa.
