### ISSUE TITLE
Getting some issues after upgrade from 4.x/6.x

### ISSUE THREAD

**Issue by fabri2000779** [pterodactyl/panel#1074]
* Panel or Daemon: both
* Version of Panel/Daemon: 7.6/5.5
* Server's OS: Ubuntu 16.04 Xenial
* Your Computer's OS & Browser:  Win 10 and Google Chrome

I was trying to reproduce this issue but i couldnt, also i need to clarify that this issue is happening on our production enviroment after a upgrade from 4. x/6.x to 5.x/7.x all works perfect except one thing, when we try to re-install a server it get stuck on installing mode and the only way to switch the status is toggle the install status. our Daemons logs are normal any unsual thing or error, our installation logs from x servers are good i tested the eggs on our development enviroment and it works without issues and before you ask yeah i checked the install.logs anyway and the installation script runs perfect.

im getting a panel log outage:
Issue one:
Server error: `PUT https://eu4.skynode.pro:8080/v1/server/power` resulted in a `503 Service Unavailable` response:
{
    "error": "An unhandled exception occured while attempting to process this request."
}
 in /var/www/html/pterodactyl/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

Issue 2:
Client error: `POST https://eu1.skynode.pro:8080/v1/server/command` resulted in a `412 Precondition Failed` response:
{
    "error": "Server is not running."
}
 in /var/www/html/pterodactyl/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

Issue 3:
[2018-03-21 01:00:06] production.ERROR: Pterodactyl\Exceptions\Repository\Daemon\InvalidPowerSignalException: The signal "Restart" is not defined and could not be processed. in /var/www/html/pterodactyl/app/Repositories/Daemon/PowerRepository.php:32

Issue 4:
 Client error: `PUT https://eu3.skynode.pro:8080/v1/server/power` resulted in a `404 Not Found` response:
{
    "error": "Unable to locate the requested server for that token."
}
 in /var/www/html/pterodactyl/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

All those issue are constantly spaming our panel logs, i tried copying the panel files from our development enviroment and replace them changing the .env and nothing same thing. This is happening with all our daemons and all eggs.

Looking some old issues i could find something kinda simillar but i dont know if this could help https://github.com/Pterodactyl/Panel/issues/888 our issues isnt with file manager it is when we try to re-install a server getting stuck on "installing"

**Comment by vipesz** [comment]
None of these issues came up in our deployment, at least in the way yours did. It may be strongly related with Docker, so provide your docker logs as well and the logs from the specific containers if you can.

## Issue 1:

`Server error: PUT https://eu4.skynode.pro:8080/v1/server/power resulted in a 503 Service Unavailable response:`
{
"error": "An unhandled exception occured while attempting to process this request."
}
in /var/www/html/pterodactyl/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

I've found that these servers still get booted. I haven't looked into specifics but in my experience, they can be ignored. This may also be related to the container.

## Issue 3:

[2018-03-21 01:00:06] production.ERROR: Pterodactyl\Exceptions\Repository\Daemon\InvalidPowerSignalException: The signal "Restart" is not defined and could not be processed. in /var/www/html/pterodactyl/app/Repositories/Daemon/PowerRepository.php:32

That sounds like you didn't migrate correctly or you've done some modifications, this has never been an issue for us. It may also be related to the container.

## Issue 4:
Client error: PUT https://eu3.skynode.pro:8080/v1/server/power resulted in a 404 Not Found response:
{
"error": "Unable to locate the requested server for that token."
}
in /var/www/html/pterodactyl/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

The server has been removed and it doesn't exist. This does not mean the server may not exist on the panel, it could be connected to the container itself. There's not much context to this, so if you provide more they can help you.

## Regarding the 404 error, as mentioned in #888 

Again, this has never been an issue for us, but this could be related to the docker container not existing which may be connected to issue 4.

**Comment by fabri2000779** [comment]
i dont think this is a issue of docker honestly, let me explain myself. One of the nodes was re-installer that means fresh OS and i installed all following the Daemons docs the only what i need is replace the config folder with the correct one, so Why will be docker if we did a fresh install on one of our nodes and we have the same issue of all the nodes.

Also it is courius because when the server is created it install without issue but when you re-install it get stuck, so the first install works. i already checked the docker logs nothing unusual.

wings log:
":"Blocking server boot until option installation process is completed.","time":"2018-03-21T12:36:11.783Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":30,"msg":"Writing output of installation process to file. { file: '/srv/daemon/config/servers/6283882d-23e6-4fc1-b4df-1b04d16ac519/install.log' }","time":"2018-03-21T12:36:11.909Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"level":30,"msg":"Pulling image alpine:3.4 ... this could take a few minutes.","time":"2018-03-21T12:36:12.947Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":30,"msg":"Temporarily suspending server to avoid mishaps...","time":"2018-03-21T12:36:14.338Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":40,"msg":"Server has been suspended.","time":"2018-03-21T12:36:14.342Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":30,"msg":"Completed installation process for server.","time":"2018-03-21T12:36:19.086Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":30,"msg":"Server booting is now UNBLOCKED.","time":"2018-03-21T12:36:19.098Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":30,"msg":"Server has been unsuspended.","time":"2018-03-21T12:36:19.105Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"level":30,"msg":"Notified remote panel of server install status.","time":"2018-03-21T12:36:19.160Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":40,"msg":"Server booting is now BLOCKED.","time":"2018-03-21T12:45:37.339Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":30,"msg":"Blocking server boot until option installation process is completed.","time":"2018-03-21T12:45:37.339Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":30,"msg":"Writing output of installation process to file. { file: '/srv/daemon/config/servers/6283882d-23e6-4fc1-b4df-1b04d16ac519/install.log' }","time":"2018-03-21T12:45:37.442Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"level":30,"msg":"Pulling image alpine:3.4 ... this could take a few minutes.","time":"2018-03-21T12:45:38.512Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":30,"msg":"Temporarily suspending server to avoid mishaps...","time":"2018-03-21T12:45:38.906Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":40,"msg":"Server has been suspended.","time":"2018-03-21T12:45:38.910Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":30,"msg":"Completed installation process for server.","time":"2018-03-21T12:45:43.684Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":30,"msg":"Server booting is now UNBLOCKED.","time":"2018-03-21T12:45:43.689Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"server":"6283882d-23e6-4fc1-b4df-1b04d16ac519","level":30,"msg":"Server has been unsuspended.","time":"2018-03-21T12:45:43.692Z","v":0}
{"name":"wings","hostname":"BGT-EU04","pid":7053,"level":30,"msg":"Notified remote panel of server install status.","time":"2018-03-21T12:45:43.779Z","v":0}

request log:
{"name":"restify.logger","hostname":"BGT-EU04","pid":7053,"audit":true,"level":30,"remoteAddress":"54.36.188.233","remotePort":43760,"req_id":"7d6004be-8086-4d96-9a71-88aa9acb41c2","req":{"query":"","method":"GET","url":"/v1/server","headers":{"host":"eu4.skynode.pro:8080","x-access-server":"ef2720f1-e00c-4682-b2d0-536bdf1ebaea","x-access-token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","user-agent":"GuzzleHttp/6.2.1 curl/7.47.0 PHP/7.2.3-1+ubuntu16.04.1+deb.sury.org+1","X-Access-Server":"ef2720f1-e00c-4682-b2d0-536bdf1ebaea","X-Access-Token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},"httpVersion":"1.1","trailers":{},"version":"*","timers":{"handler-0":4,"readBody":8,"parseJson":0,"restifyCORSSimple":5,"handler-1":8,"handler-2":117}},"res":{"statusCode":200,"headers":{"content-type":"application/json"},"trailer":false},"latency":1,"_audit":true,"msg":"handled: 200","time":"2018-03-21T12:59:44.530Z","v":0}
{"name":"restify.logger","hostname":"BGT-EU04","pid":7053,"audit":true,"level":30,"remoteAddress":"54.36.188.233","remotePort":43832,"req_id":"15f19220-924c-445a-8eb2-8c83d7de2044","req":{"query":"","method":"GET","url":"/v1/server","headers":{"host":"eu4.skynode.pro:8080","x-access-server":"e37e5d2f-bff2-45bb-8a0b-34ae55725273","x-access-token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","user-agent":"GuzzleHttp/6.2.1 curl/7.47.0 PHP/7.2.3-1+ubuntu16.04.1+deb.sury.org+1","X-Access-Server":"e37e5d2f-bff2-45bb-8a0b-34ae55725273","X-Access-Token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},"httpVersion":"1.1","trailers":{},"version":"*","timers":{"handler-0":9,"readBody":21,"parseJson":1,"restifyCORSSimple":3,"handler-1":14,"handler-2":227}},"res":{"statusCode":200,"headers":{"content-type":"application/json"},"trailer":false},"latency":1,"_audit":true,"msg":"handled: 200","time":"2018-03-21T12:59:55.511Z","v":0}
{"name":"restify.logger","hostname":"BGT-EU04","pid":7053,"audit":true,"level":30,"remoteAddress":"54.36.188.233","remotePort":43840,"req_id":"a3b84084-06a5-4efd-96f4-6b9df9caf716","req":{"query":"","method":"GET","url":"/v1/server","headers":{"host":"eu4.skynode.pro:8080","x-access-server":"ef2720f1-e00c-4682-b2d0-536bdf1ebaea","x-access-token":"xxxxxxxxxxxxxxxxxxxxxxxxxxx","user-agent":"GuzzleHttp/6.2.1 curl/7.47.0 PHP/7.2.3-1+ubuntu16.04.1+deb.sury.org+1","X-Access-Server":"ef2720f1-e00c-4682-b2d0-536bdf1ebaea","X-Access-Token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},"httpVersion":"1.1","trailers":{},"version":"*","timers":{"handler-0":6,"readBody":10,"parseJson":1,"restifyCORSSimple":7,"handler-1":8,"handler-2":143}},"res":{"statusCode":200,"headers":{"content-type":"application/json"},"trailer":false},"latency":1,"_audit":true,"msg":"handled: 200","time":"2018-03-21T12:59:55.518Z","v":0}

**Comment by parkervcp** [comment]
You know the site have a really nice plate to post logs. like the gist site. Or even pastebin/hastebin is a good one.

**Comment by parkervcp** [comment]
Also this log looks normal.
A 503 is an "unavailable" response. Something is responding with that code. I am not saying it's the daemon but anything you have in front of it may be causing that.

**Comment by fabri2000779** [comment]
@DaneEveritt will sound kinda stupid, but do you remember that this look related with a kind of url redirection, well you where right. We use cloudflare and cloudflare has a option to force to redirect all the http trffic to https, i disable that and that resolve the issue. Sorry for the troubles

**Comment by DaneEveritt** [comment]
The install status should be hitting https:// if you have everything setup correctly.
