### ISSUE TITLE
Database Options

### ISSUE THREAD

**Issue by BrightSkyz** [pterodactyl/panel#1076]
I would like to see an option that is set globally (and then per server) that allows users to have multiple databases per server. What I mean is in the admin panel, you can choose an option to set this as default for all new servers (and a button to change this on all servers that currently have the default). What this allows, it basically you can change the amount of databases you can have per server. If this is confusing, look at my "diagram" of this idea below (it sometimes makes more sense to me with diagrams).

```
panel -> login -> general settings -> database allocation settings -> this:
----
[ Input: enter a maximum number of databases allowed per server (-1 for unlimited) ]
< Button: opt 1 > or < Button: opt 2 >
----
opt 1 -> change default for all new servers will change the default for all servers that will be created (you can still override this default during creation (in panel or api) + in server settings once server us created)
opt 2 -> change default and update all servers that have the default currently (this will change the default like the first button, but will change the number on all of the servers that have the default db amount)
```

I know this idea is probable stupid, but leaving a 👍 on this really helps and leaving feedback does too.

**Comment by DaneEveritt** [comment]
This should be handled through whatever software you're using to create servers. Entering a number when making the server isn't that many more steps. I don't plan on implementing this function.
