### ISSUE TITLE
du -hsb causing massive server IO lag

### ISSUE THREAD

**Issue by vipesz** [pterodactyl/panel#1078]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v0.5.x
* Server's OS: CentOS 7.4
* Your Computer's OS & Browser: N/A

------------------------

## Load Average (Post fix)

![image](https://user-images.githubusercontent.com/16901910/37744019-619acf48-2d43-11e8-9a8f-44c2d37831ee.png)

## Alternative Approach

I am aware that this can be configured, however there should be an alternative approach to monitor the status of the du command rather then giving it a predetermined amount of time and spawning a new process to bog down a node. 

The daemon has used upwards of 3 gigs of ram and has caused the load average to spike very high as indicated above. For now, this has been configured accordingly.

**Comment by Espantonius** [comment]
I have the same problem. Having servers with millions of files collapses the machines.

Could it be modified so that it does not check on a node?

The code mentioned is here: https://github.com/pterodactyl/daemon/blob/develop/src/controllers/fs.js#L76

We hope some solution.

**Comment by Espantonius** [comment]
[Update]

I have modified the code so that it does not check the size of the folder. Sure it's not a good solution but not collapsing servers. I have changed it like this:
```
    size(next) {
        return next(null, 0);
    }
```

Until there is no other solution I will have to keep it that way.

**Comment by DaneEveritt** [comment]
Closing this as we do not use this method in the new daemon to calculate storage usage.
