### ISSUE TITLE
Error Deploying Server

### ISSUE THREAD

**Issue by wraith1200** [pterodactyl/panel#1081]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.6
* Server's OS: Ubuntu 16.04 LTS
* Your Computer's OS & Browser: Windows 10, Chrome

------------------------
When deploying a custom egg (Parkers FTB egg specifically) the panel errors to the "Whoops. looks like something went wrong " screen. When looking at the error logs for the panel it is adding a +somewhere in the regex parsing. Log link below.

[https://bin.ptdl.co/1yvru/](url)

**Comment by parkervcp** [comment]
I will confirm I have duplicated this issue. I am looking into what is is specifically causing it.

**Comment by parkervcp** [comment]
I looks like it boils down to the way laravel handles regex apparently. I am looking into it.

**Comment by DaneEveritt** [comment]
This isn't a panel bug in that case, but the regex for handling that variable appears to be using the `+` incorrectly.
