### ISSUE TITLE
Oh dear

### ISSUE THREAD

**Issue by DeveloperBoy** [pterodactyl/panel#1082]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v7
* Server's OS: Centos 7
* Your Computer's OS & Browser: Windows - Firefox

> PHP 7.2.3 (cli) (built: Mar  1 2018 14:56:34) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies

> Linux 32gb-pterodactyl-node1 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

> Containers: 2
>  Running: 1
>  Paused: 0
>  Stopped: 1
> Images: 3
> Server Version: 18.03.0-ce
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
> runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
> init version: 949e6fa
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 3.10.0-693.21.1.el7.x86_64
> Operating System: CentOS Linux 7 (Core)
> OSType: linux
> Architecture: x86_64
> CPUs: 8
> Total Memory: 30.52GiB
> Name: 32gb-pterodactyl-node1
> ID: J3SL:6A3A:6ZGQ:HOQC:M2J2:OACY:TQP7:GRVH:RK6U:XMTH:4Z6F:CU7E
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

I got this error: "[Pterodactyl Daemon] Oh dear, it seems something has gone horribly wrong while attempting to boot this server. Please contact your administrator for assistance. PTDL:ERR_ID:LPbpEv4t0LaOeW1EDCco"

I've setted up a Minecraft Vanilla server. When I startup the server, it gives that error.

How to fix it?

**Comment by DeveloperBoy** [comment]
I've changed it to spigot. Then I got this:

[Pterodactyl Daemon] Oh dear, it seems something has gone horribly wrong while attempting to boot this server. Please contact your administrator for assistance. PTDL:ERR_ID:AssyW9mJ80KMZSJ99cMM
[Pterodactyl Daemon] An error was encountered while attempting to rebuild this container. Please contact your administrator for assistance. PTDL:ERR_ID:kljBYjlCNp89EJl9Efyn

**Comment by parkervcp** [comment]
Have you tried disabling selinux with `setenforce 0`?

**Comment by DeveloperBoy** [comment]
I'm going to close this issue, because I'm going to try it with Ubuntu 16.04
