### ISSUE TITLE
Install plugins from panel

### ISSUE THREAD

**Issue by Legoman99573** [pterodactyl/panel#1083]
I was making this request of a feature that was in multicraft where you could install bukkit plugins, but I was gonna ask the same thing for pterodactyl since it has been a big discussion in pebble that the feature is missing and half of them crying wanting to switch panels because of the missing feature.

This would pull from spigot and bukkit and allow which version of the plugin you wanted to install ofc (wouldn't work for premium and shouldn't) and be installed to the servers plugins folder. Not sure if it will be hard to implement or not, but decided to put this feature request here.

**Comment by stanjg** [comment]
Features like this have been denied before. They want to keep this panel generalised for all games.

**Comment by parkervcp** [comment]
You could of course add your own mod chooser.

The panel is very generic for the support it has. It supports more than just Minecraft and we avoid adding game specific features.

**Comment by Legoman99573** [comment]
If there was a mod to allow it, then that would work out, but its not me you have to convince why its not going to be added.

If the feature is going to get denied, ill close the issue.

**Comment by parkervcp** [comment]
I never said it wasn't going to happen. You could also make a custom egg that will install whatever you want.

**Comment by Legoman99573** [comment]
@parkervcp Thanks. I will let people who use the host know there is a way to do so.

**Comment by parkervcp** [comment]
Yeah that is too specific for the panel. I have raised a new issue for a more generic mod manager in #1084 

It's a bit more intensive on the service manager but that is how I think it should be managed.
