### ISSUE TITLE
TF2 Daemon problem

### ISSUE THREAD

**Issue by gool1299** [pterodactyl/panel#1086]
* Panel or Daemon:  Daemon
* Version of Panel/Daemon:  0.7.6/0.5.5
* Server's OS:  Ubuntu 16
------------------------

Hi i can't start server to TF2

My error log is:

 > :/home/container$ ./srcds_run -game tf -console -port 27005 +map cp_dustbowl +ip 0.0.0.0 strictportbind -norestart
/entrypoint.sh: line 17: ./srcds_run: No such file or directory
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 127
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Aborting automatic reboot due to crash within the last 60 seconds.

I don't know why server files don't install. 

SS from File manager:

https://i.imgur.com/MQtP65Y.png

SS from Admin Panel:

https://i.imgur.com/jZFc3gm.png

**Comment by DaneEveritt** [comment]
`srcds_run: No such file or directory` I'm guessing you provided incorrect installation details when creating the server, but this ins't really an issue with this software since I know it works fine for tons of other people. Check on Discord for more 1-1 support please.
