### ISSUE TITLE
Preflight has no catch, Unhandled Promise Rejection causing hang

### ISSUE THREAD

**Issue by nurdism** [pterodactyl/panel#1087]
* Panel or Daemon: Daemon
* Version of Panel/Daemon:  0.5.5
* Server's OS: Ubuntu 16.01
* Your Computer's OS & Browser:  Chrome
------------------------
I found out with some digging if you have any errors during the preflight of the server, it would hang and nothing would happen. There should be a preflight catch and notify that something went wrong. 

The problem I was running into was I was using 2 environment prams in one of my services **Configuration Files**, if you have more than one and *don't* put spaces in between I.E. 
`{{server.build.default.ip}}:{{server.build.default.port}}`
vs 
`{{ server.build.default.ip }}:{{ server.build.default.port }}` 

`{{server.build.default.ip}}:{{server.build.default.port}}` would throw an *UnhandledPromiseRejectionWarning* and get stuck in preflight.

I'd recommend a note on that aswell in the panel itself, [this](https://github.com/pterodactyl/daemon/blob/develop/src/helpers/fileparser.js#L44) [regex](https://regex101.com/r/E8cZDn/2) will only match a second `{{var}}` if padded by a space. If I hadnt done some digging, I would of never known that I had to pad with spaces.

**Comment by DaneEveritt** [comment]
Thanks for that find, pretty sure I never would have noticed that either.

**Comment by DaneEveritt** [comment]
Using `{{\s?([\w\.-]+)\s?}}` as the regex seems to fix that problem (and makes way more sense anyways).

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/daemon/commit/5f4dd9ac94ebb8bc7057b462c4aa93710fb7aa91
