### ISSUE TITLE
Whoops, looks like something went wrong

### ISSUE THREAD

**Issue by BeauvR** [pterodactyl/panel#1088]
If i make a user, add a server or some other thing i get [this page](https://gyazo.com/a187d60f48b6f9969c945929522b12ac). [Logs are here ](https://hastebin.com/udoleyalen.tex). Is there any solution for this? If you need more information ask me and i send it. Also if i go to admin/packs on my panel page.

**Comment by DaneEveritt** [comment]
You need PHP 7.2

**Comment by BeauvR** [comment]
[daemon logs console](https://hastebin.com/ecewoziyim.coffeescript)
[daemon logs file](https://hastebin.com/oqakevibir.pl)
In the attachments other logs
[Archief.zip](https://github.com/pterodactyl/panel/files/1850562/Archief.zip)

**Comment by BeauvR** [comment]
@DaneEveritt php version are: PHP 7.2.3-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  6 2018 11:18:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by BeauvR** [comment]
Is that the good php version?

**Comment by DaneEveritt** [comment]
```
[2018-03-26 20:09:51] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/pterodactyl/app/Rules/Username.php:12
```

The CLI version of PHP and the webserver version are not the same thing.

**Comment by parkervcp** [comment]
Check your installed php versions with the following commands.
Ubuntu/Debian
`apt list --installed | grep php`
CentOS
`yum list installed | grep php`

**Comment by BeauvR** [comment]
i have reinstalled everything and it works thanks! But i have a new error and i post it also on this github
