### ISSUE TITLE
There was an exception while attempting to communicate with the daemon resulting in a HTTP/E_CONN_REFUSED response code. This exception has been logged.

### ISSUE THREAD

**Issue by BeauvR** [pterodactyl/panel#1091]
https://gyazo.com/39641592f30c608f7ed283d224378344
This error get i on the panel.
The debug log are:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/root/package.json'
6 verbose cwd /root
7 verbose Linux 4.4.0-116-generic
8 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
9 verbose node v8.10.0
10 verbose npm  v5.6.0
11 error path /root/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/root/package.json'
16 error enoent This is related to npm not being able to find a file.
17 verbose exit [ -2, true ]

If i start the deamon i get [this](https://hastebin.com/pexilayise.cs)

I have update thecore.json with the configruation on the site: https://beauvr.nl/admin/nodes/view/1/configuration

If you need more files say it to me

**Comment by BeauvR** [comment]
everything works bot after a reboot not

**Comment by BeauvR** [comment]
Why you closed my issue? After the reboot not. So after i rebooting my server nothing work/startup.

**Comment by DaneEveritt** [comment]
This isn't a bug, look at the directory you're in.

**Comment by BeauvR** [comment]
I was in the good directory and If i start the deamon i get [this](https://hastebin.com/pexilayise.cs)

**Comment by DaneEveritt** [comment]
This is not an issue to be resolved on Github, please use our Discord server for further assistance.

**Comment by BeauvR** [comment]
I have already send a message to help me on the discord but I don’t get answer so I tried to do it here.

**Comment by StrayCargo** [comment]
@BeauvR your not alone I also I'm having this issue and have gotten the same treatment/responses you did on the issue
