### ISSUE TITLE
User Creation - Password Setup difficult & Email sending failure

### ISSUE THREAD

**Issue by MacksTGN** [pterodactyl/panel#1093]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.6 & 0.5.5
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 Chrome 

After you make a user and it sends the email the link in the email doesn't work it comes back with invalid token. so the user has to go back to the main login page and do reset pw which is rather difficult.

Also when setting up email with smtp the mail server works for a little bit then will just stop working and you will have to go into the mail server config and redo the config and it will start working then stop working.

**Comment by DaneEveritt** [comment]
Not gonna lie, totally noticed the link issue and just assumed my dev environment was messed up. 😭

**Comment by MacksTGN** [comment]
Lmao

**Comment by WeatherSquad** [comment]
Any news on how to fix this issue

**Comment by mayed505** [comment]
Any new news about it? At least somewhat hotfix - update ish

**Comment by MikeSonor** [comment]
Confirm! After create a new user wothout password, i got  link with wrong token. 
btw! If go to login page and try to reset password, new link in e-mail work! and user can change password.
