### ISSUE TITLE
Wont read log file.

### ISSUE THREAD

**Issue by AndersNorman** [pterodactyl/panel#1095]
* Panel or Daemon: Panel
* Version of Panel/Daemon: Unkown...
* Server's OS: Ubuntu 16:04
* Your Computer's OS & Browser: FireFox, Chrome.

------------------------

I have made a 7 days to die server egg file. I have a text output log where it prints the servers log. /7DaysToDieServer_Data/output_log.txt

Pterodactyl wont pick it up tho and the server is started. All players can connect but the panel just wont print anything from the console.

Here is the log config: 

{
    "custom": true,
    "location": "7DaysToDieServer_Data/output_log.txt"
}

Here is a video too.
https://www.youtube.com/watch?v=TKqaUWd6ErM

**Comment by AndersNorman** [comment]
Tried that, didn't do anything.

**Comment by parkervcp** [comment]
I am just calling it out that it should be set to false. first of all. Second, do the logs actually have anything there?

**Comment by AndersNorman** [comment]
Yes. over 1000 lines. Pterodactyl still wont show anything. 
[output_log.txt](https://github.com/pterodactyl/panel/files/1868065/output_log.txt)

**Comment by AndersNorman** [comment]
[egg-7-days-to-die.zip](https://github.com/pterodactyl/panel/files/1868067/egg-7-days-to-die.zip)
Had to make it to a zip cause of Github not allowing json.

**Comment by AndersNorman** [comment]
Talked to EddyNetWeb and he couldn't find a solution sadly.

**Comment by parkervcp** [comment]
You could of course just post the json to a gist...

**Comment by parkervcp** [comment]
Open an issue on my eggs repo. This doesn't look to be a panel direct issue.
