### ISSUE TITLE
API missing documentation

### ISSUE THREAD

**Issue by Raideerke** [pterodactyl/panel#1097]
Hello,

So i was asking it at Discord, but nobody given me a response for it, so ask it there.
I've seen the v0.6 api reference docs, everything is ok, there is a very good documentation for it.

Right now we're using the latest version, trying to write an app to manage the server powers/send commands to it, and there is no documentation.
I tried to make requests depending the v0.6 version, but i have no chance.

I will wait patiently. Tried to browse the source to check what are the possible usages, i only want to ask for two examples for power/command change requests, i always got MethodNotAllowed exceptions, even when using PUT, POST requests.

**Comment by lancepioch** [comment]
Can you post examples of the API requests that you are sending but are failing and the error messages with them? While I can't magic a whole new set of api docs, the least I can do is try to help you get through this.

**Comment by stanjg** [comment]
The API docs are indeed lacking at the moment.

For now you can take a look at my repository [Ptero4J](https://github.com/stanjg/Ptero4J) to see how the requests are supposed to be made.

**Comment by BrainStone** [comment]
I'm also dearly missing the docs on the API here.

**Comment by DaneEveritt** [comment]
This isn't really an issue that can be solved with code, I'm closing this as we know the docs are missing information and it will be added when I can find the time.
