### ISSUE TITLE
Per user panel language

### ISSUE THREAD

**Issue by jer3m01** [pterodactyl/panel#1106]
Feature request:

Would be nice if you could have an option (under profile) where you can change your language of the panel (not being admin and without changing everyone's panel's language).
Of course the language should be in the available languages on the server.

Thanks for your consideration.

**Comment by LeCodeCo** [comment]
+1

**Comment by JanDevDE** [comment]
+1

**Comment by LeCodeCo** [comment]
I think this already exists. https://file.properties/host/MgHGkveO.png

**Comment by DaneEveritt** [comment]
Closing in favor of #2518 which can handle this at the same time.
