### ISSUE TITLE
Nest/Egg creation error

### ISSUE THREAD

**Issue by LightningBladeXYZ** [pterodactyl/panel#1107]
* Panel or Daemon: Looks to be backend but could just be panel
* Version of Panel/Daemon: Panel[0.7.6] Daemon[0.5.5]
* Server's OS: Centos 7 || Kernel: 4.15.11-1.el7.elrepo.x86_64
* Your Computer's OS & Browser: Firefox Nightly, Firefox, Chrome, Chrome Dev (Any browser basically)

------------------------
PHP: 7.2.4 <-- Update to issue: amended PHP version
docker info : https://hastebin.com/anajupuruy.go

Issue: Unable to create nests/eggs at all due to error message: "Whoops, looks like something went wrong."

Steps to reproduce:
1) Make an egg or nest
2) See the error

Since I don't know what is causing the error please advise on what logs to provide. 
N.B. wings.log and request.log seems to show no sign of the error
Also pterodactyl.app-error.log is empty

![screenshot 38](https://user-images.githubusercontent.com/27926588/38946849-a18de93c-4332-11e8-8705-ed6fbeefee12.png)

**Comment by parkervcp** [comment]
@LightningBladeXYZ  Can you please pull the logs for the panel here? .logs in discord to get the commands.

**Comment by Bl4ckSpr4y** [comment]
The minimum PHP version required for 0.7.x is 7.2.x

**Comment by parkervcp** [comment]
We have a guide for CentOS 7 as well. - https://guides.pterodactyl.io/docs/centos7-panel-07

I wrote it. I know it works.

**Comment by LightningBladeXYZ** [comment]
Also, the php version is from the wrong server btw. I have too many panel open in tmux XD.
It's actually : PHP 7.2.4

**Comment by LightningBladeXYZ** [comment]
Here is the diagnostics report: https://hastebin.com/iyoqecekic
The other one is complaining it doesn't exist. So I'll check manually

**Comment by LightningBladeXYZ** [comment]
The latest laravel log that exists is 2018-03-21: https://bin.ptdl.co/01q0x/
Nothing newer

**Comment by LightningBladeXYZ** [comment]
No new lavarel logs, maybe this updated but doesn't look to be: https://bin.ptdl.co/qe09n/
Nothing in pterodactyl.app-error.log
Only new line in pterodactyl.app-access.log: `[18/Apr/2018:19:24:18 +0200] "POST /admin/nests/new HTTP/2.0" 500 1458 "https://panel.shardmc.com/admin/nests/new" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0"`
NPM Diagnostic again: https://hastebin.com/ifexipajik

**Comment by mayed505** [comment]
@LightningBladeXYZ you're exposing your .env file.....

**Comment by LightningBladeXYZ** [comment]
am I? oops. At least this isn't a production env

**Comment by LightningBladeXYZ** [comment]
SeLinux is disabled fully, so I don't see why that would create a problem

**Comment by parkervcp** [comment]
You hadn't specified that. I was just getting to a place where I knew what was going on.

**Comment by parkervcp** [comment]
What webserver are you running? nginx/apache? Have you verified the file permissions on the panel folder yet?

**Comment by LightningBladeXYZ** [comment]
Sorry about the snarkiness, was getting annoyed at some router and switch config issues and that seemed to bleed over. I'm running nginx and the file perms on /var/www/html/pterodactyl are all ok

**Comment by Chearful** [comment]
Had the same issue, in the .env file it is including the entire command used to generate it (i.e. php artisian blah blah blah). Just edit the .env file's author section manually and it should work, or at least for me.
