### ISSUE TITLE
teamspeak works but minecraft spigot doesnt work

### ISSUE THREAD

**Issue by SocialHype** [pterodactyl/panel#1109]
Everthing is installed correctly in the prev version everythings works but with the newest verstion from the panel the minecraft spigot doesnt work any more i have installed java and everything 
![image](https://user-images.githubusercontent.com/38562536/39054388-cdd0a702-44b1-11e8-9109-5f57be6d329c.png)

**Comment by DRSchlaubi** [comment]
Please run `npm run diagnostics` in /srv/daemon and send the link to your log here

**Comment by DaneEveritt** [comment]
This is not a panel specific issue.

**Comment by SocialHype** [comment]
https://pastebin.com/R3ZtpuQZ

**Comment by SocialHype** [comment]
i know but i cannot write a issue on the daemon ;/

**Comment by SocialHype** [comment]
and yea on discord someone from the support team says send me an pm and i help you but hes ignoring me everytime

**Comment by parkervcp** [comment]
It's not daemon specific either. It's minecraft crashing.
