### ISSUE TITLE
Default Nests / Eggs aren't showing up.

### ISSUE THREAD

**Issue by sachk** [pterodactyl/panel#1110]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.6
* Server's OS: Ubuntu Server 16.04 LTS
* Your Computer's OS & Browser: Windows 10, Google Chrome

------------------------

After installing the panel, and setting up the daemon I was trying to start a server when I realized there were no eggs/nests showing up. I checked /database/seeds/eggs and the folders and files were there, but not displaying in the web interface. Everything else works

![image](https://user-images.githubusercontent.com/10218019/39082321-99d557de-4594-11e8-958c-b58b350c25be.png)

**Comment by parkervcp** [comment]
You obviously didn't follow the docs - https://docs.pterodactyl.io/docs/installing-1#section-database-setup

namely the db:seed option.
