### ISSUE TITLE
File Not Found.

### ISSUE THREAD

**Issue by SwiftyPlaysMC** [pterodactyl/panel#1111]
* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.7.6
* Server's OS: Ubuntu
* Your Computer's OS & Browser: Win 10 & Chrome

I have installed pterodactyl and i am getting a file not found error when i go to the ip

**Comment by lancepioch** [comment]
Your web server isn't setup correctly. Unfortunately on Github we can't help you because it's not a Panel or Daemon issue. Please seek help from our wonderful volunteer staff on Discord, thanks

**Comment by SwiftyPlaysMC** [comment]
What is the discord?

**Comment by TheTrueColonel** [comment]
https://pterodactyl.io/
Literally on the front page.
