### ISSUE TITLE
Panel appears to be online while status on user mainpage is offline

### ISSUE THREAD

**Issue by Julianvb97** [pterodactyl/panel#1116]
* Panel or Daemon:  Both on one machine
* Version of Panel/Daemon: 0.7.6
* Server's OS:  Ubuntu 16.04
* Your Computer's OS & Browser:  Google chrome/ Firefox

------------------------

**Comment by parkervcp** [comment]
What does this even mean?

**Comment by Julianvb97** [comment]
well it wont input the whole information for some reason

**Comment by parkervcp** [comment]
Have you done a full refresh of the servers page (shift+f5 or ctrl+shift+r)

**Comment by Julianvb97** [comment]
Yeah I did, but the point is when I for example shutdown my laptop and restart it and go to the panel page it shows that it is offline again. I dont know if this could be fixed otherwise this isnt a great issue.
