### ISSUE TITLE
The ability to apply a static internal docker IP to a server

### ISSUE THREAD

**Issue by Golumpa** [pterodactyl/panel#1121]
Just installed the panel and everything works great, except on little thing i found. When creating a bungee network you are required to use the docker subnet IPs if you want to have the ports such as 25566 and 25567 closed. This is all good and all but what i found out is that if you startup the servers in a different order then the internal IP "eg. 172.18.0.2, 172.18.0.3, etc..." on lets say Bungee can be different every time.

The first server started is assigned 172.18.0.2 the second server is assigned 172.18.0.3 and so on. this can be a little troublesome when you have a bungee configuration set to certain internal IPs.

This feature suggestion will mean that the static IPs are reserved and a docker container cannot startup with a reserved IP by forcing it to use an specific IP using the docker run flag "--ip".

Below is a little image of how it could fit in the panel for demonstration purposes.

![paneldockersettings](https://i.golu.mp/images/png/TCkO8.png)

**Comment by PurpleIsEverything** [comment]
Keep in mind binding to the gateway of the bridge may break sometime in the future with newer versions of docker and is incompatible with pretty much every other network driver type besides bridge which is the default.

This is an option and a pretty decent one at that as with BungeeCord if you use the hostname of a servers container for it's server address you may run into issues where BungeeCord does not resolve a changed IP of a container from the hostname until restart or reload.

**Comment by parkervcp** [comment]
First of all you can just use the 172.180.0.1:<port> and it will always work.

Second, this isn't a viable option. It would need major revamping to the daemon to work in any way.

**Comment by PurpleIsEverything** [comment]
I'm afraid that's not entirely true I've investigated a number of networking configurations for Pterodactyl and made a PR to add better driver support to the daemon. 

Upstream refactoring in moby will eventually break binding to the bridge driver gateway in newer versions of docker. It's also already considered bad practice and has additional routing overhead depending on the kernel.

**Comment by djzoneporro** [comment]
I have the same problem with a custom bridge but I want to assign static ip's to each docker container and in pterodactyl I can't set --ip. 
Is there a way to assign pterodactyl containers a static ip?
https://prnt.sc/5aEBoDkS3zGD
