### ISSUE TITLE
Automatic updates in Source based gameservers

### ISSUE THREAD

**Issue by akzcs** [pterodactyl/panel#1122]
It is possible to make a script or something that automatically updates the CSGO server?

**Comment by lancepioch** [comment]
Perhaps some sort of scheduler per node or some sorts.

**Comment by DaneEveritt** [comment]
They should auto-update when they restart, theres logic in the base source container to handle that.

**Comment by akzcs** [comment]
They don't update when I restart them.

**Comment by rvidelaa** [comment]
@DaneEveritt ?

**Comment by DaneEveritt** [comment]
Then its probably a game that doesn't update through normal source protocols. Feel free to PR a fix to the images repo for the source branch if you know how to fix it.

I don't run any source servers so I don't know what all needs to happen for that to be fixed for all games.
