### ISSUE TITLE
no daemon.pid or init.d script

### ISSUE THREAD

**Issue by Luukth** [pterodactyl/panel#1126]
* Panel or Daemon: daemon
* Version of Panel/Daemon: 0.5.5
* Server's OS: 16.04.4 LTS (GNU/Linux 4.4.0-87-generic x86_64)
* Your Computer's OS & Browser: Windows 10 - Chrome

------------------------

The daemon does not create the file's I need to monitor the service with monit. My `/etc/systemd/system/wings.service` looks like this:
```
[Unit]
Description=Pterodactyl Wings Daemon
After=docker.service

[Service]
User=root
#Group=some_group
WorkingDirectory=/srv/daemon
LimitNOFILE=4096
PIDFile=/var/run/wings/daemon.pid
ExecStart=/usr/bin/node /srv/daemon/src/index.js
Restart=on-failure
StartLimitInterval=600

[Install]
WantedBy=multi-user.target
```
I am looking for the files `/var/run/wings/daemon.pid` and `/etc/init.d/wings`. Looking at the code above their should definitely be a daemon.pid file but it doesn't exist.

**Comment by schrej** [comment]
The `PIDFile` option is only used for services with `Type=forking`, it doesn't get by systemd or the daemon itself.

**Comment by Luukth** [comment]
@schrej so what you are saying it that I won't be able to monitor wings with monit because it doesn't generate the required files?

**Comment by parkervcp** [comment]
init.d/wings would be for a classic init system.

If you ware using systemd you generally don't have an init.d setup. That folder exists for legacy reasons only.

I don't know who added the PIDFile line to the systemd script.

**Comment by Luukth** [comment]
@parkervcp so monit is unable to monitor the daemon and perform a start if needed?

**Comment by parkervcp** [comment]
I guess. Does monit not work with systemd? It's the standard init system now.

**Comment by parkervcp** [comment]
Honestly google found this for me https://serverfault.com/questions/270316/monit-check-process-without-pidfile?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
