### ISSUE TITLE
Upgrade to jQuery 3.1.1

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#113]
It is not a drag and drop upgrade unfortunately, seems we ended up using some deprecated features (`.indexOf` appears to have been removed, or at least breaks the way we use it).

**Comment by djmattyg007** [comment]
It would also be worth moving to sweetAlert 2, which is actually maintained https://github.com/limonte/sweetalert2

**Comment by schrej** [comment]
Upgrading to sweetalert2 requires rewriting some stuff...
