### ISSUE TITLE
Request for U2F (Yubikey) 2FA Support

### ISSUE THREAD

**Issue by rouing** [pterodactyl/panel#1132]
With the advent of USB based 2FA and U2F Support on major browsers, I feel that U2F support would be a nice addition to the panel. 

https://www.dongleauth.info/
https://www.yubico.com/solutions/
https://www.wikiwand.com/en/Universal_2nd_Factor
https://www.nitrokey.com/news/2015/list-otp-and-u2f-supporting-websites-dongleauthinfo

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/commit/28bc86e23b50cd5569e2bcfaff58aec381b60673
