### ISSUE TITLE
How to update Source Server

### ISSUE THREAD

**Issue by TheGamin93** [pterodactyl/panel#1135]
Hello! What is the correct way to update a Valve Source server? I have running a CSGO game server and every X time they release an update, I have to delete the server and create it again.

How could the server update? when I boot it, I get this error message on console:

`Your server needs to be restarted in order to receive the latest update.`

I tried to add app_update 730 and 740 on command line but doesn't work :(

I have the Panel version 0.7.6 on debian server. 

Thanks!!!

**Comment by lancepioch** [comment]
This is not an appropriate question for a GitHub issue. Feel free to ask this on the Discord.

**Comment by akzcs** [comment]
@TheGamin93 Press the button "Reinstall server" in admin mode :)

**Comment by TheGamin93** [comment]
But if I reinstall the server, part of the configuration is erased. Any way to update the server without having to reinstall it?

**Comment by rvidelaa** [comment]
@TheGamin93 I am always doing and I have the same files... retakes, arena 1v1, deathmatchs, no data deleted

**Comment by AndyLee1024** [comment]
@TheGamin93 How did you solve this problem now?
