### ISSUE TITLE
Customer Egg - Avorion - Help

### ISSUE THREAD

**Issue by ryan1161** [pterodactyl/panel#1136]
Panel version - 0.7.6
OS - Ubuntu 16.04

Can I get some help I can't get the server to run but it does install the game correctly. I have tried to start the server with the start.sh script it comes with by default. Also even tried to run it off the binary file in the bin folder.

./server.sh --galaxy-name {{GALAXYNAME}} --admin {{ADMIN}} --datapath /home/container/galaxies/{{GALAXYNAME}}

./bin/AvorionServer  --galaxy-name {{GALAXYNAME}} --admin {{ADMIN}} --datapath /home/container/galaxies/{{GALAXYNAME}}

Server Console:
![server console](https://user-images.githubusercontent.com/2374149/39797561-36cffcb6-5322-11e8-9024-6b482d629338.png)

Avorion Egg:
[egg-avorion.zip](https://github.com/pterodactyl/panel/files/1986513/egg-avorion.zip)

Install Script:

#!/bin/bash
# Avorion Installation Script
#
# Server Files: /mnt/server
apt -y update
apt -y --no-install-recommends install curl lib32gcc1 ca-certificates

cd /tmp
curl -sSL -o steamcmd.tar.gz https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz

mkdir -p /mnt/server/steamcmd
tar -xzvf steamcmd.tar.gz -C /mnt/server/steamcmd
cd /mnt/server/steamcmd

# SteamCMD fails otherwise for some reason, even running as root.
# This is changed at the end of the install process anyways.
chown -R root:root /mnt

export HOME=/mnt/server
./steamcmd.sh +login anonymous +force_install_dir /mnt/server +app_update 565060 -validate +quit

mkdir -p /mnt/server/.steam/sdk32
cp -v linux32/steamclient.so ../.steam/sdk32/steamclient.so

**Comment by lancepioch** [comment]
This isn't a Pterodactyl issue. If you're having problems getting games to work I suggest you ask for help on Discord.

**Comment by parkervcp** [comment]
As a side note. you need to restart your daemon to load the egg you created.

**Comment by ryan1161** [comment]
Just wanted to say I got it working just need that restart of wings service.
