### ISSUE TITLE
Server Owner - Results Could Not Be Loaded

### ISSUE THREAD

**Issue by drkdragonarcher** [pterodactyl/panel#1137]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.6
* Server's OS: Ubuntu 16.04.4 LTS
* Your Computer's OS & Browser:  Windows 10, Chrome
* PHP version: 7.2.5-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  5 2018 04:59:13) ( NTS )
------------------------

When creating a new server the Server Owner never gets any results and just displays "The results could not be loaded" Attached is my log from the panel. I found #902 and #944 but the solutions don't apply to my install. Thanks!
[pterodactyl.log](https://github.com/pterodactyl/panel/files/1988465/pterodactyl.log)

**Comment by DaneEveritt** [comment]
Not really sure why this is only happening to you, or why that instance is passing null through as it should be coming through as a string.

As a temporary work around, change [this line](https://github.com/pterodactyl/panel/blob/develop/app/Http/Controllers/Admin/UserController.php#L200) to be:

```php
return $this->repository->filterUsersByQuery($request->input('q') ?? '');
```

**Comment by drkdragonarcher** [comment]
That fixed it. Thank you very much!
