### ISSUE TITLE
Mixed Content when using NGINX proxy

### ISSUE THREAD

**Issue by Luukth** [pterodactyl/panel#1138]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.6
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 / Chrome

------------------------
When connecting to my panel via chrome I get this error in the developer console
`(index):111 Mixed Content: The page at 'https://<domain>/' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://<domain>/'. This endpoint should be made available over a secure connection.`

I got this error when I used NGINX to cache responses to the server. Here is my configuration file for nginx.
[https://hastebin.com/equhodedug.nginx](url)

When looking at the code of the panel I saw there was a package called trusted proxys so my guess is there is a system in place to handle this issue. But for some reason it's not working for me. Maybe someone can point me in the right direction.

php -v
```
PHP 7.2.5-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  5 2018 04:59:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.5-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```
nginx -v
```
nginx version: nginx/1.10.3 (Ubuntu)
```

uname -a
```
Linux scw-37567d 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

docker info
```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 4
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-124-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989MiB
Name: scw-37567d
ID: 5SXW:OXWI:G7VI:KJTN:7PSB:5L52:YFUY:5FFD:RFJ6:SIP6:VZK7:W3KP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by parkervcp** [comment]
Why are you proxying the https connection on port 9000? https runs on port 443.

If you  are going to go about modifying configs in ways that break it then don't ask for help.

Also you didn't set a domain in the config from the looks of it.

**Comment by Luukth** [comment]
@parkervcp I followed this guide [https://serversforhackers.com/c/nginx-caching](url). In my opinion this shouldn't break nginx. In the config I replaced my domain with <domain>.

**Comment by DaneEveritt** [comment]
Try setting `TRUSTED_PROXIES=*` in the `.env` file.

**Comment by Luukth** [comment]
@DaneEveritt thanks, that fixed the issue I was having. Is TRUSTED_PROXIES something from pterodactyl itself or from the trusted proxies module? I have a very limited knowledge of laravel.

**Comment by DaneEveritt** [comment]
Its an environment variable specific to our app, but tells the app that there is a proxy being used and to make use of the features trusted proxy implements.
