### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by thegiantredpanda** [pterodactyl/panel#1139]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7
* Server's OS: CentOS 7
* Your Computer's OS & Browser: Windows 10 & Chrome Browser

------------------------
I installed pterodactyl. I use the guide on https://guides.pterodactyl.io/docs/centos7-panel-07-redis and did everything what it said. I've had no errors. But when I try to go to the panel it says Whoops, looks like something went wrong.

**Comment by thegiantredpanda** [comment]
PHP Version is 7.2

**Comment by Polarcraft** [comment]
@thegiantredpanda we only provide support for the panel through our discord, which is located here: https://pterodactyl.io/discord

**Comment by DaneEveritt** [comment]
Please provide the error logs associated with this error or use our Discord for additional support. This is most likely not an issue with the software, but an issue with your setup.

Feel free to reopen this issue if you believe it is a bug that needs fixing and not a setup mistake.
