### ISSUE TITLE
FTP Auth Failed... Connected!

### ISSUE THREAD

**Issue by 0xC1A551C** [pterodactyl/panel#1142]
* Panel or Daemon: FTP
* Version of Panel/Daemon: 0.7.6
* Server's OS: Debian 9.4 OVH
* Your Computer's OS & Browser: Linux Mint 18 Filezilla Firefox

------------------------

When transferring files over FTP to my servers it tell me my password authentication failed in the FTP logs within filezilla.

```
Command:	open "cisnet.sb546bb54@mira1.example.com" 2022
Command:	Pass: ***********
Error:	Authentication failed.
Error:	Critical error: Could not connect to server
```

But then it reconnects 5 seconds later & tries again with success. Seems to happen randomly, and I cannot figure out why. I have tried reinstalling the docker instance, updating filezilla, rebooting pc, updating pc, updating both the panel & daemon, ect.

```
Status:    Connecting to 192.0.0.0:2022...
Response:    fzSftp started, protocol_version=4
Command:    open "name.30bc8afb@192.0.0.0" 2022
Command:    Pass: **************************
Error:    Authentication failed.
Error:    Critical error: Could not connect to server
Status:    Disconnected from server
Status:    Delaying connection for 5 seconds due to previously failed connection attempt...
Status:    Connecting to 192.0.0.0:2022...
Status:    Connected to 192.0.0.0
Status:    Starting upload of /home/desktop/Downloads/EpicSpawners 5.0.0.3.jar
Status:    local:/home/desktop/Downloads/EpicSpawners 5.0.0.3.jar => remote:/plugins/EpicSpawners 5.0.0.3.jar
Status:    File transfer successful, transferred 212.8 KB in 1 second
Status:    Retrieving directory listing of "/plugins"...
Status:    Listing directory /plugins
Status:    Directory listing of "/plugins" successful
```

This happens over both the domain & direct ip. Seems like a server side issue as I have not experienced this on any of my other servers connecting over FTP with filezilla.

**Comment by 0xC1A551C** [comment]
I have also changed the port, and updated the /srv/daemon/config/core.json config.

**Comment by DaneEveritt** [comment]
Can you provide the daemon error logs using `npm run diagnostics` in the daemon directory and then provide the link to them here?

**Comment by DaneEveritt** [comment]
Are those the logs from right after you encountered the login error?

**Comment by 0xC1A551C** [comment]
Sorry, no @DaneEveritt that log was after I was using my working ftp account.

Just so you know I am doing this over sftp not ftp

I tried to login again with the root panel account over ftp giving me problems, and it wouldn't let me login through ftp but it did let me login through the panel. I changed the password in the panel thinking it was wrong, and it still wouldn't let me login through ftp until i waited a few mins & opened a new instance of filezilla. Then it worked (ran the command after that) https://hastebin.com/iridovesef

Then I tried logging in again which worked multiple times, on the 4th or 5th try it failed to login & I got the authentication failed ftp error. Here is another log just after it failed to login to ftp: https://hastebin.com/fesutivabe 

To be clear, I was using the quicklogin within filezilla button, so I am not entering the password incorrectly as it stores the password upon login.


Here is my attempt at using grep on the pterodactyl.app-access.log on my webpanel server.

https://paste.ofcode.org/5biQZ5pCEkx3dz2QN9QUpb

**Comment by DaneEveritt** [comment]
You need to check your panel error logs in `panel_dir/storage/logs` and get the last 200 or so lines. You should be using SFTP, _not_ FTP as they are entirely different protocols and not compatible with eachother.

**Comment by 0xC1A551C** [comment]
@DaneEveritt 

Ah, ok here you go: https://paste.ofcode.org/vMGdCURPE9PWy6tWQwBWkh

I am using sftp, sorry.

**Comment by 0xC1A551C** [comment]
Thanks @DaneEveritt

I should be able to change the permissions via chmod on the directory and everything recursively to fix this correct?

Otherwise, are there any pros of going with redis over the filesystem cache?

I already do  a lot of reading/writing to my mysql db, so I dont know if the mysql option would be the best.

**Comment by DaneEveritt** [comment]
MySQL is going to be one of the least performant cache options out there, and will end up bottlenecking you a bit. Redis is quite straightforward to get setup on the machine, and will be very speedy for you, especially as you scale up.

The filesystem can work fine, you can just chmod them recursively, yes. For a small setup filesystem and MySQL will work fine, but as you grow its going to become a pain point. Do whatever you feel most comfortable with, and if things start to slow down or seem inefficient you can re-address them at that time. :)

I'm going to close this now as I believe we've sorted it out, if the problem persists please feel free to re-open it by commenting here.
