### ISSUE TITLE
Using "localhost" as FQDN allows use of SSL connection for nodes

### ISSUE THREAD

**Issue by dordsor21** [pterodactyl/panel#1145]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.6
* Server's OS: Ubuntu

------------------------

As the title says; when creating and/or updating a node, using "localhost" as the Fully Qualified Domain name allow the use of an SSL connection.

**Comment by parkervcp** [comment]
An external user can't get ssl to localhost on your server.

The connection to nodes are made from your browser. They are not proxied through the panel.

**Comment by dordsor21** [comment]
The FQDN is for the panel to connect to the daemon though? It's got nothing to do with user's connections. If the panel is on the daemon/node is on the same machine as the panel, then localhost can be used for FQDN with no problem, but SSL cannot be enabled for localhost connections.

If I'm mistaken as to what the FQDN is, then fair enough, though by my understanding this is the case^

**Comment by lancepioch** [comment]
I don't see why having SSL on localhost is a necessarily a bad thing. Personally I don't see a point in using SSL for local only connections, however if a user really wants to do that, I can't see why it'd be an issue to allow it.

**Comment by dordsor21** [comment]
It's rather that you can't have ssl on local connections really

**Comment by lancepioch** [comment]
But you can.

**Comment by dordsor21** [comment]
Ah yes true. Apologies I'm quite tired...

**Comment by parkervcp** [comment]
In order to use localhost you need to be on the server itself to connect to it.
