### ISSUE TITLE
Deleting servers

### ISSUE THREAD

**Issue by Dann0010** [pterodactyl/panel#1151]
* Panel or Daemon: 0.7.4.1
* Version of Panel/Daemon: 0.5.3
* Server's OS: Centos 7
* Your Computer's OS & Browser: Windows & Opera

------------------------

Docker Version: 18.02.0-ce

As pre request, I can't even delete servers w/o running into errors.

When attempting to safe or force delete a server;

May 16 03:41:29 na15.pebblehost.com node[26586]
```
{  
   "name":"wings",
   "hostname":"na15.pebblehost.com",
   "pid":26586,
   "server":"514982ca-3862-4557-b6a3-d50ee200545e",
   "level":40,
   "err":{  
      "message":"Unable to determine size of server data folder, exited with code 1 signal null.",
      "name":"Error",
      "stack":"Error: Unable to determine size of server data folder, exited with code 1 signal null.\n    at ChildProcess.Exec.on (/srv/daemon/src/controllers/fs.js:94:29)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at Process.Child                                                                                                                                                                                             Process._handle.onexit (internal/child_process.js:219:12)"
   },
   "msg":"Unable to determine size of server data folder, exited with code 1 signal null.",
   "time":"2018-05-16T07:41:29.173Z",
   "v":0
}
```

The daemon is online and running and other servers are deletable this error only happens to some servers.

**Comment by DaneEveritt** [comment]
Sorry for the late response, is this actually happening when deleting, or is it just in the logs around that time? Does the panel report any specific errors, or just something about there being an error on the daemon?

I wasn't under the impression that the daemon did any additional checks on data size when deleting.

**Comment by Dann0010** [comment]
Thats the only error I was able to get, Nothing on the panel.

**Comment by DaneEveritt** [comment]
So it just didn't delete from the daemon but the panel reported no errors?

**Comment by DaneEveritt** [comment]
Closing this as no one else has reported this issue, and you've not provided any follow up. Feel free to re-open with more information. 👍
