### ISSUE TITLE
PTDL on boot

### ISSUE THREAD

**Issue by Dann0010** [pterodactyl/panel#1153]
* Panel or Daemon: 0.7.4.1
* Version of Panel/Daemon: 0.5.3
* Server's OS: Centos 7
* Your Computer's OS & Browser: Windows 10 & Opera

------------------------

A fair bit of the time a user will attempt to boot their server and will run into this error;

[Pterodactyl Daemon] Oh dear, it seems something has gone horribly wrong while attempting to boot this server. Please contact your administrator for assistance. PTDL:ERR_ID:tOIIHvbIQbafJWFr1ZEn

Which results in this log;

May 16 10:08:12 eu04.pebblehost.com node[4092]: 
```
{  
   "name":"wings",
   "hostname":"ns3362587",
   "pid":4092,
   "server":"b186900f-7672-48ae-b04c-de2306ca6805",
   "level":50,
   "err":{  
      "message":"(HTTP code 500) server error - container \"50aa78be7c2bc2f24765466cdfe790d5cd887ab09394ad32718f5fbb66e87b02\": already exists ",
      "name":"Error",
      "stack":"Error: (HTTP code 500) server error - container \"50aa78be7c2bc2f24765466cdfe790d5cd887ab09394ad32718f5fbb66e87b02\": already exists \n    at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17\n    at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)\n    at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)\n    at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"
   },
   "msg":"{ errorId: 'tOIIHvbIQbafJWFr1ZEn' }",
   "time":"2018-05-16T08:08:12.052Z",
   "v":0
}
```

It can normally be resolved by stopping and removing the container, which is fine on a small scale but on a large scale this issue needs to be resolved.

**Comment by schrej** [comment]
This is a known and already fixed issue. Upgrade to Daemon v0.5.4+ to fix it.
