### ISSUE TITLE
Subusers servers showing as error

### ISSUE THREAD

**Issue by Dann0010** [pterodactyl/panel#1155]
* Panel or Daemon: 0.7.4.1
* Version of Panel/Daemon: 
* Server's OS: Centos 7
* Your Computer's OS & Browser: Windows 10 & Opera

------------------------

Once a subuser reaches a page worth of added servers (from what I know) all their servers then show up as error other than suspended servers.

Screenshot from panel:
https://i.danjackson.info/86eebc2b87d9806.png

Screenshot of the console for the browser: 
https://i.danjackson.info/a73f5c7e28bb862.png

**Comment by schrej** [comment]
Please provide the error log of the panel as well to determine what is causing that http 500 response.

**Comment by Dann0010** [comment]
The only logs within the panel I'm getting are for suspended servers.

**Comment by schrej** [comment]
Then there might be an error on the daemon side. v0.5.4 also mentions a fix with permissions regarding status and subusers.

**Comment by DaneEveritt** [comment]
There was a fix in 0.7.5 to fix subuser permissions on their outgoing connections to the daemon if they are missing a key. Upgrading the Panel from 0.7.4.1 to 0.7.7 would be a good first step to see if this is resolved by that change.

You can also take a look at the daemon_keys (can't think of the name off the top of my head unfortunately) table and see if there is a key linked between the user_id and server_id.

**Comment by lancepioch** [comment]
@Dann0010 Did upgrading the panel resolve the issue for you?

**Comment by DaneEveritt** [comment]
Closing, not enough information and no other reports of this occurring.
