### ISSUE TITLE
Cant find this one in the list

### ISSUE THREAD

**Issue by alextovey** [pterodactyl/panel#1157]
HI All,

I'm running ubuntu 16.04 and version 0.7.6 of pterodactyl.

Is it possible to have Arma 3 on the servers? Just that i've tried open game panel, tcadmin, gamepanel x and none do it well once you get away from the default option. I wanted to add exile, infistar and extended base mod. is this possible?

**Comment by TheTrueColonel** [comment]
Go to the discord server and check the pins in the `#Eggs` channel. Parker has a repo for eggs. One of the eggs is for ARMA
