### ISSUE TITLE
Database Connection 'localhost' results in Data integrity exception

### ISSUE THREAD

**Issue by JeremyGuinn** [pterodactyl/panel#1158]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.6
* Server's OS: Ubuntu 16.04.4
* Your Computer's OS & Browser: Windows 10 & Firefox Quantum 60

------------------------

1. Open admin panel
2. Have an existing database setup for a node
3. Have an existing server created on a node
4. Go to Servers>[server you're editing]>Database
5. Select the database host, database name
6. Enter an incorrect value for allowed connections (e.g. localhost)

Result: "Whoops, looks like something went wrong." page from laravel.

Expected: Error notification of incorrect value on page

```
[2018-05-16 17:06:52] production.ERROR: Pterodactyl\Exceptions\Model\DataValidationException:
Data integrity exception encountered while performing database write operation.
{"remote":["The remote format is invalid."]} in /var/www/pterodactyl/app/Repositories/Eloquent/EloquentRepository.php:58
```

[Full Stack Trace - laravel log](https://pastebin.com/raw/pMHQkAVh)

**Comment by lancepioch** [comment]
So it looks like we just need JS validation

**Comment by DaneEveritt** [comment]
That exception shouldn’t happen if the validator was used correctly. Looks like I’m not validating the host the same way that the model expects it to be.
