### ISSUE TITLE
Navigation menu shows a hint of text when minimized

### ISSUE THREAD

**Issue by JeremyGuinn** [pterodactyl/panel#1160]
*  Panel or Daemon: Panel
  *  Version of Panel/Daemon: 0.7.6
  *  Server's OS: Ubuntu 16.04.4
  *  Your Computer's OS & Browser: Windows 10 & Firefox Quantum 60

------------------------

Minimizing the navigation menu shows the Pterodactyl logo, but still shows part of the "Pterodactyl" text.

![Minimized](https://i.gyazo.com/d4bafc127faa6622420c83c4819bebc6.png)

**Comment by schrej** [comment]
Weird, I don't see that on the demo for example:
![image](https://user-images.githubusercontent.com/1710904/40221372-94a7574c-5a7c-11e8-9381-535e49ea16e5.png)

**Comment by JeremyGuinn** [comment]
It is a firefox issue. I tested on chrome and it works fine.

![img](https://i.gyazo.com/92a0c114795ac4e96ef648588d37813a.png)

**Comment by parkervcp** [comment]
Can verify on Firefox 61 as well

**Comment by JaydenDownes** [comment]
It seems that sometimes it also won't show the favicon at all. On the demo site and on my test bench it seems this issue is only in Firefox. Also, I would recommend adding a space between the logo and the start of the Pterodactyl text. I might make a pull request tonight to fix both of these issues if I get time.

**Comment by parkervcp** [comment]
I just checked and it seems to work fine for me now across different panels (personal and demo).

**Comment by ayan4m1** [comment]
Cannot reproduce on Firefox Quantum 60.2.0esr - CentOS 7. There is no text showing when the menu is collapsed, only the icon.

**Comment by lancepioch** [comment]
We've went through this issue a few times before implementing the correct `logo-lg` and `logo-mini` classes directly from bootstrap. Because only the older versions of Firefox may have issues with this, we're going to considered this resolved, thanks.
