### ISSUE TITLE
Ability for a user to select an available theme from the panel

### ISSUE THREAD

**Issue by JeremyGuinn** [pterodactyl/panel#1162]
This is a suggestion for panel themes. Currently the theme has to be specified in the environment file with APP_THEME.
It would be great if the user could select an available theme from a dropdown.

This is similar to suggestion https://github.com/pterodactyl/panel/issues/1106, and would most likely be the same implementation.

**Comment by DaneEveritt** [comment]
Won't be adding this. Moving away from a multi-theme setup and only supporting one core theme. If people want to make modifications to it they will be able to do so via the build tools or by having custom injected CSS and JS from the admin side of things.

This multi-theme setup is a huge hassle when it comes to designing a build system and is unnecessary complexity for 99% of users who are only using one theme.
