### ISSUE TITLE
[Suggestion] Add ssl proxy support

### ISSUE THREAD

**Issue by Asherslab** [pterodactyl/panel#1163]
* Panel or Daemon: panel
* Version of Panel/Daemon: 0.7.6 
* Server's OS: Centos7
* Your Computer's OS & Browser: OSX  Sierra, Firefox

------------------------

Hey there, i'm Currently running the panel on my server, and am trying to put it behind a reverse proxy that also proxies the SSL certificates. Currently when i do this the /auth/login page (for example) form has: `<form id="loginForm" action="http://MyDomain.com/auth/login" method="POST">` obviously this does not have the `https` that the url i'm acessing via does.

As far as i'm aware (Not a PHP person, so i'm not sure), the extension: https://github.com/fideloper/TrustedProxy
adds support for ssl proxies in it. This is already a dependency you guys are using. 

It would be great if you could add support for this 😄

**Comment by DaneEveritt** [comment]
This already exists, look in composer.json.
