### ISSUE TITLE
Minecraft Issue

### ISSUE THREAD

**Issue by dueckers5** [pterodactyl/panel#1165]
* Panel or Daemon:  Daemon
* Version of Panel/Daemon: 0.7
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 / Google Chrome

------------------------

I am trying to get minecraft setup but none of the servers i try will start up.
they all have an error like this 

> [Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 43M / 5000M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Oh dear, it seems something has gone horribly wrong while attempting to boot this server. Please contact your administrator for assistance. PTDL:ERR_ID:uDV4mV3fi3WoaDfpemB3

> 
If there is anything someone can do to help me it would be great! Also I can give extra info if needed.
I am trying to run Spigot btw.

**Comment by DaneEveritt** [comment]
Please provide the logs from the daemon that link up with that error. `PTDL:ERR_ID:uDV4mV3fi3WoaDfpemB3` should show up in the logs indicating which specific error lead to that display.
