### ISSUE TITLE
Daemon chown takes 4 minutes due to large number of small files.

### ISSUE THREAD

**Issue by wispoffates** [pterodactyl/panel#1172]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.7.6 / 0.5.5 
* Server's OS: Ubuntu 16.04.4
* Your Computer's OS & Browser: Ubuntu 16.04.4 - Firefox 60

------------------------

The chown run prior to minecraft server startup part of "[Pterodactyl Daemon] Ensuring file permissions." takes 4 minutes to complete.  I can't find the text log for timestamps so you'll have to trust my stopwatch on this one.  I'm wondering if there is a configuration change I can make somewhere to avoid this step.  If I set my docker daemon user as pteroractly can this step be avoided.  Or can I setup a file telling it to exclude some directories from the chown.  My guess is that the large number of small files in dynmap is causing this to occur.

---------------------------

root@ns5000312:/home/daemon-data/b76f1ef4-5558-4c08-a13c-f99fe735ae51/plugins# find dynmap | wc -l
1052260

**Comment by MarkL4YG** [comment]
You can.
In the ``core.json`` set ``internals.set_permissions_on_boot=false``.

**Comment by lancepioch** [comment]
@wispoffates Please close the issue if that solution works for you, thanks.

**Comment by wispoffates** [comment]
This fixed the issue.

**Comment by danmartinez78** [comment]
I'm having the same issue with 1.0, how to alter config.yml to disable chown check?

**Comment by trenutoo** [comment]
> I'm having the same issue with 1.0, how to alter config.yml to disable chown check?

There's no reason to bump 3-year-old issues. This is covered in [the documentation](https://pterodactyl.io/wings/1.0/configuration.html#other-values) with the variable name having a friendly name of `check_permissions_on_boot`
