### ISSUE TITLE
Ability to autostart a container once its marked "installed"

### ISSUE THREAD

**Issue by ryanbentley** [Pterodactyl/Panel#118]
It's especially useful for a SRCDS game that requires steamcmd to download/update files.

**Comment by DaneEveritt** [comment]
Easy enough, configurable per-server, or global?

**Comment by ryanbentley** [comment]
Could be an option in the service options maybe, and you can override these when creating a service. For example, by default my CSGO service option would start when the container is installed, but if I created a server that sent auto_start=False, then it doesn't.
