### ISSUE TITLE
Packs not working

### ISSUE THREAD

**Issue by Sergzy** [pterodactyl/panel#1185]
* Panel or Daemon:  Daemon
* Version of Panel/Daemon:  0.5.6
* Server's OS:  Ubuntu 16.04

------------------------

"Packs" system does not seem to do anything. It is supposed to install pack on container rebuild, but pack install function is never called in server.js or docker.js when it is rebuilding containers.
There is also no messages in any of the logs which were supposed to be sent out by pack.js.

**Comment by schrej** [comment]
It's not supposed to install the pack on container rebuild but on server reinstallation.
The container rebuild only recreates the docker container, it doesn't touch the files of the server.

**Comment by Sergzy** [comment]
Makes sense. I misunderstood the thing. Will do more testing taking this into consideration and will report back accordingly.
