### ISSUE TITLE
[Request] Allow using IPv4 and IPv6 on the same port

### ISSUE THREAD

**Issue by BrainStone** [pterodactyl/panel#1186]
It would be very cool to allow a server to run on both a IPv4 and a IPv6 address on the same port. (Assuming the server software supports having both active. Like TeamSpeak)

I came across this warning in the panel

> Please note that due to software limitations you cannot assign identical ports on different IPs to the same server.

And while I understand that it might not be possible to run a server on two IPv4 addresses on the same port, using IPv4 and IPv6 might be a different story.

**Comment by schrej** [comment]
I've done a little bit of research. I'm not really sure if docker is able to dot that. That would be the restriction preventing us from doing this.
I personally don't consider this important enough to do a lot of research, if you can find stuff related to it I'll be happy to look at it, though.

**Comment by rouing** [comment]
This is actually possible, however this requires a bit of change in the sysctl. 

`
sysctl net.ipv6.conf.default.forwarding=1

sysctl net.ipv6.conf.all.forwarding=1`

I will gather more information regarding this from my enterprise instances where we have done exactly this.

**Comment by matthewpi** [comment]
This is currently possible but may require additional configuration with Docker and or sysctl.

**Comment by BrainStone** [comment]
Then why did you close it?  
There's a limitation in Pterodactyl preventing it, even if it's possible on the docker level.

**Comment by matthewpi** [comment]
> Then why did you close it?  
> 
> There's a limitation in Pterodactyl preventing it, even if it's possible on the docker level.

There is nothing in Pterodactyl that prevents this.  I have IPv6 working on my dev panel and it only required me to enable IPv6 in Docker.

**Comment by BrainStone** [comment]
Ah ok. There absolutely used to be something in ptero. Glad to know that it was removed.

Btw not talking about ptero allowing IPv6. I meant it blocking using the same port for IPv4 and IPv6.

**Comment by matthewpi** [comment]
> Ah ok. There absolutely used to be something in ptero. Glad to know that it was removed.
> 
> 
> 
> Btw not talking about ptero allowing IPv6. I meant it blocking using the same port for IPv4 and IPv6.

It doesn't block that.  And from what I have read that sounded like a Docker limitation.
