### ISSUE TITLE
Quick Version Switch

### ISSUE THREAD

**Issue by DiscoverSquishy** [pterodactyl/panel#1190]
_It would be an easier process for users/clients if they can be able to switch their servers like how Multicraft offers it._ 

_Maybe like a dropdown menu or a modal when a user clicks a button that asks them to select the version to what they'd like switched it would take the Spigot or whatever version unzip it to the server and switch the server parameters and start the server._ 

_It would really take off the load on Pterodactyl admins to have to switch a certain server version make sure it's working and etc.._

**Anyways I hope this can be considered as it would be a big life changer for Pterodactyl admins.**

**Comment by RexTheMon** [comment]
Definitely a good addition to the panel and takes off the pressure on the system admins.

**Comment by Zeckll** [comment]
Sounds like a great idea, I'd love to see it implemented. It'd make life on all of us much easier.

**Comment by schrej** [comment]
This would be possible once #832 gets implemented. Users are able to change the version that is supposed to be installed on the Minecraft packs, they just can't reinstall the server.

**Comment by Sergzy** [comment]
There's already a Packs feature which does this, but it is lacking implementation in user side of the panel for some reason.
There's already settings (selectable, visible, locked, etc) in admin panel which indicate that packs are supposed to be user controlled.

**Comment by DiscoverSquishy** [comment]
@schrej So should I close this or keep it open for Dane or someone to close once this gets added in?

**Comment by schrej** [comment]
Let's close it, I've put the other issue on the list for 0.8.0, let's see if we also implement it :sweat_smile:

**Comment by warstrolo** [comment]
Hi, just want to know if this feature will be implemented.

**Comment by gOOvER** [comment]
> Hi, just want to know if this feature will be implemented.

schrej schrej closed this on 7 Jun 2018

The answerr for your question

**Comment by warstrolo** [comment]
Yeah but no cause he was telling that first #832 will be implemented but this issue is now implemented.

**Comment by schrej** [comment]
If there is a version field available, change it and then reinstall.
