### ISSUE TITLE
Better options for server organization as a user

### ISSUE THREAD

**Issue by DiscoverSquishy** [pterodactyl/panel#1192]
I'm always frustrated when I have to look through a unorganized list of servers because it lists them based on when it was created. If users could have folders for their servers the looking and finding process could be easier.

Maybe having these stuff in a horizontal order or like a bar with the following info
- User's Name
- Servers Assigned + Number
- MB/GB of ram using in total
- Maybe a little graph of their total CPU usage? _I guess that's possible with Chart.js_

**Comment by schrej** [comment]
I don't think we'll do folders as that's a lot of work to implement as we have to store the folders for each user and subuser etc.
We will improve the list with 0.8.0 and the Vuejs frontend though, probably including ordering of servers by name, egg and owner. We can look at the CPU graph, that's probably pretty resource hungry when showing lots of servers though.

**Comment by DubstepCraig** [comment]
This needs to be implemented

**Comment by DiscoverSquishy** [comment]
Hey @schrej what if the horizontal bars could be added but like the cpu usage stuff stays until it's fully optimized so that it wont be resource hungry? That's just a suggestion.

**Comment by schrej** [comment]
Oh, I didn't get what you requested the first time. You want an overview over the servers per user, I thought you wanted users to be able to organise their servers in folders.

We already have parts of it, see on the [demo](https://demo.pterodactyl.io/admin/users) for example. We basically need to add total ram and and, maybe, total cpu usage, even though that's going to be tough.
You can see the amount of servers as the number and a list of servers once you click on it.

**Comment by DiscoverSquishy** [comment]
@schrej Do you want me to make a mini mockup of what I exactly mean? Maybe stuff could be clearer if I do?

**Comment by schrej** [comment]
Feel free ;)

**Comment by DaneEveritt** [comment]
@DiscoverSquishy things are moving at a snails pace right now. I don't think any of this new stuff has ended up in the re-design, but the re-design is really focusing more on removing unnecessary information and making it easier to quickly locate the server you're looking for. Thats not saying this _won't_ be added, just that it isn't there yet.

![](http://i.kumquat.io/01d24b5732e2/download/Image%2525202018-09-05%252520at%25252022.45.20.png)

**Comment by DiscoverSquishy** [comment]
Alright noted @DaneEveritt

If you would like to close this you can :)
