### ISSUE TITLE
Delete Files Suggestion

### ISSUE THREAD

**Issue by Strikeless2GO** [pterodactyl/panel#1193]
Hi, I have a suggestion about the deleting files confirmation screen. So when I delete a file for example it gives me the check mark and to hit OK, except it's a pain having to hit OK every time I would like to delete a file since I for example need to do something quickly. If the OK screen could be removed, that would be awesome.

**Comment by parkervcp** [comment]
So you want to get rid of the delete confirmation process?

**Comment by Strikeless2GO** [comment]
Yes

**Comment by parkervcp** [comment]
What happens then if you hit delete on an important file?

If you are moving quickly and delete something that you don't mean to because it didn't verify then I bet it's our fault for not having the check in place.

Use the sftp connection to do this kind of work if you want it to be faster.
