### ISSUE TITLE
Can't download rar file

### ISSUE THREAD

**Issue by Strikeless2GO** [pterodactyl/panel#1194]
Hi, so I can't seem to download files on the latest update. I moved all my files to do a reinstall of a server into a folder and compressed it to a rar, and hit download, but when I hit download this happens:
https://imgur.com/a/l000QUH and it doesn't even pop up below in the download section.

Here's some information:
 Version of Panel/Daemon: Latest Panel version after SFTP Patch
 Server's OS: Ubuntu 16.04

**Comment by DiscoverSquishy** [comment]
**Just to note - It compresses onto a .tar, not .zip.**

Anyways, I'm experiencing this issue too, just tried to download a compressed folder - Gave me the loading files thing then never downloaded it.

**Comment by lancepioch** [comment]
Can you post your error log(s) or the JS errors from the console

**Comment by DaneEveritt** [comment]
Not enough information to reproduce and no one else has complained of this.
