### ISSUE TITLE
Reinitialize iptables chains each time the daemon starts

### ISSUE THREAD

**Issue by ryanbentley** [Pterodactyl/Panel#120]
I've made the mistake of clearing my iptables chains assuming the daemon would recreate them, of course you can just restart the docker service to get these back, but it's probably a good idea for a check to be in place

**Comment by DaneEveritt** [comment]
Interesting predicament, I'm not sure how often people will be clearing their chains, potentially adding a check to the daemon for them, and if they aren't there suggest restarting the docker daemon?

**Comment by ryanbentley** [comment]
Yes, that seems like the most appropriate way.

**Comment by DaneEveritt** [comment]
Can't really think of a good way of doing this aside from having docker restart. Haven't seen this happen to anyone during this time either, so I'm going to go ahead and close this.
