### ISSUE TITLE
No email sent when server is marked as installed.

### ISSUE THREAD

**Issue by n-valverde** [pterodactyl/panel#1202]
Panel or Daemon: Panel
Version of Panel/Daemon: Panel 0.7 / Wings 0.5.6
Server's OS: Debian 9 virtual machine KVM
Your Computer's OS & Browser: Windows 10 / Chrome-Firefox

Hi guys !
First of all, I'm new here, just discovered your work a few days ago, so thank you for this awesome job !

I've already run through a couple of problems which I was able to solve on my own, but I have still one and I'm not sure if it's a bug or a not implemented feature.

Here's the situation : 
I had trouble sending mail, but figured out it was a server config issue, fixed it, restarted VM to be sure, mails are now sending fine to new users when creating account, and I can see them on my mail server's logs.
But, when I create a server, booting it up or not, the assigned user never receive the mail, despite the install page saying "Server installation in progress, you will receive an email when process is complete". And if I check my mail server's logs, I find no trace of a failed connection, nor a mail passing through.
I also checked the table "jobs" and "failed_logs", 1st is empty, 2nd one contains some errors but the timestamp shows it was during older tests.

So my question is, is this mail supposed to be sent ? I've already do a lot of research in docs/guides/github/google but cannot find any clue on this one.

Anyway, thanks again for your work ! I will try to contribute, at least for langs, and try to lay some eggs :)

**Comment by stanjg** [comment]
This is indeed a bug. The lang files indeed say it's intended to send an email, however in the code there's no sign of that at all. (See: https://github.com/pterodactyl/panel/blob/5f90d841d063852b7e3692359a35deb8f5258e51/app/Http/Controllers/Daemon/ActionController.php#L19)

There is also no Notification email made for it. 

So either it should be removed from the lang file, or a notification should be made for it.

@DaneEveritt Let me know which one it should be and I can PR it.

**Comment by DaneEveritt** [comment]
Whoops 😬

We should be sending emails when the server is installed for sure, looks like it got nuked accidentally during that huge rewrite of everything. Look around and see if any parts of it remain, I feel like the template for it probably is still out there.

For the PR, It'd probably be easiest to fire off the event in the API controller function that the daemon calls on completion, and just pass the server model through.
