### ISSUE TITLE
Minecraft Vanilla egg deprecated

### ISSUE THREAD

**Issue by Doc94** [pterodactyl/panel#1205]
Actually the Minecraft Vanilla Egg use not avaible url, actually the url  `https://s3.amazonaws.com/Minecraft.Download` not work for download servers.

The form now for download servers its check versions into `https://launchermeta.mojang.com/mc/game/version_manifest.json` this json contains versions and another url for any version with more info, using the actually 1.13-pre2 the url for info is `https://launchermeta.mojang.com/mc/game/6b31fc4f3cf1672bd4cf49d2f1fc39facc2af4f3/1.13-pre2.json` and this json contains the url for download server.

Actually this egg not work correctly.

**Comment by parkervcp** [comment]
You do realize the server jar is still hosted on the aws instances. The link we generate is still good.

We aren't downloading the game. We are downloading the server.

**Comment by Doc94** [comment]
i know, i recently generate a server for the 1.13-pre2 and first i need change the rules of the version variable, and the server not download, checking the url i get a access denied.

**Comment by parkervcp** [comment]
You should specify that next time.

An exact issue like "When installing the latest pre-release" the installer is failing due to the url for downloading the server.jar is bad.

**Comment by parkervcp** [comment]
@Doc94 Here is a fixed version of the egg. https://github.com/pterodactyl/panel/blob/fix/eggs/database/seeds/eggs/minecraft/egg-vanilla-minecraft.json

**Comment by Doc94** [comment]
Updated in panel and work perfectly, thanks.

**Comment by DaneEveritt** [comment]
Fixed
