### ISSUE TITLE
Master template using wrong permission for schedules.

### ISSUE THREAD

**Issue by MarkL4YG** [pterodactyl/panel#1209]
1. Enable "List schedules" on a sub-user.
2. The user is granted ``list-schedules`` (seen in the database)
3. The panel still does not display "Schedules" to the user.
4. [layouts/master.blade.php l. 149](https://github.com/pterodactyl/panel/blob/develop/resources/themes/pterodactyl/layouts/master.blade.php#L149) seems to ask for ``list-tasks``
5. Changed it to ``list-schedules``
6. The panel does display "Schedules" to the user.

I believe this may be a left-over from an edit somewhere in the past. ^^

**Comment by schrej** [comment]
And why did you remove all the base information from the issue template?

**Comment by MarkL4YG** [comment]
Because I thought that it would not be necessary ._.
The controller clearly uses ``list-schedules`` and the template clearly doesn't. 
Panel version is 0.7.7 if you needed that. I don't see where daemon, OS and the other stuff would influence what's being stored in the DB.

**Comment by MarkL4YG** [comment]
I mean, here you go, if you really need it:

* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.7.7
* Server's OS: Ubuntu 16.04.4
* Your Computer's OS & Browser: Win10/Chrome

**Describe the bug**
A user granted "List schedules" is not shown the "Schedules" menu item.

``php -v``
```
PHP 7.2.4-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:53:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.4-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

**To Reproduce**
Grant a subuser "List schedules" using the checkbox in the permissions form.

**Expected behavior**
The user should see the "Schedules" menu item.

**Suggested fix**
Change ``list-tasks`` to ``list-schedules`` in [layouts/master.blade.php l. 149](https://github.com/pterodactyl/panel/blob/develop/resources/themes/pterodactyl/layouts/master.blade.php#L149)
