### ISSUE TITLE
Servers wont finish installing - MC Bungee, two spigots

### ISSUE THREAD

**Issue by Apprisco** [pterodactyl/panel#1211]
**Background (please complete the following information):**
* Panel or Daemon: Pterodactyl :P
* Version of Panel/Daemon: 0.7.7
* Server's OS: Linux
* Your Computer's OS & Browser: OS X/Chrome

**Describe the bug**
When I create new servers they are stuck at a certain point in installation forever.

**To Reproduce**
1. Create new server :P
2. Experience error
**Expected behavior**
I expected the installation to finish, after at least 2 hours, I decided that something was wrong.

**Comment by DragoSpiro98** [comment]
How you solve that? Anyone help me in discord
