### ISSUE TITLE
Allow to restrict access to databases to hosts/ip addresses

### ISSUE THREAD

**Issue by primaxius** [pterodactyl/panel#1215]
It would be nice to be able to change the database connection from in the panel instead of having to force it via mysql directly. http://prntscr.com/jzm4it

**Comment by parkervcp** [comment]
What would you want to change that too? You can't use 127.0.0.1

**Comment by Yomanz** [comment]
Forum or Donation systems that might need to access data from there.

**Comment by parkervcp** [comment]
% is a literal 'any'. So access is available on all addresses.

**Comment by schrej** [comment]
Yes, what they want is to be able to limit the connection source to specific hosts/ip addresses. And that's currently not possible.

**Comment by LeCodeCo** [comment]
I believe this is possible now. 

![](https://i.imgur.com/aFfbH8v.png)
