### ISSUE TITLE
Add audit logs

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#1219]
We should add audit logs of the panel that track all changes on the panel.

All changes to models should be tracked. Additionally:
- logins (maybe)
- server start/stop/restart/kill
- server commands (maybe)

It should also be configurable and allow to disable some logs, especially ones like server commands or logins that can generate a lot of data fairly quickly.

Also the option to only keep logs for a specific time, maybe even per category would be nice.

https://github.com/owen-it/laravel-auditing

**Comment by DavidRazdolski** [comment]
Maybe also add logging for commands issued via console and the possibility to see which sub-user issued them? Also, maybe a log for webbased file manager changes like deletion, uploading, editing. Just a thought

**Comment by Asherslab** [comment]
i'd say it should be decently easy to do at least commands issued via console, which would be great. 
Otherwise i like the idea of knowing if webbased file manager actions were taken too.
Either way, would be awesome to see this soon =D
Keep up the great work!

**Comment by parkervcp** [comment]
Adding after discovering that I keep getting random failed hits for sftp on the daemon we need to track SFTP login fails and their IP addresses as well.

**Comment by JustinRijsdijk** [comment]
Is this already in development?

**Comment by schrej** [comment]
Nope. But feel free to implement it and open a pull request, if you are interested :)

**Comment by JustinRijsdijk** [comment]
I will look into it.
Just for my information would we want, an audit log per server (filter on server id's?)?
or would we want an audit log for the whole app? (this does not have my perference, due to hosting companies using the panel).

**Comment by parkervcp** [comment]
The sftp logging isn't tied to a single server.

**Comment by schrej** [comment]
Ideally we would track everything globally, with the option for server owners to view the logs for their servers individually.
So we would have two locations where we display the output:
* on the admin interface with a global view of all audit log entries
* per server view of all related audit log entries (actions on the server only)

Additionally maybe a third view where a user can see all of the actions that were performed with his account.

**Comment by JustinRijsdijk** [comment]
maybe also in the admin interface, and maybe even in the server interface, it would be good to make it filterable? logins, server actions (start, restart, kill, stop), sftp?, and for each model a filter option?

so an audit will contain: user_id, server_id, type (action, login etc), performed_action (start, stop, changed file etc)

**Comment by JustinRijsdijk** [comment]
> Ideally we would track everything globally, with the option for server owners to view the logs for their servers individually.
> So we would have two locations where we display the output:
> 
> * on the admin interface with a global view of all audit log entries
> * per server view of all related audit log entries (actions on the server only)
> 
> Additionally maybe a third view where a user can see all of the actions that were performed with his account.

Why only server owners? In my eyes, that info can be relevant to anyone?

**Comment by schrej** [comment]
It can include possibly sensitive information, so I'd limit it to server owners (or subusers with full access) to make implementation easier.

**Comment by JustinRijsdijk** [comment]
> It can include possibly sensitive information, so I'd limit it to server owners (or subusers with full access) to make implementation easier.

good argument, I will narrow it down to sys-admins & server owners. eventually we can add a user vriew.

**Comment by JustinRijsdijk** [comment]
Also, for SFTP, do we want to log all file changes too?

**Comment by TristanWiley** [comment]
Would love to see this added

**Comment by JustinRijsdijk** [comment]
> Would love to see this added

I have made this for my own panel, but I won't bother creating a PR, due to the fact that there is a totally new panel coming up.

**Comment by FoksVHox** [comment]
> > Would love to see this added
> 
> I have made this for my own panel, but I won't bother creating a PR, due to the fact that there is a totally new panel coming up.

I mean, you should be able to make it with the beta, and then it _should_ be compatible with the final release of 1.0

**Comment by JustinRijsdijk** [comment]
> > > Would love to see this added
> > 
> > 
> > I have made this for my own panel, but I won't bother creating a PR, due to the fact that there is a totally new panel coming up.
> 
> I mean, you should be able to make it with the beta, and then it _should_ be compatible with the final release of 1.0

You are right here, though I don't have time to checkuot v1 alpha's/betas yet.

**Comment by ElijahRus250** [comment]
This could be a great feature. I may try to attempt this, I’ll keep it updated

**Comment by matthewpi** [comment]
> This could be a great feature. I may try to attempt this, I’ll keep it updated

When I build the react-admin I plan to do permissions and audit logs for the admin.  Doing audit logs on users should currently be possible and somewhat straight forward, but it won't be easy on servers as power actions and commands are done through the websocket which is not handled through the panel.

**Comment by Jcodeerd** [comment]
any updates?

**Comment by FoksVHox** [comment]
> any updates?

https://github.com/pterodactyl/panel/commit/ccecaa6694333d5758ddfff91c1a6cc933549674

**Comment by wolfier74** [comment]
This is really good idea

**Comment by broimsuperman** [comment]
Would love to see this added. Any ETA?

**Comment by matthewpi** [comment]
> Would love to see this added. Any ETA?

It is already partially implemented, actions are currently being logged to the database.  There is just no UI for it yet.

**Comment by snaildos** [comment]
Import backups??

**Comment by Tdash2** [comment]
> It is already partially implemented, actions are currently being logged to the database. There is just no UI for it yet.

I made a quick ui for it in the admin panel to show the database nothing fancy but it works. [https://github.com/Tdash2/Pterodactyl_audit_logs](https://github.com/Tdash2/Pterodactyl_audit_logs)

**Comment by Kowagirl** [comment]
The current implementation seems to log filesystem changes and backups, would love to see power actions (start/stop/restart/kill) and console command sending being logged.

**Comment by trenutoo** [comment]
> The current implementation seems to log filesystem changes and backups, would love to see power actions (start/stop/restart/kill) and console command sending being logged.

Refer to the messages above, e.g https://github.com/pterodactyl/panel/issues/1219#issuecomment-743314831

**Comment by Techout592** [comment]
Client-side audit logs would be nice for them to track what their sub-users are doing, as for the admin-side audit logs, it'd be nice to have it log deleted servers, modified servers, and any other administrative actions.

**Comment by DaneEveritt** [comment]
Added in 1.8.0 through multiple different commits. Not fully completely but the foundation pieces are there and this is effectively done for the sake of this ticket.
