### ISSUE TITLE
Deleting multiple files overflows the screen

### ISSUE THREAD

**Issue by casKd-dev** [pterodactyl/panel#1220]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: `0.7.7`
* Server's OS: `Ubuntu 16.04 LTS`
* Your Computer's OS & Browser: 
`Windows 7 Ultimate 64-bit SP1` 
`Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)`

**Describe the bug**
![image](https://user-images.githubusercontent.com/30688640/42089436-7186b46e-7b9d-11e8-8836-c5b934aca6ca.png)

Panel: PHP 7.2.7-1+ubuntu16.04.1+deb.sury.org+1.
Daemon: 
`Linux redxen 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
```
Containers: 15
 Running: 11
 Paused: 0
 Stopped: 4
Images: 80
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 274
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-128-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: redxen
ID: B2CP:P2KH:P45N:KUII:23U3:VQTK:TD3Z:G6HQ:LEXM:UFHZ:77FV:QT54
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**To Reproduce**
1. Select a server
2. Go to 'File manager'
3. Select more than 80 files
4. Select Mass Action and Delete

**Expected behavior**
![image](https://user-images.githubusercontent.com/30688640/42089760-f35b7294-7b9e-11e8-987f-70ba3afe87c3.png)

**Comment by schrej** [comment]
We are currently rewriting the user-frontend, this should get fixed in the process.

**Comment by DaneEveritt** [comment]
Fixed in the vue branch.
