### ISSUE TITLE
php artisan key:generate overwrites existing key with user interaction disabled

### ISSUE THREAD

**Issue by tenten8401** [pterodactyl/panel#1221]
Using panel 0.7.7, running `php artisan key:generate -n`, the key is overwritten even if it exists. I think it we should prevent from overwriting the key with user interaction disabled.
![image](https://user-images.githubusercontent.com/6174343/42101766-15880a1a-7b92-11e8-87eb-db7c5a787fd3.png)

**Comment by DaneEveritt** [comment]
That is working as intended.

**Comment by tenten8401** [comment]
Is there any way I can ensure there's a valid key in place with a script?

**Comment by DaneEveritt** [comment]
You could check if APP_ENV starts with base64: or whatever it is.

**Comment by tenten8401** [comment]
I guess that'd be the best option.
