### ISSUE TITLE
Decompression of file exited with code 2 signal null

### ISSUE THREAD

**Issue by juzhijian** [pterodactyl/panel#1228]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.5.6
* Server's OS: centos7
* Your Computer's OS & Browser: 

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
![qq 20180705050150](https://user-images.githubusercontent.com/14793250/42294006-8c319b86-8010-11e8-8654-8882baa45469.png)

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Comment by parkervcp** [comment]
Please fill out the information that was requested in when you were creating this issue.

I am interested to know what server you were installing as well.

**Comment by juzhijian** [comment]
I used a Packs ，is SpongeVanilla。
![qq 20180705051044](https://user-images.githubusercontent.com/14793250/42294221-cb524ad0-8011-11e8-836c-30a86b2bbe70.png)

**Comment by juzhijian** [comment]
I'm sorry I'm poor in English

**Comment by parkervcp** [comment]
This is a custom pack that you created then?

**Comment by juzhijian** [comment]
yes，

**Comment by parkervcp** [comment]
the archive you created is most likely the cause for this issue then. Please verify its integrity.

**Comment by juzhijian** [comment]
Can you give me a file? Let me test it.

**Comment by juzhijian** [comment]
![1](https://user-images.githubusercontent.com/14793250/42294566-8e4b2172-8014-11e8-9e88-dd401ee522cc.png)
This is the bag I made. I don't want to download when I install it

**Comment by Sergzy** [comment]
Add
``
callback => {
     this.server.setPermissions(callback);
},
``
after 
``
            callback => {
                this.checkCache(callback);
            },
``
in

> src/controllers/pack.js
