### ISSUE TITLE
Test Email button

### ISSUE THREAD

**Issue by DiscoveryOV** [pterodactyl/panel#1233]
**Is your feature request related to a problem? Please describe.**
When setting up mail, sometimes it can be somewhat complicated and irritating if things aren't working 100% properly; having a test button makes life easier. For instance, using a third-party mail service such as SendGrid and trying to work with their API key SMTP solution.

**Describe the solution you'd like**
On the mail settings page, I would like a "Send a test mail" button which would send an email using the configured (and saved) settings with test content.

**Describe alternatives you've considered**
Sending a forgot password email, but then you have to log out and complete a captcha. You could turn off the captcha, but again, this feature suggestion is about making life easier.

**Additional context**
nul

**Comment by DaneEveritt** [comment]
With this, would be nice to have some way of seeing if the queue worker and crons are setup and running. Not sure the best way to approach that check though.
