### ISSUE TITLE
Ability to change installation location for nodes after initial setup.

### ISSUE THREAD

**Issue by Yomanz** [pterodactyl/panel#1234]
When you set up a node you can choose where you would like to install the servers, `/srv/daemon-data` being the default but once setup you can't change the location.

**Comment by parkervcp** [comment]
You can technically do this already t just requires manual modification of the daemon config.

**Comment by Yomanz** [comment]
I noticed that but thought it might be nice to have it integrated into the panel.

**Comment by schrej** [comment]
No. If you need to move the servers it's really easy to change it. Just move the folder and change the daemon configuration to point to the new folder. It's not like you're switching the directory every week (I hope). For the occasional switch it's not worth the effort at all.
