### ISSUE TITLE
Server creation failed

### ISSUE THREAD

**Issue by Tutorialwork** [pterodactyl/panel#1235]
When I try to create a server I become this errors in the console.

https://image.prntscr.com/image/V2q_iAEoSUO4PBUXbvUjxQ.png

Installlog: https://cdn.discordapp.com/attachments/321366691525427210/468089681930616832/install.log

**Comment by DaneEveritt** [comment]
This is not a bug with Pterodactyl. Theres no errors anywhere in those logs, its just trying to install still and you weren't being patient.

**Comment by Tutorialwork** [comment]
And now? Even after several hours, the server is not installed. Also, yes in the log that the server has been blocked.

**Comment by parkervcp** [comment]
This still looks like the install is at fault here not a panel issue. What service are you installing?

**Comment by Tutorialwork** [comment]
I have try it with minecraft and teamspeak 3

**Comment by Tutorialwork** [comment]
And now what I can do to fix this?
