### ISSUE TITLE
Server creation failed

### ISSUE THREAD

**Issue by Tutorialwork** [pterodactyl/panel#1236]
When I want to create a server I become this message:

https://pastebin.com/MxL3ehpa

**Comment by lancepioch** [comment]
You need to post your panel logs.

**Comment by Tutorialwork** [comment]
Where can I find the log?

**Comment by DaneEveritt** [comment]
I'm guessing you set your webserver to redirect HTTP traffic to HTTPS and didn't update the URL in the daemon's core.json file to match, thus calls are being redirected. This causes the POST request to become a GET, and then throws a 405.
