### ISSUE TITLE
Daemon fails to accept changes for Maximum Web Upload Filesize

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1237]
* Panel or Daemon:  Both?
* Version of Panel/Daemon: Latest  0.7.9  / 0.5.6
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win 10 / Chrome

**Describe the bug**
Daemon -> `Linux hostname 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Attempting to update "Maximum Web Upload Filesize" in panel, Upon clicking save changes nothing actualy happens, and it failed to save the changes.

**To Reproduce**
1. Go to paneldomain.com/admin/nodes/view/1/settings
2. Edit "Maximum Web Upload Filesize" ( Something other then 100)
3. Click Save Changes
4. States "Node information has been updated. If any daemon settings were changed you will need to reboot it for those changes to take effect."
5. Restart daemon (systemctl restart wings)
6. Refresh Page -> Still 100MB limit.
**Expected behavior**

That the vaule would be updated. 

Note: /srv/daemon/logs/requests.log show the following when i click save changes and attempt to change the value.
https://hastebin.com/gifikukuze.json

I've tried this with two daemon installs, both Ubuntu 18.04

Note 2.0: 
Upon doing the following seems to work as i was able to upload a 200MB file..
1. Stop wings
2. Edit core.json ( size_limit: 250 ) -> Save
3. Start wings
But the settings page along with the file mangement page, for the selected server, fails to reflect the new value, they stay 100MB

**Comment by parkervcp** [comment]
Did you update the php file size limit in the nginx config as well?

**Comment by Sir3lit** [comment]
Are you referring to 
/etc/nginx/nginx.conf -> No upload size variable
/etc/ngina/site-available/pterodactyl.conf -> I changed -> client_max_body_size 250m;

According to phpinfo() in the core it is changed to 250m

**Comment by DaneEveritt** [comment]
The php file size does not apply here since its all over a socket and never touches PHP.

**Comment by Sir3lit** [comment]
Does changing the value in the SQL table for the nodes have an effect on anything?

**Comment by DaneEveritt** [comment]
Not really, no. You just need to manually update the core.json file as well for now.

**Comment by DaneEveritt** [comment]
They're different things. Theres already logic to update the config on the fly, it appears its just not working quite right for this.

**Comment by StealWonders** [comment]
Can confirm this error; tried changing the max upload size today and it didn't update even after changing the core.json
