### ISSUE TITLE
Daemon error when setting {{SERVER_IP}}

### ISSUE THREAD

**Issue by ClydeSheldon** [pterodactyl/panel#1239]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: Panel version v0.7 and Daemon v0.5.6  
* Server's OS: Ubuntu 16.04.4 LTS
* Your Computer's OS & Browser: Win 10 / Chrome

**Describe the bug**
When I change or install the server with "+ip {{SERVER_IP}}"  from "+ip 0.0.0.0" in the startup command for a CS:GO server then the server will not start and give the following error. 

`[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 0
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Aborting automatic reboot due to crash within the last 60 seconds.`

I have also tried to specify the IP address and still have the same issue. This error is making it unable to assign the game servers different IP addresses. I have added different ip addresses to the IP allocation for the node and each server in the panel appears to have the specified IP address however when I launch each server the Public IP set is the same.

**Default Startup Command:**
` ./srcds_run -game csgo -console -port {{SERVER_PORT}} +ip 0.0.0.0 +map {{SRCDS_MAP}} -strictportbind -norestart +sv_setsteamaccount {{STEAM_ACC}}`
Please provide additional information too, depending on what you have issues with:
Panel: PHP 7.2.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jun 22 2018 08:44:50) ( NTS )
Daemon:
 **uname -a:** Linux vps4 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**docker info:** 
`Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 3
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-130-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.855GiB
Name: vps4
ID: CO4S:OBBN:DQNT:V2MM:CNNX:GAOE:4RTM:YX6D:4HTK:DJQB:UH46:MAAT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
`

**To Reproduce**
1. Go to 'Servers'
2. Click on 'Server'
3. Click on 'Startup'
4. Change Startup command so that +ip 0.0.0.0 is +ip {{SERVER_IP}}
5. Click on 'Manage'
6. Rebuild Server Container
7. Start the Server
8. Error will show in console.

**Expected behavior**
Server will not start when the above changes are made to a Counter Strike: Global Offensive server.

**Edit**
Using different ports and same IP works such as x.x.x.x:27015 or x.x.x.x:27016 but when you assign the server different IP addreses from the allocation it assigns the same public IP in the console when the server is started.

**Comment by schrej** [comment]
You cannot use the actual server IP because inside of the docker container it doesn't exist. The port gets mapped to the selected IP by docker.
We know this is a problem with CS:GO servers because some server lists stuff, we don't have a good solution for it yet though. One possible option is to set the container networking to `host`, that disables all the networking related security features docker adds though.

**Comment by jondavis0787** [comment]
Same issue with Rust how can we use a secondary ip?
