### ISSUE TITLE
Status column in the node list

### ISSUE THREAD

**Issue by OrangeJuiced** [Pterodactyl/Panel#124]
In the node list, would it be possible to add a status column? Really useful I think, especially when having more than 1 node. (see screenshot for a very artistic representation of the idea: http://prntscr.com/cqnkjd).

**Comment by DaneEveritt** [comment]
Solely because of the artwork, I will do this.

@schrej I need your design skills.

**Comment by schrej** [comment]
@DaneEveritt i got you covered!
![screen](https://cloud.githubusercontent.com/assets/1710904/19168676/8710199c-8c11-11e6-8546-47e7f33ceee3.png)
