### ISSUE TITLE
Notes page with markdown support.

### ISSUE THREAD

**Issue by Valiantiam** [pterodactyl/panel#1240]
**Is your feature request related to a problem? Please describe.**
It's not an issue, however, the only place to put extended details for subusers/server managers is the description of the server you build for them. Too much info there can make the server list cluttered pretty quickly.

**Describe the solution you'd like**
A tab or section where the console page is, that would have extended notes that can be put their as configured either by...the egg, the admin, or even allow users/subusers to add additional notes there themselves too as a bonus. Perhaps tie in ability to edit custom notes in that area into the permissions system for "subusers"

**Describe alternatives you've considered**
Considered putting info in server description but I described issues with that above. Also considered manually adding content into pages for each server I spin up...but this would be a lot of repeat effort that could get overwritten with each update etc.

**Additional context**
![image](https://user-images.githubusercontent.com/5394853/43020265-11147df8-8c25-11e8-8b48-3cda0c5de303.png)
Referencing the above picture, Ideally this would either be a separate tab on the sidebar to the left, or even better, built in under mem/cpu usage as it's own block/cell. 

Even better yet, as described above, it would have a system admin or egg specific section that gets customized in the "Server configuration" page, and a section that can have additional custom notes added by subusers with correct permissions.

**Comment by DaneEveritt** [comment]
That type of thing should really be handled as an external service, such as a wiki page or shared document among the needed users. I won't be adding this to Pterodactyl.
