### ISSUE TITLE
Ability to filter the User & Admin server list

### ISSUE THREAD

**Issue by OrangeJuiced** [Pterodactyl/Panel#125]
Would be very useful to be able to filter these lists based on many things. For example:
- Owner
- Node
- Server Name
- Status
- Location
- Suspend status

**Comment by DaneEveritt** [comment]
Is this in the Admin CP or on the server listing page?

**Comment by OrangeJuiced** [comment]
These examples were mainly for in the Admin CP, but for the server listing page certain filters would also be useful I think. For instance: name, status.
