### ISSUE TITLE
Error 500 Since Updating and restarting server

### ISSUE THREAD

**Issue by WeatherSquad** [pterodactyl/panel#1251]
I have worked on several servers and they all now have this issue, any help much appreciated

{"name":"wings","hostname":"vmi181836.contaboserver.net","pid":18875,"server":"6a61e4ce-98bb-451e-af76-621b5b34f5cf","level":50,"err":{"message":"(HTTP code 500) server error - driver failed programming external connectivity on endpoint 6a61e4ce-98bb-451e-af76-621b5b34f5cf (90cde733a0fceb3e3a10a1e37539c1e04958cbb3c5ed4ba9d544ee9f81c23645):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d  <ipaddress> --dport 9101 -j DNAT --to-destination 172.18.0.4:9101 ! -i pterodactyl0:  (fork/exec /sbin/iptables: no such file or directory)) ","name":"Error","stack":"Error: (HTTP code 500) server error - driver failed programming external connectivity on endpoint 6a61e4ce-98bb-451e-af76-621b5b34f5cf (90cde733a0fceb3e3a10a1e37539c1e04958cbb3c5ed4ba9d544ee9f81c23645):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d <ipaddress> --dport 9101 -j DNAT --to-destination 172.18.0.4:9101 ! -i pterodactyl0:  (fork/exec /sbin/iptables: no such file or directory)) \n    at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17\n    at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)\n    at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)\n    at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"},"msg":"(HTTP code 500) server error - driver failed programming external connectivity on endpoint 6a61e4ce-98bb-451e-af76-621b5b34f5cf (90cde733a0fceb3e3a10a1e37539c1e04958cbb3c5ed4ba9d544ee9f81c23645):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d <ipaddress> --dport 9101 -j DNAT --to-destination 172.18.0.4:9101 ! -i pterodactyl0:  (fork/exec /sbin/iptables: no such file or directory)) ","time":"2018-07-22T17:32:17.816Z","v":0}

**Comment by parkervcp** [comment]
500 is a generic server error.

Can you please wrap the logs in ``` symbols or paste it somewhere like hastebin. It's impossible to read this way.

**Comment by WeatherSquad** [comment]
Supprisingly this is 1 line of the log file from the wings.log file

https://hastebin.com/agibabogaw.json

**Comment by DaneEveritt** [comment]
```
server error - driver failed programming external connectivity on endpoint 6a61e4ce-98bb-451e-af76-621b5b34f5cf (90cde733a0fceb3e3a10a1e37539c1e04958cbb3c5ed4ba9d544ee9f81c23645): (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d --dport 9101 -j DNAT --to-destination 172.18.0.4:9101 ! -i pterodactyl0: (fork/exec /sbin/iptables: no such file or directory))
```

You either uninstalled iptables or did something to modify them enough that docker is throwing a fit. Stop the daemon, restart docker, and then start the daemon again and it should be fine.
