### ISSUE TITLE
Data pack stucks server installation

### ISSUE THREAD

**Issue by n-valverde** [pterodactyl/panel#1252]
* Panel or Daemon:  Both
* Version of Panel/Daemon: Panel 0.7.9 / Wings 0.5.6
* Server's OS: Debian 9 KVM
* Your Computer's OS & Browser: Windows 10 / Firefox&Chrome

**Describe the bug**
I asked for help on Discord and Dane asked me to open an issue here.

My servers are getting stuck saying "installing" if I assign a data pack to it. I found a workaround by installing the server first without data pack, then assigning pack to it after.

https://hastebin.com/zobaqoroxu

* EDIT * :
Daemon logs : https://hastebin.com/yiriceduvo

**To Reproduce**
1. Create a data pack
2. Create a new server, with any egg
3. Assign the data pack to it before starting installation
4. Start installs and see server hanging on "installing"

**Expected behavior**
Data pack is supposed to be extracted on server, then install script runs.

Notes : 
- Ticking "Skip install script" does not help
- I created my tar.gz under Windows with 7-Zip
- I recently updated panel from 0.7.7 to 0.7.9, did not try data pack on 0.7.7
- I installed a theme on 0.7.7, can it break something ?
- The workaround I found is pretty strange as well, because if I assign the pack after install, then issue a reinstall, pack is still not there but server works. But if I then remove and assign again the pack, issue one more reinstall, and pack is finally there ! Oo
- The data pack I made is a bunch of folders with cfg files for csgo, and sourcemod/metamod plugins, for about 10Mb compressed.

I have searched for logs but did not find anything, will be happy to provide whatever you need.

**Comment by MrKaKisen** [comment]
I have the same issue - I'm running Debian 9 as well . Might this be related?

**Comment by parkervcp** [comment]
The daemon logs here are missing the actual logs.

**Comment by n-valverde** [comment]
You are right, I forget to relauch an install, I re-edited with actual logs, server is trying to install since 30min+ now.

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/daemon/commit/de86ca4b5ab49f30d10752f4c27b2c293a46bc54 and https://github.com/pterodactyl/daemon/commit/e7d02e87abb8fdd4c59e79078b736bbba898a616
