### ISSUE TITLE
File Manger mangles compressed files names

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1253]
**Background (please complete the following information):**
Panel or Daemon: Panel, Maybe Daemon
Version of Panel/Daemon: 0.7.9 / 0.5.6
Server's OS: Ubuntu 18.04
Your Computer's OS & Browser: Win10 / Chrome

**Describe the bug**
Panel: 7.2.7-Ubuntu0.18.04.2
Daemon: Linux Docker 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux & https://hastebin.com/axocaruyef.makefile

When compressing a folder via the file manager you can a random string on letters and number with the prefix of ptdlfm, File name turns into ptdlfm.TrZf1W3J.tar then inside of that tar is the same compressed file, then inside are the contents of the folder

File Tree

```
ptdlfm.TrZf1W3J.tar
├──ptdlfm.TrZf1W3J
   ├──Folder you compressed
      ├──Contents of folder
```

**To Reproduce**
1. Compress a folder via `File Manager`
2. Download it?

**Expected behavior**
The compressed file would be the name of the folder it compressed.

**Comment by DaneEveritt** [comment]
I don't see that inner folder when I create archives.

I've adjusted the compression name to make more sense though, it'll default to the name of whatever folder or file you're compressing followed by a short random string.

**Comment by DaneEveritt** [comment]
https://github.com/pterodactyl/daemon/commit/1a0b2e338b7169f2bfcc5f27faa934b6465908dd
