### ISSUE TITLE
Server Sticking in installation

### ISSUE THREAD

**Issue by WeatherSquad** [pterodactyl/panel#1254]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon:  0.7.9
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Describe the bug**
When a server is created and it auto installs, it installs all the files but stays locked in installing. please find the wings.log file attached

Please provide additional information too, depending on what you have issues with:
Panel: PHP 7.2.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jun 22 2018 08:44:50) ( NTS )

Daemon: Linux vmi181836.contaboserver.net 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-130-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 10
Total Memory: 49.14GiB
Name: vmi181836.contaboserver.net
ID: R36K:625Q:ADLL:V3CV:L44G:PA7Y:Q3SY:BBDF:ZBV2:YKP6:HWPL:FZBG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**To Reproduce**

**Expected behavior**
To unlock the installation after the files have been installed

![image](https://user-images.githubusercontent.com/25124064/43074834-869d9840-8e76-11e8-8336-a0fe6fcdf1b9.png)
[wings.log](https://github.com/pterodactyl/panel/files/2219152/wings.log)

**Comment by parkervcp** [comment]
Please join the discord and put .logs into support. This looks like something that should be handled there

From what I am seeing your web config is turning the daemon away with a 405.
