### ISSUE TITLE
RegEx Config Parser

### ISSUE THREAD

**Issue by mommalongnips** [pterodactyl/panel#1256]
Is it possible to have one of the types of configuration parsers to be regex? You enter in a regular expression and if it matches a certain part in the config then it would replace it what you specify. This would be nice for types of files that may have whitespace in them. 

As an example, 7 Days to Die has an XML config file. The server port value is:

`<property name="ServerPort"               value="26900"/>`

Using the "file" parser, its hard to compensate for the white space. RegEx would make this much easier.

`\s*<property name="ServerPort"\s*value="\d*"\/>` replace with `<property name="ServerPort" value="{{server.build.env.SERVER_PORT}}"/>`

EDIT: Github is too smart... there is lots of random amounts of whitespace in the config file between the property name and value. Github is taking it out of my XML

**Comment by lancepioch** [comment]
Instead of using regex to parse XML (or any markup language, [which is bad](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags)), instead it should be a real xml parser.

**Comment by schrej** [comment]
There is a real xml parser already, not sure how powerful he is though.
A regex parser would be useful though, some games might have a custom config format as well.

**Comment by DaneEveritt** [comment]
This is now possible, although undocumented. The example below should explain it fairly well.

```
{
    "config.yml": {
        "parser": "yaml",
        "find": {
            "listeners[0].query_enabled": true,
            "listeners[0].query_port": "{{server.build.default.port}}",
            "listeners[0].host": "0.0.0.0:{{server.build.default.port}}",
            "servers.*.address": {
                "regex:^(127\\.0\\.0\\.1|localhost)(:\\d{1,5})?$": "{{config.docker.interface}}$2"
            }
        }
    }
}
```
