### ISSUE TITLE
Error for missing .jar file

### ISSUE THREAD

**Issue by Silgica** [pterodactyl/panel#1266]
**Is your feature request related to a problem? Please describe.**
When there is no .jar file in the servers directory (Or the name entered in the startup parameters is wrong), the console doesn't tell the user that there's no .jar with the startup parameters name.
Instead, it shows this: 
https://hastebin.com/ixuyenolam.cs

**Describe the solution you'd like**
When there is no file, the console could just output "Could not find file server.jar. Review your startup parameters and check that the file exists, then try again" 

**Describe alternatives you've considered**
I looked in logs and couldn't find anything, but thought to check startup parameters and file presence anyway, however if someone has the wrong name entered for the jar, there may be issues.

**Additional context**
n/a

**Comment by parkervcp** [comment]
Minecraft is the only service that uses the executable name as a variable and thus this is the only service that would be able to really check for a startup file. Other servers would error out the same way if their executable files were removed.

**Comment by DaneEveritt** [comment]
This was fixed in https://github.com/pterodactyl/daemon/commit/1c84193aeaec3abb3069f0f071627b3035a55993
