### ISSUE TITLE
PHP cURL can't reach the host while the actual cURL works

### ISSUE THREAD

**Issue by BirkhoffLee** [pterodactyl/panel#1268]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Both latest
* Server's OS: CentOS 7
* Your Computer's OS & Browser: macOS, Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
```
PHP 7.2.8 (cli) (built: Jul 21 2018 08:09:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
```
Linux foobarbaz 4.9.112-32.el7.x86_64 #1 SMP Thu Jul 12 13:29:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 61
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.112-32.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.81GiB
Name: foobarbaz
ID: DVRL:4MQL:C47B:YSST:AJXD:RE5Z:SQE6:KMEL:MVYP:NQUV:G3Y2:BU3F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Both panel and daemon is containerized.

I get this while creating a server. Browser can correctly connect to the daemon (https://xxxx.xxxx.com:8443), but the panel won't

```
There was an exception while attempting to communicate with the daemon resulting in a HTTP/E_CONN_REFUSED response code. This exception has been logged.
``` 

This is the Laravel log:

```
[2018-08-05 18:03:19] production.WARNING: GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to xxxx.xxxx.com port 8443: Host is unreachable (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/pterodactyl/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
```

Upon seeing this I ran `curl https://xxxx.xxxx.com:8443` and everything works correctly:

```
$ curl https://xxxx.xxxx.com:8443
{
    "error": "Missing required X-Access-Token header."
}
```

**To Reproduce**

Create a server as you would

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

Server should create (i.e. panel should connect to daemon) successfully

**Comment by BirkhoffLee** [comment]
It's a problem at my side, I'll explain it later.

**Comment by BirkhoffLee** [comment]
Some backgrounds:
* Daemon's containerized
* Panel's containerized, using bridge network
* Strict firewall settings

Steps to fix:
1. Configure panel's containers to use default network settings, not bridge
2. Stop all containers, stop dockerd
3. Re-configure firewall to allow traffic, in this case, 8443/tcp
4. systemctl start docker
5. docker-compose up -d
6. voila

**Comment by AugieMucci** [comment]
Do you think you could explain your issue a little more in-depth? I seem to be having the same issue and the pterodactyl support team refuses to answer me.

**Comment by BirkhoffLee** [comment]
> Do you think you could explain your issue a little more in-depth? I seem to be having the same issue and the pterodactyl support team refuses to answer me.

It’s been two years, I’m not sure anymore. The dev team has always been like that.

**Comment by lancepioch** [comment]
This is a networking issue and not a code issue, you must have some minimum knowledge to get the panel working. This is noted in essentially the first paragraph of the Getting Started page of the docs.

Our team is constantly flooded with hundreds of messages every single day asking us for help, including lots of very basic software questions. We're sorry if we missed your messages, but we collectively spend hundreds if not thousands of hours every month and simply can't get to everybody.

**Comment by SGTGunner** [comment]
@AugieMucci Did you figure this out? I am curious about the issue too.

**Comment by wilarN** [comment]
Im having the same problem with pterodactyl and i would very much appriciate a reply
