### ISSUE TITLE
Upgraded from 0.5 to 0.6 can't see past console logs and execute command

### ISSUE THREAD

**Issue by xion87** [pterodactyl/panel#1269]
**Background (please complete the following information):**
* Panel or Daemon:  Daemon/Panel
* Version of Panel/Daemon: 0.6
* Server's OS:  ubuntu 16
* Your Computer's OS & Browser:  win10 chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon:
Linux ns3402613.ip-51-255-76.eu 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
I followed the istructions on https://pterodactyl.io/daemon/upgrade/0.5_to_0.6.html
I rebuilded all nodes and restarted only 2-3 server, in these server i can't see past logs and can't run any command
Running command trow this error on daemon:

```
{"name":"wings","hostname":"xxxxx","pid":355,"level":60,"err":{"message":"this.server.command is not a function","name":"TypeError","stack":"TypeError: this.server.command is not a function\n    at server.hasPermission (/srv/daemon/src/http/socket.js:66:33)\n    at Server.validatePermission (/srv/daemon/src/controllers/server.js:164:24)\n    at Server.hasPermission (/srv/daemon/src/controllers/server.js:156:25)\n    at Socket.activeSocket.on.data (/srv/daemon/src/http/socket.js:61:29)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at /srv/daemon/node_modules/socket.io/lib/socket.js:528:12\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"msg":"A fatal error occured during an operation.","time":"2018-08-06T08:34:12.592Z","v":0}```

**Comment by BirkhoffLee** [comment]
Can reproduce

**Comment by DaneEveritt** [comment]
So sorry, fixed in https://github.com/pterodactyl/daemon/commit/e1cc815461a482783a3ed47638c344367b39d263
