### ISSUE TITLE
Option to toggle crash behaviour

### ISSUE THREAD

**Issue by LeCodeCo** [pterodactyl/panel#1273]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v0.5.6
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 & Chrome Canary

**Describe the bug**
When a process ends, the daemon recognises the server as crashed even if the process exit code was successful.
Daemon: `Linux 01-discord 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` and https://file.properties/paste/hofeneyini

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a server with a file that stops its self after some time or task finishes.
2. Run the server.

**Expected behaviour**
If there is a successful exit code, the daemon should nicely mark the server as stopped.

This would help me display messages for users without them thinking there is an issue due to crash texts. This functionality could also be used to create that could automatically close after they have finished with whatever they needed to do and not have it automatically restart.

**Comment by DaneEveritt** [comment]
closed by https://github.com/pterodactyl/daemon/commit/ecfcfa9cd22f0f52d82ef9361bb21fa3bbe64a84

**Comment by xion87** [comment]
Hey @DaneEveritt you solved the bug partially, the server will not stuck in Online mode, but it stay in offline and need to be started manually

**Comment by DaneEveritt** [comment]
What?

**Comment by xion87** [comment]
wrong ticket sorry xD
