### ISSUE TITLE
Error with rebuilding CLI and not specifying a node

### ISSUE THREAD

**Issue by LeCodeCo** [pterodactyl/panel#1274]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.9
* Server's OS: Ubuntu 16.04.4 LTS
* Your Computer's OS & Browser: Windows 10 and Chrome Canary

**Describe the bug**
Using the CLI to rebuild only works per node and not for all nodes at one time.
Panel: `PHP 7.2.8-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul 25 2018 10:51:50) ( NTS )` (the PHP version in use).

**To Reproduce**
Steps to reproduce the behaviour:
1. Head to the Pterodactyl directory. 
2. Run `php artisan p:server:rebuild`.
3. See error `Unknown server defined in X-Access-Server header.`
4. Try running ` php artisan p:server:rebuild --node=8`
5. Works as intended

**Expected behaviour**
I expect not specifying a node to rebuild across all the nodes as stated in the [documentation here](https://pterodactyl.io/daemon/upgrade/0.5_to_0.6.html#rebuild-containers).

**Comment by DaneEveritt** [comment]
Can you please attach logs with the actual errors.

**Comment by LeCodeCo** [comment]
Here is an image of the error. 

![Error](https://file.properties/host/raw/NBSRQVMX.png "Error")

**Comment by DaneEveritt** [comment]
Do any of those servers actually exist on the Panel (and are unsuspended)?

**Comment by DaneEveritt** [comment]
This doesn't appear to be working incorrectly.
