### ISSUE TITLE
Panel stuck on "starting" & does not display anything in the server console.

### ISSUE THREAD

**Issue by 0xC1A551C** [pterodactyl/panel#1275]
**Background (please complete the following information):**
* Panel or Daemon: panel
* Version of Panel/Daemon: latest
* Server's OS: debian 9
* Your Computer's OS & Browser: firefox linux mint

**Describe the bug**
the server says "starting" and shows nothing in the console; however, the minecraft server is online & has been online for 24 hours. no problem I can login. this happened after updating to the latest version of the panel from the previous version. running minecraft spigot egg. happens to all my servers. worked prior to the upgrade. have rebooted the server.

**To Reproduce**
1. view the server panel page.

**Expected behavior**
should show started & display information in the console.

below is the result of it not working.

![image](https://user-images.githubusercontent.com/36227001/43937035-50c3d2c8-9c10-11e8-92ef-89898145d39d.png)

**Comment by parkervcp** [comment]
did you recently upgrade to the 0.6 daemon?

**Comment by 0xC1A551C** [comment]
i havent upgraded for around 3 months, so I forget what version that was originally

**Comment by MayhemGang** [comment]
Daemon version: 0.6.5

**Comment by MayhemGang** [comment]
I can start the server and the server works, I type commands into the console and they register in-game, but the console stays blank no matter what.

**Comment by parkervcp** [comment]
If you are having an issue @MayhemGang Please join discord and provide logs.
