### ISSUE TITLE
Deamon Upgrading to 0.6.4

### ISSUE THREAD

**Issue by Motovoh** [pterodactyl/panel#1277]
Hello i'm having a big issue with deamon i just upgrade it to newest version i didn't even touch the eggs
If you could help me to fix thep roblem please
![3](https://user-images.githubusercontent.com/34837966/43992062-f644c310-9d78-11e8-93e3-8f42410b213f.PNG)
![4](https://user-images.githubusercontent.com/34837966/43992063-f6665ffc-9d78-11e8-9922-98fec6477e06.PNG)
![5](https://user-images.githubusercontent.com/34837966/43992064-f6851514-9d78-11e8-97d1-a3b44ac45abd.PNG)
![45](https://user-images.githubusercontent.com/34837966/43992065-fb6edc5e-9d78-11e8-9811-31affb87a858.PNG)
![56](https://user-images.githubusercontent.com/34837966/43992066-fb8e712c-9d78-11e8-95aa-35381f540c5c.PNG)

**Comment by jacobgc** [comment]
There isn't anything running on port 8080 at pterodactyl.neon-hosting.us

**Comment by jacobgc** [comment]
Might be best to regenerate the config for the daemon and see if there is still an issue connecting.

**Comment by Silgica** [comment]
This is a support thing, not an issue with the Daemon or Panel.
To obtain a list of eggs on the panel for the Daemon to fetch, do the following:
`cd /var/www/pterodactyl
php artisan migrate --seed`
