### ISSUE TITLE
Daemon does not boot backup when restart happen that provided by plugins

### ISSUE THREAD

**Issue by JoeSGT** [pterodactyl/panel#1283]
**Background (please complete the following information):**
* Panel or Daemon:  
* Version of Panel/Daemon:
Panel: 0.7.9
Daemon: 0.6.4 
* Server's OS: Ubuntu16.04.4
* Your Computer's OS & Browser: 
I use Google Chrome for web browser

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
Linux Box2 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Hello i am using this https://github.com/ModdedMinecraft/MMCReboot
and the new daemon update cause it so it wont work, this is an issue for me because i have many type of plugins that restart the server is there a way to fix this? i had also tested with typing `restart` within the MC server console/ingame and daemon does not boot back up the server this only happen within the new daemon update is there going to fix ?

**Comment by Bl4ckSpr4y** [comment]
that is expected behavior, it was changed in daemon v0.6.3
![image](https://user-images.githubusercontent.com/25689030/44048070-02fbd190-9f39-11e8-94cf-2a2bf6fef245.png)

**Comment by JoeSGT** [comment]
This is a bad idea that has been changed because there are mini-games type plugins that run off of a server and have a built in restart system to clear a game once it's finished.

**Comment by parkervcp** [comment]
It was a bug that was fixed. If you use the panel api you can do all the things you want to do.

**Comment by parkervcp** [comment]
Relevant as always - https://xkcd.com/1172/

**Comment by JoeSGT** [comment]
Really? because i haven't seen any commit or releases on the Daemon github regarding of this issue.

**Comment by JoeSGT** [comment]
Also i do not use the panel api i do not even know how

**Comment by parkervcp** [comment]
Under changed - https://github.com/pterodactyl/daemon/releases/tag/v0.6.3

**Comment by JoeSGT** [comment]
But i am on Daemon 0.6.4 and still have the issue

**Comment by parkervcp** [comment]
That was changed in 0.6.3 to do the correct thing and make as stopped when the exit code was 0.

When a server shuts down correctly it doesn't detect as crashed.That is why it doesn't start back up.

**Comment by fabri2000779** [comment]
we have the same issue here, we are on the latest 6.4 also i reported that the scheduled task issue isnt fixed at all, at least not on our enviroment.

**Comment by Tony103** [comment]
Yeap i have the exact same issue as @JoeSGT  

@parkervcp you are right `When a server shuts down correctly it doesn't detect as crashed.That is why it doesn't start back up.`
but bare in mind that i cannot start up automatically my server that has Mini-games for Minecraft server

**Comment by JoeSGT** [comment]
But when the server doesn't detect as crash how am i even suppose to use my plugins that has a built in restart ? so your telling me to create a crash for it to automatically restart the way i want it

**Comment by parkervcp** [comment]
You should probably be using the API to start/stop servers then if this is so important.

this change should have been how it worked this entire time @Tony103

**Comment by Tony103** [comment]
Sure I'll use the panel api if you write the plugin since i do not know how to code one

**Comment by DaneEveritt** [comment]
This change was "reverted" in the most recent Daemon release `v0.6.5` with a configuration option that defaults to working how it was previously.

At some point down the road it will likely be flipped to treat ExitCode 0 as an expected stop but it won't just slip in. Sorry for the hassle, didn't expect that many people to be reliant on the crash detection like that.
