### ISSUE TITLE
502 Bad Gateway when creating new server and more

### ISSUE THREAD

**Issue by maartenhetworks** [pterodactyl/panel#1287]
**Background (please complete the following information):**
* Panel or Daemon:  Panel
* Version of Panel/Daemon: 0.7.7
* Server's OS: Ubuntu 16.04.2 LTS
* Your Computer's OS & Browser: Chrome

**Describe the bug**
When I create a new server I'm getting a 502 Bad Gateway error. Also when I save the node settings I'm getting the same error.

**To Reproduce**
1. Go to Admin Control Panel
2. Click on Create new server

**Expected behavior**
It should be creating a new server

**Comment by Sir3lit** [comment]
Are you in the discord?

**Comment by maartenhetworks** [comment]
Now I am

**Comment by Sir3lit** [comment]
Name?

**Comment by maartenhetworks** [comment]
maartenvr98#1526

**Comment by Sir3lit** [comment]
Go ahead and close this issue we'll help you in Discord.
