### ISSUE TITLE
npm fails to install daemon on Ubuntu 18.04 with node v10

### ISSUE THREAD

**Issue by masonr** [pterodactyl/panel#1289]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v0.6.5
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: N/A

**Describe the bug**
While following the daemon installation instructions, npm fails to install the daemon if using node v10 on Ubuntu 18.04 (may affect other OSes as well). See error below. Seems to fail while building mmmagic.

```
magic.target.mk:118: recipe for target 'Release/obj.target/magic/src/binding.o' failed
make: *** [Release/obj.target/magic/src/binding.o] Error 1
make: Leaving directory '/srv/daemon/node_modules/mmmagic/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.15.0-32-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/daemon/node_modules/mmmagic
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmmagic@0.4.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.4.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mrowe/.npm/_logs/2018-08-16T17_35_41_071Z-debug.log
```

Machine info:
Ubuntu 18.04.1 LTS
4.15.0-32-generic kernel
x86_64 OS

**To Reproduce**
1. Follow the [daemon instructions](https://pterodactyl.io/daemon/installing.html#installing-daemon-software) using an Ubuntu 18.04 system.
2. Install nodejs v10 instead of v8
3. After running the npm install command, the error output above will be shown.

**Expected behavior**
For npm install to exit cleanly, leaving the daemon installed

**Comment by Doc94** [comment]
In ubuntu 16.04 LTS with node 10 have the same issue, a pseudopatch you can donwgrade node to 8, using the daemon install documentation https://pterodactyl.io/daemon/installing.html

Im not secure if daemon support node 10.

**Comment by DiscoverSquishy** [comment]
I don't understand why would it not work with V10 if NodeJS are mostly all security patches? 
@Doc94 @masonr

**Comment by Doc94** [comment]
The issue is "c++" dependency in ubuntu, in ubuntu 16.04 the last version not is compatible with node10 (in my tests) in ubuntu 18.04 LTS with build-essential upgrade to the last version work correctly with node10 and the daemon build correctly.

PD: In the test i remove the package-lock i dont know if this change any.. but in my case i upgrade the c++.

**Comment by parkervcp** [comment]
From what I am reading then is Ubuntu 18.04 can run v8 or v10  when 16.04 is v8 only?

**Comment by DaneEveritt** [comment]
Seems like deleting the lock fixes this issue.

https://github.com/mscdex/mmmagic/issues/129

Will commit a fixed lock.

**Comment by zKoz210** [comment]
@DaneEveritt I removed the package-lock.json, but it didn't help me. CentOS 7
```
make: *** [Release/obj.target/magic/src/binding.o] Error 1
make: Leaving directory `/srv/daemon/node_modules/mmmagic/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.10.0-862.14.4.el7.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/daemon/node_modules/mmmagic
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! not ok 
unbuild mmmagic@0.5.2
npm ERR! weird error 1
```

**Comment by DaneEveritt** [comment]
`node -v v0.10.13`
