### ISSUE TITLE
Backup function

### ISSUE THREAD

**Issue by outtimes** [pterodactyl/panel#1291]
**Is your feature request related to a problem? Please describe.**
I want to get backup everyday in 3:00 AM.

**Describe the solution you'd like**
Add a choose in panel,and we can setting whether or not to backup in 3:00 AM.
And if they do,the daemon will backup the server files in 3:00 AM in to backup folder.
Users can go back to the backup.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by hariaakash** [comment]
Duplicate of #114
