### ISSUE TITLE
Error when creating server

### ISSUE THREAD

**Issue by mesl** [pterodactyl/panel#1293]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: Both latest 
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 / Chrome 

**Describe the bug**
When i try to create a server via the panel i get an error message:

16:10:18.120Z  INFO wings: + ------------------------------------ +
16:10:18.121Z  INFO wings: | Running Pterodactyl Daemon v0.6.5    |
16:10:18.121Z  INFO wings: |        https://pterodactyl.io        |
16:10:18.121Z  INFO wings: |  Copyright 2015 - 2018 Dane Everitt  |
16:10:18.121Z  INFO wings: + ------------------------------------ +
16:10:18.121Z  INFO wings: Loading modules, this could take a few seconds.
16:10:18.329Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
16:10:18.370Z  INFO wings: Configuring user pterodactyl (id: 999) as the owner of all server files.
16:10:18.372Z  INFO wings: Configuring timezone file location...
16:10:18.372Z  INFO wings: Checking container networking environment...
16:10:18.377Z  INFO wings: Found network interface for daemon: pterodactyl_nw
16:10:18.377Z  INFO wings: Ensuring correct network interface for containers...
16:10:18.382Z  INFO wings: Networking gateway detected as 172.18.0.1 for interface: pterodactyl0.
16:10:18.384Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
16:10:18.396Z  INFO wings: Checking existing eggs against Panel response...
16:10:18.397Z  INFO wings: Beginning server initialization process.
16:10:18.398Z  INFO wings: Configuring websocket for daemon stats...
16:10:18.399Z  INFO wings: Configuring internal SFTP server...
16:10:18.408Z  INFO wings: Pterodactyl Daemon is up-to-date!
16:10:18.408Z  INFO wings: Pterodactyl Daemon is now listening for insecure connections on 0.0.0.0:8080
16:13:21.452Z  WARN wings: Container was not found. Attempting to recreate it. (server=c72aeb4b-e368-48b8-80c5-53b773e7f240)
16:13:21.453Z  INFO wings: Checking if we need to update image quay.io/pterodactyl/core:java, if so it will happen now.
16:13:22.747Z  INFO wings: Pulling image quay.io/pterodactyl/core:java ... this could take a few minutes.
16:13:22.858Z FATAL wings: A fatal error was encountered while attempting to create a server.
    Error: (HTTP code 400) unexpected - invalid mount config for type "bind": bind source path does not exist
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
16:13:22.866Z  INFO wings: Server deleted. (server=c72aeb4b-e368-48b8-80c5-53b773e7f240)
16:13:22.885Z  INFO wings: Notified remote panel of server install status.

**To Reproduce**
1. Set swapaccount=1
2. Install both the latest version of the Daemon and Panel
3. Configure the Daemon with the configuration of the panel
4. Start both the Daemon and the Panel
5. Create a server
6. See the error in the log

**Expected behavior**
The server is created. etc

The server does download the container but doesn't start it

Output of docker info:

Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/snap/docker/common/var-lib-docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-32-generic
Operating System: Ubuntu Core 16
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.8GiB
Name: mining-station
ID: D22U:LVNX:5SR4:ZPBX:JBUR:M6U4:Z5S4:TWEA:6A3O:X34T:NFEX:VB4M
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2018-08-20T21:24:10.895854262Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Hope you can help,

Kind regards,
Merlyn van der Sluis

**Comment by parkervcp** [comment]
This looks like an IP binding issue. Basically you are trying to us an IP that's not available.

**Comment by mesl** [comment]
Thanks for your answer, I've just fixed it by manually installing docker (from 17.06.2 to 18.06.0)

Kind regards,
Merlyn van der Sluis
