### ISSUE TITLE
Sortable/Modifyable Columns (Feature Request): ex. Hide/remove ID from "Configured Nests" page

### ISSUE THREAD

**Issue by xyeLz** [pterodactyl/panel#1294]
I'd much prefer this be sorted alphabetically than by ID since the ID is practically irrelevant to the admin (at least I haven't found a reason to care for it).

**Comment by DaneEveritt** [comment]
It is very relevant when people are trying to work with the API. I don't know of anyone with enough nests on one page to require sorting, if anything a quick code change would be able to address that one.

Basically what I'm trying to say is with the current backlog of things that need to happen, I doubt I'll ever get around to adding in sortable columns on the nests page (or most of the admin area at this point). Appreciate the suggestion though.

**Comment by parkervcp** [comment]
As the guy who probably has more nests than anyone I want to keep the ID around but sorting by name would be easier than by ID.

**Comment by DaneEveritt** [comment]
Maybe I should reopen this and just make it to have them default to sorted by name and not ID?

**Comment by xyeLz** [comment]
That would be a reasonable compromise in the short-term. I may not even be using nests/eggs as they were intended, as generally I have a top-level nest for the game, and then beneath that I keep different version or mods of a particular game. Example:

Nest: Call of Duty
Egg: Call of Duty 1.1
Egg: Call of Duty 1.5
Egg: Call of Duty: United Offensive

However, other areas of the panel would seriously benefit from sortable columns. For example, Users/Locations/Databases, etc. It may be more worth your immediate time to implement other features and resolve outstanding issues, but I do think it would be beneficial for the community to implement a sortable column system for most of these pages.

**Comment by matthewpi** [comment]
Implemented in react-admin.
