### ISSUE TITLE
Inifinity symbol not resolved as character

### ISSUE THREAD

**Issue by j0nnib0y** [pterodactyl/panel#1297]
On the server list, the picture should make it self-explaining: ![Picture](https://lh3.googleusercontent.com/gLWubQn-ASroXuTc4vYzL5V5g9PhZRbnkTtfdb8kYyZHuHklqV5QcunXIo6-pIEM4oMo4Qc=s159)

**Comment by Bl4ckSpr4y** [comment]
already fixed in #1260

**Comment by j0nnib0y** [comment]
Crap, didn't find it
