### ISSUE TITLE
Optional main allocation/port

### ISSUE THREAD

**Issue by j0nnib0y** [pterodactyl/panel#1300]
I want to run services which do not need to bind to a specific port. They just need internet access. This is not possible right now without a dummy port or running multiple services in one container.

Examples for services which do not need a port to bind on:
- xAseco/UASECO, server controller for Trackmania and Maniaplanet servers
- Teamspeak 3 Bots
- scripts which fetch statistics, e.g. gameserver stats like number of players over time
- probably a lot more simple RCON- or API- based tools

**Comment by parkervcp** [comment]
Seems related to #1001 honestly.

**Comment by DaneEveritt** [comment]
Closing for #1001
