### ISSUE TITLE
Autorestart on crash was removed with 0.6.x daemon

### ISSUE THREAD

**Issue by xion87** [pterodactyl/panel#1302]
**Background (please complete the following information):**
* Panel or Daemon:  Both
* Version of Panel/Daemon:  0.7.9/0.6.5
* Server's OS: Ubuntu 16
* Your Computer's OS & Browser: Chrome

**Describe the bug**
When a minecraft server it crash, the server will stay marked as "online" without autorestarting

**To Reproduce**
Server crash, no marked as offline or restart

**Expected behavior**
The server should autorestart like on 0.5.x happen, it was usefull for me...and many other

**Comment by DaneEveritt** [comment]
It already auto-restarts. You need to provide actual daemon logs if you want me to look into this more, I'm guessing your server crashed twice in a row.
