### ISSUE TITLE
Error at server starts

### ISSUE THREAD

**Issue by lucasdidur** [pterodactyl/panel#1304]
**Background (please complete the following information):**
* Panel or Daemon: Last
* Version of Panel/Daemon: Last 
* Server's OS: Ubuntu

When I start the daemon, I got this error: 

https://pastebin.com/28hK2GLA

**Comment by matthewpi** [comment]
There is something already listening on port 2022.

Do you have a daemon already running?
Is there another service using that port?

This is not a issue with the software, help with stuff like this belongs in the Pterodactyl Discord.

**Comment by lucasdidur** [comment]
I had already asked for help with this problem, but no one helped me.

**Comment by matthewpi** [comment]
Then wait for someone to help?  No one is obligated to help you and this is an issue that could easily been solved by yourself if you read the error.
