### ISSUE TITLE
Multiuser for servers

### ISSUE THREAD

**Issue by MADS0LADEN** [pterodactyl/panel#1305]
**Is your feature request related to a problem? Please describe.**
Its not a problem, it would just be nice to assign multible owners to the same server

**Describe the solution you'd like**
Something like being able to assign more than one owner to a server, or just some sort of permission system where you can add administrators, i know the sub accounts is available but i think thats alot of work if you have for example a network of minecraft servers and want admins to control 5 servers.

**Describe alternatives you've considered**
The use of sub accounts is the only version that works, just not nicely when you have to create 5 exactly the same users under every single server.

// Mads :)

**Comment by schrej** [comment]
We are currently working on a new permissions system that should be flexible enough to allow that.

**Comment by myxxmikeyxx** [comment]
@schrej any update on this?

**Comment by RealKomander** [comment]
Has this feature been added?
