### ISSUE TITLE
The console server output contains extra spaces

### ISSUE THREAD

**Issue by xion87** [pterodactyl/panel#1307]
Background (please complete the following information):

Panel or Daemon: Both
Version of Panel/Daemon: 0.7.10/0.6.5
Server's OS: Ubuntu 16
Your Computer's OS & Browser: Chrome
Describe the bug
The console after the update it look with spaces lines and ">"
![image](https://user-images.githubusercontent.com/3611852/45138833-294ae480-b1ae-11e8-8202-7e87df36c841.png)

To Reproduce
I upgraded from 0.7.9 to 0.7.10, not sure if was a daemon fault or panel. There are no errors in logs on both daemon/panel. I see other user on discord facing the same issue after the update

Expected behavior
the console must be without spaces

**Comment by JanDevDE** [comment]
As I already mentioned in discord this could be the cause:

https://cdn.discordapp.com/attachments/272117330207571969/486904492231622676/unknown.png

**Comment by JanDevDE** [comment]
More information from other users:
- Only occurs in Chrome, not in Firefox

**Comment by xion87** [comment]
it occours also on firefox for me

**Comment by JanDevDE** [comment]
Hmm ... okay.

**Comment by parkervcp** [comment]
Which game server is this for?

**Comment by xion87** [comment]
minecraft and waterfall

**Comment by parkervcp** [comment]
minecraft as in vanilla or spigot/paperclip?

**Comment by xion87** [comment]
paperspigot

**Comment by parkervcp** [comment]
Downloaded the latest paperclip build and it runs fine.

**Comment by xion87** [comment]
it happened exact with the latest panel update... :(

**Comment by xion87** [comment]
Is werd, all my console 1.8-1.12.2 are fucked except one 1.7.10 with FTB forge....

**Comment by parkervcp** [comment]
Let me update my panel to verify.

**Comment by parkervcp** [comment]
In panel versions  0.7.9 and 0.7.10 on daemon version 0.5.6 and 0.6.5 I have no issues with this happening.

Paper build 1559

**Comment by SecretlyJealous** [comment]
This is definitely an issue but I have no idea what the cause is, I never had this problem on 0.7.9 though. There are other people who have complained about this issue on discord but no answer on fixing the issue so it does seem to be affecting people:
![untitled](https://user-images.githubusercontent.com/10485646/45422603-9b2c9d80-b688-11e8-8c81-ca47107a413a.png)

![untitled](https://user-images.githubusercontent.com/10485646/45422627-b0a1c780-b688-11e8-958e-e7058b7d772d.png)



It's happening to me too, in the screenshot you can see that I'm using paper build 1559.
Panel version: 0.7.10
Daemon version: 0.6.5
![untitled](https://user-images.githubusercontent.com/10485646/45422559-77695780-b688-11e8-8945-b59cf2da55ff.png)

**Comment by parkervcp** [comment]
I'm not saying it's not an issue, just that I am not seeing it.

**Comment by parkervcp** [comment]
I am not seeing this with a newly installed FTB server but it is the only one I see it on.

**Comment by xion87** [comment]
try to rebuild the container on all server now

**Comment by parkervcp** [comment]
I assume it's something to do with the way spigot/modded servers do text. I will look into this more when I can.

**Comment by mjmalec** [comment]
My servers replicates the same thing.

**Comment by LoYungSum** [comment]
Me too here. All spigot version (build from buildtools). Latest panel version. 0.7.10

**Comment by schrej** [comment]
What version of docker are you using?

**Comment by parkervcp** [comment]
I have 18.03.0-ce on CentOS 7.4 with kernel 3.10.0-693.17.1.el7.x86_64

This is on my server running the daemon 0.6.5 in a docker container on node 8.

**Comment by DaneEveritt** [comment]
Has anyone tried just removing that CSS that was added for whitespace handling? I'll look into this eventually, but its by no means a priority for me right now seeing as its just a UI issue.

**Comment by mjmalec** [comment]
Is this CSS mentioned the one you’re speaking of? https://cdn.discordapp.com/attachments/272117330207571969/486904492231622676/unknown.png

**Comment by parkervcp** [comment]
that does look to fix it.

**Comment by mjmalec** [comment]
I’ll give her a quick test.

**Comment by mjmalec** [comment]
I'm not seeming to be disabling that at all. Clearing cache on both my end and Cloudflare's no changes.

**Comment by xion87** [comment]
deleting that line and clear and cache and stuff the console now is beauty again :)
