### ISSUE TITLE
[pre.2] Decompress - wrong file permission 

### ISSUE THREAD

**Issue by Nbushkov** [Pterodactyl/Panel#132]
1. Upload zip from file manager (archive contains spigot server)
2. Decompress from file manager
3. Connect SFTP - on decompress file and folder - edit -Permission denied

**Comment by DaneEveritt** [comment]
closed in https://github.com/Pterodactyl/Daemon/commit/92df35cbf2c8b3a27958dd1797e2ff6fdac7d079
