### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by Games4k** [pterodactyl/panel#1321]
Hello. It looks like no of my servers cant connect to mysql. We setted up mysql and everything else, and database is getting created properly, but all of server cant connect to any of them. I also tried to make MY OWN DATABASE on main database, but it does not connect to it. It looks like servers on pterodactyl cant connect to any of databases, even cant connect to main base, but if I try running server out of pterodactyl, it works and it connects. I asked on discord, but no one seems to be active or helping me out.

Please help me here or on Discord (OpenSource#3310)

![image](https://user-images.githubusercontent.com/29690431/45356315-3c512080-b5c3-11e8-9fce-be9643b92e38.png)

![image](https://user-images.githubusercontent.com/29690431/45356334-470bb580-b5c3-11e8-992a-c8f68a6c6a3f.png)

Thanks!

**Comment by parkervcp** [comment]
If you want discord help please join our discord server.

Also you can't use 127.0.0.1 as a server IP to connect to a MySQL server from the game server

**Comment by giopalma** [comment]
I have the same problem also using docker0 IP (172.17.0.1)
I tried to get help on Discord, but no one helped me.

**Comment by parkervcp** [comment]
The docker ip should be 172.18.0.1

**Comment by Truyn** [comment]
> I have the same problem also using docker0 IP (172.17.0.1)
> I tried to get help on Discord, but no one helped me.

Bro, How did you fix this mistake
