### ISSUE TITLE
Zeroconf Daemon/Configure daemon in panel.

### ISSUE THREAD

**Issue by ccarney16** [pterodactyl/panel#1323]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem, but would be a way to simplify deployments to nodes.

**Describe the solution you'd like**
I think moving towards a "zeroconf" daemon configuration would be a really good way to simplify the daemon setup along with making sure that the configuration stays within the panel. So rather than downloading the config for the daemon, I would run `npm start -- --auth=<token> --url="https://example.com/"`.

**Comment by blastehh** [comment]
You can literally generate a token from your panel to do exactly as you described.

**Comment by ccarney16** [comment]
I mean upon every start to clarify, to dynamically get an updated config.

**Comment by Yomanz** [comment]
The current system that the daemon uses for configs requires a one time setup unless you want to change any settings in the config which is easily doable, as far as I can see there is no major advantage to a zeroconf system with the daemon since the config isn't something that needs to be edited every minute or urgently to fix anything that might arise.

**Comment by Yomanz** [comment]
Still not the worst idea I've seen on here though.

**Comment by tenten8401** [comment]
I could see it paving the way towards node->node server migrations, that way a daemon can just pull the config from the panel

**Comment by parkervcp** [comment]
Egg configs are only grabbed on server startup.

**Comment by schrej** [comment]
With the new daemon we are planning to fetch much more configuration from the panel, or have the panel send it with requests proactively. Especially stuff like eggs and configuration for single servers should be updated much more frequently.
Also stuff like daemon logs in the panel and maybe even remote restarting of the daemon is on the imaginary list.

**Comment by DaneEveritt** [comment]
Closing this out as daemon deployment is a one-line configuration command to fetch everything it needs from the Panel and doesn't require a specially generated token (any application API key with node read access will do).
