### ISSUE TITLE
Change Server ID (able to change server position)

### ISSUE THREAD

**Issue by DeCarvalho83** [pterodactyl/panel#1324]
**Is your feature request related to a problem? Please describe.**

-Isnt related -
When i 1st create the servers i didnt notice that i couldnt change its position in the servers panel.
Dunno if it my OCD but whenever i look the server's list and i see they in the wrong order it makes me feel weird and the fact that i cant change the server's order in the list makes me feel worse..

**Describe the solution you'd like**

-Since it isnt related to a problem, theres none-
But id like to be able to change the server ID, CodeCo told me that i cant do it directly by changing the PteroDatabase due the fact that 
> Users, allocations and more refer to the ID of servers.
So id like to have an option to change servers position as i want.

**Describe alternatives you've considered**
-I dont have any-

**Additional context**

The Link below is from ptero discord where i shared my list of servers and its ids from ptero database..
https://cdn.discordapp.com/attachments/122903114423599104/489562307790110731/unknown.png

Would be amazing being able, in some way, to change the order there.. like.. i want to change lobby to make it the second server in the list.. We could have an option inside the ptero panel to change it instead being able but having to change it directly from database..

**Comment by DaneEveritt** [comment]
There are multiple other open requests for server organization features.
