### ISSUE TITLE
Possible incompatibilities with MariaDB-Distributions on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by MarkL4YG** [pterodactyl/panel#1325]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel: v0.7.10
* Server's OS: Ubuntu 16.04.4 LTS

**Describe the bug**
When deleting a database the panel invokes the ``DROP USER IF EXISTS`` query.  
This may fail on most Ubuntu 16.04 distributions running the MySQL derivative MariaDB which is fairly commonly used.  
As [stated by the MariaDB documentation](https://mariadb.com/kb/en/library/drop-user/#if-exists) the ``IF EXISTS`` is supported in ``DROP USER`` since ``mariadb-server`` version ``10.1.3``.  
However, as of writing this issue, the Ubuntu package repositories for ``16.04`` LTS [only deliver ``mariadb-server 10.0.36``](https://packages.ubuntu.com/search?keywords=mariadb-server).  
Therefore the statement fails with a syntax error.  

**To Reproduce**
1. Register a database host.
2. Create a database in any server using the built-in panel functionality.
3. Try to delete that database (or even the server as this triggers the database removal too).

**Expected behavior**
The database should be deleted without an error.

**Comment**  
As this is an issue particularly involving MariaDB, I would not say that Pterodactyl has the responsibility to work around this limitation but I wanted to make sure people are aware of this.  
Therefore, this issue can be closed without having to be resolved.

**Comment by Bl4ckSpr4y** [comment]
![image](https://user-images.githubusercontent.com/25689030/45504731-53466d00-b793-11e8-849e-8b8c6ed2dc3d.png) @MarkL4YG The panel documentation says that MariaDB must be 10.1.3 or higher, and the docs even give a command to run the mariadb_repo_setup script from mariadb.com

**Comment by parkervcp** [comment]
Please update to using the mariadb repo to get the newer releases.

**Comment by MarkL4YG** [comment]
Oh, it appears that I have not been up to date with the panel docs then. I've read them a month or two ago and did not have such a warning in mind.  
I'm sorry for the obviously redundant issue in that case.
