### ISSUE TITLE
The ability to decompress rar files

### ISSUE THREAD

**Issue by mattmalec** [pterodactyl/panel#1326]
A good amount of my hosting customers use rar files their main way of compressing files.
Usually, they go ahead and attempt to upload them to the server. When they try to decompress them and it doesn’t work, customers email my support staff frustrated that they’re unable to decompress such a popular format.

If the panel had the ability to decompress rar files, it would make larger file transfers easier than using a zip file. Although zips are common, so are rars. You could easially use a zip, but at the end of the day, it really provides piece of mind that you have the option.

*tried following the format the best i could*

**Comment by parkervcp** [comment]
tar is easier in linux than rar as it's a standard lib. It's not common on Windows though.

Zip is one of those universal libraries that makes it easy to see why it is needed.

**Comment by mjmalec** [comment]
Makes sense. A lot of people ask why that rars aren’t supported. So I thought I’d ask and see if it’s possible to add or just not plausible.

**Comment by parkervcp** [comment]
I was commenting on why zips were the first choice. I can talk to Dane about rars

**Comment by mjmalec** [comment]
Good idea. I appreciate the swift reply.

**Comment by KewaiiGamer** [comment]
#1340

**Comment by DaneEveritt** [comment]
Implemented at some point in the beta builds, thanks @matthewpi
