### ISSUE TITLE
Google Analytics Input

### ISSUE THREAD

**Issue by LeCodeCo** [pterodactyl/panel#1331]
**Is your feature request related to a problem? Please describe.**
Well, after every Pterodactyl update, I have to go about editing templates to install Google Analytics to get some statistics on panel usage, etc.

**Describe the solution you'd like**
I think adding a Google Analytics code input box on settings area which adds an analytics script if there's an analytics tracking code put within it, and if the input is blank, the script is not rendered on the page to speed loading time.

**Describe alternatives you've considered**
Editing a template after updates is doable but I think this small feature could be very useful to quite a few people without affecting any core functionality of the panel.

**Additional context**
Here's a screenshot of what this could look like to configure. https://file.properties/host/fZZPtdKH.png

**Comment by matthewpi** [comment]
Instead of adding an input to the panel it should go in the `.env`.

**Comment by schrej** [comment]
Maybe we should just add the option to add additional stuff to the end of the header, would also allow to add other scripts or CSS

**Comment by refeele** [comment]
any updates on this?

**Comment by DaneEveritt** [comment]
When there are updates they will show up in this issue. :)

**Comment by Sir3lit** [comment]
Was looking into this for Pterodactyl 1.0, Seems mostly easy to add, got it hacked together by using `react-ga` module 
![image](https://user-images.githubusercontent.com/1757840/80279223-0db98800-86ca-11ea-8b43-927ee344230e.png)

As my react knowledge is very limited, ill see what I can do.
