### ISSUE TITLE
Pagination in the user panel not configurable

### ISSUE THREAD

**Issue by Raideerke** [pterodactyl/panel#1335]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.10, actually the latest
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Chrome, latest

**Describe the bug**
Panel: PHP 7.2.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Aug 19 2018 07:16:12) ( NTS )
I configured the 
```
    'paginate' => [
        'frontend' => [
            'servers' => env('APP_PAGINATE_FRONT_SERVERS', 99),
```
and the 
```
        'admin' => [
            'servers' => env('APP_PAGINATE_ADMIN_SERVERS', 99),
```

options in the config/pterodactyl.php file. The admin panel working, all the servers are shown in one page, but in the client-side panel, not.

**To Reproduce**
1. Configure the options i wrote bellow in the config/pterodactyl.php file where the panel site is located
2. Clear all the cache with 
php artisan down
php artisan cache:clear
php artisan view:clear
php artisan config:clear
php artisan up
3. Delete all the browser cache, i even tried an another browser
4. And see that only the admin panel changes as you configured, the client panel is not.

**Expected behavior**
I wanted to see it also working in the client panel, not only in the admin panel.

**Comment by parkervcp** [comment]
Maybe it's this line you are looking for - https://github.com/pterodactyl/panel/blob/ad9ed5ea0049e9fd267648b5cafddd3b7123a6f5/config/pterodactyl.php#L55

**Comment by Raideerke** [comment]
Now read what i already wrote bellow. I already mentioned that set that option to 99 (read again what i wrote). For me only the admin panel shows the servers in one page, the client panel is not.

**Comment by Raideerke** [comment]
Seems like no matter how i change this value, anything happens.
If i change the admin frontend section, it changes as well. That's why i don't understand.

**Comment by MarkL4YG** [comment]
I remember running into the same thing. One of the two (user or admin panel) lists has hard-coded pagination ignoring its setting. Not sure which one I patched though.
