### ISSUE TITLE
Including phpMyAdmin

### ISSUE THREAD

**Issue by LeCodeCo** [pterodactyl/panel#1336]
**Is your feature request related to a problem? Please describe.**
Not necessarily. I feel like this could simply enhance the user experience for the panel slightly.
Currently, there is no way for a user to view within the MySQL database without using local or external software which may be a complication for some.

**Describe the solution you'd like**
I think that if phpMyAdmin was able to be deployed with Pterodactyl, users could click phpMyAdmin on the databases page to automatically sign in to pma and view it, straight from the website. 

**Describe alternatives you've considered**
Manually installing phpMyAdmin at a directory such as /public/php/ works just fine as it simply requires a small change in the virtual host but cannot log in automatically.

**Additional context**
These two pages could be useful.
https://docs.phpmyadmin.net/en/latest/vendors.html
http://howtolamp.com/lamp/phpmyadmin/4.2/authentication-modes/

Here's a mockup. https://file.properties/host/PLjqHQOk.png

**Comment by parkervcp** [comment]
Installing phpmyadmin is easy. Build an integration on your own.
