### ISSUE TITLE
API endpoint for retrieving a servers status information.

### ISSUE THREAD

**Issue by MarkL4YG** [pterodactyl/panel#1337]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible for applications authorized via Bearer keys to get information on a servers status.  
Endpoint: ``/status/<server-short-uuid>``

**Describe the solution you'd like**
I would like to be able to query the status information on a server using a simple ``GET`` request.

**Describe alternatives you've considered**
I did not consider any alternatives.  
I could however think about asking the daemon directly but believe that this would be unnecessarily complicated and would bypass any control mechanism the panel may have in place.  
  
I tried adding the middleware to ``web`` which worked for the application but in turn disables all other authorization mechanisms as it directly throws an exception when no Bearer key has been found.

**Additional context**
``null``

**Comment by DaneEveritt** [comment]
This information is already returned by the server utilization endpoint, `/api/client/servers/{server}/utilization`

**Comment by MarkL4YG** [comment]
Nice, that works! Thank you very much ^^
