### ISSUE TITLE
Move a Folder with a lot of files using daemon SFTP will cause lag to server

### ISSUE THREAD

**Issue by xion87** [pterodactyl/panel#1341]
Panel or Daemon: Both
Version of Panel/Daemon: 0.7.10/0.6.5
Server's OS: Ubuntu 16
Your Computer's OS & Browser: Chrome
Describe the bug
I noticed when you move folder with a lot of data using SFTP sometimes it cause a lot of lag on all minecraft server and some disconect, this never happened if using normal sftp (no daemon), a example i moved a folder of a minecraft world from /worlds/myworld to /myworld, and it was big 5 gb, when i do that by using daemon sftp it stucked for like 5 mins and then after it, my server half crashed and it moved that folder, i never have this issue using the normal sftp (no daemon)
And yeah i got my latest log, but the daemon log nothing when it happened-
I used Winscp, but i think more is a daemon issue
https://hastebin.com/azofeyiqub

**Comment by xion87** [comment]
Happened again, i just deleted a folder from the panel, it crashed half minecraft server (kick out all players)

**Comment by dtandersen** [comment]
Maybe rate limit?

**Comment by DaneEveritt** [comment]
Won't fix, Nodejs daemon is in life-support only mode, and the new SFTP server in Go has resolved these issues.
