### ISSUE TITLE
Faster Transfers

### ISSUE THREAD

**Issue by PaziHD** [pterodactyl/panel#1344]
**Is your feature request related to a problem? Please describe.**
Transfers are typically slow, and (with some clients) sftp will disconnect after every singular file transfer.

**Describe the solution you'd like**
Rsync is a good alternative, and would be useful for a migration/backup system that could be included in the future.

**Describe alternatives you've considered**
Rsync is already well supported, and has many non-proprietary clients available unlike some other platforms with similar promises.

**Additional context**
Transfers can be over 2x faster.

**Comment by GMatrixGames** [comment]
I would like to second this request just because I have had first hand experience with this. I was uploading a backup of a FiveM server, and it said it was going to take 23 hrs, but when I use SCP or FTP, it would only take 8 minutes.

**Comment by DaneEveritt** [comment]
The speed is an issue with the underlying code, not the protocol. I'm not spending time replacing an already months long nightmare project with another one.
