### ISSUE TITLE
Server not stopping after timing out.

### ISSUE THREAD

**Issue by GoogleSites** [pterodactyl/panel#1347]
Sorry I don't have a picture of the console as the console doesn't show any output and it is still in stopping mode. 

When the server timed out, I stopped the server, and it has been in this state ever since.
Please help :)

If a "force stop" feature could be added that would be awesome.

Thanks

**Comment by DaneEveritt** [comment]
This is working as intended, there is already an option to kill a server process, immediately next to the stop button. Your server not stopped when it is asked to stop is a fault with the process. The daemon does not currently decide to kill it if it takes too long, although there is a feature request open for that.
