### ISSUE TITLE
Bungeecord server crash on join

### ISSUE THREAD

**Issue by OrangeJuiced** [Pterodactyl/Panel#135]
**The problem**
When joining a newly made BungeeCord server it crashes giving this error:

```
17:39:18 [INFO] Listening on /0.0.0.0:25941
17:39:18 [INFO] Started query on /0.0.0.0:25941
>Inconsistency detected by ld.so: dl-lookup.c: 128: check_match: Assertion `version->filename =
= NULL || ! _dl_name_match_p (version->filename, map)' failed!
(Daemon) Server detected as crashed! Attempting to reboot server now.
(Daemon) Server detected as booting.
(Daemon) Server container started.
(Daemon) Attached to server container.
```

Doing a container rebuild seems to solve the problem.

**Exact steps I took:**
1. Create a new Bungeecord server with these settings: http://image.prntscr.com/image/b6f04d4146a0456e882fd0aa2f2d3984.png
2. Delete the very small default bungeecord.jar that the server puts in.
3. Upload latest bungeecord build. Try starting the server, resulting in the error.
4. Rebuild the container.
5. Server now works.

**More information:**

```
Linux -removed hostname- 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Docker info:

```
Containers: 22
 Running: 6
 Paused: 0
 Stopped: 16
Images: 3
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 82
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.75 GiB
Name: -removed hostname-
ID: X33Z:VM4A:CG5G:3X3B:5UGC:D2WG:OWEK:Q333:TQKO:GSWZ:MDQ4:35QE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

Docker version: 1.12.1, build 23cf638

**Comment by MeltedLux** [comment]
Possibly related: https://github.com/netty/netty-tcnative/issues/111

**Comment by OrangeJuiced** [comment]
This issue seems to be resolved. Does not crash anymore on join and the BungeeCord jar gets properly built. Tested on rc-2.

**Comment by DaneEveritt** [comment]
This has not been reported by anyone else, and cannot be reproduced. Closing.

**Comment by DaneEveritt** [comment]
Its back, can confirm presence.

**Comment by DaneEveritt** [comment]
Confirmed as issue with Bungeecord. Fix involves using builds compiled against alpine at http://ci.pterodactyl.io/

Will probably end up changing the container to avoid that issue.

**Comment by ThaliaSenpai** [comment]
I tried Bungeecord.jar at first, and I got that error upon joining my server. So I asked and was told to try Waterfall, which works better with Docker. I was still given the same error.

http://i.imgur.com/FAA1zHP.png

And this is the Docker Container Image: quay.io/pterodactyl/core:java-glibc
Here is the full console log: https://hastebin.com/ixotibirut.sql
The error is triggered upon connecting to the server.

**Comment by ET-Bent** [comment]
As a workaround feel free to use this container:

```flatronez/sqlite_java8_debian```

It's based on Debian and also fixes all SQLite related issues.

**Comment by ET-Bent** [comment]
![selection_772](https://user-images.githubusercontent.com/5788982/27057892-69ff2984-4fce-11e7-8905-d48f6f50ff57.png)

**Comment by DaneEveritt** [comment]
Haven't heard of this happening in quite awhile, closing this again because I believe we have it all fixed.

**Comment by Ksgz** [comment]
I'm having this issue aswell, i've tried that container code and still does the same thing

**Comment by DaneEveritt** [comment]
This is over a year old, please provide logs and enough information for us to reproduce.
