### ISSUE TITLE
Xmx = Xms causes an OOM issue (using optimised startup flags)

### ISSUE THREAD

**Issue by GiansCode** [pterodactyl/panel#1351]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.10
* Server's OS: Debian 9
* Your Computer's OS & Browser: macOS Mojave (10.14) & Google Chrome v69.0.3497.100

**Describe the bug**
When using Aikar's optimised startup flags, and setting Xmx to Xms, the panel fails to start due to an OOM error. It's likely that it's being weird because the allocated is the same as the max.

**To Reproduce**
1. Create a new Server
2. Modify the startup params to those from [here](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/) 

Here it is modified for Pterodactyl:

`java -Xms{{SERVER_MEMORY}}M -Xmx{{SERVER_MEMORY}}M -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs -jar {{SERVER_JARFILE}}`

3. Save
4. Start the server

The following [error](https://imgur.com/a/z33JkAR) will occur.

**Expected behavior**
The server should startup just fine, and not run out of memory.

**Comment by DaneEveritt** [comment]
Its likely because the container overhead isn't enough for java still. There is some very arbitrary math involved that takes the assigned memory and adds a percentage extra when making the container to avoid issues like this. Probably need to bump those numbers.

**Comment by itsgatto** [comment]
> Its likely because the container overhead isn't enough for java still. There is some very arbitrary math involved that takes the assigned memory and adds a percentage extra when making the container to avoid issues like this. Probably need to bump those numbers.

It would be nice to have a configurable option for these.

**Comment by StealWonders** [comment]
Give your container ~512MB - 1GB overhead and you should be fine.
