### ISSUE TITLE
Build Spigot Container Shows 409 Error

### ISSUE THREAD

**Issue by MrJacksonville** [pterodactyl/panel#1352]
This has definitely bugged me ever since I got my panel up. I tried creating a server with the Spigot build; however, it triggers a 409 error during the installation process, during the time when the system maps out the jar. If I used BungeeCord, it works perfectly fine. Plz fix! Thanks. :D

**Comment by parkervcp** [comment]
Can you give us logs or anything?

**Comment by DaneEveritt** [comment]
CLosing due to lack of information or following the required template.
