### ISSUE TITLE
Unlimited CPU Quota results in error

### ISSUE THREAD

**Issue by Blizzard098** [pterodactyl/panel#1353]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: Latest (v0.6.7)
* Server's OS: Debian 9.4
* Your Computer's OS & Browser: Windows 10 / Google Chrome

**Describe the bug**
_Basically I have been trying to set a CPU quota for one of my servers to 0 and this results with an error._
Please provide additional information too, depending on what you have issues with:
Panel: `PHP 7.2`
Daemon: `Linux game-ca2 4.9.131-xxxx-std-ipv6-64 #405524 SMP Tue Oct 9 14:45:24 UTC 2018 x86_64 GNU/Linux` and `https://pastebin.com/bcKyQCWL`

**To Reproduce**
1. In the server configuration, head over to build configuration.
2. Set the CPU Quota to 0.
3. Receive the error in the console.

**Expected behavior**
I expected the CPU quota to be set to 0.

**Comment by tenten8401** [comment]
You sure it's not related to the OVH kernel that's notorious for issues with docker?
`4.9.131-xxxx-std-ipv6-64`

**Comment by Blizzard098** [comment]
Yeah because the kernel in the docs said that `xxxx-mod-std-ipv6-64` was the kernel that has issues, not `xxxx-std-ipv6-64`

Aside from that when I try to do the kernel fix on the docs, it says it can't find the packages.

**Comment by tenten8401** [comment]
What's the error specifically when you try installing the kernel fix?

**Comment by DaneEveritt** [comment]
Please provide the actual error, until then I'm closing this because to date, every report of this has been due to a kernel not supporting cpufs.

**Comment by Blizzard098** [comment]
**Just pointing this out for future reference,**

OVH allows you to install the original kernel! When you're intalling an OS through an OVH template, make sure you tick the "Install Original Kernel" option!
