### ISSUE TITLE
Error while attempting to fetch list of Eggs from the panel.

### ISSUE THREAD

**Issue by ItzCodex** [pterodactyl/panel#1357]
Background (please complete the following information):
- Panel or Daemon: Deamon
- Version of Panel/Daemon: 0.7.10/0.6.7 
- Server's OS: Ubuntu
- Your Computer's OS & Browser: Windows 10 & Chrome

**Describe the bug**
When I start the deamon with 'npm start' I got an error.
Here are the diagnostics: https://hastebin.com/gatinupici

**To Reproduce**
None

**Expected behavior**
That I can start my deamon again

**Comment by ItzCodex** [comment]
I fixed it!

To fix this you need to add _localhost_ in you nginx server configuration
![image](https://user-images.githubusercontent.com/32574425/46946568-72793880-d078-11e8-98cc-41b1ca6eaa98.png)

**Comment by parkervcp** [comment]
You didn't set an app_url from what I can tell. The daemon tried to use localhost as it is the default app_url.

The .env has that variable stored there.
