### ISSUE TITLE
Return to latest powerstate

### ISSUE THREAD

**Issue by BentHaase** [pterodactyl/panel#136]
As discussed on Discord, a feature which will return the servers on one node to their power state before a potential crash of the Daemon or an unplanned reboot / crash of the host system will reduce the stress on an admin to remember the correct state of each server before.

This could be further improved by allowing the following three settings upon a daemon coming online:
- Power on all servers on this node
- Return all servers to their previous power state
- Power on all servers with the selected option to power on with daemon (has to be added to the servers settings)
- Keep all servers powered off

To avoid load spikes, a defineable delay between starting the servers will be beneficial. (30 seconds should be a good value to start with).

Let me know if this fit's here or should be more a daemon feature.

**Comment by Wqrld** [comment]
Since there have been so many requests for this. Mind rethinking about adding this?

**Comment by schrej** [comment]
Why rethink? It's still open isn't it?

**Comment by Wqrld** [comment]
This was opened a long time ago and i thought i'd bump it as it kinda disappeared.

**Comment by BLEEPBLOOPforLife** [comment]
When is this going to be done?

**Comment by Doonut** [comment]
why has this been open for nearly 3 years? This is a very useful and basic feature of even docker itself.

**Comment by schrej** [comment]
It's still open because no one implemented it so far, feel free to do so.
We might be able to leverage dockers restart policy, but that would probably break the current crash detection that only tries to restart a container a few times instead of forever.

**Comment by DaneEveritt** [comment]
Age of an issue does not determine the priority of implementation. In addition, I've already given this a swing once and it was significantly more difficult to properly implement than imagined, which is why it is still here.

**Comment by YeapGuy** [comment]
This really needs implementing. +1

**Comment by DaneEveritt** [comment]
closed for now in https://github.com/pterodactyl/wings/commit/85762ba4b990c12653ac1753e1de5b1ffa67a41b

**Comment by alekitopi** [comment]
The return to the previous state only works in some containers (ex: minecraft), in the custom containers or Voice Server containers do not work. I don't know if it's my fault but it doesn't seem to be.

**Comment by Fieel** [comment]
So what are we supposed to do in case of a an unexpected shutdown? Re-start manually all servers? Genuinely confused

**Comment by schrej** [comment]
The issue is closed. It's implemented in the 1.0 betas.

> So what are we supposed to do in case of a an unexpected shutdown? Re-start manually all servers? Genuinely confused

On stable, yes.

**Comment by 0xCyberFortress** [comment]
It's been eight years since this was first proposed, and two years since the last comment on the idea. Was this just dropped and forgotten, or is someone actually working on this?

**Comment by schrej** [comment]
This issue is closed. That means that this is implemented. 1.0 was released a long time ago.

**Comment by arkanataya** [comment]
Yes

**Comment by sebastianplainer** [comment]
Hey guys! 
I am currently on Verison 1.11.7 and the auto start works great on the normal nests but for custom generated servers such as CurseForge for example they wount autostart. Is there a possibility to let these Custom Game Server start or stop depending on their last power state.
