### ISSUE TITLE
Adding a subuser crashes the panel (partially)

### ISSUE THREAD

**Issue by Janrupf** [pterodactyl/panel#1361]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.10
* Server's OS: Linux 4.9.130-xxxx-std-ipv6-64 x86_64 GNU/Linux (Arch-Linux)
* Your Computer's OS & Browser: Linux 4.18.16-arch1-1-ARCH x86_64 GNU/Linux (Arch-Linux), Google Chrome 70.0.3538.67 

**Describe the bug**
Having a subuser in the MySQL crashes the panel. When clicking on Subusers the panel displays the error page until the user is manually removed from the MySQL.

**To Reproduce**
1. Create a Server
2. Add a Subuser (a user with the same email does already exist)
3. The panel displays the Error page

**Expected behavior**
(Not to crash)

**Comment by lancepioch** [comment]
> When clicking on Subusers the panel displays the error page

Please post the error log, thank you.

**Comment by Janrupf** [comment]
If you mean `/var/log/nginx/pterodactyl.app-error.log`... it is empty.

**Comment by parkervcp** [comment]
You need to run `tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99`

**Comment by Janrupf** [comment]
http://bin.ptdl.co/j65xe

**Comment by DaneEveritt** [comment]
Please run it immediately after you encounter the error.

**Comment by Sir3lit** [comment]
He's also using

Linux 4.9.130-xxxx-std-ipv6-64 x86_64 GNU/Linux (Arch-Linux), not sure if that could be related or not.

**Comment by Janrupf** [comment]
Log taken directly after I clicked create user: http://bin.ptdl.co/nvp7s
Log taken after I tried to access the subusers page after I reproduced the bug: http://bin.ptdl.co/5u66g

**Comment by Janrupf** [comment]
Oh... well, that all was totally my fault. I forgot to remove the comment infront of the gpm extension in the php.ini. But please don't let the panel hard fail and integrate a check if all required extensions are present.
Anyway, thank you for your support.
