### ISSUE TITLE
Problems in the Account API and Application API

### ISSUE THREAD

**Issue by hypehost** [pterodactyl/panel#1364]
**Background (please complete the following information):**
* Panel or Daemon: Panel: Panel
* Version of Panel/Daemon: 0.7.10 | Daemon: 0.6.7
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Linux Mint 19, Google Chrome 

**Describe the bug**
I try to enter "account/api" or "admin/api" and it simply appears this:

"Whoops, looks like something went wrong."

**To Reproduce**
1. Go to Application API or Account API and click.

**Expected behavior**
When you click the button, open the API page and keys.

![image](https://user-images.githubusercontent.com/43867081/47519335-c0a1ef00-d863-11e8-8d21-45ef84de89dc.png)

**Comment by Yomanz** [comment]
That would be because your doing a get request without any extra info, Sir!

**Comment by TrixterTheTux** [comment]
Check your panel logs: ``tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99``

**Comment by hypehost** [comment]
> Verifique seus registros do painel: `tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99`

https://bin.ptdl.co/hnke0/

**Comment by Bl4ckSpr4y** [comment]
When you installed the panel, did you CTRL+C out of the command php artisan migrate --seed ?

**Comment by hypehost** [comment]
> Quando você instalou o painel, você CTRL + C fora do comando php artisan migrate --seed?

Do not.

**Comment by DaneEveritt** [comment]
This isn't a bug with the software, you have your database in a bad state, wether that is because you installed it incorrectly or ignored an error during an upgrade, I do not know.
