### ISSUE TITLE
Send command client API replies with "Whoops..." if server is offline.

### ISSUE THREAD

**Issue by LeCodeCo** [pterodactyl/panel#1365]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.10
* Server's OS: Ubuntu 18.04 LTS
* Your Computer's OS & Browser: Windows 10 & Chrome

**Describe the bug**
When sending a command to the server when the server is offline through the client API, the panel returns "Whoops, looks like something went wrong." when it should return "Server is not online." from the looks of [this](https://github.com/pterodactyl/panel/blob/develop/app/Http/Controllers/Api/Client/Servers/CommandController.php#L65). 

The panel log output after sending the request is https://file.properties/paste/umopavufow. 

The same command runs successfully if the server is online, which is why I believe this is an issue. I think there are more appropriate ways to respond that the server is offline than "Whoops...".

**To Reproduce**
1. POST to /api/client/servers/{server}/console while the server is offline.
4. See error.

**Expected behavior**
I expect the reply of the API to be "Server is not online." rather than the current error page. 

If this intended, feel free to close this issue.

**Comment by Sir3lit** [comment]
The correct api endpoint to send a command is /command not /console

https://github.com/pterodactyl/panel/blob/develop/routes/api-client.php#L29

**Comment by LeCodeCo** [comment]
My bad, that was a typo on my end when writing up the issue.

**Comment by Sir3lit** [comment]
Hmm, i have a discord bot with the api, and i have yet to have this issue.

So when calling upon /api/client/servers/<server>/command and sending it a command it throws a 404? and not the error of server not online?

**Comment by LeCodeCo** [comment]
Was missing the `Accept: application/json` header.

**Comment by Sir3lit** [comment]
When calling upon the api correct headers need to be in place of

Accept: application/json
Content-Type: application/json

without "Accept : application/json" it throws "Whoops, looks like something went wrong."
with the accept header it throws the correct error of 412, but fails to display the "Server is not online." message 

Without Accept json
https://justmyrandomstuff.com/img/RP1Derm.png
With Accept json
https://justmyrandomstuff.com/img/CP70rwE.png

**Comment by DaneEveritt** [comment]
I don't see what the bug is here.
