### ISSUE TITLE
EggRetrievalController not found

### ISSUE THREAD

**Issue by Bl4ckSpr4y** [pterodactyl/panel#1369]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.10 
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 & Chrome

**Describe the bug**
https://pastebin.com/CTQ2C32U
The panel tries to find the EggRetrievalController in https://github.com/pterodactyl/panel/tree/develop/app/Http/Controllers/Api , but it's actually in https://github.com/pterodactyl/panel/tree/develop/app/Http/Controllers/API/Remote
It's a problem of capitalized and non-capitalized letters.
I've also seen it with the ValidateKeyController.
Usually re-running `composer install --no-dev --optimize-autoloader` fixes it

**To Reproduce**
Re-run `composer install --no-dev --optimize-autoloader` multiple times and the panel should start erroring

**Expected behavior**
The panel should find the EggRetrievalController in https://github.com/pterodactyl/panel/tree/develop/app/Http/Controllers/API/Remote

**Comment by loversama** [comment]
Getting the same issue, cannot read Eggs from panel using daemon.. 

https://pastebin.com/WWXySY0G

**Comment by BirkhoffLee** [comment]
Same. Running `composer install --no-dev --optimize-autoloader` for a few times fixes this.
