### ISSUE TITLE
Invalid usage of `socket.io` on both the panel and daemon

### ISSUE THREAD

**Issue by meme** [pterodactyl/panel#1370]
When visiting a console window, i.e.: `server/aa605679`, a GET request is made to initialize a connection to the daemon:

https://github.com/pterodactyl/panel/blob/develop/public/themes/pterodactyl/js/frontend/server.socket.js#L56-L58

However, this is an invalid usage of `socket.io`, and therefore causes behavior which is not expected.

This code, for example, will create an address such as: http://xxx.xxx.xxx.xxx:8080/v1/ws/AN_EXAMPLE_UUID, yet, this is invalid because `socket.io` does not accept path parameters in the address parameter. If you look in the Chrome developer tools, you will not see `/v1/ws` referenced at all (try filtering, if you are skeptical), you will, however, see a request like this: http://xxx.xxx.xxx.xxx:8080/socket.io/?token=...

To fix this, it must be used like this, instead:

```js
var address = Pterodactyl.node.scheme + '://' + Pterodactyl.node.fqdn + ':' + Pterodactyl.node.daemonListen
window.Socket = io(address, {
            'path': '/v1/ws/' + Pterodactyl.server.uuid,
            'query': 'token=' + Pterodactyl.server.daemonSecret,
});
```
This will now create the request that is intended. **BUT** it will not work, because the server is not handling these requests in a valid manner either. It is able to respond to `/socket.io`, but not `/v1/ws` requests as defined here (instead, it will return a 405 specifying GET is not valid):

https://github.com/pterodactyl/daemon/blob/develop/src/http/socket.js#L36

All in all, this causes issues when running multiple Pterodactyl nodes and forwarding their connections using a reverse proxy, all because the UUID of the requested node cannot be found due to an invalid request made to the server. This is a significant bug because of this.

**Comment by DaneEveritt** [comment]
After looking at this a little more, I'm not entirely sure what issue you're trying to report here. The namespace implemention used by the Daemon is valid, and conforms to socket.io's documentation on its usage.

The browser is correctly connecting to the core socket, in this case:
```
http://192.168.1.169:8443/socket.io/?token=...&EIO=3&transport=polling&t=...&sid=...
```

At which point it then connects to the namespace defined at `/v1/ws/UUID`.
