### ISSUE TITLE
Stuck at installing Spigot when version != latest

### ISSUE THREAD

**Issue by Derkades** [pterodactyl/panel#1374]
## System & logs
System: Virtualized (bhyve) Ubuntu 18.04 with nothing other than Pterodactyl installed
Panel version: 0.7.10 
Daemon npm run diagnostics output: https://hastebin.com/neramisare

## Description
The server gets stuck at "Installing" forever, see the screenshot below for a comparison between settings and if the server successfully installed.
![image](https://user-images.githubusercontent.com/15892014/48269154-2df27a00-e437-11e8-98cb-8a3239ab9ea7.png)
- `top` does not show any cpu usage for servers that are stuck at Installing
- No installation log file is generated in /srv/daemon/config/servers/<uuid>
- `free -m` reports 7141mb available memory
- `df -h` reports 17G out of 294G used disk space
- This screenshot has been taken 3 hours after creating the servers

## To Reproduce
1. Create a server
2. Select Minecraft -> Spigot
3. Change version (e.g. to "1.8.8")

## My guess of what the issue is
```
if (version == default)
    //works fine
    run("java -jar BuildTools.jar");
else
    //for some reason this is never executed, or the command is formatted badly
    run("java- jar BuildTools.jar --rev " + version); 
```

**Comment by parkervcp** [comment]
Where is that if statement locates because it's not a bash if statement.

**Comment by Derkades** [comment]
Sorry if it wasn't clear, that piece of code was just my guess at what might be happening, it's not taken from any pterodactyl code.

**Comment by parkervcp** [comment]
You can check the install.log while the server install is actually running. I am going to assume the install failed.

**Comment by Derkades** [comment]
Isn't install.log located at `/srv/daemon/config/servers/<uuid>/install.log`? As stated in the issue, this file or even directory is never created. I see only see directories for servers that are not stuck at "Installing".

**Comment by parkervcp** [comment]
Reinstall and tail the log from the beginning...

**Comment by Derkades** [comment]
I did and you are right, it does create a folder and a log file. I kept checking the log and it looked like the normal BuildTools process. After ~5 minutes the folder was deleted, and the server is still at "Installing". If there was an error, I missed it. Why is the folder deleted? It's impossible to check for errors this way. The other **servers that did install successfully still have the directory**:
![image](https://user-images.githubusercontent.com/15892014/48271954-cb50ac80-e43d-11e8-8e05-0fe8aa42a6be.png)

**Comment by parkervcp** [comment]
If you use `tail -f` it will read the entire log as it is written to.

**Comment by Derkades** [comment]
Ok, I'll try that. The question remains: Why is the directory deleted when installation fails, but not when installation completes successfully?

**Comment by parkervcp** [comment]
That probably needs a separate issue.

**Comment by Derkades** [comment]
https://hastebin.com/usureqilaz.sql

This turns out to be the same error Ollie#1325 is having. See #support-two for the discussion we had yesterday.

**Comment by Sir3lit** [comment]
@Derkades look at #1358 I brought it up a while ago about it deleting the files when the install failed.

**Comment by Derkades** [comment]
Can this issue be re-opened? This issue is not about logs being deleted, but about spigot eggs failing to install when the server version is set to something other than "latest".

**Comment by Sir3lit** [comment]
This is corrected with https://github.com/pterodactyl/panel/pull/1388/commits/531029b534e671b5a39ce9577f1b4268a71b02f8
