### ISSUE TITLE
invalid mount config for type "bind": bind mount source path does not exist

### ISSUE THREAD

**Issue by loversama** [pterodactyl/panel#1381]
**Background (please complete the following information):**
* Panel or Daemon: Both latest
* Version of Panel/Daemon:  7.11 & 0.6.8
* Server's OS: Ubuntu Server 14
* Your Computer's OS & Browser: Chrome (latest)

**Describe the bug**
Unable to create any servers, panel is like its connected to daemon but not fully.. I used to have it working none SSL and then SSL but after upgrading the panel I can now no longer get it to create servers..

> Containers: 64
>  Running: 20
>  Paused: 0
>  Stopped: 44
> Images: 728
> Server Version: 18.06.1-ce
> Storage Driver: aufs
>  Root Dir: /home/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 1060
>  Dirperm1 Supported: false
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
> runc version: 69663f0bd4b60df09991c08812a60108003fa340
> init version: fec3683
> Security Options:
>  apparmor
> Kernel Version: 3.13.0-86-generic
> Operating System: Ubuntu 14.04.5 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 8
> Total Memory: 31.39GiB
> Name: ##########.com
> ID: #################################
> Docker Root Dir: /home/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> 
> WARNING: No swap limit support

**To Reproduce**

Upgrade from an old installation?
(using docker compose, literally just changed version numbers..)

I also saw others with this issue but they didn't post how this was solved and the cases were closed not too long after

**Expected behavior**

Start daemon after panel & then try to create a server..

> pteronode@0.6.8 start /home/daemon
> node src/index.js | node_modules/bunyan/bin/bunyan -o short
> 10:02:45.477Z  INFO wings: + ------------------------------------ +
> 10:02:45.478Z  INFO wings: | Running Pterodactyl Daemon v0.6.8    |
> 10:02:45.478Z  INFO wings: |        https://pterodactyl.io        |
> 10:02:45.478Z  INFO wings: |  Copyright 2015 - 2018 Dane Everitt  |
> 10:02:45.478Z  INFO wings: + ------------------------------------ +
> 10:02:45.478Z  INFO wings: Loading modules, this could take a few seconds.
> 10:02:45.745Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
> 10:02:45.785Z  INFO wings: Configuring user pterodactyl (id: 500) as the owner of all server files.
> 10:02:45.790Z  INFO wings: Configuring timezone file location...
> 10:02:45.790Z  INFO wings: Checking container networking environment...
> 10:02:45.794Z  INFO wings: Found network interface for daemon: gameservers
> 10:02:45.794Z  INFO wings: Ensuring correct network interface for containers...
> 10:02:45.799Z  INFO wings: Networking gateway detected as 172.18.0.1 for interface: pterodactyl0.
> 10:02:45.802Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
> 10:02:45.980Z  INFO wings: Checking existing eggs against Panel response...
> 10:02:46.735Z  INFO wings: Beginning server initialization process.
> 10:02:46.828Z  INFO wings: Configuring websocket for daemon stats...
> 10:02:46.828Z  INFO wings: Configuring internal SFTP server...
> 10:02:46.841Z  INFO wings: Pterodactyl Daemon is up-to-date!
> 10:02:46.841Z  INFO wings: Pterodactyl Daemon is now listening for secure connections on 0.0.0.0:8080
> 10:07:55.714Z  WARN wings: Container was not found. Attempting to recreate it. (server=c71d6e3e-032f-483e-a92d-856c2a7f7b4c)
> 10:07:55.716Z  INFO wings: Checking if we need to update image quay.io/pterodactyl/core:source, if so it will happen now.
> 10:07:56.862Z  INFO wings: Pulling image quay.io/pterodactyl/core:source ... this could take a
> few minutes.
> 10:07:56.901Z FATAL wings: A fatal error was encountered while attempting to create a server.
>     Error: (HTTP code 400) unexpected - invalid mount config for type "bind": bind mount source path does not exist: /home/daemon-data/c71d6e3e-032f-483e-a92d-856c2a7f7b4c
>         at /home/daemon/node_modules/docker-modem/lib/modem.js:254:17
>         at getCause (/home/daemon/node_modules/docker-modem/lib/modem.js:284:7)
>         at Modem.buildPayload (/home/daemon/node_modules/docker-modem/lib/modem.js:253:5)
>         at IncomingMessage.<anonymous> (/home/daemon/node_modules/docker-modem/lib/modem.js:229:14)
>         at emitNone (events.js:111:20)
>         at IncomingMessage.emit (events.js:208:7)
>         at endReadableNT (_stream_readable.js:1064:12)
>         at _combinedTickCallback (internal/process/next_tick.js:138:11)
>         at process._tickDomainCallback (internal/process/next_tick.js:218:9)
> 10:07:56.906Z  INFO wings: Server deleted. (server=c71d6e3e-032f-483e-a92d-856c2a7f7b4c)
> 10:07:57.037Z  INFO wings: Notified remote panel of server install status.

It used to work flawlessly before, I have read that this could mean that the IP and or ports are being used for something else but I have used:

Ports attempted: 27015 - 27050

The 27017 below was me testing a new server and getting the error message above.

`sudo lsof -i -P -n | grep LISTEN`

> vsftpd     6484       root    3u  IPv4 4051335535      0t0  TCP *:21 (LISTEN)
> docker-pr 17468       root    4u  IPv6 3925939320      0t0  TCP *:443 (LISTEN)
> docker-pr 17494       root    4u  IPv6 3925938430      0t0  TCP *:80 (LISTEN)
> ts3server 19802 teamspeak3   30u  IPv4 3244697190      0t0  TCP *:30033 (LISTEN)
> ts3server 19802 teamspeak3   31u  IPv6 3244697191      0t0  TCP *:30033 (LISTEN)
> ts3server 19802 teamspeak3   45u  IPv4 3244700182      0t0  TCP *:10011 (LISTEN)
> ts3server 19802 teamspeak3   46u  IPv6 3244700183      0t0  TCP *:10011 (LISTEN)
> docker-pr 20704       root    4u  IPv6 3937404185      0t0  TCP *:8087 (LISTEN)
> docker-pr 20869       root    4u  IPv6 3937404372      0t0  TCP *:3308 (LISTEN)
> docker-pr 21034       root    4u  IPv6 3937407089      0t0  TCP *:27017 (LISTEN)
> docker-pr 21293       root    4u  IPv6 3937402337      0t0  TCP *:5443 (LISTEN)
> docker-pr 21305       root    4u  IPv6 3937402356      0t0  TCP *:85 (LISTEN)
> docker-pr 21625       root    4u  IPv6 3937400716      0t0  TCP *:8083 (LISTEN)
> docker-pr 21752       root    4u  IPv6 3937406641      0t0  TCP *:8888 (LISTEN)
> named     23273       bind   20u  IPv4 3886650549      0t0  TCP 127.0.0.1:53 (LISTEN)
> named     23273       bind   21u  IPv6 3886650551      0t0  TCP [::1]:53 (LISTEN)
> named     23273       bind   22u  IPv4 3886650554      0t0  TCP 127.0.0.1:953 (LISTEN)
> named     23273       bind   23u  IPv6 3886650555      0t0  TCP [::1]:953 (LISTEN)
> postgres  26146   postgres    3u  IPv4 3886650680      0t0  TCP 127.0.0.1:5432 (LISTEN)
> docker-pr 26459       root    4u  IPv6 3937425134      0t0  TCP *:4567 (LISTEN)
> docker-pr 27561       root    4u  IPv6 3937432048      0t0  TCP *:8080 (LISTEN)
> docker-pr 27575       root    4u  IPv6 3937423086      0t0  TCP *:2022 (LISTEN)
> sshd      30705       root    3u  IPv4 3923653323      0t0  TCP *:22 (LISTEN)
> sshd      30705       root    4u  IPv6 3923653325      0t0  TCP *:22 (LISTEN)
> mysqld    31152      mysql   23u  IPv4 3923654545      0t0  TCP *:3306 (LISTEN)

I have also tried different network settings with the daemon:

>       "interfaces": {
>         "v4": {
>           "subnet": "172.18.0.1/22",
>           "gateway": "172.18.0.1"
>         }
>       }

Nothing is using the ports on the server, I don't think its a permission issue..

I had changed /svr/daemon-data to /home/daemon-data as I did previously for this ubuntu 14 installation. (which used to work anyway)

So a little stuck, I've basically reinstalled the lot and even upgraded docker to the latest with no luck..

_Side note, node in the panel doesn't actually show as connected, I have had this before but it just works anyway and I've also in a recent and working setup I was able to have the green heart of the node show along with its version etc, this isn't happening this time round.._

**Comment by parkervcp** [comment]
This is because the daemon couldn't create or access the `c71d6e3e-032f-483e-a92d-856c2a7f7b4c`  folder in `/home/daemon-data/`

**Comment by loversama** [comment]
So that means it will be a permissions issue then?

It's a little weird because nothings changed and docker is the thing that makes the files and assigns the user, I will do some more debugging and will report back..

**Comment by Sir3lit** [comment]
You might want to upgrade from Ubuntu 14.04.5. It's EOL is April of 2019, could solve some issues.

**Comment by Linuxy-Lin** [comment]
> You might want to upgrade from Ubuntu 14.04.5. It's EOL is April of 2019, could solve some issues.

I have not seen anyone run Ubuntu 14 for a long time. In ages I mean...

Upgrade to Ubuntu 18.04 LTS. Its will be much easier to install the panel and lots of other features with Ubuntu!

**Comment by DaneEveritt** [comment]
From what I've seen on Discord reinstalling Docker seems to fix this issue. Why it happens, no idea.

**Comment by loversama** [comment]
I can confirm that

```
sudo apt-get purge docker-ce

sudo rm -rf /var/lib/docker

```
and reinstalling docker with the same files for the panel, mysql and daemon **do not fix this issue**.. next attempt will be to _delete all files and start again from scratch_..

Seems to be a more common issue.. maybe possible to look at what this bug is generated?

**Comment by Sir3lit** [comment]
Can you post the output of `docker info`

**Comment by loversama** [comment]
Sure thing:

```
docker info
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 28
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-47-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.38GiB
Name: sinfulshadows
ID: 6RUW:SXGM:5CRZ:Y3HA:JSDW:2IOU:IX3M:OUJG:HYBX:OI2D:JTXC:ZD5N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Comment by Official-Instructions** [comment]
Did you ever find an answer @loversama ?

**Comment by Sir3lit** [comment]
I think the issue is that you're running the dockered version of the daemon. I personally don't use it, so not sure on the in and outs of it. The solution of reinstalling docker fixed it for people NOT using the dockered version. Didn't realize you're using the dockered version of the daemon. 

If you're still having issues with it, feel free to try the support channels in our discord.

**Comment by parkervcp** [comment]
It's the volumes. They have set up to use one location that is not the same outside the container.

**Comment by tobias231h** [comment]
Wow that really was it!
I changed the host-location of the volumes to /opt/pterodactyl/... and it didn't work.
Resetting it to the original path (/srv/daemon/...) did the trick.

So you can't change these lines in the docker-compos.yml file:
    volumes:
    - /srv/daemon/config:/srv/daemon/config
    - /srv/daemon/packs:/srv/daemon/packs
    - /srv/daemon-data:/srv/daemon-data

**Comment by parkervcp** [comment]
That is unless you edit the daemon config to match.

**Comment by Joshua2504** [comment]
Same issue here on a fresh Ubuntu installation!

**Comment by bambanah** [comment]
If anyone sees this in the future, I had this on a fresh Ubuntu 22.04 install and managed to fix it by [fully uninstalling docker](https://docs.docker.com/engine/install/ubuntu/#uninstall-docker-engine) from apt **and also snap** then reinstalling. I guess it's just installed through snap by default? Either way, reinstalling seems to have fixed it.

**Comment by bjQrnen** [comment]
> If anyone sees this in the future, I had this on a fresh Ubuntu 22.04 install and managed to fix it by [fully uninstalling docker](https://docs.docker.com/engine/install/ubuntu/#uninstall-docker-engine) from apt **and also snap** then reinstalling. I guess it's just installed through snap by default? Either way, reinstalling seems to have fixed it.

Thank you! still relevant to this day.
if anyone sees this: I you want to make sure docker is completely nuked before reinstalling, check with:

`dpkg -l | grep -i docker`

I had to remove docker.io as well, and then proceeded with the official pterodactyl for installing docker:

`curl -sSL https://get.docker.com/ | CHANNEL=stable bash`
