### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by devomaa** [pterodactyl/panel#1382]
**Is your feature request related to a problem? Please describe.**
No.. not a problem

**Describe the solution you'd like**
Add Bukkit service to Game server "MINECRAFT"

**Describe alternatives you've considered**
Spigot (ALREADY ADDED)

**Additional context**
API Link: https://getbukkit.org/download/craftbukkit

**Comment by parkervcp** [comment]
@devomaa I won't support adding links to download sites that have a high potnetial to be dcma'd at any point thus breaking installers everywhere.

**Comment by cinister** [comment]
Doesn't Spigot's BuildTools output CraftBukkit as well as Spigot? Creating a new egg using the existing Spigot install script but changing the line `mv spigot-*.jar /mnt/server/${SERVER_JARFILE}` to `mv craftbukkit-*.jar /mnt/server/${SERVER_JARFILE}` should work.
