### ISSUE TITLE
Set Timezone of Docker Container to the Host's Local Time

### ISSUE THREAD

**Issue by BLEEPBLOOPforLife** [pterodactyl/panel#1384]
**Is your feature request related to a problem? Please describe.**

Yes. The timezone in Docker containers is always UTC and does not match the host machine's local time.

**Describe the solution you'd like**

Please set the docker containers' time zones to the machine's local time when creating them.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by parkervcp** [comment]
This bit of code should be doing that. - https://github.com/pterodactyl/daemon/blob/6efa32d107b333955a2d00e1ac805988b45f5f08/src/helpers/timezone.js#L32

**Comment by BLEEPBLOOPforLife** [comment]
I never made any changes, but just in case, what are the commands to rebuild the containers?

**Comment by DaneEveritt** [comment]
Theres a button in the admin CP that will rebuild a server container. Once that is done you need to restart the server. Feel free to re-open this issue if that doesn't resolve the problem.

**Comment by kaganus** [comment]
try with adding "timezone_path": "/etc/localtime" to your core.json config file if you are using Ubuntu.

/srv/daemon/config/core.json:

```
  "docker": {
    "socket": "/var/run/docker.sock",
    "autoupdate_images": true,
    "timezone_path": "/etc/localtime",   <----- add this line
  },
```

**Comment by BLEEPBLOOPforLife** [comment]
Rebuilding the server container as @DaneEveritt suggested did not work, however, what @kaganus suggested worked.

Thanks, @kaganus.
