### ISSUE TITLE
Assigning New Allocations

### ISSUE THREAD

**Issue by Joshuaharry120** [pterodactyl/panel#1389]
Hello,

I cannot add my ip and ports to the panel?? .. please see recording below

https://i.imgur.com/3EjO8ZT.gifv

**Comment by parkervcp** [comment]
First of all only apply ports from 1001 and up as 100 and lower are reserved in linux.

<http://www.penguintutor.com/linux/services-tcp-udp-port-numbers-quickreference>

**Comment by DaneEveritt** [comment]
Purse don't ignore the template, it's there for a reason.
