### ISSUE TITLE
Deamon Master Key, fails to reset

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1390]
**Background (please complete the following information):**
* Panel or Daemon:  Assuming, Both
* Version of Panel/Daemon: 0.7.11 / 0.6.8
* Server's OS:  Ubuntu 18.04
* Your Computer's OS & Browser:  Win10 / Latest Chrome

**Describe the bug**
When selecting the check box to reset the daemons master key, it fails to change it.,

Panel: PHP 7.2.10-0ubuntu0.18.04.1
Daemon: Linux 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

> Containers: 10
>  Running: 1
>  Paused: 0
>  Stopped: 9
> Images: 62
> Server Version: 18.09.0
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
> runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
> init version: fec3683
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.15.0-34-generic
> Operating System: Ubuntu 18.04.1 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 8
> Total Memory: 31.28GiB
> Name: panel
> ID: OULX:OMLZ:QS44:VUNW:WB2K:THJH:N4BU:TEZI:SHAX:P6PK:QPPY:JFMN
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> Product License: Community Engine
> WARNING: No swap limit support

**To Reproduce**
1. Go to Admin panel -> nodes -> settings
2. Check the "Reset Daemon Master Key" box,
3. Select save settings
4. Claims "Node information has been updated. If any daemon settings were changed you will need to reboot it for those changes to take effect."

**Expected behavior**

For it to reset the master key, but fails to do anything noticable.

**Comment by BLEEPBLOOPforLife** [comment]
I was trying this earlier and I was able to reproduce the issue. Please fix this.

**Comment by parkervcp** [comment]
@BLEEPBLOOPforLife Please give details on your system configuration. "I can re-create this" with no base host info is useless.

**Comment by zKoz210** [comment]
@parkervcp What's the point of this if you just didn't specify a field in the Node.php? It will never be fulfilled

![image](https://user-images.githubusercontent.com/28255085/48988071-5f0bc380-f134-11e8-93a3-5d2eb5b21661.png)

**Comment by DaneEveritt** [comment]
@zKoz210 daemonSecret is defined as a fillable key in `Node.php`.

**Comment by DaneEveritt** [comment]
The problem is that it isn't defined as a validation rule so it gets stripped out. Fixing it now.
