### ISSUE TITLE
File Downloader in File Manager (like curl)

### ISSUE THREAD

**Issue by B4TT3RY** [pterodactyl/panel#1396]
**Is your feature request related to a problem? Please describe.**
I think it's inconvenient to download the file elsewhere and upload it to the server.

**Describe the solution you'd like**
I want to download files directly from the web.

**Describe alternatives you've considered**
You might want to use features like curl or wget.

Sorry for my bad english, i using Google Translator

**Comment by lancepioch** [comment]
I think this feature extends beyond the scope of Pterodactyl. I'll let others weigh in though.

**Comment by DaneEveritt** [comment]
Theres already an open issue somewhere with this request.
