### ISSUE TITLE
Bug info stats

### ISSUE THREAD

**Issue by LewaIngame** [pterodactyl/panel#1398]
Hello i have a bug with my panel information of server 
![image](https://user-images.githubusercontent.com/36868377/49327220-e1deb500-f55e-11e8-8754-88e2c81e71b8.png)

**Comment by mayed505** [comment]
Did you modify the panel or anything?

**Comment by LewaIngame** [comment]
no

**Comment by LewaIngame** [comment]
i have just my wings no start and i cd /srv/daemon && forever start ./src/index.js
to start the daemon

**Comment by LewaIngame** [comment]
wings.service - Pterodactyl Wings Daemon
   Loaded: loaded (/etc/systemd/system/wings.service; enabled)
   Active: failed (Result: start-limit) since sam. 2018-12-01 11:51:25 CET; 16s ago
  Process: 1082 ExecStart=/usr/bin/node /srv/daemon/src/index.js (code=exited, status=1/FAILURE)
 Main PID: 1082 (code=exited, status=1/FAILURE)

déc. 01 11:51:25 server systemd[1]: wings.service: main process exited, code=exited, status=1/FAILURE
déc. 01 11:51:25 server systemd[1]: Unit wings.service entered failed state.
déc. 01 11:51:25 server systemd[1]: wings.service holdoff time over, scheduling restart.
déc. 01 11:51:25 server systemd[1]: Stopping Pterodactyl Wings Daemon...
déc. 01 11:51:25 server systemd[1]: Starting Pterodactyl Wings Daemon...
déc. 01 11:51:25 server systemd[1]: wings.service start request repeated too quickly, refusing to start.
déc. 01 11:51:25 server systemd[1]: Failed to start Pterodactyl Wings Daemon.
déc. 01 11:51:25 server systemd[1]: Unit wings.service entered failed state.

**Comment by Sir3lit** [comment]
The graphs won't show anything if Wings fails to start

**Comment by parkervcp** [comment]
This is due to the daemon not running. I will be closing this now.
