### ISSUE TITLE
The list of files is not displayed with specific SSL settings

### ISSUE THREAD

**Issue by GwtLabs** [pterodactyl/panel#1403]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.11
* Server's OS: Ubuntu 18.04.1 LTS
* Your Computer's OS & Browser: Win 10 Chrome

**Describe the bug**
1. The list of files in the File Manager tab is not loaded when site use SSL and when the redirection of requests without SSL to SSL is not enabled in Nginx.
2. The error occurs also in configuration with Cloudflare, when no SSL is used between the CF and the page server.

**To Reproduce**
1. Nginx does not enforce redirections to SSL.
2. Click on the tab "File Management" with SSL.
3. This request: http://example.com/server/xxxxxxxxx/files/directory-list in File Manager tab is not loaded with SSL.
4. The list of files is not displayed (i console see error loading elements without SSL on the page with SSL).
![image](https://user-images.githubusercontent.com/3123616/49376253-f52c8480-f706-11e8-86fe-c2e371cd5897.png)

**Expected behavior**
I want to see a list of files. The request should use SSL.

**Comment by DaneEveritt** [comment]
This sounds like it is not a standard nginx SSL setup, but rather it is SSL behind a proxy system (such as Cloudflare), correct?
