### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Joshuaharry120** [pterodactyl/panel#1409]
We use GitHub issues only to discuss about Pterodactyl bugs and new features. For
this kind of questions about using Pterodactyl, please visit our Discord for assistance: https://pterodactyl.io/discord
Hello,

Please can i be unbanned from this discord, I was banned in an error...

Joshua#0848

**Comment by Bl4ckSpr4y** [comment]
no, you will most likely not be unbanned. I have proof of you trying to advertise some discord server (looks like a pyramid scheme)

**Comment by Joshuaharry120** [comment]
Ah, I honestly,  don't remember this, I apologize for my actions...
