### ISSUE TITLE
support for third-party (custom) daemons 

### ISSUE THREAD

**Issue by feardevilz** [Pterodactyl/Panel#141]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [ ] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [ ] Bug or Issue
- [ ] Feature Request
- [x] Enhancement
- [ ] Other

I noticed on your roadmap you had AWS support indicated. I'd like to see a few changes added to the panel that allows use of third-party daemons. 
1. pufferd, written in go (https://github.com/PufferPanel/pufferd)
 - i wish Pterodactyl had a go based daemon as that seems a bit faster but if the panel could interact with the pufferpanel one that would be great. I am aware pufferpanel is a fork of pterodactyl.
2. AWS opsworks support for execution of custom resources to perform daemon-like installs

**Comment by DaneEveritt** [comment]
This is already technically possible so long as the daemon you are using follows the same API style as the core daemon. Not sure I really get what you're asking for with the AWS stuff since I don't personally make use of a lot of AWS features. That roadmap goal is most likely going to be back-burnered until a future release mostly because of the sheer amount of things in 0.5.0 and 0.6.0.

**Comment by DaneEveritt** [comment]
Is there anything specific that would need to happen panel-side for this to be implemented in your mind? I'm going to close this issue for now, but if there is something specific in the panel that needs to be changed, let me know.

**Comment by feardevilz** [comment]
@DaneEveritt After reviewing some changes I wanted pushed for this feature request I was wondering if you could consider adding a modules or library section into Panel@6 (similar to modules/library from Boxbilling) that would add on to the app/Http/Controllers/API on any event call. That means end users could add in custom modules to perform events on actions such as node or server creation. Modules could then be enabled or disabled by admins in the Panel. example: Panel/modules/Event/ServerUpdate.php could have an OnServerCreate call API (Panel/app/Http/Controllers/API/ServerController.php) that would perform apt-get update && apt-get upgrade at the time of server creation request inside the panel.

Modules could also go a bit further and allow third party reports, graphs or pages to be added into a tab of the Panel including different views - just like Boxbilling. Example: Panel/modules/Panel/Overviewer.php could add a tab inside the panel which server owners could click on to display Minecraft-Overviewer of their server.

At some point it would be good to also see Daemon become a module under that but from the looks it appears its a bit too involved.

**Comment by schrej** [comment]
This would be a kind of plugin system I guess? I really like the idea. if there is no seperate issue for that, could you open one? This is not really related to this one here. Also with 0.6.0 there are some severe changes to services coming, I would love to see the possibility to add custom pages into the panel for specific services to make some tasks easier (this will get complicated I guess though)
