### ISSUE TITLE
Databses Hosts don't create

### ISSUE THREAD

**Issue by JulesFX** [pterodactyl/panel#1412]
**Background (please complete the following information):**
* Panel or Daemon: Both latest
* Version of Panel/Daemon: 7.11 & 0.6.8
* Server's OS: Debian 8
* Your Computer's OS & Browser: Win10 & Chrome

**Describe the bug**
My PHP version: 7.2.7
Daemon: 3.16.0-6-amd64
Hello,
I can not create a Database Hosts on admin panel.
When I create it, the page will refresh and still nothing, the page is empty.
And when I had succeeded the users could not delete their database create.
thank you in advance

**To Reproduce**
1. Go to Databases Hosts
2. Create a database
3. And nothing happen

**Expected behavior**
I would have to be able to create a database hosts and users in turn could use the database

Thanks.
(PS: i have already see other issue but it's don't work)

**Comment by JulesFX** [comment]
I had asked several times but never got answers
Thanks

**Comment by parkervcp** [comment]
You asked in September. You waited 3 months to open a github issue for this.

**Comment by Ethereal739** [comment]
You should ask again in the Discord
Sounds like you gotta bind MYSQL to 0.0.0.0 first
