### ISSUE TITLE
Cannot create nest

### ISSUE THREAD

**Issue by JayJay1989** [pterodactyl/panel#1414]
**Background (please complete the following information):**
* Panel or Daemon: panel: 0.7.11, Daemon: 0.6.8
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
Get "Whoops, looks like something went wrong." screen after creating a new nest

**To Reproduce**
1. Go to nest, create new nest, fill in the inputs, press the create nest button
2. See error  [lavarel.log](https://gist.github.com/JayJay1989/83933dde848eccace8a1a31eb9104a33)

**Comment by parkervcp** [comment]
You need to set an egg author email in your `.env` in the pterodactyl folder.

**Comment by JayJay1989** [comment]
this isnt in the default example.env...

**Comment by DaneEveritt** [comment]
Which the documentation mentions running. ;)

**Comment by JayJay1989** [comment]
its running like a year without any problems, did anything change in this period, that this problem occurs?
as far i know, i'm really sure i had that command already running before
