### ISSUE TITLE
Chinese character files wont be found

### ISSUE THREAD

**Issue by mkcoldwolf** [pterodactyl/panel#1415]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.7.11/0.6.8
* Server's OS: Ubuntu 18.04.1 LTS
* Your Computer's OS & Browser: Windows 10/Google Chrome

**Describe the bug**
Panel wont find the files when using the file name with chinese character
[Download/Edit]

**To Reproduce**
1. Go to Files Manager of any server
2. Right Click on any files with contains chinese character, (for me its 你好.txt)
    [Or you can just rename it into a chinese character file]
![image](https://user-images.githubusercontent.com/32544898/50045951-9b4c9700-00d6-11e9-937b-de0a82d81f69.png)
3. Click download or click the file to edit, it will gives a error
![image](https://user-images.githubusercontent.com/32544898/50045959-b15a5780-00d6-11e9-9b8b-ca4772467dc4.png)
![image](https://user-images.githubusercontent.com/32544898/50045964-d353da00-00d6-11e9-8b30-f05f2eb5c044.png)
![image](https://user-images.githubusercontent.com/32544898/50045969-e666aa00-00d6-11e9-8ccc-788775b4ec63.png)

Also:
![image](https://user-images.githubusercontent.com/32544898/50045998-3a718e80-00d7-11e9-94bf-d7f519dc7960.png)

**Expected behavior**
It should able to download and edit the files but it just throw no files found error

**Comment by SaigyoujiYuyuko233** [comment]
Yeah... I have the same problem with that...

**Comment by parkervcp** [comment]
I suspect this is probably true for many other languages that have special characters like these.

**Comment by DaneEveritt** [comment]
Closed in 1.0 Beta
