### ISSUE TITLE
Can't connect with 2FA enabled

### ISSUE THREAD

**Issue by aurelienblais** [pterodactyl/panel#1416]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.11
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Tried on OSX and Windows 10 with Chrome

**Describe the bug**
It seems impossible to connect, after credentials input, the login page refresh without any informations.
Nothing in Laravel's logs nor in nginx logs

**To Reproduce**
Unknown, tried with my account : 
- Can't connect
- Disable 2FA through SQL
- Able to connect and to re-enable 2FA
- Can't reconnect anymore

For some of my users, it's impossible to connect with or without 2FA activated 

**Expected behavior**
At least an error message, or just being able to connect

**Comment by lancepioch** [comment]
Sorry for the late response. Does this still happen and can you provide a short video?

**Comment by LuciferWPF910** [comment]
Im getting this problem, whats the solution?
