### ISSUE TITLE
Maintenance mode per node

### ISSUE THREAD

**Issue by OrangeJuiced** [pterodactyl/panel#142]
Would love some sort of a maintenance mode per node that an admin can turn on in the panel. This could send a notification to the users with servers on the node and display some error/notification on the server management page for the user. Possibly also disable server controls or pop a notification when they are clicked informing about the current maintenace and unavailability of the node.

**Comment by falceso** [comment]
Maybe also have an option to disable the notification if you have your own method of contacting.
