### ISSUE TITLE
[Feature Request] API Endpoint for Server daemonSecrets

### ISSUE THREAD

**Issue by proEndreeper** [pterodactyl/panel#1420]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but it'd be nice if clients had the ability to interface with the server socket and get daemon secrets through the api.
**Describe the solution you'd like**
I would like a client api endpoint implemented at, for example, /api/client/servers/{SERVER_ID}/socket that will return a daemon secret, the TTL of the daemon secret, and the information required to connect to the socket. This is so a client can start a socket.io client to read from the server logs, as well as get updates on the CPU, memory, storage and network usage.
**Describe alternatives you've considered**
Alternatively, a system could be setup where a daemon secret is assigned to each api token, and each api token can have a set of servers it can manage, and instead of using the daemon secret, you use the api token instead.

**Comment by DaneEveritt** [comment]
This is more possible in 0.8 since we're exposing a much larger client API to handle all of the Vue changes being made.
