### ISSUE TITLE
SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by Tetrachloromethane** [pterodactyl/panel#1421]
Hello,
I have a problem with my deamon.
When I exec `npm start` i got this error:

```
FATAL wings: A fatal error caused the daemon to abort the startup. (err.code=EPROTO)
    Error: write EPROTO 140029655103296:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:
    
        at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
    --
    additional: {
      "errno": "EPROTO",
      "code": "EPROTO",
      "syscall": "write"
    }
```
I checked and all the ports (8080, 8443, 2022) are opens.
I checked my DNS record too and it is pointing to the right ip address.
Thank you,
With best regards

**Comment by parkervcp** [comment]
@Tetrachloromethane Can you please supply the full log.

**Comment by Tetrachloromethane** [comment]
Yeah sure
'''
root@pterodactyl:/srv/daemon# npm start

> pteronode@0.6.8 start /srv/daemon
> node src/index.js | node_modules/bunyan/bin/bunyan -o short

19:40:59.919Z  INFO wings: + ------------------------------------ +
19:40:59.926Z  INFO wings: | Running Pterodactyl Daemon v0.6.8    |
19:40:59.927Z  INFO wings: |        https://pterodactyl.io        |
19:40:59.927Z  INFO wings: |  Copyright 2015 - 2018 Dane Everitt  |
19:40:59.927Z  INFO wings: + ------------------------------------ +
19:40:59.927Z  INFO wings: Loading modules, this could take a few seconds.
19:41:00.364Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
19:41:00.455Z  INFO wings: Configuring user pterodactyl (id: 999) as the owner of all server files.
19:41:00.460Z  INFO wings: Configuring timezone file location...
19:41:00.461Z  INFO wings: Checking container networking environment...
19:41:00.470Z  INFO wings: Found network interface for daemon: pterodactyl_nw
19:41:00.471Z  INFO wings: Ensuring correct network interface for containers...
19:41:00.482Z  INFO wings: Networking gateway detected as 172.18.0.1 for interface: pterodactyl0.
19:41:00.488Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
19:41:00.537Z FATAL wings: A fatal error caused the daemon to abort the startup. (err.code=EPROTO)
    Error: write EPROTO 139753159128896:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:
    
        at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
    --
    additional: {
      "errno": "EPROTO",
      "code": "EPROTO",
      "syscall": "write"
    }
19:41:00.539Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.
'''

**Comment by DaneEveritt** [comment]
This isn't a bug with this software.

**Comment by Tetrachloromethane** [comment]
Oh ok..
Is there any way I can fix this ?
Thanks
