### ISSUE TITLE
Error 404 on "Add File"

### ISSUE THREAD

**Issue by ZeProf2Code** [pterodactyl/panel#1422]
* Panel or Daemon: I don't know
* Version of Panel/Daemon: Panel: 0.7.11 **/** Daemon: 0.6.8
* Server's OS: CentOS 7 for the panel and Unbuntu 16.04 for the Daemon
* Your Computer's OS & Browser: Windows / Google Chrome

**Describe the bug**
PHP Version : 7.2.13
![image](https://user-images.githubusercontent.com/32982428/50230862-cb818780-03ad-11e9-97a5-1089ede51224.png)
![image](https://user-images.githubusercontent.com/32982428/50230900-dc31fd80-03ad-11e9-95fb-2934f79fc000.png)
Error 404 on "Add File" on the File Manager

**To Reproduce**
1. Go to File Manager
2. Click on Add File
3. See error 
![image](https://user-images.githubusercontent.com/32982428/50230975-084d7e80-03ae-11e9-9a75-156abe47812c.png)

**Comment by parkervcp** [comment]
This should be handled in our discord server. Please join there for support.
