### ISSUE TITLE
Feature Request: Daemon: SFTP access to all user's servers on node

### ISSUE THREAD

**Issue by kamcio96** [pterodactyl/panel#1426]
Let's allow login without server id suffix. Then SFTP should show server's folders (prefer with server's name than id). Why?
Now it isn't comfortable to update files on few servers :/

If you have questions ping me on discord (`kamcio96#8278`)

**Comment by DaneEveritt** [comment]
This is very difficult when you have servers spread across multiple machines and would require a complete rewrite of the entire SFTP engine, which I'm not interested in doing at this time.

Thanks for the suggestion, but I'm not even going to pretend this is going to happen in the foreseeable future.

**Comment by kamcio96** [comment]
Hmm, I don't even thought about it `servers spread across multiple machines`

But what about user's servers on each node?

**Comment by DaneEveritt** [comment]
Not as hard, but still not something I plan on adding right now. If someone wants to PR this feature in though I'll happily review it.

**Comment by kamcio96** [comment]
Could you reopen? Maybe someone see it 😸

**Comment by DaneEveritt** [comment]
No, I don't leave issues open that I will never get around to doing as a core component in the project simply because it is overwhelming as it is.
