### ISSUE TITLE
During install setup redis password not saved

### ISSUE THREAD

**Issue by Zexceil** [pterodactyl/panel#1428]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon:  0.7.11
* Server's OS: Ubuntu LTS 18.04.1
* Your Computer's OS & Browser: Win10/Chrome

**Describe the bug**
During installation if you select redis server and your redis server uses a password it will not save the inputted password to the config file causing an error to happen.

Evidence of this happening can be found by setting up the panel and checking the .env file in /var/www/pterodactyl , it will say the redis password is "NULL"

**To Reproduce**
*Set redis server password
*Fresh or old install select redis server
*restart system

**Expected behavior**
Panel will not load and display an error page "oops something went wrong"

**Manual fix**
*cd /var/www/pterodactyl
*sudo nano .env
*Set password manually and save.

**Comment by Selixe1351** [comment]
thank you 6 years later
