### ISSUE TITLE
Broken Schedules

### ISSUE THREAD

**Issue by BLEEPBLOOPforLife** [pterodactyl/panel#1430]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.11
* Server's OS: Ubuntu 18.04.1 LTS
* Your Computer's OS & Browser: Windows 10 and Ubuntu 18.04.1 LTS; Google Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:

I have schedules for both of my two servers. The settings for the daily restart schedule is "* * 2 55". It's supposed to give a chat warning at 2:55 AM and restart the server at 3:00 AM. The last run stated by the panel is "Tue, Nov 27, 2018 3:00 AM (1 month ago)" and the next run stated by the panel is "Tue, Dec 25, 2018 2:55 AM (3 days ago)". This affects all my schedules though.

**To Reproduce**
1. Go to the "Schedules" menu on any server.
2. Create a task scheduled daily.
3. Let it run.
4. Watch it not work.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

The schedule is supposed to run daily, but it hasn't in a long time.

Screenshots: https://imgur.com/a/aksznX2

**Comment by parkervcp** [comment]
Please verify that your scheduler is running.

**Comment by tenten8401** [comment]
yeah, make sure it's enabled and running with:
```systemctl enable --now pteroq```

Come to the Pterodactyl Discord and ask for help if it continues to be an issue.
https://discord.gg/pterodactyl

**Comment by BLEEPBLOOPforLife** [comment]
Okay, I ran the command. I'll see if it works.

**Comment by mayed505** [comment]
Can you check if pteroq is actually running without any issues? Can you run `service pteroq status` and give me the output, please.

**Comment by BLEEPBLOOPforLife** [comment]
I saw that it failed last night.

https://termbin.com/isw2

**Comment by DaneEveritt** [comment]
This isn't an issue with the panel, its almost always a queue worker not running correctly. Check in on discord for further assistance.

**Comment by BLEEPBLOOPforLife** [comment]
Last night, the queue worker was active and it still is. However, the schedules still didn't run. The next run is stated to be 6 hours ago.

**Comment by tenten8401** [comment]
Please use the discord and ask in one of the `#support` channels, feel free to give me a tag and I'll try helping.
