### ISSUE TITLE
[GO SFTP] All files uploaded with WinSCP get chmodded to 000

### ISSUE THREAD

**Issue by Bl4ckSpr4y** [pterodactyl/panel#1434]
* Panel or Daemon: go sftp
* Version of Panel/Daemon: 1.0.1
* Server's OS: Ubuntu 16.04 LTS
* Your Computer's OS & Browser: Windows 10 Version 1809

**Describe the bug**
uname -a : 
Linux krabs 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Every file uploaded with WinSCP (version 5.13.6) gets cmodded to ---------- (000)
This does not happen with Filezilla. sftp-server even with --debug does not display any errors.

**To Reproduce**
1. Download the go sftp
2. Disable the default sftp
3. start the go sftp
4. Download winscp version 5.13.6
5. Connect to the SFTP
6. upload a file

**Expected behavior**
for the files to be chmodded to 644

**Comment by Sir3lit** [comment]
It's a known issue?

#1380

**Comment by Bl4ckSpr4y** [comment]
i just wanted to give more info but oh well

**Comment by schrej** [comment]
Could you please comment your details on the other issue? Dane was asking for reproduction details anyways. Thank you!
