### ISSUE TITLE
Rust - 4 frames old

### ISSUE THREAD

**Issue by Sceptox** [pterodactyl/panel#1437]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.11 / 0.6.8
* Server's OS: Linux Ubuntu 18.04.1
* Your Computer's OS & Browser: Windows 10 / Google Chrome

**Describe the bug**
Upon starting a Rust server, the following error appears: Internal: `JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak`
Panel: 7.2.13
Daemon: 4.15.0-22-generic and 18.09.0

**To Reproduce**
1. Go to your server
2. See your server console
3. Scroll up

**Expected behavior**
?

**Comment by Sir3lit** [comment]
Ummm panel 7.2.13 doesn't exist? I hope you're using 0.7.11 and php version 7.2.1e

**Comment by DaneEveritt** [comment]
Nothing you've provided here leads me to believe this is a Pterodactyl issue, and none of the version information provided links up to any specific Panel or Daemon version.
