### ISSUE TITLE
Databases doesn't work

### ISSUE THREAD

**Issue by bot4you** [pterodactyl/panel#1438]
* Panel or Daemon: Panel
* Version of Panel: 0.7.11 /
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 & Google Chrome

**Describe the bug**
When I want to add a database server, it doesn't appear in the list and pretends not to exist on that server

**To Reproduce**
1. Go to 'Databases'
2. Click on 'Create New'
3. Enter your data
4. Click Create
5. See error.

**Comment by Sir3lit** [comment]
Does it actually show a error? Or does it just show nothing after it reloads? If it shows nothing after reloading the page, then you've typed in the wrong username/password/ip or port

**Comment by Ethereal739** [comment]
Bind MySQL to 0.0.0.0 and try again.

**Comment by DaneEveritt** [comment]
Please include an actual error when opening bug reports, as the template asks.
