### ISSUE TITLE
Changing Server Owner

### ISSUE THREAD

**Issue by Goatxz** [pterodactyl/panel#1440]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Latest
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 - All Browsers

**Describe the bug**
When trying to change server owners while the person owns more than one server and the server you are changing has no external uuid, it results in an 404 error.
Panel: `php -v` (the php version in use). 7.2.13
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
6_64 x86_64 x86_64 GNU/Linux
Docker Version 18.09.0

**To Reproduce**
Go to edit a servers owner
Old owner owns more than one server
Try to set new owner
Get 404 error

(https://puu.sh/CwWqb/2f4080b77e.mp4)

**Expected behavior**
The owner should be set regardless if the old owner owns more than one server or if the server has an external id or not

**Comment by mayed505** [comment]
Does the panel logs show anything at all?

**Comment by Goatxz** [comment]
It doesn't create any logs when doing this no

**Comment by Goatxz** [comment]
Assigning the server an external id makes it work, but it should work by default

**Comment by parkervcp** [comment]
Closing as duplicate.
