### ISSUE TITLE
Statistics page shake in google chrome

### ISSUE THREAD

**Issue by MikeSonor** [pterodactyl/panel#1442]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.11
* Server's OS: Ubuntu 16.04.5 LTS
* Your Computer's OS & Browser:  Windows 10 Google Chrome

**Describe the bug**

**To Reproduce**
1.Open google chrome on 1920*1080 monitor (full size but not fullscreen)
2. Go to 'https://panel_ip/admin/statistics'

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
Bug only in 1920*1080 screen resolution and only in google chrome (try edge and firefox)
If set browser fit little bit smaller - bug is gone.
i'm attach video about it.  [1.zip](https://github.com/pterodactyl/panel/files/2766026/1.zip)
Sorry for my english.

![1out](https://user-images.githubusercontent.com/1296882/51337916-67a6b900-1a56-11e9-8b64-c67fff006293.gif)

**Comment by lancepioch** [comment]
Converted his recording to a gif and posted it.

**Comment by DaneEveritt** [comment]
This bug is amazing.

**Comment by Calvin304** [comment]
im also having this issue (specifically with a tab size of 1920*948), but it looks like its [this issue in chart.js](https://github.com/chartjs/Chart.js/issues/3611)
the default theme uses chart.js version 2.3.0 however this was partially fixed in version 2.9.1 (only doesn't work if there are two scrollbars)

**Comment by DaneEveritt** [comment]
Wontfix.

**Comment by arcdigital** [comment]
I already fixed this, will push in a bit.

**Comment by Sir3lit** [comment]
@arcdigital Sooo...??? Whats going on with this.

**Comment by JanDevDE** [comment]
@Sir3lit I mean, there is no statistics page anymore, is there? ^^

(Could be closed then.)

**Comment by DaneEveritt** [comment]
Page was removed. Closing.
