### ISSUE TITLE
Panel dont recieve failed installation

### ISSUE THREAD

**Issue by Muffl0n-DE** [pterodactyl/panel#1444]
**Background (please complete the following information):**
* Panel or Daemon: Both
* Version of Panel/Daemon: Panel:  0.7.11/0.6.8
* Server's OS: Ubuntu 18.04.1 LTS
* Your Computer's OS & Browser: Windows 10 | Chrome

**Describe the bug**
When installing a new server, the installation breaks due to wrong configuration.
With me a nonexistent script container deposited with Minecraft Forge.
Then the following output at the daemon:

`15:35:53.221Z FATAL wings: A fatal error was encountered while attempting to create a server.
    Error: (HTTP code 404) unexpected - pull access denied for frolvlad/alpine-oraclejdk8, repository does not exist or may require 'docker login'
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:257:17
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:9)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
15:35:53.231Z  INFO wings: Server has been unsuspended. (server=62131f0f-9778-4cd6-be0f-2ba308746a72)
15:35:53.242Z  INFO wings: Server deleted. (server=62131f0f-9778-4cd6-be0f-2ba308746a72)
15:35:53.271Z  INFO wings: Notified remote panel of server install status.`

The panel still has "installing" as Status.
The status does not change even after a long wait

**To Reproduce**
1. Create a Minecraft-Forge Server with the default Pterodactyl-Nest
2. Check Daemon-Output
3. Check Panel-Status

**Comment by parkervcp** [comment]
closing in favor of #1358
