### ISSUE TITLE
MySQL syntax bug, incorrect quotes MySQL commands

### ISSUE THREAD

**Issue by RealKarmakun** [pterodactyl/panel#1445]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.11
* Server's OS: Ubuntu 16.04.5 LTS
* Your Computer's OS & Browser: Windows 10, Firefox 

**Describe the bug**
PHP version: PHP 7.2.13-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Dec  7 2018 08:07:08)
if you create a database that bound to the server, you can't delete it.
Full logs: https://bin.ptdl.co/pmmys/
Error itself (18 line):
```
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IF EXISTS `u18_54KDFFMrsm`@`%`' at line 1 (SQL: DROP USER IF EXISTS `u18_54KDFFMrsm`@`%`)
```

**To Reproduce**
1. Go to Servers
2. Click on any server's name
2. Go to Database
3. Create any Database
4. Then try to delete it
5. See error

**Expected behavior**
Those quotes 

> `

in mysql command 
```
IF EXISTS `u18_54KDFFMrsm`@`%`
```
must be this one:

> '

Database should get successfully removed.

P.S. This is my first bugreport ever, sorry if something is wrong

**Comment by DaneEveritt** [comment]
You're probably not using MariaDB v10.1.3+. This isn't an issue with the backticks.
