### ISSUE TITLE
Rechapta Help

### ISSUE THREAD

**Issue by TheWalker0** [pterodactyl/panel#1447]
Is it possible to disable the login captcha? If yes then how, I can't find it in the control panel, if not can it be added?

**Comment by Lunaversitay** [comment]
https://demo.pterodactyl.io/admin/settings/advanced

**Comment by TheWalker0** [comment]
Haven't*

**Comment by JanDevDE** [comment]
@TheWalker0 To deactivate Recaptcha without access to the panel, just go to your .env file, located in your panels directory and add the entry: RECAPTCHA_ENABLED=false. Afterward, you can change the key and enable it again.
