### ISSUE TITLE
Pterodactyl Failed to load?

### ISSUE THREAD

**Issue by EnchantedP** [pterodactyl/panel#1448]
Hello, I have pterodactyl on Ubuntu and I had a power cut and since then pterodactyl won't load. Is there anyway to fix this?

Error log (systemctl status pteroq):

● pteroq.service - Pterodactyl Queue Worker
   Loaded: loaded (/etc/systemd/system/pteroq.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Tue 2019-01-22 20:46:22 UTC; 3min 27s ago
 Main PID: 31750 (code=exited, status=0/SUCCESS)

Jan 22 20:46:22 server systemd[1]: pteroq.service: Service hold-off time over, scheduling restart.
Jan 22 20:46:22 server systemd[1]: pteroq.service: Scheduled restart job, restart counter is at 5.
Jan 22 20:46:22 server systemd[1]: Stopped Pterodactyl Queue Worker.
Jan 22 20:46:22 server systemd[1]: pteroq.service: Start request repeated too quickly.
Jan 22 20:46:22 server systemd[1]: pteroq.service: Failed with result 'start-limit-hit'.
Jan 22 20:46:22 server systemd[1]: Failed to start Pterodactyl Queue Worker.

**Comment by DaneEveritt** [comment]
Please use Discord (https://discord.gg/pterodactyl or https://pterodactyl.io/discord) for assistance with issues like this. We'll direct you here if there is truly a bug that needs to be addressed.

**Comment by gamingwithjohn18** [comment]
How was this solved?

**Comment by gamingwithjohn18** [comment]
> Hello, I have pterodactyl on Ubuntu and I had a power cut and since then pterodactyl won't load. Is there anyway to fix this?
> 
> Error log (systemctl status pteroq):
> 
> ● pteroq.service - Pterodactyl Queue Worker Loaded: loaded (/etc/systemd/system/pteroq.service; enabled; vendor preset: enabled) Active: failed (Result: start-limit-hit) since Tue 2019-01-22 20:46:22 UTC; 3min 27s ago Main PID: 31750 (code=exited, status=0/SUCCESS)
> 
> Jan 22 20:46:22 server systemd[1]: pteroq.service: Service hold-off time over, scheduling restart. Jan 22 20:46:22 server systemd[1]: pteroq.service: Scheduled restart job, restart counter is at 5. Jan 22 20:46:22 server systemd[1]: Stopped Pterodactyl Queue Worker. Jan 22 20:46:22 server systemd[1]: pteroq.service: Start request repeated too quickly. Jan 22 20:46:22 server systemd[1]: pteroq.service: Failed with result 'start-limit-hit'. Jan 22 20:46:22 server systemd[1]: Failed to start Pterodactyl Queue Worker.

did you get this resolved?
