### ISSUE TITLE
Time in console incorrect

### ISSUE THREAD

**Issue by OrangeJuiced** [Pterodactyl/Panel#145]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [x] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [x] Bug or Issue
- [ ] Feature Request
- [ ] Enhancement
- [ ] Other

## What Happens

The time in the console in the panel is incorrect and doesn't match the set time  zone in the env file.

**Comment by DaneEveritt** [comment]
This has been fixed in 5ba6f06 and as such I will close this. We will look into handling it from the container itself.
