### ISSUE TITLE
[File Manager] Issue with unencoded URL characters in FS path.

### ISSUE THREAD

**Issue by MarkL4YG** [pterodactyl/panel#1450]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel v0.7.11
* Server's OS: Ubuntu 16.04.4
* Your Computer's OS & Browser: Firefox 64.0.2 (Win 10)

**Describe the bug**
When the filesystem of a container includes files or directories containing URL characters (such as ``#``), those files or files below that directory are inaccessible for the on-panel editor as these characters aren't encoded.

**To Reproduce**
1. Open file browser
2. Create folder ``test``
3. Create file ``test.txt`` inside that folder ``test``
4. Rename the folder to ``#test``
5. Try to open ``test.txt``
6. Get 404d by your web server

**Expected behavior**
The file editor should open the file so one can edit it.

**How I fixed it**
1. Navigate to [line 144 of ``list.blade.php``](https://github.com/pterodactyl/panel/blob/develop/resources/themes/pterodactyl/server/files/list.blade.php#L144).
2. Change ``{{ $file['directory'] }}`` to ``{{ rawurlencode($file['directory']) }}``
3. Change ``{{ $file['entry'] }}`` to ``{{ rawurlencode($file['entry']) }}``
4. Profit

I would've submitted a PR had I invested more time in checking the validity of my fix.

**Comment by Sir3lit** [comment]
This should be a pull request that refers to this issue.
