### ISSUE TITLE
Error when making a user

### ISSUE THREAD

**Issue by MTJID** [pterodactyl/panel#1458]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Latest? 
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Chrome, Windows 10

**Describe the bug**
When making a user I get the folllowing error even though I filled out each value correctly 
[2019-01-30 09:58:22] production.ERROR: Pterodactyl\Exceptions\Model\DataValidationException: Data integrity exception encountered while performing database write operation. {"username":["The username field is required."],"name_first":["The name first field is required."],"name_last":["The name last field is required."]} in /var/www/pterodactyl/app/Repositories/Eloquent/EloquentRepository.php:58

Please provide additional information too, depending on what you have issues with: Here are the full error logs: https://bin.ptdl.co/lwffg/
Panel: `php -v` (the php version in use). PHP 7.2
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

**To Reproduce**
1. Go to SSH and type in php artisan p:user:make
Press enter 
Fill in email, username, firstname, password
Error occures

**Expected behavior**
https://prnt.sc/meav0p

**Comment by m1cr0man** [comment]
Hi. Encountered this issue myself today. It turns out that because I was using MySQL Percona 8.0 rather than MariaDB 10, some of the schema migrations during initial startup of the panel were failing and the db was never initialised. After switching to Maria 10 I got through the create user process fine. :)
