### ISSUE TITLE
Console commands not working

### ISSUE THREAD

**Issue by Frerduro** [pterodactyl/panel#1459]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.11
* Server's OS: Ubuntu 18.04 lts
* Your Computer's OS & Browser: Windows 10 pro//Google chrome version 74.0.3685.1

**Describe the bug**
While on a server's console I am unable to send console commands. I found another user on the discord server that is having the same problem as me
PHP 7.2.14-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jan 13 2019 10:05:45) ( NTS )

**To Reproduce**
1. Go to a server console
2. Enter a command into said console
3. Profit. no output nothing and the command doesn't run

**Expected behavior**
I expect the command to run and to have feedback of such command

**Comment by matthewpi** [comment]
What egg are you using?

You should also check your browser console for any errors.

**Comment by Frerduro** [comment]
I am using the default bungee and spigot eggs and there are no errors

**Comment by DaneEveritt** [comment]
Whats the output of your browser console?

**Comment by Frerduro** [comment]
nothing its blank

**Comment by ParadoxPixel** [comment]
I'm sorry if I should say it here, but I'm experiencing the same problem. But at startup in the concole I see an error. Image: [
![image](https://user-images.githubusercontent.com/28903709/52170345-91472c00-2748-11e9-83eb-22e6f6720af7.png)
](url)

**Comment by DaneEveritt** [comment]
This is a bug with Bungeecord specifically, but we might be able to address it with a container update.

**Comment by parkervcp** [comment]
Currently there is a know issue with the latest Ubuntu Kernel right now - https://www.spigotmc.org/threads/ubuntu-18-04-bad-kernel-update.357871/

**Comment by ParadoxPixel** [comment]
If I add that it just leaves me with a server that won’t start at all. I just did a fresh ubuntu 18.04 install and I see that the kernel version ends with 45 not 44. Suppose this might be a bugfix? I will check it asap and let it know.

**Comment by ParadoxPixel** [comment]
So I just tested it with kernel version 4.15.0-45 but I still got the same problem. I'm going to try downgrading to 4.15.0-43 hopefully this might fix it.

**Comment by DaneEveritt** [comment]
This isn't an issue with Pterodactyl, its an issue with the underlying host kernel, and Bungeecord. I'm closing this issue because theres really nothing we can do currently to fix it.
