### ISSUE TITLE
ReCaptcha

### ISSUE THREAD

**Issue by AlienSteel** [pterodactyl/panel#1461]
**Is your feature request related to a problem? Please describe.**
Choosing the right type of ReCaptcha keys is non trivial for inexperienced users and documentation on how to fix the resulting problem of getting locked out of your panel is not easily found.

**Describe the solution you'd like**

1. Add label to the SiteKey field for ReCaptcha settings: "Choose ReCaptcha type: v2 invisible" if possible, add the needed domain to properly work, so "Choose ReCaptcha type: v2 invisible for domain 'panel.example.com'" where panel.example.com is the domain configured for the system.

**Describe alternatives you've considered**
None

**Additional context**
Not really needed?

**Comment by DaneEveritt** [comment]
Documentation now includes details about this.
