### ISSUE TITLE
Error file

### ISSUE THREAD

**Issue by LewaIngame** [pterodactyl/panel#1464]
Hello i have a bug with de pannel {"errors":[{"code":"DaemonConnectionException","status":"504","detail":"There was an exception while attempting to communicate with the daemon resulting in a HTTP\/500 response code. This exception has been logged."}]}

https://ptero.co/akivomujat

**Comment by mayed505** [comment]
Your daemon can't connect properly for some reason, Update your daemon to the latest version please.

**Comment by parkervcp** [comment]
Make sure your daemon is running. For surther supprto join the discord server.

**Comment by LewaIngame** [comment]
Banned from the discord
