### ISSUE TITLE
Do not allow a subuser to assign permsions they don't have

### ISSUE THREAD

**Issue by mkcoldwolf** [pterodactyl/panel#1467]
**Is your feature request related to a problem? Please describe.**
Yes, as you are in subuser system, a user can assign perms that he doesn't have themself
when he has a permission to edit and list subuser
So, if i give any subuser a edit user perm, then the whole subuser system is useless sinces they get gain all perm by giving other perm that he doesn't have, idk you guys still think its how it works? 🤔

**Describe the solution you'd like**
Show Insufficient Permission or somethings like that when they trying to give other subuser permission that he dont have himself

**Describe alternatives you've considered**
no, not yet without remove their edit subuser permermission

**Additional context**
![image](https://user-images.githubusercontent.com/32544898/52173473-4ff26300-27c0-11e9-86c0-929b065b40e9.png)
![image](https://user-images.githubusercontent.com/32544898/52173477-54b71700-27c0-11e9-8864-7987ccc3f53d.png)
![image](https://user-images.githubusercontent.com/32544898/52173479-58e33480-27c0-11e9-8f59-489ce3f89e41.png)

**Comment by mkcoldwolf** [comment]
> Isn't that what a co-owner of a server is? same as owner lol
emm, maybe your right, but that features is also needed i think,
such as admin for certain server or somethings

> It's not possible to set 2 users as owner of a single server?
Yea so that match the scenario that Zexceil created

**Comment by Yomanz** [comment]
I honestly think the bigger question here is, why would you give someone just edit subuser permission.

**Comment by mkcoldwolf** [comment]
> I honestly think the bigger question here is, why would you give someone just edit subuser permission.

So as i said, there is actually somethings like admin but not co-owner at certain server... i cant give them panel admin or even all permission in one server, but i need them to manage ppl within his power

> (And even more specifically, why would you add an "_untrustworthy_" subuser to your server)

so ur server doesn't have any 'untrustworthy' admins? ......
i thought no one is trustable in internet though...

**Comment by Havila199** [comment]
Think of this feature at the level of being just a server owner who doesn't own the panel

**Comment by parkervcp** [comment]
I needed to fix that. I really did.

**Comment by mkcoldwolf** [comment]
i would suggest keeping those two feature, one option that can assign out of his power and one option for only within his power

**Comment by DaneEveritt** [comment]
This makes significantly more sense using @parkervcp's title. In the future if you wish to be taken seriously please provide coherent thoughts and solutions, not sentences just strung together complaining about something.

**Comment by mkcoldwolf** [comment]
> This makes significantly more sense using @parkervcp's title. In the future if you wish to be taken seriously please provide coherent thoughts and solutions, not sentences just strung together complaining about something.

im sorry about that, will try my best next time, since im not a eng, i may not able to explain what i wanted to say exactly

**Comment by DaneEveritt** [comment]
For example: the subuser system allows someone with the 'Edit Subusers' permission to assign permissions that they do not have to a different user. I think they should only be allowed to assign permissions that they have already.

**Comment by MatthewSH** [comment]
Looking further in into this issue, it's not even checking the user at all to see if the user has any of the requested permissions. You could make a check when setting each user permission with an `alllowedPermissions` array that doesn't allow create-subuser unless you're the owner of the server. The `allowedPermissions` can just be a copy of the current user permissions without the create-subuser one (or null for all permissions). If that makes sense.

**Comment by DaneEveritt** [comment]
A subuser should be allowed to create a subuser with the same permissions they have, but not additional ones. I'm not going to fiddle around with any of this for now though because I don't like the current permissions that we have, they're excessively granular which makes changing features/adding new ones painful.

**Comment by DaneEveritt** [comment]
Closed in 1.0.0.
