### ISSUE TITLE
Console does not send any commands to the server (SPIGOT)

### ISSUE THREAD

**Issue by georgeashby123** [pterodactyl/panel#1470]
When I type a command into the console, nothing happens.

**Details;**
**uname -a**
Linux ns3103902 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**php -v**
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

**docker info**
Containers: 10
 Running: 1
 Paused: 0
 Stopped: 9
Images: 2
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.78GiB
Name: ns3103902
ID: SF3X:7JXF:4H53:QJMW:WAVZ:TN2H:MIMZ:NOPW:T7HF:SCFN:J5AU:HFJ6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

**GIF of what happens:**
https://gyazo.com/9eb60755e4f730e1d1fc3b34a5aa36ee

**Panel Version: 0.7.12**

**Comment by LeCodeCo** [comment]
The issue is your kernel. https://www.spigotmc.org/threads/ubuntu-18-04-bad-kernel-update.357871/
