### ISSUE TITLE
JVM flags make crash

### ISSUE THREAD

**Issue by PixelNotFound** [pterodactyl/panel#1472]
**Background (please complete the following information): I added the following args for my minecraft server instead of using the default: java -Xms128M -Xmx{{SERVER_MEMORY}}M -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs -jar {{SERVER_JARFILE}}
* Panel or Daemon: Daemon, i couldnt make a issue there
* Version of Panel/Daemon: Latest
* Server's OS: Debian 9
* Your Computer's OS & Browser: Windows 10 Chrome

**Describe the bug**
The server crashes with https://hastebin.com/detipadewe.cs when i am using flags in my JVM args

**To Reproduce**
1. change the JVM args of spigot or paper to java -Xms128M -Xmx{{SERVER_MEMORY}}M -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs -jar {{SERVER_JARFILE}}
2. start up your server 

**Expected behavior**
That the server will work with these flags and not crash on startup.

**Comment by DaneEveritt** [comment]
Not a bug.

```
[Pterodactyl Daemon] Exit Code: 137
[Pterodactyl Daemon] Out of Memory: true
```

**Comment by PixelNotFound** [comment]
but i never had this issue with Pufferpanel or my own PC

**Comment by Sir3lit** [comment]
You need to remove the pre touch flag. As it's telling Java to allocate all the ram allowed by -Xmx. Whe. It does that it triggers the out of memory. And it gets killed.
