### ISSUE TITLE
JVM Flags

### ISSUE THREAD

**Issue by PixelNotFound** [pterodactyl/panel#1473]
I want to say something about this https://github.com/pterodactyl/panel/issues/1472
I didnt have this issue with PufferPanel or on my own PC.

**Comment by Sir3lit** [comment]
You need to remove the pre touch flag. As it's telling Java to allocate all the ram allowed by -Xmx. Whe. It does that it triggers the out of memory. And it gets killed.

**Comment by PixelNotFound** [comment]
java -Xms128M -Xmx{{SERVER_MEMORY}}M -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs -jar {{SERVER_JARFILE}}

So this? @Sir3lit

**Comment by PixelNotFound** [comment]
I cant turn the server off

**Comment by DaneEveritt** [comment]
Do not open new issues, you can respond to closed ones. This is still not a bug.
