### ISSUE TITLE
Can't Create Rust Server

### ISSUE THREAD

**Issue by Imrenderman** [pterodactyl/panel#1474]
* Panel or Daemon: Panel
* Version of Panel/Daemon: Stable
* Server's OS: Ubuntu Server 16.04
* Your Computer's OS & Browser: Opera

**Describe the bug**
Every time I try to create a rust server it refreshes and clears everything in the page and doesn't create the rust server.

**To Reproduce**
1. Go to 'Admin Settings'
2. Click on 'Servers'
3. Then Click 'Create New'
4. Fill out all details
5. Select The Rust node

**Expected behavior**
Create/Deploy a rust server

**Comment by Sir3lit** [comment]
I'm not sure what causes it, but it has happened to me on random eggs before, try to restart the webserver, restart wings and clear the browser cache.

**Comment by Imrenderman** [comment]
Well I got it to work by running the auto-deploy command, but it has overwritten the Minecraft Daemon core.json. So how does one run multiple at once?

**Comment by Sir3lit** [comment]
Why are you running multiple daemons?!

**Comment by Imrenderman** [comment]
Wait, I just realized that I don't have to do that. Well nevermind...

**Comment by Imrenderman** [comment]
This issue can be closed
