### ISSUE TITLE
Timezone is wrong

### ISSUE THREAD

**Issue by 0xC1A551C** [pterodactyl/panel#1476]
I have pterodactyl running on a seperate VPS and the daemon connected to my pterodactyl panel on a dedicated server. Both have the same timezone set of America/Vancouver for the PST timezone.

VPS:
![image](https://user-images.githubusercontent.com/36227001/52543062-2d7dbe00-2d5b-11e9-96ab-43cb5b89b99b.png)

Dedi:
![image](https://user-images.githubusercontent.com/36227001/52543056-1343e000-2d5b-11e9-8d0e-d8b24c446ba2.png)

But in the pterodactyl schedules panel it shows it is 3 hours ahead for some reason. It does not seem to be using a UTC timezone. More like a GMT or something.

![image](https://user-images.githubusercontent.com/36227001/52543091-80f00c00-2d5b-11e9-95df-4ec9896f92a5.png)

**Comment by Lunaversitay** [comment]
Did you configure the timezone in your .env?

https://github.com/pterodactyl/panel/blob/develop/.env.example#L5

Doesn't matter what timezone the machine is on, the panel has to be on the timezone you specify as well.

**Comment by 0xC1A551C** [comment]
Just figured that out. Thanks
