### ISSUE TITLE
Modules node js didnt work

### ISSUE THREAD

**Issue by LewaIngame** [pterodactyl/panel#1477]
root@server:/srv/daemon# node "/srv/daemon/src/index.js"
{"name":"wings","hostname":"server","pid":26119,"level":30,"msg":"+ ------------------------------------ +","time":"2019-02-11T14:12:10.728Z","v":0}
{"name":"wings","hostname":"server","pid":26119,"level":30,"msg":"| Running Pterodactyl Daemon v0.6.11    |","time":"2019-02-11T14:12:10.730Z","v":0}
{"name":"wings","hostname":"server","pid":26119,"level":30,"msg":"|        https://pterodactyl.io        |","time":"2019-02-11T14:12:10.731Z","v":0}
{"name":"wings","hostname":"server","pid":26119,"level":30,"msg":"|  Copyright 2015 - 2018 Dane Everitt  |","time":"2019-02-11T14:12:10.731Z","v":0}
{"name":"wings","hostname":"server","pid":26119,"level":30,"msg":"+ ------------------------------------ +","time":"2019-02-11T14:12:10.731Z","v":0}
{"name":"wings","hostname":"server","pid":26119,"level":30,"msg":"Loading modules, this could take a few seconds.","time":"2019-02-11T14:12:10.731Z","v":0}
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Hello my modules magic didnt work
Error: The module '/srv/daemon/node_modules/mmmagic/build/Release/magic.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 67. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/srv/daemon/node_modules/mmmagic/lib/index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

**Comment by LewaIngame** [comment]
I am using node js 10.9.0 and npm 6.7.0

**Comment by mayed505** [comment]
Did you run `npm install` or `npm rebuild` for this matter?

**Comment by LewaIngame** [comment]
yes

**Comment by LewaIngame** [comment]
![image](https://user-images.githubusercontent.com/36868377/52569461-860f9280-2e11-11e9-83a2-5d8d213343b7.png)

**Comment by mayed505** [comment]
Can you do `node -v`?

**Comment by LewaIngame** [comment]
I precise i have used the module n to install the nodejs
![image](https://user-images.githubusercontent.com/36868377/52569738-2bc30180-2e12-11e9-9e93-0df193d88ae2.png)

**Comment by parkervcp** [comment]
You are missing dependencies for mmmagic

https://pterodactyl.io/community/installation-guides/daemon/debian9.html#general-requirements

**Comment by LewaIngame** [comment]
didn't work

**Comment by mayed505** [comment]
Join Pterodactyl's discord and ask for help in #support, please :P

**Comment by LewaIngame** [comment]
![image](https://user-images.githubusercontent.com/36868377/52570021-c6234500-2e12-11e9-9564-54b115874366.png)

**Comment by LewaIngame** [comment]
LewanIngame#5049

**Comment by LewaIngame** [comment]
> 
> 
> You are missing dependencies for mmmagic
> 
> https://pterodactyl.io/community/installation-guides/daemon/debian9.html#general-requirements

Didn't work

**Comment by mayed505** [comment]
You're probably banned, nothing I can do much for you. Sorry.

**Comment by parkervcp** [comment]
It also looks like you update node versions and you need to clear the node_modules and reinstall the packages.
