### ISSUE TITLE
Handle docker startup errors

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#148]
Occasionally docker containers might go missing, or have been accidentally deleted. Currently the daemon cannot recover from such an error. If the container is detected as missing, the daemon should attempt to re-create it.

**Comment by schrej** [comment]
This occurs on startup as well as when trying to trigger a rebuild while the daemon is still running.

**Comment by DaneEveritt** [comment]
Yeah, the container gets lost if something uncaught happens, so everything trying to use the container will fail. My current work around is to just create a blank alpine container, and put that ID for the server container ID in the config file for the server, and then restart and try to rebuild from there.

**Comment by schrej** [comment]
I'm currently looking into this ;)

**Comment by DaneEveritt** [comment]
Not sure what your idea is, but I was thinking just catching the error (since it will be thrown while startup occurs) and then matching it to being a missing container. Once that happens use the build method to rebuild the container, wait until done, and then continue.

I'd considered making it build async, which we could do (i.e. loop and rebuild all at once, so multiple broken servers can be rebuilt at once). If you can think of some good logic, we could continue daemon startup and just initialize the server afterwards, the only pitfall with this is that the server would be unavailable in the panel, and potentially cause some issues.

**Comment by schrej** [comment]
Fixing containers on startup works now, even async. If the async rebuild fails, should the daemon shut down completely or just spit an error?

**Comment by DaneEveritt** [comment]
I would think it would be best to simply log a fatal error and leave it at that. Theoretically any requests to said server would spit errors and be noticed. I don't think shutting down because of one bad server is a good plan.

Hopefully once notifications are more baked into the panel we can have the daemon send a notice to the panel so it gets attention quicker.
