### ISSUE TITLE
Pterodactyl problem - auth page

### ISSUE THREAD

**Issue by stefanik11** [pterodactyl/panel#1482]
Welcome. I'd like to deal with it because I do not know what to do anymore. I installed the Pterodactyl panel at the beginning everything was okay. After the first reboot I got the error "500" on I learned that I have to run Redis and so I did. Now I stopped on the empty, white authorization page and I do not know what to do next. Error: http://bin.ptdl.co/8b0vm 1 I am asking for help.

**Comment by parkervcp** [comment]
If you rebooted you may not have redis enabled to start with the system.

On top of that join discord and ask in there.
