### ISSUE TITLE
fatal error encountered

### ISSUE THREAD

**Issue by EthanC-8** [pterodactyl/panel#1484]
Hey so basically, i just installed panel and added server..
first of all it gets stuck on installation when i enable egg script. and when i disable it and tries to run the server it gives me this

> [Pterodactyl Daemon] Server marked as STARTING
> [Pterodactyl Daemon] Checking size of server data directory...
> [Pterodactyl Daemon] Disk Usage: 10M / 1000M
> [Pterodactyl Daemon] Ensuring file permissions.
> [Pterodactyl Daemon] Running server preflight.
> [Pterodactyl Daemon] Starting server container.
> [Pterodactyl Daemon] Server marked as OFF
> [Pterodactyl Daemon] A fatal error was encountered while starting this server.

Please lemme know wht all info you need so i can add it here

**Comment by matthewpi** [comment]
Please do not use GitHub issues for support, use Discord instead.

If you are in the Discord, use the `.wlogs` command to get your daemon logs.
