### ISSUE TITLE
.zs files become un-editable

### ISSUE THREAD

**Issue by zwamdurkel** [pterodactyl/panel#1487]
**Background (please complete the following information):**
* Panel or Daemon: Not sure. Might even be related to standalone SFTP. If so, sorry for posting here
* Version of Panel/Daemon: P=0.7.12 D=0.6.11 SFTP=1.0.4
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows, Chrome
* Just to clarify: I am using the standalone SFTP

**Describe the bug**
When you open a .zs file and save it afterwards (doesn't matter if you make changes or not), it becomes "un-editable". Other file types like .txt .config etc. work fine. the same issue might apply to other file types but I don't know about that.
![image](https://user-images.githubusercontent.com/13705380/52902432-f1da6c80-3210-11e9-93e5-3828625aba1d.png)
__**^^^ Notice how the file has become black**__

Panel: `php -v` 
```PHP 7.2.13-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Dec  7 2018 08:07:08) (                                                                                                                                                              NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.13-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999                                                                                                                                                             -2018, by Zend Technologies
```
Daemon: `uname -a`
```
Linux DRMC 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
 `docker info` (your kernel version and information regarding docker)
```Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 5
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-141-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.79GiB
Name: DRMC
ID: FLGB:Y5ED:MGQG:QIIS:3WXC:6WIY:BRXJ:VWFD:Y7B3:336P:SNDI:KOLG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**To Reproduce**
1. Go to Filemanager
2. Click on a .zs file
3. Save the file
4. You can no longer edit the file

**Expected behavior**
You should just be able to edit the file again

**Comment by DaneEveritt** [comment]
Not a bug, https://zs.readthedocs.io/en/latest/

**Comment by Shigbeard** [comment]
Sorry for the necropost, but I just wanted to note that in this context, ZS is shorthand for ZenScript, https://docs.blamejared.com/1.16/en/index/ , not a file format for compressed sets.

> CraftTweaker uses a custom scripting language called **ZenScript**, which is a fairly easy to learn language that fits CraftTweaker's needs more than an already existing language would (such as JavaScript).

Perhaps in the context of a Minecraft server, ZS file formats should be interpreted as ZenScript files. In either case, I sincerely doubt Pterodactyl panel will ever interact with a ZS file as defined by https://zs.readthedocs.io/en/latest/

**Comment by schrej** [comment]
I agree, makes sense to make that editable

**Comment by notAreYouScared** [comment]
This would have to be changed in 1.0 as 0.7 is EoL?

**Comment by fabm3n** [comment]
I can edit .zs files in 1.X
They are loaded as "Plain Text"

**Comment by schrej** [comment]
@Shigbeard are you using 0.7 or 1.0?

**Comment by DaneEveritt** [comment]
We don't have any specific restrictions on files like in 0.7 (other than it detecting it as an archive and saying no for the sake of not bombing the browser with tons of utf8 data), and I'm not really concerned with random highly specific file types not being editable via the editor.

**Comment by Shigbeard** [comment]
> 
> 
> @Shigbeard are you using 0.7 or 1.0?

I'm not too sure, my experience stems from a commercial fork of Pterodactyl panel that continues to have the issue. It appears to be forked from 0.7 however. I came across this issue when I spoke to the fork's developers about it.

**Comment by schrej** [comment]
Then have them fix it themselves. Why pay for a commercial fork if they don't fix customer issues?
