### ISSUE TITLE
IP address delete idea

### ISSUE THREAD

**Issue by LewaIngame** [pterodactyl/panel#1489]
Hello i have a problem with this two ip its possible to delete with no problem and how to delete
![image](https://user-images.githubusercontent.com/36868377/52977141-71606b00-33cc-11e9-937b-b68fd5f5ed38.png)

**Comment by Yomanz** [comment]
No idea why you made this issue on this repo. They are used in docker and pterodactyl for the daemon to work.

If you want help with this, join the discord: https://pterodactyl.io/discord and ask in #linux-help
