### ISSUE TITLE
Console not showing properly

### ISSUE THREAD

**Issue by ZeProf2Code** [pterodactyl/panel#1490]
**Background (please complete the following information):**
* Panel or Daemon: I don't really know
* Version of Panel/Daemon: 
  Panel: 0.7.12 (Latest)
  Daemon: 0.6.11 (Latest)

* Server's OS: 
  Panel: CentOS7
  Daemon: Ubuntu 16.04
* Your Computer's OS & Browser: 
  Windows 10 & Google Chrome

**Describe the bug**
Console is not showing my ASCII art correctly but it displays correctly on my PC:
![image](https://user-images.githubusercontent.com/32982428/53026763-d74c0180-3463-11e9-866e-69c4a7873c69.png)

**To Reproduce**
1. Do ASCII Art with NodeJS with that code for example:
```
var figlet = require('figlet');
 
figlet('Hello World!!', function(err, data) {
    if (err) {
        console.log('Something went wrong...');
        console.dir(err);
        return;
    }
    console.log(data)
});
```
2. See that the ASCII art is not showing properly

**Expected behavior**
![image](https://user-images.githubusercontent.com/32982428/53026784-e6cb4a80-3463-11e9-9e16-70920d8c59bd.png)

**Comment by parkervcp** [comment]
@ZeProf2Code did you use tabs versus spaces in any of those places? It could be a formatting issue.

**Comment by ZeProf2Code** [comment]
I will check this

**Comment by ZeProf2Code** [comment]
No it's not using tabs

**Comment by DaneEveritt** [comment]
This is probably the same thing that people keep trying to fix which then immediately breaks Spigot server formatting.

**Comment by ZeProf2Code** [comment]
So I just need to wait and it will be fixed?

**Comment by DaneEveritt** [comment]
No, because fixing it just causes a mass influx of people complaining, and its not a severe enough bug that I feel the need to look into it.
