### ISSUE TITLE
Docker container names not updated

### ISSUE THREAD

**Issue by Xbirdfr** [pterodactyl/panel#1492]
When I set a server name, it appear on ptero panel, but the docker container name is not updated, it still have the uuid as name.
On ptero panel : 
![2019-02-20_21-10-42](https://user-images.githubusercontent.com/6831298/53121292-31c48b00-3554-11e9-9d15-1d2109736b1d.png)

On Portainer (but same on docker command line)
![2019-02-20_21-11-53](https://user-images.githubusercontent.com/6831298/53121294-31c48b00-3554-11e9-9338-c49608b6ccea.png)

**Comment by ZeProf2Code** [comment]
It is normal

**Comment by Xbirdfr** [comment]
do we have a solution to edit container names with ptero panel ? it's very nice to use custom containers name to work with proxies

**Comment by parkervcp** [comment]
The docker container name is the server uuid. It will not change.

**Comment by parkervcp** [comment]
To extend on this if you look later. Server names are not unique. The UUID is unique so it gets used to keep things in order.
