### ISSUE TITLE
Mail settings consistency .env and panel

### ISSUE THREAD

**Issue by Luukth** [pterodactyl/panel#1496]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.12
* Server's OS: Debian 9
* Your Computer's OS & Browser: -

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `PHP 7.3.2-3+0~20190208150725.31+stretch~1.gbp0912bd (cli) (built: Feb  8 2019 15:07:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2-3+0~20190208150725.31+stretch~1.gbp0912bd, Copyright (c) 1999-2018, by Zend Technologies
`

**To Reproduce**
1. Change mail settings in Admin > Settings > Mail
2. Make different changes to mail settings in .env file
3. When sending a test mail the panel will use the settings from the panel (database) and not from the .env file.

**Expected behavior**
Settings stored in the .env should be the same as on the panel.

**Comment by JanDevDE** [comment]
@Luukth This is an expected behavior IIRC. The database settings will overwrite the .env settings.
(Also if you use APP_ENVIRONMENT_ONLY=true, the database settings will be ignored completely.)

**Comment by DaneEveritt** [comment]
@JanDevDE is correct. Also even if it wrote to .env that wouldn't do anything in environments not relying on a physical `.env` file.
