### ISSUE TITLE
Request - API endpoint consistency/cleanup

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#1500]
Cleanup API endpoint inconsistencies

Some endpoints do not consistently accept the same style of input.

### Server Ports
`{panelURLl}/api/application/servers/(serverID)`

`allocation` only returns a the primary allocation, not an array of allocations.  
There is no way to associate any other assigned port to the server via the API.  
This should be something that is also setable during the POST/PATCH methods as well.

allocations should be a table or something similar to the following
```json
{
  "allocations": {
    "primary": 1,
    "additional": [
      2,
      3,
      4,
      5,
      6,
      7,
      8
    ]
  }
}
```

### PATCH Server Build Endpoint
`{panelURLl}/api/application/servers/(serverID)/build`

#### What I expect to send to update the server build  
```json
{
  "allocation": 1,
  "limits": {
    "memory": 512,
    "swap": 0,
    "io": 500,
    "cpu": 100,
    "disk": 512,
  },
  "feature_limits": {
    "databases": 1,
    "allocations": 1
  }
}
```

#### what I am expected to send to update the server build  
```json
{
  "allocation": 1,
  "memory": 512,
  "swap": 0,
  "io": 500,
  "cpu": 100,
  "disk": 512,
  "feature_limits": {
    "databases": 1,
    "allocations": 1
  }
}
```

`feature_limits.allocations` is required but it's not implimented yet.

**Describe the solution you'd like**  
Organize all the endpoints accept the same style of input for the item being updated.

The same json should be able to be used for all types of updates.

This should not only create a server but also be able to be use to edit a servers configs(dofferent endpoints and all).  
```json
{
  "name": "A Minecraft Server",
  "user": 1,
  "egg": 5,
  "docker_image": "quay.io/pterodactyl/core:java",
  "startup": "java -Xms128M -Xmx 1024M -jar server.jar",
  "environment": {
    "SERVER_JARFILE": "server.jar",
    "VANILLA_VERSION": "latest"
  },
  "limits": {
    "memory": 1024,
    "swap": 0,
    "disk": 1024,
    "io": 500,
    "cpu": 0
  },
  "feature_limits": {
    "databases": 0,
    "allocations": 0
  },
  "allocation": {
    "primary": 1,
    "additional": [
      2,
      3,
      4,
      5,
      6,
      7,
      8
    ]
  }
}
```

### POST: Node Endpoint
`{panelURLl}/api/application/nodes`

Requires `memory_overallocate` but not `disk_overallocate`

Doesn't require `daemon_base` Which seems important if not a default config (thanks OVH).

Doesn't recognize that there are 2 daemons at the same fqdn with the same daemon/sftp ports and name.

**Additional context**
This is an evolving request. I will keep updating it as I move forward.

**Comment by parkervcp** [comment]
Please note the main post of this is being updated live as I find new issues/inconsistencies.

**Comment by parkervcp** [comment]
These updates would help in my implementation of #18

**Comment by DaneEveritt** [comment]
The first one can be solved by `?include=allocations` on the URL.

**Comment by DaneEveritt** [comment]
Fixed the bugs with certain things being required or formatted wrong. As for `daemon_base`, it is only required if passed through, because it uses the same rules as the panel and that value defaults to `/srv/daemon-data` unless otherwise specified. I won't be changing that.

**Comment by DaneEveritt** [comment]
Closing this since I've fixed all the things needing fixing. Moving forward It helps to have one issue per API bug that way I can more easily track and close them in individual commits. 👍
