### ISSUE TITLE
No Steam Token for installation

### ISSUE THREAD

**Issue by Hoerli1337** [pterodactyl/panel#1502]
**Is your feature request related to a problem? Please describe.**
Clearly a feature request.

**Describe the solution you'd like**
Allow the installation of various Steam Games without Steam Token.
A Steam Token must be specified for the installation of CS:GO.
It would be better if the user himself has to insert this token to start the server.

**Describe alternatives you've considered**
No token for installation. :)

**Additional context**
With SteamCMD you can download the game data without token.

**Comment by DaneEveritt** [comment]
You can always create a custom egg that doesn't require it.

**Comment by Dancbeunny98** [comment]
up
