### ISSUE TITLE
HTTP/E_CONN_REFUSED Issue with making Server

### ISSUE THREAD

**Issue by StrayCargo** [pterodactyl/panel#1503]
This issue is in the entire scope of the program. panel daemon etc.. 
The issue is caused when I try to make a new server and gives out the message in the picture below.
The setup is set to run on a LAN behind the PFsense virtual machine. the PFsense has been set to allow the communication to the server via a port forward from the outside internet. I cannot fix this issue no matter the things I try different ports or protocols the issue persists. 
![image](https://user-images.githubusercontent.com/8396060/53461193-5e215100-3a05-11e9-896c-1baae3cfb42e.png)

**Comment by santafejay** [comment]
I get the same problem too but my daemon is also marked as dead. (related?)

**Comment by parkervcp** [comment]
Please take this to discord. That is where this sort of issue is handled.

**Comment by StrayCargo** [comment]
Not able to do so link is expired and cant connect

**Comment by StrayCargo** [comment]
The issue persists when i try a new link from a friend

**Comment by StrayCargo** [comment]
Sent an email to the support email and got no response as of yet

**Comment by DaneEveritt** [comment]
You were banned from our community for your rude and childish commentary when no one stepping in to help you right away. Github is not the place to continue requesting support for things like this.
