### ISSUE TITLE
[Feature Request] Notice the user when a required field is empty 

### ISSUE THREAD

**Issue by Kyominii** [pterodactyl/panel#1505]
**Is your feature request related to a problem? Please describe.**
When you don't fill in a generic field such as name, memory, owner or disk, you have a flash message that appears in red at the top of the page. However, when a service variable isn't provided (for instance : Steam Account Token), there's no error message (the page goes as if the refresh button were pressed).

A video is always better than words to explain the problem
![2019-03-03_17-22-26](https://user-images.githubusercontent.com/5830372/53698186-9cd65300-3dd9-11e9-9782-282621249775.gif)

**Describe the solution you'd like**
Maybe we can add an error message like empty generic fields.
![image](https://user-images.githubusercontent.com/5830372/53698200-becfd580-3dd9-11e9-9213-66d60e65d330.png)

**Comment by DaneEveritt** [comment]
This is a duplicate/fixed by #1468
