### ISSUE TITLE
Memory and CPU graphs look stretched on ultrawide monitor

### ISSUE THREAD

**Issue by bbenance** [pterodactyl/panel#1510]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.13
* Server's OS: Ubuntu Server 18.04.1
* Your Computer's OS & Browser: Windows 10, tested on both Firefox and Chrome

**Describe the bug**
The CPU and Memory graphs look very stretched and awkward on a 21:9/ultrawide monitor. The numbers are squished and at the corners they will occasionally overlap.
Image:
![image](https://user-images.githubusercontent.com/36939204/53929124-52134000-4052-11e9-9ef8-2c1bc07a8fca.png)

**To Reproduce**
Look at the graphs of your server on an ultrawide monitor.

**Expected behavior**
The graphs to be properly sized and not stretched.

**Comment by Sir3lit** [comment]
I mean that looks normal

**Comment by DaneEveritt** [comment]
Fixed in the new design which has a better fixed-width.
