### ISSUE TITLE
Allow Daemon Port Proxying

### ISSUE THREAD

**Issue by phit** [pterodactyl/panel#1511]
**Is your feature request related to a problem? Please describe.**
I want to proxy pass the daemon to be on a subdomain on port 443/80, instead of exposing a random port on the daemon server. 

**Describe the solution you'd like**
Currently you can't set the listen port of the daemon and the port the panel will actually connect to different values.
Either add an option to add a port in the FQDN field in the node settings, or remove the lower bound restriction on the daemon port field (then the user would change the listen port manually in the daemon configuration).

**Comment by phit** [comment]
apparently that's an undocumented feature of the "Behind Proxy" button

**Comment by danny6167** [comment]
If you want to to connect on a different port, set a different port in the panel.

**Comment by phit** [comment]
![](https://i.imgur.com/oxZfohD.png)

you can't hence why I made this issue

**Comment by danny6167** [comment]
Then you want a feature request to allow the daemon to be configured on a privileged port.

**Comment by sweepyoface** [comment]
> If you want it to connect on a different port, set a different port in the panel.

This does not solve the issue, since setting a different port in the panel also changes the port the *daemon is listening on*. It looks like that in order to proxy the daemon with a web server, the panel needs an option to connect to a different one (since you can't have the daemon and web server listening on the same port).

**Comment by danny6167** [comment]
Changing the port in the panel does not change the port the daemon is listening to unless you re-copied the core.json config file after making the change.

**Comment by sweepyoface** [comment]
> Changing the port in the panel does not change the port the daemon is listening to unless you re-copied the core.json config file after making the change.

Ok, but why do we need to do it that way and then need to remember to re-set that change in the panel after changing the other options and then copying them over? Why can't there be a separate option?

**Comment by danny6167** [comment]
You don't need to remember to re-set anything. you set it once just like you would during a normal setup.

If you want a more 'user friendly' setup, just run it on 8080 like 99% of users.

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/panel/commit/38cd8f296245c2edb3f0b1290385d31df7a720b8

**Comment by sweepyoface** [comment]
I don't think https://github.com/pterodactyl/panel/commit/38cd8f296245c2edb3f0b1290385d31df7a720b8 fixes this, since you still can't have the daemon listen on a different port than you want the panel to access it on (without editing config files)

**Comment by phit** [comment]
editing the daemon config is pretty much expected for any advanced setup, pretty sure the panel output is just for basic usage. a lot of the settings the config supports can't be set via the panel.

**Comment by DaneEveritt** [comment]
This is also an incredibly non-standard setup anyways, so having it in the core functionality isn't exactly an end goal of mine. Glad this will fix it for your use case though. :)
