### ISSUE TITLE
Can you add compress and move option to Mass Actions in the next version?

### ISSUE THREAD

**Issue by ati99** [pterodactyl/panel#1513]
**Is your feature request related to a problem? Please describe.**
We only can compress file (one by one) and folders and cant move/compress more files at once.

**Describe the solution you'd like**
Please add compress and move option to Mass Actions in file manager.

**Additional context**
![kep](https://user-images.githubusercontent.com/39093335/53973651-0f587300-40f9-11e9-87c5-bcdb2e0738e8.png)

**Comment by mkcoldwolf** [comment]
Up vote this one, Compress Mass Action is more important than the move one
its useful on root dir where user cant move the root folder
i dont understand why Delete Files Mass action are there but no Compress
P.S. Better with a Mass Compress Permission!

**Comment by DaneEveritt** [comment]
Closing as this is already planned down the road.
