### ISSUE TITLE
Rust Server Creation

### ISSUE THREAD

**Issue by MerlinBIOSMod** [pterodactyl/panel#1514]
**Background (please complete the following information):**
* Panel or Daemon: both
* Version of Panel/Daemon: 0.7.13
* Server's OS: Debian 9
* Your Computer's OS & Browser: Windows 10 Opera

**Describe the bug**

If I want to create a Rust Server then an error comes in the panel that says Install Failed
https://pastebin.com/HjtgfT7K daemon.log

**Comment by Sir3lit** [comment]
Please take this to the discord for support. Thanks.

**Comment by DaneEveritt** [comment]
Not a bug with this software specifically.
