### ISSUE TITLE
Dark Mode for Panel

### ISSUE THREAD

**Issue by CoolJWB** [pterodactyl/panel#1517]
**Is your feature request related to a problem? Please describe.**
The main issue is when you're working/managing a server at night the white background causes a lot of distress on your eyes.

**Describe the solution you'd like**
A switch that is located on the navigation bar to change the white background (in the content section) to a dark shade of gray (such as #151515 to distinguish it from the server console and such).

**Describe alternatives you've considered**
I have not considered any alternative solutions to this problem.

**Additional context**
![PterodactylPanel](https://user-images.githubusercontent.com/13751243/54063394-51bea480-420c-11e9-9fc4-b695f7db358e.png)

**Comment by Nevexo** [comment]
A browser extension such as DarkReader is a good temporary solution to this. 
![image](https://user-images.githubusercontent.com/4786918/54064155-c0e6c980-4209-11e9-8dec-a4816bebf05a.png)

**Comment by ZeProf2Code** [comment]
Pterodactyl should implement DarkReader into the panel directly that's would be cool!

**Comment by Lunaversitay** [comment]
There's a bunch of alternatives already for this.

I even have one for 0.6 (0.7 is private to dino.gg atm, but its super easy to fix up some stuff on 0.7)
https://github.com/Lunaversitay/pterodactyl-skins

Found these with a quick google search: https://github.com/TheFonix/Pterodactyl-Themes

Also @ZeProf2Code I don't think darkreader is "implementable" it seems like just a browser extension.

**Comment by DaneEveritt** [comment]
I don't have plans to implement dual themes, people are welcome to maintain their own versions, and this should be even easier with a more unified design system available in 0.8.
