### ISSUE TITLE
Node API expansion

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#1518]
Return the status on how much memory and disk space is allocated on a node.

**Describe the solution you'd like**
In the API I'd like to see an "allocated" array something like the following.

```json
  "attributes": {
    "memory": 2048,
    "memory_overallocate": 0,
    "disk": 5120,
    "disk_overallocate": 0,
    "allocated":{
      "memory": 1024,
      "disk": 2048
    }
  }
```

You could also return something like this instead.
```json
    "memory": 2048,
    "memory_overallocate": 0,
    "memory_allocated": 1024,
    "disk": 5120,
    "disk_overallocate": 0,
    "disk_allocated": 2048
```

**Additional context**
This would be one way to pre-check space on a node before adding a new server to the node.

**Comment by SaltyBunny12772** [comment]
Is this still open/active?
