### ISSUE TITLE
less API application/servers/ GET/POST/PATCH differences

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#1519]
We should be able to use the output of a `GET /api/application/servers/{server}` as a `POST /api/application/servers/` or as a `PATCH /api/application/servers/{server}`

Shouldn't the json returned by the panel parse the same as the json sent to the panel?

When creating a server on the panel you send the following to set allocations

```json
	"allocation": {
		"default": 2,
		"additional": [
			3,
			4
		]
	}
```

When getting server information we get

```json
    "allocation": 3,
```

**Comment by DaneEveritt** [comment]
Use `?include=allocations` to actually load the allocations onto the object. Its not going to be a perfect match from just a raw dump. I get what you're asking for but that data already exists, albeit in a slightly different form.

**Comment by parkervcp** [comment]
This was more to make it a uniform input/output. The relationship is still something I would want to get port numbers faster.

**Comment by DaneEveritt** [comment]
Closing this, the API works that way for a reason and making the GET/POST endpoints line up exactly is not important to me.
