### ISSUE TITLE
[Feature Request] Assign CPU Cores

### ISSUE THREAD

**Issue by NomisCZ** [pterodactyl/panel#1522]
Ability to set processor cores/threads per individual servers.
Docker support this with parameter --cpuset-cpus="" CPUs in which to allow execution (0-3, 0,1)

Eg. Xeon E3-1275 v5 has 4 cores and 4 threads. CS:GO server runs better on physical cores, so you can easily assign physical cores 0-1 or core 0 and thread 4 to this server / container.

Feature is already done in my fork:
Panel: https://github.com/NomisCZ/pterodactyl-panel/commit/be840951d995cc560c70592984328b88782158b7
Daemon: https://github.com/NomisCZ/pterodactyl-daemon/commit/e2e6b27709bf6d8947314370fe11a4131651b884

**Comment by DaneEveritt** [comment]
I'd recommend opening a PR if you already have the needed code, that way we can discuss better/different implementations and how to combat potential user implementation issues.

**Comment by NomisCZ** [comment]
@DaneEveritt OK, thanks.

**Comment by clienthax** [comment]
@NomisCZ Are you planning to PR this functionality upstream?, seems it works fine in your branchs

**Comment by AndyLee1024** [comment]
awesome

**Comment by ghost** [comment]
And it's gone! Noice. My favorite FOSS is the kind that disappears over politics.
