### ISSUE TITLE
Overdue schedules are performed

### ISSUE THREAD

**Issue by GwtLabs** [pterodactyl/panel#1523]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.13
* Server's OS: Ubuntu 18
* Your Computer's OS & Browser: Chromium

**Describe the bug**
Schedule Manager performing an overdue task.

**To Reproduce**
1. Create new schedule e.g. server restart in a minute
2. Save and wait for execute
3. Click toggle status (disable shedule)
4. Edit shedule run time for to start in a minute
5. Wait until the run time will pass (even a few minutes)
6. Click toggle status (enable shedule)
7. In the next runtime cycle the task will be performed even though its time is already past (regardless of how many minutes ago it was supposed to be made)

**Expected behavior**
Tasks with time in the future should not be run.

**Comment by DaneEveritt** [comment]
I feel like there was a reason why I did this when I designed that system, but I can see how that can cause some issues, so I'll make this work more logically.

**Comment by DaneEveritt** [comment]
I believe this was fixed when the client API was updated. Right now when you make edits to a schedule it updates the `next_run_at` column and resets the `is_processing` column. I can't reproduce this issue, but it seems like it no longer happens and the schedules act as expected.
