### ISSUE TITLE
Spigot servers failed to install

### ISSUE THREAD

**Issue by RealRunSpace** [pterodactyl/panel#1525]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.12
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Win10 + Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `7.2.15
Daemon: Linux vmi241713.contaboserver.net 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Without modifying anything about the panel now installations fails with this error:
`12:20:27.453Z FATAL wings: A fatal error was encountered while attempting to create a server.
    Error: Install script failed with code 1
        at DockerController.run (/srv/daemon/src/controllers/option.js:169:41)
        at /srv/daemon/node_modules/dockerode/lib/docker.js:1417:11
        at /srv/daemon/node_modules/dockerode/lib/container.js:783:7
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:270:7)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:139:11)
        at process._tickDomainCallback (internal/process/next_tick.js:219:9)`
[install.log](https://github.com/pterodactyl/panel/files/2975119/install.log)

**To Reproduce**
1. Create a spigot server
2. Installation failed

**Expected behavior**
Installation works and server boot up.

**Comment by RealRunSpace** [comment]
I've found this https://hub.spigotmc.org/jira/browse/BUILDTOOLS-286, but IDK how to reinstall java in a container. Also this install error occurs in all new spigot server I create.

**Comment by mkcoldwolf** [comment]
This has been the issue for age, but someone suggested me to build it inside the server data dir by terminal  or just upload the built spigot.jar into the server without the eggs installation, and then it will works fine

tips:
step to skip eggs installation,
give a fake Counter.jar on download link section when create server
remove the jar, and build the way u want manually

**Comment by RealRunSpace** [comment]
But is strange because days before all installations succeed without problems

**Comment by mkcoldwolf** [comment]
I never tried any success build with spigot lol

**Comment by RealRunSpace** [comment]
It was working before, also to override this just add a download path, for example https://cdn.getbukkit.org/spigot/spigot-1.13.2.jar and it will work also

**Comment by mkcoldwolf** [comment]
Just not recommend download spigot directly, its illegal

**Comment by RealRunSpace** [comment]
Well, it's an alternative

**Comment by parkervcp** [comment]
I deleted the link to the static jar files as we want to distance ourselves..

We have defaulted to Paper as it supports all the same things Spigot does. It's also not under DCMA.

When trying to build spigot now though I am getting errors pulling the bukkit files.

**Comment by RealRunSpace** [comment]
So it's not my fault I guess, and sorry for posting the link!!

**Comment by DaneEveritt** [comment]
Not a bug with this software.
