### ISSUE TITLE
2FA Image Doesn't Load, 502 From Google Charts API

### ISSUE THREAD

**Issue by foxwyn** [pterodactyl/panel#1528]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.13
* Server's OS: Ubuntu 18.04.2
* Your Computer's OS & Browser: Win 10, Chrome 73

When enabling 2FA from the /account/security page, the QR code image never loads. It sticks on "Loading QR Code". Upon doing some digging, the failure seems to be a 502 returned by Google's Charts API.

Related issue seems to indicate they've possibly EoL'd the service all together?! https://github.com/google/google-visualization-issues/issues/2721

**To Reproduce**
1. Go to /account/security
2. Click on Enable 2-Factor Authentication
3. See error

**Expected behavior**
I expect the QR code to display for scanning with my authenticator app.

**Comment by DaneEveritt** [comment]
This API got EOL'd on the 14th. Need to migrate to a different service.

**Comment by lancepioch** [comment]
Suggestion: https://www.chartjs.org
