### ISSUE TITLE
Repositorys for Eggs

### ISSUE THREAD

**Issue by Muffl0n-DE** [pterodactyl/panel#1529]
**Is your feature request related to a problem? Please describe.**
It's not directly a Problem. Its more a feature for the comfort. 
At the Moment you need to download an egg.json to upload it to the panel.

**Describe the solution you'd like**
The ability to create a repository where users can save, update and rate an egg.json would simplify the overview of existing eggs.

My idea is that this repository can be stored as a URL in the settings, so that a user can directly import and update an egg from the repository.

**Additional context**
So that you do not have any more work, you can set a specific file system structure for the repository so that the community can create their own.

**Comment by Sir3lit** [comment]
https://pteroeggs.com/ Somthing like this? pulls from the parkers egg repo

**Comment by DaneEveritt** [comment]
https://github.com/parkervcp/eggs

**Comment by Muffl0n-DE** [comment]
ok, thx for the Link^^
