### ISSUE TITLE
Server console should only auto-scroll at the bottom

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#153]
## Product
- [x] Panel
- [ ] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [ ] Bug or Issue
- [ ] Feature Request
- [x] Enhancement
- [ ] Other

The server console when managing a server should only automatically scroll to the bottom when new messages arrive if the console is scrolled all the way down (or very close to beeing so).
This would eliminate the need for the pause button and make it much easier to read the log.

We could try to set `terminal.scrollOnEcho` to `false` when the terminal isn't scrolled down if possible.

**Comment by DaneEveritt** [comment]
This is a limitation of the software being used to control it, so not much I can do about it as far as I can tell.
