### ISSUE TITLE
Feature Request: Confirmation for RESTART, STOP and KILL

### ISSUE THREAD

**Issue by GabrielSerealia** [pterodactyl/panel#1532]
It's a pretty low priority feature and more QoL but having a confirmation for those buttons would be nice especially when accessing the website on mobile.

**Comment by xopez** [comment]
I agree

**Comment by gabesystems** [comment]
I really don't see why this is necessary, like why does there need to be a confirmation? Also, would you want something like a popup that says like are you sure or something like that?

**Comment by GabrielSerealia** [comment]
Mainly for mobile usage the webpage. The user can accidently touch any of the buttons when operating the page from a touchscreen device. On the desktop browser I don't think such a think would be necessary.

**Comment by gabesystems** [comment]
I may actually make something like this, but would you want something like a popout that asks "Are you sure you want to perform this action?" or something different?

**Comment by GabrielSerealia** [comment]
Maybe have it require the user to enter their password similar to this: https://gfycat.com/pointedoptimalfrog

But in all seriousness I think your solution would be sufficient to prevent accidental clicking.

I also noticed a couple of my server's staff switching over to Pterodactyl due to muscle memory are hitting tab for autocomplete and space to confirm which is causing them to hit the start button (and in some cases restart).

**Comment by DaneEveritt** [comment]
I'm not forcing users to enter a password to stop or kill a server process, thats a horrific UX experience. I can look into something for the new design's mobile view, but I'm not backporting anything to 0.7.x.

**Comment by GabrielSerealia** [comment]
Oh, that was a joke lol

**Comment by gabesystems** [comment]
lmao. But seriously I will get to work on this, shouldn't be too difficult, I am going to make it so it will open a popup on the screen when you click "stop", "kill" or "restart". Once the popup is open if you click "yes" it will actually perform the action and "no" will close the popup.

**Comment by GabrielSerealia** [comment]
Thank's c:
(I'd submit a pull request with changes but my JS code isn't the best)

**Comment by DaneEveritt** [comment]
Closing this as the new UI will just show a little modal confirm view for killing.
