### ISSUE TITLE
[Feature] File Editor for specific eggs

### ISSUE THREAD

**Issue by ZeProf2Code** [pterodactyl/panel#1534]
**Is your feature request related to a problem? Please describe.**
It's not a problem, it's a feature. Everyone is asking for a file editor for specific eggs.
For example, we could modify server.cfg of a Garry's Mod server in a simple UI without the need to edit files manually. (It will be settable for each egg)

**Describe the solution you'd like**
For example, we could modify server.cfg of a Garry's Mod server in a simple UI without the need to edit files manually. (It will be settable for each egg)

**Additional context**

**Comment by DaneEveritt** [comment]
Not interested in implementing this as a core feature.
