### ISSUE TITLE
Deamon DDOS attack

### ISSUE THREAD

**Issue by Explosivee** [pterodactyl/panel#1536]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: Lastest
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win10 Pro 64bit / Opera, Chrome

**Describe the bug**

I'm trying to start my instance but deamon sees it as DDOS attack
https://pastebin.com/xGncVzCP

**Comment by parkervcp** [comment]
The docs cover this - https://pterodactyl.io/daemon/configuration.html#output-throttles

**Comment by gabesystems** [comment]
Shouldn't this have been taken to discord support?
