### ISSUE TITLE
Paper install egg selects the wrong java docker image file

### ISSUE THREAD

**Issue by 0xC1A551C** [pterodactyl/panel#1537]
**Background (please complete the following information):**
* Version of Panel/Daemon:  0.7.13
* Server's OS: debian 9
* Your Computer's OS & Browser:  ubuntu mozilla firefox

**Describe the bug**

The paper egg uses the image `quay.io/pterodactyl/core:java` which causes some issues with plugins while the spigot egg uses `quay.io/pterodactyl/core:java-glibc`

**Comment by 0xC1A551C** [comment]
Just wanted to add this kinda screws over paper as plugins dont load properly like bannerboard: https://hastebin.com/gapobipoqa.bash and it causes the server to crash overall. There should be a separate egg for modpacks rather than just screwing over paper as people will believe paper is causing the issue - not the egg.

https://cdn.discordapp.com/attachments/122903114423599104/560365313192099841/mVdUM52.png

**Comment by DaneEveritt** [comment]
This is not enough information for anything to understand what is going on, and why it needs to be fixed. Please include relevant logs when opening a bug report. Telling us "its broken" is not going to get anything fixed.

**Comment by 0xC1A551C** [comment]
After talking with some people from my understanding it may be the plugin developers fault for not supporting openjdk, but also pterodactyls for not defaulting to using the glibc library since that is the standard and most supported library.

The paper egg uses the musl library `quay.io/pterodactyl/core:java` which causes plugins to crash like this: https://hastebin.com/gapobipoqa.bash or for the entire server to crash like the error below:

`# A fatal error has been detected by the Java Runtime Environment:
# SIGSEGV (0xb) at pc=0x000000000000b32e, pid=33, tid=0x00007fd3acaa0ae8
# JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.10.0
# Distribution: Custom build (Thu Jan 10 09:44:25 UTC 2019)
# Problematic frame:
# C 0x000000000000b32e
# Core dump written. Default location: /home/container/core or core.33
# An error report file with more information is saved as:
# /home/container/hs_err_pid33.log
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
# http://icedtea.classpath.org/bugzilla
/entrypoint.sh: line 15: 33 Segmentation fault (core dumped) java -Xms128M -Xmx2000M -jar Paper.jar`

**Comment by parkervcp** [comment]
Can anyone offer up a plugin that has this exact issue. I don't normally host MC servers and when I don't it's usually vanilla.

**Comment by 0xC1A551C** [comment]
> 
> 
> Can anyone offer up a plugin that has this exact issue. I don't normally host MC servers and when I don't it's usually vanilla.

I sent you an email with a plugin hopefully you receive it.

**Comment by parkervcp** [comment]
No email yet. Just try this - `quay.io/parkervcp/pterodactyl-images:debian_openjdk-8-jre`

**Comment by YeapGuy** [comment]
@0xC1A551C Have you solved the issue by changing the image? If yes, what image did you change to? My server keeps crashing with a SIGSEGV and I tried dozens of "fixes", none of which work. I hope this could fix it.
