### ISSUE TITLE
/admin/settings default language shows wrong language selected

### ISSUE THREAD

**Issue by danny6167** [pterodactyl/panel#1538]
* Panel or Daemon:  Panel
* Version of Panel/Daemon:  0.7.13
* Server's OS: Debian 9
* Your Computer's OS & Browser:  Win10 - Chrome

**Describe the bug**
On the page /admin/settings the form field for "Default Language" defaults to showing/selecting the current language of the user looking at it (as set in their profile), instead of the application set default language.

Using the form and clicking Save does update the settings table to the value selected but when the page reloads the value is retrieved from the users setting to seed the html selected attribute instead of the global default value it just updated.

**To Reproduce**
1. Go to '/admin/settings'
2. Select a value different from your own language and click save.
3. See that the language select box has reset to the language your account is currently using.
4. Logout and see on the login screen that the language change did in fact work despite the form resetting to the wrong defaults.

**Expected behavior**
It's expected that when the form loads up the value of the applications default language is loaded as the currently set value instead of the value from the current user.

**Comment by matthewpi** [comment]
The admin area will be eventually replaced by react-admin and 1.0 doesn't currently support localization, making this option pointless.
