### ISSUE TITLE
LinuxGSM integration

### ISSUE THREAD

**Issue by vadrozh** [pterodactyl/panel#1539]
**Is your feature request related to a problem? Please describe.**
Now it's possible to run servers only in Docker containers, and sometimes it causes some problems then server needs to bind direct to external address.

**Describe the solution you'd like**
I want to have an opportunity to run native servers with LinuxGSM and use Pterodactyl Panel with it.

**Describe alternatives you've considered**
Other solution is to allow native servers without LinuxGSM - for example directly run SteamCMD.

**Comment by vadrozh** [comment]
duplicate

**Comment by DaneEveritt** [comment]
This isn't a duplicate based on what you're asking for which is running servers with LinuxGSM or outside of containers. The answer to both of those however, is no, that won't be something that is implemented.
