### ISSUE TITLE
Panel reported an invalid set of SFTP credentials or a malformed request

### ISSUE THREAD

**Issue by fabri2000779** [pterodactyl/panel#1541]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 7.13/6.12 
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser:  Windows 10 Pro / Opera

**Describe the bug**
People cant run commands in their console in a especifict node, this is only happening in one node. Also people cant connect via SFTP in this node

Log: https://gist.github.com/fabri2000779/383c759a16449da19749348c511db3a7

**Comment by parkervcp** [comment]
Your username is bad. It's in the sftp section of the server.

**Comment by parkervcp** [comment]
The username format is something like `mcserver.c380ed22`

**Comment by fabri2000779** [comment]
That wasnt the issue, it was a just installing mistake sorry. About the console it is interesting, this issue help me to understand that issue: https://github.com/pterodactyl/panel/issues/1459 we are running our servers with ubuntu 16.04 not 18.04 but looks like the Kernel version: 4.4.0-142-generic of Ubuntu 16.04 has that issue @parkervcp
