### ISSUE TITLE
Prometheus /metrics endpoint

### ISSUE THREAD

**Issue by ntimo** [pterodactyl/panel#1543]
**Is your feature request related to a problem? Please describe.**
There is currently no way to gather statistics about Pterodatyl and its daemon in a standardized way. 

**Describe the solution you'd like**
Prometheus, a very standardised way of returning metrics. A /metrics endpoint on the panel would return metrics like how many servers are active how much ram and cpu they use and so on. The could then be visualized in a Grafana board. 

**Possible metrics:**
- How many servers
- Server status
- Egg's usage
- Server RAM 
- Server CPU
- Server Storage usage
- How many users
- Page load time

**Comment by DaneEveritt** [comment]
Won't be implementing this, most of that server specific data is already available from the API if you look for a specific server. To gather all of that at once and show it in the endpoint would be a significant performance drain as we do not track that in the panel itself, it is up to the daemon to handle that.

You could also hook directly into the Daemon to get this information in a more direct manner, but going through the Panel is probably easiest.

**Comment by BurritoWrapped** [comment]
Any new considerations on this? Would like to see this implemented in the panel itself or via an exporter?
