### ISSUE TITLE
Cant edit files containing only a new line.

### ISSUE THREAD

**Issue by danny6167** [pterodactyl/panel#1544]
* Panel or Daemon: 
* Version of Panel/Daemon: Panel 0.7.16, Daemon 0.6.12
* Server's OS: Debian 9
* Your Computer's OS & Browser: Chrome 73

**Describe the bug**
The panel file manager incorrectly detects files containing only a new line as non-editable.
This is mostly seen on Ark servers as a few of the default configs are empty by default

**To Reproduce**
1. Create or upload a file containing nothing but a new line. (Don't use the panel as it trims the file content on save)
2. Go to the File Manager for that server
3. See that the file name is black and can not be clicked on to be edited.

**Expected behavior**
To be able to click on text files that contain only a new line and to be able to edit them.

**Comment by MatthewSH** [comment]
Can you provide an example file that you're having trouble with so it can be replicated exactly? Could be the way the file is created with that game server.

**Comment by danny6167** [comment]
[BrokenExample.txt](https://github.com/pterodactyl/panel/files/3241046/BrokenExample.txt)
Sample of non-editable file attached.

It appears that specifically this issue is triggered on files that contain only a single linefeed. (Hex 0x0A). The addition of a carriage return (0x0D) or additional line feeds result in an editable file.

This file results in a non-editable file.
![image](https://user-images.githubusercontent.com/388231/58703298-c99b0600-83da-11e9-9f32-de4a66e1ed45.png)

The following appear as available to edit.

![image](https://user-images.githubusercontent.com/388231/58703337-ec2d1f00-83da-11e9-9e4f-e9c84204d73e.png)
![image](https://user-images.githubusercontent.com/388231/58703332-e5061100-83da-11e9-9907-a6b7e9ad05c1.png)

**Comment by farizluqman** [comment]
Bump. Still have this issue

**Comment by arcdigital** [comment]
Since Dane closed #1863 as wontfix, closing this as well.
