### ISSUE TITLE
Deleting while server is still installing leads to residual files

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1545]
**Background:**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.12
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Winblows 10 / Chrome

**Describe the bug**
Deleting a server that is still "Installing" doesn't terminate the install container if it's still running. Nor does it delete the folder holding the configuration file, server.json

**To Reproduce**
1. Create Server
2. Delete it after a few seconds, While its still "Installing"
3. Look for the uuid in /config/servers

**Expected behavior**
It should see if the status is still "Installing" If so stop the install container, then delete the server so files arent left over.

**Comment by Sir3lit** [comment]
A good example is installing the spigot egg, as it takes like 3-10 minutes depending on system specs.

**Comment by DaneEveritt** [comment]
Should be closed in https://github.com/pterodactyl/wings/commit/1f6789cba3cb888fe61fd5cb6e3f4adc1e189459
