### ISSUE TITLE
Bungeecord - host - Bug

### ISSUE THREAD

**Issue by LinuxVieLoisir** [pterodactyl/panel#1546]
![Capture du 2019-03-31 23-46-31](https://user-images.githubusercontent.com/29429483/55295612-71ae4600-540f-11e9-888a-5889d89ecc8f.png)

Hello, I open this bug report, because when creating the Bungeecord server, it creates a config.yml file for me which is normal, however, in my case, I am forced to modify the "host: 0.0.0.0.0:25577" by putting the ip of my server for it to work, (I did some tests out of pterodactyl), only when I modify and restart my bungeecord server, pterodactyl still modifies the file to give me "host: 0.0.0.0.0:25577" So it is impossible to run my server and I am therefore forced to use screen for bungeecord.

I look forward to your response, best regards.

**Comment by parkervcp** [comment]
Just restart the server and the panel should change the address to `0.0.0.0:<port_you_assigned>`

**Comment by parkervcp** [comment]
It's also one reason I PR'd this change too - https://github.com/pterodactyl/panel/pull/1530

**Comment by LinuxVieLoisir** [comment]
but when I change the ip and restart the server it gives me the ip 0.0.0.0
I can change, but the restart makes it give me the ip 0.0.0.0

**Comment by parkervcp** [comment]
You should be 0.0.0.0 or edit the egg to not set that.

**Comment by LinuxVieLoisir** [comment]
where do we edit the egg?

**Comment by parkervcp** [comment]
in the nest area in the admin section of the panel.

**Comment by LinuxVieLoisir** [comment]
Okay, thank you.

Best resgards.
