### ISSUE TITLE
Show storage usage in the panel

### ISSUE THREAD

**Issue by ntimo** [pterodactyl/panel#1547]
**Is your feature request related to a problem? Please describe.**
Currently the only way to get the storage used by a server is to make a GET request to the `https://pterodactyl.app/api/client/servers/<ID>/utilization` API endpoint.

**Describe the solution you'd like**
The storage usage with the storage limit should be shown in the panel. This would make it super easy to know how much storage space is used. 

**Screenshot current interface**
<img width="1444" alt="Screenshot 2019-04-01 at 20 57 52" src="https://user-images.githubusercontent.com/6145026/55352444-25bbd980-54c1-11e9-9a0a-06627c1b1b17.png">

**Comment by ntimo** [comment]
That sounds interesting, but from a consumer point of view that's a bit techy. I am personally fine opening Postman and asking the API. But it would still be nice to simply take a look at the awesome UI and see it :)

**Comment by Sir3lit** [comment]
![image](https://justmyrandomstuff.com/img/IGMvxrn.jpg)

Good?

#1569

**Comment by ntimo** [comment]
@Sir3lit This looks fantastic 🙌
