### ISSUE TITLE
Wrong field ticked on node settings with private node visibility

### ISSUE THREAD

**Issue by JanDevDE** [pterodactyl/panel#1549]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.13
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Google Chrome, newest build

**Describe the bug**
When creating a private node, the field "public" in the database gets the value 0, which is expected. However, when opening the node settings afterward, you will see that "Allow Automatic Allocation" is ticked "Yes". This setting uses the "public" value in the database. If you change it to "No" and save the settings and after that to "Yes" and save the settings, you will see that the field "public" of the node in the database gets the value 1, which is expected.

**To Reproduce**
See description.

**Expected behavior**
"Allow Automatic Allocation" is the same as node visibility (Apparently.)
It should therefore be ticked "No" after the node is created on a private visibility level.

**Comment by arcdigital** [comment]
This was already fixed in the referenced PR
