### ISSUE TITLE
[Feature] Subdomain Manager

### ISSUE THREAD

**Issue by newbie029** [pterodactyl/panel#1550]
**Is your feature request related to a problem? Please describe.**
I always need to manually setup subdomain for my users

**Describe the solution you'd like**
Adding Subdomain manager feature to Pterodactyl, So the user can choose their own subdomain

**Additional context**
It will be great with Cloudflare API because all of my domains hosted on Cloudflare

**Comment by GwtLabs** [comment]
There was a similar topic already: https://github.com/pterodactyl/panel/issues/953

**Comment by parkervcp** [comment]
I was looking for that as I knew we shot this down in the past.
