### ISSUE TITLE
Error messages when creating database don't show up

### ISSUE THREAD

**Issue by SaigyoujiYuyuko233** [pterodactyl/panel#1551]
Hello, first of all thank you so much for the great Work on this Project!
But I really struggle on creating a Database.

**Background (please complete the following information):**
* Panel or Daemon: 
* Version of Panel/Daemon:  0.7.13/0.6.12
* Server's OS: Centos7 3.10.0-693.el7.x86_64 GNU/Linux
* Your Computer's OS & Browser: Google Chrome, newest build

**Describe the bug**
> PHP Version: PHP 7.2.13
> DataBase: MySQL10.1.26-MariaDB 

When I try to add a database in background, I click the "Create" button and nothing happened and the panel didn't show me the error infomation like "The xxx field is required.. " or something like that.
Then I look at the dir "storage/logs" and try to find some error infomation, but nothing there.

**To Reproduce**
1. Go to 'Admin Control'
2. Click on 'Database' on the left
3. Click on 'Create New'
4. Fill the form
5. Click on 'Create'
6. See error

**Expected behavior**
I think that will show a new database[Node] that I created then I can create a new database in server.

Thanks for all the people that work on this project and solve my problem!

**Comment by Sir3lit** [comment]
It normally means that the information is incorrect.

**Comment by SaigyoujiYuyuko233** [comment]
> It normally means that the information is incorrect.

But I fully fill the form and submit it and nothing happened....

**Comment by DaneEveritt** [comment]
Potentially related to https://github.com/pterodactyl/panel/commit/114afb86461b13d20c5bf5dcb3497721af43d475 and https://github.com/pterodactyl/panel/issues/1505.

Might just be some bad code though.

**Comment by Sir3lit** [comment]
https://github.com/pterodactyl/panel/blob/develop/app/Http/Controllers/Admin/DatabaseController.php#L129

Not sure if this is related, but there seems to be code to show an error message if the database host doesn't connect / work. ex. connection details are incorrect. but i fails to show a message or anything

**Comment by SaigyoujiYuyuko233** [comment]
> Potentially related to [114afb8](https://github.com/pterodactyl/panel/commit/114afb86461b13d20c5bf5dcb3497721af43d475) and #1505.
> 
> Might just be some bad code though.

Yeah... I think the error is similar

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/panel/commit/02ac308042ddd4480754ee2133300c411a31d76b
