### ISSUE TITLE
When database creation errors, alert message isn't shown

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1552]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.13
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chome / Windows

**Describe the bug**
When you attempt to create a database host with invalid, it fails to show the alert box with the error

**To Reproduce**
1. Attempt to make a database host with "invalid" credentials.

**Expected behavior**
Should show the alert with the mysql error but fails to do so

It's odd it shows no errors for some people but the demo works fine. 

This has been reported by others 
#1412 #1438 #1391
https://discordapp.com/channels/122900397965705216/404106122127998977/559750270561681409 https://discordapp.com/channels/122900397965705216/404106122127998977/559751082339991579
https://discordapp.com/channels/122900397965705216/404106122127998977/557349305438961696

**Comment by DaneEveritt** [comment]
Duplicate https://github.com/pterodactyl/panel/issues/1551
