### ISSUE TITLE
[Feature Request] Backup system

### ISSUE THREAD

**Issue by GoldeneK** [pterodactyl/panel#1553]
Hi, my idea is to add into pterodactyl panel something like "automatic backup system", it will backup server and server databases to the tar file or it will send it by ftp/scp to another server. (With restore function). 
Fast panel (web manager panel) have this feature: https://fastpanel.direct/

**Comment by ZeProf2Code** [comment]
https://github.com/Kong-plays/Pterodactyl-Auto-Backup

**Comment by parkervcp** [comment]
Literally already have an issue for this here - https://github.com/pterodactyl/panel/issues/114
