### ISSUE TITLE
Schedules - wrong time 

### ISSUE THREAD

**Issue by bloggy** [pterodactyl/panel#1554]
I am on: 0.7.12

The problem is that the scheduler is not using the correct times.

I have set a task to run every day at 20:00 PM
Screenshot: https://i.imgur.com/J7lb2yy.png

My ubuntu server's time is correct (19:18 PM at the moment)
https://i.imgur.com/ocUC8cI.png

But the schedule overview table looks like this:
https://i.imgur.com/GiBzA2p.png
It says 5 hours remaining (which would be 00:18 PM).

How to fix this bug?

**Comment by mayed505** [comment]
Are you sure that your Panel's timezone is set correctly to the timezone you want? Check your panel's .env file you will find a timezone.

**Comment by DaneEveritt** [comment]
I don't believe this a bug, I think its just a timezone being set incorrectly.
