### ISSUE TITLE
Use only one web panel for an other server

### ISSUE THREAD

**Issue by aziidok** [pterodactyl/panel#1555]
Hello, I'm trying to configure a web panel from an other server than the server which I want to manage. Their are in the same network but I think my core.json is not correct for that usage, can you please help me and tell me which line(s) I have to change to do that ? 

@IP of the web panel is 192.168.1.200 and the @IP of the server 'node' is 192.168.1.201. By the way, the server has been to be manage from a https web site (I got the SSL).

[core.json.txt](https://github.com/pterodactyl/panel/files/3070860/core.json.txt)

**Comment by schrej** [comment]
Please use our Discord server for support: https://discord.gg/pterodactyl
It's intended to have a single panel instance manage multiple nodes.
If you want your panel to be reachable and usable from the internet, you'll need to configure the nodes using external IPs on the panel, as the frontend talks directly to the nodes for the console for example.
