### ISSUE TITLE
Add NBT Editor to File Manager

### ISSUE THREAD

**Issue by phit** [pterodactyl/panel#1558]
**Is your feature request related to a problem? Please describe.**
NBT is a standardized binary format for Minecraft, currently I need to use 3rd party software if i just wanna do a quick edit

**Describe the solution you'd like**
add a simple NBT editor to the file manager

**Additional context**
existing node libraries exist https://github.com/sjmulder/nbt-js
and the format is fully documented https://wiki.vg/NBT

**Comment by cookieman768** [comment]
Personally this seems like a feature that wouldn’t really be worth implementing. I doubt more than a few users would actually utilize it. What is wrong with just using a FTP client and using a local tool?

**Comment by phit** [comment]
* no mobile support
* expecting the user to know about local tools
* convenience

this isn't a high priority feature IMO, but it would be still nice to have down the line

**Comment by schrej** [comment]
We are trying to keep this panel game agnostic. That's why there aren't any game specific features like mod/plugin managers or player lists integrated currently.
That also means that there probably won't be a nbt editor either.
