### ISSUE TITLE
Statistics page

### ISSUE THREAD

**Issue by OrangeJuiced** [pterodactyl/panel#156]
A statistic page with information (shown per node and service with a total too) to keep track of the overall installation would be great.
It could contain:
- Amount of servers
- Amount of suspended servers
- Online players total
- Resources assigned/in use (RAM, Diskspace)
- More things I currently can't think of.

**Comment by DaneEveritt** [comment]
Doesn't the node overpage page show this?

**Comment by OrangeJuiced** [comment]
Yes, it does here:
http://image.prntscr.com/image/a33387c6f4904044b518129874f56ad4.png

However, would love to be able to see this per service with some sort of total (also per service, and just a general total of everything) from all the nodes combined.

For example:
- To keep track of how many GB RAM of Minecraft servers are hosted per node and across all nodes.
- To keep track of how many GB RAM (all services combined) is assigned accross all nodes.

Hope this clarifies what I had it mind.

**Comment by DaneEveritt** [comment]
Ah, yes that makes sense. I'll tag this for `0.6.0`.
