### ISSUE TITLE
Start/stop/kill/restart log to see who did a specific action

### ISSUE THREAD

**Issue by JayJay1989** [pterodactyl/panel#1562]
**Is your feature request related to a problem? Please describe.**
My server got shutdown or restarted by other (admin)users. There is no way or log to see who it was.

**Describe the solution you'd like**
A shutdown/startup log containing the user who did specific button commands (e.g. start/stop/restart/kill)

**Additional context**

**Comment by ntimo** [comment]
There is already a feature request for a audit log feature :) https://github.com/pterodactyl/panel/issues/1219
