### ISSUE TITLE
[File Manager] Fix tar command for file names with colons

### ISSUE THREAD

**Issue by MarkL4YG** [pterodactyl/panel#1563]
**Background (please complete the following information):**
* Panel or Daemon: Panel (File Manager - uncompress)
* Version of Panel/Daemon: v0.7.12
* Server's OS: Ubuntu 16.04.6 LTS
* Your Computer's OS & Browser: Kubuntu 18.04 / FF66.0.3
* PHP: 7.2.16-1+ubuntu16.04.1+deb.sury.org+1
* Tar: tar (GNU tar) 1.28

**Describe the bug**
``.tar.gz`` archives cannot be extracted when their names include colons.
(Example: ``19-03-31_04:17:24.tar.gz``.) The file manager reports that the action has failed as tar exits with a non-zero exit code.  
This is due to tar trying to resolve files with colons on the network instead of the local file system. Adding the ``--force-local`` flag resolves this issue.  
(As seen on: https://blog.hqcodeshop.fi/archives/158-Tar-resolve-failed-weirness.html )

**Comment by Sir3lit** [comment]
Have you tested this personally? 

Seems you could add it to https://github.com/pterodactyl/daemon/blob/develop/src/controllers/fs.js#L361

**Comment by MarkL4YG** [comment]
I have encountered the error message and tried the tar command from the hosts shell. Sure enough, the extraction failed with a resolve error. The flag fixed that.
