### ISSUE TITLE
Eggs failing to install

### ISSUE THREAD

**Issue by alexbgameson** [pterodactyl/panel#1564]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 7.13
* Server's OS: Ubuntu
* Your Computer's OS & Browser: Windows 10 Chrome

**Describe the bug**
Suddenly every egg is failing to install on every one of my 10 nodes.
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

**To Reproduce**
1. Go to creat new server.
2. Fill in all required information.
3. Scroll down to egg select and minecraft egg.
4. See install error

**Expected behavior**
The server should fail to install or not install at all.

**Comment by parkervcp** [comment]
@alexbgameson This gives us no logs and this is apparently working for everyone but you.

Run both of the following commands please.
`tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99`
`cd /srv/daemon/ && npm run diagnostics`

**Comment by icedmoca** [comment]
I have the same issue. As many others.
Logs from both commands:
[https://bin.ptdl.co/lzc8e/](https://bin.ptdl.co/lzc8e/)
[https://hastebin.com/ubolurexap](https://hastebin.com/ubolurexap)

**Comment by parkervcp** [comment]
@icedmoca This needs to be done in discord. not here.
