### ISSUE TITLE
Block user from changing username

### ISSUE THREAD

**Issue by SeaLife** [pterodactyl/panel#1566]
**Is your feature request related to a problem? Please describe.**
As we'r going to use this for our company to provide a awesome control panel for our customers, we have to auto generate users and servers. Everything ist working good so for except for:
If you create a User with a pattern (ex: customerId as Username) and the User itself changes that afterwards - our System will create a new User.
For some reason there is a "external_id" field in the Ptero4J API in the UserCreate function but if i set this to the customerid the server is returning 422 (validation error).

**Describe the solution you'd like**
A option to disable the user's ability to change the userrname.
(The same problem goes for the email address if i wanted to use this instead so...)

**Describe alternatives you've considered**
- Implementing the Option mentioned above
- Implementing or make the external_id working (or am i doing something wrong with it?)

**Additional context**

So this is my function (java code) to create a new User if not exists - hopefully it helps you guys to understand my problem.

```
    private Integer createUserIfNotExist(OrderItem orderItem) {
        List<User> userList = adminInterface.getAdminAPI().getUsersController().getUsers(orderItem.getCustomerId().toString());

        if (userList.size() == 0) {
            String password = (String) orderItem.getProperties().getOrDefault("initialPassword", orderItem.getCustomerId().toString());

            log.info("Creating User {} (provider={})", orderItem.getCustomerId(), "pterodactyl");
            User user = adminInterface.getAdminAPI().getUsersController().createNew()
                    .setEmail(orderItem.getCustomerId().toString() + "@example.com")
                    .setUsername(orderItem.getCustomerId().toString())
                    .setPassword(password)
                    .setFirstName(orderItem.getCustomerId() + "")
                    .setLastName("Customer")
                    .setLanguage("de")
                    .execute();

            // orderItem.getProperties().remove("initialPassword");

            orderItemRepository.save(orderItem);

            return user.getId();
        }

        return userList.get(0).getId();
    }
```

Regards
SeaLife

**Comment by ZeProf2Code** [comment]
and `.setExternalId()` isn't working ? Can you please describe  your error?

**Comment by SeaLife** [comment]
If i use "setExternalId(<some numeric>)" then the Panel returns a 422 HTTP Error code. Unfortunately Ptero4J isnt logging the response json so i cant really see the error the panel is returning.
@ZeProf2Code 

Maybe the validation is set to something like "sometimes:string" ? This would cause the error as Ptero4J is transmitting this value as a integer.

**Comment by DaneEveritt** [comment]
I don't plan on implementing the ability to restrict username changing. If you'd like this ability it is probably best handled as custom code.

If you start at [`UserUpdateService.php`](https://github.com/pterodactyl/panel/blob/develop/app/Services/Users/UserUpdateService.php) and work backwards you should be able to find the few places handling editing, and then remove the ability and update the UI to express this as well.
