### ISSUE TITLE
[Feature Request] Packs Extending

### ISSUE THREAD

**Issue by ProJaCore** [pterodactyl/panel#1567]
I have normally no problem with adding additional content. e.g. CS:S Materials to my Garrysmod Server and others but i feel like this panel needs a remarkable change with packs.

Packs should act more like dynamic resources:::

- they run on one or more nodes native or scheduled (scripts.....)
- they have a like servers a mounted folder on their node

When we add Packs to Game servers then it should behave like:
- pack folders will mount before game start to the root of the game servers (RO or W)
- while the pack runs its script e.g. git pull or wget or anything ... it can be mounted on to multiple servers.(local same node)
- rather than extract the pack it will be mounted and then can be accessed by the server.

It has so many pros and opens up so many new possibilities than i can dream of it.

also packs should get renamed into worms (because it feeds the pterodactyls?) just kidding  
---
To Give you an Idea

Lets say you have a stupid game and you push via git new stupid patterns so the game can already without restarting access the new patterns thanks to the self updating resource

**Comment by DaneEveritt** [comment]
The current pack implementation is a nightmare as it is. It was quickly implemented to fill a small void that install scripts have effectively solved.

I think this might be better served if we completely _remove_ the packs system, or rather build a new system that allows you to define scripts that run at different stages for a server. These would be defined in the egg themselves. For example: install, reinstall, on-start, on-stop (maybe, seems less important).

**Comment by DaneEveritt** [comment]
I'm going to close this request because there are a bunch already open, and this is on my radar, but isn't going to happen for quite awhile at this rate.
