### ISSUE TITLE
POST /api/application/nodes/*/allocations returns an empty string, doesn't work without alias

### ISSUE THREAD

**Issue by Kushfield** [pterodactyl/panel#1568]
The API endpoint /api/application/nodes/*/allocations seems to have some issues for POST requests.

Not including an alias should be an option, but it results in a 500 error:
```
-bash-4.2$ curl -X "POST" "https://pterodactyl.my-servers.com/api/application/nodes/1/allocations" \
>      -H "Content-Type: application/json" \
>      -H "Authorization: Bearer key" \
>      -H "Accept: application/vnd.pterodactyl.v1+json" \
>      -d '{"ip": "123.123.123.123", "ports": ["10059"]}'
{
    "errors": [
        {
            "code": "ErrorException",
            "status": "500",
            "detail": "An error was encountered while processing this request."
        }
    ]
}
-bash-4.2$ 
```
> production.ERROR: ErrorException: Undefined index: alias in /var/www/pterodactyl/app/Http/Requests/Api/Application/Allocations/StoreAllocationRequest.php:43

If an alias is included, the allocation seems to be created fine, but the request doesn't return anything:
```
-bash-4.2$ curl -X "POST" "https://pterodactyl.my-servers.com/api/application/nodes/1/allocations" \
>      -H "Content-Type: application/json" \
>      -H "Authorization: Bearer key" \
>      -H "Accept: application/vnd.pterodactyl.v1+json" \
>      -d '{"ip": "123.123.123.123", "alias": "my-server.my-servers.com", "ports": ["10059"]}'
-bash-4.2$ 
```

**Comment by JanDevDE** [comment]
Is an alias set within the panel? (Reason I ask that is because I wonder if this error will only be thrown if an alias is set.)

**Comment by Kushfield** [comment]
> 
> 
> Is an alias set within the panel? (Reason I ask that is because I wonder if this error will only be thrown if an alias is set.)

I'm not sure what exactly you mean, but:
If I include an alias in the request, then the new allocation is created fine, and the alias is also shown in the panel. However, the response for the request is just an empty string (I would expect it to return information about the new allocation).
If I do not include an alias in the request, then it results in an error.

**Comment by parkervcp** [comment]
It looks like an alias is required. The panel should be responding with a "code": "required" error and not a 500.

**Comment by DaneEveritt** [comment]
The alias isn't actually required though, so... :|

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/panel/commit/2198269a65456079e0ef54b919b2efba1c0a75ed
