### ISSUE TITLE
stuck at starting if server starts too fast

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#1570]
**Background (please complete the following information):**
* Panel/Daemon: Daemon
* Versions
* Panel: 0.7.13
* Daemon:  0.6.12
* Server's OS: CentOS 7 running alpine container for the daemon
* Your Computer's OS & Browser: Linux / Firefox

**Describe the bug**
When starting a server it will show as starting change to online and then back to starting.

```
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 9M / 1024M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
:/home/container$ ./fragbot
2019/04/27 21:30:07 loading configs from files
2019/04/27 21:30:07 loading bot config
2019/04/27 21:30:07 loading channel config
2019/04/27 21:30:07 loading channel config
2019/04/27 21:30:07 all configs loaded
2019/04/27 21:30:07 Bot is now running. Press CTRL-C send 'shutdown' to exit.
[Pterodactyl Daemon] Server marked as ON
2019/04/27 21:30:07 starting discord connections
[Pterodactyl Daemon] Server marked as STARTING
2019/04/27 21:30:07 discord service connected
```

**To Reproduce**
1. Have a server that starts really fast. (https://github.com/parkervcp/eggs/tree/master/bots/discord/fragbot)

**Expected behavior**
The server should go online and stay online.

**Comment by parkervcp** [comment]
So this is still an issue. Just making sure it's still being seen.

![image](https://user-images.githubusercontent.com/1207679/64299035-aa65c480-cf45-11e9-9b2c-ebba3b231fa3.png)

**Comment by DaneEveritt** [comment]
Won't fix, Nodejs daemon is in life-support only mode.
