### ISSUE TITLE
Reinstall server via schedules

### ISSUE THREAD

**Issue by PixelNotFound** [pterodactyl/panel#1572]
**Is your feature request related to a problem? Please describe.**
Currently you have to update your server manually with pterodactyl by hitting the reinstall server button on the admin panel.

**Describe the solution you'd like**
I would like to see a way to add reinstall to schedules, this would be a great way to keep your server up to date!

**Describe alternatives you've considered**
I dont know any except for manually reinstalling the server everyday, otherwise i would be on an outdated version.

**Additional context**

**Comment by Sir3lit** [comment]
I feel just making it a button on the client side would be sufficient. Unless you're expecting updates weekly or even daily

**Comment by parkervcp** [comment]
Or you know you could write your own docker container for this specific thing that checks for update on restart like the steam containers do.

**Comment by DaneEveritt** [comment]
Yeah not adding this to the scheduled tasks, seems like a recipe for disaster and a very uncommon scenario. :)

Potentially if reinstalls are more involved in the future, but right now it would not accomplish much.

**Comment by erxson** [comment]
useful feature
