### ISSUE TITLE
[Feature Request] API Endpoint to get console feed in real-time

### ISSUE THREAD

**Issue by ZeProf2Code** [pterodactyl/panel#1574]
**Is your feature request related to a problem? Please describe.**
Probably, we are needing a API Endpoint to receive the feed of the console in real-time

**Describe the solution you'd like**
A API Endpoint (we need that we can access it with a client api key) to get the in-real time feed of a server's console

**Describe alternatives you've considered**
Nothing excepts embedding the console but we need to be logged.

**Additional context**
https://github.com/rubentalstra/Pterodactyl-app

**Comment by DaneEveritt** [comment]
Won't be implementing, the goal of the API is not to make it so an external service and replace the panel itself.
