### ISSUE TITLE
Documentation missing copy/paste text for core.json 

### ISSUE THREAD

**Issue by MercerK** [pterodactyl/panel#1576]
I'm following the guide here: https://pterodactyl.io/daemon/installing.html. When I get to "Configure Daemon", I do not see a section to "copy and paste" core.json.

Would you be able to provide the default example in the documentation, as something that can be literally copied and pasted, versus an image?

**Comment by parkervcp** [comment]
![Screen Shot 2019-05-01 at 3 06 39 PM](https://user-images.githubusercontent.com/1207679/57036600-c5849880-6c22-11e9-9a6c-99d441af34df.png)

We say you need to copy and paste the config. Or to use the auto-deploy command.

**Comment by parkervcp** [comment]
More specifically - 
![Screen Shot 2019-05-01 at 3 07 49 PM](https://user-images.githubusercontent.com/1207679/57036645-e8af4800-6c22-11e9-8475-514526deeb08.png)

**Comment by MercerK** [comment]
What code block though? The one in the image?

Isn't "Auto Deployment" gated behind a working panel? I tried skipping the step, but it is looking for core.json.

**Comment by parkervcp** [comment]
You need a working panel to generate a core.json in the first place.

**Comment by MercerK** [comment]
I'm assuming to start the panel, you need to run "npm start". But in order for that to run, you need a "core.json", which doesn't seem to exist in the directory on fresh installations.

So I'm a bit lost, unless the intention is that for fresh installations, users are suppose to manually copy and paste that text from the image.

**Comment by parkervcp** [comment]
This is for a daemon. Not for a panel.

**Comment by TonyS95** [comment]
As parker said and if it doesn't exist just run nano /srv/daemon/config/core.json and paste the block into there.

**Comment by parkervcp** [comment]
The docs clearly sparate the two. The daemon uses node js. The panel is php based and uses a webserver to serve it's content.

**Comment by MercerK** [comment]
@parkervcp Thanks, I understand where I went wrong. However, when you use doc's search or scan the page for "installation", only one section shows installation. Panel didn't show "Installation" unless you drill down on "Getting Started". When you google "pterodactyl installation", it also takes you to the daemon page.
