### ISSUE TITLE
Using 2 machine for 1 site 

### ISSUE THREAD

**Issue by LewaIngame** [pterodactyl/panel#1577]
Hello guys / girl y bave à problem i went To connect m'y first machine to m'y second with the node and i dont no how To make it

**Comment by LewaIngame** [comment]
And i add the ip to fcqdn and bot work

**Comment by TonyS95** [comment]
You can just install daemon on the second machine

**Comment by LewaIngame** [comment]
Alredy maked

**Comment by parkervcp** [comment]
Put them on different ports

**Comment by LewaIngame** [comment]
On two different the port can not change

**Comment by LewaIngame** [comment]
I went To connect the two machine To two site equal

**Comment by parkervcp** [comment]
I have no idea what you mean by any of this anymore.

**Comment by DaneEveritt** [comment]
This conversation is not suited for Github, as it _explicity_ stated in the issue template you used that says issues using the software *should not be reported here*.
