### ISSUE TITLE
Problem with Daemon and timezone

### ISSUE THREAD

**Issue by DockerBee** [pterodactyl/panel#1580]
We use GitHub issues only to discuss about Pterodactyl bugs and new features. For
this kind of questions about using Pterodactyl, please visit our Discord for assistance: https://pterodactyl.io/discord

DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**Comment by Sir3lit** [comment]
Umm I'm lost there is not detail what so ever in this issue...?

**Comment by DockerBee** [comment]
This is what the logs say:


> pteronode@0.6.12 start /srv/daemon

> node src/index.js | node_modules/bunyan/bin/bunyan -o short


21:23:18.581Z  INFO wings: + ------------------------------------ +

21:23:18.582Z  INFO wings: | Running Pterodactyl Daemon v0.6.12    |

21:23:18.582Z  INFO wings: |        https://pterodactyl.io        |

21:23:18.582Z  INFO wings: |  Copyright 2015 - 2019 Dane Everitt  |

21:23:18.582Z  INFO wings: + ------------------------------------ +

21:23:18.582Z  INFO wings: Loading modules, this could take a few seconds.

21:23:18.860Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...

21:23:18.911Z  INFO wings: Configuring user pterodactyl (id: 500) as the owner of all server files.

21:23:18.914Z  INFO wings: Configuring timezone file location...

21:23:18.915Z FATAL wings: A fatal error caused the daemon to abort the startup. (additional={})

    Error: No suitable timezone file was located on the system.

        at Async.parallel (/srv/daemon/src/helpers/timezone.js:53:29)

        at /srv/daemon/node_modules/async/dist/async.js:3888:9

        at /srv/daemon/node_modules/async/dist/async.js:473:16

        at iterateeCallback (/srv/daemon/node_modules/async/dist/async.js:992:24)

        at /srv/daemon/node_modules/async/dist/async.js:969:16

        at /srv/daemon/node_modules/async/dist/async.js:3885:13

        at Fs.access.err (/srv/daemon/src/helpers/timezone.js:46:21)

        at FSReqWrap.oncomplete (fs.js:135:15)

21:23:18.915Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.


And I cannot find what seems to be the problem here

**Comment by DockerBee** [comment]
Hello,

This is the error I am getting from the daemon:


> pteronode@0.6.12 start /srv/daemon

> node src/index.js | node_modules/bunyan/bin/bunyan -o short


21:23:18.581Z  INFO wings: + ------------------------------------ +

21:23:18.582Z  INFO wings: | Running Pterodactyl Daemon v0.6.12    |

21:23:18.582Z  INFO wings: |        https://pterodactyl.io        |

21:23:18.582Z  INFO wings: |  Copyright 2015 - 2019 Dane Everitt  |

21:23:18.582Z  INFO wings: + ------------------------------------ +

21:23:18.582Z  INFO wings: Loading modules, this could take a few seconds.

21:23:18.860Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...

21:23:18.911Z  INFO wings: Configuring user pterodactyl (id: 500) as the owner of all server files.

21:23:18.914Z  INFO wings: Configuring timezone file location...

21:23:18.915Z FATAL wings: A fatal error caused the daemon to abort the startup. (additional={})

    Error: No suitable timezone file was located on the system.

        at Async.parallel (/srv/daemon/src/helpers/timezone.js:53:29)

        at /srv/daemon/node_modules/async/dist/async.js:3888:9

        at /srv/daemon/node_modules/async/dist/async.js:473:16

        at iterateeCallback (/srv/daemon/node_modules/async/dist/async.js:992:24)

        at /srv/daemon/node_modules/async/dist/async.js:969:16

        at /srv/daemon/node_modules/async/dist/async.js:3885:13

        at Fs.access.err (/srv/daemon/src/helpers/timezone.js:46:21)

        at FSReqWrap.oncomplete (fs.js:135:15)

21:23:18.915Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.

Something with the timezone, but I cannot find what the problem is.
I am running docker on CENTOS7

Regards,

Jaap

**Comment by parkervcp** [comment]
I am going to request you post the error logs in code blocks...

using the
```
    ```
    format
    ```
```

**Comment by MatthewSH** [comment]
1) This is an issue you should probably go to support on the Discord server for
2) This is a daemon related issue, not related to the panel itself.
3) what is your OS?

The daemon (reference [here](https://github.com/pterodactyl/daemon/blob/develop/src/helpers/timezone.js#L53)) looks for `/etc/timezone` or `/etc/localtime`. If, for some reason, they do not exist or can not be access it will throw this error. `localtime` is just a symlink to to `/usr/share/zoneinfo` ([here's my system](https://i.imgur.com/KzwERpZ.png)). `timezone` just contains the same information (for example, mine contains the line `Etc/UTC`. 

Make sure both these files exist and the service has proper access to them.

**Comment by parkervcp** [comment]
If I am guessing correctly this is the same person that runs their daemon in a container and is having issues with timezones there.

**Comment by DaneEveritt** [comment]
Please read and follow the issue template when reporting bugs.
