### ISSUE TITLE
Deploy server from repository

### ISSUE THREAD

**Issue by hornta** [pterodactyl/panel#1581]
**Is your feature request related to a problem? Please describe.**
I am having my minecraftserver hosted in a git repository and I would like to hook up that repository to my pterodactyl server so that whenever I make a change, pterodactyl will stop the server, pull down the latest changes, run build scripts or whatever and then start the server again.

My current workflow is using SSH to enter the `/srv/daemon-data/xxxxx` and then run git pull and commands to build, it would be easier and safer to have it automated with webhooks.

- Automated deploys
- Manual deploys per branch
- Scriptable deploy(maybe running schedules before a deploy begins)
- Pass environment variables into container

**Comment by MatthewSH** [comment]
You do have a couple options with something like this...
1) Custom egg. I don't work with eggs, so I'm not sure; but you can mess around with the entrypoint and so on.
2) There's an API with most all of this. The only thing I could imagine you needing to write is the way to update the repo and handle any merges, etc. That's on you though. Most all of it is available via API.

**Comment by hornta** [comment]
But I would like this to be a part of the panel itself, having it as an Advanced mode or something.

**Comment by MatthewSH** [comment]
I don't think, personally, this would be a good feature to add to the panel itself. Usually these kind of systems are for web development and so on. I don't know many people who actively use Git for game server configuration and since this can be  done with eggs and API as it is...you can easily create an Ptero addon for this or just create a custom egg tailored to you needs.

**Comment by parkervcp** [comment]
I don't see this being helpful and the egg system can handle this already. I see no reason to actually implement this at the panel level.
