### ISSUE TITLE
Unable to modify settings even with LOAD_ENVIRONMENT_ONLY=false 

### ISSUE THREAD

**Issue by JoshuaWalsh** [pterodactyl/panel#1582]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.7.13
* Server's OS: Debian Container running on Docker CE on Windows 10 via Hyper-V
* Your Computer's OS & Browser: Windows 10, Firefox Developer Edition v67.0b18 (64-bit)

**Describe the bug**

When I go into ACP > Settings I get the following message:

> Your Panel is currently configured to read settings from the environment only. You will need to set `LOAD_ENVIRONMENT_ONLY=false` in your environment file in order to load settings dynamically. 

I have configured `LOAD_ENVIRONMENT_ONLY=false` within my .env file, but this message persists. I have also tried configuring `APP_ENVIRONMENT_ONLY=false` based on [this page](https://pterodactyl.io/panel/configuration.html#reporting-all-exceptions).

Despite these changes, the message still appears.

```
root@9fa71a2f5f9c:/var/www/html# php -v
PHP 7.2.18 (cli) (built: May  8 2019 03:11:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

**To Reproduce**
1. Append the following to the bottom of your .env file:
```
LOAD_ENVIRONMENT_ONLY=false
APP_ENVIRONMENT_ONLY=false
```

2. Sign in to the ACP
3. Navigate to the Settings section
4. Observe that the warning message appears
5. Try changing a setting and saving the change
6. Observe that the setting returns to its previous value, the save failed silently

**Expected behavior**
I would expect for setting the property to make the message go away, and allow saving properties.

It's likely that I'm doing something wrong, but I'm not really sure what to try. I've done what the message tells me. I have tried restarting php-fpm after changing .env, but it doesn't make a difference.

**Comment by MatthewSH** [comment]
The actual key, reference [here](https://github.com/pterodactyl/panel/blob/0.7-develop/config/pterodactyl.php#L14), is `APP_ENVIRONMENT_ONLY` and defaults to false. So it should get rid of the notification. However, a variety of things are cached in production.

Try clearing the cache via Artisan.
```
php artisan view:clear
php artisan optimize:clear
php artisan config:clear
```

**Comment by JoshuaWalsh** [comment]
Okay, I'm setting APP_ENVIRONMENT_ONLY=false and I've cleared the cache, but the notification still appears.

I did notice that my nginx worker processes don't have permission to write to the .env file. But based on "Some of these settings are also stored in the database and will override settings found in the environment file" I believe this shouldn't matter, right?

**Comment by jordann7778** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/61425931/94338734-78aa1a80-ffec-11ea-84f7-deb367c26369.png)

**Comment by jordann7778** [comment]
Help me plz

**Comment by MatthewSH** [comment]
@jordann7778 this is a closed issue, please visit the Discord server if you need help past what is already provided in this issue. It's over a year old.
