### ISSUE TITLE
Error while attempting to fetch list of Eggs from the panel

### ISSUE THREAD

**Issue by Pankraz01** [pterodactyl/panel#1584]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v0.6.12
* Server's OS: Ubuntu
* Your Computer's OS & Browser: MacOS & Safari

**Describe the bug**

Could not start via `npm start`

Panel:
`PHP 7.2.17-0ubuntu0.18.04.1 (cli) (built: Apr 18 2019 14:12:38) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.17-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
`

Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
`Linux CreepansServer 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

`Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 9
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-48-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.604GiB
Name: CreepansServer
ID: XSEC:WHSF:A3OD:4ZQT:ICWI:IKIK:ODNS:SSVD:B4NU:PUEV:5BA5:KSXD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support`

**To Reproduce**
1. Go to `cd /srv/daemon/`
2. Type `npm start`
3. Wait
4. Error: `npm start

> pteronode@0.6.12 start /srv/daemon
> node src/index.js | node_modules/bunyan/bin/bunyan -o short

20:05:58.957Z  INFO wings: + ------------------------------------ +
20:05:58.959Z  INFO wings: | Running Pterodactyl Daemon v0.6.12    |
20:05:58.959Z  INFO wings: |        https://pterodactyl.io        |
20:05:58.959Z  INFO wings: |  Copyright 2015 - 2019 Dane Everitt  |
20:05:58.960Z  INFO wings: + ------------------------------------ +
20:05:58.960Z  INFO wings: Loading modules, this could take a few seconds.
20:05:59.653Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
20:05:59.775Z  INFO wings: Configuring user pterodactyl (id: 1003) as the owner of all server files.
20:05:59.781Z  INFO wings: Configuring timezone file location...
20:05:59.781Z  INFO wings: Checking container networking environment...
20:05:59.798Z  INFO wings: Found network interface for daemon: pterodactyl_nw
20:05:59.798Z  INFO wings: Ensuring correct network interface for containers...
20:05:59.824Z  INFO wings: Networking gateway detected as 172.18.0.1 for interface: pterodactyl0.
20:05:59.828Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
20:05:59.837Z FATAL wings: A fatal error caused the daemon to abort the startup.
    Error: Error while attempting to fetch list of Eggs from the panel.
        at Request [as _callback] (/srv/daemon/src/controllers/service.js:95:31)
        at Request.self.callback (/srv/daemon/node_modules/request/request.js:185:22)
        at emitTwo (events.js:126:13)
        at Request.emit (events.js:214:7)
        at Request.<anonymous> (/srv/daemon/node_modules/request/request.js:1161:10)
        at emitOne (events.js:116:13)
        at Request.emit (events.js:211:7)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/request/request.js:1083:12)
        at Object.onceWrapper (events.js:313:30)
        at emitNone (events.js:111:20)
    --
    additional: {
      "responseCode": 404,
      "requestURL": "http://localhost/api/remote/eggs"
    }
20:05:59.837Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.`

**Expected behavior**
I expected to start the daemon. Because the web interfaces showed `Gateway Timeout`

**Additional Logs**
[https://hastebin.com/vohudevuqu](url)

Docker Version: `Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false`

**Comment by parkervcp** [comment]
This should be handled on Discord and not here. 

FYI your panel url is set to localhost which isn't what it should be.

**Comment by Pankraz01** [comment]
how do I change this?

**Comment by Frederick-huizinga** [comment]
yes how to change this
