### ISSUE TITLE
500 error when querying server api with include=subusers 

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#1589]
**Background (please complete the following information):**
* Panel or Daemon: panel
* Version of Panel/Daemon: 0.7.13 
* Server's OS: CentOS 7
* Your Computer's OS & Browser: Fedora 30 - Firefox Quantum (version 67)

**Describe the bug**
When running a GET request against `api/application/servers/<server_id>?include=subusers` you get a 500 error.
Please provide additional information too, depending on what you have issues with:
Panel: `php -v`
PHP 7.2.15 (cli) (built: Feb 20 2019 20:17:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15, Copyright (c) 1999-2018, by Zend Technologies

**To Reproduce**
1. run curl "https://<panel_address>/api/application/servers/<server_with_subusers>?include=subusers"   -H "Authorization: Bearer "   -H "Content-Type: application/json"   -H "Accept: Application/vnd.pterodactyl.v1+json"   -X GET

**Expected behavior**
I expected a relationship section with user IDs located in an array similar to how allocations are returned.

**Comment by MatthewSH** [comment]
@parkervcp can you provide any error logs associated with it?

**Comment by parkervcp** [comment]
https://bin.ptdl.co/eu4wl/
