### ISSUE TITLE
Warn when using outdated wings.js versions

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#159]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [x] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [ ] Bug or Issue
- [x] Feature Request
- [ ] Enhancement
- [ ] Other

The Panel should somehow notify the user if the wings.js version is to old for the current panel version (maybe to new as well?). Maybe just on the nodes overview page.

**Comment by DaneEveritt** [comment]
closed in Pterodactyl/Daemon@90cd2b6 as well as Pterodactyl/Panel@90cd2b6
