### ISSUE TITLE
SMTP Issues

### ISSUE THREAD

**Issue by eatingenderman89** [pterodactyl/panel#1593]
* Panel or Daemon: 
* Version of Panel/Daemon: Panel - 0.7.13 Daemon - 0.6.12 (Currently Latest Versions)
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows Server 2019 - Chrome 

The bug is that when I try to setup SMTP the check completes and the test email sends, I receive it in my spam box and then I save the settings. It won't send an email for password reset or send the user an password in the mail, etc.
Panel: `PHP 7.3.5-1+ubuntu16.04.1+deb.sury.org+1 (cli)` (the PHP version in use).
Daemon: `Linux fr02.lightfordac.com 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` and `Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-43-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.604GiB
Name: fr02.lightfordac.com
ID: Q5QK:AAWZ:26ZI:3CP3:A4F4:GFJF:WQYV:22IW:UZVQ:DUNW:H4MX:LBHC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support`
Sorry if it got a little long.
(your kernel version and information regarding docker)

1. Go to 'Pterodactyl Admin Panel & Click On Settings'
2. Click on 'Mail & Fill In The Information, And press save.'
3. Press reset password and put your email, nothing happens.
**Expected behavior**
I was expecting the reset password email to come in my emails inbox.

**Comment by lazarsn** [comment]
Issue fixed
php-doc was missing
Nya
