### ISSUE TITLE
"Host: localhost. is not in the cert's altnames:"

### ISSUE THREAD

**Issue by bwestcott-1** [pterodactyl/panel#1596]
Daemon, Version: 0.2.0
Server OS: Ubuntu 18.04
Computer OS & Browser: Mac OSX Mojave, Chrome

I know that issues including SFTP, SSL, etc should be dealt with in the discord but unfortunately I was unable to get any help there. 
My panel and daemon run on the same machine and have been working flawlessly over SSL since 3 weeks ago when I first set them up.
I hadn't touched any configuration in daemon or panel itself for over a week when this occurred. It started as a failed authorization over SFTP and when I restarted my server, I could no longer start the daemon. Ive tried to find a solution to this online but haven't found anything. 
Ive tried renewing my certs but that didn't help. 

Here is the diagnostic:
https://ptero.co/zelawafega

Panel logs show no errors related to this, in fact the panel is working fine as of now. 

Whats odd about this is that there are a ton of SFTP requests at the top of the log which suggests that someone was trying to get into my system. I don't know If this has anything to do with my issue but I wanted to clarify that those SFTP requests were not my doing.

**Comment by bwestcott-1** [comment]
Im now getting a "stdout maxBuffer exceeded" when I try to run diagnostics on the daemon.

Heres the paste of the log:
https://pastebin.com/YEnY2KVx

Sorry, I'm still learning how all this works

**Comment by DaneEveritt** [comment]
This is not a bug with this software, please use our [Discord](https://pterodactyl.io/discord) for support.

**Comment by bwestcott-1** [comment]
did you read what I said? Ive been in the discord support chat and I've raised my question numerous times and haven't even gotten a response.

**Comment by viaone-chenderson** [comment]
That's one way to get someone to help you, @bwestcott-1
