### ISSUE TITLE
[Core Enhancement] Removing the daemon API from the frontend

### ISSUE THREAD

**Issue by Xervia** [pterodactyl/panel#1604]
**Is your feature request related to a problem?**
I wanted to use Pterodactyl to replace our setup of two dedicated nodes for games and a virtual node as web servers, all limited by firewalls, to ensure that only allowed ports can communicate with each other, this is completely impossible with Pterodactyl from the beginning, because the demons are queried in the frontend with jQuery. In particular, it is not possible to add any security layer with a firewall in a collocation with vSwitches and VLAN or a VPN to connect them directly. It's not only annoying to have to deal with it, but in my opinion it's a security problem at the highest level because it gives everyone direct access to the nodes via the daemon API.

**Describe alternatives you've considered**
I temporarily fixed it with a proxy for all APIs of daemons via the web server and added something like a mod_secure server directly above it, but that's no solution to the problem.

**Describe the solution you'd like**
The daemon API should be called directly in the panel code, this can be achieved without changing much, the panel accesses an internal page of the panel via jQuery, which loads the contents of the daemon APIs via curl, so that the daemon APIs are proxied over the panel directly, then you can also drop the letsencrypt certificates and add a real user authentication with certificates between panel and daemon.

**Comment by parkervcp** [comment]
The panel uses a websocket for the console. It's a direct connection instead of proxying it through the panel entirely. That and the file manager also uses the same thing.

**Comment by Xervia** [comment]
I can understand the file manager, but there are also ways to change it. But that's not the point here, it should be possible to restrict the communication between the nodes and the panel without leaving the ports globally open, since the panel couldn't fully communicate with the node after the restriction.

**Comment by sergiz** [comment]
This will be changed in 0.8, so everything will go through panel.

**Comment by schrej** [comment]
This isn't "a security problem at the highest level". The daemon api still requires valid authentication. Hiding the panel<->daemon traffic behind a firewall is also possible, at least with dns. It's entirely possible to use a VPN, you just need to add the nodes to it as well.
But as sergiz said, we'll do most of it through the panel with the upcoming version 0.8. Whether it will be feasible to route the websockets required by the console through the panel is still up for discussion.
