### ISSUE TITLE
Daemon can't fetch list of Eggs from the panel

### ISSUE THREAD

**Issue by collintje01** [pterodactyl/panel#1605]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v0.6.12
* Server's OS: Ubuntu 18.04.1
* Your Computer's OS & Browser: Windows 10 / chrome, firefox

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
` (the php version in use).
Daemon: `Linux venetius 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
` and `docker info` (your kernel version and information regarding docker)

**To Reproduce**
I don't know how to reproduce this I wanted to start a website on another vm with another ip and then suddenly my daemon got knocked out

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
Expected behavior is my server just working and not dying instantly.
Here are my daemon logs:
https://hastebin.com/efexabayur

Hope someone can help me thnx in advance.
p.s. please make the support system better my questions always get ignored in discord

**Comment by DaneEveritt** [comment]
This is not a bug with this software, please use our [Discord server](https://pterodactyl.io/discord) for assistance.

**Comment by collintje01** [comment]
Would be nice if someone ever responded to me on discord :/

**Comment by parkervcp** [comment]
We have a bot that will literally answer most of the questions you have as long as you supply logs.

**Comment by collintje01** [comment]
yea but if I use the bot and it returns this : 

> It looks like the daemon is unable to reach the panel. This can be due to a multitude of reasons, so you'll need to wait for a human to help you our here. However, while you wait, is the URL being connected to correct?

Then I just get ignored
