### ISSUE TITLE
Teamspeak Server Update 3.8.0 won't work with current pterodactyl/core:glibc

### ISSUE THREAD

**Issue by arajdon** [pterodactyl/panel#1606]
```
=== Server Release 3.8.0 28 May 2019

Important: This release requires GNU C library (glibc) 2.17 or later on Linux. If you need to
           check which version of glibc is installed on your system, you can use `ldd --version`,
           which usually comes with any glibc installation.

...
```
Source: https://forum.teamspeak.com/threads/139966-Release-TeamSpeak-Server-3-8-0

Using `docker run -it quay.io/pterodactyl/core:glibc ash` I've ran the command `ldd --version`:
```
musl libc (x86_64)
Version 1.1.19
```

Already tested the 3.8.0 Server Version. I can confirm that it's not working properly.

```
Segmentation fault (core dumped)
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 139
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
```

**Comment by parkervcp** [comment]
can I ask that you try to change the base image to `quay.io/parkervcp/pterodactyl-images:debian_base`

**Comment by arajdon** [comment]
`debian_base` does not exist. I've used `base_debian`. :)

Yes. Can confirm it's working.

**Comment by Corprosss** [comment]
hey i have the same probleme how can i change the base image please somebody help
