### ISSUE TITLE
Select all for each permission section

### ISSUE THREAD

**Issue by zxFirefly** [pterodactyl/panel#1610]
**Is your feature request related to a problem? Please describe.**
Adding perms for many people in a short period can be very tedious with the current method

**Describe the solution you'd like**
Adding a select all button to each section rather then being for all perms

**Describe alternatives you've considered**
none

**Additional context**
http://prntscr.com/o36qip

on another note I see that someone made a thread about creating an account and assigning there perms and what servers that have access to rather then adding them to each server, how do I go about doing this if it's possible.

**Comment by DaneEveritt** [comment]
Done in beta. ✅
