### ISSUE TITLE
Out of place file name

### ISSUE THREAD

**Issue by para-dise** [pterodactyl/panel#1611]
* Panel or Daemon:  Pterodactyl panel, edit file subsection
* Version of Panel/Daemon:  0.7.13
* Server's OS: Ubuntu 19.04
* Your Computer's OS & Browser: Ubuntu 16.04, Google Chrome Version 73.0.3683.86 (Official Build) unknown (64-bit)

**Describe the bug**
If an edited file contains many slashes in the path (e.g. `//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////test.txt` the file name will go out of the normal screen size and under the "Return to file manager" button.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the control panel for one of the servers
2. Go to file management
3. As the file name, set many slashes and then the real file name. Eg: `///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////theactualfilename.txt`
4. Save the file
5. Look at the positioning of the file name once it's displayed.

Side note: This can be reproduced by directly accessing the file URL. Eg:
`https://pterodactyl.url/server/server_id_here/files/edit////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////example.txt

**Expected behavior**
It would be more ethical to prevent the file name from going behind the button, and instead limiting the amount of characters displayed and adding 3 dots at the end. 
For example, "//////////////////////////////////////...`

Visual Proof:
![Screenshot from 2019-06-20 01-17-57](https://user-images.githubusercontent.com/20133381/59809623-41cd5b00-92f9-11e9-8923-345e05d57cda.png)

**Comment by parkervcp** [comment]
So what you are saying is that file names that are long won't fit correctly?

Do you have many servers that have file names that long?

**Comment by para-dise** [comment]
> So what you are saying is that file names that are long won't fit correctly?
> 
> Do you have many servers that have file names that long?

:joy: no I don't. But it'd be conventional to not display extra large file names.

**Comment by DaneEveritt** [comment]
I'm not concerned about this type of bug, it requires you actually trying to break things to break.
