### ISSUE TITLE
HARDCORE bug with bungeecord

### ISSUE THREAD

**Issue by INTmAker** [pterodactyl/panel#1620]
Bungeecord do not want start I add 10 server THEY freeze on start no error and they have tag starting. Spigot server works good.

**Comment by MatthewSH** [comment]
Have you talked to anyone in support yet?

**Comment by schrej** [comment]
If you want this reopened, please write a proper issue. If you want people to spend their time, at least invest some of your own.
But this might be a user error, so please get support on https://discord.gg/pterodactyl first
