### ISSUE TITLE
Nginx 403 forbidden error after  installation

### ISSUE THREAD

**Issue by Nuc1eoN** [pterodactyl/panel#1625]
I have installed the pterodactyl panel following the documentation closely. However I am getting an 403 forbidden error when trying to enter my page.
I have tried to get help for weeks on the discord channel but nobody could help.
This is what I have found in the laravel logs:
`production.NOTICE: A query exception was encountered while trying to load settings from the database: SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `settings`)`

So as it seems maybe something is wrong with the credentials, but I am pretty sure I have entered them correctly. However if not, how can I verify or reenter them?

**Comment by parkervcp** [comment]
Without knowing your discord name I can say that I know for a fact that the bot would have responded saying your database was refusing connections.

This is not an issue caused by the panel but by a configuration issue.

Please keep support to the pterodactyl discord.

**Comment by Nuc1eoN** [comment]
Ok thanks. I just have wondered because nobody knew how to help.
