### ISSUE TITLE
Subusers API

### ISSUE THREAD

**Issue by Kolkies** [pterodactyl/panel#1631]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
It would be nice if you can create, edit and view subusers in servers via the api.

**Describe alternatives you've considered**
No alternative suggestions

**Additional context**
It is handy for when you want to add many users to a server as subuser.

**Comment by DaneEveritt** [comment]
Will be implemented in 0.8.

**Comment by Kolkies** [comment]
Nice!
