### ISSUE TITLE
Allow node tokens to be generated with API

### ISSUE THREAD

**Issue by steak-sauce** [pterodactyl/panel#1632]
**Is your feature request related to a problem? Please describe.**
This is a critical need for automating node deployment. Without this, many workarounds are needed to generate this token programmatically.

**Describe the solution you'd like**
node_token=$(curl "https://panel/api/application/nodes/token" \
-H "Authorization: Bearer shhhitsasecrete" \
-H "Content-Type: application/json" \
-H "Accept: Application/vnd.pterodactyl.v1+json" \
-X GET)

**Describe alternatives you've considered**
At this time, we're "logging into" the panel via cli to generate the token. This is not as secure as it requires a full admin user rather than using API permissions.

**Comment by DaneEveritt** [comment]
Deployment tokens now simply utilize API keys for the application API, so there is no need for a node deployment specific token. The panel still creates one which is really just a Node read-only key, however, any API key with node permissions will work in the new beta releases.
