### ISSUE TITLE
NBT Editor in File Manager

### ISSUE THREAD

**Issue by TheBlueKingLP** [pterodactyl/panel#1634]
**Is your feature request related to a problem? Please describe.**
/
**Describe the solution you'd like**
I would like to have a NBT editor built in to the file manager of the panel, maybe something like https://github.com/irath96/webNBT/

I have seen the issue #1558, but it is from 3 years ago, so I think the opinions from the developer team has changed?
**Describe alternatives you've considered**
Download the file I want to edit and reupload it, which is rather inconvenient
**Additional context**
This is not a important feature thus I could wait for quite some time, but it will be nice to see it got implemented in the future.

**Comment by schrej** [comment]
Just because the other issue is quite old, doesn't mean we've changed our mind. We still try to keep pterodactyl free of game specific features. A NBT editor certainly is game specific, so it won't be implemented, sorry.
