### ISSUE TITLE
error when using mass action to delete files

### ISSUE THREAD

**Issue by catalystsitaly** [pterodactyl/panel#1635]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.14
* Server's OS: Ubuntu Server 18.04
* Your Computer's OS & Browser: MacOS Majave & Chrome

**Describe the bug**

When using Mass Action -->Delete Files in File Management, the confirm to delete window won't pop up, it seems nothing happening.
When check the console of Chrome, There is an error generated when I clicked Delete Files button:
<img width="769" alt="屏幕快照 2019-07-12 下午6 43 48" src="https://user-images.githubusercontent.com/38031024/61122731-23f8ad80-a4d5-11e9-8245-6c2a33274583.png">

**To Reproduce**
1. Go to 'Panel File Management'
2. Click on 'Mass Action'
3. Click on 'Delete Files'
3. Open Chrome console

**Comment by ljavanbeek** [comment]
Already known, #1614
