### ISSUE TITLE
add an update option like teamspeak 3

### ISSUE THREAD

**Issue by jakub96124124** [pterodactyl/panel#1637]
it would be good to add the update function to the new version
Teamspeak 3 
source games atd

**Comment by JanDevDE** [comment]
@jakub96124124 We already have an update function. You just need to restart your server and it'll check for updates.

**Comment by jakub96124124** [comment]
I have the current version and nowhere I see the function

**Comment by JanDevDE** [comment]
@jakub96124124 You just need to restart your server and it'll check for updates. There is no button or similar.

**Comment by jakub96124124** [comment]
but I just need an addon that does not force the server to restart

**Comment by JanDevDE** [comment]
There are plenty of requests like that, see #1292 #1303 and #578

**Comment by JanDevDE** [comment]
So basically the only way to do it right now is to restart your servers.
