### ISSUE TITLE
Issues with timezones in containers

### ISSUE THREAD

**Issue by Smartjer123** [pterodactyl/panel#1638]
The time and timezone are fully correct. In the server containers the /etc/timezone  is correct but when you run date in the container it shows UTC and not Eastern standard time and the time is very off. I have already asked in the discord like 3 times and no one can give me an answer....

**Comment by JanDevDE** [comment]
This is a docker issue, not a panel, nor most likely a daemon issue.

**Comment by Smartjer123** [comment]
So is there anything i can do ?

**Comment by parkervcp** [comment]
What server is this for?

**Comment by Smartjer123** [comment]
It does it for minecraft and gmod havent checked my teamspeak or anything else..

**Comment by kgns** [comment]
have you tried putting "timezone_path": "/etc/localtime" in your core.json file?
like this:
  "docker": {
    "socket": "/var/run/docker.sock",
    "autoupdate_images": true,
    "timezone_path": "/etc/localtime"
  },

**Comment by Smartjer123** [comment]
I didnt try that yet.. Will do that now to see if it works

**Comment by Smartjer123** [comment]
Mine doesnt have auto update images should I add that as well ?

**Comment by Smartjer123** [comment]
I put that in there but it doesnt work. I am running ubuntu server 18.04. The local time file looks like this:
https://pastebin.com/FC12ksgJ

**Comment by Smartjer123** [comment]
Nvm I put /etc/timezone not /etc/localtime it works though. Thank you !
