### ISSUE TITLE
Enviornment service does not update existing servers when adding to the configuration.

### ISSUE THREAD

**Issue by Kurounin** [pterodactyl/panel#1639]
**Is your feature request related to a problem? Please describe.**
Add ALLOCATION_LIMIT environment variable to be used in the startup scripts/images.

**Describe the solution you'd like**
Have ALLOCATION_LIMIT environment variable in docker container

**Describe alternatives you've considered**
I tried adding to `Services/Servers/EnvironmentService.php` the allocation limit by adding the line `'ALLOCATION_LIMIT' => 'allocation_limit',` to the array returned by `getEnvironmentMappings()` but it doesn't seem to be taken into account

**Comment by sergiz** [comment]
Add it to the 'environment_variables' in config/pterodactyl.php. You also need to rebuild container to take effect.

**Comment by Kurounin** [comment]
Tried adding it to that file as well and rebuilt the container, but I'm still not getting it as an environment variable.
I checked the available vars by running `sudo docker exec -it ba9d4c27e5fd printenv`

**Comment by DaneEveritt** [comment]
Try running `php artisan config:clear` first and see if that fixes it?

**Comment by Kurounin** [comment]
In `app/Services/Servers/EnvironmentService.php` I have
```php
    private function getEnvironmentMappings(): array
    {
        return [
            'STARTUP' => 'startup',
            'P_SERVER_LOCATION' => 'location.short',
            'P_SERVER_UUID' => 'uuid',
            'ALLOCATION_LIMIT' => 'allocation_limit',
        ];
    }
```
In `config/pterodactyl.php` I have
```php
    'environment_variables' => [
        'ALLOCATION_LIMIT' => 'allocation_limit',
    ],
```
I **cleared opcache for cli & php-fpm** and ran in pterodactyl root:
```
php artisan config:clear
php artisan cache:clear
php artisan view:clear
systemctl restart wings
```
I **rebuilt container**, but when I check `printenv` I'm only getting:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=cafdd518-55d0-489a-b789-c3a1a4720b7b
TERM=xterm
SRCDS_MAP=de_dust2
STEAM_ACC=xxxx
SRCDS_APPID=740
STARTUP=./srcds_run -game csgo -console -port {{SERVER_PORT}} +ip 0.0.0.0 +map {{SRCDS_MAP}} -strictportbind -norestart +sv_setsteamaccount {{STEAM_ACC}}
P_SERVER_LOCATION=xxxx
P_SERVER_UUID=cafdd518-55d0-489a-b789-c3a1a4720b7b
SERVER_MEMORY=512
SERVER_IP=x.x.x.x
SERVER_PORT=27015
DEBIAN_FRONTEND=noninteractive
HOME=/home/container
```

Is there something I'm missing?

**Comment by sergiz** [comment]
You don't need to add ALLOCATION_LIMIT to EnvironmentService.php.

Anyway, try commenting out

`            'P_SERVER_LOCATION' => 'location.short',`

and re-do the steps. Then with `printenv` again and report back.

**Comment by Kurounin** [comment]
I know there isn't a need to have it in both places, but I'm trying all possible variants.
I changed `app/Services/Servers/EnvironmentService.php` to:
```php
    private function getEnvironmentMappings(): array
    {
        return [
            'STARTUP' => 'startup',
            //'P_SERVER_LOCATION' => 'location.short',
            'P_SERVER_UUID' => 'uuid',
            //'ALLOCATION_LIMIT' => 'allocation_limit',
        ];
    }
```
I changed `config/pterodactyl.php` to:
```php
    'environment_variables' => [
      'P_SERVER_CREATED_AT' => 'created_at'
    ],
```
Ran in `/var/www/pterodactyl/`
```
php artisan config:clear
php artisan view:clear
php artisan cache:clear
opcache-clear
systemctl restart wings
```
I rebuilt server container & restarted it. `docker exec -it 35819c89e07a printenv` gives me the same vars:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=cafdd518-55d0-489a-b789-c3a1a4720b7b
TERM=xterm
SRCDS_MAP=de_dust2
STEAM_ACC=xxx
SRCDS_APPID=740
STARTUP=./srcds_run -game csgo -console -port {{SERVER_PORT}} +ip 0.0.0.0 +map {{SRCDS_MAP}} -strictportbind -norestart +sv_setsteamaccount {{STEAM_ACC}}
P_SERVER_LOCATION=xxx
P_SERVER_UUID=cafdd518-55d0-489a-b789-c3a1a4720b7b
SERVER_MEMORY=512
SERVER_IP=x.x.x.x
SERVER_PORT=27015
DEBIAN_FRONTEND=noninteractive
HOME=/home/container
```
Seems that any change I do, to config files or code itself is ignored.

**Comment by Kurounin** [comment]
I did a test to see if it's some other cache I'm missing and modified `resources/themes/pterodactyl/server/index.blade.php` changing `Start` button text to `Start now` and after refreshing the webpage (no need to clear any laravel view cache) I see the `Start now`.

I also tried displaying the current config environment_variables, by changing `app/Http/Controllers/Server/ConsoleController.php` to
```php
    public function console(Request $request): View
    {
        $this->setRequest($request)->injectJavascript(['config' => [
            'console_count' => $this->config->get('pterodactyl.console.count'),
            'console_freq' => $this->config->get('pterodactyl.console.frequency'),
            'env' => $this->config->get('pterodactyl.environment_mappings', []),
        ]]);

        return view('server.console');
    }
```
In this case even after running 
```
php artisan config:clear
php artisan view:clear
php artisan cache:clear
opcache-clear
```
when navigating to https://xxx/server/cafdd518 in the DevTools `window.Pterodactyl.config` returns only `{console_count: "10", console_freq: "200"}`

**Comment by sergiz** [comment]
Since P_SERVER_LOCATION doesn't go away when you comment it out, there must be something else wrong.

I would try first with the most obvious one; make a fresh and non-related copy of the panel and new fresh node. Then comment out P_SERVER_LOCATION and see, if it's properly missing from the container.

**Comment by Kurounin** [comment]
I created a new VM with Debian 10 and installed everything fresh. The bug manifests itself like this:
- once a server is created the environment variables are not changed no matter what caches are deleted, even if a new panel is setup or if server is rebuild, even reinstalled
- if a new server is created it will get current variables from `app/Services/Servers/EnvironmentService.php`

Can I create a PR to add the ALLOCATION_LIMIT variable to `app/Services/Servers/EnvironmentService.php` ? since I want to modify the startup scripts (and in the case of minecraft the dockerfile) to take into account this limit when starting the server.

**Comment by DaneEveritt** [comment]
You can open a PR adding it, no promises it gets merged, just make sure to include all of the information about why it is necessary and such.

Also sounds like the bug here is that EnvironmentService isn't running correctly on existing servers?

**Comment by Kurounin** [comment]
Ok, will try and make a PR this weekend.

Yes, that seems to be the bug. Existing services don't use the EnvironmentService anymore. Is the daemon caching the environment variables after creating the server or once created the daemon no longer calls the panel to get environment variables even if rebuilding?

**Comment by DaneEveritt** [comment]
I believe this is fixed in the beta from my testing since we fetch an updated environment each time the server is booted rather than trying to cache it on the daemon.
