### ISSUE TITLE
Specify Server Options (ex startup command lines) via control panel using .json files.

### ISSUE THREAD

**Issue by Zendrex** [Pterodactyl/Panel#164]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [ ] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [ ] Bug or Issue
- [x] Feature Request
- [x] Enhancement
- [ ] Other

## What Happens

Have an ability to make a .json file which the panel can read, then interpreted into options on the control panel which can trigger things like add additional startup parameters and so forth.
## Example Config

Have a file named something like <panel service id>_params.json in the services directory.

Within it, have the following:
```
{
    "1": {
        "name": "Enable VAC Security",
        "return": "boolean",
        "type": "startup-paramter",
        "type-value": " -secure",
        "default-value": "true"
    },

    "2": {
        "name": "Max Player Count",
        "return": "int",
        "type": "startup-parameter",
        "type-value": " +maxplayers {int}",
        "default-value": "20"
    }
}
```

**Comment by Zendrex** [comment]
The reason I bring this up in the way that I do is so that users can modify these on the fly is allowed to from their own control panel. People love buttons and features to give more configuration, why not give it to them?

**Comment by DaneEveritt** [comment]
I'll tag this as a feature, but we're re-doing the current service/option setup for `0.6.0` so this might just end up in there in a similar fashion.

**Comment by schrej** [comment]
This should be integrated into the wings services I would say.

**Comment by DaneEveritt** [comment]
Closing this since I have a slightly different plan for how this will work.
