### ISSUE TITLE
Add the ability to start gameservers on boot.

### ISSUE THREAD

**Issue by Smartjer123** [pterodactyl/panel#1640]
**Is your feature request related to a problem? Please describe.**
This is probably a problem that lots of people have especially people that self host because the majority of people don't have 100% uptime and would like there servers to startup automatically when a power outage occurs or a system crash/ if they accidentally shut of the system forcefully. Especially if they don't have internet access or a device with them to turn the server back on/ don't even know its down.

**Describe the solution you'd like**
Make it so game servers that where turned on in the event of crash or a power outage turn back on when the server boots up.

**Describe alternatives you've considered**
You can also make it so you can turn it on for certain servers instead of all of them if you would like.
**Additional context**
If you end up adding this thank you and I bet you many other people will like it as well!

**Comment by parkervcp** [comment]
This is a duplicate of #136

**Comment by Smartjer123** [comment]
Oh sorry !
