### ISSUE TITLE
Auto restart frozen game servers

### ISSUE THREAD

**Issue by Synkstar** [pterodactyl/panel#1641]
**Is your feature request related to a problem? Please describe.**
This is a problem when you are hosting servers that can be frozen pretty easily like a gmod server. If someone manages to freeze your server with props in the case of gmod it will stay frozen until someone manually kills and starts back up the server this is a big problem if the owner of the server is away or busy and can not start back up the server so it can end up staying frozen for a very long time and once a server is frozen no new connections will be accepted and the server will appear offline to the players. 

**Describe the solution you'd like**
Maybe something like lgsm has were it can detect if it can't reach the server and after a certain amount of time it will auto restart the server.

**Additional context**
If you add this thank you and I bet people that host sandbox games or games that cant get frozen will be thankful as well !

**Comment by parkervcp** [comment]
This would require monitoring the server via some method like rcon or otherwise. This would be game specific and we don't do that. I would recommend a monitoring system that makes API calls to the panel.

**Comment by Smartjer123** [comment]
Maybe someone could make a addon to the panel or a whole other piece of software that does this or does one already exist?

**Comment by Smartjer123** [comment]
Or this can maybe be implemented into the eggs for the individual servers and in the egg they can make it possible to include how it will check if the server is crashed?!?

**Comment by parkervcp** [comment]
Same issue. Would require updates to support detecting crashes on specific games.

This is a job for a monitoring system that can fire off API calls.

Something like nagios or Prometheus.

**Comment by DaneEveritt** [comment]
I'm okay implementing something like this down the road, its pseudo game-specific, but still logical for a... game panel. :)

**Comment by MasterLuke117** [comment]
please do, i would even round up some funding for you to start coding the feature, it would help us out immensely.

heres a working auto start on boot for pterodactyl panel servers: https://github.com/Alteiria/pterodactylAutoStart

**Comment by Smartjer123** [comment]
Actually I know how to check if a srcds game server is up with python. Just don't know how to send an api call to restart it when its down. Also I would have to make it check if the status is online because when it freezes it pins at 100% and doesnt respond to any requests. Then if it is online send the kill command then the start command like 10 seconds after

**Comment by Smartjer123** [comment]
Here is a start to it. If help will be greatly appreciated. [https://github.com/Smartjer123/Srcds-crash-detector](url). This could act as like a temp solution until its actually implemented

**Comment by TheFate** [comment]
It seems like pterodactyl has some functionality of detecting crashes and auto-restarting, but not in many cases with certain freezes.

It also seems to depend on the type of server. For example, any of our source dedicated servers (srcds) do not get automatically restarted in most crashes/freezes. However, our Minecraft dedicated servers do.

It would be a great feature to have if this panel would be able to watch and make sure that the server is online and working fine, and if not, immediately force restart the server. This would be a universal solution for every server type. There are some types of freezes where the dedicated server just stops functioning properly completely. Having this feature built-in to pterodactyl would minimize overhead and optimize both performance and the complexity of the setup.

I hope that this feature gets implemented. Does anyone currently have a third-party working solution for this that actually automatically restarts the server?

**Comment by matthewpi** [comment]
The current system does not detect freezes unless it causes the process to exit, in the event of a process becoming unresponsive the daemon will try to operate like it is a normal process, only the kill action will actually do anything.

This also requires game specific implementation and will not be in 0.7 and will most likely only be added to 1.0.0.

Just be patient as stuff like this takes time to develop but also test properly, there is also still a huge list of want-to-haves for 1.0.0.

**Comment by Synkstar** [comment]
Right now I am using a python script that checks the server using python-valve. This isn't integrated with pterodactyl panel, it just sends an api request to kill then start the server if it doesn't respond 3 times in x amount of time.

**Comment by TheFate** [comment]
@Synkstar Would you mind sharing that script or publishing it to GitHub? Would be a quite useful workaround until this feature is added. I noticed you linked a script a few months back but that doesn't have the API request portion which is the more complex part.

**Comment by DaneEveritt** [comment]
Won't be implementing this.

**Comment by FlowerShopGuy** [comment]
> Right now I am using a python script that checks the server using python-valve. This isn't integrated with pterodactyl panel, it just sends an api request to kill then start the server if it doesn't respond 3 times in x amount of time.

Hello, can you share with this script?
