### ISSUE TITLE
OpenJ9

### ISSUE THREAD

**Issue by 1stian** [pterodactyl/panel#1646]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem, rather a more efficient java.

Not sure what more to bring here.. But OpenJ9 has a smaler footprint etc, reduced ram(Better GC) usage and CPU usage.

So is there a way to implement OpenJ9?

https://www.eclipse.org/openj9/

**Comment by Wqrld** [comment]
It is possible, for instance deploys does this but i'm guessing there is a reason that pterodactyl hasn't implemented it yet?

**Comment by parkervcp** [comment]
@1stian can you try out `quay.io/parkervcp/pterodactyl-images:debian_openjdk-8-openj9` and let me know how it goes?

**Comment by 1stian** [comment]
> @1stian can you try out `quay.io/parkervcp/pterodactyl-images:debian_openjdk-8-openj9` and let me know how it goes?

This worked great! Thank you.

**Comment by mechoriet** [comment]
![image](https://user-images.githubusercontent.com/4313219/61948364-f0735400-afa7-11e9-81c7-5c82c690f854.png)
![image](https://user-images.githubusercontent.com/4313219/61948377-fd904300-afa7-11e9-88fb-a66866e69aa0.png)

@parkervcp can confirm this has a 100mb+ less footprint/base memory usage
the servers on the left with the original quay.io/pterodactyl/core:java image
the right is the quay.io/parkervcp/pterodactyl-images:debian_openjdk-8-openj9 image 

both graphs are from the same server data cause we have 2 of them
so a good test

the only thing i get with the new image is 
> [13:17:52 WARN]: [HolographicDisplays] Unable to get a stack trace element, please inform the developer. You will only see this error once and a fallback method will be used.
java.lang.NoSuchMethodException: java.lang.Throwable.getStackTraceDepth()

but its not gamebreaking from what i see the holographicdisplays are displaying as normal

gonna keep it running for a few days and will report back on what i noticed if thats okay

**Comment by mechoriet** [comment]
3 hours in update
left server memory 444mb
right server memory 210mb

will keep running it like this for a day
then ill run them with the same launch options just to reassure its not from the launch options
for the same length

**Comment by mechoriet** [comment]
24 hour update post:
![image](https://user-images.githubusercontent.com/4313219/61994126-cb99e200-b076-11e9-8538-3b1074f2f69e.png)
![image](https://user-images.githubusercontent.com/4313219/61994135-e4a29300-b076-11e9-9652-256abea6744f.png)

left server memory 519mb
right server memory 245mb
just for extra context about the servers running:
the two servers are both loginservers meaning alot of player connecting/disconnecting,
so lots of objects are being created/released every minute.

now gonna run both servers with default Startup Command : 
`java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}`
for both servers for the same time span.
just to check if the launch options dont matter or they actually make a impact on the usage

**Comment by mechoriet** [comment]
3hours in update:
![image](https://user-images.githubusercontent.com/4313219/61995913-87b2d700-b08e-11e9-90e6-31e5bb9603fa.png)
![image](https://user-images.githubusercontent.com/4313219/61995920-99947a00-b08e-11e9-83d3-603c7fb67d9d.png)

left server memory 418mb vs 444mb(last test)
right server memory 215mb vs 210mb(last test)

so a slight decrese vs increase in memory but very minimal

right server is with the openj9 image

**Comment by mechoriet** [comment]
i was surfing the net last night
and found something that could potentially scrape off more footprint
[Google Distroless image](https://github.com/GoogleContainerTools/distroless)
and maybe base memory usage

what it does a very small base image (smaller then alphine i think)
[Base Image](https://github.com/GoogleContainerTools/distroless/blob/master/base/README.md)

havent tested this yet if i could get this to work with ptero cause the way ptero starts the program is different then how that image does it

this is a openjdk9 image
[openjdk9/11 image](https://github.com/GoogleContainerTools/distroless/blob/master/java/README.md)

and this is the openjdk11 example container(it was upgraded)
[the example Dockerfile](https://github.com/GoogleContainerTools/distroless/blob/master/examples/java/Dockerfile)

**Comment by mechoriet** [comment]
@parkervcp 
am i right that this gets injected always to the jvm
https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/8/jdk/debian/Dockerfile.openj9.releases.slim#L68

if so then the second test is kinda redundant to do

**Comment by parkervcp** [comment]
I am using the openj9 image as a base. So if it's in there then it is injected every time.

**Comment by mechoriet** [comment]
> I am using the openj9 image as a base. So if it's in there then it is injected every time.

okaj then ignore my second test of the same server

ill try to do it in a more block/action active server see the difference there
can`t test like the test above cause there is only one server of it

so the result will be a graph of heapmemory of last 24hr and the test 24hr

is that accurate data for you @parkervcp or do you need the docker memory value`s?

example of the graph:
![image](https://user-images.githubusercontent.com/4313219/61999599-66211200-b0c5-11e9-96b8-51a0760c2373.png)

**Comment by mechoriet** [comment]
this is the 48hour graph
the redline in the middle represends the restart point

![image](https://user-images.githubusercontent.com/4313219/62048418-1d747080-b20d-11e9-9ff2-cc1624dd42b4.png)

hope this gives a good amount of info it this image is goodgood

**Comment by DaneEveritt** [comment]
Thanks, I believe our plan is to release an office OpenJ9 image independent of the current egg so that people can switch to it on their own. :)

**Comment by parkervcp** [comment]
This is resolved by the existence of this now - https://github.com/pterodactyl/images/tree/java-8-openj9

**Comment by melvyn2** [comment]
Paper is planning to drop java <11 support, and the only java 11 image is the HotSpot one; is an openj9 image planned?

**Comment by M-AlNoaimi** [comment]
@melvyn2 To be honest, when I was building the Velocity egg I did some testing with J11 & J15 both OJ9 and HotSpot and hot spot won in stability and startup time. However feel free to do some testing in paper's eggs using the images quay.io/discoversquishy/dockerimages:openjdk-11-openj9 // quay.io/discoversquishy/dockerimages:openjdk-11-hotspot

I'd guess the best way to make this happen if you think it's worth it after testing would be to make a PR in @parkervcp's egg repo & images repo if the images aren't updated.
