### ISSUE TITLE
[Question] What are packs?

### ISSUE THREAD

**Issue by chronicals** [pterodactyl/panel#1647]
I've got a question regarding packs, as I haven't found any documentation about them. As of my understanding, you can upload an archive into a pack and users using a specific egg, can choose such a pack. But what's the pack feature exactly for? How do you use it/what do you use it for?

Sadly there is no mention what so ever in the documentation and the discord community doesn't know anything about it.

**Comment by sergiz** [comment]
It's kinda unfinished feature. The pack is extracted to the server directory prior to running the install script. The end-user control over packs is not implemented.

**Comment by DaneEveritt** [comment]
It was a feature added early on in the development cycle to try and extend some functionality the community wanted, it never really got built out properly but now there are some power users making extensive use of them so the feature has remained.

At this point they are basically just pre-install files that the daemon pulls from the Panel before running an installer script.

**Comment by chronicals** [comment]
Ok thanks, that resolved my question! Thank you for the information!
