### ISSUE TITLE
manifest.json file missing

### ISSUE THREAD

**Issue by DefaultFreelancer** [pterodactyl/panel#1649]
After panel installation and following the instruction i got this error message:

./assets/manifest.json (View: /media/default/StorageData/Work/Clients/Projects/Jacob/panel/resources/themes/pterodactyl/templates/wrapper.blade.php) (View: /media/default/StorageData/Work/Clients/Projects/Jacob/panel/resources/themes/pterodactyl/templates/wrapper.blade.php)

How may i fix this, i've noticed that this manifest.json file is missing from initial version of system on github. 

Any help, please? 
Thank you in advance!

**Comment by MatthewSH** [comment]
I can almost 100% guarantee that you're installing the development branch, when you shouldn't be unless you're planning on actively developing the project or you know what you're doing.

If you're looking to install the panel, just follow the guide at https://pterodactyl.io and it won't steer  you wrong. All commands are pre-written.

If you're looking for the 0.7 development branch, that's on `0.7-develop`

**Comment by DefaultFreelancer** [comment]
Ok, thank you,
But, i'm interested in development as well.

Thank you!
