### ISSUE TITLE
Download a file directly from the web in the file manager

### ISSUE THREAD

**Issue by OrangeJuiced** [pterodactyl/panel#165]
It would be pretty useful to able to input a URL and directly download a file to a selected location in the server. This would be done through a button in the file manager.

Example use case:
- User downloading a world or map to their server.

**Comment by matthewpi** [comment]
This is somewhat implemented.  The Panel and Wings API endpoints exist, just the UI doesn't.

**Comment by trenutoo** [comment]
Implemented in V2 3c2a6e11360001cbc33d170af2fa6cabe7866481

![image](https://user-images.githubusercontent.com/10975908/129606785-f66b1e46-9d35-4f0e-abf5-1d15310c9c0c.png)

**Comment by BIntelligent** [comment]
2022? i dont see the UI?
