### ISSUE TITLE
JLine 3

### ISSUE THREAD

**Issue by clrxbl** [pterodactyl/panel#1651]
Unsure if this should've been a bug report or a feature suggestion.
**Is your feature request related to a problem? Please describe.**
https://github.com/parkervcp/eggs/pull/261

**Describe the solution you'd like**
Include Pterodactyl console support for JLine 3 

**Describe alternatives you've considered**
There's a workaround that has been implemented for the Paper egg but other eggs like Waterfall will have to be changed soon too.

**Additional context**
![image](https://user-images.githubusercontent.com/28601081/61816984-c443c000-ae4d-11e9-9b05-148bb6108a7f.png)

![image](https://user-images.githubusercontent.com/28601081/61816992-c9087400-ae4d-11e9-969e-0304da5ca63d.png)

Recently, Paper merged a commit to update & change some of their console stuff, https://github.com/PaperMC/Paper/commit/fa8b4994ac00ad60298d727feffe607398b1a081 e.g., updating TCA + JLine and replacing JNA with Jansi. This slightly breaks Pterodactyl's console a bit (notice how it adds >... to every line and that on the second screenshot, the entered commands aren't visible but are just random unicode characters.)

A workaround was implemented (2 java arguments) in the Paper egg but JLine 3 will probably be used in more than Paper (e.g. Waterfall and others) sooner or later.

**Comment by DaneEveritt** [comment]
Closed since this is fixed in the egg now.
