### ISSUE TITLE
Change default database collation

### ISSUE THREAD

**Issue by TheSpixxyQ** [pterodactyl/panel#1655]
I am setting up database for my server which will also work with web registration but I have problems with Czech characters like "ě, š, č, ř, ž...", instead of "š" it writes "Å¡" etc.
I noticed that panel creates database with default character set latin1 and collation latin1_swedish_ci, so all new tables will have this collation too.
I'd like to see default utf8 (or any other universal character set) so I don't have to manually convert everything.
Thank you!

**Comment by DaneEveritt** [comment]
It defaults to `utf8mb4`: https://github.com/pterodactyl/panel/blob/develop/config/database.php#L42
