### ISSUE TITLE
Unable to register database hosts in 0.7.14

### ISSUE THREAD

**Issue by MarkL4YG** [pterodactyl/panel#1656]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel 0.7.14
* Server's OS: Ubuntu 16.04.6 LTS & 18.04.2 LTS
* Your Computer's OS & Browser: KUbuntu 18.04.2 LTS & FF 68.0.1
  * Content blocking is disabled, no ad-block or other security plugin installed
  
We want to move host systems and need to correctly migrate our DBs, servers and the panel.

**Describe the bug**
Registering a new database host failes without any message, exception or warning.

**To Reproduce**
1. Go to 'admin -> databases'
2. Click on 'Create new '
3. Fill information
4. Submit

**Expected behavior**
The page reloads and the new database host shows up. _OR_, any occurred error is shown.

**Actual behavior**
The form is submitted, the backend returns HTTP302, the page reloads but no new datatabase host has been registered.  
I have enabled debugging & looked into the logs. No exception or warning is shown whatsoever.

**Comment by MarkL4YG** [comment]
// As expected, this turned out to be an issue on our end: The database wasn't reachable because of an additional firewall rule on the side of our hosting provider. However, I'll keep this open as the connection error should've been logged in the first place.

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/panel/commit/02ac308042ddd4480754ee2133300c411a31d76b

**Comment by MarkL4YG** [comment]
Thank you very much! 🙂
