### ISSUE TITLE
Database host field only allows IPs

### ISSUE THREAD

**Issue by OrangeJuiced** [Pterodactyl/Panel#166]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [ ] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [ ] Bug or Issue
- [ ] Feature Request
- [ ] Enhancement
- [x] Other

The database host field when adding a database server does not allow a hostname to be entered. It currently only allows IP addresses.

**Comment by DaneEveritt** [comment]
closed in f6275058d06a9bc2b751d4ce1ef268ab7d5edb98
