### ISSUE TITLE
Cannot read property of undefined & "invalid namespace" after reinstalling a dedi with the same configuration

### ISSUE THREAD

**Issue by MrDienns** [pterodactyl/panel#1660]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: Panel 0.7.13, Daemon 0.6.12
* Server's OS: Ubuntu 19.04 / Debian 10
* Your Computer's OS & Browser: MacOS, Firefox
* Name R: Linux ubuntu 5.0.0-21-generic #22-Ubuntu SMP Tue Jul 2 13:27:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Docker info:
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-21-generic
 Operating System: Ubuntu 19.04
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.37GiB
 Name: ubuntu
 ID: UBYN:XEKZ:4LMO:KOBU:VSMZ:YCBC:2YNU:OIVH:IOFD:6XTA:Y5DY:FXOG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Describe the bug**
A little background. I was facing timeout issues of Docker on this machine, but I could not reproduce the issue on any other machine so I decided to make a backup of my `/srv/daemon-data` and reinstall the dedicated machine (from SoYouStart), used the same `core.json` from the panel. I've followed the installation steps like I always do, and everything goes fine; Docker gets installed, NPM installs its things (though a lot of deprecation warnings it seems), Let's Encrypt makes a certificate, it's shown as healthy in the Node page in the panel, etc.

However, I cannot use any of my MC servers. In the panel, trying to restart things, the panel returns with a red error box saying "invalid namespace".
See image: https://i.imgur.com/4sxJmTR.png

Talked in the Discord for support, one suggestion was to try and reinstall the server from the panel. However, trying to do so results in this Javascript error in wings:
```
07:20:24.793Z  INFO wings: + ------------------------------------ +
07:20:24.794Z  INFO wings: | Running Pterodactyl Daemon v0.6.12    |
07:20:24.794Z  INFO wings: |        https://pterodactyl.io        |
07:20:24.794Z  INFO wings: |  Copyright 2015 - 2019 Dane Everitt  |
07:20:24.794Z  INFO wings: + ------------------------------------ +
07:20:24.794Z  INFO wings: Loading modules, this could take a few seconds.
07:20:25.017Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
07:20:25.029Z  INFO wings: Creating keypair to use for SFTP connections.
07:20:27.158Z  INFO wings: Configuring user pterodactyl (id: 998) as the owner of all server files.
07:20:27.160Z  INFO wings: Configuring timezone file location...
07:20:27.161Z  INFO wings: Checking container networking environment...
07:20:27.167Z  WARN wings: No isolated network interface for containers was detected, creating one now.
07:20:42.199Z  INFO wings: Successfully created new network (pterodactyl_nw) on pterodactyl0 for isolated containers.
07:20:42.200Z  INFO wings: Ensuring correct network interface for containers...
07:20:42.213Z  INFO wings: Networking gateway detected as 172.18.0.1 for interface: pterodactyl0.
07:20:42.213Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
07:20:42.343Z  INFO wings: Checking existing eggs against Panel response...
07:20:42.682Z  INFO wings: Beginning server initialization process.
07:20:42.685Z  INFO wings: Configuring websocket for daemon stats...
07:20:42.686Z  INFO wings: Configuring internal SFTP server...
07:20:42.703Z  INFO wings: Pterodactyl Daemon is up-to-date!
07:20:42.703Z  INFO wings: Pterodactyl Daemon is now listening for secure connections on 0.0.0.0:8080
07:21:33.748Z FATAL wings: Cannot read property 'reinstall' of undefined (path=/v1/server/reinstall, method=POST, server=617d77ff-09f1-4a80-9795-d130f79b39fa)
    TypeError: Cannot read property 'reinstall' of undefined
        at auth.allowed (/srv/daemon/src/controllers/routes.js:267:31)
        at AuthorizationMiddleware.allowed (/srv/daemon/src/middleware/authorizable.js:60:24)
        at RouteController.reinstallServer (/srv/daemon/src/controllers/routes.js:264:19)
        at Server.RestServer.post (/srv/daemon/src/http/routes.js:148:12)
        at next (/srv/daemon/node_modules/restify/lib/server.js:912:30)
        at f (/srv/daemon/node_modules/once/once.js:25:25)
        at Auth.init (/srv/daemon/src/http/routes.js:56:16)
        at AuthorizationMiddleware.init (/srv/daemon/src/middleware/authorizable.js:44:16)
        at Server.RestServer.use (/srv/daemon/src/http/routes.js:54:10)
        at next (/srv/daemon/node_modules/restify/lib/server.js:912:30)
```

**To Reproduce**
1. Have a working daemon server
2. Take a backup of the /srv/daemon-data
3. Reinstall the machine, I've tried both Ubuntu 19.04 and Debian 10
4. Install the daemon as per the installation steps
5. Use the core.json from the panel
6. Try to access / reinstall any of the servers

**Expected behavior**
I expect the servers to either be reinstalled or just work straight away (since a backup was restored), but instead I am unable to use any of the daemon functionalities.

**Comment by lazarsn** [comment]
I can't remake errors
Installed panel and daemon on debian 10 and not had issues

**Comment by lazarsn** [comment]
Tested and MC servers no issues

**Comment by MrDienns** [comment]
@lazarsn have you tried the reproduce steps? Have you tried reinstalling a node as specified in the steps? I've done this at least 7 times yesterday both on Ubuntu and on Debian. It's a completely fresh installation other than the core.json used, which I took from the panel installation. I used to not have issues either, just now it is breaking.

**Comment by MrDienns** [comment]
I just noticed I do get this NPM warning when startup up the daemon:
```
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
```

I simply installed npm with `apt install npm`.

**Comment by lazarsn** [comment]
About  npm warning had same thing

**Comment by TrixterTheTux** [comment]
Hi,
For the daemon to successfully detect servers, it requires their config file being present in the folder /srv/daemon/config/servers/. Without them, it can't detect if the server actually exists (or will have missing configuration information about them) and will cause the "invalid namespace" error due to the server not existing on the daemon side.

**Comment by MrDienns** [comment]
@TrixterTheTux thanks for that information, I suppose that explains the invalid namespace error. However, I've tried reinstalling the server (which would make sense then), but then this Javascript error shows up. Do you know anything about this?

**Comment by TrixterTheTux** [comment]
As the current state in the panel is that the server is installed, instead of creating a new server it tries to reinstall it. And as the server isn't loaded due to the missing files, it fails to find the server to reinstall.

**Comment by MrDienns** [comment]
@TrixterTheTux I see, thanks for that clarification. Considering my scenario (trying to reinstall an existing dedi, with backups) how should I best solve this issue? Is there an easy way of making the server daemon this situation, or do I have to fall back to deleting all servers in the panel and recreating them (which I think is a bit overkill for such a common usecase)?

**Comment by lazarsn** [comment]
Recreate servers and import data

**Comment by DaneEveritt** [comment]
@MrDienns if you have a backup it should have all of the server data folders as well, correct? If so just ensure they're in the correct spot for the daemon to be finding and reading them.

**Comment by Sir3lit** [comment]
The issue is that he only mad ea backup of the daemon-data. And not the daemon folder, that has the config for each server in it. So without those, all you have are data files for servers not the actual configs the daemon needs

**Comment by MrDienns** [comment]
Correct I only backed up daemon data since I expected all data to be in there, including the MC server configs.

**Comment by DaneEveritt** [comment]
Oh, well in that case right now there's not much you can do about that without writing some custom code to push some configs. I'd recommend opening a new issue that focuses on adding the ability to re-publish server configurations to the daemon.

**Comment by MrDienns** [comment]
Yeah I've just manually created the JSON files for now and had the panel push some settings again by just clicking save. I will open a new ticket later today regarding repushing the configuration.

**Comment by Sir3lit** [comment]
This could be close.
