### ISSUE TITLE
(Go-)SFTP server fails to load certificate sometimes

### ISSUE THREAD

**Issue by MarkL4YG** [pterodactyl/panel#1662]
**Background (please complete the following information):**
* Panel or Daemon: SFTP-Server (standalone)
* Version of Panel/Daemon: 1.0.4
* Server's OS: Ubuntu 18.04.2 LTS
* Your Computer's OS & Browser: n/a

**Describe the bug**
Sometimes - when bad luck is involved - the standalone SFTP server fails to load existing certificates when installed into a daemon that has been run before.  
The ASN1 library of Go complains:  
```
{"error": "asn1: structure error: integer not minimally-encoded"}
```  
Often, this can be fixed by deleting the certificate files in ``config/.sftp/`` and letting the standalone SFTP server generate them.

**To Reproduce**
1. Install a daemon
2. Run that daemon (with SFTP enabled)
3. Stop the daemon
4. Install the standalone SFTP server
5. Run it (with a grain of bad luck)

**Expected behavior**
The standalone SFTP server should start normally.

**Actual behavior**
The standalone SFTP server crashes.

**Comment by DaneEveritt** [comment]
This is a pretty common bug, not sure why it happens but the fix is so simple I'm not worried about it. The end goal is moving entirely away from the internal SFTP server anyways, so this won't be a problem in the long run.

**Comment by MarkL4YG** [comment]
In that case, now the issue will show up in Google at least :sweat_smile:

**Comment by Krokit** [comment]
@MarkL4YG Backup and delete .sftp folder in the /srv/daemon/config. After that start the sftp server.

**Comment by HyburdzMC** [comment]
Hi I am having the same problem and cannot seem to find the fix online 
I only find threads like this that are closed or solved but I do not see the fix :/
Please help me?
