### ISSUE TITLE
Allow ip for direct access

### ISSUE THREAD

**Issue by Spartan9802** [pterodactyl/panel#1663]
**Is your feature request related to a problem? Please describe.**
I use Buycraft and I would like to configure push-commands that allows Buycraft to send a notification to the server so that the purchase is immediate without any delay for the player.

To do this Buycraft create an http client on the port where is running the server, but my server being under a bungeecord proxy on port 25566 exactly buycraft can not make the connection since only bungeecord communicates with the outside.

**Describe the solution you'd like**
I would like to be able to authorize some trusted ip to communicate with the local network

**Comment by ocatelle** [comment]
You can add additional ports to a server than just the main 25565 port. To do this go to the admin section, select nodes, choose your node, then click "Allocation". In the box on the right enter the same IP your Bungeecord is using and under port add the required port (e.g. 8123 for Dynmap). Then go to Servers on the left, choose the server, and under Allocation Management on the right assign the new allocation you have created as an additional port, then restart your server.

**Comment by parkervcp** [comment]
This won't restrict it to a specific IP, but will do what you are trying to do which is allow buycraft to reach your server.
