### ISSUE TITLE
adding an panel user / is there a default user?

### ISSUE THREAD

**Issue by MSandro** [pterodactyl/panel#1669]
Hi, I found your amazing game-server-management-platform and now I was able to finaly install the panel. I am using the image: ccarney16/pterodactyl-panel on my kubernetes cluster. But my main problem is, I was not able to find information in the documentation about creating the first panel user or getting credentials for the default administrator.

Pleas help.
Thank you very much.

**Comment by Nobody196** [comment]
> Hi, I found your amazing game-server-management-platform and now I was able to finaly install the panel. I am using the image: ccarney16/pterodactyl-panel on my kubernetes cluster. But my main problem is, I was not able to find information in the documentation about creating the first panel user or getting credentials for the default administrator.
> 
> Pleas help.
> Thank you very much.

https://pterodactyl.io/panel/getting_started.html#installation

**Comment by Erik-JanRieksen** [comment]
This is not an issue with pterodactyl, but rather the docker image that you use for pterodactyl. I did a google search for you and found an installation guide for the docker image you mentioned.

https://github.com/ccarney16/pterodactyl-docker/blob/master/INSTALL.md
"docker-compose run --rm panel php artisan p:user:mak"

**Comment by MSandro** [comment]
Thanks

**Comment by jemboh128-tech** [comment]
Mintaa panel pterodactyl udahhh jadiii
