### ISSUE TITLE
Docker-Image is not up to date

### ISSUE THREAD

**Issue by Muffl0n-DE** [pterodactyl/panel#1670]
**Background (please complete the following information):**
* Panel
* Version of Panel/Daemon: Version from docker-compose
* Server's OS: Ubuntu
* Your Computer's OS & Browser: Windows & Chrome

**Describe the bug**
Pulling panel (quay.io/pterodactyl/panel:latest)...
ERROR: unauthorized: access to the requested resource is not authorized
root@uwu:/home/web/webserver# docker pull quay.io/pterodactyl/panel:latest
Error response from daemon: unauthorized: access to the requested resource is not authorized

**To Reproduce**
1. get the docker-compose from https://github.com/pterodactyl/panel/blob/develop/docker-compose.example.yml
2. `cp docker-compose.example.yml docker-compose.yml`
3. `docker-compose up -d`

**Expected fix**
The address of the Docker image should be updated to

**Comment by parkervcp** [comment]
We don't have an official docker image. That is just a placeholder.

**Comment by parkervcp** [comment]
I should note that one is being worked on. Just nothing official as of yet.

**Comment by Muffl0n-DE** [comment]
ok, thx
