### ISSUE TITLE
Error on Console start

### ISSUE THREAD

**Issue by Auntex** [pterodactyl/panel#1672]
Hellothere! I am using Daemon with the Panel.

Panel version: 7.15
Server OS: Ubuntu 16.04
Using Firefox on Windows 10

Basically, when I try to start the server after created, displays me an error, here it is: https://hasteb.in/hofirahe.gradle . Not very sure from what it is.

**Comment by peterkuzik** [comment]
Got the exact same error.

**Comment by DomiiBunn** [comment]
It is more of a daemon side error. If you can check the daemon version please and also I am not too sure about this but see what is your CPU allocation for that server. It might be helpful.

**Comment by parkervcp** [comment]
Please take this to discord as that is where general support goes.
