### ISSUE TITLE
Memory Usage and CPU Usage not show perfectly 4k monitor 150% scaling

### ISSUE THREAD

**Issue by andris155** [pterodactyl/panel#1675]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.7.15
* Server's OS: Ubuntu 18.04 LTS
* Your Computer's OS & Browser: Windows 10 & Google Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
```
PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
```
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

**To Reproduce**
1. Go to my server menu console menu witk 4k monitor

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
4K monitor with 150% scaling
<img width="1749" alt="Annotation 2019-08-12 220955" src="https://user-images.githubusercontent.com/8324198/62894865-f316cd00-bd4d-11e9-912c-791fb745c354.png">
With Full HD
<img width="1048" alt="Annotation 2019-08-12 220744" src="https://user-images.githubusercontent.com/8324198/62894744-a3d09c80-bd4d-11e9-8369-c8a42dbaf391.png">

**Comment by DaneEveritt** [comment]
Wont fix, sorry. This is all changing in 0.8 and I'm not planning on spending that much time changing things around in the 0.7.X branch.
