### ISSUE TITLE
XML Config Parser does not compensate for configs with self closing tags.

### ISSUE THREAD

**Issue by Gigawiz** [pterodactyl/panel#1677]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.15 (possibly earlier variants too) 
* Server's OS: Ubuntu 19.04
* Your Computer's OS & Browser: Windows 10, Chrome 

**Describe the bug**
Pterodactyl Eggs that use the XML Parser for config settings do not compensate for game server configs that use self closing tags. Found this issue while creating a 7 days to die server. The game server is looking for `<property name="ServerPort" value="26900"/>`, however, upon crash, pterodactyl sees that the config is missing the ServerPort value, and proceeds to add `<property name="ServerPort">value="26900"</property name="ServerPort">` to the config (which crashes 7 days to die, because it's expecting a self closing tag)

**To Reproduce**
1. Create a 7 Days to Die server (untested with other games that use self closing tags in XML configs)
2. Look at the config.

**Expected behavior**
Pterodactyl should be parsing the config, first to see if it uses self closing tags (or not), then adjust how it edits the config accordingly.

**Comment by parkervcp** [comment]
The xml parser used is `xml2js` - seen here - https://github.com/pterodactyl/daemon/blob/8d8809fce24e099cc525d97fa51db6229a4c97d7/src/helpers/fileparser.js#L32

There are several other libs out that would need testing

https://www.npmjs.com/package/fast-xml-parser
https://github.com/libxmljs/libxmljs
https://github.com/assistunion/xml-stream
https://github.com/nfarina/xmldoc
https://github.com/cheeriojs/cheerio

Considering xml is a native golang language and the new daemon is in go it may be better there.

**Comment by DaneEveritt** [comment]
Unsure if this is an issue on 1.0 but no one seems to have noticed.
