### ISSUE TITLE
[Suggestion] Dark/ Night Mode

### ISSUE THREAD

**Issue by Explosivee** [pterodactyl/panel#1678]
Hello, current theme is so bright and it hurts my eyes, maybe add an option into the panel to turn dark mode on/off?

**Comment by Lunaversitay** [comment]
I have a theme for this (although it hasn't been updated past 0.6)
https://github.com/Lunaversitay/pterodactyl-skins/blob/master/discord-theme/discord.css

But the 0.8 update is going to be natively dark themed. Dane stated he's not gonna change 0.7's theme.

**Comment by mayed505** [comment]
Pterodactyl v0.8 is going to be fully on a dark theme. You can join the community discord server and you will be able to see everything in #update-logs.

**Comment by Explosivee** [comment]
That's good news, is there any ETA on that version?

**Comment by mayed505** [comment]
It's still work in progress if I were to guess probably by the end of the year or something around.

**Comment by Explosivee** [comment]
Alright, thank you
