### ISSUE TITLE
BungeeCord: allocated IP not enforced on first start

### ISSUE THREAD

**Issue by OrangeJuiced** [Pterodactyl/Panel#168]
## Product
Please check the corresponding boxes below for which products this is about.

- [ ] Panel
- [x] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [x] Bug or Issue
- [ ] Feature Request
- [ ] Enhancement
- [ ] Other

## What Happens
On first start of a BungeeCord server, directly after it has finished building the allocated port for the server does not get enforced. It starts the server using the default BungeeCord port, which is: 25577.

After a reboot it does use the allocated port and works properly.

## How to Reproduce

1. Create a BungeeCord server.
2. Start the server.

**Comment by DaneEveritt** [comment]
closed in 2860767
