### ISSUE TITLE
Can't delete database host

### ISSUE THREAD

**Issue by dikkatdeli** [pterodactyl/panel#1680]
**Background (please complete the following information):**
* Panel or Daemon:   Panel
* Version of Panel/Daemon:  Your panel is not up-to-date! The latest version is 0.7.15 and you are currently running version 0.7.14.
* Server's OS:  ubuntu 16.04
* Your Computer's OS & Browser:  chrome

**Describe the bug**

We lost our database host. We had many databases for many game servers. We cannot delete database host.

**To Reproduce**
1. Go to databases
2. Click on database host and click delete icon 
3.  See error : Cannot delete a database host server that has active databases linked to it.

**Expected behavior**
  We want to be able to delete a database whether or not you can connect to it.

**Comment by DomiiBunn** [comment]
Your error is due to the db host having associated servers with it. Go to the db and see what servers are using it. Delete the db from these servers and than delete the db host.
Also update your panel and this is a matter for the #support chanel here https://discord.gg/pGFg9Ma

**Comment by dikkatdeli** [comment]
We lost our database host so we dont have access to it. Our server's ssd is burnt. 


When we try to delete a database from a game server it also gives error: An error occurred while processing this request.

**Comment by DomiiBunn** [comment]
It is not an issue of the panel not accessing the db host but the host being associated with game servers. Jump into discord mentioned above and we'll help you out in detail.

**Comment by lazarsn** [comment]
Not enough perms

**Comment by Biorn1950** [comment]
Recover your database server and all will be fine. Or delete one by one database for each server while the panel then you can delete the main database.

**Comment by schrej** [comment]
He probably can't delete the databases, as the db host can't be reached. We should probably make this possible, at least via CLI. To solve the issue now you can, carefully, delete the database entries for the DB and the related databases manually.
The tables should be called `database_servers` and `databases`. Find the id of the database you want to delete, then delete all databases that have said id as `db_server`.

**Comment by dikkatdeli** [comment]
> He probably can't delete the databases, as the db host can't be reached. We should probably make this possible, at least via CLI. To solve the issue now you can, carefully, delete the database entries for the DB and the related databases manually.
> The tables should be called `database_servers` and `databases`. Find the id of the database you want to delete, then delete all databases that have said id as `db_server`.

I solved it with your method. Thanks.

**Comment by Uneo7** [comment]
Sorry @parkervcp I missed this one in the list :)

**Comment by DaneEveritt** [comment]
Closing as this was opened pre-1.0
