### ISSUE TITLE
[Feature Request] Automatic server stop

### ISSUE THREAD

**Issue by Henriks9** [pterodactyl/panel#1681]
Add the possibility to automatically stop the server after a certain time if there are no players on the server.

**Comment by DomiiBunn** [comment]
Pterodactyl doesn't really do "per game" options. So most likely the answer will be a no. Whoever you can easily write an ad-on that would do the exact thing

**Comment by schrej** [comment]
As DomiiBunn said, we're trying to avoid game specific features. As we need the player count, which is very game specific, for this to work, it't won't be implemented.
