### ISSUE TITLE
Don't show or allow user to modify or revoke their own permissions

### ISSUE THREAD

**Issue by lancepioch** [pterodactyl/panel#1683]
**Describe the bug**
You can see and are allowed to remove permissions from yourself.

**To Reproduce**
1. Go to `/server/123abcid/users`
2. Make sure that you have Edit Users permission for server
3. See that you can revoke or edit yourself
4. Even though you can't give yourself more permissions, you can take them away, which makes zero sense

Also this brings up another issue, should users that can edit other users be allowed to remove the edit users permission?

**Comment by DomiiBunn** [comment]
Tested this. You can see the edits but saving it doesn't apply. Can you specify your panel version? maybe a theme? I'm testing on `0.7.15`. [Screen Cap](http://images.bbsnetwork.club/rec.mp4)

**Comment by DaneEveritt** [comment]
Closed in 9387be3b0d277a0cdb985d506ff65f81caad6853
