### ISSUE TITLE
Do not access external sites

### ISSUE THREAD

**Issue by gabrielv0** [pterodactyl/panel#1686]
**Background (please complete the following information):**
* Panel or Daemon: daemon
* Version of Panel/Daemon: 0.7.15 / 0.6.12 
* Server's OS: panel: alpine linux 3.10 / daemon: centos 7
* Your Computer's OS & Browser: solus 4 & chrome

**Describe the bug**
The servers cannot connect to external sites. 
If I try to use a plugin that connects, it will give error, if I try to curl the host it will work normally.

Error appearing on console:
java.io.FileNotFoundException: http://www.jhdev.net/ip.php

However, if I try for the host:
https://prnt.sc/ox52nt

The firewall has no different configuration.

Daemon: 
uname -a: Linux nc02 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

docker info: 
Client:
 Debug Mode: false

Server:
 Containers: 37
  Running: 9
  Paused: 0
  Stopped: 28
 Images: 10
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.27.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.54GiB
 Name: nc02
 ID: J2D7:IV3F:ISLD:EL5W:PRXD:AUVT:VLH3:YAME:4FZG:7RYQ:2XHJ:XQCO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**To Reproduce**
1. Download a licensed plugin
2. Wait for him to make a connection and the error will appear

**Expected behavior**
It would be right if he makes the connection

**Comment by parkervcp** [comment]
As I have asked does DNS work in the container? When you ping a site it will give you the ip it finds for any hostname you provide.

**Comment by lancepioch** [comment]
This isn't an issue with our software. You can seek help on our Discord channels with your server configuration.
