### ISSUE TITLE
Adding support for WebAuthn 

### ISSUE THREAD

**Issue by StealWonders** [pterodactyl/panel#1687]
WebAuthn is the new W3C specification for two-factor authentication built right into the browser, so I believe. WebAuthn is supported in Chrome, Firefox and Edge browsers (not Safari).

Basically, this will allow you to use your Yubikey (security USB stick) to directly authenticate your account by pressing the button on it.

More information can be found here: https://webauthn.io/

**Comment by lancepioch** [comment]
Thank you, but we won't be supporting that. We will remain with our current TOTP 2FA solution for now.

**Comment by VeeBack** [comment]
> Thank you, but we won't be supporting that. We will remain with our current TOTP 2FA solution for now.

I'm willing to implement this. Will it be accepted if I do?
