### ISSUE TITLE
Pocketmine MP support.

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#169]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [x] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [ ] Bug or Issue
- [x] Feature Request
- [ ] Enhancement
- [ ] Other

Support for Pocketmine with the following options is requested:

https://github.com/pmmp/PocketMine-MP
https://github.com/iTXTech/Genisys
https://github.com/ClearSkyTeam/ClearSky

**Comment by schrej** [comment]
All of those are servers for the game on their own. This should be one service with multiple variants like we do it with the normal minecraft right?

**Comment by DaneEveritt** [comment]
Yes, that is the plan. I'd consider Pocketmine a different service than Minecraft.
