### ISSUE TITLE
API rate limit ENV

### ISSUE THREAD

**Issue by DomiiBunn** [pterodactyl/panel#1695]
**Requested Featuer**
It would be extreamly usefull to bring out this value [API Throttle](https://github.com/pterodactyl/panel/blob/0.7-develop/app/Http/Kernel.php#L84) to the .ENV file
**Describe the solution you'd like**
Add an ENV var for API throttle
**Describe alternatives you've considered**
Editing the file [API Throttle](https://github.com/pterodactyl/panel/blob/0.7-develop/app/Http/Kernel.php#L84) by hand

**Comment by Mindgamesnl** [comment]
+1

**Comment by Liturkey** [comment]
+1
