### ISSUE TITLE
Suggestion: Source Game Update Button

### ISSUE THREAD

**Issue by James76931** [Pterodactyl/Panel#170]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [x] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [ ] Bug or Issue
- [x] Feature Request
- [ ] Enhancement
- [ ] Other

Hi.

I was wondering if it would be possible to have a button added which updates a Source Game Server to its latest version and also maybe the option to allow automatic checking for and applying updates for servers as well.

Cheers,
_- James_

**Comment by DaneEveritt** [comment]
ref #119

**Comment by DaneEveritt** [comment]
closed as #119 handles as well as 0.6.0 in general.
