### ISSUE TITLE
Automatic load distribution

### ISSUE THREAD

**Issue by Henriks9** [pterodactyl/panel#1701]
Hey,
I think it would be a good feature that if you have multiple servers the daemon always starts a server on the server that has the least to do.

**Comment by parkervcp** [comment]
I am going to assume you mean "install new servers on node with the lowest load".

This is harder to judge by math alone. A node could have a ton of low usage servers and one spins up and starts to use more.

This would require monitoring and many other new things to actually implement properly.

**Comment by Henriks9** [comment]
I mean that the server is always started where the lowest load is, so servers are moved from one node to the other.

**Comment by parkervcp** [comment]
That would also constantly move servers around and the IP wouldn't follow.

You would constantly need to change IP addresses for your servers.

**Comment by parkervcp** [comment]
The way to handle this would be to load balance an IP with all your nodes behind it with a shared network storage layer. All of that and many other things that we don't do.

**Comment by LeCodeCo** [comment]
I think this could be achieved easier if #582 was implemented. Something like a dedicated IPv6 address per server could make moving across nodes really easy, especially now that server transfer exists/using a shared network storage layer as Parker said.

**Comment by DaneEveritt** [comment]
Closing this out, I have no intentions or motivation to build a system that transfers servers across nodes automatically just to balance a load.
