### ISSUE TITLE
When you encounter an error when navigating to a file, it redirects you back to the root instead of same directory

### ISSUE THREAD

**Issue by lancepioch** [pterodactyl/panel#1702]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Latest
* Server's OS: Linux
* Your Computer's OS & Browser: Windows/Chrome

**Describe the bug**
When you 

**To Reproduce**
1. Go to File Manager
2. Go to subdirectory /example
3. Click on File with error (eg. too large to edit in panel)
4. Redirected back to `/files` instead of `/files#/example`

**Expected behavior**
The hashtag shouldn't be discarded.

The problem is that the hashtag can't be pulled from the url on the server, because it can't ever see that information.

A possible solution might exist adding a conditional here that pulls the path's parameter: https://github.com/pterodactyl/panel/blob/086018751d24dcf698e587d925ada9010352e532/app/Exceptions/DisplayException.php#L63-L74

**Comment by arcdigital** [comment]
I can't think of a good way to fix this right now, if you can come up with something pls PR it 🙂

**Comment by DaneEveritt** [comment]
This isn't a problem in 0.8 either.
