### ISSUE TITLE
Console commands not working

### ISSUE THREAD

**Issue by 0xcore** [pterodactyl/panel#1706]
* Panel or Daemon: Panel - Arma 3 egg
* Version of Panel/Daemon: 0.7.14/0.6.12
* Server's OS: Ubuntu 18.04.03 - Kernel 4.15.0-64
* Your Computer's OS & Browser: Windows 10 - Firefox

**Describe the bug**
I am unable to send console commands.

Linux gameserver 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.2.22-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.22-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-64-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.853GiB
 Name: gameserver
 ID: 4OBO:MP23:RRPH:2MGN:APEB:YHMZ:MPWZ:DHJ5:3FTE:CXT6:EHGW:Q2I7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**To Reproduce**
1.Go to a server console
2.Enter a command into said console
3.No output

**Expected behavior**
I expect the command to run and return feedback on console

**Comment by DomiiBunn** [comment]
Have you asked for help in discord?

**Comment by DomiiBunn** [comment]
https://pterodactyl.io/discord

**Comment by schrej** [comment]
We don't use the GitHub issue tracker to provide support. Please use the mentioned Discord server instead.
