### ISSUE TITLE
Feature Suggestion: SinusBot Support

### ISSUE THREAD

**Issue by James76931** [Pterodactyl/Panel#171]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [x] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [ ] Bug or Issue
- [x] Feature Request
- [ ] Enhancement
- [ ] Other

Hey, me again.

I was wondering if you could consider adding support for SinusBot. SinusBot is basically a sort of radio or music bot for TeamSpeak and Discord which accepts plugins, user management, web interface and many more features to it. Here's a link if you consider it: https://www.sinusbot.com/ . I think it would be a nice thing to add under "Voice Servers" for when you create a server.

_- James_

**Comment by DaneEveritt** [comment]
Does this run independently from the TS3 server, or does it have to run along-side it?

**Comment by James76931** [comment]
It runs along-side it, so you don't require a TS3 server installed to actually download it and use it.
However, it does use the TS3Client in order to connect to servers and also uses something called "YT-DL" in order to retrieve audio from YouTube.

Someone in the SinusBot community made an install script to do all the installing automatically, so if you were curious about anything I guess you could look at the code in the .sh file here: https://forum.sinusbot.com/resources/sinusbot-installer-script.58/

**Comment by James76931** [comment]
Oh and also, here are the official install instructions for a linux machine: https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu

**Comment by James76931** [comment]
Do you think this could be a possible addition for the new version?

**Comment by DaneEveritt** [comment]
I'll see if I can add this to 0.5.2 for you @James76931

**Comment by James76931** [comment]
@DaneEveritt Thanks ever so much! :D

**Comment by James76931** [comment]
@DaneEveritt Is this still planned for a future update by the way? I can't seem to find it in the latest panel.

**Comment by DaneEveritt** [comment]
Yes, it is being held off until 0.6.0

**Comment by James76931** [comment]
Ok then, thanks.

**Comment by DaneEveritt** [comment]
closed in favor of #239
