### ISSUE TITLE
Forcibly kicking random players

### ISSUE THREAD

**Issue by Explosivee** [pterodactyl/panel#1715]
Hello, i'm running a minecraft server under Waterfall (It's a Bungeecord fork) and my online avg around 200 players whenver i keep getting more players my Bungeecord forcibly kick (shutdown the connection) of some random people (50-60 people), i've asked this into the Bungeecord itself and they said something `External` does it, so i'm just curious is there a any featuıre in pterodactyl panel that limits the traffic or packets somehow then when it reaches the limits it kicks people?

**Comment by parkervcp** [comment]
Nothing the panel does should be touching your connections. If waterfall is being restarted the panel/daemon will have logged that.

**Comment by Explosivee** [comment]
It's not restarting it's just forcibly kicking some random people, not the entire player base

**Comment by alhassanv** [comment]
Thats an issue with your config, nothing to do with pterodactyl.

**Comment by Explosivee** [comment]
What about docker?

**Comment by parkervcp** [comment]
It's also probably not a docker issue. All docker does is set up some iptables routing from the external ip to the internal docker network.

**Comment by DaneEveritt** [comment]
This has nothing to do with Pterodactyl, you're the only person in the 4 years of running this project that's ever reported an issue like this. We also have 0 features that would do this.
