### ISSUE TITLE
Port Allocation not being reset in DB

### ISSUE THREAD

**Issue by bastrian** [pterodactyl/panel#1719]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.15
* Server's OS: Ubuntu Server 18.04.3 LTS
* Your Computer's OS & Browser: Windows 10, Chrome
* PHP-Version: 7.2.23-1
* SQL: 5.7.27 - MySQL Community Server

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

Panel Logs: empty (no error)

Issue:
The Existing Allocation will not be reset in the Database to NULL after deleting a Server. The Field server_id is still populated with the old ID even if the ID does not exsist in the servers table anymore.

How to reproduce:
Create a server and allocate the Port
Start the server 
stop the server
delete the server
Try to delete the allocation (Bin Button grey)

**Expected behavior**
Be able to delete the allocation

I suspect that there is something wrong with the delete process. 

![sc](https://user-images.githubusercontent.com/1041566/66643748-a6515480-ec1f-11e9-86ba-c2065de0351b.PNG)

**Comment by DomiiBunn** [comment]
Have you taken this to discord yet? https://discordapp.com/invite/pterodactyl

**Comment by Sir3lit** [comment]
I am **unable** to reproduce this.

**Comment by bastrian** [comment]
@DomiiBunn Yes, and they came to the same conclusion
@Sir3lit I was able to reproduce it on 2 clean installations with 2 Nodes each time.

**Comment by Sir3lit** [comment]
I'll do a clean instill tonight and see.

**Comment by DaneEveritt** [comment]
Can you show your database table schema for the `allocations` table?

**Comment by bastrian** [comment]
Sure. A Dump from the allocations table and server table:
https://pastebin.com/gmf0iEEw

**Comment by DaneEveritt** [comment]
@bastrian you just posted sensitive data keys for the world to see, you should consider them all at risk. I specifically asked just for the allocations table _schema_ to avoid that issue. It should have a foreign key constraint on the server_id that gets set to null when the server is deleted.

**Comment by bastrian** [comment]
Sorry @DaneEveritt , that should do:
https://pastebin.com/9tAKeWd1

**Comment by srkhost** [comment]
Same error :/

**Comment by srkhost** [comment]
OK, I fixed the issue by recreating the whole allocations table and fill it up again with the old data.

**Comment by DaneEveritt** [comment]
Cannot reproduce.

**Comment by srkhost** [comment]
Actually http://prntscr.com/rgvono
the node_id and server_id was not linked, that's was issue.

but I figured it out

**Comment by DaneEveritt** [comment]
Sounds like some issue with data migrations, since there should be a foreign key on both of those columns which cascades when the server is deleted.
