### ISSUE TITLE
Failing to login to control panel (Redirect back to /auth/login)

### ISSUE THREAD

**Issue by Pixelazed** [Pterodactyl/Panel#172]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [ ] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [x] Bug or Issue
- [ ] Feature Request
- [ ] Enhancement
- [ ] Other

## What Happens
80% of the time when i try to login to the panel it stays on the login page (i assume just redirects me back to the login page), it doesn't say the password is wrong because it isn't and when the password **is** wrong it just says that.
I have made 2 admin accounts for testing it and sometimes one of them stops working but the other one still works and sometimes it only happens on one computer and not on the other.
I am running Ubuntu 16.10 on my server but i have also tried 16.04 and it happened there too.
Mostly restarting the server works for logging in once but then it breaks again.

## How to Reproduce

1. Try to login to the control panel
2. If you get logged in log out again and repeat
3. Idk if this only happens to me? It's very annoying

## Error Logs

https://gist.github.com/Pixelazed/33c0114ee87b2fac35323e45851bc568
https://gist.github.com/Pixelazed/a3c53a910e6d22c6defec5b778164e19

## System Information

Linux ruinemans-MS-7693 4.8.0-27-generic #29-Ubuntu SMP Thu Oct 20 21:03:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

#### Output of `php -v` (if Panel):

PHP 7.0.8-3ubuntu3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-3ubuntu3, Copyright (c) 1999-2016, by Zend Technologies

**Comment by DaneEveritt** [comment]
I've been unable to replicate this on my end, or even on that specific panel. Going to close this unless someone can point some proof at it being a panel issue rather than a specific computer/browser issue.

Judging by the frequency at which it happens it makes me think you have a caching issue going on preventing the browser from storing the authentication cookie, so the panel just assumes its an invalidated request.
