### ISSUE TITLE
ERROR START NPM: restify.js:71

### ISSUE THREAD

**Issue by DemOnJR** [pterodactyl/panel#1722]
Hello i get this error:

root@localhost:/srv/daemon# sudo npm start

> pteronode@0.6.12 start /srv/daemon
> node src/index.js | node_modules/bunyan/bin/bunyan -o short

19:42:46.184Z  INFO wings: + ------------------------------------ +
19:42:46.190Z  INFO wings: | Running Pterodactyl Daemon v0.6.12    |
19:42:46.190Z  INFO wings: |        https://pterodactyl.io        |
19:42:46.190Z  INFO wings: |  Copyright 2015 - 2019 Dane Everitt  |
19:42:46.190Z  INFO wings: + ------------------------------------ +
19:42:46.190Z  INFO wings: Loading modules, this could take a few seconds.
/srv/daemon/src/http/restify.js:71
RestServer.on('after', Restify.auditLogger({
                               ^

TypeError: Restify.auditLogger is not a function
    at Object.<anonymous> (/srv/daemon/src/http/restify.js:71:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Function.<anonymous> (/srv/daemon/node_modules/rfr/lib/rfr.js:160:12)
    at Object.<anonymous> (/srv/daemon/src/http/socket.js:29:20)

**Comment by Lunaversitay** [comment]
Github issues are for bug/feature reports, if you need help with installation use the discord https://pterodactyl.io/discord

**Comment by DemOnJR** [comment]
This is not an"bug"?:
/srv/daemon/src/http/restify.js:71
RestServer.on('after', Restify.auditLogger({
^

TypeError: Restify.auditLogger is not a function

**Comment by parkervcp** [comment]
It's an issue with a node_module and you need to clear out the nodejs cache and node_modules folder in the daemon folder,

**Comment by TrixterTheTux** [comment]
It's caused by running `npm audit fix` which force updates restify to a newer version without actually updating the code to respect the changes in the update.
Running ```
cd /srv/daemon && rm -rf node_modules package.json package-lock.json && wget https://raw.githubusercontent.com/pterodactyl/daemon/release/v0.6.5/package.json && wget https://raw.githubusercontent.com/pterodactyl/daemon/release/v0.6.5/package-lock.json && npm install``` should fix it (Reverts changes by npm audit fix and reinstalls the dependencies)

**Comment by baxandrei** [comment]
> cd /srv/daemon && rm -rf node_modules package.json package-lock.json && wget https://raw.githubusercontent.com/pterodactyl/daemon/v0.6.12/package.json && wget https://raw.githubusercontent.com/pterodactyl/daemon/v0.6.12/package-lock.json && npm install

Thank you! Fixed my problem

**Comment by Thomas905** [comment]
Thanks :)
