### ISSUE TITLE
Scheduled tasks are not performed

### ISSUE THREAD

**Issue by MegaNoam** [pterodactyl/panel#1729]
Hi, 
my schedules tasks aren't working even after i restarted the queue worker.
I tried also to reboot the Linux to make sure it was not a problem with the system itself

I used the following guide to try to solve the problem but it didn't help me 
https://pterodactyl.io/panel/upgrading.html#restarting-queue-workers

![image](https://user-images.githubusercontent.com/18356302/67159363-1f515a00-f34c-11e9-83a2-79545881a882.png)

Update:
I tried to use the advice of other people who had a problem like mine and unfortunately it still didn't work
https://github.com/pterodactyl/panel/issues/258#issuecomment-355087428

I would love to receive any help, thanks in advance 💜

**Comment by DaneEveritt** [comment]
Please use Discord for support with these issues, it is not a bug with the software, rather a configuration issue with your Panel.
