### ISSUE TITLE
Upload from URL option

### ISSUE THREAD

**Issue by AoElite** [pterodactyl/panel#1730]
**Is your feature request related to a problem? Please describe.**
A way to upload files from links directly to the panel.

**Describe the solution you'd like**
A upload from url/link button.

**Additional context**
Having to download a file and then upload it to the panel is a pain, especially for someone who has slow internet.

**Comment by Sir3lit** [comment]
Duplicate of #165 ?

**Comment by DaneEveritt** [comment]
Yep
