### ISSUE TITLE
Localhost only API keys

### ISSUE THREAD

**Issue by kmecpp** [pterodactyl/panel#1735]
**Is your feature request related to a problem? Please describe.**
Many applications that use the Pterodactyl API are run on the same server so it is often not necessary to expose endpoint to the open web. Obviously the API keys offer decent security but the option to have IP verification as well would be a nice security feature.

**Describe the solution you'd like**
Ideally API keys could at a minimum have the option to be marked as localhost only. This feature could also be extended to restrict access to specific addresses.

**Comment by Lunaversitay** [comment]
![](https://i.lunaversity.dev/opera_NDUwXicrhk.png)

**Comment by kmecpp** [comment]
Ahh, I was making an Application API but I suppose that's better since you can adjust permissions very finely
