### ISSUE TITLE
Fire-wall issue (bungeecord)

### ISSUE THREAD

**Issue by RelyIz** [pterodactyl/panel#1739]
Hey,

i setup 2 mc servers and a bungee cord (followed this doc: https://pterodactyl.io/community/games/minecraft.html#network-configuration)
Server's:
Bungee 192.168.1.218:9000 (because of NAT)
mc server 1: 127.0.0.1:9001
mc server 2: 127.0.0.1:9002

i followed the guide. used this command: 
`firewall-cmd --permanent --zone=public --add-source=127.0.0.1`
when that didn't work i also opend 172.18.0.1 (local ip docker instance)
with: `firewall-cmd --permanent --zone=public --add-source=172.18.0.1`
When that didnt work i got some help in the discord and from @77#7777 (private) and we changed some stuff in the firewall these commands:
`firewall-cmd --permanent --add-port=9001/tcp`
`firewall-cmd --permanent --add-port=9002/tcp`
`firewall-cmd --reload`
(9001 and 9002 in my situations change if your using different ports)
After i changed the ip back from my external one to the local on on my bungee (someone suggested it needed to be the external one) it worked.
i the only thing i changed after not working is the firewall rules. before that didn't work (if you think I messed something up plz lmk, you can find more about this in #support on the discord).

**Comment by parkervcp** [comment]
https://pterodactyl.io/community/games/minecraft.html#network-configuration

**Comment by DaneEveritt** [comment]
Please use our Discord for game specific support.

**Comment by DanKasOfficial** [comment]
you must get ip from docker container
