### ISSUE TITLE
Bug when using "0" as a memory limit for BungeeCord servers

### ISSUE THREAD

**Issue by James76931** [Pterodactyl/Panel#174]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [x] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [x] Bug or Issue
- [ ] Feature Request
- [ ] Enhancement
- [ ] Other

## What Happens

When typing 0 into the memory limit field on the New Server page of the panel to disable the memory limit feature for a BungeeCord server and then attempting to start the server will not start properly and give out an error saying "Invalid maximum heap size: -Xmx0M" since BungeeCord won't accept -Xmx0M as a valid memory limit. 
## How to Reproduce

1. Go to the Create Server page.
2. Try to create a BungeeCord server with a maximum memory limit of 0.
3. Go to the manage server page for the newly created server and attempt to start it.
4. Notice how the server will not start and give out an error saying: "Invalid maximum heap size: -Xmx0M"

## Error Logs

```
Here are the CONSOLE logs as the rest aren't really needed and would probably be humungous:
> curl -sSL http://ci.md-5.net/job/BungeeCord/lastSuccessfulBuild/artifact/bootstrap/target/Bun
geeCord.jar -o bungeecord.jar
openjdk version "1.8.0_92-internal"
OpenJDK Runtime Environment (build 1.8.0_92-internal-alpine-r1-b14)
OpenJDK 64-Bit Server VM (build 25.92-b14, mixed mode)
$ java -Xms128M -Xmx0M -jar bungeecord.jar
Invalid maximum heap size: -Xmx0M
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

#### Output of `uname -a`:

```
Linux vps123456 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

#### Output of `php -v` (if Panel):

```
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
```

#### Output of `node -v` (if Daemon):

```
v6.9.1
```

#### Output of `docker info` and `docker -v` (if Daemon or Dockerfiles):

```
DOCKER INFO:

Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 104
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 5.689 GiB
Name: vps123456
ID: DM3F:5SZ5:H4YP:3RWX:Y5DA:H6HY:6H5X:6M36:NBEA:KMXD:2LJZ:4S2Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

DOCKER -V:
Docker version 1.12.3, build 6b644ec
```

**Comment by James76931** [comment]
EDIT:
This also seems to occur for normal Spigot servers.

**Comment by DaneEveritt** [comment]
Thats more of a user error, rather than a panel error. You have to change the startup to tell it how much memory to use. Theres no way for the panel to really be smart enough to handle that without just removing the entire startup argument.

The startup line does say that it will use the value from `SERVER_MEMORY`, so its working as intended for all intents and purposes.
