### ISSUE TITLE
Better NAT Support

### ISSUE THREAD

**Issue by andrewfer000** [pterodactyl/panel#1740]
My feature is related to a problem. 

So I have a panel as with a daemon running on a port fowared main server and another server next to it as daemon only server. After doing setup and adding srv1.mydomain.com to the hosts files on the main server (which is port forwarded) it still didn't work. After I added srv.mydomain.com to my /etc/hosts file on my Linux desktop client system the CentOS daemon worked fine. I understand this because my client computer connects to the daemon itself. 

The solution I will like is a way for everything to go through the main server, This allows me to have as many srvx.mydomain.com in my NAT network without having to edit /etc/hosts files for devices that use the panel. Essentially what I am saying is that everything goes through the panel running on the main port fowared server (mydomain.com) and ONLY that main server needs to be able to connect to srv1.mydomain.com. Essentially everything proxies through the panel itself. Kind of like a Bungee server that connects many internal Minecraft servers. 

I think a proxy server can be an alternative. But I don't know how to set that up.

Yes, Everything works as long as both the main server and any clients that want to access that daemon has the node server's local IP in the hosts file. This also does not allow me to access the node outside the network.

My Desktop is Ubuntu 19.10
My main server is Ubuntu 18.04
My secondary node is CentOS 7

This would be great for me and many others. It would increase security allow people who use a NAT network to use pterodactyl to it's full potential. I'm open to any solution that's functionally sound. (like a specially configured proxy server.) I am doing this for a text/video tutorial to help others so please give as much detail as possible

**Comment by andrewfer000** [comment]
No, Its not an SSL issue either. I got SSL working fine

Here's a Photo (Top is before adding to hosts file on Desktop and bottom is after)
![ServerStuff](https://user-images.githubusercontent.com/9620913/68000877-32abd180-fc38-11e9-9315-2a236c92d731.png)

**Comment by sergiz** [comment]
It would be much easier to tell us what your end goal is. If only your main server would be able to connect to the daemon, then eventually players would not be able to connect to the daemon, so I guess your intended usage is something that this panel was not designed for?

If you really wanted to achieve that, you would have to proxy websocket connections (+ HTTP + SFTP) through your main server.

If your only concern is related to domain names, simply add your DNS records to your local DNS server (I guess you have some kind of a router which (can) run(s) DNS server in your network that connects everything together).

**Comment by andrewfer000** [comment]
there's something I haven't tried yet and thats changing the ports on the second nodes daemon and sftp. I will give that a shot soon

**Comment by andrewfer000** [comment]
That didn't work. What im looking for is a way to have multiple nodes in a NAT network environment.

**Comment by sergiz** [comment]
I already told you to connect all your servers to your local DNS server and then add records you need there.

**Comment by parkervcp** [comment]
This is a good way to add seconds of lag to servers that aren't in the immediately same data center as the panel. This could also bog down the main panel server as it gets busier trying to handle all the traffic that is hitting the network interface. 

With enough servers/users behind the panel you would be sending a DDOS to your own panel.

**Comment by andrewfer000** [comment]
Well im not building a datacenter here xD. This is just a little home setup so I can do plugin testing on different server environments. I have a xfinity router son nothing special. (I would use a multi node VPS network for real player servers )Has anyone here worked with NAT setups before? Im in no rush since is just a dev setup. At this point I just want to learn a way to make this work. I could host a DNS server on the main server and connect my nodes to it but would that work outside my network? The biggest issue is I am going to be working with different Devs who may need panel accsess

**Comment by andrewfer000** [comment]
Yeah I fixed it. Giving the other node server different ports for the daemon and SFTP and then forwarding it worked. This post was really useless so i'm going to close it soon. Sorry for wasting your time. I guess there was just an issue with my CentOS server. (Im a Debian user xD)
