### ISSUE TITLE
[0.8] Possible user model bug.

### ISSUE THREAD

**Issue by MatthewSH** [pterodactyl/panel#1745]
Accidentally forgot to checkout `0.7-develop` and checked out `develop` instead, went to create a new user via CLI and PHP memory limit hit. Found out it's because of [this change](https://github.com/pterodactyl/panel/commit/0d6cf543147fd8e705dde068a017909a7582567c#diff-4614b2d052a2cb7486640775e2bdbb55) (possibly). It's because, from what I can see, it's getting stuck in a loop because it's referencing `self` instead of the parent Validable model. Changing from `self::getRules` to `parent::getRules` fixed it. Have not attempted to do it through admin dashboard yet though.

**Comment by arcdigital** [comment]
Fixed in 06e5a05f2205e66f54ce0839bfad61ea99d116f4
