### ISSUE TITLE
Panel API poweractions Stop&Restart returning 500 error

### ISSUE THREAD

**Issue by JustinRijsdijk** [pterodactyl/panel#1746]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.15
* Server's OS: CentOS7
* Your Computer's OS & Browser: Chrom (Request is send via Postman tho)

**Describe the bug**
When a server is running, sending a stop or restart request trough the API returns a 500 error, BUT the server is actually stopping/restarting. when a server already is off, there are no problems.

postman reyurns a responsetime of 10.18 seconds, when showing the 500 error.

**To Reproduce**
1. Create an account API
2. Create a server
3. When the server is running create a post request to: http:// or https:// yourpanel.extension/api/client/servers/<your server ID>/power in postman, with the following body: raw, type json: 
```
{
	"signal":"stop"
}
```
and the account API token as Authorization->Bearer Token

**Expected behavior**
I expect a response with an empty body (204), because the server is in fact stopping/restarting.

**Comment by parkervcp** [comment]
If you get a 500 error you need to get the logs. Take this to Discord to get help please.

**Comment by JustinRijsdijk** [comment]
It is just because of a timeout, that is why i'm adressing it here.

**Comment by parkervcp** [comment]
I am getting a 204 using the api to start and stop servers. I just tested this.

We have several companies using the API to do these kinds of tasks. I assume we would have heard about it earlier if it was an issue.

Again I ask that you get the logs to check what is causing the 500 error.

**Comment by JustinRijsdijk** [comment]
log returns that the request timedout after 10000 ms.

[2019-11-12 15:39:17] production.ERROR: GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 10000 milliseconds with 0 out of -1 bytes received.

I've posted this on the discord, but it is being 'spammed over' by all the other support questions.

**Comment by schrej** [comment]
This is probably the panel failing to contact the daemon due to a firewall or something like that. Not a topic for GitHub issues.
