### ISSUE TITLE
ZFS support

### ISSUE THREAD

**Issue by YWatchman** [pterodactyl/panel#1754]
**Is your feature request related to a problem? Please describe.**
People always ask for making back-ups, nowadays you have to make them manually, write complicated code or simply don't make them. With ZFS you can simply create snapshots.

Adding an option to allow a daemon to have it's docker filesystem on multiple zfs datasets.

**Comment by YWatchman** [comment]
And fortunately ZFS has deduplication, so you don't back-up duplicated data.

**Comment by parkervcp** [comment]
This is not feasible as this would require forcing zfs on users. It's hard enough getting them to install the right versions of the software we already require.

**Comment by parkervcp** [comment]
Docker also defaults to using zfs per container as far as I know as well.

**Comment by YWatchman** [comment]
> as this would require forcing zfs on users.

Hmmm, not exactly? Installation option, you could still let your users go with overlayfs if they don't like ZFS or don't have the resources for it. 

> Docker also defaults to using zfs per container as far as I know as well.

That makes it easier, doesn't it?

**Comment by parkervcp** [comment]
While true I assume users could already set this up for themselves if they were included to do it.

**Comment by DaneEveritt** [comment]
Won't be implementing this.
