### ISSUE TITLE
Modify Insurgency Egg

### ISSUE THREAD

**Issue by ozzygit** [pterodactyl/panel#1755]
**Is your feature request related to a problem? Please describe.**
Lack of startup parameters prevent some features working with Insurgency Egg

**Describe the solution you'd like**
Parameters added to default egg as follows:
-workshop -secure +maxplayers 49

**Describe alternatives you've considered**
N/A

**Additional context**
-workshop (enables downloading of workshop items. This is normally default on servers)
-secure (enables VAC be default for AntiCheat)
+maxplayers 49 (This sets the max allowable players to 49 which is default. The game engine will not allow more)

These settings will make creating servers faster especially for novices and prevent a lot of troubleshooting like workshop items not downloading or only 8 players can join etc.

**Comment by DomiiBunn** [comment]
wrong github reppo https://github.com/parkervcp/eggs

**Comment by ozzygit** [comment]
Sorry!
