### ISSUE TITLE
Yaml parsing recognize Bug

### ISSUE THREAD

**Issue by mkcoldwolf** [pterodactyl/panel#1756]
**Background (please complete the following information):**
* Panel or Daemon: N/A
* Version of Panel/Daemon: 0.7.12
* Server's OS: Linux Ubuntu
* Your Computer's OS & Browser: Windows 10 , Chrome 

**Describe the bug**
Panel editor will not let you edit yml files contain [ or ] inside content
`private: '[Private]'`

**To Reproduce**
1. Create a yml file at own Desktop
2. Insert the below yaml content
```
private: '[Private]'
more_users: '[More Users]'
```

3. Upload to the panel
4. You cannot edit itttttttttttttttttttttt

**Expected behavior**
Should be able to edit
even changing the url directly tells you that format is not supported

**Comment by ZeProf2Code** [comment]
✅ Can reproduce

**Comment by parkervcp** [comment]
I want to call out that this is a bug in the file parser we have in the daemon. It affects other files as well.

It might be fixed in the new golang daemon if anything.

**Comment by DaneEveritt** [comment]
Closing, new version doesn't do logic checks against the file type before opening so this shouldn't be an issue anymore.
