### ISSUE TITLE
Pulling quay.io/pterodactyl/panel:latest unauthorized

### ISSUE THREAD

**Issue by NoxInmortus** [pterodactyl/panel#1757]
Hello,

Trying to setup pterodactyl panel with the docker-compose provided, but I get a 
```
Error pulling image quay.io/pterodactyl/panel:latest - 500 Server Error: Internal Server Error (\"unauthorized: access to the requested resource is not authorized\"
```

Is this normal ? Should I build and host the image myself?

**Comment by saibotk** [comment]
The panel does not provide an official image anymore, yes you should build it yourself. You might take a look at my fixed docker-compose setup 😉 here.   https://github.com/saibotk/pterodactyl-panel-docker

**Comment by parkervcp** [comment]
We never had an official image. That is all a placeholder.
