### ISSUE TITLE
Minecraft server hanging but not detected as "crashed"

### ISSUE THREAD

**Issue by RalphORama** [pterodactyl/panel#1765]
## Background (please complete the following information)
* Panel or Daemon: Daemon
* Version of Panel/Daemon: Panel `0.7.15` / Daemon `0.6.12`
* Server's OS: Ubuntu 18.04 (`4.15.0-72-generic x86_64`)
* Your Computer's OS & Browser: Windows 10 + Firefox

## Describe the bug

When performing CPU intensive tasks on my Minecraft server (i.e. pre-generating the world with WorldBorder or rendering tiles with Dynmap), the server will randomly "hang" -- CPU usage will drop to 0%, the server will not respond to commands.  However, the panel / daemon don't detect the server as crashed in this state, and do not automatically restart it.  I have to manually kill and restart the server when this happens.

**`uname -a`:** `Linux dedi54743 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**`docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-72-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.63GiB
 Name: dedi54743
 ID: 7WYG:CVE4:RDWY:EVEX:HECY:652S:2JCE:HRWU:V7Z7:UFDF:7T5U:N42A
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

## To Reproduce

1. Set PaperMC 1.14.4 server
  a. Build information:
    - RAM: 12288 MB
    - Swap: 0 / CPU Limit: 0 (Server Specs: [PebbleHost Game-01](https://pebblehost.com/dedicated))
    - Block IO: 500
    - Disk space limit: 51200 MB
    - Allocations: port 25565
  b. Startup parameters: `java -Xms8192M -Xmx{{SERVER_MEMORY}}M -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs -Dterminal.jline=false -Dterminal.ansi=true -jar {{SERVER_JARFILE}}`
  c. Plugins:
    - WorldBorder b1.9.10
    - ProtocolLib v4.5.0-SNAPSHOT
    - ServerListPlus v3.4.8
2. Begin world generation with `wb world fill 100 208 true`
  a. This will begin generating chunks on the server
3. After an arbitrary amount of time, One or more "can't keep up!" messages will appear in console.
4. CPU usage will then drop to 0. Server will stop responding to commands, but panel won't detect it as crashed. Server will remain in this "hung" state until it is manually killed and restarted.

## Expected behavior

Server shouldn't hang without being automatically rebooted by the daemon.

**Comment by parkervcp** [comment]
The flag causing issues it the `-XX:+AlwaysPreTouch` one.

We know it's recommended by the paper devs but we already have extra memory and you are using it all and causing it to technically OOM according to the panel.

**Comment by parkervcp** [comment]
Also if you have the OOM killer disabled on the node your server is running out of memory and essentially crashing.

**Comment by RalphORama** [comment]
I will drop the `-XX:+AlwaysPreTouch` argument and see if that fixes the issue.

Also, I don't believe it's an OOM error -- I have the OOM Killer disabled and am only using 12 of my server's 16 GB.  At any point during the process `free -h` shows at least a gig of memory available.

**Comment by parkervcp** [comment]
OOM is in the docker container. So it has a hard limit at 12 gigs. Doesn't mater what it says outside of the container.

**Comment by RalphORama** [comment]
> OOM is in the docker container. So it has a hard limit at 12 gigs. Doesn't mater what it says outside of the container.

Ah, OK.  I'll double check my config files and watch closely to make sure it doesn't hit the memory cap.

**Comment by RalphORama** [comment]
Removing `-XX:+AlwaysPreTouch` seems to have fixed the issue.  Thank you for your help!

**Comment by joni736** [comment]
hello pterodactyl panel my server bungeecord cpu usage 300% and son server crashed 
how to fixed cpu limit?

**Comment by parkervcp** [comment]
@joni736 It's a known issue and also not related to this issue at all. - https://github.com/pterodactyl/panel/issues/1356

**Comment by Albert481** [comment]
> OOM is in the docker container. So it has a hard limit at 12 gigs. Doesn't mater what it says outside of the container.

How can we ensure that the hard limit is not hit?
