### ISSUE TITLE
Banned From Discord?

### ISSUE THREAD

**Issue by IWetPro** [pterodactyl/panel#1767]
So apparently I'm perma banned from the Discord when I was told it was only 1 day. This was about a  month ago that I was banned, anyone wanna explain?

**Comment by parkervcp** [comment]
I fail to see how this is an issue worthy of a github issue.

**Comment by IWetPro** [comment]
How else am I supposed to report it?

**Comment by IWetPro** [comment]
And obviously it's not a github issue hence the name. Don't know why all of you have to be so rude and unhelpful.

**Comment by parkervcp** [comment]
You gave no information on who you are, so we have no way to look up who you are to see why you were banned.
