### ISSUE TITLE
How Can I Achieve Cross-Drive Compatibility?

### ISSUE THREAD

**Issue by Max604** [pterodactyl/panel#1768]
Hello,

One of my drives is full. I have two drives. I currently have 8 servers on my node and my other drive to hold the files of new servers I want to create. However, I am unsure how I can achieve this with Pterodactyl, I was thinking about symlinks but apparently that cannot work in this case. 

Hopefully, you guys can help me find a solution so that I can still use pterodactyl.

**Comment by parkervcp** [comment]
You can't make a symlink across disks.

The way to fix it would be moving all your servers to the larger drive. and mounting the larger drive as the daemon-data folder.

**Comment by FlamingPaw** [comment]
> You can't make a symlink across disks.
> 
> The way to fix it would be moving all your servers to the larger drive. and mounting the larger drive as the daemon-data folder.

Adding on to this, using something like RAID or JBOD would also work to "pool" multiple physical disks into a single mount/virtual disk for the OS to use.

**Comment by mclucario** [comment]
> 
> 
> > You can't make a symlink across disks.
> > The way to fix it would be moving all your servers to the larger drive. and mounting the larger drive as the daemon-data folder.
> 
> Adding on to this, using something like RAID or JBOD would also work to "pool" multiple physical disks into a single mount/virtual disk for the OS to use.

Maybe LVM would also be a good idea.

**Comment by Max604** [comment]
> > > You can't make a symlink across disks.
> > > The way to fix it would be moving all your servers to the larger drive. and mounting the larger drive as the daemon-data folder.
> > 
> > 
> > Adding on to this, using something like RAID or JBOD would also work to "pool" multiple physical disks into a single mount/virtual disk for the OS to use.
> 
> Maybe LVM would also be a good idea.

Are you able to perhaps elaborate how so?

**Comment by schrej** [comment]
That's not a topic to be discussed in the issue list of this repository. We can leave this open to maybe consider multiple storage locations with the new daemon at some point to make it easier, but leveraging features like RAID or LVM is probably the better choice.

You can ask for help on our discord at https://discord.gg/pterodactyl in the appropriate channels. 
There are lots of guides regarding LVM as well, e.g. [this one by digital ocean](https://www.digitalocean.com/community/tutorials/an-introduction-to-lvm-concepts-terminology-and-operations), but please don't discuss this in here any further.

**Comment by DaneEveritt** [comment]
I don't have plans to support multiple file locations at this time.

**Comment by mclucario** [comment]
> > > > You can't make a symlink across disks.
> > > > The way to fix it would be moving all your servers to the larger drive. and mounting the larger drive as the daemon-data folder.
> > > 
> > > 
> > > Adding on to this, using something like RAID or JBOD would also work to "pool" multiple physical disks into a single mount/virtual disk for the OS to use.
> > 
> > 
> > Maybe LVM would also be a good idea.
> 
> Are you able to perhaps elaborate how so?

Of course. LVM lets you add a new harddrive to the storage pool so you don't need to take care of the management. Using this you can expand the file system as long you have one that is resizeable. I had to use this quite a bit on Fedora since I was running out of space on my root partition. 

A more detailed description can be found on [nixcraft](https://www.cyberciti.biz/faq/howto-add-disk-to-lvm-volume-on-linux-to-increase-size-of-pool/)
