### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by LolTDMMMOs** [pterodactyl/panel#1769]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: I don't know 
* Server's OS: Debian 9
* Your Computer's OS & Browser: Windows 10/Microsoft Edge Dev/Chronium 

The issue occuring has happened multiple times when running / install pterodactyl. When ever i got to my panel link, it brings up a 500 error. 

500
Whoops, something went wrong on our servers.

**Comment by parkervcp** [comment]
We have support channels on the discord server please bring this there.
