### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by adrijanb** [pterodactyl/panel#1778]
Since the protocol for IPv4 addresses has now reached its limits and the last IPv4 addresses have been distributed, I wanted to ask whether it would be possible to program a future-proof version of Pterodactyl. I am aware that this will be a lot of work, but support for IPv6 should be encouraged, especially in the areas of hosting.

I would be very happy if the support for IPv6 is also added in Pterodactyl!

**Comment by TekExplorer** [comment]
yes, this is the one thing preventing me from installing it thus far, there are no more IPv4 addresses, but its cheap as all heck (ie. free) to get lots of IPv6 - please tell me this is already implemented or will be soon

**Comment by Wqrld** [comment]
I believe docker requires some flags for ipv6 still, but ill try to do some testing to see what's needed

**Comment by Wqrld** [comment]
see https://docs.docker.com/config/daemon/ipv6/, im going to have a hard time testing though as i don't have ipv6 myself

**Comment by adrijanb** [comment]
It would be awesome, if you could test it.

**Comment by Wqrld** [comment]
I just got a new laptop that does have ipv6 support (not sure why my pc didnt) so i hope i can get to this soon. Minecrafts own ipv6 support is also still somewhat buggy as far as i am aware.

**Comment by parkervcp** [comment]
You primary issue is that ipv6 still doesn't have wide adoption and 4to6 and 6to4 conversions are still non-standard.

**Comment by Wqrld** [comment]
> You primary issue is that ipv6 still doesn't have wide adoption and 4to6 and 6to4 conversions are still non-standard.

the idea was mainly that you could have minecraft listen on ipv6 AND ipv4 (which is possible through a linux setting which may or mayb not exist in those containers). To also let ipv6 users connect to your server and use v6 where possible

**Comment by adrijanb** [comment]
@parkervcp is right. There are no standards yet but i think there are going to be some soon.

**Comment by LinusTebbe** [comment]
Are there any plans to implement this in the foreseeable future?
I just stumbled upon this issue and it's kind of a major problem, as IPv6 connections are actually quicker, at least in Germany, because most IPv4 Adresses are only given via a NAT.
Basically every connection gets atleast a /64 IPv6 subnet.

**Comment by matthewpi** [comment]
I believe the plan is to get IPv6 support in `1.0`, I don't believe we are accepting features/minor fixes to `0.7` (that would include the `0.6` daemon).  As https://github.com/pterodactyl/daemon/pull/111 was submitted, CodeCo asked about if the same problem exists in `wings` (the `1.0` daemon) and I believe [it does](https://github.com/pterodactyl/wings/blob/develop/server/environment_docker.go#L783-L806).  While I'm not sure about all the minor implementation details of IPv6, we should try to make `1.0` support it as well as we can without making everything complicated.

**Comment by unixfox** [comment]
IPv6 support in Docker is kinda wobbly and I use https://github.com/robbertkl/docker-ipv6nat which allows to bind the server to a fixed IPv6 address instead of having a dynamic IPv6 address allocated each time the container gets created.

**Comment by LinusTebbe** [comment]
I got it to work by:

Applying the changes in https://github.com/pterodactyl/daemon/pull/111

Enabling IPv6 support in Docker, disabling the userland proxy by creating the file `/etc/docker/daemon.json` with the content:
```
{
  "userland-proxy": false,
  "ipv6": true,
  "fixed-cidr-v6": "fd00::/80"
}
```

Installing the previously mentioned container: https://github.com/robbertkl/docker-ipv6nat
and rebooting afterwards

Maybe this will help some people having the same problem.

**Comment by LinusTebbe** [comment]
Is there any update to this?
Now that the 1.0 is out for some time...

**Comment by matthewpi** [comment]
IPv6 is supported but may require additional docker configuration to work properly.

**Comment by unixfox** [comment]
> IPv6 is supported but may require additional docker configuration to work properly.

Which docker configuration? Could you explain a bit more or link to a documentation?

**Comment by matthewpi** [comment]
> Which docker configuration? Could you explain a bit more or link to a documentation?

https://github.com/pterodactyl/panel/issues/1778#issuecomment-619457907

You may need to run the ipv6nat container but I have had success without it sometimes.

**Comment by TekExplorer** [comment]
Someone ought to add that to the docs for wings additional configuration

**Comment by ririko5834** [comment]
How to configure node with IPv6?

**Comment by justacoasterfan** [comment]
Just bringing this back up to see if there have been any changes in IPv6 support in the last few years. Is there proper support, or is it still more experimental and a pain to get working?

**Comment by Cyanoure** [comment]
It's sad to see that IPv6 is pain to get working.
Many developers don't seem to care about IPv6, so it's pain to work with, then people will hate IPv6, but it's not that bad if they would support it properly.
I would like to my players to be able use IPv6 if they have IPv6 network. But since in Pterodactyl I can't use both IPv6 and IPv4, I can't do it.
I have to create a separated domain record for only IPv4 (if not, the IPv6 capable client would try to connect with IPv6). It's a bit pain to not having proper IPv6 support.

VPS hostings gives us free /64 IPv6 network. It's a huge amount if IPv6 addresses. This is more ip addresses than available ports on a single IPv4 address. (2^64) I could give a separated IPv6 address for every services I have.
Even my home network has a /64 public prefix length. I could use them for addressing every smart air molecules in my room. :'D

**Comment by Boy132** [comment]
> It's sad to see that IPv6 is pain to get working. [...]
>[...] But since in Pterodactyl I can't use both IPv6 and IPv4 [...]

Pterodactyl (or rather the "new" wings daemon) works fine with ipv6.

**Comment by ugh2235** [comment]
4 years later, no tutorial lmao.
This ticket has seen some stuff lmao

**Comment by Cyanoure** [comment]
> > It's sad to see that IPv6 is pain to get working. [...]
> > [...] But since in Pterodactyl I can't use both IPv6 and IPv4 [...]
> 
> Pterodactyl (or rather the "new" wings daemon) works fine with ipv6.

I just realized that the real problem for me is that I can't specify 2 or more ip addresses as primary port. (For example both IPv4 and a specific IPv6)
For outgoint connectivity with IPv6 I think I just have to setup docker properly.

It would be nice to see a separated allocation list for IPv6 and I could set a primary IPv4 and primary IPv6, because IPv4 and IPv6 are entirely independent from each other.

**Comment by matthewpi** [comment]
> > > It's sad to see that IPv6 is pain to get working. [...]
> > > [...] But since in Pterodactyl I can't use both IPv6 and IPv4 [...]
> > 
> > 
> > Pterodactyl (or rather the "new" wings daemon) works fine with ipv6.
> 
> I just realized that the real problem for me is that I can't specify 2 or more ip addresses as primary port. (For example both IPv4 and a specific IPv6) For outgoint connectivity with IPv6 I think I just have to setup docker properly.
> 
> It would be nice to see a separated allocation list for IPv6 and I could set a primary IPv4 and primary IPv6, because IPv4 and IPv6 are entirely independent from each other.

The primary allocation is not used to determine connectivity, it is purely used for the `SERVER_PORT` (and maybe an IP) variable(s).  All processes should be binding to all interfaces within the container, whether or not they support IPv6 (or dual-stacking) is still up to each individual application.  So it shouldn't really matter whether or not your IPv4 or IPv6 address is the primary allocation, as long as they share the same port which most people would want anyways.

**Comment by Cyanoure** [comment]
> > > > It's sad to see that IPv6 is pain to get working. [...]
> > > > [...] But since in Pterodactyl I can't use both IPv6 and IPv4 [...]
> > > 
> > > 
> > > Pterodactyl (or rather the "new" wings daemon) works fine with ipv6.
> > 
> > 
> > I just realized that the real problem for me is that I can't specify 2 or more ip addresses as primary port. (For example both IPv4 and a specific IPv6) For outgoint connectivity with IPv6 I think I just have to setup docker properly.
> > It would be nice to see a separated allocation list for IPv6 and I could set a primary IPv4 and primary IPv6, because IPv4 and IPv6 are entirely independent from each other.
> 
> The primary allocation is not used to determine connectivity, it is purely used for the `SERVER_PORT` (and maybe an IP) variable(s). All processes should be binding to all interfaces within the container, whether or not they support IPv6 (or dual-stacking) or not is still up to each individual application. So it shouldn't really matter whether or not your IPv4 or IPv6 address is the primary allocation, as long as they share the same port which most people would want anyways.

Okay, I feel so stupid now. :'D
Thanks for the information.
