### ISSUE TITLE
Daemon error secondary IP not working

### ISSUE THREAD

**Issue by jondavis0787** [pterodactyl/panel#1780]
Command Line is 

./RustDedicated -batchmode +server.ip "0.0.0.0" +server.port "{{SERVER_PORT}}" +server.identity "rust" +rcon.port "{{RCON_PORT}}" +rcon.web true +server.hostname \"{{HOSTNAME}}\" +server.level \"{{LEVEL}}\" +server.description \"{{DESCRIPTION}}\" +server.url \"{{SERVER_URL}}\" +server.headerimage \"{{SERVER_IMG}}\" +server.worldsize \"{{WORLD_SIZE}}\" +server.seed \"{{WORLD_SEED}}\" +server.maxplayers {{MAX_PLAYERS}} +rcon.password \"{{RCON_PASS}}\" +fps.limit "256" +server.tickrate "30" +server.saveinterval {{SAVEINTERVAL}} {{ADDITIONAL_ARGS}

Trying to setup secondary IP with OVH and game migration however the server states its running and states "IP address from external API: x.x.x.214" which isn't right IP ends in x.x.x.216 not 214 and server list is not seeing the server the game migration is turned on and ports are open.

**Comment by parkervcp** [comment]
Is this truly a secondary or a failover IP? The failover IP is one that cannot be used for hosting in the way you want.

If you have a true secondary IP you need to adjust the daemon to use host mode networking to use each IP individually. https://pterodactyl.io/daemon/configuration.html#custom-network-interfaces

A note on setting the network to "host" mode. You need to stop all servers, stop the daemon, and remove pterodactyl server containers, then you need to remove the docker network, reconfigure the daemon, and lastly start the daemon.
