### ISSUE TITLE
Connection completely broken

### ISSUE THREAD

**Issue by MatteoGrandthurin** [pterodactyl/panel#1781]
Version of Panel/Daemon: Panel version 0.7.15 / Daemon version 0.6.12
Server's OS: Ubuntu 19.04
Your Computer's OS & Browser: Windows 10, Chrome

Hello,

I'm having an issue with Pterodactyl. I host multiple minecraft servers and the problem is that we are using minecraft plugins that use MySQL databases, MongoDB and Redis.

The issue is that using Pterodactyl to start the server, plugins are not able to connect to any databases, connections are failing for MySQL, Mongo and Redis. Nothing is working. However, if I start the server without Pterodactyl, every databases work fine. Plugins are connecting to databases using localhost. I also tried switching host from 127.0.0.1 to pterodactyl private IP adress (inet) but it didn't work and it still failed. I don't know what the issue can be, it looks like servers ran through pterodactyl aren't able to create external connections. Also, one of our plugin is making requests to our website API but the connection always fail (time out) when the server is ran through pterodactyl.

Thanks.

**Comment by parkervcp** [comment]
You need to configure those services to listen on either 0.0.0.0 or 172.18.0.1 so the servers can access them on the 172.18.0.1 address.

We call this out in the docs for MySQL specifically but this would also cover redis and mongodb.

**Comment by DaneEveritt** [comment]
This is not a bug with the software, rather a configuration issue due to the processes running within isolated networks. Please use our Discord for further assistance. :)
