### ISSUE TITLE
Data integrity exception | oom disabled field must be true or false

### ISSUE THREAD

**Issue by ColaIan** [pterodactyl/panel#1783]
**Background (please complete the following information):**
* Panel or Daemon: 0.7.15
* Version of Panel/Daemon: 0.6.12
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10, Chrome
* PHP Version: Tested on 7.2, 7.3, 7.4

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: When I try to save build configuration, this error occurs https://pastebin.com/UyjZ3UaC

**To Reproduce**
1. Save build configuration

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
It's supposed to save properly with a success message

**Comment by DaneEveritt** [comment]
Update whatever theme you're using the latest version.
