### ISSUE TITLE
Can't login while 2fa is enabled on pterodactyl 0.8

### ISSUE THREAD

**Issue by Fabian-Ser** [pterodactyl/panel#1785]
So i enabled 2fa auth, now i relog and i go to this: http://<MY IP>/auth/login/checkpoint, this page is empty, i can't login anymore.

**Comment by DaneEveritt** [comment]
Are you going through the normal login flow and the checkpoint page is empty, or are you going _directly_ to the checkpoint page?

**Comment by DaneEveritt** [comment]
Cannot reproduce with the information provided.
