### ISSUE TITLE
/tmp issue returns

### ISSUE THREAD

**Issue by GhotiMayo** [Pterodactyl/Panel#179]
## Product
Please check the corresponding boxes below for which products this is about.

- [ ] Panel
- [x] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [x] Bug or Issue
- [ ] Feature Request
- [ ] Enhancement
- [ ] Other

## What Happens

Having another issue with the tmp folder. I have rebuilt the container and still get the error.

## How to Reproduce

Honestly not sure how to reproduce this. As I said the same exact plugin works fine on my test server on the panel and the setups are almost exactly identical. I tested the server without the panel and the plugin started normally.

## Error Logs

```
`> [02:06:47 INFO]: [WorldGuard] Enabling WorldGuard v6.1.2;e38d98d
> [02:06:47 WARN]: Failed to load native library:sqlite-3.15.1-a2f8cc3c-c319-47ad-ab38-5df7ecd9
d45a-libsqlitejdbc.so. osinfo: Linux/x86_64
> [02:06:47 WARN]: java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.15.1-a2f8cc3c-c319-47ad-ab38-5
df7ecd9d45a-libsqlitejdbc.so: Error relocating /tmp/sqlite-3.15.1-a2f8cc3c-c319-47ad-ab38-5df7e
cd9d45a-libsqlitejdbc.so: __isnan: symbol not found
>`
```

**Comment by DaneEveritt** [comment]
I believe we resolved this on Discord, issue being that you were using the vanilla option, and not the spigot option?
