### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by JackW6809** [pterodactyl/panel#1790]
Panel or Daemon: Wings
Version of Panel/Daemon: V0.8.0-alpha.1
Server's OS: Ubuntu 18.0.4
Your Computer's OS & Browser: Windows 10 Chrome
Describe the bug
Error when starting the server. (Permission denied)

[Status Change] Server marked as starting...
[Internal] Error Event [B9545B23-9288-4c74-b835-4659b9c08169]: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd ("/home/container") set in config.json failed: permission denied": unknown
[Status Change] Server marked as offline...

To Reproduce

Install the panel and wings
Make a server
See the error in the console
Expected behavior
The server to start without any bugs

**Comment by Fabian-Ser** [comment]
restart your daemon @JackW6809

**Comment by PBenji** [comment]
Same problem here with the nodejs daemon on debian 9 linux kernel 5.0 lxc container.
Docker works fine, but when I try to install/start a server through the pterodactyl panel I get https://pastebin.com/Vq1kFMW1 @Fabian-Ser

**Comment by Fabian-Ser** [comment]
Also @PBenji , do you restarted your daemon?

**Comment by JackW6809** [comment]
@Fabian-Ser Dane told me to put it up here so they do not forget about the bug as stated in the discord:
![image](https://user-images.githubusercontent.com/53652452/71383606-0b88d500-25d5-11ea-83d6-285c851484c5.png)

**Comment by JackW6809** [comment]
@PBenji What fixed it for me was setting the daemon-data file to 777 recursively in /srv/

**Comment by DaneEveritt** [comment]
@PBenji this issue is for the wings daemon, which is very different from the Nodejs one. Please open a separate issue to report on that.

**Comment by PBenji** [comment]
@JackW6809 chmodding the daemon-data folder to 777 permissions suprisingly fixed it, thank you.
I also tried chowning the daemon-data folder to the pterodactyl user, but that does not seem to fixed it.
@DaneEveritt Thanks, but the problem got solved!

**Comment by JackW6809** [comment]
> @PBenji What fixed it for me was setting the daemon-data file to 777 recursively in /srv/



@DaneEveritt If this fixed it I would forward such on:

> @JackW6809 chmodding the daemon-data folder to 777 permissions suprisingly fixed it, thank you.
> I also tried chowning the daemon-data folder to the pterodactyl user, but that does not seem to fixed it.

**Comment by DaneEveritt** [comment]
`777` is never an appropriate fix. :)

**Comment by NIKOSTORE733** [comment]
Gimana cara pasang script
