### ISSUE TITLE
Panel server console is not working

### ISSUE THREAD

**Issue by toxicgl** [pterodactyl/panel#1791]
* Panel or Daemon: Panel
* Version of Panel/Daemon: V0.8.0-alpha.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chrome

**Describe the bug**
Panel: Panel server console is not working.

**To Reproduce**
While on server console im getting error

WebSocket connection to 'ws://ip:27030/api/servers/7285b04d-4c32-4204-85f7-c0bff79e1d4a/ws' failed: Error during WebSocket handshake: Unexpected response code: 404

![Screenshot_3](https://user-images.githubusercontent.com/42916541/71413690-703f4080-2664-11ea-8111-831f4b2c9106.png)

On node server list im getting this error somehow its saying undefined

![Screenshot_4](https://user-images.githubusercontent.com/42916541/71414191-d1681380-2666-11ea-9fa2-2d377d852345.png)

**Comment by DaneEveritt** [comment]
Please include wings output logs when you try to connect to the socket, make sure the daemon is running in debug: `sudo ./wings -debug`

**Comment by toxicgl** [comment]
> Please include wings output logs when you try to connect to the socket, make sure the daemon is running in debug: `sudo ./wings -debug`

Wings is not giving any output, just casual INFOs.

**Comment by DaneEveritt** [comment]
Have you confirmed this server's UUID shows up in the console output when wings starts? Just want to confirm it is actually seeing the server and knows it exists.

**Comment by toxicgl** [comment]
Actually i fixed it by removing and installing completely everything from my server.

**Comment by Kolterdyx** [comment]
That doesn't really feel like a solution though
