### ISSUE TITLE
Login Error message, too big

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1792]
The login error message displays as the width of the page, when it should be the width of the login box

![](https://justmyrandomstuff.com/img/uTvWrX3.jpg)

**Comment by DaneEveritt** [comment]
![he-has-become-the-long-boy-but-how-are-he-29914148](https://user-images.githubusercontent.com/418376/71449651-0c6d5400-2706-11ea-83f9-4377956b4890.png)
