### ISSUE TITLE
Deamon does not Return Error Message when Instance Storage limit is Reached

### ISSUE THREAD

**Issue by steevLP** [pterodactyl/panel#1795]
# I am reporting an Issue with the Daemon!

A Client of Mine came to me because he could not updload files..
This happened because he had reached the storage limit of his instance.
He claims pretty sure to not have gotten any error message that would explain him storage limit reached..

If it is Possible i would recommend to add this

**Comment by Lunaversitay** [comment]
you do get an error message when the server is out of disk space, in the console it'll say something along the lines of "You've reached the max storage (x/x)"

**Comment by DaneEveritt** [comment]
There is no way to return a custom error message over the SFTP protocol to indicate that you're out of disk space.

At least none that I am aware of.

**Comment by ZeProf2Code** [comment]
![image](https://user-images.githubusercontent.com/32982428/71542604-bba96580-2968-11ea-9c51-b47f3693c9f4.png)
![image](https://user-images.githubusercontent.com/32982428/71542672-818c9380-2969-11ea-9d3f-0efc00b6663f.png)
@DaneEveritt

**Comment by schrej** [comment]
That looks like an error returned by the sftp.Client, not the sftp.Server @ZeProf2Code

**Comment by ZeProf2Code** [comment]
@screj like the first screenshot that I sent, the error code 15 would be better.

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/sftp-server/commit/368abf5d46c49f5bb0fc057d540eec12363677ae
