### ISSUE TITLE
Filesize not showing when Server is down

### ISSUE THREAD

**Issue by steevLP** [pterodactyl/panel#1796]
I am Reporting an issue about the panel.

i discovered that the maximum used filesize not is showing when the server is down.
it would be really helpfull not only for me for managing but also for my clients to plan their modpacks or other things if it would be shown even if the server went offline

**Comment by Sir3lit** [comment]
Not possible, as the values are only given to the panel when the server is running.

**Comment by DaneEveritt** [comment]
I mean we _could_ show this when the server is offline.

**Comment by Sir3lit** [comment]
True, but it's only a snapshot when the server starts, so it would have to be dynamic. Wouldn't the cause more overhead on the disk to keep getting the size?

**Comment by DaneEveritt** [comment]
It can pull from the cache in the new Daemon. :)

**Comment by sergiz** [comment]
@Sir3lit, the daemon checks disk size every (by default) 30 seconds, regardless of the server status.

**Comment by DaneEveritt** [comment]
Not the new one, pretty sure the new daemon just checks when necessary, and updates the cache if needed.

**Comment by sergiz** [comment]
I was referring to the old one yeah ¯\_(ツ)_/¯

**Comment by sergiz** [comment]
I was referring to the old one yeah. 
`¯\_(ツ)_/¯`
