### ISSUE TITLE
Easily Link Servers Together

### ISSUE THREAD

**Issue by Sampleeeee** [pterodactyl/panel#1797]
**Is your feature request related to a problem? Please describe.**
It's fairly hard to easily link servers together. For example with Garry's Mod you can mount other source games such as css, hl, Portal, etc. 

**Describe the solution you'd like**
Maybe an option in the panel that easily let's you get file paths of other servers, allowing people to easily link the games together

**Describe alternatives you've considered**
I've thought about just installing C:SS (that's what I'm trying to mount) on my local machine and moving it in with a FTP but I would have to do that for every server, which would take up a lot of space

**Comment by parkervcp** [comment]
I believe what you are looking for is a shared folder that could be in a volume

All things considered this could fall under - https://github.com/pterodactyl/panel/issues/714

**Comment by DaneEveritt** [comment]
Mounts solve this.
