### ISSUE TITLE
File Editor Replaces Slashes to %2F

### ISSUE THREAD

**Issue by steevLP** [pterodactyl/panel#1798]
I am reporting a bug of the Panel v 0.7

A Client of Mine was trying to edit a config in his Minecraft Modpack and reported to me that his file where not found from the web panel but is there.

i was looking into it myself and saw the file he wanted to open this path:  
this is the path from the file editor: `config/beneath/blockdeco.json`
/server/id/files/edit`/`config/beneath/blockdeco.json is the working one after correcting the missing slash

but it gets redirected like this: /server/id/files/edit/config`%2F`beneath/blockdeco.json
this error should be fixed as fast as possible since people are getting it everytime they want to edit a modpack config

**Comment by Lunaversitay** [comment]
You realize that `%2F` means `/` right? It works just the same, I even tested it with the exact same path you gave and file and it worked just fine.

**Comment by steevLP** [comment]
it does not work for me or other people trying it

**Comment by Lunaversitay** [comment]
Post a full screenshot of the browser when its not working

**Comment by steevLP** [comment]
![1](https://user-images.githubusercontent.com/20173431/71548009-fb437200-29a7-11ea-991c-59ea058309e8.PNG) as i said this does not work

and this where i replaced %2F after config works
![2](https://user-images.githubusercontent.com/20173431/71548013-0b5b5180-29a8-11ea-808e-36a58fdfe84a.PNG)

**Comment by Lunaversitay** [comment]
What's the full version of the panel you're using. This bug was reported in 2018 but it was fixed since then. https://github.com/ayan4m1/panel/commit/eaaa2a06b917ad4b9db47a4741cb539ea9dc4735

**Comment by steevLP** [comment]
i am using the version 0.7.15

**Comment by Lunaversitay** [comment]
https://github.com/pterodactyl/panel/pull/1674 should potentially fix your issue, apparently it was never pushed cause of 0.8 coming out soon.

**Comment by DaneEveritt** [comment]
Closing as we handle paths completely different in 0.8 as well. :)

**Comment by iamkubi** [comment]
This is an Apache issue, you didn't copy the AllowEncodedSlashes directive from the example config.
