### ISSUE TITLE
Ability to move servers to new node.

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#18]
Have the ability to transfer servers between nodes. Using the built in sftp system to transfer directly between nodes. To move servers to other geographical locations.

**Comment by parkervcp** [comment]
The process of transferring should probably be along the lines of.

1. suspend server. (disable start/stop)
2. lock files. (no making changes while moving)
3. zip and generate hash (for verification later).
4. prep folder on receiving side.
5. ship files using sftp.
6. verify hash and unpack zip.
7. set up server on new host.
8. unlock files
9. resume server. (enable start/stop)
10. Hold files on old daemon for 1w-1m depending so user can verify server status.

**Comment by schrej** [comment]
5.: HTTPS with a generated token might be easier, I'd be fine with both though.
10.: Is this really necessary? When the zip is transferred and verified using the hash, everything should be transferred... Automatically deleting the files after some time just adds additional complexity. If you want to keep them there should be a button to delete the old files (like GitHub does it with pull requests and the branch deletion)

**Comment by lancepioch** [comment]
Anyone up for doing the backup generation? This is the basic layout now: https://github.com/Pterodactyl/Panel/commit/a6a5221af3888b738a0bfa13b67cf3cbd700fc65

**Comment by parkervcp** [comment]
@schrej While I usually agree I also believe we can just keep them around a bit. I don't think it would hurt. Think of it like a remote copy in case something happens.

**Comment by Raideerke** [comment]
So it will not be resolved at all? We're still waiting for server transfer possibility.

**Comment by schrej** [comment]
It will be resolved eventually, it's a highly requested and very useful feature. We just haven't gotten around to do it as it's not that trivial to do in a good way.
It will definitively implemented into the new daemon at some point, not sure about the current one. Progress on the new one is slow at the moment though, we've started to focus on it again in the past weeks though.

**Comment by rouing** [comment]
@parkervcp Should verify somewhere along the way that there is enough disk space to actually make the transfer.

**Comment by prg-as** [comment]
Any update on this?

**Comment by steak-sauce** [comment]
This is why Kubernetes exist. In an ideal world, we could use a Kubernetes endpoint as the "node" and not care which vm the container ends up on.

**Comment by schrej** [comment]
The only reason k8s makes it easier is that you are basically required to use network storage to store any data. But that comes at a performance hit as well as massively more complex setups. Implementing a server transfer system would be a lot easier.
Pterodactyl does support the "we don't care where we end up" part, moving servers between nodes is the complicated part.

**Comment by mmmbacon** [comment]
bump, any update on server -> node migration tool? 

This would be great for administrators.

Also, if anyone can answer this..  what is the practical hit on performance when using K8S and Networked Storage?

**Comment by parkervcp** [comment]
I have been busy recently and progress has stalled at the moment. I plan on working on several things this weekend.

**Comment by steak-sauce** [comment]
@mmmbacon - there are a lot of variables to that question, but assuming you have a properly designed storage system, probably not enough for anyone to notice. Users don't typically begin to notice storage issues until latency creeps above 20ms, which might as well be an eternity.

To @schrej's point, K8s are drastically more complicated as a whole, but the network storage piece is easy to solve.

**Comment by de-Rick** [comment]
Any update?

**Comment by parkervcp** [comment]
Constantly asking for updates doesn't make it happen any faster.

**Comment by Bencor29** [comment]
I think there is one "big" problem: allocations conflicts

**Comment by FlyingBlue** [comment]
Hello,

How to do manual transfer ?

**Comment by JustinRijsdijk** [comment]
> Hello,
> 
> How to do manual transfer ?

A possibility is to suspend the server on the current node, create a new server on your second node, then copy the files to the new server on the second node, after that you can delete the 'old' server.

**Comment by Rokunas** [comment]
Another bump three and a half years later.. Any updates on the progress? Is the feature coming anytime soon?

**Comment by FlyingBlue** [comment]
I use this addon and it work fine 
https://www.mc-market.org/resources/12509/

**Comment by Rokunas** [comment]
> 
> 
> I use this addon and it work fine
> https://www.mc-market.org/resources/12509/

Awesome, Thanks!

**Comment by DaneEveritt** [comment]
Thank you to @matthewpi for taking the lead on implementing this functionality. It is still in a very beta state, but will be shipping with `0.8`.

**Comment by richiedevs** [comment]
oo cool

**Comment by anondev-sudo** [comment]
Also move server backups to new node
