### ISSUE TITLE
Server filter can't filter by node name

### ISSUE THREAD

**Issue by OrangeJuiced** [Pterodactyl/Panel#180]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [ ] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [ ] Bug or Issue
- [ ] Feature Request
- [x] Enhancement
- [ ] Other

Currently the server filter can not filter by node name, only by ID.

**Comment by DaneEveritt** [comment]
closed in 0e89ecb
