### ISSUE TITLE
Wrong message displayed on Admin Panel > Nodes > View Node > Allocations

### ISSUE THREAD

**Issue by CorruptedUbuntu** [pterodactyl/panel#1801]
https://i.imgur.com/ZTY4Cxa.png
^^ In this scenario, I edited the image.
But it shows something like that.

Panel version **0.8.0-alpha1**

**Expected behavior: It should say "Mass Actions"**

**Comment by KnuffelBeestje** [comment]
Hey.

Why are you still using an old panel version?
This issue has been fixed in the latest panel releases.
