### ISSUE TITLE
Weird behaviour of panel/daemon when world generating is taking long.

### ISSUE THREAD

**Issue by Rhydium** [pterodactyl/panel#1802]
* Panel or Daemon: Daemon / Panel
* Version of Panel/Daemon: Panel is running on 0.8.0: Alpha Release 1 / Daemon: Wings v1.0.0 Alpha Release
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows, Chrome

**Describe the bug**
When a Minecraft server is taking long too generate the world it'll get automatically shut down, after refreshing the page it is offline (without errors or stopping it).. then when you try to start it again nothing will happen, after killing it and starting it again it seems to be working again.

**To Reproduce**
1. Go to a Minecraft server you've made in the panel.
2. Click on start and wait. (I'm using Spigot 1.14.4, don't know if this matters)
3. When it takes like 2 minutes to generate a world and the percentage isn't going up anymore refresh the page.
4. Click on start again.
5. Kill the server when nothing happens.
6. Start the server again.

**Expected behavior**
When a Minecraft server takes long to generate a world it'll get stuck at a certain percentage and it won't go any further, when you refresh the page the server is offline. When you start it again nothing will happen, then you kill the server and start it again everything seems to be working again.

**Comment by Rhydium** [comment]
Extra information: 
Server had 3gb of RAM assigned and 20gb of SSD storage, so that shouldn't be the problem.

**Comment by parkervcp** [comment]
You need to wait until it finished printing all the stuff to the console and not reload. You are losing the ability to give us any logs from the startup.

**Comment by Rhydium** [comment]
> You need to wait until it finished printing all the stuff to the console and not reload. You are losing the ability to give us any logs from the startup.

I reloaded it because after 30 minutes nothing has changed, what do you want me to do?

**Comment by parkervcp** [comment]
What was the end of that output? What kind of limits did you set on the cpu?

It sounds like the machine is underpowered if it can't generate a world.

**Comment by Rhydium** [comment]
The end of the output was:
`[Status Change] Server marked as stopping...`

There are no limits on the CPU.

**Comment by DaneEveritt** [comment]
Pretty sure this bug is fixed in the latest go stuff, it was an issue with sending the correct status events over the socket and tracking it internally. If you know how to build from source, you can try that and it should fix your issues.
