### ISSUE TITLE
Directory Bar

### ISSUE THREAD

**Issue by SamBehner** [pterodactyl/panel#1803]
**Is your feature request related to a problem? Please describe.**
It's really annoying to have to wait 8 years for the panel to load a new directory in the file manager.

**Describe the solution you'd like**
There should be some kind of directory bar like the one in FileZilla. The web panel is a lot more convenient that the FTP to me, this would make life 100x easier.

**Describe alternatives you've considered**
I tried looking at how the links work but sometimes it does %2F for a / other times it does something else

**Additional context**
Example of what I'm talking about:
![image](https://user-images.githubusercontent.com/37122399/71644789-61780f80-2c9c-11ea-9e84-5745b225c6a5.png)

**Comment by Lunaversitay** [comment]
The SFTP system is actually quite fast if you're using the GoLang one, I have a suspicion you're still using the nodejs one which is super slow.

You can find the golang sftp system here: https://github.com/pterodactyl/sftp-server

As for the `%2F` things you're talking about it's basically just a `/` you can just add a `/` into the url bar and it'll work just fine.
