### ISSUE TITLE
Admins doesn't see servers in main panel page

### ISSUE THREAD

**Issue by DarKiiii** [pterodactyl/panel#1804]
**Background (please complete the following information):**
* Panel or Daemon:  Panel
* Version of Panel/Daemon: 0.8-alpha / 1.0-alpha
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows / Chrome

**Describe the bug**
Admins doesn't see the servers on the main server page if they are not the owner

**To Reproduce**
1. Create a random server but which your not the owner
2. Go on the server page

**Expected behavior**
I expected that my friends could easily access to the server console.

![Capture1](https://user-images.githubusercontent.com/52256277/71679393-c6f4fa80-2d87-11ea-80c1-dedd7fb5c10b.PNG)
![Capture2](https://user-images.githubusercontent.com/52256277/71679394-c6f4fa80-2d87-11ea-88d7-5e05226fba03.PNG)

**Comment by DarKiiii** [comment]
And I forget but sub-users aren't implemented yet ?

**Comment by DaneEveritt** [comment]
Correct, subuser stuff has not been worked on.

**Comment by DaneEveritt** [comment]
Closed in f45c03a4494b5a129bef9e9c84d5b7c4243ae3f1
