### ISSUE TITLE
Bug editing the schedules on Panel version 0.7.16

### ISSUE THREAD

**Issue by oliveradkins13** [pterodactyl/panel#1806]
![image](https://user-images.githubusercontent.com/56483932/71771130-51775e80-2f2e-11ea-940f-641ec6a9eb32.png)
![image](https://user-images.githubusercontent.com/56483932/71771131-563c1280-2f2e-11ea-96d7-736a36c4663a.png)

I don't have any theme installed.

**Comment by WillMorrow** [comment]
For a better description, the schedule localisation keys don't match the blade template.
![image](https://user-images.githubusercontent.com/11558865/71771150-a1eebc00-2f2e-11ea-9355-56c69a18ed22.png)
![image](https://user-images.githubusercontent.com/11558865/71771152-ab782400-2f2e-11ea-8762-8dd8723fa959.png)

**Comment by oliveradkins13** [comment]
How should I fix this issue?

**Comment by oliveradkins13** [comment]
Solved, please fix this in the next update though.

**Comment by sergiz** [comment]
https://github.com/pterodactyl/panel/pull/1753
Already denied.

**Comment by VizuaaLOG** [comment]
Hmm, this would verify as a bug though. The page title is wrong due to an invalid config key? I.e. typo i.e. not an intended result so a bug.

**Comment by Sir3lit** [comment]
I highly doubt this would be added as it's not a major issue.

**Comment by oliveradkins13** [comment]
![image](https://user-images.githubusercontent.com/56483932/71785476-d0849980-2ff7-11ea-9b3b-45f6706b30db.png)
Also on my friends panel, so it definitely is a bug.

**Comment by DaneEveritt** [comment]
It is indeed a bug, but I'm avoiding any additional releases of the 0.7 series, and it's quite minor.
