### ISSUE TITLE
Chance email content

### ISSUE THREAD

**Issue by Deadsecret** [pterodactyl/panel#1807]
Hello,
How can I change the content of the emails?? For example:

"
[...]
Hello deadsecret. 
Your server has finished installing and is now ready for you to use. 
[...]
"

**Comment by Lunaversitay** [comment]
GitHub issues are for bugs/feature requests, you should ask this stuff in the discord.

Email templates are located in: https://github.com/pterodactyl/panel/tree/master/resources
