### ISSUE TITLE
Can't start any (Paper)Spigot server. CPU CFS Quota ?

### ISSUE THREAD

**Issue by Celemo** [pterodactyl/panel#1808]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.7.16 and 0.6.12
* Server's OS: Debian 9
* Your Computer's OS & Browser: Android 9 and Windows 10 both with Firefox

**Describe the bug**
I'm unable to start any Spigot (ParkerVCP egg) or PaperSpigot server. Whenever the server is old or newly installed, today it's not working and I can't start any of these. My BungeeCord and my Discord Bot (ParkerVCP egg) are both working and PaperSpigot servers were working unless we were uploading much files today via SFTP, we didn't change config and we don't have installed softwares on the server last 5 days, issue appeared today, servers were working yesterday.

**System info :**
`Linux ns****** 4.19-ovh-xxxx-std-ipv6-64 #1038749 SMP Mon Dec 23 08:31:48 UTC 2019 x86_64 GNU/Linux` (I hidden ns******) and https://ptero.co/ecirosedod.sql (docker info) and  https://hastebin.com/yurazozazo (Daemon  diagnostic)
Both docker info and diagnostic showed a thing related to CPU CFS Quotas.

**To Reproduce**
1. Buy a SoYouStart dedicated
2. Install Pterodactyl Panel
3. Use it for some times without any problems
4. Have a bug !

**Comment by DaneEveritt** [comment]
https://pterodactyl.io/daemon/kernel_modifications.html#confirm-kernel
