### ISSUE TITLE
Status not updating after page refresh

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1809]
**Background (please complete the following information):**
* Panel or Daemon: Both
* Version of Panel/Daemon: Alpha 1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win 10 Pro / Chrome

**Describe the bug**
Server status bugs out when the page is refreshed and the server still starting.
https://justmyrandomstuff.com/img/LjA7eXK.jpg

As you see in the video the server is still starting but it says it's offline
https://justmyrandomstuff.com/img/kqHBOKL.mp4
**To Reproduce**
1. Start server that takes a while to start ( modded mc in my case ) 
2. Let it "startup" for a little
3. Refresh page

**Expected behavior**
It should still know the server is "starting" and not give me the option to start / restart it again.

**Comment by Sir3lit** [comment]
Simply clicking start, then refreshing the page breaks, Seems hit and miss

**Comment by Rhydium** [comment]
#1802

**Comment by Sir3lit** [comment]
Build from src, works well. I also have working cpu/ram info.
