### ISSUE TITLE
[0.8A2] Suspending shouldn't force kill, Should be graceful

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1810]
0.8 Alpha 2, When a server is suspended it force kills the container, this can lead to data loss for some games as they save before they close. Issue the stop command would be a better and more friendly solution.

**Comment by parkervcp** [comment]
Pretty sure this is the standard in the old version of the panel as well.

**Comment by Sir3lit** [comment]
Didn't know as I have no need for it, was just testing functionality

**Comment by parkervcp** [comment]
I totally agree with you. I was just calling out that it is what I believed to be the current standard.

**Comment by Sir3lit** [comment]
When a server is suspended, the stop command is sent for a graceful shutdown.

**Comment by matthewpi** [comment]
Just for tracking reasons this behavior was changed in PR #1889
