### ISSUE TITLE
Unable to CTRL-C selected console text

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1813]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Alpha 2
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win10 / Chrome

**Describe the bug**
When highlighting text in the console, CTRL-C does nothing, so you have to right-click and copy, to copy the selected text. 

**To Reproduce**
1. Start Server
2. Select text from the console
3. CTRL-C
4. Try to paste the "copied" text

**Expected behavior**
... To Copy

**Comment by schrej** [comment]
`ctrl + c` probably gets forwarded to the terminal, as it's intended to be used with actual terminals like bash. An issue suggests to use a [custom event handler](https://github.com/xtermjs/xterm.js/blob/4375b3cdb9e36cd2746ff9a101fbeb48f7d0b794/typings/xterm.d.ts#L473-L482), maybe we can stop xterm from processing the event, but still have it propagate in order for the browser to handle it.

**Comment by Sir3lit** [comment]
Hmm I didn't think about that, wouldn't ctrl c kill a minecraft server? If so it didn't do that either.

**Comment by schrej** [comment]
Well, it would if you had an actual connection to a terminal, which is not the case. We only use it as a view for the console, the content gets processed by the daemon, which only handles text, not key events.
