### ISSUE TITLE
Stuck Go-routine fails to exit when WebSocket connection closes

### ISSUE THREAD

**Issue by matthewpi** [pterodactyl/panel#1816]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: Alpha 2 (problem is present on latest develop)
* Server's OS: CentOS 8
* Your Computer's OS & Browser: Windows 10 & Brave

**Describe the bug**
There is a problem with the way the `eventChannel` go-routine functions on the websocket that causes the channel to constantly return `nil` causing the select to keep looping.

https://github.com/pterodactyl/wings/blob/develop/websocket.go#L189-L199

From https://golang.org/ref/spec#Receive_operator :
```
A receive operation on a closed channel can always proceed
immediately, yielding the element type's zero value after
any previously sent values have been received.
```

**To Reproduce**
1. Go to a server on the panel (basically open a WebSocket connection)
2. Go to a page that causes the WebSocket to disconnect (account page, admin, etc)
3. Check `htop` for wings' CPU usage

**Expected behavior**
CPU Usage is low and not killing whatever it can

**Solution**

Replace https://github.com/pterodactyl/wings/blob/develop/websocket.go#L189-L199 with

```go
go func() {
	for d := range eventChannel {
		handler.SendJson(&WebsocketMessage{
			Event: d.Topic,
			Args:  []string{d.Data},
		})
	}
}()
```

**Comment by Sir3lit** [comment]
Before: https://justmyrandomstuff.com/img/LgiW17X.jpg
After: https://justmyrandomstuff.com/img/DOmCyiR.jpg
I can confirm this fixes it. 

You can easily allocate a whole cpu by just refreshing a single console page multiple times and watch the cpu usage climb.

**Comment by DaneEveritt** [comment]
Its a feature not a bug? 🐛
