### ISSUE TITLE
Add support for game: Urban Terror 4.3.4

### ISSUE THREAD

**Issue by seanbarr1988** [pterodactyl/panel#1817]
https://github.com/thomasleveil/docker-UrbanTerror

Game is based on Quake 3 Arena (I believe similar to ET.Legacy) Could someone please add support for this game with pterodactyl ?

Thanks! <3

**Comment by parkervcp** [comment]
Better to open this here - https://github.com/parkervcp/eggs

**Comment by seanbarr1988** [comment]
Sorry I’m still new to github and pterodactyl. Thanks for moving this to the correct place

**Comment by parkervcp** [comment]
I didn't move it. I was saying you should open this over there.
