### ISSUE TITLE
Better Permission System (For Moderation)

### ISSUE THREAD

**Issue by steevLP** [pterodactyl/panel#1819]
I run into a Problem where i wanted to add my Supporters and Admins to the panel.
The problem i am talking about is i cannot give them ALL permissions they just don't need everything especially not as supporters.

I would like to have a System like the Subuser permission System where i can add a role and select what permissions the role has so i can access my staff members only what they need for their role in my company

An alternative i would consider is a hardcoded role for example Admin moderator and supporter if my primary idea not would be possible to make

**Comment by schrej** [comment]
#279 
It's even pinned.

**Comment by fdsfdsdfsdsfds** [comment]
So the system of permits was abandoned.
