### ISSUE TITLE
Incorrect spelling in heading

### ISSUE THREAD

**Issue by kalleswe** [pterodactyl/panel#1821]
* Panel or Daemon: None
* Version of Panel/Daemon: None
* Server's OS: None
* Your Computer's OS & Browser: None

**Describe the bug**
There's a spelling error in multiple of the documentation pages on the website.

Panel: No idea what you run
Daemon: No idea what you run

**To Reproduce**
1. Go to any of the following pages:

https://pterodactyl.io/community/installation-guides/daemon/debian10.html
https://pterodactyl.io/community/installation-guides/daemon/debian9.html
https://pterodactyl.io/community/installation-guides/daemon/centos8.html
https://pterodactyl.io/community/installation-guides/daemon/centos7.html
https://pterodactyl.io/community/installation-guides/daemon/ubuntu1804.html

4. See error:

In the first paragraph at the end of the sentence it says:
"configure it to use a SSL connection."
but it should say:
"configure it to use an SSL connection."

**Expected behavior**
Since you use "an" in front of words where the prounounciation starts with a vovel sound. In this case it starts with an E-sound (of the letter S).

**Comment by parkervcp** [comment]
We have a repo for this - https://github.com/pterodactyl/documentation
