### ISSUE TITLE
Non-functional Restart. 

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1822]
**Background (please complete the following information):**
* Panel or Daemon:  Panel
* Version of Panel/Daemon:  Alpha 2
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win10 / Chrome

**Describe the bug**
Clicking Restart does nothing.
https://justmyrandomstuff.com/img/6svO0Nd.gif

**To Reproduce**
Attempt to restart a server that is running. 

**Expected behavior**
The server to be issued the stop command, then the start action once its shutdown gracefully.

**Comment by matthewpi** [comment]
I wouldn't really call this a bug, it is just unimplemented.

https://i.imgur.com/6vwm5N7.png
https://github.com/pterodactyl/wings/blob/develop/websocket.go#L378

**Comment by Sir3lit** [comment]
This has already been fixed in the latest dev build pulled on 4/9/2020
