### ISSUE TITLE
Schedules are not reaching destination

### ISSUE THREAD

**Issue by LavRad** [pterodactyl/panel#1823]
**Background:**
* Pterodactyl Panel: 0.7.16
* Pterodactyl Daemon: 0.6.12
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows/Mac, Safari/Firefox

**The Issue:**
I've been having this problem for just over a week now:
Schedules don't run at their allocated times, and also stay queued when triggered. Effectively, the schedules cannot reach the Minecraft servers they need to run on. I've selected a wide range of logs around to try piece together what's going wrong, but I'm at a dead end.

PHP: 7.4.2 (https://prnt.sc/qwkb8r)
Docker: Linux ns3062997 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
Setup a schedule for a specific time, or setup a schedule then trigger it.
The schedule will stay "Queued", or if it is setup for a specific time then the "Next Run" will start counting backwards.
https://prnt.sc/quraia
https://prnt.sc/qurawu

**Expected behavior**
I expect the schedules to be carried out in the server console, however there is no sign whatsoever of this happening.

**Pteroq Service Status (Various Results):**
https://prnt.sc/qurbh7
https://prnt.sc/qwdvdz
https://prnt.sc/qwdxbf

**Journalctl Results sometimes show:**
https://prnt.sc/qwdy7z

Whenever I trigger a schedule in the panel, I get this error when I've done the command:
*/usr/bin/php /var/www/pterodactyl/artisan queue:work --queue=high,standard,low --sleep=3 --tries=3*

https://prnt.sc/qwdx7y

**Redis Status:**
https://prnt.sc/qwdxld

If you need any more information let me know,
Thank you

**Comment by parkervcp** [comment]
Were the pterodactyl files ownership set correctly?

Generally speaking not being able to write files means the user doesn't have permission in the folders.

**Comment by LavRad** [comment]
I applied 777 to all of /var/www/pterodactyl
It seems the new logs created everyday by the pteroq service don't get these updated permissions, so I have to manually update the permissions daily.

**Comment by parkervcp** [comment]
What shows up when you run `ls -Alh` on /var/www/pterodactyl

**Comment by LavRad** [comment]
https://prnt.sc/qwkrse

**Comment by srkhost** [comment]
Is your schedules table empty in your DB?
Don't you have some failed servers in the table?

**Comment by LavRad** [comment]
>Is your schedules table empty in your DB? ...

@srkhost All the schedules are there, and when I change them in the DB that is reflected in the panel as well

**Comment by srkhost** [comment]
So there is no failed servers. Only active and working servers.
hmm:O,o

**Comment by LavRad** [comment]
https://prnt.sc/qwyed8

The servers are completely fine, the schedules don't run though.
See the above photo for what the schedules look like in Phpmyadmin.

**Comment by DaneEveritt** [comment]
Is `pteroq` running?

**Comment by LavRad** [comment]
> Is `pteroq` running?

You can see the various results I get from "service pteroq status" above.

**Comment by LavRad** [comment]
Any ideas?

**Comment by LavRad** [comment]
Issue resolved - Panel was running PHP 7.2, while it seems the Schedule part of the setup managed to use 7.4.2.
