### ISSUE TITLE
Fix default theme

### ISSUE THREAD

**Issue by Greenus** [pterodactyl/panel#1826]
Pls fix the default theme (lang file), go (Schedule Manager) and Create New Schedule.

![image](https://user-images.githubusercontent.com/60868683/74125937-ec6ef280-4bd6-11ea-9310-6749fac116f2.png)

* Panel or Daemon: 
* Version of Panel/Daemon: panel v0.7.16, daemon v0.6.12
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win 10x64 Chrome and Firefox

**Comment by Sir3lit** [comment]
This most likely will not be fixed and ts not a major issue or bug and 0.8 is in the works, iirc only security issues and major bugs will be fixed.

**Comment by Greenus** [comment]
How can I fix it myself?

**Comment by Sir3lit** [comment]
Look at the commit I just did above

**Comment by Greenus** [comment]
I understand, but who can tell me how I can fix it myself?

**Comment by Sir3lit** [comment]
Edit the file that I edited on your end and remove the S at the end of the word schedules.
