### ISSUE TITLE
Wrong time in console / plugins

### ISSUE THREAD

**Issue by bloggy** [pterodactyl/panel#1828]
* Panel or Daemon: ptero 0.7.12
* Version of Panel/Daemon: 0.7.12
* Server's OS: Ubuntu

**Describe the bug**
The console time (in the logs) is 1 hour behind the system time (of dedicated server/ubuntu). Schedules are correct and the time zone is set up correctly in the env-file:
APP_TIMEZONE=Europe/Berlin

**To Reproduce**
Open console log files, compare with system time

**Expected behavior**
Have console time the same as system time.

**Comment by parkervcp** [comment]
What is the output from `timedatectl | grep “Time zone”` on your system.

**Comment by bloggy** [comment]
This:
https://i.imgur.com/wIKRLl4.png

**Comment by gabrielvinhais** [comment]
I had the same problem, added tzdata to the Egg installation script and added the variable "TZ=America/Sao_Paulo" to the container and solved...

https://serverfault.com/a/683651

**Comment by lancepioch** [comment]
Thank you @gabrielvinhais 

@bloggy Let us know if that solution didn't work and we'll take another look

**Comment by bloggy** [comment]
> I had the same problem, added tzdata to the Egg installation script and added the variable "TZ=America/Sao_Paulo" to the container and solved...
> 
> https://serverfault.com/a/683651

Egg installation script? I have pterodactyl already running and I am not able to reinstall all the stuff again. How can I fix this on a running ptero?

**Comment by parkervcp** [comment]
It looks like just adding a variable to the server is all that is needed.

**Comment by bloggy** [comment]
And how would I do it? I tried several things, but nothing worked.

**Comment by parkervcp** [comment]
You add an environment variable to the docker-compose.yml.

**Comment by bloggy** [comment]
Can you write the line that I need to add? And where can I find the docker-compose.yml ?

**Comment by parkervcp** [comment]
Or add it as a variable to your server

**Comment by bloggy** [comment]
I don't know what's better, but how can I do it? Can you give me some instructions?

**Comment by bloggy** [comment]
Actually it's 2 hours difference to the real time now due to switching to summer time in europe. A fix or step-by-step instruction on how to fix this issue would be appreciated.

**Comment by bloggy** [comment]
Still no reply on how to fix this in detail :-( Any suggestions or step-by-step instruction?

**Comment by matthewpi** [comment]
This has already been fixed in the `Wings 1.0` beta, as a temporary work around you can add a variable to the egg your server is using the following settings.

https://i.imgur.com/bqEMOCy.png

**Comment by bloggy** [comment]
> This has already been fixed in the `Wings 1.0` beta, as a temporary work around you can add a variable to the egg your server is using the following settings.
> 
> https://i.imgur.com/bqEMOCy.png

Thank you @matthewpi I will test this. In your screenshot you have set "UTC" as timezone. Is this correct for me, too? because another user replied here and mentioned I need to set "Europe/Berlin" as timezone (our server is located in Germany) ?

**Comment by parkervcp** [comment]
The list of timezones on wikipedia should be "safe" for setting as a timezone. UTC is GMT so it would be behind you by 1 or 2 hours by daylights savings time

https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by bloggy** [comment]
> The list of timezones on wikipedia should be "safe" for setting as a timezone. UTC is GMT so it would be behind you by 1 or 2 hours by daylights savings time
> 
> https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

so instead of UTC I have to set "Europe/Berlin", right?

**Comment by bloggy** [comment]
Tested today and doesn't work. Maybe I need to add something to server's startup parameters?

**Comment by Hutch79** [comment]
I know this issue is closed and over 3yo, but it was the first result on Google and still has no "good" solution.

I managed to fix this by editing `/etc/pterodactyl/config.yml`
In there is an option `timezone:` which you can set to your local zone.

After that, I restarted wings and pteroq with `systemctl restart wings` and `systemctl restart pteroq` and the time was displayed correctly in the console after I restarted the game server.

**Comment by Areomayo** [comment]
> I know this issue is closed and over 3yo, but it was the first result on Google and still has no "good" solution.
> 
> I managed to fix this by editing `/etc/pterodactyl/config.yml` In there is an option `timezone:` which you can set to your local zone.
> 
> After that, I restarted wings and pteroq with `systemctl restart wings` and `systemctl restart pteroq` and the time was displayed correctly in the console after I restarted the game server.

This worked for me, thank you :)

**Comment by TarikBerk** [comment]
> I know this issue is closed and over 3yo, but it was the first result on Google and still has no "good" solution.
> 
> I managed to fix this by editing `/etc/pterodactyl/config.yml` In there is an option `timezone:` which you can set to your local zone.
> 
> After that, I restarted wings and pteroq with `systemctl restart wings` and `systemctl restart pteroq` and the time was displayed correctly in the console after I restarted the game server.

I was wondering why it wouldn't change and all I had to do was restart the game server. Thanks.

For those who may need a little more help:
Find your corresponding timezone here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
Change directory to where config.yml is located: `cd /etc/pterodactyl`
Open config.yml using text editor: `nano config.yml`
Either find "`timezone`" yourself or find it by pressing `CTRL + W` and typing "`timezone`" and change it to your desired timezone.
Restart wings: `systemctl restart wings`
Restart pteroq: `systemctl restart pteroq`
Restart your game server through the panel.

**Comment by funnycubeguy** [comment]
still an issue...

**Comment by Hutch79** [comment]
> still an issue...

Look at one comment above yours. There are detailed instructions on how to solve it.

This is not an Issue, it's a misconfiguration.
