### ISSUE TITLE
Ads for the panel

### ISSUE THREAD

**Issue by jorickjuh** [pterodactyl/panel#1829]
Ads on panel?

**Comment by Lunaversitay** [comment]
assuming you're asking about putting ads on the panel, you can literally do anything you wan with the panel, but there's no built in ad support so you'll need to do it yourself

**Comment by jorickjuh** [comment]
How could i do that?

**Comment by lancepioch** [comment]
Not relevant to the panel.

**Comment by raapoo** [comment]
Can you teach me how?

**Comment by TnkrrGit** [comment]
> Can you teach me how?

The problem is, i don't know how
