### ISSUE TITLE
Console Doesn't Match System Time

### ISSUE THREAD

**Issue by Keviince** [pterodactyl/panel#1830]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.16
* Server's OS: CentOS 7.7
* Your Computer's OS & Browser: Windows/macOS Edge/Safari

**Describe the bug**
The time in the console doesn't match system time.
Exmaple : There is 01:07:51 in the console
BUT when I command "date" in system it reports "Wed Feb 12 09:08:37 CST 2020"
"cat .env" reports "APP_TIMEZONE=Asia/Shanghai" and "APP_LOCALE=en"

**To Reproduce**
Compare console time with the system time.

**Expected behavior**
Console time matches the system time

**Comment by parkervcp** [comment]
Console time is what is set on your server. This is not a panel issue.

**Comment by Keviince** [comment]
> Console time is what is set on your server. This is not a panel issue.

Daemon Server? it also reports "Wed Feb 12 09:14:27 CST 2020" when I command "date"

**Comment by parkervcp** [comment]
Your system time is set to CST not shanghai time. The panel env doesn't change that. You are getting a raw console from the server not parsed by the panel.

**Comment by Keviince** [comment]
> Your system time is set to CST not shanghai time. The panel env doesn't change that. You are getting a raw console from the server not parsed by the panel.

I used "timedatectl status" and it comes "Local time: Wed 2020-02-12 11:32:55 CST
  Universal time: Wed 2020-02-12 03:32:55 UTC
        RTC time: Wed 2020-02-12 03:32:55
       Time zone: Asia/Shanghai (CST, +0800)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: n/a"
