### ISSUE TITLE
How to find API Docment

### ISSUE THREAD

**Issue by leoweyr** [pterodactyl/panel#1832]
I have searched your official website. But there seems to be no documentation found for the API.Api, outreach is really important,Especially for our Minecraft servers.Because porn allows us to find online players on the server and These online players are reflected on third-party web pages.Or execute a command through the API on a third-party Web page.

**Comment by Sir3lit** [comment]
Didn't know porn can help with minecraft servers, maybe read over what you typed before clicking submit... 


Unofficial api documents can be found @ https://dashflo.net/docs/api/pterodactyl/v0.7/
