### ISSUE TITLE
Error 500 while trying to save settings on the panel

### ISSUE THREAD

**Issue by alsoGAMER** [pterodactyl/panel#1834]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.16
* Server's OS: Debian Buster
* Your Computer's OS & Browser: Manjaro 19 with Firefox Developer Edition 73.0b11

**Describe the bug**
If i go to the panel settings and try to save any change, a 500 error will be returned
Panel: `PHP 7.2.28-1+0~20200220.36+debian10~1.gbpcf4a75`

**To Reproduce**
1. Go to 'panel settings'
2. Edit anything
3. Click on 'Save'
4. Error 500

**Expected behavior**
The panel should work fine

**Additional logs**
http://bin.ptdl.co/gv6mh

**Comment by Sir3lit** [comment]
Are you using a custom theme? Are any other versions of PHP installed?

**Comment by alsoGAMER** [comment]
> Are you using a custom theme? Are any other versions of PHP installed?

No custom, yes I've other versions of PHP, but I've configured the system to use php 7.2 by default

**Comment by Sir3lit** [comment]
Hmm, are one of those other versions PHP 7.4?

**Comment by alsoGAMER** [comment]
> Hmm, are one of those other versions PHP 7.4?

Yes

**Comment by Sir3lit** [comment]
Hmm, would it be possible to remove that version, 7.4, and see if you still get the same error? as we know the panel isn't compatible with that version.

**Comment by alsoGAMER** [comment]
> Hmm, would it be possible to remove that version, 7.4, and see if you still get the same error? as we know the panel isn't compatible with that version.

Sadly nope..

**Comment by Sir3lit** [comment]
If you could, that'd be great.

**Comment by alsoGAMER** [comment]
Ok, now it is working, great!

But, when the compatibility with PHP 7.4 will be added?

**Comment by Sir3lit** [comment]
According to Dane, its a priority to have 7.4 compatibility soon

https://github.com/pterodactyl/panel/issues/1777#issuecomment-589190915

**Comment by alsoGAMER** [comment]
Noice, thanks for the information!
