### ISSUE TITLE
banned on discord for "ban evasion"

### ISSUE THREAD

**Issue by thegamerx1** [pterodactyl/panel#1835]
![image](https://user-images.githubusercontent.com/34986564/75091924-eb44aa80-5572-11ea-9f1d-a0188bf6046f.png)
I only have 1 account of discord how could i evade a ban?

! [( TheGamerX )]#7912

**Comment by schrej** [comment]
Sorry, a guy with a very similar name was banned shortly before you joined, that's why we assumed ban evasion. I've unbanned you.

**Comment by ghost** [comment]
Hello,

I was banned for advertising.

Discord ID | roguebros23#0232
