### ISSUE TITLE
Server's cannot use internet

### ISSUE THREAD

**Issue by Sm4k1na** [pterodactyl/panel#1836]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.12
* Server's OS: centOS 8
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
Every server I create can't conect to the internet, plugins and also the server itself cannot check for updates and if the server is premium I can't log in 

**To Reproduce**
I just installed the panel and Daemon, it works fine and opened theright ports on the firewall

**Expected behavior**
Server should be able to connect to the internet

**Comment by parkervcp** [comment]
can't access the internet or dns is failing?

**Comment by parkervcp** [comment]
Also please read this - https://pterodactyl.io/community/installation-guides/daemon/centos8.html

**Comment by Sm4k1na** [comment]
I did it when I installed my panel and daemon, as I think it's dns resolving from the point that I can access the serevr, but it can't check updates or even letting me in if it's in premium mode

**Comment by parkervcp** [comment]
Give me a while and I can check it later. I found a dns issue and don't have the command to fix it right now.

**Comment by Sm4k1na** [comment]
Ok, thanks for the time and the quick answer.

**Comment by parkervcp** [comment]
I found it... I PR'd it for the docs but it hasn't been merged yet - https://github.com/pterodactyl/documentation/pull/179/files

**Comment by Sm4k1na** [comment]
Thanks that fixed it
