### ISSUE TITLE
Edit File Permissions from Web File Management

### ISSUE THREAD

**Issue by gabriel3l** [pterodactyl/panel#1837]
I know this can be already done by entering the SFTP Client and tweaking the permission codes by right-clicking the files/folder and change it, but it would be good to have such tool also in the web panel, in the file management tab, so people can easily fix "permission denied" errors - in case they replace an executable file (jars, server files etc..) and don't know that this can be fixed through SFTP Client.

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/wings/commit/f62f71486375266061acaac63beb6d942f4e08f5

Just need to add the panel endpoint and UI for it.
