### ISSUE TITLE
404 error on /auth/login

### ISSUE THREAD

**Issue by ScribbleNerd** [pterodactyl/panel#1838]
**Background (please complete the following information):**
* Panel or Daemon: 
    Pterodactyl
* Version of Panel/Daemon: 
    v0.7.16
* Server's OS: 
    Ubuntu Server 18.04.4 LTS
* Your Computer's OS & Browser: 
    Windows 10 Version 2004 (OS Build 19569, 1000) Insider Build
    Chrome 80.0.3987.122 (Official Build) (64-bit)

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

php -v
    `PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies`

uname -a
    `Linux imac122 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

docker info
    `Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-88-generic
Operating System: Ubuntu 18.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 19.58GiB
Name: imac122
ID: WRDN:S5LR:ZSCP:GBMI:YEMK:D6IE:56Z5:FFS7:USGR:N4SE:XPUH:7PWA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support`

My server is giving me 404 error after installing... its trying to go to {panelurl}/auth/login which doesn't exist... is it supposed to?

**To Reproduce**
1. Install pterodactyl
2. Go to the panel url
3. it redirects to /auth/login and it throws a 404 because it doesn't exist

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

Its supposed to go to the normal login page I'm guessing

**Comment by InVaLiD-github** [comment]
/auth/login does exist, just not precisely there. Pterodactyl does some webserver magic and makes /auth/login redirect to where /auth/login resides. (i still don't know where it is though.)
It might be useful to post your pterodactyl.conf here, even though I already have yours and see no issue with it. the only thing I can think of is that you're using a sub-sub domain and it's confusing pterodactyl because it's looking for /auth/login (at least the redirect for it) on the mc subdomain, it would be a hassle but I would try moving the entire panel to panel.mysite.com and skip the mc subdomain.

**Comment by SaigyoujiYuyuko233** [comment]
Did you set the rewrite rule and set the wwwroot to the ```/public``` dir?

**Comment by arcdigital** [comment]
It sounds like your web server is configured incorrectly. Since this isn't a bug with the software, please ask for support on our Discord.

Note: You actually can use a subdomain like `something.else.cooldomain.com`, this won't cause any issues.
