### ISSUE TITLE
Daemon: docker, mount /etc/timezone 

### ISSUE THREAD

**Issue by kamcio96** [pterodactyl/panel#1840]
```
      - "/etc/timezone:/etc/timezone:ro"
```

**Comment by parkervcp** [comment]
This is not enough information for anything. I am closing it out.

**Comment by kamcio96** [comment]
docker-compose configuration dosen't mount /etc/timezone so daemon's logs has mismatched date

**Comment by parkervcp** [comment]
How is this panel related if it's the daemon. We don't even have the daemon in a container officially...

**Comment by kamcio96** [comment]
I posted here because daemon doesn't have `Issue` section. 

> We don't even have the daemon in a container officially

I don't think it's good explanation :/

**Comment by parkervcp** [comment]
You still failed to fill out the issue report items as required by all issues. I will continue to keep this closed.
