### ISSUE TITLE
Daemon is offline after using Cloudfare

### ISSUE THREAD

**Issue by Sm4k1na** [pterodactyl/panel#1842]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.12
* Server's OS: centOS 8
* Your Computer's OS & Browser: Chrome/Windows 10

After I started using Cloudfare my panel says that the daemon is offline, I turned off ssl and turned on behind a proxy, what am I doing wrong

**To Reproduce**
Using cloudfare

**Comment by schrej** [comment]
That's a configuration issue, not a bug. Please use our discord server at https://discord.gg/pterodactyl for support.
