### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by RivalPlayz** [pterodactyl/panel#1843]
i have a mc plugin that needs mongodb.. mongo is installed on the same VPS as pterodactyl... is there a way to get mongodb to work with pterodactyl

**Comment by sergiz** [comment]
Create a DB manually and connect your plugin to it? There's nothing for pterodactyl to support really.

**Comment by parkervcp** [comment]
This is not a panel issue. You need to modify your mongo db to allow access from 172.18.0.1 much like our standard db config in the docs
