### ISSUE TITLE
Persistent Folders

### ISSUE THREAD

**Issue by FrinkMan** [pterodactyl/panel#1844]
Not sure where this should be put, but I haven't gotten any answer on the Discord server. Can I keep certain folders in a container persistent? I'm using an SQLite database for a Discord bot, but everytime Pterodactyl pulls the latest git repo, it removes the sqlite database...

**Comment by parkervcp** [comment]
If the repo has a copy of the sqlit db there when it does a pull it's probably overwriting it.

**Comment by FrinkMan** [comment]
There is no data folder in the github repo, I'll try setting it up as a new server
