### ISSUE TITLE
401 on the /apI/remote/eggs when attempting to launch daemon

### ISSUE THREAD

**Issue by GhastD** [pterodactyl/panel#1847]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon:  0.7.16/0.6.12
* Server's OS: Ubuntu 18.04.4 LTS
* Your Computer's OS & Browser: Windows 10/Firefox Latest

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
`--| Docker Information
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-88-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.11GiB
 Name: ns375625
 ID: TVJ3:23EN:UGWD:YATY:ORIU:G4XE:HED4:U7HD:SLCD:3POG:N3DW:NWIR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
`
Issue:

`--| Latest Logs
13:34:42.907Z  INFO wings: + ------------------------------------ +
13:34:42.908Z  INFO wings: | Running Pterodactyl Daemon v0.6.12    |
13:34:42.908Z  INFO wings: |        https://pterodactyl.io        |
13:34:42.908Z  INFO wings: |  Copyright 2015 - 2019 Dane Everitt  |
13:34:42.908Z  INFO wings: + ------------------------------------ +
13:34:42.908Z  INFO wings: Loading modules, this could take a few seconds.
13:34:43.115Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
13:34:43.126Z  INFO wings: Creating keypair to use for SFTP connections.
13:34:44.999Z  INFO wings: Configuring user pterodactyl (id: 999) as the owner of all server files.
13:34:45.018Z  INFO wings: Configuring timezone file location...
13:34:45.052Z  INFO wings: Checking container networking environment...
13:34:45.063Z  WARN wings: No isolated network interface for containers was detected, creating one now.
13:35:00.359Z  INFO wings: Successfully created new network (pterodactyl_nw) on pterodactyl0 for isolated containers.
13:35:00.360Z  INFO wings: Ensuring correct network interface for containers...
13:35:00.367Z  INFO wings: Networking gateway detected as 172.18.0.1 for interface: pterodactyl0.
13:35:00.401Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
13:35:00.423Z FATAL wings: A fatal error caused the daemon to abort the startup.
    Error: Error while attempting to fetch list of Eggs from the panel.
        at Request [as _callback] (/srv/daemon/src/controllers/service.js:95:31)
        at Request.self.callback (/srv/daemon/node_modules/request/request.js:185:22)
        at Request.emit (events.js:198:13)
        at Request.EventEmitter.emit (domain.js:448:20)
        at Request.<anonymous> (/srv/daemon/node_modules/request/request.js:1157:10)
        at Request.emit (events.js:198:13)
        at Request.EventEmitter.emit (domain.js:448:20)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/request/request.js:1079:12)
        at Object.onceWrapper (events.js:286:20)
        at IncomingMessage.emit (events.js:203:15)
    --
    additional: {
      "responseCode": 401,
      "requestURL": "http://redacted.com/api/remote/eggs"
    }`

Tried everything, nothing works. Everything is handled with HTTP. I've properly configured everything.

**To Reproduce**

Install both latest panel and daemon on a Ubuntu 18.04 LTS machine running Apache.
Launch the panel then the daemon.
See if the issue happens.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

It's supposed to connect to the panel

**Comment by Sir3lit** [comment]
The key in the core.json is wrong.... Recopy it from the configuration tab

**Comment by parkervcp** [comment]
This should be handled on the discord server.

**Comment by GhastD** [comment]
I have tried both these things. None work. The discord has not given any sort of support, this is an issue directly in pterodactyl.

**Comment by parkervcp** [comment]
One way or another your daemon is getting denied by the panel. That is what a 401 error is. That is why they said to copy the config over again.

**Comment by GhastD** [comment]
I have multiple times. Ports are open, everything should work fine but it doesn't.

**Comment by parkervcp** [comment]
Please verify the remote url in the daemon config. If it's an ip address it may be hitting another site.

**Comment by GhastD** [comment]
Verified everything. After updating the panel to the latest release, the issue was solved.
