### ISSUE TITLE
Allow max connections to be set for user databases

### ISSUE THREAD

**Issue by iamkubi** [pterodactyl/panel#1849]
Add the ability to limit database connections for user databases.  This can prevent a user with a bad plugin from consuming all of the available database connections for a database host.

At a quick glance I expect this would be done at:
https://github.com/pterodactyl/panel/blob/7543ef085d1b466536e37efc6c4d679fb82797ae/app/Repositories/Eloquent/DatabaseRepository.php#L153-L161

This could be updated to specify max_user_connections if configured in the database host settings.

**Comment by iamkubi** [comment]
I'll take a stab at implementing this for 0.8.

**Comment by Sir3lit** [comment]
This would have to be dependant on what the servers max connections are set to?  Iirc it's like 150 by default?

**Comment by iamkubi** [comment]
It could be, but I don't think it has to be.  Right now there is no max connections, so all connections to the database are effectively limited to 150.  The problem is that one server can use all 150 of those connections and prevent any other servers from being able to use the database host.

This will allow you to set a threshold per server (or more specifically database user), so you can limit a server to say 15 simultaneous connections.  There's no need to alter the server's max, because it would be exhausted regardless of this change.

**Comment by Sir3lit** [comment]
Working on adding this, the correct location would be when the user is created as it's defined as `MAX_USER_CONNECTIONS` when the user is created 

https://github.com/pterodactyl/panel/blob/7543ef085d1b466536e37efc6c4d679fb82797ae/app/Repositories/Eloquent/DatabaseRepository.php#L140-L143

**Comment by Sir3lit** [comment]
@iamkubi I hope you're referring to `Concurrent Connections` if so... Would it be something like this? 
![](https://justmyrandomstuff.com/img/bLswkKn.gif)
