### ISSUE TITLE
Webspace Hosting Function

### ISSUE THREAD

**Issue by Trimilur** [pterodactyl/panel#1850]
Hi I would like to request a simple webspace hosting function. Just for automatical deployment of simple nginx/apache related sites. For basic websites forum etc. it's most time unnessessary to have a full webhosting panel and the user appreciate to have everything in one panel.

**Comment by ZeProf2Code** [comment]
This will not be shipped directly in the panel but you can create a egg for it yourself.

**Comment by parkervcp** [comment]
There are better free and open source panels that do the job better than pterodactyl ever will.

**Comment by Trimilur** [comment]
Ok @ZeProf but my problem with an nginx app ist that i dont know how to create multiple nginx server cause they cannot listen all to http/s ports so i only can create one nginx container which i cannot share with multiple users. any good idea?

**Comment by parkervcp** [comment]
I am actually closing this this time. I was on my phone last time. There are open source panels that are better suited or this.
