### ISSUE TITLE
Error when creating a database

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [pterodactyl/panel#1852]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.16
* Server's OS: Ubuntu Server 18.04.4 LTS
* Your Computer's OS & Browser: MacOS + Chrome

**Describe the bug**

PHP 7.3.15-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.
    with Zend OPcache v7.3.15-3+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

When creating a DataBase on a client server, got a 500 error with panel error saying that the generated password does not meet requirement (mysql medium)

**To Reproduce**
1. Install Mysql with password verification on medium
2. Install panel
3. Add Node and DataBase Node
4. Try to create a database
5. See the error

**Expected behavior**

Normaly the database should be created but here it's not
I'v seen that it's already be pathed but seems to not work ... :(
Panel error and stack trace here:
https://pastebin.com/raw/ikX28aSq

**Comment by ZeProf2Code** [comment]
That's a configuration issue, not a bug. Please use our discord server at https://discord.gg/pterodactyl for support.

**Comment by TomAvecLeVdsl** [comment]
Okay, but not so sure ... 
I will ask in the discord

**Comment by DaneEveritt** [comment]
This is not a configuration issue and is, in fact, a bug with the software as indicated by the error included in his report.

**Comment by Lemmmy** [comment]
Is there any chance a configuration option for password length could be added? Our server requires passwords to be >=64 chars with symbols.

**Comment by DaneEveritt** [comment]
@Lemmmy please open a new issue with feature requests, we do not re-open closed issues unless it is related to the same issue.
