### ISSUE TITLE
Server mod sleeping

### ISSUE THREAD

**Issue by Ho2x** [pterodactyl/panel#1853]
Hello,

did you work or plan to develop an addon that would make the servers (minecraft) once without any players going into sleeping mode.
A bit like the McMyAdmin panel does.

thank you

**Comment by DaneEveritt** [comment]
This will not be added, I do not have the bandwidth available to make something like this.

**Comment by Ho2x** [comment]
Is this happening at your bandwidth level? I admit that I don't fully understand how this functionality works then.

**Comment by parkervcp** [comment]
He's the sole dev for the whole panel and daemon. There is no-one else who really develops on the panel at a level that, I would hazard, would support Dane stepping back some.

**Comment by Ho2x** [comment]
Do you think a script like this can be automated with the panel?
https://github.com/gekigek99/minecraft-vanilla-server-hibernation

**Comment by Timongcraft** [comment]
> 

If you are still searching for a solution this should be it:
https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg
