### ISSUE TITLE
Server not starting error

### ISSUE THREAD

**Issue by LewaIngame** [pterodactyl/panel#1855]
Hello i have bought a dedicated server and i got problem with pterodactyl

![image](https://user-images.githubusercontent.com/36868377/76781999-e65cca80-67af-11ea-8588-abc9e1685ca1.png)

`[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 4237M / 102400M
[Pterodactyl Daemon] Ensuring correct ownership of files.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] A fatal error was encountered while starting this server.`

**Comment by parkervcp** [comment]
This should be taken to the discord server. This is one of the things the bot would respond to already.
