### ISSUE TITLE
CPU limit problem

### ISSUE THREAD

**Issue by LewaIngame** [pterodactyl/panel#1857]
Hello,
I got cpu limit problem my serveur doesn't have cpu limit and i added 50% on cpu limit i have 1200% available and the serveur as the 1200% and no the 50%

**Comment by LewaIngame** [comment]
I am on 7.13 of panel to use Pterodactyl Panel Minenite Theme

**Comment by parkervcp** [comment]
The panel is now on 0.7.17. As you are running a custom theme and not up to date I see those as potentially causing the issue.

**Comment by LewaIngame** [comment]
The problem is the creator doesnt make update

**Comment by LewaIngame** [comment]
https://github.com/minenite/paneltheme

**Comment by DaneEveritt** [comment]
We do not support outdated versions of this software, regardless of the reason.

**Comment by ZeProf2Code** [comment]
@DaneEveritt He is also using a leaked theme :/
