### ISSUE TITLE
Banned for no reason on discord server

### ISSUE THREAD

**Issue by StrayanDropbear** [pterodactyl/panel#1858]
Hello, I asked a simple question on discord and the responses from your support team was disgraceful. 
I simply argued this with Kubi and I got banned? not even a warning, just a straight up ban. Do you really expect people to use your software when you treat them this way? your discord is FULL of abuse from your support team, a problem that's been occurring way too frequently.

"Try again later" is the reasoning for the ban. Nice to see you have power hungry admins.

**Comment by parkervcp** [comment]
You have been unbanned from discord. I talked to kubi before you even opened this as I saw it happen before I had a chance to respond to anything.

**Comment by StrayanDropbear** [comment]
Thank you.
