### ISSUE TITLE
Use same allocation (additional) as a messaging service

### ISSUE THREAD

**Issue by mnewt00** [pterodactyl/panel#1859]
**Is your feature request related to a problem? Please describe.**
When I try to setup a plugin like NuVotifier or CommandSync, it requires a listener port. With pterodactyl, you can't give two servers the same additional allocation.

**Describe the solution you'd like**
I would like that the same additional allocations (ports) could be added to multiple servers (i.e a plugin messaging service)

**Describe alternatives you've considered**
I have considered not using pterodactyl panel, and instead running the server in 'sh' files, however, that would cause a **HUGE** inconvenience for me and my players.
**Additional context**
BTW, I am not talking about a main allocation, I am talking about an additional port that could be used in a messenger and listener configuration

**Comment by parkervcp** [comment]
This is impossible in general because all the servers can't do this by default. You can only have a single listener per port already. It's the same reason all your game servers can't use the same port.

**Comment by mnewt00** [comment]
Well could I access port that's on another server's additional allocations but not on the main?
Server.pro can do it, so why can't you?

[https://www.youtube.com/watch?v=m-xrV5TzjbI](https://www.youtube.com/watch?v=m-xrV5TzjbI)

**Comment by parkervcp** [comment]
You obviously didn't actually watch that because each server used a different port
![image](https://user-images.githubusercontent.com/1207679/77240254-3249ae00-6bba-11ea-8dd9-2c3c77bb4f19.png)

**Comment by mnewt00** [comment]
I meant to say firewall, but then I remember, that you can connect local.
