### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by AToska21** [pterodactyl/panel#1860]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.17 Panel
* Server's OS: Debian 10 (Buster)
* Your Computer's OS & Browser: MacOS 10.14 Mojave | Safari 13.0.5

When I try to create a server on the panel, It gives me a HTTP/E_CONN_REFUSED error. Also when I try to see the node status, it infinite loads.
php -v:
PHP 7.3.14-1~deb10u1 (cli) (built: Feb 16 2020 15:07:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

1. Go to Servers
2. Click on Create New
3. Fill out the form
4. (on my computer) See Error

**Expected behavior**
It should create the server and start running.

**Extra Info**
I am using the panel and daemon on the same computer. I access pterodactyl from 192.168.XX.XXX. The Daemon is up to date.

(sorry for linethrough on the php idk how to fix it)

**Comment by parkervcp** [comment]
Please use the discord server for support for this issue.
