### ISSUE TITLE
Can't edit Dockerfile file

### ISSUE THREAD

**Issue by kamcio96** [pterodactyl/panel#1863]
Hi
I can't edit Dockerfile from web panel.
![image](https://user-images.githubusercontent.com/1339911/77267073-b7f45900-6ca1-11ea-802a-a9e5b9ae3c13.png)

**Comment by DaneEveritt** [comment]
Please fill out the template that you ignored when opening this issue.

**Comment by DaneEveritt** [comment]
Wont fix, duplicate of #1544. The issue stems from `mmmagic` thinking it isn't one of the editable file types.
