### ISSUE TITLE
Assets do not load properly due to integrity errors.

### ISSUE THREAD

**Issue by PJZ9n** [pterodactyl/panel#1865]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.8.0 Alpha-2
* Server's OS: Linux version 4.18.0-25-generic (buildd@lcy01-amd64-025) (gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1~18.10.1)) #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019
* Your Computer's OS & Browser: Windows 10 Pro 1803 (Build: 17134.1304), Google Chrome 80.0.3987.149（Official Build）64Bit 

**Describe the bug**
The server's JS and CSS will not load properly due to an integrity error.
PHP Version:
PHP 7.2.19-0ubuntu0.18.10.1 (cli) (built: Jun  4 2019 14:46:43) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.10.1, Copyright (c) 1999-2018, by Zend Technologies

**To Reproduce**
1. Access the panel.

**Expected behavior**
Display the control panel or login page normally.
![screenshot_20200323_221837](https://user-images.githubusercontent.com/38120936/77320693-6062f580-6d54-11ea-87f0-5cfd3e90db18.png)

Finally, I was not good at English and used Google Translate. Thank you for reading.

**Comment by gabrielvinhais** [comment]
Try using PHP 7.4

**Comment by DaneEveritt** [comment]
Interesting. For now you can try doing `yarn install && yarn run build:production` in the root of the panel and it should generate valid assets for you.

**Comment by PJZ9n** [comment]
Then I ran that command and it was displayed correctly.
Sorry for the late reply.

![screenshot_20200327_013718](https://user-images.githubusercontent.com/38120936/77671859-8514d280-6fcb-11ea-9e84-a18985f3f0d1.png)

**Comment by DaneEveritt** [comment]
Think this is fixed in the beta.
