### ISSUE TITLE
Migrating Pterodactyl panel to another webeserver

### ISSUE THREAD

**Issue by PetrCZE** [pterodactyl/panel#1866]
Hello,
I would like to migrate Pterodactyl panel to another webserver but I don't know how to do it exactly. I tried to migrate it but I get error 500 with no-saying logs.

Kind regards

**Comment by Lunaversitay** [comment]
The github issues are primarily for breaking issues with the pterodactyl panel - you should ask for support in the discord: https://pterodactyl.io/discord
