### ISSUE TITLE
IP problem

### ISSUE THREAD

**Issue by LewaIngame** [pterodactyl/panel#1867]
Hello, 

I got 2 IP on my dedicated server and i learn it https://github.com/pterodactyl/panel/issues/459

I do the 2 solution and not work how i can use my second ip

**Comment by schrej** [comment]
This is not a bug within Pterodactly, so please ask for help on our discord: https://discord.gg/pterodactyl

**Comment by LewaIngame** [comment]
Banned 

LewanIngame#2133

**Comment by schrej** [comment]
I won't unban you. But as it's been over a year, I won't ban you for ban evasion as long as you follow the rules.
