### ISSUE TITLE
500 error when update build configuration

### ISSUE THREAD

**Issue by OfficialBart** [pterodactyl/panel#1868]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.17
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 64-bit 1909 (build 18363.720) & Chrome

**Describe the bug**
Minecraft bukkit paper server
When editing the CPU Limit in Build Configuration when server is off gave 500 error
https://bin.ptdl.co/frumq/

**To Reproduce**
1. Go to Admin Control Panel
2. Go to servers
3. Click on a minecraft paper server
4. Go to Build Configuration
5. edit CPU Limit (i want to put it on 200)
6. Click Update Build Configuration
7. Error 500 pops up

**Expected behavior**
Fix the 500 error so i can change the CPU Limit

**Comment by parkervcp** [comment]
This should be handled in the discord server. On a related note, It looks like theme you have is for an older build of the panel.
