### ISSUE TITLE
Wrong help message by responsive

### ISSUE THREAD

**Issue by PJZ9n** [pterodactyl/panel#1872]
**Is your feature request related to a problem? Please describe.**
Incorrect 2fa help

**Describe the solution you'd like**
2fa QR codes are not always displayed on the left. Must support responsive design.

**Describe alternatives you've considered**
Change help message:
Use the 2FA application on your phone to take a picture of the QR code to the left, or manually enter the code under it. Once you have done so, generate a token and enter it below.
to
Use the 2FA application on your phone to take a picture of the QR code, or manually enter the code under it. Once you have done so, generate a token and enter it below.

**Additional context**
[Related language files](https://github.com/pterodactyl/panel/blob/0.7-develop/resources/lang/en/base.php#L86)

PC View
![screenshot_20200327_023840](https://user-images.githubusercontent.com/38120936/77678217-299b1280-6fd4-11ea-906c-f4df7e6009ca.png)

Smart Phone View
![screenshot_20200327_023904](https://user-images.githubusercontent.com/38120936/77678247-3455a780-6fd4-11ea-8faf-32a6707b68b5.png)

**Comment by DaneEveritt** [comment]
Thanks, if someone wants to PR this into 0.8 with better language they can, but this is barely an issue and I don't want to flood the issues list with tiny things like this.
