### ISSUE TITLE
Incorrect Allocations help message

### ISSUE THREAD

**Issue by PJZ9n** [pterodactyl/panel#1874]
**Is your feature request related to a problem? Please describe.**
Incorrect Allocations help

**Describe the solution you'd like**
Allocations list are not always displayed on the left. Must support responsive design.

**Describe alternatives you've considered**
Change help message:
The list to the left includes all available IPs and ports that are open for your server to use for incoming connections.
to
The list  includes all available IPs and ports that are open for your server to use for incoming connections.

**Additional context**
[Related language files](https://github.com/pterodactyl/panel/blob/0.7-develop/resources/lang/en/server.php#L331)

PC View
![screenshot_20200327_044156](https://user-images.githubusercontent.com/38120936/77689936-e2b61880-6fe5-11ea-82cf-f5b27e59280e.png)

Mobile View
![screenshot_20200327_044215](https://user-images.githubusercontent.com/38120936/77689939-e34eaf00-6fe5-11ea-9348-f0e317f3f1f6.png)

**Comment by gabrielvinhais** [comment]
As far as I know, version 0.7 is just getting security updates

**Comment by Sir3lit** [comment]
When you view it on a desktop the list is to the left :)

**Comment by DaneEveritt** [comment]
Thanks, if someone wants to PR this into 0.8 with better language they can, but this is barely an issue and I don't want to flood the issues list with tiny things like this.
