### ISSUE TITLE
File Manager Error (0.7.17)

### ISSUE THREAD

**Issue by sam-chapp** [pterodactyl/panel#1879]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.17
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 / Chrome

**Describe the bug**
I am currently having an issue with the file manager when I go to access the file manager I get this error "File Error" "An error was encountered while processing this request." This is from a fresh install on a new host. 

**To Reproduce**
1. Go to 'your panelr'
2. Click on 'your server of choice'
3. Click on 'file manager'

**Expected behavior**
Once on file manager I should be able to acess all my files and edit, compress and delete files etc.

**Comment by parkervcp** [comment]
Please get your logs - `tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99`

**Comment by sam-chapp** [comment]
Here you go http://bin.ptdl.co/amjew

**Comment by parkervcp** [comment]
Your timezone is bad. Here is the list of supported timezones. https://www.php.net/manual/en/timezones.php

It looks like you want "Europe/London" though
