### ISSUE TITLE
Issue when attempting to start a TeamSpeak server

### ISSUE THREAD

**Issue by James76931** [Pterodactyl/Panel#188]
Hey,

I was just trying to start my TeamSpeak3 Server, but I got an error saying: "An unhandled exception occured while attempting to process this request." Whilst seeing that error when pressing the start button, the console read: "(Daemon) Server detected as booting." as usual but nothing happened.

**Info.log:**
https://gist.github.com/James76931/99957a0c54c27e4b5dacce4e7b2db7e8

**Error.log:**
https://gist.github.com/James76931/ec8bc376ed9d36b6e908249c8437db5c

**uname -a:**
Linux vps 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**php -v:**
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies

_- James_

**Comment by DaneEveritt** [comment]
closed in Pterodactyl/Daemon@307e9eb
