### ISSUE TITLE
File upload aborted by server

### ISSUE THREAD

**Issue by NoxInmortus** [pterodactyl/panel#1880]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel:  v0.7.16
* Server's OS: Debian 10 64bits
* Your Computer's OS & Browser: Firefox latest version
* PHP version: PHP 7.2.28
* NGINX version: 1.16

When trying to upload "large" (22mb works but from 30mb it fails) files in the File Management (for a Minecraft server), I get an instant red popup on the lower-right of the browser saying
" An error was encountered while attempting to upload this file: File upload aborted by server".

When I try to look at php/nginx/redis/syslog or even pterodactyl panel laravel logs with `APP_DEBUG=true`, I have absolutely NOTHING that can explain that to me. Neither in journalctl of any of thoses.

I have 
```
fastcgi_param PHP_VALUE "upload_max_filesize = 400M \n post_max_size=400M";
client_max_body_size 400m;
client_body_timeout 120s;
```
In my nginx conf, and 
```
memory_limit = 1G
post_max_size = 400M
upload_max_filesize = 400M
```
In my php/7.2/fpm/php.ini configuration.

I dont see where to look anymore so I'm asking here. Thanks for your time.

**Comment by arcdigital** [comment]
I can't reproduce this, I can upload files over 30mb without any issues. This seems like a configuration issue on your side. You can try to see if someone on Discord can help you. Check your daemon config (uploads.size_limit) and make sure you restarted nginx and php-fpm after you changed these values.

**Comment by NoxInmortus** [comment]
Hello @arcdigital , what is uploads.size_limit parameter and how to change it ? This is not from nginx or php-fpm

**Comment by arcdigital** [comment]
it is in your daemon config file which is probably in /srv/daemon/config/core.json. Please ask any other questions related to this on discord.

**Comment by NoxInmortus** [comment]
That was it... Thanks
