### ISSUE TITLE
Corrupted data on SFTP

### ISSUE THREAD

**Issue by Legomix13** [pterodactyl/panel#1881]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.13
* Server's OS: 16.04.6 LTS (Xenial Xerus)
* Your Computer's OS & Browser: Windows 10 | Chrome

**Describe the bug**
Whenever a file gets uploaded using the SFTP server it gets corrupted (the hash changes) but using the panel interface to upload it does not give any problems

**To Reproduce**
Upload a file using web browser check the hash of the uploaded file
Delete the file
Upload the same file using SFTP and check the hash

**Expected behavior**
The hash of the SFTP uploaded file changes (corrupted)

EDIT:

USING INTERNAL SFTP SERVER

**Comment by DaneEveritt** [comment]
What SFTP server, the one internal to the daemon, or the Go one?

**Comment by Legomix13** [comment]
internal

**Comment by DaneEveritt** [comment]
Please try utilizing the standalone one, the internal one is riddled with issues and we're not really supporting it since the standalone on performs significantly better.

**Comment by lifewcody** [comment]
I've had the same issue. The internal one needs to go ASAP. I've been fighting with corruption for a bit now.

**Comment by DaneEveritt** [comment]
Closing this since it is in the legacy node code which I won't be touching.
