### ISSUE TITLE
Qeustion sending a command via cli too the minecraft server running in the docker.

### ISSUE THREAD

**Issue by TheCompieter** [pterodactyl/panel#1883]
I want too execute a command from a backup script inside the minecraft server running inside the docker container but i am totaly new too dockers and have no clue how too do that. as of why i want this is too send a alert command too bungeecord too say that server performance can be degraded while the backup is running so people know what is going on

**Comment by DaneEveritt** [comment]
Please use Discord for help with requests like this: https://pterodactyl.io/discord

**Comment by kalleswe** [comment]
Please do not use discord for this. Please post working example reply in this thread so others can benefit from it.
