### ISSUE TITLE
Auto Shutdown and Wake on LAN for Nodes

### ISSUE THREAD

**Issue by CamGenius** [pterodactyl/panel#1888]
**Is your feature request related to a problem? Please describe.**
I run my server at home but don't always need it to be on when nobody is connected. If the panel could manage turning off the node and turning on again when needed then then my server wouldn't always have to be on.

**Describe the solution you'd like**
There should be an option for Nodes where if nobody has connected for lets say 30 minutes then it safely shuts down the Servers then shuts down the Node. Then when somebody wants to connect the Panel will send a Wake on LAN request to turn it back on and the Server that was requested.

**Describe alternatives you've considered**
N/A

**Additional context**
I would use this future by installing the Panel on a low power Raspberry Pi and the Daemon on my Server so that only the Raspberry Pi needs to be on 24/7.

**Comment by arcdigital** [comment]
This sounds like something that could be implemented outside of the panel as a script. Unfortunately, this is not a common use-case, so it's not something we can support as a feature in the panel.

**Comment by BSXRay** [comment]
i was looking for the exact same thing, it would be great to have it implemented in the panel
