### ISSUE TITLE
Ability to allow only granting start stop restart kill button to user without console

### ISSUE THREAD

**Issue by ColaIan** [pterodactyl/panel#1890]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I'd like to have the ability to only grant start stop restart kill button to user without console

**Comment by Sir3lit** [comment]
Have you looked into the sub-users permissions?

![](https://justmyrandomstuff.com/img/VucLQPU.jpg)

**Comment by ColaIan** [comment]
Hello thank you for your reply, previously I have tried the options you have mentioned, but none of the options disables the console screen. By disabling "Send Console Command" option, it only disable the ability to send a console command, instead of disabling the console screen.

**Comment by DaneEveritt** [comment]
This wouldn't work super well, the stop/start actions are pretty dependent on being able to see the console output to know if it is working well. When they hit the daemon it is processed in the background. Its not a blocking request, so the user would just be hitting the button with no idea if it was working or not.

**Comment by ColaIan** [comment]
I know it's kinda dumb, but it would be pretty helpful if we could allow maybe like moderators to restart the server without them having access to our console in case of emergency server crashes.

**Comment by DaneEveritt** [comment]
I don't think I'm going to add this functionality right now, but it should be possible with a little bit of custom code if you wanted. :)
