### ISSUE TITLE
Password Changing Problem

### ISSUE THREAD

**Issue by danielnaaman** [pterodactyl/panel#1891]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.8.0 Alpha 2
* Server's OS: Ubuntu 18.04.04 LTS (Latest LTS)
* Your Computer's OS & Browser: Chrome 80.0.3987.163 (64-bit) | Windows 10 Pro (64-bit)

**Describe the bug**
Panel: PHP 7.3.16-1+ubuntu18.04.1+deb.sury.org+1
When changing the password in the new panel, it refuses to accept the new password and after logging me out I'm still only able to use my old password. [Example can be seen here](https://buttoned.staticusercontent.com/danieln/vcuFIlhpnI.gif).
The example above shows me using a 48 characters password that I copy and pasted to the appropriate field and upon change the panel still only recognized my old password. It could be related to the length of the password.

**To Reproduce**
1. Go to 'URL/account'
2. Add input to 'Current Password, followed by the two confirmation fields.'
3. Click on 'Update Password'
4. Try to login with the new password.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

I expected that upon password change, the new password will come into place.

**Comment by matthewpi** [comment]
I am able to reproduce this on the latest develop.

However I did find something interesting when digging into the cause of this issue. In the [`AccountController.php`](https://github.com/pterodactyl/panel/blob/develop/app/Http/Controllers/Api/Client/AccountController.php#L81), if you comment out Line 81 the new intended password works on when logging in.

Looking back into `0.7-develop` I found this is how the password is updated in the [`AccountController.php`](https://github.com/pterodactyl/panel/blob/0.7-develop/app/Http/Controllers/Base/AccountController.php#L73).

Looking at the differences I would assume that the password is being updated twice for the user in 0.8.
