### ISSUE TITLE
Minor changes request on Description, Startup Command and Ports allocation

### ISSUE THREAD

**Issue by NoxInmortus** [pterodactyl/panel#1894]
First of all, thanks for your hard work, I really like it. But, I have noticed several details that could be improved, if I may :

- Server/nodes creation : Description should be optional. if I have every information I need with the name or other available informations, I dont want to bloat the display with redundant details

- Egg creation : Startup Command should be optional. I dont understand why it should be mandatory. All the docker images I ever wrote are configured through environments variables, and for all the images I had used, I never met one with a required `--command` arg. Optional yes, but never mandatory.

- Port allocation on node : More than 1000 ports at once should be allowed. I dont know why it is limited, but it's annoying.

- Also, documentation needs to be more explicit, as there as a lot of things unclear. For example, I'm adapting an image to be Pterodactyl compliant, and I had to dig out (almost reverse engineering!) that I needed to have everything important in /home/container, and I had to ask confirmation on Discord. /home/container is mentioned once in the documentation, but nothing explicit. An other example would be to have the docker-cli equivalent, like, the "Startup Command" bloc in a egg, refer to the `--comand` docker argument. Stuff like that.

I did not verify if every point I mentioned was already somewhere on an issue, if it's the case, my deepest apologies.

**Comment by parkervcp** [comment]
1 - I agree
2 - The startup command gets parsed in the entrypoint to use those variables.
3 - Why would you allocate more than 1000 at a time?
4 - we don't use `--command` The startup command itself is a variable. `/home/container` is a volume mount. You install `/mnt/server/` another volume mount.

**Comment by NoxInmortus** [comment]
@parkervcp 
About 2: Yes, I got that, but why make it mandatory if the image may start on itself ? I dont see the point.

About 3: Simple, I make one node, and I know I will run and test several servers, and they use completely differents ports. Ports I may not yet know. I dont want to bother myself going back to allocate new ports every time I want to do something. I want to be able to allocate e.g 2000-5000  because I at least know it will be in this range.

About 4: From what I understood, the startup command would be the equivalent of 
`docker run myImage ${StartupCommand}`. Am I wrong ? Because if I'm not then, this is the `--comand` parameter, but it's implicit.
About the volumes, you are confusing me, can you clarify ? 
I first tried to create an egg with an unmodified image (it had 2 volumes), and it tried to mount `/home/container`. Are you saying that Wings will mount the volume you defined in the case you have a single volume, but if anything goes wrong it tries to mount `/home/container`?

**Comment by parkervcp** [comment]
2. The way the startup is managed is a 2 part in the entrypoint. It uses eval to replace the variables to manage many things.

3. You are the only person I have seen complain about the 1000 port limit. You can of course edit this on your own - https://github.com/pterodactyl/panel/blob/7543ef085d1b466536e37efc6c4d679fb82797ae/app/Services/Allocations/AssignmentService.php#L20

4. The `/home/container/` folder is a docker volume. It is mounted when the server is started. It's also mounted during the install process at `/mnt/server/`

You install to `/mnt/server/` and it gets mounted as `/home/container/` when the server starts

**Comment by NoxInmortus** [comment]
About 2) Are you saying that the variables on a server are NOT environnements variables but ONLY used for the Startup Command ?

About 3) Well I can make a PR to raise that, but this limit existence is just...weird.

About 4) I honestly do not understand, I never saw any mention of `/mnt/server` in any doc. Do you have a image repository I can access as an example ?

**Comment by parkervcp** [comment]
2. They are environment variables. The startup command is also an environment variable.

3. I don't think that would be accepted.

4. The `/mnt/server/` is only a part of the install process and you would only see it in an egg. There are no images that would show you that mount point.

**Comment by NoxInmortus** [comment]
2: If the Startup command is an env var, what's the variable name ? And what is the point of this variable ? This is so confusing !!! 
3: Why is that? What's the goal of this limitation ?

This is so frustrating, I'm sorry to bother you this much, I'm just trying to understand

**Comment by DaneEveritt** [comment]
The port limit is for a single range at a time, not a total count. More than 1000 at a time is a performance drain because of how we store them and we basically have to generate large SQL insert statements.

Any changes would need to be PR'd against the `develop` branch which is our alpha version that is not yet released, we're not accepting PRs for features/small bugs to 0.7.

**Comment by NoxInmortus** [comment]
Hello @DaneEveritt , thanks for clarifying. 

So, if I understand this, because it is not very intuitive, the Startup Command is not used by the container ? If I can reformulate this in another way, its sole purpose is to be displayed for the user in the panel ?

**Comment by parkervcp** [comment]
The startup command is in the container as the `STARTUP` variable.

See here how it's used - https://github.com/parkervcp/images/blob/base/debian/entrypoint.sh#L8

**Comment by NoxInmortus** [comment]
@parkervcp thanks, that is something clear as crystal. But it shows how much the documentation is missing... :(

**Comment by NoxInmortus** [comment]
To synthesize this discussion :

- Make all description fields optional
- More complete documentation

Other requests can be discarded.
