### ISSUE TITLE
422 Response when installing certian egg

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1899]
**Background (please complete the following information):**
* Panel or Daemon: Both?
* Version of Panel/Daemon: Dev build as of 4/9/2020
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win 10 Pro /  Chrome Beta

**Describe the bug**
Wings replies with 422 Unprocessable Entity

**To Reproduce**
1. Create Server with bungee cord egg

Seems to only happen to this egg? Only tested the Minecraft Eggs, all others work.

**Comment by lancepioch** [comment]
422 happens when a validation error is triggered, if you turn on debug mode or retrieve the logs, it'll tell you which validation error is being hit.

**Comment by Sir3lit** [comment]
Debug mode in wings is already enabled and it only shows the post request. Shouldn't the panel of caught it before it was passed to wings?

**Comment by DaneEveritt** [comment]
closed in  3d224993cd88259cb6fbb330d6f25d9afcfe68bc
