### ISSUE TITLE
Allocated memory doesn't get set properly

### ISSUE THREAD

**Issue by OrangeJuiced** [Pterodactyl/Panel#190]
The set memory amount doesn't get set properly.

**Exact steps I took when I ran into this problem:**
1. Create a Minecraft Spigot server.
2. Start the server and accept eula.
3. Change allocated memory to something else in the build configuration.
4. Restart the Minecraft server.

The amount of memory doesn't change after doing this. Seems like at least 2 rebuilds are required to fix this.

Also encountered the memory not being set in the startup command at all:
`java -Xms128M -XmxM -Djline.terminal=jline.UnsupportedTerminal -jar server.jar`

This happens when you click "save startup arguments". Even without changing anything.

**Additional information:**
Server also automatically stops after starting to start again.
```
[14:20:04] [Server thread/INFO]: Starting GS4 status listener
[14:20:04] [Query Listener #1/INFO]: Query running on 0.0.0.0:25578
[15:55:54] [Server thread/INFO]: Stopping the server
[15:55:54] [Server thread/INFO]: Stopping server
[15:55:54] [Server thread/INFO]: Saving players
[15:55:54] [Server thread/INFO]: Saving worlds
[15:55:54] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[15:55:55] [Server thread/INFO]: Saving chunks for level 'world_nether'/Nether
[15:55:55] [Server thread/INFO]: Saving chunks for level 'world_the_end'/The End
```

**`docker exec -it -u 0 <container id> env` output:**
```
31879d6cb336
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=container
TERM=xterm
STARTUP=-Xms128M -Xmx{{SERVER_MEMORY}}M -Djline.terminal=jline.UnsupportedTerminal -jar {{SERVER_JARFILE}}
SERVER_JARFILE=server.jar
DL_VERSION=latest
DL_PATH=redacted
LANG=C.UTF-8
JAVA_VERSION=8
JAVA_UPDATE=112
JAVA_BUILD=15
JAVA_HOME=/usr/lib/jvm/default-jvm
USER=container
HOME=/home/container
```

**Docker Inspect output:**
https://gist.github.com/OrangeJuiced/28eec874000ef0c0ccb9f9561de624bf

**Comment by DaneEveritt** [comment]
And you said that the container does rebuild successfully, even when this happens (i.e. console says it is rebuilding).

We also got results in the Discord channel showing that the environment variables appeared to not be changing correctly when editing memory.
