### ISSUE TITLE
Servers stuck on installing for 2 days

### ISSUE THREAD

**Issue by MilkLegend** [pterodactyl/panel#1900]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.17 (On Website/Panel)
* Server's OS: Debian 10 Buster
* Your Computer's OS & Browser: Have no idea, I use Google Cloud's VM and just shows cmd.

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: 7.3.14-1~deb10u1
Daemon: 4.19.0-8-cloud-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux & 
![image](https://user-images.githubusercontent.com/40525094/79000934-2c891d80-7b13-11ea-98ba-30f8aa503725.png)

**To Reproduce**
1. Create a server on Paper or Bungeecord
2. Server is stuck on installing

**Expected behavior**
The server would finish installing and would ask me to accept the minecraft EULA.

**Comment by DaneEveritt** [comment]
This is an issue with the communication link between the daemon and the panel, please join the discord server for further help debugging this as it is not an issue with the software.

**Comment by MilkLegend** [comment]
I've asked Discord support about 5 times already (Trying my 6th attempt, my previous 5 was before I created this issue) Only 1 person tried to help but said my logs were empty (Running the command `npm run diagnostics`)

**Comment by Sobble2546** [comment]
Im having the same problem

**Comment by Captain-Pumpkinhead** [comment]
Y'all ever figure out a solution?  I'm trying to figure this out, too.
