### ISSUE TITLE
Daemon Issue with Ubuntu 18.04

### ISSUE THREAD

**Issue by hollowvi8** [pterodactyl/panel#1908]
Daemon doesn't seem to install on Ubuntu 18.04
My Team has tried installing it on more than 1 Dedicated Servers and it doesn't seem to work. So we are having to use another Operating system.

**Comment by hollowvi8** [comment]
And Before anyone asks. We have installed Daemon Before.

**Comment by schrej** [comment]
This is not a bug. Ask for help in our Discord.

**Comment by hollowvi8** [comment]
I did. More than 1 People have helped me. Its not working. I even got people that own hosts to do it. Still not.

**Comment by DaneEveritt** [comment]
It runs fine on 18.04. Additionally you failed to include any of our bug reporting template, so I'm not sure how anyone would have been able to help regardless. :)
