### ISSUE TITLE
Allow separate Frontend/Backend port configuration for Daemon to proxy setups

### ISSUE THREAD

**Issue by adaliszk** [pterodactyl/panel#1919]
**Is your feature request related to a problem? Please describe.**
When using a proxy in front of the Daemon, the port defined in the Node setting for daemon has to be exposed on the Daemon´s server as the Panel will try to reach the Daemon on the defined port. When set to the proxied port (eg: 443) then the proxy will able to forward the frontend to the backend but as soon as you auto-deploy the config will change the Daemon´s port.

**Describe the solution you'd like**
When the "Behind Proxy" is set to "Behind Proxy" then show up a new field to set the Frontend port on which the Panel will call the Daemon FQDN and leave the current "Daemon Port" as the backend port configuration.

**Describe alternatives you've considered**
Alternatives could be:
- use the default 8080 port for the configuration file regardless of what is set for the "Daemon Port"
- allow the edit of the configuration file on the panel before the daemon would auto-deploy
- when doing an auto-deploy on the daemon side, ask if we want to change the port
- add an extra property to the core.json to set the proxy port on which the daemon will listen

**Additional context**
I´m using ccarney16´s docker images with jwilder´s nginx proxy and letsencrypt companion. The way it´s constructed is:
```
jwilder/nginx-proxy:443
  -> ccarney16/pterodactyl-panel:80 (admin.domain.tld)
  -> ccarney16/pterodactyl-daemon:8080 (serverid.domain.tld)
```
and the panel is set to call: `serverid.domain.tld:443`

I know it´s not exactly an official image, but I could not find an official image to use, and if there is no auto-deployment done then the manual config is fine, this is just a "nice to have" request.

**Comment by mattmalec** [comment]
What do you mean by auto-deploy? You have to copy a command from the panel to copy the config over. You're still welcome to modify the `core.json` after the fact. I'm not too sure about the proxy port thing as the daemon API is mainly just used by the panel internally.

**Comment by DaneEveritt** [comment]
Excellent issue details!

So if I am understanding this correctly, you just want the auto-deployment to account for the panel connecting to the daemon using a port other than the port the daemon is configured to listen on?

**Comment by adaliszk** [comment]
> What do you mean by auto-deploy? You have to copy the command from the panel to copy the config over. You're still welcome to modify the core.json after the fact. The panel doesn't modify it automatically. I'm not too sure about the proxy port thing as the daemon API is mainly just used by the panel internally.

Yes, that is exactly the behaviour and the workaround I'm using. It is true that after it has been configured there is little reason to pull the config again, but nonetheless, when other admins are in the picture they might forget that there are extra steps to be taken on the daemon side.

> So if I am understanding this correctly, you just want the auto-deployment to account for the panel connecting to the daemon using a port other than the port the daemon is configured to listen on?

Yes, that is exactly the feature request. Currently, I'm achieving this by manually configuring the daemon after an update and never do an "auto-deploy" fetch. I've run into issues not only with this port configuration but also wrong docker network being used and getting errors whilst starting with the interface being set.

So far what I'm missing from the panel:
- setting the Data path after a node has been added (modifying the database works)
- setting the daemon port differently to the two sides (daemon, panel)
- no way to set the docker network and it doesn't seem to be created automatically
- no way to configure the SSL certificate locations (no need for it atm, but eventually I will want to have self-signed certs between the proxy and the containers to ensure encryption all the way)
- cannot edit the config manually to save it for the deployment
- no YAML format

I manage to manually change them on the core.json, but eventually, I want to create a CI/CD pipeline for the servers we use so then everything would be automatically handled as soon as an admin add a new server.

A note though @DaneEveritt, I'm using the node daemon as that one has a docker image to use for DinD setup. Should I switch to the in-development Go version? I can help with Docker/Kubernetes DevOps 😉

**Comment by parkervcp** [comment]
Is it docker in docker or docker controlling the host docker. Those are very different.

**Comment by adaliszk** [comment]
@parkervcp right, I always forget that the UNIX socket is not actually DinD 😄 
the image/daemon has a docker client and the container has the socket linked into it so then the client can reach it. The server containers are created on the host.

**Comment by matthewpi** [comment]
Implemented in react-admin.

**Comment by bcat** [comment]
I was about to file a feature request for this when I found this issue. I know it's fixed in the upcoming admin UI, but I'm curious if it would be practical to backport to the 1.x admin UI. (I understand if it's not practical or desired, but I figured it didn't hurt to check since I wasn't sure when 2.x will release.)

There's a workaround in the meantime (editing the port manually in the Wings config file), but it's error-prone since whenever the node is reconfigured in the panel, the panel sends Wings a new config with the incorrect port number, requiring the config to updated manually again to avoid Wings coming up on the wrong port next time it restarts.

For context, the reason I proxy Wings with different public vs. local port numbers is because my setup requires DNS challenges to obtain SSL certs (which Wings `auto-tls` doesn't support), and I already use Caddy on the node machines to handle all cert provisioning.

I could run a `certbot` instance just for Wings, but that's another point of failure I'd like to avoid since I'd still be running Caddy for other servers on the node machines anyway. So instead I have Caddy provision a cert for `wings.server.example.com`, then reverse proxy `wings.server.example.com:443` => `localhost:8080` (where Wings listens and serves HTTP traffic).

**Comment by Boy132** [comment]
> [...] whenever the node is reconfigured in the panel, the panel sends Wings a new config with the incorrect port number [...]

FYI, there is a config option in the wings config to disable the auto-updates from the panel. (`ignore_panel_config_updates`)

**Comment by bcat** [comment]
> > [...] whenever the node is reconfigured in the panel, the panel sends Wings a new config with the incorrect port number [...]
> 
> FYI, there is a config option in the wings config to disable the auto-updates from the panel. (`ignore_panel_config_updates`)

Oh, that's really good to know. At least that means that every time I tweak RAM allocation for the VM my node runs in, I don't need to manually restore the correct Wings config. :)
