### ISSUE TITLE
Navbar Links Are Invisible On Server Pages To Other Admins

### ISSUE THREAD

**Issue by tonystarksucks** [pterodactyl/panel#1920]
**Background:**
* Panel or Daemon: 1.0.0
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 & Chrome

**Describe the bug**
Admins who did not create the server do not see other navbar options on server pages other than console. This is only a UI bug and the pages are still available by manually typing in the URLs.

**To Reproduce**
1. Go to any server page as an admin user that did not create the server.
2. The only navbar item visible is "Console"

**Expected behavior**
The expected behavior is that any admin would have access to view all navbar options on any server regardless of if they created the server or not.

**Comment by Sir3lit** [comment]
If an admin is added as a sub-user, they're then able to view the tabs again. It should be noted that calling the tabs via the URL allows the admins to access them, but tabs are still not visible.

**Comment by DaneEveritt** [comment]
Yeah, sounds like my permissions response logic isn't quite right on the backend.
