### ISSUE TITLE
Deleting all backups when deleting the server?

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#1921]

**Comment by mattmalec** [comment]
Don't expect to make any progress with this issue without providing any details for your question. There are issue templates for a reason.

**Comment by adaliszk** [comment]
I wonder what backups (s)he talking about. I'm new but so far I only saw compression files as a backup which still lives in the server's folder which means if you delete the server you will lose all the files.

**Comment by mattmalec** [comment]
Regardless of what they're talking about, the point of having backups is to be able to restore the server if you lose data or it's accidently deleted. It wouldn't make sense to delete them, especially if your backups are on S3 for example.

**Comment by parkervcp** [comment]
You didn't fill it any information on this and I will be coming it out
