### ISSUE TITLE
Make all description fields optional

### ISSUE THREAD

**Issue by JordanPlayz158** [pterodactyl/panel#1922]
**Is your feature request related to a problem? Please describe.**
Can't leave description field blank.

**Describe the solution you'd like**
Make all description fields optional like server create field (Node and location require description field, is what I've seen so far)

**Describe alternatives you've considered**
Putting some random things in the description field.

**Additional context**
https://cdn.fastermc.xyz/vlTbqh4

**Comment by DaneEveritt** [comment]
Partial of #1894
