### ISSUE TITLE
My DAEMON does not want to connect to my pterodactyl panel

### ISSUE THREAD

**Issue by K0asBest** [pterodactyl/panel#1927]
I have cloudflare but I deactivate the proxy and I left in dns only and it and all day in https but before its launching but one day its crashed and my DEAMON did not work anymore possible to help me ?

ERROR:  jquery.min.js?t=8ec4eb32bb6bc92c5398fa3d150ddf8a:4 OPTIONS https://panel.fantaheberg.info:8080/v1 net::ERR_CONNECTION_TIMED_OUT

**Comment by DaneEveritt** [comment]
Please use Discord this support, you ignored the entire template that explicitly says _not_ to use this issue tracker for these types of issues.
