### ISSUE TITLE
No UUID set on Nodes when created

### ISSUE THREAD

**Issue by erviker** [pterodactyl/panel#1930]
**Background (please complete the following information):**
* Panel
* Version of Panel: canary 
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 Firefox

**Describe the bug**
Can not add more then one node to the panel
Getting error 500 error.
UUID field is inserted blank on all nodes thats being created and the field are a unique key

**To Reproduce**
1. Create node 1
2. Create node 2
4. See error get 500 error

**Expected behavior**
The secund node wil be created

**Comment by parkervcp** [comment]
Well he's not wrong. It does 500 when you try to create a second node.

logs are as follows - https://bin.ptdl.co/vnljh/

**Comment by dexter-dz** [comment]
Wings launch successfully, FQDN is also setup and pings but Node shows offline on the panel.. 
Did Sudo Wings and posted the log here
**
![image](https://user-images.githubusercontent.com/17889782/100040846-0dcf6100-2e2e-11eb-91bf-a5851fbd5ad2.png)
**

**Comment by parkervcp** [comment]
@dexter-dz This is unrelated to this error at all.

Please take this to our discord https://discord.com/invite/pterodactyl
