### ISSUE TITLE
EULA hook missing for Minecraft Related Eggs

### ISSUE THREAD

**Issue by tmunsch** [pterodactyl/panel#1941]
Panel or Daemon: 1.0.0-beta.1
Version of Panel/Daemon: 1.0.0-beta.1
Server's OS: Centos 7
Your Computer's OS & Browser: Windows 10 & Chrome

Description
When starting a Minecraft Based Egg the EULA prompt doesn't show/exist.

To Reproduce:

Create Minecraft based server
Start Server

Expected behavior
EULA Prompt shows automating the edit of server.properties

**Comment by LeCodeCo** [comment]
While 0.7 had this and 1.0 doesn't, I think it could be added back, but through the use of eggs so it can be configured to be used for any game type.

**Comment by Spirit55555** [comment]
The old code is still there, but it does not appear to be used: https://github.com/pterodactyl/panel/blob/develop/public/themes/pterodactyl/js/plugins/minecraft/eula.js

**Comment by matthewpi** [comment]
I'm pretty sure we are ditching this feature as it is too game specific.  The only way I see something like this being implemented is if it was handled at an egg level and wasn't something hard-coded into the UI for a specific set of eggs.

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/panel/commit/aba7df3afa3e29023fbde4aa0b42d791d0352935 & https://github.com/pterodactyl/panel/commit/fb03c411ad24e36b0ba2eb6c93bfe32447008f9a
