### ISSUE TITLE
Server usage statistics not displaying under Node>Servers for running servers

### ISSUE THREAD

**Issue by tmunsch** [pterodactyl/panel#1942]
Panel or Daemon: 1.0.0-beta.1
Version of Panel/Daemon: 1.0.0-beta.1
Server's OS: Centos 7
Your Computer's OS & Browser: Windows 10 & Chrome

Description
When viewing process manager under nodes/servers the daemon fails to relay server usage statistics to the listed view. Resulting in a display of a xhr poll error with no memory,disk or cpu usage displaying of the installed server.

To Reproduce

Go to Nodes>Select Node>Servers

Expected behavior
The Panel displays Server usage statistics about current running servers

**Comment by BrainStone** [comment]
According to the server console this is caused by the URL it tries to poll from generating as ``https://undefined/socket.io?....``.  
Then token also seems to be ``undefined``.

**Comment by DaneEveritt** [comment]
Yes that is expected since we aren't using socket.io in the new daemon.

**Comment by BrainStone** [comment]
I see. So it's just not updated yet on that page then?

**Comment by DaneEveritt** [comment]
Correct
