### ISSUE TITLE
Overwriting files when uploading

### ISSUE THREAD

**Issue by TRYTIG** [pterodactyl/panel#1943]
It is very frustrating when ever I go to upload a file (like a plugin) I have been working on I need to delete it and re-upload it instead of just being able to replace the file...

I think a solution for this problem would be a setting you can check in your user settings to replace file instead of creating one with a suffix containing a number.

Alternatives are deleting the file and re-uploading it.

**Comment by NoxInmortus** [comment]
A dedicated setting may be not neccessary, perhaps some pop-up window asking if you want to overwrite or create as `name.x.ext`

**Comment by parkervcp** [comment]
I agree with Nox on this on. Asking to overwrite may be the best option instead of just a overwrite toggle. Won't bother you on uploading new files but will verify you want to overwrite. sftp clients to is this way already.

**Comment by DaneEveritt** [comment]
Closing, this functionality now exists.
