### ISSUE TITLE
Panel tar contains apple meta file (starting with `._`)

### ISSUE THREAD

**Issue by BrainStone** [pterodactyl/panel#1944]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v1.0.0-beta.1
* Server's OS: Debian 10
* Your Computer's OS & Browser: *irrelevant*

**Describe the bug**
The current v1.0.0-beta.1 tar.gz file located at xxx contains apple metadata files that are named after the respective file with `._` prepended. While they are just a few bytes each it clutters the disk and directory listings unncessarily

**To Reproduce**
1. Run ``curl -L https://github.com/pterodactyl/panel/releases/download/v1.0.0-beta.1/panel.tar.gz | tar --strip-components=1 -tzv``

**Expected behavior**
That thoses files are not to be found in the tar files.

**Comment by parkervcp** [comment]
This is a beta and I don't see how this is relevant. It's not like you are running this in prod. They should be cleaned up in time for a full release.

**Comment by BrainStone** [comment]
Hence me pointing it out.  
Essentially in the release chain there should a step to verify that those files aren't in the release file.

**Comment by DaneEveritt** [comment]
Seems fine now
