### ISSUE TITLE
[Feature request] restart policy

### ISSUE THREAD

**Issue by NoxInmortus** [pterodactyl/panel#1948]
Hello,

I would like to ask the containers restart policy being changed or being changeable.

If a game server is stopped for any other reason than being stopped by its owner/admin, then it wont come back again.

The default restart policy (`--restart` with docker cli) is set to `no`. Having it set to `unless-stopped` would ensure the server will always go up.

**Comment by parkervcp** [comment]
Some of the hosts using the panel have thousands of servers. All of them starting with the system would probably cause it to go down on boot. I could see this as a per-node or -per server option though.

**Comment by NoxInmortus** [comment]
It probably wont go down, but rather make the system load a LOT for a few minutes (talking from experience), and it may result in containers being killed, but having the restart policy set will always ensure it to go up again.

But a node/server editable option would be 100% fine

**Comment by DaneEveritt** [comment]
We already have the daemon monitoring this in 1.0.0, without the restart policy flag so that down the road we can better support staged booting rather than all at once.

**Comment by NoxInmortus** [comment]
Nice to know that, pretty impatient to have an usable 1.0 in prod
