### ISSUE TITLE
Mobile view not properly formatted

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1949]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Beta 1.0
* Server's OS: Ubuntu 1804
* Your Computer's OS & Browser: Andorid 10 / Chrome 

**Describe the bug**
Portrait mode, mobile view doesn't properly adjust elements 
![Screenshot_20200419-142306_Chrome](https://user-images.githubusercontent.com/1757840/79696249-a0c96c80-8249-11ea-9c02-b5efd26b2df8.jpg)
![Screenshot_20200419-142258_Chrome](https://user-images.githubusercontent.com/1757840/79696257-b048b580-8249-11ea-9385-c1e29177a994.jpg)

**To Reproduce**
View on mobile. 
Current device is a Note 10+ @ 3040x1440

**Expected behavior**
Elements to dynamically format to mobile devices. 

Landscape looks fine 
![Screenshot_20200419-142213_Chrome](https://user-images.githubusercontent.com/1757840/79696315-fef64f80-8249-11ea-851f-d004721f358b.jpg)

**Comment by DaneEveritt** [comment]
Closing this just because it is something we clearly know about and isn't really a bug, just not implemented yet.
