### ISSUE TITLE
Bug: Creating containers doesn't finish

### ISSUE THREAD

**Issue by necrogami** [Pterodactyl/Panel#195]
So i'm working on some minecraft servers a bungeecord server and 2 vanilla servers and going through things it creates the container, but until i manually go in the backend and toggle the install button it never finishes but after that it's fine.

This has happened on every container i've tried to create with 0.5.3.

uname -a 
> Linux east-3 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

php -v 

> PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
>Copyright (c) 1997-2016 The PHP Group
>Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
>    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies`

docker info 

> Containers: 3
>  Running: 3
>  Paused: 0
>  Stopped: 0
> Images: 5
> Server Version: 1.12.3
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 54
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: host bridge overlay null
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Security Options: apparmor seccomp
> Kernel Version: 4.4.0-21-generic
> Operating System: Ubuntu 16.04.1 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 16
> Total Memory: 94.41 GiB
> Name: east-3
> ID: 7KY7:PTAI:EFLO:5FFT:COAL:JBC6:UBCX:EUDD:4ICL:P32W:CJC2:RWG2
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> WARNING: No swap limit support
> Insecure Registries:
>  127.0.0.0/8

**Comment by DaneEveritt** [comment]
Can you provide the logs from the daemon please, they should be in `/srv/daemon/logs`. This sounds like the config might be pointing to the wrong endpoint that it calls when installs are finished.

**Comment by necrogami** [comment]
I'm getting my logs but my daemon folder is /home/pterodactyl and /home/pterodactyl-data due to disk space availablity being in /home not /srv

**Comment by DaneEveritt** [comment]
Your issue is with the daemon contacting the panel. Ensure that the configuration file URLs are correct. If they're configured correctly, there is a networking issue causing an `ETIMEDOUT` error.

```
{"name":"wings","hostname":"east-3","pid":2014,"level":40,"err":{"message":"ETIMEDOUT","name":"Error","stack":"Error: ETIMEDOUT\n    at Timeout._onTimeout (/home/pterodactyl/node_modules/request/request.js:813:19)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)","code":"ETIMEDOUT"},"msg":"An error occured while attempting to alert the panel of server install status. { code: null, responseBody: undefined }","time":"2016-12-02T07:17:36.638Z","v":0}
```

**Comment by necrogami** [comment]
It's a local machine. Localhost daemon

**Comment by DaneEveritt** [comment]
Can you `curl <installed url>` on the machine properly?

**Comment by necrogami** [comment]
which am i curling daemon 8080 port or panel?

**Comment by DaneEveritt** [comment]
The panel. It looks like the daemon can't connect to the panel properly.

**Comment by necrogami** [comment]
from the local machine and from my macbook i can curl both urls manually toggling the server makes it work fine. and the daemon communicates just fine sending back minecraft console log to the browser.

**Comment by necrogami** [comment]
https://puu.sh/sChQh/c74f7fc9e6.png

**Comment by DaneEveritt** [comment]
Ok, in `core.json` check the `remote` block, and make sure the URLs look right. Issues generally occur if you disable/enable SSL after writing the config and the URLs don't update.

**Comment by necrogami** [comment]
yeah, i just found it .. the remote block had http instead of https
