### ISSUE TITLE
Allow regular expressions in the Server Jar File field

### ISSUE THREAD

**Issue by hornta** [pterodactyl/panel#1951]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to rename my PaperMC download from paper-XXX.jar to server.jar which gives me extra job and hides the server version.

**Describe the solution you'd like**
I would like to input a regular expression instead of a hardcoded string for example: `paper-[0-9]+\.jar` which matches paper-123.jar and paper-200.jar.

**Additional context**
Here are some blueprints for the devs.
![image](https://user-images.githubusercontent.com/4553604/79700719-23791880-8298-11ea-80eb-f5780f951d75.png)

**Comment by matthewpi** [comment]
Those environment variables are purposely passed into the container as their raw inputs.  This also is not a good solution as environment variables are used for more than setting a file path, especially the fact you are asking for regex to locate a file.

This just seems highly complicated for a feature that just saves you seconds instead of renaming a file.  I also see no use for this feature outside of your situation.

**Comment by parkervcp** [comment]
Don't forget that having multiple jars in place would make it match more than just one jar and most likely cause it to fail beautifully.

**Comment by DaneEveritt** [comment]
In retrospect, I'm not going to implement this so theres no reason to leave this open and pretend like it will happen.

I don't really see the benefit of this, and just see it causing more pain when people end up with multiple files matching. The entire goal of that field was to make it very easy for the panel to know what jar to execute, and it does that quite well currently.

**Comment by srnyx** [comment]
> I don't really see the benefit of this

I know this is closed, but I just wanted to give my thoughts.

It's highly beneficial when working with version-controlled jar files, especially ones that may update frequently. It becomes a hassle to constantly rename (or change the jar file variable) every time it updates.
I had to create a custom program that would run the jar file no matter what version it was, https://github.com/srnyx/jar-runner, and it's not great (it doesn't show the program being run's console/log).

And for multiple files that match, you can have another sub-option for the variable to choose what the panel does when that happens. The choices could be things such as "Terminate," "Use most recent," and/or "Use first occurrence." Or you can just have the panel check once the user is done editing the field, and if there are multiple occurrences, reset the field (although this wouldn't work when uploading matching files).

**Comment by Hermelijn15** [comment]
In case anyone still wants to do this, I think you can accomplish something similar by replacing {{SERVER_JARFILE}} with velocity*.jar in the startup command (works for velocity I assume also for paper)
