### ISSUE TITLE
[Feature Request] Schudule with backup function

### ISSUE THREAD

**Issue by NgLoader** [pterodactyl/panel#1952]
A function in schedulers -> task which allows automatic backups to be carried out.
And when a certain number of backups have been reached, the last backups created by the task are deleted.

### Example
![image](https://user-images.githubusercontent.com/13753840/79678112-26bcc780-81f8-11ea-9564-7770339d3b9d.png)

**Comment by DaneEveritt** [comment]
This is already planned
