### ISSUE TITLE
Config parser fails

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1956]
**Background (please complete the following information):**
* Panel or Daemon: Wings 1.0
* Version of Panel/Daemon: Wings 1.0 Beta
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win10 / Chrome

**Describe the bug**
config parser fails when servers are started

**To Reproduce**
Start a Minecraft server?

**Expected behavior**
Files to be properly parsed with the correct values. 

`
failed to parse and update server configuration file{"server": "3634433b-74a7-4509-b572-7b59aa1270c6", "error": "properties: Line 42: \"\"", "errorVerbose": "properties: Line 42: \"\"
github.com/pterodactyl/wings/parser.(*ConfigurationFile).Parse
        /Users/dane/Sites/development/code/wings/parser/parser.go:124
github.com/pterodactyl/wings/server.(*Server).UpdateConfigurationFiles.func1
        /Users/dane/Sites/development/code/wings/server/config_parser.go:27
runtime.goexit
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337"}
github.com/pterodactyl/wings/server.(*Server).UpdateConfigurationFiles.func1
        /Users/dane/Sites/development/code/wings/server/config_parser.go:28
`

Another user, pictured below, on discord had a similar issue. But in my case, the config file was not corrupted to say.
![](https://justmyrandomstuff.com/img/f9oZSlz.jpg)

**Comment by Mheetu** [comment]
Having basically the same issue using [parkervcp/eggs/gta/fivem](https://github.com/parkervcp/eggs/tree/master/gta/fivem) and the `file` parser...

The egg worked fine on the NodeJS daemon but appears to break on the GoLand daemon.

The FiveM egg has the following rules:
```json
{
    "server.cfg": {
        "parser": "file",
        "find": {
            "endpoint_add_tcp": "endpoint_add_tcp \"0.0.0.0:{{server.build.default.port}}\"",
            "endpoint_add_udp": "endpoint_add_udp \"0.0.0.0:{{server.build.default.port}}\"",
            "sv_hostname": "sv_hostname \"{{server.build.env.SERVER_HOSTNAME}}\"",
            "sv_maxclients": "sv_maxclients {{server.build.env.MAX_PLAYERS}}"
        }
    }
}
```
Given this [server.cfg template](https://github.com/parkervcp/eggs/blob/master/gta/fivem/server.cfg).
```
# only change these if you're using a server with multiple network interfaces
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

[...]
```

It mangles the first line like so:
```
# only change thsv_maxclients 32 32stname \"My new FXServer!\" "My new FXServer!""oint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

[...]
```
