### ISSUE TITLE
[Feature Request] Player numbers graph

### ISSUE THREAD

**Issue by NoxInmortus** [pterodactyl/panel#1957]
Hello,
 
I would like to suggest a feature request : player numbers new graph

At each server console, there is a CPU and Memory usage graph. To have a view on player numbers would be great.

As this would be too much complex to get player number stat from the app server itself, it is however possible to get ESTABLISHED connections to a listening port.

Something like that : `netstat -tn | grep -i ${GAME_PORT} | grep ESTABLISHED | wc -l` but daemon-side equivalent.

A very interresting alternative would be to have a telegraf listening endpoint to be able to graph differents metrics into an external grafana instance. The metrics system would need some thinking of course

**Comment by parkervcp** [comment]
I don't fell like that is an exact way to get player count.

I also feel as if this overlaps with #1218 a tool built to query servers.
