### ISSUE TITLE
Adding the ability to use hCaptcha for a direct replacement to reCaptcha

### ISSUE THREAD

**Issue by danielnaaman** [pterodactyl/panel#1958]
**Is your feature request related to a problem? Please describe.**
It's less of a problem, more of adding the ability to choose. Many hosting providers could definitely use the extra few bucks that hCaptcha offers it's users in return for captcha solvings.

**Describe the solution you'd like**
I'd like the ability to replace reCaptcha in the panel for hCaptcha, simply having two choices and anyone could choose what fits them better.

I tried following the feature request template but I think I'm pretty much repetetive, the idea should be very clear.

**Extra Words**
By the way, since I'm certain there are many installations that still use the default Site Key and Secret Key, this could actually be a small sort of extra revenue from this project, since all captcha solves on panels that weren't modified on that aspect would go directly to you guys.

**Yes, I'm aware it's similar to #1895**
I still think that hCaptcha alone (not generally 3rd party captchas) should be considered due to it raising in popularity and again, the extra income thing.

**Comment by DaneEveritt** [comment]
If someone wants to PR this feature they're welcome to, but I have no plans to put time towards supporting two systems out of the box. 👍

**Comment by DaneEveritt** [comment]
I'm actually closing this out because I'm never gonna get around to it.

**Comment by Permanently** [comment]
Surely it can't be that hard to add hCaptcha - there's a guide on migrating from [reCaptcha to hCaptcha](https://docs.hcaptcha.com/switch), which doesn't seem hard. That's only half of it though; the other half will be from toggling between reCaptcha and hCaptcha. Nevertheless it'd be nice to have, particularly as some people are sketchy with privacy, and Google.
