### ISSUE TITLE
Wings does not respect DNS settings configured

### ISSUE THREAD

**Issue by sponner** [pterodactyl/panel#1965]
* Panel :  1.0.0-beta.1
* Version of Panel/Daemon: 1.0.0-beta.1
* Server's OS: debian 10
* Your Computer's OS & Browser: not important

Hello,

i installed now new ptero and new wings but i get this error please help me
https://cdn.discordapp.com/attachments/658550982975946762/702913958733938718/unknown.png

**Comment by parkervcp** [comment]
Honestly this looks like the dns in the container is failing.

You can specify dns servers in the core.json
```
{
  "docker": {
    "dns": ["ip1", "ip2"],
  }
}
```

**Comment by sponner** [comment]
no i using

> Honestly this looks like the dns in the container is failing.
> 
> You can specify dns servers in the core.json
> 
> ```
> {
>   "docker": {
>     "dns": ["ip1", "ip2"],
>   }
> }
> ```

i using new ptero alpha and new wings i have config.yml

**Comment by parkervcp** [comment]
Then I have nothing for you at this time to fix that.

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/wings/commit/7321fe14217f8d2e22d512c190bf6b3427b3f75c
