### ISSUE TITLE
Problem with node

### ISSUE THREAD

**Issue by TheTakeus** [pterodactyl/panel#1966]
Hi, i have a problem
i bought a new vps for a second node
i have installed daemon ...
but when I try to link it, in the browser console I have
ERR_CERT_COMMON_NAME_INVALID
yet I did install certbot and configure the ssl certificate to the domain, the domain is link to vps ...
GET https://node1.takeus-gamehost.tk:8080/v1 net::ERR_CERT_COMMON_NAME_INVALID
and on the link:
(https://node1.takeus-gamehost.tk:8080/v1) We can see :     "error": "Missing required X-Access-Token header."

**Comment by parkervcp** [comment]
First you did not fill out any information, Second you aren't exactly giving the best description as to where you are seeing the error. Please resubmit with a proper Issue.
