### ISSUE TITLE
Mail error

### ISSUE THREAD

**Issue by LewaIngame** [pterodactyl/panel#1967]
Hello i got error with SMTP 

[2020-04-24 21:46:16] production.ERROR: ErrorException: Trying to access array offset on value of type null in /var/www/panel/vendor/egulias/email-validator/EmailValidator/Parser/Parser.php:147

**Comment by parkervcp** [comment]
You have filled in no information. I will be closing this out.

**Comment by LewaIngame** [comment]
The information is when i want to got mail of 
installed server
password reset

The mail system not work 
with this error

**Comment by parkervcp** [comment]
When you opened the issue you chose to ignore the issue template. That is why I closed this.

**Comment by LewaIngame** [comment]
I am french

**Comment by parkervcp** [comment]
That doesn't exempt you from filling out the issue template.
