### ISSUE TITLE
Use UUIDs for admin API as well instead of just on client API

### ISSUE THREAD

**Issue by LeCodeCo** [pterodactyl/panel#1969]
**Is your feature request related to a problem? Please describe.**
Currently, the Pterodactyl API uses a mix of incremental server IDs for admin (12) and short UUIDs. (a1b2c3) for client-facing.

**Describe the solution you'd like**
I'd like to see the admin API change from using incremental IDs to short UUIDs, so the API is consistent throughout the application and client. 

**Additional context**
This is a breaking change, but one which I think will help make the API more consistent and potentially easier to work with. I think that if this is considered, it should be done before v1.0 so that the new major update can facilitate the change.

**Comment by DaneEveritt** [comment]
Wont fix, I do not want to change the admin API at this time, and using UUIDs here would get confusing since a lot of other endpoints don't have UUIDs to reference.
