### ISSUE TITLE
Pocketmine server on pc for mcpe on tablets step 1.....

### ISSUE THREAD

**Issue by kiddgordon** [Pterodactyl/Panel#197]
Please describe your issue in full below. Include what products are affected, as well as what version(s) you are running. Please also include information about your system, such as `uname -a` and `php -v` and `docker info` if applicable.

If you're just making a suggestion, be descriptive, and link to any issues that might be releated as well.

You can delete from this line up.
---------------------

**Comment by kiddgordon** [comment]
I need help setting Pocketmine up on my pc to run a server for my kids to play on the tablets. Stupid youtube has bugging me to set it up for her aka 10 yo monster lol!  Please help if anyone can!

**Comment by DaneEveritt** [comment]
Pterodactyl Panel does not currently support Pocketmine, nor will it run on windows based operating systems.

**Comment by kiddgordon** [comment]
Pterodactyl Panel ? Have no idea what that is! Or how I even got under this section.
