### ISSUE TITLE
Not all text files are editable in the File Management 

### ISSUE THREAD

**Issue by NoxInmortus** [pterodactyl/panel#1970]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.16
* Server's OS: Debian 10 64bits
* Your Computer's OS & Browser: Firefox 75 64bits

**Describe the bug**
All text files (.txt/.cfg at least) are not editable through the file management panel.

**To Reproduce**
1. Create a new arma3 server
2. Go to File Management
3. Try to edit server.cfg (other text files are fine)
4. See that you cannot open it in text editor

**Expected behavior**
All text files should be editable

**Bonus**
And if I may add that it would be great if .yml files could be also editable.

**Comment by parkervcp** [comment]
There are known issues with the file editor.

It uses magic bytes to determine file type, which is the cause of the issue you are taking about.

In 1.0 this is fixed.
