### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by loucaslt** [pterodactyl/panel#1973]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.17 
* Server's OS: debian 10
* Your Computer's OS & Browser:  Firefox

**Describe the bug**
I was looking for sessions connected to my pterodactyl, and i saw many sessions with reserved IP of IANA and some users say me "have been hacked". I don't really understand how it's possible to have an reserved IP of IANA and how this users have found the big password of my user. After searching, 39 others accounts are with iana reserved ip address

Every account have this agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36

**To Reproduce**
idk how to repreduce

**Expected behavior**

**Comment by pbeart** [comment]
If you believe this to be a security flaw in Pterodactyl, it should be reported privately to developers, not publicly on the repository. To me however it sounds from your description like the users passwords were guessed, which is not a problem related to Pterodactyl

**Comment by loucaslt** [comment]
Possible but how.... Password was 12 long. And why IANA IP reserved ? Too
many questions in my head

Le dim. 26 avr. 2020 à 01:12, Patrick Beart <notifications@github.com> a
écrit :

**Comment by DaneEveritt** [comment]
This doesn't seem to be at all related to Pterodactyl. You're unable to reproduce, you're unable to provide expected behavior, and your issue report does not make any sense.

Feel free to re-open this issue if you're able to sufficiently prove this is indeed an issue with Pterodactyl and not a configuration issue with your systems (or normal behavior).
