### ISSUE TITLE
Docker hostname not allowed as Node FQDN

### ISSUE THREAD

**Issue by dennorske** [pterodactyl/panel#1975]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.17
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Ubuntu 20.04, Chrome

**Describe the bug**
Entering a docker hostname as FQDN / IP while creating a node, returns an error that it is not recognised as a FQDN or IP. 

**To Reproduce**
1. Go to nodes, and create a new node
2. put the daemon FQDN to "daemon" for instance, see pic: ![image.png](https://pics.ducky.rocks/images/2020/04/26/image.png)
3. See error: ![imaged66395691adcaad4.png](https://pics.ducky.rocks/images/2020/04/26/imaged66395691adcaad4.png)

**Expected behavior**
As pterodactyl can be sat up to use its components in Docker containers, hostnames for these containers are expected to work, even though this is not what pterodactyl is intentionally made for. Problem with using IP's with docker, is that these IP's are never consistent and may change every time the docker network is being recreated or host system reboots.

**Possible fix done somewhere else**
Do the same as done here: 
https://github.com/pterodactyl/panel/issues/1728
Commit: https://github.com/pterodactyl/panel/commit/41cbdb8d5902ea0bb6cfbf5f26c173bc4106eb19

**Comment by synocx** [comment]
Pterodactyl use websocket, it's need to be valid FQDN in order to connect the daemon.

**Comment by dennorske** [comment]
I understand, so this is actually so that clients can use the daemon as well, and not only internal use?

**Comment by parkervcp** [comment]
Yes. Docker IPs are private and cannot be reached by others.

**Comment by dennorske** [comment]
Thank you for the clarification, I wasn't quite informed / didn't quite understand the requirement here. Closing it :)
