### ISSUE TITLE
Specifying a local IP as a node's FDQN returns a 500

### ISSUE THREAD

**Issue by MarkKoz** [pterodactyl/panel#1979]
**Background (please complete the following information):**
* Panel or Daemon: panel
* Version of Panel/Daemon: 0.7.17
* Server's OS: Raspbian GNU/Linux 10 (buster)
* Your Computer's OS & Browser: Arch Linux; Firefox 75.0

The panel is also running within a Docker container.

**Describe the bug**
If I specify the IP of another device on my local network as the FQDN for a node, the settings will fail to save and display a page saying "500". I'm hosting the panel and the daemon on `192.168.0.12`. I'm accessing the panel on another machine, `192.168.0.6`. If I specify `192.168.0.6` or `localhost`, it will save (of course this FQDN would be incorrect though). If I specify `192.168.0.12`, I get 500. `192.168.0.13`, also 500. And so on. For what it's worth, I can access the daemon with `curl`, though this issue happens regardless of whether the daemon is even running.

There are no errors for this in any logs. The only entry in any logs I see related to this is:

```
src:"192.168.0.6" time:"26/Apr/2020:14:45:18 +0000" req:"POST /admin/nodes/view/2/settings HTTP/1.1" status:"500" agent:"Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0" for:"-"
```

The problem is twofold:

1. I cannot use 192.168.0.12 as the FQDN here
2. The logging for this issue is inadequate (i.e. non-existent) so I am unable to troubleshoot it myself

**To Reproduce**
1. Go to the settings page for any node
2. Select 'Use HTTP Connection'
3. Set the FQDN to the IP of another device on your local network
4. Observe being redirected to a 500 page and the settings not being saved

**Expected behavior**
I expect the settings to successfully save just as they would if I specified any other valid FQDN. Furthermore, I would expect the panel to subsequently attempt to connect to the daemon via the newly specified FQDN.

**Comment by Sir3lit** [comment]
We would need the panel logs in-order to see why it's failing. They're located in `/storage/logs`

**Comment by MarkKoz** [comment]
Sure:

[laravel-x.log](https://bin.ptdl.co/3plz3/)
[access.log](https://bin.ptdl.co/5zczs/)

Note the timestamps are in UTC, so the errors in the laravel log are quite old. Pretty sure they happened well before I even started messing with the node's FQDN.

**Comment by MarkKoz** [comment]
Right with my poor PHP debugging skills I managed to get an error out if it. Looks like `DaemonConnectionException` doesn't get logged so I raised a different exception to make it show up on the website.

https://github.com/pterodactyl/panel/blob/release/v0.7.17/app/Services/Nodes/NodeUpdateService.php#L89
```php
        } catch (RequestException $exception) {                                              
            // Failed to connect to the Daemon. Let's go ahead and save the configuration    
            // and let the user know they'll need to manually update.                        
            if ($exception instanceof ConnectException) {                                          
                $this->connection->commit();                                                                    
                                                                                                   
                throw new ConfigurationNotPersistedException(trans('exceptions.node.daemon_off_config_updated'));
            }                                                                                                    
                                                                                             
            throw new ConfigurationNotPersistedException($exception->getMessage()); // my line      
            throw new DaemonConnectionException($exception);                                 
        }  
```

> Error creating resource: [message] fopen(http://192.168.0.12:9008/v1/config): failed to open stream: Operation timed out [file] /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php [line] 323 

I think it should do the same thing as the `ConnectException`, committing the changes and notifying the user it couldn't connect to daemon.

**Comment by DaneEveritt** [comment]
I get the normal error for not being able to update the config when editing a node to an IP of another machine on my network:

> The daemon configuration has been updated, however there was an error encountered while attempting to automatically update the configuration file on the Daemon. You will need to manually update the configuration file (config.yml) for the daemon to apply these changes. 

I'm guessing something changed at some point and resolved this for now.
