### ISSUE TITLE
Minecraft - Bungeecord fails due to apline

### ISSUE THREAD

**Issue by necrogami** [Pterodactyl/Panel#198]
So alpine linux with bungeecord has a known problem.

Every time i connect to the bungeecord server it instantly crashes with error 
```Inconsistency detected by ld.so: dl-lookup.c: 128: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!```

I reported this to Bungeecord but this is a docker/alpine issue netty/netty-tcnative#111

SpigotMC/BungeeCord#2015

He says in there that a bulk of the spigot/bungee plugins won't work in alpine and the docker container should be switched to debian.

**Comment by MeltedLux** [comment]
Known issue, there are builds available [here ](http://ci.pterodactyl.io/job/BungeeCord-Apline/) that are compiled on alpine.

**Comment by necrogami** [comment]
@MeltedLux so according to the bungee devs not having native support will break most of the plugins for bungeecord. This is NOT supported in any way on alpine linux and suggest to switch to a different container os such as debian.

**Comment by DaneEveritt** [comment]
@necrogami — The current plan is to switch Bungee over to an Ubuntu/Debian based image in the coming days, the Alpine compiled builds are a temporary work around until we have an official image out to support it fully.

From what I can tell so far it looks like it has been working for most users, although obviously thats not indicative of 100% support, and not necessarily all plugins. But the plan is to switch containers, which will simply require a rebuild of containers, although we will need to ensure this doesn't break Alpine compiled builds first.

**Comment by parkervcp** [comment]
You can use my container - quay.io/parkervcp/bungeecord

It will auto pull BungeeCord or waterfall depending on how you set it up.

**Comment by DaneEveritt** [comment]
This has been fixed by merging @parkervcp's container into the main distribution repo.
