### ISSUE TITLE
Allow multiple nodes to be linked to one database for non-random assign.

### ISSUE THREAD

**Issue by upstreamsea** [pterodactyl/panel#1980]
**Is your feature request related to a problem? Please describe.**
Currently, you can only link one node to one database. For those of us who have multiple nodes in the same region, using the same database would be preferred. Instead, current operation gives randomness into what database is assigned.

**Describe the solution you'd like**
As the current solution is built right now, it only allows for one node to be linked. Allow multiple nodes to be linked to one database for non-random assign. This could also be added into "node creation", asking what database you'd wish to assign it to.

Another solution would be allowing a database to be linked by locations. This would, in theory, be easier as linking multiple locations to one database solves the above hassle of assigning each node.

**Describe alternatives you've considered**
There are no real other alternatives at the moment we can find.

**Comment by matthewpi** [comment]
From my understanding, couldn't you just create another `Database Host` using the exact same details and link it to another node?  I know it is an annoying workaround but it should work.

**Comment by upstreamsea** [comment]
@matthewpi No, the only workaround we've found is actually modifying SQL to "create" databases. Ptero sees that there is a current DB, and errors out saying "DB already exists".

**Comment by matthewpi** [comment]
In react-admin, the relationship for database hosts and nodes was reversed.  In 0.7 and 1.0 the relation was a node linked to a database host (node_id column on the database host), but with react-admin the relation is now a database host linked to a node (database_host_id column on the node).  With this change, multiple nodes can use the same database host.
