### ISSUE TITLE
EULA Minecraft Beta 1.0

### ISSUE THREAD

**Issue by TheCraftTheft** [pterodactyl/panel#1985]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheCraftTheft** [comment]
I have fail my message, in stable version eula can be accepted automaticaly but in 1.0 its don't work :(

**Comment by parkervcp** [comment]
@TheCraftTheft Cn you please fill out any of the information we asked for.

**Comment by DaneEveritt** [comment]
Feel free to re-open this when you edit the original issue to include details.
