### ISSUE TITLE
Having a deleted server displayed in a tab crashes wings

### ISSUE THREAD

**Issue by 9903286** [pterodactyl/panel#1988]
**Background (please complete the following information):**
* Panel or Daemon: daemon (wings)
* Version of Panel/Daemon: wings v1.0.0 beta 2
* Server's OS: ubuntu 18.04
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
Wings crashes repeatedly upon launch with the error:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0xcb0f18]

goroutine 11503 [running]:
github.com/pterodactyl/wings/server.(Server).Events(...)
        /Users/dane/Sites/development/code/wings/server/events.go:32
github.com/pterodactyl/wings/router/websocket.(Handler).ListenForServerEvents(0xc0008ba810, 0x10763a0, 0xc000cbe240)
        /Users/dane/Sites/development/code/wings/router/websocket/listeners.go:52 +0xb8
created by github.com/pterodactyl/wings/router.getServerWebsocket
        /Users/dane/Sites/development/code/wings/router/router_server_ws.go:27 +0x1cc`

**To Reproduce**
1. Have functioning server running
2. Open the server in a new tab
3. Delete the server from another tab
4. (Not sure if needed) Restart wings?
5. Everytime the panel tries to request info from the previous tab wings crashes with above message.

**Expected behavior**
I guess i want the tab with the server open to simply redirect to the users servers or display an error message.

**Comment by 9903286** [comment]
Found out that it was cause it was open in another tab by adding
`if s == nil {
	return
}`
to "router_server_ws.go" at the start of "getServerWebsocket", then when i launched wings it kept telling my that something was trying to request information about that server over and over.

**Comment by DaneEveritt** [comment]
Closed in fab489d2649c8230be5c4b259a6ffd96944037a1
