### ISSUE TITLE
Panel triggers AVC denials on an enforcing SELinux system.

### ISSUE THREAD

**Issue by ccallahan** [pterodactyl/panel#1989]
Hello there!

I am using panel 0.7.17 on CentOS 8.1 patched as of 5/2/2020. It appears that when the panel goes to generate a captcha using php-fpm, this triggers an AVC denial and SELinux blocks the action from happening.

`type=AVC msg=audit(1588446038.108:1701): avc:  denied  { name_connect } for  pid=10200 comm="php-fpm" dest=443 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:http_port_t:s0 tclass=tcp_socket permissive=1`

This seems like a bit of a security issue to me. I may be mistaken, but I believe recaptcha generation shouldn't have to be handled by PHP itself, that should be able to happen client side. Allowing PHP to make calls to an outside server like that just doesn't seem wise, and having to generate SELinux policy to allow something like this isn't very kosher either in my eyes. The whole point of having an enforcing SELinux system is to make sure programs don't do stuff like this.

CC: @wertyy102

**Comment by DaneEveritt** [comment]
I can't think of anything that would specifically be generating a captcha, other than the code that handles the transparent recaptcha firing off within the dependency code.

**Comment by ccallahan** [comment]
It's possible, and it is also understandable you haven't seen this before, the first thing many people do when setting up a Enterprise Linux server is set the whole machine to SELinux disabled. Any idea what the offending API could be?

**Comment by DaneEveritt** [comment]
I would probably recommend starting with `PragmaRX\Google2FA\Google2FA` which is used within https://github.com/pterodactyl/panel/blob/0.7-develop/app/Http/Controllers/Auth/LoginController.php.

**Comment by DaneEveritt** [comment]
I want to say it is probably something going on in the Recaptcha middleware?

https://github.com/pterodactyl/panel/blob/0.7-develop/app/Http/Middleware/VerifyReCaptcha.php

**Comment by parkervcp** [comment]
I cover the selinux commands to run in community docs - https://pterodactyl.io/community/installation-guides/panel/centos8.html#selinux-commands

**Comment by ccallahan** [comment]
Ah, I went about it a different way and got it to work fine, I just wanted to see if anything could be done so that php-fpm didn't get hit with an AVC denial for accessing an external system the way it was.

**Comment by ccallahan** [comment]
I was just curious if there may be any intention to look into and solve this issue at all, if not I'll go ahead and close this.

**Comment by DaneEveritt** [comment]
Its working as expected honestly. Unless you can find a way to make it work fine with reCAPTCHA then I'd say nothing will be changing.

**Comment by DaneEveritt** [comment]
@ccallahan I'm going to go ahead and close this unless you think otherwise? Feel free to re-open if you are planning on PR'ing a change, otherwise I think this is working as expected.
