### ISSUE TITLE
Feature Request: Node Ownership & Associated Permissions

### ISSUE THREAD

**Issue by Derragon** [Pterodactyl/Panel#199]
# Synopsis

Allow admins to assign a user a node for them to manage themselves. They would have access to the following features:

1. Unrestricted Port Allocation (Or ability to allocate ports but not IPs)
2. Create/Delete servers on the node
3. Add database servers (limited to their nodes/servers)

# Reasoning

For businesses/resellers being able to assign a whole node to a user is a must-have feature. As the panel targets both individuals and companies this feature would be greatly beneficial. It would also be useful for larger communities who want to give their members access to some administrative features (but not all!)

**Comment by schrej** [comment]
Maybe we should implement a more powerful permissions system for the admin side instead of only having `root_admin` to allow stuff like this?

**Comment by DaneEveritt** [comment]
That was my plan @schrej, although this is a slightly different request.

**Comment by DaneEveritt** [comment]
I'm going to close this as it would take a lot of re-working to implement, and frankly I don't think it is within the current scope and abilities of the project with the current backlog and small development team.
