### ISSUE TITLE
The skip scripts field must be true or false 

### ISSUE THREAD

**Issue by bagou4502** [pterodactyl/panel#1991]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: BETA 1.0 
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: New edge

When i skip instalation script of a server i have The skip scripts field must be true or false #1987

**To Reproduce**
1. Go to Create a server
2. Click on Skip install script
3. Start the server creation

**Comment by Sir3lit** [comment]
Should be noted in the request it sends `skip_scripts: on`
