### ISSUE TITLE
Daemon not updating instance status

### ISSUE THREAD

**Issue by sneak-it** [pterodactyl/panel#1993]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: Panel: 0.7.17, Daemon: 0.6.13
* Server's OS: Debian 10
* Your Computer's OS & Browser: Win 10/Chrome 81.0.4044.129

**Describe the bug**
Installed a CS:GO instance to a remote server via the panel. When using the Restart button on the panel, the gameserver properly restarts, however the Daemon sees the server as 'Stopping'. The Daemon never properly marks the server as Off, Starting, or Started. Checked with Discord an no one really had any ideas.
Please provide additional information too, depending on what you have issues with:
Panel: PHP 7.3.17-1, Apache 2.4.43
Daemon: `Linux snkusla1 4.19.0-8-rt-amd64 #1 SMP PREEMPT RT Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`
Docker Info: https://hastebin.com/abukajegov
Diagnostics: https://hastebin.com/koduyixevi

**To Reproduce**
1. Install Panel, Daemon
2. Add Location/Node
3. Add CS:GO server, install, run
4. Click Restart
5. Observe daemon only sending Stopping notification, nothing after unless process is killed and Start button is pressed.

**Expected behavior**
Restart button should properly stop and send starting/started notification to panel.

**Extra Note**
I am able to manually attach to the docker container without an issue after it is marked 'Stopping'. I have also tried restarting the wings service, which shows that the server is now online again and I can access console/all analytics.

I see that in the CS:GO egg, the "startup" config param contains `Connection to Steam servers successful`. This does indeed get displayed in the server console when restarting the CS:GO instance, however does not seem to affect anything.

When I go to kill the server via panel, here is the output:
```
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 25444M / 30000M
[Pterodactyl Daemon] Ensuring correct ownership of files.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server marked as ON
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Server marked as KILLED.```

**Comment by DaneEveritt** [comment]
Unless this is also happening in the current beta I'm not going to be fixing this, sorry.
