### ISSUE TITLE
Manually triggering a server reinstall that fails will brick the server instance

### ISSUE THREAD

**Issue by DaneEveritt** [pterodactyl/panel#1994]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: `develop`

**Describe the bug**
If a user or an administrator triggers a server reinstallation for a server that has already installed successfully but the install fails, the server will enter a state which requires manual DB modification to get working again. This occurs because the system does not know that this is a manual reinstall, and just marks the server install state as being "2" incorrectly.

**Expected behavior**
The server should just "fail" the install and go back into a state where the user can interact with ti and try again.

Honestly, all failed installs should work this way, there is no reason not to do this now that the daemon just fetches the server from the API whenever the data is needed. Theres minimal risk of bad data or data corruption happening.

**Comment by lancepioch** [comment]
Currently we only have Server::STATUS_INSTALL_FAILED. This is correct during the initial server failures. However, what we need to do is track Server::STATUS_REINSTALL_FAILED as a separate status that doesn't have these restrictions.

The easiest way to do this will be to update InstallationDataRequest to accept a new parameter isReinstall and then using that to determine the specific failure in the ServerInstallController store controller method.

These statuses are only updated via: POST /api/remote/servers/{uuid}/install
