### ISSUE TITLE
Memory error with latest Minecraft Forge 1.15.2 due to new launcher ("modlauncher")

### ISSUE THREAD

**Issue by canitzp** [pterodactyl/panel#1995]
* Panel or Daemon: Daemon (Minecraft Forge Egg)
* Version of Panel/Daemon: Panel: 0.7.17; Daemon: 0.6.13
* Server's OS: Ubuntu 18.4 Server; also happens on Debian 10
* Your Computer's OS & Browser: Everywhere

When creating a new server for Minecraft Forge (I normally just create a vanilla egg and upload all the required files myself) and sarting it, the new modlauncher is used for startup and class transforming. This leads to a new problem: The docker memory isn't enough for the game anymor. This comes from the fact that the new modlauncher start the real game in a seperate process and so a seperate virtual machine. Now the problem is that modlauncher starts the game with the -Xmx parameter that was given to itself and so the memory the modlauncher is able to use and the ram the game can use is more than the available memory supplied by the server creator. When this happens after a while playing the server just freezes and has to be killed.

1. Create a new vanilla egg server
2. Upload all server files and rename the forge file to server.jar
3. Start the container and try to use enough memory to exceed the container limit (I tried to pregenerate over 2 million chunks)
4. When the used ram is over the designated docker ram the game just freezes completly

I have no good solution for this, but I has a similar problem for one of my java projects. It a minecraft server wrapper, which does all kind of neat stuff, like backup or automated updates. After installing it i didn't realised the error that can happend and I ran into the freeze issue. I fixed it by changing the startup parameter of the wrapper to -Xmx128M only and made a build-in config into the wrapper to set the required minecraft manualy. The container memory value hasn't changed. This leads to the wrapper using 128MB of memory, the minecraft process created through the wrapper using 16000MB memory and so it doesn't exceed the maximum available docker meory of 16384MB.
I know that this solution is not appliable to pterodactyl, cause it would require changes in the modlauncher.
Here is the repo for the modlauncher project: https://github.com/cpw/modlauncher
It is maynle used now, cause the old "launchwrapper" was just old and didn't work with java versions above 8.

If any more information is needed, let me know and I try to supply it.

**Comment by parkervcp** [comment]
Why would the server need this to run? We are calling the server jar directly in any of the forge eggs.

**Comment by canitzp** [comment]
The modlauncher is required by forge, because it provides the way to interact with the game. It mainly scans for mods. All the mods it can find are added together with forge and minecraft to start the actual game. This is mendetory since java 9, because realtime jar loading is not usable anymore. Also modlauncher provides the only way to do class transformation wich is used by some mods, because forge can't do anything.
It is impossible to start a forge server without it

**Comment by DaneEveritt** [comment]
This seems like an issue with the game software itself, or resolvable by getting creative with the memory limits being assigned. I have no interest in digging into the mechanics of one small subset of games run on the platform just to support a weird server launching strategy.

If someone comes up with a graceful solution to this and wants to PR it, you're welcome to, otherwise I'm not even going to pretend like I'm going to dig into this.

**Comment by canitzp** [comment]
Only for clarification:
This issue is now in every Minecraft Server with Minecraft forge as modloader installed.
The error that happens is a complete game freeze with no other option than killing the process (through the panel), whenever the ram is at the border of being full (I tested it with 8 to 12 GB servers and all started to freeze when they reach their limit minus some Megabyte).
I for myself and all the servers I host, change the RAM startup value to be a bit lower than the docker container max. Normally around 128MB less. This works fine for me, but what is if someone experiences this issue without the knowledge I have about the Minecraft Forge startup lifecycle.
Here is a step-by-step introduction how Minecraft Forge launching works:
1. Pterodactyl does launch a "server.jar" file, which has to be the forge server jar. This has never changed
2. The "server.jar" is a java launchwrapper (Needed for class transforming). This is also the same step, but since 1.15.2 the launchwrapper was switched to a new one, in order to launch with java versions above 1.8
3. The new launchwrapper now tries to get all installed mods and pre-processes them (looking at compatibility issues).
4. The launchwrapper launches a new process for the actual game with forge installed. This is very different, since the old launchwrapper never created a new process for this. And exactly here is the problem. The new progress is launched with the same max memory as the new launchwrapper, so when the actual game needs all the memory, the docker freezes, since there isn't enough (The last bits are occupied by the launchwrapper).

There are two easy fixes:
1. On the pterodactyl side it could be possible to assign a bit more memory to the docker container than to the actual game
or
2. On the modloader/launchwrapper side, the new game process has to be loaded with less memory than itself was launched.

Maybe this overview helps someone in the future.

**Comment by DaneEveritt** [comment]
Pterodactyl already assigns additional overhead, the best solution here for now is manually tweaking the startup args, and down the road we could probably make it so you can do basic math in the args, e.g. `{{SERVER_MEMORY-512}}` or something.
