### ISSUE TITLE
Create Server Bug

### ISSUE THREAD

**Issue by Talhazzers** [pterodactyl/panel#1996]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0 Beta 3
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chrome

**Describe the bug**
https://cdn.ekiphost.com/i/oExIvBhNA8.png
When i delete 0 and press create server, giving SQL error 
ERROR: https://cdn.ekiphost.com/i/yMpLut9xbi.png
Panel: PHP 7.4.5 (cli) (built: Apr 19 2020 07:36:30) ( NTS )
Daemon: Linux localhost 4.15.0-99-generic #100-Ubuntu 

**To Reproduce**
1. Go to 'Create server'
2. Leave backup limit blank
3. Hit create server

**Comment by DaneEveritt** [comment]
Looks like a validation bug, it shouldn't be allowing an empty value, it needs to be 0 or higher.

**Comment by DaneEveritt** [comment]
Closed in 41845ffdad92d9ae81c03a2cf29dafecc258c8d7
