### ISSUE TITLE
[1.0.0 Beta-3] Pterodactyl not properly installing servers

### ISSUE THREAD

**Issue by GhastD** [pterodactyl/panel#1998]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v1.0.0-Beta-3
* Server's OS: Ubuntu 18.04-LTS
* Your Computer's OS & Browser:  Mozilla Firefox, Windows 10 Home Latest

**Describe the bug**
Pterodactyl refuses to install any server with any script. The following error continuously happens:
`ash: can't open './mnt/install/install.sh': No such file or directory`

**To Reproduce**
Steps to reproduce the behaviour:
1. Import any eggs provided by Parker into Pterodactyl (experimental)
2. Install any server, with the egg provided of course
3. Admire your empty SFTP whilst wondering why it's producing that behavior
4. Have fun with fixing the bug. It'll be a lot of digging.

**Expected behavior**
Well the server is supposed to install theoretically. No files appear in the FTP, nothing is being properly installed.

**Comment by DaneEveritt** [comment]
Given the information provided, this doesn't sound like an issue with Pterodactyl specifically, rather an egg you're using.

Please provide enough information to show that this happens with the eggs we ship by default, or that it _is not_ caused by unofficial eggs and I can re-open it.
