### ISSUE TITLE
[1.0.0 Beta-3] Pterodactyl not starting server with Alpine Base docker image (Golang)

### ISSUE THREAD

**Issue by GhastD** [pterodactyl/panel#1999]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Daemon/Panel
* Version of Panel/Daemon: v1.0.0-Beta-3
* Server's OS: Ubuntu 18.04-LTS
* Your Computer's OS & Browser: Mozilla Firefox on Windows 10 Home

**Describe the bug**
PHP Version: PHP 14
![Image](https://i.imgur.com/xBcfpxp.gif)

Docker used: quay.io/parkervcp/pterodactyl-images:base_alpine
Script container used: golang:1.12-alpine
Startup command: "./main" (theoretically should work right?)

**To Reproduce**
Install the following script:
`{
    "_comment": "DO NOT EDIT: FILE GENERATED AUTOMATICALLY BY PTERODACTYL PANEL - PTERODACTYL.IO",
    "meta": {
        "version": "PTDL_v1"
    },
    "exported_at": "2020-05-05T07:33:32-04:00",
    "name": "Lilypad - Connect",
    "author": "[retracted]@gmail.com",
    "description": "Simple lilypad connect egg",
    "image": "quay.io\/parkervcp\/pterodactyl-images:base_alpine",
    "startup": ".\/main",
    "config": {
        "files": "{\r\n    \"config.yml\": {\r\n        \"parser\": \"yaml\",\r\n        \"find\": {\r\n            \"bind\": \"{{server.build.default.port}}\"\r\n        }\r\n    }\r\n}",
        "startup": "{\r\n    \"done\":\"Connect server started, version\",\r\n    \"userInteraction\": []\r\n}",
        "logs": "{}",
        "stop": "stop"
    },
    "scripts": {
        "installation": {
            "script": "export GOPATH=$HOME\/go\r\nexport PATH=$GOROOT\/bin:$GOPATH\/bin:$PATH\r\n\r\ncd\r\n\r\napk add --no-cache --update git\r\necho \"Pulling Lilypad: Connect from the Repository\"\r\necho \"Credits to Coelho for making Lilypad\"\r\n\r\ngit clone https:\/\/github.com\/LilyPad\/GoLilyPad.git\r\n\r\ncd GoLilyPad\/server\/connect\/main\/\r\n\r\necho \"Building Connect\"\r\ngo build\r\necho \"Main built\"\r\n\r\ncp main \/mnt\/server\/\r\n\r\necho \"Install complete. If you watched this. Congrats.\"",
            "container": "golang:1.12-alpine",
            "entrypoint": "ash"
        }
    },
    "variables": []
}`

(Manually have to install GoLilypad's main since the installation is broken, as seen here: https://github.com/pterodactyl/panel/issues/1998)

Try to launch the server. Nothing happens.

**Expected behavior**
Server is supposed to start. This issue does NOT appear on 
`quay.io/pterodactyl/core:java`

**Comment by GhastD** [comment]
Following popped up once then never seen again:
`/entrypoint.sh: eval: line 1: ./main: Permission denied`

**Comment by schrej** [comment]
You'll have to set the permissions for `./main` correctly then. It probably misses the execute bit.
