### ISSUE TITLE
Feature Request: Factorio Dedicated Server

### ISSUE THREAD

**Issue by necrogami** [Pterodactyl/Panel#200]
I'm wondering if a default service can be built for factorio servers:

an example container.

https://github.com/carloe/docker-factorio

There is no documentation on how to create services available via pterodactyl.io

**Comment by DaneEveritt** [comment]
@parkervcp just made a container for Factorio servers I believe, although official panel support has not been added.

In regards to documentation on how to create services, I am currently re-doing the entire service management system to make the nodes more independent, and make it possible to keep things updated across all nodes with one panel change. That major change is under works for `Panel@0.6.0`, and once that is out I will be adding documentation for how to edit and create new services.

**Comment by parkervcp** [comment]
@necrogami I do have a factorio server in docker. I need to look into a docker file to pass off to Dane.

I am also working on the logic to pull the latest stable or whatever version you want.

**Comment by DaneEveritt** [comment]
closed in favor of #239
