### ISSUE TITLE
Send commands to the container on schedule

### ISSUE THREAD

**Issue by realkarmakun** [pterodactyl/panel#2005]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated about how I need to synchronize my cron jobs with schedules in panel. For example I need to run a bash script in container, while some server is stopped. Since panel runs it's schedule worker once in a minute, I need not only to make a separate cronjob in order to run a script, but I also need to make a delay in like 1-2 minutes in order to make sure my script will fire only when server is in needed state.

**Describe the solution you'd like**
Add an option to fire scripts bash/python/... scripts using schedules.
Adding option "Send container command" in Perform Action drop menu and allow bash commands in "With Payload". So when user need to run a script, he'll do `./myscript.sh` or `python3 myscript.py` in Payload (pretty much a primitive bash syntax  just to run scripts)

**Describe alternatives you've considered**
The only workaround is to keep track on schedules and scripts in cron manually. Which can get really tiring when there is a lot of servers. 

**Additional context**
Think this kind of feature have some synergy with Data Packs feature, since administrators will be able to ship some scripts on server installation. 
There is also no need to check if script was ran successfully, since panel doesn't check if Power Action or Send Command was successful anyway. 
Also the work-ability of a script should be on users behalf. All needed dependencies for script to work properly should be resolved by user.

**Comment by matthewpi** [comment]
I'm not quite sure what exactly you are trying to achieve with this.

If you need to run a bash script every "x" amount of time with the server stopped you could make the bash script stop the server using the Pterodactyl API and then start it once your script is finished.  Also you cannot run scripts inside of a container while it is stopped so I'm assuming you are talking about running them on the host system which would be a security risk (you could technically execute anything on the host system).

**Comment by DaneEveritt** [comment]
Yeah, this is an interesting idea but better handled by an external process interfacing with the Panel, and not by the panel itself. I personally don't see this as being extremely beneficial in the long run, or worth the build & maintenance effort right now.
