### ISSUE TITLE
Add flag -y to bypass cli confirmations for automation

### ISSUE THREAD

**Issue by lancepioch** [pterodactyl/panel#2006]
https://github.com/pterodactyl/panel/blob/2d95204e9a46b62d4ed761d7b700a8a5f641b47f/app/Console/Commands/Server/BulkPowerActionCommand.php#L93

Confirmations should be allowed to be bypassed with a flag. That way you can run them with cronjobs for example.

**Comment by DaneEveritt** [comment]
@lancepioch please add more details to this...

**Comment by Gaeta** [comment]
I think he means if the user is running cli commands like the bulk startup adding -y does yes on all?

**Comment by trenutoo** [comment]
This already works with cronjobs as it checks if the input was interactive or not. I confirmed this myself by adding the following cronjob.

```*/2 * * * * php /var/www/pterodactyl/artisan p:server:bulk-power --servers=10 >> /dev/null```

Artisan also comes with `--no interaction` option already or `-n` for short.
