### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state.

### ISSUE THREAD

**Issue by NgLoader** [pterodactyl/panel#2007]
**Background (please complete the following information):**
* Panel or Daemon: 
* Version of Panel/Daemon: v1.0.0-beta.3
* Server's OS: Debian Linux 10
* Your Computer's OS & Browser: Windows 10 & (Opera GX) Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36 OPR/67.0.3575.130

**Describe the bug**
Unable to start any kind of server

Panel: Zend Engine v3.3.14
Daemon:
- OS: Linux vmd24523.contaboserver.net 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux
- Docker: 19.03.8

**To Reproduce**
1. Go to a random server
2. Click on Start
4. See error in web console **WebSocket is already in CLOSING or CLOSED state.**

**Expected behavior**
https://cloud.wuffy.eu/s/HAA3CcfAstNZ8Cz

Wings error:
```
May 08 21:33:39 ****.contaboserver.net wings[22018]:
May 08 21:33:39 ****.contaboserver.net wings[22018]: [GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 500
May 08 21:33:39 ****.contaboserver.net wings[22018]: [GIN] 2020/05/08 - 21:33:39 | 500 |  1.025182512s |   ***.***.***.*** | GET      "/api/servers/dbc4e459-9794-46d4-b5c3-8274dd36165d/ws"
```

**Comment by matthewpi** [comment]
Have you checked that `wings` isn't throwing errors?

**Comment by parkervcp** [comment]
probably related to #2000

**Comment by NgLoader** [comment]
@matthewpi of yeah

**Comment by parkervcp** [comment]
Yeah this is related to #2000 but the panel and not wings.

**Comment by parkervcp** [comment]
I am going to go with a "this is just #2000 causing this issue." and close this as a duplicate.
