### ISSUE TITLE
Plugins can't access internet?

### ISSUE THREAD

**Issue by VorTechHosting** [pterodactyl/panel#2013]
When I try to download plugins that require to connect to a HTTP or HTTPS connection, they fail to do so.  

Here's a plugins error log 
https://hatebin.com/skyvpanbsu
Server logs:
https://hatebin.com/kanojvjuig
Everything works fine when not using Pterodactyl so when using Pterodactyl plugins can no longer access things they need to, leading to the server "hanging" infinitely.  I've tried disabling UFW, opening all ports, different allocations, and none of my plugins can access the internet. Everything else works, players can connect to the servers however if a plugin is installed than is trying to do an auto-update the servers will drop to 0% CPU Usage and do nothing, also occasionally Minecraft can't validate a user leading to them being kicked with a Timeout error, and if connecting a server marked as online-mode: true it takes a long time to connect.

**Comment by parkervcp** [comment]
You ignored any of the questions we asked when you filled this out. Can you please give us that information

**Comment by VorTechHosting** [comment]
This is what I see when I went to fill it out, what questions?
We use GitHub issues only to discuss about Pterodactyl bugs and new features. For
this kind of questions about using Pterodactyl, please visit our Discord for assistance: https://pterodactyl.io/discord

DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**Comment by VorTechHosting** [comment]
**Background (please complete the following information):**
* Panel or Daemon: Daemon 
* Version of Panel/Daemon: 0.6
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
Panel v7.4.5
Daemon: Linux Desktop-U 5.4.0-29 generic #33
Docker Server Version: 19.03.8
Plugins can't do HTTP or HTTPS connection

**To Reproduce**
Use a plugin that needs HTTP or HTTPS connection
start server

**Expected behavior**
Connection goes through to the webpage to receive the information it needs

**Comment by DaneEveritt** [comment]
This is unlikely to be an issue with this software based on the details provided and that you're the only user of many thousands who is reporting this issue.

Please use our discord for more specific support as this is not a bug, and is likely a misconfigured firewall causing outbound connection issues, some some weird DNS settings.

**Comment by VorTechHosting** [comment]
We decided to not go with the hassle as this was clearly a bug with something in Pterodactyl.  Like I stated, running it outside of Pterodactyl it worked fine.  We have moved back to multicraft with no issues.

**Comment by DaneEveritt** [comment]
Sorry to hear that, unfortunately as I stated above the information provided indicates this is not a _bug_ with this software, rather a configuration issue between Docker and your host machine (most likely) that is causing requests to fail.

Glad you found something that works for you though, cheers.
