### ISSUE TITLE
Reinstall from backups

### ISSUE THREAD

**Issue by Corenb** [pterodactyl/panel#2016]
**Describe the solution you'd like**
Allow users to reinstall their server from a available backup.

**Describe alternatives you've considered**
You can just let user reinstall their server eggs and select pack but I think this can also be useful to reinstall it from backups.

**Comment by Sir3lit** [comment]
Not bad of an idea, But we would have to decide if its A. Going to delete everything currently then extract the backup. or B. Extract the backup and overwrite files. I feel Option A would make more sense as if you're restoring from a backup something got messed up...

**Comment by DaneEveritt** [comment]
Should be easy enough to just make that a toggle, no?

**Comment by Sir3lit** [comment]
Yeh, Like on the servers page for the admin to view all servers, like a "Restore" or "Overwrite" maybe a better choice of words...

**Comment by DarthShmev** [comment]
What is the point in including an option? As long as the result is the same for the end-user, it should not matter. We should decide on one method and leave it at that. Personally, I think Option A is a 'clean' way to handle this task.

**Comment by DaneEveritt** [comment]
They're two very different things though. Imagine you regularly make backups of only a single directory and want to restore. It'd be painful to have that delete everything.

**Comment by Sir3lit** [comment]
If so, I'd suggest what you suggested with a toggle. That would be clean restore or overwrite files as your two options

**Comment by IAmLythixIAmDumb** [comment]
I think you should make it so that you can restore backups by having wings extracting the files from the backup, and moving the extracted files into the server directory essentially restoring to the backup. Should probably delete the existing files before putting the backed up files in

And also, 
Allow users to upload a backup they've downloaded in the past to restore from that. (May not be possible on servers running some eggs like minecraft as they take a lot of space and will reach the web upload limit on most servers.)

**Comment by GravityCube** [comment]
> They're two very different things though. Imagine you regularly make backups of only a single directory and want to restore. It'd be painful to have that delete everything.

You could delete everything except ignored files and extract the backup. So you will not be deleting files or directories not included in the backup. It shouldn't be so hard and the ignored files array is already included in the backup data on the panel.

**Comment by Gaeta** [comment]
What about making a new Docker Container with the backup files. then swap the server to that one and delete the old container.

and maybe make a backup of the current one before you swap to the backed up files. Just in case.

**Comment by RayvenClaw** [comment]
Yes this feature would be awesome. Maybe when installing the backup, it should either 

1. If the whole server was backuped, remove everything from the server and load everything from the backup or

2. Only delete the files/folders that were not backuped.

The lack of this feature is for me one of the only reasons not to use Pterodactyl on all my Servers. Simply because one some Servers I need to reinstall Backups at least 1-2 a week.

**Comment by Gaeta** [comment]
If your reinstalling backups at least 1-2 a week what on earth are you doing to your server.

But it should keep the old docker until the new docker is full up. Once it is it should delete the old docker. OR if the new docker errors on install it should delete the new one OR let the user press what one it wants? (this one is more of a stretch)

**Comment by RayvenClaw** [comment]
> If your reinstalling backups at least 1-2 a week what on earth are you doing to your server.
> 
> But it should keep the old docker until the new docker is full up. Once it is it should delete the old docker. OR if the new docker errors on install it should delete the new one OR let the user press what one it wants? (this one is more of a stretch)
> 
> 

Stress testing and that sometimes bricks the container/server Files inside it

**Comment by zefir-git** [comment]
Why does the server need to be re-installed to restore a backup? I believe an option to just be able to get the backup as a ZIP and decide how you're gonna extract it yourself would be much simpler. A downside to this is that it will take a lot of disk space and might exceed the server limit.
My other suggestion would be to just stop the server, delete all files, extract backup. Shutting down the server will clear data about your game stored in memory. All other game data is stored on the disk, so no re-install is needed.

**Comment by misterquestions** [comment]
Hey there. I think it would be good to be able to either use a backup on an existing server (restore) or create a new server from it

**Comment by DaneEveritt** [comment]
Closed in 1.3.0.
