### ISSUE TITLE
Unknown operating system Ubuntu 18.04

### ISSUE THREAD

**Issue by Lars225** [pterodactyl/panel#2023]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: Daemon 0.6
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: 

**Describe the bug**
On starting the Daemon this error Messages comes.

**To Reproduce**
Running as root
14:09:07.389Z FATAL wings: A fatal error caused the daemon to abort the startup. (additional={})
Error: Unable to create a pterodactyl user and group, unknown operating system.
at Async.waterfall (/srv/daemon/src/index.js:200:34)
at nextTask (/srv/daemon/node_modules/async/dist/async.js:5324:14)
at next (/srv/daemon/node_modules/async/dist/async.js:5331:9)
at /srv/daemon/node_modules/async/dist/async.js:969:16
at Getos (/srv/daemon/src/index.js:176:21)
at /srv/daemon/node_modules/getos/index.js:95:16
at wrapper (/srv/daemon/node_modules/getos/node_modules/async/dist/async.js:268:20)
at iteratorCallback (/srv/daemon/node_modules/getos/node_modules/async/dist/async.js:495:17)
at /srv/daemon/node_modules/getos/node_modules/async/dist/async.js:321:20
at /srv/daemon/node_modules/getos/index.js:90:18
14:09:07.389Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.

**Comment by parkervcp** [comment]
Are you running the daemon as root? You don't give any context around the error. Just that there is an error.

**Comment by Lars225** [comment]
updated yes running at root

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/daemon/blob/develop/src/index.js#L191 might need to be changed to `Ubuntu`.  An update to [getos](https://www.npmjs.com/package/getos) might have changed it to output `Ubuntu` instead of `Ubuntu Linux` or different installations might print something else.  As a work around to get past the error, running `useradd --system --no-create-home --shell /bin/false pterodactyl` will fix it.

**Comment by Wqrld** [comment]
see https://github.com/retrohacker/getos/commit/58e84254077e1b537d576708d70e20d35c80bb94 for the namechange

**Comment by DaneEveritt** [comment]
wontfix, not planning on doing any additional releases for the Nodejs daemon unless critical security fixes.
