### ISSUE TITLE
Add PostgreSQL support

### ISSUE THREAD

**Issue by GalacticLion7** [pterodactyl/panel#2025]
Please add PostgreSQL support in the panel for consistency with other projects.

PostgreSQL could be natively implemented into the panel, or using the [mysql_fdw](https://github.com/EnterpriseDB/mysql_fdw) wrapper to convert MySQL queries into PostgreSQL queries.

**Comment by matthewpi** [comment]
Laravel already supports Postgres, but some migrations and queries that are in the panel don't.  I'd love for Postgres to be supported, the only issue I see is the potential issues with changing older migrations, but I believe that should be mostly fine.

**Comment by DaneEveritt** [comment]
Unless someone opens a PR to add this support, I will not be implementing it. I'm closing this issue in that case, however feel free to reference it in the PR.

**Comment by Weilbyte** [comment]
Hi @DaneEveritt, I am currently working on supporting Postgres, can this issue be reopened and assigned to me? Thanks!

PR will be opened soon, just need to do some testing on my own. But so far, every integration test passes.

**Comment by ririko5834** [comment]
Will be PostgreSQL support added also to database hosts and that users can pick databse type when creating database?
