### ISSUE TITLE
File Manager Edit Chiniese file error.

### ISSUE THREAD

**Issue by williambacteria** [pterodactyl/panel#2026]
When a file named by chiniese like 传送系统.yml, click the file to edit will return 404 error.

**Comment by pbeart** [comment]
I do not encounter this issue when creating a file with that name on panel 0.7, with an English language region. Could you use the template to describe what system you encounter this on?

**Comment by DaneEveritt** [comment]
If you're not going to fill out the very obviously required template, I'm not going to take the time to look into these issues.
