### ISSUE TITLE
SFTP Server Start error

### ISSUE THREAD

**Issue by williambacteria** [pterodactyl/panel#2028]
Panel or Daemon: Daemon
Version of Panel/Daemon: 0.6.13
Server's OS: Ubuntu 18.04
Your Computer's OS & Browser: Windows 10 & Chrome

Websocket for daemon runs well ,but when user cant access to  File Manager.
I restart the wings , wings did'nt run the Sftp Server.
![image](https://user-images.githubusercontent.com/25552054/81966650-6090ba80-964c-11ea-969c-f997f84365be.png)

**Comment by williambacteria** [comment]
I can't control even if the panel has connected the daemon
![image](https://user-images.githubusercontent.com/25552054/81977608-dc92fe80-965c-11ea-9085-d39f7eca6440.png)
![image](https://user-images.githubusercontent.com/25552054/81977626-e1f04900-965c-11ea-8365-7e2fdacaacfb.png)
![image](https://user-images.githubusercontent.com/25552054/81977646-e9afed80-965c-11ea-9a7e-d805ef8333dc.png)
![image](https://user-images.githubusercontent.com/25552054/81977655-ecaade00-965c-11ea-97ca-5aa3b3409a60.png)

**Comment by LeCodeCo** [comment]
This is an issue for Discord, and not the GitHub issue tracker. https://discord.gg/pterodactyl

Your server folders are missing, which is why you get that error.
