### ISSUE TITLE
Allow more explicit setting of base URL

### ISSUE THREAD

**Issue by bppdddqqqq** [pterodactyl/panel#2029]
**Is your feature request related to a problem? Please describe.**
The way the current base URL definition works disallows usage of reverse proxies that are explicitly set to run in HTTPS mode only and prefer not to use HTTPS on IPC (say docker to router).

**Describe the solution you'd like**
Split URL into 3 parameters. Protocol, base domain and path prefix. Make these changes absolute and static, thus it shouldn't switch over sources/links to http, just because it couldn't maintain https connection. This should fix issues relating to Mixed Sources if the router is set to communicate in HTTPS only and some javascript code (looking at auto-deploy) is set to communicate in HTTP only unless HTTPS is surely "detected" by pterodactyl

**Comment by DaneEveritt** [comment]
This is likely a proxy configuration issue with the `TRUSTED_PROXIES` environment variable? I have zero plans to work on implementing this type of change when its worked fine for the last 5 years of production deployments in 99% of environments.

I imagine something on this page might help with the configuration: https://laravel.com/docs/7.x/requests#configuring-trusted-proxies

If not, I still am not going to be making any changes.
