### ISSUE TITLE
Environment Variables are all parsed as strings

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#2030]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0.0.beta.4
* Server's OS: All
* Your Computer's OS & Browser: 

**Describe the bug**
The daemon is parsing all values in the environment as strings and wraps them with double-quote marks (`"`). This breaks the startup on servers where the variable is a port number as it gets parsed as a string and not a number value. 

**To Reproduce**
Install a Rust server.
The RCON_PORT variable will be wrapped like "28016" which breaks the wrapper and potentially other servers.

**Expected behavior**
don't wrap all variables in double-quote marks

Potential fixes:  
1. Use [string]interface{} (possible to break in other creative ways)
2. Wrap strings specifically in the panel before it's sent to the daemon

**Comment by parkervcp** [comment]
Of course we could just keep it in parity with the node daemon. Would keep it in line with what is already there.

**Comment by DaneEveritt** [comment]
Well yes, that is the goal. This is just an unexpected bug because Node and Go are wildly different languages. :)

**Comment by parkervcp** [comment]
granted they are hugely different
