### ISSUE TITLE
Unable to determine server data size

### ISSUE THREAD

**Issue by a-aron12** [pterodactyl/panel#2033]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.13
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chrome

**Describe the bug**
When starting the server it takes 10-15 minutes to start as it keeps failing to determine the size of the server. When the server is started it gets to "[Pterodactyl Daemon] Ensuring correct ownership of files" then hangs for ages. 

Error pulled from logs: 

{"name":"wings","hostname":"0000","pid":,"server":"REDACTED","level":40,"err":{"message":"Unable to determine size of server data folder, exited with code 1 signal null.","name":"Error","stack":"Error: Unable to determine size of server data folder, exited with code 1 signal null.\n    at ChildProcess.Exec.on (/srv/daemon/src/controllers/fs.js:89:29)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)"},"msg":"Unable to determine size of server data folder, exited with code 1 signal null.","time":"2020-05-06T20:17:26.950Z","v":0}

**Comment by parkervcp** [comment]
Is that a large folder with time of small files? I assume it's having issues trying to do a full `du` on the folder while it starts.

**Comment by a-aron12** [comment]
Yes its quite big the full size is 165GB with a lot of chunks and dynmap files. Is there a way to disable the check for even just one server?

**Comment by DaneEveritt** [comment]
Not that I am aware of, however I also will not be addressing this issue since it is unlikely to be an issue with the new Wings code, and I'm not currently putting time into the existing daemon unless it is security related.
