### ISSUE TITLE
Able to make 2 nodes with 1 FQDN

### ISSUE THREAD

**Issue by LeCodeCo** [pterodactyl/panel#2036]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: beta4
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 & Google Chrome

**Describe the bug**
Right now, you can make two nodes with the same FQDN. When visiting the node list page, you get the error `The payload is invalid. (View: /var/www/pterodactyl/resources/views/admin/nodes/index.blade.php)`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a node
2. Create a new node with FQDN
3. Access node list page

**Expected behaviour**
I expect that making the 2nd node with the same FQDN to be blocked.

**Comment by Sir3lit** [comment]
You could have two nodes on one fqdn and just on other ports.... Now why would you have two nodes on a machine? No idea. 😂

**Comment by Telesphoreo** [comment]
What's the problem with having one FQDN for two nodes. I need to run servers off of my internal and external disk, and the only way I can do this is with two nodes and one FQDN. I personally don't think this should be blocked.

**Comment by DaneEveritt** [comment]
It is a bug though. There is no way you would have two nodes with the same FQDN and port. Its not so much the FQDN alone that is problematic, it just needs a unique constraint on `FQDN, daemonPort`

**Comment by Sir3lit** [comment]
I'm not able to reproduce this?

![image](https://user-images.githubusercontent.com/1757840/82136113-1e947f80-97d8-11ea-9036-e11f3356b1de.png)
![image](https://user-images.githubusercontent.com/1757840/82136117-2a804180-97d8-11ea-9288-323c0941ce44.png)
![image](https://user-images.githubusercontent.com/1757840/82136147-7df28f80-97d8-11ea-86c5-3e3fccccb7e1.png)



The only thing in the panel logs is that it's getting a 403, and that's correct as it doesn't have the right key/token..... I do however see that, if it cannot communicate wing wings, it fails to save changes in the database and reverts them back to whatever they were when the node was created.

Not sure where you're seeing this invalid payload error?

**Comment by LeCodeCo** [comment]
Can't reproduce the error now. Closing the issue.
