### ISSUE TITLE
Panel file manager returns 404 when attempting to view a directory with spaces in the name

### ISSUE THREAD

**Issue by gpayio** [pterodactyl/panel#2038]
**Background (please complete the following information):**

**Panel or Daemon:** Pterodactyl and Wings
**Version of Panel/Daemon:** 1.0.0 beta 3 panel and 1.0 beta 4 wings
**Server's OS:** Ubuntu 18.04
**Your Computer's OS & Browser:** Windows 10 & latest chrome version

**Describe the bug**
When you create a directory with spaces in the name such as "test dir" and attempt to enter it using the file manager, you will be presented with a 404.

**To Reproduce**

**Steps to reproduce the behavior:**
Create a directory with spaces in the name

**Expected behavior**
Don't return 404 when entering a valid directory even with spaces in the name

**Comment by parkervcp** [comment]
I can verify this is an issue I have reproduced
