### ISSUE TITLE
Config replacement escapes values unnecessarily

### ISSUE THREAD

**Issue by iamkubi** [pterodactyl/panel#2041]
Filing this on behalf of a user, some info isn't available but shouldn't be necessary to reproduce.

**Background (please complete the following information):**
* Panel or Daemon: Both
* Version of Panel/Daemon: 1.0.0-beta.4 / 1.0.0-beta.5
* Server's OS: Unknown / NA
* Your Computer's OS & Browser: Unknown / NA

**Describe the bug**
The panel unnecessarily escapes strings when performing the config replacement on startup.  The Terraria Vanilla egg (https://github.com/parkervcp/eggs/blob/master/terraria/vanilla/egg-terraria-vanilla.json#L13) uses such a replacement.

On 0.7 this works as expected and results in properly formatted paths:
```
# head -3 serverconfig.txt
worldpath=/home/container/saves/Worlds
worldname=world
world=/home/container/saves/Worlds/world.wld
```

On 1.0 the slashes get escaped and the config looks like:
![image](https://user-images.githubusercontent.com/6176191/82244782-9d7fda00-98f6-11ea-9595-015f645376a6.png)

**To Reproduce**
1. Install the Terraria Vanilla egg
2. Create a server
3. World resets any time server restarts because the save location is not properly set.

**Expected behavior**
Replacement values should not be escaped.

**Comment by iamkubi** [comment]
I also just noticed the whitespace around the equal signs, which doesn't exist in 0.7 and probably shouldn't be there.

**Comment by matthewpi** [comment]
Looking the egg, the parser line is escaped in places when it doesn't need to.
```
"files": "{\r\n    \"serverconfig.txt\": {\r\n        \"parser\": \"properties\",\r\n        \"find\": {\r\n            \"worldpath\": \"\/home\/container\/saves\/Worlds\",\r\n            \"worldname\": \"{{server.build.env.WORLD_NAME}}\",\r\n            \"world\": \"\/home\/container\/saves\/Worlds\/{{server.build.env.WORLD_NAME}}.wld\",\r\n            \"difficulty\": \"{{server.build.env.WORLD_DIFFICULTY}}\",\r\n            \"autocreate\": \"{{server.build.env.WORLD_SIZE}}\",\r\n            \"port\": \"{{server.build.default.port}}\",\r\n            \"maxplayers\": \"{{server.build.env.MAX_PLAYERS}}\",\r\n            \"motd\": \"{{server.build.env.SERVER_MOTD}}\"\r\n        }\r\n    }\r\n}",
```

Specifically `\"worldpath\": \"\/home\/container\/saves\/Worlds\",` should be `\"worldpath\": \"/home/container/saves/Worlds\",` as `/` does not need to be escaped.

Also the spaces before and or after the `=` sign are allowed, so that isn't a big deal.

**Comment by iamkubi** [comment]
I'm pretty sure that's normal for eggs.  Since it works on 0.7 and not on 1.0 that would seem to confirm it?

**Comment by matthewpi** [comment]
It could either be the panel is improperly encoding it and or wings is leaving the "escapes" as they don't escape anything.

I have a feeling this is probably the jsonparser being smart and not removing redundant escapes and treating them as real characters.

**Comment by iamkubi** [comment]
Yeah, I guess a better description would be that it's not removing the escaping that's required for the eggs in 0.7.  I'm curious to see if an exported egg on 1.0 includes the escaping.

**Comment by iamkubi** [comment]
> Also the spaces before and or after the `=` sign are allowed, so that isn't a big deal.

Also, you're acting as if game servers follow some sort of standard.  Who says the spaces are allowed?  I think they worked this time, but it's pretty obviously incorrect to change arbitrarily add spaces when doing find and replace.

**Comment by matthewpi** [comment]
> > Also the spaces before and or after the `=` sign are allowed, so that isn't a big deal.
> 
> Also, you're acting as if game servers follow some sort of standard. Who says the spaces are allowed? I think they worked this time, but it's pretty obviously incorrect to arbitrarily add spaces when doing find and replace.

You would be surprised how many file parsers are very forgiving on syntax (except YML), I'm not saying all of them follow a standard but any basic `key = value` parser should support spaces.  I don't think forcing an unwanted format should be the way it is, but what if the game server's config requires spaces?  Without having 200 different parsing options or having parsers not "reformat" files, it will always break or do unwanted behavior.  There are also a [text replacer](https://github.com/pterodactyl/wings/blob/develop/parser/parser.go#L394) which could do a find and replace with almost any syntax with enough trial and error for some of those cases.  The goal is not to support every game possible as that would require supporting every single file format that could be used (ignoring any game-specific custom formats).  If it works well enough for most games than it is doing it's job.  There is also the option to make changes to the config in the egg's entrypoint or not use the config parser entirely.

**Comment by DaneEveritt** [comment]
The spaces will stay since they're built into the package I'm using to handle parsing.

**Comment by iamkubi** [comment]
The ini parser defaults to using a PrettyFormat mode that puts spaces around the equals signs.
https://github.com/go-ini/ini/blob/v1.57.0/ini.go#L49-L51

I'll send a PR to disable PrettyFormat.

**Comment by iamkubi** [comment]
I made a fix for this on the ini parser (which someone on Discord asked about), then went to test it and realized my test egg uses the properties parser, which has the same behavior but without any way to disable it.

I guess if it's going to be mangling config files it may as well do it consistently across parsers, so I'll just leave this as is.

**Comment by DaneEveritt** [comment]
We should actually ideally managle as few as possible. Can always fork/PR a fix for the properties one.
