### ISSUE TITLE
Wings ignores default values, disables sftp out of box

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2045]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: B5
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: WinBlows 10 / Chrome

**Describe the bug**
Changes in https://github.com/pterodactyl/panel/commit/3b2e2c63c62f7df1846af193d5eea5e96259e0a6 remove the bind-address and true setting for SFTP causing it to be disabled out of the box. 

Seems the default in wings is also not working for those values. As use_internal
https://github.com/pterodactyl/wings/blob/develop/config/config.go#L86-L99

![image](https://user-images.githubusercontent.com/1757840/82294237-d1511300-997b-11ea-83dc-fc7750036b02.png)
Left is the older config from previous betas, Right is new config + power cycled wings
**To Reproduce**
Delete current "rolled over" config
Grab new config from the panel
Start wings / Stop wings
Look at the newly updated config

**Expected behavior**
The default values are used...?

**Comment by DaneEveritt** [comment]
Whoops.
