### ISSUE TITLE
API Wont connect to pterodactyl Error 500

### ISSUE THREAD

**Issue by jorickjuh** [pterodactyl/panel#2051]
I am trying to connect WHMCS to pterodactyl. But i get this error in my panel logs:

http://bin.ptdl.co/tvjxp

I have tried to use a other api for this but this also did not work:

![image](https://user-images.githubusercontent.com/26413543/82380857-7b3aa900-9a29-11ea-8fa3-f333015d1502.png)

**Comment by schrej** [comment]
This doesn't look like a bug, but like a configuration issue. Please visit our discord for support.
