### ISSUE TITLE
Panel not loading on Safari

### ISSUE THREAD

**Issue by Games4k** [pterodactyl/panel#2052]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-beta4
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: macOS Mojave, Safari (but tested on iOS 13.5 too)

**Describe the bug**
I am unable to load the panel on Safari on macOS (works perfectly fine on Chrome), and I'm completely unable to load the panel on iOS, no matter what browser I choose. I just get a white background and that's it.

**To Reproduce**
Steps to reproduce the behavior: Try loading the panel from macOS (Safari) or iOS.

**Expected behavior**
I obviously expect the panel to load normally on all the browsers.

**Comment by parkervcp** [comment]
Please check your browser console in safari. I assume they might be blocking something as they are more restrictive than chrome will be. Both browsers are chromium based.

as for iOS all browsers have the same backend.

**Comment by Games4k** [comment]
![Screen Shot 2020-05-20 at 5 02 51 PM](https://user-images.githubusercontent.com/29690431/82462352-c1d8e380-9abb-11ea-9a5c-668c6abaa644.png)

This is the console output from Safari (MacOS)

**Comment by mattmalec** [comment]
Just tested on 1.0.0-beta5 using iOS Safari on my iPhone, works perfectly fine and as expected.

**Comment by DaneEveritt** [comment]
Are you serving content over Cloudflare or something? It looks like something is getting changed in the resources which causes the hash to change and Safari (and really any browser) to block it.

**Comment by mattmalec** [comment]
On my end, I’m proxying my site through Cloudflare with all of the "Auto Minify" features unchecked (HTML, CSS, JS). Rocket Loader is also disabled. Caching is left on the default settings. Very interested to hear @Games4k setup.

**Comment by Games4k** [comment]
I'm currently on https://www.nooder.net, as they are on the same host as my machines are - servereasy.it. Maybe that could be a problem on their end?

I've also done a few tests, if you add some manual HTML code, like the one at the top of the wrapper, which says "You're currently using beta version..." it is displayed, but the rest of the JavaScript page is not - the rest is just a white background.

**Comment by DaneEveritt** [comment]
Yeah, I'm using content integrity hashing, so if the hash doesn't line up with the hash of the actual content returned, the browser won't execute it. Its a way of preventing MITM attacks or unauthorized modification of JS resources, which is why I'm tempted to believe something is changing the content of your files.

Are you able to run a diff on the JS file we ship in the bundle, and the JS that you're getting back in the browser (by direectly visiting the URL). Theoretically there should be no difference.

**Comment by Games4k** [comment]
Sure, I'll close this issue, and contact them. I'll reopen it if needed. Thanks!
