### ISSUE TITLE
Beta server pages missing "Start Configuration" section

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#2054]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0 beta 4
* Server's OS: Cent 8 (alpine docker image)
* Your Computer's OS & Browser: Windows 10 Firefox

**Describe the bug**
"Start Configuration" section is missing in server page.

![image](https://user-images.githubusercontent.com/1207679/82496929-79b9c100-9abb-11ea-8e98-66a695831b98.png)

**To Reproduce**
No steps to reproduce. It's just missing at this time

**Comment by DaneEveritt** [comment]
This is expected, seeing as it hasn't been built. :)

**Comment by parkervcp** [comment]
Was just calling it out. Didn't see anything about it.
