### ISSUE TITLE
Ability to disable the pre-release notification

### ISSUE THREAD

**Issue by danielnaaman** [pterodactyl/panel#2058]
**Is your feature request related to a problem? Please describe.**
Not exactly, it's just bugging me in the eyes and I think that one clear notification upon the initial setup should suffice. 

**Describe the solution you'd like**
Just add a toggle-able switch in the admin area to disable this.

**Describe alternatives you've considered**
Possibly a walk-through the new panel ending the in message saying that this is a pre-release version. Another possibility is just make the notification go away in three days or have it appear just in the admin panel.

**Additional context**
I'm fully aware that this version shouldn't be used for production hence all of these alerts but it's just bugging my eyes, would definitely like to see this in future versions in case beta doesn't end too soon.

**Screenshot**
![image](https://user-images.githubusercontent.com/16944217/82659370-413bf380-9c31-11ea-9a9d-8830025a1ad8.png)

**Comment by parkervcp** [comment]
Is there to constantly remind you. 

If a host decided to just hide it and use the beta in prod then they'd complain to us about issues.

**Comment by FoksVHox** [comment]
If you so badly want to remove the pre-release alert, you could just go in the code and remove it. I mean it is not exactly rocket science that is used to program & develop really neat software like Pterodactyl.
