### ISSUE TITLE
Auto-deploy uses wrong wings.service file.

### ISSUE THREAD

**Issue by FoksVHox** [pterodactyl/panel#2061]
**Background (please complete the following information):  **
I was trying to install the new Pterodactyl 1.0 Beta with the auto-deploy feature, and command went well, except for the `wings.service` which was created with the configuration for NodeJS Daemon and the Go Deamon / Go Wings
* Panel or Daemon: Daemon & Panel
* Version of Panel/Daemon: Panel: 1.0 Beta 4 & Daemon: 1.0 Beta 5
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: 7.4.3

**To Reproduce**
1. Install the panel
2. Install the daemon but use the auto-deploy feature
3. Look under the daemon tab and you'll see that the daemon is not active.
4. Look under the `wings.service` service file, and you'll see it is the NodeJS config file

**Expected behavior**
The expected behavior is that the auto-deploy feature uses the Go wings.service file and not the NodeJS.

**Comment by matthewpi** [comment]
The auto-deploy feature doesn't create a service file what so ever.  It's only purpose is to automatically fetch the config from the panel.  You are responsible for installing the daemon normally, including the systemd configuration.

**Comment by FoksVHox** [comment]
I forgot that for a quick second..
