### ISSUE TITLE
Gmod server hard crash / freeze or segmentation fault etc shows ips as the docker network interface address

### ISSUE THREAD

**Issue by Synkstar** [pterodactyl/panel#2062]
**Background (please complete the following information):**
* Panel or Daemon:  Daemon
* Version of Panel/Daemon: 0.6.13
* Server's OS: Ubuntu server 20.04
* Your Computer's OS & Browser: Windows( Shouldn't matter for this )

**Describe the bug**
After the server starts back up after having to kill it or a segmentation fault it shows the incoming ips as the docker interface for a bit then it shows the correct ips when the server has been online for awhile and for the people that have the docker network ip they would have that for like awhile until the connection table clears I guess.

**To Reproduce**
1. Freeze the server with props so its pinned at 100% and not responding
2. Kill it and start it.
3. Connect and you should see the ip as  172.18.0.1(Unless you changed it or something)

**Expected behavior**
The ip should be shown as the correct ip and not the docker interface.

**Comment by DaneEveritt** [comment]
This sounds like an issue with GMod, and not this software. Its been a long standing issue that GMod and other source games show incorrect IP addresses when run in Docker containers.

**Comment by Synkstar** [comment]
So it aint possible to fix it ?

**Comment by FoksVHox** [comment]
I’ve run GMod multiple times on Pterodactyl, and never seen this issue, even tho I’ve done the exact same things as you provided as reproducere steps...

If you belive this is an issue with Gmod then head over to Facepunch/garrysmod-issues and submit an issue report @Synkstar

**Comment by Synkstar** [comment]
Its very strange and happens sometimes and still happened when I moved it from a virtual to a physical machine. Probably something with docker not starting up fully because as you know with a gmod server when it crashes everyone connects the second it comes online but after a few it goes back to showing the correct addresses

**Comment by Synkstar** [comment]
Could it have anything to do with having multiple network interfaces on the server ? Like I have one on a vlan for connections from somewhere else but only 1 default gateway

**Comment by FoksVHox** [comment]
Elaborate?

**Comment by Synkstar** [comment]
![image](https://user-images.githubusercontent.com/26175394/82818723-248bff80-9e6d-11ea-965e-36dd53c3273c.png)
Well when I had it in a virtual machine I added physical adapters aswell. It might actually be caused by it because I don't remember seeing it before I did the vlan setup and had multiple adapters.

**Comment by Synkstar** [comment]
This problem is still a thing the only fix that I know of is to use host networking. Which I can't really do for security reasons because I host stuff for others. Usually happens after a server restart. Looks bad honestly to see lan ips, Host mode only fixes it because it binds directly to the ip and doesnt use nat so it has no lan address to show. Is it possible to have docker network issolation but get rid of NAT and have it use the external ip ?
