### ISSUE TITLE
Can't leave ignored files box empty, backup task shows as power action

### ISSUE THREAD

**Issue by IAmLythixIAmDumb** [pterodactyl/panel#2067]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel beta-4
* Server's OS: Ubuntu 18.04 LTS (Bionic)
* Your Computer's OS & Browser: Windows 10 Pro, Microsoft Edge Chromium

**Describe the bug**
When creating a make backup task in a schedule, it will require you to put something in the ignored files box, it will show up as a power action task once created.

**To Reproduce**
- Can't leave ignore files box empty
1. Make a schedule
2. Make a create backup task
3. Leave the ignore files box empty
4. Try to create the task
5. See this error:
![image](https://user-images.githubusercontent.com/54075275/82830016-e9152380-9eb4-11ea-9958-f15fd11bc024.png)
- Make backup task shows as power action
1. Make a schedule
2. Make a create backup task
3. See backup task show up as power action:
![image](https://user-images.githubusercontent.com/54075275/82830123-2c6f9200-9eb5-11ea-965a-555705b8ec73.png)

**Expected behavior**
You can create a make backup task and leave the ignore files box empty and create the task.
Task shows up as make backup.

**Comment by DaneEveritt** [comment]
That was a mess, sorry about that.

![](http://kelp.in/mvhYwi.png)
