### ISSUE TITLE
Container Running, Panel says it's stopped.

### ISSUE THREAD

**Issue by necrogami** [Pterodactyl/Panel#207]
Updated the daemon and panel today.

This has happened multiple times .. created a default minecraft container which dumps out to 1.10.2 and started the container, stopped the container, and restarted it. And after a short bit the panel think's it's not running but the docker container is running. trying to start or restart it gives an error that it's running.

Killing the container makes the container restart. stopping the minecraft server makes it restart but the panel still thinks it's not running.

I cannot issue commands via the panel but i can see the server running in the panel.

**Comment by necrogami** [comment]
Update: What has happened is if i'm looking at it (global admin) and my user is looking at the server overview at the same time. it breaks. If i attach to the docker container and stop the server while one of us is off page and it auto-restarts. The moment after the other person connects to the overview page it breaks.

**Comment by DaneEveritt** [comment]
Hey, what version of the daemon is this? I believe @parkervcp had the same issue and it was fixed last night (release `v0.3.6`).

**Comment by necrogami** [comment]
0.3.6 daemon, updated it this evening.

**Comment by necrogami** [comment]
wait hangon.

**Comment by necrogami** [comment]
found out the issue .. it's 0.3.5

https://daemon.pterodactyl.io/docs/upgrading-from-previous-versions had a 0.3.5 url for a 0.3.6 filename

**Comment by DaneEveritt** [comment]
Ah, it does indeed, I will fix that right now, thanks for letting me know!

**Comment by necrogami** [comment]
corrected the url in my update string and updated to 0.3.6 and it appears to have fixed the issue. Thanks!

**Comment by DaneEveritt** [comment]
Awesome, glad to hear, and thanks for letting me know about the URL issue. 👍
