### ISSUE TITLE
Support for reCaptcha v3

### ISSUE THREAD

**Issue by Games4k** [pterodactyl/panel#2070]
**Is your feature request related to a problem? Please describe**
No, it’s not

**Describe the solution you'd like**
I would like to request support for reCaptcha v3, as it doesn’t need user interaction and is generally more secure.

**Describe alternatives you've considered**
None

**Comment by DaneEveritt** [comment]
I don't think the current reCAPTCHA configuration is obtrusive, logins and password resets are an infrequent action for users on the panel. I also don't see this as a beneficial use of my limited time right now to implement. 

Thank you for the suggestion however. :)
