### ISSUE TITLE
Install script fails to use updated server variables, changed variables not passed to install script.

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2072]
**Background (please complete the following information):**
* Panel or Daemon: Both?
* Version of Panel/Daemon: Wings B5, Panel B4
* Server's OS: Ubuntu
* Your Computer's OS & Browser: Win10 Chrome

**Describe the bug**
When installing a server and then changing a variable, then reinstalling the server without starting it never updates the variables in the install script, So the new values are never used.

I started with Version 0.18.24, Reinstalled, Changed to 0.18.26, Reinstalled( Still used the value of 0.18.24) Then changed to 0.18.28 and it still used the original value.
https://youtu.be/6kIzyDQsEgg

**To Reproduce**
1. Install a server
2. Change a variable that's used in the install script
3. Reinstall server
4. Watch the install log and see old value is still used.
5. For giggles try and change it again and reinstall, Will use the original value 

**Expected behavior**
Newly updated values are used when the server is reinstalled.

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/wings/commit/ea2630946a0cd6117ac5c792d3939a169cba4521
