### ISSUE TITLE
**BETA** config file gets overwritten on every start/restart

### ISSUE THREAD

**Issue by MasterLuke117** [pterodactyl/panel#2074]
```
* Panel or Daemon: panel
* Version of Panel/Daemon: wings beta.5 and panel beta.4
* Server's OS: Ubuntu server 20.04
* Your Computer's OS & Browser: Win10 / Chrome 

**Describe the bug**

with nukkit and spigot, the server jar appears to not see the existing 
server.properties file in the root directory, 
therefore it regenerates it on every start/restart.
so any settings do not save.

Panel: PHP 7.4.6 (cli)
Daemon:  

Server Version: 19.03.9
Kernel Version: 5.4.0-31-generic
Operating System: Ubuntu 20.04 LTS
Linux n3 5.4.0-31-generic #35-Ubuntu SMP 
Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux


**To Reproduce**
Steps to reproduce the behavior:

1. install server (nukkit or spigot)
2. edit server.properties
3. start server
4. server.properties is overwritten to default values

**Expected behavior**
server.config settings save and do not get overwritten 
```

**Comment by parkervcp** [comment]
Part of that may be the fact that the daemon is editing the file before the server is started to meet the settings in the start config section. It really depends on what changes you are seeing here.

**Comment by MasterLuke117** [comment]
pretty much all the main settings like: level name, MOTD, max players,  view distance ect. are not saved.

**Comment by DaneEveritt** [comment]
I am unable to reproduce this on the latest codebase for the daemon using the instructions provided. If you are still seeing it happen, please let me know. Additionally, if it is indeed still happening please confirm it happens with an egg that we ship by default, and let me know _exactly_ what steps you're taking.
