### ISSUE TITLE
Schedule sometimes repeats tasks every minute, ignoring specified intervals

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#2075]
**Background:**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: Wings Beta 5
* Server's OS: Ubuntu 18.04 LTS (Bionic)
* Your Computer's OS & Browser: Windows 10 Pro, Microsoft Edge Chromium

**Describe the bug**
When creating a schedule on about 5 - 10 hours it has a chance to glitch out and keep repeating the schedule tasks over and over again once it runs the schedule.

**To Reproduce**
1. Create a schedule on about a few hours.
2. Put a task which makes it say something in the console
3. Wait for the schedule to run
4. See it repeat the same task over and over again sometimes.

**Expected behavior**
Once the schedule runs it runs the tasks once and then waits for the next time the schedule is supposed to run.

This happens like 2 out of 3 times the schedule is run.

**Comment by xiaous** [comment]
![image](https://user-images.githubusercontent.com/9314129/86018987-08dbc200-b9f4-11ea-9b30-c51dbc2fa4be.png)
![image](https://user-images.githubusercontent.com/9314129/86019000-0ed1a300-b9f4-11ea-8f02-c2ed1bb85f5f.png)

I think I may be getting the same issue.

**Comment by parkervcp** [comment]
I have questions about your pteroq services. Are they running? Logged any errors?

**Comment by DaneEveritt** [comment]
@xiaous you are not running the beta, this issue specifically is regarding the beta version.

**Comment by DaneEveritt** [comment]
Well, they have to be running if they're getting run results. 🤗 Perhaps something is erroring out though making the scheduler think it needs to keep running, logs would indeed be useful (or confirmation of the lack of logs at least).

**Comment by xiaous** [comment]
There are indeed no logs, if I check the status of the pteroq service it's just processing and processed.

```Jun 29 15:59:08 testserver php[16506]: [2020-06-29 11:59:08][CxhBmCrYX6GUvUUCL4wpxao1Lo5vbRhg] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Jun 29 15:59:08 testserver php[16506]: [2020-06-29 11:59:08][CxhBmCrYX6GUvUUCL4wpxao1Lo5vbRhg] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Jun 29 16:00:02 testserver php[16506]: [2020-06-29 12:00:02][OpGYrjEhSVghSylhrbfN1g9wR6zoPl4w] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Jun 29 16:00:02 testserver php[16506]: [2020-06-29 12:00:02][OpGYrjEhSVghSylhrbfN1g9wR6zoPl4w] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Jun 29 16:00:08 testserver php[16506]: [2020-06-29 12:00:08][ImEifoO0fbVeUOZ6eBk5WWRbaQg7sZfZ] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Jun 29 16:00:09 testserver php[16506]: [2020-06-29 12:00:09][ImEifoO0fbVeUOZ6eBk5WWRbaQg7sZfZ] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Jun 29 16:01:03 testserver php[16506]: [2020-06-29 12:01:03][WAfauqxRYytFQI6dfuilyC7kjGGhe6G2] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Jun 29 16:01:03 testserver php[16506]: [2020-06-29 12:01:03][WAfauqxRYytFQI6dfuilyC7kjGGhe6G2] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Jun 29 16:01:09 testserver php[16506]: [2020-06-29 12:01:09][52vI0WfZBNwHWMrO9bFeEcjoSn2Ui8G8] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Jun 29 16:01:09 testserver php[16506]: [2020-06-29 12:01:09][52vI0WfZBNwHWMrO9bFeEcjoSn2Ui8G8] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob```

**Comment by Porama6400** [comment]
Same problem here

I've tried

- remove and create new task
- restart pteroq
- php artisan queue:restart

none help

**Comment by DaneEveritt** [comment]
Closing this out, I believe it was tracked down somewhere else that this happens when the MySQL instance and Panel are in different timezones.
