### ISSUE TITLE
Multiple "Server marked as running" messages

### ISSUE THREAD

**Issue by fabm3n** [pterodactyl/panel#2077]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: beta 4
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Win 10 Pro 1909 Build 18363.836 & Google Chrome 83.0.4103.61
* PHP Version: 7.4.6

**Describe the bug**
In the console the message that the server is running is displayed several times although the done variable was only displayed once. If you reload the page after the server is running, the issue is gone.
![image](https://user-images.githubusercontent.com/11352551/83246503-85377700-a1a2-11ea-8740-41e85539c816.png)

![image](https://user-images.githubusercontent.com/11352551/83248930-18be7700-a1a6-11ea-9bb6-1e5d3a0048a4.png)

![image](https://user-images.githubusercontent.com/11352551/83248952-2542cf80-a1a6-11ea-84af-a078584227af.png)

**To Reproduce**
1. open a stopped server and click start
2. Start the Server and keep the Console open
3. See multiple Server markes as running messages

**Expected behavior**
The message only show once when the server started,

**Comment by fabm3n** [comment]
![image](https://user-images.githubusercontent.com/11352551/83263383-ce95bf80-a1be-11ea-84b1-6a2e32a9cdeb.png)
After some hours

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/wings/pull/32

**Comment by fabm3n** [comment]
Issue still exists:
![image](https://user-images.githubusercontent.com/11352551/83360718-c044d080-a383-11ea-953d-a5f3e51a832a.png)

**Comment by fabm3n** [comment]
I also had this issue today at a Server which was running before i opened the Console
