### ISSUE TITLE
Servers should be able to default to oom-killer enabled

### ISSUE THREAD

**Issue by iamkubi** [pterodactyl/panel#2079]
Some virtualizations (Parallels and OpenVZ based on users I've talked to) will fail to start a container if oom-killer is disabled.  When creating a new server this defaults to `off`, but for systems where `on` is the only valid option it would be useful to make the default value a system-wide setting.

**Comment by iamkubi** [comment]
The guy I just talked to had this on KVM, so I don't know what these people have in common.

**Comment by DaneEveritt** [comment]
If someone wants to PR something for this, they can, but there is a reason I don't support OpenVZ systems.

**Comment by iamkubi** [comment]
Wouldn't this be a panel thing?  I was imagining having a node setting that changes the default value of the radio button on the create server page.  I wouldn't think anything needs to be done in the daemon, unless the Go daemon doesn't currently support the oom-killer setting.

**Comment by DaneEveritt** [comment]
It is available per-server in the panel, I don't see any reason to make it per-node which only adds complexity to try and support an already unsupported system.

**Comment by DaneEveritt** [comment]
Actually, on that note, I'm just going to close this out since it is easy enough to toggle it on each server.

**Comment by SmartHosting** [comment]
sorry but I have the same question even tho it's easy enough not with whmcs my boy

**Comment by 57-Wolve** [comment]
@iamkubi I was able to fix our issue today by changing the oom_disable from true to false on server creation in [app/Services/Servers/ServerCreationService.php](https://github.com/pterodactyl/panel/blob/1260965dfdc162e9a8507d148467e2ec3f2f3ae2/app/Services/Servers/ServerCreationService.php#L228) line #228. This allowed us to create docker containers again as it was by default being disabled on container creation in the panel.

```
`INFO: [Aug 13 22:35:56.318] beginning installation process for server server=0cc279e4-1bdd-405b-84ec-09f20db0be83
INFO: [Aug 13 22:36:00.803] creating install container for server process install_script=/tmp/pterodactyl/0cc279e4-1bdd-405b-84ec-09f20db0be83/install.sh server=0cc279e4-1bdd-405b-84ec-09f20db0be83
INFO: [Aug 13 22:36:01.350] running installation script for server in container container_id=71ac1596a5513121c70020c7e5ab14c0d63e6a78433cd0b4a17143f55fcd9870 server=0cc279e4-1bdd-405b-84ec-09f20db0be83
ERROR: [Aug 13 22:36:01.654] failed to run install process for server error=Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: failed to write "1": write /sys/fs/cgroup/memory/docker/71ac1596a5513121c70020c7e5ab14c0d63e6a78433cd0b4a17143f55fcd9870/memory.oom_control: permission denied: unknown server=0cc279e4-1bdd-405b-84ec-09f20db0be83

Stacktrace:
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: failed to write "1": write /sys/fs/cgroup/memory/docker/71ac1596a5513121c70020c7e5ab14c0d63e6a78433cd0b4a17143f55fcd9870/memory.oom_control: permission denied: unknown`
```

Our platform uses Virtuozzo 7 (OpenVZ/Parallels)

I'll probably add support to disable or enable OOM for a whole node rather than each game server if I have the time.
