### ISSUE TITLE
Service name set as VAR name when adding a new var.

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#208]
Dunno if it's just on display or if the bug is real but whenever i add a new VAR to a service option, it keeps the var name as service name and same for description

**Comment by DaneEveritt** [comment]
I'm not able to reproduce this, can you walk me through what you did, and what you entered?

**Comment by jffz** [comment]
Looks like it is only a graphical bug as it's what is displayed but not registered.

Create a new service, configure it to your needs, create 1 VAR, then another, validate and you'll see the cvar name as service name on the current page.
