### ISSUE TITLE
Panel v0.7.17: Downloaded file name skipped after space character

### ISSUE THREAD

**Issue by ChrisG661** [pterodactyl/panel#2080]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.17
* Server's OS: Ubuntu 18.04 LTS
* Your Computer's OS & Browser: Windows 10 & Firefox

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `PHP 7.2.31-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 14 2020 08:27:35) ( NTS )                                   Copyright (c) 1997-2018 The PHP Group                                                                                   Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies                                                               with Zend OPcache v7.2.31-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies `

**To Reproduce**
1. Go to File management in Server Management
2.  Download a file containing space after the first characters
3.  Downloaded file name skipped after space character, eg. `THIS FILE.extension` became `THIS` after download
4. No error shown

**Expected behavior**
Downloaded file name is `THIS FILE.extension`

**Comment by DaneEveritt** [comment]
Thanks for the report, however I won't be fixing this as it is a minor issue and I'm devoting all of my resources towards the current beta.
