### ISSUE TITLE
Create API endpoint for handling server subusers

### ISSUE THREAD

**Issue by Kintull** [pterodactyl/panel#2082]
**Is your feature request related to a problem? Please describe.**
There is not way to add/edit/delete a subuser for a given server using API.

**Describe the solution you'd like**
Implement endpoint `api/application/servers/<internal-id>/subusers` with default CRUD HTTP methods.

**Describe alternatives you've considered**
Update database `subusers` and `permissions` tables programmatically.

**Comment by DaneEveritt** [comment]
This actually already exists in the beta releases. :)
