### ISSUE TITLE
PHP 7.4 mail not supported despite being mentionned in community guide

### ISSUE THREAD

**Issue by christofkaelin** [pterodactyl/panel#2083]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.17
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Windows 10 & Chrome

**Describe the bug**
Pterodactyl throws exception `production.ERROR: ErrorException: Trying to access array offset on value of type null in /var/www/pterodactyl/vendor/egulias/email-validator/EmailValidator/Parser/Parser.php:147` when PHP version is **7.4** (mine is actually 7.4.3). This seems to be a laraval related issue as explained here: https://github.com/laravel/framework/issues/30737

**To Reproduce**
1. Install the requirements for Ubuntu 20.04 as described [here](https://pterodactyl.io/community/installation-guides/panel/ubuntu2004.html#install-requirements).<br/>**Note: I'm aware of the fact that this is a community guide and pterodactyl officially recommends PHP 7.2** It's still misleading seeing this on a community guide though.
2. Proceed with the pterodactyl installation
3. Setup mail settings `php artisan p:environment:mail`. In my case SMTP with SSL.
4. Try to send a test mail in the panel or use the _forgot password_ feature
5. See the error (https://pastebin.com/ZhEmBvdH) in the logs.

**Expected behavior**
No exception when trying to send e-mail or correction of the guide.

**Comment by matthewpi** [comment]
https://github.com/laravel/framework/issues/30737#issuecomment-561140398

Laravel 5.7 (which 0.7 is using) doesn't "support" PHP 7.4, while most features might work, it is recommended you stick to the versions that are supported.  Also as this is not a major issue, development is being focused on 1.0 meaning this won't be fixed in 0.7.

**Comment by DaneEveritt** [comment]
Someone just needs to open a PR against https://pterodactyl.io/community/installation-guides/panel/ubuntu2004.html#php to change that to 7.3

**Comment by Sir3lit** [comment]
@parkervcp made that guide?

**Comment by parkervcp** [comment]
I mean I did. I didn't test emails. Didn't know it was a problem.

**Comment by Sir3lit** [comment]
One known solution is to edit the composer file and set the requirements PHP 7.4 instead of 7.2 run the update command and some people  have said it worked, I haven't found anybody that says it doesn't work
