### ISSUE TITLE
The Daemon does not write quotes

### ISSUE THREAD

**Issue by Kew1e** [pterodactyl/panel#2086]
* Daemon: 
* 0.6 
* Ubuntu 18.04
* Windows, Chrome
* php v7.2.24-0ubuntu0.18.04.6

When I try to start the server through wine, I need to run this command (xvfb-run --auto-servernum --server-args='-screen 0 640x480x24:32' wine Unturned.exe -nographics -batchmode -silent-crashes +secureserver/unturned), but in turn, the daemon sends it without quotes

I tried and " and '
But daemon send: https://prnt.sc/ss9cv2

**Comment by DaneEveritt** [comment]
Well, then gonna tag this won't fix because I really just don't have the time to even begin looking into that.
