### ISSUE TITLE
Invalid values in admin edit server throws a http 500

### ISSUE THREAD

**Issue by fabm3n** [pterodactyl/panel#2087]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: beta 4
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Win 10 Pro 1909 & Chrome 83
* php: php 7,4
**Describe the bug**
If i edit the build configuration of a server and set the Disk Space to a negative the page throws a http 500
https://bin.ptdl.co/etkef/

**To Reproduce**
1. Edit a Server
2. Set a invalid value
3. Save

**Expected behavior**
A Error message should appear

**Comment by fabm3n** [comment]
Ok it's a general issue with unvalid values in the edit server view

**Comment by DaneEveritt** [comment]
```
[2020-06-23 20:15:11] local.ERROR: Pterodactyl\Exceptions\Model\DataValidationException: Data integrity exception encountered while performing database write operation. {"disk":["The disk must be at least 0."]} in /srv/www/app/Repositories/Eloquent/EloquentRepository.php:173
Stack trace:
#0 /srv/www/app/Services/Servers/BuildModificationService.php(106): Pterodactyl\Repositories\Eloquent\EloquentRepository->update()
#1 /srv/www/app/Http/Controllers/Admin/ServersController.php(264): Pterodactyl\Services\Servers\BuildModificationService->handle()
#2 [internal function]: Pterodactyl\Http\Controllers\Admin\ServersController->updateBuild()
#3 /srv/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#4 /srv/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#5 /srv/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch()
```

**Comment by DaneEveritt** [comment]
Clarified what values are allowed and made the exception not break the page but transform back into a normal validation exception since I'm not doing any data validation on the request before trying to store it in the DB.
