### ISSUE TITLE
Feature Request: User's associated subuser

### ISSUE THREAD

**Issue by necrogami** [Pterodactyl/Panel#209]
You have a section for a user's associated servers how about a users associated subuser?

Eg associated to servers x and y
associated subuser for z

**Comment by DaneEveritt** [comment]
I'm not sure I quite understand what you're looking for here.

Are you asking for the Admin CP to list all servers a user has access to, even if they aren't the owner (when listing a user)?

**Comment by necrogami** [comment]
https://puu.sh/sQBeF/e935f87744.png
This user is a subuser of a number of servers. But when i go into his account on the admin side (Fide Account) His associated server is blank.

I'd like to add to that section for where a user is a subuser of a server. So maybe where the active column is add another for Owner/Subuser

**Comment by DaneEveritt** [comment]
I'll mark this as an enhancement for `0.6.0`. 👍
