### ISSUE TITLE
::: Beta Relese ::: CTRL + S Does not save in the file editor.

### ISSUE THREAD

**Issue by DomiiBunn** [pterodactyl/panel#2092]
When attempting to save a file in the file editor using the common shortcut `Control/Command + S` There is no save action, It would be a nice feature since the 0.7 panel had it. 

An alternative action is to hit the save button, This whoever requires the user to move their hands off the keyboard and is inconvenient

**Comment by FoksVHox** [comment]
Use the bug template when reporting bugs.

**Comment by DomiiBunn** [comment]
I did. That's all the needed info for the bug. Why would I keep the filler and guideline text?😉

**Comment by FoksVHox** [comment]
No, you didn't you're missing quite a few things that are needed for actually fixing this issue.

* Panel or Daemon: 
* Version of Panel/Daemon: 
* Server's OS: 
* Your Computer's OS & Browser: 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Comment by DomiiBunn** [comment]
It is clearly the panel. Since it is a future request it's not gonna be the 0.7 ver so probs 1.0.
There is no way to reproduce since the feature does not exist yet.
Server os isn't a part of a client side feature. 
It doesn't work on any os since it's literally not in the code

**Comment by FoksVHox** [comment]
So you should still use the template.. https://github.com/pterodactyl/panel/issues/new?template=---feature-request.md

**Comment by JanDevDE** [comment]
@FoksVHox This is not a bug, it's a feature request. Please don't backseat moderate GitHub issues.

**Comment by DaneEveritt** [comment]
@DomiiBunn can you please edit the main report to indicate that this is with the beta panel, its not immediately clear at first glance. :)

**Comment by DomiiBunn** [comment]
Sure!
