### ISSUE TITLE
wrong cpu ussage

### ISSUE THREAD

**Issue by Oberfail** [pterodactyl/panel#2095]
**Panel or Daemon:** Panel
**Version of Panel/Daemon:** 0.7.17 / 1,0 beta 4
**Server's OS:** Debian 10
**Your Computer's OS & Browser:** Windows 10 LTSC, Firefox 77.0.1 64bit

**Describe the bug**
The Panel is showing a higher cpu ussage than its beeing possible.
![grafik](https://user-images.githubusercontent.com/22199792/83903739-f062e980-a75e-11ea-81f0-bdf086a5bfb3.png)
The Panel is running on a 1 shared core VPS from Netcup. 
This also happens on both Panel 0.7 aswell as 1.0 beta

**To Reproduce**
1. Get a Netcup VPS
2. Install the Panel & Daemon on it
3. start anything cpu heavy

**Expected behavior**
The cpu ussage beeing accurate.

I currently have a non-production vps on which i can try out anything, even if the system might break.

**Comment by DaneEveritt** [comment]
Won't fix in 0.7, we've already overhauled that logic in the new versions. Thanks for the report though.
