### ISSUE TITLE
how can i setup a second node and configure it in my ubuntu 18.04 vps

### ISSUE THREAD

**Issue by MCTTV06** [pterodactyl/panel#2096]

**Comment by MCTTV06** [comment]
I have my first node running and all

**Comment by Oberfail** [comment]
https://pterodactyl.io/daemon/0.6/installing.html
# Configure Daemon

**Comment by MCTTV06** [comment]
Yes i understand that but how do I put the configuration on the core.json
with my other node on it

**Comment by FoksVHox** [comment]
@MCTTV06 you should use the Pterodactyl Discord for support in terms of configuring and setting it up. The GitHub issues are for bugs, feature requests, and that sort of thing.
