### ISSUE TITLE
CPU Limit not working

### ISSUE THREAD

**Issue by Cyanoure** [pterodactyl/panel#2097]
Daemon version: 0.6.3
Panel version: 0.7.17
Server OS: Debian 10.4 (Contabo VPS)

**Describe the bug**
CPU limit is not working. I set the cpu limit to 100%, but when I start the minecraft server, cpu usage goes above 100%, and uses all of the cores.

`uname -a`:

> Linux <my server's domain> 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux

`docker info`:

> Client:
>  Debug Mode: false
> 
> Server:
>  Containers: 16
>   Running: 6
>   Paused: 0
>   Stopped: 10
>  Images: 27
>  Server Version: 19.03.11
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk s                                                                                                                                                             yslog
>  Swarm: inactive
>  Runtimes: runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
>  runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
>  init version: fec3683
>  Security Options:
>   apparmor
>   seccomp
>    Profile: default
>  Kernel Version: 4.19.0-9-amd64
>  Operating System: Debian GNU/Linux 10 (buster)
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 4
>  Total Memory: 7.791GiB
>  Name: <my server's domain>
>  ID: HNT2:2MJ2:HXEG:UV5A:LMC2:5YTV:D5SB:6V3Z:YJUJ:MGJZ:J7K2:ISYG
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false

**Comment by Games4k** [comment]
I’m pretty sure it does not. You’re probably doing something wrong.

**Comment by Cyanoure** [comment]
What could be the problem?

**Comment by Games4k** [comment]
How much above? It should usually be about a 10% difference.

**Comment by Games4k** [comment]
Also, maybe you should consider getting help from discord

**Comment by Cyanoure** [comment]
'How much above?'
With 200% limit, it goes up to 120-130% as I see.
With 100% limit 105-110%.
Is it ok?
I remember it was more when I installed Pterodactyl months ago. :'D

**Comment by DaneEveritt** [comment]
A 200% limit going up to 130% is not a bug. A 100% limit going up to 105/110 is also not a bug, and is likely just calculation differences between the tooling you're using.

**Comment by brahmtej2009** [comment]
Hi
If you are using an Ubuntu VPS,
This is caused when your VPS Supplier Limits your resources (Usually when ur system is overloaded for more than 6 hours or so)
You gotta reinstall your vps to fix this..
