### ISSUE TITLE
Limit slots

### ISSUE THREAD

**Issue by Games4k** [pterodactyl/panel#2099]
**Describe the solution you'd like**
It would be great to see slots limitation on Pterodactyl (at least for popular games like Minecraft, CS, SAMP, and possibly GTA V). It would be incredibly useful for hosting companies, and I’m sure planty of users would really appreciate this feature being added.

**Comment by Sir3lit** [comment]
Iirc that is supported? You just make a variable for it and use it in the startup command line or have it in in the config.

**Comment by parkervcp** [comment]
This can already be handled in the eggs with variables and config settings.
