### ISSUE TITLE
Multiple search boxes within admin area not working

### ISSUE THREAD

**Issue by Games4k** [pterodactyl/panel#2100]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-b4
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Safari, MacOS Catalina

**Describe the issue**
When searching for users on the server creation page, instead of showing user I’m looking for, it displays all the user accounts.

**To Reproduce**
1. Enter server creation page (or server listing page)
2. Search for specific user (or specific server)

**Expected behavior**
I expect user that I searched for to be shown, not all of the accounts.

**Comment by Sir3lit** [comment]
Can confirm this is a bug, it returns all users.

**Comment by Games4k** [comment]
It should return user I was searching for....

**Comment by matthewpi** [comment]
Probably related to #2107

**Comment by Sir3lit** [comment]
Should be noted this issue has re-appeared as of Panel Beta 7. 

Front end search always returns nothing in its list.
The server creator still shows all users and not users matching what you've searched for.

**Comment by SpirTBBX** [comment]
All users still showing up in 1.0.0-rc3

**Comment by DaneEveritt** [comment]
Yes, that is why this issue is still open. 🙂
