### ISSUE TITLE
Upload complete folder structures via WebFTP

### ISSUE THREAD

**Issue by DAThosting** [pterodactyl/panel#2103]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when uploading worlds for minecraft, cause this is not possible with the WebFTP.

**Describe the solution you'd like**
Allow uploading of whole directories.

**Comment by DAThosting** [comment]
https://github.com/pterodactyl/panel/issues/599

This is not a solution...

**Comment by mayed505** [comment]
The panel uses WebSockets to communicate with the daemon.
Pterodactyl utilizes socket-file-upload to upload files but that doesn't support folders. Like #599 states, that will probably never be added. SFTP is already much faster and convenient.

**Comment by DAThosting** [comment]
That's very annoying...
A solution would be using monstaftp which supports sftp.
https://monstaftp.com

**Comment by parkervcp** [comment]
Upload a zip and unpack it.

The other answer is still valid as Dane said no it's probably never happening.
