### ISSUE TITLE
Panel unresponsive when one of the nodes is offline

### ISSUE THREAD

**Issue by VibeGAMESNL** [pterodactyl/panel#2104]
**Background (please complete the following information):**
* Panel or Daemon: 0.7.17 
* Version of Panel/Daemon: 0.6.13
* Server's OS: Ubuntu 18, Ubuntu 20
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
When you have multiple nodes and one of them is offline because someting like a DDoS attack, other users that have a server on another node can't use the panel. The panel becomes unresponsive for all users. The panel is running standalone.

**To Reproduce**
1. add 2 nodes to pterodactyl
2. Create 2 servers on each node.
3. DDoS 1 of the nodes xD
4. Try to use the panel for a users on the node that is online.

**Expected behavior**
Panel will load endless and then give a timeout or 503 gateway error.

**Comment by parkervcp** [comment]
Your browser is trying to reach all the nodes that you have configured. It needs to wait for the single node to time out.

**Comment by DaneEveritt** [comment]
This bug report does not provide a succicient enough example of what specifically is not working. "The panel is unresponsive" is not exactly a detailed explanation, and there are thousands of other users who have yet to report this issue (including a multitude of hosts).

So either there is a weird configuration on your end, or it is simply something that has always worked that way which is being mistaken for a bug.

Additional clarification would be great, and I will reopen this issue once that information is provided and we can determine if it is a bug or not.
