### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by Games4k** [pterodactyl/panel#2107]
**Background (please complete the following information):**
Panel or Daemon: Panel
Version of Panel/Daemon: 1.0.0-beta4
Server's OS: Ubuntu 18.04 Bionic
Your Computer's OS & Browser: MacOS Mojave Safari

**Describe the bug**
The server search not working. It always displays a random server instead of the one I'm searching for.

**To Reproduce**
Open up your search panel and type in the name of a server.

![Screen Shot 2020-06-10 at 10 31 59 PM](https://user-images.githubusercontent.com/29690431/84315674-4b834a80-ab6a-11ea-9bac-84b75e71a490.png)

**Comment by matthewpi** [comment]
🙃  https://github.com/pterodactyl/panel/commit/5b4a65a60c5b523c27a994b552d491f6f99d7c46

**Comment by DaneEveritt** [comment]
Closing, related to #2100
