### ISSUE TITLE
::: Beta Relese :::  Expected response code 220 but got an empty response

### ISSUE THREAD

**Issue by DomiiBunn** [pterodactyl/panel#2109]
## Background
Panel `1.0 Beta`
Server's OS `Ubuntu 18.04`
Php Info
```bash
php-common/bionic,now 2:76+ubuntu18.04.1+deb.sury.org+9 all [installed,automatic]
php7.4/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 all [installed]
php7.4-bcmath/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
php7.4-cli/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
php7.4-common/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
php7.4-curl/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
php7.4-fpm/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
php7.4-gd/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
php7.4-json/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php7.4-mbstring/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
php7.4-mysql/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
php7.4-opcache/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php7.4-readline/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php7.4-xml/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
php7.4-zip/bionic,now 7.4.6-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed]
```
MariaDB version `Server version: 10.4.13-MariaDB-1:10.4.13+maria~bionic-log mariadb.org binary distribution
`

## Bug Description
During the 1st installation process while [Creating a new user](https://pterodactyl.io/panel/1.0/getting_started.html#add-the-first-user) Console logs
```bash
root@domi:/var/www/pterodactyl# php artisan p:user:make

 Is this user an administrator? (yes/no) [no]:
 > yes

 Email Address:
 > domi@imagine.team

 Username:
 > domi

 First Name:
 > domi

 Last Name:
 > domi

Passwords must be at least 8 characters in length and contain at least one capital letter and number.
If you would like to create an account with a random password emailed to the user, re-run this command (CTRL+C) and pass the `--no-password` flag.

 Password:
 >


In AbstractSmtpTransport.php line 445:

  Expected response code 220 but got an empty response
```
All other steps are completed as in the documentation, The user does get created. Full stack trace can be found [here](https://ptero.co/abixuzovoj.sql)

## Reproduction steps
Create the 1st user using the artisan cli. 

## Expected Behavior
No error is returned to the user.

## Some thoughts
It's the 1st time I see the bug and It would be at least the 5th time I am installing the beta on the exact same VM, no variables have really changed to cause the error so I am quiet unsure. I do have a snapshot of the vm if someone wants to poke at it.

**Comment by parkervcp** [comment]
You have any logs for this error?

**Comment by DomiiBunn** [comment]
> You have any logs for this error?

Yep I linked the hastebin log. I didn't make it quiet clear enough I think https://ptero.co/abixuzovoj.sql

**Comment by parkervcp** [comment]
It looks like your DB didn't set up properly.

**Comment by DomiiBunn** [comment]
I did see that at 1st but it did create the user properly.

**Comment by DaneEveritt** [comment]
That is an error from whatever you're using to send emails, not Pterodactyl specifically.
