### ISSUE TITLE
Server status issues and console not updating unless I refresh the page (Panel 1.0)

### ISSUE THREAD

**Issue by andrewfer000** [pterodactyl/panel#2110]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0 & 1.0 
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Ubuntu 20.04 LTS & Firefox (Latest) 

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: I am using PHP 7.4 with Apache, nothing special about my configuation besides the web-server running behind HAProxy in http mode.

**To Reproduce**
1. Login to panel
2. click on server from the list
3. type the command pl into the console
4. nothing happens
5. refresh the page and see that the pl command was run.
Also, The server stats, start, stop, and restart buttons have issues, the server will sometimes say its offline using no resources when its obviously online. On server list, the stats work normally.

**Expected behavior**
The expected behavior is that the console will work like in 0.7 and the server stats will be working normally. No refreshes required.

![ptero-problem](https://user-images.githubusercontent.com/9620913/84473811-b199cb80-ac57-11ea-91c7-25d1d19c4d74.png)

**Comment by andrewfer000** [comment]
Tested on chrome. Same issue

**Comment by fabm3n** [comment]
Can you check your Browser Console and your Panel / Wings Logs?

There aren't stats because the Server is marked as offline.

**Comment by andrewfer000** [comment]
Where are the logs at again?

**Comment by andrewfer000** [comment]
I just switched to the older panels and have no issues. So I cannot work on this issue anymore. When the next beta comes out I'll give it a shot.

**Comment by Sir3lit** [comment]
This is a WebSocket issue, and iirc it was already addressed and a fix was put in place but has not been released yet.
