### ISSUE TITLE
ARM architecture support?

### ISSUE THREAD

**Issue by FarmVivi** [pterodactyl/panel#2111]
* Panel or Daemon: Deamon
* Version of Panel/Daemon: Panel: v1.0.0 Beta Release 4 / Deamon: v1.0.0 Beta Release 5
* Server's OS: Raspberry Pi OS (Raspbian)
* Your Computer's OS & Browser: Windows 10 (with Chrome)

Panel:
- 'php -v': `PHP 7.4.6 (cli) (built: May 14 2020 10:03:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies`

Daemon:
- 'uname -a': 'Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux'
- 'sudo docker info': 'Client:
 Debug Mode: false
Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.118-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 3.814GiB
 Name: raspberrypi
 ID: KXUS:7VG6:4LVC:MQSJ:CISL:DLVT:FSKR:JL4Z:PNN2:I3AA:GHAX:RQCO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support'

I am trying to install the daemon beta on a raspberrypi 4 B (4G RAM) with Raspberry Pi OS (Raspbian), I followed the installation documentation but I have a problem when executing the command 
'sudo wings': '/usr/local/bin/wings: 1: /usr/local/bin/wings:ELF: not found
@.@.▒▒?▒E▒h=▒▒ڊ̓▒N▒7▒%M/Uњi▒▒1▒▒▒▒▒▒▒▒ܲ▒▒]P: Directory nonexistent!▒
/usr/local/bin/wings: 2: /usr/local/bin/wings: Qㆺ▒w3: not found
/usr/local/bin/wings: 2: /usr/local/bin/wings: ▒: not found
/usr/local/bin/wings: 3: /usr/local/bin/wings: Syntax error: ")" unexpected'
then when I make the command
'ls': '''$'\001\270''z'$'\225''@@8'$'\003''@'$'\001\005''@@L'$'\215''UL'$'\215''U'$'\020\001\006\220\225\220\225''8?'$'\334\020''Q'$'\345''td'$'\006\b\004''
it creates a weird file which is impossible to delete (file created corrupted?) to delete it I am obliged to delete the folder in which I made the 'sudo wings' command. I think the problem is that wings does not support the ARM architecture. Is that right? If yes, could you make wings compatible with the ARM architecture?

**Comment by parkervcp** [comment]
The wings binary is compiled for amd64 and not for arm. That is the only supported linux version for us.

**Comment by FarmVivi** [comment]
It seems that everything works I have compiled wings replacing "amd64" by "arm" in the Makefile file. I replaced "GOOS = linux GOARCH = amd64 go build -ldflags =" - s -w "-gcflags" all = -trimpath = / Users / dane / Sites / development / code "-o build / wings_linux_amd64 -v wings. go "by" GOOS = linux GOARCH = arm go build -ldflags = "- s -w" -gcflags "all = -trimpath = / Users / dane / Sites / development / code" -o build / wings_linux_arm -v wings.go "

**Comment by parkervcp** [comment]
My concern is the majority game servers won't support arm.

**Comment by DaneEveritt** [comment]
I mean I doubt we do much of anything specifically _within_ the wings code that would make arm architectures unsupported (plus its easy enough in go to change out bits and pieces as needed for arm). 

Won't we have a lot of trouble with all of the docker images and such though? I honestly haven't poked around that space in ages so I'm kinda behind.

**Comment by schrej** [comment]
Yes, you need custom images for arm. Containers don't abstract away the host architecture.

Not sure how it would be with Katacontainers as a runtime, but the performance would probably be pretty shitty.

Wings should run fine on any architecture though, or at least be easy to adapt.

**Comment by Greaper88** [comment]
I personally would like ARM support because I want to use a RPi dedicated to being my controller (panel only) for my other backend servers.

**Comment by matthewpi** [comment]
> I personally would like ARM support because I want to use a RPi dedicated to being my controller (panel only) for my other backend servers.

That should already be possible, this issue was specifically referring to the daemon (wings) not being built for arm.

**Comment by Greaper88** [comment]
> > I personally would like ARM support because I want to use a RPi dedicated to being my controller (panel only) for my other backend servers.
> 
> That should already be possible, this issue was specifically referring to the daemon (wings) not being built for arm.

Ah ok. Do you have to compile, or just run the usual install?

**Comment by matthewpi** [comment]
> > > I personally would like ARM support because I want to use a RPi dedicated to being my controller (panel only) for my other backend servers.
> 
> > 
> 
> > That should already be possible, this issue was specifically referring to the daemon (wings) not being built for arm.
> 
> 
> 
> Ah ok. Do you have to compile, or just run the usual install?

For the panel the regular install should work.  For wings you just need to get the arm executable (instead of amd64).

**Comment by MegaTKC** [comment]
> My concern is the majority game servers won't support arm.

Hello, I am sorry for responding to a topic that is over 1 year but, won't this command make wings work on arm devices?

Add i386 to your device
`sudo dpkg --add-architecture i386`

Add amd64 to your device
`sudo dpkg --add-architecture amd64`

**Comment by parkervcp** [comment]
> > My concern is the majority game servers won't support arm.
> 
> Hello, I am sorry for responding to a topic that is over 1 year but, won't this command make wings work on arm devices?
> 
> Add i386 to your device
> `sudo dpkg --add-architecture i386`
> 
> Add amd64 to your device
> `sudo dpkg --add-architecture amd64`

no. these packages don't magically make arm support other architectures.

**Comment by ArtichautDev** [comment]
wings is supported on arm : https://github.com/ArtichautLearnCode/PterodactylArmInstalationGuide

**Comment by parkervcp** [comment]
> 
> 
> wings is supported on arm : https://github.com/ArtichautLearnCode/PterodactylArmInstalationGuide

This is for the panel...

**Comment by Bluscream** [comment]
> > wings is supported on arm : https://github.com/ArtichautLearnCode/PterodactylArmInstalationGuide
> 
> This is for the panel...

https://github.com/ArtichautDev/PterodactylArmInstalationGuide#install-wings

**Comment by aadi2206** [comment]
I've Tried it, Given Script `https://github.com/ArtichautLearnCode/PterodactylArmInstalationGuide` Is Used to Install Wings Which is Now Officially Provided by Pterodactyl Itself: https://github.com/pterodactyl/wings/releases/download/v1.11.13/wings_linux_arm64 Also, You can install Panel as Normal Way, I've prepared a Script for Installing Panel & Wings on ARM Servers.
