### ISSUE TITLE
Bring back upload through web file manager

### ISSUE THREAD

**Issue by Games4k** [pterodactyl/panel#2112]
**Describe the solution you'd like**
I would like a feature to allow us, like before, to drag and drop and upload files to the file manager through the browser, instead of forcing the use of SFTP, as some users prefer to use browser file manager instead.

**Comment by matthewpi** [comment]
Web file uploads are still planned to be added, they weren't removed, they just haven't been added yet.

**Comment by parkervcp** [comment]
I assume this is a panel 1.0 issue but will close this as oyu gave us no information on it. 

If you do fill out that information feel free to re-open.

**Comment by Games4k** [comment]
Ummm... I'm not sure what are you talking about and why did you close it. This is not an issue, this is a **FEATURE REQUEST**. What information do you need? Of course, if someone is opening feature requests, they are all about 1.0.0... @DaneEveritt could you please take a look? :)

**Comment by DaneEveritt** [comment]
You don't need to drag me into this, you were asked to fill out the template, same as we ask of everyone, and the same template you've made a point of raking people over the coals for not filling out in other issues so recently.

Plus, this doesn't need a feature request, I'm fully aware that _already existing_ feature is not exposed in the 1.0 UI. :+1:
