### ISSUE TITLE
::: Beta ::: Power Status

### ISSUE THREAD

**Issue by DomiiBunn** [pterodactyl/panel#2116]
### Problem
Not enough information on the index page/too obfuscated

### Solution
Set a color to the `Ethernet` Icon depending on the server status

* Green - Server Online
* Yellow - Server starting/shutting down
* Gray - Server Offline
* Red - Server crashed/suspended

### Alternatives
Seeing the servers cpu usage or looking at the server page

![](https://i.imgur.com/fXLGcIn.jpg)

**Comment by DomiiBunn** [comment]
Maybe while at that do the same for CPU/RAM/Disk with a % calcumation?

**Comment by DaneEveritt** [comment]
Won't implement, CPU/RAM/Disk already turn red once over 85%. Excessive colors goes against the design principals of this new version and don't really communicate the information any better than just looking at the number since they are often determined arbitrarily by the developer, and not by the user looking at the values.

**Comment by ghost** [comment]
@DomiiBunn In wich file i can do this, this looks nice.

**Comment by DomiiBunn** [comment]
Something really similar is already implemented. As seen by Dane acutally closing the issue as complete on Jun 13th

![image](https://user-images.githubusercontent.com/51760394/177191203-03299725-2752-4909-90e4-304b94e42fb4.png)

**Comment by ghost** [comment]
yeah but i like to make it purple for my webinterface.

**Comment by DaneEveritt** [comment]
Please do not use old issues for support with custom modifications — it notifies everyone in the organization and is quite annoying when there is no issue at hand. You're welcome to use Discord for additional help, we have entire channels setup specifically for this type of stuff.
