### ISSUE TITLE
[Question] Getting a file

### ISSUE THREAD

**Issue by TheSilentPro** [pterodactyl/panel#2119]
Considering the discord is a mess, i'll ask here:
How would i go on about getting a file? (Client API)

i saw this but i don't know the full endpoint to fetch it https://github.com/Pterodactyl/Panel/issues/586

**Comment by DomiiBunn** [comment]
Hoi there. I would not know for certain whoever [here](https://dashflo.net/docs/api/pterodactyl/v1/) are the (Unofficial API docs) I don't believe it is possible.

**Comment by DomiiBunn** [comment]
I was wrong. Here is the code
```bash
curl --request GET \
  --url https://pterodactyl.file.properties/api/client/servers/1a7ce997/files/contents \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'Authorization: Bearer wwQ5DJ6X1XaFznQSYRWCQKl0sCpoAJobLw6EsSCUnfIdB0Xh' 
```

**Comment by TheSilentPro** [comment]
What would pterodactyl.file.properties be?
just the panel link?
