### ISSUE TITLE
Login email field appears to be case sensitive.

### ISSUE THREAD

**Issue by DomiiBunn** [pterodactyl/panel#2120]
### Background 
* Panel: `canary`
* Your Computer's OS: `Windows 10`
* Browser: `Chrome`

### Bug Description
Login email filed is case sensitive. 

### Reproduction Steps

1. Create a user with an email eg. `TeSt@domain`
2. Attempt to login using `test@domain` Login fails

**Expected behavior**
User email is not case sensitive allowing the user to login

**Comment by matthewpi** [comment]
Cannot reproduce on https://github.com/pterodactyl/panel/commit/364b645b8128759d3652c79e4aba9cf204a79359, doubt anything was changed for authentication recently either.

**Comment by DaneEveritt** [comment]
Also unable to reproduce.
