### ISSUE TITLE
wings ARM wings server creation error

### ISSUE THREAD

**Issue by FarmVivi** [pterodactyl/panel#2122]
* Panel or Daemon: daemon
* Version of Panel/Daemon: latest
* Server's OS: Raspbian (10 buster)
* Your Computer's OS & Browser: Windows 10 / Chrome

I built wings for ARM architecture, it works but when I create a server an issue append:
` sudo wings

                     ____
__ Pterodactyl _____/___/_______ _______ ______
\_____\    \/\/    /   /       /  __   /   ___/
   \___\          /   /   /   /  /_/  /___   /
        \___/\___/___/___/___/___    /______/
                            /_______/ v0.0.1

Website: https://pterodactyl.io
Source: https://github.com/pterodactyl/wings

Copyright © 2018 - 2020 Dane Everitt & Contributors

 INFO: [Jun 15 21:40:58.978] loading configuration from path path=/etc/pterodactyl/config.yml
DEBUG: [Jun 15 21:40:58.980] ensuring root data directory exists path=/var/lib/pterodactyl
DEBUG: [Jun 15 21:40:58.981] ensuring log directory exists path=/var/log/pterodactyl
DEBUG: [Jun 15 21:40:58.985] ensuring server data directory exists path=/var/lib/pterodactyl/volumes
DEBUG: [Jun 15 21:40:58.989] ensuring archive data directory exists path=/var/lib/pterodactyl/archives
DEBUG: [Jun 15 21:40:58.990] ensuring backup data directory exists path=/var/lib/pterodactyl/backups
 INFO: [Jun 15 21:40:58.991] checking for pterodactyl system user username=pterodactyl
 INFO: [Jun 15 21:40:58.995] configured system user successfully gid=994 uid=999 username=pterodactyl
 INFO: [Jun 15 21:40:58.999] beginning file permission setting on server data directories
 INFO: [Jun 15 21:40:59.003] finished ensuring file permissions
DEBUG: [Jun 15 21:40:59.004] making request to external HTTP endpoint endpoint=http://192.168.1.30/api/remote/servers headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[Bearer lDci2ohY(redacted)] Content-Type:[application/json]] method=GET
DEBUG: [Jun 15 21:40:59.927] saw server status change event server=53f89ffa-8d0e-43a9-8fd1-46e698488153 status=offline
DEBUG: [Jun 15 21:40:59.928] loaded server state from cache file server=53f89ffa-8d0e-43a9-8fd1-46e698488153 state=offline
 INFO: [Jun 15 21:40:59.935] loaded configuration for server server=53f89ffa-8d0e-43a9-8fd1-46e698488153
DEBUG: [Jun 15 21:40:59.946] saw server status change event server=53f89ffa-8d0e-43a9-8fd1-46e698488153 status=offline
 INFO: [Jun 15 21:40:59.946] ensuring server environment exists server=53f89ffa-8d0e-43a9-8fd1-46e698488153
 INFO: [Jun 15 21:40:59.946] ensuring server environment exists duration=1.481µs server=53f89ffa-8d0e-43a9-8fd1-46e698488153
 INFO: [Jun 15 21:40:59.948] configuring webserver...  host=0.0.0.0 port=8080 ssl=false
1.5922500599585397e+09  info    sftp    sftp-server@v1.1.2/server.go:122        sftp subsystem listening for connections        {"host": "0.0.0.0", "port": 2022}
DEBUG: [Jun 15 21:41:16.124] GET /api/servers/53f89ffa-8d0e-43a9-8fd1-46e698488153 client_ip=192.168.1.30 latency=373.022µs status=200
DEBUG: [Jun 15 21:41:38.952] saw server status change event server=53f89ffa-8d0e-43a9-8fd1-46e698488153 status=stopping
DEBUG: [Jun 15 21:41:38.983] DELETE /api/servers/53f89ffa-8d0e-43a9-8fd1-46e698488153 client_ip=192.168.1.30 latency=34.608612ms status=204
DEBUG: [Jun 15 21:41:44.619] OPTIONS /api/system client_ip=192.168.1.16 latency=2.52µs status=200
DEBUG: [Jun 15 21:41:44.624] GET /api/system client_ip=192.168.1.16 latency=487.699µs status=200
DEBUG: [Jun 15 21:42:09.009] making request to external HTTP endpoint endpoint=http://192.168.1.30/api/remote/servers/29b7e4ed-b18c-412e-9abf-80f0661a8a26 headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[Bearer lDci2ohY(redacted)] Content-Type:[application/json]] method=GET
 WARN: [Jun 15 21:42:09.128] failed to determine root server directory size error=invalid path resolution server=29b7e4ed-b18c-412e-9abf-80f0661a8a26

Stacktrace:
github.com/pterodactyl/wings/server.init
        /usr/local/bin/test/wings/server/filesystem.go:28
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5228
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5223
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5223
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5223

DEBUG: [Jun 15 21:42:09.129] POST /api/servers client_ip=192.168.1.30 latency=119.247589ms status=202
DEBUG: [Jun 15 21:42:09.130] creating required server data directory path=/var/lib/pterodactyl/volumes/29b7e4ed-b18c-412e-9abf-80f0661a8a26 process=installer server=29b7e4ed-b18c-412e-9abf-80f0661a8a26
DEBUG: [Jun 15 21:42:09.130] creating required environment for server instance process=installer server=29b7e4ed-b18c-412e-9abf-80f0661a8a26
DEBUG: [Jun 15 21:42:11.651] pulling docker image... this could take a bit of time image=quay.io/pterodactyl/core:java
 INFO: [Jun 15 21:42:12.075] successfully created environment for server during install process process=installer server=29b7e4ed-b18c-412e-9abf-80f0661a8a26
DEBUG: [Jun 15 21:42:12.075] making request to external HTTP endpoint endpoint=http://192.168.1.30/api/remote/servers/29b7e4ed-b18c-412e-9abf-80f0661a8a26/install headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[Bearer lDci2ohY(redacted)] Content-Type:[application/json]] method=GET
 INFO: [Jun 15 21:42:12.168] beginning installation process for server server=29b7e4ed-b18c-412e-9abf-80f0661a8a26
DEBUG: [Jun 15 21:42:14.290] {"status":"Pulling from library/alpine","id":"3.9"}
DEBUG: [Jun 15 21:42:15.005] {"status":"Digest: sha256:414e0518bb9228d35e4cd5165567fb91d26c6a214e9c95899e1e056fcd349011"}
DEBUG: [Jun 15 21:42:15.006] {"status":"Status: Image is up to date for alpine:3.9"}
 INFO: [Jun 15 21:42:15.007] creating install container for server process install_script=/tmp/pterodactyl/125909684/install.sh server=29b7e4ed-b18c-412e-9abf-80f0661a8a26
 INFO: [Jun 15 21:42:15.293] running installation script for server in container container_id=a982f22fcf02074ff28c872363c76698c1d03940db2ecea8a59f6a35537689e9 server=29b7e4ed-b18c-412e-9abf-80f0661a8a26
DEBUG: [Jun 15 21:42:54.901] GET /api/servers/53f89ffa-8d0e-43a9-8fd1-46e698488153/ws client_ip=192.168.1.16 latency=1m27.494210743s status=200
DEBUG: [Jun 15 21:43:53.884] pulling installation logs for server container_id=a982f22fcf02074ff28c872363c76698c1d03940db2ecea8a59f6a35537689e9 server=29b7e4ed-b18c-412e-9abf-80f0661a8a26
 INFO: [Jun 15 21:43:53.959] completed installation process for server server=29b7e4ed-b18c-412e-9abf-80f0661a8a26
DEBUG: [Jun 15 21:43:53.959] notifying panel of server install state server=29b7e4ed-b18c-412e-9abf-80f0661a8a26
DEBUG: [Jun 15 21:43:53.960] making request to external HTTP endpoint endpoint=http://192.168.1.30/api/remote/servers/29b7e4ed-b18c-412e-9abf-80f0661a8a26/install headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[Bearer lDci2ohY(redacted)] Content-Type:[application/json]] method=POST
DEBUG: [Jun 15 21:44:00.243] GET /api/servers/29b7e4ed-b18c-412e-9abf-80f0661a8a26/ws client_ip=192.168.1.16 latency=1m10.05093079s status=200
DEBUG: [Jun 15 21:44:02.018] saw server status change event server=29b7e4ed-b18c-412e-9abf-80f0661a8a26 status=starting
 INFO: [Jun 15 21:44:02.018] syncing server configuration with panel server=29b7e4ed-b18c-412e-9abf-80f0661a8a26
DEBUG: [Jun 15 21:44:02.019] making request to external HTTP endpoint endpoint=http://192.168.1.30/api/remote/servers/29b7e4ed-b18c-412e-9abf-80f0661a8a26 headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[Bearer lDci2ohY(redacted)] Content-Type:[application/json]] method=GET
DEBUG: [Jun 15 21:44:04.132] pulling docker image... this could take a bit of time image=quay.io/pterodactyl/core:java
DEBUG: [Jun 15 21:44:04.473] parsing server configuration file parser=yaml path=/var/lib/pterodactyl/volumes/29b7e4ed-b18c-412e-9abf-80f0661a8a26/config.yml
DEBUG: [Jun 15 21:44:06.155] saw server status change event server=29b7e4ed-b18c-412e-9abf-80f0661a8a26 status=stopping
DEBUG: [Jun 15 21:44:06.155] saw server status change event server=29b7e4ed-b18c-412e-9abf-80f0661a8a26 status=offline
ERROR: [Jun 15 21:44:06.155] failed to handle websocket process; an error was encountered processing an event error=Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"failed to write \\\\\\\"-1\\\\\\\" to \\\\\\\"/sys/fs/cgroup/cpu,cpuacct/docker/dbf6cab3d4f7ac7fd183fce60d5db35a98f56cd8ae8b9ccae003313a9e281ef9/cpu.cfs_quota_us\\\\\\\": open /sys/fs/cgroup/cpu,cpuacct/docker/dbf6cab3d4f7ac7fd183fce60d5db35a98f56cd8ae8b9ccae003313a9e281ef9/cpu.cfs_quota_us: permission denied\\\"\"": unknown error_identifier=5b533092-57fa-4c1c-be01-0c89c7eaed25 event=set state server=29b7e4ed-b18c-412e-9abf-80f0661a8a26

INVALID TRACER
`
after when I make docker ps command there is no container. May be a missing permission which "wings" user is using?

**Comment by parkervcp** [comment]
First: The image is trying to pull is amd 64. So it won't work there. You need to build custom images.

Second: does arm64 even support cgroups? You need to set the CPU limit to 0 or higher.

**Comment by DaneEveritt** [comment]
I'm closing this, `arm64` is explicitly not a supported architecture for this software at this time. I appreciate the effort, but I'd like to avoid polluting an already busy and slow moving issue tracker with additional issues that I have no intention of working through.

**Comment by marfier** [comment]
> I'm closing this, `arm64` is explicitly not a supported architecture for this software at this time. I appreciate the effort, but I'd like to avoid polluting an already busy and slow moving issue tracker with additional issues that I have no intention of working through.
> 
> You are welcome to open PR's to support `arm` functionality assuming they're not drastic architectural changes to the software, but I doubt arm will ever be officially support by us for the forseeable future.

Now that arm64 builds for Wings are part of the official releases, shouldn't this Issue be reconsidered? I think it's redundant to release arm64 builds without also releasing arm64 images.

**Comment by DaneEveritt** [comment]
Just because Wings can run on arm doesn't mean it is a priority focus for the project, or that I'm going to spend time making images for everything. It is just there for the people that really want to run on ARM and have the know-how to make it work. Its a trivial change in our build pipeline to actually output the arm binary which is why it exists.

**Comment by trenutoo** [comment]
> > I'm closing this, `arm64` is explicitly not a supported architecture for this software at this time. I appreciate the effort, but I'd like to avoid polluting an already busy and slow moving issue tracker with additional issues that I have no intention of working through.
> > You are welcome to open PR's to support `arm` functionality assuming they're not drastic architectural changes to the software, but I doubt arm will ever be officially support by us for the forseeable future.
> 
> Now that arm64 builds for Wings are part of the official releases, shouldn't this Issue be reconsidered? I think it's redundant to release arm64 builds without also releasing arm64 images.

Matthew provides [ARM64 images](https://github.com/matthewpi/images), and you can also create your own

**Comment by marfier** [comment]
> > > I'm closing this, `arm64` is explicitly not a supported architecture for this software at this time. I appreciate the effort, but I'd like to avoid polluting an already busy and slow moving issue tracker with additional issues that I have no intention of working through.
> > > You are welcome to open PR's to support `arm` functionality assuming they're not drastic architectural changes to the software, but I doubt arm will ever be officially support by us for the forseeable future.
> > 
> > 
> > Now that arm64 builds for Wings are part of the official releases, shouldn't this Issue be reconsidered? I think it's redundant to release arm64 builds without also releasing arm64 images.
> 
> Matthew provides [ARM64 images](https://github.com/matthewpi/images), and you can also create your own

Thanks, this solves it for me.
