### ISSUE TITLE
Error when install csgoserver

### ISSUE THREAD

**Issue by ttibau** [pterodactyl/panel#2124]
Hello Guys, 

On my web panel, the status of my CSGO server is installing. **After hours** I saw the install log and get success with this message: 

```
 Success! App '740' fully installed.
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 2 items discarded.
'linux32/steamclient.so' -> '../.steam/sdk32/steamclient.so
```

![image](https://user-images.githubusercontent.com/16947646/84801330-6a079c80-afd5-11ea-9ddc-ccdf3d667d64.png)

How Can I solve this?

**Comment by parkervcp** [comment]
That looks perfectly normal to me. Unless the server install is failing, and the server is not working, I don't see this being an actual issue.

**Comment by ttibau** [comment]
@parkervcp  Thanks for your reply! 
The server status still "installing" and I can't do anything :( 
![image](https://user-images.githubusercontent.com/16947646/84801880-1d709100-afd6-11ea-96c7-f9b88fc4b41d.png)

**Comment by DaneEveritt** [comment]
There is no bug here, this is likely a communication issue between your Daemon and Panel. Please use our Discord for further debugging assistance with this matter, or just check the Daemon logs which will likely point you in the right direction.
