### ISSUE TITLE
Server randomly "hanging", but not detected as crashed

### ISSUE THREAD

**Issue by Lauriethefish** [pterodactyl/panel#2127]
Panel or Daemon: Daemon (Maybe panel, not completely sure)
Version of Daemon: 0.6.12
Server's OS: Ubuntu 18.04
Your Computer's OS & Browser: Windows 10, Google Chrome

The issue is that when I am running a paper 1.12.2 server, it will occasionally "hang" with no error. (The CPU usage drops to <0.1%, not responding to commands in the console and players time out but it isn't detected as crashed.). This generally happens when a decent amount of players are on (5+), and the CPU and RAM are being utilized a lot.
I saw another thread with a similar issue, ([here](https://github.com/pterodactyl/panel/issues/1765)), and the solution turned out to be removing the flag `-XX:+AlwaysPreTouch`. However, I am not using this flag, and the issue still happens regularly.
 
1.Start a new paper 1.12.2 server
2. Do something that consumes a lot of CPU/RAM, such as setting a worldborder with the WorldBorder plugin, then executing `/wb fill` to generate a lot of chunks.
3. Wait a while
4. Notice that typing commands in the console doesn't work, nobody can join the server and the CPU usage is at 0, but the server isn't detected as crashed.

Expected Behaviour:
If the server crashes, it should restart without hanging or maybe it shouldn't be crashing in this situation atall.

**Comment by parkervcp** [comment]
You are causing the server to oom. If you have oom disabled that is what happens.

**Comment by Lauriethefish** [comment]
So if I enabled it, would the server restart correctly? I'm presuming that if this is happening I need to allocate more ram to stop OOM from having to step in.

**Comment by parkervcp** [comment]
if you enable oom-killer it will restart servers that use too much ram. Which is probably what this one did.

**Comment by Lauriethefish** [comment]
OK, I'll do that. Sorry for the stupid question, thanks for explaining it to me.

**Comment by henrikx** [comment]
@parkervcp Currently having this issue. Do you mean that if the server uses up it's allocation it will just start hanging? Will leaving some "room" between the top limit of the container vs the -Xmx flag help?

**Comment by parkervcp** [comment]
The issue is that you're server is running it of memory and unable to clean up.

**Comment by henrikx** [comment]
> 
> 
> The issue is that you're server is running it of memory and unable to clean up.

So I probably have a memory leak in a plugin, right?

**Comment by Lauriethefish** [comment]
Possible, but I think it's more likely that you just don't have enough memory allocated. My server was getting OOM killed with only 5 players on 3GB of ram on newer versions.

**Comment by henrikx** [comment]
> Possible, but I think it's more likely that you just don't have enough memory allocated. My server was getting OOM killed with only 5 players on 3GB of ram on newer versions.

I had allocated 4 GB to it. It's weird because regardless of playercount there are no memory problems for at least 8 hours. 

I've increased swap to 1024mb increased to 5120mb ram, so we'll see if it helps.

**Comment by hornta** [comment]
Iäm having this problem too. I have not enabled the OOM-killer and when I start a render process with dynmap or bluemap(I tried both) the server responds but after a while it just hangs. Can't join server and the server is not responding against any commands.

**Comment by henrikx** [comment]
> 
> 
> I`m having this problem too. I have not enabled the OOM-killer and when I start a render process with dynmap or bluemap(I tried both) the server responds but after a while it just hangs. Can't join server and the server is not responding against any commands.

I have not had any issues since adding more RAM. I use Dynmap too. It seems that those need to load quite a few chunks sometimes. I recommend just increasing your memory cap. If you don't have any, allocate swap. It's slow, but better than OOM.

**Comment by hornta** [comment]
@henrikx I enabled the OOM-killer now and set my server to use unlimited swap memory space but now it crashed on me:
```
/entrypoint.sh: line 15: 24 Killed java -Xms128M -Xmx1024M -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 137
[Pterodactyl Daemon] Out of Memory: true
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server process detected as entering a crashed state; rebooting.
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 408M / 500M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
```

It shouldn't be out of memory if I enable unlimited swap space right?

**Comment by henrikx** [comment]
Well, 1GB is not enough at all to run a Minecraft server, even if it has swap.

**Comment by henrikx** [comment]
But if you insist on using swap, I think the Xmx parameter must include the swap space you want it to be able to use. You can try just removing the -Xmx flag and it should in theory use whatever is available to it.

**Comment by parkervcp** [comment]
leaving it to manage it's own memory won't mean it limits to the container limit and will will most likely oom harder.
