### ISSUE TITLE
Support for Sentry in Wings

### ISSUE THREAD

**Issue by LeCodeCo** [pterodactyl/panel#2133]
**Is your feature request related to a problem? Please describe.**
Currently, if there's an error starting a server, Wings will log it and display it in the console. For hosting providers, unless the issue is reported, or eventually come across, it'll just remain an issue.

**Describe the solution you'd like**
It would be nice if an error logging software such as Sentry was to optionally be available in Wings, and maybe even the panel to those who configure it.

**Additional context**
This feature won't really benefit small game server owners, but rather medium to large-sized hosting providers that use Pterodactyl.

**Comment by DaneEveritt** [comment]
@schrej Probably, yes. The major advantage of Sentry, Bugsnag, et. al. is that you can get far more detailed information including metadata, events leading up to the error, who triggered the error (less relevant since almost everything is a "system user" here), and more advanced alarms based on frequency and whether or not it has been seen before.

I'm all for integrating them, although I'm not sure if there is a good way to handle their implementation such that you can opt-in to them. I've only ever used them in contexts where I know I want to send my data to them.

**Comment by matthewpi** [comment]
Due to the way Golang works with error handling this could be a pain to implement unless there is a way to hook directly into the logger.  There isn't a global error or crash handler like you would see in other programming languages.

**Comment by DaneEveritt** [comment]
I'm pretty sure there is a way to handle it to some degree, its more the additional tooling such as breadcrumbs and such that are really useful in Bugsnag for example that I am unsure about.

**Comment by LeCodeCo** [comment]
I think that would be limiting on both Bugsnag and Sentry as I figure they have a fancy way of all getting information they need in their Go libraries. I don't know if this is possible in Go, but surely we could just only start them if the API key/DSN is specified in the config.

**Comment by schrej** [comment]
> I'm not sure if there is a good way to handle their implementation such that you can opt-in to them. I've only ever used them in contexts where I know I want to send my data to them.

Also abstracting them away might be difficult. I'd assume they are both built for custom software that is monitored by a single company, not software that is sold and needs to integrate into different monitoring systems. If we have to implement both systems throughout wings I would be strongly against implementing support at all.

**Comment by DaneEveritt** [comment]
Closing this due to difficulty and specificity to each deployment. Can't think of a good solution right now and would like to start trimming the issue list down to a more manageable size.
