### ISSUE TITLE
| Automatic backups | Schedules bug

### ISSUE THREAD

**Issue by Nexusatko** [pterodactyl/panel#2134]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0
* Server's OS: Ubuntu 18.04 LTS Server
* Your Computer's OS & Browser: Windows 10 Home | Google Chrome

Panel: 7.4.7 PHP

1. Go to schedules
2. Remove and recreate schedule to closest time for test
3. Wait
4. Still nothing did happen

**Expected behavior**
I want to automatic backups of servers on certain hours ( As screen )
![SharedScreenshot](https://user-images.githubusercontent.com/59520956/85861509-c41c1500-b7c0-11ea-8764-87a9cdcb7621.jpg)

**Comment by DaneEveritt** [comment]
There is not enough information here to understand a.) what the bug is and b.) how to reliably reproduce whatever the bug is.
