### ISSUE TITLE
Crashed state detected allthough properly stopped

### ISSUE THREAD

**Issue by dorsax** [pterodactyl/panel#2136]
**Background:**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.7.17
* Server's OS: Ubuntu 18.04.4 LTS
* Your Computer's OS & Browser: Win10 Edge/Firefox/Chrome

**Describe the bug**
The Daemon shall restart itself if a crash is detected. But it also restarts if the corresponding server was shut down from within the program, because it falsely detects a crashed state.

**To Reproduce**
e.g. SpigotMC:
* issue `/stop` ingame
* The server stops
* Console shows the following lines 
```
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 0
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server process detected as entering a crashed state; rebooting.
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 18310M / 50000M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
```

**Expected behavior**
When the Server is marked as OFF, it should stay off and the Daemon should not restart it.

**Comment by parkervcp** [comment]
This is a long standing bug that people complained about when I got fixed so it was added back in.

**Comment by dorsax** [comment]
Wasn't aware of this. Consider it as a feature request then, as a thing which could be located at the Egg level or on Server level at Startup Configuration. 
As of Minecraft, the thing is that SpigotMC has a very ugly implemented "restart" feature, which just uses a file `start.sh` to start the server. It's not that good at all, I personally would prefer a while loop or a systemd module, but this seems to not be possible at most server architectures.

You could either support that `?tar.sh`, or listen for specific log entries to support restarts (like `Startup script './start.sh' does not exist! Stopping server.`)

**Comment by DaneEveritt** [comment]
Thanks for the report, however this has gone back and forth over the years and I'd rather maintain what we have currently. It isn't perfect and there are cases where it doesn't work as expected but I have no plans (or time honestly) to work on smaller things like this right now.

Closing out this issue since it is unrealistic to assume I'll ever actually get around to making anything configurable for this right now.

**Comment by parkervcp** [comment]
@dorsax I just tested and it looks like this is working properly in 1.0 FYI.

**Comment by dorsax** [comment]
> @dorsax I just tested and it looks like this is working properly in 1.0 FYI.

@parkervcp I just tested it in 1.0.0-rc.2 and unfortunately it does not work: https://pastebin.com/FmeZtSbL

**Comment by DaneEveritt** [comment]
https://github.com/pterodactyl/wings/blob/c7e732d084a9bc540499482de1ca0e1a50bd78bc/server/crash.go#L65

You can add `system.detect_clean_exit_as_crash=true` to your `config.yml` to make it not treat a `0` exit code as a crash.

**Comment by dorsax** [comment]
> You can add `system.detect_clean_exit_as_crash=true` to your `config.yml` to make it not treat a `0` exit code as a crash.

Just tried it and have to give a little correction: Set it to `false` to treat a 0 exit code as clean exit.
