### ISSUE TITLE
Minecraft's "Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by nesperida911** [pterodactyl/panel#2138]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7 and Beta 
* Server's OS: Ubuntu 18.04 and 20.04
* Your Computer's OS & Browser: Windows 20.04 and Edge Chromium

**Describe the bug**
On a Minecraft Server installed in a Pterodactyl 0.7 and Beta shows an "Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host" on some users.
When I installed the same Minecraft server directly on the VM where I installed also the Pterodactyl I told to some of my users that encountered this issue to connect on this test server that I run directly on the VM and not on the pterodactyl and they had no issue on connecting and that error didn't show up that's why I suspected Pterodactyl if something is going on the networking side.
I've tested running the Vanilla, Spigot and Paper Minecraft Server build and same result when its created on pterodactyl
Users who encountered this error and also me tried suggestions on some forum to clear dns and change dns and also changing the java settings but still gives the same error

Please provide additional information too, depending on what you have issues with:
Panel: PHP 7.4.7
Daemon: 
 - Kernel: Linux vm-pterodactyl 5.4.0-1019-azure #19-Ubuntu SMP Fri Jun 19 17:38:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Docker: 
    Server:
        Containers: 1
        Running: 1
        Paused: 0
        Stopped: 0
        Images: 3
        Server Version: 19.03.8
        Storage Driver: overlay2
        Backing Filesystem: <unknown>
        Supports d_type: true
        Native Overlay Diff: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
        Volume: local
        Network: bridge host ipvlan macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version:
        runc version:
        init version:
        Security Options:
        apparmor
        seccomp
        Profile: default
        Kernel Version: 5.4.0-1019-azure
        Operating System: Ubuntu 20.04 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 4
        Total Memory: 15.61GiB
        Name: vm-pterodactyl
        ID: ITG3:7L3A:YC4Q:B72C:YJ2F:T2BW:XFZ5:4GJT:X65I:J6VM:AY3J:WOF7
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
        127.0.0.0/8
        Live Restore Enabled: false

    WARNING: No swap limit support

**To Reproduce**
This Minecraft error is hard to reproduce because it appears randomly even on a fresh install pterodactyl and the whole server

**Expected behavior**
User can connect to the server without the "Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host"

**Comment by DaneEveritt** [comment]
Thanks for taking the time to report this, however unless additional users are able to corroborate this report I will not be investigating or taking action against it.

**Comment by derech1e** [comment]
I have the same Problem as @haliknihudas666. As he has already described, the connection to a Minecraft server that is directly on the VM works. However, if you set up the server in the Docker container and the users try to connect, the exact same error occurs after about 10 seconds.

Was there or is there already a solution for this? @haliknihudas666 @DaneEveritt

**Comment by samukatb** [comment]
The same is happening to me, I have 5 servers running normally, so I decided to switch to the pterodactyl panel because it is easier to handle the server files, restart and other things. However now when some players try to connect, they are disconnected by the remote host error. They are disconnected after about 5 ~ 10 seconds after entering the server.

**Comment by derech1e** [comment]
> The same is happening to me, I have 5 servers running normally, so I decided to switch to the pterodactyl panel because it is easier to handle the server files, restart and other things. However now when some players try to connect, they are disconnected by the remote host error. They are disconnected after about 5 ~ 10 seconds after entering the server.

Yeah, I have extactly the same problem. Can you open a new issue and link that one to it?

**Comment by banan47** [comment]
I have the same problem, players has been disconnected after joined the server. Use of ipconfig /flushdns in cmd console by players doesn't work.
