### ISSUE TITLE
SSL Hot Reloading in Wings

### ISSUE THREAD

**Issue by LeCodeCo** [pterodactyl/panel#2140]
**Is your feature request related to a problem? Please describe.**
Currently to my knowledge, SSL certificates aren't automatically reloaded when they're changed on file, in most cases automatically from LetsEncrypt. This means that Wings would need restarting to have these certificates take effect.

**Describe the solution you'd like**
I'd like certificates to automatically hot-reload when the file on disk changes, to prevent Wings from having to be restarted.

**Describe alternatives you've considered**
A cronjob to manually restart Wings frequently or an after run hook into LetsEncrypt works too.

**Comment by DaneEveritt** [comment]
Closing as discussed in Discord...

```
--auto-tls --tls-hostname wings.example.com
```

😍

**Comment by Sir3lit** [comment]
```
INFO: [Jul  1 06:44:56.985] configuring internal webserver host_address=0.0.0.0 host_port=8080 use_auto_tls=true use_ssl=true
INFO: [Jul  1 06:44:56.985] webserver is now listening with auto-TLS enabled; certificates will be automatically generated by Let's Encrypt hostname=test.justmyrandomstuff.com

2020/07/01 06:46:32 http: TLS handshake error from 88.198.68.87:37236: acme/autocert: unable to satisfy "https://acme-v02.api.letsencrypt.org/acme/authz-v3/5589039442" for domain "test.justmyrandomstuff.com": no viable challenge type found
2020/07/01 06:47:29 http: TLS handshake error from 88.198.68.87:37456: acme/autocert: missing certificate

```

Get this upon trying to visit the daemon in the panel. The daemon returns a 504 in the browser console.

**Comment by Fallen-Breath** [comment]
I have the same issue as described in https://github.com/pterodactyl/panel/issues/2140#issue-648617908, wings doesn't reload the changed cert files managed by externel acme.sh and rsync

The solution https://github.com/pterodactyl/panel/issues/2140#issuecomment-652185398 does not work for me, because the auto tls thing cannot setup in my environment
