### ISSUE TITLE
NodeJS issue Ubuntu 20.04

### ISSUE THREAD

**Issue by andrewfer000** [pterodactyl/panel#2142]
**Background (please complete the following information):**
* Panel or Daemon:  Daemon 
* Version of Panel/Daemon: 0.6
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Firefox

**Describe the bug**
When setting up NPM I get these errors with gyp. 

> mmmagic@0.5.3 install /srv/daemon/node_modules/mmmagic
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 47, in <module>
    import gyp
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 10, in <module>
    import gyp.input
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 7, in <module>
    import ast
ImportError: No module named ast
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-31-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/daemon/node_modules/mmmagic
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmmagic@0.5.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmmagic@0.5.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-02T00_32_49_796Z-debug.log

**To Reproduce**

Follow the install instructions as normal
Once at the last setp "npm install --only=production --no-audit --unsafe-perm" 
get errors

**Expected behavior**
No errors durring install.

**Comment by parkervcp** [comment]
We request that install issues with the daemon get brought to the discord server. https://discord.gg/pterodactyl

Also you are missing the `python-dev` or `python-devel` package.
