### ISSUE TITLE
API returns incorrect info

### ISSUE THREAD

**Issue by williamd5** [pterodactyl/panel#2143]
**Background (please complete the following information):**
* Panel or Daemon: panel
* Version of Panel/Daemon: 0.7.17
* Server's OS: Ubuntu 18.04 LTS
* Your Computer's OS & Browser: Windows 10 with Chrome

**Describe the bug**
When requesting `application/servers`, the `node` attribute of every server is always `2`, regardless of the node that it is actually on. In our case, node ID 2 is the first node (ID 1 has been deleted).
**To Reproduce**
1. Send a get request using CURL
2. Loop through all of the pages and save all servers in a list
3. Print the list, all servers have `node: 2`

**Expected behavior**
Display the actual ID of the node

**Comment by parkervcp** [comment]
So you are saying that the first node you had was removed and this is the only node you have?

**Comment by williamd5** [comment]
> So you are saying that the first node you had was removed and this is the only node you have?

No, we have over 5 nodes, but the api endpoint says all servers are on node id `2`

**Comment by DaneEveritt** [comment]
I just checked and have a two servers on two different nodes and I get the expected response with one server having node 1 and the other node 2.

**Comment by williamd5** [comment]
I can program a simple demo that dumps the response if needed.

**Comment by parkervcp** [comment]
You want to drop a curl command that I can query a panel with?

**Comment by DaneEveritt** [comment]
Based on details from other's on Discord I still believe this to either be an issue unique to your setup, or a bug in your looping script so I will be keeping this closed.
