### ISSUE TITLE
Support configuring pagination data length when querying the API.

### ISSUE THREAD

**Issue by williamd5** [pterodactyl/panel#2145]
Yes, it's nice that on the admin panel servers are split into pages and this is crucial for proper rendering when browsing.

However, when requesting data using CURL, the response is also in pages (with 50 servers on each). This makes it extremely difficult to obtain a list of all servers with 1 request and forces you to send n requests, where n is the number of pages that you have. In our case, we have to send over 80 requests to the endpoint get a full list of the created servers; quite inconvenient.

The JSON that is returned should always be the full list. On the panel, this list can be cached and split into pages of 50 servers easily.

Please let me know if I'm missing something and there is a way to obtain a full list with 1 request (did not find any information about this in the docs).

**Comment by DaneEveritt** [comment]
Returning all... 4,000 servers of yours at once in a single response will most likely result in serious performance issues, not only as a result of hydrating 4k server models (and not even looking at any potential `includes` passed through), but also with returning an enormous JSON document back.

The results are paginated for a reason, and it isn't something that is unique to this software. We can look at making this configurable, however I will not make any endpoints that return all of the results at once.

**Comment by williamd5** [comment]
There is no difference if I send 80 requests and then merge the result into one array with 4000 servers and if I just get the full list with 1 request. An option to disable paginating would really be something useful to see.

**Comment by schrej** [comment]
I guess we should allow to specify the amount of servers per page. If someone crashes their panel, that's on them. Maybe a configurable limit to prevent API abuse.

**Comment by DaneEveritt** [comment]
> There is no difference if I send 80 requests and then merge the result into one array with 4000 servers and if I just get the full list with 1 request. An option to disable paginating would really be something useful to see.

There is a huge difference between 80 requests and 1 request on the Panel itself. I'm not talking about whatever API consumer is running. If you truly want to return everything un-paginated I'd recommend just modifying the source yourself to return all of them, but I'm not making that something that is possible by default in the Panel.

**Comment by williamd5** [comment]
> > There is no difference if I send 80 requests and then merge the result into one array with 4000 servers and if I just get the full list with 1 request. An option to disable paginating would really be something useful to see.
> 
> There is a huge difference between 80 requests and 1 request on the Panel itself. I'm not talking about whatever API consumer is running. If you truly want to return everything un-paginated I'd recommend just modifying the source yourself to return all of them, but I'm not making that something that is possible by default in the Panel.

This is important on the pannel as all results have to be rendered and displayed by the browser. You can't display 4k servers on one page. However, fetching all the servers with the API does not mean that all of them are being displayed. You may fetch all servers, for instance, for analytical purposes. A normal server will have no problem downloading a JSON document with 4k servers within a second.

**Comment by DaneEveritt** [comment]
You're missing my point, the actual backend code is likely unable to handle hydrating and responding with 4k server models, and all of their relationships. I'm not doubting a server's ability to send/receive a JSON document of whatever size, thats hardly where my concern lies in this issue.

PHP will quickly run out of memory on most setups when trying to return all of those servers at once, its precisely why I don't do that. 👍

**Comment by alekitopi** [comment]
I'm starting to use the Pterodactyl API and this that says @williamd5 is true, in browser could not show 4,000 servers but if when making a request to the API can specify the number of servers per page would be perfect because depending on the server can support it or not. In my case this happens when I want to get all the allocations to get the IP of the server; for this I have to go page by page getting the allocations in use and having to make several requests for this same thing.

**Comment by DaneEveritt** [comment]
You can just add `?include=allocation` to the API call for the server to get the allocation details... (Or `allocations` I don't remember which).

**Comment by trenutoo** [comment]
Isn't this already possible in the current latest panel version (1.4.2) with the use of `?per_page=x`?

**Comment by zefir-git** [comment]
> Isn't this already possible in the current latest panel version (1.4.2) with the use of `?per_page=x`?

At the time [v0.7.17](https://github.com/pterodactyl/panel/releases/tag/v0.7.17) was the latest version. Does `per_page` allow you to include all entries into a single page?

**Comment by trenutoo** [comment]
> > Isn't this already possible in the current latest panel version (1.4.2) with the use of `?per_page=x`?
> 
> At the time [v0.7.17](https://github.com/pterodactyl/panel/releases/tag/v0.7.17) was the latest version. Does `per_page` allow you to include all entries into a single page?

I created 250 servers and requested them all at once without any issues nor saw any set limits. I am not too keen to create dummy records to test further, but 5000 allocations in one request worked fine.
