### ISSUE TITLE
More useful diagnostic/debugging tools

### ISSUE THREAD

**Issue by rcmaehl** [pterodactyl/panel#2146]
**Is your feature request related to a problem? Please describe.**
While troubleshooting why ptero stopped working overnight and attempting to work with discord support on what appears to be a connection error, support stated "With all of those errors i would just reinstall the panel" and no additional support was provided. I feel like either ptero documentation is lacking or ptero needs additional debugging tools to help support diagnose issues.

**Describe the solution you'd like**
More explicit diagnostic errors in ptero on what succeeded and what didn't. Providing errors as listed from https://pterodactyl.io/panel/0.7/troubleshooting.html#transfer-exceptions-xhr-poll-error to support is clearly not enough to be useful.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/716581/86483369-f201dc00-bd21-11ea-9b0b-371d08568769.png)

**Comment by parkervcp** [comment]
Just to call out. The guy with the Green name isn't a project team member. They donated to the panel. I am fairly certain they were just joking.

**Comment by parkervcp** [comment]
the diagnostics we have now are fine. they were just kidding.

**Comment by schrej** [comment]
I think the troubleshooting guide could be improved further though. We should think about that for 1.0, it might also reduce support load in discord.
