### ISSUE TITLE
Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by iceBear67** [pterodactyl/panel#2149]
**Background (please complete the following information):**
* Panel or Daemon: panel
* Version of Panel/Daemon: 0.7.17
* Server's OS: CentOS Linux release 7.8.2003 (Core)
* Your Computer's OS & Browser: ArchLinux & Firefox

**Describe the bug**
It occurs when I'm trying to edit something in `admin/settings` (e.g Company Name).
Logs: [production.ERROR: ErrorException: Trying to access array offset on value of type int in /home/wwwroot/pterodactyl/vendor/symfony/console/Input/ArrayInput.php:135](https://paste.ubuntu.com/p/hvZsCHW2rz/)
But the save was successful..

PHP 7.4.7 (cli) (built: Jul  4 2020 00:15:24) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies

**To Reproduce**
1. Go to 'admin/settings'
2. Click on 'Save'
3. See error

**Expected behavior**
Save it without errors.

**Comment by iceBear67** [comment]
Might be caused by php version?I'm trying 7.2

**Comment by iceBear67** [comment]
Alright.It caused by php version

**Comment by Wqrld** [comment]
@DaneEveritt Please do look into this as the community guide suggests using php 7.4 for ubuntu 20.04

**Comment by Wqrld** [comment]
It might be the default but then you should either update laravel to support 7.4 (if it has an update for it) Or just use the default method that is adding a apt repo for 7.2/7.3

**Comment by parkervcp** [comment]
By default the docs are for Ubuntu 18.04. The community guides are community maintained.

The decision for the 20.04 guid to have 7.4 was forward looking to the eventual 1.0 release. If you have complaints about that decision then take it to the pterodactyl/documentation repo
