### ISSUE TITLE
File Manager Directory Issues

### ISSUE THREAD

**Issue by AshMW-com** [pterodactyl/panel#2150]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Beta.5 
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chrome Windows 10

**Describe the bug**
A clear and concise description of what the bug is:
When you click on a directory starting with a "." it keeps adding directory on the path. ![GIF](https://dscord.ga/i/2yzdo.gif)

**To Reproduce**
1. Go to 'File Manager'
2. Click on 'A directory starting with a "."'
3. Look at directory and url.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

It should not keep adding on to the directory path.

**Comment by fabm3n** [comment]
Can't reproduce it using a panel at commit b5576742

**Comment by thetrueash93** [comment]
https://dscord.ga/4s8tg.gif

**Comment by fabm3n** [comment]
I'm using a newer selfbuilt version than you, so it looks like this bug is already fixed.

**Comment by AshMW-com** [comment]
Hello i actually didnt realise the issue effects all directories....
https://dscord.ga/dvrlh.gif

**Comment by AshMW-com** [comment]
Hello I have found our issue was our Reverse proxy.
