### ISSUE TITLE
Panel shows Server as Offline while its still running

### ISSUE THREAD

**Issue by MisterCookie1234** [pterodactyl/panel#2153]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.17
* Server's OS: Ubuntu 18
* Your Computer's OS & Browser: Win 10 + Chrome

Hello!
Whenever i start my MC Server, it goes to Online in the Panel, but after a while the panel sets it to "offline" making it impossible
to work with the server from the console - even tho the Server still stays online. 
Any fixes for that?

**Comment by DaneEveritt** [comment]
wontfix.

This is generally a misconfigured egg or customized server process that the Daemon doesn't know how to listen for. Please try Discord for further assistance.
