### ISSUE TITLE
Invalid namespace

### ISSUE THREAD

**Issue by Leon1273** [pterodactyl/panel#2155]
Hi there!

I have just got my new node working as it can connect to the panel but I get this error when I try to use one of my servers

**_There was an error attempting to establish a WebSocket connection to the Daemon. This panel will not work as expected.

Invalid namespace_**

Any help would be great!

**Comment by Sir3lit** [comment]
This error happens when the config for the server was removed from the configs/servers folder for that specific server. Didbyou mvoe the daemon or delete it and reinstall it?

**Comment by Leon1273** [comment]
I reinstalled the daemon but not daemon-data, would that be the problem?

**Comment by Sir3lit** [comment]
Yes. The server config files are saved in daemon/config/servers

**Comment by Leon1273** [comment]
Any idea on what to do about it?
