### ISSUE TITLE
Randomly banned

### ISSUE THREAD

**Issue by Technofied** [pterodactyl/panel#2156]
Hi there,

I was banned for spamming for sending the following 

"[Error] XMLHttpRequest cannot load https://panel.xxxxxx.net:8080/v1 due to access control checks."

I don't think this was spam? My tag is - Technofied#2823

**Comment by TrixterTheTux** [comment]
Hi,
Seems that one of our bots for some reason thought it was spam even though I don't see why it would get triggered from that, I've unbanned you.
