### ISSUE TITLE
record time server was last started/files updated/etc. for activity monitoring

### ISSUE THREAD

**Issue by williamd5** [pterodactyl/panel#2159]
**Is your feature request related to a problem? Please describe.**
Public server hosts are often filled with inactive servers. 

**Describe the solution you'd like**
If the API has an attribute that has the date of the last time the server was started or any of the files have been modified, system administrators can easily set up a CRON job to notify their owners and delete the servers afterwards.

**Describe alternatives you've considered**
We had falsely assumed that the "updated_at" attribute had this function and had developed a system based on that, but it turns out Laravel sets that whenever something in the server table is modified, so if you change the name or description. It doesn't update when servers are started/stopped, files modified and so on.

**Additional context**
This could nicely go into `server->attributes` as `lastactive_at` or something similar.

**Comment by DaneEveritt** [comment]
Closing as partially duplicative of #1219
