### ISSUE TITLE
Feature request: Set db limit

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#216]
It would be nice if it could be possible to manage size limitations per database within the panel.

**Comment by DaneEveritt** [comment]
As discussed on Discord, theres not really an effective way to do this that the panel could control. Setting it via a disk quota isn't possible without the panel itself running commands on the system, which is not in the scope of the current project, and also runs issues on remote MySQL machines.

**Comment by anondev-sudo** [comment]
This option to limit size per mysql db or to count mysql db size to your server storage limit would be nice.

**Comment by anondev-sudo** [comment]
Maybe mysql databases size could be just counted to your server disk limit, no need to setup disk quota for mysql. It should act the same - that you can't start server when your disk limit was reached + mysql db should be paused (if not possible the password for mysql should be rotated and don't allow user to view new password when disk limit was reached).
