### ISSUE TITLE
Queue Worker failed to start

### ISSUE THREAD

**Issue by Corenb** [pterodactyl/panel#2162]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel v1.0.0 Beta Release 5 / Daemon v1.0.0 Beta Release 7
* Server's OS: Debian 9
* Your Computer's OS & Browser: Win 10 + Mozilla Firefox

**Expected behavior**
Schedules won't works but the crontab is correctly configured.

![1](https://user-images.githubusercontent.com/1338450/87223180-07f34a80-c37b-11ea-9b8c-bd407eb44f93.png)
![2](https://user-images.githubusercontent.com/1338450/87223181-07f34a80-c37b-11ea-9db2-7efad0c2bed5.png)
![3](https://user-images.githubusercontent.com/1338450/87223182-088be100-c37b-11ea-8be9-9ddefcd1a6af.png)
![4](https://user-images.githubusercontent.com/1338450/87223183-088be100-c37b-11ea-908e-a656fc10f1c6.png)
![5](https://user-images.githubusercontent.com/1338450/87223184-088be100-c37b-11ea-929b-a399c3a52ab9.png)

**Comment by MrPadingy** [comment]
You should use the Discord for support. As this most likely is just an issue with your system. People may have been able to assist in there.

Try `systemctl reset-failed pteroq && systemctl restart pteroq`

**Comment by Corenb** [comment]
I've already ask on Discord but receive no answer...

**Comment by MrPadingy** [comment]
> I've already ask on Discord but receive no answer...

Did you try the above command? After running it see if it is running properly

**Comment by Corenb** [comment]
> Did you try the above command? After running it see if it is running properly

Yes the command works thank you very much !
