### ISSUE TITLE
Two-Factor Authentication Stripping Zeros

### ISSUE THREAD

**Issue by dkay0670** [pterodactyl/panel#2163]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0 Beta 5
* Server's OS:  Ubuntu 18.04
* Your Computer's OS & Browser: macOS 10.16 on FIrefox 

**Describe the bug**
If the two-factor authentication code starts in 0 the code will strip off that zero causing it to not be 6 digits.
Please provide additional information too, depending on what you have issues with:
Panel: `php7.4`.

**To Reproduce**
1. Enable Two-Factor Authentication
2. Wait for a two factor authentication code that begins with 0
3. Type the code
4. See the error

**Expected behavior**
Accepting your six digit two-factor authentication code without stripping off zeros.

**Comment by DaneEveritt** [comment]
_nice_ 👌
