### ISSUE TITLE
My daemon is not working!

### ISSUE THREAD

**Issue by M4iky1** [pterodactyl/panel#2175]
I have a problem when i try to start a minecraft server! From the panel (Panel version: 0.7, Daemon Version: 0.6)!
in the server console i have: 
`[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 47M / 1024M
[Pterodactyl Daemon] Ensuring correct ownership of files.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] A fatal error was encountered while starting this server.`
and here is the npm diagnostics: https://hastebin.com/esucubeloy

**Comment by schrej** [comment]
Please use our Discord for support: discord.gg/pterodactyl

**Comment by M4iky1** [comment]
no one is responding to me

**Comment by fabm3n** [comment]
Then you have to wait longer
