### ISSUE TITLE
Storing backups using an external storage provider

### ISSUE THREAD

**Issue by T-x-T** [pterodactyl/panel#2177]
**Is your feature request related to a problem? Please describe.**
If you want to store backups on a remote server or storage provider you either have to mount a remote directory into the the path on the host where the backups are stored or you need to use a script to upload them somewhere. 
Mounting something like google drive can be a bit unreliable from my experience.

**Describe the solution you'd like**
My favorite solution would be a store / retrieve command that should get executed on the host. You could get a wildcard for the file path on the host, something like {path} and {file} which you could then use in an rclone command for example
Then every time the panel wants to store a backup and there is a specified command it will trigger the command once the backup got saved. Optionally you could also enter a command for retrieval of the file that should get executed to pull the file out of the remote storage before the user can download it again through the panel.
An example command could be `rclone move {path} gsuite_backup:/ptero/` or `rclone copy gsuite_backup:/ptero/{file} {path}`

**Describe alternatives you've considered**
Alternatively you could look into either directly integrating with external storage providers or integrate rclone more directly to remove the need for specifying the commands yourself. Then you would just enter stuff like paths on the remote host, API keys, etc into the panel directly and pterodactyl itself takes care of uploading and downloading.

**Comment by FoksVHox** [comment]
I believe this already is a thing and I think it is supports AWS and a other service, but can't remember what it's called.

**Comment by schrej** [comment]
We have support for S3 and local path backups right now. That would also allow to create backups on any mounted remote storage. While rclone also does support mounting storage, it's worth to consider building in direct support for rclone as that would provide integration with a huge amount of providers in one go.

**Comment by matthewpi** [comment]
I'm going to close this issue in favor of any issues that request support for a specific service or software for storing backups.  Currently, wings supports local storage (on the node itself) and S3 for storing backups.
