### ISSUE TITLE
Fully automate wings installation

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#218]
Now that we have an auto-install script for wings, installing it should be fully automated by automatically downloading the config from the panel.

A one-time link should be creatable that works for a few minutes with a token that allows downloading the install script and the config (something like `panel.something.tld/install-node/<somerandomtokenwhichmakesitsecure>`).
Also, a ready-to-paste command should be shown in the panel that can be copied to the node server to make installing as easy as possible.

- [x] Automatic wings configuration
- [ ] wings auto-install script with auto-configuration

**Comment by DaneEveritt** [comment]
I'm going to assign this to you to work out a plan for how it should work. I can add endpoints if needed, just let me know. 👍

**Comment by schrej** [comment]
Well its rather simple. We just serve the install script on that Endpoint. We just need to add a Part to write the specific config for the node in question. I will implement that as well though. ;)

**Comment by schrej** [comment]
As we have a way to download the configuration from the panel, we only need an install script for wings hosted somewhere (still voting for `fly.pterodactyl.io/wings`) and make it consume a configuration retrieval token and call the auto configure script to make the setup fully automatic.
