### ISSUE TITLE
Injecting secrets into containers

### ISSUE THREAD

**Issue by rxdn** [pterodactyl/panel#2181]
**Is your feature request related to a problem? Please describe.**
I'm facing the dilemma of securely managing secret keys which I'd like to inject into containers in a secure fashion

**Describe the solution you'd like**
A solution similar to kubernetes' secret key management, in which you define secret keys in a manifest file (Pterodactyl alternative would be via the panel). You can then tell Kubernetes to inject certain secrets via the manifest files of your other services, sets, etc. The pterodactyl alternative would be to allow you to select which secrets to inject into a server via a checklist on the panel.

**Describe alternatives you've considered**
- Hardcoding the keys in my application (hard to update, insecure)
- Hardcoding the keys in my Dockerfile (insecure)
- Using /usr/bin/env for the startup command (insecure)

**Additional context**
Secrets should be encrypted in the database.

**Comment by parkervcp** [comment]
In theory, depending on who has access to the server using a variable would make it accessible as an env variable. While I get that it's "insecure" if you are the only one using the server and the only one with access it's effectively hidden. Other servers can't see it.

You can query it via the API, but that is tied to application level API access.

The only other option I really have here is potentially using a mount (available in 1.0) that each server has access to and keeping the secretes in files there.

**Comment by parkervcp** [comment]
Per their docs, [here](https://kubernetes.io/docs/concepts/configuration/secret/), it looks like that is how they are doing it honestly.

Either as env vars or as files in a volume.

**Comment by rxdn** [comment]
> The only other option I really have here is potentially using a mount (available in 1.0) that each server has access to and keeping the secretes in files there.

I'll investigate this when 1.0 is released - thank you.

For now, I think I'll just create variables on my egg and set the default value for easy updating
