### ISSUE TITLE
"Waiting for RCON to come up..." Rust.

### ISSUE THREAD

**Issue by syntaxxl** [pterodactyl/panel#2182]
Hey, first of all, I'm sorry for posting this here.
I've asked for help *multiple* times in Discord, but no one seems to care, so I'm here - and hopefully I can get some help, thank you by the way.

So, every time I try to start my server, this message keeps popping up "Waiting for RCON to come up...", I tried multiple things, changing my server port, the Rcon port, nothing worked.

Any help would be really appreciated, thank you very much.

**Comment by parkervcp** [comment]
First: You didn't fill out any information.
Second: You don't say what game server this is for.
Third: Eggs problems should be asked about in the #eggs channel
