### ISSUE TITLE
Wings B6, All Server status always reported as stopped

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2183]
**Background (please complete the following information):**
* Panel or Daemon: Wings B6
* Version of Panel/Daemon:  Beta 6
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Win10 / chrome

**Describe the bug**
`/api/client/servers/<uuid>/resources` endpoint reports server as stopped when servers are actually running.
![](https://justmyrandomstuff.com/img/bZ9Bu8a.gif)
```
{
   "object":"stats",
   "attributes":{
      "current_state":"stopped",
      "is_suspended":false,
      "resources":{
         "memory_bytes":0,
         "cpu_absolute":0,
         "disk_bytes":0,
         "network_rx_bytes":0,
         "network_tx_bytes":0
      }
   }
}
```
**To Reproduce**
Upgrade from B5 to B6
View index page, servers all show 0

**Expected behavior**
/resources to return proper data

**Comment by thermaldrg** [comment]
Also worth noting that all resources return 0, such as "disk_bytes"
