### ISSUE TITLE
Daemon: docker, mount /etc/localtime

### ISSUE THREAD

**Issue by kefirawp** [pterodactyl/panel#2185]
My time zone in the file /etc/timezone is "Europe/Moscow", but the time is displayed incorrectly.
Is it possible to mount the /etc/localtime file?

**Comment by SkippTekk** [comment]
If you want the server to be a certain time for Minecraft. Use

-Duser.timezone="LOCATION"

**Comment by kefirawp** [comment]
I have CSGO server

**Comment by fabm3n** [comment]
Please use the Discord for Support. https://pterodactyl.io/discord
If this is a bug or feature request use the issue template.

**Comment by fabm3n** [comment]
Also i think it's a dupe of #2073

**Comment by andris155** [comment]
@SkippTekk big thanks for solution.
