### ISSUE TITLE
Client databases don't work

### ISSUE THREAD

**Issue by ggeed** [pterodactyl/panel#2187]
database host works properly, but plugins can't connect to the databases.
DB host configuration
![изображение](https://user-images.githubusercontent.com/56407064/88417881-67297400-cdeb-11ea-8ec7-8b540f0a1206.png)
mysql luckperms setup
![изображение](https://user-images.githubusercontent.com/56407064/88418003-9213c800-cdeb-11ea-9185-950db7bc8af7.png)
![изображение](https://user-images.githubusercontent.com/56407064/88418513-54636f00-cdec-11ea-82f5-78884f2f6bee.png)
hikari pool error
![изображение](https://user-images.githubusercontent.com/56407064/88418783-c0de6e00-cdec-11ea-8b78-6f43e0d02f7c.png)

i allowed 3306 port in the firewall.
MariaDB version: 10.5.4

**Comment by parkervcp** [comment]
Per our docs: Chances are you'll need to allow external access to this MySQL instance in order to allow servers to connect to it.

https://pterodactyl.io/tutorials/mysql_setup.html#creating-a-database-host-for-nodes
