### ISSUE TITLE
Panel stuck is refresh loop after server installed, when viewing the console during install

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2190]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel Beta 6
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Win 10 / Chrome

**Describe the bug**
When viewing a server that is installing it refreshes the console container rapidly once the install is complete and loops, A manual F5 fixes it and takes you to the normal screen 

![](https://justmyrandomstuff.com/img/WNJT2Sh.gif)
**To Reproduce**
1. Install server
2. View console as an admin
3. When the server completes install, loops 

**Expected behavior**
Single refresh and show proper options

**Comment by IAmLythixIAmDumb** [comment]
As far as I know, this also makes it so after the page has been reloaded and fixed it still says server marked as ... and then you have to press stop, then kill, and then press the restart button and it will start. Basically broken smh

**Comment by Sir3lit** [comment]
If you click stop and then restsrt then kill it, it fixes it.

**Comment by IAmLythixIAmDumb** [comment]
> If you click stop and then restsrt then kill it, it fixes it.

Yeah, there's multiple combinations that work to fix it.
