### ISSUE TITLE
Container adding extra symbols to MOTD server.properties on server start

### ISSUE THREAD

**Issue by lpjn** [pterodactyl/panel#2192]
**Server version:** 1.16.1 Paper (git-Paper-117)
**Pterodactyl version:** 1.0.0-beta.4 (upgraded to 1.0.0-beta.6, issue still prevalent)
**Wings version:** 1.0.0-beta.5

Server offline, MOTD set as "motd=\u00A76BBQ - [Main]"

Server started, MOTD switches to "motd=§6BBQ - [Main]" briefly (this is fine, symbol is valid) and then "\u00C2\u00A76BBQ - [Main]" when fully started. It is possible the forced conversion of the MOTD is interpreting § as \u00C2 - which is causing the phantom A character to appear. This issue is not prevalent on the main build of pterodactyl, or when run locally on my desktop. No variables have been setup to modify the MOTD.

Produces the following results in the client:
![image](https://user-images.githubusercontent.com/38690189/88623095-24da8e00-d09c-11ea-8957-dd4c31184e6a.png)

**Comment by Oberfail** [comment]
My workarround is to remove all "Configuration Files" variables from the egg.

The huge drawback is, it wont apply those variables anymore upon startup, for example setting the correct port.

**Comment by lpjn** [comment]
> My workarround is to remove all "Configuration Files" variables from the egg.
> 
> The huge drawback is, it wont apply those variables anymore upon startup, for example setting the correct port.

Correct, removing all JSON reference of the server properties fixes it, with the obvious drawbacks.

**Comment by parkervcp** [comment]
You should also update your beta versions. You are quite far behind and a new version night fix that.

**Comment by lpjn** [comment]
Hey Parker! Thanks for the suggestion. I just upgraded and sadly see the issue still using paper & vanilla minecraft eggs.

**Comment by Yendric** [comment]
Indeed the issue still occurs on panel 1.0.0-beta.6 with wings v1.0.0 Beta Release 8.

**Comment by DaneEveritt** [comment]
Can you please attach a configuration file that gets messed up by the parser so I can test against it?

**Comment by IAmLythixIAmDumb** [comment]
> Indeed the issue still occurs on panel 1.0.0-beta.6 with wings v1.0.0 Beta Release 8.

Yep. happens here too. Its confirmed to be a known issue now I guess.

**Comment by DaneEveritt** [comment]
After further digging, this is not a bug in Pterodactyl. Even completely disabling the parser still results in the file being modified like that.

And digging into the parser even more, it was working correctly and saving the file as expected but then the server process would trigger a change to that MOTD.

**Comment by lpjn** [comment]
Thanks Dane, however I'm a bit puzzled here.

Any JSON configuration to the server properties file causes the MOTD issue from past experience. Removing all of said configuration fixes it. This has been reported by various people who are using the same workaround. Are we missing something?

**Comment by IAmLythixIAmDumb** [comment]
Personally, I think the issue might be occuring due to the java version used in the containers and how it reads the § symbol in the properties file. It could be possible to re-create this issue outside of a container if the correct java version is installed. 

I might be completely wrong, if I am, please correct me.

**Comment by lpjn** [comment]
Off the back of that though, why is § potentially being used even when it is not specified in the properties, but rather the actual MOTD codes as highlighted in the top post?

This would avoid any potential errors that could be caused by utilising that symbol.

**Comment by IAmLythixIAmDumb** [comment]
It could also be that the § symbol is the same as the motd code, but is being read incorrectly, it tries to fix it, and just makes it worse. There's a lot of things possible that might not even be related to the wings itself, just the java version or incorrect code in the jar file itself.

**Comment by lpjn** [comment]
I think this is getting slightly side tracked. The base issue is that the same MC server using the same java version works on a local machine using the same MOTD code which pterodactyl proceeds to display incorrectly in the server browser with the properties JSON configuration populated. If this is not a bug with pterodactyl, then what can users do to help fix this without outright removing the JSON?

**Comment by IAmLythixIAmDumb** [comment]
The easiest way right now to avoid the issue for now is to use a MOTD plugin like ServerListPlus or something else.

**Comment by kiweezi** [comment]
> 
> 
> Thanks @DaneEveritt , however I'm a bit puzzled here.
> 
> Any JSON configuration to the server properties file causes the MOTD issue from past experience. Removing all of said configuration fixes it. This has been reported by various people who are using the same workaround. Are we missing something?

I agree with @Ipjn. Even if Pterodactyl is not the issue here, would you be able to point people in the direction you think could be causing the problem?

**Comment by DaneEveritt** [comment]
I don't play Minecraft, so I don't know.

All I can tell you is that I completely disabled configuration file edits and it still happened once the process was running, so it's out of my control.

**Comment by DaneEveritt** [comment]
closed by https://github.com/pterodactyl/wings/pull/56
