### ISSUE TITLE
Allow defining additional request origins for Wings websocket

### ISSUE THREAD

**Issue by Corenb** [pterodactyl/panel#2194]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0 beta release 8
* Server's OS: Debian 9
* Your Computer's OS & Browser: Win 10 + Mozilla Firefox

**Describe the bug**
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/1338450/88653825-ddb8c100-d0cc-11ea-8384-d077e9f3048b.gif)
Error in the console when trying to use server console :  https://hastebin.com/ujubukohis.coffeescript

**Comment by DaneEveritt** [comment]
Your hastebin link does not work, please just post the error contents in the issue itself rather than linking out of Github to avoid this issue in the future.

**Comment by Corenb** [comment]
Ok so it's caused by accessing to the panel by a different URL then wich is configured  ?

`ERROR: [Jul 28 11:30:57.031] encountered HTTP/500 error while handling request error=websocket: request origin not allowed by Upgrader.CheckOrigin error_id=605810ff-2aca-4ee4-85e9-8c7ab6f9211e server=8fd72008-b2ac-496c-af4a-9bfe5267baba

Stacktrace:
github.com/pterodactyl/wings/router.(*RequestError).AbortWithStatus
        /home/runner/work/wings/wings/router/error.go:74
github.com/pterodactyl/wings/router.(*RequestError).AbortWithServerError
        /home/runner/work/wings/wings/router/error.go:95
github.com/pterodactyl/wings/router.getServerWebsocket
        /home/runner/work/wings/wings/router/router_server_ws.go:16
github.com/gin-gonic/gin.(*Context).Next
        /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/pterodactyl/wings/router.ServerExists
        /home/runner/work/wings/wings/router/middleware.go:66`

**Comment by DaneEveritt** [comment]
Yes.
