### ISSUE TITLE
Time not displayed correctly

### ISSUE THREAD

**Issue by IAmLythixIAmDumb** [pterodactyl/panel#2195]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v1.0 beta 6
* Server's OS: Ubuntu 18.04 LTS Bionic
* Your Computer's OS & Browser: Ubuntu 20.04 Focal, Google Chrome latest.

**Describe the bug**
The panel displays date and time wrong such as this in schedules:
![image](https://user-images.githubusercontent.com/54075275/88728018-138f9100-d131-11ea-9c42-3ab00d27b272.png)

**To Reproduce**
1. Create a schedule
2. Have the schedule run
3. See possibly incorrect date
**Expected behavior**
Panel displays the date and time correctly

**Comment by parkervcp** [comment]
The time and date displayed is based on the server time not on your computer or local time.

**Comment by IAmLythixIAmDumb** [comment]
Should be fixed soon anyways so...
![9C0814F5-1A85-42A6-A3E7-7749D262C50C](https://user-images.githubusercontent.com/54075275/88788712-048efa00-d196-11ea-86e3-c781651d3968.jpeg)
