### ISSUE TITLE
Container ID or 'pretty' name in file manager

### ISSUE THREAD

**Issue by LaurenceMillward** [pterodactyl/panel#2197]
Hi

I often have many tabs open for various containers, some of which have a very similar file structure. In BETA 6 (I assume all the previous ones too) I have no idea which container i'm editing so have to jump out and into the Console to double check. 

This request is to make it more clear which files are being edited in which container. Screenshot attached shows I have 3 different containers file managers open, however I have no idea which one it is.

![ptera](https://user-images.githubusercontent.com/26876521/88951626-279cd500-d28e-11ea-864f-1031b8a65049.png)

Thanks

**Comment by IAmLythixIAmDumb** [comment]
If you're managing multiple containers, why did you give all of them the same name? I think if you changed the name of them you would know which one is which easier.

**Comment by LaurenceMillward** [comment]
@IAmLythixIAmDumb  They don't have the same name, the <title> header of the page only reflects the sites name, not the containers name.

**Comment by IAmLythixIAmDumb** [comment]
> @IAmLythixIAmDumb They don't have the same name, the <title> header of the page only reflects the sites name, not the containers name.

Ah right, I'm too used to the 0.7.X series.

**Comment by matthewpi** [comment]
Related to https://github.com/pterodactyl/panel/pull/1916

**Comment by Sir3lit** [comment]
I'm working on a new pr to replace that one. The new PR is going to use react helmet to manage the page title and follows the same format of `server name | pagw`
