### ISSUE TITLE
Schedule might be created twice if you click fast.

### ISSUE THREAD

**Issue by IAmLythixIAmDumb** [pterodactyl/panel#2199]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0 Beta 6
* Server's OS: Ubuntu 18.04 Bionic
* Your Computer's OS & Browser: Ubuntu 20.04, Chrome (Latest)

**Describe the bug**
When creating a schedule if you press the button to create 2 times quickly (which some users do as they expect things to react instantly) the schedule is created twice.
![issue](https://user-images.githubusercontent.com/54075275/88968353-7c9d1300-d2af-11ea-8bf3-a2215f0c68dd.gif)

**To Reproduce**
1. Go to the schedules tab,
2. Start creating a schedule
3. Press the create button twice like a impatient person and see it create twice.

**Expected behavior**
The panel will start processing the first click and ignore the second click.
Then only create the schedule once.

**Comment by Sir3lit** [comment]
I mean clicking it twice will send the request twice.... Not sure what else you'd expect to happen. Maybe disable the button once clicked.

**Comment by IAmLythixIAmDumb** [comment]
> I mean clicking it twice will send the request twice.... Not sure what else you'd expect to happen. Maybe disable the button once clicked.

I know that lol. I’m just making sure this is fixed so that people who aren’t patient and press multiple times don’t have to delete extra schedules if you get what I mean.

**Comment by IAmLythixIAmDumb** [comment]
I mean, this seems like a pretty minor thing to report. I'll close it for now, and then someone can pick up on it later if they want to.
