### ISSUE TITLE
Remove multiple ports at a time

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#220]
When removing ports they need to be removed one at a time.

The option to select more than one port and mass remove would be a good improvement

**Comment by Edbtvplays** [comment]
maybe a mass add feature aswell so you can select a range of ports that you would like to be added and it will add all the ports in bettween saves time if you have 10 + ports you need to add

**Comment by parkervcp** [comment]
You can already add a range of ports. The limit is something like 2000 at a time.

**Comment by parkervcp** [comment]
This was resolved. I'll close this out.
