### ISSUE TITLE
500 error when renaming a file that doesn't exist

### ISSUE THREAD

**Issue by matthewpi** [pterodactyl/panel#2200]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: develop (not sure what commit)
* Server's OS: CentOS 8
* Your Computer's OS & Browser: MacOS Big Sur (Developer Beta), Safari 14.0 (16610.1.21.1.2)

**Describe the bug**
When renaming a file that does not exist a 500 error is returned instead of a 400 or 404.

**Steps to Reproduce**
1. Send an API Request to Rename a file. (Set `from` to a file that doesn't exist, `to` shouldn't matter)
2. See that wings returned a 500 error.

For my testing I sent the following request:
```
PUT /api/client/servers/e0182b5b-705b-44ee-92d1-be27f44d00a7/files/rename HTTP/1.1
Authorization: Bearer <REDACTED>
Accept: application/json
Content-Type: application/json; charset=utf-8
Cookie: <REDACTED>
Host: <REDACTED>
Connection: close
User-Agent: Paw/3.1.10 (Macintosh; OS X/10.16.0) GCDHTTPRequest
Content-Length: 77

{
     "root": "/",
     "files": [
          {
               "to": "server.properties",
               "from": "server.properties2"
          }
     ]
}
```

Wings Stacktrace:
```
ERROR: [Jul 31 18:38:17.007] encountered HTTP/500 error while handling request error=stat /var/lib/pterodactyl/volumes/e0182b5b-705b-44ee-92d1-be27f44d00a7/server.properties2: no such file or directory error_id=6f647a61-75a6-4749-86b6-e8e167509746 server=e0182b5b-705b-44ee-92d1-be27f44d00a7

Stacktrace:
github.com/pterodactyl/wings/router.(*RequestError).AbortWithStatus
        router/error.go:74
github.com/pterodactyl/wings/router.(*RequestError).AbortWithServerError
       router/error.go:95
github.com/pterodactyl/wings/router.putServerRenameFiles
        router/router_server_files.go:138
github.com/gin-gonic/gin.(*Context).Next
        /root/.golang/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/pterodactyl/wings/router.ServerExists
       router/middleware.go:66
```

UPDATE:
Also occurs when decompressing or copying a file.
Delete returns a 204 regardless of if the file exists or not.

**Expected Behaviour**
Response should be a 400 or 404, not a 500.

**Comment by IAmLythixIAmDumb** [comment]
The same thing also happens when extracting archives.
