### ISSUE TITLE
SMTP E-mail Bug

### ISSUE THREAD

**Issue by Matteolibeert** [pterodactyl/panel#2201]
**Background:** Okay , so i was testing my SMTP and trying out the 'I forgot my password' button.
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.18
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10, Revamped Edge

**Describe the bug*
Okay, so the issue is that when you press the button, sending the e-mail is not instant it takes around 15 minutes to receive the email. But the test button for SMTP settings is instant.
Please provide additional information too, depending on what you have issues with:
Panel: PHP 7.2.32-1+ubuntu18.04.1+deb.sury.org+1

**To Reproduce**
1. Go to 'Auth page (logout)'
2. Click on 'I forgot my password'
3. Type your account email.
4. Check your account email.

**Comment by parkervcp** [comment]
I fail to see how this is a system bug. When a user requested a password reset it gets out into a queue to send the email in a batch.

**Comment by DaneEveritt** [comment]
Sounds like an issue with your queue worker or email provider. Some systems greylist emails for spam reasons which can add a significant delay. If the email is sending then it is out of the control of this software.
