### ISSUE TITLE
Renaming of file/ folders from panel is failing

### ISSUE THREAD

**Issue by kruthers** [pterodactyl/panel#2203]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel Beta 6
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
When using the panel file browser when renaming files the rename window will instantly close on most files.
![Rename Failing](https://user-images.githubusercontent.com/10118799/89112015-0a663300-d455-11ea-9f40-ed124af994c5.gif)
Panel: `php 7.4.3`

**To Reproduce**
1. Go to `File Manager`
2. Right click on any file
3. Select rename

**Expected behavior**
The rename entry box will open and allow you to rename a file

**Comment by Sir3lit** [comment]
The issue seems to be that the page gets reloaded when the box appears causing it to act as a page refresh.
