### ISSUE TITLE
Captcha not disabling 

### ISSUE THREAD

**Issue by Jouniora** [pterodactyl/panel#2208]
* Panel or Daemon: Panel
* Version of Panel/Daemon: Latest I think 7.0
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows, Chrome

My issue is that I was testing my google captcha key so I logged out right, but I couldn’t log in cause the key had an issue, So I can’t log back in to disable it, I tried setting RECAPTCHA_ENABLED=false in my .env but it didn’t work. Any Ideas?

**Comment by Jouniora** [comment]
And me.admin it’s correct

**Comment by DaneEveritt** [comment]
Try running `php artisan config:clear`.

**Comment by Jouniora** [comment]
I tried that and tried the view:clear or whatever and it still didn’t work.

**Comment by matthewpi** [comment]
What is the `APP_ENVIRONMENT_ONLY` value set to in your `.env`?

**Comment by Jouniora** [comment]
The production one?

**Comment by Jouniora** [comment]
Ohh, its false

**Comment by DaneEveritt** [comment]
From the information provided this does not appear to be a bug with this software.

Please use discord for further support. https://pterodactyl.io/discord
