### ISSUE TITLE
Bad gateway while under DDoS (huge amount of connections)

### ISSUE THREAD

**Issue by Games4k** [pterodactyl/panel#2209]
**Background (please complete the following information):**
* Panel or Daemon: panel
* Version of Panel/Daemon: 0.7.18
* Server's OS: Linux Ubuntu 18.04
* Your Computer's OS & Browser: Safari, macOS

**Describe the bug**
Well, the problem is that when there is a DDoS attack that gets through CloudFlare (for example) it is enough to take Pterodactyl completely down. In my current example, I have a homepage and panel. While under an attack, my homepage is able to handle the attack without any issues, however, Pterodactyl always reports Bad Gateway. The amount of the traffic that passes through is not significant - about 50mb/s, and the machine is powered by i9 9900K, which can handle such an attack quite easily. The point is, all the websites stay up while under attack, but only pterodactyl can't handle larger amount of connections, which may be due to some internal error. I was looking to get error log, but sadly, there wasn't any. The same happened to everyone I know, and was fixed in 1.0.0 beta, but until than, maybe a hotfix for other versions would be great.
**To Reproduce**
1. Launch a stress test (Layer 7) on any of your websites. If some traffic passes through whatever filter you have, Pterodactyl will report Bad Gateway error
**Expected behavior**
Pterodactyl should be able to handle larger amount of traffic with Pugh significant issues.

If you have any additional questions, please let me know.

**Comment by TrixterTheTux** [comment]
You need to configure php-fpm properly to handle your wanted amount of traffic, the traffic never actually reaches Pterodactyl for it to be an issue with it.

**Comment by matthewpi** [comment]
I do not understand how this is an issue or a bug with Pterodactyl.  If a Bad Gateway error is being returned that is due to PHP either being timed out or the database is struggling to handle with the load.

**Comment by itsgatto** [comment]
This is not an issue of the software itself but of your setup.

You're probably going over what your php-fpm config can handle based on the workers, way of scaling, etc. Tweaking it a bit should let you use a certain amount of processing power (defined by you) or all of it.

**Comment by Games4k** [comment]
Thank you very much for your help guys. I'll check it out and reopen it if needed.
