### ISSUE TITLE
Bootstrap row overflow due to too long FQDN

### ISSUE THREAD

**Issue by simpleauthority** [Pterodactyl/Panel#221]
See this picture: 
![img](http://i.imgur.com/r34Rzva.png)

I have long FQDNs. Most users may not, however due to this long FQDN the bootstrap row overflows. It may be resolved by resizing the text for abnormally long FQDNs.

This is not a usability issue, just a cosmetic issue and bothers me a bit. :)

**Comment by DaneEveritt** [comment]
Closed with new theme.
