### ISSUE TITLE
Automatically skipping question if panel/database has been installed while installing daemon

### ISSUE THREAD

**Issue by RamonRobben** [pterodactyl/panel#2210]
**Is your feature request related to a problem? Please describe.**
Some people just don't read text above a question clearly.

**Describe the solution you'd like**
Automatically skip the question if a MySQL instance is detected on the system.

**Describe alternatives you've considered**
None.

**Additional context**
Small addition to the script. After you have installed only the panel and want to install the daemon using the same script. It tells you that if you have the panel installed you should answer no to the next question. But can't this just be skipped since you can just check if a panel has been installed and then skip that option for the user by default?

Referring to when it asks if you want to install MariaDB in the daemon script.

**Comment by fabm3n** [comment]
There is no official install script.

**Comment by RamonRobben** [comment]
> There is no official install script.
Sorry wrong github haha.
