### ISSUE TITLE
SFTP Slow and won't handle too much request

### ISSUE THREAD

**Issue by Adrawyn** [pterodactyl/panel#2221]
Hi,
when I use the sftp provided by the new wings system ( bug that i didn't have in the release version ).

Some of my transfers are getting canceled for the reason: File transfer interrupted by user
in Filezilla

But when i use WinSCP my transfer fail and the sftp keep asking me the password.

**Comment by mattmalec** [comment]
Have you considered trying the standalone SFTP server? https://pterodactyl.io/daemon/0.6/standalone_sftp.html

**Comment by matthewpi** [comment]
> Have you considered trying the standalone SFTP server? https://pterodactyl.io/daemon/0.6/standalone_sftp.html

User is using the 1.0 beta which includes the standalone SFTP server.

**Comment by Adrawyn** [comment]
Uh i think that i have an hint, it's maybe related to MaxAuthTries: 6 in the sftp initializer method.

When i transfer a huge amount of data authentication may failed sometimes and 6 is a little bit too short for a big amount of files i think.

**Comment by Sir3lit** [comment]
I wouldn't consider it "slow". Seems that it currently only allows 4 concurrent connections. I feel an easy solution would be to allow it to be configurable within wings config file under the `sftp:` section

**Comment by Adrawyn** [comment]
Where did you see that it currently allows 4 concurrent connections?

**Comment by Sir3lit** [comment]
That was the max concurrent connections I could get before it failed to connect. Filezilla you can set concurrent connections for downloads. Anything 5 and over they failed. Only the first 4 would connect and proceed to download.
