### ISSUE TITLE
sftp: High CPU usage when downloading files, increases with more downloads active

### ISSUE THREAD

**Issue by AreYouRlyScared** [pterodactyl/panel#2225]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: Wings Beta 7
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win10 / Chrome

**Describe the bug**
Downloading files results in ~9.5% CPU usage PER connection downloading...Both results are achievable by downloading via sftp client or via file manager.  

**One file download results in 7-12% usage.**
![](https://justmyrandomstuff.com/img/tF4mhfU.gif)

**Two files being downloaded results in 18-24% usage.**
![](https://justmyrandomstuff.com/img/ICiMc1p.gif)

**To Reproduce**
1. Download files

**Expected behavior**
CPU usage not be as high?

**Comment by Adrawyn** [comment]
I've tested it, and have the same problem, cpu will reach 90% easily.

**Comment by matthewpi** [comment]
Related to #2221 most likely.  This is also linked to https://github.com/pkg/sftp/issues/334 which explains that performance is similar but with noticeably higher CPU usage, I believe the packages were all updated on the `sftp-server` which should help partially.  This issue is not going to really be possible to fix as the bottleneck is with ssh encryption.

![BiOFccKa51PMuEEJ](https://user-images.githubusercontent.com/26559841/90988708-2cce0680-e552-11ea-9802-b35d11f10500.png)

**Comment by ChocolateRoll** [comment]
How is this low priority 😂😂

**Comment by zKoz210** [comment]
Need update to https://github.com/pkg/sftp/releases/tag/v1.12.0

**Comment by schrej** [comment]
The priority is low as this is not really a direct issue of pterodactyl/wings and also I think Dane wasn't really able to reproduce it.
pkg/sftp v1.12 does at least claim that it improves the situation, so it might be resolved by simply upgrading the library.

**Comment by notAreYouScared** [comment]
Have we updated that library in 1.0.2?

**Comment by schrej** [comment]
nope

**Comment by BenasPaulikas** [comment]
Any plans to implement ftp bandwith limit ? if no - why ? Any limits ?

**Comment by DaneEveritt** [comment]
This has nothing to do with bandwidth limiting.

**Comment by DaneEveritt** [comment]
If this is still happening I'm just going to write it off as a dependency issue and not something I can really do much of anything about.
