### ISSUE TITLE
Account Security

### ISSUE THREAD

**Issue by keiney20** [pterodactyl/panel#2228]
**Is your feature request related to a problem? Please describe.**
Active Sessions
Your host has not enabled the ability to manage account sessions via this interfac [...]

**Describe the solution you'd like**
Right now, i am running a user demo to test my panel for everyone, the problem is that it show all ips connected in security page.
How i can turn off this in the panel? is this option added in some config file? If not, can be cool add it to show users a demo of our panels.

**Comment by schrej** [comment]
Set the [session driver](https://github.com/pterodactyl/panel/blob/0.7-develop/config/session.php#L18) to something else than `database` and the session list won't be visible.

**Comment by keiney20** [comment]
I like add in this section for all people that doesn't understand it well, that you need change in .env `SESSION_DRIVER=database` to `SESSION_DRIVER=redis` and it won't show more.
