### ISSUE TITLE
Variables with 0 value considered as empty

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#223]
IF you set a variable with a value of 0, it is considered as empty. 
You can verify it by creating a new variable in a service, set the variable as required with a value and 0 and the panel will throw you an error saying the variable should'nt be empty.

https://gyazo.com/762709e4df107a937c95620b7790ca5b

**Comment by DaneEveritt** [comment]
I'm not able to reproduce this when adding a new variable. I was able to successfully create a variable with a default value of `0`.

**Comment by DaneEveritt** [comment]
Oh, actually I see. The error occurs when adding a new server.
