### ISSUE TITLE
Users are not able to change variables

### ISSUE THREAD

**Issue by RamonRobben** [pterodactyl/panel#2230]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-beta-7 
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 Pro 1909, Chrome (Latest)

I've asked this in the Discord: "If you have variables in your egg how are people/users able to change that? I am using 1.0.0-beta panel but I don't see any way to edit those even though I set them to viewable by user and editable by user." And got a response saying "They are editable". After some more looking and testing I give up and am now writing this bug report.

**Describe the bug**
I'm not sure if its exactly a bug or just a feature that's missing in this newer version.
But there doesn't seem to be ANY way for a user to edit variables even if the permissions are set to "Users can view, Users can edit" and because the permissions exists I think this feature probably hasn't been implemented yet or has been accidentally forgotten about.

It only seems possible for Admins to change the variables but not for users.

**To Reproduce**
1. Make an EGG with at least 1 variable.
2. Set those variable permissions to be viewable by users and editable by users
3. Log into a user account (NO ADMIN)
4. Try to edit the variables (e.x server.jar filename)

**Expected behavior**
I thought I could change those variables at the settings tab but I couldn't find them there.
Otherwise I would've expected a tab saying Variables maybe.

I looked through the github for existing issues containing the word "Variable" or "Variables" but couldn't find any so sorry if this is a duplicate of another issue except worded differently.

**Comment by matthewpi** [comment]
Assuming this is related to #2215 

Also for future note, unimplemented behavior is not a bug and doesn't need to be filled out as a bug report.
