### ISSUE TITLE
Laravel Error SMTP

### ISSUE THREAD

**Issue by Hydra2k** [pterodactyl/panel#2232]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.18
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10; Chrome

Massive error while configuring mail.
Panel: 7.2.32
Daemon: 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
1. Mail tab in admin settings
2. Configure mail like attached image.
3. Save and test

#EDIT: https://hastebin.com/fubusumena.shell; It says this when getting logs and I don't know how to get stacktrace.
![Capture2](https://user-images.githubusercontent.com/63931572/89725754-ce951580-d9e0-11ea-9538-38725bf3bd65.PNG)

Should come up with a lot of laravel errors.
![Capture](https://user-images.githubusercontent.com/63931572/89725606-42362300-d9df-11ea-8212-3a28223ddcc7.PNG)

**Comment by matthewpi** [comment]
When making an issue that involves an error, please post the actual error message, logs, and stacktrace.

**Comment by Hydra2k** [comment]
Edited

**Comment by fabm3n** [comment]
The command to get error logs fails because there aren't any of them.

Can you provide more informations what your actual problem is?

**Comment by DaneEveritt** [comment]
This is unlikely to be an issue with this software, rather an issue with your mail setup. Please use discord for further assistance.
