### ISSUE TITLE
Daemon is not reading out the data of one server sometimes

### ISSUE THREAD

**Issue by JanDevDE** [pterodactyl/panel#2238]
**Background (please complete the following information):**
* Panel or Daemon: Panel & Daemon
* Version of Panel/Daemon: 1.0.0-beta.7 & 1.0.0-beta.9
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Chrome

**Describe the bug**
After restarting the daemon, one of the servers will not show disk usage on the main page.
When clicking on that server in the main page, all statistics except the status of the server are not available.
If the server is started, it can still be stopped. After stopping it cannot be started again.
(Yes, I agree that's a pretty specific/weird problem.)

**To Reproduce**
1. Have some servers running.
2. Restart the daemon
3. Visit the main page of the panel to see the problem / Click on a server to see the problem
4. Restart the daemon, this time the same problem will occur on another random server.

**Expected behavior**
Daemon should read all servers statistics correctly.

**Screenshots**
![Mainpageafterrestart](https://user-images.githubusercontent.com/11154004/90314086-5a430080-df11-11ea-851a-f6762f594962.PNG)

![Serverafterademonrestart](https://user-images.githubusercontent.com/11154004/90314085-59aa6a00-df11-11ea-9fa7-8c7f062878a5.PNG)

**Comment by matthewpi** [comment]
Fixed in https://github.com/pterodactyl/wings/pull/48

**Comment by fabm3n** [comment]
I'm currently on the latest dev build and my Memory and CPU Usage doesn't work at all.
Thats from my Browser Console:
![image](https://user-images.githubusercontent.com/11352551/90317950-2675d400-df2d-11ea-83d4-d9dceccf7348.png)
