### ISSUE TITLE
Built-in Web File Manager throws JS Errors

### ISSUE THREAD

**Issue by imWillX** [Pterodactyl/Panel#224]
**Test Enviroment**
Panel (`0.5.5`) 
Dameon (`0.3.7`)
Chrome: `55.0.2883.87 (Official Build) m (64-bit)`

Tested with Icognito.

**Issue**
Where? Server Panel File Manager
What? Unable to to perform actions such as *move, rename, copy, download, delete*.
Error:
<pre>Uncaught ReferenceError: ActionsClass is not defined
    at ContextMenuClass.showMenu (contextmenu.js:21)
    at HTMLTableCellElement.$.on.event (contextmenu.js:17)
    at HTMLTableCellElement.dispatch (jquery.js:4732)
    at HTMLTableCellElement.r.handle (jquery.js:4544)</pre>

**Comment by DaneEveritt** [comment]
Thanks, appears that we need to transpile to ES5 standards since not all browsers support ES6.

I'm thinking that for releases I will run a transpiler to create the corrected files for use, while the development branch will remain on ES6 since that is significantly easier to maintain.

**Comment by schrej** [comment]
Do we have something like grunt or gulp (i prefer gulp)? We could add it project wide and add everything needed for releases there. Minify CSS, babel and minify JS and so on. Then anyone can run it to test if their changes work.
