### ISSUE TITLE
No CPU and Memory Data displayed

### ISSUE THREAD

**Issue by fabm3n** [pterodactyl/panel#2240]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: latest dev buiöd
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Chrome 84

**Describe the bug**
CPU and Memory data were not displayed at all.
![image](https://user-images.githubusercontent.com/11352551/90318099-61c4d280-df2e-11ea-8c38-8422eb31d8d3.png)
![image](https://user-images.githubusercontent.com/11352551/90318104-6c7f6780-df2e-11ea-9d29-06aea2dd3b6c.png)

Browser Console: 
![image](https://user-images.githubusercontent.com/11352551/90318090-45c13100-df2e-11ea-9afb-8882cf21d15e.png)

**To Reproduce**
1. Go to the main server overview or to a server console
2. See error

**Expected behavior**
You can see all stats

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/wings/commit/5b241fdf36a995acbf7169b81bb45a16d6bf4a7c
