### ISSUE TITLE
Time Out Install

### ISSUE THREAD

**Issue by Alexop137** [pterodactyl/panel#2242]
![image](https://user-images.githubusercontent.com/49793786/90326741-a08d7380-df94-11ea-83f3-84a068588ce0.png)

![image](https://user-images.githubusercontent.com/49793786/90326746-adaa6280-df94-11ea-9463-17ba2d3b6471.png)

**Comment by matthewpi** [comment]
Please use Discord for support, only use issues for reporting actual bugs or problems.  Also, if there is a problem with the documentation you should create an issue or pull request on the [documentation](https://github.com/pterodactyl/documentation) repository, not the panel repository.
