### ISSUE TITLE
Daemon issues with a big host

### ISSUE THREAD

**Issue by danielpmc** [pterodactyl/panel#2246]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: Latest (0.6.13)
* Server's OS: Debian 10
* Your Computer's OS & Browser: Chrome latest.

**Describe the bug**
A clear and concise description of what the bug is: Daemon using 98% CPU usage. When i kill the daemon cpu usage goes to 20 - 30% (This happens right after the node got over 250+ servers and happens on multipe nodes with the same amount of servers) 
Please provide additional information too, depending on what you have issues with: issue goes when wings is stopped. when its started it goes back up to 98% cpu usage. built in SFTP server is disabled and im using external sftp server.
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
uname -a: Linux Node1 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
docker info: `root@Node1:~# docker info
Client:
 Debug Mode: false

Server:
 Containers: 369
  Running: 122
  Paused: 0
  Stopped: 247
 Images: 21
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-9-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 9.759GiB
 Name: Node1
 ID: WVBV:F446:FARO:54GG:DCMY:2DLO:UI6F:G2JM:IDRY:5YV7:CJDY:FMGY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
root@Node1:~#
`

**To Reproduce**
Steps to reproduce the behavior: Run over 250 servers (this doesnt happen instantly over that limit but the more servers. the more it happens

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem: the daemon to work normally.

**Comment by danielpmc** [comment]
i also have a node with 300+ servers. 20gb ram 32cpu cores. that has the exact same issue and does the exact same thing when i stop wings

**Comment by danielpmc** [comment]
some issues while i had it in `npm start`

17:36:49.348Z  INFO wings: Daemon detected that the server container is currently running, re-attaching to it now! (server=e25dd86e-743d-417a-b22d-db1537388cb3)
17:37:20.796Z  INFO wings: Configuring websocket for daemon stats...
17:39:45.847Z  INFO wings: Pterodactyl Daemon is up-to-date!
17:39:45.929Z  INFO wings: Pterodactyl Daemon is now listening for secure connections on 0.0.0.0:8080
17:49:25.410Z FATAL wings: A fatal error occured during an operation.
    SyntaxError: Unexpected token l in JSON at position 68
        at JSON.parse (<anonymous>)
        at Tail.logStream.on.data (/srv/daemon/src/controllers/docker.js:248:40)
        at Tail.emit (events.js:198:13)
        at Tail.EventEmitter.emit (domain.js:448:20)
        at ReadStream.stream.on (/srv/daemon/node_modules/tail/lib/tail.js:44:31)
        at ReadStream.emit (events.js:198:13)
        at ReadStream.EventEmitter.emit (domain.js:448:20)
        at addChunk (_stream_readable.js:288:12)
        at readableAddChunk (_stream_readable.js:265:13)
        at ReadStream.Readable.push (_stream_readable.js:224:10)
18:04:27.861Z  WARN wings: Unable to determine size of server data folder, exited with code 1 signal null. (server=f6e5228d-9a88-4d1a-917c-2abeb90b3bdc)
    Error: Unable to determine size of server data folder, exited with code 1 signal null.
        at ChildProcess.Exec.on (/srv/daemon/src/controllers/fs.js:89:29)
        at ChildProcess.emit (events.js:198:13)
        at ChildProcess.EventEmitter.emit (domain.js:448:20)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
18:12:35.768Z  WARN wings: Unable to determine size of server data folder, exited with code 1 signal null. (server=0d74cf88-c917-465a-93d7-bb7357c3902d)
    Error: Unable to determine size of server data folder, exited with code 1 signal null.
        at ChildProcess.Exec.on (/srv/daemon/src/controllers/fs.js:89:29)
        at ChildProcess.emit (events.js:198:13)
        at ChildProcess.EventEmitter.emit (domain.js:448:20)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

**Comment by yourboyjoe** [comment]
hi shawty <3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3

**Comment by Kyle8973** [comment]
Hey Joeeee

**Comment by flashmaster303** [comment]
Agreed. there has been multiple issues with the nodes; especially with Daemon.

**Comment by DaneEveritt** [comment]
I won't be putting any effort into addressing these issues, sorry. The current daemon is effectively on life-support as I work to get the new Go based daemon out the door. This new daemon has significant performance improvements, and improves many aspects of the Nodejs daemon that have not scaled well.

Unfortunately this means there isn't really a good resolution for you. My only recommendation would be spreading out the server load a bit more, since the daemon is not going to handle 200+ servers on a machine with 10GB of memory and limited CPU availability very well, not to mention the IO impacts of all those server processes running in addition to the daemon trying to handle file management and boot actions for all of them.

Its pretty much a recipe for disaster with the currently codebase we're working with. There are other hosts who have made this work, but I believe most have just disabled disk space checking and permissions stuff on boot, either deferring them to server startup or just not running them at all. You can probably ask around on the Discord server to get some more specifics from them.
