### ISSUE TITLE
Panel docker image seems private

### ISSUE THREAD

**Issue by marier-nico** [pterodactyl/panel#2248]
Hello and thanks for this awesome project!

I've been using this for some time now, and I just noticed there was an example `docker-compose` file in the repo. I was really happy to see it, because Docker is convenient for me, but when I went to try it, I was not authorized to pull the image. Is this expected? If so, would it be possible to get a public Docker image for the panel once again? :smile: 

```
$ docker pull quay.io/pterodactyl/panel:latest
Error response from daemon: unauthorized: access to the requested resource is not authorized
```

**Comment by parkervcp** [comment]
There is no image built there. It's a stand in for an image.

**Comment by marier-nico** [comment]
I see! So is the Dockerfile in the repo for testing? Or is an official means of installing the panel? I wasn't really able to find documentation about using Docker for the panel, so I was a bit unsure. In any case, would it be fair to reopen this as a feature request? I think having an official docker image for the panel would be super cool. :slightly_smiling_face:

**Comment by marier-nico** [comment]
That's pretty sweet! I'll definitely look into it then.

I'm sure others would be happy to know that it's possible to use Docker for the panel, so maybe adding it to the official documentation could be a nice add-on (but really up to you).

Thanks again!
