### ISSUE TITLE
<code> tags are hard to read

### ISSUE THREAD

**Issue by linusstretchtips** [pterodactyl/panel#2254]
The font colour (currently light grey) is difficult to read on a white background

Example:
![image](https://user-images.githubusercontent.com/64327566/91027573-2e500b00-e5f4-11ea-9627-fda18f97f6c0.png)

**Comment by fabm3n** [comment]
Issue occours on "old" edge. @linusstretchtips can you provide a browser version?

**Comment by DaneEveritt** [comment]
@LeCodeCo Looks like something in the admin area, since you handled that quick reskin would you be able to double check on this?

**Comment by fabm3n** [comment]
![image](https://user-images.githubusercontent.com/11352551/91064661-d59e6380-e62f-11ea-9676-8949bc971222.png)

Thats the comparison picture from discord.

**Comment by DaneEveritt** [comment]
Oh, if it is in old edge I'm closing this since thats hardly a supported browser and we're redoing all of the admin area soon anyways.
