### ISSUE TITLE
EAI_AGAIN panel version 0.7 with ubuntu 18.04 LTS. Windows 10 with Firefox and chrome.

### ISSUE THREAD

**Issue by DrTableBasse** [pterodactyl/panel#2260]
*Panel or Daemon : Panel
*Version on Panel/ Daemon : 0.7
*Server's OS : Ubuntu 18.04 LTS
*Your Computer's OS & Browser : Windows 10 with Chrome and Firefox

The bug is on the screen with this post, when i'm logged etc... i have gateway error for the status of every session. 
My hostname is sopernetwork.com

```11:58:30.846Z  INFO wings: + ------------------------------------ +
11:58:30.847Z  INFO wings: | Running Pterodactyl Daemon v0.6.13    |
11:58:30.847Z  INFO wings: |        https://pterodactyl.io        |
11:58:30.847Z  INFO wings: |                                      |
11:58:30.847Z  INFO wings: |  Copyright 2015 - 2020 Dane Everitt  |
11:58:30.847Z  INFO wings: |           and contributors           |
11:58:30.847Z  INFO wings: + ------------------------------------ +
11:58:30.847Z  INFO wings: Loading modules, this could take a few seconds.
11:58:30.994Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
11:58:31.020Z  INFO wings: Configuring user pterodactyl (id: 999) as the owner of all server files.
11:58:31.022Z  INFO wings: Configuring timezone file location...
11:58:31.022Z  INFO wings: Checking container networking environment...
11:58:31.025Z  INFO wings: Found network interface for daemon: pterodactyl_nw
11:58:31.025Z  INFO wings: Ensuring correct network interface for containers...
11:58:31.029Z  INFO wings: Networking gateway detected as 172.18.0.1 for interface: pterodactyl0.
11:58:31.030Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
11:58:31.034Z FATAL wings: A fatal error caused the daemon to abort the startup. (err.code=EAI_AGAIN)
    Error: getaddrinfo EAI_AGAIN sopernetwork.com sopernetwork.com:443
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
    --
    additional: {
      "errno": "EAI_AGAIN",
      "code": "EAI_AGAIN",
      "syscall": "getaddrinfo",
      "hostname": "sopernetwork.com",
      "host": "sopernetwork.com",
      "port": 443
    }
11:58:31.034Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.
``` 
but thx for the last link but nothing working :-/ i tried my best to understand and patch it but nothing
Screen of result 
![image](https://user-images.githubusercontent.com/34471493/91045073-9283c680-e616-11ea-8f68-88c175229484.png)

**Comment by NickEvansDev** [comment]
Is your panel on the same system as the node?

**Comment by DrTableBasse** [comment]
Yeap it's on the same system

**Comment by parkervcp** [comment]
1. I said to fill out the template you have ignored twice now.
2. I said to reopen the old issue

**Comment by parkervcp** [comment]
That's still not the template.

**Comment by parkervcp** [comment]
Can you ping the hostname from the server itself. It honestly looks like it's having issues resolving that address.

**Comment by DrTableBasse** [comment]
> 
> 
> Can you ping the hostname from the server itself. It honestly looks like it's having issues resolving that address.

it's sopernetwork.com i said it

**Comment by parkervcp** [comment]
That doesn't answer the question I asked. 

I asked if the server can ping itself on that hostname.

**Comment by DrTableBasse** [comment]
nop ```teomporary failure in name resolution```

**Comment by parkervcp** [comment]
So that is your problem. You server cannot resolve the hostname. Like I said before. This is a DNS issue.

**Comment by DrTableBasse** [comment]
ok i fixed it, ufw do shit :derp: sorry and thx u
