### ISSUE TITLE
Saving a file with control + s in the text editor creates a new file/folder with the contents of the file as the name

### ISSUE THREAD

**Issue by danny6167** [pterodactyl/panel#2266]
**Background (please complete the following information):**
* Panel or Daemon:  Panel
* Version of Panel/Daemon:  develop branch (tested at 9e60cf9f5399511957794e3498e31adb79162164)
* Server's OS: Debian 10, panel running in docker.
* Your Computer's OS & Browser:  Windows 10 / Chrome

**Describe the bug**
Saving a file with control + s in the text editor creates a new file/folder with the contents of the file as the name.

**To Reproduce**
1. Open a text file with contents in the editor
2. Press Control + S - you must be selected inside the text area
3. See that the file name you were editing has been changed to a name using the contents of the file and that a file with that name has been created.

**Expected behavior**
Control + S should save the file correctly just as the SAVE CONTENT button currently does.

![image](https://user-images.githubusercontent.com/388231/91148532-5e7ad500-e6ec-11ea-9f2c-79b51646cbaa.png)
![image](https://user-images.githubusercontent.com/388231/91148570-6b97c400-e6ec-11ea-9210-d2cf68ce75be.png)

**Comment by Corenb** [comment]
I've the same issue with the RC1 version
![Screenshot_2020-08-25 Horyzon Proxy File Manager](https://user-images.githubusercontent.com/1338450/91170491-40f04000-e6d9-11ea-8c21-969f5fc61173.png)
