### ISSUE TITLE
The text doesn't resize on the admin boxes

### ISSUE THREAD

**Issue by INfoUpgraders** [pterodactyl/panel#2270]
* Panel
* Version of Panel: 1.0
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Ubuntu 18.04 & Firefox

**Describe the bug**
The text in the box with the icon doesn't resize to your screen
![idk](https://gyazo.com/9b7012bcc7f56c64ca262fa94dba3594.png)

**To Reproduce**
1. Create a server
2. Go to the admin panel of the server
3. Make your screen small

**Expected behavior**
For the text to resize to the box.

**Comment by DaneEveritt** [comment]
Wont fix, will be solved with the future admin area rewrite.
