### ISSUE TITLE
Servers with a large amount of files hang with no feedback on startup

### ISSUE THREAD

**Issue by cyberkitsune** [pterodactyl/panel#2272]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 / Chrome

**Describe the bug**
In Wings 1.0, when starting a server with many files (in my case 15 million) the `Filesystem.Walk` and `Filesystem.Chown` operations on server startup take a very very long time (Over 15+ minutes)

With Daemon 0.7 you could disable ensuring file permissions to halve the wait time as a workaround 

**To Reproduce**
1. Create a new game server
2. Create a bunch of files (`touch` in a for loop could work)
3. Attempt to power on the server
4. Server will be marked as starting and "nothing" would appear to happen for a long time

**Expected behavior**
I'd expect my server to begin to start "quickly" (maybe a minute or two) and notify me of what's going on. 

**Potential Fixes**
Currently checking server free space doesn't provide any feedback like it does on 0.7; May be worth adding a panel console log call before getting free space on startup

I'm honestly not sure how to work around making `Filesystem.Walk` or `Filesystem.Chown` any faster-- it may be worth adding back in the ability to skip ensuring permissions and skipping free space calculation on the daemon. Potentially a better workaround would be the ability to configure this per-server.

**Comment by DaneEveritt** [comment]
I wonder if it could also be useful to not only make it togglable, but also have the ability to define folders to skip over when doing that (extending/duplicating the `.pteroignore` type of thing)? I'm guessing you have one specific folder that is the main issue, and it would still be useful to have other file's permissions auto-set?

That and/or adding in the ability to configure individual file permissions via the web file manager, theres an open feature request for that somewhere.

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/wings/commit/5f1ceeff9032e05bf21b76f4f526613dbf9af508
