### ISSUE TITLE
Upgrade from 1.0.0 beta 7 to 1.0.0-rc.2

### ISSUE THREAD

**Issue by LucidAPs** [pterodactyl/panel#2274]
* Panel or Daemon:  Daemon
* Version of Panel/Daemon:  1.0.0-rc.2
* Server's OS:  Ubuntu Server 20.04 "Focal Fossa"
* Your Computer's OS & Browser:  Win 10 - Chrome

I upgraded from 1.0 beta 7 to 1.0.0-rc.2. The panel indicators are broken, the terminal doesn't refresh in real time, the startup flags don't get updated and the connections are dropped every 10 to 15 mins loosing access to panel webpage and the sftp connection. I have to hard reboot only for the same thing to happen again.

Wings log : https://pastebin.com/raw/72nR68M9
Panel hardware indicators: https://cdn.discordapp.com/attachments/658550982975946762/748427543622975529/unknown.png

**Comment by DarthShmev** [comment]
Please follow the issue template.

**Comment by LucidAPs** [comment]
@DarthShmev Done, sorry about that.

**Comment by Sir3lit** [comment]
Shows something is already using port 8080 that's probably why everything is broke. As its not using the new version of wings. 

This also should've been brought to the discord first

**Comment by LucidAPs** [comment]
Kubi told me to post it here, sorry for the trouble. If you could spare some of your time to help me out because i am a beginner i would appreciate it. I am not sure what to do to fix the problem, can i point to wings to a different port?

**Comment by LucidAPs** [comment]
Okey changing the ports to 8081 or 8089 or anything still gives me the same error, that is already in use.
I did pkill wings i then updated the port on daemon and on /etc/pterodactyl and allowed the port through ufw and then restarted wings with systemctl restart wings. And i keep getting port already in use.
