### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by Aeris1One** [pterodactyl/panel#2275]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0-rc2 (both)
* Server's OS: Ubuntu 18.04 LTS

**Describe the bug**
Just upgraded from 0.7.18 to 1.0-rc2, in fact I fully reinstalled the panel keeping the database and env key. When trying to install Wings I removed the old Daemon and installed Wings and then I had this error

**To Reproduce**
1. Panel 0.7.18 with a node and some servers on it
2. Reinstall the panel keeping database and env key
3. Replace Daemon with Wings

**Logs**
https://hastebin.com/omamodisem.cs

**Comment by DaneEveritt** [comment]
Can you clarify what egg this was? Looks like one of the values being passed along isn't quite right.

**Comment by Aeris1One** [comment]
My servers are (with id): 
- 1x Bungeecord (ca1d)
- 2x Paper (604f, 9b2b) + 1x Suspended (880e)
- 1x Spigot (Egg by Parkervcp) (7943) + 1x Suspended (7f62)
- 1x Custom egg (just a `java -jar bot.jar` for a Discord bot) (b074)
- 1x Teamspeak (06bd)
- 2x Forge Enhanced (by Parkervcp) (8560, 4141)

**Comment by DaneEveritt** [comment]
Can you link to the forge enhanced egg? I _think_ server `414121ba-28da-45c5-905e-afe5e9ed733f` is the one crashing things, but not entirely certain. I've tested servers with Bungee, Spigot, and Paper without issues so I'm guessing there might be a parameter from that Forge egg that is problematic.

**Comment by Aeris1One** [comment]
Yes, servers with IDs starting by 4141 and 8560 are Forge Enhanced, how can I solve as I can't start Wings (so I can't delete/add/suspend servers) ?

**Comment by DaneEveritt** [comment]
There's nothing you can do unless you plan on editing the code to fix it and opening a PR. I'm not even sure it is that egg to be honest.

**Comment by Aeris1One** [comment]
Tried to change the egg "Forge Enhanced" to "Forge Minecraft" (the Pterodactyl's default one) and then I got this :
```
DEBUG: [Aug 27 20:58:11.303] pulling docker image... this could take a bit of time image=quay.io/parkervcp/pterodactyl-images:debian_openjdk-8-jre
DEBUG: [Aug 27 20:58:11.363] pulling docker image... this could take a bit of time image=quay.io/parkervcp/pterodactyl-images:base_debian
DEBUG: [Aug 27 20:58:11.364] pulling docker image... this could take a bit of time image=quay.io/pterodactyl/core:java
 INFO: [Aug 27 20:58:11.457] ensuring server environment exists server=604fb36c-e3fd-4734-b221-f57dc48cb96a
DEBUG: [Aug 27 20:58:11.527] pulling docker image... this could take a bit of time image=quay.io/pterodactyl/core:java
panic: interface conversion: interface {} is nil, not string

goroutine 109 [running]:
github.com/pterodactyl/wings/environment.Variables.Get(0xc00050e060, 0xc0005f02a0, 0x19, 0x19, 0x9)
/home/runner/work/wings/wings/environment/settings.go:123 +0x35b
github.com/pterodactyl/wings/environment.(*Configuration).EnvironmentVariables(0xc0005fc0a0, 0xc00053e1a8, 0xc00096a030, 0x0)
/home/runner/work/wings/wings/environment/config.go:80 +0x553github.com/pterodactyl/wings/environment/docker.(*Environment).variables(0xc0005fe360, 0xc00096a030, 0xc00064e000, 0x3)
/home/runner/work/wings/wings/environment/docker/container.go:208 +0x36
github.com/pterodactyl/wings/environment/docker.(*Environment).Create(0xc0005fe360, 0x1, 0xc000676000)
/home/runner/work/wings/wings/environment/docker/container.go:151 +0x26e
github.com/pterodactyl/wings/cmd.rootCmdRun.func1()
/home/runner/work/wings/wings/cmd/root.go:185 +0x96
github.com/gammazero/workerpool.worker(0xc00025a060)
/home/runner/go/pkg/mod/github.com/gammazero/workerpool@v1.0.0/workerpool.go:204 +0x2d
created by github.com/gammazero/workerpool.startWorker
/home/runner/go/pkg/mod/github.com/gammazero/workerpool@v1.0.0/workerpool.go:195 +0x49
```

**Comment by parkervcp** [comment]
@DaneEveritt I believe this is the "done" value being a single string and not an array.

**Comment by DaneEveritt** [comment]
It isn't. That is a completely different panic and not caused by trying to call `Variable.Get`

**Comment by DaneEveritt** [comment]
@Aeris1One you can use this wings build to address this issue and avoid the crash: https://github.com/pterodactyl/wings/suites/1110189656/artifacts/15595749

**Comment by Aeris1One** [comment]
Thanks it works, now I can start servers but the only remaining problem is that they're not marked as "Started" when the done text appears, always "Starting"
