### ISSUE TITLE
High CPU usage on the "node" process even when no server is running

### ISSUE THREAD

**Issue by MAXOUXAX** [pterodactyl/panel#2281]
**Background:**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v0.6.13
* Server's OS: Debian 10
* Your Computer's OS & Browser: Not relevant

**Describe the bug**
I have a Minecraft server on Pterodactyl for a long time now and I recently decided to reduce the game area by setting up a worldborder, and pre-generating the world & dynmap tiles on the server. Thus, the server size went from 2G to more than 20G and I noticed on my netdata dashboard that the CPU usage was very high and the load was around 80 (which is crazy since I have a 2vCores VPS).
However, the CPU usage was not coming from the "user" category (which is the one containing the java process) but from the "system" category, and I also noticed that my iowait was always at a value above 10.
I then decided to stop the Minecraft server and the CPU usage was 60% or more, the disk usage was at 100% and didn't go below 90%.
By browsing the "applications" tab of my netdata dashboard, the CPU usage was coming from the process "node".
Here's what I've tried so far:
* Restart the daemon - Outcome: CPU usage is the same as normal when the daemon is off, but every time I try to restart the daemon, CPU usage goes back to over 60% with high disk usage.
* Restart the VPS - Outcome: same as above.

`uname -a` > `Linux vps-ee197cf8 4.19.0-10-cloud-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux`
`docker info` > `Kernel Version: 4.19.0-10-cloud-amd64`

The Minecraft server has been off for over 24 hours now and nothing has changed.

**To Reproduce**
1. Create a game server on Pterodactyl
2. Make it so that it uses a lot of disk space (??)
3. See the CPU usage

**More information**
I created a netdata snapshot from my netdata dashboard so you guys can import it to check what's happenning in details and browse all of the data the dashboard has to offer.
Link: https://vps1-fr.maxouxax.me/
Snapshot file: https://mega.nz/file/msETyQ7T#wigg_jELiWy648Ir1JLBEeaCG3hf5OC7l5UHuof_APU
Tutorial: ![EPEp03PtIs](https://user-images.githubusercontent.com/24844231/91528550-3e276200-e908-11ea-922f-f1ad6a830764.gif)

**Comment by schrej** [comment]
Probably caused by the periodic disk usage check. Try to set `internals.disk_use_seconds` to something high, by default its 30s.
If you're the only one using that vps you shouldn't need it at all and can also remove the [lines responsible for the check](https://github.com/pterodactyl/daemon/blob/b551500dfa2ca703997f09492fdeab189a9125da/src/controllers/server.js#L104-L105) from the daemon.
