### ISSUE TITLE
Mysql local host

### ISSUE THREAD

**Issue by Tdash2** [pterodactyl/panel#2282]
* Panel 
* Version of Panel 1.0.0-rc.2
* Server's OS: Ubuntu 18.04 (64 Bit)
* Your Computer's OS & Browser: windows 10 Chrome 

When Adding  a mysql host to pterodactyl For clients to use. If you use any thing that would bring you to local host you get "The host must be a valid IPv4 address or hostname that resolves to a valid IPv4 address." I have check that all my info is wright and that my sql is running 
![image](https://user-images.githubusercontent.com/69229823/91610154-54501500-e93e-11ea-9a5f-7b74e3c0e881.png)

**Comment by Tdash2** [comment]
The data base worked before the update

**Comment by Ender38-cmd** [comment]
I can confirm that this is a bug... the same thing happened to me.

**Comment by Tdash2** [comment]
I have not herd anything about this. I am stuck Rignt now because i cannot make or use a my sql database.
