### ISSUE TITLE
Server console unresponsive after around a day

### ISSUE THREAD

**Issue by BrainStone** [pterodactyl/panel#2283]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0.0-rc.2
* Server's OS: Debian 10

**Describe the bug**
After around a day the server consoles become unresponsive on the web panel. The servers work fine. Sent commands are processed however no messages from the server are being sent to the browser anymore.  
Restarting the wings daemon fixes it.

I think the issue is that when the server rolls over the server log the daemon keeps track of the old (now renamed) file instead of the new actual log file. This suspicion is growing due to the fact that this is only happening with my Minecraft servers (which all roll their logs) and not with my TeamSpeak Server.

`uname -a`:  
```
Linux mc1.root.project-creative.net 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
```

`docker info`:  
```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-6-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.61GiB
 Name: mc1.root.project-creative.net
 ID: G4GJ:RQ5E:UP2D:FG7V:GSLY:JMI4:PTJZ:GYWL:QF52:RRGL:ELAB:UG4O
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**To Reproduce**
1. Start a Minecraft Server
2. Let it and the wings daemon run for 24h
3. Do something on the MC server that produces log messages, like sending from the console.
4. Notice the lack of responses.
5. Restart the wings daemon to see it being fixed

**Expected behavior**
The logs should be captured continously regardless of how long the daemon or the game server runs.

**Comment by parkervcp** [comment]
The daemon doesn't use the server logs. It uses the docker console logs.

**Comment by DaneEveritt** [comment]
Which also rotate.
