### ISSUE TITLE
Add back the file search in the "File Manager" (beta)

### ISSUE THREAD

**Issue by BrainStone** [pterodactyl/panel#2285]
**Is your feature request related to a problem? Please describe.**
In the "old" 0.x version you were able to open a file search when pressing <kbd>Ctrl</kbd> + <kbd>F</kbd>. Now that no longer happens. In addition the files are no longer loaded into the browser in full which means the browser native search can't find any search terms not on the screen.

**Describe the solution you'd like**
A search functionality that considers the whole file like before the beta. Ideally also with the option to enable regex and to search and replace. Those were insanely useful for small edits.

**Describe alternatives you've considered**
An alternative would be that the files shown in the File Manager are loaded in full so that the browser search can actually find something.

**Comment by DaneEveritt** [comment]
They are not loaded in full because that would have huge performance impacts. In order for this to work we'll have to build out a custom finder function in the file editor.

**Comment by BrainStone** [comment]
I thought so that sending the whole files wasn't sensical to do.

It's just that without a working search function editing files through the browser is practically useless.

**Comment by Niko302** [comment]
Agreed, if this feature could be added back it would make editing files in the browser useful again.
Otherwise our whole panel other then for tracking server usage is useless.

**Comment by Pemigrade** [comment]
I'd really like this feature as well

**Comment by Sir3lit** [comment]
With the commit above... It's built into CodeMirror

![2020-09-14_00-33-26](https://user-images.githubusercontent.com/1757840/93044158-00258000-f622-11ea-896b-a03163723baa.gif)
