### ISSUE TITLE
Warning if attempting to edit a non-editable file.

### ISSUE THREAD

**Issue by Yomanz** [pterodactyl/panel#2286]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I accidentally open a .jar and it shows me some jibberish.

**Describe the solution you'd like**
Warn the user before opening specific file extensions/types.

**Describe alternatives you've considered**
None.

**Additional context**
https://canary.discordapp.com/channels/122900397965705216/122902526751145984/748992510453350460
A little bit of discussion there ^

**Comment by Sir3lit** [comment]
I agree with this to an extent, common files like zip,exe,jar,tar etc. Should either just be downloaded when clicked whether it be a pop-up window saying this file isn't editable and give them a button that allows them to download or just display the message saying this file type isn't editable

**Comment by DaneEveritt** [comment]
I can do that for archives but I'm not adding any other file checking logic, it always ends up causing some pain.
