### ISSUE TITLE
Separate the "file.read" permission

### ISSUE THREAD

**Issue by Intriguing-RC** [pterodactyl/panel#2288]
**Is your feature request related to a problem? Please describe.**
The feature I'm requesting isn't related to any sort of bug. In 1.0, changes to the permissions system for sub users were made, which I feel the new file permissions need some adjusting. 

Currently:
`file.read`
-> Allows users to download files
-> Allows users to see what is inside a file
-> Allows users to list files

I don't really see how *listing files* and *downloading files* go together. I feel that they should be separate permissions. 

**Describe the solution you'd like**
I feel like there should be 3 separate permissions:
- `file.read` - Allows you to see inside a file
- `file.list` - Allows you to list files
- `file.download` - Allows you to download files

**Describe alternatives you've considered**
Probably a dumb alternative, but you could just bring back only the **file** permissions from 0.7. I really liked them, and they were more customizable. I do love all the other permission changes, great job 👍

**Comment by DaneEveritt** [comment]
If you can open a file and view it, there is nothing stopping you from downloading said file, that is why the download permission is wrapped into it.

I can however add `file.list` to handle listing the actual contents of the directory, and `file.read` to cover viewing the contents of said file and downloading it.

**Comment by Intriguing-RC** [comment]
Yep, that works.

**Comment by DaneEveritt** [comment]
Closed out in https://github.com/pterodactyl/wings/commit/1e633ae302493fa8cad96f08667560776f3ffb03
