### ISSUE TITLE
route() links use http even if the APP_URL uses https

### ISSUE THREAD

**Issue by matthewpi** [pterodactyl/panel#2289]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: develop (this issue does not effect 0.7)
* Server's OS: N/A
* Your Computer's OS & Browser: N/A

**Describe the bug**
Route links always use `http` even if the `APP_URL` uses `https`

**To Reproduce**
1. Go to the admin area
2. Copy any navigation link, could be from a form, the sidebar, etc.
3. Inspect the copied link, if your `APP_URL` has `https` the link will still start with `http`.

**Expected behavior**
The URL should use `https` if the `APP_URL` has `https`

**Additional Information**
This seems to be caused by the use of the `route()` function provided by `Illuminate/Foundation/helpers.php`

This also breaks the daemon's configuration if you copy it directly from the panel without changing the `remote` value in it to use `https`

I flagged this issue as a security risk as this can lead to forms being submitted over `http` which will expose all of the information inside of the request body.

**Comment by matthewpi** [comment]
This is a problem when the panel is behind a proxy.  In order to get https to properly work you need to set the `TRUSTED_PROXIES` environment variable.

In my use-case I just set it to `TRUSTED_PROXIES='*'` as the panel runs in Docker and isn't publicly exposed except through the reverse proxy itself.

**Comment by JanDevDE** [comment]
I don't think this should be resolved by needing to define "TRUSTED_PROXIES" manually, although it is documented here: https://pterodactyl.io/panel/0.7/configuration.html#reverse-proxy-setup (On a side note, it's not documented for 1.0 at all).

If you don't define this and save the config within the panel, the daemon receives a corrupted config by the panel (remote is defined as HTTP), which will then result in a 401 error on subsequent requests. This is very confusing at first to debug, first-hand experience.

I think if the panel is set to use SSL to connect to the daemon, all requests should be made with https, without needing to specify this trusted_Proxies option.

Just my 2 cents, feel free to disagree. :)

**Comment by JanDevDE** [comment]
Also, this issue can be further hard to identify because if Cloudflare is enabled, http is most probably getting rewritten to https, so this issue will be left unidentified except when saving the config in the panel and thus breaking the daemon.

**Comment by matthewpi** [comment]
> I don't think this should be resolved by needing to define "TRUSTED_PROXIES" manually, although it is documented here: https://pterodactyl.io/panel/0.7/configuration.html#reverse-proxy-setup (On a side note, it's not documented for 1.0 at all).
> 
> If you don't define this and save the config within the panel, the daemon receives a corrupted config by the panel (remote is defined as HTTP), which will then result in a 401 error on subsequent requests. This is very confusing at first to debug, first-hand experience.
> 
> I think if the panel is set to use SSL to connect to the daemon, all requests should be made with https, without needing to specify this trusted_Proxies option.
> 
> Just my 2 cents, feel free to disagree. :)
> 
> @matthewpi ^

This is a problem with how the reverse proxy connects over HTTP instead of HTTPS I believe, if you have SSL on your proxy but not on the container itself then the panel thinks you are using HTTP because it will ignore the `X-Forwarded-Proto` header (might have a different name).

**Comment by JanDevDE** [comment]
@matthewpi Understandable. Maybe we should add a notice on the 1.0 docs anyway.
