### ISSUE TITLE
Ram Usage Slowly Rising

### ISSUE THREAD

**Issue by LucidAPs** [pterodactyl/panel#2290]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0rc2
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Win10 / Brave

OVH dedicated machine , 32gb total ram

One of the servers on my node is raising slowly it's memory usage until it crashes and i am not sure why, i set it up to start up at 12gb ram with java flags and then it keeps rising until it crashes.

Stats at peak usage
![image](https://user-images.githubusercontent.com/42933023/91716077-97f18b80-eb97-11ea-80ad-79325242243e.png)

Node settings
![image](https://user-images.githubusercontent.com/42933023/91716200-d0916500-eb97-11ea-8b96-aed96f70d13c.png)

Server in question settings
![image](https://user-images.githubusercontent.com/42933023/91716253-f159ba80-eb97-11ea-9a72-7f22c7acfcbf.png)

**Comment by parkervcp** [comment]
This is most likely not a pterodactyl issue, but a plugin or something that you have running with a memory leak.

**Comment by LucidAPs** [comment]
> This is most likely not a pterodactyl issue, but a plugin or something that you have running with a memory leak.

I run a heapsummery after gc and i got this
https://spark.lucko.me/#SSTsbgd6o7
maybe com.gamingmesh.jobs aka Jobs Reborn is causing the leak?
https://cdn.discordapp.com/attachments/715676669959995396/749961884425388102/unknown.png

Hhhmm any advice for my problem would be very much appreciated.

**Comment by schrej** [comment]
Does the java process crash on it's own or is it killed by the OOM killer?

**Comment by LucidAPs** [comment]
I am not 100% sure, but the terminal on the server said Out of Memory error.

**Comment by DaneEveritt** [comment]
This is not a bug with Pterodactyl, it is something with your game server.
