### ISSUE TITLE
Missing file browser upload option

### ISSUE THREAD

**Issue by JanDevDE** [pterodactyl/panel#2294]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I think the "upload" button should provide a file browser popup to manually search for the file like in the old panel. Personally I don't like the drag and drop feature at all, because then I need to open windows explorer and navigate to the file, then split the browser windows to drag the file into that window. It is a lot easier to just open a file browser right away and then select the file.

**Describe alternatives you've considered**
The current behavior of just drag-and-drop.

**Comment by DarthShmev** [comment]
I would like to see the conventional file uploader in 1.0.

**Comment by BrainStone** [comment]
That option has been there since RC1
![grafik](https://user-images.githubusercontent.com/4106544/92296346-1487bf80-ef34-11ea-9ae6-4213b55d88de.png)

**Comment by matthewpi** [comment]
> That option has been there since RC1 or RC2

> I think the "upload" button should provide a file browser popup.

He is asking for the ability to select a file using the Operating Systems native file selector like so
![xwWWs7ul7NoLP3Rs](https://user-images.githubusercontent.com/26559841/92297497-04082280-eefd-11ea-85be-b54cacce05b0.png)

**Comment by BrainStone** [comment]
I see. My apologies.  
I agreee that would be useful. I mean showing the drag and drop text makes sense but there should be a button to open the dialog.
