### ISSUE TITLE
More careful dismissal of dialogue options within the file manager

### ISSUE THREAD

**Issue by JanDevDE** [pterodactyl/panel#2295]
**Is your feature request related to a problem? Please describe.**
Currently, the dialogue pop-ups can be dismissed too easily when e.g trying to select something.
Here is a good example:

![2020-08-31_17-42-17](https://user-images.githubusercontent.com/418376/91787284-5e804680-ebbe-11ea-9374-9551f408bc49.gif)

-> When trying to edit a file, for example, dragging too far with the cursor dismisses the whole dialogue.

**Describe the solution you'd like**
I actually cannot think of a good solution. Either only makes dialogue options disappear when clicking a cancel button, or direct if the user is currently dragging the mouse cursor to select something,

**Comment by DaneEveritt** [comment]
This is a bug with how chrome handles these events it looks like, hooray.
