### ISSUE TITLE
SSH RCON

### ISSUE THREAD

**Issue by DomiiBunn** [pterodactyl/panel#2297]
**Solution you'd like**
An ability to use a SSH program to interact with server console as in many cases it is more secure and versatile than the RCON protocol which servers include.

**Describe alternatives you've considered**
Using default RCON that is less secure and more cumbersome to use

**Additional context**
This has been kind of discussed on discord
https://discordapp.com/channels/122900397965705216/376449434654998539/749796586472603658

**Comment by DaneEveritt** [comment]
Closing this out actually, I don't foresee myself having the time or bandwidth to implement such a feature. While a neat idea in theory, it is just complicated to implement, and implement well. For implementing with a server itself, it is much more recommended for you to use the websocket itself to have real-time communications, or utilize the Panel API to send commands and pull logs.

**Comment by darrenwjlau** [comment]
You can also use a console to ssh plugin

**Comment by Serega007RU** [comment]
@mickeydarrenlau Can you give a link to this plugin? Google does not give me any results on this plugin

**Comment by DomiiBunn** [comment]
I think this would be it. https://www.spigotmc.org/resources/minecraft-sshd-ssh-for-your-minecraft-server-universal-support.71887/

The goal of this issue was to make it work with all servers natively. 

P.S. i never used the plugin above and can not say if it's secure or working well

**Comment by YKDZ** [comment]
Sorry to bump the old issue.
I was wondering if there were any relevant solutions. Simply emulating the TAB fill function would be a great improvement.

**Comment by DomiiBunn** [comment]
@YKDZ The issue is closed thus it's not gonna gain view of the devs. 

Tab complete would be a seperate issue in and out of it's self tho a similar issue has been rewiewed in the past https://github.com/pterodactyl/panel/issues/3461
