### ISSUE TITLE
The egg variable delete button typography is wrong

### ISSUE THREAD

**Issue by Diamax10** [pterodactyl/panel#2299]
**Background :**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-rc.2
* Server's OS: Ubuntu
* Your Computer's OS & Browser: MacOS, Chrome

**Describe the bug**
When you hover the button to delete an egg variable the typography is not the same of other buttons like the save button for example.

**To Reproduce**
1. Go to an egg
2. Click on 'variables'
3. Try to delete a variable
4. Compare typography with other components

**Comment by DaneEveritt** [comment]
Wont fix, will be solved with the future admin area rewrite.
