### ISSUE TITLE
Support selecting multiple files in file manager

### ISSUE THREAD

**Issue by ET-Bent** [Pterodactyl/Panel#23]
Allow multiple selections to delete multiple files at once, copy them or cut and paste them to another location.

Selection could be done similar to OwnCloud.

![folders](https://cloud.githubusercontent.com/assets/5788982/12212763/1e0c15aa-b66e-11e5-96c4-8df904907176.png)

**Comment by DaneEveritt** [comment]
closed by #544 and #558
