### ISSUE TITLE
Request for 7zip file support while using the decompression / file manager Tool

### ISSUE THREAD

**Issue by SupaCURE** [Pterodactyl/Panel#230]
If you try to transfer a file over using the File Manager, and it is compressed using the non-basic zip file extension (7z) it will not allow you to decompress the file.

**Comment by schrej** [comment]
Imho .zip should be sufficient, just recompress your files with zip. Adding 7z (and rar etc.) would just add more dependencies to the panel.

**Comment by DaneEveritt** [comment]
Yeah, decompressing those would require non-standard extensions installed on the server. For now I'm going to close this as I don't plan on supporting the decompressing of those files. Thanks for the suggestion though. :)
