### ISSUE TITLE
v1.0.0-rc.3 floods the base directory and breaks composer

### ISSUE THREAD

**Issue by relavis** [pterodactyl/panel#2300]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v1.0.0-rc.3
* Server's OS: Centos 8
* Your Computer's OS & Browser: Windows 10, Firefox

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
PHP 7.4.8
Command `composer install --no-dev --optimize-autoloader` causes massive errors and it appears that a previous command on the guide has caused the /var/www/pterodactyl directory to be flooded. 
Image of error: https://i.imgur.com/cPaI2Gw.png
Flooded base directory: https://i.imgur.com/8HFLs6L.png

**To Reproduce**
1. Follow "Upgrading 0.7 series to 1.0 Series" guide up until the `composer install --no-dev --optimize-autoloader` command

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
A working composer command

**Comment by relavis** [comment]
Looks like removing `--strip-components=1` from `tar --strip-components=1 -xzvf panel.tar.gz && rm -rf panel.tar.gz` solves the issue. Base directory is still flooded with miscellaneous files.

**Comment by fabm3n** [comment]
Yeah it's the untested migration guide. To clean up your base directory you need to remove all folders which are included in panel.tar.gz manually or reinstall the panel.

**Comment by DaneEveritt** [comment]
Just copy the environment file to a safe location, delete all the files, and then unpack the archive again without the flag and put the environment file back. It's certainly not the end of the world.

**Comment by DaneEveritt** [comment]
PR was merged to fix the docs
