### ISSUE TITLE
File upload progress to be reflected in UI

### ISSUE THREAD

**Issue by msharp19** [pterodactyl/panel#2302]
If you drag and drop large files via the file manager, you are only presented with a loading cursor. 

This is fine for small file transfer but when it comes to large file transfer (which takes a varying amount of time) it would be nice to see the upload progress. 

If you ask me it would be good to see the progress bar/percentage uploaded regardless of the file size but that's up to you!

Thanks!

**Comment by danielnaaman** [comment]
Isn't there a feedback provided by the browser? Such as the one seen here.

![image](https://user-images.githubusercontent.com/16944217/93010636-59949d00-f597-11ea-9638-6fbb9966ac5d.png)

I'm not saying it's a replacement to a good, satisfying progress bar, but it might not be as important.

**Comment by msharp19** [comment]
Hi danielnaaman - not that I can see on Chrome (just tested again to be sure)

**Comment by danielnaaman** [comment]
> Hi danielnaaman - not that I can see on Chrome (just tested again to be sure)

Odd, I noticed it many times in the past.

I switched to Safari so I can't test it out myself, but since it does only work in Chrome so it's not a viable solution either ways.

Forget I said anything.

**Comment by Pemigrade** [comment]
I relied on this feature a lot when I was uploading new paper jars, and I think it'd make a great addition to the 1.0 panel if it was re-implemented

**Comment by LoneDev6** [comment]
> 
> 
> Isn't there a feedback provided by the browser? Such as the one seen here.
> 
> ![image](https://user-images.githubusercontent.com/16944217/93010636-59949d00-f597-11ea-9638-6fbb9966ac5d.png)
> 
> I'm not saying it's a replacement to a good, satisfying progress bar, but it might not be as important.

Sadly nope, using Firefox.
Currently uploading a 500MB file and it would be very nice to see how much time it remains and the upload speed.
Thanks all!

![immagine](https://user-images.githubusercontent.com/27242001/105486236-7a3fd280-5cae-11eb-8fa7-6e8dbc849171.png)

**Comment by matthewpi** [comment]
File upload progress is only shown by the browser if it is submitted using an HTML form which we don't use.

**Comment by FoksVHox** [comment]
> File upload progress is only shown by the browser if it is submitted using an HTML form which we don't use.

So that means that this isn't possible? Or could you maybe explain it a bit more in-depth?

**Comment by matthewpi** [comment]
> > File upload progress is only shown by the browser if it is submitted using an HTML form which we don't use.
> 
> So that means that this isn't possible? Or could you maybe explain it a bit more in-depth?

No, it's possible but we would have to handle it manually, similarly to how 0.7 did it.  But unlike other sites where you see upload progress in the bottom left (like when you hover over a link), that is handled by the browser itself.

**Comment by LoneDev6** [comment]
To get a more noob proof panel I think that is a must have, users may complain with the hosting service if they see no apparent progress.

This is just a suggestion, feel free to accept it considering if it's difficult or not to implement

**Comment by DaneEveritt** [comment]
Its always possible, I just don't have the motivation or desire to build such a thing right now, which is why the issue is just sitting with a label.

**Comment by FoksVHox** [comment]
> > > File upload progress is only shown by the browser if it is submitted using an HTML form which we don't use.
> > 
> > 
> > So that means that this isn't possible? Or could you maybe explain it a bit more in-depth?
> 
> No, it's possible but we would have to handle it manually, similarly to how 0.7 did it. But unlike other sites where you see upload progress in the bottom left (like when you hover over a link), that is handled by the browser itself.

Thanks for clarifying that.

**Comment by VottusCode** [comment]
> 
> 
> Its always possible, I just don't have the motivation or desire to build such a thing right now, which is why the issue is just sitting with a label.

This was a feature I really needed, especially because we update our servers frequently and there's 1-2 files that are around 100MB, so seeing the progress is a nice touch.

I've had the chance to play around with the frontend and implemented it inside of UploadButton. It currently looks like this

![unknown](https://user-images.githubusercontent.com/53915302/118628097-95d66800-b7cc-11eb-97b2-0154150a63bb.png)

If you want, I can make a PR for it.

**Comment by ShioGa** [comment]
Hello, I am French server host, I do not know if the translation is good because I use Google Translation. I would like to know if there is way to know how to do that, because my clients and I send us a lot of files to the server via the file explorer. I would like to know if there was a way to get file back and explain and put it in the server for it to work.

Thank you in advance ^^

**Comment by trenutoo** [comment]
Implemented in V2 https://github.com/pterodactyl/panel/commit/c6dccc568d91d95e6b5fa4dcaad4dfd532b6a5f6

![image](https://user-images.githubusercontent.com/10975908/129607269-06cb39bb-ac1c-4dba-9063-707c6a530023.png)

**Comment by matthewpi** [comment]
> Implemented in V2 [c6dccc5](https://github.com/pterodactyl/panel/commit/c6dccc568d91d95e6b5fa4dcaad4dfd532b6a5f6)
> 
> ![image](https://user-images.githubusercontent.com/10975908/129607269-06cb39bb-ac1c-4dba-9063-707c6a530023.png)

Still a WIP, but it is implemented.

**Comment by ShioGa** [comment]
How do I install it?

**Comment by trenutoo** [comment]
> How do I install it?

Pterodactyl V2 is a work in progress and has not been released yet.
