### ISSUE TITLE
Configuring a Server Network => 172.18.0.1 don't work

### ISSUE THREAD

**Issue by GeistFighter** [pterodactyl/panel#2307]
I apologize in advance for errors of expression I am not English.

In this documentation that I had followed under version 0.7.X :
https://pterodactyl.io/community/games/minecraft.html

It is explained that to configure and attach a local server we use IP 172.18.0.1.

But, after I switched to 1.0, it doesn't work anymore, it's very annoying.

**Comment by GeistFighter** [comment]
Finally I just changed the IPs in the configuration of the node which was 127.0.0.1 and I put everything in 172.18.0.1 and it works.

I don't know if that's how it should work.

**Comment by TheFlash787** [comment]
I can confirm this too. 

Whilst using `127.0.0.1` in the server allocation should work (as previously), it doesn't seem to in the latest 1.0-RC builds. Using `172.18.0.1` does work, but shouldn't be necessary.

Thank you! ❤️

**Comment by parkervcp** [comment]
In 0.7/0.6 it replaces the 127.0.0.1 in the config with a 172.18.0.1 on start. That is specific to certain configs I believe.

In the guide it says to use 172.18.0.1 for a reason.

**Comment by DaneEveritt** [comment]
It's bugged, it should still be auto replacing 127.0.0.1

**Comment by williammck** [comment]
Seeing the same issue, previously the Daemon would replace allocations of `127.0.0.1` with `172.18.0.1` when binding the ports in Docker. Looks like Wings is not doing that.

before migration to Wings:
```
cc8fcef5a671        561f7d202979                    "/bin/bash /entrypoi…"   2 months ago        Up 2 months         172.18.0.1:50002->50002/tcp, 172.18.0.1:50002->50002/udp         082cbe06-d2f0-4973-b3c3-8f6c0c90ed41
40bb010fbde3        561f7d202979                    "/bin/bash /entrypoi…"   2 months ago        Up 2 months         172.18.0.1:50004->50004/tcp, 172.18.0.1:50004->50004/udp         a83c0646-8c8c-437d-beff-bec90d220a02
a1603fc5bbea        561f7d202979                    "/bin/bash /entrypoi…"   2 months ago        Up 2 months         172.18.0.1:50003->50003/tcp, 172.18.0.1:50003->50003/udp         302b9634-b99c-483c-83ce-db4f84e12ae5
```

after migration to Wings:
```
465d7ffc0ac3        quay.io/pterodactyl/core:java   "/bin/bash /entrypoi…"   11 seconds ago       Up 9 seconds        127.0.0.1:50002->50002/tcp, 127.0.0.1:50002->50002/udp           082cbe06-d2f0-4973-b3c3-8f6c0c90ed41
b5905aeb390f        quay.io/pterodactyl/core:java   "/bin/bash /entrypoi…"   42 seconds ago       Up 41 seconds       127.0.0.1:50003->50003/tcp, 127.0.0.1:50003->50003/udp           302b9634-b99c-483c-83ce-db4f84e12ae5
c3c1da542fc7        quay.io/pterodactyl/core:java   "/bin/bash /entrypoi…"   About a minute ago   Up About a minute   127.0.0.1:50004->50004/tcp, 127.0.0.1:50004->50004/udp           a83c0646-8c8c-437d-beff-bec90d220a02
```

**Comment by arantesxyz** [comment]
> It's bugged, it should still be auto replacing 127.0.0.1

If this is a bug, should be considered as a feature. Use `172.18.0.1` instead of `127.0.0.1` is waaay better.

**Comment by schrej** [comment]
Actually, we should just make hostnames of containers predictable (and I think they are already) and show them in the panel. That way you can just connect to the containers directly, which would also eliminate the need for the firewall rules.

**Comment by DaneEveritt** [comment]
I'm not doing anything special in the current Nodejs code for this @schrej. All it does is replace allocations for 127.0.0.1 with the `pterodactyl0` interface. 👍 

And I think the Bungeecord egg at least has a config value that does the same.

**Comment by arantesxyz** [comment]
> I'm not doing anything special in the current Nodejs code for this @schrej. All it does is replace allocations for 127.0.0.1 with the `pterodactyl0` interface. 👍
> 
> And I think the Bungeecord egg at least has a config value that does the same. This feature needs to be added back anyways, its a massive BC break and I _really_ don't want to have a flood of support volume from that.

0.7 you had to create allocations for 127.0.0.1 and then you had to put 172.18.0.1 in the bungee config, it's messy, even tho we know why not everyone does, etc.

And now in 1.0, we just create allocations with 172.18.0.1 and put the same in the config. That's easier to work with, and understand.

I don't think this should be considered as a bug. (And even if it is, this is a good one that improves UX).

**Comment by arantesxyz** [comment]
Instead of adding back, just update the page that talks about it. It's really easy for people migrating from 0.7 to 1.0 to change, they just have to change their "127.0.0.1" allocations for "172.18.0.1", everything else is the same.

**Comment by DaneEveritt** [comment]
I'd rather just make it work the same way, its not the end of the world to make `127.0.0.1` auto-link to `pterodactyl0`, and it allows you to use the same logic for Docker and non-docker (if we ever get there) environments. We can always just make the documentation update to not bother discussing `127.0.0.1` specifically, however for a lot of new people that is just easier for them to reason about.

**Comment by H4zlq** [comment]
help me, i still cannot connect to server, im new at pterodactyl

**Comment by arantesxyz** [comment]
> help me, i still cannot connect to server, im new at pterodactyl

Hello, you need to configure your firewall and bungee correctly. Here's how i did it:

Server Allocations (s1, bungee and lobby in that order):
![Screen Shot 2021-02-03 at 19 08 32](https://user-images.githubusercontent.com/42740492/106815964-6ce1fb00-6653-11eb-9f56-72d54b1b7522.png)
 
Bungee config:
![Screen Shot 2021-02-03 at 19 09 01](https://user-images.githubusercontent.com/42740492/106815959-6b183780-6653-11eb-95bd-82ec0dcfca48.png)

Firewall:
![Screen Shot 2021-02-03 at 19 13 15](https://user-images.githubusercontent.com/42740492/106816258-e11c9e80-6653-11eb-9497-dc06a5a00faf.png)


This is the command (using ufw) for allowing the proxy to connect to port `24387`: `sudo ufw allow in on pterodactyl0 to 172.18.0.1 port 24387 proto tcp`

**Comment by H4zlq** [comment]
so the bungee i need to use my vps ip ?

**Comment by H4zlq** [comment]
in server.properties what should i put the ip ?

**Comment by arantesxyz** [comment]
> so the bungee i need to use my vps ip ?

yes

> in server.properties what should i put the ip ?

default, nothing

**Comment by H4zlq** [comment]
![image](https://user-images.githubusercontent.com/76235095/106821978-2de69080-66b9-11eb-8f0a-a0cabd8b2f07.png)
im stuck here and got this error  disconnected with: ReadTimeoutException : null

**Comment by H4zlq** [comment]
can you message me on discord ? here my discord нazιq#2653

**Comment by H4zlq** [comment]
> > so the bungee i need to use my vps ip ?
> 
> yes
> 
> > in server.properties what should i put the ip ?
> 
> default, nothing

so on spigot.yml i need to leave server-ip: blank here

**Comment by arantesxyz** [comment]
> can you message me on discord ? here my discord нazιq#2653

I added you
