### ISSUE TITLE
1.0.0-rc.3 corrupting server.properties

### ISSUE THREAD

**Issue by Technofied** [pterodactyl/panel#2308]
**Background (please complete the following information):**
* Panel or Daemon: 
* Version of Panel/Daemon: 1.0.0-rc.3
* Server's OS: Ubuntu 20.04.1
* Your Computer's OS & Browser: Safari, macOS Big Sur Public Beta 5

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` PHP 7.3.21-1+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Aug  7 2020 14:44:37) ( NTS )
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
Linux panel 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

A regular long MOTD gets split and randomly chucked across the server.properties file. Even after fixing it so its back on one line it breaks and gets thrown across again

**To Reproduce**
Just have a motd that's all on one line, upgrade to 1.0 then see it get thrown across the file.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
Motd to stay on one line after saving and especially after restarts

See attached image of issue below:

<img width="1131" alt="Screen Shot 2020-09-02 at 7 49 44 am" src="https://user-images.githubusercontent.com/40795318/91917126-a5228d80-ecf1-11ea-9fc5-ea132d794fe7.png">

**Comment by Technofied** [comment]
<img width="1140" alt="Screen Shot 2020-09-02 at 8 01 04 am" src="https://user-images.githubusercontent.com/40795318/91917432-7953d780-ecf2-11ea-9386-16750e1b1f96.png">
This is what it should normally look like

**Comment by gabefraser** [comment]
Can confirm I have the exact same issue. Typically happens after a server restart.

**Comment by DaneEveritt** [comment]
Please post the actual file contents and not a picture of you don't mind, can't exactly copy and paste from an image.

**Comment by gabefraser** [comment]
Providing some insight here as the OP hasn't responded as this seems like a major issue.

Special characters seem to be encoded after a server restart. This might be due to the way the egg rewrites the `server-port=` property in the `server.properties` file.

Take a look at the below screenshots and text blobs:

**Before restart:**
`motd=\u00A7n\u00A7l\u00A7aTest of \u00A7bPterodactyl Breakage`

**After restart:**
`motd=\u00C2\u00A7n\u00C2\u00A7l\u00C2\u00A7aTest of \u00C2\u00A7bPterodactyl Breakage`
![image](https://user-images.githubusercontent.com/10922294/91927302-7837a000-ed1c-11ea-9d87-d7e8e2befd1a.png)

I am running the latest version of Panel and Wings `1.0.0-rc3` on Ubuntu 18.04.

Please let me know if you require any additional information @DaneEveritt.

**Comment by DaneEveritt** [comment]
@gabefraser see https://github.com/pterodactyl/panel/issues/2192#issuecomment-670310020

**Comment by gabefraser** [comment]
Makes sense. Thanks for the follow up.

**Comment by DaneEveritt** [comment]
@gabefraser you can confirm that is the case by disabling all of the config stuff for the egg (e.g. empty `{}` in the files field for the egg). If it still gets mangled, it is def not Pterodactyl specifically.

**Comment by DaneEveritt** [comment]
@Technofied can you please do the same thing, disabling any config modification for the specific egg, and attempting to start the server. If the MOTD is still messed up it is likely not an issue with Pterodactyl.

**Comment by Technofied** [comment]
> @Technofied can you please do the same thing, disabling any config modification for the specific egg, and attempting to start the server. If the MOTD is still messed up it is likely not an issue with Pterodactyl.

I have no modifications.

**Comment by Technofied** [comment]
> @Technofied can you please do the same thing, disabling any config modification for the specific egg, and attempting to start the server. If the MOTD is still messed up it is likely not an issue with Pterodactyl.

That seems to have fixed it!

**Comment by DaneEveritt** [comment]
Well, if that fixed it then that is tragic because that means it is indeed something with Pterodactyl most likely.

**Comment by JanDevDE** [comment]
On a side note, this issue exists not only in rc3 but also in prior versions. I stumbled across this some weeks ago but thought it might be a spigot issue.

**Comment by DaneEveritt** [comment]
It seems to be an issue with the game server not realizing its a utf-8 encoded file, thus leading to issues. Its certainly caused by the server itself touching the file I believe, but is a result of Pterodactyl writing the contents and the file ending up as not utf-8? Perhaps?

I'm a little baffled to be honest.

**Comment by clienthax** [comment]
> It seems to be an issue with the game server not realizing its a utf-8 encoded file, thus leading to issues. Its certainly caused by the server itself touching the file I believe, but is a result of Pterodactyl writing the contents and the file ending up as not utf-8? Perhaps?
> 
> I'm a little baffled to be honest.

It seems to be trying to escape any existing characters with more unicode.

**Comment by DaneEveritt** [comment]
Yeah, I'm quite sure it's the game itself doing that but Pterodactyl is saving the file in a format that makes the server not realize it should be utf8.

**Comment by clienthax** [comment]
> Yeah, I'm quite sure it's the game itself doing that but Pterodactyl is saving the file in a format that makes the server not realize it should be utf8.

I think the problem may be that wings is parsing the original \u00A7 into the unicode character § , then when it comes to writing it, it may be playing the character § back into the file, instead of the original escaped code, likely hitting this bug https://bugs.mojang.com/browse/MC-2215

**Comment by JanDevDE** [comment]
^ Either that, or wait for mojang to fix the issue ^^.

**Comment by clienthax** [comment]
> ^ Either that, or wait for mojang to fix the issue ^^.

No, wings shouldn't be screwing with the contents of files for unrelated lines, and it won't be backported anyway.

**Comment by JanDevDE** [comment]
> > ^ Either that, or wait for mojang to fix the issue ^^.
> 
> No, wings shouldn't be modifying the contents of files for unrelated lines, and it won't be backported anyway.

Oops, yea, I didn't read the last replies properly, sorry.

**Comment by matthewpi** [comment]
> No, wings shouldn't be modifying the contents of files for unrelated lines, and it won't be backported anyway.

Wings has to rewrite the entire file to disk which requires decoding and then re-encoding it.  There is no way around that process.  The only work around for this is to disable the config parser on the egg so that wings doesn't even look at the file.

This shouldn't be difficult to fix.

**Comment by clienthax** [comment]
> > No, wings shouldn't be modifying the contents of files for unrelated lines, and it won't be backported anyway.
> 
> Wings has to rewrite the entire file to disk which requires decoding and then re-encoding it. There is no way around that process. The only work around for this is to disable the config parser on the egg so that wings doesn't even look at the file.
> 
> This shouldn't be difficult to fix.

The problem is that it's decoding escaped chars which causes this, (thanks golang)
