### ISSUE TITLE
Subuser permissions are not migrated properly from 0.7 to 1.0

### ISSUE THREAD

**Issue by AusHick** [pterodactyl/panel#2309]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-rc3
* Server's OS: Debian 10
* Your Computer's OS & Browser: Win x64 Chrome

**Describe the bug**
Subusers who previously had permissions in the 0.7 panel no longer have access due to the new permission IDs in the 1.0 panel.
```
php -v
PHP 7.4.9 (cli) (built: Aug  7 2020 14:55:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```

**To Reproduce**
Migrate a 0.7 subuser to the 1.0 panel
Visit an assigned server's control page
403 error served
Reassign permissions to subuser, causing 0.7 permissions to persist on top of the 1.0 ones
Subuser section reports ~2x the amount of granted permissions due to the old permissions still existing

**Expected behavior**
0.7 panel subuser permissions should be migrated during the 1.0 upgrade process.
1.0 permissions should be derived from existing 0.7 permissions, and then the 0.7 permissions should be discarded.

**Comment by stijnb1234** [comment]
When you try to change the permissions, it returns a 404.

```
/api/client/servers/37c3db18-c3b6-40d7-aa11-93d9b10c3d49/users/9cfe120f-6ed5-4a2f-b817-949ecd2e1e27:1 Failed to load resource: the server responded with a status of 404 ()

bundle.187dc0ed.js:1 Error: Request failed with status code 404
    at e.exports (bundle.187dc0ed.js:1)
    at e.exports (bundle.187dc0ed.js:1)
    at XMLHttpRequest.p.onreadystatechange (bundle.187dc0ed.js:1)
```
