### ISSUE TITLE
File Manager has an error where the loading bar will automatically complete itself.

### ISSUE THREAD

**Issue by SupaCURE** [Pterodactyl/Panel#231]
For visual reference.

![image](https://cloud.githubusercontent.com/assets/1207517/21587946/08d557ea-d0b8-11e6-959f-5e186799b851.png)

This happens immediately when you select a file, however if you monitor network traffic in task manager you can clearly see when it peaks / finishes and these times do not correlate with the bar. It finishes immediately while the upload seems to take 10 or so seconds.

**Comment by DaneEveritt** [comment]
Can you provide the logs from your browser?

**Comment by DaneEveritt** [comment]
Unable to reproduce.

**Comment by OrangeJuiced** [comment]
Same thing happens to me. Using Chrome on Windows 10. Browser console log:

```
Uncaught DOMException: Failed to execute 'readAsArrayBuffer' on 'FileReader': The object is already busy reading Blobs.
    at x (<redacted>/js/vendor/upload/client.min.js:9:231)
    at Array.<anonymous> (<redacted>/js/vendor/upload/client.min.js:11:449)
    at n.<anonymous> (<redacted>/js/vendor/upload/client.min.js:15:179)
    at n.e.emit (<redacted>/js/vendor/socketio/socket.io.min.js:23:1606)
    at n.onevent (<redacted>/js/vendor/socketio/socket.io.min.js:22:31333)
    at n.onpacket (<redacted>/js/vendor/socketio/socket.io.min.js:22:30955)
    at n.<anonymous> (<redacted>/js/vendor/socketio/socket.io.min.js:23:2238)
    at n.e.emit (<redacted>/js/vendor/socketio/socket.io.min.js:23:1606)
    at n.ondecoded (<redacted>/js/vendor/socketio/socket.io.min.js:21:23673)
    at s.<anonymous> (<redacted>/js/vendor/socketio/socket.io.min.js:23:2238)
x @ client.min.js:9
(anonymous) @ client.min.js:11
(anonymous) @ client.min.js:15
e.emit @ socket.io.min.js:23
n.onevent @ socket.io.min.js:22
n.onpacket @ socket.io.min.js:22
(anonymous) @ socket.io.min.js:23
e.emit @ socket.io.min.js:23
n.ondecoded @ socket.io.min.js:21
(anonymous) @ socket.io.min.js:23
e.emit @ socket.io.min.js:21
s.add @ socket.io.min.js:21
n.ondata @ socket.io.min.js:21
(anonymous) @ socket.io.min.js:23
e.emit @ socket.io.min.js:22
n.onPacket @ socket.io.min.js:22
(anonymous) @ socket.io.min.js:21
e.emit @ socket.io.min.js:22
n.onPacket @ socket.io.min.js:22
n.onData @ socket.io.min.js:22
ws.onmessage @ socket.io.min.js:22
```

**Comment by DaneEveritt** [comment]
Reported to plugin repo at https://github.com/vote539/socketio-file-upload/issues/63

This might be due to the fact that we're on `0.5.0` and the latest release is `0.5.2` which included changes to blob handling in vote539/socketio-file-upload#60

**Comment by ET-Bent** [comment]
Same for `Google Chrome (stable) 55.0.2883.87` on `Ubuntu 16.04.1 (64 bit)`

**Comment by Darksleep** [comment]
since this have been reopend i comment here

ive had issue with filemanagers green bar with my when i upload a file it dose nothing it make empty file with right name but no green bar nothing file empty and is 0kb in size when file uploading is 1.5mb in size

on google chrome on windows server 2016

**Comment by IlPicasso** [comment]
Happens on 0.5.7

**Comment by DaneEveritt** [comment]
This is all with these stable version correct? Not with the prerelease versions.

**Comment by IlPicasso** [comment]
Correct Stable Version 0.5.7
