### ISSUE TITLE
Hover bug on pack list

### ISSUE THREAD

**Issue by GiovaniFerraroTrivelli** [pterodactyl/panel#2310]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: rc3 
* Server's OS: Debian 9
* Your Computer's OS & Browser: Firefox

**Describe the bug**
The table breaks when hover on row.

**To Reproduce**
Go to "List Packs" in admin panel and hover on pack number.

![TajTL2b2mD](https://user-images.githubusercontent.com/27016185/92061962-ea84a080-ed6d-11ea-95f7-97ddc8711e1a.gif)

**Expected behavior**
Show tooltip without breaking the table.

**Comment by DaneEveritt** [comment]
cc @LeCodeCo

**Comment by LeCodeCo** [comment]
Think I know how to fix that. Any reason we even need the UUID there?

**Comment by DaneEveritt** [comment]
Not really, no.

**Comment by Sir3lit** [comment]
I was going to make a pr to just remove it and put it on the page when you view the details of the pack

**Comment by DaneEveritt** [comment]
Not blocking up 1.0 over such a minor issue.

**Comment by Sir3lit** [comment]
Now sure why this wasn't closed when the pr was merged... but it can probably be closed
