### ISSUE TITLE
Error 500 when creating database

### ISSUE THREAD

**Issue by nathen148** [pterodactyl/panel#2311]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-rc.3
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chrome Windows

**Describe the bug**
A clear and concise description of what the bug is. When going in to create a new database once i fill in all the database info and click create it throws a 500 error
Please provide additional information too, depending on what you have issues with:
Panel: 7.2
Daemon: `uname -a` and `docker info` Linux cb.skyhighinv.net 5.4.0-42-generic #46~18.04.1-Ubuntu SMP

**To Reproduce**
1. Go to admin
2. Click on database
3. Fill in info
4. Click create

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
For it to create the database host

**Comment by Sir3lit** [comment]
Most likely have incorrect permissions for whatever user you used to make the database host. Please provide the error log in /var/www/pterodactyl/storage/logs

**Comment by nathen148** [comment]
Sure heres the latest log http://bin.ptdl.co/ylco9

**Comment by nathen148** [comment]
> Most likely have incorrect permissions for whatever user you used to make the database host. Please provide the error log in /var/www/pterodactyl/storage/logs

Sure heres the latest log http://bin.ptdl.co/ylco9

**Comment by Sir3lit** [comment]
So its complaining that 127.0.0.1 isn't a valid address.... I'll look into it when I get home.

**Comment by DaneEveritt** [comment]
Not quite a duplicate, but def related to https://github.com/pterodactyl/panel/issues/2282

**Comment by nathen148** [comment]
any update?

**Comment by nathen148** [comment]
@Sir3lit

**Comment by DaneEveritt** [comment]
Once it is fixed it will be closed, theres no reason to ping people and ask for updates.
