### ISSUE TITLE
Wings logs not rotated.

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2312]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.0 rc2
* Server's OS: Ubuntu 18.04

**Describe the bug**
Wings currently just keeps adding to the same file and doesn't rotate log files as the nodejs daemon does. 
Nobody likes a 4.6MB log file :) let alone a log file with 36,875 lines

![PqRpizI](https://user-images.githubusercontent.com/1757840/92075358-53781280-ed86-11ea-953e-cb2056162f32.gif)
![image](https://user-images.githubusercontent.com/1757840/92075370-5a068a00-ed86-11ea-814d-ff9ce0d214c3.png)

**To Reproduce**
1. Just run wings.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Comment by DaneEveritt** [comment]
We actually use https://github.com/nytimes/logrotate which rotates the logs when a given logrotate service rotates them.

**Comment by DaneEveritt** [comment]
I made wings write a logrotate file to the disk, and then it is up to the system running it to be running logrotate. We can update the documentation to get that enabled for wings.

**Comment by Nick2253** [comment]
This may still need some tweaking.

On Fedora 32, logrotate expects a username and a group name, and does not work with a user ID or a group ID.  Once I change the `create` line to: `create 0640 root root` everything works.

**Comment by sapphonie** [comment]
> 
> 
> This may still need some tweaking.
> 
> On Fedora 32, logrotate expects a username and a group name, and does not work with a user ID or a group ID. Once I change the `create` line to: `create 0640 root root` everything works.

agree, same issue on ubuntu 20.10

https://github.com/pterodactyl/wings/blob/e09cc3d2dd18753562c808136bf9aeca9428914d/templates/logrotate.tpl

setting this to `create 0640 root root` fixed it for me as well
