### ISSUE TITLE
Panel isn`t downloading Server Files

### ISSUE THREAD

**Issue by TheRedCmdCraft** [pterodactyl/panel#2313]
Hey i've installed the panel, nginx(Version 1.14.0), the deamon(Version 0.6.12), redis-server(Version 4.0.9), php (Version 7.4.9). After the installation i've configured the panel and the daemon, then i would be creating a server that i can look if i had any mistakes. Yes I did a mistake. but i don't know where? I can create Servers, the server-folders will be created in /srv/daemon-data/ and in this folder it will created two files (a log file which is empty and a sever.json file) 

Does anyone know what the mistake is? 
btw: at the following point the panel will be stopping: 
![temp](https://user-images.githubusercontent.com/57496807/92262732-dbbbfc00-eedb-11ea-8f45-eed0051e58a4.JPG)

**Comment by LeCodeCo** [comment]
Please join the Discord. https://discord.gg/pterodactyl

**Comment by TheRedCmdCraft** [comment]
> Please join the Discord. https://discord.gg/pterodactyl

I am joinee the Discord. I had also asked on this, but i got no answer.
