### ISSUE TITLE
Hashtag character in MySQL password causing connection error

### ISSUE THREAD

**Issue by Harieo** [pterodactyl/panel#2315]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0-rc
* Server's OS: Ubuntu 18.10
* Your Computer's OS & Browser: Firefox

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

PHP version: `PHP 7.2.19-0ubuntu0.18.10.1`
When using the hashtag character ('#') in the password of the MySQL user for pterodactyl, which runs the main database for the panel, it appears to cause Pterodactyl to cut-off all characters after the hashtag when it tries to use the password to connect to the MySQL database. After investigating the .env file, it appeared in nano as if the # character caused the rest of the password to be read as a comment (and therefore it was excluded when read). 

I experienced this issue upgrading from panel v0.7 to v1.0-rc and the issue has never occurred on v0.7. I have updated to new versions of v0.7 without experiencing this, the issue only appears to be on v1.0.

When trying to update with a password containing a hashtag, this error occurs on executing `php artisan migrate --force`:
`SQLSTATE[HY000][1045] Access denied for user 'pterodactyl'@'localhost' (using password: YES)`

While I can't be absolutely certain this is the issue, removing the # fixed my problem immediately and without any other changes to the pterodactyl user or my database. I can also understand it being read as a comment as there's no quotation marks to indicate it's part of a string in .env but I am not an expert in web applications!

**To Reproduce**
1. Setup a pterodactyl MySQL user with a # somewhere in the password
2. Perform an update of your panel from v0.7 to v1.0-rc using the steps in the [docs](https://pterodactyl.io/panel/1.0/upgrade/0.7_to_1.0.html) up to 'Database Updates'
3. Attempt to run `php artisan migrate --force`
4. There will be multiple permission denied issues stemming from Connection.php

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

When attempting to update my database as part of upgrading to v1.0-rc, I expected that my current password work the same as it did on v0.7 without issue. Instead, it caused issues with connecting to the database and resulted in permission being denied. Changing the password to simply remove the # character fixed my issue but I didn't expect any problems to come from using special characters in my password.

**Comment by parkervcp** [comment]
can you wrap the password in single quote `'` marks and see what happens?

**Comment by Harieo** [comment]
> 
> 
> can you wrap the password in single quote `'` marks and see what happens?

Wrapping in quotation marks does fix the issue

**Comment by DaneEveritt** [comment]
Guessing the environment dependency got updated at some point which is breaking a few things. I don't really have a good approach to preventing that break but it is fixed going forward already.

**Comment by DaneEveritt** [comment]
https://github.com/pterodactyl/panel/commit/b707147b73f0adeb35ab39f53008d02d689aff86

**Comment by 0x-Fede** [comment]
Same problem upgrading from v0.7x to v1.0 series.

 #php artisan migrate --force

In Connection.php line 671:
  SQLSTATE[HY000] [1045] Access denied for user 'pterodactyl'@'localhost' (using password: YES) (SQL: select * from informat
  ion_schema.tables where table_schema = panel and table_name = migrations and table_type = 'BASE TABLE')

In PDOConnection.php line 31:
  SQLSTATE[HY000] [1045] Access denied for user 'pterodactyl'@'localhost' (using password: YES)

In PDOConnection.php line 27:
  SQLSTATE[HY000] [1045] Access denied for user 'pterodactyl'@'localhost' (using password: YES)

**Comment by 0x-Fede** [comment]
Solved:

Edit /var/www/pterodactyl/.env
Add single quotes DB_PASSWORD='YOUR_PASSWORD'

**Comment by DaneEveritt** [comment]
Correct, nothing gets fixed in an upgrade, I can only fix it for re-runs.
