### ISSUE TITLE
Suspended server results in "stopping" state, then breaks ws when unsuspended

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2318]
**Background (please complete the following information):**
* Panel or Daemon: Both
* Version of Panel/Daemon: 1.0rc3 Panel / Cutsom Wings from https://github.com/pterodactyl/panel/issues/2298#issuecomment-686895711
* Server's OS: Ubuntu 18.04 

**Describe the bug**
Suspending a server that is already offline results in the state getting changed to stopping and staying like that until the server is unsuspended. Once the server is unsuspended it is then stuck in stopping even after clicking `Kill`  results in the errors of processing another power action. Once it sorts itself out and starts, resource polling fails to notice and stats are reported as 0, and console lines require a page refresh to view newlines like #2298 

Wings thinks the server is running when it's not and issues the stop command...
`INFO: [Sep  6 21:12:44.673] server suspended with running process state, terminating now server`
![2020-09-06_15-16-13](https://user-images.githubusercontent.com/1757840/92333529-2496c080-f054-11ea-9272-90add8f0ee9a.gif)

**To Reproduce**
1. Suspend stopped/offline server.
2. Verify status changed to "stopping"
3. Unsuspended server.
4. attempt to start server,
5. Notice is not polling stats and still shows offline.

**Expected behavior**
The server to be properly identified if running or not and appropriate action is taken. If the server's not running just suspend the server to prevent it from breaking WS and resource polling.

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/wings/commit/c415abf9716a43a16366b6ec7d34f9c27da6432b
