### ISSUE TITLE
Mail settings reset when migrating

### ISSUE THREAD

**Issue by Telesphoreo** [pterodactyl/panel#2320]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-rc3
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 on Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
```
PHP 7.4.9 (cli) (built: Aug  7 2020 14:30:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
```Linux cloudstepper 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```
```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 4
  Paused: 0
  Stopped: 2
 Images: 10
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-45-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.83GiB
 Name: cloudstepper
 ID: CXS5:M35H:MC4P:NP2S:JIBW:RH7A:XW3R:HLD4:O4HQ:FJVA:UDOM:QPWL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
The mail settings were reset when upgrading from 0.7.18 to 1.0.0-rc3. In the settings panel, it was replaced with the default mailtrap.io and 2525 port, however the username and password still showed in the panel. Updating the settings from the panel resulted in a successful message, but it did not actually change anything. Changing the mail settings to what it's supposed to be in the .env file worked, and I was able to receive a message from the test button.

**To Reproduce**
1. Upgrade a 0.7.18 install to 1.0.0-rc3
2. Mail settings are reset
3. Expect to change them back in panel
4. Does not work
5. Change in .env file, mail system works

**Expected behavior**
The expected behavior is for the correct mail settings to carry over when upgrading. If they can't, reset it and when you hit the "Save" button, it'll actually update as opposed to having to change it in the .env file.

Edit: i just realized what this means "Your Panel is currently configured to read settings from the environment only. You will need to set APP_ENVIRONMENT_ONLY=false in your environment file in order to load settings dynamically."

but I already have that set to false in my .env?? perhaps this bug report should be about pterodactyl not updating things even though APP_ENVIRONMENT_ONLY=false is set to false

**Comment by DaneEveritt** [comment]
You need to run `php artisan clear:cache` (or `cache:clear`, can't remember off the top of my head). This isn't a bug, you're the only one from many people who have upgraded to report this issue, and based on the information you've provided it sounds like your config is cached (which is not part of our documentation anyways, so not sure how you did that) which is why things aren't changing.
