### ISSUE TITLE
[Wings Error]: The data provided in the request could not be validated.

### ISSUE THREAD

**Issue by Hydra2k** [pterodactyl/panel#2326]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.0RC 3
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10; Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use). 7.2.32
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
Linux 2vfu.l.time4vps.cloud 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 Debug Mode: false

Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 13
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic

**To Reproduce**
1. Go to admin panel
2. Create server
3. any type of server
4. error

**Expected behavior**
It should say [Wings Error]: The data provided in the request could not be validated.

This may be my server issue; but I wasn't getting any response in the discord

**Comment by DaneEveritt** [comment]
Cannot reproduce with the steps provided. Please provide a more narrow set of reproduction steps, or errors from the Panel and/or Wings relating to this.
