### ISSUE TITLE
Timezone correct in container but time is incorrect

### ISSUE THREAD

**Issue by Synkstar** [pterodactyl/panel#2329]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0rc4
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: - Not applicable because it has to do with the docker container 

**Describe the bug**
The timezone in the container is correct and the localtime and timezone files are the same on the server and the daemon because they are mounted. I even tried mounting /usr/share/zoneinfo. Help would be greatly appreciated

**To Reproduce**
For me you would just make a server and the time would be incorrect

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
The time should sync with the server like it did on the old daemon.

**Comment by DaneEveritt** [comment]
Please see https://github.com/pterodactyl/panel/issues/2239#issuecomment-675213274 for the reason why I am closing this.

**Comment by andris155** [comment]
Same problem. I don't know how to fix this.
