### ISSUE TITLE
Backups silently fail if size is too big

### ISSUE THREAD

**Issue by IAmLythixIAmDumb** [pterodactyl/panel#2330]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: RC.5
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: ElementaryOS 5.1 Ohera | Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Describe the bug**
If a backup gets too big in file size, the backup silently fails. This issue might possibly be related to #2068 as it behaves the same way.

**To Reproduce**
1. Get a server in large size
2. Create a backup
3. See the backup never finish
4. See the daemon log no longer processing the command

**Expected behavior**
Backup failure is detected, cancelled and removed. (Add an info box if possible)

**Comment by JanDevDE** [comment]
@IAmLythixIAmDumb Can you define "large size"? Works fine for me at RC.5 with 70GB.

**Comment by DaneEveritt** [comment]
This is almost certainly not because of the size, but because of https://github.com/pterodactyl/panel/issues/2068. It just shows up at larger sizes since its more likely one of those files is being touched while the backup happens.
