### ISSUE TITLE
React still polls resource usage even when dashboard page is not active

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2331]
I'm sure that is a horrid title for what I'm trying to report. 

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Rc5
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Win10 / Chrome

**Describe the bug**
When viewing a server or viewing one of the tabs within a server ( file manager/databases / etc. ) the stats on the home page for the server rows are still updating and sending requests to the /resources endpoint to get the stats even though you're not actively looking at that page.

**To Reproduce**
1. Go to a server's File Manager page or any other page, just looking at the console works too.
2. Watch network requests in DevTools or Wings log
3. Notice its still calling /resources for each server you can view on the main page.

**Expected behavior**
The content to be unloaded and not continue to reload in the background, as when you go back to the main page its called again.

**Comment by DaneEveritt** [comment]
I cannot reproduce this?
