### ISSUE TITLE
Can not connect to one of 20 servers on one node

### ISSUE THREAD

**Issue by Pomdre** [pterodactyl/panel#2336]
Version of Panel/Daemon: 0.7.18/0.6
Server's OS: Ubuntu 18.04.3 LTS
DB-Server-type: MariaDB 10.1.44
PhP-v: 10.1.44
Error log: https://pastebin.com/t5zmMYzX

I get Connection Error when I try to access one of my servers. 
All the other servers on the same node talk fine with my db.

Do not have much more info to give.. thanks for the help in advance!

I also get this message when I try to drop the server through the database:
![image](https://user-images.githubusercontent.com/30056774/93024668-4d8cf780-f5f8-11ea-9953-e0c4570eff9b.png)

**Comment by DaneEveritt** [comment]
Whatever server you're trying to access is completely corrupted in the database and is also missing from the node. Theres nothing I can specifically do to fix this and it isn't really a bug with this software since there is no telling what you did to cause this.

**Comment by Pomdre** [comment]
Sorry to mark it as a bug.
Do you have any ideas on how I can remove that one server completely?

**Comment by Pomdre** [comment]
solution delete the game servers db
