### ISSUE TITLE
[Improvement] Indication of the server's name in the panel

### ISSUE THREAD

**Issue by Sourack** [pterodactyl/panel#2337]
**Is your feature request related to a problem? Please describe.**
When I browse servers for example in files and databases it is very frustrating because sometimes I forget the server on which I am working and there is absolutely no indication to identify the server except in the url (/server/e607a98a) and again it's not always obvious.

**Describe the solution you'd like**
I would like that when we are on a server in the panel that the name of it is indicated in front of the button to display the console a little bit like it was before with 0.7.

**Describe alternatives you've considered**
There are no other alternatives in my opinion.

**Additional context**

Where put the name of the server:
![image](https://user-images.githubusercontent.com/20821366/93025080-12270480-f5c9-11ea-98d3-372d6ac4eff0.png)

How it was on 0.7:
![image](https://user-images.githubusercontent.com/20821366/93025092-24a13e00-f5c9-11ea-9142-0914b7ca4d7d.png)

I hope you find my idea useful 😄

**Comment by matthewpi** [comment]
The server's name is displayed in the Page Title.

![Mv10aXtL7EeGfAs4](https://user-images.githubusercontent.com/26559841/93025286-ea7c7000-f5b9-11ea-9a8a-3e509fdda990.png)

**Comment by Sourack** [comment]
Yeah but that is when you are in the console.

**Comment by matthewpi** [comment]
> Yeah but that is when you are in the console.

It also appears when you are on other tabs, look at the top of the screenshot I posted.

**Comment by Sourack** [comment]
Oh yeah but you had to see it xD

**Comment by DaneEveritt** [comment]
I won't be changing that design.
