### ISSUE TITLE
The panel writes 2FA enabled when is 2FA disabled

### ISSUE THREAD

**Issue by andris155** [pterodactyl/panel#2345]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0 RC5
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 20H2, Google Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

The panel write 2FA enabled when is 2FA disabled - under lock icon.

```
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

**To Reproduce**
1. Go to the server
2. Click on Users

<img width="100" alt="Capture" src="https://user-images.githubusercontent.com/8324198/93190523-c51b6d80-f743-11ea-9f15-f4bccda6d4ad.PNG">

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
Writes the 2FA disabled when is disabled.

**Comment by DaneEveritt** [comment]
Can you please include "_a clear and concise description of what the bug is._" I do not understand what the specific issue here is because you didn't quite follow the template we have, and theres just a picture with a circle and something about 2FA but no additional details.

**Comment by Sir3lit** [comment]
This isn't a bug. The icon represents if its enabled or not. The text is telling you what the icon represents

**Comment by andris155** [comment]
> This isn't a bug. The icon represents if its enabled or not. The text is telling you what the icon represents

okay thanks for information.
