### ISSUE TITLE
The schedules not support fully cron syntax

### ISSUE THREAD

**Issue by andris155** [pterodactyl/panel#2347]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0 RC5
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 20H2, Google Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

```
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

**To Reproduce**
1. Go to the server.
2. Click on schedules.
3. Setup scheduler with this 1 4 * fri

<img width="718" alt="Capturee" src="https://user-images.githubusercontent.com/8324198/93198943-f6993680-f74d-11ea-8966-a96b27b688f5.PNG">
<img width="967" alt="Capture" src="https://user-images.githubusercontent.com/8324198/93198947-f862fa00-f74d-11ea-9f6b-e87beac92a48.PNG">

And MONTH setting missing from panel.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

The schedules fully support the cron syntax.

**Comment by victiondev** [comment]
You can just use the numeric day of the week, as shown here:

![image](https://user-images.githubusercontent.com/26467584/93207966-b341c680-f753-11ea-802a-a687f0596da1.png)

**Comment by DaneEveritt** [comment]
This is working as intended. The library we use for parsing crons doesn't seem to allow that type of expression, which is honestly something I've never actually seen in a production environment. The missing month is also by design, and not something I care to add in.
