### ISSUE TITLE
laravel error by API Access

### ISSUE THREAD

**Issue by BartEmbregts** [Pterodactyl/Panel#235]
[2017-01-02 16:06:19] production.ERROR: exception 'ErrorException' with message 'Undefined index: location' in /var/www/pterodactyl/html/app/Repositories/ServerRepository.php:129
Stack trace:
#0 /var/www/pterodactyl/html/app/Repositories/ServerRepository.php(129): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/pterod...', 129, Array)
#1 /var/www/pterodactyl/html/app/Http/Controllers/Admin/ServersController.php(169): Pterodactyl\Repositories\ServerRepository->create(Array)
#2 [internal function]: Pterodactyl\Http\Controllers\Admin\ServersController->postNewServer(Object(Illuminate\Http\Request))
#3 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9395): call_user_func_array(Array, Array)
#4 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9422): Illuminate\Routing\Controller->callAction('postNewServer', Array)
#5 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(8476): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Pterodactyl\Http\Controllers\Admin\ServersController), 'postNewServer')
#6 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(8457): Illuminate\Routing\Route->runController()
#7 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(8166): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(3162): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9880): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/pterodactyl/html/app/Http/Middleware/AdminAuthenticate.php(71): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9880): Pterodactyl\Http\Middleware\AdminAuthenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9880): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9865): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(8167): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(8158): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#21 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(8149): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#22 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(2472): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/pterodactyl/html/app/Http/Middleware/LanguageMiddleware.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9880): Pterodactyl\Http\Middleware\LanguageMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(13494): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9880): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(11920): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9880): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(13240): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9880): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(13177): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9880): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(3224): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9880): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/pterodactyl/html/vendor/dingo/api/src/Http/Middleware/Request.php(108): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9880): Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/pterodactyl/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(9865): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(2416): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /var/www/pterodactyl/html/bootstrap/cache/compiled.php(2400): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#48 /var/www/pterodactyl/html/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#49 {main}
[2017-01-02 16:28:47] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'new' (T_NEW), expecting identifier (T_STRING)' in /var/www/pterodactyl/html/app/Http/Controllers/Base/APIController.php:51
Stack trace:
#0 {main}

**Comment by DaneEveritt** [comment]
What version of the panel, and how did you cause this error?

**Comment by BartEmbregts** [comment]
Newest version on Debian.
I want to setup API remote

**Comment by BartEmbregts** [comment]
When i click on API access i get the Laravel error.

**Comment by DaneEveritt** [comment]
Is button on the sidebar?

**Comment by BartEmbregts** [comment]
Yes. On the user page.

**Comment by DaneEveritt** [comment]
Can you provide me the URL that is throwing the error?

**Comment by BartEmbregts** [comment]
I removed my virtual server so i dont have de url.
I think /account/api but i dont know.

**Comment by BartEmbregts** [comment]
I get only the Laravel error on Debian, on Ubuntu it works fine.

**Comment by DaneEveritt** [comment]
It was determined this was due to a reserved keyword in 5.6 not there in PHP 7.

**Comment by DaneEveritt** [comment]
This issue was fixed by https://github.com/Pterodactyl/Panel/commit/a85ac87ae85b93eb1b0fa55159fdffabc33f2171
