### ISSUE TITLE
The panel uses the global time zone instead of the set one

### ISSUE THREAD

**Issue by andris155** [pterodactyl/panel#2351]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0 RC5
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 20H2, Google Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

The panel uses the global time zone instead of the set one. The set time zone would be Europe/Budapest.

```
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

**To Reproduce**
1. Set a not global timezone.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
The panel uses the set time zone.

**Comment by parkervcp** [comment]
If you are seeing the timezone in the console as UTC that is in the docker container. 

Servers doesn't respect the timezone files and there are enough differences between debian and redhat based that there is no "one way" to make it always work.

**Comment by matthewpi** [comment]
Also it won't use the panel's timezone, it will **try** use the timezone on the host system (which runs wings).

**Comment by DaneEveritt** [comment]
There is not enough information in this issue for me to take any actions or provide any guidance. In the future _please_ make sure you're providing more than a few words to describe an issue and what you're expecting to happen. 

For context, this means absolutely nothing to me, and I don't even know where to begin. Is this a Panel UI issue? Wings console output issue? Something else?

> The panel uses the global time zone instead of the set one. The set time zone would be Europe/Budapest.

Please also carefully read the templates here, you've left that massive banner at the top on all of the issues you've created, which does explicitly state that you should delete it when submitting. 👍
