### ISSUE TITLE
Unable to right-click in input feilds in file-manger modals 

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2353]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: rc5
* Server's OS: Ubuntu 18.04

**Describe the bug**
When renaming a file...or Moving a file you're unable to right-click in the text area.

**To Reproduce**
1. 'Rename' or 'Move' a file.

**Expected behavior**
Allowed to right-click like in the 'Create Directory' text area.

**Comment by DaneEveritt** [comment]
Fixed in develop already
