### ISSUE TITLE
Flood of errors when JWT expires in websocket

### ISSUE THREAD

**Issue by DaneEveritt** [pterodactyl/panel#2354]
Looks like the JWT expires sometimes without the Panel correctly refreshing it.

```
ERROR: [Sep 16 22:08:30.454] failed to handle websocket process; an error was encountered processing an event error=no jwt present error_identifier=96ff4ef9-159e-4d54-86ab-fce4f6ed3335 event=status server=5e0b3372-e378-42f2-93a5-06faca2d42f0

Stacktrace:
github.com/pterodactyl/wings/router/websocket.(*Handler).TokenValid
	/home/vagrant/wings/router/websocket/websocket.go:138
github.com/pterodactyl/wings/router/websocket.(*Handler).SendJson
	/home/vagrant/wings/router/websocket/websocket.go:97
github.com/pterodactyl/wings/router/websocket.(*Handler).ListenForServerEvents.func1
	/home/vagrant/wings/router/websocket/listeners.go:55
github.com/pterodactyl/wings/events.(*EventBus).Publish.func1
	/home/vagrant/wings/events/events.go:62
github.com/gammazero/workerpool.worker
	/home/vagrant/go/pkg/mod/github.com/gammazero/workerpool@v1.0.0/workerpool.go:204
```

Leads to this amazing behavior:
![ezgif-7-c7d63526db1f](https://user-images.githubusercontent.com/418376/93422912-ac0cdc80-f869-11ea-9ac1-eac99ad49d7d.gif)

**Comment by DamonOnYT** [comment]
Unsure if this is related, but it seems it might be.

Ran a server action, and then I was greeted with the nice spam of errors:

` WARN: [Sep 18 02:53:17.258] invalid JWT detected for server websocket! error=no jwt present server=53251764-93e7-4929-9d95-9b42e9adcdab

Stacktrace:
github.com/pterodactyl/wings/router/websocket.(*Handler).TokenValid
        /home/runner/work/wings/wings/router/websocket/websocket.go:139
github.com/pterodactyl/wings/router/websocket.(*Handler).SendJson
        /home/runner/work/wings/wings/router/websocket/websocket.go:97
github.com/pterodactyl/wings/router/websocket.(*Handler).ListenForServerEvents
        /home/runner/work/wings/wings/router/websocket/listeners.go:68
runtime.goexit
        /opt/hostedtoolcache/go/1.15.0/x64/src/runtime/asm_amd64.s:1374
`
I have tried refreshing the page, Restarting Wings, Changing the build of wings all of them still returning the same issues.


After a while, Wings just ended up crashing altogether
`panic: send on closed channel

goroutine 2652 [running]:
github.com/pterodactyl/wings/events.(*EventBus).Publish.func1.1(0xc000796000, 0xc0004c8b00, 0xad, 0x1029030, 0x5)
        /home/runner/work/wings/wings/events/events.go:54 +0x5d
created by github.com/pterodactyl/wings/events.(*EventBus).Publish.func1
        /home/runner/work/wings/wings/events/events.go:53 +0x151
panic: send on closed channel

goroutine 2690 [running]:
github.com/pterodactyl/wings/events.(*EventBus).Publish.func1.1(0xc000796000, 0xc0009ac580, 0xac, 0x1029030, 0x5)
        /home/runner/work/wings/wings/events/events.go:54 +0x5d
created by github.com/pterodactyl/wings/events.(*EventBus).Publish.func1
        /home/runner/work/wings/wings/events/events.go:53 +0x151
`
