### ISSUE TITLE
SSFTP 1.0.5 Not producing additional logging

### ISSUE THREAD

**Issue by Meganitrospeed** [pterodactyl/panel#2355]
**Background (please complete the following information):**
* Panel or Daemon: Daemon ( Standalone SFTP )
* Version of Panel/Daemon: 1.0.5
* Server's OS: Ubuntu
* Your Computer's OS & Browser: Windows

**Describe the bug**
On new SFTP release, we are getting the same log-output as at the old release, making it not possible to use fail2ban (haven't tried building from source)

**To Reproduce**
Simply follow the instructions provided
Check logs produced by the standalone sftp

**Expected behaviour**
Extended logging that makes it possible to parse the logs and make Fail2Ban rules to avoid brute forces

I discussed this back in July with kubi, apparently, the new release wasn't working but I never raised an issue on Github

**Comment by DaneEveritt** [comment]
Closing this out, I have no intentions of going back and re-releasing a new SFTP binary or continuing maintenance for that software as it has been rolled into 1.0.
