### ISSUE TITLE
Banned from the Discord

### ISSUE THREAD

**Issue by yashendra2797** [pterodactyl/panel#2357]
Hey there! I was banned on the 24th of August (IST) from the Discord. On looking for some info I realized that there is no normal way to appeal, and I also found these issues:  #2156, and #1858 which line up with what happened to me.

Reading these it seems like typing `xxx.com` in chat bans you because the bot thinks you're linking to porn. 

Now I really didn't want to make an issue here because everyone works really hard, and I didn't want to add clutter, so I then messaged @parkervcp on Discord: 

> Hey Parker I apologize for messaging you directly. I was just perma banned by the bot from the Pterodactyl server for "Excessive spamming (by Valkyrja)". Thing is that it was after just 1 post, and for posting about an error happening on https://eu.xxx.com. I looked around and saw some GitHub issues where other people have been banned for the same reason. I couldnt find a way to appeal the ban other than make an issue as well, but I thought it would be less cluttered if I messaged you directly.

Now post that I had exams, and I was not online much. Parker never responded, and I cannot find any other admin on Discord, and I'd rather not be rude and PM every admin on GitHub, so I'm creating this issue. I'd really appreciate some help. 

This happened sometime around 08:00 IST (UTC +05:30) on Aug 24 2020.

Thanks!

**Comment by matthewpi** [comment]
I have gone ahead and unbanned you.  But for future reference (as you already stated), GitHub issues are not the place for dealing with this type of stuff.

**Comment by yashendra2797** [comment]
Thank you so much! Could Ptero devs please add some kind of ban appeal feature via the bot?

**Comment by ghost** [comment]
I have been banned from your Discord Server ask will it says advertising 

roguebros#0232
