### ISSUE TITLE
Updating to rc.6 from rc.5 when i download the package it downloads and then spams console with a Cannot open file: file exists

### ISSUE THREAD

**Issue by xXEthyleneXx** [pterodactyl/panel#2358]
We use GitHub issues only to discuss about Pterodactyl bugs and new features. For
this kind of questions about using Pterodactyl, please visit our Discord for assistance: https://pterodactyl.io/discord

DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

PLEASE stop spamming our tracker with "bugs" that are not related to this project.
![image](https://user-images.githubusercontent.com/66333948/93555885-5279e000-f945-11ea-8cca-06272edcf67e.png)

**Comment by DaneEveritt** [comment]
Cannot reproduce, looks like an issue with your system and not our documentation (which has not changed at all in weeks) or builds.
