### ISSUE TITLE
Too many symlinks (told to put in here by AreYouScared)

### ISSUE THREAD

**Issue by MilkMGN** [pterodactyl/panel#2364]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Daemon (wings)
* Version of Panel/Daemon: 1.0 rc6
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 & Firefox 

**Describe the bug**
 WARN: [Sep 18 07:56:42.024] failed to determine disk usage in go-routine error=EvalSymlinks: too many links server=d3927f7c-4d2c-48c2-8ad6-1b23a5bd60c0

Stacktrace:
github.com/pterodactyl/wings/server.(*Filesystem).DiskUsage.func1
        /home/runner/work/wings/wings/server/filesystem.go:275
runtime.goexit
        /opt/hostedtoolcache/go/1.15.2/x64/src/runtime/asm_amd64.s:1374

**To Reproduce**
1. i dont know, was told to make an issue.
2. i guess you make a bunch of symlinks?
3. mine links from a server container to `/var/www/pterodactyl/public`

**Expected behavior**
i can start wings

**Comment by DaneEveritt** [comment]
How many files exist for the server in `/var/lib/pterodactyl/volumes/d3927f7c-4d2c-48c2-8ad6-1b23a5bd60c0` (or whereever the data directory for that server is)?

**Comment by MilkMGN** [comment]
19011 (i think). there was a small mistake where there was somehowa symlink redirecting to itself but i fixed that and wings works now

**Comment by DaneEveritt** [comment]
Guess it got stuck in a loop, closing this for now.
