### ISSUE TITLE
The server owner search bar seems to only work on the email field

### ISSUE THREAD

**Issue by Antideveloppeur** [pterodactyl/panel#2366]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-rc.6
* Server's OS: CentOS 8
* Your Computer's OS & Browser: Windows 10, Edge Chromium

**Describe the bug**
We cannot search for a server owner using first name, last name or username, it only works using the email.
![image](https://user-images.githubusercontent.com/55905781/93596065-0ff1eb00-f9b9-11ea-99c4-b0f3decc9467.png)
![image](https://user-images.githubusercontent.com/55905781/93596076-12ecdb80-f9b9-11ea-9d16-b93cf58fd29a.png)
![image](https://user-images.githubusercontent.com/55905781/93596083-154f3580-f9b9-11ea-850e-5914f5b93f77.png)

**To Reproduce**
1. Create a new server
2. In the "server owner" field, try using either the user first name or username.
3. Does not work. It only works if you type a word contained in the email field of that user.

**Expected behavior**
I should be able to type the user's username or first name to find him.

**Comment by gabefraser** [comment]
Looks to be a pretty simple fix. It's just adding some additional fields into the filter array:

https://github.com/pterodactyl/panel/blob/develop/app/Http/Controllers/Admin/UserController.php#L188

**Comment by DaneEveritt** [comment]
This is intentional for the time being and will be addressed by the admin area re-write.
