### ISSUE TITLE
Issue with Configuration Parser In Latest Wings RC Candidate 

### ISSUE THREAD

**Issue by eddynetweb** [pterodactyl/panel#2369]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0.0-rc.6 (Golang Version)
* Server's OS: Debian 10 Buster x64
* Your Computer's OS & Browser: Debian 10 Buster x64 with Chromium 

**Describe the bug**
There seems to be issue with the configuration parser in regards to a particular egg that I've created. The issue appears to have started with `1.0.0-rc.4` and above in which the following error occurs when attempting to run the server, which causes `wings` to crash: 
```
DEBUG: [Sep 18 11:57:33.648] syncing stop configuration with configured docker environment server=a43dcdd7-1957-4b6e-9f0b-ba69aeeafb2b
DEBUG: [Sep 18 11:57:33.649] syncing server settings with environment server=a43dcdd7-1957-4b6e-9f0b-ba69aeeafb2b
 INFO: [Sep 18 11:57:33.649] performing server limit modification on-the-fly server=a43dcdd7-1957-4b6e-9f0b-ba69aeeafb2b
DEBUG: [Sep 18 11:57:33.650] parsing server configuration file parser=properties path=/srv/daemon-data/a43dcdd7-1957-4b6e-9f0b-ba69aeeafb2b/Viewmode.cfg
DEBUG: [Sep 18 11:57:33.651] parsing server configuration file parser=properties path=/srv/daemon-data/a43dcdd7-1957-4b6e-9f0b-ba69aeeafb2b/properties/server.properties
panic: runtime error: index out of range [0] with length 0

goroutine 223 [running]:
github.com/pterodactyl/wings/parser.(*ConfigurationFile).parsePropertiesFile(0xc00052ad20, 0xc0006500c0, 0x52, 0x0, 0x0)
        /home/runner/work/wings/wings/parser/parser.go:441 +0x128c
github.com/pterodactyl/wings/parser.(*ConfigurationFile).Parse(0xc00052ad20, 0xc0006500c0, 0x52, 0xc000650000, 0x52, 0x0)
        /home/runner/work/wings/wings/parser/parser.go:146 +0x5b8
github.com/pterodactyl/wings/server.(*Server).UpdateConfigurationFiles.func1()
        /home/runner/work/wings/wings/server/config_parser.go:25 +0x1b1
github.com/gammazero/workerpool.startWorker(0xc000440780, 0xc00038a6c0)
        /home/runner/go/pkg/mod/github.com/gammazero/workerpool@v1.0.0/workerpool.go:194 +0x27
created by github.com/gammazero/workerpool.(*WorkerPool).dispatch
        /home/runner/go/pkg/mod/github.com/gammazero/workerpool@v1.0.0/workerpool.go:156 +0x2a9
```
The specific configuration file parser configuration: 
```
{
    "properties/server.properties": {
        "parser": "properties",
        "find": {
            "port": "{{server.build.default.port}}",
            "verify-names": "True",
            "public": "True"
        }
    },
    "Viewmode.cfg": {
        "parser": "properties",
        "find": {
            "cli": "True",
            "high-quality": "False"
        }
    }
}
```
As shown above, the parser seems to be able to parse `Viewmode.cfg` fine, but seems to die with the `index out of range` error for `server.properties`. Removing references to the `server.properties` in the egg configuration resolves this issue. 

I can supply the entire egg if needed.

Additional system information (if needed): 
`Linux silver.us.eddyn.net 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux`
Docker: `Server Version: 19.03.13` - no other issues reported by Docker. 

**To Reproduce**
Steps to reproduce the behavior: Restarting or attempting to start a server which has an egg with this particular configuration parse causes `wings` to crash. See above. I can provide the exact egg that allows you to deploy to re-produce. 

**Expected behavior**
It shouldn't crash - should just start. This started happening after the `rc.4` and above release.

**Comment by DaneEveritt** [comment]
If you could provide the full egg that would be fantastic. Thanks.

**Comment by eddynetweb** [comment]
Here's the egg. 

[egg-pterodactyl.zip](https://github.com/pterodactyl/panel/files/5247605/egg-pterodactyl.zip)

**Comment by DaneEveritt** [comment]
I am having trouble accessing that link, can you use a different service or just paste it here?

**Comment by eddynetweb** [comment]
Sorry about that. Try this one: https://dev.eddyn.net/content/ptero-egg.txt
