### ISSUE TITLE
Sponge servers listed under spigot tag

### ISSUE THREAD

**Issue by ccarney16** [Pterodactyl/Panel#237]
[](https://github.com/Pterodactyl/Panel/blob/develop/database/seeds/MinecraftServiceTableSeeder.php#L93)

Sponge servers under Minecraft Service options are tagged as spigot, not sponge, image listed below

![ejwdyfeogyamanc7caaqfbh4g4iezbqlulopzxdf4vt8x3wpu61qf-lzbdiowxhsegqp3kpuzo2sur9tf74gi-syx5vkgg3erxoste6fds3inkrjboyy0lsyddz0jv6q7ttu7w8iwcls](https://cloud.githubusercontent.com/assets/22264545/21596733/44806c62-d10d-11e6-9d1e-2b4f5ef72ae1.png)

**Comment by parkervcp** [comment]
When you add a server it is okay. this looks like a "service" page issue.

![](http://i.imgur.com/zgMZZrA.png)

**Comment by DaneEveritt** [comment]
Yeah but it'll bug out the daemon since it sends the `spigot` tag so the daemon is looking for spigot config files.
