### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Sundeep-deJongh** [pterodactyl/panel#2370]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0 BETA 
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 & Google Chrome

**Describe the bug**
De console spams lots of caracters.

**To Reproduce**
You can't reproduce it (try F5 some times)

**Expected behavior**

Screenshot: 
![image](https://user-images.githubusercontent.com/63871046/93624835-3d528f00-f9e1-11ea-8bdf-d91f4b7ee7ac.png)

**Comment by DaneEveritt** [comment]
What egg is this? And have you verified it still happens even when not using any plugins?

**Comment by Sundeep-deJongh** [comment]
@DaneEveritt Paper Egg and i have test it with plugins and no plugins.

**Comment by Sundeep-deJongh** [comment]
> @DaneEveritt Paper Egg and i have test it with plugins and no plugins.

still the same.

**Comment by DaneEveritt** [comment]
Unless someone else is able to reproduce this and provide more detailed steps I am closing this issue out as I have not ever seen this happen, no one else running the RC builds has reported it, and without a more narrowed reproduction scope I don't see myself spending time trying to track down what might be causing it.

Wings literally just pipes whatever output comes from the server over to the browser, so I fail to see how this would even happen.

Sorry.
