### ISSUE TITLE
Ace Editor Monospace Font

### ISSUE THREAD

**Issue by SaltyBunny12772** [pterodactyl/panel#2372]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7 & 1.0
* Server's OS: Ubuntu 20
* Your Computer's OS & Browser: Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

**To Reproduce**
1. Go to the "File Editor" page on any server
2. Click on start editing the file. The further from the left you get, the further the cursor is messed up (Google "Ace Editor Monospace Font Issue")

**Expected behavior**
The cursor should always accurately depict where you're typing. 

**Possible/Known Fixes**
I know what needs to be done, I am just unsure as to where the issue is located. The ace editor required a font-face of "monospace" to be set. This is mainly achieved via css, however there may be a way to do it here that I am unaware of.

**Comment by matthewpi** [comment]
Closing this as the editor in 1.0 was recently changed to CodeMirror and this is a minor issue that won't be fixed for 0.7.
