### ISSUE TITLE
IP are not static causing massive problems with multiservered installations [WINGS]

### ISSUE THREAD

**Issue by TheCreeperCow** [pterodactyl/panel#2373]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: RC-1.0.6
* Server's OS: Ubuntu
* Your Computer's OS & Browser: Windows 10 | Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
The IP of servers running on wings change constantly and are not accessible thru the gateway of wings. So if your running a multiservered instance like bungeecord its impossible to make it operate properly as the IP you configured eventually change causing the bungeecord instance to no longer function

**To Reproduce**
1. Make a server that publicly accessible 
2. Make a server that not publicly accessible and should only be accessible by the local instance
3. Wait until the IP leash expires and see the IP change

**Expected behavior**
I expect the IP to be static or at least allow them to be static in the panel

**Comment by parkervcp** [comment]
To connect to a serve behind a proxy we recommend using 127.18.0.1:<server_port>.

That is guaranteed to get to the server you have. Docker allocates IP's on a "as needed" basis so when a server is started it is allocated the next unused IP.

**Comment by TheCreeperCow** [comment]
Im aware of that and we tried that before however the gateway does not direct us to the server it just times out it seems to be related to #2307 I have tried setting the allocations to 127.0.0.1 and 172.18.0.1 and i have tried to connect to both 127.0.0.1 and 172.18.0.1 still not working

**Comment by parkervcp** [comment]
It may also be a firewall issue blocking access to the address.

Per our docs for running a minecraft network <https://pterodactyl.io/community/games/minecraft.html#firewalls>

**Comment by DaneEveritt** [comment]
You should be using whatever the `pterodactyl0` interface IP is, which is used automatically if you use `127.0.0.1` for bungee networks, or `127.0.0.1` as the server allocation. If that does not work then it is most likely a system configuration issue and I'd recommend using Discord for further support, because this is how Pterodactyl has always operated and it has always worked fine.
