### ISSUE TITLE
BadMethodCallException when adding a mount to a server

### ISSUE THREAD

**Issue by matthewpi** [pterodactyl/panel#2374]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0-rc6
* Server's OS: CentOS 8
* Your Computer's OS & Browser: Windows 10 and Brave

**Describe the bug**
When adding a mount to a server (I guess you could also say "mounting a mount" 😉) you will get a 500 error due to an undefined method.

**To Reproduce**
1. Go to the admin area
2. Create a new mount (or use an existing one)
3. Go to a server that has the mount available
4. Attempt to add the mount

**Expected behavior**
The mount is mounted 😉 and the Panel doesn't blow up.

![dvPDz1I2fRAVTU9l](https://user-images.githubusercontent.com/26559841/93690991-671cbc00-fa9c-11ea-9c44-74a563e4ba65.png)

**Comment by DaneEveritt** [comment]
We're (me) gonna have to re-work this entire mount code logic, it doesn't follow the normal principles I've seen for Laravel models like this, and its kind of just working with black magic (which is a lot of Laravel, but I hate).

**Comment by stanier** [comment]
@DaneEveritt in the meantime, could we address the issue of the `attach()` and `detach()` functions being non-existent?
