### ISSUE TITLE
[FileManager] Error creating a folder with multiple slashes

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2376]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/0908830003cd1338a7e162cdf8c596ebda98fd64 & https://github.com/pterodactyl/wings
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
```
ERROR: [Sep 20 09:18:55.056] encountered HTTP/500 error while handling request error=not a directory error_id=1dc31b90-50b9-4fac-a97f-981ef1e58983 server=e270ded0-ebfb-4210-8e48-b360177304dd

Stacktrace:
github.com/pterodactyl/wings/router.TrackedServerError
	/home/runner/work/wings/wings/router/error.go:36
github.com/pterodactyl/wings/router.postServerCreateDirectory
	/home/runner/work/wings/wings/router/router_server_files.go:271
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/pterodactyl/wings/router.ServerExists
	/home/runner/work/wings/wings/router/middleware.go:80
github.com/gin-gonic/gin.(*Context).Next
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161

DEBUG: [Sep 20 09:18:55.058] POST /api/servers/e270ded0-ebfb-4210-8e48-b360177304dd/files/create-directory client_ip=127.0.0.1 latency=2.233888ms status=500
```

**To Reproduce**
1. Create a folder in file manager `///////home/home2/home3/`

**Comment by matthewpi** [comment]
What should the intended behavior be?  As creating a directory with slashes in it (example: `tmp/tmp`) will create a `tmp` folder with another `tmp` folder inside.

It should probably return a 400 error instead of a 500 but this isn't really a bug.

**Comment by zKoz210** [comment]
I also think that returning a 400 error with a user-friendly message would be helpful

**Comment by DaneEveritt** [comment]
@matthewpi I think wings just needs to clean all of those slashes off and then it should work fine.

**Comment by parkervcp** [comment]
I am pretty sure linux handles multiple slashes by removing any extras.

Example `///////home//home2////home3/` becomes `/home/home2/home3/`

**Comment by DaneEveritt** [comment]
Well, something is clearly not working right then.

**Comment by DaneEveritt** [comment]
Figured this one out, it wasn't the slashes, its because you had a file named `home` (or `home2` inside `/home`). Same error occurs for normal FS operations outside of Wings as well. Added an error handler to catch those errors and make them not a 500 error.

**Comment by zKoz210** [comment]
@DaneEveritt This fixed, but the folder looks like this:
![image](https://user-images.githubusercontent.com/28255085/94027719-d4458f80-fdc3-11ea-8166-c407c44dd590.png)

after reload page:
![image](https://user-images.githubusercontent.com/28255085/94027867-fb9c5c80-fdc3-11ea-9b35-155cb698a788.png)

**Comment by DaneEveritt** [comment]
Then open a new bug please.
