### ISSUE TITLE
[FileManager] Invalid file renaming when creating a copy

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2380]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/0908830003cd1338a7e162cdf8c596ebda98fd64 & https://github.com/pterodactyl/wings
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
![image](https://user-images.githubusercontent.com/28255085/93709062-ef09d100-fb43-11ea-8218-70b8aa6d0521.png)

unarchive:
![image](https://user-images.githubusercontent.com/28255085/93709082-2aa49b00-fb44-11ea-9486-9ae82ba689df.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/28255085/93709053-e2857880-fb43-11ea-9e2a-d1654c08e91e.png)

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/wings/commit/ff597672db24f85a8ed46b38c86a55e88780047b
