### ISSUE TITLE
[Subusers] Add select all button back, as-well as "done" at top.

### ISSUE THREAD

**Issue by fadedmax** [pterodactyl/panel#2383]
**Is your feature request related to a problem? Please describe.**
As i have to migrate all my subusers over too the new system it would help to have a done button back.

**Describe the solution you'd like**
I just want users to have "control" permissions, and i dont really like scrolling all the way down, this is ui/ux
it would also help to have a select all button back.

**Additional context**
<img width="690" alt="Screen Shot 2020-09-21 at 00 17 23" src="https://user-images.githubusercontent.com/32599075/93737215-d3ccaf00-fb9f-11ea-8be8-d2cdb054d2e6.png">
<img width="694" alt="Screen Shot 2020-09-21 at 00 17 31" src="https://user-images.githubusercontent.com/32599075/93737222-d8916300-fb9f-11ea-937d-b3d3e9a687ae.png">

**ui/ux** and **1.0**

**Comment by fadedmax** [comment]
this is ui and ux mainly, good first issue.

I tried to polish this as best i can, but its 2am and i need sleep.

**Comment by notAreYouScared** [comment]
I see no need to have a select all button for all the permissions when each has a check box for each section.

**Comment by fadedmax** [comment]
@AreYouRlyScared I do, if a server owner wants to quickly add a bunch of perms, its just much simpler to press 3 times then 15 and scrolling a ton
