### ISSUE TITLE
Checkbox to start a server once installation completes does not do anything

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2384]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/0908830003cd1338a7e162cdf8c596ebda98fd64 & https://github.com/pterodactyl/wings/commit/62d5248b0c63bda6737eb8a799f9455317286430
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**To Reproduce**
1. Create a server
![image](https://user-images.githubusercontent.com/28255085/93744559-b7aa2b80-fbfa-11ea-8086-d06d912aa898.png)
2. You will see that the server does not start
3. Click to start server
![image](https://user-images.githubusercontent.com/28255085/93744290-423e5b00-fbfa-11ea-9c82-b11e680560c5.png)

**Comment by JacobPassam** [comment]
is this still a bug, or is there a way to fix this?

**Comment by DaneEveritt** [comment]
If it wasn't a bug this issue wouldn't exist, and if it was fixed the issue would be closed. :)

**Comment by JacobPassam** [comment]
Is there a known workaround?

**Comment by sergejostir** [comment]
Click the start button.

**Comment by timossileandro** [comment]
HI! 
I update this bug saying that even in version 1.2.2 it still does not work. 
Thanks, goodbye!

**Comment by JacobPassam** [comment]
I’ve resulted to forking pterodactyl to sort this.

**Comment by DaneEveritt** [comment]
Sweet, we accept pull requests to fix broken functionality if you've fixed it already. Otherwise it will get addressed when I have time to get around to it.

**Comment by JacobPassam** [comment]
Don't really know if it counts as a fix, more of a workaround. I've just edited the server installer in wings to send a start signal to every server that's installed - it's what I need for my use but it probably wouldn't be best in production as it doesn't take into account the value requested by the user (which I don't think is sent to the daemon in the first place?). It purely starts all servers no matter what. Only a quick fix, but it works for me.

**Comment by trenutoo** [comment]
This has already been resolved in 1.4.0

**Comment by JacobPassam** [comment]
> This has already been resolved in 1.4.0

Doesn't seem to work in 1.4.2.

**Comment by trenutoo** [comment]
> > This has already been resolved in 1.4.0
> 
> Doesn't seem to work in 1.4.2.

It wasn't actually merged, which I completely missed. There's currently a PR to implement it for the panel and wings.

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/pull/3431
