### ISSUE TITLE
[Server] Error sending command when starting the server

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2385]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/0908830003cd1338a7e162cdf8c596ebda98fd64 & https://github.com/pterodactyl/wings/commit/62d5248b0c63bda6737eb8a799f9455317286430
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
![image](https://user-images.githubusercontent.com/28255085/93745576-7155cc00-fbfc-11ea-895a-ae316bf0884a.png)
Update:

A similar situation is repeated if you quickly press the "Restart", "Stop", and "Kill" buttons in any order when the server is turned on
![image](https://user-images.githubusercontent.com/28255085/93747106-e2967e80-fbfe-11ea-97b2-846a60be011a.png)

**To Reproduce**
Click the "Start" button and try to enter commands in the console as quickly as possible

**Comment by AreYouRlyScared** [comment]
I mean this is normal behavior as the container hasn't started yet.

**Comment by DaneEveritt** [comment]
Don't think this is really a bug so much as it is just a weird logic check that is happening. Doesn't really need to hit you with that error if you send a command and it is stopped, should just send the normal "server not running".
