### ISSUE TITLE
[WINGS] Docker containers using UTC time instead of local host time

### ISSUE THREAD

**Issue by MAXOUXAX** [pterodactyl/panel#2389]
**Background:**
* Panel or Daemon: Daemon Wings
* Version of Panel/Daemon: 1.0.0-rc.6
* Server's OS: Debian 10
* Your Computer's OS & Browser: Not relevant

**Describe the bug**
When I was using the old NodeJS Daemon, Docker containers were synchronized to the local host time, but now that I switched to the new Wings Daemon, the Docker containers are using UTC time, which is a HUGE problem for almost all the servers I host.
I saw the issue #2351 so let me give some more details:
When I retrieve the date with a random Java program and print it in the console, I get the UTC time instead of the local host time.

**Expected behavior**
Docker containers should be, as they were, synchronized with the local host time instead of UTC.

**Comment by DaneEveritt** [comment]
This has been covered already by https://github.com/pterodactyl/panel/issues/2239#issuecomment-675213274 and https://github.com/pterodactyl/panel/issues/2329

**Comment by MAXOUXAX** [comment]
There's something that I don't get: why timezones worked great with the NodeJS Daemon and I never had issue with those, and not with this new Wings Daemon ?

**Comment by parkervcp** [comment]
They may have worked for you just fine but several people had issues with the timezone being off by a few hours with the node daemon as well.

**Comment by kFxDaKing** [comment]
same problem here
for Europe/Prague
