### ISSUE TITLE
Containers/Service Options to add for v0.6

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#239]
- [ ] Factorio
- [ ] Minecraft: PE
- [ ] Rust
- [ ] CS:GO (Works on the 'Other Steam Game', but very popular)
- [ ] Others?

**Comment by parkervcp** [comment]
- [ ] SA:MP (San Andreas Multiplayer)
- [ ] Forge Minecraft Server
- [ ] SinusBot #171 
- [ ] ARK
- [ ] Space Engineers

**Comment by ccarney16** [comment]
- [ ] Arma 2/3 (along with DayZ support)
- [ ] Space Engineers
- [ ] JC2 Multiplayer

**Comment by schrej** [comment]
We could add all those for people to download (from nest?)

**Comment by DaneEveritt** [comment]
These requests are now being tracked at https://github.com/Pterodactyl/Dockerfiles/projects/1 which is managed by @parkervcp
