### ISSUE TITLE
[Accounts sessions] Last session revoked when logging in from somewhere else

### ISSUE THREAD

**Issue by MAXOUXAX** [pterodactyl/panel#2390]
**Is your feature request related to a problem? Please describe.**
Indeed, it is.
So I recently migrated from 0.7 to 1.0 and realized that the current session was revoked when logging in from another device.
While this may be "OK" for many use cases, it is not the case for mine.
I'm using the Panel from my Main PC, my laptop and phone, and having to always log back in is annoying.

**Describe the solution you'd like**
Re-adopt the same behavior as 0.7, which allowed having more than one session at a time.

**Comment by fabm3n** [comment]
I'm currently loggen in on mutliple devices.
If you have issues with this, open a Bug Report, not a Feature Request.

**Comment by DaneEveritt** [comment]
Cannot reproduce with the information provided.
