### ISSUE TITLE
Create server but not showing

### ISSUE THREAD

**Issue by Pidihajzlikhra** [pterodactyl/panel#2394]
When i create server i cant add Server owner, not showing. I cant write in line 
![Pterodactyl](https://user-images.githubusercontent.com/33321731/93923563-d5b77f00-fd13-11ea-9f7e-86b7c581c175.png)

**Comment by DaneEveritt** [comment]
Clear your browser cache.

**Comment by Pidihajzlikhra** [comment]
No working

**Comment by Pidihajzlikhra** [comment]
@DaneEveritt not work

**Comment by DaneEveritt** [comment]
Please use Discord for further support, this has always been a cache issue and there is no information here in this bug report so I'm not going to look into it further. If you truly believe this is a bug please confirm first by clearing the cache and removing whatever theme customization you've made here, and then re-open this issue and actually follow the template, which makes it _incredibly clear_ what is required for a bug report.
