### ISSUE TITLE
Backups can still be made via schedules

### ISSUE THREAD

**Issue by fadedmax** [pterodactyl/panel#2395]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-rc.6
* Server's OS: Ubuntu
* Your Computer's OS & Browser: Mac, Chrome

**Describe the bug**
Creating a schedule on a server that can not have backups allows you to still have backups

**To Reproduce**
1. Go to a server that does not allow backups
2. Click on schedule
3. Click on new task
4. Click on action, then new backup
5. You can still have it as part of the schedule

**Expected behavior**
It does not appear or it will show a error message

<img width="690" alt="Screen Shot 2020-09-22 at 16 42 28" src="https://user-images.githubusercontent.com/32599075/93944674-9af11f00-fcf2-11ea-8032-f8550b2cab2a.png">
<img width="848" alt="Screen Shot 2020-09-22 at 16 42 40" src="https://user-images.githubusercontent.com/32599075/93944692-a2b0c380-fcf2-11ea-8061-26d3ebd4d49b.png">

**Comment by fadedmax** [comment]
**ignore the highlight on databases, thats where my mouse was while i was taking the screenshot**

**Comment by AreYouRlyScared** [comment]
But does it actually make the backup?
