### ISSUE TITLE
"Failed to validate reCAPTCHA data" after failed login attempt

### ISSUE THREAD

**Issue by DaneEveritt** [pterodactyl/panel#2397]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: `develop`
* Your Computer's OS & Browser: OSX Firefox & Chrome

**To Reproduce**
1. Hit the login page, ensuring recaptcha is enabled on the Panel instance.
2. Enter an incorrect password, see expected error.
3. Enter correct password and try logging in again.
4. See error.
5. Refresh page, login with correct credentials, works.

**Comment by aprilthepink** [comment]
stil having same bug

**Comment by schrej** [comment]
That might be because this was fixed yesterday and there hasn't been a release yet.

**Comment by skerit** [comment]
I just had this issue again, on a new install I made by following the install guide.
Only thing that is different is that I'm running it via PHP-FPM and behind a reverse proxy.
Disabling recaptcha allowed me to login.

**Comment by MarkJesterMC** [comment]
How to disable reCaptcha?

**Comment by schrej** [comment]
You can set `RECAPTCHA_ENABLED=false` in your .env file, see here: https://github.com/pterodactyl/panel/blob/1.0-develop/config/recaptcha.php#L7
