### ISSUE TITLE
Hitting disk limit results in weird behaviour after corrected...?

### ISSUE THREAD

**Issue by AreYouRlyScared** [pterodactyl/panel#2401]
**Background (please complete the following information):**
* Panel or Daemon: Wings?
* Version of Panel/Daemon: Rc 6
* Server's OS: Ubuntu 18.04

**Describe the bug**

![aNvpMxP](https://user-images.githubusercontent.com/1757840/93976568-2d231280-fd47-11ea-83de-ac3e1d65908f.gif)

When a server hits its disk limit, the console prints a "cannot start server, not enough disk space available" as expected.

Once files are deleted to allow the server to start the disk usage is printed as `NaN undefined` and allows the server to start... 
Even if the server is still over its disk usage.... until the next disk space check 
![image](https://user-images.githubusercontent.com/1757840/93976220-aa9a5300-fd46-11ea-83eb-42ecc273bace.png)

Once the next disk check passes, it's displayed correctly but is still over 
![image](https://user-images.githubusercontent.com/1757840/93976366-e1706900-fd46-11ea-8819-c097a1c3c092.png)

As you see it's still over..... But i was able to still start the server as it was "NaN undefined"

Wings reports the disk usage as a negative number shown below
```
{
   "event":"stats",
   "args":[
      "{
	  "memory_bytes":955498496,
	  "memory_limit_bytes":2355200000,
	  "cpu_absolute":5.529,
	  "network":{"rx_bytes":4390,"tx_bytes":4390},
	  "state":"running",
	  "disk_bytes":-6645192009
      }"
   ]
}
```

While the disk size is stated as NaN undefined, this allows the server to start even if its STILL over its limit. 

Kind of hard to explain in text. @Dane I can talk with you if you're not able to understand what I'm explaining. 

**To Reproduce**
1. Create a server with a low disk limit
2. put the server over the disk limit and wait for the next "disk size check interval"
3. Attempt to start the server
4. Remove files that put the server "over" the limit
5. Observe the NaN undefined in the disk usage section on the console page
 Note: After ANOTHER disk size check the correct size is shown.

**Expected behavior**
Good question...

**Comment by DaneEveritt** [comment]
Pretty sure I'm doing some bad math somewhere in that delete function which is subtracting far too much from the current limit, thus causing it to go negative. This report is A+ on details, I think I can reproduce that.
