### ISSUE TITLE
Support modifying constraints while a server is running

### ISSUE THREAD

**Issue by TheNickSkater** [pterodactyl/panel#2402]
**Describe the solution you'd like**
It would be cool to have an option just like the MAX-CPU usage, but for time a Server is starting.
Why? Well, some Servers use extremely much CPU performance on Startup, but may only use very little when finally ready.
This leads to a high CPU usage for the time the server starts which may influence other tasks.

Sure, startup time may take longer, but uses less CPU.

**Comment by schrej** [comment]
Why not simply limit the CPU further in general? You're saying the service only requires a lot of CPU during startup anyway, so why would it even need a higher limit after startup?

**Comment by TheNickSkater** [comment]
> Why not simply limit the CPU further in general? You're saying the service only requires a lot of CPU during startup anyway, so why would it even need a higher limit after startup?

In some occasions I actually need the performance some times while the Server is running (where I know it wont interfere with anything). For example my Paper server takes 400% if I set it to 400% on startup just because of world loading, but I do need those 400% later if players load chunks.

**Comment by schrej** [comment]
While I don't see this getting added as a feature to pterodactyl directly, it might be worth to consider supporting modification of resource limits while a server is running. This could allow add-ons to implement behavior like this.
Whether that's going to happen is for Dane to decide though.

My idea would be to reach out to wings when resource constraints are changed and have it reply with details about which constraints were applied and which require a container rebuild to become effective. Afaik CPU constraints can be modified, RAM constraints can't.

**Comment by DaneEveritt** [comment]
You can already change CPU & Memory and have those limits applied immediately to the container. I have no intention of making limits that change based on process state, its just a weird scenario honestly and I don't see it as a good fit for the software.
