### ISSUE TITLE
[FileManager] An error occurs when creating a file/directory with a long name

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2403]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/cbedd4539c750fd647ee13dee15c7cb0556029c2 & https://github.com/pterodactyl/wings/commit/f0a4efb242a66c1ec34b1139e8853ab1795cfeea
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
![image](https://user-images.githubusercontent.com/28255085/94028713-c2182100-fdc4-11ea-9550-a1d759da8cd6.png)

**To Reproduce**
Create file/directory with name 
`
$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception$exception
`

**Comment by fadedmax** [comment]
uhh, i mean, why would it need to be this long, and have you tried other names?
