### ISSUE TITLE
[Database] An error occurs when creating a database with a long name

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2404]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/cbedd4539c750fd647ee13dee15c7cb0556029c2 & https://github.com/pterodactyl/wings/commit/f0a4efb242a66c1ec34b1139e8853ab1795cfeea
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
There is a limit of up to 64 characters, which does not correspond to the actual length of the database name.

We need to subtract the number of letters in the prefix to work correctly

![image](https://user-images.githubusercontent.com/28255085/94029926-f04a3080-fdc5-11ea-85c5-3e1eef1c3bcb.png)

**To Reproduce**
Create name with name 64 `a`

**Comment by AreYouRlyScared** [comment]
I feel that this is correct it's telling you that the name is too long... I know mysql 8 has a limit of 64... not sure on other versions.
