### ISSUE TITLE
[FileManager|UI] Folder with an empty name by creating with multiple slashes

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2407]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/cbedd4539c750fd647ee13dee15c7cb0556029c2 & https://github.com/pterodactyl/wings/commit/f0a4efb242a66c1ec34b1139e8853ab1795cfeea
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
![image](https://user-images.githubusercontent.com/28255085/94027719-d4458f80-fdc3-11ea-8166-c407c44dd590.png)

after reload page:
![image](https://user-images.githubusercontent.com/28255085/94027867-fb9c5c80-fdc3-11ea-9b35-155cb698a788.png)

**To Reproduce**
1. Create a folder in file manager `///////home/home2/home3/`

**Comment by DaneEveritt** [comment]
Merging this with https://github.com/pterodactyl/panel/issues/2377
