### ISSUE TITLE
Wings error

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2409]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/cbedd4539c750fd647ee13dee15c7cb0556029c2 & https://github.com/pterodactyl/wings/commit/f0a4efb242a66c1ec34b1139e8853ab1795cfeea
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
I don't know how to describe the error, so I created a .gif for you
![image](https://user-images.githubusercontent.com/28255085/94038032-a9ad0400-fdce-11ea-9b03-54a92406beb1.png)

**To Reproduce**
![2020-09-23-190447](https://user-images.githubusercontent.com/28255085/94039510-7e2b1900-fdd0-11ea-9c36-4f83d07d9726.gif)

**Comment by AreYouRlyScared** [comment]
So reinstalling the server while its starting results in. No container error...

**Comment by DaneEveritt** [comment]
Please provide written steps to reproduce, not a single gif since I cannot follow what you're doing there.

**Comment by VottusCode** [comment]
> Please provide written steps to reproduce, not a single gif since I cannot follow what you're doing there.

1. Start the server
2. Stop the server
3. Reinstall the server
4. Check wings

**Comment by zKoz210** [comment]
I start the server and try to reinstall it as quickly as possible, as a result I get such errors. For simplicity, I have opened two pages in different windows

**Comment by DaneEveritt** [comment]
Thanks @zKoz210. Sounds like we could pretty easily solve for this by just blocking until whatever current power action has finished running since there is a lock we can check for. Should keep things pretty simple.
