### ISSUE TITLE
php socket 7.2 > 7.4

### ISSUE THREAD

**Issue by Twonkk** [pterodactyl/panel#2419]
Panel or Daemon: Panel
Version of Panel/Daemon: Panel 0.7
Server's OS: Ubuntu 20.04
Your Computer's OS & Browser: ANY
 
[https://github.com/Pterodactyl/Panel/issues/913](url)
> * Panel or Daemon: Panel
> * Version of Panel/Daemon: v0.7 RC
> * Server's OS: Ubuntu
> * Your Computer's OS & Browser: Not relevant
> 
> ## Add Details Below:
> In the documentation PHP 7.2 gets installed. However in the nginx webserver configuration the php 7.1 socket still gets used, resulting in a 502 bad gateway error.
> 
> ## Fix
> Change `fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;` to `fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;`

same issue as this except with php7.4-fpm.sock.. ubuntu server 20.04 installs php7.4 by default, if i downgrade back to 7.2 everything works.

error below is from my log file

`2020/09/26 00:34:14 [crit] 505364#505364: *154 connect() to unix:/run/php/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.1.1, server: example.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "example.com"`

**Comment by DaneEveritt** [comment]
If this is an issue with the documentation please open a PR in that repository to fix it.
