### ISSUE TITLE
Adding Locations and Nodes from CLI

### ISSUE THREAD

**Issue by parkervcp** [Pterodactyl/Panel#242]
### What to add to
- [x] Panel
- [x] Daemon
### Request Type
- [x] Feature Request
- [x]  Enhancement

Add CLI commands for adding locations and nodes to the panel.

Also support for auto-grabbing daemon configs for daemons to connect with a single use key for initial setup.

**Comment by parkervcp** [comment]
I am looking at "I have the node installed" and have a 
`npm start -panel_url "http(s)://subdomain.domain.tld" -key <insertrandomstringhere>` 
and the daemon starts and grabs it's config

**Comment by schrej** [comment]
But that requires to manually install the daemon before doing that. I guess a fully automated installer with automatically added config would be even better. But we could do both I'd say. For when the auto installer fails to at least automatically configure.

**Comment by parkervcp** [comment]
I have docker containers with a working daemon install...

**Comment by schrej** [comment]
ah right, completely forgot about those, ok, then we/i'll do both
