### ISSUE TITLE
File manager archive function ignores disk space limits

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2420]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/4f21fa85f879b4dc05effe90d279767333b18bef & https://github.com/pterodactyl/wings/commit/3391d5803e442ca03b51906fb755075ff20e8298
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
I tested with a PocketMine-MP egg. The bottom line is that at some point the update of the remaining free space freezes and you can exceed the allowed limit.
![image](https://user-images.githubusercontent.com/28255085/94338767-85833a00-fffd-11ea-909f-03a546b90f05.png)

**To Reproduce**
Again, I only tested with the PocketMine-MP egg.
1) Creating a clean server (50 MB)
2) archive the `bin` folder (there is little space left, about 20 MB)
3) Archive the PocketMine-MP.phar file many times (20-25) and we will see in a couple of minutes that the limit was exceeded

- When creating a new file, disk restrictions are not taken into account
- Creating a limit of 50 megabytes, filling the disk with 46 megabytes, and trying to upload a file weighing 7 MB - we were able to circumvent the restrictions
- Delete all files from the file manager, fill in 50 MB. Reinstall server again, we bypassed the restrictions on the disk

**Comment by DaneEveritt** [comment]
Server re-installs do not care about disk space limits, just FYI (and I have no intention of making them care).

**Comment by zKoz210** [comment]
Creating and uploading files has been fixed, thank you. However, the problem with archiving is still open.



See video https://youtu.be/djiFdVfxEsE

**Comment by zKoz210** [comment]
@DarthShmev ping
