### ISSUE TITLE
A bug with the rendering of data servers

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2424]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/47697e07cfeee569bea15d57ab1eaac07a89cfc4 & https://github.com/pterodactyl/wings/commit/4748d7cb294cba802894a27a8cc968fb061bc581
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
If the server is turned off and we go from the "Console" tab to any other one, and then return, the data about the storage and the console will be empty.

![image](https://user-images.githubusercontent.com/28255085/94364224-74572d80-00d0-11eb-8a79-fc1ee116e12e.png)
![image](https://user-images.githubusercontent.com/28255085/94364231-7d47ff00-00d0-11eb-957f-208b5ccc1bdf.png)

**To Reproduce**
The server must be turned off!
1) Open the home page for the server (console, management)
2) Go to the file manager or another tab, go back - the server data (disk, console) will be empty

**Comment by DaneEveritt** [comment]
dupe #2414
