### ISSUE TITLE
Reset "is_processing" state on schedules when enabling/disabling it.

### ISSUE THREAD

**Issue by Pho3niX90** [pterodactyl/panel#2425]
**Background (please complete the following information):**
* Panel or Daemon:  Daemon
* Version of Panel/Daemon:  1.0.0-rc.6 (Wings)
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chrome

Non standard cron setup doesn't seem to work, this should either be displayed with an error, or more importantly work. 

**To Reproduce**
1. Go to 'Server control'
2. Click on 'Schedules'
3. Create a schedule, with the following "*/30 5 * * *"
4. Schedule will never run.

**Expected behavior**
There are multiple reason why this would be needed. A user might want to send a message every 5mins ONLY between 5 & 6. Expected behavior is for it to do it as such.

**Comment by DaneEveritt** [comment]
Did you confirm that `pteroq` is running? If the schedule lets you make it with that cron (which isn't even a non-standard cron), it means Pterodactyl was able to parse it and was fine with things.

If it never ran, it means your queue worker isn't running, or stopped running. Try giving it a reboot and see if that gets things working.

**Comment by Pho3niX90** [comment]
It seems that the queue worker was in fact down. I will monitor it for the next 24hours and report back. 

Might be worthwhile to report liveliness on the administration panel.

**Comment by Pho3niX90** [comment]
It has not worked for the above mentioned scenario. For a simple cron that runs every 5mins it works:

Here is a screenshot
![image](https://user-images.githubusercontent.com/7858187/94520989-8bf7f880-022d-11eb-9f82-5d6905e7ad1c.png)

**Comment by DaneEveritt** [comment]
What is in the database for the `next_run_at` time for that schedule (in the `schedules` table).

**Comment by Pho3niX90** [comment]
So this is the status from the service: 
![image](https://user-images.githubusercontent.com/7858187/94685485-c34bcf80-0329-11eb-860f-0c341b14fba0.png)



And this is the info from the DB:
![image](https://user-images.githubusercontent.com/7858187/94685400-aca57880-0329-11eb-8f36-bac1c3f5e894.png)

Note I just created the 'Test' schedule to test. You will notice I tried different times as well for restarts, non is working/running.

**Comment by DaneEveritt** [comment]
Interesting, looks like they got stuck in the `is_processing` state for some reason. Can you set that `5 */30`one to `is_processing = 0` and see what happens?

**Comment by Pho3niX90** [comment]
When I changed the value to `0`, all of the schedules ran, within a minute.

**Comment by DaneEveritt** [comment]
Yeah, something seems to have locked them up somehow. Did they reset to 0 after running?

**Comment by Pho3niX90** [comment]
Yes they did reset afterwards. I will wait till the time elapses and see if it runs, or locks again, will let you know. It might have locked due to the fact that the worker wasn't started the first time?

**Comment by Pho3niX90** [comment]
Alright, so after 3 days it all seems to be fine. 

One suggestion would be that if a schedule is turned off, to maybe reset `is_processing` to 0? Or alternatively have a button to reset it from the UI when in edit mode? Example: 
![image](https://user-images.githubusercontent.com/7858187/94989312-07321500-0574-11eb-891a-3181ca1005a9.png)

The button could even have a condition to display ONLY when the `is_processing` is 1?
