### ISSUE TITLE
Integrating Traefik

### ISSUE THREAD

**Issue by kubo6472** [pterodactyl/panel#2426]
**Is your feature request related to a problem? Please describe.**
Some plugins have interfaces or provide some kind of http traffic, it is quite hard to keep track of all the ports needed to be open.

**Describe the solution you'd like**
I would like to see traefik integrated into the panel.

**Describe alternatives you've considered**
I tried installing it manually and setting up its own interface, but that alone kinda defeats the purpose, combined with that I need to move between two interfaces, always configuring everything manually...

**Additional context**
I imagine a checkbox in settings, or some option during installation, that would install traefik, and an option in "allocation" to add domains and subdomains that would get assigned automatically.

**Comment by DaneEveritt** [comment]
Interesting idea, but this is not something that I see being beneficial to a majority of users running this software, and is yet another moving piece in an already complex system that I do not wish to maintain at this time. 👍
