### ISSUE TITLE
Deleting subuser don't block access to power and the console

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2429]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/f31a6d3967b89b7b37ef41d677efd0add73de606 & https://github.com/pterodactyl/wings/commit/0f7bb1a3716c335bd2a2f9f4d713205e2fd0fe12
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
Deleting subuser don't block access to power and the console. I understand that there is a token lifetime after which access is closed. The question is, is it possible to deny access immediately?

**To Reproduce**
1) Adding a subuser
2) Go from another account to the "Console" tab
3) Deleting a subuser
4) Switch to a different account and you still have access to the console, commands, and power controls for a short time

**Comment by DaneEveritt** [comment]
This is working as it was designed to work, and right now I'm fine leaving it as is and coming back to it at a later date. For reference, it works the exact same way on 0.7.
