### ISSUE TITLE
Hidden server status in the server list

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2431]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/f31a6d3967b89b7b37ef41d677efd0add73de606 & https://github.com/pterodactyl/wings/commit/0f7bb1a3716c335bd2a2f9f4d713205e2fd0fe12
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
For some reason, you have hidden the status of the servers. 

![image](https://user-images.githubusercontent.com/28255085/94427005-16d9e400-0197-11eb-890b-2ac0a08bdc7b.png)

![image](https://user-images.githubusercontent.com/28255085/94426863-e5611880-0196-11eb-8e71-5cb68db5ebad.png)

Control panel itself does not attempt to reconnect without reloading the page if wings was not started at boot ("Connection error")

**Comment by DaneEveritt** [comment]
@LeCodeCo is this some code you added? Doesn't look like anything I wrote 🤔

**Comment by AreYouRlyScared** [comment]
Thats used for the status indicator on mobile as you can't see the resource usage

**Comment by AreYouRlyScared** [comment]
![Uploading Screenshot_20200928-172335_Chrome.jpg…]()

**Comment by zKoz210** [comment]
![image](https://user-images.githubusercontent.com/28255085/94515832-27d53480-022d-11eb-8887-bf4f26d3fcb5.gif)


Gif from README, on md, lg it would be great to see such a status too for more informational content

**Comment by AreYouRlyScared** [comment]
It was there.... but removed as it didn't flow well.

**Comment by matthewpi** [comment]
This is intentional behaviour, the status was originally on the server list on desktop but was removed as it didn't flow well with the UI.

**Comment by DaneEveritt** [comment]
It should be there though, we just decided that specific design was garbage and it needed a better one.

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/panel/commit/d1c30607cf2fe73192952cf7192a5f120a1c7eae
