### ISSUE TITLE
WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by d0m3y03** [pterodactyl/panel#2432]
**Background:**
* pterodactyl-panel-1.0.0-rc.6/
* Debian 10
* Windows 10/Brave (Chromium)

**Describe the bug**
When I'm trying to do anything on any server of my panel, I alway get the error
"We're having some trouble connecting to your server, please wait..."
Then I looked into the Browser Console and saw this error.
![image](https://user-images.githubusercontent.com/72037533/94464448-c8d8d680-01be-11eb-93f0-151e9a73946b.png)

**To Reproduce**
1. Logged into my panel
2. Clicked on a server
3. Error.
4. Saw the error in my browsers console

**Expected behavior**
I wanted to start my servers.

**Comment by DaneEveritt** [comment]
https://acp.tofg.de:37481/api appears to be inaccessible in my browser, which would explain why it cannot connect.

**Comment by d0m3y03** [comment]
And how can I fix that?

**Comment by matthewpi** [comment]
Check the wings logs (`/var/log/pterodactyl/wings.log` should be the default path) and your firewall settings.  Also, the information you provided isn't very helpful, stating you have connection issues on the browser doesn't really help narrow down any potential bugs.

**Comment by d0m3y03** [comment]
Okay, I've just changed the port of the Node, copied the config to wings, restarted wings, and now it works. I don't exactly know what the problem was, but it's working now!

**Comment by otDan** [comment]
This still happens on the brave browser, when you restart a vpn that makes you connect to the panel you cannot see the console until you restart the browser or you will have the "WebSocket is closed before the connection is established" log

**Comment by HussainBeast** [comment]
> Check the wings logs (`/var/log/pterodactyl/wings.log` should be the default path) and your firewall settings. Also, the information you provided isn't very helpful, stating you have connection issues on the browser doesn't really help narrow down any potential bugs.

dude  i am noob can you pls telll me how to fix it i cant not understand what you said i am geting same problem pls help ;/

**Comment by HussainBeast** [comment]
bundle.f57341e4.js:1 WebSocket connection to 'wss://node3.epikhost.xyz:8080/api/servers/8daf1309-baf8-41e7-a738-2a21055be8cd/ws' failed: WebSocket is closed before the connection is established.

**Comment by LoneDev6** [comment]
This happens to me sometimes.
A restart of the browser fixes the issue.

**Comment by Pinou007** [comment]
I have the same problem how to solve it?

**Comment by LoneDev6** [comment]
> This happens to me sometimes.
> A restart of the browser fixes the issue.

This:
> A restart of the browser fixes the issue.

Also try incognito mode.

**Comment by fabian4613** [comment]
I have the same problem, I have already tried different browsers.

**Comment by fabian4613** [comment]
In my case I have solved it by correctly defining the fqdn used by the websocket.

I was guided by the following:

- Retry with another browser or delete cookies
- DNS settings
- Definition of FQDN

**Comment by cheshire4cat** [comment]
check the wings or some connection shit

**Comment by elutac** [comment]
Restarting wings with `systemctl restart wings` solved it for me.
