### ISSUE TITLE
Remove obsolete fields in the settings

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2435]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/f31a6d3967b89b7b37ef41d677efd0add73de606 & https://github.com/pterodactyl/wings/commit/0f7bb1a3716c335bd2a2f9f4d713205e2fd0fe12
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
https://github.com/pterodactyl/panel/blob/develop/resources/views/admin/settings/advanced.blade.php#L85-L107

**Comment by AreYouRlyScared** [comment]
They're still used?

https://github.com/pterodactyl/wings/blob/develop/config/config_throttles.go

Most likely the panel hasn't been updated for the variables. As throttling was just added not that long ago to wings...

**Comment by DaneEveritt** [comment]
They're actually unused, wings handles all of the throttling and the values aren't defined anywhere in the panel. These are from the old frontend specific throttling (which doesn't exist anymore).
