### ISSUE TITLE
Panel Incorrect Zoom - 1.0.0-rc.6

### ISSUE THREAD

**Issue by Hamster-0001** [pterodactyl/panel#2436]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-rc.6
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 64 Bit, Firefox 81.0

**Describe the bug**
When zooming out and back in on the console screen, it causes the console and graph boxes to become unaligned and zoomed-in incorrectly. (Displays as over 100% while browser zoom is 100%). 

Example: https://cdn.foxybots.xyz/H5wl8L

Please provide additional information too, depending on what you have issues with:
Panel: php7.4

**To Reproduce**
1. Open a live server console
2. Zoom out to the browser maximum (30% When reproducing)
3. Reset the zoom (On Firefox, click the zoom percentage)
4. The console and graph boxes should now be enlarged and unaligned

**Expected behavior**
The console should return to the aligned setup, console on the top next to the statistics of the server and the graphs below it left and right. 

Correct View: https://cdn.foxybots.xyz/jv3b4c

**Comment by zKoz210** [comment]
Fixed in https://github.com/pterodactyl/panel/pull/2411
