### ISSUE TITLE
Deletion of server doesn't delete?

### ISSUE THREAD

**Issue by aidanellyer** [pterodactyl/panel#2438]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0 // Wings 10.o 
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Firefox & Windows 10 

**Describe the bug**
Please provide additional information too, depending on what you have issues with: When deleting a server there is no changes within storage, here's some stats I pulled from my VPS, and between these times there have been multiple server deletions, 
![image](https://user-images.githubusercontent.com/11576326/94845036-00da5680-0417-11eb-98b0-fc412fafe457.png) as you can see there has been no dip in storage space. 

Panel: 7.3

**To Reproduce**
1. Go to the deletion page
2. Click on safely delete
3. No change in storage

**Expected behavior**
Storage space should drop when deletion of a server occurs.

**Comment by DaneEveritt** [comment]
Can you please confirm by looking in the actual server directory that they're not being deleted, rather than relying on a graph of unknown origin for us. Thanks.

**Comment by aidanellyer** [comment]
Hi @DaneEveritt I can confirm that in /svr/daemon-data the only servers that exist there are the current deployed servers. However that graph is pulled directly from vmanager which monitors all my VPS resources.

**Comment by DaneEveritt** [comment]
Well, I'm not sure what to tell you if the data files are indeed gone. That seems to indicate that it isn't calculating disk space correctly, or they're hiding in some other location (which would be... interesting).

I know on OSX at least with Docker it creates a type of volume that only goes down in size as needed, and therefore can inflate the total disk usage. Is it possible something like that is occurring? If wings is properly deleting the files from the system when a server is deleted, but your graph isn't updating, I'm strugging to see how its a bug with this software specifically. 👍

**Comment by zKoz210** [comment]
@DaneEveritt This was not the case until the latest changes https://github.com/pterodactyl/wings/commit/0f7bb1a3716c335bd2a2f9f4d713205e2fd0fe12

![image](https://user-images.githubusercontent.com/28255085/94855926-ed8bb300-0437-11eb-8e89-fce529ee44c6.png)

**Comment by AreYouRlyScared** [comment]
Thats deleting a backup archive. Not the server itself as this issue was created for.

**Comment by DaneEveritt** [comment]
I could not replicate the issue of disk space not freeing up, and based on what you're describing I'm not sure what specifically would be your issue here since the data directories are indeed being removed.
