### ISSUE TITLE
Shared Databases between Servers

### ISSUE THREAD

**Issue by IConnC** [pterodactyl/panel#2443]
I find myself trying to access data stored in a  MySQL database from multiple servers but it seems as if I am unable to share databases between the servers using the built in database manager. What I resort to doing is creating the database manually and accessing it through the external IP of the physical server from each individual Pterodactyl game server. It would be great if we were able to share databases between the servers.

**Comment by DaneEveritt** [comment]
They're already available between servers, however the instance itself is associated with a specific server UUID, and not with the account that owns the server.

I have no plans on changing this at this time, but I'm pretty sure there is another issue somewhere in this repo about this.
