### ISSUE TITLE
Panel is not reading disk usage for servers correctly

### ISSUE THREAD

**Issue by x390** [pterodactyl/panel#2445]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-rc.7
* Server's OS: Debian 10 (buster)
* Your Computer's OS & Browser: Brave V1.14.84

**Describe the bug**
Frontend of the panel is showing a disk usage of 0kb for server when they do have data on and have been installed.
PHP version: 7.4.10
![Image](https://user-images.githubusercontent.com/31023360/95007744-daa6f780-065e-11eb-9554-97a0e038e42a.png)

**To Reproduce**
Go to any server on the frontend of the panel and it will display  wrong disk usage.

**Expected behavior**
Panel should be showing disk usage for the server.

**Comment by CemaICT** [comment]
I have a similar issue where some of my servers are showing incorrect disk usage, example ~10GB instead of the 65GB it actually is. And because of the wrong reporting the can exceed the hard limit.

**Comment by Thegoodmen** [comment]
I think its fitting to jump on here. 

I am working on an API warpper right now and the Resource usage curl is also giving out 0kB on working and running Servers .

`

        "current_state": "running",
        "is_suspended": false,
        "resources": {
            "memory_bytes": 1352216576,
            "cpu_absolute": 0.253,
            "disk_bytes": 0,
            "network_rx_bytes": 2509690,
            "network_tx_bytes": 2509690
        }
`

**Comment by DaneEveritt** [comment]
Yes, I am aware of this. It simply got forgotten in the big filesystem change to wings.

**Comment by tmunsch** [comment]
I am having a similar issue, However mine seems to be only related to my Centos Installs
