### ISSUE TITLE
SFTP/ WebFTP Broken after upgrading to RC7 from RC6

### ISSUE THREAD

**Issue by elliotnichols** [pterodactyl/panel#2449]
**Background (please complete the following information):**
* Panel or Daemon: RC7
* Version of Panel/Daemon:  RC7
* Server's OS: Ubuntu 18.04 LTS
* Your Computer's OS & Browser: MacOS - Chrome 85

**Describe the bug**
Unable to upload files through SFTP and WebFTP

Errors from Wings:
https://pastebin.com/wZuR5tr1

A persistent upload wheel on the web panel. No errors in the console.
Upload timeout on Filezilla due to "inactivity"

**To Reproduce**
Upgrade from RC6 to RC7
Attempt to upload via WebFTP or SFTP (FileZilla)

**Expected behavior**
Upload of the file to succeed.

**Comment by AreYouRlyScared** [comment]
Those logins aren't even valid logins.... so of course, they're not going to work...?

**Comment by elliotnichols** [comment]
> Those logins aren't even valid logins.... so of course, they're not going to work...?

The point is, in RC6 these were not appearing. In RC7 these DO appear. It is a difference between the two versions.
It seems like a test unit may have been left in?

**Comment by DaneEveritt** [comment]
No, you just have a bot trying to log into your server, this is entirely normal and not a bug.
