### ISSUE TITLE
Panel downloads files when you upload them while one is still uploading

### ISSUE THREAD

**Issue by JackCrispy** [pterodactyl/panel#2451]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0
* Server's OS: centos7
* Your Computer's OS & Browser: win 10, chrome

**Describe the bug**
When uploading files using the panel file manager, when uploading 1 and then trying to upload another one at the same time while the first one is there and has a loading bar, will download the file to your pc.

**To Reproduce**
1. Go to File Manager
2. Upload a file
3. Whilst that file is uploading drop another file on the screen to upload
4. See that it will say Drop file to upload & it will not upload it, it will Download it

**Expected behavior**
It either uploads it or says you cannot upload multiple files

**Comment by schrej** [comment]
Please specify the version you were using. Latest can both refer to 0.7 as well as 1.0. In addition, if the issue would stay open for a longer time, it would be unnecessary work to figure out which version was "latest" at the time. Thanks!

**Comment by JackCrispy** [comment]
its latest 1.0.0 also can repo it on rc 7

**Comment by matthewpi** [comment]
Fixed in v2 due to changes how file uploads work.
