### ISSUE TITLE
Unspecified error when uploading temp files (zip/rar)

### ISSUE THREAD

**Issue by JackCrispy** [pterodactyl/panel#2452]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: latest 
* Server's OS: centos7
* Your Computer's OS & Browser: win 10, chrome

**Describe the bug**
If you have files in a rar file or zip file, open in winzip or winrar, ect. When you upload files from that program, it will say a general error, instead it should show an error stating you cannot upload files from zip or you cannot upload folder files. Something other than that general error.

**To Reproduce**
1. Go to File Manager
2. Try to upload files from inside winzip or winrar. Or folders
3. See the general error.

**Expected behavior**
it will say a general error, instead it should show an error stating you cannot upload files from zip or you cannot upload folder files. Something other than that general error.

**Comment by DaneEveritt** [comment]
I have no intention of changing how this is working. That is such an edge case scenario, and I'm not even sure that is something I can properly detect and avoid.
