### ISSUE TITLE
Password Decryption

### ISSUE THREAD

**Issue by hansputera** [pterodactyl/panel#2453]
We use GitHub issues only to discuss about Pterodactyl bugs and new features. For
this kind of questions about using Pterodactyl, please visit our Discord for assistance: https://pterodactyl.io/discord

DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

PLEASE stop spamming our tracker with "bugs" that are not related to this project.

How to decrypt the password in pterodactyl mysql database?

**Comment by DaneEveritt** [comment]
No.
