### ISSUE TITLE
Spam with an error message during 2FA authorization

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2455]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/e1e079bc1297cc3c2ae70abd2e14b51340332bc1 & https://github.com/pterodactyl/wings/commit/37e59e69286c2b570869acfe93e2cc4219147276
* Version of Panel/Daemon: 1.0 RC 7
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
![image](https://user-images.githubusercontent.com/28255085/95059965-4d1ce380-0702-11eb-9a60-a7264930ddf4.png)
Errors do not disappear when navigating through tabs:
![image](https://user-images.githubusercontent.com/28255085/95061099-d2ed5e80-0703-11eb-860e-e7e8918e05a2.png)

**To Reproduce**
1. Enter any code and press "enter" many times (or just hold it down)

**Comment by AreYouRlyScared** [comment]
I'm not able to reproduce this? Win10, Chrome

![jo9Ra5J](https://user-images.githubusercontent.com/1757840/95691968-435b1a80-0bf1-11eb-842a-4720d52a09ed.gif)


Must be a Safari thing

**Comment by wardpieters** [comment]
I was able to reproduce this bug on Safari (macOS) with version 1.0.1 of the panel.

**Comment by DaneEveritt** [comment]
I cannot reproduce this issue either.

**Comment by zKoz210** [comment]
I'll try to check it out now

**Comment by zKoz210** [comment]
still reproduce in Safari
![image](https://user-images.githubusercontent.com/28255085/96354202-a9a5d880-10dc-11eb-8bd7-5181cda15580.png)

**Comment by wardpieters** [comment]
I've made some changes to the code, this works for me on Safari and Chrome on macOS. Feedback on the PR is welcome 😄

**Comment by zKoz210** [comment]
disable 2FA
![image](https://user-images.githubusercontent.com/28255085/96354623-436f8480-10e1-11eb-97d4-4f183bbe6e50.png)

**Comment by wardpieters** [comment]
You did not describe this in your issue, but I will take a look at it.

**Comment by wardpieters** [comment]
@zKoz210 please take a look at the changes in https://github.com/pterodactyl/panel/pull/2545.
