### ISSUE TITLE
Gateway error...

### ISSUE THREAD

**Issue by SoNotMC** [pterodactyl/panel#2458]
When i do the command 
stop wings && cd /srv/daemon && npm start

It works but then 30 mins later it just says gateway error

![image](https://user-images.githubusercontent.com/43901997/95101593-3c806380-072a-11eb-9621-c25477a774c4.png)
![image](https://user-images.githubusercontent.com/43901997/95101633-473af880-072a-11eb-932f-ea664a75e7be.png)

**Comment by parkervcp** [comment]
If you are running this via command and close the terminal then is will also stop the daemon.

https://pterodactyl.io/daemon/0.6/installing.html#daemonizing-using-systemd

**Comment by SoNotMC** [comment]
Panel or Daemon: https://panel.texar.club/
Version of Panel/Daemon: newest as of 5th of oct
Server's OS: Ubuntu 18.04
Your Computer's OS & Browser: Chrome / Win 10

**Comment by SoNotMC** [comment]
Already there

![image](https://user-images.githubusercontent.com/43901997/95101886-9a14b000-072a-11eb-9be9-6168c8efccb6.png)

**Comment by victiondev** [comment]
npm start doesnt start start the service, do "systemctl enable --now wings"

**Comment by DaneEveritt** [comment]
This is unlikely an error with Pterodactyl specifically, rather an issue with your setup. Additionally the information provided does not lead me towards a reproducible example, or any ability to provide you a resolution.

Please use Discord for further assistance, this issue can be re-opened if we do indeed find there to be a bug with the software.
