### ISSUE TITLE
Use Laravel's config:cache for environment

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#246]
Avoids `Dotenv` calling `setenv()` on every request and making that `.env` file available to the requesting process each time. Improves speed as well as overall security.

This does require that `php artisan config:cache` be run each time that `.env` is modified, but we can slip that into `php artisan pterodactyl:env` to run at the end, and also document it elsewhere.

**Comment by schrej** [comment]
Do we actually only have to add `php artisan config:cache` into `php artisan pterodactyl:env` to be run when environment is production for this to work?

**Comment by DaneEveritt** [comment]
Something like that, I need to look into it a little more to get a better idea of when and where we should be running it.

**Comment by DaneEveritt** [comment]
e18391e and 6220f71 address this
