### ISSUE TITLE
user is stuck on connecting.

### ISSUE THREAD

**Issue by luckyywastaken** [pterodactyl/panel#2461]
* Panel or Daemon: I think its the deamon but not 100% sure 
* Version of Panel/Daemon: 1.0.0.0
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: microsoft edge, Windows 10 pro

**Describe the bug**

PHP 7.2.33-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug  7 2020 14:44:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.33-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

Linux devpanel 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
1. Go to 'this only happened to some users, they were trying to get onto any server but it is stuck on connecting. '
2. Click on 'the server'
3. Scroll down to 'console '

**Expected behavior**
You should be able to easily access the panel like so:

<img width="1440" alt="Screen Shot 2020-10-06 at 1 32 36 PM" src="https://user-images.githubusercontent.com/64851720/95239040-67c18c00-07d8-11eb-9d8a-db97bb247911.png">

But this user was experiencing this: (he was not on any VPNS, I tried restarting wings.)

![image](https://user-images.githubusercontent.com/64851720/95239141-87f14b00-07d8-11eb-9f61-8402c39fdac7.png)

**Comment by iqfx** [comment]
This is happening to me on the 0.7 version of the panel as well, I just refresh the page 2 times and it magically works like normal again. Not sure if that is the same happening here.

**Comment by schrej** [comment]
This doesn't seem like a bug, but rather a configuration error. Likely firewall related, maybe DNS. Regardless, this should probably be discussed on our discord at https://discord.gg/pterodactyl.
