### ISSUE TITLE
Rename CPU Threads to CPU Pinning

### ISSUE THREAD

**Issue by schrej** [pterodactyl/panel#2462]
The name "CPU Threads" has lead to confusion twice today, and it actually is confusing. It sounds like it's the amount of CPU threads the server can use, not which specific (multi threaded) cores the server will use.

I suggest renaming it to "CPU Pinning", as that's more correct, and less likely to fall victim to "oh, I don't really know what I'm doing but my server needs all the performance it can get". While we're at it, we should probably make the "advanced" warning more prominent.

**Comment by occanowey** [comment]
Maybe "CPU Quota" [same as docker](https://docs.docker.com/config/containers/resource_constraints/#cpu).

**Comment by AreYouRlyScared** [comment]
I mean. I see no issues with it called threads.... as if you have a dual core cpu  and its multi threaded.... you have 4 threads. So 0 through 3... not sure how it sounds like that amount of the thread it can use.......?

As for the fall victim part. Thats 100% their fault for changing values that they have no idea what they do. 

I'd suggest just changing the wording of the description to not say `CPU cores` but `CPU threads`.

**Comment by schrej** [comment]
The name is misleading though. And linux doesn't call them threads either, but just CPUs. We can include that in the description maybe.
The correct name is Processor Affinity or CPU Pinning: https://en.wikipedia.org/wiki/Processor_affinity

**Comment by AreYouRlyScared** [comment]
Okay. We can change it.

**Comment by mayersgamer** [comment]
i dont get it tho , cpu pinn lets use decide with cores to use or which threads ? if i have 2 cores and 4 threads and only allocation 50% of a single core for the server , what shoud l i pit in cpu pinnig ?
