### ISSUE TITLE
Add back the Select all perms button for subusers

### ISSUE THREAD

**Issue by luckyywastaken** [pterodactyl/panel#2464]
**Is your feature request related to a problem? Please describe.**
When you want to ad a sub user quickly yea you can select all the sections but it would be nice to have the feature from the 0.0.7 versions where you could select all the perms at once then remove some you some you do not want

**Describe the solution you'd like**
Add back the "select all button/select none buttons" for sub users 

**Describe alternatives you've considered**
You can add a select all and select none buttons back to the panel!

**Additional context**

Old:
<img width="1259" alt="Screen Shot 2020-10-06 at 4 25 16 PM" src="https://user-images.githubusercontent.com/64851720/95256319-a7946d80-07f0-11eb-9458-5433312fd52e.png">

Where it could go on the new one:
<img width="634" alt="Screen Shot 2020-10-06 at 4 27 03 PM" src="https://user-images.githubusercontent.com/64851720/95256506-e9251880-07f0-11eb-967b-f68735246f1b.png">

**Comment by schrej** [comment]
There's now the "select all" boxes in the top right, are they not sufficient?
They might be better placed on the right side though.

**Comment by luckyywastaken** [comment]
I dont see them?

**Comment by DaneEveritt** [comment]
Duplicate #2383
