### ISSUE TITLE
Make the subuser should be an existing user

### ISSUE THREAD

**Issue by outtimes** [pterodactyl/panel#2467]
**Describe the solution you'd like**
To have a option for control if invite the user as a subuser should be an existing user.

**Comment by RealTriassic** [comment]
This is confusing

**Comment by Doc94** [comment]
Why is this necesary?
In teory only users with the owner of server (or subusers with the perm) can add new subusers.

**Comment by DaneEveritt** [comment]
I don't really understand what this is asking. Subusers already have an account created if one does not exist, otherwise it just links to the matching account in the database.
