### ISSUE TITLE
shows Welcome to nginx!

### ISSUE THREAD

**Issue by joshilita** [pterodactyl/panel#2468]
I might be missing something but I get 

Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.

I was trying to get the panel

**Comment by fabm3n** [comment]
Visit our Discord for help and close this issue. Thanks.

**Comment by Hydra2k** [comment]
delete the default file in sites-available and sites-enabled and then restart nginx

**Comment by joshilita** [comment]
> delete the default file in sites-available and sites-enabled and then restart nginx

I am sorry I have no idea how to do it im a noob at linux

**Comment by parkervcp** [comment]
This is an nginx config issue and not a panel issue.
