### ISSUE TITLE
git doesn't works within builtin images

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#247]
I'm using my own images derived from yours (https://github.com/Pterodactyl/Docker-SRCDS). 
Trying to clone a git repo within the startscript doesn't works (ofc i added git as dependencies within the dockerfile). 

i.e: git clone https://<login>:<passwd>@giturl.com/namespace/projet.git /tmp/project
```bash
fatal: unable to look up current user in the passwd file: no such user
```

Then i triied to login into the container to manualy check what's wrong, maybe a start ...
```bash
$ id
uid=15015 gid=0(root) groups=0(root)

$ whoami
whoami: cannot find name for user ID 15015

$ cat /etc/passwd | grep container
container:x:1000:1000::/home/container:

```

**Comment by DaneEveritt** [comment]
Processes in the container are run as a non-existant user for a reason, as it is also a limitation of docker. This is not a bug with the daemon or panel as it is exactly how we designed the system to work. If you need something like that to have a specific user attached to it, you'll need to wait until `0.6.0` is out and allows pre-install building of packs.
