### ISSUE TITLE
Schedules bug | Pterodactyl 1.0.0 - rc. 7

### ISSUE THREAD

**Issue by Nexusatko** [pterodactyl/panel#2470]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-rc.7
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 | Google Chrome

**Describe the bug**
When I try to make automatic backups with schedules, those schedules won't run at the time what I was given.

**To Reproduce**
Steps to reproduce the behaviour:
1. Delete the schedule
2. Restart Server where is Pterodactyl running
3. Re-create schedule
4. Still the same error.

**Expected behaviour**
I need those automatic backups, and that's the reason why I'm on this new version of Panel. I'm planning automatic backups by schedules every 6 hours.

**Comment by DaneEveritt** [comment]
What do you mean by they don't run. Are they running at a different time, or not at all? If they don't run at all, is there anything in the `failed_jobs` table?

**Comment by Nexusatko** [comment]
I don't know, what you know.
But they won't run at all. Also "Last run at : never".
![image](https://user-images.githubusercontent.com/59520956/95455190-c66c3e80-096d-11eb-8206-156c57b08e6b.png)
![image](https://user-images.githubusercontent.com/59520956/95455244-dab03b80-096d-11eb-9b10-45bf89434e69.png)

**Comment by DaneEveritt** [comment]
Your queue worker probably isn't running. If it is, make sure you restart it and see what happens.
