### ISSUE TITLE
Server owner search bar doesn't find user/hardly finds user

### ISSUE THREAD

**Issue by dhalucario** [pterodactyl/panel#2472]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon:  1.0.0-rc.7
* Server's OS: CentOS Linux 8 (Core)
* Your Computer's OS & Browser: Fedora 32 (Workstation Edition) | Firefox 80.0.1 (64-bit)

**Describe the bug**
When creating a new server the field Core Details > Server Owner does not give good enough search responses.
My name is Leon Grünewald and the username is dhalucario. When searching for dhalucario or just leon the search doesn't spit anything out. I have to use Grünewald to find anything.

**To Reproduce**
1. Go to Create Server
2. Click on the search bar for Core Details > Server Owner 
3. Enter my username (in this case dhalucario or leon)
4. No results are shown

**Expected behavior**
I expect it include usernames and "pretty names" in the search instead of just my surname or the e-mail. I didn't have this bug in previous versions of Pterodactyl.

**Comment by DaneEveritt** [comment]
Duplicate https://github.com/pterodactyl/panel/issues/2366
