### ISSUE TITLE
http error 500 when going to any settings in the admin settings page "top right"

### ISSUE THREAD

**Issue by thewickening** [pterodactyl/panel#2477]
Panel
latest 1.0  
Ubuntu 18.04
Windows 10 & Chrome

**Describe the bug**
As soon as I go to the admin page "top right" and click on settings or anything in there, databases etc, it goes to an error 500 page.
I also rebooted the entire box etc.
This seemed to have happened after the latest 1.0 update.

Panel: `php -v` (the php version in use). 7.4.11
Daemon: Linux ns531230 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk s                                                                                                                                                             yslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-118-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.57GiB
 Name: ns531230
 ID: SZVR:463O:MTQY:P64F:GGU6:3E3B:IL2A:AGNQ:TDQP:CRLY:7EC6:E2PT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**To Reproduce**
1. Go to 'admin page top right'
2. Click on 'any of the selections on the left side'
3. Scroll down to 'N/A'
4. See error "http error 500"

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

Should be able to click the settings in the admin panel.

**Comment by DaneEveritt** [comment]
Please provide actual panel errors logs and I will re-open this issue. The information provided here is not enough for anyone to be able to help you.
