### ISSUE TITLE
Ability to disable user accounts.

### ISSUE THREAD

**Issue by Ender38-cmd** [pterodactyl/panel#2478]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be nice if you could disable an account. what would happen is an admin would disable a users account,
the user gets an email saying "Your account for (name) has been disabled" (also would be nice if admins could
give a reason why the account was disabled) and after 14 days the user gets deleted unless the user gets re-enabled.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by DaneEveritt** [comment]
This is better handled by your billing software.
