### ISSUE TITLE
New language

### ISSUE THREAD

**Issue by Limerio** [pterodactyl/panel#2479]
Hello ^_^
I have create a new folder to add a new languages who is the french and after by others person add a other language to reach a maximum number of people and for ease of use this panel. For me it's a important chose but that may not be your opinion.

I have a idea to choose the language of the panel in .env enter in 
`LANGUAGE_PANEL = "en" // or fr or others languages`
And in https://github.com/pterodactyl/panel/blob/develop/resources/scripts/i18n.ts make process.env.LANGUAGE_PANEL in property lng
 
*If would you the folder contact me* :)

**Comment by DaneEveritt** [comment]
We do not currently support multiple languages at this time in 1.0. If that changes down the road there will be more information on how to contribute.
