### ISSUE TITLE
Breadcumbs do not update correctly when going forward.

### ISSUE THREAD

**Issue by JackCrispy** [pterodactyl/panel#2485]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0 
* Server's OS: Centos7
* Your Computer's OS & Browser: Chrome, win10 

**Describe the bug**
Breadcrumbs does not correctly display the directory when editing a file or inside a folder.

**To Reproduce**
1. Go to file manager
2. Go to the root cotainer
3. Open 3 folders e.g /home/container/folder1/folder2/file1
4. Open the file1 file.
5 Look at the breadcumbs and click folder1
6. Click the back arrow to go back to file1
7. See how folder2 is missing but it says folder1/file1

**Expected behavior**
It will say the folder2 name and not skip it.

**Comment by luckyywastaken** [comment]
Could you please show some pictures?

**Comment by JackCrispy** [comment]
Ok. Examples:

1. Go to a dir like this https://i.crisp.codes/f3db6c.png

2. Go to plugins dir https://i.crisp.codes/32ff62.png

3. Should look like this https://i.crisp.codes/5bef44.png

4. Then click the back button, either the one on the top left of screen or the mouse back button.
 Then it should look like this https://i.crisp.codes/6258da.png

There is no config.yml in my plugins folder. It is not displaying the CleanMoTD folder.
