### ISSUE TITLE
WebSocket issue

### ISSUE THREAD

**Issue by runescapejon** [pterodactyl/panel#2486]
**Background (please complete the following information):**
I was upgrading between 0.7 to 1.0 following the guide. Until the issue that I can come up. It's all coming from connection issues from something. Base on my research the Laravel log is spamming with error's that are coming from curl. I am unsure. I don't know what to do in terms of fixing this. I tried changing the node port and copy/paste config then reboot wings. Didn't work. Also, tried changing the URL that didn't work. I'm on OVH so the firewall is pretty much not a problem I even check to see what was wrong with it but it seems that the firewall was off the whole time so that wasn't an issue. I am on Cloudflare but it wasn't an issue before on panel 0.7. That I even tried switching between Behind Proxy and not Behind Proxy nothing had work. and I don't understand where I am doing wrong when I am updating from 7 to 1.0 Any idea?

Laravel Log: https://hastebin.com/cuharosoku.less - Contain errors this stacktrace  
Wings Diagnostics: https://ptero.co/canimupiho - doesn't seem to be a wings issue
Browser console: https://gyazo.com/fd3b3a13f8a997679fea5744062298c2 - Contains 504 error

* Panel or Daemon: 1.0
* Version of Panel/Daemon: 1.0
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: Windows 10 and Google Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use). PHP 7.4.10
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
Linux ns508205 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
https://pastebin.com/raw/8yXqKmpP
**To Reproduce**

Sadly I don't know how to reproduce. I as was simply following the guide once I was finish with both Upgrading panel and Wings 1.0 from Migrating to 0.7 the error regarding about Webshocket came up.
**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
Unable to see the console output or interact with it *(image above)*

**Comment by SmallEngineMechanic** [comment]
We are having the same issue on a Debian 10 system 
Linux pterodactyl-debian 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
getting 500s on the websocket

```
ERROR: [Oct 12 00:47:54.326] encountered HTTP/500 error while handling request error=websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header error_id=c

Stacktrace:
github.com/apex/log.(*Entry).Error
        /home/runner/go/pkg/mod/github.com/apex/log@v1.8.0/entry.go:96
github.com/pterodactyl/wings/router.(*RequestError).AbortWithStatus
        /home/runner/work/wings/wings/router/error.go:76
github.com/pterodactyl/wings/router.(*RequestError).AbortWithServerError
        /home/runner/work/wings/wings/router/error.go:97
github.com/pterodactyl/wings/router.getServerWebsocket
        /home/runner/work/wings/wings/router/router_server_ws.go:17
github.com/gin-gonic/gin.(*Context).Next
        /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
```

**Comment by parkervcp** [comment]
have you logged out and back in on the panel yet?

**Comment by SmallEngineMechanic** [comment]
yes

**Comment by SmallEngineMechanic** [comment]
![5997972e12.png](https://user-images.githubusercontent.com/36752402/95764850-0178b580-0c7f-11eb-8548-3ab3ce920cdb.png)![891d80ca56.png](https://user-images.githubusercontent.com/36752402/95764857-03427900-0c7f-11eb-82d6-765dd793ef07.png)

**Comment by SmallEngineMechanic** [comment]
those go with the daemon debug error

**Comment by runescapejon** [comment]
Yes, I have tried to log out and log in back in. I even tried using google incognito

**Comment by runescapejon** [comment]
It appears that Wings was bugging out, even if I was to `systemctl stop wings` that the port was still open in somewhat. I'd run the command to kill this process 
```
sudo kill -9 `sudo lsof -t -i:8080`
```
and then 
```
systemctl start wings
```
My panel is now working. I don't know what happen that made WebSocket bug out. Feel free to close this issue, or to leave it open for a possible bug in Websocket.

**Comment by SmallEngineMechanic** [comment]
didn't fix it for me

**Comment by DaneEveritt** [comment]
@SmallEngineMechanic your issue is completely unrelated to this. You likely have a firewall or service running that is stripping required headers out of the request, note the:

> the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

That is completely different than what this issue is about.

**Comment by SmallEngineMechanic** [comment]
I fixed it

**Comment by Lele991** [comment]
> I fixed it

how you fixed it?

**Comment by chrispro-21** [comment]
> I fixed it

please tell us on how

**Comment by FurJorden** [comment]
in my case the problem was with nginx proxy, you mus in the wings domain enable the "Websockets Support"
![image](https://user-images.githubusercontent.com/70817878/127712551-bbfdf86e-5454-4c78-b58e-4aca6f0c3db7.png)

**Comment by kshchukin** [comment]
Hello
Have a similar problem with panel
Although, wss in nginx is enabled but with empty proxy_pass
![Снимок экрана 2022-12-11 в 20 16 48](https://user-images.githubusercontent.com/94689075/206918439-fb5386e3-e391-4323-9b64-cafc44655600.png)
![Снимок экрана 2022-12-11 в 20 17 01](https://user-images.githubusercontent.com/94689075/206918450-15fc8d60-4c8b-4e33-9033-697bd47cf1c5.png)
Where is my mistake?

**Comment by arturgoms** [comment]
@FurJorden ty a lot bro, you solved my problem
