### ISSUE TITLE
php artisan p:user:delete not working

### ISSUE THREAD

**Issue by stijnb1234** [pterodactyl/panel#2487]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10, Brave (Chromium based)

**Describe the bug**
`php artisan p:user:delete` will always return "No users were found for the search term provided.", even if the user does exists.

**To Reproduce**
1. Go to the panel folder (/var/www/pterodactyl)
2. Run `php artisan p:user:delete`
3. Typ the username or email from a user
4. It will return the "No users were found for the search term provided." message.

**Expected behavior**
It should give the user(s), and the ability to remove it.

**Comment by AreYouRlyScared** [comment]
```
root@node2 /var/www/pterodactyl # php artisan p:user:delete

 Enter a Username, UUID, or Email Address:
 > test

+---------+---------------+-----------+
| User ID | Email         | Name      |
+---------+---------------+-----------+
| 18      | test@test.com | test test |
+---------+---------------+-----------+

 ID of user to delete (Enter '0' to re-search):
 > 18

 Are you sure you want to delete this user from the Panel? (yes/no) [no]:
 > yes

User successfully deleted from the Panel.
root@node2 /var/www/pterodactyl #

```

Worked for me?

**Comment by stijnb1234** [comment]
If I try to create the user:
```
 Data integrity exception encountered while performing database write operat
  ion. {"email":["The email has already been taken."],"username":["The userna
  me has already been taken."]}
```

And if I try to delete the same user:
```
No users were found for the search term provided.
```

**Comment by AreYouRlyScared** [comment]
Ahh, I see now. It's very very picky...
