### ISSUE TITLE
no jwt present

### ISSUE THREAD

**Issue by vFinn9** [pterodactyl/panel#2488]
**Background**
* Panel or Daemon:  Daemon/Wings
* Version of Daemon: 1.0
* Server's OS:  Debian 10
* Your Computer's OS & Browser: Windows 10 1909, Google Chrome

**Describe the bug**
We've successfully upgraded to Pterodactyl 1.0 and Wings. After around 6 hours of it running perfectly fine, it stopped working for every node, but one.

We're now greeted with a nice little "There was an error validating the credentials provided for the websocket. Please refresh the page.".
Checking devtools, I see those requests to the websocket:
{"event":"auth","args":["eyCENSOREDTHISONPURPOSE"]}

Which then responds with:
{"event":"jwt error","args":["jwt: no jwt present"]}

Console:
bundle.a6dd5e07.js:1 JWT validation error from wings: jwt: no jwt present
(anonymous) @ bundle.a6dd5e07.js:1
c.emit @ bundle.a6dd5e07.js:1
onmessage @ bundle.a6dd5e07.js:1

At the same time, this works fine for another wings node, which runs on the same specs & OS:
{"event":"auth success"}

Pretty much everything except for reboot operations & console works fine.

uname -a: Linux 104.143.2.99 5.4.0-0.bpo.2-amd64 #1 SMP Debian 5.4.8-1~bpo10+1 (2020-01-07) x86_64 GNU/Linux
docker info: https://pastebin.com/WUw1Kf09

**Expected behavior**
Authentication should pass.

**Comment by vFinn9** [comment]
Edit: This was seemingly an issue with SYNProxy conflicting with the actual panel. Resolved.

**Comment by kubo6472** [comment]
How did you fix it if I may ask? I am facing the same error but do not notice any synproxy of some sort. Thanks
