### ISSUE TITLE
Command history don't work on 1.0

### ISSUE THREAD

**Issue by xion87** [pterodactyl/panel#2491]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon:  1 .0
* Server's OS: Ubuntu 18
* Your Computer's OS & Browser:  Chrome

**Describe the bug**
Pressing "up" key don't show anymore the old comand used on console

**To Reproduce**
1. Go to console
2. write some comand and execute
3. press up
4. the old comand is not showed

**Expected behavior**
It should be showed

**Comment by yashendra2797** [comment]
Can confirm. using v1.0 panel, and wings.

**Comment by matthewpi** [comment]
This is behavior that just hasn't been implemented in 1.0 yet.
