### ISSUE TITLE
Translations not showing up

### ISSUE THREAD

**Issue by PiggyChain** [pterodactyl/panel#2492]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v1.0.0
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Ubuntu 18.04, Chromium
* PHP Version: 7.4.3

**Describe the bug**
The translations, that you can define don't work, because they aren't implemented. If you look for example in `resources/scripts/components/dashboard/forms/UpdatePasswordForm.tsx` you kann see at the bottom that the text "Update Password" is hard coded in, even though in the languages (base.php, account --> update_pass) it can be translated.

**To Reproduce**
1. Go to the admin page of your account and set the language to e.g. german
2. Click on go to the user page of your account
3. See the issue, "Update Password" doens't get translated, reason explained above.

**Expected behavior**
It should be translated to the selected language. To see that the translations work on other places, click on e.g. "Update User" on your admin account page, the text in the green box is translated.

**Comment by xion87** [comment]
I confirm, thanlations are not working

**Comment by matthewpi** [comment]
Translations are not implemented in 1.0 yet, this isn't a bug.
