### ISSUE TITLE
Add back the server sidebar on 1.0

### ISSUE THREAD

**Issue by xion87** [pterodactyl/panel#2494]
**Is your feature request related to a problem? Please describe.**
I miss the quick sidebar with all server

**Describe the solution you'd like**
Add back the server sidebar for quick switch, i used it a lot of time on old ptero

**Comment by LeCodeCo** [comment]
There's a search button which you can use to easily search for servers.

**Comment by parkervcp** [comment]
The side bar has been moved to the top. It's still easy to switch.

**Comment by xion87** [comment]
> The side bar has been moved to the top. It's still easy to switch.

You mean the search bar?

**Comment by parkervcp** [comment]
Can you post a screenshot of what you are looking for here. Because I don't think you are getting the point across.

**Comment by xion87** [comment]
![image](https://user-images.githubusercontent.com/3611852/95769053-8aabde80-0cb7-11eb-84b9-0d55c50f79a9.png)

**Comment by parkervcp** [comment]
I mean the old bar you are looking for.

If you are just looking to get back to the server list click the host name.

**Comment by xion87** [comment]
i dont have the olde ptero right now, it was enter in any server console, there was a button on right-top that open a right sidebar will all server installed/owned

**Comment by parkervcp** [comment]
I have a 0.7 install still and there is no button to change to other servers. You need to go back to the main server list and select the other server.

**Comment by xion87** [comment]
here click the arrow  and see the magic
![image](https://user-images.githubusercontent.com/3611852/95770022-0e19ff80-0cb9-11eb-84dc-75ad998f303f.png)

**Comment by DaneEveritt** [comment]
I won't be adding that back, sorry.

**Comment by parkervcp** [comment]
I didn't even know that existed.
