### ISSUE TITLE
Configuration ability for 'Crash Detection'.

### ISSUE THREAD

**Issue by DJTerrum** [pterodactyl/panel#2495]
**Is your feature request related to a problem? Please describe.**
When the 'Crash Detection' restarts the server, it has a timer that will stop the server from restarting if the server crashes again within that timer.

The problem with this for me is that I run game servers that are not heavily in development (HLDS/SRCDS) and not easy to fix errors/bugs without waiting for Valve to release an update for their servers in years to come.

As my intention to use Pterodactyl is to allow the servers to run with very little human interaction, it is important that Pterodactyl keeps these servers online for me regardless of the crash count.

**Describe the solution you'd like**
I think it would be really useful if the 'Crash Detection' feature can possess an ability to either enable/disable the timer for the second crash, so that it will just continuously try to restart no matter how many times it has crashed, or have a settable time for how many times it should attempt to restart and/or settable timer.

**Describe alternatives you've considered**
I have considered using server-side plugins (on the games themselves) to solve the errors/bugs within the game server, and tried reporting the issues to the developer of the game servers, but unfortunately as mentioned above updates are very rare from the developers.

**Additional context**
I believe this feature would be useful for more than just my purpose, adding configurable variables for more of Pterodactyl's features will make it far more advanced and versatile, even in comparison to some other game server panels out there :)

**Comment by DaneEveritt** [comment]
I'm pretty sure you can disable crash detection globally for Wings. But perhaps it is per-server which is kinda pointless currently since there is no toggle.

**Comment by DJTerrum** [comment]
I am aware that you can globally disable crash detection on Daemon (not sure if it can be done on Wings as I've only started using 1.0 today). However the issue is not related to enabling/disabling the crash detection itself, but the feature within the crash detection that stops restarting the server after the second crash.

**Comment by DaneEveritt** [comment]
Yes, I understand. It all ties together though and doesn't make sense to only do part of the fix. It should all be easily configurable via the Panel & node config.

**Comment by DJTerrum** [comment]
I agree. I think this sort of thing ('easily configurable via the Panel & node config') should be applied to many other features of Pterodactyl as well, unrelated to the 'Crash Detection'. Such as giving users better ability to re-install servers themselves and/or pick different game versions (e.g: for example, change Minecraft server version from Vanilla to Paper), but of course it's unrelated to this request so I will make new feature requests related to such at a later date :)

**Comment by Prophet731** [comment]
I would also really like to see this feature. Right now when crashes happen it doesn't give enough time or attempts for the "service" to recover right for what I am running. I would also like to see an option to set the restart policy on the docker container itself somehow. I don't know how this would be done in the 1.x update.

**Comment by trenutoo** [comment]
This is currently possible in 1.x Wings by modifying the timeout value.  Setting it to 0 would allow infinite crash restart loops.

Perhaps another value could be added to specify the number of restart attempts within the timeout period.

**Comment by DJTerrum** [comment]
> This is currently possible in 1.x Wings by modifying the timeout value. Setting it to 0 would allow infinite crash restart loops.
> 
> Perhaps another value could be added to specify the number of restart attempts within the timeout period.

Yes this feature was added in the new (non-NodeJS) Wings. Therefore I will close this issue.
