### ISSUE TITLE
config parser for "plain text" broken

### ISSUE THREAD

**Issue by kubo6472** [pterodactyl/panel#2496]
**Background:**
* Panel or Daemon: panel I think
* Version of Panel/Daemon: 1.0/1.0
* Server's OS: Debian 10
* Your Computer's OS & Browser: W10Pro/Firefox

**Describe the bug**
The JMusicbot egg uses config.txt (plain text file). On start the values from "startup" tab in server admin are pseudorandomly inserted into the file, breaking the bot.

**To Reproduce**
Start the "server"

**Expected behavior**
The server would start and the bot would work.

**Actual behavior**
Config file is a mess and bot errors out.

**Comment by DaneEveritt** [comment]
Please include the actual egg export file in this issue so I can properly reproduce the issue.

**Comment by kubo6472** [comment]
You mean this? https://github.com/parkervcp/eggs/tree/master/bots/discord/jmusicbot

**Comment by parkervcp** [comment]
This is working for me as is right now in my quick "I just set up a server" testing.

**Comment by kubo6472** [comment]
I managed to fix the issue I was having and that by removing the config file, and re-setting up the bot. The config still got messed up, on the first edit I needed to make, but luckily it kept the double slash in the line beginning and that was enough to keep the bot running.

**Comment by gewonegebruiker** [comment]
i had the same problem.
foud a temporaly fix by deleting this part: 
![image](https://user-images.githubusercontent.com/38141182/95784040-58a87580-0cd3-11eb-9de0-f7ac12db1c5f.png)

just updated to the 1.0 release of wings and the problem is fixed.
so i would suggest try updating

**Comment by kubo6472** [comment]
I updated, thought I was on the 1.0, but apperently, I was on some other 1.0. I did not delete anything, but confirmed, the "latest 1.0.0" fixes this problem. closing.
