### ISSUE TITLE
Turning down the server an retry to power it up it trow error

### ISSUE THREAD

**Issue by xion87** [pterodactyl/panel#2498]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon:  Both?
* Version of Panel/Daemon: 1.0 
* Server's OS:  Ubuntu
* Your Computer's OS & Browser:  windows 10 chrome

**Describe the bug**
When you shutdown a server and try to power up or restart and the error  it show on console "Error Event [ddc73816-5bbe-4714-945d-36b8486824b6]: unable to sync server data from Panel instance: Error response from Panel: :  (HTTP/403)" and this error on wings: https://gist.github.com/xion87/de56c5c8afeb9603f1d3e5ca4a939fb8

**To Reproduce**
1. Shutdown a server
2. try to power it on
3. You will have  Error Event [ddc73816-5bbe-4714-945d-36b8486824b6]: unable to sync server data from Panel instance: Error response from Panel: :  (HTTP/403)

**Expected behavior**
The server should start

**Comment by DaneEveritt** [comment]
You're getting a 403, which means the authentication details being sent to the Panel are incorrect. This is not a bug.

**Comment by xion87** [comment]
sure that is the issue? the console/file manager and all other stuff are working

**Comment by DaneEveritt** [comment]
Well, either way with the information provided I cannot reproduce this, and I've not seen anyone else having this issue, so theres not much I can really do.

**Comment by xion87** [comment]
i solved after i:
- purged cloudflare cache (it seem to be the cause)
- setted new master key
- regenerated certificate,

and voilà wings work again
