### ISSUE TITLE
Console Page Is Blank

### ISSUE THREAD

**Issue by linusstretchtips** [pterodactyl/panel#2499]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon:  Panel
* Version of Panel/Daemon: 1.0.0 / v1.0.0 
* Server's OS: 
* Your Computer's OS & Browser: Ubuntu 18.04
* Logs: http://bin.ptdl.co/8xn9l 

**Describe the bug**
Please provide additional information too, depending on what you have issues with:

After Updating from RC 7  to Main Release (1.0.0) Console page Of the servers stopped working but every other page works

Panel: 
PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies

Wings: v1.0.0

**Expected behavior**
A Page where Console is visible and can be used With the start and stop etc buttons
![image](https://user-images.githubusercontent.com/64327566/95779033-360d6100-0cc1-11eb-9c4f-3ecafec9bdb1.png)

**Comment by DaneEveritt** [comment]
Please provide a more clear description of what your issue is. Telling me the page doesn't work and including a random screenshot does not make it likely that this issue will be a.) resolved and b.) fixed.

**Comment by grzegorzkibitz** [comment]
im going to close this issue as we found a fix.

**Comment by DaneEveritt** [comment]
@linusstretchtips good to hear, mind expanding on the fix so that down the road people finding this issue aren't left in the dark as to how they can resolve it?
