### ISSUE TITLE
Add support for port forwarding through the Panel.

### ISSUE THREAD

**Issue by iaxedu** [Pterodactyl/Panel#25]
Hello,

Could you look into adding a method to add port forwarding through the Panel instead of the current method?

**Comment by DaneEveritt** [comment]
Im not entirely sure what you mean by that, what is the current method you are speaking of?

We allow you to assign multiple IPs and Ports to a single server which are are open on that container so any service you are running on that single server can use those ports. The panel doesn't necessarily track if they are actually being used (other than which one is set for the main connection address) but it does track which ones *could* be used.
