### ISSUE TITLE
updates to symfony break the install

### ISSUE THREAD

**Issue by parkervcp** [Pterodactyl/Panel#250]
![image](https://cloud.githubusercontent.com/assets/1207679/21919537/15170f02-d929-11e6-8cfc-699dac5e6a85.png)

Left: old  
Right: new

symphony version changed recently and now `composer install --ansi --no-dev` installs the latest one

**Comment by schrej** [comment]
Doesn't composer have a Lockfile for those kinds of issues? I'm not sure when it's used and when it isn't though

**Comment by schrej** [comment]
Composers `composer.lock` file keeps track of the currently installed dependencies. When you run `composer install` the versions from the lock file will be used. Only `composer update` will use the ones from `composer.json` then.
We should commit the lock file to git for that to work.

**Comment by DaneEveritt** [comment]
Composer install also uses composer.json

**Comment by schrej** [comment]
Yes but if there is a `composer.lock` file it will use that instead. 
https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file

**Comment by parkervcp** [comment]
I am stupid and it is all my fault.

While working on a new setup for the containers I was accidentally replacing a folder with a docker volume.
