### ISSUE TITLE
How do I run multiple things in 1 container?

### ISSUE THREAD

**Issue by MegamiSoftware** [pterodactyl/panel#2500]
Hi, I need to run 2 things in 1 container, But I have no idea how. I need to run a bot and a game server, someone told me this is possible with entrypoint.sh but I have no idea what that is or how to use it for this.
Can someone help?
Thanks alot!
-Megami

**Comment by DaneEveritt** [comment]
Please use Discord for help with things like this, the issue tracker is for bugs and feature requests, not general questions. Thanks.
