### ISSUE TITLE
Wings Diagnostics upload not working

### ISSUE THREAD

**Issue by fabm3n** [pterodactyl/panel#2501]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.0 Stable
* Server's OS: Ubuntu 20.04

**Describe the bug**
The wings diagnostics command is not able to post the diagnostics to ptero.co. 
Afaik there is only a Server under bin.ptdl.co on port 99 for the nc command.

Error Message:
Failed to upload report to  https://ptero.co/documents Post "https://ptero.co/documents": dial tcp 95.216.28.149:443: connect: connection refused

**To Reproduce**
1. Run wings diagnostic
2. with upload to "hastebin.com" (forgotten to rename?)
3. See error

**Expected behavior**
diagnotics should be uploaded to bin.ptdl.co

**Comment by DaneEveritt** [comment]
The site is down, explaining the error. It isn't a bug with this software and will be resolved when it comes back online.
