### ISSUE TITLE
ARM support for Wings

### ISSUE THREAD

**Issue by wardpieters** [pterodactyl/panel#2504]
**Is your feature request related to a problem? Please describe.**
Currently there is only a AMD64 binary available of the new Wings daemon (version 1.0). However, the daemon works great on a ARM device, e.g. a Raspberry Pi 4.

The only thing I had to change in the source code before compiling was [line 12 of stat_linux.go](https://github.com/pterodactyl/wings/blob/develop/server/filesystem/stat_linux.go#L12).

I've changed it into `return time.Unix(int64(st.Ctim.Sec), int64(st.Ctim.Nsec))`. I'm inexperienced in Go, so I don't know if that's the best fix.

**Describe the solution you'd like**
A ARM binary of the Wings daemon.

**Describe alternatives you've considered**
Compiling Wings myself (not a great alternative since I have to recompile it every time there is an update available of the daemon).

**Additional context**
I created this issue after a short chat with @DaneEveritt via Discord.

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/wings/commit/19051c99efcf739d824edc1a037e03df50c79504

**Comment by wardpieters** [comment]
@DaneEveritt, thanks for your response on this issue. I really appreciate your work.

Maybe I wasn't specific enough, but what I meant was a ARM binary, not ARM64.

**Comment by DaneEveritt** [comment]
@matthewpi see above

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/wings/runs/1269522782 has the first `arm` builds
