### ISSUE TITLE
Files inside backup contain all starting slash "\"

### ISSUE THREAD

**Issue by Malachiel87** [pterodactyl/panel#2505]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.1 
* Server's OS: Ubuntu 18
* Your Computer's OS & Browser: Chrome Windows 

**Describe the bug**
When you create a backup file, i noticed all files and folder are starting with "\"
![image](https://user-images.githubusercontent.com/3611852/95852838-bdf07b00-0d54-11eb-8de0-a79e497e5a60.png)

**To Reproduce**
1. Create a backup
2. Open it
3. See all files starting with \

**Expected behavior**
Files and folder inside it should don't have "\"

**Comment by tinyoverflow** [comment]
What zip-program are you using?
I cannot reproduce this, when opening the zip files on a Windows 10 machine with 7zip 20.00 alpha.

**Comment by Rhydium** [comment]
Have been able to reproduce this on Ubuntu 18.04 LTS, Panel@1.0.1, Wings@1.0.0 and using WinRAR.
The \ only appears on files and folders in the "root" folder of the backup.

**Comment by notAreYouScared** [comment]
Also, The files aren't named like that if you extract them or open them the slash doesn't exist. 70% sure it's a winrar thing.

**Comment by Malachiel87** [comment]
try to untar on your linux macchine, it will show a warning about these slash and remove it automatic

**Comment by Rhydium** [comment]
Yeah, this is a WinRAR thing. I just used 7zip and the \ is gone.
\ only appears with WinRAR..

**Comment by notAreYouScared** [comment]
I wouldn't consider it an issue with the panel then.

**Comment by Malachiel87** [comment]
Try to untar it will show this
![image](https://user-images.githubusercontent.com/3611852/95855389-9ef3e800-0d58-11eb-9744-9fc61d978440.png)

**Comment by DaneEveritt** [comment]
This is not a bug with Pterodactyl. Every sane unarchive tool handles this just fine.
