### ISSUE TITLE
Scroll Bar shows on small tables

### ISSUE THREAD

**Issue by DamonOnYT** [pterodactyl/panel#2506]
**Background (please complete the following information):**
* Panel or Daemon: v1.0.1
* Version of Panel/Daemon: N/a
* Server's OS: Ubuntu 18.04 LTS
* Your Computer's OS & Browser: Windows 10, Brave Browser

**Describe the bug**
The scroll bar shows on a small table such as the Databases List with 1 server or Locations with 2 locations

**To Reproduce**
1. Head to panel.url/admin/locations OR panel.url/admin/databases
2. Observe scroll bar
![http://ben.has-raped.me/ENRNk0b.png](http://ben.has-raped.me/ENRNk0b.png)
![http://ben.has-raped.me/sZzQANu.png](http://ben.has-raped.me/sZzQANu.png)

**Expected behavior**
Scroll bar is not displayed

**Comment by tinyoverflow** [comment]
Hello,

can you please try it again with a different browser?
This doesn't seem to happen on Windows 10 Pro v2004 with Firefox x64 81.0.1.
<img width="244" alt="grafik" src="https://user-images.githubusercontent.com/6287093/95856118-cf885180-0d59-11eb-9134-fc178e96a456.png">

**Comment by DaneEveritt** [comment]
No worried about this in the admin area, will be addressed by an eventual rewrite.
