### ISSUE TITLE
How use Mounts folders?

### ISSUE THREAD

**Issue by Malachiel87** [pterodactyl/panel#2510]
Hi, which directory i have to use for have access to mounts that i created for the server?
i tried
/home/mountname
/home/container/mountname
mountname
/mountname - don't work it stuck you at start saying that is not correct

**Comment by DaneEveritt** [comment]
Once you've added a mount you must also _manually_ update the node config from the admin area to ensure that the specific mount you've created gets whitelisted on the host.

**Comment by Malachiel87** [comment]
a user replied with more better info and guided me, i just have inverted the values x)
