### ISSUE TITLE
Timezone is not correct on Wings

### ISSUE THREAD

**Issue by Malachiel87** [pterodactyl/panel#2513]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0.1
* Server's OS:  Ubuntu 18
* Your Computer's OS & Browser: Windows 10 & Chrome 

**Describe the bug**
So i noticed after i upgraded ptero to 1.0.0 (coming from 0.7) the timezone in all server is messed, yeah i found some closed issues on github, but is still not clear if is a know issue or you say that is a misconfigured system (as you wills see here is all correct), i feel  that i have to open a new one about this, so i check these:
- .env timezone is correct (Europe/Rome)
- .less /etc/timezone will output Europe/Rome on both server (panel vps and docker server)
- date will show correct value mer 14 ott 2020, 08.56.48, CEST
- using timedatectl it will show this
Local time: mer 2020-10-14 09:01:09 CEST
Universal time: mer 2020-10-14 07:01:09 UTC
RTC time: mer 2020-10-14 07:01:10
Time zone: Europe/Rome (CEST, +0200)
System clock synchronized: yes
systemd-timesyncd.service active: yes
RTC in local TZ: no
Wings seem to use the Universal Time instead Local Time

Panel: `php -v` PHP 7.4.11 (cli) (built: Oct 10 2020 19:44:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

Daemon: `uname -a` and `docker info`
Linux ns31182259 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Client:
 Debug Mode: false

Server:
 Containers: 30
  Running: 28
  Paused: 0
  Stopped: 2
 Images: 6
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-118-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 187.6GiB
 Name: ns31182259
 ID: GBRA:33TN:D5LH:YEXR:QM5Y:WHON:EUAB:M6IX:WVNA:QQ5D:7S67:3PGZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**To Reproduce**
1. Have a macchine with different timezone than UTC
2. Start any minecraft server for example it will show -2h difference
3. This issue will mess the logs and schedules, starting with different times

**Expected behavior**
Wings should use local time instead universal one

**Comment by schrej** [comment]
Dane, before you refer to [#2239 (comment)](https://github.com/pterodactyl/panel/issues/2239#issuecomment-675213274) again, can we verify that the eggs included in the panel actually work with the stuff that's in place for timezones right now?

@xion87 what egg(s) are you using?

**Comment by sergejostir** [comment]
In regards to https://github.com/pterodactyl/panel/issues/2239#issuecomment-675213274, setting TZ env var will have no effect unless tzdata package is installed within container (which is normally not).

**Comment by Malachiel87** [comment]
@schrej 
I am using minecraft/paper egg but it affect also all kind of eggs (Teamspeak/Sinusbot/Redbot)

**Comment by GiovaniFerraroTrivelli** [comment]
Steamcmd servers (in my case, CS:GO and HLDS) are also affected.

**Comment by Malachiel87** [comment]
For now i added to minecraft server the startup flag "-Duser.timezone=Europe/Rome" for cover the issue,, and i noticed panel tasks are working fine at right time

**Comment by parkervcp** [comment]
panel tasks are parsed separate from the servers.

**Comment by DaneEveritt** [comment]
As mentioned in the commit that closed this, if there are still images behaving incorrectly those will need to be fixed individually to respect the `TZ=` environment variable.
