### ISSUE TITLE
Add ability to manually execute a schedule from the panel

### ISSUE THREAD

**Issue by DrewSin-4** [pterodactyl/panel#2516]
**Is your feature request related to a problem? Please describe.**
I love the new UI and features that 1.0 brings, the one thing I miss from 0.7 is the ability to trigger and disable schedules, I'm not sure if it's an oversight on my part but I can't seem to find how to trigger schedules from the panel.

**Describe the solution you'd like**
A button to trigger and toggle schedules or the ability to right click the schedule and have a trigger and toggle option.

**Describe alternatives you've considered**
Deleting and remaking schedules is currently the only way I can think of toggling them.

**Additional context**
N/A

**Comment by notAreYouScared** [comment]
You can disable the schedule with the toggle under the edit menu...


![image](https://user-images.githubusercontent.com/1757840/95975616-639efb00-0de4-11eb-96f5-a83e5120eac4.png)
![image](https://user-images.githubusercontent.com/1757840/95975659-70235380-0de4-11eb-8d39-81b53592fdb6.png)

**Comment by DrewSin-4** [comment]
Oh cool, I never noticed that.

The Trigger button still seems like it could come in super handy though.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by DaneEveritt** [comment]
This was added yesterday. The 'Run Now' button is clickable when the schedule is enabled and not currently processing.

![](http://kelp.in/PpGcbE.png)
