### ISSUE TITLE
Make CPU usage display like memory usage

### ISSUE THREAD

**Issue by justinnobledev** [pterodactyl/panel#2520]
**Is your feature request related to a problem? Please describe.**
The CPU usage graph doesn't accurately represent how much CPU usage you are actually using at a glance and can be quite confusing.

**Describe the solution you'd like**
I would like for the CPU usage graph to be displayed the same way memory usage is displayed ie instead of 0-+1 of current CPU usage make it 0-100 always and draw the graph normally.

**Describe alternatives you've considered**
The other alternative is leaving as it currently is.

**Additional context**
<img width="878" alt="image" src="https://user-images.githubusercontent.com/3823604/96033400-a208da00-0e25-11eb-9cd3-48c065906ec3.png">

**Comment by notAreYouScared** [comment]
Not sure how that's confusing as its showing you what that specific server is using? Which seems to be about 3%

**Comment by matthewpi** [comment]
The only thing I could see doing is making the CPU graph's max value on the y-axis be the server's CPU Limit instead of being a smaller value.  So for example, if your server has a CPU limit of 100%, the graph's y-axis will have a maximum of 100% and a minimum of 0%.

Other than that I don't see how anything else could improve it.

**Comment by justinnobledev** [comment]
> 
> 
> The only thing I could see doing is making the CPU graph's max value on the y-axis be the server's CPU Limit instead of being a smaller value. So for example, if your server has a CPU limit of 100%, the graph's y-axis will have a maximum of 100% and a minimum of 0%.
> 
> Other than that I don't see how anything else could improve it.

I might've just worded this badly but this is what I meant. Since I was more talking about viewing it at a glance and not getting a reference of where it is at. Like I understand how it works and this might just be more of how I use the CPU graph and wanting the two graphs to work the same.

**Comment by DaneEveritt** [comment]
What happens when the limit is 400% and you're only using 20%? It would be next to impossible to see any changes in it. Although I suppose it is the same for memory and this is a moot point.

edit: What about when there is no limit, what is the cap in that scenario?

**Comment by justinnobledev** [comment]
> 
> 
> What happens when the limit is 400% and you're only using 20%? It would be next to impossible to see any changes in it. Although I suppose it is the same for memory and this is a moot point.
> 
> edit: What about when there is no limit, what is the cap in that scenario?

Wouldn't the cap be the what ever the cap of the CPU or does it not work that way?

**Comment by matthewpi** [comment]
> > What happens when the limit is 400% and you're only using 20%? It would be next to impossible to see any changes in it. Although I suppose it is the same for memory and this is a moot point.
> > edit: What about when there is no limit, what is the cap in that scenario?
> 
> Wouldn't the cap be the what ever the cap of the CPU or does it not work that way?

Servers can have an "unlimited" CPU limit if it is set to `0`.

**Comment by justinnobledev** [comment]
I guess you figure out the max and display that as the CPU max ie 8 core would be 800% while a 4 core would be 400%  I'm also starting to see why the CPU graph is designed the way it is.

Another option would be to display a new graph for every 100% since if I read the documentation correctly its core count * 100 per core and anything less that 100 would be just a percentage of 1 core. This way also would be useful for the CPU Pinning setting to display how much of that core is being used.

**Comment by Shinrai** [comment]
Personally I’d like to see a scale from 0-100% regardless of how many cores are assigned to the server. Graphs are supposed to be easy references. Having to do math (even as simple as it is) doesn’t give me the info at a glance I want.

**Comment by notAreYouScared** [comment]
0-100 wouldn't make sense, as linux each thread is 100%, so a 4 thread server will have usage of 400% if it's using everything.

**Comment by tinyoverflow** [comment]
I see the following options, ordered by how much I like these solutions:
1. Set the default cap to 100%, scale up by 100% if it exceeds it. (10% cpu => 100% graph, 120% cpu => 200% graph)
2. Set min=0 and max=cpu_limit from build configuration, otherwise leave it as is.
3. Leave it as is, as it definitely is possible to get used to it.
4. Same as above but cap to 100%.

I would like to see your opinions about that.
1: 🎉  2: ❤️  3: 🚀  4: 👀

**Comment by DaneEveritt** [comment]
We used to calculate everything as a scale of 100%, and a lot of people disliked it and found it incredibly confusing.

To me, the two options are:

1.) Leave it how it is.
2.) Use the maximum CPU limit as the graph cap. (e.g. 100/200/800) and if no limit is assigned just make it increments of 100 so it isn't as dramatic when things change.

**Comment by tinyoverflow** [comment]
With these two options available, I would definitely go with number two.

**Comment by justinnobledev** [comment]
I definitely think the 2nd option would be a lot more user friendly, but as others have mentioned you get use to it eventually.

**Comment by Roma123456789** [comment]
Hi,
Is that a way to scrape CPU and Memory utilization on same granafa panel?
