### ISSUE TITLE
Bug - White Screen after yarn build:production

### ISSUE THREAD

**Issue by booky10** [pterodactyl/panel#2527]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: `1.0.1`/`1.0.0`
* Server's OS: Ubuntu Server 20.04
* Your Computer's OS & Browser: Ubuntu Desktop 18.04, Chromium

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `7.4.3`
Daemon:
  Kernel: `Linux pterotest 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
  Docker:
```
    Client:
     Debug Mode: false
    
    Server:
     Containers: 3
      Running: 1
      Paused: 0
      Stopped: 2
     Images: 2
     Server Version: 19.03.13
     Storage Driver: overlay2
      Backing Filesystem: extfs
      Supports d_type: true
      Native Overlay Diff: true
     Logging Driver: json-file
     Cgroup Driver: cgroupfs
     Plugins:
      Volume: local
      Network: bridge host ipvlan macvlan null overlay
      Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
     Swarm: inactive
     Runtimes: runc
     Default Runtime: runc
     Init Binary: docker-init
     containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
     runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
     init version: fec3683
     Security Options:
      apparmor
      seccomp
       Profile: default
     Kernel Version: 5.4.0-48-generic
     Operating System: Ubuntu 20.04.1 LTS
     OSType: linux
     Architecture: x86_64
     CPUs: 1
     Total Memory: 13.7GiB
     Name: pterotest
     ID: TD7I:MIBH:ODCK:AEZF:ARZX:HFPS:UR3R:7VCX:VW3M:377X:TQXS:HCN3
     Docker Root Dir: /var/lib/docker
     Debug Mode: false
     Registry: https://index.docker.io/v1/
     Labels:
     Experimental: false
     Insecure Registries:
      127.0.0.0/8
     Live Restore Enabled: false
    
    WARNING: No swap limit support
```

**To Reproduce**
1. Go to your panel
2. In the pterodactyl panel directory run `yarn install` and `yarn build:production`
3. Hard refresh the page (Shift + F5)
4. Page will be completely white, if you are not on the admin page

**Expected behavior**
Page should be displayed normally, not white.

**Additional Information**
When you run `yarn build:production` some files in `public/assets` get deleted because the command `cd public/assets && find . \( -name "*.js" -o -name "*.map" \) -type f -delete` is run. Through that the page can probably no longer be displayed and shows a white screen.

**Comment by DaneEveritt** [comment]
Please include the actual error output from the browser development console and/or your `yarn build` output. The white screen is because something is not running correctly, this is not a bug.
