### ISSUE TITLE
Automatically focus text input in console page

### ISSUE THREAD

**Issue by Malachiel87** [pterodactyl/panel#2528]
**Is your feature request related to a problem? Please describe.**
Similiar issue of #2522, you need to click console box when you load the page before entering any command here, it was working on ptero 0.7

**Describe the solution you'd like**
I think the fix make for #2522 would work also in this case

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by DaneEveritt** [comment]
I don't like the idea of having that field auto-focus (even if it did that in 0.7). That just seems like it is asking to accidentally send commands or random junk when you're not aware that you're auto-focused in it.

Plus, it means any keyboard navigation/hot-keys get ignored right away whenever that page is loaded?

I think sending a command to the console should be an explicit action, e.g. clicking into the command field.

**Comment by Malachiel87** [comment]
what you mean? i never have trouble to false-click/type on it... it would be usefull for run and switch comands in all server

**Comment by parkervcp** [comment]
Just because you have never accidentally sent a command doesn't mean others haven't

**Comment by Malachiel87** [comment]
I think is more a user responsability to open the console page and keep it active than prevent ptero to do it

**Comment by DaneEveritt** [comment]
I will not be implementing this, but thank you for the suggestion. :)

**Comment by kmecpp** [comment]
@DaneEveritt instead of auto focus, could the console input be [tabindex="0"](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) ?

A keyboard shortcut (like Ctrl + K or something) would also be helpful
