### ISSUE TITLE
Server Name Abbreviation

### ISSUE THREAD

**Issue by Clarkcj12** [pterodactyl/panel#2532]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just a UI enhancement.

**Describe the solution you'd like**
A field for doing abbreviated server names. While it looks fine if a person has the sidebar fully opened when it is made smaller, the text gets mostly hidden, when it should have an option to do like up to a three-letter abbreviation for it, ie: a company named Splash Hosting, their abbreviation may be SPH. Even adding the option to instead of a text, the server name has the option to do a server, logo for either when the sidebar is opened full, or having a smaller icon/logo when the sidebar is made smaller.

**Comment by DaneEveritt** [comment]
There is no sidebar in 1.0, I'm not sure what you're referring to.

**Comment by Clarkcj12** [comment]
![Capture](https://user-images.githubusercontent.com/1118301/96328237-a512ee80-100e-11eb-8d9c-4b37b5d9e206.PNG)
@DaneEveritt That is what I am talking about, on the left-hand sidebar when you click the hamburger icon it makes it smaller and larger.
This is what it looks like when it is made smaller, 
![Capture](https://user-images.githubusercontent.com/1118301/96328259-f28f5b80-100e-11eb-95e3-8c5a7b6e6cbb.PNG)
