### ISSUE TITLE
Schedule with backup and power actions fails and never runs

### ISSUE THREAD

**Issue by Phyremaster** [pterodactyl/panel#2534]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.1
* Server's OS: Ubuntu 18.04.5 LTS
* Your Computer's OS & Browser: Windows 10, Firefox

**Describe the bug**
I am using PHP 7.4.11 (latest 7.4, as of a few days ago). I have two schedules on a Minecraft server. One is purely command tasks, and the other has a few commands followed by a stop, backup, and start. Both are enabled, and have been for a few days (they are set to run daily). The schedule that only contains commands has been running just fine, but the other schedule fails and never runs. I know that it fails because I found this in a log file `/var/www/pterodactyl/storage/logs/laravel-2020-10-15.log`:
```
[2020-10-15 03:59:03] production.ERROR: ErrorException: Trying to get property 'id' of non-object in /var/www/pterodactyl/app/Services/Schedules/ProcessScheduleService.php:73
Stack trace:
#0 /var/www/pterodactyl/app/Services/Schedules/ProcessScheduleService.php(73): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/pterodactyl/app/Console/Commands/Schedule/ProcessRunnableCommand.php(69): Pterodactyl\Services\Schedules\ProcessScheduleService->handle()
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(202): Pterodactyl\Console\Commands\Schedule\ProcessRunnableCommand->Pterodactyl\Console\Commands\Schedule\{closure}()
#3 /var/www/pterodactyl/app/Console/Commands/Schedule/ProcessRunnableCommand.php(82): Illuminate\Support\Collection->each()
#4 [internal function]: Pterodactyl\Console\Commands\Schedule\ProcessRunnableCommand->handle()
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure()
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call()
#10 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#11 /var/www/pterodactyl/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute()
#12 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#13 /var/www/pterodactyl/vendor/symfony/console/Application.php(911): Illuminate\Console\Command->run()
#14 /var/www/pterodactyl/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#15 /var/www/pterodactyl/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#17 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#18 /var/www/pterodactyl/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#19 {main}
```
Going by the Minecraft server logs, I can clearly see that none of the commands in the schedule have run, so it isn't failing just when it executes the power actions and backup; it's failing before that, likely in some form of parsing or loading stage.
This does not appear to be related to the specifics of the commands sent to the server; the only real difference between the commands in the working schedule and the broken one is that the broken one includes a `kick @a` command. Maybe the `@` is causing special character issues? Here are both schedules:
![image](https://user-images.githubusercontent.com/48633331/96334641-3c446a00-1040-11eb-952e-ed3da0defd74.png)
![image](https://user-images.githubusercontent.com/48633331/96334660-5e3dec80-1040-11eb-9625-ab0743a9c60a.png)
This may be related to #2470 and #2134, and possibly also #2032 as I have not yet tried rebooting the whole machine (not really an option at the moment). I looked at those issues and they appear to have closed mainly from lack of information, so I tried to include everything I could find.

**To Reproduce**
1. Create a (Minecraft?) server
2. Create two schedules
3. Add several (`say`?) command tasks to both
4. Add (`kick @a` command,?) stop, backup, and start actions to one schedule
5. Wait for the schedules to be triggered
6. Note that only one schedule executes
7. Find error logs in `/var/www/pterodactyl/storage/logs`

**Expected behavior**
All tasks in both schedules are executed.

**Comment by Malachiel87** [comment]
for me is working with these task (i still don't use the backup system)
![image](https://user-images.githubusercontent.com/3611852/96336867-c7465400-1082-11eb-90cb-58d3bc184df9.png)

**Comment by Shinrai** [comment]
I have a simple restart and the tasks aren’t working. Backups aren’t working after I upgraded to 1.0 and upgraded wings. Even manual backups fail.

**Comment by Phyremaster** [comment]
I can confirm that the `@` symbol is not the cause of the issue, because I tried replacing `@a` with `Phyremaster` and it still didn't run.

**Comment by Phyremaster** [comment]
Removing the backup task also didn't work.

**Comment by Phyremaster** [comment]
Removing the stop and start tasks also didn't work. This left only command tasks, which I know work from my other schedule. There's something more complicated going on here.

**Comment by DaneEveritt** [comment]
Please check the `failed_jobs` table in the database and see if there are any entries. Please also try creating a different schedule with a single task and see if it runs. 

Have you attempted to restart `pteroq`?

**Comment by Phyremaster** [comment]
Six entries in `failed_jobs` table: https://ghostbin.co/paste/c8525
I have another schedule with several commands that has been running daily without issue.
I'll try restarting various things (including `pteroq`) tomorrow. For tonight, I disabled and re-enabled the schedule to see if maybe the removal of a problematic task hadn't actually registered a change in the schedule.

**Comment by Phyremaster** [comment]
Those entries appear to be unrelated, in retrospect. I do, however, have the following in `laravel-2020-10-18.log`:
```
[2020-10-18 03:59:03] production.ERROR: ErrorException: Trying to get property 'id' of non-object in /var/www/pterodactyl/app/Services/Schedules/ProcessScheduleService.php:73
Stack trace:
#0 /var/www/pterodactyl/app/Services/Schedules/ProcessScheduleService.php(73): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/pterodactyl/app/Console/Commands/Schedule/ProcessRunnableCommand.php(69): Pterodactyl\Services\Schedules\ProcessScheduleService->handle()
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(202): Pterodactyl\Console\Commands\Schedule\ProcessRunnableCommand->Pterodactyl\Console\Commands\Schedule\{closure}()
#3 /var/www/pterodactyl/app/Console/Commands/Schedule/ProcessRunnableCommand.php(82): Illuminate\Support\Collection->each()
#4 [internal function]: Pterodactyl\Console\Commands\Schedule\ProcessRunnableCommand->handle()
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure()
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call()
#10 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#11 /var/www/pterodactyl/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute()
#12 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#13 /var/www/pterodactyl/vendor/symfony/console/Application.php(911): Illuminate\Console\Command->run()
#14 /var/www/pterodactyl/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#15 /var/www/pterodactyl/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#17 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#18 /var/www/pterodactyl/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#19 {main}
```

**Comment by Phyremaster** [comment]
It's also entirely possible that the schedule itself is in some way bugged. I believe that it was my second schedule, and I renamed my first schedule so that this schedule could take its original name (which happens to be a substring of the first schedule's new name). This schedule should start right as another schedule is finishing. The first task of this schedule is delayed by 55 seconds, and a few tasks (a command task, stop task, backup task, and start task, in that order) have no delays. Any of these facts could be relevant, which is why I posted screenshots of the entirety of both schedules.

**Comment by DaneEveritt** [comment]
It looks like your schedule has no task with a sequence ID of `1` 🤔. I might have fixed the specific error you're seeing by changing all of the code, but let me dig a little more and see if there is something not properly setting the IDs.

**Comment by DaneEveritt** [comment]
Ah yeah, this is super bugged. You can reproduce it by making a schedule with two tasks, and then deleting the first task. The remaining task doesn't get assigned a `sequence_id` of `1` therefore it is never found and the current `1.0.1` code doesn't check to make sure a task is even returned.

**Comment by Phyremaster** [comment]
Oh interesting, that would explain it. But for now it sounds like I should be able to fix it if I recreate the schedule from scratch and avoid deleting tasks?

**Comment by Phyremaster** [comment]
Can confirm that my schedule works now, thank you very much!
