### ISSUE TITLE
Various - usability items/suggestions - posted fromn discord as requested

### ISSUE THREAD

**Issue by Ma8ician** [pterodactyl/panel#2537]
Hi Guys - a few more usability suggestions
1) Search - should be permanently active - and /or when you click the magnifying glass - set the context to the search box
2)  As per attached image - the file management element and server management elements in your server - these are critical all the time usage items - please can we have them in a heading bar - 

(https://user-images.githubusercontent.com/49976325/96348147-e3f48300-10a6-11eb-9125-4f6311a7f893.png)

3) No criticism - but from a daily usage perspective - you should be looking to reduce clicks and scrolls in all functions ( Think 40+ servers and 60+ plugins from a logic perspective)
4) I know it's a pain to make these suggestions at "release" - I however do not have a spare machine so couldn't test and make suggestions during dev.

Still great update - a few elements to make it even better

**Previous Suggestions:**

A) nodes > Servers - memory and harddrive allocations used to be shown - this is critical to me - when trying to reallocate resources between and to servers - I now have to click through everything or maintain an external list to be able to judge where resources are used or jump to the main page and search for them collectively

Suggestion:
1) Servers in general = add a field to allow us to group servers, and then filter the server list by that field.  I have Production / Test / Dev / Minigames / Other  servers - this with a drop down selector it would make things a lot easier
2) Similarly with users - except it would be awesome if we could have group permissions - I have separate levels of users Owners / Technical x3 / Server Staff x 7 (Each Server or group of servers)

**Comment by DaneEveritt** [comment]
Can you break this issue into a few based on the specific request, having 6 different things in one issue is impossible for me to manage. 👍  (You can edit this one to just be whatever the first request is, and make a few new ones for everything else).
