### ISSUE TITLE
Console text unreadable with white background/highlight

### ISSUE THREAD

**Issue by VibeGAMESNL** [pterodactyl/panel#2541]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.1 
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10, Chrome 

**Describe the bug**
If the server outputs a string with a white background in the console, the text becomes unreadable.
![image](https://user-images.githubusercontent.com/66668585/96352010-502fb080-10c0-11eb-8784-a8ebec8a3b2d.png)

**To Reproduce**
1. Create a game server using the FiveM egg of @parkervcp 
2. Enable txadmin
3. Start the server and watch the console

**Expected behavior**
Text color should be black when background/highlight is white

**Comment by DaneEveritt** [comment]
That's a bug with the game, not Pterodactyl. It just reads the color codes sent in the output and renders them.

**Comment by VibeGAMESNL** [comment]
I don't agree. This is on windows and this issue was not present on the 0.7 version:
![image](https://user-images.githubusercontent.com/66668585/96352079-e1068c00-10c0-11eb-85ea-11ff13f2e434.png)
