### ISSUE TITLE
Secure access to Docker Socket

### ISSUE THREAD

**Issue by NoxInmortus** [pterodactyl/panel#2542]
Hello, I'm trying to give a secured access to the Docker Socket to Wings.

I'm using this image to be a proxy between Wings and the Docker socket : https://github.com/Tecnativa/docker-socket-proxy

First of all, I did not find any details about the Docker API features Wings require. I would say CONTAINERS and NETWORKS features, but is there more ? 

More critical, it seems Wings is unable to connect to a remote socket through TCP.
I edited the config.yml to have `socket: tcp://socket-proxy:2375`. The container does resolve `socket-proxy` correctly and can access the `2375` port. But Wings keeps crashing and the log still displays `Cannot connect to the Docker daemon at unix:///var/run/docker.sock` like I did not edit the config.yml.

I then request more documentation the first point, and to be able to remotely access to the Docker API through TCP.

Everybody working with Docker knows that mounting in a container the `/var/run/docker.sock` is a bad security practice, specially when this container is reachable from the outside, but that's just a common bad habit everyone does.

**Comment by schrej** [comment]
Unfortunately the config file is lying, those config values do not get used. Try setting `DOCKER_HOST=tcp://socket-proxy:2375`, you can also do that in the .service file.

**Comment by DaneEveritt** [comment]
Removed the confusion in https://github.com/pterodactyl/wings/commit/9b54be06bbecbdc6a273b07ccc92fca9eab606d1

**Comment by NoxInmortus** [comment]
Hello @DaneEveritt @schrej 

Thanks for the answer and the commit. Adding the variable to the config.yml does not work, but adding it to environments parameters is alright.

About the API features wings needs, it seems to require the following : 
```
      POST: '1'
      CONTAINERS: '1'
      NETWORKS: '1'
```
