### ISSUE TITLE
Timezone error

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2546]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/c370e08f651a33085fef29bf001b149c4bb913b0 & https://github.com/pterodactyl/wings/commit/3cd17a28565ca55176dc072edfaddb62a3dbb07d
* Version of Panel/Daemon: 1.0.1
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
![image](https://user-images.githubusercontent.com/28255085/96354444-7a449b00-10df-11eb-95e3-b71db7f6ba72.png)

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/wings/commit/560c832cc6657434ab5bd7df8f91631f030f7eec
