### ISSUE TITLE
Wings: token too long

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2549]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/c370e08f651a33085fef29bf001b149c4bb913b0 & https://github.com/pterodactyl/wings/commit/3cd17a28565ca55176dc072edfaddb62a3dbb07d
* Version of Panel/Daemon: 1.0.1
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
![image](https://user-images.githubusercontent.com/28255085/96355081-6cdedf00-10e6-11eb-9498-8c89d3ef2b9e.png)

Spam console `sdsdsdsdsdsdsdsdsdsd` more 10000 length

**Comment by DaneEveritt** [comment]
This is normal in Go, anything over 4096 bytes I believe gets truncated by the line scanner. At this point it is such a minor thing that I am not concerned with adding additional complexity just to handle it.

Don't spam the console with 10,000 characters of `sddsdsd` and it won't be a problem. :)

(I'm solving for the 99% use case, not all of the wildly unlikely edge cases.)

**Comment by zKoz210** [comment]
That is, is it normal that the console then stops working and this is not a problem? 🐋

**Comment by DaneEveritt** [comment]
Oh the entire console stops, or just that line doesn't come through?

**Comment by zKoz210** [comment]
it stops updating at all until the server is restarted

**Comment by DaneEveritt** [comment]
In the future let's include that with the bug report, that is very important to know about and wasn't mentioned. :)
