### ISSUE TITLE
Documentation Update Request

### ISSUE THREAD

**Issue by Mike981874** [Pterodactyl/Panel#255]
Hi,

Nothing important, just a potential addition to the documentation pages for CentOS 7, because I'm sure there will be people who don't have much experience and won't know the differences.

Page: https://docs.pterodactyl.io/docs/queue-listeners

Under "**Installing Supervisor**" section add display for CentOS 7 command:
`sudo yum install supervisord -y`
`service supervisord start`
`chkconfig supervisord on`

Under "**Creating Configuration File**" add the proper config file location for CentOS 7:
`/etc/supervisord.conf`
_On CentOS 7 you can add the config contents to the bottom of this file and restart supervisord._
Also make sure to change the `user=www-data` to `user=apache` otherwise it'll fail to start.

**Comment by DaneEveritt** [comment]
Hey there, there is actually a way to suggest edits right in the docs by using the `Suggest Edits` button.

![](https://s3.kelp.in/lOuCE.png)
