### ISSUE TITLE
Schedules run now always processing

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2550]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/c370e08f651a33085fef29bf001b149c4bb913b0 & https://github.com/pterodactyl/wings/commit/3cd17a28565ca55176dc072edfaddb62a3dbb07d
* Version of Panel/Daemon: 1.0.1
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
![image](https://user-images.githubusercontent.com/28255085/96355198-a8c67400-10e7-11eb-80b5-31de96c7f725.png)

reload page - ACTIVE

- Try renaming the task, and then click run now, the name and commands (list tasks) will go back

Also steps:
- create schedules
- add task
- run now
- rename schedules
- add task
- run now
- schedules always processing

**Comment by tmunsch** [comment]
I am having a similar issue, good steps to reproduce this would be:
Set server backup limit to 1
Create backup manually
Create schedule to create backup
Click Run now
Message displays backup limit reached
Task stays on processing indefinitely
