### ISSUE TITLE
Backups: Wings error

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2551]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/c370e08f651a33085fef29bf001b149c4bb913b0 & https://github.com/pterodactyl/wings/commit/3cd17a28565ca55176dc072edfaddb62a3dbb07d
* Version of Panel/Daemon: 1.0.1
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
![image](https://user-images.githubusercontent.com/28255085/96355376-b54bcc00-10e9-11eb-9c2b-73ad00a677c7.png)

I can't say exactly how I was able to get this error, I just tried to overflow the array of ignored files when creating the request

**Comment by matthewpi** [comment]
Due the amount of logic changed with `v1.2.0` regarding backups and the api requests for it, I'm going to assume that this was fixed or is no longer a problem.  If you are still able to produce this error, reply to this issue in order for it to be reopened.
