### ISSUE TITLE
IP allocation note not removed on de-allocation

### ISSUE THREAD

**Issue by tinyoverflow** [pterodactyl/panel#2553]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.1
* Server's OS: Debian 10 x64
* Your Computer's OS & Browser: macOS 10.15.7, Firefox 81.0.1

**Describe the bug**
A note created on an IP address by a user won't get removed when the IP/Port gets removed from the server.
Therefore it still exists when attaching the IP/Port to a new server.

**To Reproduce**
1. Assign an IP/Port allocation to a server
2. Switch to the frontend Network-tab of the server
3. Create a note
4. Remove the allocation from the server in the admin panel
5. Add the allocation to a different server
6. Navigate to the frontend Network-tab of the new server
The note is still visible.

**Expected behavior**
The note should be removed once the allocation gets removed from a server.

**Comment by DaneEveritt** [comment]
Does it go away if you refresh?
