### ISSUE TITLE
Visual canvas issue

### ISSUE THREAD

**Issue by Corenb** [pterodactyl/panel#2556]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.0.1/1.0.0
* Server's OS: Centos 8

**Describe the bug**
We can adjust text boxes outside of their canvas.

![image](https://user-images.githubusercontent.com/1338450/96367035-b7467700-114b-11eb-87bc-04477ea8e22f.png)

**Comment by DaneEveritt** [comment]
I'm not worried about this.
