### ISSUE TITLE
Ability to fully automate installations

### ISSUE THREAD

**Issue by tinyoverflow** [pterodactyl/panel#2557]
**Is your feature request related to a problem? Please describe.**
As an administrator, I have to create a server by myself in the panel and copy the config to the server. I cannot fully automate the provision of linux hosts with Wings without manual intervention.

**Describe the solution you'd like**
As an administrator, I want to create a token which I can pass to Wings together some other parameters such as the panel url, internal name, fqdn, memory, allocations, [...] to be able to fully automate provisioning of new linux hosts with wings on it.
Wings should then reach out to the given Panel URL and register itself using the secret token. This creates a server at a specific location (can be specified using the parameters passed to Wings). I would also appreciate it if all of these settings could be specified via a provisioning file that can be passed to wings instead.

To improve security, the token could _optionally_ be bound to a specific subnet.

This allows to simply order servers and add the IPs to the automation tool like Ansible to get a gigantic fleet of host machines with a single click.

**Describe alternatives you've considered**
Keep it the way it is right now.

**Additional context**
None.

**Comment by DaneEveritt** [comment]
You can already do this based on what you're asking. The endpoint to fetch a node configuration just needs node:read permissions to fetch the configuration in 1.0.

Hit the "auto deploy" button on a node and you'll see what it does. The system will auto-create an API key for this if there is not one with only `node:read` permissions.

**Comment by tinyoverflow** [comment]
Thanks for your fast reply, Dane!
I think you misunderstood me. Correct me if I'm wrong, please.

Yes, you're absolutely right. There is a button to auto-deploy node. But this node have to be created in Pterodactyl before either through the API or by hand. That requires an external source. This is doable with a few nodes, but when provisioning houndreds of nodes, this will become really a really tedious task to do.

While it is possible to create eg. a script that automatically creates a node in pterodactyl, receives the deploy-token and then passes it to wings, it also is an external thing that
- has to be maintained seperately
- can break easily through updates

I'm trying to do some examples.

    # Currently the auto-deploy command does this:
    wings configure --panel-url https://[panel.host] --token [some-read-only-token] --node [id]

    # I imagine something like this:
    wings configure --panel-url https://[panel.host] \
                    --token [some-read-write-token] \
                    --name "de.fra1.toast" \
                    --location "de.fra1" \
                    --fqdn "toast.fra1.de.hosts.myhost.tld" \
                    --ssl \
                    --memory-limit 65536 \
                    --memory-softlimit 10 \ # The overallocation-limit in percent
                    --disk-limit 524288 \
                    --disk-softlimit 0 \
                    --daemon-port 8080 \
                    --sftp-port 22 \
                    --allocations "12.34.56.78:25100-25900,56.78.90.12:51337"

This would allow to just maintain a host inventory to fully automate everything without manual intervention. 
With Ansible, for example, the FQDN could be read from the hostname. The location from the FQDN und the node name could also be derived by the hostname. Even the IP addresses could be substituted by tools like Ansible

**Comment by matthewpi** [comment]
The current system works well for most use-cases and I don't see how anything could be changed to really help your use-case.

Also, the API rarely has breaking changes (except 0.7 to 1.0) so that shouldn't be a reason why you wouldn't use the API.

**Comment by tinyoverflow** [comment]
I'll see if I find time to try a few things. Thank you. I really appreciate your time!

**Comment by DaneEveritt** [comment]
You can create the node using the Panel API and then use the API to get the config for the node, right?
