### ISSUE TITLE
Custom local Docker images are failing to pull

### ISSUE THREAD

**Issue by chelog** [pterodactyl/panel#2559]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0
* Server's OS: Ubuntu 18.04

This problem was described in #431, but appeared again after upgrading to 1.0 and new Wings daemon.

**Describe the bug**
Servers won't run if using local Docker images, it's trying to pull these from repo, but fails to find them:
```
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as stopping...
container@pterodactyl~ Server marked as offline...
container@pterodactyl~ Error Event [9820182f-7a9f-47ff-b6b0-0c3ea6375586]: Error response from daemon: pull access denied for octoteam/gmod, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Using `~` as prefix fails also:
```
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as stopping...
container@pterodactyl~ Server marked as offline...
container@pterodactyl~ Error Event [32910e64-616c-4671-98da-396629444b2b]: invalid reference format
```

**Comment by parkervcp** [comment]
for local images you put a `~` before the name in the panel.

**Comment by chelog** [comment]
@parkervcp as I mentioned in second part, this gives `invalid reference format` error. I set it to `~octoteam/gmod`

**Comment by parkervcp** [comment]
I missed that part and was just commenting.

**Comment by tinyoverflow** [comment]
Possible workarounds until this is fixed:
1. Setup your own [Docker Registry](https://hub.docker.com/_/registry/) and push your images to it. After that you can add the address to your registry to your egg.
2. You might be able to use the GitHub registry though, as I haven't used it, I'm not sure if it allows you do pull images without authentication.

**Comment by chelog** [comment]
@tinyoverflow yes, for now I'm using help from [this comment to old issue](https://github.com/pterodactyl/panel/issues/431#issuecomment-318133149), however I think it should be fixed :)
Not using hub because images are rather big, don't want to send those amounts of data each rebuild

Thanks for heads-up though!

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/wings/commit/3f9ac8b89a5bd2d6cce259b674b8188054b16811
