### ISSUE TITLE
FiveM alpine folder server transfer issue

### ISSUE THREAD

**Issue by VibeGAMESNL** [pterodactyl/panel#2561]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.0.0
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
When I try to transfer a server that uses the FiveM egg of @parkervcp wings outputs an error and the transfer will fail.
`ERROR: [Oct 19 19:54:10.482] failed to get archive for server error=walking /srv/daemon-data/8eded47d-5ae9-4c1a-b43c-3dae29f69980/alpine: /srv/daemon-data/8eded47d-5ae9-4c1a-b43c-3dae29f69980/alpine/bin/arch: writing: alpine/bin/arch: readlink: readlink alpine/bin/arch: no such file or directory server=8eded47d-5ae9-4c1a-b43c-3dae29f69980`

the crazy part is that this (alpine/bin/arch) file exists: 
![image](https://user-images.githubusercontent.com/66668585/96505273-2f00c880-1256-11eb-9b5f-756abd74584a.png)

**To Reproduce**
1. Create a server with [this egg](https://github.com/parkervcp/eggs/tree/master/gta/fivem)
2. Transfer the server to another node.
3. Check the wings logs

**Expected behavior**
Complete the transfer without error.

**Comment by parkervcp** [comment]
You need to update your egg and change the image the server is using.

I ask that you bring egg issues to the eggs and games channel in discord first.

**Comment by parkervcp** [comment]
At first I thought this was the arch missing error people have had that changing the image to the debian one fixed.

That's my bad.

Back on topic I have no idea what the file does

**Comment by DaneEveritt** [comment]
@matthewpi guessing this might be a trivial solve (and for backups too) to just ignore symlinks?

**Comment by parkervcp** [comment]
This is probably related to #2418

**Comment by DaneEveritt** [comment]
Yes, identical cause.
