### ISSUE TITLE
Feature Request: Audit logging

### ISSUE THREAD

**Issue by JustinRijsdijk** [pterodactyl/panel#2562]
**Is your feature request related to a problem? Please describe.**
Auditlog what happens to the server, and in the most ideal situations even log when users edit files or zip files etc.

**Describe the solution you'd like**
A new tab accessible for server owners and subusers with the permission, where audit logs are listed.

**Describe alternatives you've considered**
Well, there isn't ana lternative to this really.

**Comment by RihanArfan** [comment]
Duplicate of #1219

**Comment by JustinRijsdijk** [comment]
My bad, I thought that Issue was closed.
