### ISSUE TITLE
Unable to move files outside of subdirectories [Browser File Manager]

### ISSUE THREAD

**Issue by DrewSin-4** [pterodactyl/panel#2563]
**Background (please complete the following information):**
* Panel or Daemon: 
* Version of Panel/Daemon: PANEL: 1.0.1 DAEMON: 1.0.0
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser:  Windows 10 - Google Chrome

**Describe the bug**
Unable to move files outside of sub directories. 

Panel: PHP 7.2.34-2+ubuntu18.04.1+deb.sury.org+1
Daemon: 4.15.0-118-generic 19.03.13

**To Reproduce**
Go to your file manager
You're now in the main directory (/home/container) 
Create a folder in there called "mods" and move a file into there
Try to move the file out of there back into the main directory
You're unable to.

Example https://i.imgur.com/IaIrWmr.gif

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

It'd be nice to be able to move files back into the main directory.

**Comment by DaneEveritt** [comment]
Use `../<name>` to move the file up a directory. :)
