### ISSUE TITLE
Servers not marked as Suspended.

### ISSUE THREAD

**Issue by Sibald** [pterodactyl/panel#2565]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Google Chrome

Version: PHP 7.4.11

When scrolling to the server list.
Some servers are marked as Suspended.
While some servers are not marked as suspended, but when you click on it. You are not able to access them.
Because they are suspended.

The bug is that they are sometimes not marked as suspended when they are.

**Comment by fadedmax** [comment]
@Sibald Mind including some screenshots?

**Comment by DaneEveritt** [comment]
Closing in favor of #2613 which managed to narrow down the specific issue.
