### ISSUE TITLE
Console size and console text is too small on ultrawide monitors

### ISSUE THREAD

**Issue by SecretlyJealous** [pterodactyl/panel#2566]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.1
* Server's OS: CentOS 7
* Your Computer's OS & Browser: Windows 10 & Google Chrome

**Describe the bug**
I'm using an ultrawide monitor (21:9 aspect ratio) and my desktop resolution is 3440x1440 but the console size is very small:
![Untitled](https://user-images.githubusercontent.com/10485646/96611920-15628e00-12f5-11eb-958b-8d229c13540a.png)

Minimizing the browser still makes the text very hard to read:
![Untitled](https://user-images.githubusercontent.com/10485646/96612616-dda81600-12f5-11eb-9cf8-ee275a52fbe5.png)

**To Reproduce**
1. Use an ultrawide monitor to access the panel
2. Update the panel to 1.0.1

**Expected behavior**
I'm hoping there's a way to add support for people that use ultrawide monitors

**Comment by DaneEveritt** [comment]
I have no plans to make the design stretch to fit the entire window, it would look absolutely horrendous at extreme resolutions.

**Comment by AngryCarrot789** [comment]
Would it be possible to add user preferences that allow it if a user wants it? I experience the same problem looking at log files too, i usually have to download or copy the logs to something like VSCode just so i can read them properly, due to text wrapping on the file viewer

**Comment by AngryCarrot789** [comment]
I found a sort of work around. If you search for an element that uses the style `jyeSuy`, you can edit that style's `margin-left` and `margin-right` properties to `2.5rem`, and also set `max-width` to 100%, and that will stretch the console and everything to your browser's width
