### ISSUE TITLE
Backup restore option

### ISSUE THREAD

**Issue by VibeGAMESNL** [pterodactyl/panel#2567]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice if you could restore a backup from the panel. You now have to download it and upload everything again via FTP.
![image](https://user-images.githubusercontent.com/66668585/96613519-58c1fa00-12ff-11eb-97ab-f6dbda341e01.png)

**Describe alternatives you've considered**
Restore a backup manually via SFTP but that is slow and not automatic.

**Comment by DaneEveritt** [comment]
Gonna call this a duplicate of https://github.com/pterodactyl/panel/issues/2016 they're effectively the same concept.
