### ISSUE TITLE
Allocation shows alias instead of IP

### ISSUE THREAD

**Issue by TeemoCell** [pterodactyl/panel#2568]
https://github.com/pterodactyl/panel/blob/4028588621c931a1c8715bea42e86698e8737d6f/resources/themes/pterodactyl/base/index.blade.php#L56

It should show the IP and not the alias of the allocation.

`<td><code>{{ $server->getRelation('allocation')->ip }}:{{ $server->getRelation('allocation')->port }}</code></td>`

**Comment by DaneEveritt** [comment]
You're linking to code from 0.7, and regardless that is intentional and not a bug.
