### ISSUE TITLE
Ability to copy servers

### ISSUE THREAD

**Issue by narashini** [pterodactyl/panel#2569]
**Is your feature request related to a problem? Please describe.**
It is quite annoying when I'm setting up a bungeecord network and I can't just make 1 server and then copy it to make all the servers in my network

**Describe the solution you'd like**
I would like to be able to copy servers with the exact same files, owner and configuration.

**Describe alternatives you've considered**
Making an autohotkey to auto fill out the details on making a new server. But this doesnt copy the server so i have to edit configs to get bungeecord to work

**Additional context**
I dont have any additional content

**Comment by matthewpi** [comment]
Duplicate of #2148
