### ISSUE TITLE
White Pages, name field is required

### ISSUE THREAD

**Issue by EshanMistry73** [pterodactyl/panel#2570]
_I am not sure if this is a bug, however nobody on Discord has been able to resolve it, so in the case that it is, i have created this. If it is not, please close this_

**Background (please complete the following information):**
* Panel or Daemon: https://panel.villagerhost.net/
* Version of Panel/Daemon: 1.1
* Server's OS: Ubuntu 18.04.5 LTS
* Your Computer's OS & Browser: Windows 10, Google Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `7.3.23` 
Daemon: `Linux eu1 4.15.0-122-generic #124-Ubuntu` and ` Kernel Version: 4.15.0-122-generic`

https://bin.ptdl.co/fc2uf/

production.ERROR: Pterodactyl\Exceptions\Model\DataValidationException: Data integrity exception encountered while performing database write operation. {"name":["The name field is required."]} in /var/www/pterodactyl/app/Models/Model.php:60

**Expected behavior**
Panel login and main page are blank/white for users, however, the admin area is still accessible and that account can still view servers directly.

**Comment by DaneEveritt** [comment]
Your error does not line up with what you are describing, please check your browser development console logs for the true error, which is likely an issue with the compiled JS. Have you made any custom modifications?

Additionally, 1.1 is not a version for either the Panel or Wings, please check what your actual version is and update that.

**Comment by EshanMistry73** [comment]
> Your error does not line up with what you are describing, please check your browser development console logs for the true error, which is likely an issue with the compiled JS. Have you made any custom modifications?
> 
> Additionally, 1.1 is not a version for either the Panel or Wings, please check what your actual version is and update that.

Hey! Thanks for the quick reply, super-sorry, version 1.0.1.

![image](https://user-images.githubusercontent.com/14224587/96751940-b882d880-13c5-11eb-9f99-d6e69f81db5f.png)


Nothing custom, i accidently moved a folder and forgot what it was, so i re-entered the commands listed here to generate new panel files - https://pterodactyl.io/panel/1.0/upgrade/1.0.html

In regards to dev tools, i am getting: Refused to execute script from 'https://panel.villagerhost.net/auth/login' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled. (Seems not to be related to the issue in the logs from earlier like you mentioned, although i am not sure whether that, or this is the reason its showing a white page, and why for some reason the admin area is still visible to myself, and i can access all the servers but users cannot)

![image](https://user-images.githubusercontent.com/14224587/96751970-c3d60400-13c5-11eb-9691-eee7a0e043ee.png)


Once again, sorry for pestering with this issue, however i appreciate your assistance and help!

**Comment by EshanMistry73** [comment]
So i re-installed the files again using the guide (https://pterodactyl.io/panel/1.0/upgrade/1.0.html) and its now resolving the pages again, just as we had people that needed access to it, although i did this before twice and after a while it broke again on both occasions- ill keep you posted if it does it again/when and if its the same error.

**Comment by DaneEveritt** [comment]
This is almost certainly an issue with your setup specifically as that error says. Glad you got it resolved.
