### ISSUE TITLE
Refused to execute script from 'https://domain.tld/assets/bundle.54692811.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by INfoUpgraders** [pterodactyl/panel#2574]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v1.01
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 Pro & Chrome

**Describe the bug**
```
Refused to execute script from 'https://domain.tld/assets/bundle.54692811.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```
There seems to be fixes for it [here](https://stackoverflow.com/questions/40574159/refused-to-execute-script-strict-mime-type-checking-is-enabled)
But I've listed a temporary (until it's fixed) below.

**To Reproduce**
1. `cd /var/www/pterodactyl`
2. `yarn run build:production`
3. Open browser and visit your server IP or domain.

**Expected behavior**
To not bug out like this

**Fix**
Follow the upgrade guide:
```cd /var/www/pterodactyl && php artisan down```
```curl -L https://github.com/pterodactyl/panel/releases/download/v1.0.1/panel.tar.gz | tar -xzv```
```chmod -R 755 storage/* bootstrap/cache```
```composer install --no-dev --optimize-autoloader```
```php artisan view:clear```
```php artisan config:clear```
```chown -R www-data:www-data *```
```php artisan queue:restart```
```php artisan up```
Check IP or domain and it should be fixed.

**Comment by DaneEveritt** [comment]
This is not a bug, you did not configure your webserver correctly and therefore it is throwing back content with a 200 response code rather than a 404 error.

**Comment by INfoUpgraders** [comment]
I didn't configure it wrong, I put `domain.tld` there to redact my personal domain. I literally listed a fix that worked for me that had nothing to do with messing with the webserver @DaneEveritt

**Comment by DaneEveritt** [comment]
Again, this is not a bug with the software, your "fix" worked because you effectively re-installed the software by properly following the documentation.

**Comment by INfoUpgraders** [comment]
And why did I reinstall the panel? 🤡

**Comment by DaneEveritt** [comment]
This is going no where productive so I'm locking this issue.
