### ISSUE TITLE
% sign in folder name causes white screen of death

### ISSUE THREAD

**Issue by alliraine** [pterodactyl/panel#2575]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.1/1.0.0
* Server's OS: Debain 10
* Your Computer's OS & Browser: Windows 10 Firefox

**Describe the bug**
When there is a folder that contains a % sign and you try to go into the folder you get a white screen.

**To Reproduce**
1. Create a folder with a % in its name.
2. Click on the folder

**Expected behavior**
It should have an escape character for the % sign to allow it load in the browser. If no one else gets around to it before I get to it I will make a PR for the fix.

**Comment by Hydra2k** [comment]
i got this bug; ubuntu 20.04 without even clicking on the folder

**Comment by DaneEveritt** [comment]
Just crashed the file manager UI by attempting to create a directory (using the create dir button) that included a `%` in the name. Immediate white screen when the `%` character is entered.
