### ISSUE TITLE
Button to restore the backup

### ISSUE THREAD

**Issue by DrakMC** [pterodactyl/panel#2579]
**Describe the solution you'd like**
I would like to have a backup restore button for the server. The user wouldn't have to download the backup and then upload it to the server again.

This is what it might look like:
![image](https://user-images.githubusercontent.com/40771376/96987018-b84c1f80-1522-11eb-94a2-3a12b04e6700.png)

**Comment by FoksVHox** [comment]
Dupe of #2016?

**Comment by DrakMC** [comment]
I'm sorry, I didn't notice. Yes, it's a dupe of #2016.

**Comment by FoksVHox** [comment]
@DrakMC Close the issue if its a dupe.
