### ISSUE TITLE
Scheduled tasks not being triggered by artisan schedule:run

### ISSUE THREAD

**Issue by Aaronstar-McClure** [Pterodactyl/Panel#258]
i have two schedualed tasks set up and neither of them are being run, both are active, but the next time they are to be run is 12 hours ago, this is the second time it happened and i already re configured them once.
![untitled](https://cloud.githubusercontent.com/assets/24755349/22151622/cfeeb76c-deec-11e6-8eeb-45edcf819584.png)

**Comment by schrej** [comment]
Did you setup all of this correctly?
https://docs.pterodactyl.io/docs/queue-listeners

**Comment by Aaronstar-McClure** [comment]
just noticed a system mail, something killed the chrontab process

**Comment by Aaronstar-McClure** [comment]
`Subject: Cron <root@*server name*> php /var/www/pterodactyl/html/artisan schedule:run >> /dev/null 2>&1
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
Message-Id: <20170119015819.DD618101171@*server name*.*host company*.net>
Date: Thu, 19 Jan 2017 02:58:19 +0100 (CET)

/bin/sh: line 1:  8816 Killed                  php /var/www/pterodactyl/html/artisan schedule:run >> /dev/null 2>&1`

**Comment by DaneEveritt** [comment]
Restarting cron should address the issue. Theres not really anything bug wise going on in your reply there that I can see.

**Comment by Aaronstar-McClure** [comment]
but it happened about three times according to my mail, and how do i restart chrontabs?

**Comment by DaneEveritt** [comment]
`service cron restart` should get it. Depends on the OS though, check Google.

**Comment by Aaronstar-McClure** [comment]
still is not working and now im not getting mail about it breaking

**Comment by tenten8401** [comment]
I'm with @Aaronstar-McClure (friend of his) and after doing some investigating I'm noticing the following problems... 
![image](https://cloud.githubusercontent.com/assets/6174343/22175657/641bdb24-dfc7-11e6-8dd0-817e6042ef40.png)

Every time variable is set to *, and artisian claims there are no scheduled tasks to be run.

**Comment by tenten8401** [comment]
@DaneEveritt

Here's what his scheduled task looks like:
![image](https://cloud.githubusercontent.com/assets/6174343/22175676/d38e2818-dfc7-11e6-9200-022c333ec8f7.png)

**Comment by tenten8401** [comment]
The task does not seem to be running at all even when first scheduled.

**Comment by DaneEveritt** [comment]
So the way this works means there could be a few issues at play. To begin, that crontab is calling Laravel's event scheduler which is seeing what we need to do. Now, Pterodactyl is setup to run `php artisan pterodactyl:tasks` every minute by default as seen in [`Kernel.php](https://github.com/Pterodactyl/Panel/blob/develop/app/Console/Kernel.php#L37).

That command then runs a query to determine which tasks in the database are now due to be run again, which is done in [`RunTasks.php`](https://github.com/Pterodactyl/Panel/blob/develop/app/Console/Commands/RunTasks.php#L75). This puts the task into the queue system, which will generally be run almost immediately afterwards, depending on the number of queued tasks currently there.

It is possible that the cronjob is running correctly, but your queue handler is configured wrong, and not running. You can check both the `jobs` and `failed_jobs` table, as well as checking the Pterodactyl Panel logs in `storage/logs` to try and see where this is going wrong.

**Comment by tenten8401** [comment]
So, in theory, this should be queued to run right:
![image](https://cloud.githubusercontent.com/assets/6174343/22176735/a8a2e820-dfde-11e6-8413-b9d5160d62eb.png)

Nope.
![image](https://cloud.githubusercontent.com/assets/6174343/22176727/92250bbe-dfde-11e6-9aab-d7d8af918de6.png)

But wait!
![image](https://cloud.githubusercontent.com/assets/6174343/22176732/a02806bc-dfde-11e6-97a8-6206d1067cbd.png)

**Comment by DaneEveritt** [comment]
I've been unable to replicate this, as have many users as no one else has ever reported this. Going to close it and assume it was some server specific fluke.

**Comment by ShadowKitten** [comment]
Bump! Able to replicate.

**Comment by GhotiMayo** [comment]
Last week, I had upgraded from v0.6.2 of the panel to the latest version on Ubuntu 16.04. This broke my scheduler as the version I was running was still using Supervisor. I switched over to the newer pteroq service instead, but the I could not get the panel's scheduler to do anything. I have tried everything from re-entering all the scheduled commands to flat-out rebooting the machine. Cron appears to be running normally, and the panel sends emails just fine too. I check the logs and failed_jobs and cannot find any useful/relevant information. Running php artisan schedule:run runs all of the scheduled commands once. A support team member looked into my problem and could not figure out what is going wrong, so I am thinking I am experiencing a bug.

**Comment by GhotiMayo** [comment]
So I reinstalled the panel and reconnected it to my databases. I also ran php artisan pterodactyl:tasks which changed "Queued" from no to yes, but still did not make a difference with the scheduler running tasks. However, php artisan schedule:run no longer runs the tasks once.

**Comment by DaneEveritt** [comment]
I know this is still affecting some individuals on the current release, but I am closing this because of the significant changes to the system in the next release that might resolve these issues. We can create a new issue if this occurs once `0.7.0` is released.

**Comment by Yertled** [comment]
I have the same issue as the people above. Tasks don't run, and I won't have to explain it again because it's perfectly explained above. It's identic.

**Comment by DaneEveritt** [comment]
@Yertled tasks have been completely rewritten in 0.7 so I'm waiting to see if this crops back up once we have that release out. Hopefully it does not.

**Comment by ProJaCore** [comment]
Schedules still not working for me or some friends

**Comment by schrej** [comment]
@ProJaCore Some more detailed info would be nice. Panel version? Is the service and the cronjob setup correctly?

**Comment by ProJaCore** [comment]
Panel: 0ec5a4e
Daemon: 77df1eb
