### ISSUE TITLE
Server marked as "starting" instead of "running" when using BIND

### ISSUE THREAD

**Issue by Dr3Ame3r** [pterodactyl/panel#2580]
**Background (please complete the following information):**
* Panel or Daemon: Panel i think, could be daemon that's doing it
* Version of Panel/Daemon: 1.0.2/1.0.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chrome/Firefox/EDGE/Opera/Brave 

**Describe the bug**
If you're using SA-MP  Egg to run a san andreas server, the panel will mark your server as "starting" IF you use BIND to make it listen to specific IP(your container ip to be precise), but, there is a BUT, if you restart the daemon, it marks it as started

Linux v: Linux games2 5.5.0-18.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.5-22.1~buster (2020-04-18) x86_64 GNU/Linux

Docker info:
https://paste.gg/p/anonymous/c8d6f13f14e34e368342d4365bf8e26e

So, the issue is this:
`
1. Open server.cfg

2. add 
bind ip.ip.ip.ip

3. restart the server, you will have it marked as "starting" now.
4. systemctl wings restart ( to mark it as running)
`
**Expected behavior**
Mark it as running without restarting wings

**Comment by parkervcp** [comment]
The thing here is that the ip for the container changes regularly and cannot be guaranteed.

The sever should listen to 0.0.0.0 as it's the best way to guarantee it will listen.

**Comment by Dr3Ame3r** [comment]
Yes, but if i don't place that BIND in the server.cfg, it will not start at all.. 

I am using HOST setup! So the ip doesn't change at all 

Without BIND, serverinfo looks like this 
http://prntscr.com/v586zf
instead of
http://prntscr.com/v587hy

**Comment by parkervcp** [comment]
This sounds a lot like an egg issue and not the panel.

You should take this to my eggs repo... Seeing as this is not an egg integrated into the panel by default

**Comment by Dr3Ame3r** [comment]
Ok, i am closing this issue and opening an EGG issue, thanks
