### ISSUE TITLE
Servers owned filtering doesn't work

### ISSUE THREAD

**Issue by LukasW1337** [pterodactyl/panel#2581]
**Background (please complete the following information):**
* Panel or Daemon:  Panel
* Version of Panel/Daemon: 1.0.1
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
Clicking Servers owned number doesn't show the users owned server.

**To Reproduce**
1. Go to /admin/users
2. Click on the number under Servers Owned for a user

**Expected behavior**
Only showing that one users owned servers.

**Comment by grzegorzkibitz** [comment]
Bump!

I reproduced this easily. it just lists all servers instead of filtering
