### ISSUE TITLE
Cannot add or modify Subusers of any server

### ISSUE THREAD

**Issue by gavidroselj** [pterodactyl/panel#2583]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel: 1.0.2, Daemon: 1.0.1
* Server's OS: Ubuntu 20.04.1
* Your Computer's OS & Browser: Windows 10, Google Chrome (Also tested Microsoft Edge)

**Describe the bug**
I am unable to add or edit sub-users on any of the servers I own.

Panel: `php -v` (the php version in use): PHP 7.4.11

**To Reproduce**
1. Select any server
2. Open "Users" tab
3. Click "New User"
4. Input any email and any permissions
5. Click "Invite User"
6. Nothing happens

1. Select any server which already has a subuser
2. Open "Users" tab
3. Edit any subuser
4. Change or don't change anything
5. Click save
6. Nothing happens

**Expected behavior**
User is sucessfully added / edited

**Comment by ItzKai** [comment]
Also got this error on 2 different panels that I updated. Before updating editing and creating subusers worked fine. After doesn't but everything else works fine.

**Comment by brandan-schmitz** [comment]
I can confirm the issue is happening for me as well. Looking at the console in FIrefox and Google Chrome, when you click the **Invite User** button there is not even an event that fires off in the browser or any indication that it was pressed. Additionally there are no errors being produced in the /var/www/pterodactyl/storage/logs/ folder for this. I currently am registering no errors at all for pterodactyl in that directory. Looking at my NGINX access logs it loads the page for it fine but then nothing else occurs.

My system is configured identical to the setup @CommandStorm5 described, only difference is I am using a macOS computer instead of Windows. I also tried it on Firefox, Google Chrome, and Safari.

**Comment by Malachiel87** [comment]
I confirm the issue, using panel 1.0.1 it work again, also weid stuff like pressing k on console will open server search 
Ubuntu 18
Php 7.4

**Comment by YTRemRem** [comment]
I am using CentOS 8 and php7.4 having same issues

**Comment by tywin1104** [comment]
I am also experiencing the same on Ubuntu 18 and PHP 7.4.11.  I believe I setup the smtp correctly and I can receive email sending from creating admin user inside the admin panel. However clicking the invite user doesn't seem to trigger anything - seems the button is not working in my opinion

**Comment by alliraine** [comment]
Can confirm we had this issue as well. To fix it I had to move the <Form></Form> tags from EditSubuserModal.tsx 260 and 262 to 154 and 215.

**Comment by tywin1104** [comment]
> EditSubuserModal

Thank you! Could you elaborate on how to actually change this with the existing setup? since the code is part of the panel could I just go to the code files and manually change that?

**Comment by ghost** [comment]
Confirm. Ubuntu 20.04 LTS, php 7.4
Client: MacOS 10.15.7, Safari 14.0

**Comment by JordanDIG** [comment]
> 
> 
> Can confirm we had this issue as well. To fix it I had to move the
> tags from EditSubuserModal.tsx 260 and 262 to 154 and 215.

I don't understand what needs to be changed in the file, can you please explain more clearly? (I don't understand what "tags" you are talking about)

**Comment by pilot22** [comment]
Confirm. Ubuntu 18.04, php 7.4.

**Comment by ghost** [comment]
> > Can confirm we had this issue as well. To fix it I had to move the
> > tags from EditSubuserModal.tsx 260 and 262 to 154 and 215.
> 
> I don't understand what needs to be changed in the file, can you please explain more clearly? (I don't understand what "tags" you are talking about)

Same!

**Comment by pilot22** [comment]
@frenchbones @jojoponey The tags are `<Form> and </form>` But you can't place it at line 154. The fix isn't clearly explained and I can't make it. If someone succeed, please send more precise information here

**Comment by dfcgaming** [comment]
having the same issue at this time.
Ubuntu 18.04.05
PHP: 7.4.11

**Comment by dfcgaming** [comment]
Having the same issue.
i updated the panel manually with the new commit and cleared all caches but no luck.
the "invite user" button is stil unusable
