### ISSUE TITLE
Add a button to copy connection details to clipboard

### ISSUE THREAD

**Issue by robingroppe** [pterodactyl/panel#2585]
**Is your feature request related to a problem? Please describe.**

In the 0.7 series it was easy to quickly copy the IP or alias+port from the main page.
However in the 1.0 series its not anymore. 

**Describe the solution you'd like**

I would suggest a little clipboard icon next to the connection details on the main page to "click them to clipboard" as a solution.

**Comment by wardpieters** [comment]
Please use the feature request template: https://github.com/pterodactyl/panel/issues/new?template=---feature-request.md

**Comment by robingroppe** [comment]
updated
