### ISSUE TITLE
Problems with Packages

### ISSUE THREAD

**Issue by johnacek** [pterodactyl/panel#2586]
Hello, I got Pterodactyl on my VPS and I have an "issue". I set up the pterodactyl discord.js egg and I got errors from some NPM packages, e.g quick.db and Canvas. Can you help me? I get the error when i try to start the bot, but from PuTTy client started bot normally. Thanks for your help

Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.1
* Server's OS: Ubuntu 20.04 x86_64
* Your Computer's OS & Browser: Windows 10

**Comment by parkervcp** [comment]
This is not a panel issue but an egg issue.

Please take any issues you have to the eggs-and-games channel in discord first.
