### ISSUE TITLE
Default vanilla minecraft egg won't install curl

### ISSUE THREAD

**Issue by alkanex-xyz** [pterodactyl/panel#2591]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v1.0.2
* Server's OS: Debian9
* Your Computer's OS & Browser: WIn10 && Chrome

**Describe the bug**
the default Vanilla EGG won't install with following log, because curl isn't selected to install:
https://pastebin.com/1WQmzzc0

**To Reproduce**
1. Create a new server with minecraft vanilla
2. Watch the installation
3. Try to start the server after installation

**Expected behavior**
Successful installation of vanilla minecraft

**Steps to repair the script**
1. Edit Vanilla Egg installation script
2.  Write curl after jq in line 6
3. successful installation

**Comment by parkervcp** [comment]
It's a known issue and I have a pr on to fix it already.

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/panel/pull/2587
