### ISSUE TITLE
Different timezones cause schedules to fire every minute

### ISSUE THREAD

**Issue by alliraine** [pterodactyl/panel#2596]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.2
* Server's OS: Debian 10.5
* Your Computer's OS & Browser: Windows 10 Firefox

**Describe the bug**
When the timezone on the MySQL database is different from the App timezone it runs schedules every minute.

**To Reproduce**
1. Set App timezone to something other than the MySQL database timezone.
2. Create a schedule to run every 5 minutes.
3. Watch it run every minute instead.

**Expected behavior**
The timezone of the MySQL database should be set on connection to the same time as defined in the .env file.

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/panel/commit/8c6327fd3253e009f86313695a57469728fd7807 and https://github.com/pterodactyl/panel/commit/996fb5b46f6ebaa9e38d58d3aeeb2feae654e814
