### ISSUE TITLE
Spaces lines console

### ISSUE THREAD

**Issue by Malachiel87** [pterodactyl/panel#2597]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 
* Server's OS: Ubuntu 18
* Your Computer's OS & Browser: 

**Describe the bug**
![image](https://user-images.githubusercontent.com/3611852/97117663-7c24e480-1705-11eb-8fdb-e55de1de63dc.png)
After the daemon update from 1.0.0 to 1.0.1 i started to see these empy space behind lines on all console in some occasions, on 1.0.0 it worked fines

**To Reproduce**
1. open any console
2. Wait some times, it will show space behind lines

**Expected behavior**
It should not create spaces

**Comment by DaneEveritt** [comment]
This is an issue with the specific game you're running, which is not included here, and therefore I cannot reproduce this issue.

**Comment by Malachiel87** [comment]
sure? this happened after the daemon update

**Comment by DaneEveritt** [comment]
Again, without more specific information I cannot reproduce this issue and will not spend time looking into it.

**Comment by parkervcp** [comment]
This is a java bug. it crops up from time to time and it's why we have the jline flag set.

**Comment by Malachiel87** [comment]
but why it don't happen with 1.0.0 daemon version and only with 1.0.1?

**Comment by Malachiel87** [comment]
right now i tried to downgrade wings to 1.0.0 and spaces issue is gone

**Comment by DaneEveritt** [comment]
Because I changed how console lines are parsed to work in other scenarios that aren't as easily controlled.

You've still not told me what specific game/egg this is, or what startup command you're using. Did you try just setting a jline flag and seeing if that fixes it?

**Comment by Malachiel87** [comment]
is minecraft egg paper one, 
My startup is java -Xmx5120M -Duser.timezone=Europe/Rome -jar paperspigot.jar
sorry for missed such information

**Comment by DaneEveritt** [comment]
What happens when you add `-Dterminal.jline=false` to the startup args?

**Comment by Malachiel87** [comment]
it seem to work with that flag

**Comment by DaneEveritt** [comment]
Cool, we ship that by default now in the startup.
