### ISSUE TITLE
Paper Egg doesn't recognize MC version

### ISSUE THREAD

**Issue by alkanex-xyz** [pterodactyl/panel#2598]
as already written in #2587 : 

the Paper installscript has also a failure:
https://pastebin.com/ju1cPdsS

jq won't find Paper 1.16.1, trough ist available: https://papermc.io/api/v1/paper

The paper egg from @parkervcp works fine and installs 1.16.1

**Comment by parkervcp** [comment]
I am checking this now.

**Comment by parkervcp** [comment]
This is a jq error apparently.

**Comment by Malachiel87** [comment]
i got a more simple script where you type the version and it download that release


[egg-paper-spigot.zip](https://github.com/pterodactyl/panel/files/5435938/egg-paper-spigot.zip)

**Comment by alkanex-xyz** [comment]
The idea is not bad to check if the choosen Version is valid and to be able to choos ab build number.
I replaced the egg by parkervcps which works fine

**Comment by parkervcp** [comment]
I am using their api to get the list of versions they support.

I have fixed the issue and am making a PR now
