### ISSUE TITLE
S3 backups cannot upload files larger than 5GB

### ISSUE THREAD

**Issue by alliraine** [pterodactyl/panel#2599]
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.0.1
* Server's OS: Debian 10.5
* Your Computer's OS & Browser: Windows 10 Firefox

**Describe the bug**
When creating a backup larger than 5GB upload fails to S3. This is due to limitations in s3 put requests via http.
**To Reproduce**
1. Configure s3 storage option on panel
2. Create backup of service that is over 5GB
3. Watch it crash and burn.

**Expected behavior**
Wings needs to use either MultiPart uploads via HTTP or use AWS SDK for Go.

MultiPart Upload Information:
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRESTAPImpUpload.html

Go API:
https://docs.aws.amazon.com/sdk-for-go/api/

**Comment by matthewpi** [comment]
Seems like we are going to need to presign a lot of URLs for this one 🙃
