### ISSUE TITLE
Schedules not running

### ISSUE THREAD

**Issue by FunixG** [pterodactyl/panel#2601]
**Background :**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel -> 1.0.2 & Daemon 1.0.1
* Server's OS: Debian 10 4go ram
* Your Computer's OS & Browser: Windows10 Chrome

Hello ! I have issues using pterodactyl schedules, only some of them are running but not all of them. The schedules was working on version 0.7. 

This is what i have tried :
Setup a schedule executed every minute who types in console the command tps for my minecraft server but the command is not triggered.

**Comment by DaneEveritt** [comment]
Update to 1.0.2

**Comment by FunixG** [comment]
I am alerady at the version 1.0.2 the problem is not the version my panel and wings are up to date

**Comment by Sikatsu** [comment]
I experience the same issue on 1.0.2, the "last run" date only updates when I click on "Run now", and if I don't use that button, the schedule will not run at all.

**Comment by DaneEveritt** [comment]
Check your Panel and Wings logs, as well as the contents of the `failed_jobs` table.

**Comment by Sikatsu** [comment]
This is one error that occurs: https://paste.gg/p/anonymous/7cc1abecbc51456da7e5273933a56c3f

**Comment by Sikatsu** [comment]
I just let the system admin check the logs and contents of the failed_jobs table, but there was nothing regarding this matter.

The last run date is from when the panel was still on 0.7, ever since it doesn't work unless I click the ''Run now'' button introduced in 1.0.2. Updated to 1.0.3 as well, but no luck. I tried setting up a test schedule every minute, but unless I click run now it never runs.

![image](https://user-images.githubusercontent.com/5664135/97164620-b54f6a00-1782-11eb-9689-b7b74855ad2d.png)

**Comment by MasterLuke117** [comment]
I'm having the same issue even on 1.0.3, except no schedules are running for me,  the error log shows this every minute: https://hatebin.com/cbazivpavp

```
[2020-10-24 06:34:01] production.ERROR: Pterodactyl\Exceptions\Model\DataValidationException: Data integrity exception encountered while performing database write operation. {"name":["The name field is required."]} in /var/www/pterodactyl/app/Models/Model.php:60
```

**Comment by DaneEveritt** [comment]
@Sikatsu  do you have the crontab setup properly and it's it running? Have you restarted pteroq?

**Comment by Sikatsu** [comment]
@DaneEveritt Crontab is running and pteroq is restarted. 

It does seem to process something (my knowledge doesn't go to far with this) https://pastebin.com/658qiWqs

**Comment by DaneEveritt** [comment]
Lets move this to https://github.com/pterodactyl/panel/issues/2609 I can't keep up with all of these.
