### ISSUE TITLE
TS3 Egg

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#2602]
You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: 1.0.2
* Version of Panel/Daemon: 1.0.2
* Server's OS: ubuntu 18.04
* Your Computer's OS & Browser: Microsoft edge, windows 

**Describe the bug**
TS3 server is not working anymore.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'admin panel, in nests'
2. Click on 'create server'
3. create a server with the TS3 egg.

**Expected behaviour**
It installs the TS3 server.

**Comment by ClumsyAdmin** [comment]
I believe this fixes it, just needs to be merged https://github.com/pterodactyl/panel/pull/2600

**Comment by ghost** [comment]
ah alright, didn't see that lol
