### ISSUE TITLE
Schedules Status Locked

### ISSUE THREAD

**Issue by JordanDIG** [pterodactyl/panel#2605]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel v1.0.3 and Deamon 1.0.0
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10, Firefox

**Describe the bug**
When scheduling a backup when the backup limit is reached the job remains blocked with the status "Processing" it does not go to Inactive.

**To Reproduce**
1. Reach the limit of backups
2. Go to 'schedules'
3. Create a schedules
4. Add him the task to create a backup
5. The task executes no error but the status remains locked on processing.

**Comment by Dieudetous** [comment]
u noob

**Comment by edbrk** [comment]
I receive a similar error when doing anything. It gets stuck on Processing forever, unless you refresh the page.

**Comment by DaneEveritt** [comment]
Please respond if this is still happening, otherwise I will assume it was fixed in one of the many releases since this was opened.
