### ISSUE TITLE
Pressing "k" key on console page will open search server

### ISSUE THREAD

**Issue by Malachiel87** [pterodactyl/panel#2607]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon:  1.0.3
* Server's OS:  Ubuntu 18
* Your Computer's OS & Browser:  Windows 10 and Chrome

**Describe the bug**
Pressing K on console page will open search server function, not sure if is a new function or a bug

**To Reproduce**
Go to any console server and press K

**Expected behavior**
It should don't do that?

**Comment by dfcgaming** [comment]
It should it is a keybind for quick search. if you press the terminal input field and you press k it wouldn't do this.
so this ain't a bug.
