### ISSUE TITLE
[wings] Bind source path does not exist...

### ISSUE THREAD

**Issue by Atm85** [pterodactyl/panel#2612]
**Background (please complete the following information):**

* Panel or Daemon:  Daemon

* Version of Panel/Daemon: v1.0.1

* Server's OS: Ubuntu 18.04 GNU/Linux

**Describe the issue**
Whenever i try to create a new server, I get an error in the wings console:
```
ERROR: [Oct 26 13:41:52.257] failed to create server environment during install process error=Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /var/lib/pterodactyl/volumes/73347980-e2fe-49af-90a8-096be0625f75 server=73347980-e2fe-49af-90a8-096be0625f75

Stacktrace:
github.com/pterodactyl/wings/environment/docker.(*Environment).Create
        /usr/local/bin/wings/environment/docker/container.go:223
github.com/pterodactyl/wings/server.(*Server).CreateEnvironment
        /usr/local/bin/wings/server/server.go:177
github.com/pterodactyl/wings/router.postCreateServer.func1
        /usr/local/bin/wings/router/router_system.go:60
runtime.goexit
        /snap/go/6637/src/runtime/asm_386.s:1333
```
I own the physical machine im trying to run wings on, and it is an old 32-bit machine  <2010. I just wanted to repurpose it rather than let it collect dust in storage.

I'm not an expert at reading stacktraces, but it seems to be an issue with docker?

`uname -a` reports:
```
Linux ubuntu 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:02:56 UTC 2020 i686 i686 i686 GNU/Linux
```
and `docker --version` reports:
```
Docker version 19.03.11, build dd360c7
```

**Comment by DaneEveritt** [comment]
Does `/var/lib/pterodactyl/volumes` exist, or is it a symlink to somewhere else? People have reported this in the past and fixed it by just re-installing docker entirely.

**Comment by Atm85** [comment]
> Does `/var/lib/pterodactyl/volumes` exist

Yes, `/var/lib/pterodactyl/volumes`  does exist

And im not sure what you mean by it being a symlink to somewhere else?

**Comment by ClumsyAdmin** [comment]
Just for the record, have seen like 5 or so people come into the #help channel in discord with this issue in the past week or so. Never knew how to fix it.

**Comment by Atm85** [comment]
Does it matter that I installed docker using `snap install docker` instead of following the installation guide on pterodactly?

**Comment by DaneEveritt** [comment]
I have no idea. I've never seen this issue on my own environments, and I've seen it come up in the past and the only thing that seemed to solve it for people was re-installing Docker. This error doesn't really seem to be something caused by Pterodactyl.

**Comment by parkervcp** [comment]
I guarantee that the snap version of docker is causing issues.

It may not be the exact cause but I have seen it cause issues with binds before as well.

**Comment by Syntax3rror404** [comment]
I have this problem to with the newest docker version after upgrading from 0.7
