### ISSUE TITLE
Suspended label doesn't show until node is unreachable

### ISSUE THREAD

**Issue by Rhydium** [pterodactyl/panel#2613]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.3
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 & Google Chrome

**Describe the bug**
When suspending a server it should show "Suspended" in the server list in the same way it also shows "Connection error" when the node that the server is on is unreachable, but it doesn't. Instead the "Suspended" label only shows when the node that the suspended server is on is unreachable. (this may be the same issue as #2565 but I think this is worth a seperate issue)

**To Reproduce**
1. Suspend a server
2. Go to the server overview (not the admin view) and see
3. Shut wings down on the node of the suspended server
4. Now you do see the "Suspended" message as it should do

**Expected behavior**
It should show the "Suspended" label instead of the server statistics.

**Comment by ClumsyAdmin** [comment]
Was able to reproduce, same issue here. From client view it just shows server info instead of "Suspended" which only shows from client view when wings is offline. Admin panel shows that the server is suspended just fine.

**Comment by DaneEveritt** [comment]
Caused by https://github.com/pterodactyl/panel/issues/2279
