### ISSUE TITLE
Unable to access the server console from the panel

### ISSUE THREAD

**Issue by MegaNoam** [pterodactyl/panel#2614]
Panel or Daemon: Panel
Version of Panel/Daemon: 1.0.1
Server's OS: Ubuntu 18.04.5 LTS
Your Computer's OS & Browser: Chrome
Describe the bug
Panel: I'm unable to access the server console from the panel

To Reproduce
I can not access the console, I can only access the files

Every time I look at the console I have the following error:
`WebSocket connection to 'ws://**Censored-IP**:8080/api/servers/fe055362-901c-41f6-a0a9-459c3fa86a91/ws' failed: Error during WebSocket handshake: Unexpected response code: 403`

wings output logs
https://ptero.co/zequbocace.sql

![image](https://user-images.githubusercontent.com/18356302/97239159-a785fd00-17f3-11eb-9a06-66e1dc3b8bec.png)

**Comment by DaneEveritt** [comment]
Please check the wings error log, this is not a software bug as you're likely just passing an expired JWT from the Panel or your node is using a completely different authentication token.

So:
* Check that the server time is not out-of-sync between the Panel and Wings instances.
* Check that the node configuration is properly copied over to Wings.
* Check the wings error logs and see whats being reported.
