### ISSUE TITLE
Graphs Display | 0.7.x -> 1.x.x Transition

### ISSUE THREAD

**Issue by mechite** [pterodactyl/panel#2616]
**Is your feature request related to a problem? Please describe.**
Back on the old 0.7.x panel, it used to display CPU / RAM % when you hovered over a graph, showing the value of it.
**Describe the solution you'd like**
Just bringing back the feature / reasoning for the lack of it.
**Additional context**
![image](https://user-images.githubusercontent.com/50027352/97244290-2711cd00-17f0-11eb-9130-2fd87defcffd.png)

**Comment by mechite** [comment]
This issue is caused by the shift in graph packages, makes sense to me why it happens. Not many people use graphs but it would be good for accessibility imo

**Comment by notAreYouScared** [comment]
So are you asking for data-points? I don't have a 0.7 install to reference it.

**Comment by grzegorzkibitz** [comment]
This would be a cool thing to be added back. i used to do many benchmarks and those graphs were very helpful getting the exact ram/cpu usgae.

**Comment by DaneEveritt** [comment]
![Screen Capture on 2020-11-01 at 13-29-36](https://user-images.githubusercontent.com/418376/97815962-b67f0c00-1c46-11eb-967c-a880a27b3411.gif)

This is hilariously unusable given how fast data moves (even with huge target areas), I'm not going to add this in, sorry.

**Comment by mechite** [comment]
What I would like (and would make it better) is an animation for sliding that box when you hover between locations so it's genuinely usable, and possibly Graph Scrolling if you're able to add that? Saving the past 5 seconds of usage data to the panel
