### ISSUE TITLE
Add button to scroll to bottom of console when scrolled up and new lines come in

### ISSUE THREAD

**Issue by mechite** [pterodactyl/panel#2617]
**Is your feature request related to a problem? Please describe.**
Transitioning from 0.7.x to 1.x.x, I miss the notification button where if a new line is outputted to console, there would be a button to jump back down to it.

**Describe the solution you'd like**
Add the notification button again.

**Describe alternatives you've considered**
Alternatives would be to have it automatically jump, although this would break accessibility for reading previous logs.
 
**Additional context**
![image](https://user-images.githubusercontent.com/50027352/97245021-ffbbff80-17f1-11eb-82f2-040ac19a2d24.png)

**Comment by mechite** [comment]
Also want to expand, the scrolling on the console window has no animation on PC, and scrolls per line on mobile. 

Top navbar has a scrollbar on mobile too, maybe hide overflow there too

**Comment by notAreYouScared** [comment]
Due to the recent update to Xterm.js v4.9.0 the only notification option is sound.

**Comment by mechite** [comment]
Honestly the only use I had for this is quick scrolling to the bottom, is it not possible to just add a down arrow that takes you to the bottom of terminal?

**Comment by mechite** [comment]
> Due to the recent update to Xterm.js v4.9.0 the only notification option is sound.

If a down button isn't possible could you not have soft/hard scrolling instead? Soft scrolling just ignoring new lines and hard scrolling jumping you down.

If you're unable to jump down, then how about a blue outline/glow around the console window when there are new notifications (togglable)

**Comment by schrej** [comment]
This was a custom addition to xterm before, and it can be one again.
