### ISSUE TITLE
CPU usage readability

### ISSUE THREAD

**Issue by VibeGAMESNL** [pterodactyl/panel#2619]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.3
* Server's OS: Ubuntu 20.03
* Your Computer's OS & Browser: Chrome

**Describe the bug**
The CPU usage can be higher then 100%. I understand that 1 core = 100% and 2 cores are 200% but customers don't understand this.

I understand that this isn't really a bug but more like a change request.

![image](https://user-images.githubusercontent.com/66668585/97324821-916b5180-1872-11eb-9d8e-b66ef5872474.png)

**To Reproduce**
Create a load that will use more then 1 core.

**Expected behavior**
CPU usage should be devided by the number of cores I gues? So it will be better readable for a customer.

**Comment by parkervcp** [comment]
100% == 1 core is a linux standard. It's not really something we control. This was like this in 0.7 as well. This isn't a new thing to 1.0.

**Comment by VibeGAMESNL** [comment]
> 100% == 1 core is a linux standard. It's not really something we control. This was like this in 0.7 as well. This isn't a new thing to 1.0.

Yes it's a linux standard but not everybody knows this. A maximum of 100% is better to understand for most people.
I understand if you don't want to change this. Just a suggestion.

**Comment by DaneEveritt** [comment]
I won't be changing this, we've previously capped things at 100% and it just caused even more confusion to people, and was not intuitive in the long run.

**Comment by schrej** [comment]
How about adding a `/ x00%` so it's clear what the limit is?

Edit regarding the marking as spam: If you like an idea, like the comment. Anything that's basically a `+1` (which includes "awesome idea") without providing extra content, e.g. an good argument why it's a good solution, is considered spam on GitHub.

**Comment by VibeGAMESNL** [comment]
> How about adding a `/ x00%` so it's clear what the limit is?

Awesome idea? @DaneEveritt 👍:D
