### ISSUE TITLE
Wings cannot edit files with "+" in their name

### ISSUE THREAD

**Issue by Jake-Moore** [pterodactyl/panel#2620]
**Background (please complete the following information):**
* Panel or Daemon: Panel (Wings)
* Version of Panel/Daemon: v1.0.3 Panel
* Server's OS: Ubuntu 18.04 LTS
* Your Computer's OS & Browser: Windows 10 Pro, Chrome

**Describe the bug**
Panel: PHP 7.4.11
Description: When editing a file using the Wings website, file names with + cannot be edited, the following error is displayed:
https://i.imgur.com/P3PsYjW.png
Discovered when trying to edit a spigot plugin config for Pass+, named "pass+.yml"
Tested by creating a file named test+.yml, same error

**To Reproduce**
1. Use version 1, panel version 1.0.3
2. In Wings, in a server's file manager, create a file with any contents with the name "test+.yml"
3. The error will immediately show up when you attempt to create the file. 
Furthermore, existing files display the error when you try to edit them using Wings.

**Expected behavior**
The file cannot be edited and the following error is displayed:
https://i.imgur.com/P3PsYjW.png

F12 console shows this if it helps:
https://i.imgur.com/eVzWgrn.png

**Comment by notAreYouScared** [comment]
Might be related to #2399

**Comment by josephverburg** [comment]
My guess would be that the  "+" is not being url encoded and/or decoded correctly.
