### ISSUE TITLE
WebSocket issue in panel

### ISSUE THREAD

**Issue by decodef** [pterodactyl/panel#2621]
**Background (please complete the following information):**
* Panel or Daemon: Panel & Daemon
* Version of Panel/Daemon: Panel is 1.0.3, Daemon is 1.0.1
* Server's OS: Ubuntu 20.04.1 LTS
* Your Computer's OS & Browser: Windows 10 & Microsoft Edge

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Hello everyone, I tried to get help at pterodactyl discord server, but nobody can help me, thats why I'm here. So, I have issue with WebSocket and server. Everything was fine and the panel & server was working until now, I tried to open the server console, but an error popped up. I check the console, and it says that the ws is closed or closing, error 403. Like, the server is fully dead, file manager doesn't work, sftp doesn't work and etc. Btw the egg is discord.py. I tried to make new server, but the problem is same. Restart nginx, wings doesn't help. Logs of wings debug:
`ERROR: [Oct 28 19:53:14.134] encountered HTTP/500 error while handling request error=websocket: request origin not allowed by Upgrader.CheckOrigin error_id=44bf9f4c-d361-4aa6-b89d-30d6b82f8693 server=bc8ea49f-d9a9-46c3-925a-d44ec209a78e
Stacktrace:
github.com/apex/log.(*Entry).Error
        /home/runner/go/pkg/mod/github.com/apex/log@v1.8.0/entry.go:96
github.com/pterodactyl/wings/router.(*RequestError).AbortWithStatus
        /home/runner/work/wings/wings/router/error.go:76
github.com/pterodactyl/wings/router.(*RequestError).AbortWithServerError
        /home/runner/work/wings/wings/router/error.go:97
github.com/pterodactyl/wings/router.getServerWebsocket
        /home/runner/work/wings/wings/router/router_server_ws.go:17
github.com/gin-gonic/gin.(*Context).Next
        /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161`
Panel logs:
`http://bin.ptdl.co/jdre7`
Panel: `PHP 7.4.3 (cli)` (the php version in use).
Daemon: `
Linux ubuntu-2gb-hel1-3 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2                 020 x86_64 x86_64 x86_64 GNU/Linux
` and `https://hastebin.com/wiyuzivafe.yaml` (kernel version and information regarding docker)

**To Reproduce**
1. Create egg discord.py by parkervcp and server with it.
2. Try to launch it?

**Expected behavior**
The server to run and work.
 - Best regards, Decodef.

**Comment by Thiritin** [comment]
Hi @decodef thank you for reporting an issue.

Please check your `/etc/pterodactyl/config.yml` if at `remote:` is http:// or https:// if its http:// change it to https://.

**Comment by decodef** [comment]
> Hi @decodef thank you for reporting an issue.
> 
> Please check your `/etc/pterodactyl/config.yml` if at `remote:` is http:// or https:// if its http:// change it to https://.

Hello @Thiritin ,
It is already https://. 
![Screenshot_20201028-233825_Mobile SSH](https://user-images.githubusercontent.com/65123524/97499693-fa3bf200-1976-11eb-8335-5d1396e60d70.jpg)
Maybe I can write something to `allowed_origins` and it will work? For example *

**Comment by henrikx** [comment]
Do you use a reverse proxy between the daemon and the browser?
edit:
this might help you https://github.com/photoprism/photoprism/issues/209#issuecomment-576315296

**Comment by decodef** [comment]
> Do you use a reverse proxy between the daemon and the browser?
> edit:
> this might help you [photoprism/photoprism#209 (comment)](https://github.com/photoprism/photoprism/issues/209#issuecomment-576315296)

Hi @henrikx ,
I tried the thing allowing origin in nginx pterodactyl config, but it doesn't work

**Comment by henrikx** [comment]
> 
> 
> > Do you use a reverse proxy between the daemon and the browser?
> > edit:
> > this might help you [photoprism/photoprism#209 (comment)](https://github.com/photoprism/photoprism/issues/209#issuecomment-576315296)
> 
> Hi @henrikx ,
> I tried the thing allowing origin in nginx pterodactyl config, but it doesn't work

So you have set on proxy between client and daemon?
```
proxy_set_header    Connection "Upgrade";
```

**Comment by decodef** [comment]
> > > Do you use a reverse proxy between the daemon and the browser?
> > > edit:
> > > this might help you [photoprism/photoprism#209 (comment)](https://github.com/photoprism/photoprism/issues/209#issuecomment-576315296)
> > 
> > 
> > Hi @henrikx ,
> > I tried the thing allowing origin in nginx pterodactyl config, but it doesn't work
> 
> So you have set on proxy between client and daemon?
> 
> ```
> proxy_set_header    Connection "Upgrade";
> ```

I don't remember, but I don't think so.
I set the ```proxy_set_header    Connection "Upgrade";```
But its still doesn't work

**Comment by henrikx** [comment]
> 
> 
> > > > Do you use a reverse proxy between the daemon and the browser?
> > > > edit:
> > > > this might help you [photoprism/photoprism#209 (comment)](https://github.com/photoprism/photoprism/issues/209#issuecomment-576315296)
> > > 
> > > 
> > > Hi @henrikx ,
> > > I tried the thing allowing origin in nginx pterodactyl config, but it doesn't work
> > 
> > 
> > So you have set on proxy between client and daemon?
> > ```
> > proxy_set_header    Connection "Upgrade";
> > ```
> 
> I don't remember, but I don't think so.
> I set the `proxy_set_header Connection "Upgrade";`
> But its still doesn't work

What is the contents of your nginx config file? Feel free to redact any IP addresses or domain names.

**Comment by decodef** [comment]
> > > > > Do you use a reverse proxy between the daemon and the browser?
> > > > > edit:
> > > > > this might help you [photoprism/photoprism#209 (comment)](https://github.com/photoprism/photoprism/issues/209#issuecomment-576315296)
> > > > 
> > > > 
> > > > Hi @henrikx ,
> > > > I tried the thing allowing origin in nginx pterodactyl config, but it doesn't work
> > > 
> > > 
> > > So you have set on proxy between client and daemon?
> > > ```
> > > proxy_set_header    Connection "Upgrade";
> > > ```
> > 
> > 
> > I don't remember, but I don't think so.
> > I set the `proxy_set_header Connection "Upgrade";`
> > But its still doesn't work
> 
> What is the contents of your nginx config file? Feel free to redact any IP addresses or domain names.

https://hastebin.com/rowidobilo.nginx

**Comment by henrikx** [comment]
Yeah, those options won't work there because it's not a proxy. So I assume you do not go through a proxy when connecting to the daemon then? You're showing the nginx file hosting the panel, but WebSocket is used when connecting to the daemon.

**Comment by decodef** [comment]
> Yeah, those options won't work there because it's not a proxy. So I assume you do not go through a proxy when connecting to the daemon then? You're showing the nginx file hosting the panel, but WebSocket is used when connecting to the daemon.

So, what I can do?

**Comment by henrikx** [comment]
Are you accessing panel via https?

**Comment by schrej** [comment]
The GitHub issue tracker is for bugs and feature requests, not configuration errors with your instance. Please use our Discord instead: https://discord.gg/pterodactyl
