### ISSUE TITLE
"APP-ENVIROMENT_ONLY=false" false positive 

### ISSUE THREAD

**Issue by A-Yamout** [pterodactyl/panel#2622]
* Panel or Daemon:  Panel
* Version of Panel/Daemon: 1.0.3
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser:  Google Chrome | 86.0.4240.111 (Official Build) (64-bit) (cohort: Stable)

**Describe the bug**
When opening the settings to change panel name, 2FA, ETC. the panel will say "Your Panel is currently configured to read settings from the environment only. You will need to set APP_ENVIRONMENT_ONLY=false in your environment file in order to load settings dynamically.". APP_ENVIRONMENT_ONLY in pterodactyl.php is set to false and I found an earlier issue which included some cashe clearing commands all did not work, I searched all over Pterodactyl.io and GitHub and found nothing. can someone please help me?

**To Reproduce**
1. Go to 'The panel'
2. Click on 'settings'
3. Change any settings 
4. See error: "Your Panel is currently configured to read settings from the environment only. You will need to set APP_ENVIRONMENT_ONLY=false in your environment file in order to load settings dynamically."

**Expected behavior**
From what I can tell the Expected behavior is to be able to change any of the settings and for it to update the DB and have no errors.

Thank you for any help you can provide.

**Comment by matthewpi** [comment]
Did you check if you have `APP_ENVIRONMENT_ONLY=true` in the `.env` file located at the base directory of your Pterodactyl installation (the default path for this will be `/var/www/pterodactyl`)?  The `(bool)env('APP_ENVIRONMENT_ONLY', false)` function call does not mean that the value is set to `false`, it means that it will default to `false` if the environment variable is not present.

**Comment by A-Yamout** [comment]
Could you send me a copy of what the .env file is supposed to look like?
Thank You for your help.

**Comment by CMProjects7-8** [comment]
Can you please send a copy of what the file is supposed to look like? I am not good at PHP nor SQL. Thank You again for your help.

**Comment by A-Yamout** [comment]
Never mind I feel stupid I kept looking with ls to find the .env file and was just messing around and I typed in sudo nano .env and it worked. I am so sorry for wasting your time.

For people that come to look at this in confusion cd into /var/www/pterodactyl and then type sudo nano .env and then you can edit your .env file.

**Comment by Neihost** [comment]
Hello, I entered the panel today and I saw an error in the panel settings is its content "Your Panel is currently configured to read settings from the environment only. You will need to set APP_ENVIRONMENT_ONLY = false in your environment file in order to load settings dynamically."

and I don't know what to do with it, can you please explain the repair step by step?

below I am sending a screen from the panel

regards !

![Zrzut ekranu 2021-09-03 204723](https://user-images.githubusercontent.com/90064635/132052981-ac0b0500-aa2e-4982-bd52-f7c610247e61.png)
