### ISSUE TITLE
Allow to find servers by short UUID with the API

### ISSUE THREAD

**Issue by Hadimhz** [pterodactyl/panel#2625]
**Is your feature request related to a problem? Please describe.**
Getting a server by its visible ID requires many requests.
if I want to get a specific server using the ID visible to the user (example: efcecec0) I will have to list all servers and then filter the list. but that requires a lot of requests depending on the number of pages you have.

**Describe the solution you'd like**
can you add a filter to the servers API that will allow us to get a server using the serverID (the one visible to the user example: efcecec0) I've been told this is already a thing for the client API why not introduce it to the Admin one

**Describe alternatives you've considered**
add a filter that we can use when listing all servers. (similar to the one for listing all users)

**Comment by matthewpi** [comment]
Is there a reason you don't just filter by the `uuid` column which always starts with `uuidShort`?
https://github.com/pterodactyl/panel/pull/3340#issuecomment-835837117

**Comment by trenutoo** [comment]
Wasn't this solved by https://github.com/pterodactyl/panel/pull/3340 ?
