### ISSUE TITLE
V7.19 Error 

### ISSUE THREAD

**Issue by lewanpe** [pterodactyl/panel#2626]
Hello, i am on the V7.19 and there a problem with the /settings/startup

`[2020-10-30 14:30:08] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Argument 2 passed to str_contains() must be of the type string, array given, called in /var/www/pterodactyl/app/Models/EggVariable.php on line 90 in /var/www/pterodactyl/vendor/symfony/polyfill-php80/bootstrap.php:29
Stack trace:
#0 /var/www/pterodactyl/app/Models/EggVariable.php(90): str_contains('required|string...', Array)`

**Comment by schrej** [comment]
There is no version 7.19, I'll assume you're referring to 0.7.19 though.

Please be aware that v0.7 is no longer actively developed. If possible, consider migrating to v1.0.

Critical bugs and security issues will still be fixed, but minor issues would require patches by the community. If this is actually a bug, and not just a configuration issue, you'll have to provide a lot more details, especially instructions on how to reproduce this. If you still have that issue, open a new issue and do not ignore the issue template that time.

**Comment by lewanpe** [comment]
To repair this do 
`curl-sS https://getcomposer.org/installer | sudo php -- -install-dir=/usr/local/bin --filename=composer  --version=1.10.16 && cp -r ./composer /usr/local/bin && composer clear-cache && rm -r /var/www/pterodactyl/vendor && cd /var/www/pterodactyl/ && composer install --no-dev --optimize-autoloader`

**Comment by HavilahOG** [comment]
Are you on php8?

**Comment by lewanpe** [comment]
No, on php7.3, and my mail not work `Anerror occurred while attempting to test mail settings: Failed to authenticate on SMTP server with username "mail@techni-heberg.fr" using 2 possible authenticators. Authenticator LOGIN returned Swift_TransportException: Expected response code 235 but got code "535", with message "535 5.7.3 Authentication unsuccessful`

**Comment by HavilahOG** [comment]
Why is it using the wrong ver 
`/var/www/pterodactyl/vendor/symfony/polyfill-php80/bootstrap.php ` This didn’t exist in my vendor folder when I tried it yesterday

**Comment by lewanpe** [comment]
Actually my problem where solved just my email not work 
PHP7.3 and composer 1.10.16
