### ISSUE TITLE
Suspended server is unsuspended on transfer

### ISSUE THREAD

**Issue by Wouter0100** [pterodactyl/panel#2629]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.3
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Chrome on Ubuntu 16.04 

**Describe the bug**
A server that is suspended, is automatically unsuspended with a server transfer to a different node. This behavior is unexpected, as there is no mention that the server will be suspended and unsuspended for a server transfer, and I'd say is a side-effect of the transfer implementation that (mis?)uses suspend to lock a server temporarily.

**To Reproduce**
1. Suspend a server.
2. Move the server to a different node.
3. Notice that the server is now unsuspended.

**Expected behavior**
Keep the server suspended after a server move, when it's suspended.

Or, as an easy fix (which is a workaround) is to hide the server transfer option once a server is suspended.

**Comment by Wouter0100** [comment]
As an addition to this issue, I will be happy to provide a PR for this in the upcoming days myself. Storing the old suspend state in the transfer object in the DB, and only unsuspending at a transer success once it was unsuspended.

**Comment by matthewpi** [comment]
For this, I'd rather separately track a transferring status rather than it just relying on suspending the server.

**Comment by matthewpi** [comment]
The logic for transfers was reworked to no longer use the suspension feature to lock a server while it is being transferred, so this is no longer a problem.

**Comment by Wouter0100** [comment]
For reference, #2883 is the PR - isn't it? :)
