### ISSUE TITLE
Timezone is always UTC inside the container

### ISSUE THREAD

**Issue by SagnikSRHUSE** [pterodactyl/panel#2630]
Background:
Daemon
Panel: v1.0.3 ; Daemon: 1.0.1 (latest)
Server's OS: Ubuntu 20.04.1
Your Computer's OS & Browser: Manjaro, Chrome v86.0.4240.111

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: 7.4.11
Daemon: 
uname -r:  
```Linux ManilaRoleplay 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```
docker info: 

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-52-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.843GiB
 Name: hostname
 ID: TXZE:SYLQ:FPTL:VVW6:KRTD:E5HB:VN7P:BIPH:NP2H:XYZ3:TFLK:XC5X
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

1. Set timezone to Asia/Manila in /etc/pterodactyl/config.yml
2. Restart the daemon and the container (I tried restarting docker too, just in case)
3. Time inside the container stays at UTC, but it shows up as Asia.
```Sat Oct 31 11:36:35 Asia 2020```, the actual time in Asia/Manila is 19:36:35

**Expected behavior**
Time should be the actual Asia/Manila time.

Side note: I have noticed that there is no /etc/localtime file inside the container, and in previous releases, I had to bind that file, instead of /etc/timezone to get timezones to work as expected inside the container.

**Comment by schrej** [comment]
see #2513
