### ISSUE TITLE
SAML Authentication

### ISSUE THREAD

**Issue by Weilbyte** [pterodactyl/panel#2635]
**Is your feature request related to a problem? Please describe.**
It would be nice if Pterodactyl could leverage SAML authentication. As an example, could probably use Cloudflare Access.

**Describe the solution you'd like**
SAML authentication support.

**Describe alternatives you've considered**
LDAP would be a close alternative, there is already an issue out for that. Though you can log into Microsoft AD without LDAP through the use of Azure AD connections. Could even go further and log in with SAML through the use of Cloudflare Access with an Azure AD auth application.

**Additional context**
Understandably y'all probably don't have time for this feature as you have more important work. Just leaving this issue here in case I want to pick this up in like a few weeks or so.

**Comment by Wunderharke** [comment]
Most provides of SAML also provide OIDC, there is already a pull request (#1964) on that, this could be an alternative until SAML might get integrated.

**Comment by matthewpi** [comment]
Closing, SAML itself is complex regardless of if libraries for it exist.  If any type of SSO is to be added officially, it would be through OAuth2 or OIDC which almost every SSO provider seems to offer.
