### ISSUE TITLE
Error while creating a Rust game container

### ISSUE THREAD

**Issue by FunixG** [pterodactyl/panel#2641]
Panel Version: 1.0.3
Deamon Version : 1.0.1
Service: Rust
Modified: no

Hello i have an issue when creating a rust server on pterodactyl. I am using the egg of this github: https://github.com/parkervcp/eggs/tree/master/steamcmd_servers/rust/rust_staging

But when i start the container this error is prompted
curl: (7) Failed to connect to media.steampowered.com port 80: No route to host
tar (child): steamcmd.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/mnt/install/install.sh: line 12: ./steamcmd.sh: No such file or directory
cp: cannot stat '/mnt/server/steam/linux32/steamclient.so': No such file or directory

The container has network connexion because he does updates and packets install before that.
How can i download steamcmd ?

**Comment by DaneEveritt** [comment]
Firstly this issue does not follow our issue reporting template, secondly this is not an issue with Pterodactyl, rather an issue with the specific egg you're using. Please use the appropriate Discord channels for support or get in touch on the egg repository.
