### ISSUE TITLE
Access logging through a webhook

### ISSUE THREAD

**Issue by BehnH** [pterodactyl/panel#2644]
**Is your feature request related to a problem? Please describe.**
This is not issue related

**Describe the solution you'd like**
An ability to log authentications with the panel/each time a user accesses the panel.
When turned on, JSON data would be sent to a configurable endpoint containing data such as the username, IP, email, and the time accessed.

**Describe alternatives you've considered**
There are no alternatives

**Additional context**
None

**Comment by DaneEveritt** [comment]
Duplicate #1219
