### ISSUE TITLE
Uploading files brings server tps to 1/2. Can crash server

### ISSUE THREAD

**Issue by crispyaus** [pterodactyl/panel#2645]
* Panel or Daemon: Both?
* Version of Panel/Daemon: Panel: 1.0.3 Wings: 1.0.1 
* Server's OS: Panel: CentOS 7. Wings: Ubuntu 20.2
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
Simple. Go into file manager, drop a plugin (for me i did it with a plugin)
and it will load for a solid minute. After you drop it in the file manager it says this in consle.

```
[00:10:04 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-251 (MC: 1.16.3) ---
[00:10:04 ERROR]: The server has not responded for 10 seconds! Creating thread dump
[00:10:04 ERROR]: ------------------------------
[00:10:04 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[00:10:04 ERROR]: ------------------------------
[00:10:04 ERROR]: Current Thread: Server thread
[00:10:04 ERROR]:       PID: 21 | Suspended: false | Native: true | State: RUNNABLE
[00:10:04 ERROR]:       Stack:
[00:10:04 ERROR]:               sun.nio.fs.UnixNativeDispatcher.unlink0(Native Method)
[00:10:04 ERROR]:               sun.nio.fs.UnixNativeDispatcher.unlink(UnixNativeDispatcher.java:146)
[00:10:04 ERROR]:               sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:231)
[00:10:04 ERROR]:               sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
[00:10:04 ERROR]:               java.nio.file.Files.deleteIfExists(Files.java:1165)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.SystemUtils$2.getAsBoolean(SystemUtils.java:358)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.SystemUtils.a(SystemUtils.java:403)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.SystemUtils.a(SystemUtils.java:414)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.SystemUtils.a(SystemUtils.java:432)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.SystemUtils.a(SystemUtils.java:426)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.WorldNBTStorage.save(WorldNBTStorage.java:37)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.PlayerList.savePlayerFile(PlayerList.java:486)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.PlayerList.lambda$savePlayers$5(PlayerList.java:1156)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.PlayerList$$Lambda$5490/745220289.get(Unknown Source)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.MCUtil.ensureMain(MCUtil.java:350)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.PlayerList.savePlayers(PlayerList.java:1149)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1237)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[00:10:04 ERROR]:               net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3038/835472955.run(Unknown Source)
[00:10:04 ERROR]:               java.lang.Thread.run(Thread.java:748)
[00:10:04 ERROR]: ------------------------------
[00:10:04 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[00:10:04 ERROR]: ------------------------------
[00:10:05 WARN]: Can't keep up! Is the server overloaded? Running 11042ms or 220 ticks behind
```

The tps drops sometimes to 17 for a couple seconds or sometimes to 2/4 for minutes. I have 0 clue what could cause this, but it happens every time & hopefully that error can get the devs to understand it.

**To Reproduce**
1. Drop a file in file manager

**Comment by crispyaus** [comment]
This is pretty urgent to me and my players too. So if someone has any ideas on how to fix this before the devs can please lmk.

**Comment by TekExplorer** [comment]
Please supply actual logs that may give actually useful info.

**Comment by JackCrispy** [comment]
> Please supply actual logs that may give actually useful info.

You think i would of done that if I had them buddy. Please don't comment unless you have something beneficial to say. Not just requesting more logs.

**Comment by MWHunter** [comment]
What are the specs of the machine you are uploading to?

**Comment by DaneEveritt** [comment]
I cannot reproduce this with the information provided, and this is unlikely to be an issue caused by Pterodactyl specifically — especially since if it was I would expect there to have been _far_ more reports of this, since it isn't exactly an uncommon scenario.

More than likely you're running into some resource limitations with your machine, but I just gave it a quick spin locally and didn't notice any issues, and I'm unsure how I can help much more given my limited knowledge of a.) Java and b.) Paper.

**Comment by crispyaus** [comment]
> What are the specs of the machine you are uploading to?

64gb ram, forget CPU specs, 2tb storage, OVH.

**Comment by crispyaus** [comment]
> I cannot reproduce this with the information provided, and this is unlikely to be an issue caused by Pterodactyl specifically — especially since if it was I would expect there to have been _far_ more reports of this, since it isn't exactly an uncommon scenario.
> 
> More than likely you're running into some resource limitations with your machine, but I just gave it a quick spin locally and didn't notice any issues, and I'm unsure how I can help much more given my limited knowledge of a.) Java and b.) Paper.

Well that's bs since it is coming from ptero.

**Comment by DaneEveritt** [comment]
I'm not going to help you if you're going to have that type of attitude. I need you to understand I am one person who has limited scope with the amount of games we support. I try my best to help people, but I'm not a personal systems admin and there are plenty of things I don't understand well enough to dedicate time digging into; especially based on an un-substantiated claim that something as vague as this is caused by Pterodactyl.

**Comment by crispyaus** [comment]
> I'm not going to help you if you're going to have that type of attitude. I need you to understand I am one person who has limited scope with the amount of games we support. I try my best to help people, but I'm not a personal systems admin and there are plenty of things I don't have the knowledge to be able to spend all day digging into on the un-substantiated claim that something as vague as this is caused by Pterodactyl.

How could it now be coming from ptero? If i swapped to just running the java command from the command line it would obv work and files would get uploaded. If I upload files via ptero and then it errors saying something about a native file manager then you would tie the two together. I mean, what else could it be 😆

**Comment by disconsented** [comment]
> > What are the specs of the machine you are uploading to?
> 
> 64gb ram, forget CPU specs, 2tb storage, OVH.

This isn't that useful, need CPU model and drive model.

Try installing netdata and watching for resource exhaustion, dmesg and journal might also have some extra hints.

Generally I'd agree otherwise if this was a issue it'd be prolific by it's nature.

**Comment by GravityCube** [comment]
You are probably exceding your disk i/o capacity (It can probably be solved switching to a SSD) or your cpu can't sustain a compression and running a server at the same time.

You should send the info that they requested you. I doubt that someone is going to help you if you ask for help like that anyway.

**Comment by crispyaus** [comment]
Please take a look at this. https://streamable.com/2gc93q

Showing how I uploaded the clearlagg plugin into plugins folder as an example, server was fine for 10 seconds and it dropped to 7tps. I then waited for around a minute and it said Network error on the file manager page. But on refresh the plugin was there & uplaoded.

**Comment by crispyaus** [comment]
Also any system stats ill get for you, I'm running an SSD.

CPU Stats: https://i.crisp.codes/610f63.png

**Comment by DaneEveritt** [comment]
Run Wings in the foreground using `wings --debug --profile`, upload your file, and then as soon as it is completed stop the process with `Ctrl + C` and upload the resulting `cpu.pprof` file here.

**Comment by crispyaus** [comment]
Will do where will the cpu.pprof save?

**Comment by DaneEveritt** [comment]
It'll output something like:

```
DEBUG: [Nov  1 16:50:35.628] listening for server events over websocket server=0cb5cf39-0b31-4bf7-8516-0f873f4bdcd1
^C2020/11/01 16:50:38 profile: caught interrupt, stopping profiles
2020/11/01 16:50:38 profile: cpu profiling disabled, /tmp/profile492015838/cpu.pprof
```

Also, please add the output of `docker info`.

Do you have any CPU limits on that specific server, or have you made any modifications to the IO weight for it? Can you include a screenshot of that server's build settings page (with the memory limits, etc.)

**Comment by alliraine** [comment]
I run Pterodactyl on over 100 nodes, including ones from OVH, and host over 800 Minecraft servers. If this was an issue with Pterodactyl I would have discovered it by now. I would recommend going to Admincraft and see if they have any ideas what could be causing this.

**Comment by crispyaus** [comment]
So I am running the wings from CL and I uploaded the file(s) one after another and it is still stuck on loading, but no errors come from console or say profile caught interrupt, ect .

This is my build config https://i.crisp.codes/c04b29.png

**Comment by TekExplorer** [comment]
Its possible that a plugin you have could be reacting badly to the uploaded file. could you supply a list of your plugins?

**Comment by crispyaus** [comment]
> Its possible that a plugin you have could be reacting badly to the uploaded file. could you supply a list of your plugins?

Sure. https://i.crisp.codes/8b3145.png

**Comment by DaneEveritt** [comment]
@JackCrispy you have to upload a single file, and then use `CTRL+C` to stop the wings process to get the profile. But I need it to be a relatively "clean" run where you start, immediately upload, and then stop wings so I can have a decently not-complex profile to look at.

**Comment by crispyaus** [comment]
Oh okay. here you go: https://i.crisp.codes/e4e333.pprof

Took around 2 minutes for the file to fully upload before it said Network error in the file manager.

**Comment by DaneEveritt** [comment]
Please also add your `docker info` output @JackCrispy

**Comment by crispyaus** [comment]
Yep: https://i.crisp.codes/d6b95f.png

**Comment by crispyaus** [comment]
Update??

**Comment by FoksVHox** [comment]
@JackCrispy First of all, this isn't a major bug. It's simple to fix, don't upload files when it's running.

Secondary, you're not entitled to receive any kind of support, you would know that if you read the license. 

Thirdly, Dane is the cool person that chose to make Pterodactyl open source, and he would be able to sell this software with ease. However, he has chosen to make it open source, so at least show the man respect by having some patience, as Dane has a full-time job, and Pterodactyl is his side project.

**Comment by crispyaus** [comment]
Excuse me what? I'm not being entitled at all, im asking for an update on findings. Just get off github lmfao. And this remark: "First of all, this isn't a major bug. It's simple to fix, don't upload files when it's running" What? I cannot belive the stupidity of some. I'm not going to turn off my server everytime I want to upload a file. Even if i can that's impractical and the issue still exists. Go find something better to do than attacking on a github issue. 🤡

**Comment by crispyaus** [comment]
"Dude, you act so entitled people on discord are mocking you." Love this. They can mock me all they want, that community is filled with complete pricks.

**Comment by schrej** [comment]
Have some patience. Dane was merely requesting the necessary amount of information to investigate the issue, that doesn't mean he'll look at a performance profile right away. It'll take a while.

This impatient behavior is also what's generally considered as entitlement as others have pointed out. GitHub is not the place to discuss that, please take it somewhere else. Ideally also not the Pterodactyl Discord, we're tired of it. From now on only provide meaningful comments to this issue, or it'll be locked.

**Comment by crispyaus** [comment]
I'd like it if you all stopped commenting useless things on this issue. I was **Not** rushing or pressuring or impatient. I was just asking for an update on what he has found.

**Comment by DaneEveritt** [comment]
I will not be further investigating this issue. I do not believe it is caused by Pterodactyl directly and have not heard from anyone else, including many large hosts, that this is an issue they are facing.

In general, don't insult the community you're seeking free support from.

Best,
That complete prick from the community.
