### ISSUE TITLE
Panel emails missing URL/Sender Name

### ISSUE THREAD

**Issue by ripinet5** [Pterodactyl/Panel#265]
Hello,

After experimenting with the panel I have identified a bug with email sending. Another user in Discord was able to confirm this bug is present as well. 

Steps to replicate:
> Cleanly install panel
> Create account (sends account creation email)

Sent email will contain the following:

"If you’re having trouble clicking the "Setup Your Account" button, copy and paste the URL below into your web browser: http://localhost/auth/password/reset/0pXDOtPaVyOWmjVhADVG0o8Hjh6yf8w7?email="

It appears that APP_URL is not being applied to the generated emails, this occurs with **any** email sent from the panel. In addition, my installation is ignoring the "Email Sender Name:" and is using the default sending name of 'Pterodactyl Panel' instead. My mail configuration is not to blame, all variables are properly defined in the .env and I have been able to replicate this issue on 2 separate clean installs using 2 different mail methods (PHP Mail and SMTP). 

Both installs were done on Ubuntu 16.04 following the instructions to the letter. Just in case it helps, here is my environment:

PHP 7.0.13-0ubuntu0.16.04.1
nginx 1.10.0-0ubuntu0.16.04.4 
Mail: Tried SMTP/PHP Mail, issue is present in both.

**Comment by ripinet5** [comment]
After updating the .env file to include http:// in the APP_URL I am seeing proper URLs in emails.

However, the issue with Email Sender Name is still present. The panel seems to be ignoring the setting.

**Comment by xyeLz** [comment]
Not that it matters at this point, but I also was able to confirm this was the case.
