### ISSUE TITLE
Nodes with SSL are being forced to have a FQDN when it's not necessary.

### ISSUE THREAD

**Issue by applebee1558** [pterodactyl/panel#2650]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel 1.0.3
* Server's OS: Centos 7.6 with PHP 7.2
* Your Computer's OS & Browser: Firefox 82 on Windows 10

**Describe the bug**
The panel does not let you add a node using an IP if you have SSL enabled.

**To Reproduce**
1. Go to the admin area and add a node
2. Make sure SSL is enabled for the node
3. Put an IP address in the node FQDN

**Expected behavior**
It should allow IPs if you have SSL on since the node does not have a strict restriction being FQDN only. It allows IPs if you have SSL off. 

Here's an excerpt: SSL certificates can contain IP addresses on the Subject Alternative Name according to RFC-5280 . Here's an except from it:  The subject alternative name extension allows identities to be bound to the subject of the certificate.  These identities may be included in addition to or in place of the identity in the subject field of the certificate.  Defined options include an Internet electronic mail address, a DNS name, **an IP address**, and a Uniform Resource Identifier(URI).

**Comment by DaneEveritt** [comment]
While technically correct, in practice 99% of users will need to be using a FQDN and I'd rather not change this when it has been working fine as is for the last 5 years now.

**Comment by applebee1558** [comment]
Why would most users need to use a FQDN? CAs issue certificates for IP addresses too if you are talking about trust. Some people also use self-signed certificates for internal network traffic and would like SSL on it. The current solution is to hack the database and change it.
