### ISSUE TITLE
Mumble / Murmur server does not install properly on 1.0.3

### ISSUE THREAD

**Issue by sapphonie** [pterodactyl/panel#2651]
**Background (please complete the following information):**
* Panel or Daemon: uhh IDK panel probably
* Version of Panel/Daemon: panel 1.0.3 , daemon 1.0.1
* Server's OS: Ubuntu 20.10
* Your Computer's OS & Browser: Win 10 64x Firefox Latest 

**Describe the bug**
Mumble / Murmur server can not be installed properly on ptero panel as it fails with the following:

https://ghostbin.co/paste/7933b5a

Please provide additional information too, depending on what you have issues with:

`php -v`:
```
# steph @ dedibuntu-CHI in ~ [1:59:45]
$ php -v
PHP 7.4.9 (cli) (built: Oct 26 2020 15:17:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```
`uname -a`
```
# steph @ dedibuntu-CHI in ~ [2:07:15]
$ uname -a
Linux dedibuntu-CHI 5.8.0-26-lowlatency #27-Ubuntu SMP PREEMPT Thu Oct 22 00:13:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
`sudo docker info`
https://ghostbin.co/paste/492g
**To Reproduce**
1. Go to `panelurl`/admin
2. Click "servers"
3. Create a new Murmur server

**Expected behavior**
Expected server to install properly. It did not.

**Comment by parkervcp** [comment]
This is known. The egg has been updated in the panel and should be updated in the next release.

**Comment by parkervcp** [comment]
These are the updated eggs.

https://github.com/pterodactyl/panel/tree/develop/database/seeds/eggs/voice-servers
