### ISSUE TITLE
Console stops updating after some time

### ISSUE THREAD

**Issue by itaquito** [pterodactyl/panel#2652]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.3
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 > Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
Hello! After some time, with no apparent reason, the console stops updating. No new lines are being displayed, however, you can still send commands. When you refresh the panel (F5), you can see the newer lines that weren't displayed before.
This seems that this is per-server because some other servers on the same daemon and panel doesn't have this problem. 

**To Reproduce**
1. Create a server
2. Wait....
I haven't confirmed this, but I have a strong feeling that the bug happens when the server sends a lot of text really fast into the console.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
Recording a video is very difficult because the server the error is happening on displays a lot of sensitive information on the console.
Expected behaviour: The panel keeps updating the information of the console.

Thanks.

**Comment by itaquito** [comment]
Update: Restarting the server seems to fix the issue.

**Comment by zKoz210** [comment]
I confirm.  I started the PocketMine-MP server and left it on for a few hours, after which I go to the console and it is empty.  If you try to write some commands several times, logs will start to appear.  It looks strange.
![B83A4B3E-9715-4B9A-AF11-88BAB82AFA98](https://user-images.githubusercontent.com/28255085/98355014-a2fee700-2032-11eb-8f25-c818b8b12de8.jpeg)

**Comment by notAreYouScared** [comment]
Are you leaving the browser open? or is the server just running for a few hours?

**Comment by zKoz210** [comment]
No, I close my browser, the server works from 2 to 24 hours and the console stops updating.  I open a page from servers and the console is empty

**Comment by itaquito** [comment]
> Are you leaving the browser open? or is the server just running for a few hours?

I do leave the panel open on my browser while I do my daily tasks on the computer. This may be the cause of the error.

I think @zKoz210 and I are talking of 2 different problems that might be related. In contrast of his problem, I do see the text on the console, however, it only updates when I hit F5.

**Comment by DaneEveritt** [comment]
I'm not about to spend hours trying to reproduce this, so if it happens again can you just look at the browser console and see what might be happening in there? Honestly if it takes hours of the page being open and it just goes blank I'm gonna call that a minor issue and not be spending a lot of energy (personally) to track it down.

**Comment by itaquito** [comment]
Yeah.. it's a weird issue that doesn't have a clear cause. 
I just checked the browser console and no errors appear on it. 

Maybe we can schedule a call so I can screen share you so you can get more details of it?

**Comment by matthewpi** [comment]
Without any clear reproduction steps and this seeming to be a "may happen time-to-time" problem, I'm going to close this issue.  If anyone comes across a way to somewhat reproduce this consistently, feel free to comment on this issue to have it re-opened.

**Comment by DaneEveritt** [comment]
Pretty sure this is the same as the other open issue where Docker explodes when reading from the logs and causes the reader to just be reading an empty loop @matthewpi.

Suffice to say theres a more accurate issue somewhere.
