### ISSUE TITLE
Request failed with status code 504

### ISSUE THREAD

**Issue by 123hotdog1100** [pterodactyl/panel#2653]
**Background (please complete the following information):**
* Panel or Daemon: panel 
* Version of Panel/Daemon: Panel:V1+ Daemon:V1+
* Server's OS: Ubuntu
* Your Computer's OS & Browser: Windows 10 pro Firefox

**Describe the bug**
when ever i look at the servers on the dashboard the servers have connection refused but sometimes connect in the firefox browser console it gives the error "Request failed with status code 504" me and some others on the discord have this error and have tried to think of why it does this
Please provide additional information too, depending on what you have issues with:
Panel: "PHP 7.4.12 (cli) (built: Oct 31 2020 10:04:33) ( NTS )"
**To Reproduce**
load up dashboard 
see the error in the console of the browser
![image](https://user-images.githubusercontent.com/14129417/97999076-c92e4800-1de2-11eb-9202-d5c8d3ed2641.png)

**Expected behavior**
it was expected to give the RAM CPU usage and disk usage reports but says connection error

**Comment by fabm3n** [comment]
Please visit the Discord for Support.
Probaply you can't reach wings.
This is not a Bug.

**Comment by 123hotdog1100** [comment]
> 
> 
> Please visit the Discord for Support.
> Probaply you can't reach wings.
> This is not a Bug.

me and many other people have the same issue and it started randomly so we either have a bug somehow or we all made the exact same mistake which is unlikely and we have tried everything and non of us can come up with a reason for this happening

**Comment by TekExplorer** [comment]
we tried, the issue seems to be that the panel cant reach its own api. (/api/servers/...) with a gateway timeout error.

**Comment by fabm3n** [comment]
Then provide Logs and more Informations when you are still thinking it's a issue.

**Comment by 123hotdog1100** [comment]
Panel logs: http://bin.ptdl.co/ntdqp
Wings logs: http://bin.ptdl.co/zkngg

**Comment by TekExplorer** [comment]
Here is a slightly more useful image that someone with the issue sent in the discord earlier, in case it helps
![image](https://user-images.githubusercontent.com/30291302/97999980-f74b6200-1db9-11eb-8510-619d822950e3.png)

**Comment by fabm3n** [comment]
There aren't any requests in your wings log when the issue appears in the panel (14:348:05) , so it can't reach wings. That has nothing to do with wings or the panel. It looks like there is another system which interrupts the request (Firewall, Proxy, etc.).

**Comment by fabm3n** [comment]
And still: please provide more informations. I read something about some nginx config to fix this in Discord. Is your Wings behind a reverse Proxy?

**Comment by 123hotdog1100** [comment]
No that was redseals idea to see if it can get it working by making it so the proxy added the daemon port to the request but i did not do that and their is no service on the server that should be blocking the request

**Comment by fabm3n** [comment]
Did you tried to reach wings without the panel in your browser when the issue occurs? (example: wings.domain.com:8080)

**Comment by 123hotdog1100** [comment]
Yes i can reach that just gives this error  "The required authorization heads were not present in the request." but i think that is expected

**Comment by fabm3n** [comment]
Yes that's expected. So the issue is currently appearing and you can reach wings in another tab?
Are you using SSL. If yes both panel and wings?

**Comment by 123hotdog1100** [comment]
the issue is the panel can't reach wings and yes i am using SSL on both panel and wings and the panel and wings are hosted on the same server

**Comment by DaneEveritt** [comment]
This is not a bug, at least not given the information being reported.

You likely have a janky network setup blocking requests, or some local issue hindering connections. Specially your Panel is unable to connect to Wings.

This is not a bug appropriate for this issue tracker.
