### ISSUE TITLE
Checkbox "Start server when installed pterodactyl" not working

### ISSUE THREAD

**Issue by timossileandro** [pterodactyl/panel#2660]
**Background (please complete the following information):**

- 1. Panel or Daemon: Panel/Daemon
- 2. Version of Panel and Daemon: 1.0.3 and 1.0.1
- 3. Server's OS: Debian 10
- 4. Your Computer's OS & Browser: Windows 10 > Chrome

**Describe the bug**
When creating a new server, I check the box for it to start after installation is complete. The server is created successfully but does not start automatically.
Panel: PHP Versión 7.2.33-1
Daemon: Linux 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux. Docker info: Server Version 19.03.12

**To Reproduce**

1. Create a server:
![image](https://user-images.githubusercontent.com/17083780/98155101-7f159700-1eb4-11eb-84ac-b08f47993293.png)

2. Wait for install:
![image](https://user-images.githubusercontent.com/17083780/98155289-bf751500-1eb4-11eb-87b8-33d7ca3de479.png)

3. Once you are in Active go to the console:
![image](https://user-images.githubusercontent.com/17083780/98155368-e3d0f180-1eb4-11eb-80f6-97562981906a.png)

4. The server remains like this and does not start
![image](https://user-images.githubusercontent.com/17083780/98155431-fcd9a280-1eb4-11eb-9932-c0045d54d790.png)

**Expected behavior**
When the server is created it should start automatically

Thanks.

**Comment by zKoz210** [comment]
duplicate https://github.com/pterodactyl/panel/issues/2384

**Comment by parkervcp** [comment]
closed as a duplicate
