### ISSUE TITLE
Add custom configuration for setting MTU of servers interfaces created via docker

### ISSUE THREAD

**Issue by SAMXPS** [pterodactyl/panel#2662]
**Is your feature request related to a problem? Please describe.**
Yes, we are having problems configuring the panel because we need custom MTU settings so that our network connection works properly inside the servers.

**Describe the solution you'd like**
I'd like some way of configuring the MTU of interfaces created here:
https://github.com/pterodactyl/wings/blob/develop/environment/docker.go#L91

The default MTU of 1500 doesn't work for us.

**Other solutions considered**
We considered changing the source code by ourselves and trying to add this functionality, but we need more help to do so.

**Comment by parkervcp** [comment]
You can just change that one line and re-compile wings to have a different MTU. Go is quite easy to compile.

**Comment by SAMXPS** [comment]
Ok, I will try that.

After,
Would you like me to create a custom configuration setting and pull request as a feature?

https://prnt.sc/ve4nnt

**Comment by parkervcp** [comment]
I think it being a configurable value makes sense.

**Comment by sergejostir** [comment]
You can create a new docker network and simply point wings to use it ("docker.network.name" config). Or delete "pterodactyl_nw" and recreate it manually with desired settings.

**Comment by parkervcp** [comment]
While that is possible making it a configurable value would be good for more people.

**Comment by schrej** [comment]
I think this was possible with the old daemon as well.

**Comment by sergejostir** [comment]
> 
> 
> I think this was possible with the old daemon as well.

Negative
https://github.com/pterodactyl/daemon/blob/208f85ca96e400dec43faf28bcc34e28a0bd8424/src/controllers/network.js#L85

**Comment by SAMXPS** [comment]
> While that is possible making it a configurable value would be good for more people.

Yes. That would be great.

**Comment by SAMXPS** [comment]
> You can create a new docker network and simply point wings to use it ("docker.network.name" config). Or delete "pterodactyl_nw" and recreate it manually with desired settings.

This worked for me! Thank you very much!

**Comment by DaneEveritt** [comment]
I think since you can just create custom networks Im going to leave it at that.

It's been five years and you're the first person to find this needed, and it was easily resolved with a custom network (which would allow allow all the customization you'd ever need, without us having to support effectively an entire docker config as well).
