### ISSUE TITLE
404 error after middle clicking to open a new tab

### ISSUE THREAD

**Issue by BillyDaPoop** [pterodactyl/panel#2663]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.3
* Server's OS: Debian GNU/Linux 10 (buster)
* Your Computer's OS & Browser: Chrome OS Version 86.0.4240.183, Google Chrome

**Describe the bug**
Middle clicking on a folder(opens a new tab), and then clicking on a file inside that folder brings you to a 404 page instead letting you edit it.

**To Reproduce**
1. Go to file manager on server page
2. Middle click on a folder.
3. Click on editable text file inside that folder.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Edit**: To add onto this, seems like middle clicking brings you to 
[https://panel.example.com/server/aa11b2cd/files/#/folder](https://panel.example.com/server/aa11b2cd/files/#/folder)
which is different from left clicking on it normally:
[https://panel.example.com/server/aa11b2cd/files#/folder](https://panel.example.com/server/aa11b2cd/files#/folder)

Page not go kaboom(404).

**Comment by YajTPG** [comment]
I can confirm this is true

**Comment by ClumsyAdmin** [comment]
Same here
