### ISSUE TITLE
[FileManager] Encoded name is displayed

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2664]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/009f9c297de000589778b493c080e3b4d5dcc20a & https://github.com/pterodactyl/wings/commit/af9ed4bff1cb65c822634e3a9a7e1f40c1098bce
* Version of Panel/Daemon: 1.0.3
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**

The encoded file name is displayed in breadcrumbs

![93DBEBCE-D5F8-4D8F-A202-B265091EA8EA](https://user-images.githubusercontent.com/28255085/98355376-186ab780-2033-11eb-888d-68b387ec655b.jpeg)

**Comment by DaneEveritt** [comment]
What is the actual name of the file?

**Comment by zKoz210** [comment]
name - "лол"
