### ISSUE TITLE
Error index.tsx 

### ISSUE THREAD

**Issue by EshanMistry73** [pterodactyl/panel#2667]
**Background (please complete the following information):**
* Panel or Daemon: 1.0.3
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chrome

**Describe the bug**

When running the yarn run build:production command, i get a error - although i checked the line and it seems (potentially) to be related to the schedules bug, are the two related? https://github.com/pterodactyl/panel/issues/2609 - For context its the data validation error, https://bin.ptdl.co/356rg/

![image](https://user-images.githubusercontent.com/14224587/98395945-e79b7a00-2054-11eb-99c1-9c92427781b6.png)

I asked on Discord a few times but nothing, i figured it may be best to ask directly. Once again thank you in advance!

**Comment by DaneEveritt** [comment]
Duplicate https://github.com/pterodactyl/panel/issues/2363

No one has been able to provide enough information to prove that this is an issue specifically with Pterodactyl, I've been completely unable to reproduce it, much Googling has found nothing, and I don't have the time to sit here trying to reproduce it or dig through tons of results to guess at what it might be.

Try starting over fresh, and ensure you're running a normal `yarn install` and nothing else before building.

**Comment by RoxyBoxxy** [comment]
@DaneEveritt i am also having the issue, i have removed all files in my dir and redownloaded them, i have also tried to build it with no modifications.
OS: Ubuntu 18.04LTS
Node: 13.0
PHP: 8.0.3
Yarn: 1.22.5

**Comment by DaneEveritt** [comment]
This was already fixed in 1.3.0, the information you have provided does not indicate what version of the software you're using.
