### ISSUE TITLE
Cannot open admin settings

### ISSUE THREAD

**Issue by kareemfakhuri** [pterodactyl/panel#2670]
I'm facing an issue with accessing the admin settings section of the panel.
It doesn't let me open the page and instead just opens the user settings page.

![H7mub2bYse](https://user-images.githubusercontent.com/73457418/98434832-3111b680-20a1-11eb-92b5-dbf30b1c3466.gif)

Could anyone help me with this? I have no idea what could be causing it

Server OS: Debian 10 v4.19.0-12
PHP Version: 7.3.19

**Comment by notAreYouScared** [comment]
What browser are you using?

**Comment by kareemfakhuri** [comment]
I just submitted this bug again with proper formatting and some more info so I'm going to close this one. I'm using Google Chrome though
https://github.com/pterodactyl/panel/issues/2673

**Comment by schrej** [comment]
For the future: It's possible to edit comments on GitHub, just click the three dots in the corner.
