### ISSUE TITLE
[Wings][Docker] wings exit in alpine docker

### ISSUE THREAD

**Issue by pedxyuyuko** [pterodactyl/panel#2671]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0.3/0.0.1
* Server's OS: Fedora 33
* Your Computer's OS & Browser: Fedora 33/Chrome

**Describe the bug**
When I was using the wings in docker(alpine) and try to start the daemon in ash, the ash showed: ``./wings: command not found`` (I am sure about the file exist and it has correct perm)
![image](https://user-images.githubusercontent.com/39913604/98444976-f2870500-214f-11eb-897e-756f8d91a792.png)
Then, I google with the keyword: ``docker alpine go executable not found`` and I found https://stackoverflow.com/questions/34729748/installed-go-binary-not-found-in-path-on-alpine-linux-docker
http://dominik.honnef.co/posts/2015/06/statically_compiled_go_programs__always__even_with_cgo__using_musl/

```bash
> uname -a
Linux localhost.localdomain 5.8.17-300.fc33.x86_64 #1 SMP Thu Oct 29 15:55:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> docker info
Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 7
  Paused: 0
  Stopped: 3
 Images: 18
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: /usr/libexec/docker/docker-init
 containerd version:
 runc version: c9a9ce0286785bef3f3c3c87cd1232e535a03e15
 init version:
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.8.17-300.fc33.x86_64
 Operating System: Fedora 33 (Thirty Three)
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 15.59GiB
 Name: localhost.localdomain
 ID: 5DOL:YJ6B:VVHJ:4LFG:MSAZ:QSBJ:LLL4:SEUE:PIVR:KC3J:CIFX:4IUF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**To Reproduce**
1. run the docker ``docker run --privileged --rm -ti --entrypoint (image)``
2. exec command ``./wings``

**Expected behavior**
The daemon run correctly.

**Fix**
I think may be disable the ``CGO`` or add the command in the dockerfile 
``RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2`` will work.
(base on the source above)
![image](https://user-images.githubusercontent.com/39913604/98445100-ccae3000-2150-11eb-8d2e-e6bcfd08b46e.png)

**Comment by parkervcp** [comment]
The wings dockerfile we already have should work fine - https://github.com/pterodactyl/wings/blob/develop/Dockerfile

Please note the container is already alpine and compiles with no issues.

**Comment by pedxyuyuko** [comment]
My bad sorry that is not the wings problem.
@gzzchh find out ``CGO`` will link the system lib. So you have to build and run in the same system such as build in alpine and run in  alpine too.

**Comment by chisaato** [comment]
I did some experiments, here is the result 

| Build           | Run             | Status |
|-----------------|-----------------|--------|
| Alpine\(musl\)  | Fedora\(GLIBC\) | NO     |
| Alpine\(musl\)  | Alpine\(GLIBC\) | YES    |
| Fedora\(GLIBC\) | Alpine\(musl\)  | NO     |
| Fedora\(GLIBC\) | Fedora\(GLIBC\) | YES    |

enable the CGO will bring the system c lib to the binary.  
for more indepently, we should make the file static linked

**Comment by chisaato** [comment]
![image](https://user-images.githubusercontent.com/17796830/98445751-5ca1a900-2154-11eb-8042-afd00193ce6b.png)

```bash
❯ go build -ldflags="-s -w" -o wings-cgo
❯ CGO_ENABLED=0 go build -ldflags="-s -w" -o wings-no-cgo
❯ file wings-cgo
wings-cgo: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=uJTTqnOj66uULqxbSgzx/eDDvG4dDfju5eSpDG2Hz/gGEIYrOViv6_8rrzao_O/fk442xOtEbibVSY78OXv, stripped
❯ file wings-no-cgo
wings-no-cgo: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=UlLhjus0TlQaQGK_5KJy/jwX-su7S9bVLXWCK3lPI/gGEIYrOViv6_8rrzao_O/IcnecY1-rxEipp81dLxS, stripped

```
here is the comparation about enable and disable the `CGO`
