### ISSUE TITLE
Delay in schedules makes a schedule stuck in processing mode until being removed

### ISSUE THREAD

**Issue by OpenSource03** [pterodactyl/panel#2672]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.3
* Server's OS: Debian 9
* Your Computer's OS & Browser: Safari, macOS

**Describe the bug**
Adding a delay in schedules does not work.

**To Reproduce**
1. Go to schedules
2. Create a new schedule
3. Name it whatever you'd like, set it at any time...
4. Create a new task with a delay of 0
5. Create a new task with a delay of 30
6. Run it, it will be stuck under processing and execute the command with delay 0, the command with delay 30 will never be executed...

**Comment by GravityCube** [comment]
![image](https://user-images.githubusercontent.com/31770111/98452948-bbeec180-2132-11eb-91b9-1491ed8c5f9a.png)
![image](https://user-images.githubusercontent.com/31770111/98452952-c90bb080-2132-11eb-8d19-467b14b0d4a0.png)
I just tried to reproduce it and it works as intended. Did you add the cron task? https://pterodactyl.io/panel/1.0/getting_started.html#queue-listeners

**Comment by OpenSource03** [comment]
Yeah, seems to be working for me as well now... Weird... I'll close it for now and reopen if I'm able to reproduce it again.
