### ISSUE TITLE
Unable to open admin settings

### ISSUE THREAD

**Issue by kareemfakhuri** [pterodactyl/panel#2673]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.3
* Server OS: Debian 10
* Your Computer's OS & Browser: Windows 10/Google Chrome

**Describe the bug**
I am having an issue accessing the admin settings section of the panel. I simply can't open admin settings to edit node settings, etc. Admin settings used to work just fine up until I added the following to the beginning of the conf file in sites-available:
`server {
return 403
}`
I'm not sure if that's the cause, but I added it to allow panel access from a single domain. Tried removing it and restarting but that didn't fix it.
I also checked nginx and daemon logs, all empty.

**To Reproduce**
1. Log in using admin user.
2. Click on 'admin settings'
3. Redirects to user settings page instead.

![l5bW6GSCRc](https://user-images.githubusercontent.com/73457418/98459860-dc3b7200-216c-11eb-9c2d-1e0009be9ea8.gif)

**Expected behavior**
Has anyone had this issue before? I'm just trying to get it working again and I don't know what to do.
Really appreciate any input!

Edit: **SOLVED**
The issue wasn't related to nginx. I had setup 2FA for admin and then temporarily disabled for third party maintenance, which was the cause of the problem. Re-enabling 2FA was the solution.

**Comment by parkervcp** [comment]
If I am reading this right, you changed the nginx conf file to 403 on /servers and now you can't reach the admin pages?

**Comment by kareemfakhuri** [comment]
> If I am reading this right, you changed the nginx conf file to 403 on /servers and now you can't reach the admin pages?

Not changed, just added it as an extra server block to the top of the conf file so the panel is only accessible through the subdomain defined in server_name in the pterodactyl server block. Removing it and restarting nginx didn't fix it though.

**Comment by DaneEveritt** [comment]
I can't reproduce this and no one else has reported it, so I really don't know what to tell you. Its just a generic link element.

**Comment by kareemfakhuri** [comment]
**SOLVED**
The issue was that 2FA, which had been previously enabled, was temporarily disabled. For some reason that restricts access to admin settings. Re-enabling 2FA fixed it.

**Comment by jaspermayone** [comment]
I am having this issue without 2fa 🤔
