### ISSUE TITLE
Wrong server.jar version after reinstallation

### ISSUE THREAD

**Issue by DrakMC** [pterodactyl/panel#2676]
**Background (please complete the following information):**
* Version of Panel/Daemon:  1.0.3
* Server's OS: Debian 10

**Describe the bug**
When you reinstall the server, the latest server.jar is downloaded instead of the desired version.
PHP version: PHP 7.3.19-1~deb10u1
Daemon: Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/40771376/98476650-6f6cba00-21f6-11eb-8d91-b7201eb6c998.png)

![image](https://user-images.githubusercontent.com/40771376/98477375-ab078400-21f6-11eb-9741-6a3ea21b92b5.png)

**Comment by parkervcp** [comment]
If a version isn't valid it defaults to latest. It even says that in the variable description.

**Comment by DrakMC** [comment]
Fixed by reinstalling Egg.
