### ISSUE TITLE
Cannot edit any files on 1.1

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#2679]
**Background (please complete the following information):**
* Panel or Daemon:  Both
* Version of Panel/Daemon: 1.1
* Server's OS: Ubuntu (Docker build)
* Your Computer's OS & Browser: Windows and Linux Firefox

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: 7.4
Daemon: Linux gollum 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
1. Attempt to edit any text file in any folder including the base folder
2. get error page
Logs - https://gist.github.com/parkervcp/82593f7d6580dfd2d6401ed414ff0257

**Expected behavior**
Be able to edit text files.

**Comment by BillyDaPoop** [comment]
Am able to reproduce, but only for certain files.

**Comment by notAreYouScared** [comment]
Able to reproduce with log/ini/md/sh/bat files and hit and miss with txt
