### ISSUE TITLE
Separate Stop and Kill again

### ISSUE THREAD

**Issue by NickCloudAT** [pterodactyl/panel#2685]
**Is your feature request related to a problem? Please describe.**
Currently the "Kill" button will only show once you've already pressed the "Stop" button.

**Describe the solution you'd like**
Separate the two buttons like in 0.7.

**Additional context**
I'd like to have this because of the following scenarios I have encountered:

Let's say I play on a Minecraft Server and, for whatever reason, a whole bunch of TNT blows up destroying many things.
Back in 0.7 I just hit the "Kill" button and the explosion never happened because the World did not save on kill. Sure you might loose progress of the past few minutes.
But in the new Panel, once I hit "Stop", the Server most of the times has enough time to still save the world to disk BEFORE my kill signal gets through.

Yes yes yes BACKUP YOUR THINGS! I know and I do, but I cannot backup every 5 Minutes.

**Comment by GravityCube** [comment]
If that kind of problems are common for you maybe you should try a block logger like CoreProtect. I think that the buttons should be separated anyway.

**Comment by NickCloudAT** [comment]
> If that kind of problems are common for you maybe you should try a block logger like CoreProtect. I think that the buttons should be separated anyway.

It does not happen very often. Also I do also have modpacks (where coreprotect would not log many many mod items).

**Comment by DaneEveritt** [comment]
I won't be changing this functionality. If you want to have the stop button send a kill command to the instance you can always make a custom egg that sends `^C` rather than `stop`. Using a kill button like you are anyways seems more like an issue with how you're handling your server, and less to do with how the Panel operates.

**Comment by soshimee** [comment]
`^C` usually just does `stop` on most server softwares.
