### ISSUE TITLE
422 Error When Trying Read or Download A File In The Panel File Browser

### ISSUE THREAD

**Issue by dparkinson101** [pterodactyl/panel#2692]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.1.1
* Server's OS: CentOS 8
* Your Computer's OS & Browser: Windows 10 and Chrome

**Describe the bug**
This bug appears when trying to use the File Browser section on any server on the panel. When a file is clicked on to read or when right clicked to download it gives an error banner and a 422 error in the browser debug console which states:
```
{
code: "ValidationException"
detail: "The file field is required."
meta: {source_field: "file", rule: "required"}
rule: "required"
source_field: "file"
status: "422"
}
```

The underlying issue seems to be that the file name is not being set properly in the request to open / download it and so returns a validation error but I have not investigated enough to confirm this.

**To Reproduce**
1. Go to any server's "File Browser" section which has files in it
2. Click on any file to read it or right click and select the option to download it
4. See the returned error for the request in browser network debug and note that there is now an error displaying on the page mentioning the file field being required.

**Expected behavior**
Presumably when clicked the page should show what the file contains in plain text and when downloaded the file should begin to download.

**Comment by schrej** [comment]
I assume this doesn't occur with files that can be edited with the panel, at least when just clicking them?

**Comment by DaneEveritt** [comment]
I cannot reproduce this and haven't heard reports from anyone else reporting this.
