### ISSUE TITLE
View User's Details - Error 500

### ISSUE THREAD

**Issue by DrakMC** [pterodactyl/panel#2699]
* Version of Panel:  1.1.1
* Server's OS: Debian 10

**Describe the bug**
If I view the user's details in the administration, I get error 500.

Panel: PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
Daemon: Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

**Comment by GravityCube** [comment]
You need to add laravel logs (/var/www/pterodactyl/storage/logs) and wings logs (sudo wings diagnostics).

**Comment by DrakMC** [comment]
**/var/www/pterodactyl/storage/logs:**
https://0bin.net/paste/-RyjLGBj#ltLQ-AmGw5iubUxz7sZCWoRuHQQMoe1TFUaExVhysI+

**wings diagnostics:**
https://0bin.net/paste/LFjeGa7m#fI3Qk50yd1dvoKGtXYD-IPnkoE1ykOKf8sjFTVddVby

**Comment by matthewpi** [comment]
`cd /var/www/pterodactyl && chmod -R 755 storage/* bootstrap/cache/`

**Comment by DrakMC** [comment]
I upgraded the panel version incorrectly. It works now, thank you. :)
