### ISSUE TITLE
srcds -autoupdate parameter lock container from behing stopped

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#270]
Using `-autoupdate` parameter prevent the container from behind stopped, it's just restarted after 10 seconds. 
Using `-norestart` doesnt fix it.

Its annoying for updates as we need to manualy delete `/home/container/steamcmd/steamcmd.sh` to launch the update.

**Comment by DaneEveritt** [comment]
That sounds more like a source-engine thing that I can't really control from the panel itself. How do you normally stop a source server with autoupdate flags?

**Comment by jffz** [comment]
I usualy just stop the daemon, also `quit` should works but i need to test.

**Comment by jffz** [comment]
Just triied to use `quit` within a classic srcds process using `-norestart` and `-autoupdate`, it works, the server is shutting down properly.

**Comment by DaneEveritt** [comment]
Is that not the command being sent when using the stop button in the panel?

**Comment by jffz** [comment]
Well, after lookking into it, seems like srcds_run takes args in the order they are set. 
Solution is to put -norestart at the end of the start options.
