### ISSUE TITLE
Scheduled backup stores locally instead of configured s3 destination

### ISSUE THREAD

**Issue by tmunsch** [pterodactyl/panel#2700]
Panel or Daemon:  1.1.1
Version of Panel/Daemon: 1.1.1
Server's OS: Ubuntu 20.04 LTS
Your Computer's OS & Browser:  Chrome

**Describe the bug**
When a scheduled backup runs, the backup stores locally on the node even though the .env file is configured for s3. The backup goes to s3 when created manually from the Backup menu but stores locally if run through a schedule.
Panel: PHP 7.4.12
S3 Backup provider:Wasabi

1. enable s3 backups via .env file
2. verify backups are going to s3 storage
3. create scheduled task
4. add backup task
5. allow scheduled backup to run automatically
6. scheduled backup uses wings driver instead of s3 driver when running automatically but if you run the scheduled task manually via run now it stores it properly via s3

Expected behavior:
The backup is stored on the configured s3 backup endpoint

**Comment by DaneEveritt** [comment]
Restart your queue worker after making environment changes.

**Comment by tmunsch** [comment]
Thank you! That fixed it!
