### ISSUE TITLE
Servers not appearing on main page

### ISSUE THREAD

**Issue by bountythebeast** [pterodactyl/panel#2701]
This may be an isolated issue, so I apologize.

We currently have 20 servers running and connected to the panel, but only 18 show up on the main screen. There is no 'page 1 of 2' or any other form of showing more. The only way to see the other 2 servers in this case, is to go into the admin console and view servers there. I am a Panel Admin with 'Showing others servers' on. 

This isn't the most critical thing in the world but has caused some confusion between some of my associates and myself. Mostly just curious if this is a bug or an isolated issue that i've managed to bring upon myself in some way.

**Comment by revij** [comment]
Have you checked through another browser? I experienced something similar a while ago but after clearing cache+cookies everything looks good.

**Comment by bountythebeast** [comment]
I just tried it on both Chrome and Firefox before and after clearing cache+cookies and it still seems to be doing it unfortunately.

**Comment by revij** [comment]
Running with the latest version on both panel and wings?

**Comment by bountythebeast** [comment]
yessir

**Comment by parkervcp** [comment]
Can you at least share an example screenshot?

Also you filled out none of the requested information when you submitted this.
