### ISSUE TITLE
Wings: Failed to load server configurations

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2703]
* Version of Panel/Daemon: 1.1.1 (release)
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
![image](https://user-images.githubusercontent.com/28255085/99069580-ac063000-25bf-11eb-99e5-e3f2068be3ad.png)

I performed a clean install of the panel and wings, the error still appears

**Comment by parkervcp** [comment]
This looks like your wings install can't reach the panel properly

**Comment by DaneEveritt** [comment]
Yep, either something isn't being returned correctly because of a proxy returning something else or your Panel isn't actually on 1.1.

This isn't a bug, I've been running latest releases all night without issue.
