### ISSUE TITLE
Outgoing network issue

### ISSUE THREAD

**Issue by VibeGAMESNL** [pterodactyl/panel#2704]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.1.1
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Chrome

**Describe the bug**
I have 2 IPv4 addresses on my server. If you allocate the second IP adress to a server, the outgoing traffic (like a http request) will be routed via main IPv4 address and not the second IPv4 address. This is causing issues with several game servers like FiveM. (server listing issue)

A great guy @Dreae has posted a fix for this 2 years ago: https://github.com/pterodactyl/panel/issues/459#issuecomment-373942796
But it would be much cleaner if this was build into wings. Also alot of pterodactyl users are not aware of this fix.

With the fix of @Dreae: changing the primary port will brake everything and a reboot is required so a little tweaking is required.

I'm aware this may be a docker issue but let's help docker a little? <3

**To Reproduce**
1. Add a second IP to your network interface
2. Add an allocation in pterodactyl with the second IP
3. Create a server (for example FiveM)
3. Add the allocation to the new server.
4. Boot it up
5. Monitor the outgoing http request with tcpdump or someting like that.

**Expected behavior**
Outgoing traffic should be routed via the second IP address.

**Comment by parkervcp** [comment]
This has been covered many times and is a docker issues. The fix is to run wings in host network mode which loses the protections that docker offers for servers such as minecraft behind bungeecord.

What drae posted i running the container in host network mode if you read it.

**Comment by VibeGAMESNL** [comment]
> This has been covered many times and is a docker issues. The fix is to run wings in host network mode which loses the protections that docker offers for servers such as minecraft behind bungeecord..
What drae posted i running the container in host network mode if you read it.

Yes I understand like I said but there is an easy fix. I only ask to take a look at this fix and build it into wings? I posted a link in my  first comment.

**edit:**
Isn't drae running a docker container that just adds some extra iptable rules?
https://github.com/Dreae/docker-external-ip/blob/master/dockergen/update-iptables.tmpl

**Comment by DaneEveritt** [comment]
This needs to be implemented as a part of docker, I'm not adding anything that messes with the system networking, that's just asking for pain.

Assuming docker ever adds that support we can come back and implement such a feature.
