### ISSUE TITLE
Maintenance mode does not work

### ISSUE THREAD

**Issue by OpenSource03** [pterodactyl/panel#2705]
**Background (please complete the following information):**
* Panel or Daemon: panel
* Version of Panel/Daemon: 1.1.1
* Server's OS: Debian 9
* Your Computer's OS & Browser: macOS, Safari 

**Describe the bug**
I'm not sure if you're aware of this, but Maintenance mode does not work. 

**To Reproduce**
After trying to enable it, and hitting the save button, it automatically disables after the page refresh.

**Expected behavior**
The Maintenance mode should enable and not let any users enter their server panel if they are on the node with mm enabled.

**Comment by GravityCube** [comment]
It does enable it. It seems to take a few seconds and F5 to see that it was enabled (The admin dashboard is not using React). Regardless of that it doesn't have the effect that is suppose to have. The clients can still access their servers.

**Comment by GravityCube** [comment]
It seems that the maintenance mode is not implemented. I couldn't find anything related on wings and the Node model doesn't take maintenance into account so it is never sent to wings.
https://github.com/pterodactyl/panel/blob/c928214a833cb108cfbc4a06daa56af2ab573c56/app/Models/Node.php#L149-L175

**Comment by notAreYouScared** [comment]
Its not exported in the configuration. Never was exported in 0.7 either but its there
