### ISSUE TITLE
[Feature Request] Auto-focus on the command input field (console)

### ISSUE THREAD

**Issue by Feniksovich** [pterodactyl/panel#2706]
**Is your feature request related to a problem? Please describe.**
Every time I navigate to the server and I need to quickly run a console command, I first need to set the cursor focus to the command input field with the mouse. This is very inconvenient when working with multiple servers.

**Describe the solution you'd like**
I suggest making the cursor auto-focus on the command input field. After navigating to a specific server, the cursor will already be in the input field to quickly enter a command.

![capture](https://user-images.githubusercontent.com/33875970/99143063-e4237680-2684-11eb-9af3-8ef551c0c5cc.png)

**Comment by DaneEveritt** [comment]
https://github.com/pterodactyl/panel/commit/76e3bcaa4206423c4be4770736e6b8f84940b248

**Comment by DaneEveritt** [comment]
Duplicate https://github.com/pterodactyl/panel/issues/2528
