### ISSUE TITLE
Servers not showing CPU and RAM usage after system reboot

### ISSUE THREAD

**Issue by PouletteMC** [pterodactyl/panel#2707]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.1.1
* Server's OS: Ubuntu Server 20.04 
* Your Computer's OS & Browser: Windows 10 2004 - Chrome 86

**Describe the bug**
The CPU and RAM usage are not shown in the overview nor the server view

**To Reproduce**
1. Reboot the server while servers are online
2. Open the panel in a browser
3. See error
4. Restart servers 
5. It works

**Expected behavior**
The CPU and RAM usage should be show immediately and not require a game server restart to work.
Happens on both minecraft servers and NodeJS apps.

Can be reproduced 100% of the time

**Comment by PouletteMC** [comment]
Already reported

**Comment by GravityCube** [comment]
Reference: #2695
