### ISSUE TITLE
Unreadable text when resisting fingerprint in Mozilla Firefox

### ISSUE THREAD

**Issue by Maxximou5** [pterodactyl/panel#2708]
**Background (please complete the following information):**
* Panel or Daemon: **Panel**
* Version of Panel/Daemon: **1.1.1 & 1.1.1**
* Server's OS: **Ubuntu 18.04.4 LTS**
* Your Computer's OS & Browser: **Windows 10 & Firefox 82.0.3 (64-bit)**

**Describe the bug**
Setting `privacy.resistFingerprinting` to `true` results in text becoming unreadable. The text can be copied and pasted to become readable. The following console output is reported:

```
20:26:02.811 Blocked https://panel.real.website/server/f5f5b05f from extracting canvas data because no user input was detected. 19 vendors-console.e607f09b.js:1:88001
20:26:02.865 Blocked https://panel.real.website/server/f5f5b05f from extracting canvas data because no user input was detected. 93 vendors-console.e607f09b.js:1:163137
```

Panel: **PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:09) ( NTS )**

**To Reproduce**
1. Open Firefox
2. Go to `about:config`
3. Set `privacy.resistFingerprinting` to `true`
4. Go to Panel and any server console
5. See error

![Firefox-Fingerprint-Pterodactyl-Panel-Error](https://user-images.githubusercontent.com/5216374/99156690-ce30a880-26ba-11eb-97b2-f97cd90f8419.png)

**Expected behavior**
A normal display of text in the console.

**Comment by DaneEveritt** [comment]
Won't fix, the console requires canvas elements not be blocked in order to work. This is something you need to modify on your end to make it display.
