### ISSUE TITLE
Server booting errors result in broken console if root admin

### ISSUE THREAD

**Issue by notAreYouScared** [pterodactyl/panel#2709]
**Background (please complete the following information):**
* Panel or Daemon: Panel + Wings
* Version of Panel/Daemon: v1.1.1
* Server's OS: Ubuntu 20.04

**Describe the bug**
With the changes from pterodactyl/wings@08d1efb pterodactyl/wings@65664b6 & https://github.com/pterodactyl/panel/commit/009f9c297de000589778b493c080e3b4d5dcc20a when an error is sent to the console on the WebSocket it displays `There was an error validating the credentials provided for the WebSocket. Please refresh the page.` when really that fixes nothing other than if the end-user has an invalid token. If a root admin is trying to debug a server that's erroring on boot, the only way to see why is via the browser's console or looking at the wings logs. 

The error above also doesn't clear when navigating to other tabs. 

![image](https://user-images.githubusercontent.com/1757840/99157817-72eebe00-269a-11eb-9e20-78389110aeeb.png)
![image](https://user-images.githubusercontent.com/1757840/99157841-a6c9e380-269a-11eb-9452-1773df137e78.png)

**To Reproduce**
1. Give a server an invalid IP to bind to.
2. See you're given the red error at the top of the console page.
3. View browser console/wings logs.
4. See actual error :) 

**Expected behavior**
If the error is `jwt: created too far in past (denylist)` then show the error above, if not pass the error to the console if the user is a root admin.

Should be noted this is only if you're an admin, if you're a normal user you're greeted with the below when starting a server.

![image](https://user-images.githubusercontent.com/1757840/99157879-e85a8e80-269a-11eb-94fd-4436d73e4b42.png)

**Comment by ivanpmartell** [comment]
Hi, I keep getting this error on a fresh install no matter the egg being used or the ports that are allocated. Can you please let me know how to fix this. It is my first time using pterodactyl and wings. They are on separate servers and they can connect through ports 8080 and 2022. The installation works, but I cannot start the server (always getting this error).

**Comment by notAreYouScared** [comment]
Look at the browsers console when you click start it will tell you the error.

**Comment by ivanpmartell** [comment]
I get the exact same error message you're getting JWT validation error.

**Comment by notAreYouScared** [comment]
Then you're trying to bind to an ip address your machine doesn't have allocated to the network interface.

**Comment by ivanpmartell** [comment]
Is the allocation ip coming from the machine with wings or the one with the panel? I'm using the ip from the machine that has wings installed.
Okay, I found out that the allocations mean relative to the wings machine, therefore the allocation should be 127.0.0.1 (not the machines public ip) and a random port that is open to make it work. I was trying to start a discord bot. Hope this helps anyone else that gets lost in the documentation for this (or me in the future when I inevitably forget).
Thank you so much for your help btw.

**Comment by AlHadiHabib** [comment]
> Is the allocation ip coming from the machine with wings or the one with the panel? I'm using the ip from the machine that has wings installed. Okay, I found out that the allocations mean relative to the wings machine, therefore the allocation should be 127.0.0.1 (not the machines public ip) and a random port that is open to make it work. I was trying to start a discord bot. Hope this helps anyone else that gets lost in the documentation for this (or me in the future when I inevitably forget). Thank you so much for your help btw.

help me bro i am getting same problem and i am fully new user of pterodactyl. I am not good at English so i don't understand clearly what you say. i am trying to run Minecraft bedrock server.
