### ISSUE TITLE
Delete Backup Schedule

### ISSUE THREAD

**Issue by Clarkcj12** [pterodactyl/panel#2711]
I am frustrated that we have to manually delete backups.

**Describe the solution you'd like**
It would be nice if it was possible via the schedules to be able to automatically delete backups. Instead of manually doing them, to be able to fine grain the backups a bit more. Since we can automatically create backups on a schedule should be able to automatically delete them after a period of time, or daily so keep backups clean and rotated.

**Comment by DaneEveritt** [comment]
Does this accomplish what you want: https://github.com/pterodactyl/panel/pull/2691
