### ISSUE TITLE
Wings instance behind Cloudflare impossible to edit settings on if offline

### ISSUE THREAD

**Issue by DaneEveritt** [pterodactyl/panel#2712]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v1.1.2

Running Wings behind a Cloudflare proxy introduces a ton of pain if the Panel cannot communicate with Wings properly (especially if Wings is just offline entirely). This is normally handled because the connection is refused, however what happens is the Panel catches a CF 521 error, and therefore we just get slapped constantly because it doesn't fall back to the normal "save changes and tell the user to manually make edits" flow.

Should probably treat any 5XX error (other than maybe 500 specifically) as we do a connection failure, and just save the changes without the query going through.

Actually, any network request should probably do that if it fails, seems weird to completely block edits if something ends up incorrect.

**Comment by SpicyTakis** [comment]
This also happened with me just today as I have my wings instance proxied behind cloudflare.

**Comment by TekExplorer** [comment]
ive seen it happen multiple times. dunno why it didnt occur to me that that was the cause
