### ISSUE TITLE
One specific account has erros.

### ISSUE THREAD

**Issue by justinbea** [pterodactyl/panel#2713]
hey i have multiple accounts on the panel and only one has an error atm, the rest are fine, its saying the following error started on the main link were normally the servers are shown 
![image](https://user-images.githubusercontent.com/34838726/99179294-6b6ff900-271c-11eb-9529-e886f7145d8d.png)

logs from storage/logs/ laravel https://pastebin.com/gGNh7hAg

**Comment by notAreYouScared** [comment]
You missed one of the two steps in the install 

https://pterodactyl.io/panel/1.0/getting_started.html#set-permissions
or you didn't run `chmod -R 755 storage/* bootstrap/cache/` in the panels directory

**Comment by justinbea** [comment]
did that for sure even multiple times after installation due mail templates but to make sure did it again and still the same issue.
also other accounts are working fine only this account has this error listed. while many other accounts and servers are okay

**Comment by justinbea** [comment]
I have solved this idk how but new bug appeared I'll open a new issue for that.
