### ISSUE TITLE
Auto start

### ISSUE THREAD

**Issue by submgr** [pterodactyl/panel#2715]
I have a problem. I have a server where I have a plugin that stops the server after a certain amount of time if no one is playing. When the plugin stops the server, pterodactyl panel thinks it crashes and starts the server again .. what can I do to prevent the server from starting again after stopping?

It seems to me that in the server settings it should be possible to configure this, because not everyone needs to start the server after disabling it ...

**Comment by JakeySuccessor** [comment]
Maybe try to make it so the plugin sends stop in the console as a command so pterodactyl knows you are stopping it rather it just stopped?

**Comment by FoksVHox** [comment]
> I have a problem. I have a server where I have a plugin that stops the server after a certain amount of time if no one is playing. When the plugin stops the server, pterodactyl panel thinks it crashes and starts the server again .. what can I do to prevent the server from starting again after stopping?
> 
> It seems to me that in the server settings it should be possible to configure this, because not everyone needs to start the server after disabling it ...

If you believe this is a bug with Pterodactyl, I would recommend using the provided template, if not you should use the Pterodactyl Discord, where you can ask for support
