### ISSUE TITLE
The Docker socket is somewhere else, not /var/run/docker.sock

### ISSUE THREAD

**Issue by marfier** [pterodactyl/panel#2716]
How can I make Wings look for the Docker socket somewhere else other than `/var/run/docker.sock`? The Docker socket is not there in my system, but somewhere else.

**Comment by marfier** [comment]
Please note that I have asked this question in the support Discord numerous times, but then was advised to open as Issue. I also wanted to open this Issue in the Wings repo, but there is no Issues tab there.

**Comment by schrej** [comment]
set the appropriate environment variable correctly.

**Comment by fabm3n** [comment]
Check this docs entry: https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option

(there is not reason to give shrej a -1....)

**Comment by parkervcp** [comment]
@GalacticLion7 

If you filled out the issue template, we may have been able to help you.
