### ISSUE TITLE
Dynmap link suggestion

### ISSUE THREAD

**Issue by Misio12320** [pterodactyl/panel#2717]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Hey. Add a button if user have dynmap installed to forward user into this page under the disk stats.

**Describe alternatives you've considered**
I think its a good suggestion because I don't want to copy the sites URL and paste and combinate.

**Additional context**
Here a image.
![bandicam 2020-11-16 12-40-56-098](https://user-images.githubusercontent.com/42146429/99248821-62a92100-2809-11eb-8bab-af721e3ef266.jpg)

**Comment by parkervcp** [comment]
This is a very specific feature. This would only be useful to those running mc servers with dynmap.

We try to avoid game specific features like this.

I hope that explains why I am suggesting we close this.

**Comment by Misio12320** [comment]
Yeah, I mean people which use dynmap. Arlight them, I understand, feel free to close.

Edit. Oh, I have also a question. Can I make myself this option or this is not possible?

**Comment by M-AlNoaimi** [comment]
Why not instead of closing this, keep it as low priority and have one extra text field under the servers IP maybe that's configurable in the **Settings** or **Startup** pages of the server? 
In other words, if the user set it up that extra field would show up, if it's not configured then it stays as how it currently is in the screenshot above. 
What do you guys think? @parkervcp @Misio12320

**Comment by parkervcp** [comment]
Why not use the server description then? as that already exists.

**Comment by M-AlNoaimi** [comment]
I'd honestly assume it'd be for convince and aesthetic reasons, I would guess something that's specific to MC would be a good ease of access thing to have. Although the server description feature is still valid so.. 🤷

**Comment by DaneEveritt** [comment]
While a neat idea it does go again the "no heavily game specific features" line this project has always been run by. Appreciate the idea though, I just don't think it's the right fit for this project.
