### ISSUE TITLE
mounts dont seem to work

### ISSUE THREAD

**Issue by MilkMGN** [pterodactyl/panel#2721]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl
^ chat is too full up and if i get a response it is one time, and i dont get anything else unless i ask 5 times

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: both?
* Version of Panel/Daemon: latest (1.1.1)
* Server's OS: ubuntu 18.04
* Your Computer's OS & Browser: windows 10, firefox

**Describe the bug**
A clear and concise description of what the bug is. mounts do not show in the file manager of the server. i have no way to debug this myself as the docs dont have anything on mounts. i have posted at least 3 times in #help on the server asking about it and i got shown a document that didnt tell me anything. (https://cdn.discordapp.com/attachments/658550982975946762/778120483806904330/Screenshot_20201116-235237_Chrome.jpg)
Please provide additional information too, depending on what you have issues with: why cant we just use symlinks, or just point the plugin out of docker?
Panel: `php -v` (the php version in use).
PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
Linux sanctum 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Client:
 Debug Mode: false

Server:
 Containers: 18
  Running: 3
  Paused: 0
  Stopped: 15
 Images: 18
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-123-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.55GiB
 Name: sanctum
 ID: FFLH:TLAE:54Y6:RFYN:32XE:TFBD:MOLL:NIVE:RDYY:RDBO:H6MG:7PXI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**To Reproduce**
1. make mount
2. assign it to server
3. try to access mount

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
the mount works, or i can point dynmaps webdir to /var/www/mg_map

**Comment by sergejostir** [comment]
You can find your answer in the 4th point of the screenshotted text.

**Comment by matthewpi** [comment]
As said in the screenshot of what I posted on another issue, the contents are not visible on the web file manager or SFTP, this is 100% intentional.

**Comment by MilkMGN** [comment]
looked through that, assigned my mount to be in /map/mg on ptero's fs and point to /var/www/map_mg on the linux fs, but no dice. 
![image](https://user-images.githubusercontent.com/42798255/99474762-ee9d8300-2998-11eb-8d32-e98cbbba27de.png)

Dynmaps error:

```
[02:24:14 ERROR]: [dynmap] Exception while writing JSON-file - /map/mg/standalone/dynmap_world.json.new
java.io.FileNotFoundException: /map/mg/standalone/dynmap_world.json.new (Permission denied)
        at java.io.RandomAccessFile.open0(Native Method) ~[?:1.8.0_275]
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[?:1.8.0_275]
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[?:1.8.0_275]
        at org.dynmap.storage.MapStorage.setStandaloneFile(MapStorage.java:272) ~[?:?]
        at org.dynmap.JsonFileClientUpdateComponent$FileProcessor.run(JsonFileClientUpdateComponent.java:88) ~[?:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) ~[?:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[02:24:14 ERROR]: [dynmap] Exception while writing JSON-file - dynmap_world.json
[02:24:14 INFO]: [dynmap] Image file /map/mg/tiles/_markers_/basket.png - unable to write - failed
```

**Comment by MilkMGN** [comment]
back to commenting on this since my issue got locked. so much for being able to get support, the discord doesnt have anyone with a lot of knowledge a lot of the time and github seems to just be a one response to fix your issue and if it doesnt then the user is wrong and cant respond

**Comment by DaneEveritt** [comment]
Your issue was "mounts do not show in the file manager of the server" which @matthewpi pointed out is by design and not a bug, ergo this is not a bug report.

Your second issue has nothing specifically to do with Pterodactyl, and is an issue with the permissions on your specific mount point, likely because you have multiple different server processes all trying to read and write to said mount, which isn't going to work out well since all of the file permissions are all over the place.

**Comment by MilkMGN** [comment]
I have one server mounted to it, unless I have to not have any nodes
allowed to it?
