### ISSUE TITLE
Weird error during install

### ISSUE THREAD

**Issue by dylanmaniatakes** [pterodactyl/panel#2722]
Everytime i try to install I get this: 
![image](https://user-images.githubusercontent.com/24499681/99463505-ee9f7380-2903-11eb-95ca-5b0d9c1965ff.png)

when i type redis-server,  i get this output 
![image](https://user-images.githubusercontent.com/24499681/99463550-0545ca80-2904-11eb-9a33-a0fcdbb7f3fa.png)

I tried discord and no one could help. im at a loss and have been following the instructions to a letter this attempt was on a freshly formated ubunu server vm just to see if it was my actual server

**Comment by trenutoo** [comment]
Check the .env file in /var/www/pterodactyl , do you have anything in the REDIS_PASSWORD field or is empty?

**Comment by matthewpi** [comment]
That error is caused by you setting a value for the `REDIS_PASSWORD` when you don't have one configured.  To resolve this problem change `REDIS_PASSWORD=...` to be `REDIS_PASSWORD=null`.

Also for future reference, please ask for help in our Discord instead of creating an issue.
