### ISSUE TITLE
Node SSL certificate

### ISSUE THREAD

**Issue by WaterChick** [pterodactyl/panel#2725]
* Panel or Daemon: Panel/Deamon
* Version of Panel/Daemon: Panel - 1.1.1/Daemon - 1.1.1
* Server's OS: Debian 10 GNU/Linux 4.19.146-1  x86_64
* Your Computer's OS & Browser:  N/A

**Describe the bug**
* I have a problem with SSL, which won't change in node settings "Configuration", sometimes it replace the SSL variable in the config. This is the same problem for SSL files. I can change it in /etc/pterodactyl/config.yml and it works normally, but sometimes after restart it change ssl to false in the config.yml.

![Výstřižek](https://user-images.githubusercontent.com/65216786/99595396-f0952f80-29f4-11eb-90ac-5b3df4efb9fd.JPG)
![Výstřižek2](https://user-images.githubusercontent.com/65216786/99595397-f12dc600-29f4-11eb-960a-026a5d44830f.JPG)

**To Reproduce**
* I don't know

**Expected behavior**
* Already setted values
**Errors**
* N/A

**Comment by DaneEveritt** [comment]
What is the value of the proxy field below that in the panel?

**Comment by WaterChick** [comment]
When I set it to "Not Behind Proxy" it set ssl to true.

![proxy](https://user-images.githubusercontent.com/65216786/99603431-93ed4100-2a03-11eb-89ca-16848e1c3fa6.JPG)

**Comment by SpicyTakis** [comment]
Yes this is happening to me too. I have my nodes behind a cloudflare proxy and when I restart a wings instance it sets the wings instances' config to false, preventing access to servers on the node.

**Comment by DaneEveritt** [comment]
This is working as intended, "Behind Proxy" means the Panel should communicate with Wings using HTTPs but Wings is running behind an SSL-terminated proxy (e.g. flex SSL from CloudFlare). Set that back to `Not Behind Proxy` to enable SSL on wings.
