### ISSUE TITLE
/entrypoint.sh: line 11: ./samp03svr: Permission denied

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#2726]
After users upload server files including samp03svr(samp launch file) they get this error in console.

/entrypoint.sh: line 11: ./samp03svr: Permission denied

**Expected behavior**
File would automatically chmod so it could be executed ?

**Comment by BenasPaulikas** [comment]
Probably related to https://github.com/pterodactyl/panel/issues/901

**Comment by parkervcp** [comment]
This is definitely an issue with the uploading files and not setting permissions.

**Comment by BenasPaulikas** [comment]
Hmm I tried minecraft server and without execute permissions it was working okay.
However on samp server it needs execute permission. 

So when users upload samp03svr they need to chmod it. But I think not all users are pro ftp users :D ? Even in panel there's no chmod button.

@parkervcp thoughts?

**Comment by parkervcp** [comment]
They can change it using an sftp client like winscp or filezilla.

I have a samp server egg that doesn't need a user to upload the server files.

**Comment by DaneEveritt** [comment]
Sounds like something that just needs to be handled by the user in these specific cases, I can't reasonably know/guess what permissions to set on a file for booting. The image could also be adjusted to set those permissions before trying to execute the file.

This doesn't really strike me as a bug.
