### ISSUE TITLE
Cannot connect to the database using a nodejs/discrod.js script.

### ISSUE THREAD

**Issue by MS-DOS2** [pterodactyl/panel#2727]
Hello,
I have a problem with pterodactyl when I connect to the database via a script nodejs/discord.js on a server created it doesn't work ! while if I connect via phpmyadmin or other it works I tried a local connection in 127.0.0.1 and externally ip it doesn't work :/ do you know how I can fix it ?

**Comment by parkervcp** [comment]
All servers run in docker container. 

You need to configure your server to use 172.18.0.1 as the database address.


The docs cover how to configure mysql/mariadb

https://pterodactyl.io/tutorials/mysql_setup.html#creating-a-database-host-for-nodes
