### ISSUE TITLE
After creating a server via the API it does not appear on the assigned users dahboard

### ISSUE THREAD

**Issue by freddierick** [pterodactyl/panel#2728]
**Background (please complete the following information):**
* Panel or Daemon: 1.1.1
* Version of Panel/Daemon: 1.1.1
* Server's OS: Ubuntu 16
* Your Computer's OS & Browser: Chrome

**Describe the bug**
When you create a server via the API the server does not appear on the assigned user's dashboard however, the user account can access it directly via the server link e.g `/server/789dbcb4`  and it is visible in the admin panel (when signed in with an admin account). It is also not returned in the array when you request the `/api/application/servers` endpoint.

**To Reproduce**
1. create a new server via the endpoint (get a success message)
2. Sign in as the user that the server was allocated to
3. it is not visible on the dashboard  (when signed in with a user account)
4. it is visible on the admin panel  (when signed in with an admin account)
5. it is not returned from a request for all servers via the API

**Expected behavior**
the server is created and the user can see it on there dashboard

**Comment by RihanArfan** [comment]
Is the server owned by the user, or are they a subuser?

**Comment by freddierick** [comment]
the server is owned by the user

**Comment by DaneEveritt** [comment]
Neither @matthewpi nor myself could reproduce this when creating a server. This sounds more like the user needs to refresh the page in their browser.

**Comment by freddierick** [comment]
I thought that might be the problem too however it's not it is returned from a request for all servers via the API.
