### ISSUE TITLE
Allocations is not visually changed in network tab

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2729]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/1473bf9b8c0e09e82a08f1359ba8af8bcf173a07 & https://github.com/pterodactyl/wings/commit/40c70673cd6b853e7d68d8efcc66dc1daf87f629
* Version of Panel/Daemon: 1.1.1
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
Address selected in the network tab is not visually saved if you switch to another tab

1. Make primary any address
2. Click Backup tab
3. Click Network 

Changes in the Network tab were not saved, and the address on the console tab is not changed.

**Comment by trenutoo** [comment]
Yeah, I just tested and it only updates the next time you refresh the page. This issue also affects the maintenance mode toggle for a node.

**Comment by zefir-git** [comment]
Sounds like caching to me, given that it updates once refreshed
