### ISSUE TITLE
Replace SweetAlert Modals with AdminLTE Modals

### ISSUE THREAD

**Issue by schrej** [pterodactyl/panel#273]
I would prefer to use the AdminLTE modals instaed of the SweetAlert ones, just for consistency.

I'm not sure if it is possible to redesign the SweetAlert modals or if we would have to replace/reimplement SweetAlert and if it's worth the effort.

https://almsaeedstudio.com/themes/AdminLTE/pages/UI/modals.html

**Comment by MatthewSH** [comment]
You could always create your own SweetAlert theme.
