### ISSUE TITLE
The password length of the message is different

### ISSUE THREAD

**Issue by PJZ9n** [pterodactyl/panel#2732]
**Background (Obviously it has nothing to do with it, so I omitted some of it. Sorry)**
develop branch (10548c9d8fa79f10df915b9c4aaaa7aa98e42ad1)

**Describe the bug**
I thought the password length in the message was different.

passwords.php:
[least six characters](https://github.com/pterodactyl/panel/blob/10548c9d8fa79f10df915b9c4aaaa7aa98e42ad1/resources/lang/en/passwords.php#L14)

dashboard/account.php
[least 8 characters](https://github.com/pterodactyl/panel/blob/10548c9d8fa79f10df915b9c4aaaa7aa98e42ad1/resources/lang/en/dashboard/account.php#L10)

**Comment by schrej** [comment]
Translations are not currently used in 1.0, and those old ones won't be used once it gets added. It is easy to fix for people who are still on 0.7, but this is too minor for us to fix it.
