### ISSUE TITLE
PHP file extensions tries to render when creating a file

### ISSUE THREAD

**Issue by INfoUpgraders** [pterodactyl/panel#2733]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.x (latest of 0.7)
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Google Chrome

**Describe the bug**
When I try to create a file via the built in file editor with a .php file extension, it tries to render the php file.

**To Reproduce**
1. Create server and go to file editor
2. Create a file and name it anything with a .php extension.
2. Save the file
As you can see it says file not as it tries to render it

**Expected behavior**
For it not to try and render the php, to possible ignore the extension somehow.

**Comment by DaneEveritt** [comment]
Non-security related bugs with 0.7 will not be addressed as it is EOL.
