### ISSUE TITLE
Cannot connect (TLS handshake error)

### ISSUE THREAD

**Issue by fizzrepo** [pterodactyl/panel#2735]
**Server Info**
* Panel or Daemon: I don't know
* Version of Panel/Daemon: 1.1.1
* Server's OS: Ubuntu server 20.04
* Your Computer's OS & Browser: Windows 10 Pro Google Chrome 71.0.3578.80 (Official Build) (64-bit)

**Describe the bug**
![image](https://user-images.githubusercontent.com/58730469/100097990-433b7500-2e55-11eb-9e60-7200a8c57963.png)
I get this whenever i load my server.
![image](https://user-images.githubusercontent.com/58730469/100098027-53535480-2e55-11eb-9458-e38befcf84ec.png)

**To Reproduce**
1. Create a server
2. Go to your server
3. CTRL+SHIFT+I --> Console

**Expected behavior**
I think it is something wrong with Wings?

 INFO: [Nov 24 13:58:38.572] writing log files to disk path=/var/log/pterodactyl/wings.log
 INFO: [Nov 24 13:58:38.575] loading configuration from path path=/etc/pterodactyl/config.yml
 INFO: [Nov 24 13:58:38.576] configured wings with system timezone timezone=Europe/Berlin
 INFO: [Nov 24 13:58:38.577] checking for pterodactyl system user username=pterodactyl
 INFO: [Nov 24 13:58:38.579] configured system user successfully gid=997 uid=998 username=pterodactyl
 INFO: [Nov 24 13:58:38.580] fetching list of servers from API
 INFO: [Nov 24 13:58:51.288] processing servers returned by the API total_configs=1
 INFO: [Nov 24 13:58:51.291] creating new server object from API response server=xxxxx
 INFO: [Nov 24 13:58:51.294] registering event listeners: console, state, resources... server=xxx
 INFO: [Nov 24 13:58:51.295] finished processing server configurations duration=7.271987ms
 INFO: [Nov 24 13:58:51.314] loaded configuration for server server=xxx
 INFO: [Nov 24 13:58:51.316] configuring server environment and restoring to previous state server=xxx
 INFO: [Nov 24 13:58:51.350] configuring internal webserver host_address=0.0.0.0 host_port=8080 use_auto_tls=false use_ssl=true
 INFO: [Nov 24 13:58:51.364] sftp subsystem listening for connections host=0.0.0.0 port=2022
**2020/11/24 14:00:26 http: TLS handshake error from MY IP: EOF**

**Comment by fizzrepo** [comment]
Sorry if this is a simple mistake, I am quite new to Pterodactyl.

**Comment by trenutoo** [comment]
This is not a panel issue, rather a problem with your configuration. You should ask for assistance in the Discord channel and wait for someone to respond.

First I'd check that you have SSL installed for both the wings FQDN and the panel.

**Comment by fizzrepo** [comment]
Ok, I will dm you on discord. Thanks.

**Comment by trenutoo** [comment]
Do not DM me, use the publicly available help channels on the Pterodactyl Discord server
