### ISSUE TITLE
Clickable URLs in the server console

### ISSUE THREAD

**Issue by BillyDaPoop** [pterodactyl/panel#2736]
**Is your feature request related to a problem? Please describe.**
It's frustrating to have to click, and then select text on a moving console in order to get a link.

**Describe the solution you'd like**
Make clicking URLs in console automatically bring you to a new tab, similar to how it's done on discord.

**Describe alternatives you've considered**
Not making urls clickable.

**Additional context**
If feature is add, links there would be clickable and bring to a new page.
![image](https://user-images.githubusercontent.com/65975856/100134257-c69c9c80-2e3c-11eb-8042-1675725675b0.png)

**Comment by matthewpi** [comment]
To accomplish this it seems we just need to use https://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-web-links
