### ISSUE TITLE
Add the ability to add IP ranges to panel (like port ranges)

### ISSUE THREAD

**Issue by PeterP1212** [pterodactyl/panel#2738]
**Is your feature request related to a problem? Please describe.**
People who buy a lot of IPs have to manually add one by one...
**Describe the solution you'd like**
I definitely think it would be helpful for people who buy IPs in bulk to add a feature that allows one to add multiple IP ranges similar to port range functionality...
**Describe alternatives you've considered**
I mean this feature is kinda a have it or you don't... I do not think there are alternative solutions besides making the functionality similar to adding port ranges.
**Additional context**
Nope... Thank you for everything you do though!
P.S. I thought someone would have already made an issue about this, but from my research I do not see one so sorry if this has already been an issue...

**Comment by trenutoo** [comment]
You can already do this to add a block of ips, ex. 1.1.1.1/26

**Comment by JakeySuccessor** [comment]
You can already do it by specifying the IP block IP/30 for 4 IPs for example
