### ISSUE TITLE
Should be able to delete all allocations besides ones currently in use

### ISSUE THREAD

**Issue by PeterP1212** [pterodactyl/panel#2741]
**Is your feature request related to a problem? Please describe.**
Should not have to delete page by page
**Describe the solution you'd like**
Delete all allocations besides ones currently in use
**Describe alternatives you've considered**
No other solutions except deleting page by page which can take a while
**Additional context**
N/A

**Comment by trenutoo** [comment]
I don't have a panel on hand right now, but from what I remember there was a button for that next to the IP address text

**Comment by JakeySuccessor** [comment]
Do you mean in the admin menu?

if so you can delete it by clicking the red box which is in V1 and 0.7

![image](https://user-images.githubusercontent.com/41645610/100154724-19b33580-2eb7-11eb-849a-38d8e419e186.png)
