### ISSUE TITLE
Transferred files not removed after completion

### ISSUE THREAD

**Issue by JakeySuccessor** [pterodactyl/panel#2742]
**Background (please complete the following information):**
* Panel or Daemon: V1.1.1
* Version of Panel/Daemon: V1.1.1
* Server's OS: Ubuntu 18.04

**Describe the bug**
When you transfer the server from node 1 to node 2, it will put the files in /var/lib/pterodactyl/archives for node 2 which remains there even after the server finished transferring which keeps the archives there for no use using up space.

**To Reproduce**
Transfer a server from node 1 to 2.
Wait for it to complete transferring 
Check node 2 directory for the archive still there even after completing the transfer "/var/lib/pterodactyl/archives"

**Expected behavior**
After a transfer is completed it should delete the archive

**Comment by Gaeta** [comment]
Can repeat.
