### ISSUE TITLE
Moving back in directory using the move feature

### ISSUE THREAD

**Issue by JakeySuccessor** [pterodactyl/panel#2746]
**Background (please complete the following information):**
* Panel or Daemon: V1.1.1 
* Version of Panel/Daemon: V1.1.1 
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chrome & Windows 10

**Describe the bug**
You cannot move from /home/container/example1/file.html to /home/container/file.html but you can only move it and create extra folders ahead. ex. /home/container/example1/example2/file.html 
Previously in 0.7 you can move it to anywhere in the container so I am guessing it is a bug but not sure 100%

**To Reproduce**
Click on move on any file in the panel file management 

**Expected behavior**
You should be able to move files back and not just forward files.

**Comment by matthewpi** [comment]
Use `../` to move the file or folder up a directory.
