### ISSUE TITLE
Missing tzdata package in egg core:source image

### ISSUE THREAD

**Issue by Kurounin** [pterodactyl/panel#2748]
**Describe the bug**
Timezone is UTC as noted in https://github.com/pterodactyl/panel/issues/2630 and https://github.com/pterodactyl/panel/issues/2513 in all Source Engine eggs (for example Counter-Strike: Global Offensive).

I could not find the repository that is used to build that image (https://github.com/pterodactyl/images/tree/source hasn't been updated since June 2019).

**Expected behavior**
The **tzdata** package should be installed in the **quay.io/pterodactyl/core:source** image. It could also be missing in the other images, like **core;java**, although I didn't check.

**Comment by trenutoo** [comment]
Not related to a panel, this should just stick to the image PR

**Comment by matthewpi** [comment]
Please open an issue or PR on the [images](https://github.com/pterodactyl/images) repository for anything involving the Dockerfile or entrypoint of any images.
