### ISSUE TITLE
console resize issue

### ISSUE THREAD

**Issue by popcorn9499** [pterodactyl/panel#2749]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: panel 1.1.1 
* Server's OS: Panel: Ubuntu Server 18.04.5 4.15.0-124 Running apache 2.4.29
* Your Computer's OS & Browser: Windows 10 Google Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Essentially the console text does not resize to the console itself. some lines go off the side
```
PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
```

**To Reproduce**
1. Go to Server console page
3. Resize the webpage window to different sizes

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

I expect the text to fit to the console space and not go over the side [how it looks atm](https://photos.popicraft.net/u/files/11.58.11-26.11.20.png)

[how it should look.](https://photos.popicraft.net/u/files/11.58.31-26.11.20.png)

**Comment by DaneEveritt** [comment]
Cannot reproduce on Firefox or Chrome.

**Comment by popcorn9499** [comment]
Would it be possible to share any additional information to prove or disprove this issue? It may be something specific to the length of the line attempting to be displayed because those lines in console were quite large.
@DaneEveritt

**Comment by popcorn9499** [comment]
[how to reproduce in chrome](https://photos.popicraft.net/u/files/16.27.48-01.12.20-pmcVrHhyYS.mp4)

Could not reproduce in firefox. ~~so im wondering if the event to resize the xterm canvas to the space is accually occuring or not on firefox vs chrome~~

This seems to be absolutely what is happening

[output from chrome dev console](https://photos.popicraft.net/u/files/16.34.30-01.12.20-LkhUJ0O4b6.mp4)
[output from firefox dev console](https://photos.popicraft.net/u/files/16.35.20-01.12.20-OkWAJtl3Vx.mp4)
