### ISSUE TITLE
Invalid Regex on Ark

### ISSUE THREAD

**Issue by Fabricio20** [Pterodactyl/Panel#275]
Ark settings/control panel has an invalid Regex, `/^(\w\.*)$/`, both on the server and admin password field.

That regex limits the input to a single character only. (`a` will work `aa` will fail).

**Comment by schrej** [comment]
My RegEx is not that great but i'm pretty sure `\.*` allows 0..n of any character.

**Comment by ki2007** [comment]
How about `/^[\w\.]*$/` ?

**Comment by Fabricio20** [comment]
That works but don't forget to add the capture group.

`/^([\w\.]*)$/`

**Comment by DaneEveritt** [comment]
Fixed in https://github.com/Pterodactyl/Panel/commit/97cad1d55e234c9cf8c27184b47678d7ba244591#diff-2cdf53d8555853b659047fd9346dda77R237
