### ISSUE TITLE
_

### ISSUE THREAD

**Issue by emyfops** [pterodactyl/panel#2755]

**Comment by Edouard127** [comment]
And i have this

[2020-11-27 00:27:02] production.ERROR: GuzzleHttp\Exception\ServerException: Server error: `GET http://panel.rawanarchy.tk:8080/api/servers/303573b1-e34b-4de2-90da-c6405e48e91d/files/list-directory?directory=%252F` resulted in a `521 Origin Down` response:
<html>
<head><title>521 Origin Down</title></head>
<body bgcolor="white">
<center><h1>521 Origin Down</h1></center>
 (truncated...)
 in /var/www/pterodactyl/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

**Comment by matthewpi** [comment]
This error is caused when you use a different URL for accessing the panel on the client than wings does.

You can try modifying the `allowed_origins` option in the `config.yml` of wings to make sure the panel's url is allowed.

**Comment by Edouard127** [comment]
> This error is caused when you use a different URL for accessing the panel on the client than wings does.
> 
> You can try modifying the `allowed_origins` option in the `config.yml` of wings to make sure the panel's url is allowed.

Thank you it work

**Comment by GianlucaUlivi** [comment]
> This error is caused when you use a different URL for accessing the panel on the client than wings does.
> 
> You can try modifying the `allowed_origins` option in the `config.yml` of wings to make sure the panel's url is allowed.

I do confirm is now working for me too, I was still using the IP Address to connect to the Panel while Wings was (Correctly) using the URL, by using the URL too everything started working fine.
Here is how to configure the config.yml file to allow both IP and URL:
```
allowed_origins:
- http(s)://<URL>
- http(s)://<IP>
```
OR
`allowed_origins: ["http(s)://<URL>", "http(s)://<IP>"]`
And this will be automatically translated to the first version on the next Wings restart.

**Comment by h4ppyfox78** [comment]
doesnt work
