### ISSUE TITLE
Add the ability to add math expressions to variables in startup parameters.

### ISSUE THREAD

**Issue by JordanPlayz158** [pterodactyl/panel#2758]
**Is your feature request related to a problem? Please describe.**
When someone requests changing their java startup flags to add garbage collectors or use Aikar's optimized startup flags pterodactyl users need to lower the ram normally by 1-1.5G for the server to boot. The issue is (especially with a host) when you upgrade someone's server, you need to need to manually change the ram which when you have a lot of clients that can be quite time-consuming.

**Describe the solution you'd like**
I thought a good solution would to be able to add math expressions to the startup parameters, for instance
{{{SERVER_MEMORY}} - 1000} (The wrapped equation in {} represents there is a math expression to calculate)

**Describe alternatives you've considered**
I have considered to not allow the changing of startup flags.
I have also considered to make an addon for it although I lack the programming experience to modify the panel.

**Additional context**
I think this would be a good feature not only for minecraft but i'm sure there are many cases where doing math with variables would be beneficial in all games.

**Comment by parkervcp** [comment]
You can technically already do this in the panel as is. The start command is quite flexible as it's also a bash one liner.

You can do math in bash just fine with no issues.

**Comment by JordanPlayz158** [comment]
Thanks parker, for anyone in the future, I believe this is a good way to implement the math in bash to resolve the issue.
`java -Xms128M -Xmx$(({{SERVER_MEMORY}}-1000))M`
