### ISSUE TITLE
0.7.x -> 1.x.x Transition | No find and replace in text editor (CTRL+H)

### ISSUE THREAD

**Issue by mechite** [pterodactyl/panel#2759]
**Background:**
* Panel or Daemon: 1.x.x
* Version of Panel/Daemon: 1.x.x (all)
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Chromium (Custom skin with Opera GX theme and features + support for Windows program intergration, FULLY respects all Chrome rendering standards)

**Describe the bug**
Text editor doesn't have CTRL+H (Find and replace) like 0.7.x and is rather hard to quickly edit in.

**To Reproduce**
1. Create and open any text based file. YAML files are the standard.
2. Press CTRL+F
3. The replace box is missing.
4. Close find and try pressing CTRL+H (a working combo on the last editor)
5. No success.

**Expected behavior**
A find and replace box to open with regex support and standard UTF-8 support, allowing to replace text in a document.

**Comment by trenutoo** [comment]
It was replaced because the 0.7 editor had problems, was outdated, and had compatibility issues. Matthew and Dane pointed out in Discord that the functionality of the current CodeMirror editor can be extended once the new version of the editor is released.

**Comment by matthewpi** [comment]
https://codemirror.net/demo/search.html

It's a terrible way to go about find and replace but it is there.

**Comment by mechite** [comment]
> It was replaced because the 0.7 editor had problems, was outdated, and had compatibility issues. Matthew and Dane pointed out in Discord that the functionality of the current CodeMirror editor can be extended once the new version of the editor is released.

_This is true, the 0.7 editor is very outdated software._

Will the new editor implement all the features, 1:1? Also, will it have regexp support?

If they're going to extend CodeMirror I expect them to release extras too such as code reformatting (e.g YAML) so we can fix indentation and formatting before saving, context menu, etc.

I've seen some sites with an Eclipse Theia (I use this reference instead of Visual Studio Code as both are the same but Eclipse Theia is web based) styled editor. Does anyone know where this is from? It would be nice if this was used as it has all the functionality anyone could ever need and is legitimately the best way we could edit files.

However if this is not considered, PLEASE implement EVERYTHING modern editors have as they're there **_for a reason_** and all users will appreciate the inclusion of them.

**Comment by matthewpi** [comment]
> > It was replaced because the 0.7 editor had problems, was outdated, and had compatibility issues. Matthew and Dane pointed out in Discord that the functionality of the current CodeMirror editor can be extended once the new version of the editor is released.
> 
> _This is true, the 0.7 editor is very outdated software._
> 
> Will the new editor implement all the features, 1:1? Also, will it have regexp support?
> 
> If they're going to extend CodeMirror I expect them to release extras too such as code reformatting (e.g YAML) so we can fix indentation and formatting before saving, context menu, etc.
> 
> I've seen some sites with an Eclipse Theia (I use this reference instead of Visual Studio Code as both are the same but Eclipse Theia is web based) styled editor. Does anyone know where this is from? It would be nice if this was used as it has all the functionality anyone could ever need and is legitimately the best way we could edit files.
> 
> However if this is not considered, PLEASE implement EVERYTHING modern editors have as they're there **_for a reason_** and all users will appreciate the inclusion of them.

The editor you are referring to is [Monaco](https://github.com/Microsoft/monaco-editor) which is not very easy to integrate as a simple text editor.  I'd happily take a look into it when I get more time, but we also have the option of making our own extensions/modifications around CodeMirror.

**Comment by DaneEveritt** [comment]
I don't really see why we need to ship and embed an _entire_ file editor with the Panel, that seems like solving a case for a small percentage of users while negatively impacting user experience (via JS bundle size and feature complexity) for most every other user. Every file editor is going to have some missing features/confusion for some percentage of users, but I really am not that concerned with such issues.

My opinion and design philosophy is that complex file editing should not be done via the web.

**Comment by mechite** [comment]
Pterodactyl API? If we could have a system of authenticating to access a whole account externally we could have some better things e.g. CLI similar to git for pushing files. SFTP is _really_ inconvenient which is the reasoning behind the use of web solutions.

**Comment by BrainStone** [comment]
Those aren’t advanced editor functions but basic ones. Even Windows XP’s Notepad had a search and replace function.

**Comment by DaneEveritt** [comment]
Unless it is an easy change to the editor we're using I'm not putting any times towards building it out.

**Comment by mechite** [comment]
I feel like there is definitely a good compromise you can make considering a lot of users like to manage their servers from devices like their phones, including me, and I do not wish to open a full editor on my phone just to make one small change to let's say, a value, or broken message. On my PC, I personally use Sublime Text over Visual Studio Code and it opens literally instantly allowing for quick editing, and I tend to not worry about web editors.

It isn't required however small functions such as find & replace are useful, regex isn't even needed as stuff like that would be classified as "complex" in most terms.

You only need syntax highlighting, find and replace, and configurable indentation. Nothing else is required to have an editor that people can use for quick edits. I also liked how save had a keybind in 0.7.x where pressing CTRL+S instantly saved the file, but not even that is needed at all, I just want basic editing in the browser, else it's impossible to make quick modifications to software and we may as well just have SSH always open to open every single config in tools like vim, nano or mcedit.

**Comment by mechite** [comment]
![image](https://user-images.githubusercontent.com/50027352/105744814-84273700-5f35-11eb-9502-9b9edf41ec3e.png)
I have noticed that the features from https://codemirror.net/demo/search.html are available on the panel but I would honestly add something like a preview for these keybinds for the average user or actually have a better keybind set that people are used to (i.e. CTRL+F, CTRL+H, and then on screen buttons for replace next and replace all)

The issue can remain closed because of this however I would like to see UX improvements in the future honestly.

**Comment by matthewpi** [comment]
> ![image](https://user-images.githubusercontent.com/50027352/105744814-84273700-5f35-11eb-9502-9b9edf41ec3e.png)
> I have noticed that the features from https://codemirror.net/demo/search.html are available on the panel but I would honestly add something like a preview for these keybinds for the average user or actually have a better keybind set that people are used to (i.e. CTRL+F, CTRL+H, and then on screen buttons for replace next and replace all)
> 
> The issue can remain closed because of this however I would like to see UX improvements in the future honestly.

I plan on upgrading that editor to CodeMirror 6 once it is more ironed out which improves a lot of problems with the current one, until then I am not spending anymore time trying to improve the editor.
