### ISSUE TITLE
Error Socket.io

### ISSUE THREAD

**Issue by DaedalusPrime97** [Pterodactyl/Panel#276]
Hello, 

I don't know if this problem has been logged before but I cannot seem to find it.

I got a problem with either my Daemon or SSL, I'am having this error which is displaying on the bottom-right corner of my screen: We were unable to connect to the main Socket.IO server, there may be network issues currently. The panel may not work as expected.

I don't know what this error means, can someone help me with it?

Thank you in advance!

I also have this error when starting the daemon: 

Error: ENOENT: no such file or directory, open '/etc/letsencrypt/live/mc.example.com/fullchain.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/srv/daemon/src/http/restify.js:50:64)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by schrej** [comment]
Disable SSL on the daemon or generate letsencrypt certificates and set the correct certificate paths.

**Comment by DaedalusPrime97** [comment]
So did that now I'am getting this error: 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/root/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /root
7 error Linux 4.4.0-59-generic
8 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
9 error node v6.9.4
10 error npm  v3.10.10
11 error path /root/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/root/package.json'
16 error enoent ENOENT: no such file or directory, open '/root/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]

**Comment by schrej** [comment]
well you'll have to run `npm start` from the directory you installed your daemon in, `/srv/daemon` in case you followed the guide.

**Comment by DaedalusPrime97** [comment]
Well I think I can call myself dumb now :(, Thank you very much haha, It works! 💃

**Comment by DaedalusPrime97** [comment]
One more question though, when I enter this URL: www.domain.com/panel/ I appear to get a Kitten with a error 404. I think I need to change that somewhere, do you by any chance know that?

**Comment by schrej** [comment]
You cannot install the panel into a subfolder, it has to be at the root of the (sub) domain at the moment

**Comment by DaedalusPrime97** [comment]
Aha well hmm, because I thought I could run a website next to it aswell

**Comment by schrej** [comment]
Just add a subdomain like `panel.domain.com`

**Comment by DaedalusPrime97** [comment]
So how do I do that in the panel, I got it setup at my domain registrat

**Comment by schrej** [comment]
you have to reconfigure your webserver

**Comment by iwhosts** [comment]
npm config set prefix /srv/daemon
