### ISSUE TITLE
Server stuck in Connecting state

### ISSUE THREAD

**Issue by Riddler76** [pterodactyl/panel#2761]
Hello Guys, i do a new install of Ptero. I have an issue with the server console, she stuck in Connecting state :/
HTTP/2 500 Internal Server Error , in navigator console

![image](https://user-images.githubusercontent.com/8199973/100515460-b6f2c000-317c-11eb-9ba7-c1225f728b62.png)

**Comment by Riddler76** [comment]
Wings log :

 INFO: [Nov 28 14:46:13.195] registering event listeners: console, state, resources... server=e7951470-78a7-4cfa-b411-2b0bab3dec6e
 INFO: [Nov 28 14:46:14.600] beginning installation process for server server=e7951470-78a7-4cfa-b411-2b0bab3dec6e
 INFO: [Nov 28 14:46:16.103] creating install container for server process install_script=/tmp/pterodactyl/e7951470-78a7-4cfa-b411-2b0bab3dec6e/install.sh server=e7951470-78a7-4cfa-b411-2b0bab3dec6e
 INFO: [Nov 28 14:46:16.207] running installation script for server in container container_id=b3924839fe62b1d1cbf6216ac9ee51fe5ae9c93c467f9470b4cca81d049135f6 server=e7951470-78a7-4cfa-b411-2b0bab3dec6e
 INFO: [Nov 28 14:46:34.625] completed installation process for server server=e7951470-78a7-4cfa-b411-2b0bab3dec6e


Install log :

Setting up ca-certificates (20200601~deb10u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Updating certificates in /etc/ssl/certs...

**Comment by DaneEveritt** [comment]
Please follow the required template that yells at you in all caps to complete when opening bug reports.
