### ISSUE TITLE
Pterodactyl Panel on CPanel 

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#2764]
Hi,

Can you add a tutorial for installing Pterodactyl Panel on CPanel?

It would be very useful.

Thank you in advance.

**Comment by M-AlNoaimi** [comment]
I don't think ptero is even installable on cPanel...

**Comment by matthewpi** [comment]
Installing Pterodactyl on cPanel is technically possible but requires the host to provide console access.  As only a very small minority of users will ever even think about installing Pterodactyl on cPanel, I don't see the benefit in writing documentation for it, especially if it requires modification to cPanel itself.
