### ISSUE TITLE
FR: Automatic allocation based on location availability when creating servers

### ISSUE THREAD

**Issue by zefir-git** [pterodactyl/panel#2765]
**Is your feature request related to a problem? Please describe.**
Currently, you can only create servers on specific nodes. Many utilise pterodactyl to offer clients hosting solutions and this context, usually clients are prompted to select a location. Using the Pterodactyl API, you need to loop all nodes on that location, check their allocation usage, and based on that pick a node.

**Describe the solution you'd like**
It would be great to be able to tell Pterodactyl what the desired location upon server creation is and let it pick a node. This would make the usage of the API significantly easier with the content given. This should not by any means replace the option to manually choose a node.

**Describe alternatives you've considered**
The only alternative at this time is to loop all nodes on the desired location, save their usage into the RAM and then find the one with the lowest usage.

**Additional context**
It might be more suitable to add this functionality to `/api/application/locations` and it to return a node ID so that the server creation endpoint need not be modified. Additionally, it would be nice to also set criteria such as `lowest memory usage`, `lowest disk usage`, `lowest number of servers`, etc.

**Comment by TrixterTheTux** [comment]
You're already able to choose allocation automatically based on the location with the `deploy` array (https://github.com/pterodactyl/whmcs/blob/master/pterodactyl/pterodactyl.php#L391-L395) instead of `allocation` array.
