### ISSUE TITLE
Cannot add database to panel.

### ISSUE THREAD

**Issue by opiepl** [pterodactyl/panel#2766]
**Background (please complete the following information):**
* Panel and daemon: latest
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
After installing database host for nodes (following instruction on this site: https://pterodactyl.io/tutorials/mysql_setup.html#creating-a-database-host-for-nodes I cannot add database in my panel. Error code: There was an error while trying to connect to the host or while executing a query: "SQLSTATE[HY000] [2002] Connection timed out (SQL: SELECT 1 FROM dual)"

**To Reproduce**
1. Go to 'admin control panel'
2. Click on 'databases'
3. Add database

**Comment by DaneEveritt** [comment]
This is not a bug with this software, please use [Discord](https://discord.gg/pterodactyl) for further assistance.

**Comment by opiepl** [comment]
> This is not a bug with this software, please use [Discord](https://discord.gg/pterodactyl) for further assistance.

I used, nobody knows how to help me.
