### ISSUE TITLE
FR: Option to delete oldest backup when creating a new one via schedule tasks

### ISSUE THREAD

**Issue by zefir-git** [pterodactyl/panel#2769]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to set up limited automatic backups via Pterodactyl alone. When trying to create a new backup, and the server has reached its limit, the following exception is generated:

> Cannot create a new backup, this server has reached its limit of *n* backups.

**Describe the solution you'd like**
It would be great to have a checkbox or switch of any sort to allow a `Create backup` task to delete the oldest backup for the target server. Another solution would be to be able to manually create a task of a new type `Delete backup` or `Delete oldest backup`.

**Describe alternatives you've considered**
Automatically deleting backups at this time is only possible via an external cron job. The issue with that is that not all users may want their backups deleted at this frequency (e.g. if they don't create backups via tasks and only manually).

**Comment by notAreYouScared** [comment]
Was already added from https://github.com/pterodactyl/panel/pull/2691
