### ISSUE TITLE
Allow backups to be stored on a different server or in the cloud

### ISSUE THREAD

**Issue by Gaeta** [pterodactyl/panel#2770]
**Is your feature request related to a problem? Please describe.**
If users create backups of lets say a 50gb server twice thats a 100gbs used + the 50gb of the server it self. This can get costly for hosting companies

**Describe the solution you'd like**
Allow the panel to have storage servers that just hold backups to make sure servers have enough space to run the users servers.

**Describe alternatives you've considered**
It should be allowed to use cloud servers like AWS cloud storage.

**Additional context**
I think a lot of people would like this feature as storage servers are "cheap" and it would help with downloading backups to remove strain off the server it self. Also I think its a cool feature that people would enjoy.

**Comment by TekExplorer** [comment]
Pterodactyl 1.0 already supports s3 compatible storage

**Comment by parkervcp** [comment]
As for the other option for using other servers you can already use something like a network mount to store on another server.

**Comment by RihanArfan** [comment]
> As for the other option for using other servers you can already use something like a network mount to store on another server.

Adding to this, you can also run Minio on the other server.

**Comment by Gaeta** [comment]
> Pterodactyl 1.0 already supports s3 compatible storage

How?

**Comment by trenutoo** [comment]
Backup location is specified in the wings config file, a driver is set to local by default. You can change it to s3 for enabling s3 off-site backups

**Comment by TekExplorer** [comment]
> > Pterodactyl 1.0 already supports s3 compatible storage
> 
> How?

quick doc i made for [enabling s3](https://g.oaka.xyz/pterodactyl/s3-backups/)

**Comment by almir101** [comment]
Would be nice that users can select their own remote server to backup servers as optional.
Sometimes they want to clone their server for their own stuff and would be nice to have option to store it on remote server at UCP, via ftp/google drive.
