### ISSUE TITLE
Inactive server stats

### ISSUE THREAD

**Issue by JustinPooters** [pterodactyl/panel#2772]
**Describe the solution you'd like**
on the stats page it would be handy to see what server hasn't been started in over 2 weeks or something related so "free" hostings that use this panel can review those

**Describe alternatives you've considered**
On the online / offline stats Show which servers are offline and for how long

**Additional context**
It would be pretty self-explainiatoring, for questions reply here i guess?

**Comment by RihanArfan** [comment]
This feature has a benefit for only a tiny group of people, in my opinion, and something that could be implemented externally through the API or be integrated by a 3rd party.

**Comment by DaneEveritt** [comment]
Agree with @LeCodeCo, I don't see a huge benefit to a majority of users by adding this.
