### ISSUE TITLE
Scanner error on server install causes install to fail

### ISSUE THREAD

**Issue by astro-angelfish** [pterodactyl/panel#2773]
**Background (please complete the following information):**
* Panel or Daemon: https://github.com/pterodactyl/wings/commit/20ece60a72d3591bcbb1332426016226aada0ff1 and https://github.com/pterodactyl/panel/commit/085fa8dcb502ea5fbe9c8664c78d11b9b042f022
* Version of Panel/Daemon: 1.1.1
* Server's OS: CentOS 8 for panel, Stream for wings
* Your Computer's OS & Browser: Arch linux kernel 5.9.10-arch1-1 & Firefox 83.0

**Describe the bug**
We have met some error while install server.

When we try to install a server, it says:
```
WARN: [Dec  1 22:17:46.675] error processing scanner line in installation output for server container_id=acc5d07b23cb006034c3d58ed029e60b1417bb4d4baa1f051af8e520cd472220 error=bufio.Scanner: token >
Stacktrace:
github.com/pterodacty1/wings/server.(*InstallationProcess).StreamOutput
                /home/runner/work/wings/wings/server/install.go:503
github.com/pterodacty1/wings/server.(*InstallationProcess).Execute.func2
                /home/runner/work/wings/wings/server/install.go:461
runtime.goexit
                /opt/hostedtoolcache/go/1.15.2/x64/src/runtime/asm_amd64.s:1374
```
and
```
output for server container_id=acc5d07b23cb006034c3d58ed029e60b1417bb4d4baa1f051af8e520cd472220 error=bufio.Scanner: token too long server=108f39b6-c531-4a78-ae91-4260379cac63
```
Later the panel shows the server is installed, but if we try to start the server, it would say `There was an error validating the credentials provided for the websocket. Please refresh the page.` and there is some error in console like `Error: Request failed with status code 409` and in network like 
```json
{
    "errors": [
        {
            "code": "ConflictHttpException",
            "status": "409",
            "detail": "Server has not completed the installation process."
        }
    ]
}
```

Anyway we cannot join the server with a Minecraft client.

Our panel and daemon is **not** on the same server, I don't know if it is the cause of the problem.

Panel: 
```
# php -v
PHP 7.4.11(cli) (built: Sep 29 2020 10:17:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```
Daemon: 
```
# uname -a
Linux ht-server-gdgz-126 4.18.0-240.el8.x86_64 #1 SMP Fri Sep 25 19:48:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
and
```
# docker info
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 2
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Flysystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765aba0d05254012b0b9e595e995c09186427f
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-240.el8.x86_64
 Operating System: CentOS Stream 8
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.18GiB
 Name: ht-server-gdgz-126
 ID: 7M5C:A56Z:DTNO:RTQL:5BY5:DPR4:3WRP:VVEA:OEGT:IMJG:4HCL:4Q2Y
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**To Reproduce**
1. Install the panel on a server, and install the daemon on the another server.
2. Configure them to make them connected.
3. Enter the admin control panel via panel server
4. Create a new server with any configure you want, but don't select the `Skip Egg Install Script` box
5. Wait for the installation of the server
6. Check out the log via `journalctl -xe`, you could see the error log. 

**Expected behavior**
The server should be properly installed and there should be no error in the system log.

**Comment by matthewpi** [comment]
Running the panel and wings on different servers would not be the cause of this problem, that is actually how Pterodactyl was designed to be ran.

From what I can tell, something during the install process wrote a line large enough to fill an entire buffer which caused the `bufio.Scanner: token too long` error.
