### ISSUE TITLE
[Wings] Cannot have same port on different interfaces

### ISSUE THREAD

**Issue by rugter100** [pterodactyl/panel#2775]
So basically i tried having a server with ports opened to the local and public ip at the same time so my bungeecord can access the server from inside the same server but also from the outside. When doing this we noticed that the docker would only grab one of the interfaces. A friend of mine looked into the code and found that it can probably be fixed here: https://github.com/pterodactyl/wings/blob/5bead443ad23b279f2d6383a04ecb3fa6a116d27/environment/allocations.go#L48

Im not sure if this is intentional but it has caused issues for me. I was able to use the global interface for both bungeecord instances without a firewall enabled but this causes security issues.

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/wings/pull/72
