### ISSUE TITLE
Missing variable value on server start

### ISSUE THREAD

**Issue by Kurounin** [pterodactyl/panel#2778]
**Background (please complete the following information):**
* Panel version: 1.1.1
* Version of Daemon: wings 1.1.1
* Server's OS: Debian GNU/Linux 10 (buster)
* Your Computer's OS & Browser: Windows 10, Google Chrome 86.0.4240.198 (Official Build) (64-bit)

**Describe the bug**
I made a copy of the default egg Counter-Strike: Global Offensive to add more variables in the start-up command. After upgrading panel from version 0.7 to 1.1.1 and from nodejs daemon to go wings, I noticed that for the servers associated with this egg the variable `SRCDS_MAP` is sometimes empty when server is started, which requires going to startup tab, clicking inside the SRCDS_MAP variable input and pressing enter to resave the value, which will then be used on the next server restart.
Panel:
```
# php -v
PHP 7.4.12 (cli) (built: Nov  3 2020 14:31:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
```
Daemon:
```
# uname -a
Linux panel3 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
```
```
# docker info
Client:
 Debug Mode: false

Server:
 Containers: 24
  Running: 21
  Paused: 0
  Stopped: 3
 Images: 13
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-12-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.791GiB
 Name: panel3
 ID: MHBS:3G2E:VY4N:R2AW:3FPB:NJ76:CHQA:BL6E:6V5R:GOHI:MSPT:POOW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**To Reproduce**
1. Go to Server Console and start the server
![image](https://user-images.githubusercontent.com/2346482/101128648-c94f7c80-3608-11eb-9776-63bacd5e7cd7.png)
2. Go to Startup and check current command
![image](https://user-images.githubusercontent.com/2346482/101128429-51815200-3608-11eb-998b-fa0f4e684131.png)
3. Check the current variables in database
![image](https://user-images.githubusercontent.com/2346482/101128457-63fb8b80-3608-11eb-8286-b0cb1323c6dc.png)
![image](https://user-images.githubusercontent.com/2346482/101128473-6d84f380-3608-11eb-82e0-c635e0ab4352.png)
4. Restarting the server any number of times does not help
5. Click map input in Startup and press Enter key
6. Go to Server Console and restart the server
![image](https://user-images.githubusercontent.com/2346482/101128603-b2108f00-3608-11eb-8b62-abebc7697d45.png)

**Expected behavior**
Map value should have been used when starting the server, without requiring resaving the variable.

**Comment by Maelep** [comment]
Are you working on this bug?

**Comment by matthewpi** [comment]
Is anyone still able to reproduce this?

**Comment by matthewpi** [comment]
Closing as there has been many changes regarding server configuration between the Panel and Wings.  If anyone is able to reproduce this on the latest version of the Panel and Wings, please reply to this issue and it will be re-opened.
