### ISSUE TITLE
Panel requests to API work for creating servers, etc, but does not work for editing files in the panel

### ISSUE THREAD

**Issue by RalphORama** [pterodactyl/panel#2788]
## Background (please complete the following information):

* Panel or Daemon: Connection issue between the two
* Version of Panel/Daemon: both 1.1.1
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Firefox Developer Edition, Windows 10
* `uname -a`: `Linux estrone 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* `php -v`:

```
PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
```

## Describe the bug

I just freshly installed Pterodactyl Panel and the Wings Daemon v1.1.1 on my Ubuntu 20.04 server. Now that I have successfully set up a node and created my first game server, I find that I am unable to edit files in the web-based control panel. This is not an issue for any other functions. I am able to create schedules, create subusers and databases, etc.

The URL the panel directs me to is 

```
https://cp.friendos.club/server/f5cdab43/files/edit/#/canyon.yml
```

## To Reproduce

Perform a clean installation, make a mistake I'm somehow missing, and you'll have this problem.

## Expected behavior

File browsing, editing, etc functionality works in the web panel

**Comment by RalphORama** [comment]
## More logs:

- `wings diagnostics` https://ptero.co/tiyoboziwo
- `tail: cannot open '/var/www/cp.friendos.club/storage/logs/laravel-2020-12-05.log' for reading: No such file or directory`
- wings.log: http://bin.ptdl.co/24j2p

## More info

After doing more digging, I've found that the issue seems to be with the request itself. If I watch the network monitor when trying to access files, I get this error:

![image](https://user-images.githubusercontent.com/6566104/101262517-6b588d00-370d-11eb-978c-119d27bd0d4a.png)

![image](https://user-images.githubusercontent.com/6566104/101262526-7dd2c680-370d-11eb-841f-4157a647fcf7.png)

**But,** for a directory listing of `/` (which **does** work), the following request occurs:

![image](https://user-images.githubusercontent.com/6566104/101262558-be324480-370d-11eb-863a-309d4fdb10a0.png)

![image](https://user-images.githubusercontent.com/6566104/101262563-d1451480-370d-11eb-8fc5-83462df2fc59.png)

**Comment by DaneEveritt** [comment]
Please show the response of the failing request. 👍

**Comment by RalphORama** [comment]
For editing a file (`GET contents?file=/eula.txt`):

![image](https://user-images.githubusercontent.com/6566104/101385507-e47cef00-3889-11eb-80b5-a8e97d9964e2.png)

For a subdirectory listing (`GET list?directory=world`): https://hastebin.com/juyeguxipo.json

**Comment by DaneEveritt** [comment]
My best guess is that you have a proxy or something that is stripping `?file=` off the request since it works completely fine for me and just about every other user.
