### ISSUE TITLE
Allow eggs to specify multiple docker images to be used, allowing a user to select from the list

### ISSUE THREAD

**Issue by alliraine** [pterodactyl/panel#2790]
Add a Java Selector for Minecraft eggs since Java 8 is at EOL.

This could be done by having a drop down selector to select docker image or by have a selector for what startup to use if the image had multiple version of java installed. 

Ps: you're welcome @DaneEveritt ❤️

**Comment by TekExplorer** [comment]
why not go all out and give eggs the ability to have drop-down selections for variables?

**Comment by DaneEveritt** [comment]
Because those are two completely different suggestions. ;)

**Comment by TekExplorer** [comment]
ah, good point docker image isnt the same as a variable ig :sweat_smile: 
i do think it would make usability increase by adding it though

**Comment by DaneEveritt** [comment]
Closed in https://github.com/pterodactyl/panel/commit/78c4ac80bc6a9ddd401220673a72f788a75acb46, https://github.com/pterodactyl/panel/commit/638ea2e81550bd3ab4d47d6c6c968e4e947f94ab, and https://github.com/pterodactyl/panel/commit/5bbb36b3cf94a2a56ea1a5f6b5a59b483d0fc024
