### ISSUE TITLE
When I set IP address for allowed IP on client the API not work

### ISSUE THREAD

**Issue by andris155** [pterodactyl/panel#2793]
**Background (please complete the following information):**
* Panel or Daemon:  Panel
* Version of Panel/Daemon: Panel 1.1.1
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Windows 10, Google Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
```
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```
When I set IP address for allowed IP on client the API not work.
https://pastebin.com/Wx0nKXdr

**To Reproduce**
1. Go to account menu.
2. Click to API Credentials menu.
3. Create API key with ALLOWED IP.
4. Use the API.
5. See error
<img width="481" alt="Capture" src="https://user-images.githubusercontent.com/8324198/101294334-ea85b800-3816-11eb-8794-9a20444ee480.PNG">

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
When I set IP address for allowed IP on client the API works.

**Comment by DaneEveritt** [comment]
https://github.com/pterodactyl/panel/pull/2684
