### ISSUE TITLE
[FileManager] Encoded folder name is displayed

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2794]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/009f9c297de000589778b493c080e3b4d5dcc20a & https://github.com/pterodactyl/wings/commit/af9ed4bff1cb65c822634e3a9a7e1f40c1098bce
* Version of Panel/Daemon: 1.0.3
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**

The encoded folder name is displayed in breadcrumbs (after refresh page) `ааааааааааааа`

![image](https://user-images.githubusercontent.com/28255085/101298479-35b3c100-383f-11eb-8cb7-0b6d897491c3.png)

**Comment by DaneEveritt** [comment]
This is a complete nightmare and I'm honestly ready to just give up on it and say if you name your files with crazy characters you're gonna end up with a broken name in the output.

I got it like 80% working, but the moment they start to contain `%` characters and the like shit breaks down. Pretty sure thats next to no one though, so I'll at least get it working with "normal" special characters.

(For reference, I've probably spent close to 10 hours between multiple issues like this just fixing one thing only to break another, I'm pretty done with it.)

**Comment by DaneEveritt** [comment]
closed in one of many commits related to https://github.com/pterodactyl/panel/commit/5d03c0d2e593e226067ed6bfb35a867bd432ee5a
