### ISSUE TITLE
High iowait and memory usage when creating backups

### ISSUE THREAD

**Issue by kakduman** [pterodactyl/panel#2798]
**Is your feature request related to a problem? Please describe.**
Backing up to an HDD causes huge spikes in iowait, which can slow servers down.

**Describe the solution you'd like**
I'd like the limit the speed at which they read/write to the HDD. wings is currently trying to sustain 100-200M/s reads/writes for an HDD backup, which just isn't viable. There may be a better way to handle this than simply limiting read/write speeds, but I'm not sure what it would be.

**Describe alternatives you've considered**
I think the alternatives would be to either disable backups for users with an HDD or to simply pay a few bucks to upgrade from an HDD to an SSD. Still, I think it'd make sense for wings to handle this in a way that won't lag servers.

**Additional context**
iotop output for two separate backups:
![image](https://user-images.githubusercontent.com/43528123/101324854-76f0a480-3830-11eb-81aa-fefa54cf8a34.png)
![image](https://user-images.githubusercontent.com/43528123/101324872-7b1cc200-3830-11eb-98dc-ada9a8929d71.png)

**Comment by kakduman** [comment]
Thanks Matthew for the PR that'll fix this issue :)

I think I realized an associated bug with it and just wanted to mention that because I had already typed an explanation and didn't see the harms in pasting it here:

Basically, you can cause the server to have an iowait spike in the 80+% range and force containers over to swap by sustaining backups to HDDs for long enough.

When you start a backup to an HDD, the cache will slowly increase. Eventually, there will be 0 RAM available, and it'll all be cached + used. This is normally fine since I'd expect used memory to take priority over cached memory, which is what normally happens. Interestingly enough, though, cached memory continues to increase and now used memory decreases. Servers are forced to switch over from memory to swap, even if 0 swap is allocated, since the server's memory runs out.

Then, all servers on the node have a huge lag spike while they switch from RAM to swap for necessary processes in order to make space for cache used for the backup. iowait can reach 80+% during this time.

Clearing the cache with `echo 1 | sudo tee /proc/sys/vm/drop_caches` makes RAM available, and servers switch back from swap to regular RAM. iowait also decreases.

Using this knowledge, a temporary solution is to create a cronjob to clear the cache every minute. This prevents the cache from building above ~20GB, meaning that you'll be safe unless you have <20GB free. I am consistently able to reproduce the error without the cronjob and consistently unable to reproduce the error with the cronjob. It's a temporary solution and the permanent solution is probably limiting backup speeds through Matthew's PR.

**Comment by matthewpi** [comment]
> When you start a backup to an HDD, the cache will slowly increase. Eventually, there will be 0 RAM available, and it'll all be cached + used.

A solution to this might be to limit the memory usage of wings itself (this could be achieved by running wings in Docker) in order to prevent it from caching the entire system memory which it will end up doing if a big enough server is being backed up.

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/wings/commit/8e29ffed50648926ec4e9ed7559ffdfa3eb0596c

**Comment by kakduman** [comment]
I thought I'd provide an update after my few days of testing with that new PR: I love it! It solves 90% of the problem I was having. Thanks so much! :)

Regarding running wings in docker: I set up wings in docker (with the help of parkervcp and TekExplorer), but putting it in a container causes iowait to shoot up even higher than it is without the container. iowait went to 50+% basically 24/7 even when wings wasn't using all of the 8G its container was allocated. I'm not sure why. With that said, while it prevents the system from running out of memory, and while it prevents the containers from switching to swap, it does not prevent iowait lag caused by wings. Overall, game servers running on the panel are rendered unplayable, with TPS on Minecraft servers dipping down to the single digits when a backup is created. The overall effect on performance is just about the same as not limiting backup speed at all and running it outside of a container.

The best solution I've found is to limit backup speed to 50MB/s in addition to creating a cronjob to clear the cache every minute. This prevents the system from running out of memory provided that about 20GB are free, and it prevents iowait from getting too high. Iowait still sometimes spikes at around 50%, causing servers to have a lag spike, but it does not render the games they're running unplayable since it happens infrequently. I've found that it happens most often when starting or when concluding a server backup. 

At the moment, I'm just manually creating backups by running `tar czf backup.tar.gz /var/lib/pterodactyl`, and that seems to keep iowait below 10% and minimize lag. Cache grows, but it behaves as expected and does not force containers over to swap.

**Comment by kakduman** [comment]
After a day of testing, it looks like this solution resolves all issues previously associated with high iowait/mem usage. Backing up a 60GB server does not force servers over to swap and iowait never rises above 15% when speed is not throttled. It can be lowered even further by throttling speed.

Thanks so much for working on this :)
