### ISSUE TITLE
Console not rendering properly on Firefox

### ISSUE THREAD

**Issue by akiraveliara** [pterodactyl/panel#2799]
Panel: Panel v1.1.3
Server's OS: Debian 10
Your Computer's OS & Browser: Windows 10 Build 2004, Firefox 83.0
PHP version: PHP 7.3.19-1~deb10u1

The console's text bar gets hidden behind the text field, see attachment 
![here](https://user-images.githubusercontent.com/61018569/101332008-091a9c00-3875-11eb-872d-4634e23babd8.png)

On Chromium-based browsers like MS Edge or Google Chrome, the console works just fine.
![fine.](https://user-images.githubusercontent.com/61018569/101332105-2485a700-3875-11eb-9859-87213ebcf8f6.png)

**Comment by matthewpi** [comment]
Cannot reproduce (v1.1.3, as of now that is also the latest develop build, UI was compiled using `yarn build:production`)

```
OS: Windows 10 Pro 2004
Browser: Brave [v1.17.75, Chromium: 87.0.4280.88 (Official Build) (64-bit)]
--
OS: Windows 10 Pro 2004
Browser: Firefox Developer Edition 84.0b8 (64-bit)
--
OS: Windows 10 Pro 2004
Browser: Firefox 83.0 (64-bit)
--
OS: macOS Big Sur 11.0.1 (amd64)
Browser: Firefox Developer Edition 84.0b7 (64-bit) and 84.0b8 (64-bit)
--
OS: macOS Big Sur 11.0.1 (amd64)
Browser: Firefox 83.0 (64-bit)
```

**Comment by DaneEveritt** [comment]
I also use firefox for all development stuff and I've never seen this?

**Comment by akiraveliara** [comment]
This seems to be related to the font size settings, i couldnt reproduce it with font size > 13 but for lower browser font sizes it became more and more apparent:
font size 9: 
![image](https://user-images.githubusercontent.com/61018569/102017055-ccfba580-3d64-11eb-8f3b-1ab36e45ca40.png)

font size 15:
![image](https://user-images.githubusercontent.com/61018569/102017059-d97ffe00-3d64-11eb-83e4-15660d3d63f8.png)

**Comment by DaneEveritt** [comment]
I'm not worried about it in that case.
