### ISSUE TITLE
Ability to transfer servers between nodes

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#280]
It should be possible to transfer servers between nodes easially from the panel.

A first idea was to select the new node, ip and port, zip up the server, transfer it to the new node, unzip it and set it up. Also keep the old server backed up or validate everything with some checksum.

**Comment by DaneEveritt** [comment]
Duplicate of #18

**Comment by schrej** [comment]
Oops, didn't see that one, sorry.
