### ISSUE TITLE
Add a toggle for default behavior on stop (halt vs. restart)

### ISSUE THREAD

**Issue by kNoAPP** [pterodactyl/panel#2802]
**Is your feature request related to a problem? Please describe.**
Servers stop for a wide variety of reasons. Some due to crashes, many due to manual commands. The default behavior in Pterodactyl is to halt when this occurs. When the programs closes, a manual start request needs to be made by a user logged into the Panel. I 100% realize the termination of these programs **is not** Pterodactyl's fault, but I'm frustrated in how manual intervention is required to restart the server.

**Describe the solution you'd like**
I'd like a toggle that defines the default behavior when a server is stopped outside the panel (i.e. crashes, manual /stop, etc.). The first toggle is "stop" and will maintain the same behavior currently in the panel. The second toggle is "restart" and will attempt to restart the instance automatically.

**Describe alternatives you've considered**
The same behavior can already be achieved by manually adding restart logic in and making the start command point to that file. While this works, it unfortunately breaks the "Stop/Restart" requests on the panel. The script, by definition, never stops so this breaks Pterodactyl's halt logic and status indicator. A properly-timed kill request needs to be made to stop the script.

I just feel like there's a better way to do this.

**Additional context**
Obviously, this new behavior would mean crash-loops become a possibility. So some guidelines like two manual stops in 60s will default to halting the server, requiring manual intervention.

**Comment by trenutoo** [comment]
Pterodactyl will attempt to restart the server automatically already upon a detected crash state?

**Comment by kNoAPP** [comment]
> Pterodactyl will attempt to restart the server automatically already upon a detected crash state?

It's not fool-proof though, and it leaves out manually initiated stopping like typing /stop in Minecraft.

**Comment by parkervcp** [comment]
That is a know issue and people complained when it was fixed to just stop the server. We could of course just stop it using the panel.

**Comment by matthewpi** [comment]
Is this not covered by `detect_clean_exit_as_crash`?

From the code comments in wings
```go
// Determines if Wings should detect a server that stops with a normal exit code of
// "0" as being crashed if the process stopped without any Wings interaction. E.g.
// the user did not press the stop button, but the process stopped cleanly.
DetectCleanExitAsCrash bool `default:"true" yaml:"detect_clean_exit_as_crash"`
```

**Comment by kNoAPP** [comment]
I didn't know this setting existed, it solves what I need changed. Thanks. 

However, I still think it could be expanded upon. The setting applies automatic restarting to every server on the node. What if you wanted control over this on a per-server basis? Food for thought.
