### ISSUE TITLE
Locking Backups

### ISSUE THREAD

**Issue by TASelwyn** [pterodactyl/panel#2803]
**Is your feature request related to a problem? Please describe.**
Revolving backups is great, but being able to keep/snapshot key points in a servers timeline can be good. 
This could be useful for a server wipe, or a big event, or maybe just "start of server"

**Describe the solution you'd like**
Being able to "lock" a backup. In such circumstance, the "delete latest backup" system will skip over it and leave it be.

**Describe alternatives you've considered**
Backing up to an alternative place outside of pterodactyl

**Additional context**

**Comment by parkervcp** [comment]
is this not what a backup rotation would already do? Which is built into the panel already?

**Comment by matthewpi** [comment]
> is this not what a backup rotation would already do? Which is built into the panel already?

They want to be able to lock a backup so if it is the oldest it will not be rotated, but instead the oldest non-locked backup will be rotated.  It's basically a way of keeping old backups on the panel instead of downloading them which could be useful once backup restoration is implemented.

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/panel/commit/5d5e4ca7b1e46d005785c1899678c3b7f0257004
