### ISSUE TITLE
add the ability to right click on a backup and open menu prompt

### ISSUE THREAD

**Issue by tmunsch** [pterodactyl/panel#2804]
Much like the feature in file manager where you don't have to click on the bubbles to open a menu you can just right click. Same thing just for the backups. 
![image](https://user-images.githubusercontent.com/27962004/101435186-e1115400-38d9-11eb-9705-ed0551c13538.png)

**Comment by DaneEveritt** [comment]
I don't like overriding default behavior of the cursor, it is only done in the file manager because that is the most logical operation. It seems like overkill on any other page.

**Comment by DaneEveritt** [comment]
Thinking about this more I'm not sure overriding the default mouse behavior for things is really the best idea. I only do this for the file manager because, well, it is a file manager where that is a very normal thing. I don't think it makes a ton of sense for backups though.
