### ISSUE TITLE
Schedule gets stuck/locked at "Processing" when you have two or more tasks

### ISSUE THREAD

**Issue by smcclennon** [pterodactyl/panel#2806]
**Background:**
* Panel or Daemon: **Panel**
* Version of Panel: **1.1.3**
* Server's OS: **Fedora Workstation 33**
* Your Computer's OS & Browser: **Fedora Workstation 33**, **Firefox 83**

**Bug description**
When there are two or more tasks in a schedule, when the schedule is run, the first task will run/execute, but the rest will not, and the schedule will be stuck/locked in the "Processing" status (previously being "Active" before the schedule ran)

**To Reproduce**
Steps to reproduce the behaviour:
1. Visit the schedule creator for your server (`domain.com/server/xxxxxxxx/schedules`)
2. Click `Create Schedule` and fill in the fields with any valid data, (and click the small `Create Schedule` button on the bottom right of the popup` to create the schedule)
3. Visit the schedule you just created, and add two (or more) `Send Command` tasks (time offset does not matter)
4. Click `Run Now` on the bottom right.
5. Your schedule should now be stuck with the "Processing" status.

**Temporary fix**
These fixes will get the schedule out of the "processing" status, however the schedule will become stuck/locked when it next runs, and **only the first task in the schedule ever runs/executes**.
1) Edit your database (setting `schedules` -> `is_processing` to `0`).
2) Toggle the schedule's "Enabled" off, save the schedule, and then toggle "Enabled" back on.

**Expected behaviour**
All tasks within the schedule to be ran/executed, and then for the schedule status to exit "Processing", and return to its previous state (for example "Active").

**Comment by DaneEveritt** [comment]
IS your queue worker running correctly?

**Comment by smcclennon** [comment]
My `pteroq.service` was failing to start:
```
systemd[1]: pteroq.service: Start request repeated too quickly.
systemd[1]: pteroq.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Pterodactyl Queue Worker.
```

I tried `systemctl reset-failed && systemctl start pteroq`, but the same error occurred.

The strange thing was I was able to run the `ExecStart` command from `/etc/systemd/system/pteroq.service` with success.

I then had a look inside `pteroq.service`, and saw this:
```
# On some systems the user and group might be different.
# Some systems use `apache` or `nginx` as the user and group.
User=www-data
Group=www-data
```
I am using nginx on Fedora (following CentOS documentation), so I changed `www-data` to `nginx` for both `User` and `Group`.

`systemctl start pteroq`, Success!

My schedules and the tasks within them now perform as expected.
