### ISSUE TITLE
Typo in Bug Report "installating"

### ISSUE THREAD

**Issue by mav2020** [pterodactyl/panel#2808]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: n/a
* Version of Panel/Daemon: n/a
* Server's OS: n/a
* Your Computer's OS & Browser: Windows 10 Edge

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
I know we delete it before adding bugs, but the text reads "For assistance installating this software..." at the top of the Bug Report. It should read "For assistance installing this software..."
Sorry if this isn't the right place to put this.
**To Reproduce**
1. Go to 'github'
2. Click on 'New Issue'
3. Scroll down to 'the top of the Bug Report'

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
It should read "For assistance installing this software..."

**Comment by TASelwyn** [comment]
"For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl"

Should say
"For assistance installing this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl"

It should also, imo, reference the pterodactyl guide's because "assistance installing this software" should be redirected to the website unless they are having issues with a particular step then they ask for help.

**Comment by DaneEveritt** [comment]
You can just open a PR to fix that.

**Comment by mav2020** [comment]
Oh, sorry, how do I do that?
    On Tuesday, December 8, 2020, 10:19:15 PM EST, Dane Everitt <notifications@github.com> wrote:  
 
 


You can just open a PR to fix that.

**Comment by trenutoo** [comment]
> Oh, sorry, how do I do that? On Tuesday, December 8, 2020, 10:19:15 PM EST, Dane Everitt <notifications@github.com> wrote: You can just open a PR to fix that. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

You'd have to search on Google how to create a pull request, however, there is already one created to resolve the typo and it was merged like 10 minutes ago

**Comment by mav2020** [comment]
Ok, thanks. I wasn't sure if there was a specific way for pterodactyl panel. I will google it for future use. Thanks for all the hard work. Sorry for putting that in the wrong place.

    On Tuesday, December 8, 2020, 11:01:30 PM EST, Alex <notifications@github.com> wrote:  
 
 



Oh, sorry, how do I do that? On Tuesday, December 8, 2020, 10:19:15 PM EST, Dane Everitt notifications@github.com wrote: You can just open a PR to fix that. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


You'd have to search on Google how to create a pull request, however, there is already one created to resolve the typo and it was merged like 10 minutes ago
