### ISSUE TITLE
Node server list: individual usage details

### ISSUE THREAD

**Issue by MassimoDeLuca** [pterodactyl/panel#2809]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, Feature was removed with 1.0 release.

**Describe the solution you'd like**
On the Nodes > Servers Page, the re-addition of individual server's usage details such as CPU, RAM, Disk that was previously shown on 0.7. ([0.7 preview](https://gyazo.com/cdf09ec0757a0ae5fd200b4a897901c2)) 

**Additional context**
This was very useful in the past for tracking down high usage server's on specific nodes.

**Comment by DaneEveritt** [comment]
This will not be changed at this time and will require the admin area React rewrite be completed.
