### ISSUE TITLE
Clean up Model code

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#282]
The current models are effective, but are using mostly blacklisted columns, rather than an explicit list of whitelisted columns. This is a security fix.

We also need to go through and check all the controllers and clean them up to use explicit `collect()->only()` or `$request->only()` methods to avoid any potential field injections. This risk is mitigated on the front-end by the way we do things, but theoretically possible on the back-end.

**Comment by schrej** [comment]
We should also add some more getters for stuff like hashed IDs, just for good measure.
