### ISSUE TITLE
File not showing up in the panel. Throws error in console and in wings.

### ISSUE THREAD

**Issue by SpicyTakis** [pterodactyl/panel#2854]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: v1.1.3
* Server's OS: Ubuntu 20.04.1
* Your Computer's OS & Browser: Windows 10 / Chrome

**Describe the bug**
Trying to load a certain file on the panel file manager throws a error in the console and in wings. This started happening after I added a `public` folder to my files. Then after a restart of the server I could no longer access the file. I can still access all other files using the file manager though.
![image](https://user-images.githubusercontent.com/67237931/101856445-562b9600-3b33-11eb-857e-564cb0607481.png)
https://ptero.co/uwaruginom

**To Reproduce**
1. Access the file in the file manager

**Expected behavior**
The file being accessed contents would show up on the panels file manager.

**Comment by matthewpi** [comment]
As shown in the browser console, there was a 500 error while loading the file, the errors in wings has nothing to do with fetching the file.  Nobody else has this problem, including myself; so I'm assuming there is a problem with your setup.  Check your panel logs
