### ISSUE TITLE
Boolean with "true" and "false" doesnt work

### ISSUE THREAD

**Issue by OxygenLack** [pterodactyl/panel#2857]
* Panel
* Version of Panel/Daemon: 1.1.3
* Server's OS: Linux v2202010131063129336 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
* Your Computer's OS & Browser: Windows 10 v2004 (build 19041.630) Chrome (87.0.4280.88)

Please provide additional information too, depending on what you have issues with:
I tried to add a variable as an boolean for Nest configurations which should require "true & false".
When I tried to set a server up it said that I the variable should be "true" or "false". But it clearly is true. 0 and 1 work normally...

PHP-Version: PHP 7.3.19-1~deb10u1
Docker Version: Docker Inc., v0.9.1-beta3

1. Go to Nest Eggs
2. Create a variable with a required boolean and save
3. Go to Servers
4. Create a Server with the created Nest Egg and enter the required boolean as true/false

Expected behavior:
Accepting true or false as valid boolean. (It accepts 0 and 1)
![boolean](https://user-images.githubusercontent.com/67149453/101896760-c2e17780-3ba9-11eb-9598-86aa149c4248.png)
![booleanerror](https://user-images.githubusercontent.com/67149453/101896755-c07f1d80-3ba9-11eb-9d6d-92ebf69fbda8.png)

**Comment by DaneEveritt** [comment]
This is working as intended: https://laravel.com/docs/7.x/validation#rule-boolean

String "true"/"false" are not accepted under the `boolean` rule in Laravel.

**Comment by trenutoo** [comment]
> This is working as intended: https://laravel.com/docs/7.x/validation#rule-boolean
> 
> String "true"/"false" are not accepted under the `boolean` rule in Laravel.

Unless I'm blind it states that it indeed accepts them.

The field under validation must be able to be cast as a boolean. Accepted input are true, false, 1, 0, "1", and "0".

**Comment by sergiz** [comment]
true and false as values, not as strings ("true", "false").
```php
is_bool('true');
// => false
```

**Comment by sergiz** [comment]
true doesn't equal "true".

**Comment by sergejostir** [comment]
Your input is a string, so "true" or "false" and these are not accepted.

**Comment by schrej** [comment]
Shouldn't this then just be a Checkbox or Dropdown instead of a textbox?

**Comment by DaneEveritt** [comment]
Probably, yes, but that is unrelated to this issue specifically (and there is an open issue somewhere about adding those types of fields).

@Software-Noob the `true` and `false` in the docs refer to boolean, not string literals. `(bool)"true"` and `(bool)"false"` in PHP will always give you `true`.
