### ISSUE TITLE
Redundant greater-than sign (u003e) in console output 

### ISSUE THREAD

**Issue by Orhideous** [pterodactyl/panel#2862]
**Background:**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.1.3
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: not relevant, reproducible on all browsers

**Describe the bug**
When I start the Minecraft server all new lines are interspersed with the symbol `>`.
![Screenshot_20201212_145724](https://user-images.githubusercontent.com/2265184/101984642-60f93e80-3c8b-11eb-9a2d-5cb610274462.png)
It is not seen in `latest.log`. It is also absent when launching the process from the console.
![Screenshot_20201212_150410](https://user-images.githubusercontent.com/2265184/101984634-5179f580-3c8b-11eb-9856-2bd6a5dd04db.png)
Interestingly, when refreshing the page old lines in the log are displayed correctly - extra symbol > is displayed **only after the new ones**:
![Screenshot_20201212_145820](https://user-images.githubusercontent.com/2265184/101984661-779f9580-3c8b-11eb-8a13-6370291c756c.png)

The problem doesn't seem to be with the panel — it just renders what comes from the wings side.
I looked inside the websocket channel and saw messages like
```json
{"event":"console output","args":["\u003e"]}
```

**Comment by parkervcp** [comment]
Which minecraft egg is this? This is a java issue so far as I know and it's likely the dline terminal bug again, or something similar.

**Comment by Orhideous** [comment]
@parkervcp Custom minecraft egg and docker image, JRE based on [bellsoft/liberica-openjdk-debian:8u275-1](https://bell-sw.com/pages/liberica-release-notes-8u275/)
<details> 
  <summary>Egg bootstrap script</summary>
<pre>
# SpongeForge Installation Script
#
# Server Files: /mnt/server
cd /mnt/server
mkdir logs mods
echo -e "\nDownloading Forge Version $FORGE_VERSION\n"
wget -q http://files.minecraftforge.net/maven/net/minecraftforge/forge/$FORGE_VERSION/forge-$FORGE_VERSION-installer.jar -O installer.jar
echo -e "\nInstalling forge server usint the installer jar file.\n"
java -jar installer.jar --installServer
echo -e "\nDownloading SpongeForge Version $SPONGE_FORGE_VERSION\n"
wget -q https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/$SPONGE_FORGE_VERSION/spongeforge-$SPONGE_FORGE_VERSION.jar -O mods/spongeforge-$SPONGE_FORGE_VERSION.jar
echo -e "\nRename server jar to desired name\n"
mv forge-$FORGE_VERSION-universal.jar $SERVER_JARFILE
echo -e "\nDeleting installer jar file and logs.\n"
rm -rf installer.jar installer.jar.log
</pre>
</details>

<details> 
  <summary>Image with JRE runtime</summary>
<pre>
FROM        bellsoft/liberica-openjdk-debian:8u275-1
LABEL       author="Andriy Kushnir (Orhideous)" maintainer="me@orhideous.name"
RUN apt-get update -y \
 && apt-get install -y curl ca-certificates openssl git tar sqlite fontconfig tzdata iproute2 \
 && rm -rf /var/lib/apt/lists/* \
 && useradd -d /home/container -m container
USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container
COPY        ./entrypoint.sh /entrypoint.sh
CMD         ["/bin/bash", "/entrypoint.sh"]
</pre>
</details>

If similar problems have occurred before, please advise where to read about their troubleshooting and/or debugging?
P.S. I found only https://github.com/pterodactyl/panel/issues/1651, but no commit with fix.

**Comment by Orhideous** [comment]
As suggested in https://github.com/pterodactyl/panel/issues/2597#issuecomment-716207801, adding `-Dterminal.jline=false` fixes this problem, but the colors in the console disappear.

**Comment by matthewpi** [comment]
> As suggested in [#2597 (comment)](https://github.com/pterodactyl/panel/issues/2597#issuecomment-716207801), adding `-Dterminal.jline=false` fixes this problem, but the colors in the console disappear.

Try `-Dterminal.jline=false -Dterminal.ansi=true`

**Comment by Orhideous** [comment]
It works. Thanks!
