### ISSUE TITLE
Some weird error with .json files

### ISSUE THREAD

**Issue by blazecoding2009** [pterodactyl/panel#2863]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installing this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**Background (please complete the following information):**
* Panel or Daemon: Panel I think
* Version of Panel/Daemon: Latest
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows, Chrome

**Describe the bug**
A error occurs when I start the server of a JSON file. This didn't happen before 1.1.3. Used to work file in 1.1.1
Error: 
`(node:35) ExperimentalWarning: The ESM module loader is experimental.
internal/process/esm_loader.js:90
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for /home/container/config.json
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:116:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:247:31)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:49:17)
    at async Promise.all (index 1)
    at async link (internal/modules/esm/module_job.js:53:9) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}`
**To Reproduce**
No idea

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Comment by DaneEveritt** [comment]
We do not offer game specific support, please use Discord or reach out to other sources for assistance.
