### ISSUE TITLE
Updating Advanced settings asking for ports

### ISSUE THREAD

**Issue by Alfatossa** [pterodactyl/panel#2866]
Updated re Captcha in the advanced setting and it is asking for port in the Automatic Allocation even if the service is disabled
![bug](https://user-images.githubusercontent.com/15367208/102001764-ad607080-3cc3-11eb-9ab8-5773256f152d.png)

**Comment by DomiiBunn** [comment]
There is no captcha on that page. Have you tried asking for help in discord 1st?

**Comment by notAreYouScared** [comment]
@DomiiBunn Yes, there is he just dosen't show it in the screenshot, for the time being just put random ports in for the start and end, until it's fixed. Ill open a proper bug report later tonight

**Comment by DomiiBunn** [comment]
I didn't know that anything but the login page has it

**Comment by Alfatossa** [comment]
i simply putted the lowest la highest port available

**Comment by matthewpi** [comment]
> I didn't know that anything but the login page has it

They are referring to is the setting for it, not the actual reCaptcha prompt.

**Comment by DaneEveritt** [comment]
Please complete the template when opening bug reports.
