### ISSUE TITLE
Allow dropdown menus in eggs

### ISSUE THREAD

**Issue by BillyDaPoop** [pterodactyl/panel#2869]
**Is your feature request related to a problem? Please describe.**
It's hard(er), and less user friendly for users to input their own values for egg variables, and it would be amazing if users had some way to select from a predefined list of supported options.

**Describe the solution you'd like**
Allow users to select from a dropdown menu(bonus point if they can use search!), to change an egg variable.

**Describe alternatives you've considered**
Not doing this, It's possible to also add a list of supported variables in the description, but this is less user friendly, and is impractical when there's many different variables you can use.

**Additional context**
EX: the section under "Server Map" would have a dropdown selector where you can select each map, instead of having to type each one. This becomes more useful if there's too many items to list under the description.
![image](https://user-images.githubusercontent.com/65975856/102006097-38953280-3cd3-11eb-859f-56cb101df9e6.png)

**Comment by DomiiBunn** [comment]
#1493 duplicate ^.^

You can make the variable be a drop-down in your billing panel(well in whmcs and blesta anyhow)

**Comment by BillyDaPoop** [comment]
> #1493 duplicate ^.^
> 
> You can make the variable be a drop-down in your billing panel(well in whmcs and blesta anyhow)

sorry about this, was searching for dropdown 😟 
also didn't realize it was a duplicate of #570

**Comment by DomiiBunn** [comment]
It's a commonly requested fechner since long
