### ISSUE TITLE
User creation emails not sending

### ISSUE THREAD

**Issue by InternetBitch** [Pterodactyl/Panel#287]
` public function toMail($notifiable)
{ 
return (new MailMessage)
->line('You are reciving this email because an account has been created for you on Pterodactyl Panel.'
->line(Email:' . $notifiable->email)
->action('Setup Your Account', url('/auth/password/reset/'. $this->token.'?email='. $notifiable->email)); 
}
}`

Look! That's the function in `/var/www/pterodactyl/app/AccountCreated.php`! You see, the issue is it's not sending to the user's email accounts. This has been bothersome, me making emails and passwords and having to send it to them manually. 
The logs that show in `/var/www/pterodactyl/storage/logs/queue-worker.log' are listed below:
`[2017-04 20:35:26] Failed Illuminate/Notifcations/SendQueuedNotifications
[2017-04 21:02:09]  Failed Illuminate/Notifcations/SendQueuedNotifications`
Those are when I create a user account. 

When I assign a server to a user, it throws the same error. 

You may be thinking, "ugh he hasnt configured it probably!"

Well trust me. I reran the 'php artisan pterodactyl:mail` and made SURE it was all correct. Then I repeated the action, and in the `queue-worker.log` it generated the same error but with a different timestamp. 

Hope you can fix this.

**Comment by DaneEveritt** [comment]
```
[2017-04 21:02:09] Failed Illuminate/Notifcations/SendQueuedNotifications
```

Find the relevant error from the `laravel-<date>.log` file for that time. There is something misconfigured that is causing emails to not send.

**Comment by DaneEveritt** [comment]
Closing this until you can provide more information.
