### ISSUE TITLE
Backup Management System

### ISSUE THREAD

**Issue by lukedaviskzn** [pterodactyl/panel#2870]
**Is your feature request related to a problem? Please describe.**
Just a suggestion to improve backup management and retention. In the current system, if you have hourly backups, your backups will always be up to date, but they will go back a few hours. If you had weekly back ups, you could go back a few weeks, but could be as much as a week behind if something bad happens.

**Describe the solution you'd like**
Allow users to set a prefix when creating a "Create Backup" task. If backup limit reached, oldest backup with the same prefix will be deleted, if one doesn't exist it will default to oldest overall backup.
This would fix the above problem and allow users to have both recent hourly backups, and weekly or monthly backups concurrently, if need be. Allowing the user to restore a server to only an hour back without having to worry about losing all good backups after only a few hours.

**Describe alternatives you've considered**
Setting expiry dates for backups, however I think this might cause issues with rotation of old backups, as it wouldn't be clear exactly which backup to rotate; so monthly backups might be rotated in favour of hourly backups. Fine tuning of expiry times would be required to prevent this.

**Comment by tinyoverflow** [comment]
There is an issue with this, specfically when you reach the daily, weekly or monthly backups.
Imagine the following:
1. 1x backup every hour
2. 1x backup every day at 4am
3. 1x backup every week at monday, 4am
4. 1x backup every month, at the first day of the month at 4am

The issues:
1. No specific issue here.
2. You get 25 updates a day and 2 backups for 4am
3. Every monday at 4am, you get 3 backups for the hourly, daily and weekly backup.
4. For every first day of a month, you get at least 3 backups at 4am. If it is a monday, the backup system would create 4 backups.

The backup system is evolving, but I think that your use, while following a well known scheme, is too specific for the panel.

**Comment by zefir-git** [comment]
This issue has already been addressed in pr #2691

I didn't understand why you needed prefixes. The PR I mentioned above finds the oldest one anyway.

**Comment by lukedaviskzn** [comment]
I forgot to close this after the last guys comment.
