### ISSUE TITLE
Error when using the command migrate:refresh

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2875]
* Panel: https://github.com/pterodactyl/panel/commit/5bbb36b3cf94a2a56ea1a5f6b5a59b483d0fc024
* Version of Panel/Daemon: 1.1.3
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
Enter in the console: `php artisan migrate:refresh`
![image](https://user-images.githubusercontent.com/28255085/102213169-65ba2e80-3ee7-11eb-97e7-bfdbb9b29fe9.png)

**Comment by DaneEveritt** [comment]
I am not concerned with this error, the fact that migrations even continue rolling back decently well is a small miracle. The only time I ever use migrations like this is in the tests, and the `down` commands are really only supported for the sake of emergency rolling back during an upgrade, not for normal day-to-day stuff.
