### ISSUE TITLE
cURL error 28

### ISSUE THREAD

**Issue by xGius00** [pterodactyl/panel#2876]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.1.3
* Server's OS: Panel: Ubuntu 18.04.5 LTS - Dedicated: Ubuntu 20.04.1 LTS
* Your Computer's OS & Browser: Windows 10 - Chrome

**Describe the bug**
When I try to open "File Manager", i see an error:
Something went wrong
timeout of 20000ms exceeded

Error on file log: https://bin.ptdl.co/4oqli/
[2020-12-15 13:11:08] production.WARNING: GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 50001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/pterodactyl/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200

curl DedicatedServerIP:8081
{"error":"The required authorization heads were not present in the request."}

Panel: PHP 7.4.13
Daemon: 
Linux DED-SRV-01H 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
https://hastebin.com/tidelejigu.yaml

**To Reproduce**
https://prnt.sc/w36tsu

**Comment by DaneEveritt** [comment]
This is not a bug with this software.
