### ISSUE TITLE
Wrong FTP Username when logged in as an Admin

### ISSUE THREAD

**Issue by adrijanb** [pterodactyl/panel#2877]
**To Reproduce**
1. Go to one server
2. Click on SFTP

Normally the user sees the sftp:// - Connection Box within the IP of the node and then port. Below that the username gets inserted followed by a dot and a random string for the connection to the sftp service.

Example: 

My username is "krservers". I am an administrator of a pterodactyl panel instance connected to WHMCS. My customers username is "manfred", therefore his sftp username would something be like "manfred.ededa21". When I visit the server and go to the sftp tab, his username gets replaced by mine and therefore i get the username "krservers.ededa21" displayed, which is wrong!

**Comment by trenutoo** [comment]
It will show the username of the person that is viewing the SFTP details. You see that because you are logged in as that account.

**Comment by TekExplorer** [comment]
this is correct. logged in users get their own login credentials. there is no sharing of logins.

**Comment by adrijanb** [comment]
But the username is not working then

**Comment by parkervcp** [comment]
the username is "username+serverid" and that is on purpose.

**Comment by adrijanb** [comment]
Yes, but is there a way to login via sftp to the specific directory as an admin? Without using root

**Comment by matthewpi** [comment]
> Yes, but is there a way to login via sftp to the specific directory as an admin? Without using root

You login using your username (the one on the SFTP page) and your password.  The username is different for each server (as it includes the server id).

**Comment by trenutoo** [comment]
> Yes, but is there a way to login via sftp to the specific directory as an admin? Without using root

You can log in to any server using the details shown in SFTP and your account password.

**Comment by parkervcp** [comment]
So the following would be what you use for that specific server

username: `krservers.ededa21`
password: `<your panel password>`
