### ISSUE TITLE
[SRCDS] Servers stuck on "starting" status (but still fully operational)

### ISSUE THREAD

**Issue by ncronin** [Pterodactyl/Panel#288]
Prerequisites: Panel is on it's own server (VPS), game servers are on their own dedicated machine. Ubuntu 16.04 LTS for both, nginx. SSL is enabled.

I have 10 TF2 servers currently installed, all with their own dedicated IP address using the default SRCDS port (27015). All are fully operational; accepting players, logging, console output is fine and I can control them (stop/start/restart/etc) just fine, but they're stuck on "starting" status.

I'm pretty sure this is just a cosmetic bug since I haven't encountered any other issues.

**Comment by DaneEveritt** [comment]
It's because we're looking for a specific line to determine if they started but it probably ain't being output. Do you perhaps have a log you could share that shows when it is done booting and ready to go?

**Comment by ncronin** [comment]
That's what I figured. I run quite a few custom SourceMod plugins on each server, they print various things to the console on startup.

Here's the last few lines outputted into console upon startup:

```
Connection to Steam servers successful.
   Public IP is <snip>.
Assigned persistent gameserver Steam ID [G:1:255552].
VAC secure mode is activated.
Received 3457089 bytes item schema version D5AEA5A0 direct data; update is queued.
perks
forum
rules
apply
discord
raffle
```

The last few bits are custom commands to redirect players to webpages within the server.

**Comment by ncronin** [comment]
That's what I figured. I run quite a few custom SourceMod plugins on each server, they print various things to the console on startup.

Here's the last few lines outputted into console upon startup:

```
Connection to Steam servers successful.
   Public IP is <snip>.
Assigned persistent gameserver Steam ID <snip>.
VAC secure mode is activated.
Received 3457089 bytes item schema version D5AEA5A0 direct data; update is queued.
perks
forum
rules
apply
discord
raffle
```

The last few bits are custom commands to redirect players to webpages within the server.

**Comment by ncronin** [comment]
I fixed this myself. I also noticed there's a pull request on the Daemon repo [here](https://github.com/Pterodactyl/Daemon/pull/34/commits/b4ac4e8d00dd47ab4bd36f4853c9dd3911ee6a93).

I ended up using:
```
        "startup": {
            "done": "VAC secure mode is activated.",
            "userInteraction": []
        },
```

Since GSLT and logging into the Steam servers is often times buggy from my past experience.

**Comment by DaneEveritt** [comment]
Do all servers output that though?

**Comment by ncronin** [comment]
They do, yes. The only game that GSLT's are enforced on is CS:GO, TF2 and others will output the VAC status regardless of the tokens (Server SteamIDs), it will usually always show up.

**Comment by xyeLz** [comment]
Can confirm that "CS:GO" servers also show as "Starting" even though they are fully functional and accessible. I believe there is another string that can be referenced to confirm these servers have successfully started, though I am not sure what it is.

**Comment by jffz** [comment]
I think the PR i did has the 'best' specific line as it works for both, lan and WAN (there is no VAC connexion on LAN servers)
