### ISSUE TITLE
Expand Text Editor box in the File Manager

### ISSUE THREAD

**Issue by marcusmauricio** [pterodactyl/panel#2880]
**Is your feature request related to a problem? Please describe.**
I feel like the Text Editor box in the File Manager is too small, and there is too much blank space, for example:
http://prntscr.com/w49xa9

**Describe the solution you'd like**
I'd like for the Text Box to be expanded at least a little bit more, or so that you can stretch it or shrink it to your consent.

**Describe alternatives you've considered**
Explained previously

**Additional context**
Nope

Thanks,
Redblock6

**Comment by DaneEveritt** [comment]
This is completely intentional, the Panel design does not scale past a fixed width (I want to say that is `1200px`) and I have no plans to make it do so, especially not on singular pages.

Sorry.

**Comment by FoksVHox** [comment]
> This is completely intentional, the Panel design does not scale past a fixed width (I want to say that is `1200px`) and I have no plans to make it do so, especially not on singular pages.
> 
> Sorry.

@DaneEveritt I know you said it is completely intentional, but I think that it would make sense to have the panel scale, even past the fixed-width (1200px). It will make the panel design look odd on larger screens.

**Comment by DaneEveritt** [comment]
Making it scale past 1200px looks _really_ weird on large screens, nothing in the UI is designed to be viewed at an enormous width.
