### ISSUE TITLE
Error 500 due to massive memory allocation when creating server whilst having a lot of IP/port allocations

### ISSUE THREAD

**Issue by TR-SLimey** [pterodactyl/panel#2881]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.1.3
* Server's OS: Ubuntu 20.04 Server
* Your Computer's OS & Browser: openSUSE Tumbleweed / Brave Browser
* PHP Version: 7.4.3

**Describe the bug**
When a lot of IP/port allocations are added ( 44870 in my case (5 IPs, 1025-9999 each) ), it is impossible to access the "create a server" menu (with default PHP memory settings - 128Mb max) due to a 500 server error. This error is likely caused by the server attempting to load all allocations at once and running out of memory (
>production.ERROR: Symfony\Component\ErrorHandler\Error\FatalError: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097160 bytes) in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Collection.php:640

). It may be worth noting that this does not happen in the allocation management panel so can be (and in this case, was) fixed by removing some allocations.

I am not familiar with the codebase, and therefore, don't know how this process happens behind-the-scenes, but maybe a possible solution is to lazy-load the allocations?

**To Reproduce**
1. Ensure PHP memory limit is at the default (or lower for testing)
2. Create a large amount of allocations (35896 should do it (4 IPs - 8974 ports each)
3. Try to create a server
4. Observe a (rather appealing but unwanted all the same) 500 error page

**Expected behavior**
The lack of a 500 error page

**Comment by schrej** [comment]
I think we should rather limit how many allocations can be created at once. There really is no need to be able to add almost 50k allocations in one go.

**Comment by trenutoo** [comment]
> I think we should rather limit how many allocations can be created at once. There really is no need to be able to add almost 50k allocations in one go.

They are not created in one go, however, it loads all of the available allocations right away when you select the available allocations during server install.

Obviously, you would not need ever 50k allocations for one IP as you can never use them.

**Comment by schrej** [comment]
Yeah, I misread parts of the issue. Then we might just need to limit the amount of ports that can be added, or change the system, e.g. allow to define ranges from which allocations can be created on demand.

**Comment by TR-SLimey** [comment]
I don't think limiting the ports is a good solution. It feels a bit like a workaround if anything, and would also probably be quite annoying for large-scale hosts.

The latter idea, defining a range and creating allocations on-demand, seems better though. In that case all allocations would never need to be displayed together anyway avoiding the issue. If my input influences the decision here at all, this would be a preference.

**Comment by matthewpi** [comment]
I'm going to say this is either going to be left as is or fixed by limiting the amount of ports pulled from the database.  I have no wish to implement pagination or search on the New Server page for allocations when nobody should have 50000 allocations in the first place, especially with the admin still being in plain html and JavaScript.  This will eventually be solved by the new React Admin which will paginate and or search the allocations list.
