### ISSUE TITLE
[1.1.3] Identations errors when editing a python file

### ISSUE THREAD

**Issue by Maxime48** [pterodactyl/panel#2889]
Panel 1.1.3
Ubuntu 20.04
Tested with Opera and Chrom on 3 different computers and 2 different panel accounts

![image](https://user-images.githubusercontent.com/37154360/102689810-61e91d80-4201-11eb-8585-cea3f7b47eec.png)

![image](https://user-images.githubusercontent.com/37154360/102689932-3b77b200-4202-11eb-80fc-54da75abb84e.png)
![image](https://user-images.githubusercontent.com/37154360/102689939-47637400-4202-11eb-99e8-e6cf65099322.png)
https://media.discordapp.net/attachments/732627336440315905/785092589782827068/unknown.png

If you need more info, feel free to ask

**Comment by parkervcp** [comment]
This is a standard tab = 4 spaces formatting.

**Comment by Maxime48** [comment]
so he must use tab or space ?, it annoys him
![image](https://user-images.githubusercontent.com/37154360/102690456-da51dd80-4205-11eb-8366-af1d7227bf4c.png)
![image](https://user-images.githubusercontent.com/37154360/102690473-ec338080-4205-11eb-8ec3-bda05135d937.png)

**Comment by DaneEveritt** [comment]
I'm not reading through screenshots. Please fill out the bug template if you're reporting a bug, including the detailed reproduction steps and what you think the problem is.
