### ISSUE TITLE
[SCRDS] Steam subscription loop

### ISSUE THREAD

**Issue by Fabricio20** [Pterodactyl/Panel#289]
By using the custom source game option, one can specify a game id, though if the game needs subscription (like Killing Floor in this example) the container will start a fail loop and keep "erroring"/restarting forever (unless force killed).

This is a steam issue, not a game-related issue.
```
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.
Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
ERROR! Failed to install app '215350' (No subscription)
```
After this error message the container restarts - and keeps looping.

**Comment by ET-Bent** [comment]
Just for completeness, the game in use is `Killing Floor`.

**Comment by DaneEveritt** [comment]
This will require a custom container or at least some modifications. Will look into it for 0.6.0!

**Comment by jffz** [comment]
I'm pretty sure this is due to steam api key not set

**Comment by rivermigue** [comment]
It is not due to a steam api key. Killing Floor needs a valid steam account instead of anonymous to download the game. Some other games will require you to own a copy on that specific steam account such as arma3

**Comment by DaneEveritt** [comment]
This is resolved with the new installation script system that will make defining specific parameters very easy.
