### ISSUE TITLE
Make the Mounts Feature more User-friendly

### ISSUE THREAD

**Issue by KoromaruKoruko** [pterodactyl/panel#2891]
**Is your feature request related to a problem? Please describe.**
we just spent a good 2 hours figuring out that we HAVE to put a mount source inside `/var/lib/pterodactyl/mounts/` which didn't exist in our install (updated from 1.0.0 to latest 1.1.3). Thereover we had to create the specific mount file ourselves.

**Describe the solution you'd like**
Make it to where when you create a mount it prefixes `/var/lib/pterodactyl/mounts/` and creates the folder automatically.

**Describe alternatives you've considered**
Make a doc on the wiki!

**Additional context**
This wasted my time and I'm annoyed.

**Comment by matthewpi** [comment]
You do not have to create a mount inside of that path.  It can be anywhere on the system except [Mount.php#L95-L97](https://github.com/pterodactyl/panel/blob/v1.1.3/app/Models/Mount.php#L95-L97) but the path (or a parent path) must be added to the `allowed_mounts` option in the config.
