### ISSUE TITLE
API automatic port range determination & egg config addition

### ISSUE THREAD

**Issue by wdpfm** [pterodactyl/panel#2893]
Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

We want to auto assign multiple ports for an WHMCS order, but the WHMCS module seems to only assign static port ranges. The problem seems to be, that the API doesn't allow for an automatic assignment of multiple ports, without stating a static point range. For example, we have a customer buying a ARMA III server, we need a port for the basic game, one steam port and one RCON port, that's a total of three ports needed. Currently that's not easibly doable, you're only able to assign static port ranges.

Describe the solution you'd like

What we would need, would be a possibility on the api to state that we need 3 ports in a row, while the panel / api automatically chooses a free port range and assigns it to the newly installed server.
In order for the panel to be able to determine, how many ports are needed, you could expand the egg template configuration with a desired port amount.

Describe alternatives you've considered

Trixter from crident.com stated in the public support channel that :

the api doesn't really allow me to do it without having tens of requests per single deployment

Additional information
#1653
#1012
#1204
#1001
#2434
pterodactyl/whmcs#8
pterodactyl/whmcs#78
pterodactyl/whmcs#29

**Comment by notAreYouScared** [comment]
Copying and pasting the same issue will not help this...
