### ISSUE TITLE
Server error 500 on all Eggs after installing 1.1.3 on new server.

### ISSUE THREAD

**Issue by BolverBlitz** [pterodactyl/panel#2894]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.1.3
* Server's OS: Debian 10
* Your Computer's OS & Browser: Latest: Firefox/Chrome/Edge/Opera ( Win 10 and Andoid)

**Describe the bug**
https://domain.tld/admin/nests/view/1 gives Server 500, so is every other egg also the import egg padge.
PHP 7.4.13 (cli) (built: Nov 30 2020 20:40:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies

**To Reproduce**
1. Go to https://domain.tld/admin/nests/view/1
2. See error

**Expected behavior**
Not a internal server error 500

Made directly after the error happend:
https://bin.ptdl.co/oiw2n/

**Comment by trenutoo** [comment]
You are missing mbstring PHP extension, you can view all the required dependencies in the [install docs.](https://pterodactyl.io/panel/1.0/getting_started.html#dependencies)

**Comment by BolverBlitz** [comment]
![grafik](https://user-images.githubusercontent.com/35345288/102719913-1f9f0980-42f1-11eb-824d-0b63c559277d.png)

I know you toled me that on discord already but that didn´t help
It also is listet with php -m

**Comment by BolverBlitz** [comment]
sudo a2dismod php7.3
sudo a2enmod php7.4
sudo systemctl restart apache2

Did fix it. Thanks
