### ISSUE TITLE
Impossible to reset password when email contains "+"

### ISSUE THREAD

**Issue by kakduman** [pterodactyl/panel#2896]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.1.3 
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
Users with a + in their email cannot reset their password. They can request to reset their password and will receive a password link to reset it. However, clicking on that password link will show them a page that resets the password for an account that has the "+" replaced with a space. For instance, `purpur+testing@gmail.com` would be taken to a password reset link for email `purpur testing@gmail.com` since the "+" in the URL bar is interpreted as a space. Upon clicking reset password, they'll be told that the email is an invalid email address since the email address should have a + rather than a space. Example:
![image](https://user-images.githubusercontent.com/43528123/102855061-7f78db80-43e9-11eb-863e-c263325adb83.png)

**To Reproduce**
1. Use an email that you have access to. Use a provider that supports plus addressing such as Gmail or Outlook. Create a panel account with an email that has +[something] suffixed to the username. For example, if your email is `name@gmail.com`, create an account with the email `name+testing@gmail.com`.
2. Click on forgot password on the login screen and try to reset your password
3. Click on the link given to you in your email
4. You'll be unable to reset your password because `name testing@gmail.com` doesn't exist; `name+testing@gmail.com` does

**Expected behavior**
You should be able to reset your password and the email should show up as `name+testing@gmail.com` in the password reset screen.

**Potential solutions**
I think a possible solution could just be to make the panel replace all spaces it receives with a "+" on the password reset email field since spaces are not possible in emails.

**Comment by parkervcp** [comment]
Just so this is well known. Google is the only email provider to do this. No other email provider supports the `+` for emails.

**Comment by tinyoverflow** [comment]
This is not limited to Google. Actually, this is called "plus addressing" or "sub addressing" and it is supported by many hosting providers and not just Google. It is also a feature of Postfix. While I'm not 100% sure about that, but if I remember correctly, it is enabled by default.

I've just tested this with Microsoft: The free outlook.com also allows sub addressing, while the Microsoft 365 for Business doesn't allow that (by default, might be an option).

**Comment by DaneEveritt** [comment]
This is literally just a URL encoding issue, has nothing to do with the provider.

**Comment by tinyoverflow** [comment]
> This [...] has nothing to do with the provider.

Just wanted to note that there are multiple providers offering this, so being able to have a + inside the email address is not a nieche and therefore shouldn't be low prioritised.
