### ISSUE TITLE
S3: Entity Too Large

### ISSUE THREAD

**Issue by VibeGAMESNL** [pterodactyl/panel#2905]
* Panel or Daemon: 1.1.3
* Version of Panel/Daemon: Daemon
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
When I create a large backup using S3 (minio) I will get this error:
```
backup: error while generating server backup

 INFO: [Dec 23 17:31:12.668] attempting to upload backup.. adapter=s3 backup_id=59a886d1-77c4-4dcc-8d2e-b856568fe735
 WARN: [Dec 23 17:31:12.732] failed to upload part     adapter=s3 backup_id=59a886d1-77c4-4dcc-8d2e-b856568fe735 error=failed to put S3 object part, 413:413 Request Entity Too Large part_id=https://xxxxxxxxxxxxx/af21a97c-ac5c-49c5-9e18-351f81946db2/59a886d1-77c4-4dcc-8d2e-b856568fe735.tar.gz?uploadId=97c91463-b8a9-4757-aec3-bd829de292b1&partNumber=1&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxxxx27748324%2F20201223%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20201223T173112Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Signature=81b1a3b95e4107cb2f3716d2b21252237ca5a9248333cbxxxxxxxxxxxxxxxxxx
 INFO: [Dec 23 17:31:13.347] notified panel of failed backup state backup=59a886d1-77c4-4dcc-8d2e-b856568fe735 error=failed to put S3 object part, 413:413 Request Entity Too Large server=af21a97c-ac5c-49c5-9e18-351f81946db2

Stacktrace:
failed to put S3 object part, 413:413 Request Entity Too Large

ERROR: [Dec 23 17:31:13.347] failed to generate backup for server error=backup: error while generating server backup: failed to put S3 object part, 413:413 Request Entity Too Large server=af21a97c-ac5c-49c5-9e18-351f81946db2

Stacktrace:
failed to put S3 object part, 413:413 Request Entity Too Large
backup: error while generating server backup
```

Should be fixed here https://github.com/pterodactyl/panel/issues/2599 but still got the error in wings 1.1.3.

**To Reproduce**
1. Create backup bigger then 5GB via S3 storage (tested via minio)

**Comment by matthewpi** [comment]
I've had no problems uploading files larger than 5GB using the multipart upload with minio.  That is actually the setup I use for testing.  Do you know the actual size of the backup file?

**Comment by VibeGAMESNL** [comment]
4.1GB

My config:
```
APP_BACKUP_DRIVER=s3
AWS_DEFAULT_REGION=eu-central-1
AWS_ACCESS_KEY_ID=xxxxxxx
AWS_SECRET_ACCESS_KEY=xxxxxx
AWS_BACKUPS_BUCKET=test
AWS_ENDPOINT=https://xxxxxxxxx.net
AWS_BACKUPS_USE_ACCELERATE=false
AWS_USE_PATH_STYLE_ENDPOINT=true
```

**Comment by VibeGAMESNL** [comment]
> I've had no problems uploading files larger than 5GB using the multipart upload with minio. That is actually the setup I use for testing. Do you know the actual size of the backup file?

4.1GB

My config:
```
APP_BACKUP_DRIVER=s3
AWS_DEFAULT_REGION=eu-central-1
AWS_ACCESS_KEY_ID=xxxxxxx
AWS_SECRET_ACCESS_KEY=xxxxxx
AWS_BACKUPS_BUCKET=test
AWS_ENDPOINT=https://xxxxxxxxx.com
AWS_BACKUPS_USE_ACCELERATE=false
AWS_USE_PATH_STYLE_ENDPOINT=true
```

**Comment by VibeGAMESNL** [comment]
@matthewpi So... the issue was caused by the maximum upload size of cloudflare (100MB) :/

It seems to work now but on backups > 500MB It will now freeze here:

![image](https://user-images.githubusercontent.com/66668585/103175413-220de000-486a-11eb-83eb-8c60324b9674.png)

**Comment by DaneEveritt** [comment]
That sounds like an issue with how your instance is configured and I'm not interested in getting that far into the weeds with this backup utility. Sorry.

**Comment by VibeGAMESNL** [comment]
> That sounds like an issue with how your instance is configured and I'm not interested in getting that far into the weeds with this backup utility. Sorry.

@DaneEveritt  Also been solved. Thx guys. All ok now.
