### ISSUE TITLE
Server Not Starting

### ISSUE THREAD

**Issue by oxama96** [pterodactyl/panel#2907]
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:3969ff763cbc59e42ada8866404ace4c51d3867f31347ee67a6a8153ac148272 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:base_debian 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
container@pterodactyl~ Error Event [60964cd4-d873-43f2-a85a-a0a731e13e7f]: Error response from daemon: driver failed programming external connectivity on endpoint 7f885afd-816a-4f25-a7d9-d1e5bb248450 (0f62a1f9af0401cc780eb566f57a497cc54c1de1a60a9983685358d1cf7d435a): Error starting userland proxy: listen tcp 34.89.248.171:30120: bind: cannot assign requested address
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 128
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:3969ff763cbc59e42ada8866404ace4c51d3867f31347ee67a6a8153ac148272 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:base_debian 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Server crash was detected but an error occurred while handling it.
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 128
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by hypersmc** [comment]
Not a panel issue.

**Comment by gOOvER** [comment]
This errors say's nothing.

**Comment by DaneEveritt** [comment]
If you're not going to put any effort into filling out the template I'm not even going to put effort into trying to help.
