### ISSUE TITLE
500 server error in node 

### ISSUE THREAD

**Issue by serverkur** [pterodactyl/panel#2913]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installing this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: 1.0.0
* Version of Panel/Daemon:1.0.0 
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 Google Chrome 

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

**To Reproduce**
1. Go to 'admin panel'
2. Click on 'click node'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
![image](https://user-images.githubusercontent.com/36241002/103149990-2fe73680-4780-11eb-901c-0a497641a136.png)

**Comment by serverkur** [comment]
`sudo wings

                     ____
__ Pterodactyl _____/___/_______ _______ ______
\_____\    \/\/    /   /       /  __   /   ___/
   \___\          /   /   /   /  /_/  /___   /
        \___/\___/___/___/___/___    /______/
                            /_______/ v1.0.0

Copyright © 2018 - 2020 Dane Everitt & Contributors

Website:  https://pterodactyl.io
 Source:  https://github.com/pterodactyl/wings
License:  https://github.com/pterodactyl/wings/blob/develop/LICENSE

This software is made available under the terms of the MIT license.
The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

 INFO: [Dec 26 10:30:40.876] writing log files to disk path=/var/log/pterodactyl/wings.log
 INFO: [Dec 26 10:30:40.876] loading configuration from path path=/etc/pterodactyl/config.yml
 INFO: [Dec 26 10:30:40.877] checking for pterodactyl system user username=pterodactyl
 INFO: [Dec 26 10:30:40.877] configured system user successfully gid=998 uid=999 username=pterodactyl
 INFO: [Dec 26 10:30:40.878] fetching list of servers from API
FATAL: [Dec 26 10:30:40.976] failed to load server configurations error=Error response from Panel: QueryException: An unexpected error was encountered while processing this request, please try again. (HTTP/500)

Stacktrace:
github.com/pterodactyl/wings/server.LoadDirectory
        /home/runner/work/wings/wings/server/loader.go:40
github.com/pterodactyl/wings/cmd.rootCmdRun
        /home/runner/work/wings/wings/cmd/root.go:157
github.com/spf13/cobra.(*Command).execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846
github.com/spf13/cobra.(*Command).ExecuteC
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
`

**Comment by notAreYouScared** [comment]
You should really use the latest versions of the panel and wings if you would like some support. Also, logs need to be provided to see why it's showing a 500 error.

**Comment by serverkur** [comment]
http://bin.ptdl.co/44ep5

**Comment by serverkur** [comment]
I re-install for not solving thanks

**Comment by Clashplayer-PROTECT** [comment]
Hello.
I patched the BUG with node error.
Check your version of mariadb.
I must have a 10.2 or higher ...

----------------------------------------------------------------------
Command :
apt install -y mariadb-common mariadb-server mariadb-client
php artisan migrate --seed --force
----------------------------------------------------------------------

Good luck this is simple if you have a problem contact me on discord: Clashplayer # 8772
