### ISSUE TITLE
Scrolling & selecting/copying text from console broken on mobile

### ISSUE THREAD

**Issue by AnttiMK** [pterodactyl/panel#2919]
Currently, scrolling the console and selecting (thus also copying) text from it are broken on mobile. 

- Scrolling works as long as you keep your finger on the screen, after that it stops immediately (as in, flicking your finger up/down to scroll quickly doesn't work, as you'd normally expect). Also, you can't use the scrollbar on mobile, although it's visible and usable on desktop.
- Trying to select text from the console (long-pressing) brings up a keyboard, but doesn't allow any text to be selected. The command input textbox works correctly.

These issues can be reproduced in Chrome DevTools' Device Mode.

Current user agent: `Mozilla/5.0 (Linux; Android 10; ONEPLUS A5010) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36`

**Comment by AnttiMK** [comment]
Still an issue with `Panel@1.2.0`.

**Comment by trenutoo** [comment]
This is an issue with the xtermjs dependency itself, which does not currently fully support mobile (ex. selection)

**Comment by matthewpi** [comment]
We are not going to spend time implementing this behavior unless it is already supported by [xterm.js](https://github.com/xtermjs/xterm.js).
