### ISSUE TITLE
When set the wings timezone like UTC+8 in config,it will replaced with UTC

### ISSUE THREAD

**Issue by FanhuaCloud** [pterodactyl/panel#2922]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon:  v1.1.3
* Server's OS: Centos 8
* Your Computer's OS & Browser: Windows 10,Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

**To Reproduce**
1. Change wings config,Set the time zone to UTC+8
2. Resrart wings

**Expected behavior**
It will be replaced with UTC again

I think this code have error:
https://github.com/pterodactyl/wings/blob/5c78cb9ab384a32d4d9f9651958a5b345b68cca2/config/config_system.go#L262

A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Comment by fabm3n** [comment]
If you have the /etc/timezone or your timedatctl command set up correctly, just keep the timezone empty.

If you want to set the timezone manually, it must be a timezone as a text for example Europe/Berlin
