### ISSUE TITLE
Backup name

### ISSUE THREAD

**Issue by almir101** [pterodactyl/panel#2926]
Currently I have over 20 ark servers on same machine and I want to upload them on remote server but each backup is hashed
and I have no idea which server it belongs to.
There is option to mount remote storage and connect it to pterodactyl panel, and then restore them/download from that remote server via UCP, which is very fine.
But what would happen if database server fails for any reason and I end up with having 100 archived backups on remote server without knowing what server it belongs to.
(example: servername-date-xxxxx-yyyyy-zzzzz-11111-22222 would be nice with option servername to be editable or pulled)

**Comment by parkervcp** [comment]
I was fairly certain that all the backup names were the server uuid because that can't be changed.

**Comment by almir101** [comment]
Well each backup has very different name and not including the server uuid at all.

**Comment by matthewpi** [comment]
This will not be changed as backups need to just be identifiable by a UUID, there is already an open issue requesting backups to be stored under a Server ID as well.  https://github.com/pterodactyl/panel/issues/2594
