### ISSUE TITLE
Schedules not running automatically

### ISSUE THREAD

**Issue by garrettsummerfi3ld** [pterodactyl/panel#2930]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.1.3
* Server's OS: Debian 10 Buster
* Your Computer's OS & Browser: Windows 10 Pro for Workstations 20H2, Chrome 87.0.4280.88 

**Describe the bug**
Schedules set within the panel are not running. Restarting the queue worker is not running and nothing has been run in any of the servers. The systemd status says it has been run however the panel does not reflect it running. Panel logs are not helpful as its just raw HTML written in the laravel log.

Logs of the `pteroq.service`:
```
● pteroq.service - Pterodactyl Queue Worker
   Loaded: loaded (/etc/systemd/system/pteroq.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-12-25 02:45:23 UTC; 3 days ago
 Main PID: 16291 (php)
    Tasks: 1 (limit: 4915)
   Memory: 31.1M
   CGroup: /system.slice/pteroq.service
           └─16291 /usr/bin/php /var/www/pterodactyl/artisan queue:work --queue=high,standard,low --sleep=3 --tries=3

Dec 28 09:31:10 ns557064 php[16291]: [2020-12-28 04:31:10][QHqt28UDxE5O3HacrogBsmRcjS277kPz] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Dec 28 09:31:11 ns557064 php[16291]: [2020-12-28 04:31:11][QHqt28UDxE5O3HacrogBsmRcjS277kPz] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Dec 28 09:31:11 ns557064 php[16291]: [2020-12-28 04:31:11][0a4HSEpX7cuEIgZv11WBTpBeTpX3SMUD] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Dec 28 09:31:11 ns557064 php[16291]: [2020-12-28 04:31:11][0a4HSEpX7cuEIgZv11WBTpBeTpX3SMUD] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Dec 28 09:31:11 ns557064 php[16291]: [2020-12-28 04:31:11][imBF5b7ErnvhaeA31rw4WcXkZwn0lpKy] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Dec 28 09:31:11 ns557064 php[16291]: [2020-12-28 04:31:11][imBF5b7ErnvhaeA31rw4WcXkZwn0lpKy] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Dec 28 09:31:11 ns557064 php[16291]: [2020-12-28 04:31:11][N15KMEuiMs7ADJMNQWrvZMAPDbW7QlBK] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Dec 28 09:31:11 ns557064 php[16291]: [2020-12-28 04:31:11][N15KMEuiMs7ADJMNQWrvZMAPDbW7QlBK] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
Dec 28 09:31:14 ns557064 php[16291]: [2020-12-28 04:31:14][mVoz9rsYGqSoQjkt5sDbEX2CDLjOo3HF] Processing: Pterodactyl\Jobs\Schedule\RunTaskJob
Dec 28 09:31:14 ns557064 php[16291]: [2020-12-28 04:31:14][mVoz9rsYGqSoQjkt5sDbEX2CDLjOo3HF] Processed:  Pterodactyl\Jobs\Schedule\RunTaskJob
```

Screenshot of panel schedule:
![image](https://user-images.githubusercontent.com/7040719/103254832-8903c580-494c-11eb-93e3-161bee6daf84.png)

Panel:
```
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
```

**To Reproduce**
1. Go to 'Schedules'
2. Click on 'Create Schedule'
3. Create a schedule (does not matter the times when the schedule runs)
4. Edit schedule and click on 'New Task'
5. Set action to 'Send command' and set a payload to anything (does not matter the payload command)
6. Wait for schedule to execute
7. Schedule does not execute

**Expected behavior**
Schedules run on the specific times given to run.

**Comment by almir101** [comment]
Hello,
I have tried this on my system and it runs just fine with crons.
I am also using debian 10 buster for server hosting and windows 10 as my personal.
The only thing is server itself, which game-server this is related to?

**Comment by garrettsummerfi3ld** [comment]
The game being used is Minecraft, the only thing that is different from the default egg on one server is using the `core:java-8-openj9` rather than the default value, but that single difference shouldn't affect other servers and not a single server is able to run a schedule.

**Comment by almir101** [comment]
You have enabled it in crontab?
`* * * * * php /var/www/pterodactyl/artisan schedule:run >> /dev/null 2>&1`

**Comment by garrettsummerfi3ld** [comment]
Closing, the crontab was not properly written for at the end was `* * * * * php /var/www/pterodactyl/artisan schedule:run >> /dev/null 2>&1ú` instead of the proper line for crontab.
