### ISSUE TITLE
522 error when going to my panel.

### ISSUE THREAD

**Issue by MilkMGN** [pterodactyl/panel#2931]
**Background (please complete the following information):**
* Panel or Daemon: Both?
* Version of Panel/Daemon: Latest (1.1.3) 
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Ubuntu 20.04, Firefox

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:14) ( NTS )`
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker):
`Linux sanctum.gq 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
```
Client:
 Debug Mode: false

Server:
 Containers: 25
  Running: 2
  Paused: 0
  Stopped: 23
 Images: 30
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-126-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.55GiB
 Name: sanctum.gq
 ID: FFLH:TLAE:54Y6:RFYN:32XE:TFBD:MOLL:NIVE:RDYY:RDBO:H6MG:7PXI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**To Reproduce**
1. Go to https://panel.sanctum.gq/
2. see error
Sorry for not being able to  reproduce on another machine, i dont know much about what happened, it just randomly happened

**Expected behavior**
going to my panel would actually work and not error out

**Comment by matthewpi** [comment]
522 is caused by Cloudflare, not Pterodactyl.  This is not a bug, this is an issue with your setup.
