### ISSUE TITLE
Panel sends Stop Signal when Adding Spongeforge to a Modded Minecraft Server

### ISSUE THREAD

**Issue by Irgendwer01** [pterodactyl/panel#2935]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.1.3
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Manjaro Linux, Firefox
* Nest: Minecraft
* Egg: Forge Minecraft
* Minecraft Version: 1.12.2
* Forge Version: 1.12.2-14.23.5.2847
**Describe the bug**
The Daemon is Sending a Stop signal when the server is almost started and Spongeforge is added, i can only reproduce the Issue when the server is running on the Daemon. Its an Modpack Called Dungeons, Dragons and Space Shuttles which can be found here
https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles
Spongeforge can be found here
https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2
Daemon Log: https://bin.ptdl.co/kldky/
Server Log: https://mclo.gs/ZeOKVIc

**To Reproduce**
1. Add Spongeforge to the mods folder of the server
2. Go to the folder asm and edit the file hammercore.xml and set
< entry key="World.ITickable.Override" >true< /entry > to false
3. Go to the mods folder and remove the file Sledgehammer-1.12.2-0.7-2.0.1.jar
4. Start Server
5. See Problem

**Expected behavior**
I Excepted that it's just running fine like all my other Servers i have on the panel, this is the first time i have this issue.

**Comment by DaneEveritt** [comment]
Please run your Wings instance in debug mode and then provide the log output from Wings when this happens. I'm not looking through tens of thousands of lines of log.

Also please include more detailed reproduction steps. I don't play 99% of the games this Panel supports, therefore telling me to "Add sponge to the server" means nothing to me. What egg? What specific download? What other things do I need to have configured?

**Comment by Irgendwer01** [comment]
@DaneEveritt I have edited my Message, hope it's enough information

**Comment by Irgendwer01** [comment]
After i have looked myself in the logs from Wings, i seen that the Daemon thinks the server is Crashing because of the many errors but it isn't, is there any way disabling the crash handler?

**Comment by DaneEveritt** [comment]
You need to put Wings into debug mode (`debug: true` in the config file, or `--debug` using the CLI command) to get more context to the issue, but the crash handler doesn't just "randomly fire" so there is certainly something very wrong happening. Not the least of which is that your server dumps thousands of lines to the output just to boot which is absolutely ridiculous.

**Comment by tinyoverflow** [comment]
I've tried to reproduce this in Pterodactyl 1.2.0 and I couldn't manage to get the same results as you. It works fine for me. I assume that there is something wrong with your setup. I don't think this is related to Wings or Pterodactyl.

Please make sure your server has enough RAM and it is not related to the OOM Killer, though I do not know if the Panel / Wings sends a stop-command when the OOM Killer kicks in.

![grafik](https://user-images.githubusercontent.com/6287093/103594132-110f3f80-4ef8-11eb-93e9-4c6e0c515629.png)

**Comment by Irgendwer01** [comment]
@tinyoverflow The issue is related to the Modpack since it sends too many Errors and warnings in the console and then the Crash Handler thinked it will crash in a few minutes, but i got it fixing by filtering out the most errors out of the log via a mod so i will close the issue
