### ISSUE TITLE
Ignored files textbox behaves unexpectedly

### ISSUE THREAD

**Issue by kakduman** [pterodactyl/panel#2936]
**Background (please complete the following information):**
* Panel or Daemon: Panel, I think. Might require a fix on wings' end instead/in addition.
* Version of Panel/Daemon: Panel 1.1.3 & Wings 1.1.3
* Server's OS: Ubuntu 20.04 for panel, happens on Ubuntu 20.04 and Debian 10.5 for wings.
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
Specifying both a file inside the root directory and a file within a subdirectory through the popup ignored files textbox when creating a backup causes the ignored files (& folders) to be completely ignored, and it causes the entire server to be backed up. This might make more sense after reading the reproduction steps. I'm not sure how well I explained it.

The below image shows the file size of backups when different folders/files were specified in the Ignored files & directories popup when creating a backup. One shows the backup size when the folders/files were specified in .pteroignore and the Ignored files & directories textbox was left blank.
![image](https://user-images.githubusercontent.com/43528123/103324027-2cb3ab00-4a0b-11eb-8331-c4b16da24060.png)

**To Reproduce**
1. Create a server with just three files: `/file`, `/f`, and `/folder/file`. Try to make /file and /folder/file at least a kilobyte so that you can easily tell when one of them hasn't been backed up. /f can be really small 
2. Click on the backups tab and create a backup with no ignored files. This will be your baseline so that you don't have to download and uncompress to see what's been backed up. Observe the backup size.
3. Click on the backups tab and create a backup with the following ignored files:
![image](https://user-images.githubusercontent.com/43528123/103324075-6b496580-4a0b-11eb-9b6b-b05b681cbb4a.png)
4. The error: observe that the new backup is the same size, even though only /f should have been backed up.
5. If you place the same ignored files in the .pteroignore file, only /f will be backed up as expected, and the backup size will be small.

**Expected behavior**
The files ignored in the ignored files and folders textbox should be ignored. It's possible that the Ignored Files & Directories textbox intentionally behaves differently than the .pteroignore file. If it is intentional/expected, the description of the ignored files and directories textbox should be modified to express the difference between itself and the .pteroignore file

**Comment by matthewpi** [comment]
I changed some of this logic on both the panel and wings on develop so this may occur on v1.1.3 but I am unable to reproduce it on `develop` (I was using [pterodactyl/panel@`32d99c9`](https://github.com/pterodactyl/panel/commit/32d99c98ec4b02f261d3317f14b113516b6b8ead) and [pterodactyl/wings@`d6e189d`](https://github.com/pterodactyl/wings/commit/d6e189df5e8489479ebed8dde469574f78181f15) for this testing).

There was not a `.pteroignore` file in the root directory, I put content in files named `f`, `file` and `folder/file`, and used the ignore content
```
/file
/folder/*
```
when creating the backup.  This server also had BungeeCord files but that shouldn't matter either.  The result was all the BungeeCord files were backed up (other than a empty `plugins` folder).  `folder` (including the file inside of it) and `file` were excluded, but `f` was still included in the archive.

So from my testing this works as intended.

**Comment by kakduman** [comment]
Awesome! I tested on a slightly modified version of 1.1.3 so it's likely that some of the other changes in the develop branch fixed this bug.

**Comment by code-fanatic** [comment]
i was looking for layout of `.pteroignore` file thanks for sharing screenshot really helped me :) @kakduman
