### ISSUE TITLE
Console commands do not work when using Wine.

### ISSUE THREAD

**Issue by VibeGAMESNL** [pterodactyl/panel#2937]
**Background (please complete the following information):**
* Panel or Daemon: Both?
* Version of Panel/Daemon: 1.1.3 
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 Pro, Chrome 

**Describe the bug**
When using wine you can't use console commands. There is no response at all.

![image](https://user-images.githubusercontent.com/66668585/103341787-1d267780-4a88-11eb-9391-b239efdc5967.png)

Startup command:
`wine64 ./fxserver/FXServer.exe +exec server.cfg`

Tested on:
> Wine 5.0.3 (stable)
> Wine 5.16 (staging)
> Wine 6.0-rc4  (staging)

**To Reproduce**
1. Create a server with an egg that uses wine.
2. Start the server
3. Execute a console command

**Expected behavior**
Console commands should be executed and a response should be displayed.

**Comment by parkervcp** [comment]
This might just be a wine issue.

**Comment by matthewpi** [comment]
Wings literally just writes content to the Stdin of the container, I don't see how this is a bug with Pterodactyl.

**Comment by DaneEveritt** [comment]
Its not.
