### ISSUE TITLE
Requests are not sent to https

### ISSUE THREAD

**Issue by zandercodes** [pterodactyl/panel#2938]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.1.3
* Server's OS: Debian GNU/Linux 10 (buster)
* Your Computer's OS & Browser: Windows 10 (20H2), Firefox 84.0.1

**Describe the bug**
I don't know if it's a bug or a configuration file setting.
On Discord I could not be helped.
The panel is running in a Docker container with the Traefik reverse proxy.
My problem is that the panel can be accessed via HTTPS but when I save on a link or something, it is sent to HTTP.
My browser also shows that the request is sent unsecured.
The panel itself runs under port 80 with a Nginx container with PHP.

**To Reproduce**
1. Install Traefik
2. connect the panel with Traefik
3. set up the panel
4. execute links or save content
And now you can see that it sends the request to HTTP.

**Expected behavior**
Actually, the requests should be sent to HTTPS and not to HTTP.

**Comment by matthewpi** [comment]
If you are using Traefik for HTTPS but the panel behind Traefik is not using HTTPS you need to set the `TRUSTED_PROXIES` environment variable for the Panel in order for it to properly handle HTTPS traffic.  Please also make sure your `APP_URL` has the URL being accessed by the client and not the one the panel is listening on.

**Comment by zandercodes** [comment]
> 
> 
> If you are using Traefik for HTTPS but the panel behind Traefik is not using HTTPS you need to set the `TRUSTED_PROXIES` environment variable for the Panel in order for it to properly handle HTTPS traffic. Please also make sure your `APP_URL` has the URL being accessed by the client and not the one the panel is listening on.

Don't work with environment variable `TRUSTED_PROXIES=*`
Requests are further sent to http.
My `APP_URL` begin with `https://`

**Comment by matthewpi** [comment]
> > If you are using Traefik for HTTPS but the panel behind Traefik is not using HTTPS you need to set the `TRUSTED_PROXIES` environment variable for the Panel in order for it to properly handle HTTPS traffic. Please also make sure your `APP_URL` has the URL being accessed by the client and not the one the panel is listening on.
> 
> Don't work with environment variable `TRUSTED_PROXIES=*`
> Requests are further sent to http.
> My `APP_URL` begin with `https://`

Try quoting the `*` in the environment variable with single quotes. (`TRUSTED_PROXIES='*'`)

**Comment by zandercodes** [comment]
I don't know why but it doesn't work.
I have looked at the HTML context and there my domain is displayed with `http` although I have entered with `https` in `APP_URL`.
```html
<form action="http://panel.example.com/admin/servers/view/9/build" method="POST">
```
I can not explain why there is no https :C

**Comment by DaneEveritt** [comment]
I don't know how to provide anything else to this conversation, sorry. Thats likely something with how Laravel handles proxies which may get you moving in the right direction. Regardless, without a specific solve I'm not looking into this since that is a setup I do not run (and a vast majority of the community does not).

**Comment by zandercodes** [comment]
I have found a solution.
I think there is a bug somewhere in the code of the panel.

The solution is:
Place this in the `AppServiceProvider` in the `boot()` method.
```php
if (!empty(env('APP_URL')) && str_starts_with(env('APP_URL'), 'https')) {
    URL::forceScheme('https');
}
```

**Comment by kolbyd** [comment]
Bump. Laravel route generator returns http by default, unless you force the scheme in the provider. This causes issues loading and making requests from the front-end to insecure URLs (when you're on an HTTPS page).
