### ISSUE TITLE
Serveur crashing, console error

### ISSUE THREAD

**Issue by Mimexe** [pterodactyl/panel#2939]
Hello,

I am an developpers in a server french (I am french) and the minecraft serveur crash with this error :
1.Error Event [6f5ccd91-9ae6-4636-8822-0abe4a2c1879]: an unexpected error was encountered while handling this request

 Exit code: 128
 Out of memory: false

Cordially,
Mime

**Comment by matthewpi** [comment]
When reporting a bug please follow the provided template.  The information you provided is not helpful in trying to understand the problem you are facing.

**Comment by Mimexe** [comment]
What it the template ?
