### ISSUE TITLE
Unable to see node information after upgrade to 1.2.0

### ISSUE THREAD

**Issue by christofkaelin** [pterodactyl/panel#2940]
**Background:**
* Panel or Daemon:  Panel
* Version of Panel/Daemon: Both 1.2.0
* Server's OS: Ubuntu 20.04 5.4.0-58-generic
* Your Computer's OS & Browser: Windows 10 & Google Chrome

**Describe the bug**
In the admin control panel, when going to the nodes, selecting a node and then choosing Configuration, Allocation or Servers, I receive an interal server error 500.

Please provide additional information too, depending on what you have issues with:
Panel: PHP 7.4.3
Error from `/var/log/nginx/pterodactyl.app-error.log`: https://pastebin.com/3S9b0nxQ

**Comment by matthewpi** [comment]
I am unable to reproduce this issue and the error you are reporting seems to be related to bad file permissions.  You most likely forgot to run `cd /var/www/pterodactyl && chmod -R 755 storage/* bootstrap/cache/` after updating the panel.
