### ISSUE TITLE
Wings | Fatal error at maintenance mode | Missing error message

### ISSUE THREAD

**Issue by lunibo** [pterodactyl/panel#2941]
* Panel or Daemon: Daemon
* Version of Daemon: 1.2.0
* Server's OS: Ubuntu 19.10

**Describe the bug**
If the panel is in maintenance mode, the daemon starts without an error message and crashes a short time later

The error cannot be clearly identified with 'systemctl status wings.service':
`● wings.service - Pterodactyl Wings Daemon`
`   Loaded: loaded (/etc/systemd/system/wings.service; enabled; vendor preset: enabled)`
`   Active: failed (Result: exit-code) since Thu 2020-12-31 17:10:39 CET; 46s ago`
`  Process: 3373 ExecStart=/usr/local/bin/wings (code=exited, status=1/FAILURE)`
` Main PID: 3373 (code=exited, status=1/FAILURE)`

`Dec 31 17:10:39 ubuntu systemd[1]: wings.service: Service RestartSec=100ms expired, scheduling restart.`
`Dec 31 17:10:39 ubuntu systemd[1]: wings.service: Scheduled restart job, restart counter is at 5.`
`Dec 31 17:10:39 ubuntu systemd[1]: Stopped Pterodactyl Wings Daemon.`
`Dec 31 17:10:39 ubuntu systemd[1]: wings.service: Start request repeated too quickly.`
`Dec 31 17:10:39 ubuntu systemd[1]: wings.service: Failed with result 'exit-code'.`
`Dec 31 17:10:39 ubuntu systemd[1]: Failed to start Pterodactyl Wings Daemon.`

The error only becomes clear with 'wings diagnostics':
`FATAL: [Dec 31 16:57:55.418] failed to load server configurations error=Error response from Panel: MaintenanceModeException:  (HTTP/503)`

`FATAL: [Nov 29 18:10:54.229] failed to load server configurations error=json: cannot unmarshal array into Go value of type api.allServerResponse`

**To Reproduce**
1. Set Panel to Maintenance Mode 'php artisan down'
2. Start the Daemon 'systemctl start wings'
3. Wait some seconds
4. Check the Daemon Status 'systemctl status wings.service'
5. Error present, but no description
6. Run Wings diagnostics 'wings diagnostics'
7. Only here are all errors clearly recognizable

**Expected behavior**
If the panel is in maintenance mode, the daemon should throw an error like this on startup before exiting itself: **The web panel is in maintenance mode. Please exit maintenance mode first and then start the daemon**

**Comment by JoshJames04** [comment]
Literally had this problem myself around 10 minutes ago.

Make sure your Maintenance Mode is disabled after the update - `php artisan up`

**Comment by lunibo** [comment]
Fortunately, I've already found the solution, but an error message would be nice for other users

**Comment by matthewpi** [comment]
This is expected behavior and isn't a bug.

**Comment by lunibo** [comment]
But shouldn't the daemon display a corresponding error message anyway?
@matthewpi

**Comment by matthewpi** [comment]
> But shouldn't the daemon display a corresponding error message anyway?
> @matthewpi

No, we don't manually handle displaying error messages unless they are sent by the panel.  Either way, HTTP 503 already denotes a maintenance state.

**Comment by JoshJames04** [comment]
> But shouldn't the daemon display a corresponding error message anyway?
> @matthewpi

Not necassarily, it's by human error that maintenance mode wasn't disabled so I guess the system wouldn't "need" to display an error message for this

**Comment by ghost** [comment]
and the solutions iS?
