### ISSUE TITLE
Player count on console window

### ISSUE THREAD

**Issue by JoshJames04** [pterodactyl/panel#2942]
**Is your feature request related to a problem? Please describe.**

---

**Describe the solution you'd like**

I want there to be a clear player count (number of players online) on the console window. I'm currently only using the minecraft module, so I'm not sure if other servers do but I know MC doesn't.

**Describe alternatives you've considered**

There are no other alternatives. I mean, other than checking the server in game - but I think there should definately be a way to do this via the panel.

**Additional context**

No

**Comment by TekExplorer** [comment]
I would take a look at issue #1218
Generally, game-specific features won't be added

**Comment by JoshJames04** [comment]
I was looking if this was mentioned before, couldn't find anything.
Surely it would be a very similar function to work amoungst all games?
I think something like this is critical to a server owner - this is literally the only downside I have found to Pterodactyl

**Comment by matthewpi** [comment]
I don't see this being implemented any time soon as it is too game-specific and requires a different implementation for different games.  Either way, issue 1218 exists which covers what this issue is requesting.

**Comment by TekExplorer** [comment]
> I was looking if this was mentioned before, couldn't find anything.
> Surely it would be a very similar function to work amoungst all games?
> I think something like this is critical to a server owner - this is literally the only downside I have found to Pterodactyl

different games handle this type of thing differently, which is why #1218 is likely the only way this gets implemented
