### ISSUE TITLE
Username overlapping in admin area

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#2943]
**Background (please complete the following information):**
* Version of Panel/Daemon: 1.2.0
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10, Microsoft edge.

**Describe the bug**
If a user has a long enough name, and you assign a server to them... the 'server owner' field will overlap.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Servers'.
2. Click on 'Details'.
3. Assign a server to someone with a long name.
4. See an error.

**Expected behaviour**
Username does not overlap.

**Comment by TekExplorer** [comment]
"See an error."
frankly this does not help at all

**Comment by ghost** [comment]
The overlapping name would be the error

**Comment by DaneEveritt** [comment]
I don't really care about UI issues in the admin area, especially for edge cases like this given that we're slowly rolling a new UI for it all.
