### ISSUE TITLE
Encoding Issue: Unable to delete / rename / unarchive files with special characters in name

### ISSUE THREAD

**Issue by kakduman** [pterodactyl/panel#2944]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.2.0
* Server's OS: Debian 10.5
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
It's impossible to delete, rename, or unarchive a file with a space, parentheses, brackets, etc. It's interpreted as %20 or similar encoding thing by Wings rather than the actual character, meaning the file that Wings searches for doesn't exist.

The implications of this bug are that it is impossible to remove an outdated plugin which is commonly called something like VotingPlugin (29).jar without using FileZilla to SFTP to the server. Therefore, Minecraft servers cannot update their plugins through the panel. It is also impossible to unarchive some Pterodactyl-generated files which contain a + to specify the timezone.

`uname -a`: `Linux crabwings 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux`
`docker info`: [https://bin.birdflop.com/cegaxawule.yaml](https://bin.birdflop.com/cegaxawule.yaml)

**To Reproduce**
1. Create a .tar.gz file
2. If it doesn't have a `+` in it, rename that file to have a space or other similar special character in it.
3. Try to rename that file again. You'll be unable to.
4. Try to delete that file. It will appear deleted, but will return when the page is refreshed.
5. Try to unarchive that file. Wings will throw an error saying that it could not be found ([https://ptero.co/ratonetiqo](https://ptero.co/ratonetiqo))
6. Same error occurs with other special characters. It's a similar bug to #2896.

**Expected behavior**
I should be able to delete / rename / unarchive files, even those with special characters in the name

**Comment by VibeGAMESNL** [comment]
When you create an archive since pteordactyl 1.2.0 it will automaticly add a +0100 behind the file name.

This causes unarchrive and rename to **fail.** I had no issue with delete or download.

![image](https://user-images.githubusercontent.com/66668585/103441079-c8cbf500-4c4b-11eb-8819-3183cc389f57.png)
![image](https://user-images.githubusercontent.com/66668585/103441089-db462e80-4c4b-11eb-90e2-93fe6757d9c8.png)

> [2021-01-01 16:10:13] production.ERROR: GuzzleHttp\Exception\ServerException: Server error: `POST https://xxxxxx.net:8080/api/servers/ba866c15-bb99-424c-83be-8d8822b91752/files/decompress` resulted in a `500 Internal Server Error` response:
> {"error":"An unexpected error was encountered while processing this request.","error_id":"e0dde420-1d30-4728-8d47-9aece1 (truncated...)
>  in /var/www/pterodactyl/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
> Stack trace:
> #0 /var/www/pterodactyl/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create()
> #1 /var/www/pterodactyl/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
> #2 /var/www/pterodactyl/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler()
> #3 /var/www/pterodactyl/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
> #4 /var/www/pterodactyl/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run()
> #5 /var/www/pterodactyl/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
> #6 /var/www/pterodactyl/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
> #7 /var/www/pterodactyl/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
> #8 /var/www/pterodactyl/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
> #9 /var/www/pterodactyl/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Promise\Promise->wait()
> #10 /var/www/pterodactyl/vendor/guzzlehttp/guzzle/src/Client.php(95): GuzzleHttp\Client->request()
> #11 /var/www/pterodactyl/app/Repositories/Wings/DaemonFileRepository.php(264): GuzzleHttp\Client->__call()
> #12 /var/www/pterodactyl/app/Http/Controllers/Api/Client/Servers/FileController.php(241): Pterodactyl\Repositories\Wings\DaemonFileRepository->decompressFile()
> #13 [internal function]: Pterodactyl\Http\Controllers\Api\Client\Servers\FileController->decompress()
> #14 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
> #15 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
> #16 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher->dispatch()
> #17 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route->runController()
> #18 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route->run()
> #19 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
> #20 /var/www/pterodactyl/app/Http/Middleware/Api/Client/Server/AuthenticateServerAccess.php(92): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #21 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\Client\Server\AuthenticateServerAccess->handle()
> #22 /var/www/pterodactyl/app/Http/Middleware/RequireTwoFactorAuthentication.php(68): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #23 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\RequireTwoFactorAuthentication->handle()
> #24 /var/www/pterodactyl/app/Http/Middleware/Api/AuthenticateIPAccess.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #25 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\AuthenticateIPAccess->handle()
> #26 /var/www/pterodactyl/app/Http/Middleware/Api/AuthenticateKey.php(82): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #27 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\AuthenticateKey->handle()
> #28 /var/www/pterodactyl/app/Http/Middleware/Api/ApiSubstituteBindings.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #29 /var/www/pterodactyl/app/Http/Middleware/Api/Client/SubstituteClientApiBindings.php(60): Pterodactyl\Http\Middleware\Api\ApiSubstituteBindings->handle()
> #30 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\Client\SubstituteClientApiBindings->handle()
> #31 /var/www/pterodactyl/app/Http/Middleware/Api/IsValidJson.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #32 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\IsValidJson->handle()
> #33 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #34 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\AuthenticateSession->handle()
> #35 /var/www/pterodactyl/app/Http/Middleware/Api/SetSessionDriver.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #36 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\Http\Middleware\Api\SetSessionDriver->handle()
> #37 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #38 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle()
> #39 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #40 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
> #41 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
> #42 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #43 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then()
> #44 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack()
> #45 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute()
> #46 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute()
> #47 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch()
> #48 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
> #49 /var/www/pterodactyl/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #50 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
> #51 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #52 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
> #53 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #54 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
> #55 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #56 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
> #57 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #58 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
> #59 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #60 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
> #61 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
> #62 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then()
> #63 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
> #64 /var/www/pterodactyl/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle()
>

**Comment by kakduman** [comment]
I'm able to reproduce the issue with a + since that is also enoded differently. However, I'm still unable to delete it. Are you sure that you were able to?

Please keep in mind that when deleted there will be NO error message, and it will appear to have been successfully deleted. However, it just looks deleted. The file will reappear when you refresh.

**Comment by VibeGAMESNL** [comment]
> I'm able to reproduce the issue with a + since that is also enoded differently. However, I'm still unable to delete it. Are you sure that you were able to?
> 
> Please keep in mind that when deleted there will be NO error message, and it will appear to have been successfully deleted. However, it just looks deleted. The file will reappear when you refresh.

Deleting is not working for me either. I was wrong.
