### ISSUE TITLE
Outdated documentation - incorrect command for crontab for schedules

### ISSUE THREAD

**Issue by Lucavon** [pterodactyl/panel#2947]
Hello!
It seems the documentation is outdated. See here:
https://pterodactyl.io/panel/1.0/getting_started.html#crontab-configuration

The crontab configuration says to use `schedule:run` as the artisan command, while it (at least according to what I found) should be `p:schedule:process` - schedule:run does not seem to work.

**Comment by TekExplorer** [comment]
if you think the docs need an update or correction, feel free to make an issue/pr over at its repo: https://github.com/pterodactyl/documentation

**Comment by Lucavon** [comment]
I'll do that tomorrow then, thanks!
