### ISSUE TITLE
.pteroignore GUI or Guide

### ISSUE THREAD

**Issue by TekExplorer** [pterodactyl/panel#2948]
**Is your feature request related to a problem? Please describe.**
Currently, the `.pteroignore` file is somewhat unintuitive to use. not many people using the panel are going to be familiar with how a `.gitignore` works, beyond maybe being able to figure out the absolute basics, but it's not at all intuitive. Not to mention online `.gitignore` guides will be full of unrelated dev things that would only confuse someone just wanting to tune their backups.

**Describe the solution you'd like**
Some sort of GUI interface for the file that can generate or edit rules that work intuitively.

**Describe alternatives you've considered**
Somewhat simpler for the implementer but less intuitive for the user: create a comprehensive guide on how you can use the file to specify certain files and directories in different ways with different rules.

Perhaps also include a method to add pre-tailored `.pteroignore` templates that can be made per-egg similar to `.gitignore` templates? (preferably should include the ability to store several presets in the egg for flexibility) -- lmk if I should split this part off into its own issue

**Comment by DaneEveritt** [comment]
Someone is welcome to PR such a guide, but I'm not going to leave an issue open for it, I cannot handle the sheer volume of things as it is.

**Comment by TekExplorer** [comment]
would you like me to make an issue on the docs instead? this way its there for someone to make. (i might do it too, but ill easily forget)
