### ISSUE TITLE
Pterodactyl Editor Bug

### ISSUE THREAD

**Issue by Konstanius** [pterodactyl/panel#2950]
Example:

> Held:
    Weapon_Weight: -0.01
    Hide_Attributes: true
    Update_Lore:
      Maxium_Attachments_Per_Line: 2
      New_Line_Format: "&7✴   &c➣ &7#ATTACHMENTS#"
      Lore:
        - "&7✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴  "
        - "&7✴ &c➣ &7Attachments #ATTACHMENTS#"
        - "&7✴ &c➣ &7Skin &c⟹ &7#SKIN#"
        #- "&7✴ &c➣ &7StatTrak &c⟹ &7#STATTRAK#"
        - "&7✴ &c➣ &7#DAMAGE# &c&l⟸&r &7Damage"
        - "&7✴ &c➣ &7#WEIGHT# &c&l⟸&r &7Weight"
        #- "&7✴ &c➣ &7#SPREAD# &c&l⟸&r &7Spread"
        - "&7✴ &c➣ &7#PROJECTILE_SPEED# &c&l⟸&r &7Projectile Speed"
        - "&7✴ &c➣ &7#RELOAD_DURATION# &c&l⟸&r &7Reload Duration"
        - "&7✴ &c➣ &7#RELOAD_AMOUNT# &c&l⟸&r &7Reload Amount"
        #- "&7✴ &c➣ &7#EXPLOSION_RADIUS# &c&l⟸&r &7Explosion Radius"
        - "&7✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴ ✴  "
  Skin:
    Default_Skin: "NoSkin"
    Skins: "Blue,Pink,Red"

If you have that code in the Editor and try to select the entire skin part plus the empty line above, like this (in another editor):

![image](https://user-images.githubusercontent.com/30499120/103440460-2bba8d80-4c46-11eb-867c-7840cb74128b.png)

Then the panel will do this, because of the other characters in the code:

![image](https://user-images.githubusercontent.com/30499120/103440468-455bd500-4c46-11eb-81bd-5df144090a9b.png)

Just wanted to let you know, it doesnt affect what it copies but its kinda buggy visually

**Comment by MrPadingy** [comment]
You haven't followed the template before reporting this bug.

That looks like the old panel (0.7) This issue is not present in the supported 1.0 release so I'd recommend upgrading your panel.

Upgrading to 1.0 Documentation: https://pterodactyl.io/panel/1.0/upgrading.html#upgrading

![PLyBl0lgua](https://user-images.githubusercontent.com/40717029/103440667-7d134e80-4c3f-11eb-93aa-8528fd0b2776.gif)

**Comment by matthewpi** [comment]
Closing due to this being an issue on 0.7.
