### ISSUE TITLE
Suggestion: Online players graph

### ISSUE THREAD

**Issue by James76931** [Pterodactyl/Panel#296]
Hi,

Just a small little suggestion, would it be possible to have an online players graph with time stamps added to the panel in the future?

Thanks,
_- James_

**Comment by Technowix** [comment]
For now, as I understand, the stats Query haves been removed from the panel since there is no fully featured and maintained library to fetch thoses datas.
Ptero dev team will have to rewrite one I think, and this will take a lil bit more time :p

**Comment by DaneEveritt** [comment]
ref #98
