### ISSUE TITLE
xhr error poll

### ISSUE THREAD

**Issue by joppari** [pterodactyl/panel#2967]
http://bin.ptdl.co/731im
https://hastebin.com/aviseqohaz

tried installing custom egg but failed so i tried to uninstall it from the panel. But its giving error .

**Comment by FoksVHox** [comment]
How about you fill the templates, this isn't providing enough info to actually find the isse.

**Comment by matthewpi** [comment]
Please use our Discord or discussions for assistance with problems.  Issues are used for reporting bugs, not a channel for support.
