### ISSUE TITLE
wings error

### ISSUE THREAD

**Issue by IDKB0x** [pterodactyl/panel#2968]
whenever I start my wings I get this error 
![image](https://user-images.githubusercontent.com/71957022/103492649-e4710000-4df1-11eb-9af9-8ebc98676f7b.png)

**Comment by notAreYouScared** [comment]
Delete the config and grab a new copy from the panel. The keys are wrong

**Comment by IDKB0x** [comment]
wdym

**Comment by IDKB0x** [comment]
i got it but how do u stop the wing

**Comment by IDKB0x** [comment]
it worked nvm
