### ISSUE TITLE
Bug: Non-editable variables only using the value from the latest server for that particular game

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#297]
I have modified numerous service options to have variables that users can customize. For example, the ability to modify the server name or description as well as other values. These may be required or non-required, but they are visible and editable.

However, there are also other service options that are specified only by admins. Therefore these are classified as non-editable. They are still visible to the users and in most cases are required. This includes items such as an RCON port number or maximum players.

**Issue:** Any non-editable value seems to only use the value from the most recently created server for that particular game. For example, let's say we're talking about Minecraft. SRV1 has a non-editable value of {{SERVER_MAXPLAYERS}} which references the --max-players command in the startup command. Let's say SRV1 has a max players of 10. This command works normal when there is only one server. However, I created SRV2 for a friend which also has the max players variable. I created max players of 20 for SRV2. All works normal, it seems. However, the owner of SRV1 decided to change his server name to "Best Server" and then noticed that his max players changed from 10 to 20. He can't edit this because it's non-editable. I can edit this, but if he changes his startup arguments again, this value changes back to 20. I created SRV3 to test for myself. I configured SRV30 with 30 players. Now, if I edit either SRV1 or SRV2, the max players value now changes from 10 or 20 to 30. Thus, whichever server is the most recent is the one in which it seems the non-editable commands are following. These commands do not follow through to any other service options. For example, the {{SERVER_MAXPLAYERS}} value for Minecraft does not affect CS:GO. However, if I have 3 CS:GO servers, the same issue does persist.

I did not do further testing to determine if this being "not visible to the user" would affect anything. As you can imagine, this is really only a big deal because I specify non-editable RCON ports that the user should know. When SRV1 and SRV2 try to make a simple change to their server name or other value, their RCON ports change to whatever the most recent server is using for its RCON port and then they can't access RCON anymore.

**Comment by DaneEveritt** [comment]
We seem to have fixed this in `develop` at some point in time. I'll wait for you to play with it and confirm.

**Comment by xyeLz** [comment]
I have confirmed that this appears to be resolved in 0.6.
