### ISSUE TITLE
wings: automatically retry failed API requests

### ISSUE THREAD

**Issue by matthewpi** [pterodactyl/panel#2971]
This is an issue for tracking the progress of having wings automatically retry failed API requests.  The addition of this feature into wings is important for maintaining reliability and stability of all features.  Currently requests will only be tried once, this can be problematic if the Panel is temporarily unavailable for a short period of time but wings failed to send a request or in the case where unexpected behavior such as #2962 occurs.

The way this will be implemented is by writing a wrapper around the standard `net/http` library provided by Go and using an exponential back-off.

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/wings/commit/ddfd6d9cce4c025626ea72cecf8226495fba024f
