### ISSUE TITLE
Can't upload folders "Network error" in file manager

### ISSUE THREAD

**Issue by Oyplap** [pterodactyl/panel#2972]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.2.0
* Server's OS: Ubuntu-20.04-x86_64
* Your Computer's OS & Browser: Windows 10 pro, Edge Chromium

**Describe the bug**
I can't upload folders. For example i can't upload a minecraft map. It gives me a "Network error". But when i upload files like config.json or other small files, it works.

**To Reproduce**
1. Go to file manager
2. Drag and drop a folder. Not a file.
3. You can see that you can't upload a folder.

**Expected behavior**
To be able to upload folders/a minecraft map

Kind regards,
Oyplap

**Comment by Oyplap** [comment]
I have found a workaround by using winscp, so this isnt that big of a deal.

**Comment by trenutoo** [comment]
You can only upload a single file over the web, if you want to upload folders that consist of multiple files then you would have to archive the folder and upload it or use SFTP

**Comment by Oyplap** [comment]
> You can only upload a single file over the web, if you want to use upload folders that consist of multiple files then you would to archive the folder and upload it or use SFTP

Alright, thanks!
