### ISSUE TITLE
Random percent signs and numbers in file manager

### ISSUE THREAD

**Issue by Prophecized** [pterodactyl/panel#2973]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installing this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.2.0 
* Server's OS:  Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10  Microsoft edge

**Describe the bug**
I go to my file manager i go to delete a plugin or rename some of them has numbers and percent signs and others do not the ones that do not can be edited the name wise ones that do have the percent signs and numbers cant be edited or removed
**To Reproduce**
It is on all servers and it isnt the same it is different ones on every one

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
![Screenshot_379](https://user-images.githubusercontent.com/73750993/103566020-50ee0c80-4e8f-11eb-872a-0b520397a52f.png)
![Screenshot_380](https://user-images.githubusercontent.com/73750993/103566093-65caa000-4e8f-11eb-9191-45adf4e91ba1.png)
![Screenshot_381](https://user-images.githubusercontent.com/73750993/103566159-7f6be780-4e8f-11eb-8e30-dea8ccc6b81b.png)

**Comment by Prophecized** [comment]
Their is many more but I dont even know how it happened and no idea how to reproduce but I cant rename them if they have the numbers and percent signs

**Comment by matthewpi** [comment]
I recommend you try clearing your browser cache, I created a folder and file with a space in the name (`%20` if it was url-encoded) and I do not see the encoded name, it is properly displayed.

**Comment by DaneEveritt** [comment]
Update your panel.
