### ISSUE TITLE
JSON Config Parser not updating nested keys properly

### ISSUE THREAD

**Issue by GrenadeApe** [pterodactyl/panel#2975]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.2.0
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Manjaro & Chrome

**Describe the bug**
When creating a custom egg nested JSON config files are not parsed properly to replace values. First level keys are matched and replaced properly, however second level keys are not matched.

**To Reproduce**
1. JSON config file like this:
{
	"serverLogId": "server_log_ID_here",
	"apiKeys": {
		"apiKey1": "your_API_key_here",
		"apiKey2": "your_API_key_here"
	}
}
2. Use config file parser setup like this:
{
	"config.json": {
	    "parser": "json",
	    "find": {
			"serverLogId": "{{server.build.env.LOG_CHANNEL}}",
			"apiKeys": {
				"apiKey1": "{{server.build.env.apiKey1}}",
				"apiKey2": "{{server.build.env.apiKey2}}"
			}
		}
	}
}
3. Create server with egg
4. Start server
5. Check config file, it looks like this:
{
	"apiKeys": {
		"apiKey1": "your_API_key_here",   # Unchanged
		"apiKey2": "your_API_key_here"    # Unchanged
	},
	"serverLogId": 1234567890123  # Proper value substituted
}

**Expected behavior**
All key pairs should have their values updated to the customized env variables.

**Comment by matthewpi** [comment]
Try using
```
{
  "config.json": {
    "parser": "json",
    "find": {
      "serverLogId": "{{server.build.env.LOG_CHANNEL}}",
      "apiKeys.apiKey1": "{{server.build.env.apiKey1}}",
      "apiKeys.apiKey2": "{{server.build.env.apiKey2}}"
    }
}
```

For the config parser configuration.

**Comment by GrenadeApe** [comment]
I swear I tried that previously, but that works! Thank you!
