### ISSUE TITLE
Pterodactyl Unaccessable Due To MySQL Corruption + Missing Dependency Loops

### ISSUE THREAD

**Issue by ethsmith** [pterodactyl/panel#2976]
Hello! 

My Ubuntu basically needs to be reinstalled due to some massive corruption with the mysql and apt-get packages. I am trying download my server files from the docker containers but both docker export and docker save do not have the files present when I export them on my windows. What can I do to download my 3 servers' files to the host and then download that to my windows PC for a backup? Any help would be appreciated. 

I have used docker before but usually I can login with root and just install a few things and I would just zip it and download the zip to the host. It is a way the docker containers were setup by pteerodactyl which is making me not sure how to get these files if there is read only stuff and i can't use root.

**Comment by ethsmith** [comment]
Like I really really need help with this

**Comment by matthewpi** [comment]
Please use our Discord or create a discussion for support.  Creating an issue is for reporting bugs or requesting features.

However, server files are located by default in `/var/lib/pterodactyl/volumes` unless you upgraded from 0.7 in which case they will most likely be in `/srv/daemon-data`

**Comment by ethsmith** [comment]
@matthewpi I already did. No one either knows how to help me or is busy. This is important. Also when I search through the file system of the container. I do not see anything like that.

**Comment by matthewpi** [comment]
The container doesn't store the files of the server, it's on the host system.  If you can get into SSH or SFTP, the files will be located in one of those directories unless you specified a custom directory which you can check by looking at the `config.yml` located in `/etc/pterodactyl`.

**Comment by ethsmith** [comment]
Oh! I misunderstood the purpose of the docker containers. Thanks!
