### ISSUE TITLE
the  question of disk limited

### ISSUE THREAD

**Issue by 2300206764** [Pterodactyl/Panel#298]
i am sorry that i have make a unvaluable question.But could you please tell me where is the codes which control the disk limit. Or it has been deleted?

**Comment by Darksleep** [comment]
As far as i know there is no disk space control for  game servers

**Comment by DaneEveritt** [comment]
@darksleep is correct, disk space is an option but we have not yet found it implemented a suitable method for controlling it.

**Comment by 2300206764** [comment]
ok.if it will be add in future?

**Comment by DaneEveritt** [comment]
We plan to add it, but we were hoping for better docker integration with it. Certain filesystems in docker allow it, but they aren't supported on all systems, so we don't push it right now.
