### ISSUE TITLE
Node is restarting automatically

### ISSUE THREAD

**Issue by theredcmdcraft** [pterodactyl/panel#2984]
Hey, i am From GamesRapid an we use the Pterdactyl GamePanel. All works fine, but our one Node/Host is restarting automatically. We don´t know why? Does the @Developer has an idea why the node is restarting? We in the Team think it is why the server is overloaded but there are more than 2gb of ram free. So we can exclude this. If someone other has an idea please anwser me.

**Comment by parkervcp** [comment]
have you checked the previous dmesg logs to see if there were any errors to case a restart yet?

**Comment by DaneEveritt** [comment]
This a.) doesn't follow our bug reporting template and b.) is unlikely an issue with this software.
