### ISSUE TITLE
Error while trying to update password.

### ISSUE THREAD

**Issue by BaxAndrei** [pterodactyl/panel#2988]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel 1.2.1 | Daemon 1.2.2
* Server's OS: CentOS Linux release 7.9.2009 (Core)
* Your Computer's OS & Browser:  Win 10 pro & Chrome latest version

**Describe the bug**
When user try to update his password, this error occur: ![image](https://user-images.githubusercontent.com/12484505/104106087-a2e1c880-52bb-11eb-9a99-f61afd1b9521.png)

**To Reproduce**
1. Login
2. Go to account
3. Enter current password
4. enter new pass
5. repeat new pass
6. submit
7. see error

**Expected behavior**
No error will occur and user will be able to update his password

Extra: no error log was created.
EDIT: Also users comaping that recovery email never get to them.

**Comment by DaneEveritt** [comment]
Your system is redirecting a PUT request to GET. This is not a bug with this software, rather a configuration issue with your system.

**Comment by BaxAndrei** [comment]
Wow, what a support. I wouldn't have made a ticket if this problem hadn't appeared after an update ... Anyway, it doesn't matter anymore, I'll solve it myself.

**Comment by FoksVHox** [comment]
> Wow, what a support. I wouldn't have made a ticket if this problem hadn't appeared after an update ... Anyway, it doesn't matter anymore, I'll solve it myself.

The issue tracker isn't for support, use the Discord. Also Pterodactyl is licensed under MIT, which means that there isn't a warranty of support.

**Comment by DaneEveritt** [comment]
This is not a support ticketing system, please check your ego at the door.
