### ISSUE TITLE
wings: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Nobodyno-boop** [pterodactyl/panel#2989]
* Panel: 1.2.1
* Version of Panel/Daemon: 1.2.2
* Server's OS: Ubuntu 18.04.5 LTS (both machine) 
* Your Computer's OS & Browser: windows 10 & brave

**Describe the bug**
i have one machine for the panel and one for wings, 
But the node works not properly...
`Failed to load resource: net::ERR_CONNECTION_REFUSED` when i'm on `admin/nodes`
But view server work (`admin/nodes/view/1`)
(server panel on panel[domain.fr], wings on node[domain.fr] linked with dns zone A. SSL enable.)

i have see on [DeamonConfigurationRepository.php](https://github.com/pterodactyl/panel/blob/6893f9bfcdc858a17f2e7144967ba84917a7ff9f/app/Repositories/Wings/DaemonConfigurationRepository.php#L20) the http request. Maybe is not work because not the same origin?

**Comment by Nobodyno-boop** [comment]
My bad. DNS zone take long time to setup correctly. Now its work properly.

**Comment by GraveyardEnthusiast** [comment]
> My bad. DNS zone take long time to setup correctly. Now its work properly.

Im having this problem, how did you fix it?

**Comment by Enoal-Fauchille-Bolle** [comment]
bruh same
