### ISSUE TITLE
csgo download uses more cpu than server limit 

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#2990]
Hey. I've set limit for server to 1ghz however it uses more than 6ghz. Is it possible to limit installation cpu ?

Also is it possible to somehow symlink/cache steamcmd downloads so it wouldn't download(and freeze server) on each installation ?

![image](https://user-images.githubusercontent.com/6473565/104133352-c07e6300-538b-11eb-801c-2d9d98218a08.png)

**Comment by parkervcp** [comment]
install containers do not get limited due to it causing installs to fail at one point.

**Comment by BenasPaulikas** [comment]
Ok makes sense. Any suggestions how to optimize CS GO installation ? So it wouldn't download same files over and over ?
