### ISSUE TITLE
More documentation on Filters and Additional Parameters

### ISSUE THREAD

**Issue by samdev-7** [pterodactyl/panel#2991]
**Is your feature request related to a problem? Please describe.**
So I've been trying to use the API but it has no documentation on how to use the Filters or Parameters.
An example is [List Users](https://dashflo.net/docs/api/pterodactyl/v1/#req_5703791f721f4b50bb0318cf19e2262d), it says that filters could be used but never said how it could be used.

**Describe the solution you'd like**
Provide more documention on the Filters and Additional Parameters

**Describe alternatives you've considered**
There are some alternatives solutions to some of the problems but, for example, the list users, you could manually search the JSON but it has a limit and does not display all users.

**Additional context**
Using Pterodactyl v1 API

**Comment by trenutoo** [comment]
The documentation you linked is not official API documentation nor controlled by Pterodactyl directly, I think one of the moderators is managing it.

The API documentation is there to show you the endpoints without you having to scan them. The documentation shows you the parameters and filters that are available, it also shows how to use them in the "Docs Guide" section in the beginning, however it's the same for all APIs really.

**Comment by MASSKAgithub** [comment]
For using filters or params just add this things to the end of the url that you request:

Filters:
> yourdomain.com/pathtoyourapicall/**?filter[email]=something**

=> here you can replace the email by the available filter shown in the docs.

Parameters:
> ?example=something&example2=something

or ?include=PARAMHERE
if it doesn't have any value

=> so just add this add the end of your url as before but replace example by the available param and something by the value, if you wanna second param add $ between.
