### ISSUE TITLE
SFTP not working with Intellij deployement tool

### ISSUE THREAD

**Issue by tutur1004** [pterodactyl/panel#2994]
**Background (please complete the following information):**
* Panel or Daemon: 1.2.1
* Version of Panel/Daemon: 1.2.3
* Server's OS: Debian 10
* Your Computer's OS & Browser: Win10/Chrome

**Describe the bug**
I want use pterodactyl sftp subusers with Intellij Deployement Tool, but Intellij can't resolved the connection.

**To Reproduce**
1. I create a server (In pterodactyl panel).
2. I test the sftp connection with FileZilla on my PC, it's work.
3. I register my login informations in Intellij SSH Configurations, then Test connection, and it's Successfully connected !
4. Now I'm trying to use this SSH Configuration in the SFTP connection, but the Test Connection in this tab can't resolved the connection.

**Expected behavior**
I think, it's because when you try to connect as a SSH client you get this :
* X11 forwarding request failed on channel 0
* PTY allocation request failed on channel 0
* shell request failed on channel 0

Because this SSH connection haven't shell access ?

**Comment by DaneEveritt** [comment]
Correct, it is SFTP only. I don't care to deal with supporting a non-standard SFTP client like that.
