### ISSUE TITLE
Teamspeak Egg wrong Query Startup Command

### ISSUE THREAD

**Issue by Paddyboy1991** [pterodactyl/panel#2995]
Hello,
I found a wrong Startup Command at the Teamspeak Egg..
The standard Query Port from Teamspeak is 10011 and the Container start with this Port, but in the completly Egg is in the startup command the SERVER_PORT defined.. so is my Teamspeak Port for Users (standart 9987) then is the query port the same port too.. I miss a option to define the query port extra..

![Screenshot_1](https://user-images.githubusercontent.com/16993167/104266087-391a1800-548f-11eb-9c68-87843a0f88f4.png)
Filemanager have an Option but Query Port not.
Cheers

**Comment by Slitzo3** [comment]
I think this is a issue for this repo: https://github.com/parkervcp/eggs

As this is the repo for the panel/wings. So i would suggest you to post the issue there and close it here.

**Comment by gOOvER** [comment]
Teamspeak Egg is default shipped with ptero, so the Report is fine here

**Comment by Paddyboy1991** [comment]
> I think this is a issue for this repo: https://github.com/parkervcp/eggs
> 
> As this is the repo for the panel/wings. So i would suggest you to post the issue there and close it here.

"name": "Teamspeak3 Server",
"author": "support@pterodactyl.io",

i think it is right here ;)
