### ISSUE TITLE
Add Boolean -> Always Restart on STOP

### ISSUE THREAD

**Issue by IlPicasso** [Pterodactyl/Panel#300]
I wanted to suggest a way to add an option to ALWAYS RESTART the server

This will be useful for minigames servers

**Comment by DaneEveritt** [comment]
Seems like a very game-specific option, and how would you actually stop the server rather than having it reboot?

The easiest hacky way to do this is make the server stop without outputting stop to the console, or sending a command that does not show as stop for the server `stop -d` for example.
