### ISSUE TITLE
Creating Client API keys using Application API

### ISSUE THREAD

**Issue by Juan-Esc** [pterodactyl/panel#3000]
**Is your feature request related to a problem? Please describe.**
There's no way to generate a Client API key without actually login in the panel and creating it in the settings section.

**Describe the solution you'd like**
It would be awesome if you could create API keys for users directly via the Application API. That way users would not have to do it and would be easier for them.

**Additional context**

**Comment by DaneEveritt** [comment]
This is intentional, I will not be adding CLI API key creation for clients, it makes no sense since they're already a client and wouldn't have CLI access.

**Comment by lightPlugins** [comment]
Then how can i start/stop servers from a specified user over the application API ?

**Comment by tim-dreier** [comment]
@lightPlugins Take a look at this composer package for the pterodactyl panel server which adds some endpoints to the api so you can create an client api token using the application api. After that, you can store and use the created client token.

https://github.com/Rene-Roscher/pterodactyl-api-addon

**Comment by vpb11** [comment]
There is a new one and I can confirm working as of today writing this post. https://github.com/PteroCA-Org/pterodactyl-addon/tree/main
