### ISSUE TITLE
Java being unable to create more threads

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#3001]
**Background (please complete the following information):**
* Panel or Daemon:  Daemon
* Version of Panel/Daemon: Wings@1.2.3 | Panel@1.2.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 Pro | Firefox

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

I am having an issue where my servers are getting Out Of Memory errors, even though my System, and Servers have enough Memory spare.

Here is an example of one of the errors:
`[11:10:01 WARN]: Exception in thread "luckperms-hikari connection closer" java.lang.OutOfMemoryError: unable to create new native thread
[11:10:01 WARN]:        at java.lang.Thread.start0(Native Method)
[11:10:01 WARN]:        at java.lang.Thread.start(Thread.java:717)
[11:10:01 WARN]:        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
[11:10:01 WARN]:        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
[11:10:01 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[11:10:01 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:10:01 WARN]:        at java.lang.Thread.run(Thread.java:748)`

This usally happens if I have more than 7 servers online at one time.

Linux ns3022662 4.15.0-130-generic #134-Ubuntu SMP Tue Jan 5 20:46:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 27
  Running: 11
  Paused: 0
  Stopped: 16
 Images: 12
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-130-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.79GiB
 Name: ns3022662
 ID: QRTU:YQW6:A35Z:YV36:XGTI:LWIZ:IVG4:K6GW:XVLW:GWDS:Y54I:V6VE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**To Reproduce**
1. Create ~7 servers.
2. Start them all.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

All my servers to run without any of these errors.

**Comment by trenutoo** [comment]
The issue is with Java being unable to create more threads, not the lack of memory

**Comment by ghost** [comment]
> 
> 
> The issue is with Java being unable to create more threads, not the lack of memory

Ah, sorry! My bad! By any chance do you know how I can fix this?

**Comment by trenutoo** [comment]
> > The issue is with Java being unable to create more threads, not the lack of memory
> 
> Ah, sorry! My bad! By any chance do you know how I can fix this?

Do you have a VPS? You are reaching the max thread limit of your system or JVM, probably have some plugin causing that since the limit by default is 32k which is very high.

You could increase the thread's max limit or better check the amount used and if it's really high, then find what is creating so many. Some VPS providers limit the available system threads, I've encountered this same issue once when I was testing Contabo VPS.

**Comment by ghost** [comment]
> 
> 
> > > The issue is with Java being unable to create more threads, not the lack of memory
> > 
> > 
> > Ah, sorry! My bad! By any chance do you know how I can fix this?
> 
> Do you have a VPS? You are reaching the max thread limit of your system or JVM, probably have some plugin causing that since the limit by default is 32k which is very high.
> 
> You could increase the thread's max limit or better check the amount used and if it's really high, then find what is creating so many. Some VPS providers limit the available system threads, I've encountered this same issue once when I was testing Contabo VPS.

I am running a Dedi from Soyoustart. Would it be possible to increase the limit?

Or would I be able to find out what is using so much?

**Comment by schrej** [comment]
Not caused by Pterodactyl, so not a bug.

**Comment by toster234** [comment]
> Not caused by Pterodactyl, so not a bug.

@schrej Were you able to fix this issue?
Have the exact same problem after updating wings from 1.2.3 to 1.4.5, were thread limits changed between those versions?

**Comment by trenutoo** [comment]
> > Not caused by Pterodactyl, so not a bug.
> 
> @schrej Were you able to fix this issue?
> Have the exact same problem after updating wings from 1.2.3 to 1.4.5, were thread limits changed between those versions?

1.4.5 has container pid limit in the wings config for you to adjust.
