### ISSUE TITLE
Console text is grey on white background in Command input field

### ISSUE THREAD

**Issue by tmunsch** [pterodactyl/panel#3002]
Panel or Daemon: Panel
Version of Panel/Daemon: Panel- 1.2.1 Daemon - 1.2.3
Server's OS: Ubuntu 20.04 
Your Computer's OS & Browser: Chrome

**Describe the bug**
Console input field renders with grey text on a white background when typing.

**To Reproduce**
1. Go to Console
2. Type Something
3. Hard to read
4. See white on white

![image](https://user-images.githubusercontent.com/27962004/104551352-ba46eb80-5604-11eb-9e0b-b8f620523733.png)

**Expected behavior**
Text should be easily legible from the console input field

**Comment by notAreYouScared** [comment]
![2021-01-14_01-15-45](https://user-images.githubusercontent.com/1757840/104552072-12322200-5606-11eb-8154-c1db702597fc.gif)

Also tested on 
Chrome Version 87.0.4280.141 (Official Build) (64-bit)
Chrome Beta Version 88.0.4324.87 (Official Build) beta (64-bit)
Edge Version 87.0.664.75(64bit)

**Comment by justinbea** [comment]
I have the same after a clear install/update there is nothing wrong but when I run yarn run build:production it just breaks the chat box couldn't find a solution either!
![image](https://user-images.githubusercontent.com/34838726/105233359-0a283400-5b6a-11eb-9acc-0261807cc8e0.png)

**Comment by DaneEveritt** [comment]
@justinbea are you using some customized JS logic or something? What happens if you run `yarn install` before building?

**Comment by justinbea** [comment]
@DaneEveritt nope I'm not using any customized JS logic, only clear installed panel files, everytime I do `yarn run build:production` it makes that box white etc, but when I curl in the latest files it sets it back to normal, yarn install and than building doesn't change anything, only these errors appear but idk if that is an issue, saw parker posting it in the Discord I believe.
![image](https://user-images.githubusercontent.com/34838726/105259452-1e7d2880-5b8c-11eb-9426-891bc34f2312.png)

**Comment by BenHall-1** [comment]
We found that the default text-neutral-100 on the text box was way too light for the theme and switched to text-primary-900 - this solved the above issue that others were having (resources/scripts/components/server/Console.tsx line 219)

**Comment by justinbea** [comment]
![image](https://user-images.githubusercontent.com/34838726/105579986-f9ee9f80-5d89-11eb-8118-414f767668fb.png)
didnt help for me only changed the $ sign in blue?

**Comment by BenHall-1** [comment]
Sorry wrong line, add the following below type={'text'} on line 223
```
css = {tw`text-primary-900`}
```

**Comment by DaneEveritt** [comment]
The box isn't supposed to be white, changing the color isn't really the correct fix, but I guess it works for now.

**Comment by justinbea** [comment]
@BenHall-1 Now it kinda looks like this xD
![image](https://user-images.githubusercontent.com/34838726/105624457-25bd6400-5e22-11eb-92f9-6f66df201541.png)

@DaneEveritt Yea I know just after the rebuild of assets with yarn it does that, after I reinstalled the files from the github its fine.

**Comment by stefandev15** [comment]
@justinbea you changed the wrong thing. 
![image](https://user-images.githubusercontent.com/75332399/105627530-0d5c4200-5e40-11eb-9f79-972d75ebe19b.png)
It should be like this

**Comment by justinbea** [comment]
@kor3y I also tried that but didn't change anything

**Comment by stefandev15** [comment]
> @kor3y I also tried that but didn't change anything

this dose not make it go back to normal, this only makes the text that is hard to read more visible
![image](https://user-images.githubusercontent.com/75332399/105635730-24fdef80-5e6d-11eb-9a05-876e9458268a.png)
![image](https://user-images.githubusercontent.com/75332399/105635744-3d6e0a00-5e6d-11eb-90de-3ca7367788c7.png)

**Comment by justinbea** [comment]
Yea i'k but than the box is still white wich isn't meant to be or?

**Comment by stefandev15** [comment]
Currently, only managed to fix the text

**Comment by stefandev15** [comment]
Stll it is way better than before

**Comment by DaneEveritt** [comment]
Closed by https://github.com/pterodactyl/panel/pull/3050

**Comment by justinbea** [comment]
Is yarn than just broken as it rebuilds it in other files than original? or just closing it and leave it how it is?
