### ISSUE TITLE
Pterodactyl Wings API Error

### ISSUE THREAD

**Issue by 0xIO32** [pterodactyl/panel#3006]
I have a problem!😒

I can't get into the Pterodactyl Wings API because an error occurs

Code: 403
Message: "You are not authorized to access this endpoint."I have a problem!

I can't get into the Pterodactyl Wings API because an error occurs

Code: 403
Message: "You are not authorized to access this endpoint."

**Comment by DaneEveritt** [comment]
Please stop ignoring the very obvious and clear issue reporting template, it is a waste of everyone's time. Additionally, this isn't a bug, use Discord for help.

**Comment by 0xIO32** [comment]
I have but nobody helps me there
