### ISSUE TITLE
 Allocated Memory set to 0 interpreted as 0 and not as "unlimited memory"

### ISSUE THREAD

**Issue by gekigek99** [pterodactyl/panel#3007]
**Background (please complete the following information):**
* Panel or Daemon: daemon
* Version of Panel/Daemon: v1.2.3
* Server's OS: ubuntu 20.04
* Your Computer's OS & Browser: windows, firefox

**Describe the bug**
A clear and concise description of what the bug is:
if I set 0 as parameter in the game server's "Allocated Memory" it gets interpreted as 0 and not as "unlimited memory"
Please provide additional information too, depending on what you have issues with (Daemon):
uname -a:
`Linux vmserver 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

docker info:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-62-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.816GiB
 Name: vmserver
 ID: 2MBI:CDSM:76KI:VDCS:OK6S:7BN2:CK2Z:OL3P:IZIY:IBDJ:LI2N:C6QM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

**To Reproduce**
- install a minecraft server vanilla with the default egg
- in build config change the allocated memory to 0
- launch the server in the console
- error launching game server

**Expected behavior**
game server should be launched without the `-Xmx` parameter and not with `-Xmx0MB`

**Comment by parkervcp** [comment]
This is an issue with java base applications alone.

**Comment by parkervcp** [comment]
I called out a fix here. https://github.com/pterodactyl/panel/issues/2316#issuecomment-688016590

There have been numerous other issues opened for this.
