### ISSUE TITLE
Schedules Import and Export

### ISSUE THREAD

**Issue by hwalker928** [pterodactyl/panel#3010]
**Is your feature request related to a problem? Please describe.**
Currently, you have to manually remake the schedule each time. It would be a lot easier to create some sort of import and export function to solve this. 

**Describe the solution you'd like**
2 new buttons. One on the main schedules page for importing/uploading an existing schedule. Another on the edit schedule area to export the said schedule as a downloadable file. 

**Describe alternatives you've considered**
Manually creating the schedule and adding the information. 

**Additional context**
None.

**Comment by DaneEveritt** [comment]
Duplicate https://github.com/pterodactyl/panel/issues/1346
