### ISSUE TITLE
On Backup Limit, last Backup not deleting. instead of last the newest is deleting/ RESLOVED in 1.2.0

### ISSUE THREAD

**Issue by GekkeGlennDev** [pterodactyl/panel#3012]
**Background (please complete the following information):**
* Panel or Daemon:  panel and daemon
* Version of Panel/Daemon: 1.1.3
* Server's OS: Unbunto 18.04
* Your Computer's OS & Browser: Windows 10 and google chrome

**Describe the bug**
If the backup limit is reached. Then the newest backup is going to deleted. And i had searched in the code and found this:
```
// Remove oldest backup
$oldestBackup = $server->backups()->where('is_successful', true)->orderByDesc('created_at')->first();
$this->deleteBackupService->handle($oldestBackup);
```
Here is something going wrong. Instead of he get the last backup to delete. He get the newest backup for deleting.
I found this code in: app/services/Backups/InitiateBackupService.php on line 127.

**To Reproduce**
1. Go to a server and then the backup section
2. Click on create new backup. If your limit is reached (use for this example 2 backup slots.
4. Now see that the older backup is not deleted, Instead of the oldest the newest backup is deleted.

**Expected behavior**
The oldest backup has to delete. instead of the newest one.

![Screenshot 2021-01-17 134550](https://user-images.githubusercontent.com/44021961/104843336-5b19fd00-58ca-11eb-9c63-bd8a13d8a7a1.png)

**Comment by trenutoo** [comment]
You did not fill in the template correctly, what is your version?

The issue was resolved in 1.2.0

**Comment by GekkeGlennDev** [comment]
I forgot to set it. 
Panel is 1.1.3

**Comment by GekkeGlennDev** [comment]
deamon 1.1.3
