### ISSUE TITLE
 Settings to change favicon and logo

### ISSUE THREAD

**Issue by timossileandro** [pterodactyl/panel#3013]
**Is your feature request related to a problem? Please describe.**
It would be a good idea to have options in the panel configuration that upload an SVG image to modify the logo on the login screen and the favicon in the browser.

![Screenshot_1](https://user-images.githubusercontent.com/17083780/104846286-81cf3800-58b8-11eb-8e05-56c9b8acde1a.png)

![Screenshot_2](https://user-images.githubusercontent.com/17083780/104846294-8ac00980-58b8-11eb-8140-714f029cbbdc.png)

**Describe the solution you'd like**
I would add two new parameters in configuration:

![image](https://user-images.githubusercontent.com/17083780/104846310-9c091600-58b8-11eb-9518-4dffdb5a05d2.png)

![image](https://user-images.githubusercontent.com/17083780/104846367-e8ecec80-58b8-11eb-8160-e912edd490d0.png)

**Comment by nikrozman21** [comment]
You can already do so quite easily by simply replacing the two mentioned files.
Even then, I think Pterodactyl panel and its creators should get at least some recognition.
It's almost as if one wanted to have the copyright notice removed or changed.

**Comment by matthewpi** [comment]
There is not going to be options for customization like this, if you want to customize it, replace the file or edit the code to point to a new asset.

**Comment by ririko5834** [comment]
Where can I find the code that I should edit?

**Comment by ghost** [comment]
> Where can I find the code that I should edit?

yeah

**Comment by cashlycash** [comment]
> mentioned

yes please tell

**Comment by anondev-sudo** [comment]
I edit it manually by overwriting the files currently but that option would be appreciated to set favicon and login screen logo (pterodactyl will still have copyright in the footer with link to pterodactyl docs - I dont want to remove pterodactyl branding). 
I have to edit it manually after every update so I think that this option would be really good.

**Comment by shubhankartrivedi** [comment]
Yeah it should have a custom logo setting also.

**Comment by rmflom** [comment]
The files you need to change are here:

**/var/www/pterodactyl/public/assets/svgs** (If you want to change the login page picture to something else - Change pterodactyl.svg)

**/var/www/pterodactyl/public/assets** (If you need to change anything on the login page like the filename for the above mentioned picture or the text that says Login to continue - Change auth.32bd45c4.js)

**/var/www/pterodactyl/public/favicons** (all the favicons)

Hope this helps

**Comment by aliencord** [comment]
> The files you need to change are here:
> 
> **/var/www/pterodactyl/public/assets/svgs** (If you want to change the login page picture to something else - Change pterodactyl.svg)
> 
> **/var/www/pterodactyl/public/assets** (If you need to change anything on the login page like the filename for the above mentioned picture or the text that says Login to continue - Change auth.32bd45c4.js)
> 
> **/var/www/pterodactyl/public/favicons** (all the favicons)
> 
> Hope this helps

Also don't forget to take down the site first putting it into maintenance mode by:
`cd /var/www/pterodactyl`
`php artisan down`
`php artisan view:clear`
`php artisan config:clear`
# If using NGINX or Apache (not on CentOS):
`chown -R www-data:www-data /var/www/pterodactyl/*`

# If using NGINX on CentOS:
`chown -R nginx:nginx /var/www/pterodactyl/*`

# If using Apache on CentOS
`chown -R apache:apache /var/www/pterodactyl/*`
`php artisan queue:restart`
`php artisan up`

Then clear your browser cache.
