### ISSUE TITLE
Copy egg contents to add eggs

### ISSUE THREAD

**Issue by ElijahRus250** [pterodactyl/panel#3014]
**Is your feature request related to a problem? Please describe.**
My request is not an issue however it would make updating and adding eggs a lot easier.

**Describe the solution you'd like**
Currently you have to upload a json file, this is really annoying due to when you are in the eggs repo, you cannot just download one you have to either download all of them or copy and paste one into local make the json folder, It would make more sense if you could copy and paste the contents aswell as have the option to upload. 

**Describe alternatives you've considered**
You could upload a file but im lazy

**Additional context**
It would have a little button "Paste egg files contents" and would let you paste it in

**Comment by DaneEveritt** [comment]
Its like one extra step to download and drag the file over to the UI, I don't want to add a giant text box that does literally the same thing as dropping a file on the screen (sorry @matthewpi). Let us also not forget uploading eggs is almost always an infrequent action, this is just optimizing for an infrequent scenario.

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/commit/e8ddadc608b940eeb9a5da83566de800e96f9016
