### ISSUE TITLE
Changing APP_URL doesn't change the URL it redirects to

### ISSUE THREAD

**Issue by Robin-Sch** [pterodactyl/panel#3017]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 9684456
* Server's OS: Ubuntu

**Describe the bug**
Updating the `APP_URL` in `docker-compose.yml` doesn't update the redirect URL

**To Reproduce**
1. Put `https://test1.domain.com` as app URL
2. Run `docker-compose up`
3. Exit
4. Change the app URL to `https://test2.domain.com`
5. Run `docker-compose up`
6. Watch it creating a new certificate for `test2.domain.com`

**Expected behavior**
The IP should redirect to `https://test2.domain.com`, but instead, it will still redirect to `https://test1.domain.com`.

I already tried deleting the containers, images, Github repo, `/etc/pterodactyl` (where the volumes are).
After that cloning this repo, setting the `APP_URL` to `https://test2.domain.com`, but it still redirects to `https://test1.domain.com`.

**Comment by DaneEveritt** [comment]
If you deleted everything and started fresh and it still redirects, what exactly leads you to believe it is an issue with this software, and not a DNS configuration issue or a cached browser redirect?

**Comment by Robin-Sch** [comment]
it's a problem with docker because it's installed from the snap store. I had to manually install it.
