### ISSUE TITLE
Sub-user console commands blacklist with regex support

### ISSUE THREAD

**Issue by Malachiel87** [pterodactyl/panel#3018]
**Is your feature request related to a problem? Please describe.**
More security, example i add somesone to console as subuser, i dont wanna he to be able to run some security commands

**Describe the solution you'd like**
when you add a subuser you can specific along the permission a sort of blacklisted worlds (with regex maybe?) that if are typed on console it will be prevented blocked with a popup warning "This command is disabled is disabled by the server owner",

**Describe alternatives you've considered**
I don't  think exist any alternative than don't give the guy the console :)

**Additional context**
Nah, i think woul be super usefull and make the server ower more safer

**Comment by iSilviu-debug** [comment]
**I approve of this idea too I use pterodactyl** 

In addition to the console, I don't know if this function is already implemented, but a sub-user, when he has access to the file manager, can touch all the files on the server. One thing I don't want is that it can touch **my** database configuration files.
`it is so insecure`

**Other**
🌵

**Comment by parkervcp** [comment]
If you are giving a user access to the to the file manager/console you should trust them.

**Comment by Malachiel87** [comment]
> If you are giving a user access to the to the file manager/console you should trust them.

Yeah, but for example on Minecraft: I wanna give all commands except permission commands plugin

**Comment by iSilviu-debug** [comment]
Yeah, or if I trust a person but don't want them to see some files such as store licenses or other plugins

**Comment by DaneEveritt** [comment]
I will not be implementing this feature, I do not believe in creating a system that has so many footguns just to say a user can run only these subsets of commands.

**Comment by iSilviu-debug** [comment]
Too bad, it could have served users so much for their server and staff management ...

**Comment by parkervcp** [comment]
I state my prior argument. 

> If you are giving a user access to the to the file manager/console you should trust them.

**Comment by parkervcp** [comment]
> > If you are giving a user access to the to the file manager/console you should trust them.
> 
> Yeah, but for example on Minecraft: I wanna give all commands except permission commands plugin

My argument against this is in game perms. They don't need console access to use the commands.

**Comment by iSilviu-debug** [comment]
> > > Se stai dando a un utente l'accesso al file manager / console dovresti fidarti di loro.
> > 
> > 
> > Sì, ma ad esempio su Minecraft: voglio dare tutti i comandi tranne il plugin dei comandi di autorizzazione
> 
> Il mio argomento contro questo è nelle permanenti di gioco. Non hanno bisogno dell'accesso alla console per utilizzare i comandi.

This seems right to me. 
For the fact of the file manager anyway? 
For example, if you want to keep your database password or a license key visible in the config, at least not seen in subusers.

**Comment by DaneEveritt** [comment]
I'm sorry you feel this way, but I have extremely limited time to work on this project as is and my priorities lie with requests made by those who are sponsoring the project, for which there are numerous big-ticket items. This feature has no such priority because of that, and because I do not believe it to be beneficial to the majority of users. Additionally, as @parkervcp  mentioned it is possible to have such functionality by just using in-game plugins and permission systems.

As for the file manager that is a _completely_ different story, and a feature that is already in the works. However, it is unlikely to solve the specific issue you are trying to solve, for which I can only suggest not giving user's access to systems for which you do not trust them.
