### ISSUE TITLE
Feature Request: User editable username, first name, and last name

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#302]
In the current design, the new account creation process requires an administrator to configure a username, first name, and last name for a user during account setup, thus also requiring the administrator to actually know what username that particular user would like as well as what their first and last name are. These are actually really good options to have (for integration with something like Blesta or WHMCS), but tedious if I have no idea what the person's name is or what username they would like to use.

Would it be possible to still allow us to configure this for the user (which prevents them from logging in, if possible), but also not force an administrator to *require* this feature, but instead require the user to configure this when they receive their email?

**Comment by DaneEveritt** [comment]
Not going to change this because it starts to get really confusing to manage when there are a bunch of not-required fields that can later be changed.
