### ISSUE TITLE
Servers can not be transferred between nodes: connection timed out

### ISSUE THREAD

**Issue by OpenSource03** [pterodactyl/panel#3025]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.2.3
* Server's OS: Debian 10
* Your Computer's OS & Browser: macOS, Safari

**Describe the bug**
There is an error when trying to transfer a server. All firewalls are turned off. Servers can ping each other, however, there is still a "connection timed out" message. The message below is the output on the destination server.
```
 INFO: [Jan 22 12:49:16.538] downloading server archive from current server node server_id=43089b81-9353-4e0e-adcc-bff8569c3d76 subsystem=transfers
ERROR: [Jan 22 12:49:23.677] failed to download archive for server transfer error=Get "https://ju$$$.$$$$$flow.cloud:8080/api/servers/43089b81-9353-4e0e-adcc-bff8569c3d76/archive": dial tcp 185.$$.148.134:8080: connect: connection timed out server_id=43089b81-9353-4e0e-adcc-bff8569c3d76 subsystem=transfers

Stacktrace:
Get "https://ju$$$.$$$$$$$flow.cloud:8080/api/servers/43089b81-9353-4e0e-adcc-bff8569c3d76/archive": dial tcp 185.$$.148.134:8080: connect: connection timed out
github.com/pterodactyl/wings/router.postTransfer.func1
        /home/runner/work/wings/wings/router/router_transfer.go:359
runtime.goexit
        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/asm_amd64.s:1374



 INFO: [Jan 22 12:49:23.678] notifying Panel of server transfer state server_id=43089b81-9353-4e0e-adcc-bff8569c3d76 subsystem=transfers transfer_successful=false
```

**To Reproduce**
Try to transfer a server between nodes.

**Comment by matthewpi** [comment]
This is a problem with your networking or firewall.  Your target node (where the server is being transferred to) cannot connect to your source node (where the server currently installed).
