### ISSUE TITLE
Data Import 

### ISSUE THREAD

**Issue by mirmen** [pterodactyl/panel#3029]
Add the ability to import all data from FTP/SFTP to the panel. The data will be copied to your server and you will non need to do it manually.

**Comment by parkervcp** [comment]
I am not even sure what this means.

**Comment by mirmen** [comment]
> I am not even sure what this means.

I'm from Russia. Using Google translator. The bottom line: you have 2 servers. 1 already has ready-made files, but 2 no files. Using this function, you can import data from 1 server 2 via SFTP

**Comment by gOOvER** [comment]
It's like CLONE a server. But i don't understand, why u need this?

**Comment by parkervcp** [comment]
Also a duplicate of #2148
