### ISSUE TITLE
Trying to Open FIleManager , or Edit SFTP password outputs File Error  

### ISSUE THREAD

**Issue by IlPicasso** [Pterodactyl/Panel#303]
My issue is basically that I can't access to the filemanager, either edit SFTP details  inthis single server on my node2  , (other servers in the same node dont have this problem)

This is the error.log

http://f.cgm.rs/2017-02-17_18-04-19.txt

More info:

Docker

http://f.cgm.rs/2017-02-17_18-09-03.txt

PHP 5.6.30-1+deb.sury.org~xenial+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

UNAME 
Linux ns511015.ip-167-114-103.net 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

http://f.cgm.rs/2017-02-17_18-04-19.txt

**Comment by DaneEveritt** [comment]
Can you run `sudo npm run-script diagnostics` in your daemon directory and provide the output?

**Comment by IlPicasso** [comment]
I found out that it was a character issue

directory, stat '/srv/daemon-data/eggwar_d3483cb0/data/Champi�on'"
}
That is supposed to be an ñ
Which would make the word Champiñon


Modified the map name and now the filemanager works


@DaneEveritt
