### ISSUE TITLE
Server folders to make sorting the panel easier 

### ISSUE THREAD

**Issue by freddierick** [pterodactyl/panel#3037]
**Is your feature request related to a problem? Please describe.**
If you have a lot of servers the panel looks messy and is difficult to put in order and use.

**Describe the solution you'd like**
A way of each user being able to create folders for servers so they can separate projects.

**Describe alternatives you've considered**
Being able to change the order the servers appear apposed to by date. (repositioning them)

**Additional context**
It would just make it much easier to order and sort through servers; as well as making the panel much easier for most users to use, who just host for themselves and a couple of friends and need to separate everything.

Thanks for your time

**Comment by DaneEveritt** [comment]
#498
