### ISSUE TITLE
Unable to remove pinned CPUs once set until server restarts.

### ISSUE THREAD

**Issue by Oberfail** [pterodactyl/panel#3039]
* Panel or Daemon: idk, i'd guess wings
* Version of Panel/Daemon: 1.2.2 & 1.2.3
* Server's OS: Debian 10
* Your Computer's OS & Browser: Winblows 10 & Firefox

1. Pin a Core to any server
2. Remove the CPU Pinning and press Update Build Config

A clear and concise description of what you expected to happen:
No Cores should be pinned anymore

**Comment by trenutoo** [comment]
I've pinned a core, saved, removed a pinned core, saved, and it was removed. Did I misunderstand your issue or?

**Comment by Oberfail** [comment]
Not really, i've tested it on 2 different machines. I'll make a Video so it might be clearer.

//edit:
there you go: https://youtu.be/N-rNZJJYAVQ
same thing on my non-canary panel which is on 1.2.2 & 1.2.3

**Comment by trenutoo** [comment]
> Not really, i've tested it on 2 different machines. I'll make a Video so it might be clearer.
> 
> //edit:
> there you go: https://youtu.be/N-rNZJJYAVQ
> same thing on my non-canary panel which is on 1.2.2 & 1.2.3

Can you explain your problem, as I don't see it?

You are pinning cores 0-7, after that, you are pinning core 0. If you want to disable pinning, then leave it empty and restart the server to rebuild.

**Comment by Oberfail** [comment]
If I pin Core 0 and remove the pinning, its still pinned to Core 0.
If I pin Core 0-2 and remove the pinning, its still pinned to 0-2.

Removing the pinning does nothing. There is no Value in it so the previous value isn't getting overwritten.

**Comment by DaneEveritt** [comment]
Nothing I can do about this right now, it is an issue with Docker, tracking here: https://github.com/moby/moby/issues/41946

For now the only solution is to just reboot the server when _removing_ the pinning. You can modify it all you want without trouble.

Edit: This also appears to affect setting memory limits to 0 while the server is running.
