### ISSUE TITLE
Bug (0.6): Assigning IP aliases works "some of the time"

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#304]
This isn't a very well tested issue, but I figured I'd report it.

I created a new node and added an new allocation to the node (23.111.xxx.xxx) and then added 5 ports (25565-25569). I assigned an **IP Alias** to all of these ports simply called **vgs1.** I left the page to create a user and when I returned, I found that only every other port got the alias (ie: 25565, 25567, and 25569 had the alias, and the others did not). I typed it back in for the other 2, changed pages, and returned and found that only 25566 had received the port. I added it for 25568, left and returned, and it was fine now.

**Comment by DaneEveritt** [comment]
You're just typing too fast. I'll fix this when we re-do the admin theme.
