### ISSUE TITLE
Dockerized wings unable to write into server folder inside mounted volume

### ISSUE THREAD

**Issue by Dr3nz4r** [pterodactyl/panel#3040]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installing this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: Panel 1.2.2 & Wings 1.2.3
* Server's OS: Unraid 6.9.0-rc2 (wings) & Ubuntu 20.04 (panel)
* Your Computer's OS & Browser: Windows 10 1903 & Chrome 87.0.4280.141 64Bit

**Describe the bug**
Wings is seemingly unable to use the volume mapping provided through docker correctly. It's able to create a folder for the server but it seems to be lacking the ability to write into that folder as if the volume mapping as not recursive or it sets the incorrect permissions on the folders
**Panel:** 
`php -v`: <pre>PHP 7.4.9 (cli) (built: Aug  7 2020 14:30:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
</pre>

**Daemon:** 
`uname -a`:  <pre>Linux Unraid 5.10.1-Unraid #1 SMP Thu Dec 17 11:41:39 PST 2020 x86_64 AMD Ryzen 5 2600 Six-Core Processor AuthenticAMD GNU/Linux</pre>
`docker info`: 
<pre>Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 9
 Server Version: 19.03.14
 Storage Driver: btrfs
  Build Version: Btrfs v4.20.1 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765aba0d05254012b0b9e595e995c09186427f
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.1-Unraid
 Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 31.36GiB
 Name: Unraid
 ID: 66KO:SZG7:YXJW:RZPH:DFW5:JQH3:I22G:EMB5:TGIZ:DHVP:LPK6:SY4N
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
</pre>

Error from the log:
<pre>
INFO: [Jan 27 18:57:49.997] beginning installation process for server server=a2a0108d-6594-4c9b-97e2-3dc5c32e7167
WARN: [Jan 27 18:57:50.015] unable to pull requested image from remote source, however the image exists locally err=Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:52127->[::1]:53: read: connection refused image=debian:buster-slim

INFO: [Jan 27 18:57:50.033] creating install container for server process install_script=/tmp/pterodactyl/a2a0108d-6594-4c9b-97e2-3dc5c32e7167/install.sh server=a2a0108d-6594-4c9b-97e2-3dc5c32e7167
ERROR: [Jan 27 18:57:50.145] failed to complete server re-install process error=Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /var/lib/pterodactyl/volumes/a2a0108d-6594-4c9b-97e2-3dc5c32e7167 server=a2a0108d-6594-4c9b-97e2-3dc5c32e7167

Stacktrace:
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /var/lib/pterodactyl/volumes/a2a0108d-6594-4c9b-97e2-3dc5c32e7167
</pre>

Filesystem inside the docker container before creating the server:

<pre>
/ # ls /var/lib/pterodactyl/volumes/ -alh
total 0      
drwxrwxrwx    1 root     root           6 Jan 27 19:10 .
drwxrwxrwx    1 root     users         21 Jan 26 16:56 ..
drwxrwxrwx    1 root     root          20 Jan 26 17:06 .sftp
</pre>

Filesystem inside the docker container after creating the server & failing to install:
<pre>
/ # ls /var/lib/pterodactyl/volumes/ -alh
total 0      
drwxrwxrwx    1 root     root          50 Jan 27 19:10 .
drwxrwxrwx    1 root     users         21 Jan 26 16:56 ..
drwxrwxrwx    1 root     root          20 Jan 26 17:06 .sftp
drwx------    1 988      988            6 Jan 27 19:10 62140187-d585-4e14-bf36-9f44c60d9341
</pre>

path mappings for docker container:

| Host Path | Container Path | Access |
| - | - | - |
| /var/run/docker.sock | /var/run/docker.sock | rw |
| /mnt/user/pterodactyl-data/testNode/var/lib/docker/containers | /var/lib/docker/containers | rw |
| /mnt/user/pterodactyl-data/testNode/etc/pterodactyl | /etc/pterodactyl | rw |
| /mnt/user/pterodactyl-data/testNode/var/lib/pterodactyl | /var/lib/pterodactyl | rw |
| /mnt/user/pterodactyl-data/testNode/var/log/pterodactyl | /var/log/pterodactyl | rw |
| /mnt/user/pterodactyl-data/testNode/tmp/pterodactyl | /tmp/pterodactyl | rw |
| /mnt/user/pterodactyl-data/testNode/etc/letsencrypt | /etc/letsencrypt/ | rw |
| /etc/ssl/certs | /etc/ssl/certs | ro |

**To Reproduce**
1. Using unraid, create a docker container from ghcr.io/pterodactyl/wings:latest (at the moment of writing that's v1.2.3)
2. configure the new node in the panel
3. configure your path mappings and use lets encrypt (my path mappings above)
4. Try install any server onto the dockerized node
5. See error in the wings docker container output/logs

**Expected behavior**
No path mapping issues and a working wings docker container

**Comment by parkervcp** [comment]
I am certain that this is due to unraid not matching the mappings properly.

edit - see @matthewpi response

**Comment by matthewpi** [comment]
You need to make sure the host path for volumes is the same as the container path and change the `data_directory` option in wings to be the same path.

So the mount should be `/mnt/user/pterodactyl-data/testNode/var/lib/pterodactyl:/mnt/user/pterodactyl-data/testNode/var/lib/pterodactyl` and the `data_directory` should be `/mnt/user/pterodactyl-data/testNode/var/lib/pterodactyl` as well.

**Comment by Dr3nz4r** [comment]
Will try that, thanks guys! confused why that would be an issue having the two paths mismatch. I mean it's able to create folders 😕

**Comment by matthewpi** [comment]
> Will try that, thanks guys! confused why that would be an issue having the two paths mismatch. I mean it's able to create folders 😕

Wings creates the folders from within the container but the mounts are done by Docker on the host system.

**Comment by Dr3nz4r** [comment]
> > Will try that, thanks guys! confused why that would be an issue having the two paths mismatch. I mean it's able to create folders 😕
> 
> Wings creates the folders from within the container but the mounts are done by Docker on the host system.

Right. And because the new server runs in docker on the host, it's not able to access that path properly then. Meaning the actual "issue" would be:

servers started by wings do not use the same volume mappings as the wings container has (possibly, because wings is not able to access the exact mappings?)

**Comment by matthewpi** [comment]
> servers started by wings do not use the same volume mappings as the wings container has (possibly, because wings is not able to access the exact mappings?)

Wings just uses the data directory specified in the config, it is not aware it's running in Docker other than some hacky magic I added for the system-user detection logic.

**Comment by Dr3nz4r** [comment]
>Wings just uses the data directory specified in the config, it is not aware it's running in Docker other than some hacky magic I added for the system-user detection logic.

maybe an idea to tell wings in runs in docker though the config file? could then configure the mappings there explicitly as well. that removes the need for the folder structure to be equal

**Comment by Dr3nz4r** [comment]
Edit: ignore this.. Forgot the /volumes in the config.yml

> You need to make sure the host path for volumes is the same as the container path and change the `data_directory` option in wings to be the same path.
> 
> So the mount should be `/mnt/user/pterodactyl-data/testNode/var/lib/pterodactyl:/mnt/user/pterodactyl-data/testNode/var/lib/pterodactyl` and the `data_directory` should be `/mnt/user/pterodactyl-data/testNode/var/lib/pterodactyl` as well.

Tried that, getting a different error now. Seems to forget that the actual server is in {data_directory}/volumes

<pre>
WARN: [Jan 27 19:54:41.062] failed to determine root fs directory size error=filesystem: server path [/] resolves to a location outside the server root: /mnt/user/pterodactyl-data/testNode/var/lib/pterodactyl/62140187-d585-4e14-bf36-9f44c60d9341 root=/mnt/user/pterodactyl-data/testNode/var/lib/pterodactyl/62140187-d585-4e14-bf36-9f44c60d9341


Stacktrace:
filesystem: server path [/] resolves to a location outside the server root: /mnt/user/pterodactyl-data/testNode/var/lib/pterodactyl/62140187-d585-4e14-bf36-9f44c60d9341
github.com/pterodactyl/wings/server/filesystem.(*Filesystem).HasSpaceAvailable
github.com/pterodactyl/wings/server/filesystem/disk_space.go:66
github.com/pterodactyl/wings/router/websocket.(*Handler).HandleInbound
github.com/pterodactyl/wings/router/websocket/websocket.go:324
github.com/pterodactyl/wings/router.getServerWebsocket.func2
github.com/pterodactyl/wings/router/router_server_ws.go:79
runtime.goexit
runtime/asm_amd64.s:1374
</pre>

**Comment by parkervcp** [comment]
> > Wings just uses the data directory specified in the config, it is not aware it's running in Docker other than some hacky magic I added for the system-user detection logic.
> 
> maybe an idea to tell wings in runs in docker though the config file? could then configure the mappings there explicitly as well. that removes the need for the folder structure to be equal

We have discussed this internally. in the mean time it all needs to match.

**Comment by Dr3nz4r** [comment]
It's working now. Thanks a lot 💯 

things that I had to change aditionally:

`/tmp/pterodactyl` cannot be changed. Some hard-coded references seem to prevent this (tmp folder not re-configureable)
