### ISSUE TITLE
Display Database size

### ISSUE THREAD

**Issue by Sibald** [pterodactyl/panel#3041]
**Is your feature request related to a problem? Please describe.**
It is just a feature that could be nice for the panel and not extremely heavy I think.

**Describe the solution you'd like**
Display the size of the mysql database on the database tab on the panel

**Additional context**
This would allow to check the database size without needing to login to the phpmyadmin interface or mysql cli.

**Comment by nikrozman21** [comment]
I'd like to see that become a feature too.

**Comment by DaneEveritt** [comment]
This would also require the Panel either track the size of databases and have additional overhead to keep that state tracked, or constantly be querying potentially N+1 DB instances to get database sizes. Its a neat feature, but more work than I am interested in putting into such functionality when other software is available that can give you this information in a more relevant context.
