### ISSUE TITLE
SIGINT via ^C isnt forwared to server process

### ISSUE THREAD

**Issue by DatMayo** [pterodactyl/panel#3042]
**Background (please complete the following information):**
* Panel or Daemon:  Deamon
* Version of Daemon: 1.2.0 - 1.2.3
* Server's OS: Debian
* Your Computer's OS & Browser: W10 & Chrome

**Describe the bug**
Server process won't be shutdown gracefully. This happens to all eggs whu use `^C` as stop command

**To Reproduce**
Create a server that uses a SIGINT to be terminated (i.E. TeamSpeak), start & stop the server. The server process will be killed after some time

**Expected behavior**
A clean shutdown

**Comment by DaneEveritt** [comment]
Looks like that code is missing, for now switch it to use `^SIGKILL` and it'll stop. There is no process code handling though, so everything will be a `SIGKILL`. `^C` just falls through to the normal `docker stop <id>` command, so if that doesn't correctly stop the instance it won't work.

**Comment by DaneEveritt** [comment]
Closing this as it is really more of an issue with the games themselves, please feel free to open a PR if there is a more appropriate signal that you can find for the instances that gets them to stop correctly.

**Comment by sergejostir** [comment]
> 
> 
> Closing this as it is really more of an issue with the games themselves, please feel free to open a PR if there is a more appropriate signal that you can find for the instances that gets them to stop correctly.

It's not. It's an issue with container's entrypoint: https://github.com/parkervcp/images/issues/73

**Comment by schrej** [comment]
cc @parkervcp
