### ISSUE TITLE
ThrottleRequestsException - Too Many Attempts.

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3043]
Hey how to increate attempts for pterodactyl panel?

```
{
   "errors": [
       {
           "code": "ThrottleRequestsException",
           "status": "429",
           "detail": "Too Many Attempts."
       }
   ]
}
```

**Comment by trenutoo** [comment]
There are different throttle limits, what are you doing to trigger the throttle limit?

If you are receiving this on your panel/API, then you can adjust the API rate limits by adding and adjusting these parameters in your .env file:

APP_API_CLIENT_RATELIMIT=720
APP_API_APPLICATION_RATELIMIT=240
