### ISSUE TITLE
Compose file from master does not include Laravel logs

### ISSUE THREAD

**Issue by niekcandaele** [pterodactyl/panel#3045]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: canary/latest
* Server's OS: Debian host, but running panel in containers
* Your Computer's OS & Browser: 

**Describe the bug**

Installing the Pterodactyl ecosystem I ran into a lot of configuration issues, all caused by myself. However, it is hard to debug because logs for the panel seem to be very minimal. It seems like a lot of errors are not making it to the log directories created by the compose file.

```
php -v
PHP 7.4.14 (cli) (built: Jan 16 2021 00:21:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

I've been working on my deployment for a while now, but atm I'm stuck with a connectivity issue. I tried to consult the panel logs for more info, but my error is nowhere to be found 

```
find /srv/pterodactyl/logs/ -type f -exec wc -l {} \;
0 /srv/pterodactyl/logs/supervisord/queue-worker-stderr---supervisor-gg86b5j2.log
37683 /srv/pterodactyl/logs/supervisord/php-fpm-stderr---supervisor-0q9ue1n9.log
0 /srv/pterodactyl/logs/supervisord/nginx-stdout---supervisor-ijelhlnb.log
0 /srv/pterodactyl/logs/supervisord/php-fpm-stdout---supervisor-z7bcl7vp.log
4 /srv/pterodactyl/logs/supervisord/queue-worker-stdout---supervisor-9_qzt5y0.log
4 /srv/pterodactyl/logs/supervisord/supervisord.log
0 /srv/pterodactyl/logs/supervisord/nginx-stderr---supervisor-2pexxbv_.log
0 /srv/pterodactyl/logs/nginx/access.log
0 /srv/pterodactyl/logs/nginx/error.log
1 /srv/pterodactyl/logs/nginx/pterodactyl.app-error.log
4 /srv/pterodactyl/logs/crond
```

As you can see, the panel has been in use for a while (`php-fpm-stderr---supervisor-0q9ue1n9.lo` contains http access logs, hence why there's 37k lines in there). However, all the other log files have practically no contents.

**To Reproduce**
1. Install compose file from the repo
2. Do some stuff that should log errors

**Expected behavior**
Error messages to be created in the log files.

I tried to resolve this myself by using volumes like this:
```
      - "/srv/pterodactyl/logs/var:/var/log/"
      - "/srv/pterodactyl/logs/laravel:/app/storage/logs"
```

But `/srv/pterodactyl/logs/laravel` just contains a symbolic link, probably to try and get the Laravel logs into `/var/log` but that doesn't seem to work too well with Docker.

**Comment by DaneEveritt** [comment]
@niekcandaele can you see if that change fixes it?

**Comment by schrej** [comment]
Can't we reconfigure laravel to log into /var/log? Otherwise we'd need 2 mounts to be able to access all relevant ones.

**Comment by DaneEveritt** [comment]
Probably yeah, or just setup a symlink at that location  -- which I actually think there is an artisan command to do.

**Comment by niekcandaele** [comment]
Thanks for the fix!

Changed the mounts as you did in the commit, did some bad things to a node config and I now see error logs show up in /srv/pterodactyl/logs :smile: 

This issue can be closed for me, but I'll leave it up to you guys if you maybe want to redirect the laravel logs still.

Thanks again :)

**Comment by DaneEveritt** [comment]
I'll close this for now and we can always tackle it changing later.
