### ISSUE TITLE
[Daemon] CLOSE_WAIT

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3046]
Hey

On ubuntu 18.04 my daemon "crashes"(needs restart to become functional again) few times per day. I've finally narrowed this issue to "CLOSE_WAIT" ~200 connections. It rises to 200 from 0 in ~5 minutes every time...

Unfortunately i don't have "reproduce" list. This happens on wings process only.

Is there any keepalive config for wings ?

Any help is much appreciated.

**Comment by mason-rogers** [comment]
issue template who
