### ISSUE TITLE
daemon CLOSE_WAIT crash

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3047]
* Panel or Daemon: 
**Daemon**
* Version of Panel/Daemon: 
**1.1.1**
* Server's OS: 
**Ubuntu 18**
* Your Computer's OS & Browser: 
**It happens from all sorts of OS & browsers**

**Describe the bug**

Every day my daemon "crashes"(needs restart to become functional again) few times per day. I've finally narrowed this issue to "CLOSE_WAIT" connections. Once they start appearing then daemon is unresponsive and It needs restarting. 

When CLOSE_WAIT starts happening I've tried following command
```
ss --tcp state CLOSE-WAIT --kill
```
Even tho it killed all CLOSE_WAIT new ones appear again and again... So only restart helps in this scenario.
P.S. Files limit isn't a problem it's much higher than open files.
P.S. all connections to daemon goes through cloudflare

**To Reproduce**
Unfortunately I don't know how to reproduce. I just wait and this happens.

**Expected behavior**
No CLOSE_WAIT connections

**Comment by notAreYouScared** [comment]
If you would like some help you should be using the latest version of the panel and wings.

**Comment by DaneEveritt** [comment]
There is not enough information here for me to spend time trying to dig into this issue. You've not explained at all what specifically you're running to determine this is the source of your issue, nor would I even know where to begin looking. Additionally, unless you're running the latest version of Wings I'm not wasting time looking at an issue that might not even exist anymore.

**Comment by BenasPaulikas** [comment]
I've updated everything to latest version both wings and panel 1.2.2 and tried to figure this out again for many days. Tried to reproduce this in many possible ways...

However no luck and I'm still having same issue. Plus more info:
I have ~150 servers online.
~2000 servers offline.

~ 159 connections(mostly ws) to :8080
~ 104 connections to :2022

Wings using ~1148MB ram

**Comment by BenasPaulikas** [comment]
> CLOSE_WAIT - Indicates that the server has received the first FIN signal from the client and the connection is in the process of being closed. This means the socket is waiting for the application to execute close(). A socket can be in CLOSE_WAIT state indefinitely until the application closes it. Faulty scenarios would be like a file descriptor leak: server not executing close() on sockets leading to pile up of CLOSE_WAIT sockets.

So this is super strange. Because I tried to do stress testing and everything looks okay... close() is being called everywhere. But at some point it fails to call .close() on all api requests + websockets.

Is it possible that wings run out of memory or something ?

**Comment by BenasPaulikas** [comment]
And some more debug info. Wings is using < 4000 file descriptors during crash. And limit is 648574

> root@Ubuntu-1804-bionic-64-minimal ~ # pidof wings
> 19025
> root@Ubuntu-1804-bionic-64-minimal ~ # ls /proc/19025/fd | wc -l
> 3077

> root@Ubuntu-1804-bionic-64-minimal /proc/19025 # ulimit -aH
> core file size          (blocks, -c) unlimited
> data seg size           (kbytes, -d) unlimited
> scheduling priority             (-e) 0
> file size               (blocks, -f) unlimited
> pending signals                 (-i) 515207
> max locked memory       (kbytes, -l) 16384
> max memory size         (kbytes, -m) unlimited
> open files                      (-n) 648574
> pipe size            (512 bytes, -p) 8
> POSIX message queues     (bytes, -q) 819200
> real-time priority              (-r) 0
> stack size              (kbytes, -s) unlimited
> cpu time               (seconds, -t) unlimited
> max user processes              (-u) 515207
> virtual memory          (kbytes, -v) unlimited
> file locks                      (-x) unlimited

**Comment by BenasPaulikas** [comment]
Closing this issue. Probably it was fixed by tuning kernel params.
