### ISSUE TITLE
[Feature Request] Adding Users Selector

### ISSUE THREAD

**Issue by Pankraz01** [pterodactyl/panel#3049]
**Is your feature request related to a problem? Please describe.**
Its frustrating to think what email my subuser has.

**Describe the solution you'd like**
A Selector similar to the one in the server creation section

**Additional context**
![grafik](https://user-images.githubusercontent.com/19345513/106200506-61a45080-61b7-11eb-8720-3da549960083.png)

**Comment by mason-rogers** [comment]
this can easily be abused to just form a catalog of most users registered on the panel, finding out someones email so you can add them as a subuser isn't hard

**Comment by matthewpi** [comment]
This is a security risk as this would expose all the user's registered on the panel.  This will not be implemented.

**Comment by Pankraz01** [comment]
and if this is only available with admin access? Admins still have access to all user emails?

**Comment by DaneEveritt** [comment]
Doesn't matter, not building that feature, sorry.
