### ISSUE TITLE
Error response from daemon: OCI runtime create failed: IPv6 Crash

### ISSUE THREAD

**Issue by Bixilon** [pterodactyl/panel#3053]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: Latest: `1.2.3`
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Not important (But a custom linux distro based on somewhat like ubuntu)

**Describe the bug**
I am running pterodactyl in a lxd box (Before somebody write: LXD, unsupported, ...: Pterodactyl and docker works fine in it) It is security privileged and probably not the main issue here. It is the same container as before. I made some network changes on the host system to support IPv6. Since that, I can not start any server or docker container. See the logs below. It is probably related to #1778, but not sure about it. IPv6 is fully enabled and is working. It also happens when I remove all IPv6 addresses in the container, so the issue is somewhere else.  But yes, I can not ping any IPv6 host in a docker container (tested with `docker run -it ubuntu bash`). I must admit, I have no clue of docker.

**To Reproduce**
1. Launch a lxd container, with a ipv6 network address
2. Install wings (according to the documentation)
3. Setup wings, setup port forwarding, etc
4. Run wings with `wings --debug`
5. Start any server
6. See the crash :)

**Expected behavior**
Starting normally

```
DEBUG: [Jan 29 13:04:46.027] making request to external HTTP endpoint endpoint=https://xxx/api/remote/servers/94a07e44-7fe6-4e22-b329-399e4ac82412 headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[Bearer xxxx(redacted)] Content-Type:[application/json] User-Agent:[Pterodactyl Wings/v1.2.3 (id:xxx)]] method=GET
DEBUG: [Jan 29 13:04:46.212] syncing stop configuration with configured docker environment server=94a07e44-7fe6-4e22-b329-399e4ac82412
DEBUG: [Jan 29 13:04:46.213] syncing server settings with environment server=94a07e44-7fe6-4e22-b329-399e4ac82412
 INFO: [Jan 29 13:04:46.213] performing server limit modification on-the-fly server=94a07e44-7fe6-4e22-b329-399e4ac82412
DEBUG: [Jan 29 13:04:46.221] parsing server configuration file parser=properties path=/srv/minecraft/daemon-data/94a07e44-7fe6-4e22-b329-399e4ac82412/server.properties
DEBUG: [Jan 29 13:04:46.243] saw server status change event server=94a07e44-7fe6-4e22-b329-399e4ac82412 status=starting
DEBUG: [Jan 29 13:04:47.471] pulling docker image... this could take a bit of time image=quay.io/pterodactyl/core:java
{"status":"Pulling from pterodactyl/core","id":"java"}
{"status":"Digest: sha256:cf8006eea562c6f3c42167b175e994412f20cad85bfa1e05184edef427829042"}
{"status":"Status: Image is up to date for quay.io/pterodactyl/core:java"}
DEBUG: [Jan 29 13:04:47.475] completed docker image pull image=quay.io/pterodactyl/core:java
ERROR: [Jan 29 13:04:48.589] error processing websocket event "set state" error=Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: time="2021-01-29T13:04:48Z" level=fatal msg="failed to add interface vethb732cee to sandbox: error setting interface \"vethb732cee\" IPv6 to fdba:17c8:6c94::1/64: failed to enable ipv6: reexec to set IPv6 failed: exit status 4": unknown error_identifier=73282b98-0d4d-4185-81aa-fec8b0ca6091 event=set state server=94a07e44-7fe6-4e22-b329-399e4ac82412

Stacktrace:
Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: time="2021-01-29T13:04:48Z" level=fatal msg="failed to add interface vethb732cee to sandbox: error setting interface \"vethb732cee\" IPv6 to fdba:17c8:6c94::1/64: failed to enable ipv6: reexec to set IPv6 failed: exit status 4": unknown

DEBUG: [Jan 29 13:04:48.590] saw server status change event server=94a07e44-7fe6-4e22-b329-399e4ac82412 status=offline
 INFO: [Jan 29 13:04:48.594] detected server as entering a crashed state; running crash handler server=94a07e44-7fe6-4e22-b329-399e4ac82412
 INFO: [Jan 29 13:04:48.596] syncing server configuration with panel server=94a07e44-7fe6-4e22-b329-399e4ac82412
```

Sadly, I can not try disabling ipv6 completely in wings (I have no clue about go or docker).

**Comment by DaneEveritt** [comment]
Based on your statement of "I made some network changes on the host system to support IPv6" I'm going to guess you broke something else, especially since this is already running in an unsupported environment, even if it "works."

Unless someone can reliably point to this event happening and show it happening outside of an OpenVZ system I will not be pursuing any fixes.

**Comment by Bixilon** [comment]
Yah, the thing is: Before this change (just enabling IPv6), everything worked fine. The container is privileged and nesting is enabled, so that shouldn't be a problem.

**Comment by Bixilon** [comment]
Just to say it: It is working now. This issue has NOTHING to do with LXD. It is dockers/wings fault, but I see, I can't talk with you, you're fixated on the no to LXD.

Create `/etc/docker/daemon.json` with:
```
{
  "userland-proxy": false,
  "ipv6": true,
  "fixed-cidr-v6": "fd00::/80"
}
```
and change the IPv6 Address of the pterodactyl interface to something different like:
```
      v6:
        subnet: fdba:1888:8888::1/64
        gateway: fdba:1888:8888::1
```

Delete the old network with `docker network rm <network>`. Restart wings and see it is working.


I don't know, why it fails, but the error is definitely on your side, not on mine, nor on LXD's.
