### ISSUE TITLE
Unable to extract large zip file

### ISSUE THREAD

**Issue by NoozAbooz** [pterodactyl/panel#3054]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.2.2
* Server's OS: Ubuntu 18.04 LTS
* Your Computer's OS & Browser: Windows 10 on MS Edge

**Describe the bug**
When I upload a big zip file containing backup files or something and try to unzip it via the unarchive button, I get a error:
![image](https://user-images.githubusercontent.com/44128563/106300811-25eba400-6214-11eb-880a-578ac5db5d07.png)
If I unarchive a smaller zip file, then it successfully unarchives.

**To Reproduce**
1. Upload a big 10gb zip file
2. Click unarchive
3. See the error

**Expected behavior**
I expect the unarchive command to successfully complete and unzip the zip file.

**Comment by DaneEveritt** [comment]
Please include your logs from Wings, the information provided is not useful.

**Comment by NoozAbooz** [comment]
Ah, I use a hosting provider, they gave me the OS info but don't want to give me the wing logs since they contain sensitive info or something.

**Comment by tinyoverflow** [comment]
Then please contact your hosting provider about this issue.

**Comment by NoozAbooz** [comment]
Well I did, but they told me to unzip the files on my pc and upload them, but I'm not sure my wifi can handle that much bandwidth. Sorry that I can't get the logs, but it shouldn't be too hard to replicate considering you just need to upload a 10gb zip

**Comment by DaneEveritt** [comment]
I cannot help you if you cannot provide the logs from wings. If you are not the one running this instance you need to have the person doing so open an issue.

If your housing providers solution to your problem was telling you to open an issue here, you should drop them and move elsewhere.

Simply "upload a 10 GB zip" is not adequate there are far more factors at play than just the file size.

**Comment by g1i7ch** [comment]
I know this issue has been closed for some time, but I'm experiencing the exact same issue, and I'm not using a hosting service.
I've adjusted the php.ini and nginx.conf, as well as set it on the wings node within panel.
I noticed others speaking of adding an entry of "max_size=300" to the core.json (I'm not sure if "/var/lib/snapd/sequence/core.json" is the proper file, but I tried that as well, to no avail.)
Here are the logs of me trying to install a file over 100M.
[_wings_wings_1_logs.txt](https://github.com/pterodactyl/panel/files/9585928/_wings_wings_1_logs.txt)
Under 100M:
[_wings_wings_1_logs (1).txt](https://github.com/pterodactyl/panel/files/9586204/_wings_wings_1_logs.1.txt)
