### ISSUE TITLE
failed to start / install servers

### ISSUE THREAD

**Issue by 1Euro7Cent** [pterodactyl/panel#3060]
I know. Go to discord. But in discord I do not get any response.

I cannot install / start a server. I can install the server without the egg thingy when I load a server in there the server doesn't start
when I try to start a server
log: https://ptero.co/gumanocawe
console from a not starting server: (the server worked on my local machine and on the server before pterodactyl) https://cdn.discordapp.com/attachments/764995848101691402/805534384190259301/unknown.png

**Comment by DarthShmev** [comment]
Use the issue template

**Comment by FoksVHox** [comment]
Use the Discussions tab, instead of the issues, if you dont get any response on Discord.

**Comment by parkervcp** [comment]
This is an issue with your vm/vps most likely.
