### ISSUE TITLE
Adding a sub-user will not send an email with login info

### ISSUE THREAD

**Issue by Pomdre** [pterodactyl/panel#3064]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.2.2
* Server's OS: Ubuntu
* Your Computer's OS & Browser: Windows 10 Google Crhome

Adding a sub-user will not send an email so that the user can log in.
I was trying to add a sub user to a server the sub user does not receive any email with login info.
Otherwise, the email system works fine I tried the test button via the admin panel and it sends an email as usual

**Comment by DaneEveritt** [comment]
Please confirm your queue worker is running.
