### ISSUE TITLE
Deleting 500 Files Bug

### ISSUE THREAD

**Issue by xKurt** [pterodactyl/panel#3065]
Hello,

So I need help. First of all the page is showing that it can only show 500 files, therefore I selected them all because I need to delete those 500 files. But, all of the files just got deleted. I mean I thought it would just delete the 500 files but it deleted all of it, all of the files inside that directory. Second, I didn't know. There are no warnings or saying that it will all be deleted, it wasn't very clear. Basically, there were only 500 files listed and it deleted more than 500 files.
Those files are very very very important to me such as my server lobby world, survival world, etc.

Pterodactyl needs to fix this asap or else it will happen to different users as well. Now, I've lost those files because of this bug.

Kind Regards,
Kurt

**Comment by DaneEveritt** [comment]
Please fill out the template when reporting bugs.
