### ISSUE TITLE
[Wings] 2021/02/03 19:52:20 http: TLS handshake error from IP:port: local error: tls: bad record MAC

### ISSUE THREAD

**Issue by LeRouteur** [pterodactyl/panel#3068]
**Background (please complete the following information):**
* Panel or Daemon: Pterodactyl?
* Version of Panel/Daemon: latest (1.2.1)
* Server's OS: Ubuntu 20.04.1
* Your Computer's OS & Browser: Windows 10 & Chrome (latest)

**Describe the bug**
Getting error: `http: TLS handshake error from IP:port: local error: tls: bad record MAC` while running Wings after VPS update.
Debug log (obtained from wings diagnostics): https://ptero.co/ejimozulad

**To Reproduce**
Just update a Ubuntu 20.04 VPS to it's latest package and you'll get the error in the title...

**Expected behavior**
Just be able to run the Wings instances?

**Comment by DaneEveritt** [comment]
Duplicate of https://github.com/pterodactyl/panel/issues/2523, https://github.com/pterodactyl/panel/issues/2526

**Comment by LeRouteur** [comment]
It's not a duplicate since the two others don't even have answers.

**Comment by LeRouteur** [comment]
And btw I already tried to do what they say...

**Comment by DaneEveritt** [comment]
It is exactly the same issue, the closing reason is here: https://github.com/pterodactyl/panel/issues/2523#issuecomment-709561214

**Comment by LIADPRODUCTIONS** [comment]
Use the following commands and it should sort your issue!
`sudo ifconfig eth0 mtu 1350`
`sudo ip link set dev eth0 mtu 1350`
