### ISSUE TITLE
[API] Utilization per server

### ISSUE THREAD

**Issue by FlorianMifsud** [pterodactyl/panel#3069]
**Is your feature request related to a problem? Please describe.**
Have an API to recover RAM / CPU via the administration, to list the most greedy servers exemple:

`curl "https://pterodactyl.file.properties/api/application/servers/5/utilization" \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer apikey' \
  -X GET`
And for all servers ?
`curl "https://pterodactyl.file.properties/api/application/servers/utilization" \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer apikey' \
  -X GET`

return: https://dashflo.net/docs/api/pterodactyl/v0.7/#get-server-resource-utilization

**Comment by dennisrijsdijk** [comment]
just use https://dashflo.net/docs/api/pterodactyl/v1/#req_a8875d2840c64cbdb40e9bdb6cba4f75 in your code with a foreach loop.

**Comment by DaneEveritt** [comment]
You'd also be far better off using a different tool for monitoring servers for excessive use. Querying a static API for a single value is not going to be useful compared to a tool that can detect trends and relative usage.
