### ISSUE TITLE
Lack of next/previous page / scrolling

### ISSUE THREAD

**Issue by mesl** [pterodactyl/panel#3073]
**Background (please complete the following information):**
* Panel or Daemon: **Panel**
* Version of Panel/Daemon: **panel 1.2.2, wings 1.2.3** 
* Server's OS: **Ubuntu 20.04**
* Your Computer's OS & Browser: **Windows 10 - Google Chrome**

**Describe the bug**
Having more than 30 servers, I cannot access the other servers unless I use the search function, there used to be a next / previous page 

**To Reproduce**
Open a panel with 31 servers, server 31 and onwards are inaccessible unless you use the search function

**Expected behavior**
Either longer scroll list or a next/previous page

**Comment by Slitzo3** [comment]
This exists
![](https://nextcloud.albinhakanson.se/s/cbe2btX3q3j7dbz/preview)

**Comment by mesl** [comment]
I do not see that?

**Comment by DaneEveritt** [comment]
"Latest" is not a version, please include the specific version numbers.

**Comment by mesl** [comment]
panel 1.2.2 and daemon 1.2.3

**Comment by OpenSource03** [comment]
I can confirm that pagination works perfectly fine on the latest version.
