### ISSUE TITLE
Clicking navigation options for the same page the user is on does not refresh the page

### ISSUE THREAD

**Issue by mechite** [pterodactyl/panel#3075]
**Background (please complete the following information):**
* Panel or Daemon: Panel 1.2.3, Wings 1.2.2
* Server's OS: Ubuntu
* Your Computer's OS & Browser: Chrome

**Describe the bug**
When clicking titles or navigation to the same page, it doesn't reload.

**Expected behaviour**
It should allow me to reload the page when clicking.
https://gyazo.com/0099146dc4e960598b5c88c0ab9aafbc

**Comment by mechite** [comment]
Sorry for the updated comment to this issue, I accidentally submitted without editing the template for an issue. [For anyone who saw my issue super early]

**Comment by trenutoo** [comment]
What would be the point of refreshing the page on which you currently are, when it's not static content that requires any manual action to update

**Comment by mechite** [comment]
I do it to refresh my servers list and such, along with also being able to
get a clean console and other useful things.

**Comment by notAreYouScared** [comment]
I've experienced this issue but only if I leave the tab open for an extended amount of like. Like over 30ish minutes without interacting with it.

**Comment by mechite** [comment]
> I've experienced this issue but only if I leave the tab open for an extended amount of like. Like over 30ish minutes without interacting with it. 

I experience it everywhere, reloading the current tab means accessing a seperate one then heading back. Also to note how this functionality is basic UX, and especially to DISCARD a file in the text editor. Clicking the files button should be the go-to way to go straight to /home/container AND discard the file.

It's a very useful piece of functionality that makes sense to keep.

**Comment by DaneEveritt** [comment]
Closing this out as I'm not going to change the behavior. This is how the router logic works for the SPA and I'm very concerned that changing it will lead to a significant degradation in performance and cause unexpected refreshing/re-rendering all over the app.

It doesn't "refresh" because there are no changes being made to the state.
