### ISSUE TITLE
Add a mount to a node and game server via the API.

### ISSUE THREAD

**Issue by scolastico** [pterodactyl/panel#3077]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like to have a feature to add a mount to a node and a game server via the API. If this feature already exists please add it to the docs https://dashflo.net/docs/api/pterodactyl/v1/

**Describe alternatives you've considered**
I have no alternatives

**Additional context**
I have no other context

**Comment by DaneEveritt** [comment]
This will occur whenever we eventually finish the admin area rewrite.

**Comment by cloudmaker97** [comment]
I need this as well.
