### ISSUE TITLE
V7.19 : Daemon Version 0.6.13

### ISSUE THREAD

**Issue by LewaIngame** [pterodactyl/panel#3082]
Hello, i actually got a problem, when i restart wings all my SOURCES server are making lua refresh, did anyone knew why ?

**Comment by LeCodeCo** [comment]
1. You did not read the issue template.
2. Use the Discord for help. https://discord.gg/pterodactyl

**Comment by parkervcp** [comment]
the 0.7 panel and 0.6 daemon are now deprecated, You should be working on upgrading to 1.0
