### ISSUE TITLE
Egg Importing

### ISSUE THREAD

**Issue by JackW6809** [pterodactyl/panel#3083]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v1.2.2
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10, Chrome.

**Describe the bug**
When importing a new Egg you will get Error 500 when importing. This is because if you use an Egg you exported recently this now exists in the Egg file. ```"file_denylist": "",``` The feature is not yet implemented so people who listen to the egg file will not edit it and be stuck with the Error 500 issue. ```"DO NOT EDIT: FILE GENERATED AUTOMATICALLY BY PTERODACTYL PANEL - PTERODACTYL.IO"```
Please provide additional information too, depending on what you have issues with:
Panel: `PHP v7.4.14`

**To Reproduce**
1. Go to Nests
2. Click on Any Nest
3. Click on Any Egg
4. Scroll down to Export
5. Then go back to 'Nests
6. Then Import
7. Error 500

**Expected behavior**
Import the Egg without any issues.

**Comment by parkervcp** [comment]
This is known and fixed in here https://github.com/pterodactyl/panel/commit/b00def253746d1c96ba2c4bdc232d436fd7b7fee - #3034
