### ISSUE TITLE
[Firefox] Server Console Overlapping command-box

### ISSUE THREAD

**Issue by TekExplorer** [pterodactyl/panel#3084]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.2.2
* Server's OS: Whatever [ccarney16/pterodactyl-containers](https://github.com/ccarney16/pterodactyl-containers/) uses.
* Host Server OS: Ubuntu 18.04
* Your Computer's OS & Browser: Kubuntu 20.04 Firefox. _Does not appear to happen in chrome!_

**Describe the bug**
From what I can see, the console container seems to go past the point it should be at, overlapping the command box and making it impossible to send commands. Best to view the below video
Also seems to work at some zoom levels?

https://user-images.githubusercontent.com/30291302/107457885-e761bd80-6b20-11eb-951e-192375f97428.mp4

**To Reproduce**
1. Open any server console in a Firefox window.

**Expected behavior**
The console to stay in its room and not over-extend
Actually be able to send commands

**Comment by ghost** [comment]
Related to font sizes #2799

**Comment by DaneEveritt** [comment]
Please provide written steps, not a video.

**Comment by TekExplorer** [comment]
> Please provide written steps, not a video.

seems to happen on any server console in a firefox window. tested in a private window to remove extention-related madness

edit: tested across 4 different panels. some with the server running, some not, some where I'm admin, some where I'm not.
