### ISSUE TITLE
Docker does not delete old iptables rules sometimes

### ISSUE THREAD

**Issue by VibeGAMESNL** [pterodactyl/panel#3088]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.2.3
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Chrome, Windows 10

**Describe the bug**
For some reason pterodactyl/docker is sometimes (rarely) not removing old iptables rules. Ofcourse that is causing issues. It happends with both TCP and UDP rules.

Output of: `iptables -t nat -L DOCKER -n`. See port 31326
![](https://i.imgur.com/4Sm5CPE.png)

**To Reproduce**
Unknown, my gues is that when you remove an allocation or a server is deleted, it does not always remove all iptables rules.

**Expected behavior**
If you re-assign a allocation to another server or delete a server, the old rules should be removed.

**Comment by matthewpi** [comment]
Docker should automatically handle this.  If it doesn't, then it is most likely a Docker bug.
