### ISSUE TITLE
Bug (0.6): Adding subusers fails

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#309]
Pretty self-explanatory. I'm trying to add a sub-user for a specific Minecraft server. I select every single permission available and use an email address of a user that already exists as a user (this also fails when I select a user that doesn't exist) and receive the following error: `An unknown error occured while attempting to add a new subuser.`

**Comment by DaneEveritt** [comment]
Already resolved by https://github.com/Pterodactyl/Panel/commit/3240601d036817fcc83729a7f48eea2b28fc1a67
