### ISSUE TITLE
[Panel] Node Configuration: SSL Enabled not set to true in generated config when using behind proxy

### ISSUE THREAD

**Issue by MattW-source** [pterodactyl/panel#3091]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.2.2
* Server's OS: 18.04.5 LTS
* Your Computer's OS & Browser: Windows 10 - Edge

**Describe the bug**
When creating or configuring a node in the panel, setting "Communicate Over SSL" to "Use SSL Connection" with "Behind Proxy" enabled, SSL is set to false in the generated configuration.
```  
ssl:
    enabled: false
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to admin/nodes
2. Either create a new node or configure an existing one
3. Enable "Behind Proxy"
4. Enable SSL 
5. Observe that the config in the configuration tab has SSL set to false

**Expected behavior**
Generated configuration should have
```  
ssl:
    enabled: true
```

**Comment by mason-rogers** [comment]
This works for me, are you sure you actually saved it?

**Comment by MattW-source** [comment]
Just realised what it was which is making the difference. If you have behind proxy enabled, it will override SSL and sets it to false.

I assume this has something to do with
> If you are running the daemon behind a proxy such as Cloudflare, select this to have the daemon skip looking for certificates on boot.

However if I try to run wings with SSL off behind Cloudflare, the panel and wings will not communicate, regardless of whether SSL is enabled or not in the panel. So I still need to have SSL set to True in order for the web socket to work.

I will update my reproduction steps to reflect this.

**Comment by mason-rogers** [comment]
If you're running through the daemon through cloudflare, you have to use 8443 as the port as 8080 isn't on the HTTPS ports cloudflare allows, you can see those [here](https://support.cloudflare.com/hc/en-us/articles/200169156-Identifying-network-ports-compatible-with-Cloudflare-s-proxy)

**Comment by MattW-source** [comment]
I've already switched over to Port 8443. 

So if I disable SSL (in Wings) as the configuration seems to want me to do, and use port 8080 I start seeing a "504: Gateway time-out" when the Panel tries to communicate to Wings.

If I then tell the panel to use HTTP I start getting 404 errors when attempting to communicate to wings. 

Probably worth mentioning here that this system has nothing else running on it, it's a development VM which I made for trying to setup a Pterodactyl instance, so port 8080 shouldn't be trying to point to any other webserver other than wings. 

The only configuration I can seem to get working here is
**Panel**
Communicate Via SSL: True
Behind Proxy: True
Daemon Port: 8443

**Wings**
Port: 8443
SSL: True (manually changed in the config)

**Comment by mason-rogers** [comment]
I use the daemon through cloudflare, you need to have ssl set to false in the wings config, I have this and it works fine for me.

**Comment by MattW-source** [comment]
> I use the daemon through cloudflare, you need to have ssl set to false in the wings config, I have this and it works fine for me.

So I set it to false in the wings config, set the port to 8080 and left "Communicate via SSL" on and it just gave me a bunch of 504's. I wonder what's different between our environments

**Comment by mason-rogers** [comment]
As I said, the port needs to be 8443... Cloudflare handles the SSL for you hence why you do not need it set as true in the config.

**Comment by MattW-source** [comment]
Ok having now set the port to 8443, keeping Communicate via SSL enabled on the panel and having ssl set to false in the config, I now see `525: SSL handshake failed`

As mentioned, the only configuration that seems to work is using port 8443 with use_ssl:True in Wings. Anything else (including what the panel wants me to do) fails.

**Comment by DaneEveritt** [comment]
This is working as intended. Setting it to false keeps Wings from requiring a SSL certificate to run, allowing your proxy to properly terminate the SSL connection and do the final hop as a regular HTTP request. You can always make wings run on SSL as well behind a proxy, but for a lot of beginners they're just trying to make use of the Flex SSL offering or something similar where it doesn't expect the service to be running behind SSL.

**Comment by MattW-source** [comment]
Aha, that might be where my configuration differs then as I have encryption mode set to **full** instead of **flexible**. Anyway thank you for the assistance, much appreciated.

**Comment by DaneEveritt** [comment]
No problem, you should set it to `true` on your end in that case, we just use false because thats what a majority of the users who are trying to get this setup end up picking. I don't think asking them to select true/false would go very well unfortunately.
