### ISSUE TITLE
break AuthenticateServerAccess logic

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#3092]
https://github.com/pterodactyl/panel/commit/e30a765071723fd1dc5438c19c7be73f6d4aa2a4#diff-d4bd12e1f2644d13f8b5bd83f44c06f50ddc7441dc20aa91743908a65120633bL63

you have made an access check below the condition:

https://github.com/pterodactyl/panel/commit/e30a765071723fd1dc5438c19c7be73f6d4aa2a4#diff-d4bd12e1f2644d13f8b5bd83f44c06f50ddc7441dc20aa91743908a65120633bL68

suspend server:

![image](https://user-images.githubusercontent.com/28255085/107954868-1313f600-6fae-11eb-83cd-369de38787a7.png)

**Comment by DaneEveritt** [comment]
Please use the actual bug reporting template, two links and a screenshot really doesn't explain the issue, even though I can mostly infer what you're trying to report.

**Comment by zKoz210** [comment]
1. suspend server 
2. go server page file manager or other

**Comment by DaneEveritt** [comment]
Please copy the template and replace your initial report with it, thank you. It isn't just me that follows these reports, other people like to see them and try to fix things, but without a consistent template for reporting it puts all of the onus on myself to keep track of things and be able to figure out what is being reported.
