### ISSUE TITLE
Remove suspended gameservers from Node Memory Allocated

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3093]
**Remove suspended gameservers from Node Memory Allocated**

If a server is suspended, no more RAM should be reserved for the server in the node. 
So that the whmcs module can work properly.

**Comment by trenutoo** [comment]
The server still exists and can always be returned back to life hence resources being reserved. You can increase over-allocation or delete them

**Comment by DaneEveritt** [comment]
If you're not going to follow the template I'm not going to do anything about this.
