### ISSUE TITLE
Save suspended gameserver on external data like hdd and move him back when the Server is unsuspended

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3094]
**Save suspended gameserver on external data like hdd and move him back when the Server is unsuspended:**

When a game server is suspend mode, the server will go into copy mode.
In copy mode all data is copied from the game server to an external storage.
If the gameserver has been successfully moved to the external storage, the gameserver is deleted from the node and the reserved "Memory Allocated" and "Disk Space Allocated" is released again from the node. 

If the player wants to have the server again, he has to pay the bill, so the server is unsuspended and the data is copied back.

**Comment by trenutoo** [comment]
This is a very specific feature aimed at commercial services, third-party modification would be more appropriate

**Comment by Felix5566** [comment]
I am using the WHMCS Module, is it better i request the feature there?

**Comment by DaneEveritt** [comment]
Yeah I'm not building this, sorry. Mostly because I'm just not interested in building logic for such a use case, or the complexity the comes with it.

**Comment by RihanArfan** [comment]
You can accomplish this by calling the API to transfer the server to a different node.
