### ISSUE TITLE
Gmod Server can't start anymore

### ISSUE THREAD

**Issue by baptiste-fourmont** [pterodactyl/panel#3097]
**Background (please complete the following information):**
* Panel or Daemon: Daemon Last
* Version of Panel/Daemon: Last
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 last version 2604H | Firefox Nightly

[docker.txt](https://github.com/pterodactyl/panel/files/5988113/docker.txt)
[debug-2.log](https://github.com/pterodactyl/panel/files/5988101/debug-2.log)
Linux ns3083795 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Hi,
I own two gmodservers since yesterday I use the last version of pterodactyl and Ubuntu 18.04.4 LTS
And my gmodservers crashed with this error:

Segmentation fault (core dumped)
cat: hlds.36.pid: No such file or directory
email debug.log to linux@valvesoftware.com
Tue Feb 16 10:59:22 CET 2021: Server Quit

**Comment by DaneEveritt** [comment]
`Last` is not a version, also with the limited information provided this does not appear to be a bug with this software, please use Discord for further game-specific support.
