### ISSUE TITLE
Wings memory and cpu problem

### ISSUE THREAD

**Issue by Kaesewuerfel** [pterodactyl/panel#3098]
**Background (please complete the following information):**
* Panel or Daemon: Latest Wings
* Version of Panel/Daemon: Latest Panel
* Server's OS: Debian 10
* Your Computer's OS & Browser: /

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `4.19.0-12-amd64`

**Expected behavior**
After 1 day wings is using all memory and its also shown in htop and produce 100 % cpu utilization on all cores.

**Comment by mason-rogers** [comment]
You didnt follow the template properly, also state the versions you're running, it's more common than you'd expect that people say they are on latest and actually not.

Many production systems use pterodactyl and a cpu/memory leak would've been spotted way faster than this.

**Comment by DaneEveritt** [comment]
I'm not debugging an issue whose only information is just run wings for a day and see 100% utilization. Please provide additional details and screenshots showing what leads you to believe there is a leak specifically.
