### ISSUE TITLE
UI - Admin area search bar is unusably small in certain contexts on mobile

### ISSUE THREAD

**Issue by Sabinno** [pterodactyl/panel#3099]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.2.2 (:latest in docker)
* Server's OS: CentOS 8
* Your Computer's OS & Browser: Android 11; Microsoft Edge and Google Chrome

**Describe the bug**
On the Nodes, Servers, and Users pages in the Admin area when on a mobile device, the text area for the search bar is unusably small.

See this image for visual: https://ibb.co/bHnyQmZ

**To Reproduce**
1. Enter Admin area on a mobile device.
2. Look at search bar in the aforementioned pages.

**Expected behavior**
Search bar should take up significantly more space, especially since the entire remainder of the element's header bar is empty space. Presumably, this could be fixed by adjusting the width percentage of the search bar on a mobile-specific stylesheet.

**Comment by DaneEveritt** [comment]
Will be fixed by admin area rewrite, otherwise unconcerned with this right now. Thanks for the report though. :)
