### ISSUE TITLE
Container labels

### ISSUE THREAD

**Issue by DomiiBunn** [pterodactyl/panel#3100]
**Is your feature request related to a problem? Please describe.**
In some use cases it may be useful to set labels on containers, with the current implementation of pterodactyl it is impossible.

**Describe the solution you'd like**
Add a tab in the panel similar to env but allow it to be a key value pair for each server

**Describe alternatives you've considered**
Setting a label manually, this gets removed on a reboot due to the automatic rebuild

**Additional context**
Would be a rather useful feature for automatic deployments where you need to pass extra info about each individual server

**Comment by Thesam1798** [comment]
Up 👍

**Comment by krickler** [comment]
To add to this request, you could install Traefik on the nodes, and using labels configure reverse proxy routes, e.g. for Minecraft dynmap or the Killing Floor 2 admin panel.

**Comment by DomiiBunn** [comment]
That was the idea behind this issue
