### ISSUE TITLE
When trying to copy database password from panel (server, no admin required) it will copy "function valueOf() { [native code] }"

### ISSUE THREAD

**Issue by fizzrepo** [pterodactyl/panel#3104]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.2.2 
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Google chrome and windows 10 pro

**To Reproduce**
1. Go to databases on your server (I am using bungeecord)
2. Click on a database's eye icon
3. Click the password
4. Paste it

**Expected behavior**
Copy the database password.

**Comment by FoksVHox** [comment]
I'm unable to replicate this.

**Comment by fizzrepo** [comment]
> I'm unable to replicate this.

Should I create a video of this?

**Comment by FoksVHox** [comment]
> > I'm unable to replicate this.
> 
> Should I create a video of this?

I guess, but I don't think it would change the behavior.

**Comment by DaneEveritt** [comment]
This was already fixed in https://github.com/pterodactyl/panel/issues/2807, are you positive you have correctly updated your system.

**Comment by fizzrepo** [comment]
> This was already fixed in #2807, are you positive you have correctly updated your system.

I was running an outdated version.
