### ISSUE TITLE
Rust | Panel freezing

### ISSUE THREAD

**Issue by Lewman3** [pterodactyl/panel#3106]
**Background (please complete the following information):**
* Panel or Daemon: Panel (I assume)
* Version of Panel/Daemon: 1.22
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 & Chrome

**Describe the bug**

- Timescales vary from a hour to a few days, but after a period of time my Rust Servers stop outputting to the console, the Discord bots go offline and I can't connect to them via a third party RCON tool - A wings restart has no effect, nothing in the Rust logs.

Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use). 

- 7.4.14

Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

- https://pastebin.com/qz1bbGac

**To Reproduce**
1. Not sure

**Expected behavior**
Self explanatory.

**Comment by FoksVHox** [comment]
Without steps to reproduce that behavior there isnt much that Dane, or anyother member can do, other then try, but that could result in a different behavoir :)

**Comment by Lewman3** [comment]
> Without steps to reproduce that behavior there isnt much that Dane, or anyother member can do, other then try, but that could result in a different behavoir :)

I understand I can provide Panel access but the problem is that I have no idea how the issue occurs.

**Comment by FoksVHox** [comment]
> > Without steps to reproduce that behavior there isnt much that Dane, or anyother member can do, other then try, but that could result in a different behavoir :)
> 
> I understand I can provide Panel access but the problem is that I have no idea how the issue occurs.

Did you check the Wings logs?

**Comment by Lewman3** [comment]
> > > Without steps to reproduce that behavior there isnt much that Dane, or anyother member can do, other then try, but that could result in a different behavoir :)
> > 
> > 
> > I understand I can provide Panel access but the problem is that I have no idea how the issue occurs.
> 
> Did you check the Wings logs?

Yes, I've been having the issue for months only just decided to report it as not 100% it is a Panel or Wings issue - Nothing in any of the logs from what I can see.

**Comment by FoksVHox** [comment]
What version of Wings are you using?

**Comment by schrej** [comment]
Are those discord bots hosted as separate servers? What eggs are you using?

**Comment by DaneEveritt** [comment]
If a Wings restart has no effect and all of the servers are going offline at the same time I'd be more inclined to believe you're exhausting the resources available on your machine, or running into a bug with Docker. Unfortunately I just don't have the resources available to try to debug this on our issue tracker, so I'd encourage you to seek additional support in our Discussion area, or on Discord.

If you do manage to track down specific things that lead you to believe it is actually Wings causing the issues, and can provide more concrete reproductions steps you're welcome to re-open this issue with those details.

**Comment by ItsGamingTube** [comment]
ssd
