### ISSUE TITLE
Feature Request: Search bar on "Your Server"

### ISSUE THREAD

**Issue by IlPicasso** [Pterodactyl/Panel#311]
Hello it would be great to add a Search Bar here

http://f.cgm.rs/opera_2017-02-18_09-47-33.png

Would make life easier for a lot of us, also adding different filters to the search like NODE

**Comment by DaneEveritt** [comment]
Added in the new theme https://github.com/Pterodactyl/Panel/commit/b926d432e8011fd540e02f398037dda4420dea4a
