### ISSUE TITLE
Schedules not working

### ISSUE THREAD

**Issue by DrakMC** [pterodactyl/panel#3111]
Hello, schedules stopped working for me. It says: processing

`tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99` https://pastebin.com/raw/z6Z9tEMN
`sudo wings diagnostics` https://pastebin.com/raw/UV7S5MB6

**Comment by FoksVHox** [comment]
Follow the provided template, otherwise Dane and others who want to help, can't do....

**Comment by DrakMC** [comment]
**Background (please complete the following information):**
* Version of Panel: 1.2.2
* Version of Daemon: 1.2.3
* Server's OS: Ubuntu Server 20.04
* Your Computer's OS & Browser:  Windows 10 & Google Chrome

All servers have schedules: processing (https://i.imgur.com/aE12wVr.png)
Panel: PHP 7.4.3 
Daemon: Linux ns92110 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Docker info: https://pastebin.com/raw/4gybdwPF

**To Reproduce**
1. Go to any server
2. Click on Schedules
4. You can see error: processing

**Expected behavior**
Schedules should work and execute.

**Comment by FoksVHox** [comment]
You've entred "1.2.2" in "Panel/Wing" you should put what you think it is, which is most likely the panel.

**Comment by DrakMC** [comment]
I'm using:
* Version of Panel: 1.2.2
* Version of Daemon: 1.2.3

**Comment by DaneEveritt** [comment]
Your `pteroq` service is likely not running, please use Discord for asking questions like this in the future rather than immediately opening a bug report (and ignoring the obvious template that you're asked to fill out).
