### ISSUE TITLE
Uncaught exception rendering console view

### ISSUE THREAD

**Issue by hwalker928** [pterodactyl/panel#3121]
**Background (please complete the following information):**
* Panel or Daemon: Not 100% sure
* Version of Panel/Daemon: v1.2.2
* Server's OS: Ubuntu 20.04, but most likely all 
* Your Computer's OS & Browser: Windows 10 Firefox, doubt it's a OS issue as it also occurs on Mac's. 

**Describe the bug**
While switching between servers, or tabs (backups, schedules) and then back to console, you may occasionally get a "An error was encountered by the application while rendering this view. Try refreshing the page.". Refreshing seems to fix it 100% of the time, but it is extremely annoying. This is not host or device specific, as I have had this issue on multiple different panels, devices and even locations. The console error can be found attached as an image, as well as the rendering error. 

**To Reproduce**
1. Go to a server or to console from another tab. 
2. See error

**Expected behavior**
For the console to show without needing a refresh. 

![9f37h1j3aj.png](https://user-images.githubusercontent.com/63236817/108912950-3d565b00-7621-11eb-83bb-74ac21182122.png)

![unknown-4.png](https://user-images.githubusercontent.com/63236817/108912961-40e9e200-7621-11eb-92f4-99cc71de65ff.png)

**Comment by mason-rogers** [comment]
![image](https://user-images.githubusercontent.com/26467584/108914191-e782b280-7622-11eb-83a5-2051f9ef43e0.png)

at e.resize shows that it's related to the resizing portion of the react code
at eval when clicked shows the exact line causing the error in Console.tsx [here](https://github.com/pterodactyl/panel/blob/develop/resources/scripts/components/server/Console.tsx#L143)

**Comment by DaneEveritt** [comment]
Appears to be related to https://github.com/xtermjs/xterm.js/issues/3118

Do you notice it only happening when returning to the console screen?

**Comment by mason-rogers** [comment]
If it happens, it renders the entire page (all tabs in /server/:id) unusuable till refresh (whole ServerContainer)

**Comment by DaneEveritt** [comment]
Yeah, that error catcher wraps all of those pages, if I moved it down some levels it would theoretically only break the console itself.

**Comment by hwalker928** [comment]
I have only ever noticed it when visiting the console tab.

**Comment by mason-rogers** [comment]
That's the cause of it, but when it happens it will affect all pages due to the reason Dane mentioned

**Comment by notAreYouScared** [comment]
I've had this issue if I leave the console page opened for a while without interacting with it. A F5 is required to fix it.

**Comment by hwalker928** [comment]
![image](https://user-images.githubusercontent.com/63236817/109980882-49fd4200-7cf8-11eb-8006-949c4f94b3ab.png)
This now occurs. @DaneEveritt (Because the issue is closed, I wasn't sure if you would see this)
