### ISSUE TITLE
Internal Network Issues.

### ISSUE THREAD

**Issue by TheJavaHacker** [pterodactyl/panel#3123]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Both
* Version of Panel/Daemon: Panel Version 1.2.2, Daemon Version 1.2.3.
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: OS X 11.2.1, Safari 14.0.3

**Describe the bug**

We're using the default pterodactyl_nw sub-network to handle internal connections between our BungeeCord and Spigot instances on our network. When restarting our servers, their IPs on this internal network changes and causes our BungeeCord to no longer connect to our back-end Spigot servers. 

**How to reproduce**
There is no clear method to reproduce this bug, because we don't know what the hell just happened.
1. I would assume you configure the panel based upon the documentation laid out on the 'Getting Started' page.
2. Create 3 Servers, 1 being BungeeCord and 2 being Paper sub-servers.
3. BungeeCord should be on the public IP, whereas the Paper servers should be on the IPs listed in the pterodactyl_nw sub-network.
4. Restart all of the servers at the same time. -- This is where the issue seems to have occurred. 

**Expected behavior**
The default internal network is with range 172.18.0.X and the expected X variable was theorised to be the Internal Server ID (i.e the ID is '3', so the IP would be '172.18.0.3') however upon restart it the IP changed to end in 4, and then to end in 2.
*We expected those Internal IPs to remain consistent upon restarts.*

**Comment by parkervcp** [comment]
In your bungee config set it to use 172.18.0.1:port and not the ip address

**Comment by TheJavaHacker** [comment]
We've set the BungeeCord config.yml to listen to the internal network IPs for each of the containers. Setting them all to 172.18.0.1:port doesn't appear to work for each of the servers.

**Comment by trenutoo** [comment]
> We've set the BungeeCord config.yml to listen to the internal network IPs for each of the containers. Setting them all to 172.18.0.1:port doesn't appear to work for each of the servers.

Have you followed the [Minecraft tutorial](https://pterodactyl.io/community/games/minecraft.html)?

**Comment by TheJavaHacker** [comment]
We've set it up as according to the documentation laid out on the website. That's how we always set it up, in-case the recommendations for software operations change per version.

**Comment by TheJavaHacker** [comment]
Seemingly fixed by a completely fresh install.
