### ISSUE TITLE
Add documentation for creating panel themes / add official support for themes

### ISSUE THREAD

**Issue by elinarbur** [pterodactyl/panel#3126]
**Is your feature request related to a problem? Please describe.**
I always look at the default theme and think how much I'd like to change it but when it comes to actually making that change it's much more difficult than expected since any documentation regarding how to create a theme is missing.

**Describe the solution you'd like**
I suggest that official documentation about creating themes be added to the pterodactyl.io website, making the lives of those who wish to contribute much easier.

**Describe alternatives you've considered**
I have considered looking into the codebase myself and have explored it a fair bit but that doesn't mean a developer who's competent in frontend development will have the time to do the same.

**Additional context**
Before deciding the ultimate fate of this issue please consider that Pterodactyl is now one of the big widely used server control panels out there and, although open-source, is used heavily in a commercial environment by hundreds of businesses, both big and small. Despite the fact that the panel is not ultimately built and maintained for any specific use case, it cannot be ignored that those businesses & other users will want to change the look of their panel. 
And besides, official theming support can act as another source of income to help support the development of the project by offering paid themes.

**Comment by craxydev** [comment]
Would be very sick

**Comment by trenutoo** [comment]
Web developer competent in redesigning the theme should not have any issues with figuring out how all the react components work.

There's no real documentation that can be made, it would pretty much end up being a web development guide 101.

We at Pterodox (third-party site unrelated to Pterodactyl) do work on making theme templates and guides/snippets together with helping on our Discord.

**Comment by SuperS123** [comment]
> Web developer competent in redesigning the theme should not have any issues with figuring out how all the react components work.
> 
> There's no real documentation that can be made, it would pretty much end up being a web development guide 101.
> 
> We at Pterodox (third-party site unrelated to Pterodactyl) do work on making theme templates and guides/snippets together with helping on our Discord.

I really hope those themes on your page aren't stolen, and you own it/have permission to distribute it. I've seen those exact themes on a Github

**Comment by trenutoo** [comment]
> > Web developer competent in redesigning the theme should not have any issues with figuring out how all the react components work.
> > 
> > There's no real documentation that can be made, it would pretty much end up being a web development guide 101.
> > 
> > We at Pterodox (third-party site unrelated to Pterodactyl) do work on making theme templates and guides/snippets together with helping on our Discord.
> 
> I really hope those themes on your page aren't stolen, and you own it/have permission to distribute it. I've seen those exact themes on a Github

Do you mean the same github repository to which they link and who's creator is sharing them on Pterodox?

**Comment by elinarbur** [comment]
Perhaps I should rephrase, what I mean by adding documentation is a page that displays some relevant information about theming your installation:

* Where the themes folder is located
* A downloadable zip file that contains sample files to create your own theme
* What framework it is in, knowing that it's react before trying anything is helpful
* Adding your theme and changing it in the .env file

I've also realized that perhaps this should've been posted in the pterodactyl/documentation repository, let me know if I should repost it there instead of keeping this issue here.

**Comment by trenutoo** [comment]
> Perhaps I should rephrase, what I mean by adding documentation is a page that displays some relevant information about theming your installation:
> 
> * Where the themes folder is located
> * A downloadable zip file that contains sample files to create your own theme
> * What framework it is in, knowing that it's react before trying anything is helpful
> * Adding your theme and changing it in the .env file
> 
> I've also realized that perhaps this should've been posted in the pterodactyl/documentation repository, let me know if I should repost it there instead of keeping this issue here.

There's no "theme system" or any official plans to implement that as of now in 1.x Pterodactyl and as such no themes folder or a way to specify from where the files should be fetched. 

All the files that you require are available on this Github repository together with being in your webroot folder; technology and location of the files are also displayed in the [building panel assets](https://pterodactyl.io/community/customization/panel.html) documentation.

The official theme is technically a sample theme from which you can create your own. You could make your completely new different panel that uses the [API](https://dashflo.net/docs/api/pterodactyl/v1/) and leaves the original panel untouched, I've been working on a completely separate panel template that uses the API in my spare time.

**Comment by DaneEveritt** [comment]
I'm sorry, but I won't be creating documentation for how to create a whole new theme for the Panel. At this point in this project I'm honestly getting tired of the constant requests/pings/questions about theming. I get that people want that, but I truly do not have the desire to implement such functionality, nor do I see it being beneficial to how I'm trying to run this project and what I'm hoping to get accomplished.

If you want to theme Pterodactyl you're welcome to do so by creating a private fork of the software and then modifying the frontend files in `resources/scripts` to your hearts content (see `BUILDING.md`) and then recompiling and using that. There are many hosting companies doing such things without much trouble and just merging upstream changes into their Panel as they go.

Thats pretty much the end of the discussion around theming, I understand this angers some people but it just isn't something I want to add to the Panel. Additionally, as @Software-Noob mentioned I really don't see how it would be beneficial for me to spend time writing that documentation when it would effectively just be "how to make things with React & Typescript 101." There is nothing inherently special about the frontend setup going on with Pterodactyl.
