### ISSUE TITLE
Podman Networking issues

### ISSUE THREAD

**Issue by ollimaz** [pterodactyl/panel#3127]
Id like to change my container software from docker to [podman](https://podman.io/). Which is a drop-in replacement for docker. Which is able to run on my VPS.

Setting an alias works fine but the wing wont start with following error:

`failed to create required docker network for containers error=Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?Stacktrace:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
github.com/pterodactyl/wings/environment.ConfigureDocker
        /home/runner/work/wings/wings/environment/docker.go:47
github.com/pterodactyl/wings/cmd.rootCmdRun
        /home/runner/work/wings/wings/cmd/root.go:196
github.com/spf13/cobra.(*Command).execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854
github.com/spf13/cobra.(*Command).ExecuteC
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/pterodactyl/wings/cmd.Execute
        /home/runner/work/wings/wings/cmd/root.go:61
main.main
        /home/runner/work/wings/wings/wings.go:8
runtime.main
        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/proc.go:204
runtime.goexit
        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/asm_amd64.s:1374`

Seems to be a networking error. I think this is structure related... could this be changed?

Greetings

**Comment by notAreYouScared** [comment]
It's looking for the docker process to interact with. If it can't find it then it won't start. You'd probably have to edit the wings source in order for it to work properly. I doubt dane will add support for Podman

**Comment by sergejostir** [comment]
You have to configure the correct socket path. The default for podman appears to be `/run/podman/podman.sock` when running as root. The old daemon allowed to configure that using "docker.socket" config key, not sure what is it for the wings (check in the source).

**Comment by schrej** [comment]
Wings is using the regular docker environment variables and defaults. So either change the socket name or set the correct environment variable to the podman socket.

Note that podman is not supported and we most likely won't fix any incompatibilities.
