### ISSUE TITLE
Pinned containers persist even after unpinning

### ISSUE THREAD

**Issue by kakduman** [pterodactyl/panel#3130]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.2.3
* Server's OS: Debian 10.8
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
Pinning a container to certain threads makes the container run on those threads even after the pinned threads entry field is cleared.

**To Reproduce**
1. Start server with a multithreaded CPU. Do not pin CPU to threads.
2. Observe that the server is using a bit of all threads. Netdata helps visualize this, but there are plenty of ways to check.
3. Pin server to thread 0. Start the server.
4. Observe that the server is running on only thread 0.
5. Edit the server to remove thread 0 from the pinned threads. Leave the field blank. Start the server.
6. Observe that the container is still only running on thread 0.

**Expected behavior**
Removing thread 0 from the pinned threads and making the box blank should allow it to run on all threads again. Setting the box to contain all threads on the CPU (e.g. 0-31 for 3950X) should behave the same way as leaving it blank. However, leaving it blank saves the previous value rather than defaulting to all threads.

**Comment by trenutoo** [comment]
Duplicate of #3039

**Comment by kakduman** [comment]
My bad, looks like I missed it. Thanks :)
