### ISSUE TITLE
Dynamic IP Port Allocation

### ISSUE THREAD

**Issue by ewoudje** [pterodactyl/panel#3133]
**Is your feature request related to a problem? Please describe.**
My node has a dynamic public ip. Everytime it changes i need to modify my public ports to the new ip.

**Describe the solution you'd like**
You are able to type in a domain name in the IP Tab for adding allocations but it gets replaced by the ip from domain name at that moment, keep the DNS and use that instead of the IP at that moment.

**Comment by arantesxyz** [comment]
Have you tried using `0.0.0.0`?

**Comment by DaneEveritt** [comment]
This software is not designed to be used with such networks. You should use some other mechanism such as NAT to allow your servers to bind to a static IP address that resolves to a dynamic IP. Granted my knowledge of networking & terminology is slim, but that is also how things like AWS & GCP work, so this isn't really some crazy idea.
