### ISSUE TITLE
Regarding Sub Users File Manager 

### ISSUE THREAD

**Issue by IlPicasso** [Pterodactyl/Panel#314]
Even thought I am giving permissions to a sub user to modify a server in the file manager 

He stills get the message that says he is not allowed to

![image](https://cloud.githubusercontent.com/assets/5110242/23185329/1e0b2fac-f851-11e6-9982-1bad2c6304ee.png)

tried removing the sub user and adding it again
Just saw it is when you press the +

![image](https://cloud.githubusercontent.com/assets/5110242/23185335/25aa5af8-f851-11e6-973a-8d84c9d0b63b.png)

But he can still upload files by DRAGGING the file to the manager 

its weird

**Comment by IlPicasso** [comment]
Found out it is even more than that, they can't decompress even thought they have permissions

**Comment by DaneEveritt** [comment]
closed in https://github.com/Pterodactyl/Panel/commit/7e45f917c7cd563753ade5095e1aabdee748371a
