### ISSUE TITLE
Wings in Docker does not respect TZ env var

### ISSUE THREAD

**Issue by Sabinno** [pterodactyl/panel#3145]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.2.3
* Server's OS: CentOS 8 (Docker image is BusyBox)
* Your Computer's OS & Browser: Windows 10/Edge Chromium

**Describe the bug**
Upon startup, due to the fact that `tzdata` does not appear to be installed in the Wings docker image, the TZ env var is completely ignored.

This is a known behavior of the BusyBox image, per my rudimentary Google-fu. Apparently, adding the tzdata package, then setting the TZ env var, resolves this.

Daemon (uname -a): `Linux d4dd8918b66f 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 GNU/Linux`

**To Reproduce**
1. Set TZ env var to literally anything in example docker-compose.yml
2. `docker-compose up`
3. Look at logs; you will see Wings sets the TZ to UTC

**Expected behavior**
Set timezone properly when setting TZ in docker-compose.yml.

**Comment by DaneEveritt** [comment]
Dupe https://github.com/pterodactyl/panel/issues/3036
