### ISSUE TITLE
Restart doesn't work if a container doesnt already exist

### ISSUE THREAD

**Issue by mason-rogers** [pterodactyl/panel#3149]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.3.0
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: 

**Describe the bug**
If the container for the server doesn't exist on the node, the restart button spits out an error in the console as such:
![image](https://user-images.githubusercontent.com/26467584/110226053-732df600-7ee3-11eb-83dc-eff75bdba9ee.png)

**To Reproduce**
1. Stop the server if it's running
2. Delete the container (or restart node)
3. Click restart

**Expected behavior**
Start the server as usual

**Comment by DaneEveritt** [comment]
Does start work?

**Comment by mason-rogers** [comment]
Yep, start/stop works as usual it's just restart errors out if container doesn't exist already
