### ISSUE TITLE
Unable to download backups

### ISSUE THREAD

**Issue by notAreYouScared** [pterodactyl/panel#3151]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3

**Describe the bug**
When trying to download a backup you're greeted with a page refresh and that's about it...

**To Reproduce**
1. Create a backup
2. Attempt to download created backup

**Expected behavior**
The backup to start downloading.

![2021-03-07_01-23-01](https://user-images.githubusercontent.com/1757840/110231108-b25c4700-7ee3-11eb-8894-56176fb281a6.gif)

No logs in the console as it refreshes the page. Tried to slow the network down to see if anything popped out and nothing.... Wings appeared to get the request, as the below is posted in the console when the download button is clicked.

```
DEBUG: [Mar  7 07:21:17.517] GET /api/servers/bb0281b5-55d0-48e4-8508-a57c8283bd6f/ws client_ip=127.10.52.105 latency=4.518513274s request_id=326a9d21-1ad5-4f42-847b-7ffb8785396d status=200
```

**Comment by finnie2006** [comment]
Hello i have the same problem men

**Comment by BloomVPS** [comment]
Hi we are having the exact same issue as well on 1.3
