### ISSUE TITLE
 PHP Fatal error:  Trait 'Illuminate\\Database\\Eloquent\\Factories\\HasFactory' not found in /var/www/panel/app/Models/Model.php on line 15

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3153]
This error I get after updating panel to v1.3.0

even phpstorm sees something's not right.

![image](https://user-images.githubusercontent.com/6473565/110240778-2b948200-7f56-11eb-8df8-e310518511e0.png)

**Comment by mason-rogers** [comment]
Have you updated to PHP 7.4 or PHP 8, as the upgrade docs say to do?

I can't reproduce this on any of my test panels

**Comment by trenutoo** [comment]
You must upgrade your PHP and composer by following the PHP upgrade guide, after that return to the panel upgrade guide and perform the composer install command.

**Comment by sergejostir** [comment]
You need to run `composer install` ;)
