### ISSUE TITLE
file_denylist issue with BungeeCord

### ISSUE THREAD

**Issue by hypersmc** [pterodactyl/panel#3155]
**Background (please complete the following information):**
* Panel or Daemon: Panel and/or Wings (unsure most likley panel)
* Version of Panel/Daemon: 1.3.0 (both)
* Server's OS: Ubuntu Server 18.04 LTS
* Your Computer's OS & Browser: Windows 10 Pro 20H2 & Chrome 88.0.4324.190 

**Describe the bug**
On every egg there is the new function file_denylist but the only one that is bugged is Bungeecord
I have checked my DB if there is anything that it blocks everything is NULL, I have checked the file and the file have 
"file_denylist": [],
Even tho i get on my bungee server that file_denylist denies me from editing files.

**To Reproduce**
1. Make a BungeeCord server
2. Click on File Manager
3. Find a config file or some sort.
4. save it (No edit needed tho even if edited it still says error) and boom error.

**Expected behavior**
Well if the DB says NULL and there isn't any listed files in the egg then it shoudn't block anything.

**Comment by gOOvER** [comment]
Update your Panel; this should be fixes with 1.3.0

**Comment by hypersmc** [comment]
> Update your Panel; this should be fixes with 1.3.0

If you watched what version of panel and wings i am using it says 1.3.0

**Comment by gOOvER** [comment]
I saw it a lot of times today, that the installation stops and people means, that they have 1.3.0 ;)

"file_denylist": [],

is the normal entry in eggs.  File Deny List a a future feature

**Comment by hypersmc** [comment]
> I saw it a lot of times today, that the installation stops and people means, that they have 1.3.0 ;)

I went thro the update process 2 times. The first time failed second time didn't

**Comment by DaneEveritt** [comment]
Can you please provide the output of `php artisan p:info` (run in the panel root directory).

**Comment by hypersmc** [comment]
> Can you please provide the output of `php artisan p:info` (run in the panel root directory).

Yes here:
![image](https://user-images.githubusercontent.com/16544278/110250230-7f18c700-7f7a-11eb-957d-15e66c073c36.png)

**Comment by DaneEveritt** [comment]
I cannot reproduce this.

**Comment by hypersmc** [comment]
> I cannot reproduce this.

Updating to 1.3.1 (Wings and Panel) Fixed the issue.
