### ISSUE TITLE
Transfers of discord.js servers fail

### ISSUE THREAD

**Issue by Slitzo3** [pterodactyl/panel#3156]
**Background (please complete the following information):**
* Panel or Daemon: Panel & Daemon
* Version of Panel/Daemon: 1.3.0 for panel & daemon
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 & Chrome

**Describe the bug**
Transfers of discord.js servers fail with this error: 
![image](https://user-images.githubusercontent.com/33166817/110249071-7ae9ab00-7f74-11eb-82fc-ca0d840f6948.png)

**To Reproduce**
1. Have a discord.js server with node_modules installed
2. Transfer a discord.js server to another node

**Expected behavior**
The server should transfer.

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/issues/3015#issuecomment-761872227
