### ISSUE TITLE
CTRL+C and CTRL+F does not work in console (Panel 1.3)

### ISSUE THREAD

**Issue by Nice-Hosting** [pterodactyl/panel#3158]
**Background:**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3 
* Server's OS: Linux, Debian
* Your Computer's OS & Browser: Chrome, Firefox, Edge

**Describe the bug**
Panel PHP version: PHP 7.4.15
CTRL+C and CTRL+F does not work in the server-console.
Search bar doesn't appear. Text does not get copied.

**To Reproduce**
1. Go to the game-server console
2. Press CTRL+F
3. DefaultEvent gets cancelled by Console.tsx, but no search box appears
4. Mark text and press CTRL+C
5. Nothing happens

**Expected behavior**
Search box appears with CTRL+F, and text gets copied with CTRL+C

**Comment by EsserGaming** [comment]
Same issue here, was gonna point this out earlier but I got busy :/

Also my panel is latest 1.3.1 wings & panel. Using Ubuntu 20.04.2
