### ISSUE TITLE
Self Update fails because files are not downloaded

### ISSUE THREAD

**Issue by Boy132** [pterodactyl/panel#3159]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.0
* Server's OS: Debian 9
* Your Computer's OS & Browser: Win 10 & Opera

**Describe the bug**
When running the new self update command curl fails to download the new files:
> $upgrader> curl -L "https://github.com/pterodactyl/panel/releases/latest/download/panel.tar.gz" | tar -xzv
> [...]
> curl: (23) Failed writing body (402 != 1371)

**To Reproduce**
1. Go to your panel's dir
2. Run 'php artisan p:upgrade'
3. Start the process with 3 times 'yes'
5. Installation "finishes" but with old files

**Expected behavior**
Download the newest files. :D

**Comment by FoksVHox** [comment]
Can confirm this is happening on Ubuntu 20.04 as well.

**Comment by trenutoo** [comment]
Pretty sure you should receive an error regarding invalid -f flag usage. The path for -f flag is missing in the upgrade command, adding a dash will fix it
