### ISSUE TITLE
Failed to change SFTP-Password

### ISSUE THREAD

**Issue by ryaba** [Pterodactyl/Panel#316]
Then I changing password for SFTP-account of server. It returns this error:
There was an error while attmping to contact the remote service to change the password.

In logs of daemon I find only this:

> 14:58:10.416Z FATAL wings: A fatal error occured during an operation.
>     Error: Can't remove headers after they are sent
>         at ServerResponse.OutgoingMessage.removeHeader (_http_outgoing.js:390:11)
>         at ServerResponse.restifyWriteHead [as writeHead] (/srv/daemon/node_modules/restify/lib/response.js:426:14)
>         at _cb (/srv/daemon/node_modules/restify/lib/response.js:326:14)
>         at ServerResponse.send (/srv/daemon/node_modules/restify/lib/response.js:342:9)
>         at Responses.generic204 (/srv/daemon/src/helpers/responses.js:35:25)
>         at Auth.server.start.err (/srv/daemon/src/controllers/routes.js:154:27)
>         at Async.series.err (/srv/daemon/src/controllers/server.js:243:20)
>         at /srv/daemon/node_modules/async/dist/async.js:3853:9
>         at /srv/daemon/node_modules/async/dist/async.js:484:16
>         at replenish (/srv/daemon/node_modules/async/dist/async.js:1025:25)
> 14:58:10.418Z FATAL wings: A fatal error occured during an operation.
>     Error: Callback was already called.
>         at /srv/daemon/node_modules/async/dist/async.js:985:32
>         at /srv/daemon/node_modules/async/dist/async.js:3850:13
>         at apply (/srv/daemon/node_modules/async/dist/async.js:41:25)
>         at /srv/daemon/node_modules/async/dist/async.js:76:12
>         at Object.container.stats [as callback] (/srv/daemon/src/controllers/docker.js:246:29)
>         at /srv/daemon/node_modules/dockerode/lib/container.js:645:10
>         at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:230:19)
>         at ClientRequest.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:215:10)
>         at emitOne (events.js:96:13)
>         at ClientRequest.emit (events.js:188:7)

**Comment by DaneEveritt** [comment]
Can you try rebooting the daemon and see if that fixes it?

**Comment by ryaba** [comment]
Yeah, thanks, it didn`t work before, now it works.

**Comment by DaneEveritt** [comment]
Excellent! It's a known issue that should be fixed soon.
