### ISSUE TITLE
The created_at column on recovery_tokens is null

### ISSUE THREAD

**Issue by RihanArfan** [pterodactyl/panel#3163]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 / Chrome

**Describe the bug**
The created_at column on the recovery_tokens is null.
Panel: PHP 8.0.3

**To Reproduce**
Set up 2-factor authentication
Check the recovery_tokens table

**Expected behaviour**
I expect the created_at column to be populated.

**Comment by trenutoo** [comment]
I created two accounts with 2FA enabled on my test panel running 1.3.1 with PHP 8.0.3, and each time it populated the recovery_tokens table with 10 tokens for each user

**Comment by matthewpi** [comment]
> I created two accounts with 2FA enabled on my test panel running 1.3.1 with PHP 8.0.3, and each time it populated the recovery_tokens table with 10 tokens for each user

Did it populate the `created_at` column as well?

**Comment by trenutoo** [comment]
> > I created two accounts with 2FA enabled on my test panel running 1.3.1 with PHP 8.0.3, and each time it populated the recovery_tokens table with 10 tokens for each user
> 
> Did it populate the `created_at` column as well?

Oh, I completely missed that part. I shouldn't read issues before having morning coffee.

created_at is indeed set to (NULL)
