### ISSUE TITLE
Setting memory to 0 breaks console

### ISSUE THREAD

**Issue by marcusmauricio** [pterodactyl/panel#3164]
**Background:**
* Panel or Daemon: Pterodactyl? and wings
* Version of Panel/Daemon: 1.3.1
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 20, Google Chrome

**Describe the bug**
Panel: '7.4.16'

When I try to set the allocated memory of a server to 0 to allow unlimited memory, it completely breaks that server's console. (https://prnt.sc/10ghpuu (ignore the Redis errors, that's my plugin) and sometimes I will get this https://prnt.sc/10giij7)

**To Reproduce**
1. Go to 'Admin Panel'
2. Click on 'The server'
3. Scroll down to 'Ram'
4. Set it to 0 and save

**Expected behavior**
Allowing unlimited memory

**Comment by notAreYouScared** [comment]
It's a Java application so you can't use 0 for the xmx argument. You'd have to set it to the actual max the server has or remove the argument( might get angry never tried removing it )

You also don't want to use always pretouch or else OOM will kill it. As it will allocate all the ram when it stsrt.

**Comment by marcusmauricio** [comment]
> It's a Java application so you can't use 0 for the xmx argument. You'd have to set it to the actual max the server has or remove the argument( might get angry never tried removing it )
> 
> You also don't want to use always pretouch or else OOM will kill it. As it will allocate all the ram when it stsrt.

I know, but in pterodactyl when you set the amount of ram to 0 it means unlimited. And even when I set it back to 2000, it still breaks :/

**Comment by DaneEveritt** [comment]
This is not a bug, you cannot use "0" without adjusting the startup arguments to not try to auto-inject that value into the parameters. It's not that smart.

**Comment by marcusmauricio** [comment]
> This is not a bug, you cannot use "0" without adjusting the startup arguments to not try to auto-inject that value into the parameters. It's not that smart.

It's weird because my other servers are working with me setting the server ram in the admin panel to 0 as it works as expected and sets the ram to unlimited. But with this one server, the console is completely blank and the status stuff does not work (https://prnt.sc/10gkhgt).

I am talking about this section in the admin panel btw: https://prnt.sc/10gkk86
