### ISSUE TITLE
Bug with schedules

### ISSUE THREAD

**Issue by lejoueur50** [pterodactyl/panel#3165]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10, Chrome

**Describe the bug**
When a schedule is created with two tasks, and with a time offset defined, the first task will be executed, but the second isn't, and the schedule is set on "processing" forever.
![Capture](https://user-images.githubusercontent.com/56761209/110467103-e055ad00-80d6-11eb-91e7-54182673c096.PNG)
Panel: PHP 8.0.3

**To Reproduce**
Upgrade the panel to 1.3.1, and try to create or update a schedule created before the 1.3.0 with two tasks and a time offset

**Expected behavior**
I expected the schedule to work normally like before the panel's update

**Comment by trenutoo** [comment]
Do you have any errors in your Panel logs? I've seen this occur when other schedules are missing the month syntax, which was added in 1.3 but wasn't populated during the database seeding.

You can check the Panel logs with the following command:
`tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99`

**Comment by Espantonius** [comment]
It happens the same to me. I have fixed the topic of the month in the database but the same thing keeps happening to me.
Even if i give "run now" it only executes the first command and stays in processing.

**Comment by trenutoo** [comment]
> It happens the same to me. I have fixed the topic of the month in the database but the same thing keeps happening to me.
> Even if i give "run now" it only executes the first command and stays in processing.

I personally can't reproduce this issue with either two of my Panels that are running 1.3.1 with both older and new schedules while running PHP 8.0.3, but I've seen a couple of reports for this on the Discord Server.

**Comment by lejoueur50** [comment]
Here are the logs : https://bin.ptdl.co/vtzfx/
I corrected the lackings months entries in the database before opening this issue, but nothing had changed, the problem is still there

**Comment by matthewpi** [comment]
> Here are the logs : https://bin.ptdl.co/vtzfx/
> I corrected the lackings months entries in the database before opening this issue, but nothing had changed, the problem is still there

`InvalidArgumentException: 50 6 *  * is not a valid CRON expression` I don't think you did correct them unless those errors happened before you corrected it.  Make sure your queue worker is running and that you restarted it after upgrading to `1.3.1` (`cd /var/ww/pterodactyl && php artisan queue:restart`)

**Comment by lejoueur50** [comment]
I have corrected every schedule manually, and ran the command `UPDATE panel.schedules SET cron_month = '*';` after that, so I thinks these errors was created before I updated everything

> Make sure your queue worker is running and that you restarted it after upgrading to 1.3.1 (cd /var/www/pterodactyl && php artisan queue:restart)

I've tried, but nothing seems to change, the problem is still there

**Comment by Telesphoreo** [comment]
Make sure pteroq.service is running. If it's failed here's what's happening: The /var/www/pterodactyl/storage/logs is owned by root:root when it should be owned by www-data:www-data. This causes the service to fail so you should chown the folder to www-data:www-data

To prevent this from happening you should add a PreExecStart chowning the files to www-data:www-data. Here is what my pteroq service looks like

```
# Pterodactyl Queue Worker File
# ----------------------------------

[Unit]
Description=Pterodactyl Queue Worker
After=redis-server.service

[Service]
# On some systems the user and group might be different.
# Some systems use `apache` or `nginx` as the user and group.
User=www-data
Group=www-data
Restart=always
ExecStartPre=/usr/bin/chown -R www-data:www-data /var/www/pterodactyl/storage/logs/
ExecStart=/usr/bin/php8.0 /var/www/pterodactyl/artisan queue:work --queue=high,standard,low --sleep=3 --tries=3

[Install]
WantedBy=multi-user.target
```
I had to add a php8.0 to the ExecStart but you may not necessarily have to. No idea why that happens

**Comment by lejoueur50** [comment]
> Make sure pteroq.service is running. If it's failed here's what's happening: The /var/www/pterodactyl/storage/logs is owned by root:root when it should be owned by www-data:www-data. This causes the service to fail so you should chown the folder to www-data:www-data

I found that pteroq.service wasn't running, I've started it, and the schedules seems to be working normally, thanks you !
So, the fix that worked for me is to run the command `sudo systemctl start pteroq.service`
