### ISSUE TITLE
i have a problem installing pterodactyl on my dedicated server it won't let me reconnect to the server by ssh

### ISSUE THREAD

**Issue by Family4GamersYT** [pterodactyl/panel#3167]
good afternoon, i have a problem installing pterodactyl on my dedicated server it won't let me reconnect to the server by ssh
The problem arises because where I rent the dedicated server you can only connect to the ssh through the port that they give me, which is custom, when trying to connect to it through port 22 it does not connect only happens when you install pterodactyl panel, if the panel is not installed, no There is no problem when connecting to ssh but when installing the panel it stops working

**Comment by trenutoo** [comment]
This is in no way related to Pterodactyl. What you're looking for is general Linux support. Change the overlapping ports or get someone to help you with your administration issues. Wings ports are by default 8080/2022 and can be altered in the panel's Node settings.
