### ISSUE TITLE
Backups not Deleted

### ISSUE THREAD

**Issue by adrijanb** [pterodactyl/panel#3171]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.2.2
* Server's OS: Ubuntu18.04
* Your Computer's OS & Browser: Chrome, macOS

**Describe the bug**
If a backup fails (for example: it could not reach the s3) the panel is saying that the backup is "failed". Due the failed state of the backup , you cannot delete the backup anymore.

is there a way to delete them from database or how can i remove them?

https://streamable.com/t22ntb

**To Reproduce**
Watch the video. I wanted to create a backup, but for some reason it was not able to upload to AWS S3, so i wanted to delete them. 

**Expected behavior**
They should get deleted

**Comment by FoksVHox** [comment]
Upgrade to the latest version. The 1.2.2 version of the panel isn't supported anymore.

**Comment by adrijanb** [comment]
I did it. Same issue.

**Comment by DaneEveritt** [comment]
A video is not useful, please provide the error logs from your panel relating to this request.
