### ISSUE TITLE
Incorrect year specification under the servers

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3172]
**Background (please complete the following information):**
* Panel or Daemon: Panel Frontend
* Version of Panel/Daemon: 1.3.1 / PHP 7.4.16 / Linux pterodactyl 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
* Server's OS: Debian 10
* Your Computer's OS & Browser: Win 10: Firefox / Chrome

**Incorrect year specification under the servers**
https://i.imgur.com/Frcgglp.png

**Comment by DaneEveritt** [comment]
This isn't a bug.

**Comment by Felix5566** [comment]
But it is also not good
