### ISSUE TITLE
Cannot delete server if node is already destroyed

### ISSUE THREAD

**Issue by acl1704** [pterodactyl/panel#3176]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.1
* Server's OS: N/A
* Your Computer's OS & Browser: Windows 10 / Firefox 88

**Describe the bug**
A 500 server error results upon trying to forcibly delete a server when the node cannot be contacted.

No stacktrace is written to the panel logs unfortunately.

**To Reproduce**
1. Create a node and a server
2. Delete/stop the wings host
3. Try to forcibly delete the server
4. See 500 server error

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

The server is successfully deleted which then allows the node to be deleted. If this is working as intended then this issue can be a feature request.

**Comment by notAreYouScared** [comment]
I've tried this and not able to repeat it. I've stopped wings and forcibly deleted the server, deleted just fine in the panel.

You also cannot delete a node that has servers attached to it in the panel, the button is disabled?

**Comment by DaneEveritt** [comment]
@AreYouRlyScared can you try by removing the DNS entry for it? Wonder if a different error is returned for some networking events which causes it to fail out. There is likely a difference between connecting and not finding a service on that port, and not resolving it at all.

**Comment by DaneEveritt** [comment]
Just tested with a completely random node and had no issue forcibly deleting the server from it even without any type of running wings instance or resolving DNS.
