### ISSUE TITLE
Unable to upload executable files

### ISSUE THREAD

**Issue by FoksVHox** [pterodactyl/panel#3177]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.1
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Brave
* PHP version: 8.0.3

**Describe the bug**
You're unable to upload an executable file for Ubuntu. I use Parker's DiscordGO egg. And when I compile the bot on a VM and then tries to upload it to the server, the panel returns an error, say "An unexpected error was encountered while processing this request"

**To Reproduce**
1. Add the egg to the panel
2. Upload a Go application to the server
3. See an error

**Expected behavior**
I would expect the server to just allow the upload.

**Logs** 
Panel: https://bin.ptdl.co/x01sa/

**Comment by DaneEveritt** [comment]
Please include the egg and file you're trying to upload (if possible) in this issue.

**Comment by DaneEveritt** [comment]
Please include the egg and file you're trying to upload (if possible) in this issue.

**Comment by FoksVHox** [comment]
@DaneEveritt 
Egg: https://github.com/parkervcp/eggs/blob/master/bots/discord/discordgo/egg-discordgo-generic.json
If you'd like the file, I can email it, I'd prefer not to upload it publically

**Comment by DaneEveritt** [comment]
Thats fine I can just upload a wings binary

**Comment by DaneEveritt** [comment]
I cannot reproduce this issue, I'm able to upload files without issue.
