### ISSUE TITLE
Delete all files before restore does not work.

### ISSUE THREAD

**Issue by alliraine** [pterodactyl/panel#3178]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon:  1.3.1
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 Firefox

**Describe the bug**
When selecting to delete all files before restoring from backup, that checkbox isn't actually passed. It's just ignored.

**To Reproduce**
1. Restore from backup.
2. Select delete all files first
3. Watch it not delete the files

**Expected behavior**
It should delete the files and not keep them.

**Comment by trenutoo** [comment]
I can confirm that it does indeed not work as advertised at this moment
