### ISSUE TITLE
Docker host network support AKA LAN mode

### ISSUE THREAD

**Issue by craige1** [Pterodactyl/Panel#318]
I would like an option to allow a container/game server to be joined to the host/node's docker host network. This will allow a container to share the servers network interface directly without bridging/natting. I understand that this will share the ports with the host, and that server will not get their own ip (they will share the hosts), but that is part of the requirement.

Reason.
1. It would allow game servers to broadcast to the local host network. Enabling normal game lan support, that shows up in the game clients network browser.

Use case:
1. I run the IT network for a couple school in town. The schools have requested to use minecraft education edition and other types of games for learning. These server need to be hosted on the lan, but essentially controlled by non-tech people, like teachers and school staff. Pretodactyl comes along way in making that happen, and it would be great if we could use it to manage the games on the local network.

2. Actual LAN event support. I also run a fairly large LAN 50+ people, and again, it would be great if some non tech people could have basic control of servers (start, stop, console access, file access for logs/scores etc).

**Comment by DaneEveritt** [comment]
So effective add support for the `host` interface within Docker?

**Comment by craige1** [comment]
In one word, yes.

**Comment by DaneEveritt** [comment]
Done.
