### ISSUE TITLE
Failed to get multipart form data from request.

### ISSUE THREAD

**Issue by Indigodevops20** [pterodactyl/panel#3180]
**Background (please complete the following information):**

1. Panel or Daemon: Panel
2. Version of Panel/Daemon: 1.3.1
3. Server's OS: Ubuntu 18.04
4. Your Computer's OS & Browser: Windows 10 Chrome

**Describe the bug**
I was looking at the pterodactyl api to upload a file and the post returns this error.

**To Reproduce**

1. get the url with the get method to "https://pterdactyl.file.properties/api/client/servers/1a7ce997/files/upload"
2. make the post with the url obtained and from the body place file_get_contents($file['tmp_name']) 
Note: I use php 7.2 

**Expected behavior**
upload the file correctly without sending errors

**Comment by DaneEveritt** [comment]
This is the exact same endpoint we use internally for uploading files, which works fine. This is unlikely to be a bug with this software is and most likely an issue with your implementation. However there is no actual detail here so I have no answer for you.
