### ISSUE TITLE
Pterodactyl considering status code 0 as crash

### ISSUE THREAD

**Issue by arantesxyz** [pterodactyl/panel#3181]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.1.1
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Does not apply 

**Describe the bug**
Wings consider status code 0 as a crash and restarts the server.
![802E0D30-E067-4877-8B2A-7B7056C51EA2](https://user-images.githubusercontent.com/42740492/111019593-f5fcf800-839e-11eb-80fa-4d09c23d7201.png)

Sample code that ends returning 0 (success):
![7A0E9177-A898-4860-B908-061AF29F7CBE](https://user-images.githubusercontent.com/42740492/111019594-f72e2500-839e-11eb-82a7-b7d045f07d0d.png)

**To Reproduce**
1. Create a server to run a program of yours
2. Make the program exit with status code 0
3. See error

**Expected behavior**
Programs that exit with status code 0 shouldn’t be considered as crashed and shouldn’t restart.

**Comment by arantesxyz** [comment]
I just saw this was already fixed in the code, i guess I’m just not up to date.

https://github.com/pterodactyl/wings/blob/217ca72eb3024cc062fb82da5f2c32ddb36e0f48/server/crash.go#L65

**Comment by arantesxyz** [comment]
I'm reopening because the error persist in 1.3.1.

Wings version: 1.3.1
SO: Ubuntu 20.04 - Linux (amd64) 5.4.0-65-generic

**Comment by DaneEveritt** [comment]
This is not a bug, there is a config setting for it and it is working as expected.

**Comment by trenutoo** [comment]
You can change it using the detect_clean_exit_as_crash option in the Wings `config.yml`, it's noted in the [Additional Wings configuration](https://pterodactyl.io/wings/1.0/configuration.html#other-values) documentation.

**Comment by arantesxyz** [comment]
Thank you, i didn't see that. My bad.
