### ISSUE TITLE
Migrations fail to run when sql_require_primary_key is set

### ISSUE THREAD

**Issue by halkeye** [pterodactyl/panel#3183]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: v1.3.1
* Server's OS: Linux (Digital ocean Apps Platform)
* Your Computer's OS & Browser: Windows + Firefox 87.0b9

**Describe the bug**
I'm trying to see if I can run pterodactlyl panel on digital ocean's app platform, mostly to see if i can. When running `php artisan migrate --seed --force` (https://github.com/ccarney16/pterodactyl-containers/blob/df8846df99b5dce0aaee6382f67dafd630aed6fb/manifest/panel/root/entrypoint.sh#L67) on with a managed database, which apparently has strict mode turned on:

```
SQLSTATE[HY000]: General error: 3750 Unable to create or change a table wit  
  hout a primary key, when the system variable 'sql_require_primary_key' is s  
  et. Add a primary key to the table or unset this variable to avoid this mes  
  sage. Note that tables without a primary key can cause performance problems  
   in row-based replication, so please consult your DBA before changing this   
  setting. (SQL: create table `password_resets` (`email` varchar(191) not nul  
  l, `token` varchar(191) not null, `created_at` timestamp not null) default   
  character set utf8mb4 collate 'utf8mb4_unicode_ci') 
```

This stops the migration and doesn't keep creating tables so when you go to run the app, as expected, it errors out with missing tables.

It looks like running `SET SESSION sql_require_primary_key='OFF';` before creating one of those tables that fails prevents the error from being outputted. 

The other option is to actually add primary indexes to tables that are missing it. I'm not sure how doable it is to past migrations though.

**To Reproduce**
(I can provide an app platform spec file if desired)
1) Fresh mysql install
2) SET sql_require_primary_key='ON'; -- or other way of setting it
3) run migration

**Expected behavior**
Mysql tables are created

**Comment by DaneEveritt** [comment]
I won't be fixing this at this time, you need to run the server with `sql_require_primary_key = OFF` to use Pterodactyl as we have multiple tables without primary key indexes and I don't want to add indexes to them at this time.

**Comment by ibigpapa** [comment]
can this be reconsidered as I have this issue and for performance reasons the require primary key is in place.

Heres the info from the provider of the server

> MySQL databases containing tables without a primary key and which contain more than 5000 rows may experience replication issues. To prevent this, DigitalOcean now requires you to add a primary key for each new table you create in any managed MySQL database created after 8 April 2020. We strongly recommend that you also add primary keys in existing databases to avoid replication issues.

**Comment by ibigpapa** [comment]
So I have a work around.  I created a temp instance using the docker-compose example.  Then I used docker exec on the db container to dump the data and tables .  Added `USE panel; ` to the top of the file and added `SET sql_require_primary_key='ON';` after then at the bottom added `SET sql_require_primary_key='OFF';`

**Comment by czmdav** [comment]
> I won't be fixing this at this time, you need to run the server with `sql_require_primary_key = OFF` to use Pterodactyl as we have multiple tables without primary key indexes and I don't want to add indexes to them at this time.

@DaneEveritt This issue is still present with the latest version, will this change be considered in the future?
