### ISSUE TITLE
Dynamically add servers on Pterodactyl

### ISSUE THREAD

**Issue by HevelMc** [pterodactyl/panel#3184]
**Is your feature request related to a problem? Please describe.**
No, this is a feature I would like to see on pterodactyl.

**Describe the solution you'd like**
A system that would allow, with a request (or other) to dynamically add a server to the list of servers of a person and to start it. It would take as parameters a docker image and the root of the server to start it (and potentially other parameters like the RAM used...).
A second request could be sent to delete or archive it.

**Describe alternatives you've considered**
At the moment, I use a python script that receives by sockets the notice of the Java plugin on the BungeeCord (static on Pterodactyl), copies files to create a functional server (with paper, configurations, plugins...) and starts it with a docker command.
The idea would be to launch this server not directly with a docker command, but by the panel automatically in order to be able to see the console of the server from pterodactyl, to manage it, etc.

**Additional context**
I can provide a part of my python program if needed.

Thanks in advance for your help.
Regards, Hevel.

**Comment by mason-rogers** [comment]
The application api...?

**Comment by matthewpi** [comment]
This is already available through the Application API

**Comment by NickEvansDev** [comment]
For more information, you can see the Application API docs (by codeco): https://dashflo.net/docs/api/pterodactyl/v1/#req_190b1006d60748abbeda37c7d407345a
