### ISSUE TITLE
Panel Update Error 500

### ISSUE THREAD

**Issue by ItsConnor631** [pterodactyl/panel#3193]
I updated to the new 1.3 panel and when i log on to the website it show "500 | Server Error" Please help

**Comment by trenutoo** [comment]
Join the [Discord server](https://discord.gg/pterodactyl) for support or use the [Discussions ](https://github.com/pterodactyl/panel/discussions)tab.

**Comment by ItsConnor631** [comment]
When I try it says "Whoops... Unable to accept invite"

**Comment by ItsConnor631** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/73563401/111412543-cfd6a100-8699-11eb-830c-b150b56c8887.png)
