### ISSUE TITLE
Link's don't highlight correctyl in console

### ISSUE THREAD

**Issue by hsnbozkurt** [pterodactyl/panel#3194]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.1
* Server's OS: Not Releated 
* Your Computer's OS & Browser: Google Chrome Stable Build 89.0.4389.90 Windows 8.1

**Describe the bug**
Server Console
**To Reproduce**
Log A link containing & To Console
Observe
[İmage](http://de1.nightservers.xyz:25565/vQhu)
**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
Link highlight's correctyl

**Comment by hsnbozkurt** [comment]
[Used Link in test](https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token)

**Comment by DaneEveritt** [comment]
Probably a bug in the plugin we use, I don't really care though, its such a minor thing.
