### ISSUE TITLE
Backups issue

### ISSUE THREAD

**Issue by Rezanans-wow** [pterodactyl/panel#3199]
**Background (please complete the following information):**
* Panel or Daemon: 1.3.1 (Panel, and wings last)
* Version of Panel/Daemon:  1.3.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Firefox  & Windows 10 

**Describe the bug**
The bug on high size of backup (Default not AWS), are crashing OS. The OS is clean, its not overload issue, its not hosting 'oversell' because its located at my home. Its a dedicated i7 7700k with NVME SSD, and DDR4 / 48 GB KVM Virtualisation (Claster not overloaded too maximal 80% of usage processor server). So its like a bug, for crashing OS with servers. 
Uptime log: https://status.pterohost.com/787280452 

**To Reproduce**
1. Go to Backups
2. Click on Create new (With file size example 29.98 GB like on video)
3. Wait 1-2 minutes 
4. See error (OS are complete down!)
4.1 Next error, if system boot manually (Backup are creating, but you wait up to 10 minutes and see red box 'FAILED')

**Expected behavior**
I really try do any log, or additional information. But i cant log it error, if you know how i can do logs of down system on backup write me, i try use it.
Video (without cuts, of problem for understand) https://www.youtube.com/watch?v=gwh1o59Cj3w

**Comment by DaneEveritt** [comment]
I'm not going to waste time looking into this unless you can provide explicit logs from your server indicating why it is shutting down. This is highly unlikely to be a bug with this software, please provide actual logs showing the shutdown occurring, and whatever might be happening in Wings at the same time.

Servers don't just shut down for no reason.
