### ISSUE TITLE
Redesign using Semantic UI

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#32]
This is open for discussion from everyone. I am considering rewriting the front-end design using Semantic UI (found [here](http://semantic-ui.com)). Personally I think it looks much better and is more feature rich than bootstrap.

**Comment by DDynamic** [comment]
I am all for it!

**Comment by IanSzot** [comment]
I support that, Bootstrap is too overused

**Comment by DaneEveritt** [comment]
After playing with it a bit I'm not super thrilled about layouts using it. I might consider this later down the road.
