### ISSUE TITLE
Deleting Servers Issue

### ISSUE THREAD

**Issue by IlPicasso** [Pterodactyl/Panel#320]
So I have detected many issues regarding deleting servers which I have mentioned to @DaneEveritt 

Basically, the servers are getting deleted in the daemon but are not getting deleted on the PANEL, so you need to force delete them

Another thing that happened me, yesterday I tried deletting a server. This server had a Database associated.

Rarely, when I deleted the server it deleted the database linked (as it had to) the issue here is that the panel didn't deleted the server, either the database from the panel DB, so it appeared as it was still existing

Every time I tried to delete the server I got an exception

The exception said that it could not DROP the database because it didn't exist. 

So my conclusions here is that the panel did deleted the Mysql Database, but it didn't got registered back in the panel. So the reason it didn't let me delete the server in the first place was because it was trying to delete the database first which was already deleted (I had to recreate the database so I could delete the server)

So, there are two situations here, it happens with servers created with databases and servers created without database

**Comment by DaneEveritt** [comment]
It seems like my code here might be faulty, as it should be trying to delete the server on the panel first, and if any pat of that fails it doesn't touch the node. I'll take a look and get back to you with the findings.

**Comment by IlPicasso** [comment]
Maybe the problem was generated because cron tasks were not configured correctly

Just a thought.

**Comment by DaneEveritt** [comment]
This is now fixed by 4ad09c5435e12a9ab216ca0e8a882e597ad3ed84

The main issue was that if the daemon timed out or took too long it would hang the MySQL server.
