### ISSUE TITLE
Global Start/Stop/Kill button for all owned servers.

### ISSUE THREAD

**Issue by the-w41k3r** [pterodactyl/panel#3207]
Add a Global command for all owned servers.

A button/command area which can be used to start all/stop all/kill all or send commands to all the servers

**Comment by NickEvansDev** [comment]
If someone has several servers they could overload a node if they are started/restarted at the same time, so maybe an optional delay could be added

**Comment by trenutoo** [comment]
Duplicate of #278 

You can at this moment perform bulk power actions using [artisan](https://pterodactyl.io/community/tutorials/artisan.html#server-bulk-power)
