### ISSUE TITLE
Sending email via smtp appears broken in 1.3.1

### ISSUE THREAD

**Issue by joker-119** [pterodactyl/panel#3208]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Fedora 33 Chrome

**Describe the bug**
After updating the panel to 1.3.1, I am unable to send smtp emails via sendgrid, receiving the following message:
An error occurred while attempting to test mail settings: Connection could not be established with host smtp.sendgrid.net :stream_socket_client(): unable to connect to ssl://smtp.sendgrid.net:465 (Connection timed out)

PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

Sending emails via sendgrid works just fine on the same machine in WHMCS.

**To Reproduce**
1. Install panel version 1.3.1
2. Setup SMTP email settings with sendgrid
3. Try and send a test email

**Expected behavior**
It successfully sends the email as it did in previous versions.

**Comment by trenutoo** [comment]
I'm using Sendgrid, and it works fine for me. The issue is most likely with your SMTP port and encryption. Have you tried using the default 587 port with TLS?

**Comment by joker-119** [comment]
I have, and it results in the same error message, just with tcp:// instead of ssl:// and :587 instead of :465

The same machine also runs a WHMCS website, and sendgrid works fine there.

**Comment by joker-119** [comment]
Interesting, traceroute shows that packets on ports 25, 465 and 587 aren't making it anywhere at all, but it's strange that sending emails on WHMCS seems to work fine. 

This report may be incorrectly placing the blame on Pterodactyl, I will need to investigate further with the network admin where this server is located.

**Comment by DaneEveritt** [comment]
This is not a bug with this software, as is indicated by the error messaging:

```
unable to connect to ssl://smtp.sendgrid.net:465 (Connection timed out)
```

We do not control your systems networking when it comes to things like this. :)
