### ISSUE TITLE
Password reset emails are not sent

### ISSUE THREAD

**Issue by joker-119** [pterodactyl/panel#3209]
**Background (please complete the following information):**
* Panel or Daemon:  Panel
* Version of Panel/Daemon: 1.3.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Fedora 33 Chrome

**Describe the bug**
PHP Ver 7.4

I fixed my previous bug report, it turned out to be an issue with the data center, they decided to block all outgoing smtp ports without telling anyone and I had to request to have them re-opened. 
Now my test emails are sent successfully, however, password recovery emails are still not sent.

An entry gets added to the pterodactyl database password_resets, but the email containing the reset link never appears. 3 of my clients have reported this issue, and I've tested it myself with my own account on the panel, and can confirm that the password reset link never shows up, but I cannot find any record of any errors anywhere, and when i test the mail function, the test email shows up in my inbox virtually instantly.

**To Reproduce**
1. Try to reset your password on the pterodactyl panel

**Expected behavior**
Receive an email with the password reset link.

**Comment by DaneEveritt** [comment]
Your queue worker (`pteroq`) probably isn't running or needs to be restarted?

**Comment by joker-119** [comment]
Interesting, I'm not sure why it ever got stopped, but you're correct, I needed to start it again as it was inactive. This issue is also invalid, sorry for wasting your time, thanks for you help Dane.
