### ISSUE TITLE
Connecting to Local Servers in BungeeCord Issue

### ISSUE THREAD

**Issue by IlPicasso** [Pterodactyl/Panel#321]
Hello, so this is an issue regarding BungeeCord

The issue here is that I can't connect to the servers that are on the same node with BungeeCord but I can connect to other servers in other nodes through BungeeCord

I have tried in the config.yml of bungeecord using the public ip, 127.0.0.1 and localhost. Something that worked out but I am not sure if it is a good practice is using these ips that provides the same panel

http://f.cgm.rs/putty_2017-02-22_14-02-59.png

But as I said, I don't think it is a good practice to use those, mostly considering the fact that we don't know if those are static and won't change at any time

**Comment by schrej** [comment]
Using 127.18.0.1 as the IP should work. The ports need to be open on the firewall as well.

**Comment by IlPicasso** [comment]
Just checked with Clean Firewall (only dockers one)
a
You can only connect to a server from the same node using the IP provided by the daemon to the port designed

Like this
http://f.cgm.rs/putty_2017-02-23_20-18-30.png

http://f.cgm.rs/opera_2017-02-23_20-18-50.png

Otherwise it wont connect

So using 172.18.0.1 is not the solution

**Comment by schrej** [comment]
It has worked for us in the past, we will try to improve networking. I'll close this as it is resolved for now. The IPs may change when you rebuild containers, we'll try to get consistent container names per server so you can use those instead (docker has some dns resolution for the container names)
