### ISSUE TITLE
Make Pterodactyl bandwidth like on Google

### ISSUE THREAD

**Issue by Misio12320** [pterodactyl/panel#3210]
**Is your feature request related to a problem? Please describe.**
I have a problem while downloading/uploading some files because the connection is slow. When I upload to Google Drive the speed is increadibly fast.

**Describe the solution you'd like**
Google and Discord have this thing where slow connection while downloading/uploading are much faster than normal sites. Pterodactyl can add this feature.

**Describe alternatives you've considered**
Add this thing. 

**Additional context**
Uploading to YouTube a example video bandwidth:
![bandicam 2021-03-22 20-17-54-240](https://user-images.githubusercontent.com/42146429/112045995-c5118580-8b4b-11eb-8e76-e4ba304bab93.jpg)
Uploading to my pterodactyl Panel and other sites..
![bandicam 2021-03-22 20-20-01-139](https://user-images.githubusercontent.com/42146429/112046227-0d30a800-8b4c-11eb-9ca2-171f43883d20.jpg)
Downloading from Google Drive speed:
![bandicam 2021-03-22 20-23-01-243](https://user-images.githubusercontent.com/42146429/112046525-72849900-8b4c-11eb-9dcb-25b1a63aca5c.jpg)
Downloading from my Pterodactyl Panel:
![bandicam 2021-03-22 20-21-39-312](https://user-images.githubusercontent.com/42146429/112046378-3d784680-8b4c-11eb-851f-50f1d35630c3.jpg)

**Comment by AdmiraalA** [comment]
This is just a matter of routing geo-ip CDN and how the webserver is configged ( Nginx/Apache config , NICspeed)

**Comment by matthewpi** [comment]
Upload speed is determined by your internet connection and your server, uploads are directly sent to wings and are capable of saturating gigabit connections.
