### ISSUE TITLE
Lost my database when recovering from a backup

### ISSUE THREAD

**Issue by iWanheda** [pterodactyl/panel#3211]
Yeah so, I recovered from a backup and boom database is gone
![Image](https://b.catgirlsare.sexy/YpeGZNy6.png)

(yes it was created when I did the backup), any way to recover it?

**Comment by FoksVHox** [comment]
Use the template, they're there for a reason..

**Comment by NietThijmen** [comment]
You could make a mysql backup in most mysql software iirc 

I know it is a feature in heidisql

**Comment by DaneEveritt** [comment]
Unless you use the template I'm not burning limited time on this. But regardless the in-panel backup system has zero touch points with the databases.

**Comment by iWanheda** [comment]
I have no idea what you guys mean by template, but I did a FULL BACKUP of the machine, not pterodactyl, just wondering why the database is gone, but for the other server it's still there.

**Comment by FoksVHox** [comment]
> I have no idea what you guys mean by template, but I did a FULL BACKUP of the machine, not pterodactyl, just wondering why the database is gone, but for the other server it's still there.

Whenever you open an issue on the [bug tracker](https://github.com/pterodactyl/panel/issues/new/choosel) then you'll see something like this: 
![image](https://user-images.githubusercontent.com/37844753/112204245-bd1d1880-8c13-11eb-94bb-6b3a4e2caab7.png)

If you believe that this is a bug with Pterodactyl you'll choose the "Get Started"-button on "Bug Report", if you have a feature request, you'll choose the "Get Started"-button on feature request.. But honestly, it doesn't sound like an issue with Pterodactyl to me.
