### ISSUE TITLE
Ability to skip a schedule and cancel a running schedule

### ISSUE THREAD

**Issue by SeaLife** [pterodactyl/panel#3212]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
1) Sometimes it would be neat to "skip" an execution, in case the worker died and was not restarted, all pending schedules will run after it comes back. This may be mid-day but a restart command for a server was queued at the morning, which will be executed mid-day.
This should be "undoable".Like, my schedule runs next morning, i'll skip this, the schedule runs to the next time it should run. But i should be able to undo my decision and let it run tomorrow.

2) Cancel a already processing schedule. If a schedule is already being processed but the worker died while processing and comes back mid-day, the same happens as above, so cancelling a current processing schedule would be neat.

**Describe alternatives you've considered**
I personally dont know how the whole scheduling works, so not alternatives considered there.
Its totally fine for me if there is a manual way to do it, like, doint a REDIS-Update or an database update.
Everything is fine by me as long as its not restarting my customers rust servers mid-day if the worker died and i had to restart it :D 

**Additional context**
No additional context.

**Comment by DaneEveritt** [comment]
The worker dying should be something that gets restarted immediately by `systemd`, and not left hanging. That sounds more like a system configuration issue. Additionally, you'd have to know to go into the schedules and fiddle with their pending status _before_ restarting, which is untenable on a large scale.
