### ISSUE TITLE
Mumble Egg Certificate Permissions Issue

### ISSUE THREAD

**Issue by HidYn** [pterodactyl/panel#3213]
**Background (please complete the following information):**
* Panel or Daemon:  1.3.1
* Version of Panel/Daemon:  1.3.1
* Server's OS: CentOS7
* Your Computer's OS & Browser:  Windows 10 / Firefox

**Describe the bug**
Mumble appears to have issues reading LetsEncrypt certificates directly from the container or from mount points. I have seen this mentioned on the Discord a while back and I'm experiencing it myself.

**To Reproduce**
1. Generate a LetsEncrypt certificate for you domain eg. mumble.example.com and try and apply the certificates in the mumble.ini file. 
2. Server will now fail to start due to being unable to read the certificates.

**Expected behavior**
Server would start and be protected via and SSL certificate.

Apologies - I logged this in the community eggs repo originally as I didn't notice it was a core egg.

In terms of research maybe the below threads will help.
https://github.com/mumble-voip/mumble/issues/1949#issuecomment-189831316
https://github.com/mumble-voip/mumble/issues/3297

**Comment by DaneEveritt** [comment]
Please provide the relevant error logs (specifically from Mumble itself).

**Comment by HidYn** [comment]
![Mumble Error](https://user-images.githubusercontent.com/31063223/112173389-6dc3f180-8bed-11eb-91f7-4ab076c77cdd.jpg)

Thanks for the swift reply. This is the only error I get which from reading on the Mumble github and their Wiki always seems to point to permission issues like in the 2 links I shared.

Not sure if this helps too - https://www.georglutz.de/blog/2021/01/17/how-to-fix-mumble-server-startup-with-letsencrypt-certificates-on-ubuntu/

Looks like Mumble can only read certificates if it's running as root user.

Edit: Just had a Mumble developer confirm on their matrix chat "The Murmur user has to be the owner of the files" I assume this is instead of being root.  I have tried 777 perms but still the same issue.

**Comment by DaneEveritt** [comment]
Not really sure how we're supposed to fix this seeing as it is just doing what Docker does by default with mounts. You won't be able to run a root, that is specifically denied within the container.

Your best bet is just manually uploading the certificates to the server itself though SFTP/the web and using that path.

**Comment by HidYn** [comment]
I did upload manually to the container and it still can't read them. I tried that before opening the issue.

**Comment by DaneEveritt** [comment]
> Looks like Mumble can only read certificates if it's running as root user.

There is no ability for a game server to run as root in Pterodactyl and I have no intention of adding that ability. If the files are owned correctly by the server user there is no reason Mumble should not be able to read them. If you're uploading them through the file manager and Mumble still cannot read them there is really nothing I can do about that, sounds more like an issue with their system.

**Comment by HidYn** [comment]
Yeah the Mumble developers said the files must be owned by the Murmur user so no idea how we can sort that.

No problem thanks for taking your time to look at the ticket. Keep up the good work.

**Comment by TjeuKayim** [comment]
> Your best bet is just manually uploading the certificates to the server itself though SFTP/the web and using that path.
> I did upload manually to the container and it still can't read them.

In the screenshot it seems like you specified the wrong path. Have you tried something like this?

```ini
# murmur.ini
sslCert=/home/container/certificates/fullchain.pem
# instead of
sslCert=/certificates/fullchain.pem
```

This configuration works for me, so I think you just have to prefix the path with `/home/container` to resolve the issue.

![image](https://user-images.githubusercontent.com/15987676/112754837-42227c00-8fde-11eb-9d5b-44ba4201ef6f.png)
