### ISSUE TITLE
Error when transfering a server to another node

### ISSUE THREAD

**Issue by Kriiiiiiiz** [pterodactyl/panel#3214]
**Background:**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.2.3
* Server's OS: Ubuntu Server 20.04
* Your Computer's OS & Browser: Mac OS Big Sur - Safari

**Describe the bug**
It hapens when i try to transfer a server to another node. Im ussing cloudflares certs with acme.sh. (Dont know if this matters.)

**To Reproduce**
1. Go to 'server name'
2. Click on 'manage'
3. Click on 'Transfer Server'
4. Select node and allocation
5. Error happens

**Expected behavior**
It should succesfully transfer the server to the new node,

![screenshot_ptero](https://user-images.githubusercontent.com/13300613/112149638-7a414d80-8bdf-11eb-9637-c5341aa21d52.png)

**Comment by matthewpi** [comment]
Read the bottom two log lines.

**Comment by Kriiiiiiiz** [comment]
> Read the bottom two log lines.

I know, but it was not transferred :(

**Comment by Kriiiiiiiz** [comment]
> Read the bottom two log lines.

I know, but it was not transferred :( @matthewpi
