### ISSUE TITLE
Server 500 error when deleting a server that is using a database

### ISSUE THREAD

**Issue by joker-119** [pterodactyl/panel#3215]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: fedora 33 Chrome

**Describe the bug**
When you try to delete a server that is using a database, the server files are correctly deleted, however the server remains in the pterodactyl database, and the deletion returns a server 500 error.

The only way I found to proceed from here, is to manually delete the link between the server and the database in the databases table, and then manually delete the server entry from the servers table (as even after removing the database link, you will still get a server 500 error because the server files no longer exist). 

Attempting to delete the server, or removing it from the database, prior to removing it's databases table entry, returns an SQL error: 
#1451 Cannot delete or update a parent row: a foreign key constraint fails

If you remove the database from the server first, then delete it, this doesn't occur.

PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

**To Reproduce**
1. Create a server
2. Add a database to the server
3. Attempt to delete the server, either via the panel interface, or the WHMCS module
4. Witness a Server-500 error

**Expected behavior**
The panel recognizes that the server has a database assigned to it, and deletes that and deletes it's entry in the databases table, before attempting to remove the server's entry from the servers table, then removes the server from the servers table correctly.

**Comment by trenutoo** [comment]
I created a server, attached five databases, and deleted the server without any issues. Your database constraint error should have more to it, which you've left out of the report

**Comment by NietThijmen** [comment]
did you use forcibly delete this server or not? @galaxy119

**Comment by joker-119** [comment]
It was not a forced deletion, no, but I did attempt to do so after the initial server 500 error, and it still simply resulted in the error.
This is the MySQL error that I ran into:

#1451 - Cannot delete or update a parent row: a foreign key constraint fails (`pterodactyl`.`databases`, CONSTRAINT `databases_server_id_foreign` FOREIGN KEY (`server_id_ REFERENCES `servers`)`id`))

**Comment by DaneEveritt** [comment]
Please include the _full_ stack trace, the error alone is really not super useful to most people.

**Comment by DaneEveritt** [comment]
I cannot reproduce this, and based on the error details provided it looks like something is messed up in your database and not properly deleting references when the server itself is deleted.
