### ISSUE TITLE
UI/UX Logout button.

### ISSUE THREAD

**Issue by dragon2611** [pterodactyl/panel#3217]
**Is your feature request related to a problem?

Partly just me being an idiot but on several occasions I've hit the logout button by mistake when wanting to exit from a screen 
(E.g a the server console)

**Describe the solution you'd like**
A confirmation message when clicking the button to confirm logout

**Describe alternatives you've considered**
Changing the icon for the logout button so it doesn't look like a door/exit arrow which I at least have mistaken for exist back to the main screen on more than one occasion.

**Comment by trenutoo** [comment]
It's a sign-out icon which is pretty much the standard for logging out icons. You can click on your page title in the left top corner for a quick way back into the client view

**Comment by dragon2611** [comment]
In the admin panel it actually brings up a tooltip saying logout, seems however in the non-admin areas it doesn't

**Comment by FoksVHox** [comment]
Well a solution to it, could be adding a SweetAlert2-popup asking if you're sure that you want to log out?

**Comment by DaneEveritt** [comment]
I can't think of any other major website that does this.

**Comment by NickEvansDev** [comment]
> I can't think of any other major website that does this.

<img width="300" alt="Screenshot 2021-03-24 at 00 06 51" src="https://user-images.githubusercontent.com/19759929/112234655-e4d0a880-8c34-11eb-8ab1-845712b46d08.png">
<img width="300" alt="Screenshot 2021-03-24 at 00 06 42" src="https://user-images.githubusercontent.com/19759929/112234658-e601d580-8c34-11eb-901b-d051c7799859.png">
<img width="300" alt="Screenshot 2021-03-24 at 00 06 35" src="https://user-images.githubusercontent.com/19759929/112234660-e69a6c00-8c34-11eb-9d91-9847e1a0c5d2.png">
