### ISSUE TITLE
Suggestion - Add Rate Limit on the panel console

### ISSUE THREAD

**Issue by IlPicasso** [Pterodactyl/Panel#322]
There is this useful option to skip lines when it goes over the rate limit

For example multicraft does this

Skipped 58 lines due to rate limit (30/s)

It is something that would be helpful

**Comment by schrej** [comment]
We have that already, it's throttling the output and shows a warning while it's throttled. Will be even better with 0.6.0.

**Comment by IlPicasso** [comment]
Oh! I guess it will be better on 0.6 because right now , there is a server I have which is making my web browser to crash because of the output of the console 

I can confirm there is warning , but haven't seen anything else yet on 0.5.7

**Comment by DaneEveritt** [comment]
If you're on 0.5.7 and its crashing your browser that is concerning. You can try fiddling with [these](https://github.com/Pterodactyl/Panel/blob/release/v0.5.7/.env.example#L8) arguments to tweak it.

`CONSOLE_PUSH_FREQ` is the time in ms between pushes and `CONSOLE_PUSH_COUNT` is the number of lines pushed each cycle.

**Comment by DaneEveritt** [comment]
This is most likely entirely fixed in 0.6.0 as the method used to send to console was adjusted.
