### ISSUE TITLE
S3 backups don't get deleted at all

### ISSUE THREAD

**Issue by dennisrijsdijk** [pterodactyl/panel#3221]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.1
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10, Opera GX (browser independent issue)

**Describe the bug**
On S3 backups, backups aren't deleted from the remote, even if you delete the backups through panel, the backups get rotated out due to scheduled backups, or the server gets deleted (I am aware of #2564)

**To Reproduce**
1. Set up S3 backups
2. set an automatic backup schedule on a server
3. log into your backups provider
4. see high disk usage due to many backups that are not deleted

**Expected behavior**
Once a backup is no longer visible on the panel (eg. backup deleted, overwritten by automatic backup, or server deletion) it should be removed from S3 to conserve filesize.

**Comment by hwalker928** [comment]
I am experiencing the same issue.

**Comment by DaneEveritt** [comment]
I cannot reproduce this issue when manually deleting a backup through the Panel. It is properly removed from within the S3 bucket. Do you have versioning or something enabled that prevents objects from being removed?

**Comment by elinarbur** [comment]
I have the same issue on S3, versioning is disabled but the backup is not deleted.
