### ISSUE TITLE
Infinity loading circle on servers panel homepage

### ISSUE THREAD

**Issue by Wepwawetcode** [pterodactyl/panel#3223]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installing this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel 
* Version of Panel/Daemon: 1.3.2
* Server's OS: UBUNTU 20.04
* Your Computer's OS & Browser: Windows & Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use). 
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

**To Reproduce**
1. Go to 'Your Panel on the webbrowser '
2. Open the browser console(Usually F12)
3. Try to view your server status from the server list
4. See errors in the console (Infinity Loading Circle)

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

What I expect to happen is that I can view the server usage.

**Comment by james090500** [comment]
More in depth issue in #3224

**Comment by TASelwyn** [comment]
Can confirm this issue persists.
I'm on php7.4.16

**Comment by gOOvER** [comment]
I can't confirm. Works all as it should. No error in Console and no Infinity loading circle. Tested with Chrome, Edge and Firefox

**Comment by gOOvER** [comment]
duplicate #3224

**Comment by TASelwyn** [comment]
> duplicate #3224

3223 was posted before 3224

Also, the error seems to happen with cache_driver set to file.. Using redis fixes it.

**Comment by gOOvER** [comment]
> > duplicate #3224
> 
> 3223 was posted before 3224
> 
> Also, the error seems to happen with cache_driver set to file.. Using redis fixes it.

But #3224 have more detailed informations then #3223 ;) I bet #3223 is the same as #3224 ;)

**Comment by XTechLabs** [comment]
I can confirm switching CACHE_DRIVER=file to CACHE_DRIVER=redis in .env fix the problem.
