### ISSUE TITLE
detected server as entering a crashed state

### ISSUE THREAD

**Issue by ryrzy** [pterodactyl/panel#3227]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installing this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: 1.3.2 (1.3.1 to)
* Version of Panel/Daemon: 1.3.2 (1.3.1 to)
* Server's OS: Debian 10
* Your Computer's OS & Browser: win10 chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
I have had few time a false positive "detected server as entering a crashed state; running crash handler server=" of 2 rust servers, servers was working ok, no lags, players on server and suddenly it has restarted. Few days ago:

```
Mar 25 10:17:19 nxxxxxwings[16008]:  INFO: [Mar 25 10:17:19.370] detected server as entering a crashed state; running crash handler server=f13xxx-xxx6-xxc-bxxxa-xxcxxxx

Mar 25 12:15:31 nxxxxx wings[16008]:  INFO: [Mar 25 12:15:31.285] detected server as entering a crashed state; running crash handler server=b5xxxxx7-xxxx5-xxxxe-xxxxe-5xxxxxx5
```

and today (before update panel/wings and after to)
```
 INFO: [Mar 27 05:41:03.749] detected server as entering a crashed state; running crash handler server=b5x-xxxx-xxxx-xxxx-yyyyyyyyy

 INFO: [Mar 27 08:10:23.961] detected server as entering a crashed state; running crash handler server=b5xxx-xxxx-xxxx-xxxx-5xxx95
```
in game logs there are no errors, nothing, suddenly restart...

after todays restart on 5:41 i've got a 10GB file named 'core' in game directory like on ss.

php version:
`PHP 8.0.3 (cli) (built: Mar  5 2021 08:38:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
`
kernel:
`Linux n42c35c 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux`

docker info:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 8
  Running: 7
  Paused: 0
  Stopped: 1
 Images: 5
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-5-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.93GiB
 Name: xxxxx
 ID: ER7F:xxxxxxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**To Reproduce**

don't know how to reproduce this, it's random.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
![core](https://user-images.githubusercontent.com/2003973/112713658-b3770780-8ed6-11eb-9315-ab1c5a3bc3bd.png)

**Comment by DaneEveritt** [comment]
> after todays restart on 5:41 i've got a 10GB file named 'core' in game directory like on ss.

Then your game crashed and core dumped, this is working as intended.
