### ISSUE TITLE
Automatic Purge Backup

### ISSUE THREAD

**Issue by NotYusta** [pterodactyl/panel#3228]
**Is your feature request related to a problem? Please describe.**
Old backup should be purged automatically to free spaces.

**Describe the solution you'd like**
Make a configurable backup purge schedule that is older than * days / month.

**Comment by DaneEveritt** [comment]
Please include more information about what you're requesting, I can put two and two together here but it is very vague. It basically is just saying "make this very broad feature but I'm not going to say what specifically I would like out of it or what problem I'm trying to solve.".

**Comment by broimsuperman** [comment]
> Please include more information about what you're requesting, I can put two and two together here but it is very vague. It basically is just saying "make this very broad feature but I'm not going to say what specifically I would like out of it or what problem I'm trying to solve.".

I am assuming he means that backups should automatically be purged upon time input, like every month, day, hour, minute, etc..... you know. Old backups should be deleted if space is reaching critical points. I'd suggest making this editable in the admin menu and also editable for the server owner/admins.

**Comment by DaneEveritt** [comment]
No response from author.

**Comment by NotYusta** [comment]
> 
> 
> > Please include more information about what you're requesting, I can put two and two together here but it is very vague. It basically is just saying "make this very broad feature but I'm not going to say what specifically I would like out of it or what problem I'm trying to solve.".
> 
> I am assuming he means that backups should automatically be purged upon time input, like every month, day, hour, minute, etc..... you know. Old backups should be deleted if space is reaching critical points. I'd suggest making this editable in the admin menu and also editable for the server owner/admins.

yeah that's what i meant
