### ISSUE TITLE
Migration store_node_tokens_as_encrypted_value fails: savepoint does not exist

### ISSUE THREAD

**Issue by tari** [pterodactyl/panel#3229]
**Background (please complete the following information):**
* Panel or Daemon: panel
* Version of Panel/Daemon: 1.3.1 (`ghcr.io/pterodactyl/panel:v1.3.1`)
* Server's OS: Linux
* Your Computer's OS & Browser: n/a

**Describe the bug**

As noted in #1959, the `2020_04_10_141024_store_node_tokens_as_encrypted_value` migration can sometimes fail with an error `SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT trans2 does not exist`. However, that bug was closed without any resolution.

I've encountered the `SAVEPOINT trans2 does not exist` issue again, and believe this is caused by attempting to use an explicit transaction while inside the implicit transaction of a migration that does DDL, because DDL statements cause implicit commit.

To illustrate the issue, I can reproduce a similar problem manually. Using an empty database on MariaDB 10.3:

```sql
> CREATE TABLE table1 (id int);
> BEGIN;
> ALTER TABLE table1 ADD COLUMN (value int);
> SAVEPOINT trans2;
> INSERT INTO table1(id, value) VALUES (1, 1);
> RELEASE SAVEPOINT trans2;
ERROR 1305 (42000): SAVEPOINT trans2 does not exist
```

This follows what the migration in question does, where it is wrapped in a transaction implicitly, does some DDL, then creates a savepoint that silently fails to be created because [executing DDL caused an implicit commit](https://mariadb.com/kb/en/sql-statements-that-cause-an-implicit-commit/). Attempting to release that savepoint then causes the visible error. Once it's in this state, attempting to roll back the migration also fails because it was recorded as complete but never finished, so the rollback fails to drop the `nodes_daemonsecret_unique` index because it was never created.

The issue could be fixed in a few ways:
 * Remove the explicit `DB::Transaction` from the migration. Minimal change but still has issues with being impossible to roll back in case of error while running, due to implicit commit.
 * Split into two or three migrations: one for the initial DDL, one to run the `UPDATE`s, and optionally one to do the index updates (which could be part of the update one, but then still has potentially problematic implicit commits).

As for why this isn't a common error that people see, I suspect it may be down to the database engine or settings often being such that this error isn't reported- possibly related to `STRICT_TRANS_TABLES` mode or lack of support for transactions in the current engine (MyISAM..).

**Comment by mason-rogers** [comment]
I'd first suggest to upgrade to v1.3.2 (panel & wings)

**Comment by tari** [comment]
As this migration is unchanged between 1.3.1 and 1.3.2, I expect that to make no difference.

For completeness, I dropped the database and tried 1.3.2, observing no difference.

**Comment by tari** [comment]
I tried with MariaDB 10.2-10.5 and every version exhibits the same issue (given the default configuration or the official docker image). This is consistent with [the documentation](https://mariadb.com/kb/en/savepoint/):

> If SAVEPOINT is issued and no transaction was started, no error is reported but no savepoint is created. When ROLLBACK TO SAVEPOINT or RELEASE SAVEPOINT is called for a savepoint that does not exist, an error like this is issued:

While MySQL doesn't document this behavior, MySQL 8 does the same thing. I'm unsure how this migration has ever worked.
