### ISSUE TITLE
Wings rebuild

### ISSUE THREAD

**Issue by kiozix** [pterodactyl/panel#3232]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.3
* Server's OS: Ubuntu | 18.04
* Your Computer's OS & Browser: windows/Chrome

**Describe the bug**
hello I tried to rebuild wings but I came across this message

`root@game01:/usr/local/bin/new# go build
wings.go:4:2: cannot find package "github.com/pterodactyl/wings/cmd" in any of:
        /usr/lib/go-1.10/src/github.com/pterodactyl/wings/cmd (from $GOROOT)
        /root/go/src/github.com/pterodactyl/wings/cmd (from $GOPATH)`

`Linux game01 4.15.0-137-generic #141-Ubuntu SMP Fri Feb 19 13:46:27 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
`root@game01:/usr/local/bin/new# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-137-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.39GiB
 Name: game01
 ID: T5L6:TGM7:OQMX:5AOH:OZIS:7M3U:YOS3:HKAE:TGOF:RAXA:L5CE:PBKI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`

**To Reproduce**
1. new folder 
2. download wings from github
3. use go build

**Comment by matthewpi** [comment]
Wings requires go1.14 to build, while you are using go1.10 to build it.

**Comment by kiozix** [comment]
Ok update this page https://pterodactyl.io/community/customization/wings.html#build-requirements

**Comment by DaneEveritt** [comment]
https://pterodactyl.io/community/customization/wings.html#build-requirements literally links to https://github.com/pterodactyl/wings/blob/develop/go.mod#L3
