### ISSUE TITLE
Server Transfer doesn´t work

### ISSUE THREAD

**Issue by Phyroks** [pterodactyl/panel#3233]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.2
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows/Chrome

**Describe the bug**
I´ve started a server Transfer hours Ago. The Server is 9 GB big. And after more than 4 hours nothing happens
**To Reproduce**
1. Go to 'Servers'
2. Click on 'Manage'
3. Press Transfer
4. Wait

**Expected behavior**
I thought he would transfer it in about half an hour but nothing happened after 4 hours.

**Comment by parkervcp** [comment]
What kind of server? Have any logs? This is lacking any usable information.

**Comment by Phyroks** [comment]
I have found nothing in the logs on the subject of transfer. It is a tuinity server.

**Comment by Phyroks** [comment]
Logs of the Current Server: https://ptero.co/iluhipafut
Logs of the target server: https://ptero.co/uloqitubaf

**Comment by MackenzieMolloy** [comment]
Have you tried removing the CPU pinning associated server you wish to transfer?

> Stacktrace:
> Error response from daemon: Requested CPUs are not available - requested 0,1,2,3,4,5,6,7,8,9,10,11, available: 0-5

Also - what is the container ID of the server you are wanting to transfer?

**Comment by DaneEveritt** [comment]
Closing this issue, your error is above.
