### ISSUE TITLE
DigitalOcean One-Click app

### ISSUE THREAD

**Issue by iSaluki** [pterodactyl/panel#3235]
This is really simple and exactly as it sounds, having a One-Click app on the DigitalOcean marketplace would be super helpful.

**Comment by parkervcp** [comment]
Please fill out the template for this.

**Comment by iSaluki** [comment]
**Is your feature request related to a problem? Please describe.**

Faster installation, less chance of failure or install issues and a better way to quickly spin pterodactyl up.


**Describe the solution you'd like**
A one-click Pterodactyl app submitted to DigitalOcean.

**Describe alternatives you've considered**

Install scripts.

**Additional context**
Not relevant.

**Comment by DaneEveritt** [comment]
Someone can PR something for this if they want, but otherwise I'm not putting any effort into that.

**Comment by iSaluki** [comment]
This wouldn't require any additional code, it would just require someone to setup a VM running Pterodactyl. 

See this for reference: https://marketplace.digitalocean.com/vendors

![image](https://user-images.githubusercontent.com/37915796/113022756-d9bdd100-917c-11eb-86fb-afec6b314fa1.png)

**Comment by NickEvansDev** [comment]
> This wouldn't require any additional code, it would just require someone to setup a VM running Pterodactyl.
> 
> See this for reference: https://marketplace.digitalocean.com/vendors

@iSaluki "require someone to setup a VM" **every time** there is an update

**Comment by iSaluki** [comment]
> > This wouldn't require any additional code, it would just require someone to setup a VM running Pterodactyl.
> > 
> > See this for reference: https://marketplace.digitalocean.com/vendors
> 
> @iSaluki "require someone to setup a VM" **every time** there is an update
> 

You don't have to keep it exactly in sync with releases. A lot of organisations just release an update to the image during major updates, so it would only require a VM image to be provisioned and then updated once every few months. It really wouldn't be too much effort.

**Comment by NickEvansDev** [comment]
> > > This wouldn't require any additional code, it would just require someone to setup a VM running Pterodactyl.
> > > See this for reference: https://marketplace.digitalocean.com/vendors
> > 
> > 
> > @iSaluki "require someone to setup a VM" **every time** there is an update
> 
> You don't have to keep it exactly in sync with releases. A lot of organisations just release an update to the image during major updates, so it would only require a VM image to be provisioned and then updated once every few months. It really wouldn't be too much effort.

if it's not updated with every new release, lots of people will ask

**Comment by iSaluki** [comment]
> > > > This wouldn't require any additional code, it would just require someone to setup a VM running Pterodactyl.
> > > > See this for reference: https://marketplace.digitalocean.com/vendors
> > > 
> > > 
> > > @iSaluki "require someone to setup a VM" **every time** there is an update
> > 
> > You don't have to keep it exactly in sync with releases. A lot of organisations just release an update to the image during major updates, so it would only require a VM image to be provisioned and then updated once every few months. It really wouldn't be too much effort.
> 
> if it's not updated with every new release, lots of people will ask

Well they might, but it would provide a better way to quickly install Pterodactyl as a development environment, and would also allow people to run a node with much less setup, which would attract a lot more people.

**Comment by DaneEveritt** [comment]
Again, someone can set it up on their own if they want, but I'm not handling it.

**Comment by iSaluki** [comment]
I'm not sure if I can do it without being properly affiliated with the organisation making the software.

**Comment by FoksVHox** [comment]
It's open-source, so yes you can do it

**Comment by iSaluki** [comment]
Okay, I'll definitely look into this then

**Comment by FoksVHox** [comment]
If you read the license of Pterodactyl, you'd know that you're allowed to do what you want
