### ISSUE TITLE
Unable to create / update a user, And login with the user!

### ISSUE THREAD

**Issue by H4RDY-DEV** [pterodactyl/panel#3236]
Hey! So I created a user or update a user. I then go to login (well the account owner) and it states **No account matching those credentials could be found.** 
As shown below
![image](https://user-images.githubusercontent.com/80357856/113007333-09191180-916e-11eb-82b5-dd5e01ec82c0.png)
I checked chromes console and encountered these errors.
![image](https://user-images.githubusercontent.com/80357856/113007460-24841c80-916e-11eb-8d91-8712fa0aa90b.png)
I'm fairly new to pterodactyl so I'm not quite sure whats wrong etc,

Thank you for your support!

**Comment by parkervcp** [comment]
Please fill out the issue template.

**Comment by H4RDY-DEV** [comment]
> Please fill out the issue template.

No problem!

**Comment by H4RDY-DEV** [comment]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.2
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows / Google Chrome

**Describe the bug**
Unable to log into the panel when creating a new user, Or updating a current one!
Please provide additional information too, depending on what you have issues with:
Panel: 8.0.3

**To Reproduce**
Steps to reproduce the behavior:
1. Go to the panel, and go to the users section.
2. Click on create new user, and fill out details. Once you have done this save the details!
3. If you now log out of your current account and attempt to log into the new user created

**Expected behavior**
You should be able to login to the panel etc.

**Comment by H4RDY-DEV** [comment]
Any suggestions on how to fix this error, As it's annoying due to me not being able to get to my discord bot.

**Comment by Mansffer** [comment]
> ![imagem](https://user-images.githubusercontent.com/80357856/113007333-09191180-916e-11eb-82b5-dd5e01ec82c0.png)
> 

I'm also having this error...
Any idea how to solve it?

**Comment by alexgn100** [comment]
What is the output of storage/logs/DATE.log ?

**Comment by Mansffer** [comment]
> What is the output of storage/logs/DATE.log ?

https://github.com/Mansffer/error_logs/blob/main/laravel-2021-04-01.log

The error in MySQL and sftp seems strange to me since they were configured correctly, maybe I will reinstall Pterodactyl again.

**Comment by Mansffer** [comment]
> 
> maybe I will reinstall Pterodactyl again.
>
After reinstalling the entire panel again things went back to normal :)

**Comment by DaneEveritt** [comment]
If this was actually broken there would be far more people having issues. It honestly sounds like you have something setup wrong, or are legitimately entering the wrong credentials. I'm closing this since there are no logs or any confirmation of it being anything other than a user issue.

**Comment by Miniontoby** [comment]
Uhmm, Hi

Since idk a week ago I am unable to login on pterodactyl panels that use Cloudflare. Logging in tells me "No account matching those credentials could be found."

I have tried 4 different ones, the first 3 are behind Cloudflare and didn't work. The 4th one is not behind Cloudflare and that one actually DID work!

So idk if this issue is the correct place for my comment, but yeah it is related because the same error message.

It might just be a coincidence, but I just don't understand why I am unable to login. 

- Miniontoby

**Comment by DefomCode** [comment]
same problem
