### ISSUE TITLE
[Suggestion] Add a warning about running Minecraft images that requires compiling on low memory containers

### ISSUE THREAD

**Issue by beschio** [Pterodactyl/Panel#324]
I'm not sure if this should be a Panel or Daemon issue. Minecraft images where the user doesn't supply a jarfile download link has to be decompiled, patched and recompiled. This takes quite a bit of memory so a warning could save some less savvy users from headaches related to running out of memory.

Let me know what you think!

**Comment by DaneEveritt** [comment]
This is fixed by service packs allowing pre-configured files to be deployed.
