### ISSUE TITLE
panel report wrong ram when i upgraded from 1.0 to 1.3.2

### ISSUE THREAD

**Issue by DicoSky** [pterodactyl/panel#3247]
**Background:**
* Panel or Daemon                         : **Uncertain**
* Version of Panel/Daemon            : **1.3.2/1.3.2**
* Server's OS                                   : **Linux (ubuntu 20.04)**
* Your Computer's OS & Browser   : **Windows 10/opera**

**Describe the bug**
The panel currently shows incorrect RAM usage for servers.

**htop stats**
![wrong ram](https://user-images.githubusercontent.com/32613334/113521041-e3857100-958e-11eb-8289-e59fe497098c.png)

this happened when i upgraded from v1.0 to v1.3.2.

**Comment by NickEvansDev** [comment]
what does it say in the "mem usage" column of the command "docker stats --no-stream"

**Comment by parkervcp** [comment]
There can be a difference between what the server is using and what is cached for it as well from docker.

**Comment by DaneEveritt** [comment]
Closing unless other information can be provided to prove this is indeed incorrect. We read from Docker, so if that is wrong you've found a bug in Docker and can take it up with them.

**Comment by DicoSky** [comment]
> docker stats --no-stream

![mem](https://user-images.githubusercontent.com/32613334/113653505-de5b1b80-968d-11eb-9d0e-38060ed5585e.png)

**Comment by DicoSky** [comment]
> There can be a difference between what the server is using and what is cached for it as well from docker.

this is happened just when i changed the panel/wings version

**Comment by DicoSky** [comment]
any help about this problem ?

**Comment by parkervcp** [comment]
> any help about this problem ?

It's not a problem. What you are thinking the process is using is incorrect. The cached ram on top of actual in-use ram is what docker is reporting
