### ISSUE TITLE
Schedules not automatically completing

### ISSUE THREAD

**Issue by Skizzles** [pterodactyl/panel#3248]
**Background (please complete the following information):**
* Panel or Daemon: Both?
* Version of Panel/Daemon: 1.3.2
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Windows 10 Google Chrome

**Describe the bug**
My automated restart schedules are not completing, they get stuck in processing after completing the first task in the schedule.
Panel: 7.4.15
Daemon: Linux 5.4.0-48-generic

**To Reproduce**
1. Go to Schedules
2. Click on Schedule
3. Attempt to run the Schedule
4. Notice how first task runs
5. No further tasks run

**Expected behavior**
I expect the schedule to run all tasks please see video below:

https://screenshots.skizzles.me/wAnA3/zEgULOri38.mp4/raw

**Comment by notAreYouScared** [comment]
What's the status of the pteroq service?

**Comment by Skizzles** [comment]
https://screenshots.skizzles.me/wAnA3/yaGUDOhO47.png

Active and running, just updated to latest wings earlier so. issues still present.

**Comment by DaneEveritt** [comment]
Please provide error logs from the Panel at the time the schedule is running.

**Comment by bmearnhardt** [comment]
I'm having a similar issue. Mine is only set to run a backup at 4 AM everyday and never completes. Just says "Processing". I'll try to get some logs collected from it.

**Comment by iOshawott** [comment]
got same issue! How to turn back my panel to 1.3.1? :( I need it so much

**Comment by iOshawott** [comment]
I got rid of this issue typing this
```
cd /var/www/pterodactyl
php artisan queue:restart
```
AGAIN after upgrade, cuz first time doing it was glitchy. Weird, but seems fixed for me at this moment

**Comment by bmearnhardt** [comment]
> 
> 
> I got rid of this issue typing this
> 
> ```
> cd /var/www/pterodactyl
> php artisan queue:restart
> ```
> 
> AGAIN after upgrade, cuz first time doing it was glitchy. Weird, but seems fixed for me at this moment

This worked for me. The ones that were "Processing" completed instantly. Also got a couple of emails from a server that I had started days ago. I'll have to wait and see if it is still working when the next scheduled backup at 4AM runs.
