### ISSUE TITLE
FiveM keeps on Crashing Exit Code: 134

### ISSUE THREAD

**Issue by NexCodeJimM** [pterodactyl/panel#3249]
**Background (please complete the following information):**
* Panel or Daemon:  Pterodactyl Panel
* Version of Panel/Daemon: 1.3.2
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows Google Chrome

The server keeps on crashing. Below the is log before the crash. I'm trying to run a personal FiveM server with txAdmin enabled using the FiveM egg provided by parkervcp. It keeps saying Exit code: 134 but I do not really know what that means. Hopefully, someone can help me with this :/

Build tasks completed - starting resource webpack.
Creating script environments for webpack
Running build tasks on resource chat - it'll restart once completed.
Started resource webpack
server thread hitch warning: timer interval of 168 milliseconds
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[21]: ../../../../vendor/node/src/env-inl.h:408:void node::Environment::DecreaseWaitingRequestCounter(): Assertion `(request_waiting_) >= (0)' failed.
Stacktrace:

/proc/self/maps:
40021000-40031000 rwxp 00000000 00:00 0 
413a9000-413d9000 rwxp 00000000 00:00 0 
5908140000-5908180000 ---p 00000000 00:00 0 
6166340000-6166380000 rw-p 00000000 00:00 0 
79b8e40000-79b8e80000 rw-p 00000000 00:00 0 
bd52dc0000-bd52e00000 ---p 00000000 00:00 0 
1f0d7bc0000-1f0d7c00000 rw-p 00000000 00:00 0 
1f70c080000-1f70c0c0000 ---p 00000000 00:00 0 
2d5f5900000-2d5f5940000 ---p 00000000 00:00 0 
2e718a80000-2e718ac0000 ---p 00000000 00:00 0 
34d54000000-34d54040000 rw-p 00000000 00:00 0 
382f0500000-382f0540000 rw-p 00000000 00:00 0 
3be44a00000-3be44a40000 rw-p 00000000 00:00 0 
3d7cdbc0000-3d7cdbc1000 rw-p 00000000 00:00 0 
3f2adf40000-3f2adf80000 ---p 00000000 00:00 0 
4056ce40000-4056ce80000 rw-p 00000000 00:00 0 
51dbe780000-51dbe7c0000 ---p 00000000 00:00 0 
55849180000-558491c0000 ---p 00000000 00:00 0 
55f86f00000-55f86f85000 rw-p 00000000 00:00 0 
569df300000-569df340000 ---p 00000000 00:00 0 
57c45440000-57c45480000 rw-p 00000000 00:00 0 
5fa40b00000-5fa40b40000 ---p 00000000 00:00 0 
5fc7c200000-5fc7c240000 rw-p 00000000 00:00 0 
64fd6980000-64fd69c0000 rw-p 00000000 00:00 0 
68a66a00000-68a66a40000 rw-p 00000000 00:00 0 
Memory around native instruction pointer (0x7fc98531d3b2):
0x7fc98531d3a2  00 00 b8 0e 00 00 00 31 d2 bf 02 00 00 00 0f 05  .......1........
0x7fc98531d3b2  c3 48 63 ff 50 b8 24 00 00 00 0f 05 48 89 c7 e8  .Hc.P.$.....H...
0x7fc98531d3c2  47 89 fd ff 5a c3 48 63 ff 50 48 63 f6 b8 3e 00  G...Z.Hc.PHc..>.
0x7fc98531d3d2  00 00 0f 05 48 89 c7 e8 2f 89 fd ff 5a c3 85 ff  ....H.../...Z...

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

/entrypoint.sh: line 12:    21 Aborted                 (core dumped) $(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 134
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by parkervcp** [comment]
This is an egg issue and not the panel.
