### ISSUE TITLE
Database specify nodes / locations

### ISSUE THREAD

**Issue by JakeySuccessor** [pterodactyl/panel#3250]
**Is your feature request related to a problem? Please describe.**
Yes, If I have a server in asia it will create a database randomly when I have NA / EU / & ASIA databases set

**Describe the solution you'd like**
Make it so we can specify which locations use which databases and if we can choose multiple locations

**Describe alternatives you've considered**
An option to create databases or set them to specific nodes / locations

**Additional context**
I don't think there is any additional context needed

**Comment by matthewpi** [comment]
This is very close to https://github.com/pterodactyl/panel/issues/1980 except it doesn't give the user an option.
