### ISSUE TITLE
Error 403 API

### ISSUE THREAD

**Issue by masterhacka** [pterodactyl/panel#3251]
I am trying to get acces via API. Everything is setup fine but Eroor is 403. What is wrong?

[https://i.imgur.com/rw1ALcg.png](https://i.imgur.com/rw1ALcg.png)
[https://i.imgur.com/VgYeHSK.png](https://i.imgur.com/VgYeHSK.png)

**Comment by parkervcp** [comment]
A 403 is an http forbidden. You gave the api bad information it didn't like.

**Comment by masterhacka** [comment]
But what is wrong? I took the example from here and changed the apikey and website: https://dashflo.net/docs/api/pterodactyl/v1/

Do I have to change the pterodactyl_session? Where do I get it?

**Comment by trenutoo** [comment]
Can't read the image on mobile, most of the time 403 is because you are trying to use application key on the client endpoint or client key on application endpoint. 

Pterodactyl_session is a cookie that you will get after a request has been made and is not requiredA

**Comment by masterhacka** [comment]
I am trying to get this: https://pterodactyl.file.properties/api/client/servers/1a7ce997/resources
And took an Application API key with Read & Write on all options

**Comment by trenutoo** [comment]
You can not use application key on the client endpoint. You have to generate a client token from the client view and use it instead

**Comment by masterhacka** [comment]
Okay and how can I do this? Sorry I am very new to this

**Comment by masterhacka** [comment]
Nvm I found it. Thanks for your help guys!
