### ISSUE TITLE
Add *more* site customizations. 

### ISSUE THREAD

**Issue by broimsuperman** [pterodactyl/panel#3252]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Essentially, we should be able to customize the colors, icons possibly (could use font awesome, a project that has implemented this is Flarum), and additional/addon css (again like Flarums implementation). The panel is really good don't get me wrong, but I feel the UI is just not up to the hype or what you'd expect. By allowing people to customize it, it'd make pterodactyl 100x better and probably more popular. 

Also here's some other ideas:

Custom Cursor(s)
Location of menus (like admin menu from left to right for example). 
Server icons (can be animated).
Sort by menu on the main page of the panel. 
Customizable Favicon
Customizable footer.
Backgrounds for the server buttons.

**Describe alternatives you've considered**
Theme support 👀 

**Additional context**
For the background for the server buttons I mean the large buttons on the main page of the panel. They're quite bland and not very expressive.

**Comment by DaneEveritt** [comment]
Not interested in doing any of this, sorry. With the tiny amount of free time I have to work on this I'm much more interested in shipping features rather than making it easy for someone to change the color of the Panel.

**Comment by broimsuperman** [comment]
ok :(
