### ISSUE TITLE
panel report wrong ram when i upgraded from 1.0 to 1.3.2

### ISSUE THREAD

**Issue by DicoSky** [pterodactyl/panel#3253]
**Background:**

Panel or Daemon :  **panel/deamon**
Version of Panel/Daemon :  **1.3.2/1.3.2**
Server's OS : **Linux (ubuntu 20.04)**
Your Computer's OS & Browser :  **Windows 10/opera**
Describe the bug
The panel currently shows incorrect RAM usage for servers.

**docker stats --no-stream**
![mem](https://user-images.githubusercontent.com/32613334/113960157-eea10100-981b-11eb-849f-aff7f5464ceb.png)

**Panel graphic error**
![Opera Instantané_2021-04-08_033550_panel hi-otaku com](https://user-images.githubusercontent.com/32613334/113960186-fcef1d00-981b-11eb-8221-2bf001fdaeaf.png)

htop stats
![113521041-e3857100-958e-11eb-8289-e59fe497098c](https://user-images.githubusercontent.com/32613334/113960100-d4672300-981b-11eb-8d63-77db60253316.png)

this happened just when i upgraded from v1.0 to v1.3.2. before that everything was good.

any ideas ?

**Comment by matthewpi** [comment]
#3247
