### ISSUE TITLE
Server description in admin area, about server

### ISSUE THREAD

**Issue by NoodlesDev987** [pterodactyl/panel#3254]
Add that server description will be displayed in admin => servers => some server => About 
It should be below the server name

**Comment by NoodlesDev987** [comment]
Why this was closed? 
below this field should be Server description field in admin area:
![image](https://user-images.githubusercontent.com/81709846/114140883-22118780-9911-11eb-9c1b-cb6d18530d20.png)

**Comment by trenutoo** [comment]
It was closed because you completely ignored the template which would've been pre-filled for you.
