### ISSUE TITLE
Panel design bug (startup tab, mobile) 

### ISSUE THREAD

**Issue by playaz44** [pterodactyl/panel#3255]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.2
* Server's OS: debian 10
* Your Computer's OS & Browser: android 10, chrome 89.0.4389.105

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)

Panel: PHP 8.0.3
The startup tab becomes wider than the rest of the page when you add your own parameter field when editing an egg

**To Reproduce**
1. Add your own field, nests - > I think any egg - > Variables (user can view, user can edit) input rules "required|string|max:256" 
2. Go to the server where the additional field was added 
3. Go to the "startup" tab and see what its looks on phone 
4. https://i.imgur.com/k7vPPkc.jpg

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

I'm using resolution 2240x1080 on the phone, additional parameters should be consistent with the rest of the page, after checking other servers I find that the error occurs only after adding your own parameter field when editing the egg

**Comment by tinyoverflow** [comment]
Please upload screenshots directly to GitHub.

**Comment by playaz44** [comment]
> Please upload screenshots directly to GitHub.

![k7vPPkc](https://user-images.githubusercontent.com/9553500/116683052-5ed01c00-a9af-11eb-8a4d-e3dbabe9e4ff.jpg)

**Comment by playaz44** [comment]
Fixed in panel 1.4.1
