### ISSUE TITLE
Copyright Date On User End // Small bug not urgent

### ISSUE THREAD

**Issue by JackW6809** [pterodactyl/panel#3257]
**Background (please complete the following information):**
* Panel or Daemon:  Panel
* Version of Panel/Daemon: 1.3.2
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 Pro, Chrome

**Describe the bug**
On the user end, it shows © 2015 - 2020 Pterodactyl Software when it should be © 2015 - 2021 Pterodactyl Software like it is on the admin end.

**To Reproduce**
1. Just go to the panel itself on the dashboard, it will show it. The admin end works fine.

**Expected behavior**
It should show © 2015 - 2021 Pterodactyl Software like it does in the admin end.

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/commit/a072b9c5be9c1103d7fa6a2910805f1808fd9a75
