### ISSUE TITLE
Issue with console text being blured and unreadable

### ISSUE THREAD

**Issue by Pendred** [pterodactyl/panel#3259]
Didn't feel that the template provided was applicable to this issue, so I didn't use it.

https://i.imgur.com/xxdoWYF.png

Console is unreadable and is output like that

I run Firefox, doesn't happen on any other browser that I have tested. Asked in Discord before coming here but couldn't get any help.

**Comment by parkervcp** [comment]
The template is always applicable. Please fill it out.
