### ISSUE TITLE
Please support the latest version of waterdog.

### ISSUE THREAD

**Issue by MegaTKC** [pterodactyl/panel#3260]
The latest version of waterdog is not on CodeMC anymore. It is on their Jenkins server. [Jenkins Server](https://jenkins.waterdog.dev/job/Waterdog/job/Waterdog/job/master-zlib/)

You can download Waterdog directly here:
[Click me](https://jenkins.waterdog.dev/job/Waterdog/job/Waterdog/job/master-zlib/lastSuccessfulBuild/artifact/Waterfall-Proxy/bootstrap/target/Waterdog.jar)

**Comment by victiondev** [comment]
????

**Comment by MegaTKC** [comment]
> ????

Sir the version of Waterdog is at 1.14.60. We need 1.16.220. The latest version isn't on CodeMC anymore. It is on there Jenkins server.

**Comment by victiondev** [comment]
how is this related to pterodactyl

**Comment by parkervcp** [comment]
https://github.com/parkervcp/eggs/tree/master/minecraft/proxy/cross_platform/waterdog
