### ISSUE TITLE
Re-enable username/identity changes

### ISSUE THREAD

**Issue by JasonHorkles** [pterodactyl/panel#3261]
**Is your feature request related to a problem? Please describe.**
It's not necessarily a problem, just slightly annoying at times

**Describe the solution you'd like**
Users should be able to change their usernames again. This used to be a feature in 0.7 but it seems like it's no longer a feature

**Describe alternatives you've considered**
None

**Additional context**
If it is still possible, please let me know so I can contact the host.

**Comment by tinyoverflow** [comment]
As Pterodactyl is build for large scale environments, I don't see any benefit in this feature. The usernames are mostly set by the automation system behind it.

**Comment by matthewpi** [comment]
I don't see why this is necessary, usernames are pretty pointless as we have emails (which most people should use for logins) and they only seem to add unneeded complexity.
