### ISSUE TITLE
Server status does not load on the 'My Servers' page after transfer

### ISSUE THREAD

**Issue by CharlieMaskell** [pterodactyl/panel#3263]
**Info**
- Panel: 1.3.2 (Hosted on same server as Daemon 1)
- Daemon 1 - v1.3.2
	- PHP -V: PHP 8.0.3 (cli) (built: Mar  5 2021 07:53:56) ( NTS )
	- Uname -a: Linux sv-ctxgs01 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
	- Docker info: [daemon-1-docker.txt](https://github.com/pterodactyl/panel/files/6311175/daemon-1-docker.txt)
- Daemon 2 - v1.3.2
	- Uname -a: Linux sv-ctxgs02 5.4.0-71-generic #79-Ubuntu SMP Wed Mar 24 10:56:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
	- Docker info: [daemon-2-docker.txt](https://github.com/pterodactyl/panel/files/6311183/daemon-2-docker.txt)
- Computer: Windows 10, Google Chrome

**Description/Steps to reproduce**
I recently acquired a new server to run as a pterodactyl node and have done the following:
1. Updated my panel and Daemon 1 (hosted on the same server) to v1.3.2 from v1.1.
2. I then built a new daemon (v1.3.2) and added it to the panel as a node.
3. I then transferred my existing two servers from Daemon 1 to Daemon 2.

Everything seems to have worked without issue and I can start/stop the servers so this bug (if it is a bug) is relatively minor.
However, on the 'my servers' page, all servers infinitely load their status and show as offline. If you click on the server, it will load the server and you can then see its status without any issues. 

Chrome Developer Tools show the following GET request failing:
http://<IP>/api/client/servers/a0782234-6469-4705-be49-e4d303d5e8cd/resources
`{
    "errors": [
        {
            "code": "BadMethodCallException",
            "status": "500",
            "detail": "An unexpected error was encountered while processing this request, please try again."
        }
    ]
}`

Looking at [laravel-2021-04-14.log](https://github.com/pterodactyl/panel/files/6311224/laravel-2021-04-14.log), it is spammed with the following:
`[2021-04-14 14:47:48] production.ERROR: This cache store does not support tagging. {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): This cache store does not support tagging. at /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:483)`

I have attempted to restart the daemons and the panel to see if it was just a caching issue but no avail.

**Expected Behaviour**
I'd expect that the server status is still displayed without issue after a server is transferred to a different node. I understand that the transfer is untested and has a warning about bugs, just thought this might be useful for future testing of the Transfer functionality.

Let me know if you require any further logs/detail.

Keep up the good work!

**Comment by matthewpi** [comment]
#3224
