### ISSUE TITLE
Offsite S3 backups randomly fail

### ISSUE THREAD

**Issue by ukdaaan** [pterodactyl/panel#3265]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.3.2
* Server's OS: Ubuntu 20.04.2 LTS x86_64
* Your Computer's OS & Browser: Various (Primarily Mac OS Big Sur)

**Describe the bug**

Periodically we see the following occur with our S3 offsite backups - only ever happens when scheduling and doesn't happen every time (manual backups never have the issue), maybe once or twice a day tops - some servers don't see the issue at all while another might see it 2 days on the spin.

Error from Wings 
```
created backup successfully adapter=s3 backup=cd0b9ee6-{redacted} request_id=95871077-{redacted} server=e00c07d3-{redacted}
 WARN: [Apr 15 16:00:32.071] failed to notify panel of failed backup state backup=cd0b9ee6-{redacted} error=Error response from Panel: BadRequestHttpException: Cannot update the status of a backup that is already marked as completed. (HTTP/400) server=e00c07d3-{redacted}

Stacktrace:
Error response from Panel: BadRequestHttpException: Cannot update the status of a backup that is already marked as completed. (HTTP/400)
github.com/pterodactyl/wings/server.(*Server).notifyPanelOfBackup
        /home/runner/work/wings/wings/server/backup.go:29
github.com/pterodactyl/wings/server.(*Server).Backup
        /home/runner/work/wings/wings/server/backup.go:71
github.com/pterodactyl/wings/router.postServerBackup.func1
        /home/runner/work/wings/wings/router/router_server_backup.go:50
runtime.goexit
        /opt/hostedtoolcache/go/1.16.2/x64/src/runtime/asm_amd64.s:1371

ERROR: [Apr 15 16:00:32.073] router: failed to generate server backup error=backup: error while generating server backup: Error response from Panel: ConflictHttpException: This backup is already in a completed state. (HTTP/409) request_id=95871077-{redacted} server_id=e00c07d3-{redacted}

Stacktrace:
Error response from Panel: ConflictHttpException: This backup is already in a completed state. (HTTP/409)
backup: error while generating server backup
github.com/pterodactyl/wings/server.(*Server).Backup
        /home/runner/work/wings/wings/server/backup.go:88
github.com/pterodactyl/wings/router.postServerBackup.func1
        /home/runner/work/wings/wings/router/router_server_backup.go:50
runtime.goexit
        /opt/hostedtoolcache/go/1.16.2/x64/src/runtime/asm_amd64.s:1371
```

**To Reproduce**

Create a schedule from the panel
Create one task to backup the server
Leave to run for 24 hours - You will eventually see failed backups 

**Expected behavior**

Every backup is successful and doesn't fail.

**Comment by DaneEveritt** [comment]
potentially ref #2962

**Comment by iTzEthqnHD** [comment]
I too have this same exact error in the logs, only it happens on some manual backups too. My s3 provider is Wasabi if that helps. Still happens after updating to 1.4.0 too. I'm not sure if this has something to do with this issue, but the backups only run at 100Mbps too...

**Comment by ukdaaan** [comment]
I can confirm after updating to the latest wings and panel we're still seeing errors however they're now alot more frequent

![image](https://user-images.githubusercontent.com/33575896/116632039-17fe0a00-a94e-11eb-8b7a-0121fcaed184.png)

**Comment by DaneEveritt** [comment]
Pictures of failed backups is not helpful, please provide relevant error logs.

**Comment by DaneEveritt** [comment]
Can you pull the audit logs for those backups by chance?

```sql
select * from audit_logs where metadata->>"$.backup_uuid" = "123456789"
```

Replace `123456789` with the UUID for the failed backup.

**Comment by ukdaaan** [comment]
i will give this a shot in the morning - i did attempt to grab wings logs for those backups however there was nothing in the pastebin other than a single line stating backup was starting.

**Comment by ukdaaan** [comment]
> 
> 
> Can you pull the audit logs for those backups by chance?
> 
> ```sql
> select * from audit_logs where metadata->>"$.backup_uuid" = "123456789"
> ```
> 
> Replace `123456789` with the UUID for the failed backup.

here's the audit from the database - (all have come from the same minecraft server 11 failed in the last 72hrs only 3 produce anything in the audit logs.)

{"id":6737, "uuid":"6df3f89b-b797-438a-8924-8ca85a5057bb", "is_system":1, "user_id":0, "server_id":44, "action":"server:backup.failed", "subaction":"", "device":"{\"ip_address\":\"x.x.x.x\",\"user_agent\":\"Pterodactyl Wings\\/v1.4.1 (id:sRItOCFtXCXiDtBg)\"}", "metadata":"{\"backup_uuid\":\"8c430d47-5eb2-4ed7-bac5-c7e181c9139d\"}", "created_at":"2021-05-06 16:03:28"},

 {"id":6397, "uuid":"720082ce-4df7-492f-a0a3-3aeb8f5eef8b", "is_system":1, "user_id":0, "server_id":44, "action":"server:backup.failed", "subaction":"", "device":"{\"ip_address\":\"x.x.x.x\",\"user_agent\":\"Pterodactyl Wings\\/v1.4.1 (id:sRItOCFtXCXiDtBg)\"}", "metadata":"{\"backup_uuid\":\"4a2bc988-9b06-4798-8af3-fa7cbddca430\"}", "created_at":"2021-05-05 13:03:17"},

 {"id":5691, "uuid":"8b59b8ae-4798-459b-bb4b-57a4b9fc15bd", "is_system":1, "user_id":0, "server_id":44, "action":"server:backup.failed", "subaction":"", "device":"{\"ip_address\":\"x.x.x.x\",\"user_agent\":\"Pterodactyl Wings\\/v1.4.1 (id:sRItOCFtXCXiDtBg)\"}", "metadata":"{\"backup_uuid\":\"02df1d99-72e9-4192-81fd-3c0ca2c66028\"}", "created_at":"2021-05-03 09:06:31"},

**Comment by DaneEveritt** [comment]
Sorry can you also provide the logs from Wings as well @djsmithuk relating to any of the failed backups (but also ideally any of those three above).

**Comment by ukdaaan** [comment]
The above examples had nothing in the wings diagnositcs, the following failed backup appeared in the wings diagnositcs but not in the SQL audit logs. (came from the same minecraft server as the above)

```
INFO: [May  7 00:21:28.410] creating backup for server adapter=s3 backup=3bf6c167-d102-4535-846d-73500667473f path=/var/lib/pterodactyl/backups/3bf6c167-d102-4535-846d-73500667473f.tar.gz request_id=ee208878-b858-499c-999f-d27e59c8e058 server=c9ea7ec8-dd10-4a6e-947d-ce62976af327
 INFO: [May  7 00:21:30.249] created backup successfully adapter=s3 backup=3bf6c167-d102-4535-846d-73500667473f request_id=ee208878-b858-499c-999f-d27e59c8e058 server=c9ea7ec8-dd10-4a6e-947d-ce62976af327
 INFO: [May  7 00:21:31.145] attempting to upload backup to s3 endpoint... adapter=s3 backup=3bf6c167-d102-4535-846d-73500667473f parts=1 request_id=ee208878-b858-499c-999f-d27e59c8e058 server=c9ea7ec8-dd10-4a6e-947d-ce62976af327
 INFO: [May  7 00:36:17.044] successfully uploaded backup part adapter=s3 backup=3bf6c167-d102-4535-846d-73500667473f part_id=1 request_id=ee208878-b858-499c-999f-d27e59c8e058 server=c9ea7ec8-dd10-4a6e-947d-ce62976af327
 INFO: [May  7 00:36:17.044] backup has been successfully uploaded adapter=s3 backup=3bf6c167-d102-4535-846d-73500667473f parts=1 request_id=ee208878-b858-499c-999f-d27e59c8e058 server=c9ea7ec8-dd10-4a6e-947d-ce62976af327
 INFO: [May  7 00:36:46.362] failed to notify panel of successful backup state error=Error response from Panel: ValidationException: The successful field must be present. (HTTP/422) server=c9ea7ec8-dd10-4a6e-947d-ce62976af327

Stacktrace:
Error response from Panel: ValidationException: The successful field must be present. (HTTP/422)
github.com/pterodactyl/wings/server.(*Server).notifyPanelOfBackup
	/home/runner/work/wings/wings/server/backup.go:29
github.com/pterodactyl/wings/server.(*Server).Backup
	/home/runner/work/wings/wings/server/backup.go:93
github.com/pterodactyl/wings/router.postServerBackup.func1
	/home/runner/work/wings/wings/router/router_server_backup.go:50
runtime.goexit
	/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371


```

(No backup makes it to the S3 bucket either)

**Comment by PrivateGER** [comment]
Same issue here.
However, the failed backups don't appear in the audit log at all for me. Only successful backups do.
The wings daemon gives this stacktrace:
```
Error response from Panel: ValidationException: The successful field must be present. (HTTP/422)
github.com/pterodactyl/wings/server.(*Server).notifyPanelOfBackup
/home/runner/work/wings/wings/server/backup.go:29
github.com/pterodactyl/wings/server.(*Server).Backup
/home/runner/work/wings/wings/server/backup.go:71
github.com/pterodactyl/wings/router.postServerBackup.func1
/home/runner/work/wings/wings/router/router_server_backup.go:50
runtime.goexit
/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371
ERROR: [Jun  5 22:03:40.609] router: failed to generate server backup error=backup: error while generating server backup: Error response from Panel: ConflictHttpException: T>Jun 05 22:03:40 
Stacktrace:
Error response from Panel: ConflictHttpException: This backup is already in a completed state. (HTTP/409)
```
The S3 bucket doesn't receive the backup.

**Comment by ukdaaan** [comment]
Hi there,

Just an update we've made two changes which seem to have fixed the issue for us (so far.. it's only been 3 days but not a single failed backup touch wood) 

1) Turning off the Cloudflare Proxy for the panel (nodes never had it deployed) there seems to be a limitation of 100MB file uploads that can be made in one request 

This fixed our issue for HTTP 413 request entity too large 

2) Changing S3 bucket providers moving our services to Scaleway from wasabi has proven to also be beneficial 

This fixed our issue of the failing backups with no explanation

**Comment by parkervcp** [comment]
This may be an issue with Wasabi then and not an issue with the S3 functionality.

**Comment by PrivateGER** [comment]
I have the issue with DigitalOcean Spaces as S3 provider. Maybe I should add that.

**Comment by Technoguyfication** [comment]
I'm also experiencing this issue using Wasabi as an S3 provider.

**Comment by parkervcp** [comment]
As I have called out last time. This seems like a provider specific issue and not S3 support as a whole.

**Comment by nikrozman21** [comment]
I can also replicate this same issue across 3 different providers.

**Comment by schrej** [comment]
With people reporting this issue with multiple different providers, I doubt that it's a provider issue. Also, if uploading large files would be broken for a provider, that would be noticed. Storing large files like backups on S3 is one of it's prime use cases.

**Comment by DaneEveritt** [comment]
Theres multiple different errors so if people are only going to respond with "this doesn't work for me either" its going to do absolutely nothing to get it fixed.

**Unless you're including error logs and version information about Wings and the Panel, please don't just respond with what is effectively a long-worded "+1". Thanks :)**

**Comment by ukdaaan** [comment]
Further update, since we made our changes things have been running smoothly - I'd assume this is some form of S3 provider compatibility thing. We've done 15TBs worth of backups since making the change and no issues have occurred.
