### ISSUE TITLE
Issue with unarchiving .RAR files

### ISSUE THREAD

**Issue by SneakyHub** [pterodactyl/panel#3267]
**Background (please complete the following information):**
PHP Version: **8.0.3** ( Current latest )
Panel Version: **1.3.2**
Wings Version: **1.3.2**
Server Operating System: Ubuntu 18.04
My Computer OS: Windows 10 64 bit
Browser: Firefox Developer Edition ( I also tried in incognito )

**Describe the bug**

If you use winrar and rar a file then upload it to the panel either from the web browser or via SFTP. Go over to the panel on https://panel.example.com/ then as you go to right click the file and select unarchive it will spit out an error. The error is below, This happens with any file that ends with .rar. No matter what it will not allow you to unarchive even though it has an option to unarchive.

Error:
There was an error while communicating with the machine running this server. This error has been logged, please try again. (code: 500) (request_id: d02886a9-90cf-4713-92d9-ef7c9ccac8eb)

Wings Error:
https://cdn.sneakyhub.com/Bo4sab4.png
^ if you don't wanna view the screenshot.

> DEBUG: [Apr 16 04:54:32.569] checking if space is available for file decompression file=bg.rar request_id=65afc9c4-f167-41d0-8829-cec785d510fb root_path=/ server_id=b2c816f3-dbe7-4f7d-9ba2-471178de255c
>  INFO: [Apr 16 04:54:32.570] starting file decompression file=bg.rar request_id=65afc9c4-f167-41d0-8829-cec785d510fb root_path=/ server_id=b2c816f3-dbe7-4f7d-9ba2-471178de255c
> 
> 
> 2021/04/16 04:54:32 [Recovery] 2021/04/16 - 04:54:32 panic recovered:
> runtime error: invalid memory address or nil pointer dereference
> /opt/hostedtoolcache/go/1.16.2/x64/src/runtime/panic.go:212 (0x435eda)
> /opt/hostedtoolcache/go/1.16.2/x64/src/runtime/signal_unix.go:734 (0x44f8f2)
> /home/runner/work/wings/wings/system/utils.go:55 (0x9030f0)
> /home/runner/work/wings/wings/server/filesystem/compress.go:124 (0xc82e8e)
> /home/runner/go/pkg/mod/github.com/mholt/archiver/v3@v3.5.0/rar.go:319 (0x8ed3c7)
> /home/runner/go/pkg/mod/github.com/mholt/archiver/v3@v3.5.0/archiver.go:228 (0x8e8303)
> /home/runner/work/wings/wings/server/filesystem/compress.go:120 (0xc7cae4)
> /home/runner/work/wings/wings/router/router_server_files.go:401 (0xd32eb1)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xd018cb)
> /home/runner/work/wings/wings/router/middleware/middleware.go:274 (0xd018ab)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xd01ce7)
> /home/runner/work/wings/wings/router/middleware/middleware.go:302 (0xd01cc6)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xd01ce7)
> /home/runner/work/wings/wings/router/middleware/middleware.go:302 (0xd01cc6)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xc56f33)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0xc56ef2)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xd00c7c)
> /home/runner/work/wings/wings/router/middleware/middleware.go:177 (0xd00c5f)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xd00bb6)
> /home/runner/work/wings/wings/router/middleware/middleware.go:168 (0xd00b99)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xd01497)
> /home/runner/work/wings/wings/router/middleware/middleware.go:251 (0xd0147e)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xd00d2f)
> /home/runner/work/wings/wings/router/middleware/middleware.go:194 (0xd00d0f)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xd00ae5)
> /home/runner/work/wings/wings/router/middleware/middleware.go:159 (0xd00ac5)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xc57eb0)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0xc57e97)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xc4e06f)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0xc4e056)
> /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0xc4db0c)
> /opt/hostedtoolcache/go/1.16.2/x64/src/net/http/server.go:2887 (0x70fb22)
> /opt/hostedtoolcache/go/1.16.2/x64/src/net/http/server.go:1952 (0x70af4c)
> /opt/hostedtoolcache/go/1.16.2/x64/src/runtime/asm_amd64.s:1371 (0x472280)

**To Reproduce**
1. Go to the website where the panel is located at.
2. Go to file manager and upload the rar file.
3. (optionally) go to your SFTP and upload the .rar file there.
4. Go back to the file manager on the website and right click the file you have just uploaded.
5. Right click the file and click unarchive
6. You will be given the same error as what I have except the ID may be different.

**Expected behavior**
The .rar is expected to unarchive all of it's contents.

**Comment by trenutoo** [comment]
I can confirm that the request goes through and shows up in Wings logs, but the archive decompression isn't processed

`INFO: [Apr 16 04:54:57.859] starting file decompression file=test.rar request_id=b8067fad-5571-496e-a2fe-230acbd85ee6 root_path=/ server_id=4cb720fe-46e8-44f8-b2ec-19b881e4e933`

**Comment by DaneEveritt** [comment]
I never really intended for `.rar` files to be supported, so probably just needs to not even try at that point.

**Comment by SneakyHub** [comment]
Shouldn't be that hard to implement but if it gives the option to unarchive i thought it was supported.
