### ISSUE TITLE
Setting up a slave node

### ISSUE THREAD

**Issue by crombiecrunch** [Pterodactyl/Panel#327]
I have multiple dedicated servers that I would like to setup as slave nodes. I already have one server setup with the front end and node 1. While trying to setup the second server I only installed the daemon and adjusted the config file to point from 0.0.0.0 to the IP of the main server. Ports 8080 are open on both servers but I can not connect. 

I get Error: listen EADDRNOTAVAIL myip:8080

---------------------

**Comment by parkervcp** [comment]
Did you configure then in the panel first? Each node needs to be added individually. Each node also has a different config.

**Comment by DaneEveritt** [comment]
It sounds like the IP you're using in the config didn't actually exist on the server
