### ISSUE TITLE
Add manual refresh button in the File Manager

### ISSUE THREAD

**Issue by EsserGaming** [pterodactyl/panel#3274]
Would be nice to have a refresh button in the File Manager, it would be very useful for a handful of things.

**Comment by mason-rogers** [comment]
1. You didnt follow the issue templates available
2. F5 exists

**Comment by EsserGaming** [comment]
the first one is ok, I apologize for being lazy but the second one, yes, you can use f5 but why not use a dedicated refresh button like alot of other ftp programs?

**Comment by FoksVHox** [comment]
> the first one is ok, I apologize for being lazy but the second one, yes, you can use f5 but why not use a dedicated refresh button like alot of other ftp programs?

Either Update the issue to contain the template, or close this and open a new issue with the template filled. Dane isn't going to even look at this, if the template isn't filled.
