### ISSUE TITLE
Update button

### ISSUE THREAD

**Issue by finnie2006** [pterodactyl/panel#3276]
**Is your feature request related to a problem? Please describe.**
Nope,
**Describe the solution you'd like**
A update button at system glance when there is an update if u push it u get a little screen with the log And then it will update
Somewhere here:
![afbeelding](https://user-images.githubusercontent.com/57916807/115202292-8f35d180-a0f6-11eb-859c-12844b2e3278.png)

**Comment by FoksVHox** [comment]
Just use the command? It isn't harder than that.

**Comment by finnie2006** [comment]
Yeah nevermind i will close it

**Comment by FoksVHox** [comment]
@finnie2006 Don't get me wrong, but when @matthewpi's react-admin branch is merged, you could submit a PR, with the required code to have an update button.
