### ISSUE TITLE
php artisan node creation/setup & php artisan allocation creation/setup

### ISSUE THREAD

**Issue by JackW6809** [pterodactyl/panel#3277]
**Is your feature request related to a problem? Please describe:**
I'm always frustrated when I have to go into the panel and create the node and allocations manually.

**Describe the solution you'd like:**
Like for example ```p:location:make``` works great. So why not make a command for node creation and allocation creation? Also while we are there, why not allow the Wings configuration file to be automatically filled in according to what is in the panel rather than having to generate the token, etc?

**Describe alternatives you've considered:**
I have been using the API for a while, however, sometimes it is lengthy. Especially when I have to put in lots of allocations. I think having the command available will make installs quicker and easier. Also more foolproof.

**Additional context:**
If this feature is added, and node creation is all been able to be done via a command. And allocations are able to be specified when creating the node. Then it automatically configuring Wings on the same machine, then it would allow for an entirely headless installation.

**Comment by Boy132** [comment]
You can auto-deploy nodes with one command:
![image](https://user-images.githubusercontent.com/8203120/115255435-8d880000-a12e-11eb-8e54-b328e7af2bea.png)

**Comment by JackW6809** [comment]
Yes, however that is not the point I am attempting to make. I am trying to make it a headless installation. The Auto-Deploy command just configures Wings after the Node is created in the panel. Whereas I would be looking to create the node, deploy wings and set allocations using either a command or several commands.

**Comment by FoksVHox** [comment]
I'm most likely going to try to make this tomorrow

**Comment by matthewpi** [comment]
Is there a reason you don't use the Application API to achieve this?

**Comment by FoksVHox** [comment]
It could be faster to create/deploy new nodes?
