### ISSUE TITLE
Copying does not work perfectly

### ISSUE THREAD

**Issue by Seef0x** [pterodactyl/panel#3284]
**Background:**

* Panel or Wings: Panel
* Version of Panel/Wings: 1.3.2
* Server's OS: Debian GNU/Linux 10 (buster)
* Your Computer's OS & Browser: Firefox

**Describe the bug**
Since a certain update, CTRL + C or click to copy no longer works, only the right click -> copy

**To Reproduce**
Steps to reproduce this behavior:

Try to copy an item without using right click -> copy

**Comment by FoksVHox** [comment]
Is that withon the filemanager, the console, the SFTP information or where is it? If you don't include that stuff, it isn't going to be looked in to.

**Comment by trenutoo** [comment]
Fixed in [#3195](https://github.com/pterodactyl/panel/pull/3195)

**Comment by Seef0x** [comment]
> Fixed in [#3195](https://github.com/pterodactyl/panel/pull/3195)

My bad, I did not see
