### ISSUE TITLE
Would contributions adding support for playit.gg be welcome?

### ISSUE THREAD

**Issue by loriopatrick** [pterodactyl/panel#3286]
I created playit.gg (a tunneling service like ngrok) that supports UDP and TCP tunnels. It's free and we charge for custom .playit.gg domains ($1/month, $6/year). A handful of our users have setups that use this program. Would contributions adding a playit.gg integration be supported? Playit.gg is proprietary and I'm not prepared to opensource the client program. I can however ship it as a docker image (does not require elevated privileges).

Do others want this also? Would remove the need for port forwarding and issues for people with CGNAT.

**Comment by DaneEveritt** [comment]
I have no intentions of including 3rd party commercial integrations, sorry. But thanks for asking :)

**Comment by slimshizn** [comment]
Maybe this can be integrated now that control has shifted. I think this should be reconsidered since sftp is easier to use through playit.gg.

**Comment by slimshizn** [comment]
Especially for those of us using cloudflare tunnels.

**Comment by loriopatrick** [comment]
I'm actually working to make third party integrations easier with a simplified protocol and API as several other app expressed interest in integrating.

@DaneEveritt the playit client is now open source: https://github.com/playit-cloud/playit-agent, but the backend is still proprietary. Not sure if that changes anything.

@slimshizn what do you mean by control has shifted? I see the funding.yml changed. I don't really want to go against the original author's goal for the project even if there is a new maintainer.

**Comment by slimshizn** [comment]
That's all I meant, no harm or foul. Just hopeful for additions to make some things easier.

**Comment by slimshizn** [comment]
@matthewpi is this something you are willing to look into or is this still a pass? Thank you.

**Comment by matthewpi** [comment]
> @matthewpi is this something you are willing to look into or is this still a pass? Thank you.

Currently, I'm not interested in integrating such functionality, so for now the answer remains the same.

**Comment by EuleMitKeule** [comment]
I would love having playit integrated with pterodactyl!

**Comment by Butterkeks1000** [comment]
+1

**Comment by core6quad** [comment]
+1

**Comment by Fibbicles** [comment]
I know this is an extremely old thread but why has no one made a Pterodactyl egg so we can just use the PlayIt docker image?

**Comment by DaneEveritt** [comment]
Please open a discussion with reasoning as to why this should be considered and it may be re-evaluated. [However, per our post](https://github.com/pterodactyl/panel/issues/5491) the issue tracker is not the appropriate place for this discussion.
