### ISSUE TITLE
Panel unable to connect to Wings after a clean install.

### ISSUE THREAD

**Issue by Delta18-Git** [pterodactyl/panel#3293]
**Background:**

* Panel or Wings: Wings
* Version of Panel/Wings: 1.4.0
* Panel Logs: https://bin.ptdl.co/0qh63/
* Wings Logs: https://ptero.co/yesebokeru
* Server's OS: DietPi (Based on Debian 10 with customized and special software for media servers, using PC version)
* Your Computer's OS & Browser: Windows 10, Google Chrome Dev

**Describe the bug**
The panel and node do not connect. They are on the same computer. I followed the community guide for Debian 10 and tried a clean install. However, the bug persists. I don't have a domain name, so the panel has the public IP address in the domain area, and I am not using SSL for anything.
Panel: `php -v` `PHP 8.0.3 (cli) (built: Mar  5 2021 08:38:30) ( NTS )`
Wings: 
`uname -a`: `Linux DietPi 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux`
`docker info`: https://ptero.co/awenikayew

**To Reproduce**
Steps to reproduce this behavior:

1. Follow the community guide for Debian 10 but use php 8.0 using deb.sury.org repository.
2. Install Wings on the same server.
3. Add the server as a node.
4. Node is not added

**Expected behavior**
A node is added, and you can add servers to the node.

![image](https://user-images.githubusercontent.com/64347927/115995310-6763d380-a5f8-11eb-8fa8-706bdfc27ed4.png)

![image](https://user-images.githubusercontent.com/64347927/115995341-7a76a380-a5f8-11eb-8083-5100f7fd6b4a.png)

![image](https://user-images.githubusercontent.com/64347927/115995388-967a4500-a5f8-11eb-8232-e733329c8163.png)

**Comment by Delta18-Git** [comment]
I hope that this is the required information. I am pretty new to php and MySQL and apologize if this is not a issue that should be opened here.

**Comment by parkervcp** [comment]
it looks like your firewall is blocking access to wings. You need to port forward 8080 and 2022 to your wings host.

**Comment by Delta18-Git** [comment]
They are on the same computer though, so I don't know why or how it would be blocking access.

**Comment by Shadowhackercz** [comment]
You don't know why or how, did you tried to allow it though? If you are using ufw (you can install it, easy firewall, find tutorials on internet) then you can just "ufw allow 2022" and such, you didn't said if it's allowed, still it may be blocking some connections, no harm in trying those:)

**Comment by Delta18-Git** [comment]
However, whenever I try to do curl (ip address):8080 on the server, it gives an error: `{"error":"The required authorization heads were not present in the request."}`

**Comment by Delta18-Git** [comment]
> You don't know why or how, did you tried to allow it though? If you are using ufw (you can install it, easy firewall, find tutorials on internet) then you can just "ufw allow 2022" and such, you didn't said if it's allowed, still it may be blocking some connections, no harm in trying those:)

Will try.

**Comment by Delta18-Git** [comment]
> You don't know why or how, did you tried to allow it though? If you are using ufw (you can install it, easy firewall, find tutorials on internet) then you can just "ufw allow 2022" and such, you didn't said if it's allowed, still it may be blocking some connections, no harm in trying those:)

Tried it, but the panel still doesn't connect to the node.

**Comment by DaneEveritt** [comment]
This is almost certainly not an issue with this software, rather an issue with a firewall configuration or something specific to your machine. This is not an uncommon setup that almost everyone runs without issue.

Sorry to close this on you, but this tracker is specifically for tracking known bugs with the software, and not diagnosing issues with specific server configurations. :)

**Comment by Delta18-Git** [comment]
Ah sorry, I didn't know if it was supposed to go here or not. I had put it here because I couldn't find any information for if Wings and the Panel were on the same computer.

**Comment by Delta18-Git** [comment]
The server now works. I am not sure why it is working as I did nothing different other than opening the port of the daemon. However, when I later changed the port, it was still working, so ¯\ _ (ツ) _ /¯.
