### ISSUE TITLE
Syntax error, unexpected 'DaemonServerRepository' after update from 1.3.0 to 1.4.0

### ISSUE THREAD

**Issue by ollimaz** [pterodactyl/panel#3294]
**Background:**

* Panel or Wings: Panel
* Version of Panel/Wings: Update from 1.3.0 to 1.4.0
* Panel Logs: See below
* Server's OS: Ubuntu 18.04 LTS

**Describe the bug**
After updating the panel returns a 500 Server Error Response. I am using PHP 8.0.3 (cli) (built: Mar  5 2021 07:53:56) ( NTS ) and the log contains follwing:
`[2021-04-25 15:34:42] production.ERROR: syntax error, unexpected 'DaemonServerRepository' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'DaemonServerRepository' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) at /var/www/vhosts/**censored**/dashboard.**censored**/app/Http/Controllers/Api/Client/Servers/ResourceUtilizationController.php:18)
[stacktrace]
#0 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/var/www/vhosts...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Pterodactyl\\\\Htt...')
#2 [internal function]: spl_autoload_call('Pterodactyl\\\\Htt...')
#3 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/RouteAction.php(91): method_exists('Pterodactyl\\\\Htt...', '__invoke')
#4 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/RouteAction.php(47): Illuminate\\Routing\\RouteAction::makeInvokable('Pterodactyl\\\\Htt...')
#5 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/Route.php(183): Illuminate\\Routing\\RouteAction::parse('api/client/serv...', Array)
#6 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/Route.php(164): Illuminate\\Routing\\Route->parseAction(Array)
#7 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/Router.php(556): Illuminate\\Routing\\Route->__construct(Array, 'api/client/serv...', Array)
#8 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/Router.php(475): Illuminate\\Routing\\Router->newRoute(Array, 'api/client/serv...', Array)
#9 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/Router.php(454): Illuminate\\Routing\\Router->createRoute(Array, '/resources', Array)
#10 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/Router.php(146): Illuminate\\Routing\\Router->addRoute(Array, '/resources', 'Servers\\\\Resourc...')
#11 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Routing\\Router->get('/resources', 'Servers\\\\Resourc...')
#12 /var/www/vhosts/**censored**/dashboard.**censored**/routes/api-client.php(44): Illuminate\\Support\\Facades\\Facade::__callStatic('get', Array)
#13 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/Router.php(422): Illuminate\\Routing\\RouteFileRegistrar->{closure}(Object(Illuminate\\Routing\\Router))
#14 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/Router.php(381): Illuminate\\Routing\\Router->loadRoutes(Object(Closure))
#15 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Routing\\Router->group(Array, Object(Closure))
#16 /var/www/vhosts/**censored**/dashboard.**censored**/routes/api-client.php(120): Illuminate\\Support\\Facades\\Facade::__callStatic('group', Array)
#17 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/RouteFileRegistrar.php(35): require('/var/www/vhosts...')
#18 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/Router.php(424): Illuminate\\Routing\\RouteFileRegistrar->register('/var/www/vhosts...')
#19 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/Router.php(381): Illuminate\\Routing\\Router->loadRoutes('/var/www/vhosts...')
#20 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php(135): Illuminate\\Routing\\Router->group(Array, '/var/www/vhosts...')
#21 /var/www/vhosts/**censored**/dashboard.**censored**/app/Providers/RouteServiceProvider.php(53): Illuminate\\Routing\\RouteRegistrar->group('/var/www/vhosts...')
#22 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Pterodactyl\\Providers\\RouteServiceProvider->map()
#23 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#25 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#26 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#27 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(122): Illuminate\\Container\\Container->call(Array)
#28 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(45): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->loadRoutes()
#29 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->Illuminate\\Foundation\\Support\\Providers\\{closure}()
#30 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#31 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#32 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#33 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#34 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(113): Illuminate\\Container\\Container->call(Object(Closure))
#35 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(872): Illuminate\\Support\\ServiceProvider->callBootedCallbacks()
#36 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\\Foundation\\Application->bootProvider(Object(Pterodactyl\\Providers\\RouteServiceProvider))
#37 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Pterodactyl\\Providers\\RouteServiceProvider), 27)
#38 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): array_walk(Array, Object(Closure))
#39 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#40 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#41 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#42 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#43 /var/www/vhosts/**censored**/dashboard.**censored**/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#44 /var/www/vhosts/**censored**/dashboard.**censored**/public/index.php(68): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#45 {main}
"}  `

**To Reproduce**
Happened to me after updating from 1.3.0 to 1.4.0, all update steps have been successful and I have made them twice.

**Comment by ollimaz** [comment]
Fixed... Composer used php8 to install but the webserver was still running on php7.4 that's what caused the error

**Comment by trenutoo** [comment]
The bot on the Discord is configured to reply to this, I'd recommend posting your logs and issues on Discord first
