### ISSUE TITLE
JWT validation error from wings: jwt: no jwt present

### ISSUE THREAD

**Issue by TreeHD** [pterodactyl/panel#3295]
**Background (please complete the following information):**

* Panel or Wings: Panel
* Version of Panel/Wings:  1.4.0
* Panel Logs: No Logs and No Error
* Wings Logs: https://ptero.co/ivajikavow
* Server's OS: CentOS 8
* Your Computer's OS & Browser: Windows 10 & Chrome 90

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Wings: `uname -a` and `docker info` (your kernel version and information regarding docker)

php -v
PHP 8.0.3 (cli) (built: Mar  9 2021 22:10:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies

uname -a
Linux vm1.tp.mcsh.co 4.18.0-240.el8.x86_64 #1 SMP Fri Sep 25 19:48:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
Steps to reproduce this behavior:

1. Go to 'Server'
2. Click on 'My Servers'
3. See error

**Expected behavior**
On Chrome DevTools,only says 'JWT validation error from wings: jwt: no jwt present'
File Browser is working correctly
![image](https://user-images.githubusercontent.com/23317010/115997533-fcc19080-a615-11eb-9304-a5d1ced2457a.png)

**Comment by DaneEveritt** [comment]
Does refreshing the page fix the issue? And in any case, there should be an XHR request to `/websocket` that returns a token in the response, is that present and does it contain a token value? (Please, do not actually show the output of that endpoint as those are live tokens).

**Comment by TreeHD** [comment]
Re-Fresh Page isn't fix
/websocket return data/token+token value and socket <wss://node:port>

But WSS request stuck in pending

**Comment by nikrozman21** [comment]
Encountered the same issue today.
A refresh didn't fix it for me either.

Attempted fixes:

- reset node daemon key
- recompiled and reinstalled wings
- reinstalled and updated golang
- suspended and un-suspended the server
- changed server's install state
- changed used Docker image

None of these fixed the issue, however a reinstall through the admin panel did fix it eventually and they were able to use it normally after that. Here are a couple of screenshots from when it happened: (debug mode on)

[Daemon](https://cdn.discordapp.com/attachments/297133809130799127/839147416295964772/unknown.png)
[Panel](https://cdn.discordapp.com/attachments/297133809130799127/839151859179585607/unknown.png)

Here's some additional info:

Version of Panel/Wings: 1.4.1/1.4.2
Panel Logs: no logs
Wings Logs: refer to screenshot
Server's OS: Ubuntu server 20.04 LTS
Your Computer's OS & Browser: Win10, Chrome 90.0.4430.93

**Comment by VibeGAMESNL** [comment]
I got the same issue today. Rebooting the entire node did help...
