### ISSUE TITLE
Ability to define custom root directory for subusers with file access

### ISSUE THREAD

**Issue by misterquestions** [pterodactyl/panel#3297]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When creating a sub-user for a server it would be nice that if we want to grant them access to files and sftp, to be able to define a home/root directory for this user. So they can see some of the files but not all.

For example: We have a FiveM server where we want to give permission to some user call it "adam", however we just want him to add models to the server and not be able to see all of the scripts. So a simple solution is to create a subuser for him in the panel with file access and chroot jail to "[models]" folder.

**Describe alternatives you've considered**
Using another ftp service on the host server isn't secure at all, and not synchronized with panel stuff.

**Additional context**
None

**Comment by DaneEveritt** [comment]
Duplicate #2757
