### ISSUE TITLE
unarchive feature struggle with filenames containing accents

### ISSUE THREAD

**Issue by JulienTant** [pterodactyl/panel#3298]
**Background (please complete the following information):**

* Panel or Wings: wings
* Version of Panel/Wings: 1.4.0
* Panel Logs: n/a
* Wings Logs: n/a
* Server's OS: ubuntu 1804
* Your Computer's OS & Browser: n/a

**Describe the bug**
When unarchiving a zip containing a file with an accident in its name, the file names are not handled correctly and that makes the file unusable through the UI. The problem **does not** exist if you upload a file with an accent directly through the UI,

(green=uploaded manually, red=from an unarchive action)
![image](https://user-images.githubusercontent.com/785518/116010496-1b9f3300-a5d4-11eb-8221-52c580b43910.png)

also here's what stored on the server
```console
[REDACTED]# ls -la
total 10456
drwx------ 2 pterodactyl pterodactyl     4096 Apr 25 21:28  ./
drwxrwxr-x 5 [REDACTED][REDACTED] 4096 Apr 24 07:20  ../
-rw-r--r-- 1 pterodactyl pterodactyl        0 Apr 25 21:23  léo.txt #<- uploaded
-rw-r--r-- 1 pterodactyl pterodactyl        0 Apr 25 21:21 'l'$'\202''o.txt' #<- unarchived
```

**To Reproduce**
Steps to reproduce this behavior:

1. Go to the file manager of a server
2. Upload a zip containing a file with an accent and unarchive it
3. Try to rename/download/remove the file containing an accent
4. if you removed the file, refresh the page. The wing doesn't trigger an error so the UI "removes" the file from the list.

**Expected behavior**
I should be able to interact with any file,

**Attachments**
[test.zip containing one file with an accent](https://github.com/pterodactyl/panel/files/6373178/test.zip)

**Comment by DaneEveritt** [comment]
Quoting the go source... "The ZIP format has a sad state of affairs regarding character encoding."

I put some effort into trying to solve this, got nowhere useful, and its honestly not going to be productive for me to keep trying to hack a fix into this code for this. If someone figures it out and wants to PR a fix go for it, but otherwise I'm just going to call that an edge case not worth my time.
