### ISSUE TITLE
Themeing support

### ISSUE THREAD

**Issue by parkervcp** [Pterodactyl/Panel#33]
Have a quick way to add themes for the panel. Allowing for large graphical overhaul of the panel.

Can be convenient for a provider to differentiate their panel from others.

**Comment by DaneEveritt** [comment]
My thought process for this is to basically make it so you can edit all of the templates from the Admin CP, as well as modify themes from it.

Should there be multiple-theme support where users can pick their theme?

**Comment by DDynamic** [comment]
This has been taken care of internally.
