### ISSUE TITLE
Error binding to 0.0.0.0 / Service unkown

### ISSUE THREAD

**Issue by alexgn100** [pterodactyl/panel#3300]
* Panel or Wings: Wings
* Version of Panel/Wings: 1.4.0
* Panel Logs: not available 
* Wings Logs: https://ptero.co/emupilokew.js
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 | Microsoft Edge 90.0.818.46 

**Describe the bug**
Since the last update 1.4.0 I have the problem that when I start a game server (eg Minecraft, Garrys Mod...) which have in the config bind IP to 0.0.0.0 crash with the following message:

java.net.UnknownHostException: server-ip=0.0.0.0: Name or service not known

Additional after the once crashes it destroys the configs of the gameservers or the worlds, because it converts them then completely messed up

**To Reproduce**
Steps to reproduce this behavior:

1. Go to a Server
2. Click on Start
3. See error in the console

**Expected behavior**
Destroy Config after crashing:
![msedge_vPVY5i8Kof](https://user-images.githubusercontent.com/32128537/116107492-5fb53500-a6b3-11eb-85a9-fe0bc43fd390.png)

![msedge_cylel4aiQM](https://user-images.githubusercontent.com/32128537/116107711-8e331000-a6b3-11eb-9581-114cfcbdd617.png)

**Comment by alexgn100** [comment]
I have now downgraded the Wings to version 1.3.2 and now everything works again without errors.

**Comment by DaneEveritt** [comment]
What egg are you using? It looks like you have something configured quite wrong here. I'd fully expect if this was a bug in the software that plenty of other people would be complaining about it. There were no changes in 1.4.0 that affected the configuration files.

Your steps to reproduce are useless to me since I do that all the time and have never seen this happen.

**Comment by TASelwyn** [comment]
Why is your server.properties file saying "server-ip=server-ip=0.0.0.0"?
it should just be server-ip=0.0.0.0

Happens all throughout your server properties file... which is strange....

It should look like: https://raw.githubusercontent.com/parkervcp/eggs/master/minecraft/java/server.properties

**Comment by alexgn100** [comment]
> Why is your server.properties file saying "server-ip=server-ip=0.0.0.0"?
> it should just be server-ip=0.0.0.0
> 
> Happens all throughout the server properties file... that is very strange.
> 
> It should look like: https://raw.githubusercontent.com/parkervcp/eggs/master/minecraft/java/server.properties

The server-ip=server-ip=0.0.0.0 coming from the crashing, every crash add a second server-ip= to the config.

For the Minecraft Server i use the Paper egg from parkervcp (https://github.com/parkervcp/eggs/blob/master/minecraft/java/paper/egg-paper.json)

**Comment by Kaesewuerfel** [comment]
> > Why is your server.properties file saying "server-ip=server-ip=0.0.0.0"?
> > it should just be server-ip=0.0.0.0
> > Happens all throughout the server properties file... that is very strange.
> > It should look like: https://raw.githubusercontent.com/parkervcp/eggs/master/minecraft/java/server.properties
> 
> The server-ip=server-ip=0.0.0.0 coming from the crashing, every crash add a second server-ip= to the config.
> 
> For the Minecraft Server i use the Paper egg from parkervcp (https://github.com/parkervcp/eggs/blob/master/minecraft/java/paper/egg-paper.json)

Telling lies
