### ISSUE TITLE
Regular Expressions in eggs startup configuration

### ISSUE THREAD

**Issue by ghostdevv** [pterodactyl/panel#3301]
**Is your feature request related to a problem? Please describe.**
I host a lot of discord bots, small api's, etc, using pterodactyl, and unlike something like a minecraft server the startup messages logged by them applications are inconsistent, while I could ask clients to say the same message on startup or one from an array of messages it would be easier to have a regular expression or two to check if the application can be marked as online

**Describe the solution you'd like**
Have the ability to give a regular expression or an array of regular expressions

**Describe alternatives you've considered**
I have tried with just getting clients to log from an array of items to mark their application as online but as the amount I host grows it isn't as easy to do that

**Comment by matthewpi** [comment]
You can already do this.

The done configuration supports not only being an array of options but if you specify `regex:` in one of the options it will be parsed as a regex.  It should be noted that this uses Go's [regexp](https://golang.org/pkg/regexp) engine which doesn't support some regex features like JavaScript does.

For example:
```
{
	"done": [
		"regex:foo.*"
	]
}
```
would match any line that contains `foo`.

**Comment by ghostdevv** [comment]
Oh thank you for the tip @matthewpi . I was told in the Discord that this wasn't supported

**Comment by matthewpi** [comment]
> Oh thank you for the tip @matthewpi . I was told in the Discord that this wasn't supported

Sadly, many people don't know what is or is not supported; especially as this feature specifically was initially implemented during one of the 1.0 alphas and it hasn't been well documented.

**Comment by ghostdevv** [comment]
Makes sense, thanks for letting me know
