### ISSUE TITLE
Import Backups

### ISSUE THREAD

**Issue by broimsuperman** [pterodactyl/panel#3308]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
There should be an import button on the backup section of a server and the backup section from the admin side. the import button would allow you too choose either existing backups already stored, or one from your device (open a window to choose a compressed file containing the backup i.e .tar.gz and .zip). After a file is chosen (and/or uploaded) it should add the backup, then ask you if you'd like to restore it. 
Shouldn't be too hard as you'd just need to look for files in the backup directory and open a dialog to choose files essentially.

Also: you should be able to view the backups of a server from the admin side, in case of something ever happened. 

**Describe alternatives you've considered**
Manually editing :(

**Additional context**

**Comment by DaneEveritt** [comment]
Not interested in adding such functionality. If you want a backup to show up in the Panel, make it from the Panel.
