### ISSUE TITLE
Scheduled backups fail using Amazon S3 backend

### ISSUE THREAD

**Issue by Technoguyfication** [pterodactyl/panel#3311]
**Background (please complete the following information):**

* Panel or Wings: Panel
* Version of Panel/Wings: Panel 1.4.0 PHP 8.0.3
* Panel Logs: https://pastebin.com/Aby3PGJz
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 Chrome

**Describe the bug**
I'm using Amazon S3 as a storage backend. I can create manual backups just fine, but scheduled backup tasks are not creating a backup and causing the scheduled task to hang forever:

![](https://tkno.pw/3gTChAR)

The scheduled task started on April 15th, and this screenshot was taken April 29th. The task has been hanging for 2 weeks straight.

**To Reproduce**
Steps to reproduce this behavior:

1. Set up S3 as a backup storage backend
2. Create a manual backup
3. Observe that it works fine
4. Set a scheduled task to create a backup
5. Wait for the scheduled task to execute
6. Error: Scheduled task never completes and backup is never created

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

The backup should be created and the task should complete.

**Comment by Juha686** [comment]
Have you restarted the pteroq queue worker after setting up S3?

**Comment by Technoguyfication** [comment]
> Have you restarted the pteroq queue worker after setting up S3?

Yes, I've also updated since then to the latest version of the panel.

**Comment by DaneEveritt** [comment]
Not a bug with this software.

```
[2021-04-12 22:26:02] production.ERROR: SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `schedules` where `is_active` = 1 and `is_processing` = 0 and next_run_at <= NOW()) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `schedules` where `is_active` = 1 and `is_processing` = 0 and next_run_at <= NOW()) at /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php:678)
[stacktrace]
#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Database/Connection.php(752): Illuminate\\Database\\Connection->runQueryCallback()
...
#11 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Pterodactyl\\Console\\Commands\\Schedule\\ProcessRunnableCommand->handle()
...
#17 /var/www/pterodactyl/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
...
#23 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#24 /var/www/pterodactyl/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#25 {main}
```

**Comment by Technoguyfication** [comment]
@DaneEveritt  Then what is the bug with? How do I fix it? I have an unmodified panel and I'm using S3 which is supposed to be supported?

**Comment by Technoguyfication** [comment]
@DaneEveritt I just realized the log link I sent cut off the important part of the log at the end, please see this one: https://pastebin.com/Aby3PGJz

**Comment by DaneEveritt** [comment]
You're sending logs for 3 weeks ago. Without current logs I have no idea why it would not be working, but there is no reason a scheduled task would not run successfully but a manual run would. Sorry, no clue what the issue could be.

**Comment by Technoguyfication** [comment]
> You're sending logs for 3 weeks ago. Without current logs I have no idea why it would not be working, but there is no reason a scheduled task would not run successfully but a manual run would. Sorry, no clue what the issue could be.

I'm sending logs from so long ago because the task has been hanging for that long :/

I don't know why it's happening either, is there some way I can get more logs out of it? Or check logs from the queue worker specifically? All I know is backups work perfectly unless they're on a schedule, it sounds like the bug has to be somewhere in Pterodactyl for that behavior to happen.
