### ISSUE TITLE
There was an error validating the credentials provided for the websocket.

### ISSUE THREAD

**Issue by OneHitX** [pterodactyl/panel#3315]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installing this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in the closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

To obtain logs for the panel and wings the below commands should help with the retrieval of them.
Panel: tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99
Wings: sudo wings diagnostics

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**

* Panel or Wings: Both
* Version of Panel/Wings: Panel: 1.4.0 Wings: 1.4.1
* Panel Logs: https://ptero.co/iqivuregaz
* Wings Logs: http://bin.ptdl.co/reydp
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Windows 10 Chrome 90

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:38) ( NTS )

Wings: `uname -a` and `docker info` (your kernel version and information regarding docker)
Linux user 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
Steps to reproduce this behavior:

1. Go to 'Servers'
2. Click on 'My Servers'
3. See error

![image](https://user-images.githubusercontent.com/25916072/116769706-7e4d6000-aa14-11eb-9d7e-d4b107555cfd.png)
![image](https://user-images.githubusercontent.com/25916072/116769713-96bd7a80-aa14-11eb-9f54-03f70d61e7cf.png)

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

The problem occurs spontaneously after some time or always when a new node is added.

**Comment by DaneEveritt** [comment]
#3295
