### ISSUE TITLE
Server want start

### ISSUE THREAD

**Issue by eliaskyt** [pterodactyl/panel#3316]
Hi!
When i start a Server from Node it will not work.

Bugs:
1. Server is marked as offline, cant start. (directly after installation)
or
2. it installs, after install bug 1.

How can you help me?
Dear Wishes

**Comment by gOOvER** [comment]
Logs would be nice and i bet its not a Ptero Issue

**Comment by eliaskyt** [comment]
> Logs would be nice and i bet its not a Ptero Issue

Hey!
How i get the logs?
