### ISSUE TITLE
empty lines in the console

### ISSUE THREAD

**Issue by vaniron** [pterodactyl/panel#3317]
* Panel: 1.4.0
* Server's OS: Ubuntu 20.04.2 - minecraft sponge 1.12.2
* Your Computer's OS & Browser: W10 chrome, also tried on edge and mobile phone

**Describe the bug**
Empty lines are appearing in the console, refreshing the site magically repairs it for already generated lines.

**To Reproduce**
1. Open the console
2. Wait for the lines to appear
3. Refresh the site to delele already generated lines.

**Expected behavior**
Console without empty lines.

Problem:
![panel1](https://user-images.githubusercontent.com/17107410/116805009-a37cc400-ab23-11eb-8af9-c48b13a54782.png)

After refreshing the page, those lines are gone:
![panel2](https://user-images.githubusercontent.com/17107410/116805020-b4c5d080-ab23-11eb-8de6-60132aa23ec0.png)

I tried it with numerous browsers, even switching to mobile or trying with friend and still the same issue on all devices.
I am running minecraft sponge server but have seen some guy posted same issue on discord and he is running spigot so its not mc software related i think.

![178465475_286023723233181_4538344125307021440_n](https://user-images.githubusercontent.com/17107410/116805076-1a19c180-ab24-11eb-860f-b14677a3ce42.png)

**Comment by DaneEveritt** [comment]
I believe `--no-jline` or whatever the flag is fixes that. Its not a bug with this software that I find important enough to invest time into fixing.

**Comment by vaniron** [comment]
This problem was not present in 0.7 version of the panel, so there must be problem somewhere within the new version?
