### ISSUE TITLE
Make External Identifier Visible in Server List

### ISSUE THREAD

**Issue by Pankraz01** [pterodactyl/panel#3318]
![grafik](https://user-images.githubusercontent.com/19345513/116823004-3ba99600-ab82-11eb-9e20-cc784e26cc54.png)
It would be nice to have an extra column for `External Identifier`

**Comment by parkervcp** [comment]
Why is this needed? The external identifier exists for an api call to specify a server with it's own id system.

**Comment by trenutoo** [comment]
This might be useful for a quick search based on an external identifier, not sure? I doubt it's worth a PR as you can use the search feature which accepts external identifiers. You can edit the file at `/var/www/pterodactyl/resources/views/admin/servers/index.blade.php`

Add `<th>EXT.ID</th>
` and `<td><code title="{{ $server->external_id }}">{{ $server->external_id}}</code></td>`.into the existing table.

**Comment by DaneEveritt** [comment]
Closing this out, neat idea but as @parkervcp mentioned the external_id is really just for external systems to find servers based on what they're using. It has minimal if any relevance to the code within the Panel.
