### ISSUE TITLE
Add TMP folder option for the docker user

### ISSUE THREAD

**Issue by JamesDAdams** [pterodactyl/panel#3321]
**Is your feature request related to a problem? Please describe.**
yes, if we use pterodactyl in docker we don't have the possibility to change the tmp folder

**Describe the solution you'd like**
Add in wings -> config.go -> **type SystemConfiguration struct** a option to tmp folder

**Describe alternatives you've considered**
for now the only solution is use the default path

**Additional context**
For the Docker user

**Comment by DaneEveritt** [comment]
I do not understand what you're asking for here, do you want to use something other than `/tmp` as the... temp folder?

**Comment by JamesDAdams** [comment]
> I do not understand what you're asking for here, do you want to use something other than as the... temp folder?`/tmp`

yes i have another directory for my temp file on another disk

**Comment by DaneEveritt** [comment]
Just symlink them together? This feels like a really really strange use-case and isn't something that has ever come up before so I don't really think it would be highly beneficial to support, sorry.

Also, to my knowledge docker doesn't even support what you're asking for: https://docs.docker.com/storage/tmpfs
