### ISSUE TITLE
Transfer entirety of panel and/or wings

### ISSUE THREAD

**Issue by MilkMGN** [pterodactyl/panel#3324]
**Is your feature request related to a problem? Please describe.**
My problem is nitpicky but i just bought a new server to replace my old homelab one, and is a dell r710 so i can just stick the drive in, since that will wipe it, but i want to keep all my servers

**Describe the solution you'd like**
maybe a seperate script or something to copy all of the files and zip them/use ftp .etc to put panel/wings on the new server

**Describe alternatives you've considered**
resetting, copying manually, virtualising the entire drive.
**Additional context**

its probably a one use case so i understand if yall dont want to 
thanks for your time

**Comment by DaneEveritt** [comment]
This is really something you should be handling for your specific environment and use case.
