### ISSUE TITLE
B2/S3 Backups fail due to "context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

### ISSUE THREAD

**Issue by yashendra2797** [pterodactyl/panel#3326]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**

* Panel or Wings: Wings I think, though the error shows up in the Panel
* Version of Panel/Wings: Panel 1.4.1 | Wings: 1.4.2
* Panel Logs: https://bin.ptdl.co/nx4mu/
* Wings Logs: https://ptero.co/semaxohuhu
* Server's OS: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64) (Panel and Wings are on separate machines, but same OS)
* Your Computer's OS & Browser: macOS Big Sur v11.2.3 (20D91) | Safari Version 14.0.3 (16610.4.3.1.7)

**Describe the bug**

Every time I create a backup, it fails. Can't find any errors in particular in Wings log, but Panel logs has this error:

```
INFO: [May  5 19:04:16.285] creating backup for server adapter=s3 backup=7bcb2f87-6c16-4ac2-b49f-1c3b64420d94 path=/var/lib/pterodactyl/backups/7bcb2f87-6c16-4ac2-b49f-1c3b64420d94.tar.gz request_id=718e775e-f72b-4f52-b802-896198c734a4 server=178216b5-e4a9-471d-821b-c63fc5e52b98
 INFO: [May  5 19:06:25.082] created backup successfully adapter=s3 backup=7bcb2f87-6c16-4ac2-b49f-1c3b64420d94 request_id=718e775e-f72b-4f52-b802-896198c734a4 server=178216b5-e4a9-471d-821b-c63fc5e52b98
 INFO: [May  5 19:06:55.508] notified panel of failed backup state backup=7bcb2f87-6c16-4ac2-b49f-1c3b64420d94 server=178216b5-e4a9-471d-821b-c63fc5e52b98
ERROR: [May  5 19:06:55.508] router: failed to generate server backup error=backup: error while generating server backup: http: request creation failed: Get "https://panel.sneakycraft.com/api/remote/backups/7bcb2f87-6c16-4ac2-b49f-1c3b64420d94?size=136183693": context deadline exceeded (Client.Timeout exceeded while awaiting headers) request_id=718e775e-f72b-4f52-b802-896198c734a4 server_id=178216b5-e4a9-471d-821b-c63fc5e52b98
```

(pls check panel logs for more)

I am trying to backup to B2 and its a new empty bucket with 0bytes of data in it. Data is never changed. I have tried disabling Cloudflare and this error still happens. I have asked for help for weeks on the Discord and no one's given me a response, so I'm posting here.

Panel is on a $10 Digital Ocean droplet, Wings is on a Ryzen 3600X server.

Please let me know if there is anything else I can do, I am willing to troubleshoot this any way possible. Thanks a lot. <3 

Panel: `php -v` (the php version in use). `PHP 8.0.5 (cli) (built: May  3 2021 11:30:57) ( NTS )`
Wings: `uname -a` and `docker info` (your kernel version and information regarding docker)
`Linux eu1.sneakycraft.com 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 23
  Running: 4
  Paused: 0
  Stopped: 19
 Images: 21
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-72-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.81GiB
 Name: eu1.sneakycraft.com
 ID: 4V2H:NSIF:FDC3:HERK:WDLT:LYBX:KMRY:OCIP:QMKY:ZZKH:5BPG:MOXM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```
**To Reproduce**
Steps to reproduce this behavior:

1. Go to 'Backup'
2. Create New Backup
3. Wait a few minutes
4. Backup marked as "Failed"

**Expected behavior**
Backup is successful.

**Comment by yashendra2797** [comment]
.env error.

Should have been `AWS_ENDPOINT=https://s3.us-west-001.backblazeb2.com` not `AWS_ENDPOINT=http://s3.us-west-001.backblazeb2.com`. Note the lack of `s` in my own config.

Much love to everyone in the ptero team, sorry for wasting everyone's time.

**Comment by DaneEveritt** [comment]
Ah, confusing error but reading with that context it makes sense that it got stuck trying to connect to the endpoint and not during the upload phase.
