### ISSUE TITLE
Websocket problem

### ISSUE THREAD

**Issue by Kaesewuerfel** [pterodactyl/panel#3327]
**Background (please complete the following information):**

* Panel or Wings: Panel 1.3.2 and Wings 1.3.2
* Version of Panel/Wings: 1.3.2
* Panel Logs: nothing suspicous
* Wings Logs: https://ptero.co/uwoxovihah.pl
* Server's OS: Debian 10
* Your Computer's OS & Browser: Ubuntu and Windows, Firefox & Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: PHP 7.4.16 (cli) (built: Mar  5 2021 08:36:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies
Wings: Kernel: `Linux server02 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux` and Docker Infos: `Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 446
  Running: 51
  Paused: 0
  Stopped: 395
 Images: 37
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-16-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 30
 Total Memory: 492.1GiB
 Name: game02
 ID: HH6O:IBHE:FBKK:LKEI:4RZ5:VYQ5:GHBW:XVPD:VNSK:RPLJ:5Q4O:FGPX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`

**To Reproduce**
Steps to reproduce this behavior:

Sorry, but I don't really know to reproduce this, because this bug was just there all of a sudden.

**Expected behavior**
When this bug occurs, neither the console, stats nor their graphs update. Only a reload like F5 will update the data. If you press stop to stop the server, everything is also updated only after a browser reload.

**Comment by notAreYouScared** [comment]
Can you update to the latest version and see if the issue still persists

**Comment by DaneEveritt** [comment]
You've also not described the bug at all, so I'm not really sure what I'm supposed to be looking for. "websocket problem" is not a descriptive error.
