### ISSUE TITLE
Schedules not working

### ISSUE THREAD

**Issue by hardixnph** [pterodactyl/panel#3330]
* Panel or Wings: Both I think
* Version of Panel/Wings: 1.4.1 for Panel and 1.4.2 for Wings
* Panel Logs: I don't have .log file for 05.06.2021
* Wings Logs: https://ptero.co/ipajuvahol
* Server's OS: Ubuntu 20.04 Focal
* Your Computer's OS & Browser: Windows (now I from Android) and I'm using Google Chrome

**Describe the bug**
PHP 8.0.3 (cli)
Linux jbromania 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Docker App (Docker Inc., v0.9.1-beta3)

My scheludes status is **Processing** all the time, when I hit Run button, the task that I created is working. 

**To Reproduce**
Make a schedule, set a task and you will get status **Processing** forever.

**Expected behavior**
The task that I created is for auto-backup and is not working. I tried with restart too.

![Screenshot_20210506-065633_Chrome](https://user-images.githubusercontent.com/48999517/117240913-8ce3af00-ae3a-11eb-85d0-e117d8d0b775.jpg)

**Comment by trenutoo** [comment]
What is the status of your pteroq service? Is it running, if so have you tried restarting it?

**Comment by hardixnph** [comment]
> What is the status of your pteroq service? Is it running, if so have you tried restarting it?

They were running, I restarted the service and now it's working, thanks!
