### ISSUE TITLE
Transfers don't work - ServerTransferController::processFailedTransfer() fails with NULL argument being given

### ISSUE THREAD

**Issue by elmorti** [pterodactyl/panel#3332]
* Panel or Wings: Both
* Version of Panel/Wings: v1.4.1 / v1.4.2
* Panel Logs:

[2021-05-06 21:22:20] production.ERROR: Pterodactyl\Http\Controllers\Api\Remote\Servers\ServerTransferController::processFailedTransfer(): Argument #1 ($transfer) must be of type Pterodactyl\Models\ServerTransfer, null given, called in /home/zucchini/panel/app/Http/Controllers/Api/Remote/Servers/ServerTransferController.php on line 87 {"exception":"[object] (TypeError(code: 0): Pterodactyl\\Http\\Controllers\\Api\\Remote\\Servers\\ServerTransferController::processFailedTransfer(): Argument #1 ($transfer) must be of type Pterodactyl\\Models\\ServerTransfer, null given, called in /home/zucchini/panel/app/Http/Controllers/Api/Remote/Servers/ServerTransferController.php on line 87 at /home/zucchini/panel/app/Http/Controllers/Api/Remote/Servers/ServerTransferController.php:197)
[stacktrace]
#0 /home/zucchini/panel/app/Http/Controllers/Api/Remote/Servers/ServerTransferController.php(87): Pterodactyl\\Http\\Controllers\\Api\\Remote\\Servers\\ServerTransferController->processFailedTransfer(NULL)
#1 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Pterodactyl\\Http\\Controllers\\Api\\Remote\\Servers\\ServerTransferController->archive(Object(Illuminate\\Http\\Request), '19f794ac-d68d-4...')
#2 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('archive', Array)
#3 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Pterodactyl\\Http\\Controllers\\Api\\Remote\\Servers\\ServerTransferController), 'archive')
#4 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#5 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->run()
#6 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#7 /home/zucchini/panel/app/Http/Middleware/Api/Daemon/DaemonAuthenticate.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Pterodactyl\\Http\\Middleware\\Api\\Daemon\\DaemonAuthenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#13 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#14 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#15 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#16 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#17 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home/zucchini/panel/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /home/zucchini/panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#33 /home/zucchini/panel/public/index.php(68): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#34 {main}
"}

* Wings Logs:

Destination Daemon Node:

daemon_1  | ERROR: [May  6 19:21:33.868] failed to reset server states on Panel: some instances may be stuck in an installing/restoring state unexpectedly error=remote: failed to reset server state on Panel: Error response from Panel: QueryException: An unexpected error was encountered while processing this request, please try again. (HTTP/500)
daemon_1  |
daemon_1  | Stacktrace:
daemon_1  | Error response from Panel: QueryException: An unexpected error was encountered while processing this request, please try again. (HTTP/500)
daemon_1  | github.com/pterodactyl/wings/remote.(*client).request.func1
daemon_1  |     /home/runner/work/wings/wings/remote/http.go:153
daemon_1  | github.com/cenkalti/backoff/v4.RetryNotifyWithTimer
daemon_1  |     /home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:55
daemon_1  | github.com/cenkalti/backoff/v4.RetryNotify
daemon_1  |     /home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34
daemon_1  | github.com/cenkalti/backoff/v4.Retry
daemon_1  |     /home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:28
daemon_1  | github.com/pterodactyl/wings/remote.(*client).request
daemon_1  |     /home/runner/work/wings/wings/remote/http.go:133
daemon_1  | github.com/pterodactyl/wings/remote.(*client).Post
daemon_1  |     /home/runner/work/wings/wings/remote/http.go:93
daemon_1  | github.com/pterodactyl/wings/remote.(*client).ResetServersState
daemon_1  |     /home/runner/work/wings/wings/remote/servers.go:61
daemon_1  | github.com/pterodactyl/wings/cmd.rootCmdRun.func5
daemon_1  |     /home/runner/work/wings/wings/cmd/root.go:272
daemon_1  | runtime.goexit
daemon_1  |     /opt/hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371
daemon_1  |
daemon_1  | remote: failed to reset server state on Panel
daemon_1  |
daemon_1  |

Source Daemon Node:

daemon_1  | ERROR: [May  6 19:19:35.250] failed to reset server states on Panel: some instances may be stuck in an installing/restoring state unexpectedly error=remote: failed to reset server state on Panel: Error response from Panel: QueryException: An unexpected error was encountered while processing this request, please try again. (HTTP/500)
daemon_1  |
daemon_1  | Stacktrace:
daemon_1  | Error response from Panel: QueryException: An unexpected error was encountered while processing this request, please try again. (HTTP/500)
daemon_1  | github.com/pterodactyl/wings/remote.(*client).request.func1
daemon_1  |     /home/runner/work/wings/wings/remote/http.go:153
daemon_1  | github.com/cenkalti/backoff/v4.RetryNotifyWithTimer
daemon_1  |     /home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:55
daemon_1  | github.com/cenkalti/backoff/v4.RetryNotify
daemon_1  |     /home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34
daemon_1  | github.com/cenkalti/backoff/v4.Retry
daemon_1  |     /home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:28
daemon_1  | github.com/pterodactyl/wings/remote.(*client).request
daemon_1  |     /home/runner/work/wings/wings/remote/http.go:133
daemon_1  | github.com/pterodactyl/wings/remote.(*client).Post
daemon_1  |     /home/runner/work/wings/wings/remote/http.go:93
daemon_1  | github.com/pterodactyl/wings/remote.(*client).ResetServersState
daemon_1  |     /home/runner/work/wings/wings/remote/servers.go:61
daemon_1  | github.com/pterodactyl/wings/cmd.rootCmdRun.func5
daemon_1  |     /home/runner/work/wings/wings/cmd/root.go:272
daemon_1  | runtime.goexit
daemon_1  |     /opt/hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371
daemon_1  |
daemon_1  | remote: failed to reset server state on Panel
daemon_1  |
daemon_1  |
daemon_1  |  INFO: [May  6 19:21:32.809] successfully created server transfer archive, notifying panel.. server=19f794ac-d68d-4195-8e93-8c1cf878428b
daemon_1  | ERROR: [May  6 19:21:54.580] panel returned an error when notifying it of a successful archive status error=Error response from Panel: TypeError: An unexpected error was encountered while processing this request, please try again. (HTTP/500) server=19f794ac-d68d-4195-8e93-8c1cf878428b
daemon_1  | ERROR: [May  6 19:22:20.887] panel returned an error when notifying it of a failed archive status error=Error response from Panel: TypeError: An unexpected error was encountered while processing this request, please try again. (HTTP/500) server=19f794ac-d68d-4195-8e93-8c1cf878428b

* Server's OS:

CentOS Linux release 8.3.2011

* Your Computer's OS & Browser:

Windows 10 Pro / Edge

**Describe the bug**

When trying to run a server transfer, Laravel complains of null argument given to the processFailedTransfer() call:

[2021-05-06 21:22:20] production.ERROR: Pterodactyl\Http\Controllers\Api\Remote\Servers\ServerTransferController::processFailedTransfer(): Argument #1 ($transfer) must be of type Pterodactyl\Models\ServerTransfer, null given

This is also not well transpired to the nodes (transferer and transferee) which they only see a 500 coming from the panel.

Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Wings: `uname -a` and `docker info` (your kernel version and information regarding docker)

elmorti006-wings-node [ ~/github/zucchini-containers/wings ]$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 6
  Running: 4
  Paused: 0
  Stopped: 2
 Images: 18
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-240.10.1.el8_3.x86_64
 Operating System: CentOS Linux 8
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 7.586GiB
 Name: elmorti006-wings-node
 ID: OSQJ:W3EP:FX2R:ITOD:K7TF:MDU2:LYCJ:G6C2:JX2K:6XVE:P4WH:6DMK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support

elmorti006-wings-node [ ~/github/zucchini-containers/wings ]$ uname -a
Linux elmorti006-wings-node 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

elmorti004-wings-node [ ~ ]$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 20.10.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-240.10.1.el8_3.x86_64
 Operating System: CentOS Linux 8
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.65GiB
 Name: elmorti004-wings-node
 ID: 6MWD:VGWU:TORF:XXQ5:TEID:BOHK:F3AI:6EKT:3LYI:RQ7B:OUTG:I4FG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

elmorti004-wings-node [ ~ ]$ uname -a
Linux elmorti004-wings-node 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Panel PHP:
bash-5.1$ php -v
PHP 8.0.2 (cli) (built: Feb  5 2021 00:39:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies

**To Reproduce**
1. Have 2 working nodes, where you are sure you can spawn new servers and have available allocations.
2. Go to one of the servers.
3. Click on Manage
4. Click on Transfer Server
5. Select the other node and one of the available allocations
6. Click Confirm
7. Check the logs of Laravel in the Panel and Wings

**Expected behavior**

Transfer process should be initiated with no issues as it used to be.

**Comment by notAreYouScared** [comment]
I'm not able to reproduce this, Might be an issue related to the docker'd version of wings and the panel?

I was able to move a Minecraft server between two nodes, A->B B->A, without any issues.


```
Thu, 06 May 2021 15:59:35 EDT [Pterodactyl Transfer System] [Source Node]: Attempting to archive server...
Thu, 06 May 2021 15:59:36 EDT [Pterodactyl Transfer System] [Source Node]: Successfully created archive, attempting to notify panel..
Thu, 06 May 2021 15:59:36 EDT [Pterodactyl Transfer System] [Source Node]: Successfully notified panel of successful archive status
container@pterodactyl~ Server marked as offline...
Thu, 06 May 2021 21:59:38 CEST [Pterodactyl Transfer System] [Target Node]: Got server archive response from remote node. (Content-Length: 778820068)
Thu, 06 May 2021 21:59:38 CEST [Pterodactyl Transfer System] [Target Node]: Creating local archive file...
Thu, 06 May 2021 21:59:38 CEST [Pterodactyl Transfer System] [Target Node]: Writing archive to disk...
Thu, 06 May 2021 21:59:41 CEST [Pterodactyl Transfer System] [Target Node]: Downloading [=========                ] 295.6 MiB / 742.7 MiB
Thu, 06 May 2021 21:59:44 CEST [Pterodactyl Transfer System] [Target Node]: Downloading [====================     ] 608.1 MiB / 742.7 MiB
Thu, 06 May 2021 21:59:45 CEST [Pterodactyl Transfer System] [Target Node]: Downloading [=========================] 742.7 MiB / 742.7 MiB
Thu, 06 May 2021 21:59:45 CEST [Pterodactyl Transfer System] [Target Node]: Successfully wrote archive to disk.
Thu, 06 May 2021 21:59:45 CEST [Pterodactyl Transfer System] [Target Node]: Verifying checksum of downloaded archive...
Thu, 06 May 2021 21:59:47 CEST [Pterodactyl Transfer System] [Target Node]: Creating server environment, this could take a while..
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/core 
Digest: sha256:c0139c52f8ae3581e64c5d598b1d4da7328599a7abb41b76d66487900a3396f7 
Status: Image is up to date for quay.io/pterodactyl/core:java 
[Pterodactyl Daemon]: Finished pulling Docker container image
Thu, 06 May 2021 21:59:56 CEST [Pterodactyl Transfer System] [Target Node]: Server environment has been created, extracting transfer archive..
Thu, 06 May 2021 21:59:56 CEST [Pterodactyl Transfer System] [Target Node]: Archive extracted successfully.
Thu, 06 May 2021 21:59:56 CEST [Pterodactyl Transfer System] [Target Node]: Transfer completed.
Thu, 06 May 2021 22:00:08 CEST [Pterodactyl Transfer System] [Source Node]: Attempting to archive server...
Thu, 06 May 2021 22:00:08 CEST [Pterodactyl Transfer System] [Source Node]: Successfully created archive, attempting to notify panel..
Thu, 06 May 2021 22:00:08 CEST [Pterodactyl Transfer System] [Source Node]: Successfully notified panel of successful archive status
container@pterodactyl~ Server marked as offline...
Thu, 06 May 2021 16:00:10 EDT [Pterodactyl Transfer System] [Target Node]: Got server archive response from remote node. (Content-Length: 778718239)
Thu, 06 May 2021 16:00:10 EDT [Pterodactyl Transfer System] [Target Node]: Creating local archive file...
Thu, 06 May 2021 16:00:10 EDT [Pterodactyl Transfer System] [Target Node]: Writing archive to disk...
Thu, 06 May 2021 16:00:13 EDT [Pterodactyl Transfer System] [Target Node]: Downloading [=====                    ] 156.4 MiB / 742.6 MiB
Thu, 06 May 2021 16:00:16 EDT [Pterodactyl Transfer System] [Target Node]: Downloading [==========               ] 318.6 MiB / 742.6 MiB
Thu, 06 May 2021 16:00:19 EDT [Pterodactyl Transfer System] [Target Node]: Downloading [================         ] 479.9 MiB / 742.6 MiB
Thu, 06 May 2021 16:00:22 EDT [Pterodactyl Transfer System] [Target Node]: Downloading [=====================    ] 642.7 MiB / 742.6 MiB
Thu, 06 May 2021 16:00:24 EDT [Pterodactyl Transfer System] [Target Node]: Downloading [=========================] 742.6 MiB / 742.6 MiB
Thu, 06 May 2021 16:00:24 EDT [Pterodactyl Transfer System] [Target Node]: Successfully wrote archive to disk.
Thu, 06 May 2021 16:00:24 EDT [Pterodactyl Transfer System] [Target Node]: Verifying checksum of downloaded archive...
Thu, 06 May 2021 16:00:26 EDT [Pterodactyl Transfer System] [Target Node]: Creating server environment, this could take a while..
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/core 
Digest: sha256:c0139c52f8ae3581e64c5d598b1d4da7328599a7abb41b76d66487900a3396f7 
Status: Image is up to date for quay.io/pterodactyl/core:java 
[Pterodactyl Daemon]: Finished pulling Docker container image
Thu, 06 May 2021 16:00:27 EDT [Pterodactyl Transfer System] [Target Node]: Server environment has been created, extracting transfer archive..
Thu, 06 May 2021 16:00:28 EDT [Pterodactyl Transfer System] [Target Node]: Archive extracted successfully.
Thu, 06 May 2021 16:00:33 EDT [Pterodactyl Transfer System] [Target Node]: Transfer completed.
```

**Comment by elmorti** [comment]
It is quite possible, my infra setup is a bit more complex since I am running the nodes on a containerized virtual machine (QEMU under Podman for the VMs that are running CentOS for Wings and Docker) so at the beginning I was suspecting of some networking issue but since the Laravel log was complaining about `ServerTransferController::processFailedTransfer(): Argument #1 ($transfer) must be of type Pterodactyl\Models\ServerTransfer, null given` I thought that somehow the code logic is unable to get the right node/server information to pass to the function, thus getting a null reference. I might need to setup a proper CNI to make this work but I'll check also why the null reference is happening, maybe something can be arranged in the code to actually support the setup. Both nodes are reachable between them by proper DNS resolving so I believe that, thought my setup is not the most common, it could be supported. I'll try to do my part of research though :) (I have zero experience with PHP and Laravel beyond configuration of apps)

**Comment by elmorti** [comment]
I think I am gonna close this issue and double check whether my particular network infra is not causing any problem.

**Comment by lindlaaa** [comment]
Little late to the part here. I had the EXACT same issue, but my error was a 404, not a 500.
```ERROR: [Jan 18 19:45:16.536] panel returned an error when notifying it of a successful archive status error=Error response from Panel: DaemonConnectionException: An error occurred on the remote host: There was an error while communicating with the machine running this server. This error has been logged, please try again. (code: 404) (request_id: bd8a2753-7a7b-4512-a6b9-11fae8704354). (request id: bd8a2753-7a7b-4512-a6b9-11fae8704354) (HTTP/404) server=df49dc7a-b3e0-4c8a-a5be-648562b47aeb```

I updated the panel and wings and the transfer worked. The fact that it gave a 404 is still confusing, though.
