### ISSUE TITLE
A place shows you that how many disk usage does your node use

### ISSUE THREAD

**Issue by YTRemRem** [pterodactyl/panel#3337]
**Is your feature request related to a problem? Please describe.**
As the title said it would be great to show **current** disk usage for the node in the panel, not a problem just a feature that want to be added in the pterodactyl panel

**Describe the solution you'd like**
Count the total file size for the nodes

**Additional context**
Nope :)

**Comment by DaneEveritt** [comment]
Yeah I'm not writing code to do what you can handle with external monitoring tools far more effectively, sorry.
