### ISSUE TITLE
In panel database viewer

### ISSUE THREAD

**Issue by snaildos** [pterodactyl/panel#3338]
**Is your feature request related to a problem? Please describe.**
Instead of viewing databases with eggs such as phpadmin, you should be able to view the database with a mini viewer in the panel.

**Describe the solution you'd like**
It be pretty cool to go to 'database' and click on your database and get a view of it. (Like PHPmyadmin)

**Describe alternatives you've considered**
Obviously you can use complex eggs, but it would be cool without that.

Thanks. :P

**Comment by DaneEveritt** [comment]
I'm not building that, sorry.

**Comment by snaildos** [comment]
I understand. Hah. Thanks for the reply tho. :)
