### ISSUE TITLE
Ability to access to Databases, Schedules, Users, Network and Startup when reinstalling the server

### ISSUE THREAD

**Issue by DrakMC** [pterodactyl/panel#3342]
**Is your feature request related to a problem? Please describe.**
If my server is being installed or reinstalled, I can't use any sections in the server administration.

**Describe the solution you'd like**
It would be good to access to Databases, Schedules, Users, Network and Startup when reinstalling the server.

**Comment by ririko5834** [comment]
Yes, admins should be able to use this when server is running reinstall script

**Comment by DaneEveritt** [comment]
They are disabled specifically because Wings will not accept updates to things while it is installing, and I don't want users to get stuck in a middle state where Wings cannot properly take actions or self-update the server instance as a result.
