### ISSUE TITLE
Maintenance mode doesn't work

### ISSUE THREAD

**Issue by SaintWish** [pterodactyl/panel#3344]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**

* Panel or Wings: Panel
* Version of Panel/Wings: 1.4.1
* Panel Logs: There's no logs for today's date.
* Wings Logs: https://ptero.co/vogosageye
* Server's OS: Debian 10 for the panel, Ubuntu 18 for node.
* Your Computer's OS & Browser: Firefox & Chrome on Windows 10

**Describe the bug**
When I enable maintenance mode on my node it doesn't prevent the users from using their servers on that node at all. The users are still able to do everything they'd normally be able to do.
Please provide additional information too, depending on what you have issues with:
Panel: ``PHP 8.0.5 (cli) (built: May  3 2021 11:58:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.5, Copyright (c), by Zend Technologies``
Wings: `Linux lax1 4.15.0-121-generic #123-Ubuntu SMP Mon Oct 5 16:16:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` and https://ptero.co/imupojovoz.php

**To Reproduce**
Steps to reproduce this behavior:

1. Go to 'Admin > Node > Settings'
2. Check 'Maintenance Mode > Enabled'
3. Click 'Save Changes'
4. Node shows as being under maintenance in via Admin side, but clients are still able to use servers as normal.

**Expected behavior**
I expected the servers on the node that's in maintenance to be un-accessible for the clients to use.

**Comment by trenutoo** [comment]
Maintenance mode only disables automated provision to the node as far as I know.

**Comment by SaintWish** [comment]
That might be the case, I never tested that. Though, I thought it would disable user's access because of what it says under the maintenance mode enable thing.

**Comment by DaneEveritt** [comment]
#3168 #2705
