### ISSUE TITLE
Minecraft's "Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by derech1e** [pterodactyl/panel#3346]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installing this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in the closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

To obtain logs for the panel and wings the below commands should help with the retrieval of them.
Panel: tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99
[laravel-2021-05-11.log](https://github.com/pterodactyl/panel/files/6461245/laravel-2021-05-11.log)

Wings: sudo wings diagnostics
https://ptero.co/cepohukefi

**Background (please complete the following information):**

* Panel or Wings: Both?
* Version of Panel/Wings: 1.4.1/ 1.4.0
* Panel Logs: [laravel-2021-05-11.log](https://github.com/pterodactyl/panel/files/6461245/laravel-2021-05-11.log)
* Wings Logs: https://ptero.co/cepohukefi
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 & Chrome

**Describe the bug**
This issue referes to #2138. It is a issue that now occurs with multiple users and is slowly becoming a possibly bigger problem.
For a near description you must read #2138 and **especially the comments below the issue.**

Maybe I am wrong and there is already a solution to this problem. If so, I would be very happy to receive an answer.

Php version: 
```
PHP 8.0.3 (cli) (built: Mar  5 2021 08:38:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
```

Wings: 
uname: `Linux rs-zap105094-3 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux`
docker info: 
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 9
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-16-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.791GiB
 Name: rs-zap105094-3
 ID: QIVV:3CBC:5XDD:DLQG:MBRW:3EEP:OI3S:LRLF:4BLB:EAIO:SSED:MHU6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
**To Reproduce**
Steps to reproduce this behavior:

1. Setup a Minecraft Server with the default egg.
2. Try to connect to the server. It will kick you after a few seconds.
3. Setup a Minecraft Server manuall on the VM  directly.
4. Try to connect to the server. It wont kick you. 

**Expected behavior**
The player should not be kicked after a while.

**Comment by DaneEveritt** [comment]
No one has yet proven this has anything to do with this software, please do not open duplicate issues like this.

I do not have the time or resources available to investigate things like this that affect a tiny fraction of users out of the thousands that are able to run their servers successfully. Unless someone is able to take time and point to a definitive problem and at least give a solid attempt at identifying a potential issue that other issue will remain closed as there is a high probability it is due to factors outside the control of Pterodactyl.

**Comment by PetKCH** [comment]
I've tried multiple hosts that offer Pterodactyl panel interface and no matter the location I am the "victim" of these disconnects. If you wish to use my internet connection for debugging, figuring it out, please let me know I am of service.

**Comment by derech1e** [comment]
> I've tried multiple hosts that offer Pterodactyl panel interface and no matter the location I am the "victim" of these disconnects. If you wish to use my internet connection for debugging, figuring it out, please let me know I am of service.

Like that idea. Maybe you need to contact @DaneEveritt directly.
