### ISSUE TITLE
Process bar for status on transfer

### ISSUE THREAD

**Issue by FoksVHox** [pterodactyl/panel#3347]
**Is your feature request related to a problem? Please describe.**
When transferring it isn't clear in what state the transfer is in, this is especially for larger servers, with more complex files.

**Describe the solution you'd like**
It would be cool to have a process bar to see how much it has completed the transfer. I'm aware that the transfer process has more steps on is more complex than it sounds like.

**Describe alternatives you've considered**
None really, maybe using the console, but it isn't really getting updated before it has archived successfully.

**Additional context**
![image](https://user-images.githubusercontent.com/37844753/117886105-06eabc80-b2af-11eb-9f3d-97ff1d6907a9.png)

**Comment by snaildos** [comment]
100% totally agree. This would be amazing.

**Comment by matthewpi** [comment]
I don't see how this is useful, all it does is give a false sense of progress.  The console logs should be more than enough and I have thought about adding more information during the archiving process as it can seem like nothing is being done if there hasn't been any output for a long time.

**Comment by DaneEveritt** [comment]
Kinda agree with @matthewpi here, it would turn into Apple's infamous progress bars where there is zero indication what is happening. Right now we just don't have the system setup to support this effectively, so I'm just going to close this.
