### ISSUE TITLE
Network limit per server

### ISSUE THREAD

**Issue by snaildos** [pterodactyl/panel#3352]
**Is your feature request related to a problem? Please describe.**
I really don't want people killing my network. It be epic to have a mb/s cap.

**Describe the solution you'd like**
Be able to create network caps on per servers, or every server on default creation.

**Describe alternatives you've considered**
None, except slowing the whole server down. Don't really want to do that.

**Additional context**
Nope.

**Comment by parkervcp** [comment]
Docker doesn't support a bandwidth limiter like you are asking for.

**Comment by snaildos** [comment]
*Oh no*. That's not good. alright then. I'll close this, if there is no way, But can someone help me with a sort of "limiter?".
I'm running my servers at a office, I don't want me getting the whole office network just ddosed.

**Comment by parkervcp** [comment]
You would need to look into linux utilities to do that.

**Comment by snaildos** [comment]
Alright then. Thank you for your time. :)
