### ISSUE TITLE
Choose where S3 backups go based on backup size

### ISSUE THREAD

**Issue by ohaitrans** [pterodactyl/panel#3354]
**Is your feature request related to a problem? Please describe.**
Cheaper S3-compatible storage providers are cheaper, but large backups often fail with them. If they don't fail, large backups still take unacceptably long because these providers are slower. Because of this, more expensive storage has to be used for all backups just so that the few very large backups don't fail and are completed in an acceptable timeframe, even though most backups, which are small, would be fine with cheaper storage.

**Describe the solution you'd like**
It would be nice if Pterodactyl could be configured so different size backups go to different places. For example, being able to configure it such that backups <5GB go to B2, <50GB go to OVH, everything else goes to AWS, or something like that.

**Comment by matthewpi** [comment]
No.

**Comment by DaneEveritt** [comment]
You probably can configure this for your own instance, but this is an incredible niche request which is why we're not going to build this for general consumption.

**Comment by ohaitrans** [comment]
Fair enough, but enough people have had issues with large backups that I wouldn't agree it's too niche.

**Comment by DaneEveritt** [comment]
That is something to fix with the software, not make more complicated.
