### ISSUE TITLE
Minor Bug | File Manager - Cannot interact with files inline with the mass actions pop-up

### ISSUE THREAD

**Issue by MackenzieMolloy** [pterodactyl/panel#3355]
**Background (please complete the following information):**

* Panel or Wings: Panel
* Version of Panel/Wings: 1.4.1
* Panel Logs:  https://bin.ptdl.co/j14u8/

* Wings Logs: https://ptero.co/oribuzuzit
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Chrome

**Describe the bug**

When having the mass actions pop-up at the bottom of the screen in the file manager, you cannot interact with any of the files within its horizontal axis.

https://user-images.githubusercontent.com/48184419/118364012-adc0a880-b58e-11eb-8c50-3b1c1dd98c33.mp4

Panel: 7.4.14
Wings: 
- Docker info: https://paste.helpch.at/oqonokugun.js
- Uname -a: https://paste.helpch.at/zewaqotuxo.nginx

**To Reproduce**

1. Go to the file manager of a server
2. Have enough files to cover beyond the bottom of the screen
3. Select at least 1 file (the check box)
4. Then try to select any files inline with the mass actions pop-up

**Expected behavior**

You should be able to select files inline with the mass actions pop-up

**Comment by willypro7** [comment]
Same here
