### ISSUE TITLE
S3 backups fail on large servers

### ISSUE THREAD

**Issue by Sabinno** [pterodactyl/panel#3356]
**Background:**

* Panel or Wings: Wings in Docker
* Version of Panel/Wings: 1.4.1/1.4.2 (Docker)
* Panel Logs: https://mcpaste.io/4721c9795ea815c5 (nothing of value here)
* Wings Logs: https://mcpaste.io/5cd9d2fcb514abda
* Server's OS: CentOS 8.3 stable (not Stream)
* Your Computer's OS & Browser: Microsoft Windows 10, Microsoft Edge (Chromium)

**Describe the bug**
When backing up large servers, S3 backups fail inexplicably. Granted, backups fail with local storage as well. Perhaps this is due to Ptero "timing out" and thinking backups fail after a long period of time? Note that the backup in question here took nearly an hour to complete, as I'm assuming the S3 backup system still uses local storage first -- that being on a 5400rpm HDD.

**Addl info:**
Wings:
`uname -a`: Linux centos-01 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Apr 8 19:01:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`docker info`: https://mcpaste.io/f9139f5dd0cc13dd

**To Reproduce**
Steps to reproduce this behavior:

1. Create a large server, maybe 75GB or so in my case
2. Back up to S3 (Linode, but should not matter whatsoever) on a server running rather slow HDD storage
3. Watch it fail about 1 hour later!

**Expected behavior**
Successful backups.

**Comment by DaneEveritt** [comment]
duplicate #3334
