### ISSUE TITLE
Wings listener does not start (runc related)

### ISSUE THREAD

**Issue by philip-ulrich** [pterodactyl/panel#3358]
*Background (please complete the following information):**

* Panel or Wings: Wings
* Version of Panel/Wings: 1.4.2
* Panel Logs: N/A
* Wings Logs: https://ptero.co/ikaduluxof.cs
* Server's OS: Ubuntu 20.04.2 LTS
* Your Computer's OS & Browser: N/A

**Describe the bug**
When starting wings, the daemon stops at preparing/getting status of docker. It never starts the listener for the api nor sftp. I have attempted to restart quite a number of times and once restarted I have let it sit overnight. The process is still running, but it never starts the listeners.

```
$ uname -a
Linux gs2 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 15
  Running: 12
  Paused: 0
  Stopped: 3
 Images: 25
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-72-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.8GiB
 Name: gs2
 ID: KWVG:FUMK:3JTM:X4HH:ZLZM:WL6P:HPQL:26IW:JILL:NYPC:TD7Y:XGGN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: [redacted]
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**To Reproduce**
Not sure if it's reproducible, but this is what lead to the issue: 

After upgrading to daemon 1.4.2 - the first run the daemon started up and working for roughly 15 minutes, but would not start a docker container because there was supposedly a pending power action (there wasn't). I gave it about 10 minutes to sort itself out and restarted wings.

Wings refuses to come up ever since. See bug description for further details on what that looks like.

**Expected behavior**
```
May 15 17:59:30 Ubuntu-2004-focal-64-minimal wings[81144]:  INFO: [May 15 17:59:30.749] configuring internal webserver host_address=0.0.0.0 host_port=8080 use_auto_tls=false use_ssl=true
May 15 17:59:30 Ubuntu-2004-focal-64-minimal wings[81144]:  INFO: [May 15 17:59:30.750] updating server states on Panel: marking installing/restoring servers as normal
May 15 17:59:30 Ubuntu-2004-focal-64-minimal wings[81144]:  INFO: [May 15 17:59:30.750] sftp server listening for connections listen=0.0.0.0:2022
```

**Comment by philip-ulrich** [comment]
I was finally able to schedule another maintenance and a server restart seems to have "fixed" it. It appears as if there is something related to the start up that can cause the process to not boot up though. Likely related to docker and getting container statuses.

**Comment by philip-ulrich** [comment]
I was able to reproduce it by adding a new server - trying to start it - getting an error saying there is a pending power action (there is not). I restart wings. Wings never comes up, same error.

**Comment by philip-ulrich** [comment]
This is what is showing in the logs before the restart if it helps.

```
 INFO: [May 26 02:07:23.816] creating install container for server process install_script=/tmp/pterodactyl/cddefbbb-292e-4568-b1ce-4318f6f35e80/install.sh server=cddefbbb-292e-4568-b1ce-4318f6f35e80
 INFO: [May 26 02:07:23.826] running installation script for server in container container_id=2c8a884c14cf62bc09813c722a28ad8873c23ddfd0d74c73f97f6b109c8890f7 server=cddefbbb-292e-4568-b1ce-4318f6f35e80
 INFO: [May 26 02:07:23.978] completed installation process for server server=cddefbbb-292e-4568-b1ce-4318f6f35e80
 INFO: [May 26 02:15:24.916] syncing server configuration with panel server=cddefbbb-292e-4568-b1ce-4318f6f35e80
 INFO: [May 26 02:15:25.212] performing server limit modification on-the-fly server=cddefbbb-292e-4568-b1ce-4318f6f35e80
 INFO: [May 26 02:15:35.542] detected server as entering a crashed state; running crash handler server=cddefbbb-292e-4568-b1ce-4318f6f35e80
 INFO: [May 26 02:16:16.374] syncing server configuration with panel server=cddefbbb-292e-4568-b1ce-4318f6f35e80
 INFO: [May 26 02:16:16.556] performing server limit modification on-the-fly server=cddefbbb-292e-4568-b1ce-4318f6f35e80
 WARN: [May 26 02:16:26.557] failed to perform on-the-fly update of the server environment error=environment/docker: could not inspect container: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.41/containers/cddefbbb-292e-4568-b1ce-4318f6f35e80/json": context deadline exceeded server=cddefbbb-292e-4568-b1ce-4318f6f35e80

Stacktrace:
Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.41/containers/cddefbbb-292e-4568-b1ce-4318f6f35e80/json": context deadline exceeded
environment/docker: could not inspect container
github.com/pterodactyl/wings/environment/docker.(*Environment).InSituUpdate
        /home/runner/work/wings/wings/environment/docker/container.go:127
github.com/pterodactyl/wings/server.(*Server).SyncWithEnvironment
        /home/runner/work/wings/wings/server/update.go:135
github.com/pterodactyl/wings/server.(*Server).onBeforeStart
        /home/runner/work/wings/wings/server/power.go:177
github.com/pterodactyl/wings/server.(*Server).HandlePowerAction
        /home/runner/work/wings/wings/server/power.go:126
github.com/pterodactyl/wings/router/websocket.(*Handler).HandleInbound
        /home/runner/work/wings/wings/router/websocket/websocket.go:353
github.com/pterodactyl/wings/router.getServerWebsocket.func2
        /home/runner/work/wings/wings/router/router_server_ws.go:81
runtime.goexit
        /opt/hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371
```

**Comment by philip-ulrich** [comment]
I'm narrowing it down to docker. The container exists, but it doesn't start or stop and I'm not able to find out why. I think that wings should not fail even if a docker power/status command fails though. This seems like a bad idea - especially in situations like this. I think that my root cause lies within docker though.

**Comment by philip-ulrich** [comment]
hey! looky there, there is a new pinned issue that addresses this problem: 

#2475 

I think this can be closed ref that. I'll try updating docker and runc and see if it fixes it. I think it will.

**Comment by DaneEveritt** [comment]
Sounds good, that was going to be my next guess as to the issue. Perhaps theres a way to narrow down what specifically is causing the hang and add some context timeouts to it, but I'm not sure what difference it would end up making anyways since it would just push the bug to the next thing in the line.

**Comment by philip-ulrich** [comment]
I get what you are saying in theory, but in practice, I'd rather have the wings daemon start back up and give me access to managing all but one of my containers - compared to losing access to all of them and having to reboot to get it back.

**Comment by DaneEveritt** [comment]
Indeed, going to re-open this issue in that case since no one else really ran into this specific problem, but it helps to know it is stemming from the same source issue so that should help me at least guess at some places to throw in better timeout handling.
