### ISSUE TITLE
Launch SFTP button stopped working

### ISSUE THREAD

**Issue by UndercoverNL** [pterodactyl/panel#3361]
**Background (please complete the following information):**

* Panel or Wings: Panel
* Version of Panel/Wings: 1.4.1
* Panel Logs: No logs, only console error
settings:1 Failed to launch 'my_sftp_address' because the scheme does not have a registered handler.
* Wings Logs: Nothing inside. Panel redirect issue
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10, Brave (happens on every browser)

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: 8.0.5 for Panel web server, 7.2 for PHPMyAdmin web server. (problem also appears without PHP 7.2 installed / PHPMyAdmin)
Wings:
Linux ubuntu 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
https://ptero.co/hawuqafaje.js

**To Reproduce**
Steps to reproduce this behavior:

1. Go to any server and click on Settings.
2. Click on Launch SFTP
3. See error in console.

**Expected behavior**
SFTP client opens up like it always did.

The error means that the http:// or https:// is missing from a redirect. But the SFTP:// is actually included in the redirect link.

**Comment by DaneEveritt** [comment]
"see error in console" is not a description of the bug. The link is correct and valid to my knowledge, this issue does not clarify what actual issue you see.

**Comment by UndercoverNL** [comment]
When you press the button nothing hapends, The SFTP is not opening.

**Comment by JackW6809** [comment]
@UndercoverNL Make sure you are using a client that supports it. FileZilla does not support it but I know WinSCP does work with it. I just tested it on the latest release and it work's fine.

**Comment by UndercoverNL** [comment]
aa, that seems to be the problem. Thanks
