### ISSUE TITLE
Allow Allocations without Port displayed to customer.

### ISSUE THREAD

**Issue by calvinthefreak** [pterodactyl/panel#3362]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when users use the IP with the Port, I wanted to use the "SRV" DNS entry, because Minecraft is OK with that.

**Describe the solution you'd like**
The thing, I wanted to be added or changed is, that the display over here
![grafik](https://user-images.githubusercontent.com/5560381/118410527-265b5e00-b690-11eb-838b-ff67813794ff.png)
can be without the Port-Display, so only the hostname is displayed.

so maybe add an checkbox to display or not display the port.
![grafik](https://user-images.githubusercontent.com/5560381/118410716-23ad3880-b691-11eb-9742-cafe5141c559.png)

**Describe alternatives you've considered**
there is no alternative right now but telling my friends not to use the port with the address

**Additional context**
Nope.

Edit: Leaked IPs on the first Screenshot

**Comment by DaneEveritt** [comment]
Thanks for the suggestion, but I won't be implementing this functionality.

**Comment by calvinthefreak** [comment]
You know.... Wasting IPv4 is useless these days.... and it is just plain stupid if you can say so... and most people will want to use the IPs without any port attached to the domain.

but its your decision. I will patch that upstream and will do a push, if I find the time to do this.
