### ISSUE TITLE
Ability to run standard docker containers

### ISSUE THREAD

**Issue by jaapieaapie1** [pterodactyl/panel#3363]
**Is your feature request related to a problem? Please describe.**
Yes, I really want to run some standard docker containers in pterodactyl so I can manage them easily, but you need to do that whole entrypoint thing.

**Describe the solution you'd like**
I just want to be able to start up a docker image I found somewhere (or created myself) that doesn't have the entrypoint stuff.
So basicly when creating a server I would like an option to just fill in a docker image name/url

**Describe alternatives you've considered**
I have created my own images with entrypoints but it's a pain in the ass and I find it quite annoying to change someone else's docker image

**Comment by RihanArfan** [comment]
Pterodactyl is a control panel for game servers. Use something like Portainer to manage other Docker containers.

**Comment by jaapieaapie1** [comment]
Still if I write my own gameserver for a game why wouldn't I just be able to run it as a normal docker container?
It doesn't seem hard to implement and makes my life (and probably a lot of other people) a lot easier

**Comment by mason-rogers** [comment]
"It doesn't seem hard to implement" is what a lot of people who make feature requests say, why rework how pterodactyl's container system works just because you're too lazy to implement the entrypoint requirements to make ptero work as intended for your usecase

**Comment by DaneEveritt** [comment]
Thanks for the suggestion, but the intended usage of this software is running game servers, not just any Docker image. Additionally the entrypoint requirement was the best way we found to ensure the games can run correctly with our setup. The bigger issue is not the entrypoint, it is that we have a very specific way in which user information and volumes are mounted, and if your specific image does not support that then things will not work correctly.

It is much easier to just have a defined setup for images than trying to support tons of wildly different formats and random mount requirements.
