### ISSUE TITLE
Invalid command 'SSLEngine'

### ISSUE THREAD

**Issue by LoneDespair** [pterodactyl/panel#3368]
**Is your feature request related to a problem? Please describe.**

The ssl version of apache2 refuses to run because of invalid command 'SSLEngine'

**Describe the solution you'd like**

So would like to recommend having this in the documentation
sudo a2enmod ssl
sudo apachectl restart
sudo systemctl restart apache2

**Describe alternatives you've considered**

**Additional context**

**Comment by DaneEveritt** [comment]
If this is an issue with the documentation please open an issue (and ideally a PR fixing it) in that repository, thanks.
