### ISSUE TITLE
Panel Links are HTTP Even with TRUSTED_PROXIES=*

### ISSUE THREAD

**Issue by bmearnhardt** [pterodactyl/panel#3371]
* Panel or Wings: Panel
* Version of Panel/Wings: 1.4.1
* Panel Logs: Nothing useful related to the issue.
* Server's OS: Proxmox Hypervisor, Debian 10 VM, OPNsense Firewall with HAProxy.
* Your Computer's OS & Browser: Windows 10, Firefox

**Describe the bug**
Links in the panel are in HTTP instead of HTTPS. I've seen that adding "TRUSTED_PROXIES=*" to the .env file should fix that. It does not for me. The links are still in HTTP and I get an error along the lines of "Request will be sent over an insecure connection".
HAProxy is setup to listen on port 443 and SSL offload with a certificate and then go to port 80 on the backend. I have set the "APP_URL=" to https instead of http. Cloudflare is my domain provider and I have disabled the proxy on it. I used the "NGINX without SSL" in the Panel Installation instructions. The browser states I have a valid certificate and connects with HTTPS.
Cloudflare SSL/TLS is set to Full.

**To Reproduce**
Steps to reproduce this behavior:

1. Run panel behind HAProxy with "TRUSTED_PROXIES=*" added to the config.
2. Open panel and view links on the side. They are HTTP.

**Expected behavior**
Links in the panel should be HTTPS when running behind a reverse proxy.

HA Proxy Screenshots
[HAProxy Condition](https://user-images.githubusercontent.com/32975897/118949832-9cc5bd80-b927-11eb-8f28-f7e955813a26.PNG)
[HAProxy Rule](https://user-images.githubusercontent.com/32975897/118949834-9cc5bd80-b927-11eb-876b-bb8af079f4f0.PNG)
[HAProxy Server](https://user-images.githubusercontent.com/32975897/118949836-9cc5bd80-b927-11eb-85ec-c09a6a866960.PNG)
[HAProxy Backend](https://user-images.githubusercontent.com/32975897/118949837-9d5e5400-b927-11eb-99db-7847359a5a0e.PNG)
[HAProxy Public Service 1](https://user-images.githubusercontent.com/32975897/118949838-9d5e5400-b927-11eb-8422-912a9b6b7cf3.PNG)
[HAProxy Public Service 2](https://user-images.githubusercontent.com/32975897/118949839-9d5e5400-b927-11eb-9db7-09f99bc9877a.PNG)

Other Screenshots
[Showing HTTP link with working HTTPS site and browser cert](https://user-images.githubusercontent.com/32975897/118951116-cfbc8100-b928-11eb-8387-0aabb665e3b3.PNG)

**Comment by Kaesewuerfel** [comment]
Very nice

**Comment by fayalalebrun** [comment]
I have the same problem. I am not familiar with Laravel, but I cannot find the code that actually uses the trusted proxy configuration to fix this issue, as is detailed here: 
https://stackoverflow.com/questions/29992233/how-do-i-configure-ssl-with-laravel-5-behind-a-load-balancer-ssl-termination

Perhaps that is the problem? The config variable resulting from `TRUSTED_PROXIES` environment variable is never actually used in the end?

**Comment by matthewpi** [comment]
Can you confirm that in your `.env` you have
```
APP_URL=https://<public domain used to access the panel>
TRUSTED_PROXIES='*'
```
Make sure you try `TRUSTED_PROXIES` with the single quotes around the `*` otherwise it might not work

**Comment by bmearnhardt** [comment]
> 
> 
> Can you confirm that in your `.env` you have
> 
> ```
> APP_URL=https://<public domain used to access the panel>
> TRUSTED_PROXIES='*'
> ```
> 
> Make sure you try `TRUSTED_PROXIES` with the single quotes around the `*` otherwise it might not work

Can confirm that is in my .env:
APP_URL=https://ptero.mydomain.com
TRUSTED_PROXIES='*'

Tried both with and without and have the same issue.

**Comment by fayalalebrun** [comment]
This morning I updated my panel from `v1.4.1` to `v1.4.2`. This left it in a non-working state, since for some reason it refused to connect to the database afterwards (At least I presume this was the issue, it's what the artisan worker reported).

After I downgraded back to `v.1.4.1`, the links generated by the panel are now HTTPS.

**Comment by bmearnhardt** [comment]
Still have the issue after updating. However, it only looks like it is the ones in the admin panel. Anything on the main page or in the server pages are HTTPS.

**Comment by DaneEveritt** [comment]
Honestly, this sounds like an issue with the trusted proxies package or your environment, there is nothing different or special about the code we use, it is just the standard code that ships with every Laravel project.
