### ISSUE TITLE
Shutdown all Server with a button, after restart, start the server with button again

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3372]
After a system update I restart the server, but I have installed a lot of servers that are also used. Before every restart I have to shut down all servers manually in order to restart them after the restart with the help of a screenshost.

My solution:
A button in the admin area can be clicked on it to stop all currently online servers, these are then saved in the database so that you can start again via the button after the restart.

For example:
https://i.imgur.com/dMZpExD.png
https://i.imgur.com/Xk2yqXN.png

**Comment by Fabian-Ser** [comment]
Hmm, I don't see the point of making this when you have an artisan command for this: https://pterodactyl.io/community/tutorials/artisan.html#server-bulk-power

**Comment by DaneEveritt** [comment]
Yeah, there is a command to do this, which is more useful than a button in my opinion, especially with the current lack of granular admin permissions to protect such a button right now.
