### ISSUE TITLE
Panel behind NAT router see diferent config on node

### ISSUE THREAD

**Issue by eteodun** [pterodactyl/panel#3373]
Hi ,

* Panel or Wings: 1.4.1
* Version of Panel/Wings: Wings/v1.4.2 
* Server's OS:Ubuntu LTS 18.4
* Your Computer's OS & Browser: Windows 10

**Describe the bug**

  I try to use Pterodactyl Panel behind an router with NAT. 
   When I access panel from local network and I add new node, I see in configuration remote: http://192.168.10.4 that I set on installation panel and node bring up . 
   When I access Panel from Internet , I see and take configuration on node the URL or IP that I access pannel for example 
    remote: 'http://panel.cacaya.io' (for testing domain) or if I access panel via IP take in configuration the IP that I access (for example (192.168.100.130) take remote: 'http://192.168.100.130' and on both cases node is down

Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Wings: `uname -a` and `docker info` (your kernel version and information regarding docker)

root@vm-master-panel:/home/eteodun# uname -a
Linux vm-master-panel 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

root@slave-1-test:/home/eteodun# uname -a
Linux slave-1-test 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
PHP on panel machine

root@vm-master-panel:/home/eteodun# php -v
PHP 8.0.5 (cli) (built: May  3 2021 11:30:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.5, Copyright (c), by Zend Technologies

docker info on Node1
root@slave-1-test:/home/eteodun# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-143-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 985MiB
 Name: slave-1-test
 ID: H46X:R2QM:HDW4:TMOQ:BFIQ:XNLP:OATR:7GLE:3SSC:NSSD:VO6Q:QBTV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by eteodun** [comment]
Network config used
![Config yml from external computer from internet](https://user-images.githubusercontent.com/84614966/119217671-5f5a5f00-bae4-11eb-963f-7dc67963eb04.PNG)

Config.yml on panel from external computer in Internet

![Network config](https://user-images.githubusercontent.com/84614966/119217639-1d311d80-bae4-11eb-8d37-53d3398b5f53.PNG)

Status node from external computer in Internet

![Status node from Internet computer](https://user-images.githubusercontent.com/84614966/119217684-7305c580-bae4-11eb-9461-aa468a68a87e.PNG)


![config yml from internet with domain panel cacaya io](https://user-images.githubusercontent.com/84614966/119217723-bceeab80-bae4-11eb-8b40-34dd9a4b1451.PNG)


###############
From local network

Config.yml 
![Config yml on local network](https://user-images.githubusercontent.com/84614966/119217709-99c3fc00-bae4-11eb-9373-f98df57fe74c.PNG)

**Comment by DaneEveritt** [comment]
This sounds like an issue with your specific network setup, and nothing to do with the software itself.

**Comment by eteodun** [comment]
That print screens that I posted are from the same panel on the same machine. Panel was installed according with official documentation.
  It is a simple network , I don't see where to be config issue when the daemon config show and take different remote host

**Comment by eteodun** [comment]
Why did you close the TT without a clear resolution related to that
issue. You can reproduce in LAB to see that is a real problem.

În lun., 24 mai 2021 la 20:51, Dane Everitt ***@***.***> a
scris:

**Comment by Jerlag01** [comment]
It isn't a problem, you just have to adapt to your network infrastructure. Internal DNS server or put your server as DMZ to allow translation within the same network
