### ISSUE TITLE
Couldn't flush user prefs

### ISSUE THREAD

**Issue by DarkerMinecraft** [pterodactyl/panel#3374]
Ok I am running an ubuntu 20.0.4 I am getting this error when starting a Minecraft Server Paper 

May 24, 2021 4:17:35 AM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 2.
May 24, 2021 4:17:35 AM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.

I change the docker image to use this https://hub.docker.com/_/adoptopenjdk because Paper likes Java 16 better than Java 8 and 11.

**Comment by parkervcp** [comment]
The image you used isn't built for pterodactyl.

I have this one right now for testing - `quay.io/parkervcp/pterodactyl-images:debian_openjdk-16`
