### ISSUE TITLE
Pterodactyl, api

### ISSUE THREAD

**Issue by MathDiprio** [pterodactyl/panel#3377]
**Is your feature request related to a problem? Please describe.**
Hey, I'm using the pterodactyl api and i'm frustrated about something
When you try to get /api/application/servers/ID it shows you everythings but you can't get /ressources or other things
Also the documentation, doesn't explain very well how do you connect to the console websocket, can you help me ? Or change a little bit the doc

**Describe the solution you'd like**
Solution: add the server management,  in /api/application/servers/ID
As the same way if you do /api/client/servers/ID

**Describe alternatives you've considered**
I don't really considered any other alternatives

**Additional context**
It can be very usefull for developers that try to use the api

**Comment by DaneEveritt** [comment]
You access the resources using the client API. `/api/client/servers/<id>/resources`

**Comment by MathDiprio** [comment]
Yes i know, but i want to acces it with /application/servers/id/ressources
