### ISSUE TITLE
How to change template mail server installed massage?

### ISSUE THREAD

**Issue by e-zhuravlev** [pterodactyl/panel#3381]
![Безымянный](https://user-images.githubusercontent.com/35569496/120084642-78fa3880-c0da-11eb-9212-b381b28bde9c.png)

**Comment by mason-rogers** [comment]
https://github.com/pterodactyl/panel/blob/develop/app/Notifications/ServerInstalled.php

**Comment by e-zhuravlev** [comment]
ok tnx. how to change to UI?)
