### ISSUE TITLE
Alert of Subuser not having 2FA

### ISSUE THREAD

**Issue by hwalker928** [pterodactyl/panel#3384]
**Is your feature request related to a problem? Please describe.**
This is not a bug. 

**Describe the solution you'd like**
A popup warning if the subuser you are adding to your server does not have 2fa enabled if the server owner has 2fa enabled. 

**Describe alternatives you've considered**
No other alternatives available. 

**Additional context**
Possibly also add a warning triangle to the subusers tab next to the subuser without 2fa.

**Comment by nikrozman21** [comment]
I see this as a bad thing since that way people could tell if a user has 2FA or not which just screams unnecessary information disclosure in my opinion.

**Comment by mason-rogers** [comment]
![image](https://user-images.githubusercontent.com/26467584/120110121-38470180-c164-11eb-9903-7df987cd770a.png)

It already discloses that info once you add the user, I dont see any harm in also disclosing it before giving the invite.

**Comment by matthewpi** [comment]
Once a user is invited vs before a user is invited are two completely separate things.  What you are basically asking for is a way to check if a user with a email has 2FA enabled and essentially if the user already exists which is a terrible idea.  Ideally we wouldn't even show if the subuser has 2FA enabled unless they actively accept an invite (which is not how the current system works).  If anything we would just add a way to require 2FA on subusers and not show if they do or do not have 2FA enabled.

**Comment by mayed505** [comment]
I think the 2FA icon should show up if they accepted the sub-user invite, adding them directly and seeing if they have had 2FA or not might be the best idea vs showing as a pop-up before adding.
