### ISSUE TITLE
When starting wings, "Heart" on Nodes-page updates, but not its tooltip

### ISSUE THREAD

**Issue by CWies** [pterodactyl/panel#3385]
Minor problem.
When you have the nodes-page open in your panel and then start the wing of a specific node, the "heart" will update to its green beating state, but the tooltip of the heart will remain the error message.
Fixes by reloading the page.
Unfortunately I do not have a screenshot, as I have already reloaded the site.
Panel Version: 1.1.3
Wings Version: 1.2.0
Browser: Brave Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)

**Comment by trenutoo** [comment]
What do you mean by tooltip? Your panel/wings versions are mismatched and also not up to date
