### ISSUE TITLE
Displaying the server load in the panel

### ISSUE THREAD

**Issue by e-zhuravlev** [pterodactyl/panel#3386]
**Background (please complete the following information):**

* Panel or Wings: 1.4.2
* Version of Panel/Wings: 1.4.2

Found a very strange problem when using the isolcpus=CoreRange utility
For example, if you run the panel on a regular dedicated server, everything works well and there are no problems...
But if you try to reserve on this server, for example, stream 0 from 16 under the OS only, then the panel does not show the server load, although it does show everything in HTOP.

**Comment by parkervcp** [comment]
The load you see is from docker. This may be a weird kernel bug or a docker issue. Either of which is not something that wings is doing wrong. 

https://github.com/moby/moby/issues/31086
