### ISSUE TITLE
Entrypoint.sh: variables randomly empty.

### ISSUE THREAD

**Issue by Maelep** [pterodactyl/panel#3387]
**Background (please complete the following information):**

* Panel or Wings: Panel
* Version of Panel/Wings: 1.4.1
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows & Firefox

**Describe the bug**
I made a custom Rust egg that add some variables and features. When I try to get some variables in my entrypoint.sh, some are randomly empty.

**To Reproduce**
Steps to reproduce this behavior:

1. In your egg, add some `required|integer|min:0|max:1000` variables (eg: `MAX_PLAYERS`, `MIN_PLAYERS` and `MID_PLAYERS`)
2. In your entrypoint.sh, add some echo (`echo "MAX: ${MAX_PLAYERS}, MIN: ${MIN_PLAYERS}, MID: ${MID_PLAYERS}"`)
3. Start your server multiple time.
4. See variables randomly empty.

**Expected behavior**
Variable not empty.

**Comment by Maelep** [comment]
![image](https://user-images.githubusercontent.com/53207714/120283745-ceda0680-c2bb-11eb-81bc-a293b4b7a7ee.png)

**Comment by Maelep** [comment]
This bug doesn't concern only integer but string too. So I think it concerns all variables.

**Comment by Maelep** [comment]
It looks like that running the egg for the first time on a fresh panel looks working but running the egg multiple time (like if you are developing a new image) looks bugging. As Red-Thirten said, it looks like a Caching issue.

**Comment by DaneEveritt** [comment]
#2778
