### ISSUE TITLE
Allow us to reinstall a failed-install server

### ISSUE THREAD

**Issue by skerit** [pterodactyl/panel#3388]
**Background (please complete the following information):**

* Panel or Wings: Panel
* Version of Panel/Wings: 1.4.1
* Panel Logs: https://bin.ptdl.co/ew5ei/
* Wings Logs: https://ptero.co/zilerovodi
* Server's OS: Linux
* Your Computer's OS & Browser: Linux & Firefox

**Describe the bug**

I tried to install a new server, and had to modify the install script a bit. I forgot to add `-y` to my `apt install` command, so the install never finished.

There was no clear way to stop & restart the process, so I suspended & unsuspended the server.
After that I got this error:

```
 This server is in a failed install state and cannot be recovered. Please delete and re-create the server. 
```

Well, I'm glad I encountered this so early instead of on a server that's been in use for a while. Why would we need to delete a server because an install failed? Just let us run the install command again. But now I can't do that, all I can do is delete.

(And if I wasn't the admin of my own server, I wouldn't even be able to access the file manager or databases, since that keeps saying `Running Installer`)

**The way I solved it**

I manually stopped the hanging `install` container, like so:

```
docker stop 4baf282d44f7
```

And then I had to manually modify the `status` column of this server in the `servers` table in the database. It was something like `install_failed` and I had to change it back to NULL. After that, everything worked fine.

**Comment by DaneEveritt** [comment]
see also https://github.com/pterodactyl/panel/issues/1994

**Comment by trenutoo** [comment]
Also #1590
