### ISSUE TITLE
Intermediate certificate required. Unable to get issuer certificate.

### ISSUE THREAD

**Issue by scolastico** [pterodactyl/panel#3392]
**Background (please complete the following information):**

* Panel or Wings: Wings
* Version of Panel/Wings: 1.4.2
* Panel Logs: not necessery
* Wings Logs: 
* Server's OS: Debian 10 + Plesk
* Your Computer's OS & Browser: Windows 10 + Vivaldi

**Describe the bug**
If i use https and my generated certificate from lets encrypt i get the NET::ERR_CERT_AUTHORITY_INVALID warning from my browsers

It seems like the wings use an old intermidate certificate because i cant use the new Lets Encrypt Certificates.
Linked to related issue: https://github.com/shred/acme4j/issues/116#issuecomment-853822878

I tryd it allready on all common browsers (Chrome, Firefox, IE, Edge, Vivaldi) throug browserling but all result in the same.

**To Reproduce**
Steps to reproduce this behavior:

1. Generate a new certificate from lets encrypt throu ACME ([RFC8555](https://datatracker.ietf.org/doc/html/rfc8555))
2. Configure the cert in the wings.
3. Start wings and try to connect to it throug ssl. 

**Expected behavior**
Normal ssl secured connection that browsers doesnt block

**Comment by scolastico** [comment]
I also checked my certificate seems all ok to me:
![image](https://user-images.githubusercontent.com/26954501/120672361-87f23980-c492-11eb-92b1-2bf09d0aecb5.png)

**Comment by DaneEveritt** [comment]
This is not a bug with this software it is an issue with your server, as the comment you linked says. We don't do anything special with the certificate, it is just pulled in when spinning up the webserver instance.

**Comment by DaneEveritt** [comment]
You're also using a staging certificate, which [has a completely different intermediate heirarchy](https://letsencrypt.org/docs/staging-environment/#staging-certificate-hierarchy).

**Comment by scolastico** [comment]
> This is not a bug with this software it is an issue with your server, as the comment you linked says. We don't do anything special with the certificate, it is just pulled in when spinning up the webserver instance.

If it would what i was thinking the bug is it would be a big with the server **but**

> You're also using a staging certificate, which [has a completely different intermediate heirarchy](https://letsencrypt.org/docs/staging-environment/#staging-certificate-hierarchy).

like you sayd and in the linked other issue an other user told me (https://github.com/shred/acme4j/issues/116#issuecomment-853981638) i forgot to remove the staging in the ACME url.

**Comment by scolastico** [comment]
But thx anyway!
