### ISSUE TITLE
Upgrade Laravel

### ISSUE THREAD

**Issue by FoksVHox** [pterodactyl/panel#3394]
**Is your feature request related to a problem? Please describe.**
As of laravel/framework#36960, we can make sure that passwords aren't in data leaks and that they've specific requirements. This should be done, as Pterodactyl is built with security in mind.

**Describe the solution you'd like**
Upgrade Laravel, and make use of this.

**Describe alternatives you've considered**
None

**Additional context**
laravel/framework#36960

**Comment by DaneEveritt** [comment]
Dependency upgrades will happen as time permits. 👍🏼 

I try not to leave issues open for them though, hence the reason for me closing this.

**Comment by FoksVHox** [comment]
> Dependency upgrades will happen as time permits. 👍🏼
> 
> I try not to leave issues open for them though, hence the reason for me closing this.

@DaneEveritt Yeah, but is this something that you'd consider implementing? As it improves account security?

**Comment by DaneEveritt** [comment]
Perhaps, but again I don't consider it to be of pressing urgency so it'll happen when time permits. :)
