### ISSUE TITLE
Artisan trans() Coding Issue

### ISSUE THREAD

**Issue by JackW6809** [pterodactyl/panel#3395]
You can remove all of the translation stuff for this, that was a bad choice made awhile back but it is pretty pointless for the CLI.

_Originally posted by @DaneEveritt in https://github.com/pterodactyl/panel/pull/3319#discussion_r633123249_

Hi Dane or whoever reads this issue. I have tried removing the `trans()` part from my own code and it just fails to display the message.
My test:
Normal - 
`$node_id = $this->option('nodeid') ?? $this->ask(trans('command/messages.allocation.ask_nodeid'));`
![image](https://user-images.githubusercontent.com/53652452/119226288-42338980-bb00-11eb-8add-11268f9e47d1.png)
Then without -
`$node_id = $this->option('nodeid') ?? $this->ask('command/messages.allocation.ask_nodeid');`
![image](https://user-images.githubusercontent.com/53652452/119226309-57a8b380-bb00-11eb-8695-aa129cdb5ec9.png)
So I am not really sure what I am meant to do here other than keep `trans()` in my code unless you can provide an example piece of code of what I am meant to use? Unless this is a bug I am stuck.

Thanks,
Jack.

**Comment by occanowey** [comment]
Dane meant remove translations not just remove the function trans. Just use "Enter a valid Node ID" not the translation key.

**Comment by JackW6809** [comment]
Hi @occanowey,

Oh my, I thought I tried this. I specifically remember doing this. Oh well, what you suggested worked anyways.

Thank you,
Jack.
