### ISSUE TITLE
Startup command fails to update to new eggs value, same for common variables.

### ISSUE THREAD

**Issue by notAreYouScared** [pterodactyl/panel#3397]
**Background (please complete the following information):**

* Panel or Wings: Panel
* Version of Panel/Wings: 1.4.1
* Server's OS: Ubuntu 20.04

**Describe the bug**
When changing a server's egg from one to another the startup command fails to update to the new startup command.

Also, If the previous egg and new egg share a common variable name, Source eggs all have Source AppID / `SRCDS_APPID`, the value that is already set is used in the new egg. 

**To Reproduce**
1. Install a game with ARK/CSGO/Custom Source/ GMOD etc.
2. Change the server to another egg that has common variables, I used ARK->CSGO
3. Attempt to reinstall the server, notice ARK was installed again due to the value of `SRCDS_APPID` not updating to the new eggs default value 

**Expected behavior**
All variables should be cleared when a server changes eggs, and the defaults of the new egg put in place. Same with the startup command.

**Comment by TekExplorer** [comment]
So it would function as if you re-created the server, except with the same files, ports, databases, and users?

**Comment by notAreYouScared** [comment]
Yes. It should wipe the current variables values and startup command. and replace it with the new eggs variables and startup command
