### ISSUE TITLE
Download nests

### ISSUE THREAD

**Issue by anondev-sudo** [pterodactyl/panel#3398]
**Is your feature request related to a problem? Please describe.**
When i want to download all the eggs, I need to download every egg file, it's not possible to download whole nests with more eggs in one file.

**Describe the solution you'd like**
Add download button to nest, it should download the nest config and all eggs that are in that nest in one json file.

**Describe alternatives you've considered**
Create checkboxes that you can choose eggs, and then download them in one file.

**Additional context**

**Comment by tmunsch** [comment]
A workaround is just exporting the nests via mysqldump

**Comment by DaneEveritt** [comment]
This is such an infrequent thing that I don't believe it to be enough of a priority to leave an issue open for.
