### ISSUE TITLE
OpenLiteSpeed Config Help

### ISSUE THREAD

**Issue by MaximKing1** [pterodactyl/panel#3401]
OpenLiteSpeed is a Web Server being used by a lot of hosting company’s now, it’s been proven to be almost 10 times faster than any solution available and I think it would be a great idea to include a config option on the site or maybe you could provide some steps to help me? Getting a bit stuck when I go to the domain all I see is a white screen.

**Comment by parkervcp** [comment]
nginx and apache are the standard web server included in all distributions. While OpenLightSpeed may be faster it's not an industry standard.

**Comment by MaximKing1** [comment]
> nginx and apache are the standard web server included in all distributions. While OpenLightSpeed may be faster it's not an industry standard.

Well you say that, LiteSpeed is used by 
- 20i
- A2 Hosting – Great low-priced VPS LiteSpeed hosting.
- GreenGeeks.
- LiquidWeb.
- Hostwinds.
- Hawk Host.

**Comment by Slitzo3** [comment]
> > nginx and apache are the standard web server included in all distributions. While OpenLightSpeed may be faster it's not an industry standard.
> 
> Well you say that, LiteSpeed is used by
> 
> * 20i
> * A2 Hosting – Great low-priced VPS LiteSpeed hosting.
> * GreenGeeks.
> * LiquidWeb.
> * Hostwinds.
> * Hawk Host.

Just because a few big hosting companies are using it doesn't mean it's a industry standard.

**Comment by chisaato** [comment]
I have done some research about it. here is what I did on OLS

https://discord.com/channels/122900397965705216/272796619592695808/535111619659956228

**Comment by MaximKing1** [comment]
> I have done some research about it. here is what I did on OLS
> 
> https://discord.com/channels/122900397965705216/272796619592695808/535111619659956228

Thank you, i did get it working thanks to help in the discord and started writing a little docs for it will hopefully put in here soon...

**Comment by voitsekhovskymax** [comment]
> I have done some research about it. here is what I did on OLS
> 
> https://discord.com/channels/122900397965705216/272796619592695808/535111619659956228

Hi! Could you post a solution here?
