### ISSUE TITLE
Upload Custom Backups

### ISSUE THREAD

**Issue by EmeraldWither** [pterodactyl/panel#3402]
Note: When I say "server", I refer to the actual machine running the server, not Wings or the game server.
**Is your feature request related to a problem? Please describe.**
Usually when I play, I only leave my server on for the time that me and my friends will play (1 hour-ish), and then I shut it off. Now sometimes, I can play when my friends can't, I download the backup I made before we got off, and play on that on my local machine. Now, when I need to put the newly updated files on the server, I would have to wait until we turn on the server, and upload it via SFTP. This can take upwards of 20 minutes, which is really annoying. 

**Describe the solution you'd like**
I would like to see a "Upload Backup" button which lets us upload a backup to S3 (or compatible storage), and be able to restore them when I turn on the server, and then when I click "restore", it adds the updated files to Wings. This will also be nice for my other friends who maybe also will be able to play when I can't and they can upload backups.

**Describe alternatives you've considered**
None for now. 

**Additional context**
![2021-06-07 08_26_00-Window](https://user-images.githubusercontent.com/68785503/121017061-d9d4e100-c76a-11eb-84cf-e85f99577533.png)

**Comment by mattmalec** [comment]
You might have better upload performance using SFTP when uploading a single ZIP file vs. multiple little files (like configuration files and world region data). You can also not include large files like a Spigot jar since you usually won't be changing it often.

**Comment by DaneEveritt** [comment]
I won't be adding support for such functionality. You'd be better off manually uploading the file and un-archiving it with the file manager to achieve what you're trying to do.
