### ISSUE TITLE
ERROR! Failed to install app '258550' (Disk write failure)

### ISSUE THREAD

**Issue by LNAhri** [pterodactyl/panel#3403]
**Background (please complete the following information):**

* Panel or Wings: latest
* Version of Panel/Wings: latest
* Panel Logs: none
* Wings Logs: where all successfull
* Server's OS: ubuntu 20.04 LTS

**Describe the bug**
Install a fresh ubuntu server and install docekr & wings according to the docs.
Try to install any Steam Game, ends with .
ERROR! Failed to install app '...' (Disk write failure)
I tried it with Rust/CSGO/GarrysMod ...
All the Stuff is completly new installed

WINGS:
Linux ln-game-2 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-74-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 19.09GiB
 Name: ln-game-2
 ID: KDLS:I7KU:2GKY:YZKL:KYEX:3W5X:6BCC:TRIB:SEG4:J5A4:FIYI:SIOZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**To Reproduce**
Steps to reproduce this behavior:

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.

**Comment by LNAhri** [comment]
df -h for the wings server

udev            9.6G     0  9.6G   0% /dev
tmpfs           2.0G  1.1M  2.0G   1% /run
/dev/sda2       492G   11G  456G   3% /
tmpfs           9.6G     0  9.6G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           9.6G     0  9.6G   0% /sys/fs/cgroup
/dev/loop0       56M   56M     0 100% /snap/core18/2066
/dev/loop1       68M   68M     0 100% /snap/lxd/20326
/dev/loop2       33M   33M     0 100% /snap/snapd/12057
tmpfs           2.0G     0  2.0G   0% /run/user/1000

**Comment by parkervcp** [comment]
```
To Reproduce
Steps to reproduce this behavior:

    Go to '...'
    Click on '....'
    Scroll down to '....'
    See error
```


These steps are not reproduction steps.

**Comment by parkervcp** [comment]
Pretty sure this is a steam issue as has been discussed in discord.

**Comment by LNAhri** [comment]
ahh sry forgot the bottom part: i wrote it upperwards 
Describe the bug
Try to install any Steam Game, ends with .
ERROR! Failed to install app '...' (Disk write failure)
I tried it with Rust/CSGO/GarrysMod ...
All the Stuff is completly new installed

But thanks I check a look :D

**Comment by parkervcp** [comment]
I am sure valve will fix this. They probably already have bug reports for it with as many people that use steamcmd.
