### ISSUE TITLE
Sign Up UI

### ISSUE THREAD

**Issue by ghostdevv** [pterodactyl/panel#3408]
**Is your feature request related to a problem? Please describe.**
There is no way to sign up on the panel, I have to wrap it in my own UI

**Describe the solution you'd like**
A (probably toggleable in settings) signup ui

**Describe alternatives you've considered**
Wrapping it myself in a bot or website, which works just would be great to have it built in

**Comment by TrixterTheTux** [comment]
There's no reason to allow users to register when they aren't able to do anything in the panel without a game server.

**Comment by ghostdevv** [comment]
@TrixterTheTux not the point, they might be purchasing a server or being added to someone elses server

**Comment by RihanArfan** [comment]
> @TrixterTheTux not the point, they might be purchasing a server or being added to someone elses server

When they get added as a subuser, an account is generated if it does not exist already.

**Comment by ghostdevv** [comment]
> When they get added as a subuser, an account is generated if it does not exist already.
Alright

But it would still be useful for potential clients to have a sign up UI. I have been asked about it before a few times

**Comment by TrixterTheTux** [comment]
Useful how? Most of the use cases aren't what applies to most people, and nothing stops you from automatically creating an account when they're ordering a server (vs. for some reason having to first register on the panel, then go and deploy a server somewhere else for themselves?).

**Comment by ghostdevv** [comment]
@TrixterTheTux Both should be a option imo, I did mention that the sign up ui would probably need to be toggleable as in you can enable or disable it as some people would want it some people wouldn't
