### ISSUE TITLE
Suggestion to cut files.

### ISSUE THREAD

**Issue by Minionguyjpro** [pterodactyl/panel#3409]
Make it possible to cut files in the panel and paste them in an map backwards and forwards.

**Comment by hwalker928** [comment]
You can already move files.

**Comment by Minionguyjpro** [comment]
That's not the same. That only works on folders forwards, but not backwards.

**Comment by trenutoo** [comment]
> That's not the same. That only works on folders forwards, but not backward.

You can move them up or down the directory tree. Type `../` in the beginning to move it up one step. Type it multiple times to move it multiple directories up `../../`.
