### ISSUE TITLE
More database types to assign for servers

### ISSUE THREAD

**Issue by hydridity** [pterodactyl/panel#3412]
**Is your feature request related to a problem? Please describe.**
Negative

**Describe the solution you'd like**
In management, database hosts, would be nice to have possibility to add database host of databases other than just mysql, for example when the server(as an item in pterodactyl, could be a bot or a plugin for minecraft that is using another type of database, or anything) is using mongodb, so it could be possible to assign mongodb database for that server
Does not applies just for mongodb, i think best approach would be via plugins, where users can create custom database drivers for panel to manage.

**Describe alternatives you've considered**
1. Running the database as separate server in pterodactyl, but that adds additional workload when automating deployment, which requires spawning the database as server, filling the details such as name, limits ..., reading the assigned port, testing if database works, spawning new server and linking them together. And fills the panel with double the amount of servers items that are deployed and also consumes the port assignments.

2. Automation script deploys the database on another automation host and just pass the configuration to the server on pterodactyl

**Comment by ririko5834** [comment]
I totally agree with this idea, there should be option to add MongoDB, PostgreSQL and Redis database hosts and when user wants to create databse, there should be picker to choose database type

**Comment by DaneEveritt** [comment]
I have no plans on supporting additional databases at this time.

**Comment by ririko5834** [comment]
Keep it open so someone can contribute in the future
