### ISSUE TITLE
panel zip file decompression yields in all files (including nested) being extracted to the location of the zipfile

### ISSUE THREAD

**Issue by dennisrijsdijk** [pterodactyl/panel#3413]
* Panel or Wings: Wings
* Version of Panel/Wings: Panel 1.4.2, Wings 1.4.3
* Panel Logs: None
* Wings Logs: https://ptero.co/woninimoji.pl
* Server's OS: Ubuntu 20.04 LTS Server
* Your Computer's OS & Browser: Windows 10 Home, Google Chrome

**Describe the bug**
when decompressing zip archives with nested files (files inside of folders) the files get extracted to the zip's location, rather than the folder being created.
Please provide additional information too, depending on what you have issues with:
Panel: PHP 8.0.7
Wings: Linux Ubuntu-2004-focal-64-minimal 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

root@Ubuntu-2004-focal-64-minimal /var/www/pterodactyl # docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 7
  Running: 2
  Paused: 0
  Stopped: 5
 Images: 21
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-67-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.81GiB
 Name: Ubuntu-2004-focal-64-minimal
 ID: NDWA:EQVD:XSXM:KVBQ:K7GZ:355E:DLWG:SUDB:ZPCD:BXW6:QGPY:O2GU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**To Reproduce**
Steps to reproduce this behavior:

1. Create a zip file with a folder, and a file inside
2. upload zip file to pterodactyl panel
3. right click zip file in file manager
4. click unarchive

**Expected behavior**
Zip files extract with correctly placed files (eg. nested files are in their respective folders)

**Comment by trenutoo** [comment]
The versions you provided don't seem to match what is shown in the wings logs. Can you double-check, because this sounds like a bug that was already fixed

**Comment by dennisrijsdijk** [comment]
looks like wings never rebooted after I updated it... Will retest asap
