### ISSUE TITLE
Panel add-ons - where to look?

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#3414]
There are a lot of resources on the search engines that offer add-ons, but all of them contain the same add-ons.
But where is the main source?

I am also interested in add-ons for my tasks ...

**Comment by hwalker928** [comment]
Legit sites include:
- https://pterohub.com (unreleased)
- https://pterodactylmarket.com/
- https://mc-market.org/

Any other site that is not listed above may be illegally distributing the addons. If you post the URL in the Pterodactyl discord, the bot should let you know if it is legit or not.
