### ISSUE TITLE
Error 500 after a scheduled backup

### ISSUE THREAD

**Issue by trentonb18** [pterodactyl/panel#3418]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installing this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in the closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

To obtain logs for the panel and wings the below commands should help with the retrieval of them.
Panel: tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99
Wings: sudo wings diagnostics

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**

* Panel or Wings: Panel & Wings
* Version of Panel/Wings: 
* Panel Logs: Returns no logs
* Wings Logs: https://ptero.co/kumowuyuno
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Windows 10, Brave 

**Describe the bug**
PHP Version 7.4.13
uname - a 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86                           _64 x86_64 x86_64 GNU/Linux
docker info  Kernel Version: 5.4.0-74-generic
 Operating System: Ubuntu 20.04 LTS

When creating a server backup using scheduled tasks the server goes into an error 500, once the backup task happens and fails I can't seem to get the server out of the error 500 

**To Reproduce**
Steps to reproduce this behavior:

1. Create a task to run a backup 
2. Run a backup (Most of the time works) 
3. Server gives error 500 and can't access anything, sometimes fixes itself 

**Expected behavior**
The server should create a backup without causing an error

**Comment by trentonb18** [comment]
Forgot to put version, but while debugging I updated to the latest I don't really know how to check the exact version as I can't access the web interface is there a command I can run?

**Comment by notAreYouScared** [comment]
If the panel returned a 500, there has to be panel logs.

**Comment by trentonb18** [comment]
There were no panel logs, but I figured out the issue so i'll close this.

The problem was with actually with the panel cause it ran out of storage on the SSD I had in the system.
