### ISSUE TITLE
GUI feature requests for avatar and account

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#342]
In 0.6, the top right shows your account name and avatar. Currently, the avatar doesn't seem to be easily configurable (unless linking with Gravatar). Also, when you click on your name/avatar, it has no functionality.

I'm sure you're all aware of this, but it would be nice to either remove that altogether and have it bring you to your account page (where you can also update your avatar image).

**Comment by DaneEveritt** [comment]
Closing as its something that will be taken care of eventually.
