### ISSUE TITLE
permissions are not preserved when backup is restored

### ISSUE THREAD

**Issue by hz-ad** [pterodactyl/panel#3423]
**Background:**

* Panel or Wings: Wings
* Version of Panel/Wings: 1.4.3
* Server's OS: Debian 10

**Describe the bug**
Using the Valheim Vanilla egg from parker's repo, after a local backup is restored, and the server is started, the following error is thrown on server start:
`/entrypoint.sh: line 36: ./valheim_server.x86_64: Permission denied
`

**To Reproduce**
Steps to reproduce this behavior:

1. Make a server using the Vanilla Valheim egg
2. Do a local server backup 
3. Restore the backup
4. Start the server 

**Expected behavior**
After a backup is restored, file permissions should hopefully try to be retained

**To work around**

To manually fix the problem: 
1. Stop the server
2. Restore the backup as your normally would
3. chmod 755 the `valheim_server.x86_64`
4. Start the server

**Comment by parkervcp** [comment]
This is not a panel issue but an egg issue.

https://github.com/parkervcp/eggs

**Comment by trenutoo** [comment]
> This is not a panel issue but an egg issue.
> 
> https://github.com/parkervcp/eggs

It's not an egg issue, although it sounds like one. The actual issue is with backup restoration not preserving permissions, breaking server binaries from starting unless the permissions are manually altered. This affects all servers and eggs, not just valheim.

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/wings/commit/31ff3f8b568f3c8cc76ec07f07e12921f23bab65
