### ISSUE TITLE
 Ban for spam steam scam

### ISSUE THREAD

**Issue by Pidihajzlikhra** [pterodactyl/panel#3424]
![Bez názvu](https://user-images.githubusercontent.com/33321731/122679591-c6565b00-d1eb-11eb-9f60-767930c58eb0.png)

Hello Highly, I apologize for the spam that happened 20.6 around 17 ... I have no idea how it happened 1 week I was off the PC and I was not even on the Internet ... Therefore, I would like to ask for unban my nickname is Pidihajzlik ... I changed my password and turned on 2-phase verification ...

**Comment by schrej** [comment]
I'll give you another chance, make sure it doesn't happen again.
