### ISSUE TITLE
Paper 1.17 and possibly all new minecraft-servers require Java 16

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#3425]
**Is your feature request related to a problem? Please describe.**
Any panel-users restarting Paper-Minecraft Servers now get the Paper 1.17 update, which requires Java 16. The latest Java-version using the core-eggs is Java 11.

**Describe the solution you'd like**
Update the core image for Minecraft-servers to use Java 16, which should not be any issue even for servers running older server jars.

**Describe alternatives you've considered**
Self-adding an option for panel-users to use a self-supplied Java binary, so that they can run the new update while the core image is being updated. This was however not a good idea, mostly because my panel-users wouldn't know how to set it up and because the self-supplied Java binary would be a waste of space once the core-image gets updated.

**Comment by trenutoo** [comment]
This is something that https://github.com/pterodactyl/panel/pull/3382 is going to solve. You can add additional images to any eggs yourself.

**Comment by TASelwyn** [comment]
As Software-Noob said, you need to add an additional (java 16) docker image.
This is the "official" java16 image.
quay.io/parkervcp/pterodactyl-images:debian_openjdk-16

**Comment by notAreYouScared** [comment]
The new java images are on the yolks repo.

`ghcr.io/pterodactyl/yolks:java_16`

https://github.com/pterodactyl/yolks#available-images
