### ISSUE TITLE
[UI - Dashboard] Console z-index overlaps with search modal

### ISSUE THREAD

**Issue by VottusCode** [pterodactyl/panel#3428]
**Background (please complete the following information):**

* Panel or Wings: Panel, frontend
* Version of Panel/Wings: Both `1.4.2` and `canary` (develop branch) are affected
* Panel Logs: -
* Wings Logs: -
* Server's OS: -
* Your Computer's OS & Browser: -

**Describe the bug**
Incorrect z-index causes the terminal loader to interfere with the modal

![Screenshot 2021-06-21 at 11-05-00 Proxy Console](https://user-images.githubusercontent.com/53915302/122736654-8b523700-d280-11eb-99ee-9ee2caca23a3.png)

**To Reproduce**
Steps to reproduce this behavior:

1. Go to the server
2. Open the search modal
3. See error

**Expected behavior**
The z-index of the modal should be higher than the loading overlay of the console, not causing the overlay to interfere with the modal.

**Comment by DaneEveritt** [comment]
This would be a fantastic time for knowing the browser and OS...

**Comment by VottusCode** [comment]
> This would be a fantastic time for knowing the browser and OS...

Sorry; Firefox 90.0b10, also was able to reproduce on Chrome 91.0.4472.114

Neofetch output if you for whatever reason need that:
![obrazek](https://user-images.githubusercontent.com/53915302/122983994-d6fa0300-d39c-11eb-8323-508edfb3e705.png)

**Comment by trenutoo** [comment]
I can confirm this issue, and it explicitly requires the Wings connection error to occur (ex. turn off wings). During this state, the issue can easily be reproduced each time you click on the search button

**Comment by VottusCode** [comment]
Like, not to be rude, but you can't fix a simple z-index issue in 21 days since it being reported?

**Comment by DaneEveritt** [comment]
I have had all of 6 hours of free time in the last month to work on Pterodactyl, so no a little z-index bug has not really been the top of my priority list.

**Comment by VottusCode** [comment]
> I have had all of 6 hours of free time in the last month to work on Pterodactyl, so no a little z-index bug has not really been the top of my priority list.

Fair enough, maybe that's why it takes month/s for PRs to get merged.
