### ISSUE TITLE
How to translate the panel to Chinese？

### ISSUE THREAD

**Issue by LuRenDing2020** [pterodactyl/panel#3432]
How to translate the panel to Chinese？

**Comment by trenutoo** [comment]
Currently, there is no translation system. There is a WIP pull request to add such functionality https://github.com/pterodactyl/panel/pull/2888

At this moment, your only option is to wait or manually modify each hard-coded text in the panel files. You'd have to [rebuild the panel assets](https://pterodactyl.io/community/customization/panel.html) to apply the changes. Keep in mind that updating the panel would overwrite these files unless you manually merge the changes using git.
