### ISSUE TITLE
Default Memory and Disk Space to 0 on server creation

### ISSUE THREAD

**Issue by lancepioch** [pterodactyl/panel#3436]
CPU Limit is already defaulted to 0.

If you want to be fancy, I'd say add conditional text to show below each description that highlights the fact that it's "Unlimited X" when the value is set to 0.

**Comment by DaneEveritt** [comment]
I'd rather not, defaulting to 0 on memory would just flood us with people complaining about -Xmx0 issues. I don't think making people explicitly fill out these fields is the end of the world. Entering 0 is not that hard in the grand scheme of it all.
