### ISSUE TITLE
Minecraft Eggs: Use aikar's flags

### ISSUE THREAD

**Issue by kalebchoi** [pterodactyl/panel#3437]
It would be nice for the eggs to use [aikar's flags](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/) by default for added performance.

**Comment by kalebchoi** [comment]
Without the -XX:+AlwaysPreTouch flag

**Comment by parkervcp** [comment]
Can you actually verify that those are needed especially with the java 16 change over?

**Comment by kalebchoi** [comment]
wdym

**Comment by yeetyboi56-deprecated** [comment]
I don't feel like this feature is necessary to be added. You can edit the egg or add your own.

**Comment by matthewpi** [comment]
Yeah, not gonna happen.  These flags shouldn't be treated as general purpose and added to every server.  If users want them, they can add them themselves.

**Comment by Danieljunek17** [comment]
You can maybe have a selection of pre created flags for people to easy optimize their servers
