### ISSUE TITLE
S3 backup downloads should generate pre-signed URLs

### ISSUE THREAD

**Issue by MarshallOfSound** [pterodactyl/panel#3438]
**Is your feature request related to a problem? Please describe.**
For security reasons when you make an S3 bucket you should always make it non-public and only provide access keys that have the minimum required permissions.  The bucket I created for pterodactyl is set up in this way and therefore doesn't have public access for the files enabled.  This means that when you click "Download" in the panel it sends you straight to a raw S3 URL:

```
https://{bucket}.s3.us-west-1.amazonaws.com/{backup_path}
```

For non-public buckets, this won't work.

**Describe the solution you'd like**
The download button should generate a temporary [presigned URL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html) so that the download button works even for private buckets

**Describe alternatives you've considered**
🤷 

**Additional context**
N/A

**Comment by matthewpi** [comment]
We already generate presigned urls for this?

**Comment by MarshallOfSound** [comment]
Hm, any ideas where to get started debugging what's going on.  You're right (I made an assumption and didn't actually check the full URL 😆 ). But I'm still hitting the AWS `AccessDenied` S3 page 🤔

**Comment by MarshallOfSound** [comment]
Oops, let's put this one down to user error, I had my IAM policy incorrectly configured 😅 Basically had the `GetObject` permission locked behind the same request condition as `PutObject` which was limited to the IP range of my pterodactyl nodes.  Adding my local IP or adding a new permission for `GetObject` _without_ that request condition made the download URL start working 👍 

Sorry for the run around 😄
