### ISSUE TITLE
Using SFTP even after the server is suspended

### ISSUE THREAD

**Issue by DrakMC** [pterodactyl/panel#3439]
**Background (please complete the following information):**

* Panel: 1.4.2
* Version of Wings: 1.4.3
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Google Chrome

**Describe the bug**
If the server is suspended, you can still make changes to SFTP if I have already been connected. I can delete files, upload new ones, etc... until I disconnect.

**To Reproduce**
Steps to reproduce this behavior:

1. Connect to SFTP of the server
2. Suspend the server
3. You still have access to all files until you disconnect

**Expected behavior**
When the server is suspended, it should disconnect all connected users from the SFTP of the server.

**Comment by playaz44** [comment]
Hi, I think it's very good that the server's SFTP is blocked and that shouldn't be changed.

**Comment by playaz44** [comment]
Hi, I can confirm this bug on the latest version of the panel (1.4.2), as long as we are connected before the server is suspended, we can do anything in FTP.
