### ISSUE TITLE
Setting timezone for Wings in docker not working

### ISSUE THREAD

**Issue by eliskvitka** [pterodactyl/panel#3442]
**Background (please complete the following information):**

* Panel or Wings: Wings
* Version of Panel/Wings: v1.4.2/v1.4.4
* Panel Logs: nothing
* Wings Logs: https://pastebin.com/3cw49hv0
* Server's OS: host OS - ubuntu 20.04; docker base image - busybox:1.33.0
* Your Computer's OS & Browser: kubuntu 20.04; Google Chrome

**Describe the bug**
Can't change timezone for wings in docker
I tried `Europe/Kiev`, `UTC+3`, `EEST+2EEDT`, `EEST/EEDT` values in: 
- set with `TZ` env var
- set with `system.timezone` in wings config.yml 
- set with mounting host `/etc/timezone` and `/etc/localtime`  

Nothing works.
When i set `UTC+3` it just use `UTC`

**To Reproduce**
Steps to reproduce this behavior:
1. Clone [pterodactyl/wings](https://github.com/pterodactyl/wings) repo
2. Copy [docker-compose.example.yml](https://github.com/pterodactyl/wings/blob/develop/docker-compose.example.yml#L14) and change `TZ` env variable to `Europe/Kiev` or something else
3. `docker-compose up`
4. See error in logs and failed container

**Expected behavior**
Wings runs in docker container with custom timezone settings.

**Comment by DaneEveritt** [comment]
Do you have a different timezone set in your `config.yml`? The `TZ` environment variable is only read if there is no configuration file present, or the config file specifies UTC as the timezone.

**Comment by eliskvitka** [comment]
> Do you have a different timezone set in your `config.yml`? The `TZ` environment variable is only read if there is no configuration file present, or the config file specifies UTC as the timezone.

I've tried to change timezone with config file too. With and without TZ env variable.
Wings starts correctly only with UTC

**Comment by eliskvitka** [comment]
Fixed. Thank you 🍎
