### ISSUE TITLE
Font issues in Console on Firefox

### ISSUE THREAD

**Issue by West14** [pterodactyl/panel#3449]
**Background (please complete the following information):**

* Panel or Wings: Panel 
* Version of Panel/Wings: 1.4.2
* Panel Logs: not applicable
* Wings Logs: not applicable
* Server's OS: not applicable
* Your Computer's OS & Browser: Win10 20H2, Firefox 90.0b12 (64-bit) (Developer Edition)

**Describe the bug**
There are some issues with font rendering in Firefox. The bottom part of glyphs is cut-off.
Especially the underscore character is not visible.
Everything is fine in Google Chrome.
For example, Firefox:
![image](https://user-images.githubusercontent.com/30056636/123955467-521d7380-d9b2-11eb-9af5-f0d1c58f8917.png)
Google Chrome:
![image](https://user-images.githubusercontent.com/30056636/123955503-5b0e4500-d9b2-11eb-9efb-3bd78bfb7305.png)

**To Reproduce**
Steps to reproduce this behavior:

1. Open your Pterodactyl Panel
2. Click on any server
3. Check the console output

**Expected behavior**
Glyphs should be rendered fully.

**Comment by schrej** [comment]
Seems like this is caused by the recent xtermjs upgrade: xtermjs/xterm.js#3353

**Comment by sapphonie** [comment]
When will this be fixed? It makes using ptero panel on firefox way less usable than it needs to be

**Comment by sapphonie** [comment]
^ ignore me this is an upstream issue

**Comment by West14** [comment]
The issue in xtermjs has been resolved - https://github.com/xtermjs/xterm.js/issues/3353. Do you have any plans to update the panel with new version of xtermjs included?
