### ISSUE TITLE
Spigot server requires server.jar to exist before server is started

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#345]
This may be a redundant or known issue, and I apologize if that is the case.

It seems like when selecting the Minecraft Spigot option, it requires a server.jar to already exist in the directory prior to the server being started, otherwise it won't start. I went online and downloaded a Spigot server.jar and simply upload this whenever a Spigot server is requested, but obviously it would be better if I didn't need to do this every time I spin up the server.

**Comment by DaneEveritt** [comment]
Closed as this is fixed by packs and better docker images.
