### ISSUE TITLE
SteamServer Disconnected (ServiceUnavailable)

### ISSUE THREAD

**Issue by DrakMC** [pterodactyl/panel#3451]
**Background (please complete the following information):**
* Panel or Wings: 1.4.2
* Version of Panel/Wings: 1.4.3
* Wings Logs: https://ptero.co/nocapameno.coffeescript
* Server's OS: Ubuntu 20.04 LTS
* Your Computer's OS & Browser: Google Chrome

**Describe the bug**
I run a Rust server. The problem is that it disconnects the player at a random time.
There is an error in the log:
- `SteamServer Disconnected (ServiceUnavailable)`
- `SteamServer Connection Failure (NoConnection)`

After a while, the SteamServer connects and players can connect. However, I don't know why it disconnects and what it can cause. Can't it be caused by a problem like #3447 ?

Please provide additional information too, depending on what you have issues with:
PHP version: `8.0.7`
Wings:
- `Linux mydomain.com 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- docker info: https://ptero.co/okohuwuwok.js

**To Reproduce**
It's happening at a random time, I don't know why.

**Expected behavior**
SteamServer should not disconnect so that it does not kick players from the server.

**Comment by DaneEveritt** [comment]
This is unlikely to be an issue with this software, rather a networking issue somewhere between your server and Steam.
