### ISSUE TITLE
Logrotate error

### ISSUE THREAD

**Issue by b-kneisel** [pterodactyl/panel#3452]
**Background (please complete the following information):**

* Panel or Wings: Wings
* Version of Panel/Wings: 1.4.2 / 1.4.4
* Panel Logs: /
* Wings Logs: /
* Server's OS: Debian 10
* Your Computer's OS & Browser: /

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: /
Wings: The problem is that due to a faulty logrotate config the Wings log is not rotated.

**To Reproduce**
Steps to reproduce this behavior:

1. Install a pterodactyl node on debian 10

**Expected behavior**
The problem is that Wings applies a wrong logrotate config. Logrotate cannot find the user '0' and the group '0' and thus never rotates the log.

Logrotate error:
```
logrotate[15307]: error: wings:10 unknown user '0' 
logrotate[15307]: error: found error in /var/log/pterodactyl/wings.log , skipping 
```

With larger infrastructures this can lead to immense instabilities with Wings, which sporadically loads the CPU enormously, since the logs become partly enormous.

The solution for this problem is a small config change, because logrotate doesn't recognize the user '0' and the group '0':
From this:
```
/var/log/pterodactyl/wings.log {
    size 10M
    compress
    delaycompress
    dateext
    maxage 7
    missingok
    notifempty
    create 0640 0 0
    postrotate
        killall -SIGHUP wings
    endscript
}
```
**to this:**
```
/var/log/pterodactyl/wings.log {
    size 10M
    compress
    delaycompress
    dateext
    maxage 7
    missingok
    notifempty
    create 0640 root root
    postrotate
        killall -SIGHUP wings
    endscript
}
```

**Comment by BolverBlitz** [comment]
This error also occurs on all my nodes.
Installed wings on 1.0 release and now running latest version 1.4.5
