### ISSUE TITLE
Make downloading files a different permission again

### ISSUE THREAD

**Issue by diamkil** [pterodactyl/panel#3453]
**Is your feature request related to a problem? Please describe.**
In 0.7 we had a permission that was different from read-content to download files, this permission got removed in 1.X but we would like to get it back again

**Describe the solution you'd like**
Add back the separate download permission for sub-users

**Describe alternatives you've considered**
On one of our two panels (the oldest version of the two, 1.1.3) our last sys-admin edited pterodactyl's files to make it a separate permission again, I tried the mod on the newer panel (1.4.2) but that doesn't work and we can't update our old panel since we depend on that setting

**Additional context**
How it should be:
<img width="652" alt="Panel with Download permission" src="https://user-images.githubusercontent.com/35732047/124314799-eddcea00-db40-11eb-9036-73d134435b04.png">
How it is:
<img width="658" alt="Unmodified Panel" src="https://user-images.githubusercontent.com/35732047/124314858-06e59b00-db41-11eb-9d37-b2d883adae95.png">

**Comment by DaneEveritt** [comment]
https://github.com/pterodactyl/panel/pull/2917#issuecomment-751499881
