### ISSUE TITLE
Can't start Server again, only after changing the port

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3455]
* Panel or Wings: Panel
* Version of Panel/Wings:  1.4.2 / 1.4.5
* Docker: 20.10.7
* Kernel: 4.19.0-17-amd64
* Panel Logs: https://pastebin.com/A6WatMr3
* Wings Logs: 
* Server's OS: Debian 10.10
* Your Computer's OS & Browser: Win10 & Firefox | Android & Firefox App
* PHP: PHP 7.4.16

**Describe the bug**
https://i.imgur.com/LpyOV2U.png
I can't start the server agian, but after changing the port i can start the Server again.

**To Reproduce**
Steps to reproduce this behavior:
I dont no. The error is not every restart.

**Comment by trenutoo** [comment]
That's not a bug with the software. The port is already in use by another service. Join [Discord](https://discord.gg/pterodactyl), post the red error message, and the bot will reply with instructions on how to find out what is using the port.

**Comment by Felix5566** [comment]
Thx, but the server isnt running anymore: https://i.imgur.com/2nTnlfM.png

**Comment by Felix5566** [comment]
Thx, in this log he is running, but in the console he isn't: https://i.imgur.com/WRIPi9b.png
