### ISSUE TITLE
WebSocket connection problems using Brave

### ISSUE THREAD

**Issue by MAXOUXAX** [pterodactyl/panel#3456]
**Background:**

* Panel or Wings: Panel
* Version of Panel/Wings: 1.4.2 / 1.4.5
* Panel Logs: None
* Wings Logs: None
* Server's OS: Docker: 20.10.6 | Kernel: 4.19.0-16-cloud-amd64 | Debian GNU/Linux 10 (buster)
* Your Computer's OS & Browser: Windows 11 | Brave (Stable)

**The bug**
This issue is related to #2432, I have essentially the same problem.
Wings start up fine, the panel works fine, but the websocket connection doesn't work and leaves this loading screen on the server page.
![image](https://user-images.githubusercontent.com/24844231/124368886-17dbfc80-dc66-11eb-869a-cb22e7578de3.png)
![image](https://user-images.githubusercontent.com/24844231/124368976-2f67b500-dc67-11eb-89f8-2203052e3e5b.png)

I tried another browser (Chrome) and the problem does not occur with this one.
However, Brave was working fine a few minutes ago, and the problem suddenly appeared for no apparent reason.
I tried logging back in, clearing my browser cache, clearing cookies, etc. but nothing solved the problem.
This may be a Brave related bug, but I find it odd that it happens randomly.

I would also like to point out that Brave can access `https://domain.tld:8080/api/servers/uuid/ws` since I get this response:
```
Bad request
{ "error" : "An unexpected error was encountered while processing this request.", "error_id" : "uuid"}
```
 
Panel: PHP 8.0.5
Wings : Not relevant

**To Reproduce**
Steps to reproduce this behavior:

0. Use Brave
1. Go to your panel
2. Click on the server of your choice
3. See if the page loads correctly
4. If step 3 is successful, try the next day.

**Expected behavior**
The WebSocket connection should work every time

**Comment by lancepioch** [comment]
Turn off Brave Shield, just tested with @AreYouRlyScared on W11

**Comment by MAXOUXAX** [comment]
> Turn off Brave Shield, just tested with @AreYouRlyScared on W11

Forgot to mention that yes, I did try disabling Brave Shields (this is basically the first debug step when you have a problem on a website and you're running Brave) and that no, it did not fix the problem for me.
Pretty surprised to see that it fixed it for someone else running the same softwares :/

**Comment by notAreYouScared** [comment]
![image](https://user-images.githubusercontent.com/1757840/124369331-b9e4f000-dc38-11eb-8fcc-7813764b5427.png)
 I toggled it off then back on and its working just fine 


Try restarting wings

**Comment by MAXOUXAX** [comment]
I can see that, I'm pretty sure this is the type of bug that solves overnight. I'll try to turn off Brave Shields again tomorrow if the issue didn't get fixed by itself.

By the way thanks for the quick support guys :)

EDIT: Just saw your edit, during redaction, I deleted the part stating it but I did try to restart wings, php-fpm, my browser, my computer, even my router, but the problem persisted.
And as I said it's not happening with Chrome so it's definitely not wings-related.

**Comment by lancepioch** [comment]
Sorry, we've tested it on Chrome and Brave on multiple computers running W10 and W11. If you can help narrow it down more so that it's reproducible for us, we can take another look. Otherwise there's not much left. Thanks again for your support so far.

**Comment by MAXOUXAX** [comment]
> Sorry, we've tested it on Chrome and Brave on multiple computers running W10 and W11. If you can help narrow it down more so that it's reproducible for us, we can take another look. Otherwise there's not much left. Thanks again for your support so far.

As expected, the problem was resolved overnight. I'm not sure what caused it since I tried to restart almost everything that could have caused it.
Anyway, thank you for the quick support and I wish you guys the best!
Thanks!
