### ISSUE TITLE
Issue with installing pterodactyl-panel as NPM package

### ISSUE THREAD

**Issue by YWatchman** [pterodactyl/panel#3458]
**Is your feature request related to a problem? Please describe.**
For writing modules to extend the feature-set of Pterodactyl for internal purposes, I now need to support installing the frontend package within my module since Pterodactyl migrated over to a react frontend. This is not possible, because as of now no packages are present on npmjs.org and neither a version is set in the package.json.

**Describe the solution you'd like**
Push the package to npmjs.org or any other repository and thus add versioning, this way executing `yarn add git+ssh://git@github.com/pterodactyl/panel.git#v1.4.0` would work.

**Describe alternatives you've considered**
Creating a local downstream fork and add the package.json version there, but this ofcourse doesn't help the rest of the community building their modules.

**Additional context**
```
feature/pterodactyl-v1-compat!module *> yarn add git+ssh://git@github.com/pterodactyl/panel.git#v1.4.0
yarn add v1.22.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Can't add "pterodactyl-panel": invalid package version undefined.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by mason-rogers** [comment]
Why do you need the panel's frontend to be published to NPM? Everyone who modifies the panel for their purposes run a private fork with modifications done on their copy, and whenever ptero pushes an update they can just merge it in from upstream.

**Comment by YWatchman** [comment]
Because I'm trying to build a module... In the past you could just publish your blade views. Having a private fork is more of a hassle to maintain than just building modules and updating them for every new pterodactyl version.

**Comment by DaneEveritt** [comment]
This project was never designed in such a way, and at this time I do not believe it beneficial to tackle such a project with my limited availability.
