### ISSUE TITLE
Uploading FIles with the File Manager shows wrong uploading green bar 

### ISSUE THREAD

**Issue by IlPicasso** [Pterodactyl/Panel#346]
I want to report a bug with uploading green bar at the bottom of the page 
![image](https://cloud.githubusercontent.com/assets/5110242/23861873/60d153a6-07d9-11e7-96ed-6515f9e3ccac.png)

When you upload something it will always fill the greenbar fastly even thought it is not uploaded completely yet so you have to keep waiting even thought the bar already filled

**Comment by DaneEveritt** [comment]
Ok so this isn't fixed...

Can you see if there are any browser console errors that show up, and what OS and Browser are you using?

**Comment by DaneEveritt** [comment]
Duplicate of #231 report in that for me.

**Comment by IlPicasso** [comment]
Sorry didn't saw it, will close this and comment there
