### ISSUE TITLE
Auto Minecraft Plugin Updater

### ISSUE THREAD

**Issue by coco0325** [pterodactyl/panel#3460]
**Is your feature request related to a problem? Please describe.**
It's a time consuming job to update plugins, especially when you have multiple servers in a network. Since the server owner can't replace plugin jars while the server is running.

**Describe the solution you'd like**
You can put a new plugin jar in a specific directory and Pterodactyl will replace the plugin in the server to this jar when the server is restarting. Pterodactyl can use jar file name to determine which jar to replace.

**Comment by gOOvER** [comment]
^Normally, as i know, the jar will updated on a Reinstall. So why is this needed?

**Comment by trenutoo** [comment]
Panel does not create any game specific features

**Comment by coco0325** [comment]
> ^Normally, as i know, the jar will updated on a Reinstall. So why is this needed?

The panel only update server jar on reinstall, not plugin jars.

**Comment by coco0325** [comment]
> Panel does not create any game specific features

It don't have to be a game specific feature. You can see it as a file updater.

**Comment by gOOvER** [comment]
> > ^Normally, as i know, the jar will updated on a Reinstall. So why is this needed?
> 
> The panel only update server jar on reinstall, not plugin jars.

I think, you can do this in the egg or Image (Never take a look into it, where is the best place for it)
. Not a really needed feature for Ptero, because not everyone plays Minecraft

**Comment by FoksVHox** [comment]
Could be solved, if a system like #2911 got in place.

**Comment by DaneEveritt** [comment]
#1084
