### ISSUE TITLE
tab-completion support for minecraft servers

### ISSUE THREAD

**Issue by AngryCarrot789** [pterodactyl/panel#3461]
**Describe the solution you'd like**
when you press the tab key (on your keyboard) while typing something in console, it counts as "tab completion", meaning it executes the `onTabComplete()` in minecraft commands

**Additional context**
it does this in windows console/terminal. e.g., type in "h", press tab, and it shows any command that begins with "h". it also does this ingame, but in console it also formats it based on the size of the window
![image](https://user-images.githubusercontent.com/32274404/125174288-19ed1080-e1bc-11eb-8bea-843b94937971.png)

im not sure how its done in CMD, but ive even tried running a minecraft server on another computer, ssh-ing into that computer, running the server, and tab completion still works fine. so it seems like this feature should be implementable (although currently, pressing tab in the pterodactyl console causes it to do that "select next element in the web page" thing, so maybe that stops it from working)

**Comment by i-eat-burgers** [comment]
Sounds like something that really isn't needed and it would be quite challenging, if even possible to make it count for all the mods/plugins the server may have.

**Comment by AngryCarrot789** [comment]
i have a few plugins installed on my server, and they all use tab-completion to select select "sub-commands" (e.g. /mycommand subcommand arguments). and being able to just type in "mes" and have it auto-complete to "message" is very helpful and efficient.

and i dont see how there would be problem, because even windows' command prompt supports it

**Comment by DaneEveritt** [comment]
I won't be adding support for this functionality at this time.

**Comment by i-eat-burgers** [comment]
> i have a few plugins installed on my server, and they all use tab-completion to select select "sub-commands" (e.g. /mycommand subcommand arguments). and being able to just type in "mes" and have it auto-complete to "message" is very helpful and efficient.
> 
> and i dont see how there would be problem, because even windows' command prompt supports it

If you think it's not a problem, then be my guest! Go on code and make a pull request... :D

**Comment by AngryCarrot789** [comment]
okay :)

**Comment by lilynet336** [comment]
Just now coming across this after installing Pterodactyl last night. Has there been any progress on this? It’s been a few hours using it and I already miss the tab completion.

**Comment by yesBad** [comment]
> Just now coming across this after installing Pterodactyl last night. Has there been any progress on this? It’s been a few hours using it and I already miss the tab completion. 

The answer has not changed.

**Comment by lilynet336** [comment]
That’s what I feared. Thank you
