### ISSUE TITLE
OCI runtime create failed

### ISSUE THREAD

**Issue by Bazsi15** [pterodactyl/panel#3462]

**Comment by trenutoo** [comment]
Looks like you have unsupported virtualization type, such as LXC, OPENVZ or OVZ. Type `systemd-detect-virt` to double-check. This could also occur with cgroup V2.

You should use Discord for support. The support bot is configured to respond to your issue.

**Comment by parkervcp** [comment]
please fill out the issue template.

Then you can re-open this issue.
