### ISSUE TITLE
Server is online but no performance statistics being reported

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#347]
I see a previous post which is similar in nature to this one, but not quite the same. This seems to occur for Minecraft and Minecraft Spigot, but I'll be honest in stating that I haven't tested this for other games.

In a few situations, it appears as if the performance statistics simply stop reporting for certain servers. It works fine for other servers running on the same host. This has occurred a few times for different servers. In my case, the indicator in the top left is still green and the server is still online and functional. Restarting the server resolves the issue.

These are the last lines in the console:

```[09:32:07] [Server thread/INFO]: Done (1.488s)! For help, type "help" or "?"
[09:32:07] [Server thread/INFO]: Starting GS4 status listener
[09:32:07] [Query Listener #1/INFO]: Query running on 0.0.0.0:25574
[09:32:07] [Server thread/INFO]: Timings Reset
000008_378b981c:~$

**Comment by DaneEveritt** [comment]
It's the same issue, go ahead and tag onto that issue. 😁
