### ISSUE TITLE
Add memo column to server console

### ISSUE THREAD

**Issue by sakastudio** [pterodactyl/panel#3471]
When running a server, there are some things to keep in mind.
However, there is no space in the current panel to describe them.
The server description can't contain many things, nor can it open links.
Therefore, we want to add a space in the image below where we can write notes and things to note.

![image](https://user-images.githubusercontent.com/55620461/126020881-00ab89da-e5b0-4496-a0e6-26aba5d5ea89.png)

**Comment by mason-rogers** [comment]
use the feature request template, otherwise this issue will likely just get closed without being read by dane
