### ISSUE TITLE
Add memo column to server console 

### ISSUE THREAD

**Issue by sakastudio** [pterodactyl/panel#3472]
**Is your feature request related to a problem? Please describe.**
When running a server, there are sometimes a few rules and precautions to follow. However, the current panel does not have the capability to display them.

**Describe the solution you'd like**
We want to add a memo column to the server console screen, write rules or precautions there.

**Describe alternatives you've considered**
We considered writing rules on our discord server.
However, sometimes we forget rules to make trouble.

**Additional context**
We want to add a space in the image below where we can write notes and things to note.
![126020881-00ab89da-e5b0-4496-a0e6-26aba5d5ea89](https://user-images.githubusercontent.com/55620461/126022603-9c72aac3-bae3-4c4b-a4bc-19bc51ac93cc.png)

**Comment by anondev-sudo** [comment]
Really good idea

**Comment by DaneEveritt** [comment]
Not interested in adding this.
