### ISSUE TITLE
latency issue > 1 min

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3474]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

DEBUG: [Jul 17 23:34:55.006] GET /api/servers/3a5f06ad-2145-456d-baf5-245a97394121/ws client_ip=xxx latency=1m15.930235076s request_id=9ad0cb5d-7987-41e5-8682-8e6b93805e2f status=200
DEBUG: [Jul 17 23:35:10.009] GET /api/servers/4cea36d6-f348-4720-9dae-773f3a89593b/ws client_ip=xxx latency=1m4.178271602s request_id=a9c8f681-e4c3-4edd-96cc-d5f052a0704a status=200
DEBUG: [Jul 17 23:35:18.772] GET /api/servers/b57de45a-ac24-42dd-aaa3-e7185e3726cb/ws client_ip=xxx latency=1m43.156699194s request_id=23673884-69c3-4a52-9e67-c33c8ba93e9f status=200
DEBUG: [Jul 17 23:35:51.128] GET /api/servers/52a24d36-6b4d-4bda-8bc6-6a8dd23fe651/ws client_ip=xxx latency=1m22.639172715s request_id=8edde28f-03bf-4bac-9c00-05d7e885d626 status=200
DEBUG: [Jul 17 23:36:01.123] GET /api/servers/d112ea06-fefb-4d57-95f8-7ef0095f0ed5/ws client_ip=xxx latency=1m0.539116003s request_id=e0492570-44eb-4d8e-b0c5-216851081a55 status=200

### Expected Behavior

less latency ?

### Steps to Reproduce

Start wings and check logs.

### Panel Version

1.40

### Wings Version

1.4.2

### Error Logs

```bash
0
```

**Comment by matthewpi** [comment]
That time for websocket connections is how long the websocket was connected for, not the latency.
