### ISSUE TITLE
Check server current states with application apikey

### ISSUE THREAD

**Issue by HirziDevs** [pterodactyl/panel#3475]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

You can see server current states by using application apikey for admin that want to see how much server are online or offline on the node or on the panel, since we need to use client apikey to check server resource api and it only check user servers not all server on the node or panel

### Describe the solution you'd like.

Application apikey can see server current states likes server resource api from client api

### Additional context to this request.

![20210718_184627](https://user-images.githubusercontent.com/64255651/126065809-d90114b7-3ad9-47ab-b4a1-4d57a7336d28.jpg)

**Comment by trenutoo** [comment]
The status is when the server is transferring, installing, restoring, or suspended. Your admin user's client API key can access all servers on the panel, and through that, you can view each server's resource usage.

**Comment by DaneEveritt** [comment]
Closing this out, 2.0 will support using the same API key for all operations, there won't be a distinction between client and application when it comes to using the key.
