### ISSUE TITLE
Add Velocity Support

### ISSUE THREAD

**Issue by mrxbox98** [pterodactyl/panel#3476]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Velocity Jar in the list of available jars and fix to the stop button.

### Describe the solution you'd like.

Velocity jar file added to the available jars and stop button command changed to "end" for Velocity servers as "stop" does not work on velocity.

**Comment by trenutoo** [comment]
Velocity is available on [Parkers egg repository](https://github.com/parkervcp/eggs/tree/master/game_eggs/minecraft/proxy/java/velocity)

**Comment by RealTriassic** [comment]
I think he mean't that he wanted Velocity egg to be available within the default eggs of Pterodactyl that come shipped with the Panel.

**Comment by mrxbox98** [comment]
> I think he mean't that he wanted Velocity egg to be available within the default eggs of Pterodactyl that come shipped with the Panel.

Correct

**Comment by schrej** [comment]
We don't really add things to the default list of eggs anymore. *If* you want something added, you should provides some motivation to *why* it should get added as a default egg. We can't add everything as a default.
