### ISSUE TITLE
S3 Backups Fail (Context Timeout)

### ISSUE THREAD

**Issue by DerSimeon** [pterodactyl/panel#3484]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

We have a schedule that backups our Servers every 12 hours, which worked for a while. Through the process of setting it up we had a lot of failed backups due to context timeouts  it stopped happening for around a month. but yesterday out of nowhere our backups started Failing again, resulting in us having nearly 4 pages of failed backups. when checking the logs I get the Above error as well as in the Panel I get this (unsure if it's related tho) 

Also we do noticed that sometimes when we manually make backups they aren't failing

BTW: We use a custom S3 solution called minio

### Expected Behavior

Backups work as expected resulting in no failures (except when the bucket is full)

### Steps to Reproduce

1. Install Minio S3
2. Setup Minio S3
3. Setup Pterodactyl to work with S3
4. Start Schedule that auto backups

### Panel Version

1.4.2

### Wings Version

1.4.5

### Error Logs

```bash
https://ptero.co/ozaxedofoh
http://bin.ptdl.co/50gef
```

**Comment by matthewpi** [comment]
Assuming the panel error is at a similar time to the context timeout it would seem your database is having a problem with trying to get a lock for writing.  Or the panel is failing to reach Minio.  Regardless, unless you have a consistent way to reproduce the database lock issue, this seems like a problem with your configuration.

**Comment by DerSimeon** [comment]
Small Update : yesterday we noticed All Backups are uploaded to minio without issues, the archives are also not corrupted. They still Show up as failed in pterodactyl. Thats why we arent worried Too much.

**Comment by DerSimeon** [comment]
Also when resetting the Status of the Backup via the database we can restore it without Problems

**Comment by DerSimeon** [comment]
Also all configuration Has been Done according to the original documentation of both minio and pterodactyl.

**Comment by DerSimeon** [comment]
Any update here?

**Comment by DaneEveritt** [comment]
No

**Comment by DerSimeon** [comment]
Is there additional Information I can provide that will help find a fix?

**Comment by DaneEveritt** [comment]
Closing, Wings logs are no longer available and I feel like this is more than likely an issue with the system setup — if the Panel logs are correct and the timestamps line up how I think, it is likely to be an issue with the database transactions causing a lock up which then causes backups to not be able to be saved.
