### ISSUE TITLE
Bad API Structure

### ISSUE THREAD

**Issue by unitythemaker** [pterodactyl/panel#3485]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The API and the documentation doesn't seem to be well made. I want it to be improved for reducing the waste of requests. So I want to explain this situtation more detailed:
<br />
- [I assume API documentation is this](https://dashflo.net/docs/api/pterodactyl/v1/)
- I am more interested in with Application API and I'm writing more about it.

1. [Creating a new user](https://dashflo.net/docs/api/pterodactyl/v1/#req_802e27a56fe142c99db4106d8e8e8892)
Firstly, the documentation omits too many variables and doesn't explains types of variables. For example, in this page, we cannot see the password variable. We can add password while creating an account but it's not pointed here so I thought that we can only define password after creating an account which is ridiculous. To, understand that I'm able to define password for created user, I needed to test and lost time.

2. [Updating a user](https://dashflo.net/docs/api/pterodactyl/v1/#req_657a10e0d5aa4afcbcb1f69a338cc83d)
In this page, we cannot understand the types of variables or all of them required details. So, in my code I wanted to only update the password but I encountered with 422 error. I understood email, username, first_name, last_name fields were required to update the user. This is extremely wrong and ridiculous. Why cannot just omit this variables in the request to leave them same?!

3. Updating User Permissions for a Server with Application API
We cannot add people to a server as a admin of the panel. We need the client's API token to do this because it's only implemented at [here](https://dashflo.net/docs/api/pterodactyl/v1/#req_6ee829d0394d4485a947f3e0ca2c1fb2). So I cannot implement my teams feature on my own software using this panel. You cannot expect me to do reverse-engineering and use undefined API routes.

4. [Creating a new server](https://dashflo.net/docs/api/pterodactyl/v1/#req_190b1006d60748abbeda37c7d407345a)
I just can't understand. If I will define startup script, docker image, environment variables why do I define egg?! Why are these fields are required?! Also why we don't define a location instead of the ID of the IP address?!! I didn't even know we can only define a node instead of a location and even with the node field is optional and the IP address is required. Also why do I need to get all the allocations and filter available ones and find which location are they, why can't you just automatically determine this? It's very hard to create a server automatically.

5. [Updating a server](https://dashflo.net/docs/api/pterodactyl/v1/#req_31589033fb344040ad70c43d102e45b5)
Finally, we can see a table that shows us types and requirements and I am about to go crazy. I must update name and user to only update external_id. AWESOME...
<br />
<br />

There were too much more wrong thing with that API. I just want you to make this API better. Thanks & have a nice day.

### Describe the solution you'd like.

Firstly, please avoid requiring every field on the routes. While updating a data, it doesn't matter if I will not change anything, every field I didn't define should be unchanged. While creating something, if I define a placeholder data (like egg) for the missing fields they should be automatically determined from that placeholder. Add all available fields in the documentation with an explanation text for each field. For example: while creating a server, I didn't understand what allocation field meant and it took me a few hours to figure out. Keep the examples in the documentation while adding the field definition tables, it's not required to add examples but it's required to add field definition tables. Grant Client API access to the Application API tokens. So we can take more actions in these servers.

**Comment by parkervcp** [comment]
The dashflo docs are not official.

**Comment by unitythemaker** [comment]
> The dashflo docs are not official.

I didn't know that, thanks for informing. Is there an official documentation? If there is not, I'll try to make one and open a PR.
Also I want someone to solve the other issues about the API.

**Comment by trenutoo** [comment]
> > The dashflo docs are not official.
> 
> I didn't know that, thanks for informing. Is there an official documentation? If there is not, I'll try to make one and open a PR.
> Also I want someone to solve the other issues about the API.

Dashflo is as official as it gets at this moment. Matt is planning to create official API documentation after the react-admin release.

**Comment by DaneEveritt** [comment]
You can reach out to CodeCo for API updates, they're generally quite receptive to productive feedback and suggestions.

I won't be changing how the API works to only require partial fields, the application is designed around all of the fields always being provided, and I don't see value and dealing with the pain of changing that.
