### ISSUE TITLE
Errors occurs right after Valheim server is created

### ISSUE THREAD

**Issue by allen-huang9** [pterodactyl/panel#3487]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Error occurs after the start up of the server and when the status of the server changes from starting to running. No changes have been made to any of the server files and folders.
![image](https://user-images.githubusercontent.com/8008839/126756705-af732e77-6406-4b06-af18-5ddad54bc218.png)
![image](https://user-images.githubusercontent.com/8008839/126756747-6890dbbb-7568-4e37-ac53-1af7d2c13c5d.png)
![image](https://user-images.githubusercontent.com/8008839/126756800-663c6b9f-24ff-4a37-96f5-312e960f6bcc.png)
![image](https://user-images.githubusercontent.com/8008839/126756876-94ad6dba-024f-4317-9ba1-b97bb8b13713.png)
![image](https://user-images.githubusercontent.com/8008839/126756915-64784016-776a-442f-bade-4cdee56443f7.png)
![image](https://user-images.githubusercontent.com/8008839/126757201-715d6d02-2dc2-42b1-9475-0228a5b824cb.png)
![image](https://user-images.githubusercontent.com/8008839/126757288-594d3e92-7fed-4a28-9285-ab631c4fafa5.png)
![Screenshot 2021-07-23 014247](https://user-images.githubusercontent.com/8008839/126758025-2ac44bf0-d726-49d3-9a13-0c51e98928fb.png)

### Expected Behavior

I expected it to be able to start up without any problems since I have not added any mods yet.

### Steps to Reproduce

Create a server in the node and then start it after changing the settings of the server.

### Panel Version

1.4.2

### Wings Version

1.4.5

### Error Logs

```bash
http://bin.ptdl.co/x72z4
```

**Comment by Linux123123** [comment]
This is not a panel issue, but an egg issue.

Please take any issues you have to the eggs-and-games channel in discord first.

**Comment by matthewpi** [comment]
Not an issue with the panel.  You are more than welcome to ask for help in our [Discord](https://discord.gg/pterodactyl) (eggs-and-games channel).

**Comment by gOOvER** [comment]
> This is not a panel issue, but an egg issue.
> 
> Please take any issues you have to the eggs-and-games channel in discord first.

Thats no Egg Issue.

Take a closer look at th error   `xxx.dll.so ;)`

Thats normal and can be ignored
