### ISSUE TITLE
500 Server error when deleting servers

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#3489]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Deleting servers should not return a 500 error

### Expected Behavior

Deleting servers should well... delete a server

### Steps to Reproduce

1. Install pterodactyl
2. Try to create a server
3. Realize you need to restart for it to init
4. Theres now 3 servers
5. Try to delete them
6. Error appears

### Panel Version

1.4.2

### Wings Version

1.4.2

### Error Logs

```bash
Wings: https://ptero.co/nudadikima

Panel: http://bin.ptdl.co/jhi2h (this is from installation logs, it isnt revelant)
```

**Comment by mason-rogers** [comment]
This error comes from the fact that wings can't bind to the correct port on your node, not from an issue with server deletion. Without wings running the panel wont be able to properly delete a server since it depends on contacting Wings to delete the files.

**Comment by notAreYouScared** [comment]
If that's the case. The server should have never been made in the panels databse if it was unable to contact wings. To delete the servers, you can force delete them in the panel.

**Comment by ghost** [comment]
> This error comes from the fact that wings can't bind to the correct port on your node, not from an issue with server deletion. Without wings running the panel wont be able to properly delete a server since it depends on contacting Wings to delete the files.

No, this was when I was installing wings, it is irrevelant. (i fixed that issue)

**Comment by ghost** [comment]
> If that's the case. The server should have never been made in the panels databse if it was unable to contact wings. To delete the servers, you can force delete them in the panel.

Read the above comment

**Comment by DaneEveritt** [comment]
You have no relevant error logs, which leads me to believe something here is incorrect or you're not pulling the latest logs. If all of your errors are from hours ago and you're actively getting 500 errors I would expect there to be fresh Panel logs.

**Comment by notAreYouScared** [comment]
Then I'm confused on what the actual issue is. Was it a http 500 error or was it a 500 server error. Both are different 500 errors.

**Comment by ghost** [comment]
> Then I'm confused on what the actual issue is. Was it a http 500 error or was it a 500 server error. Both are different 500 errors.

500 server error 

> You have no relevant error logs, which leads me to believe something here is incorrect or you're not pulling the latest logs. If all of your errors are from hours ago and you're actively getting 500 errors I would expect there to be fresh Panel logs.

these are the latest logs, which the issue template provided me to run

**Comment by ghost** [comment]
im reinstalling, ill reopen if it happens again

**Comment by kubo6472** [comment]
Hello, y'all. Found this as it is shockingly similar to the issue I am getting. When force deleting servers from a panel, due to non-existent wings, it should go through anyway, right? Bc I tried both safe deletion, which was supposed to give out an error message, and force deletion, which I assume should've gone through no probs. Both gave 500 | Server error screen. Browser console: https://hastebin.com/uyifetemat.pl I don't know if I should open a new issue, if this was self-closed. Thanks for any insight :)

**Comment by ghost** [comment]
by the way, i moved to pufferpanel, its simpler, but its still good

**Comment by kubo6472** [comment]
Sadly that alternative is not viable for me as it doesn't include all the features I need, like Docker-based virtualization/isolation of processes, and also I run 5 other wings on that panel which do work no-problem.

**Comment by ghost** [comment]
> Sadly that alternative is not viable for me as it doesn't include all the features I need, like Docker-based virtualization/isolation of processes, and also I run 5 other wings on that panel which do work no-problem.

it does have docker support though
