### ISSUE TITLE
Changing servers per page

### ISSUE THREAD

**Issue by Volxz** [Pterodactyl/Panel#349]
I was curious as to how I would go about changing the amount of servers displayed per page. I know some basic PHP and JavaScript so if you point me in the right direction I should be able to figure it out myself.

**Comment by Chomiciak** [comment]
I have not read the code, but I bet it's SQL-side 'limit', so you should
look for that query.

śr., 15.03.2017, 07:08 użytkownik Ethan Gallant <notifications@github.com>
napisał:

**Comment by schrej** [comment]
[Here](https://github.com/Pterodactyl/Panel/blob/develop/app/Http/Controllers/Base/IndexController.php#L50) you go.

**Comment by DaneEveritt** [comment]
You actually want [this](https://github.com/Pterodactyl/Panel/blob/release/v0.5.7/app/Http/Controllers/Base/IndexController.php#L51) unless you're on a pre release.

**Comment by Volxz** [comment]
Thanks!
