### ISSUE TITLE
Problem of updating server statistics. (CPU / RAM)

### ISSUE THREAD

**Issue by savalet** [pterodactyl/panel#3490]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

For a few days, the statistics of the cpu and the ram of all servers have been blocked at 0%. I have already tried to update the panel but I am already on the latest version. Or restart Wings even reboot my server but nothing changes.

### Expected Behavior

  .

### Steps to Reproduce

Go to a server in the panel.

### Panel Version

1.4.2

### Wings Version

1.4.5

### Error Logs

```bash
https://ptero.co/cucovivexu
```

**Comment by DaneEveritt** [comment]
I don't know how we're supposed to be able to help with redacted logs, no photos, and no details other than "it doesn't update".

**Comment by savalet** [comment]
here is a screenshot: https://arkia-mc.fr/storage/img/demjk.png

**Comment by shugen002** [comment]
try enable oom killer and restart the server , it works for me .
But  i have no idea why disable oom killer in ubuntu cause  docker don't have statistics .
