### ISSUE TITLE
Remove the 20 character limit for server jarfiles

### ISSUE THREAD

**Issue by JIBSIL** [pterodactyl/panel#3492]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Is there a reason for the jarfile 20 character limit? It seems to work just fine if you remove it; it would be a useful quality improvement to remove the regex prohibiting jarfiles above 20 characters.

### Describe the solution you'd like.

100 characters would be a reasonable jarfile limit.

### Additional context to this request.

Not quite sure why this was implemented in the first place; it doesn't seem like any of the applications would have trouble parsing strings of over 20 characters. Also, I think this is a Panel issue, if it's actually Wings that's causing the issue, sorry for filing it on the wrong project.

**Comment by araskihu** [comment]
If you want, you can raise this limit by editing the egg's server jar file variable on the admin panel. At the input rules just change the max:20 to the new limit you want, or just remove it like that: `required|string|max:20 -> required|string`

**Comment by trenutoo** [comment]
What egg is this for? There are no regex rules limiting the length. `/^([\w\d._-]+)(\.jar)$/`

It matches `a-zA-Z0-9_` and `.jar` at the end

**EDIT:** Paper egg is missing this rule. All others are using the regex method.

**Comment by JIBSIL** [comment]
Nice. 

Closed issue. See #3494

**Comment by notAreYouScared** [comment]
Should've left the issue open. It will auto close when the pr is merged.

**Comment by JIBSIL** [comment]
@AreYouRlyScared Ok, I will keep that in mind in the future.
