### ISSUE TITLE
S3 Backups not working properly

### ISSUE THREAD

**Issue by RealH0peLess** [pterodactyl/panel#3495]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

i have found an important bug: you can't backup big servers with S3 Backups, every time it will fail. my server with 120gb can't backup, but every other server with around 20 can

https://i.imgur.com/WUPbBpj.png

### Expected Behavior

the backup should work.

### Steps to Reproduce

simply create a big minecraft server with around 100 gb and try to backup with S3.

### Panel Version

1.4.2

### Wings Version

1.4.5

**Comment by EmeraldWither** [comment]
Can you provide wings logs?

Make sure you have enough space on your wings server so you can zip the files and upload them.
