### ISSUE TITLE
Redis issue with panel setup

### ISSUE THREAD

**Issue by MachineRat8** [pterodactyl/panel#3497]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When attempting to connect to my panel so that I can set up Wings, I get ERR_CONNECTION_REFUSED, so I get the panel logs, and it seems to be related to Redis.

### Expected Behavior

When I attempt to connect to my panel, it works, and I can continue with setting up Wings.

### Steps to Reproduce

I am using an aarch64 system, on Ubuntu 20.04.2 and this is what I did:

1. I installed all the dependencies and composer
2. Downloaded, installed, and set up Pterodactyl as instructed in the documentation. (Selecting redis all 3 times in the setup)
3. I set up the webserver configuration using NGINX and enabled it.
4. I tried to connect to my panel using the IP directly and the domain, both failed with the error ERR_CONNECTION_REFUSED
(5. I retrieved the panel logs (which are attached to this issue), and looked for support in the discord server, and nobody could help as they didn't know what to do.)

### Panel Version

1.4.2

### Wings Version

N/A

### Error Logs

```bash
https://bin.ptdl.co/a2uyo/
```

**Comment by matthewpi** [comment]
`production.ERROR: Error while reading line from the server. [tcp://localhost:6379] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 0): Error while reading line from the server.)`

Something is most likely wrong with your redis server.  This error occurs when redis reaches a [timeout during read or write operations](https://github.com/predis/predis/issues/32#issuecomment-1319744).

What system are you running this on?  I know you said `aarch64`, but that isn't very specific.
