### ISSUE TITLE
UPnP option for allocations

### ISSUE THREAD

**Issue by TekExplorer** [pterodactyl/panel#3498]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Universal Plug and Play is a way for devices to discover each other on the network, but in this case, i am referring to it's ability to forward ports on a UPnP-enabled router

### Describe the solution you'd like.

My idea is as follows:

Each allocation (or allocation list) should optionally have UPnP enabled.

This way, a user can have the ports needed auto-forwarded without messing with their router, and keep all currently unused allocations (a server is off, or allocation not yet assigned) closed fully.

Perhaps Wings could also have the option to disable UPnP for a node fully in the config

It should probably be auto-disabled if the router doesn't support it...

Edit: Perhaps the entire feature should be manually enabled per-node?

**Comment by parkervcp** [comment]
This may or may not work with enterprise gear.

**Comment by TekExplorer** [comment]
> It should probably be auto-disabled if the router doesn't support it...

**Comment by PrivateGER** [comment]
UPnP should be off by default. Some providers don't like it when a VPS sends UPnP requests.

**Comment by TekExplorer** [comment]
i thought i had said it should be opt in, guess i didnt.

**Comment by matthewpi** [comment]
I am going to close this based off our private discussion.  This is not something that should be natively supported by Pterodactyl, especially since nobody should have UPnP enabled, especially on a home network.  This is a niche feature that is complicated to implement and easy to break.

**Comment by TheSainEyereg** [comment]
For anyone who still faces this problem (most likely home hosting), I wrote a simple bash script. It runs periodically via cron, gets a list of all allocations from panel via API, and sends a request via upnpc ([miniupnpc](https://manpages.debian.org/unstable/miniupnpc/index.html)) to open all assigned ports. Keep in mind that script must be placed on the same machine as Wings

https://gist.github.com/TheSainEyereg/0c33562960ec0bd67eb658f3b65bf6a3

**Comment by StrangeWill** [comment]
I've taken some inspiration from @TheSainEyereg and made a Python version that runs on Wings servers and added node self-discovery, it can be found here:

https://github.com/StrangeWill/pteroupnp

And has a docker container on Dockerhub that can run alongside Wings (mine is containerized), you put one on each Wings server, it'll talk to the panel to figure out allocations, it'll hook up UPNP as needed.
