### ISSUE TITLE
143

### ISSUE THREAD

**Issue by PluexoMC1** [pterodactyl/panel#3499]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 143
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Expected Behavior

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 143
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps to Reproduce

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 143
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Panel Version

1.4.0

### Wings Version

1.4.2

**Comment by trenutoo** [comment]
You provided zero information for us to understand the issue. Exit code alone doesn't say anything.

The actual error would be above all of that.

**Comment by SlayorPlayz** [comment]
Also, ur wings and panel versions r kinda outdated
