### ISSUE TITLE
SSL-terminating Traefik causes plain HTTP forms

### ISSUE THREAD

**Issue by PrivateGER** [pterodactyl/panel#3500]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

The panel generates Laravel routes with the HTTP protocol when it is being accessed by a reverse proxy because the transport protocol visible to the server is HTTP.

### Expected Behavior

There should be an option to force HTTPS for all generated routes.
This can be implemented really easily using the AppServiceProvider->boot() method, but would require a new enviroment variable to enable or disable it, for example FORCE_HTTPS.

### Steps to Reproduce

Have a setup like this:

Internet => SSL Terminating Loadbalancer (Traefik) => Nginx (over port 80) => Panel

### Panel Version

1.4.2

### Wings Version

1.4.5

**Comment by matthewpi** [comment]
See https://github.com/pterodactyl/panel/issues/2289

**Comment by PrivateGER** [comment]
@matthewpi Unless I missed something, there is zero documentation of this in the docs. Maybe a notice should be added.
