### ISSUE TITLE
Restoring Wings Backup causes panel to break.

### ISSUE THREAD

**Issue by snaildos** [pterodactyl/panel#3501]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Over the last week, My node file system got corrupted and I resolved it and restored a backup, however, when going to the panel, loading servers and making a server takes about 3mins straight to load everything and sometimes still breaks, The logs just report a server is not found on the remote node...

### Expected Behavior

It should not be throwing errors since I deleted the server in SQL, and, in the server list.

### Steps to Reproduce

Create a panel, create a node, backup, create 2 servers or more, restore a backup and it will break.

### Panel Version

1.4.0

### Wings Version

1.4.2

### Error Logs

```bash
I can't check it right now, it's pretty urgent though, so my bad for not posting logs, however, it basically says "Server [UUID] not found! on [node]" then some stack error.
```

**Comment by snaildos** [comment]
I'll post logs in about 5 hours when I get home! Thank you for looking through this! If anyone knows a way to resolve this with SQL, I would apperciate it. :)

**Comment by snaildos** [comment]
Turns out, there is no logs... At all..?

**Comment by snaildos** [comment]
After some research, turns out it's a panel problem and I need desperate help. When going to a server list on ptero, it loads forever, going to network tab and reloading shows select2 is pending forever.
However, viewing it here http://host.snaildos.com//themes/pterodactyl/vendor/select2/select2.full.min.js loads instantly...???

**Comment by DaneEveritt** [comment]
Honestly sounds like an issue with your system, not the software. Without logs there is nothing I can do to help resolve this issue for you, and without logs it quickly points to it not being an issue with this software, rather an issue with the hardware you're running on.
