### ISSUE TITLE
Retry backups that result in HTTP 500/503 

### ISSUE THREAD

**Issue by Sabinno** [pterodactyl/panel#3505]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

In essence, instead of backups being considered "failed" in the result of a 500/503 error, I'd at least like to see the backup driver retry the upload, as usually it succeeds the second (if not the third) time.

### Describe the solution you'd like.

I would like for the panel to simply retry backups (or failed parts of backups) that result in an HTTP 500/503 error code, as this is a common problem for Backblaze B2 users, who are one of the world's most respected names in storage at scale.

### Additional context to this request.

I recently cut over my cloud backup storage provider from Linode Object Storage to Backblaze B2 for cost reasons. One of the ways Backblaze cuts down on cost is by shifting some load balancing responsibility to the client. Currently, via B2's S3-compatible endpoint (and natively through the B2 API, even), Backblaze will allow the client to upload data until storage runs out in a specific area, at which point the upload results in a 500 or 503 error. This is actually by design. For more details, see [this article](https://www.backblaze.com/blog/b2-503-500-server-error/).

**Comment by matthewpi** [comment]
Backblaze B2's S3 API has many problems with large file uploads due to the way it works.  Privately, I have implemented both the solution you are suggesting and a B2 specific driver.  The solution you are suggesting fixed some problems, but just revealed another problem; which seemed to be caused by the pod (the server we are uploading to) running out of space and the S3 API not switching to a new one (even after requesting an entirely new upload url).  The B2 driver I have referred to will not be added officially (even if I had permission to do so) due to the amount of problems I've had with B2.  I'd highly recommend avoiding B2 for storing large files, you get what you pay for.

**Comment by Sabinno** [comment]
Well, that's fair. Back to Linode for me, then (unless you recommend something else?)! This adventure will only cost me like $5 thankfully. Could be worse. Shame that the whole internet, especially Reddit, shilled B2 like it was the second coming of the Messiah. That's the last time I listen to Reddit.

That said, I will note that, in regards to not getting a new upload URL, Backblaze recommends waiting a minute before requesting another link. I'm not sure if your logic already considers this official recommendation.

**Comment by asineth0** [comment]
> Backblaze B2's S3 API has many problems with large file uploads due to the way it works. Privately, I have implemented both the solution you are suggesting and a B2 specific driver. The solution you are suggesting fixed some problems, but just revealed another problem; which seemed to be caused by the pod (the server we are uploading to) running out of space and the S3 API not switching to a new one (even after requesting an entirely new upload url). The B2 driver I have referred to will not be added officially (even if I had permission to do so) due to the amount of problems I've had with B2. I'd highly recommend avoiding B2 for storing large files, you get what you pay for.

B2 works perfectly fine and I've used it in production for years. I get if you've had issues in the past with it, but in my experience it's not uncommon for S3 "compatible" storage providers to have some compatibility issues.
