### ISSUE TITLE
The device.user agent must be a string.

### ISSUE THREAD

**Issue by snaildos** [pterodactyl/panel#3506]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

The device.user agent must be a string. when making a backup.

Data integrity exception encountered while performing database write operation. {"device.user_agent":["The device.user agent must be a string."]}

### Expected Behavior

It creates a backup...

### Steps to Reproduce

Make a backup

### Panel Version

1.4.0

### Wings Version

1.4.2

### Error Logs

```bash
None?
```

**Comment by NoSharp** [comment]
Bump also getting this
