### ISSUE TITLE
sudo wings --debug not working 

### ISSUE THREAD

**Issue by joloman2** [pterodactyl/panel#3510]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

when i try to start the wings befor demonizing i get the error /usr/local/bin/wings: 1: Not: not found command: sudo wings --debug 
![afbeelding](https://user-images.githubusercontent.com/64356554/127768269-391ab109-52d5-4219-9ea5-94ae700f004c.png)

### Expected Behavior

that it runs the wings

### Steps to Reproduce

sudo wings --debug

### Panel Version

1.4.2

### Wings Version

1.4.5

**Comment by Git-North** [comment]
what did you do
