### ISSUE TITLE
Not Properly Compatible With Android Devices!

### ISSUE THREAD

**Issue by Evo-Pro** [pterodactyl/panel#3511]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Tbh its really really irritating and annoying these days to work on pterodactyl panel being an Android user. It was perfectly working on my old vivo device, later I switched to poco x3 and then I can't work on it properly. What the issue is, I cannot backspace a line. Which means imagine that I am on line 2 and I wanted to remove line 2 and make it only line 1. When I backspace, the letters keeps removing and when it reaches 0, my keyboard pops down. And whenever I try to backspace that line my keyboard keeps popping down. Another problem is that, I can't select all and then just backspace or remove it. Whenever I do it, everything gets disappeared for one or so and my keyboard again pops down and then everything will come back to normal. I am really disappointed in this state, as I am a developer who controls mostly everything on pterodactyl panel. Hope you wont regret me in the next update/fix.

### Expected Behavior

Everything was just expected to run in the opposite behavior that I just reported above.

### Steps to Reproduce

I have no idea what this space is for.

### Panel Version

1.4.3

### Wings Version

1.4.5

**Comment by AreYouRlyScared** [comment]
https://user-images.githubusercontent.com/1757840/127785753-3833d280-f31f-484c-849e-8db8c48ee0e4.mp4

I don't have this issue.

**Comment by Evo-Pro** [comment]
But I do have. Also 3 of my collaborators

**Comment by Malachiel87** [comment]
i have this issue too xIaomi mi max 3

**Comment by matthewpi** [comment]
Based off this being a per-device issue, I'm going to close this.  The editor is not made or managed by us, we just use a library for it.  I've already upgraded the editor in v2 to a complete re-build of the existing editor and don't plan on spending any time trying to fix this.
