### ISSUE TITLE
Servers not autorestarting after crash on p1.5.0 & w1.4.6

### ISSUE THREAD

**Issue by sapphonie** [pterodactyl/panel#3521]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Server crashes, and does not get restarted by ptero, failing instead with `Aborting automatic restart, crash detection is disabled for this instance`, regardless of `timeout` or `detect_clean_exit_as_crash` values

### Expected Behavior

Server should restart on crash and respect `timeout` and `detect_clean_exit_as_crash` values in `config.yml`

### Steps to Reproduce

* Get Source server with `-norestart` in launch options
* Start it
* Let it boot
* Type `quit`
* Server doesn't restart

### Panel Version

1.5.0

### Wings Version

1.4.6

### Error Logs

```bash
https://ptero.co/uyimedetak
https://bin.ptdl.co/xfqvw/
```

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/wings/commit/25f3cb60cbbc37e6692a7b6b88ba35314c4f7283
