### ISSUE TITLE
Backup bug 1.5.1/others

### ISSUE THREAD

**Issue by ViniciusD3v** [pterodactyl/panel#3525]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

If a backup fails and I create a task to create a backup, if I press run now, there will be 2 backups, one failed and one failed, if the backup limit is one, the button appears.

### Expected Behavior

Let the task take the failed backup and replace it with a new one.

### Steps to Reproduce

you need to have a backup failed ( uses 1.5.0 to get it )

### Panel Version

1.5.1

### Wings Version

1.4.6

**Comment by ViniciusD3v** [comment]
![image](https://user-images.githubusercontent.com/88354048/128252352-b545797a-734c-4d43-84c2-57d795831dd2.png)

**Comment by matthewpi** [comment]
Failed backups don't count towards the backup limit.  There is no reason to overwrite failed backups, they are not stored anywhere taking up disk space.

**Comment by ViniciusD3v** [comment]
block the button :>

**Comment by ViniciusD3v** [comment]
> Failed backups don't count towards the backup limit. There is no reason to overwrite failed backups, they are not stored anywhere taking up disk space.

Do you fix the button?
