### ISSUE TITLE
Configuration Files: YAML Parser not setting boolean values

### ISSUE THREAD

**Issue by CoDev21** [pterodactyl/panel#3527]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

The parser for egg configuration files cannot set boolean values:
```
#manually created yaml file
#if no file exists, an empty file containing "{}" is created
node:
   value: 15
```
if the egg configuration files contains a yaml parsed file:
```
{    
    "test.yml": {
        "parser": "yaml",
        "find": {
            "node.value": true,
        }
    }
}
```

### Expected Behavior

The configuration file should have been updated to
```
node:
   value: true
```

### Steps to Reproduce

When creating/modifying an egg, add a yaml parsed configuration to the configuration files:
```
{    
    "test.yml": {
        "parser": "yaml",
        "find": {
            "node.value": true,
        }
    }
}
```

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
Wings doesn't report any errors and apart from a timeout error the panel doesn't either.
https://bin.ptdl.co/nadd2/
```

**Comment by s0u1burn** [comment]
I am having the same problem, I want to force all my servers to install as bungeecord: true,  but it doesn't work.
```
{   
  "spigot.yml": {
    "parser": "yaml",
    "find": {
      "settings.bungeecord": true
    }
  }
}`
if I do "settings.bungeecord": "true" it makes it 'true' in the file which does not work either.
