### ISSUE TITLE
[Daemon] Daemon assumes 172.18.0.0 network is free

### ISSUE THREAD

**Issue by ccarney16** [Pterodactyl/Panel#353]
While resetting docker and using docker-compose to setup all my stuff, I have noticed that the daemon seems to assume that the network '172.18.0.0' is free. So typically I have to stop all my docker-compose setups and run the pterodactyl daemon using --rm and exit out of it once the pterodactyl0 bridge is created.

**Comment by DaneEveritt** [comment]
You can set custom interface IPs using the documentation:

https://daemon.pterodactyl.io/docs/customizing-network-interfaces
