### ISSUE TITLE
Allocate node to specific user

### ISSUE THREAD

**Issue by LosBagros** [pterodactyl/panel#3532]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Let non admin user to create servers on node allocated for him

### Describe the solution you'd like.

Give non-admin users the ability to create their own server on specific node allocated to them

**Comment by DaneEveritt** [comment]
Not interested in adding such functionality, it has been requested a few times before.
