### ISSUE TITLE
Unable to setup 2fa on my account

### ISSUE THREAD

**Issue by Pr1ter** [pterodactyl/panel#3534]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

I have updated my panel to require 2FA on all account without setting up 2FA on my account beforehand.
I have tried to use `php artisan p:user:disable2fa` to remove the 2FA from my account but the panel still says that I need to have 2FA configured.
Each time that I try to attach my 2FA it errors and the console log is showing error 400

https://gyazo.com/59da48ceb825081f1f9dc7363932a040

### Expected Behavior

I should be able to set up 2FA

### Steps to Reproduce

remove 2FA from account then set panel to only allow all users

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
https://ptero.co/kalihixemi
```

**Comment by danny6167** [comment]
You have attached wings logs when this is related to the panel. Please run ``tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99`` and provide the output.

**Comment by Pr1ter** [comment]
https://bin.ptdl.co/xewjr/
Sorry about that @danny6167

**Comment by trenutoo** [comment]
You didn't use the command correctly. { } showcases the available options. They don't have to be provided, but the curly braces have to be removed if they are. I tested this, and it works even when 2fa is disabled.

`php artisan p:user:disable2fa` or `php artisan p:user:disable2fa --email=test@example.com`

---

I couldn't replicate your issue with 2FA. Enabling 2fa would force you to configure two-factor authentication, which I did successfully. Also, you have access denied to database errors in your logs. I would fix those first as nothing in your Panel will work when the database can't be accessed.

**Comment by Pr1ter** [comment]
I had re-run the `php artisan p:user:disable2fa` and it still hasn't been disabled. Would it be because of the database errors that I am getting? and how would I look at fixing those errors?

**Comment by trenutoo** [comment]
If you are still receiving database connection refused errors, then that'd be your issue in the first place before looking into any software-related problems. Check your user permissions and database status. For more assistance, use the help channels on [the Discord server.](https://discord.gg/pterodactyl)
