### ISSUE TITLE
Auto-upgrade failing and putting panel in unusable state

### ISSUE THREAD

**Issue by ssh-sysadmin** [pterodactyl/panel#3535]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Auto upgrade using `cd /var/www/pterodactyl && php artisan p:upgrade` fails and does not work.
DB does not fully migrate and permissions for the webserver are not set properly. Panel returns error 500.

![](https://ssh.pics/ilzRvdxreJ.png)
![](https://ssh.pics/RyoPyMVNp5.png)

### Expected Behavior

Panel to update

### Steps to Reproduce

Have standard panel install on version 1.4.2, use `cd /var/www/pterodactyl && php artisan p:upgrade`, answer yes to all prompts.

### Panel Version

1.4.2 to 1.5.1

### Wings Version

1.4.7

**Comment by notAreYouScared** [comment]
Running the command a second time fixes it.

**Comment by lifewcody** [comment]
I can confirm this happened to us as well. Running it a second time fixed it.

**Comment by DaneEveritt** [comment]
Closing this out, its been 9 months and trying to resolve it just isn't a priority of mine if a second run fixes it.
