### ISSUE TITLE
Cant connect to the database.

### ISSUE THREAD

**Issue by totoygamingyt** [pterodactyl/panel#3539]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

After i create database from the server. it was successfully created but, i cant connect to the database thru heidi sql

### Expected Behavior

I was expecting that the heidi sql connects to the database

### Steps to Reproduce

1 Homepage
2 Click the Server
3 Go to Database tab
4 Create database
5 Successfully Created

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
https://ptero.co/isakutafat - Wings
http://bin.ptdl.co/2n0xg - Panel
```

**Comment by trenutoo** [comment]
This is not a bug with the Pterodactyl software. Your database host does not have external connections enabled, the port is closed, or you set the connection host to a local IP while connecting from elsewhere.

Refer to the [MySQL database host documentation](https://pterodactyl.io/tutorials/mysql_setup.html#creating-a-database-host-for-nodes) to enable external connections. 

For assistance with configuration, use the [Discord server.](https://discord.gg/pterodactyl)

**ED:** Solved on Discord, the port was closed.

**Comment by totoygamingyt** [comment]
Thanks sorry for not closing this, i forgot but thankss <3
