### ISSUE TITLE
Error response from Panel: _MissingResponseCode: No error response returned fromAPI endpoint. (HTTP/403)

### ISSUE THREAD

**Issue by justmimiroot** [pterodactyl/panel#3540]
Hello,
I just updated the panel from version 1.4.2 to 1.5.1 and when I run Wings (which is also up to date) it gives me the error below.
Yours truly

Error : https://hastebin.com/owerurovem.sql

**Comment by 641i130** [comment]
How did you solve this? I'm currently stuck trying to fix it.

**Comment by KARONAGAMING** [comment]
> How did you solve this? I'm currently stuck trying to fix it.

just `systemctl restart wings`
