### ISSUE TITLE
Python Package (Torch) won't install, "no space left on device", even though there is more than enough space.

### ISSUE THREAD

**Issue by imadqadri** [pterodactyl/panel#3541]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When I add the pip package "torch" into requirements.txt in the Python egg on a Python discord bot, it gives the error "Could not install packages due to an OSError: [Errno 28] No space left on device". This same issue occurs completely different systems and panels too, so I believe it's a bug with Pterodactyl.

![](https://media.discordapp.net/attachments/830338405308301352/875801900476411914/unknown.png)

### Expected Behavior

Install the pip package without any issue, and be able to use it in the bot itself.

### Steps to Reproduce

1. Create a python bot using the default Python Bot egg.
2. Add the pip package "torch" into requirements.txt
3. Run the pterodactyl server
4. You will get the error "Could not install packages due to an OSError: [Errno 28] No space left on device".

### Panel Version

1.5.1

### Wings Version

1.4.7

**Comment by trenutoo** [comment]
You need to increase the [tmpfs_size](https://pterodactyl.io/wings/1.0/configuration.html#other-values) in your Wings config. This is not a bug with the software. Use the [Discord server](https://discord.gg/pterodactyl) for assistance with configuration issues.
