### ISSUE TITLE
why is package.json not allowed to be uploaded on server ?

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3542]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

{"error":"This file cannot be modified: present in egg denylist."}

### Expected Behavior

Allowed to be uploaded

### Steps to Reproduce

Upload package.json

### Panel Version

1.40

### Wings Version

1.4.2

### Error Logs

```bash
None
```

**Comment by JustinRijsdijk** [comment]
which egg do you use?

**Comment by trenutoo** [comment]
Update your panel and wings to the supported version. 

After that, try again and should it happen again check your eggs file_denylist. None of the eggs have any lists by default.

**Comment by BenasPaulikas** [comment]
Issue fixed. I was using wrong panel/wings version.
