### ISSUE TITLE
Performance issue with Minecraft servers

### ISSUE THREAD

**Issue by DarkOakHD** [pterodactyl/panel#3544]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

For some reason, starting a Minecraft server takes more time then usual. When starting the server thru the panel it takes 34 seconds.
![slika](https://user-images.githubusercontent.com/20874142/129481441-1deafc41-4c1a-490f-9da9-0c90dddccafd.png)

But when starting the same server with "screen" on SSH the server starts in 11 seconds.
![slika](https://user-images.githubusercontent.com/20874142/129481471-bc99f09d-ce67-4ae0-8485-7a8b286d37e3.png)

It also affects the TPS when there are more then 10 people online.

### Expected Behavior

It should be the same like on SSH.

### Steps to Reproduce

The best way to reproduce it is to generate a new world with Multiverse. Takes longer to create world then on SSH.

### Panel Version

1.5.1

### Wings Version

1.4.7

**Comment by hwalker928** [comment]
How much CPU% is assigned to the Minecraft Server on Pterodactyl?

**Comment by DarkOakHD** [comment]
> 
> 
> How much CPU% is assigned to the Minecraft Server on Pterodactyl?

![slika](https://user-images.githubusercontent.com/20874142/129481826-b5db0eef-ab3f-412e-852a-b5ffd35c5cf0.png)

**Comment by hwalker928** [comment]
> > 
> > 
> > How much CPU% is assigned to the Minecraft Server on Pterodactyl?
> 
> ![slika](https://user-images.githubusercontent.com/20874142/129481826-b5db0eef-ab3f-412e-852a-b5ffd35c5cf0.png)
> 

Try removing the 0 in CPU pinning, just leave it as blank.

**Comment by DarkOakHD** [comment]
> 
> 
> > > How much CPU% is assigned to the Minecraft Server on Pterodactyl?
> > 
> > 
> > ![slika](https://user-images.githubusercontent.com/20874142/129481826-b5db0eef-ab3f-412e-852a-b5ffd35c5cf0.png)
> 
> Try removing the 0 in CPU pinning, just leave it as blank.

Then my server won't even start.

**Comment by hwalker928** [comment]
> > 
> > 
> > > > How much CPU% is assigned to the Minecraft Server on Pterodactyl?
> > > 
> > > 
> > > ![slika](https://user-images.githubusercontent.com/20874142/129481826-b5db0eef-ab3f-412e-852a-b5ffd35c5cf0.png)
> > 
> > Try removing the 0 in CPU pinning, just leave it as blank.
> 
> Then my server won't even start.

Why won't it? What error?

**Comment by DarkOakHD** [comment]
> 
> 
> > > > > How much CPU% is assigned to the Minecraft Server on Pterodactyl?
> > > > 
> > > > 
> > > > ![slika](https://user-images.githubusercontent.com/20874142/129481826-b5db0eef-ab3f-412e-852a-b5ffd35c5cf0.png)
> > > 
> > > 
> > > Try removing the 0 in CPU pinning, just leave it as blank.
> > 
> > 
> > Then my server won't even start.
> 
> Why won't it? What error?

The issue was CPU pinning.
Thanks
