### ISSUE TITLE
Bug when creating subusers

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#355]
Pre-release 0.6.0-pre7: Just a minor graphical bug, but when clicking on a server and go to the Subusers tab, I provide the email address for the user and then want to select their permissions. However, anything I check doesn't seem to actively reflect that change (ie: the box doesn't show that it's checked). If I click "Update Subuser", it actually _does_ show that what I clicked on is checked now.

**Comment by schrej** [comment]
It seems to be working fine for me, what browser are you using?
If you have time to waste you could also install the latest version from develop and test if the issue still occurs :P

**Comment by DaneEveritt** [comment]
I fixed this and forgot to close it.
