### ISSUE TITLE
Removing mounts when deleting a server

### ISSUE THREAD

**Issue by VanishedMC** [pterodactyl/panel#3553]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When deleting a server on the panel, all its related `mount_server` rows in the database are not cleaned up

### Describe the solution you'd like.

Clean up the mount relation when deleting a server

**Comment by matthewpi** [comment]
This shouldn't be a feature request, rows not being deleted (or detached) when one of their relations is deleted is a bug.
