### ISSUE TITLE
Adding / removing mounts to a server via application api

### ISSUE THREAD

**Issue by VanishedMC** [pterodactyl/panel#3554]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

There are currently no API endpoints to add or remove a mount from a server, this would be great for deployment over api

### Describe the solution you'd like.

adding endpoints PUT `/api/application/servers/5/mounts`, DELETE `/api/application/servers/5/mounts`

**Comment by matthewpi** [comment]
Will be added with v2, due to this being required to implement the existing functionality with the new UI.

**Comment by BenasPaulikas** [comment]
wen v2?
