### ISSUE TITLE
Mounts doesn't work

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3556]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Mounts dont work

### Expected Behavior

cache folder would be visible

### Steps to Reproduce

I've created mount in admin

source:
/var/lib/pterodactyl/mounts/cache

target:
/cache

enabled it for egg, node, server.

changed  config.yml
```
allowed_mounts:
- /var/lib/pterodactyl/mounts
- /home/cache
- /var/lib/pterodactyl/mounts/cache
```

```
/
cat: /home/cache: No such file or directory
cat: /cache: No such file or directory
cat: cache: No such file or directory
ls: cannot access 'cache': No such file or directory
ls: cannot access '/cache': No such file or directory
ls: cannot access '/home/cache': No such file or directory
ls: cannot access '/mnt/cache': No such file or directory
```

`ls` command on startup doesn't returns everything but not cache folder.

What am I doing wrong ?

### Panel Version

1.5.1

### Wings Version

1.4.7

**Comment by trenutoo** [comment]
Did you restart the wings and the specific server to apply the change?

**Comment by BenasPaulikas** [comment]
@Software-Noob yes wings was restarted. Server too. Many many times

**Comment by trenutoo** [comment]
Can you share the screenshot of your mount itself and the mount on the server? You missed something. I can make it work myself.

1. Create a folder `/var/lib/pterodactyl/mounts` with `test.txt` inside of it
2. Create a mount on the Panel with the source of `/var/lib/pterodactyl/mounts` and target `test`
3. Added the mount to the node and egg of the server.
4. On the admin panel "Mounts" tab of the individual server enabled the mount
5. Restarted Wings
6. Changed startup parameter to `ls test`, restarted the individual server and the contents were displayed.

```
:/home/container$ ls test
test.txt

**Comment by BenasPaulikas** [comment]
@Software-Noob did everything as you said however got

```
container@pterodactyl~ Error Event [03f485e3-666a-4f35-81c4-1bacd9cb0d82]: environment/docker: failed to create container: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'test' mount path must be absolute
```

so set target to `/test` instead of `test`

and `ls` is showing again only server folders

**Comment by trenutoo** [comment]
> @Software-Noob did everything as you said however got
> 
> ```
> container@pterodactyl~ Error Event [03f485e3-666a-4f35-81c4-1bacd9cb0d82]: environment/docker: failed to create container: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'test' mount path must be absolute
> ```
> 
> so set target to `/test` instead of `test`
> 
> and `ls` is showing again only server folders
> 

That looks like you set `test` as the source path instead. Please share the screenshot of your mount details as requested before. It's way easier to confirm that you set it all correctly that way.

ls will not show the mount as it's not actually inside the container. Use `ls <target path>` instead to view the mount, that is once you've fixed the wings mount error.

**Comment by BenasPaulikas** [comment]
![image](https://user-images.githubusercontent.com/6473565/130292049-0bfcdc54-9dd9-4026-9708-5a6e7988b10c.png)

```
:/home/container$ ls && ls test && echo "test"
KFGame
ls: cannot access 'test': No such file or directory```

And some more debug:
/var/lib/pterodactyl/mounts # cat test.txt
wololo

**Comment by matthewpi** [comment]
> :/home/container$ ls test
> ls: cannot access 'test': No such file or directory

You should be using `ls /test` not `ls test`

**Comment by BenasPaulikas** [comment]
Dang ok. It worked. Ty

I see I've tried something simmilar before but failed to make it work.

Maybe you also know if it's possible to add mount to server so it would be available during installation ?
If not maybe it's possible to define global mount for all docker containers ?

**Comment by trenutoo** [comment]
Mount is not available during the install. Right now, you have to apply it manually to each server.
