### ISSUE TITLE
imposible to map `ip link show` veth to server ?

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3559]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

ip link show reports

226301: veth9beece5@if226300: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master pterodactyl0 state UP mode DEFAULT group default 
    link/ether aa:1e:57:98:2e:e1 brd ff:ff:ff:ff:ff:ff link-netnsid 192
223229: vethff451e5@if223228: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master pterodactyl0 state UP mode DEFAULT group default 
    link/ether 66:39:54:9a:93:83 brd ff:ff:ff:ff:ff:ff link-netnsid 181
224767: vethd2c9cc6@if224766: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master pterodactyl0 state UP mode DEFAULT group default 
    link/ether d2:30:24:61:74:57 brd ff:ff:ff:ff:ff:ff link-netnsid 4

I found no way to map it to server ? And also it's not saved in database ?

### Expected Behavior

some unified system where It would be possible to understand which interface belongs to which server

### Steps to Reproduce

a

### Panel Version

1.5.1

### Wings Version

1.4.7

**Comment by parkervcp** [comment]
I'm trying to figure out what you are looking for here.

Those are docker interfaces and I don't see why it needs to be tracked in the panel.

**Comment by BenasPaulikas** [comment]
@parkervcp sorry i forgot to mention reason. I'm trying to implement wondershaper to limit upload/download bandwith to each server :)

**Comment by parkervcp** [comment]
As far as I understand, Docker spins these up and down in container stop and start. We aren't creating them.

I don't see you automating that united you do a lot of work around it. 

You could do `docker inspect` on the containers.

**Comment by matthewpi** [comment]
Docker manages these networks, not Pterodactyl or wings.
