### ISSUE TITLE
Feature requests for subusers

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#356]
First and foremost, it would be great if the server owner could select the first name, last name, and username of the account being created. I can see some potential problems with this (for example, if a malicious server owner creates hundreds of accounts to try and steal all the usernames or something) so perhaps maybe you can allow the admin to configure a limit on the amount of subusers each account can create per server? For example, the admin configures "Subusers Per Server: 5", so John Doe who owns Server1 can only make 5 subusers for that server.

Secondly, and this is my more highly desired request, would it be possible to configure another section in the Users tab that shows how many subusers a specific account is related to? Right now, when clicking on a user that's assigned as a subuser, it doesn't even show that subuser with an associated server. I understand why this is like this (because the user isn't the _owner_, and if they were the owner we can't delete the user account until the server is deleted), but I've been getting very confused lately with certain people creating subusers and I have no clue who they are, who created them, or what server they're associated with without going into each and every server manually and documenting them. Thus, I think it would be neat if there was another section on the Users page, maybe next to **Servers**, called **Subuser**, with a number next to it indicating how many servers this person is a subuser for. Then, if you click on their account, maybe it can show up under **Associated Servers** but with the fancy new **Subuser** icon.

**Comment by DaneEveritt** [comment]
Is this solved by #209?

I don't really get what your asking for here.

**Comment by xyeLz** [comment]
I think some of my request overlaps with #209, but I had an additional request. See my attached image:

http://imgur.com/S30fjn5
