### ISSUE TITLE
Suggestion for the mount system

### ISSUE THREAD

**Issue by lewanpe** [pterodactyl/panel#3564]
Hello,

Could the mount be automaticaly mounted on eggs parameter, for exemple for the garrysmod servers CSS to not force the admin to add manualy ?

**Comment by mason-rogers** [comment]
without issue template this'll likely be closed without even being considered - use feature request template

**Comment by matthewpi** [comment]
No, mounts will not be automatically attached.  However, there will be an option in v2 when creating a server to attach specific mounts.
