### ISSUE TITLE
panel fails to unarchive archive with space inside " example.zip"

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3567]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

panel fails to unarchive archive with space inside " example.zip"

### Expected Behavior

no failure

### Steps to Reproduce

0

### Panel Version

latest_version

### Wings Version

latest_version

**Comment by hwalker928** [comment]
Are you able to provide at least some error information, like wings logs?

**Comment by BenasPaulikas** [comment]
Aug 22 20:44:46 Ubuntu-1804-bionic-64-minimal wings[19654]: ERROR: [Aug 22 20:44:46.410] error while handling HTTP request error=opening zip reader: open /var/lib/pterodactyl/volumes/7d8a0784-0eee-412a-848d-0896d59f868a/name.zip: no such file or directory request_id=146cfec1-4edc-4060-bfa5-29765044e801 server_id=7d8a0784-0eee-412a-848d-0896d59f868a status=500 url=/api/servers/7d8a0784-0eee-412a-848d-0896d59f868a/files/decompress

even tho it's uploaded as " name.zip" notice space.

**Comment by parkervcp** [comment]
You have to actually work to make a file with a space at the beginning of the file name. I don't see this is a major issue or a regular one.
