### ISSUE TITLE
Why Minecraft Server just stop responding and freezing when it exceeds ram limit?

### ISSUE THREAD

**Issue by Envqu** [pterodactyl/panel#3568]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Why Minecraft Server just stop responding and freezing when it exceeds ram limit?
OOM Killer Disabled

### Expected Behavior

Why instead freeze server will not just lag or something?

### Steps to Reproduce

..

### Panel Version

1.5.0

### Wings Version

1.4

**Comment by parkervcp** [comment]
If a server runs out of am it will freeze. This is normal. If you are allocated 4 gigs of ram and use it all it will do the same thing. The host process can't get more to use and essentially hangs while waiting to get more.

This is not a pterodactyl issue, but an issue with how memory is allocated as a whole.
