### ISSUE TITLE
Remove drop down option from File Browser?

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#357]
Sorry for another seemingly stupid request, but this one actually came from one of my test users and I somewhat agreed with them after dissecting what they were trying to say.

First off, I want to say that I _do_ like the ability to have drop down menus in the left navigation pane. I think that's pretty slick and adds a flashy aesthetic feel to the panel. However, for File Management, 
it seems like it isn't really necessary and is redundant. There's already a "Create File" option on the File Browser page. If users use this page often (instead of SFTP), I guess it can become somewhat annoying for them to have to click File Management, let the drop down commence, and then click File Browser when really all they want to do is click File Browser from the get go. If they need to create a file, they can do so from the File Browser anyways.

Just some food for thought. Feel free to close this if you think it's stupid. I just thought it actually made sense.

**Comment by schrej** [comment]
I noticed that as well and totally agree with you. Any reasons not to do that @DaneEveritt ?

**Comment by DaneEveritt** [comment]
No reason go for it!
