### ISSUE TITLE
Error when creating Database for a Server (500 error)

### ISSUE THREAD

**Issue by Xen0Xys** [pterodactyl/panel#3571]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

I can't create a database for a server, I get the error: "An unexpected error was encountered while processing this request, please try again."

I have configured my Database like that:
  host: localhost
  port: 3306
  linked node: Master (my only node, where my database is)

I can specify that I have Panel and Wing on same VPS.
Thanks for your help!

### Expected Behavior

Normally, database will be created without any problems

### Steps to Reproduce

Try to create a database in a server

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
https://bin.ptdl.co/isyhi
```

**Comment by matthewpi** [comment]
You're database host has bad credentials, `SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'Xen0Xys'@'%' to database 's4_netherrp'`.  This is not a bug.

**Comment by Xen0Xys** [comment]
But I don't understand, user is configured with all rights, and the specified database isn't created, I am sorry but I don't understand why I have this...
