### ISSUE TITLE
Trailing slash messes up relative paths

### ISSUE THREAD

**Issue by crazygmr101** [pterodactyl/panel#3576]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Adding a trailing slash to the /server/<server-id> endpoint causes the relative paths for links on the control panel to be incorrect and result in a 404

### Expected Behavior

No 404
(idk where to put this but forcing an answer, especially with something like this, is rather annoying :( )

### Steps to Reproduce

Go to your panel, on the `/server/<server-id>` endpoint. Add a trailing slash, and click files.
The panel links to `./files`, which the browser interprets as `/server/<server-id>//files`, and 404's.

![image](https://user-images.githubusercontent.com/22755628/130826155-86f57376-1379-4923-bba7-b850161f8109.png)

### Panel Version

1.4.2

### Wings Version

1.4.5

### Error Logs

```bash
https://bin.ptdl.co/8i5i7/
```

**Comment by trenutoo** [comment]
Update your Panel and Wings. It's below the supported version.

Unable to reproduce this on 1.5.1/1.4.7, although not sure why you would try to modify the URL manually.

**Comment by crazygmr101** [comment]
> Update your Panel and Wings. It's below the supported version.

aAAAA will do

> Unable to reproduce this on 1.5.1/1.4.7, although not sure why you would try to modify the URL manually.

/files was what came up in my browser's autocomplete (since firefox's url bar can be searched by page title) and i just deleted the `files` portion, ending up with `server/xxxxxxx/`
![image](https://user-images.githubusercontent.com/22755628/130827248-e2862a46-d510-4f39-ba71-c0ff51a4f300.png)
Obviously, it's not a *normal* thing to do, but the fact it caused a 404 is undesirable. Will update and see if it's still a thing though

**Comment by crazygmr101** [comment]
Still an issue on 1.5.1/1.4.7, after following the manual upgrade steps from https://pterodactyl.io/panel/1.0/updating.html

**Comment by matthewpi** [comment]
https://github.com/remix-run/react-router/issues/4841

This is such a minor issue that requires the user to modify the URL that I'm not going to bother fixing it.  If we upgrade to react-router v6 (which is in beta, we currently use v5) it will force us to handle nested paths differently which should avoid this problem entirely.
