### ISSUE TITLE
[API] GraphQL API

### ISSUE THREAD

**Issue by Superkooka** [pterodactyl/panel#3579]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Expose two GraphQL schema for the "client" and "application" Pterodactyl APIs.

### Describe the solution you'd like.

Laravel have a fabulous package for GraphQL, [lighthouse](https://lighthouse-php.com/).

**Comment by matthewpi** [comment]
While I see the value in adding something like this, it's not needed.  The API already provides everything that is needed and adding a GraphQL API is just going to be another thing that can go wrong and that will need to be maintained.
