### ISSUE TITLE
Password resets show if account exists

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#358]
When going to reset a password, if you enter an email address that doesn't exist, it will tell you straight up that there is no record of the account. In my opinion, this is a security concern since a malicious user can continue to enter email addresses until they find one that actually resets. If they're determined enough, they can then go after that email address to try and hack into it and obtain access. I know it sounds ridiculous, especially for a small project like this, but I think the panel should simply say something like **If this user account exists, password reset instructions will be emailed to this address.** instead. This way, the user has no idea whether the account exists or not.

**Comment by schrej** [comment]
Hmmm. Some websites do it the way we do, others do it like you prefer it. I'd say it is more secure your way though.

**Comment by xyeLz** [comment]
No worries. :) I always like to think big picture. Bogs me down a lot of the time, but some day I'll feel super happy with the end result!

**Comment by DaneEveritt** [comment]
Should add a captcha to that page while we're at it.
