### ISSUE TITLE
ARM64 Support for Docker image

### ISSUE THREAD

**Issue by Cubxity** [pterodactyl/panel#3580]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add support for ARM64 for `ghcr.io/pterodactyl/panel`,

### Describe the solution you'd like.

Add ARM64 to platforms in GitHub Actions workflow file, similar to [here](https://github.com/pterodactyl/wings/blob/develop/.github/workflows/docker.yml#L56).

**Comment by parkervcp** [comment]
This required the base images to have arm 64 images as well.

`mhart/alpine-node` is amd64 only

**Comment by Cubxity** [comment]
It appears like `php:7.4-fpm-alpine` has support for ARM64. The alpine-node image doesn't, but I am not sure if that's needed for the builder image.

**Comment by parkervcp** [comment]
> It appears like `php:7.4-fpm-alpine` has support for ARM64. The node-alpine image doesn't, but I am not sure if that's needed for the builder image.

The node install is likely arch dependent and thus would fail this.

**Comment by Cubxity** [comment]
> The node install is likely arch dependent and thus would fail this.

Is there a reason that the image is used instead of `node:14-alpine`?

**Comment by Cubxity** [comment]
Update: using `FROM --platform=$BUILDPLATFORM mhart/alpine-node:14` eliminates the need for ARM64 support for builder stage.

**Comment by trenutoo** [comment]
This is definitely be possible. I have a different custom version running on my pi. I can take a look later if no one else does it before me.

**Comment by Cubxity** [comment]
> This is definitely be possible. I have a different custom version running on my pi. I can take a look later if no one else does it before me.

Mind sharing the custom version?

**Comment by trenutoo** [comment]
> > This is definitely be possible. I have a different custom version running on my pi. I can take a look later if no one else does it before me.
> 
> Mind sharing the custom version?

I am currently away on vacation this month. However, this is something I can tackle when I come back.

**Comment by lucasdidur** [comment]
Any update @Software-Noob about this?

**Comment by trenutoo** [comment]
> Any update @Software-Noob about this?

I've misunderstood the label that Matthew had assigned. I can try to take a look into this next week.
