### ISSUE TITLE
Docker and Server RAM

### ISSUE THREAD

**Issue by Envqu** [pterodactyl/panel#3581]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Can I set Minecraft Server RAM to 3GB for example, but docker ram (or something what killing/freezing server) to 4GB?

### Describe the solution you'd like.

.

**Comment by parkervcp** [comment]
The panel already over-allocates ram. If you are hitting the oom limits then it's already using more than was allocated.

**Comment by trenutoo** [comment]
Besides the existing overhead you can lower the XmX to accomplish this. `-Xmx$(({{SERVER_MEMORY}}-1024))M`

If you're using aikar flags, then do not pre-allocate all memory.
