### ISSUE TITLE
Stale multipart uploads using S3 backups do not get removed

### ISSUE THREAD

**Issue by Juha686** [pterodactyl/panel#3582]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Using S3 as backup storage, if a large backups fails it can leave stale multiparts behind on the S3 side. Some S3 compatible providers do not provide lifecycle rules for users, and as such this can become a "hidden" issue for some users.

```
Command: s3cmd multipart s3://bucket
Output:
s3://bucket/
Initiated       Path    Id
2021-08-09T07:00:10.799Z        s3://bucket/server_uuid/backup_uuid.tar.gz 2~multipart_id
2021-08-13T17:00:10.551Z        s3://bucket/server_uuid/backup_uuid.tar.gz 2~multipart_id
2021-07-28T19:10:08.960Z        s3://bucket/server_uuid/backup_uuid.tar.gz 2~multipart_id
2021-07-22T18:10:10.567Z        s3://bucket/server_uuid/backup_uuid.tar.gz 2~multipart_id
2021-08-02T07:10:22.598Z        s3://bucket/server_uuid/backup_uuid.tar.gz 2~multipart_id
```

```
Command: s3cmd multipart s3://bucket | wc -l
Output: 155
```

### Expected Behavior

A failed upload should not leave behind it's multiparts, or if there are any, they should get detected and deleted in a reasonable timeframe.

### Steps to Reproduce

Configure backups to use S3
Have a server large enough to warrant multipart uploads. 
Have the backup fail (Example: Setting backup state to done fails due to expired certificate. other failure modes are available)
Using s3cmd, run the following command: `s3cmd multipart s3://bucket`

If you see multipart uploads despite there being no backup jobs running, you have found a stale multipart upload.

### Panel Version

1.5.1

### Wings Version

1.4.7

**Comment by DaneEveritt** [comment]
This isn't a big, you can configure S3 to prune stale uploads at a given interval.
