### ISSUE TITLE
Failed (?) Json5 Syntax Highlighting Support

### ISSUE THREAD

**Issue by AL1L** [pterodactyl/panel#3583]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Opening a file with the `.json5` extension sets the syntax highlighting to Plain Text

### Expected Behavior

Opening a file with the `.json5` extension should set the syntax highlighting to JSON

This file has Json5 in the aliases, but doesn't seem to notice. Also not sure if this file is responsible for that

https://github.com/pterodactyl/panel/blob/3af9e926035aecb6c92689774f36a78cb5b5fb89/resources/scripts/modes.ts#L43-L50

### Steps to Reproduce

1. Navigate to a server console
2. Navigate to the file manager
3. If not already exists, create file with extension `.json5` and valid Json5 contents (e.g. `{}`)
4. Open (edit) the file
5. Notice the automatically selected language mode at the bottom right

### Panel Version

1.5.1

### Wings Version

1.4.4

### Error Logs

```bash
n/a
```

**Comment by matthewpi** [comment]
Highlighting for `json5` files works on v2.
