### ISSUE TITLE
TLS Bad Error Mac

### ISSUE THREAD

**Issue by KarloDerEchte** [pterodactyl/panel#3586]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Hello i have a very wierd Problem with my Panel i cant access the Servers anymore i checked the Logs and what i got is a 
2021/08/29 16:02:53 http: TLS handshake error from PUBLIC-IP:45288: local error: tls: bad record MAC i Updated the SSL Certificates but before i did this i saw that the current one isnt expired my Panel Server is behind a NGINX Reverse Proxy also some users are Reporting that they can start their servers but cant access the file manager the other ones are reporting that they can do nothing on their servers i readed the other Reports about this problem  but i couldnt fix this myself what is saw in the Panel Log is that a Certificate on Port 8080 has expired but this wars already 3 Months ago and now out of the blue its just dont working anymore i am currently on vecation and did nothing on my servers the last 2 weeks.

### Expected Behavior

No Problems with the Server

### Steps to Reproduce

Unknown, happend  randomly today with no modifaction  to the box in any way.

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
https://ptero.co/ezegosarid
http://bin.ptdl.co/kgrir
```

**Comment by parkervcp** [comment]
The error literally says `[2021-08-29 16:15:34] production.WARNING: GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: certificate has expired`

you should just need to regenerate the certs and restart wings.

**Comment by KarloDerEchte** [comment]
I regenerated the certificates but its not working anyway the last one should also not be expirered  becouse it got generated last month and told me that it will expire in 3 months

**Comment by parkervcp** [comment]
I you didn't restart after generating new certs it doesn't automatically load the new ones. You need to restart wings to use the new ones.

**Comment by KarloDerEchte** [comment]
Also a User Reported a expired certificate on Port 8080 if he Puts 8080 behind the Domain  but this one already expired 3 Months ago and the panel hat no Problems this morning

**Comment by KarloDerEchte** [comment]
> I you didn't restart after generating new certs it doesn't automatically load the new ones. You need to restart wings to use the new ones.

I restarted them also the Complete server

**Comment by DaneEveritt** [comment]
Just visit your Wings URL. https://panel.karlo-hosting.de:8080

Restart wings, this isn't a bug.

**Comment by poloskey** [comment]
yeah.. we're gonna restart wings every day now.
