### ISSUE TITLE
The console doesn't updating and the panel says "Starting"

### ISSUE THREAD

**Issue by VerusBungee** [pterodactyl/panel#3589]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Hi. I founded a bug.

This bug has a bug with the server panel because its says "Starting" and the console doesn't updating tho. 

The CPU is 0.00% / 100% doesn't updating tho
The memory doesn't updating 0 kB / 2 GB
The console doesn't updating

A screenshot of the bug: https://skidsterman-is-have.a-small-dick.tk/‍​​​​‍​​​‍‍‍‍​‍​​​​​​‍​‍​​‍‍‍​

### Expected Behavior

.

### Steps to Reproduce

.

### Panel Version

1.5 current, latest

### Wings Version

1.5 current, latest

### Error Logs

```bash
Wings: https://ptero.co/itamizosoj
Panel: tail: cannot open '/var/www/pterodactyl/storage/logs/laravel-2021-08-30.log' for reading: No such file or directory
```

**Comment by AreYouRlyScared** [comment]
Restarting wings should fix this.

Also you should put the actual version numbers. As wings isn't at 1.5.x
