### ISSUE TITLE
[Feature request] Make logs available from panel

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#359]
For ease of debugging, it could be interesting to have at least panel logs in the panel and why not daemon logs when it's possible ?

**Comment by DaneEveritt** [comment]
Most likely not going to implement this as there is logic required to store those logs in the DB, and then if that fails log them to the files anyways.

There is also a good chance people will not track this stuff and end up with thousands of logs in the DB slowing everything down.

Realistically users shouldn't even need to check logs unless something is not working, in which case checking a log that cannot be accessed by anything except a user on the system is a better idea. These logs can contain sensitive information, so storing them in the DB in just an additional attack surface, and encrypting them isn't really ideal (and just slows everything).

*However*, the log driver is highly extensible (thanks Laravel), so you can always write a custom module to do this as needed, and I would even encourage that and make it something installable with composer.
