### ISSUE TITLE
Reading files with html syntax fails.

### ISSUE THREAD

**Issue by jvvan** [pterodactyl/panel#3590]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When you open a file with html syntax, the panel just shows an error page.

This is probably due to the panel not being able to get the Content-Length header from wings.
[DaemonFileRepository.php:38](https://github.com/pterodactyl/panel/blob/e96ead4c4dbc947a78620d32b6662325dbc1626e/app/Repositories/Wings/DaemonFileRepository.php#L38)

### Expected Behavior

The panel should show the file's contents.

### Steps to Reproduce

- Go to the server's file manager.
- Create a file with HTML syntax (For example: `<html></html>`).
- Panel creates the file but fails to read it.

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
Wings: https://ptero.co/barasetidu
Panel: https://bin.ptdl.co/kz5j1/
```

**Comment by hwalker928** [comment]
Works fine for me.

**Comment by trenutoo** [comment]
Related to #2603 #2886
