### ISSUE TITLE
API request "POST /api/application/servers" sometimes returning error code 403

### ISSUE THREAD

**Issue by MinecraftiUndCo** [pterodactyl/panel#3592]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Sometimes we want to create a new server via the api of the panel and we use the endpoint **"POST /api/application/servers"** for that. We generated an api key with all rights (read & write) and are using this one for our requests.

Normally our API request goes through without any problems and we get the status code 201 back with all the information we need. In about half of the cases, however, we get a status code 403 back. We use the **exact same token, code, host & node** for all requests.

![grafik](https://user-images.githubusercontent.com/5124180/131581139-e965cabb-ad1e-43cd-9515-d22eb65b2f47.png)

In the panel log we find the entry that the node has returned the error 403 and the panel therefore probably only forwards this response. But this does not explain the behavior that the request sometimes works and sometimes not. Also all other requests for getting servers, deleting them and so on do not have any problem like this.

![grafik](https://user-images.githubusercontent.com/5124180/131581233-4e7cf453-fa6d-44b9-9135-7cddc682817b.png)

Because of this erratic behavior, we believe that there is an error with this endpoint or the status code 403 is incorrect.

### Expected Behavior

Since the API key is legitimized to create new servers, a 201 status should be returned in all cases and the request should be executed properly.

### Steps to Reproduce

Request for a new server via the named endpoint. Multiple attempts may be necessary to reproduce the error. We have been able to reproduce the error on two separate Pterodactyl instances.

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
https://bin.ptdl.co/30hcc/
https://ptero.co/wecetusoge
```

**Comment by iamkubi** [comment]
Presumably you use Cloudflare.  Check the Cloudflare firewall logs, it's likely the one returning the 403s.  If this is the case you can resolve it by whitelisting your IPs.

**Comment by MinecraftiUndCo** [comment]
Yes, we are using Cloudflare as our DNS provider, but all domains for the pterodactyl communication (panel, node) are added without proxy or filtering (I just checked that again to make sure it’s correct). And as you can see in the logs, the request is definitely arriving at the panel and later on also at the node.

**Comment by DaneEveritt** [comment]
Sorry, I don't have the skills or bandwidth necessary to try and reproduce something that to my knowledge is only happening to you. There is nothing special about that endpoint that would cause it to randomly return a 403 other than something standing between you and the endpoint stripping or modifying the request causing the token to be invalidated.

If you come to a more specific reproduction case feel free to re-open, but this error is far too vague and smells a lot like a networking specific issue — especially given the volume of people using this API without issue.
