### ISSUE TITLE
RCON not working properly

### ISSUE THREAD

**Issue by Envqu** [pterodactyl/panel#3593]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Minecraft server can see outside connection but it doesnt executing command.

![image](https://user-images.githubusercontent.com/70281617/131733614-447985d9-5a6d-4b1d-8b8d-bbe9b39c32fa.png)
This is showing in console when i trying to execute command via RCON.

I assigned RCON port in pterodactyl config.

### Expected Behavior

.

### Steps to Reproduce

.

### Panel Version

1.4.0

### Wings Version

1.4.2

**Comment by DaneEveritt** [comment]
This is not a software bug.

**Comment by Envqu** [comment]
Yes. This was a software bug.
I fixed it when I set network interface to "host".

**Comment by matthewpi** [comment]
> Yes. This was a software bug.
> I fixed it when I set network interface to "host".

RCON is handled within the egg, not by the panel or wings.
