### ISSUE TITLE
Allow SSL to be enabled even if the Node is behind a Proxy

### ISSUE THREAD

**Issue by Charismara** [pterodactyl/panel#3594]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Since i'm getting a ssl handshake error if ssl is diabled on my wing which is behind a cloudflare proxy it would be nice if the Panel would allow to enable ssl even if the Node if behind the Proxy. Otherwise i would have to always edit the node config by my own to enable it.

### Describe the solution you'd like.

Allow SSL to be enabled even if the setting "Behind Proxy" is enabled

**Comment by trenutoo** [comment]
Just don't enable behind proxy option? It's there to do just that, disable checking for ssl certificates on boot.

**Comment by Charismara** [comment]
well in that case i guess this is not needed.

Thank you anyways :)
