### ISSUE TITLE
Allow to set a custom ssl cert path for Nodes in Node Settings

### ISSUE THREAD

**Issue by Charismara** [pterodactyl/panel#3595]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Since i'm using a cloudflare cert which isn't located in the default path, i would love to set a custom path on Node creation or in the Node settings.

### Describe the solution you'd like.

An additional field in the Node Setting page to configure the cert & key path

**Comment by andrei0465** [comment]
You don't necessarily need that. You can edit /etc/pterodactyl/config.yml

**Comment by Charismara** [comment]
it's not necessarily needed but it would make life a bit easier if it would be possible

**Comment by andrei0465** [comment]
> it's not necessarily needed but it would make life a bit easier if it would be possible

I added and tested what you asked for. I do some more tests and I will come back with a pull request that you can take.
P.S: Certificates are automatically updated in /etc/pterodactyl/config.yml

![image](https://user-images.githubusercontent.com/19708361/132125804-5628d6ee-f3d3-4f3a-b71c-d933fdae378a.png)

**Comment by andrei0465** [comment]
#3600
