### ISSUE TITLE
Allow all origin to access the websocket

### ISSUE THREAD

**Issue by RyderAsKing** [pterodactyl/panel#3599]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Here is a example
pterodactyl running at `pterodacty.app`
a remote server running at `abcd.app`
```Access to XMLHttpRequest at 'http://pterodacty.app' from origin 'abcd.app' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://pterodacty.app' that is not equal to the supplied origin.```

Code: 
```js
<script src="{{ asset('js/socket.io.js') }}" crossorigin="anonymous"></script> <!-- Socket IO -->
<script>
const socket = io("wss://pterodacty.app:8080/api/servers/68f2c8c9-5e75-4258-b115-e6bcdeb0922a/ws", {
   reconnectionDelayMax: 10000
 });
</script>

```

I just feel like its pointless to have Access-Control-Allow-Origin set to the pterodactyl panel's URL for the websocket.
I was trying to connect to websocket from some other host and I wasn't able to do so due to this. Allowing everything would just add little more functionality for the developers. Obviously anyone can dig in the code and change it manually however when someone is a "client" himself and wants to use websocket directly instead of the panel (just an example). 

I was able to replace the origin header in a node JS app using https://www.npmjs.com/package/ws but its just impossible in a browser.

### Describe the solution you'd like.
Just allow all origin for the websockets
```
Access-Control-Allow-Origin: *
```

**Comment by trenutoo** [comment]
This is a Wings config value. You can allow all or specific origins using the `allowed_origins`array. By default, only panel origin is allowed.

```
allowed_origins:
- '*'
```

**Comment by tempusthales** [comment]
Still to this day this is not documented correctly on how to fix.

**Comment by Daisune** [comment]
Still to this day not documented

**Comment by FoksVHox** [comment]
> Still to this day not documented

Then open a PR to the documentation repo.

**Comment by Daisune** [comment]
You mean like the existing pull request to add it to documentation dating
back a solid 2-3 years?

**Comment by FoksVHox** [comment]
> You mean like the existing pull request to add it to documentation dating
> back a solid 2-3 years?

That PR hasn't been worked since the 15th of October 2022, but it doesn't mean that you can't make a PR, to add this value to the documentation.

**Comment by Daisune** [comment]
I mean realistically Documentation should be fleshed out from the people doing the work & building a platform & not a random layperson who is furiously googling to fix a issue That could have been documented by the Developers over 3 years ago.
Again. I'm not a Dev & have no clue what i would even be documenting. More of the fact that the only 2-3 places i have found anything have been in long long closed issues as opposed to anywhere in the published documentation
