### ISSUE TITLE
[Suggestion] Search to download plugin

### ISSUE THREAD

**Issue by themaster00mc** [Pterodactyl/Panel#360]
i think you should add a search thing to search for plugins on spigot/bukkit ive seen mcph have it and bisect hosting and it looked pretty nice and was really helpfoull and gave users more time

**Comment by DaneEveritt** [comment]
I have no plans to add game specific plugin managers to this panel. That is something that should be done with code extensions and template extensions.

**Comment by schrej** [comment]
I'm personally thinking about allowing services to extend panel functionality for that kind of stuff. Would need a good API though and definitely take some time
