### ISSUE TITLE
Create backup with API returning 422 when set ignored field

### ISSUE THREAD

**Issue by belinazzi** [pterodactyl/panel#3602]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Endpoint: /api/client/servers/xxxxxx/backups

Json Payload: 
```
{
  "name": "TESTE",
  "ignored": [
      "xpto",
      "xpto2"
  ]
}
```
Returning error:

```
{
    "errors": [
        {
            "code": "ValidationException",
            "status": "422",
            "detail": "The ignored must be a string.",
            "meta": {
                "source_field": "ignored",
                "rule": "string"
            }
        }
    ]
}
```

### Expected Behavior

This endpoint must accept "ignored" as an array.

### Steps to Reproduce

Simple send a POST request to the endpoint with ignored as an array

### Panel Version

1.5.1

### Wings Version

1.4.5

**Comment by belinazzi** [comment]
If used this: 
```
{
  "name": "TESTE",
  "ignored": "xpto"
}
```
The response is:

```
{
    "object": "backup",
    "attributes": {
        "uuid": "0fcbf2d6-bb34-460b-9e11-58061509387d",
        "is_successful": false,
        "is_locked": false,
        "name": "TESTE",
        **"ignored_files": [
            "xpto"
        ],**
        "checksum": null,
        "bytes": 0,
        "created_at": "2021-09-07T15:13:51-03:00",
        "completed_at": null
    }
}
```
The endpoint must accept array.

**Comment by matthewpi** [comment]
The endpoint excepts a string that can have multiple entries if they are separated by a newline (`\n`), this is intentional and will not be changing.

**Comment by belinazzi** [comment]
Thanks!! @matthewpi
