### ISSUE TITLE
Selective file restoring from backups

### ISSUE THREAD

**Issue by Feniksovich** [pterodactyl/panel#3607]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Usually, server backup are quite large. There are frequent cases when you need to restore only some files or just one (or the entire directory).

**To do this for now, you have 3 options:**
1. Restore entire backup.
2. Download backup to your PC, unarchive specific files and upload them to the server via SFTP.
3. Unarchive backup on a machine and move them to the server directory via SSH.

### Describe the solution you'd like.

So, it would be nice if you could view the contents of the backup in the panel UI and select needed files for restoring.
I'm not entirely sure if it's possible and how it change the  "backend architecture" of the backup system.

Select "Backups" tab -> Click "Restore" -> Option to restore entire backup or select specific files to be restored.

**Comment by matthewpi** [comment]
While this would be a useful feature, it's highly complicated and would still require that the entire archive be downloaded to the node if it isn't already stored locally.  Backups are provided as a one-click entire server archive, not a I need to restore `x` file from `x` date, there are much better solutions to handle stuff like that.
