### ISSUE TITLE
cannot start new nodejs discord bot server

### ISSUE THREAD

**Issue by 1Euro7Cent** [pterodactyl/panel#3608]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

1. I install a new NodeJS discord bot server and I want to start the server.
After pulling docker images and stuff this comes
![image](https://user-images.githubusercontent.com/67194495/132989993-5b36714f-ee74-4a82-b22a-2ca5815f9b21.png)
and nothing happens. Even after a lot of minutes
Sometimes the console will be spammed with \n.
I tried with changing docker image etc. and even updated the panel and wings to the newest version and still it doesn't work

on existing servers it works

2.And I have a second problem.
The servers don't have the correct time. The system has the correct time using npt

### Expected Behavior

1. to work and start the server
2. to have the correct time

### Steps to Reproduce

IDK. Creating a new DC bot server (NodeJS) and start it

### Panel Version

1.5.1

### Wings Version

1.4.7

### Error Logs

```bash
Wings: https://ptero.co/derilanasi
panel: http://bin.ptdl.co/qw24q
```

**Comment by parkervcp** [comment]
please restart wings.

**Comment by 1Euro7Cent** [comment]
I did, and it still doesn't want to start. Now it spamms the console with \n
oh. and the server is still marked as starting

**Comment by trenutoo** [comment]
The timezone of containers is set in the Wings `config.yml`. The "starting" status is covered in the egg readme that you should read.

Have you tried to restart both Wings and Docker,  and if so can you post the output of `uname -m`?

**Comment by 1Euro7Cent** [comment]
I fixed the other bugs but `uname -m` gives me `x86_64`

**Comment by 1Euro7Cent** [comment]
With other I mean every one except the starting bug

**Comment by gOOvER** [comment]
> I fixed the other bugs but `uname -m` gives me `x86_64`

Thats normal, that newer Linux Distros are x86_64

**Comment by trenutoo** [comment]
> With other I mean every one except the starting bug

So, does your server start now, or is it still stuck on finished pulling Docker image?

**Comment by 1Euro7Cent** [comment]
It is still stuck, but I tried MC server too and that works. Even a new server. That means it is a problem with NodeJS or am I wrong

**Comment by 1Euro7Cent** [comment]
I tried different NodeJS images too (10,12,14,15,16)
for all non default images I used https://github.com/Software-Noob/pterodactyl-images

**Comment by trenutoo** [comment]
Is the server stuck in starting, or stuck on the "finished pulling Docker image"?

Did you restart Docker and Wings?

**Comment by 1Euro7Cent** [comment]
on finished pulling
and how do i restart docker

**Comment by trenutoo** [comment]
The same way you restart any other Linux service, including Wings. `systemctl restart docker`

**Comment by 1Euro7Cent** [comment]
restarted both and still stuck in finished pulling Docker image

**Comment by gOOvER** [comment]
i think, thats a bug in Petro. I cant say, where, but i have the same issue with some images. And a lot of users too.

**Comment by 1Euro7Cent** [comment]
> i think, thats a bug in Petro. I cant say, where, but i have the same issue with some images. And a lot of users too.

so what could i do to fix that

**Comment by gOOvER** [comment]
> > i think, thats a bug in Petro. I cant say, where, but i have the same issue with some images. And a lot of users too.
> 
> so what could i do to fix that

if i know that, i wouldn't have the same issues with some images :).

**Comment by DaneEveritt** [comment]
Without steps to reproduce I'm not leaving this issue open, sorry. Feel free to re-open it when concrete reproduction steps can be provided.

**Comment by BasToTheMax** [comment]
It looks like I have the same issue, but I don't know what it caused or how to fix it

**Comment by andreasclaesson** [comment]
I had this issue once but it was only because the machine I bought was accidentally OpenVZ
