### ISSUE TITLE
Suspending server causes failed server deletion

### ISSUE THREAD

**Issue by Dpendable** [Pterodactyl/Panel#361]
## Server  Info
```
Linux 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
PHP 7.0.17-2+deb.sury.org xenial+1 (cli) (built: Mar 15 2017 09:21:55) ( NTS )
```
```
Panel 0.5.7
Daemon 0.3.7 (Latest: 0.3.7)
```

Scenario
---------------------
I created a test node, and a test server on that node (it was a ts server). After I was done testing I wanted to delete the server. I suspended the server, Idk I figured it might be safer for it to be suspended when I try to delete, I then click the delete (not force delete) option. We looked the server was still there. We figured maybe it was on a delay. So then I looked and saw the 10 minute timer. 10 minutes passed, still there so I attempted to force delete. So, I just figured I would look into it later, and worked on something else. Then the next morning while testing the API call for account creation from my E-commerce platform I noticed the accounts weren't being created. So started looking into it. Ended up restarting the worker/supervisor and then noticed the account was created. So I figure the worker got hung up on trying to delete the server or something. So that night I was wanting to test more but I didn't want to create a bunch of stuck servers. So i looked into manually deleting the previous one. Starting with trying to remove the from the DB.

Tried to truncate the servers, table and received:
```
> ERROR 1701 (42000): Cannot truncate a table referenced in a foreign key constraint (panel.allocations, CONSTRAINT allocations_assigned_to_foreign FOREIGN KEY (assigned_to) REFERENCES panel.servers (id))
```
Then tried to truncate allocation table and received:
```
> ERROR 1701 (42000): Cannot truncate a table referenced in a foreign key constraint (panel.servers, CONSTRAINT servers_allocation_foreign FOREIGN KEY (allocation) REFERENCES panel.allocations (id))
```

SS's
---------------------
https://i.gyazo.com/1b42f5585784880e1e9a5b6120c22360.png
https://i.gyazo.com/28aad58c780aef029c4043ef442e3119.png
https://i.gyazo.com/4774f5a499a13b05748a7e5369a3c584.png

Additional
---------------------
Force deleting the server without suspending prior works fine.
https://i.gyazo.com/64eab6d3b793a10aa750163c91448d76.png

If you would like me to do any additional testing let me know.

**Comment by schrej** [comment]
Did you test deleting multiple times? You said you had to restart supervisor at some point. Are you sure it got stuck because of the suspended server? I'd assume the server just didn't get deleted because of the supervisor not running correctly.

**Comment by Dpendable** [comment]
The scenario describes the first time I tried it. I went back and was able to replicate it the next night. Using the same methodology. Fresh pterodactyl database, added node, added server, suspend server, then delete server. If you would like any further information about the environment, let me know and I'll see what I can do about providing it.

**Comment by DaneEveritt** [comment]
I'm tempted to just scrap that queued deletion system and go back to immediate deletion.

**Comment by DaneEveritt** [comment]
closed by https://github.com/Pterodactyl/Panel/commit/536865b22a80c2277cd3ff8d6b777c1d7131e582
