### ISSUE TITLE
About the decompression function

### ISSUE THREAD

**Issue by fishfuture** [pterodactyl/panel#3612]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

I decompress the zip package when I use it. When there are files in the file named as Chinese, the wrong encoding will be decompressed and cannot be deleted. You need to go to ssh to delete it.

### Expected Behavior

Hope it can display Chinese normally

### Steps to Reproduce

Unzipped folders or files with Chinese characters appear garbled

### Panel Version

1.6.0

### Wings Version

1.5.0

**Comment by WaffleThief123** [comment]
Do you have an example zip to test with?

**Comment by matthewpi** [comment]
Closing due to lack of a reply with a specific example.
