### ISSUE TITLE
Build configuration Not updating

### ISSUE THREAD

**Issue by andy01745** [pterodactyl/panel#3613]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When trying to update a servers Build configuration which has already been created everything turns back to the way it was before you edited it. So for example if i had set CPU limit to 250%. when i got in and change it to 350% it goes back to 250% after clicking update Build configuration.

I have looked over the logs and nothing shows up to be wrong. 

### Expected Behavior

When changing something under build configuration settings it is expected to stay as what you set it to not revert backwards

### Steps to Reproduce

Go into the admin panel. Go to a server that you have created and try to change anything under build configuration.

### Panel Version

1.6.0

### Wings Version

1.5.0

### Error Logs

```bash
No logs get shown
```

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/pull/3610
