### ISSUE TITLE
Api endpoint for schedule activation

### ISSUE THREAD

**Issue by JeroenoBoy** [pterodactyl/panel#3618]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like an api endpoint for activating server schedules, maybe something like
```
GET https://pterodactyl.file.properties/api/client/servers/1a7ce997/schedules/{schedule}/run
```

### Describe the solution you'd like.

This has pretty much been discribed above, but i would like an endpoint like
```
GET https://pterodactyl.file.properties/api/client/servers/1a7ce997/schedules/{schedule}/run
```

**Comment by mason-rogers** [comment]
https://github.com/pterodactyl/panel/blob/develop/routes/api-client.php#L77 this route already exists. its just called execute not run

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/blob/develop/routes/api-client.php#L77

**Comment by JeroenoBoy** [comment]
> https://github.com/pterodactyl/panel/blob/develop/routes/api-client.php#L77 this route already exists. its just called execute not run

Thanks for pointing out, but its not been defined in the api documentation, so i assumed it didn't exist.
