### ISSUE TITLE
CSRF token mismatch

### ISSUE THREAD

**Issue by OneHitX** [pterodactyl/panel#3619]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When logging into Pterodactyl the error "CSRF token mismatch." appears, denying access.

![image](https://user-images.githubusercontent.com/25916072/133151898-80469538-70be-4c06-a8e3-3bdbbe5e0167.png)

### Expected Behavior

This error is usually caused by SSL problems, however the server has a valid SSL in the APP_URL and also when accessing the URL (https://painel.purplehost.com.br) it is functional. Connection to nodes was not affected.

Changing the SESSION_SECURE_COOKIE to false had no result and the problem remains. Even after pteroq, nginx and php-fpm restart. Clear cookies and access via anonymous window also without result.

![image](https://user-images.githubusercontent.com/25916072/133152047-9ff3a1c4-8f87-479e-a12e-23ca9dfb2cd3.png)

### Steps to Reproduce

Open the panel --> fill in your valid credentials --> login.

### Panel Version

1.6.0

### Wings Version

1.5.0

### Error Logs

```bash
http://bin.ptdl.co/mtg0e
```

**Comment by DaneEveritt** [comment]
This is not a bug with this software, please use Discord for further support.
