### ISSUE TITLE
Scheduler is not executed

### ISSUE THREAD

**Issue by lMozGl** [pterodactyl/panel#3621]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

The scheduler does not execute the commands given to it, instead it just goes into proccessing mode and waits - which is not clear.

### Expected Behavior

In the case of this error, just at least execute the command.

### Steps to Reproduce

According to the instructions, CRON was configured to execute the command every minute and run it in the background.
A scheduling rule has been added to the installed minecraft server, which should issue the command to the server 'say Server restart in 5 minutes', at the specified time 5:55. When this time is reached, the scheduler starts executing the specified command, but it goes into processing mode without executing the command and does nothing else.

### Panel Version

1.6.0

### Wings Version

1.5.0

### Error Logs

```bash
There are no error logs
```

**Comment by trenutoo** [comment]
Check the status of the pteroq.service and restart it.

**Comment by lMozGl** [comment]
Thanks a lot. Restarting the service helped solve the problem.
