### ISSUE TITLE
Form is not sent to HTTPS if APP_URL environment is https URL

### ISSUE THREAD

**Issue by zandercodes** [pterodactyl/panel#3623]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

I have Pterodactyl Panel running in a Docker container and is used with a reverse proxy "Traefik".
The problem is that form are always sent to "http" although APP_URL environment is "https".

### Expected Behavior

Actually the form should be sent to https if https is specified in the environment

### Steps to Reproduce

1. Create a Traefik v2
2. Reverse Proxy the Pterodactyl Panel
3. Create a Server
4. And see the warning from the browser

### Panel Version

1.6.1

### Wings Version

1.5.0

**Comment by trenutoo** [comment]
Can you set `TRUSTED_PROXIES='*'` in your dotenv file?

**Comment by DaneEveritt** [comment]
This is not a bug with this software.

**Comment by zandercodes** [comment]
> 
> 
> This is not a bug with this software.

But I think so

I have change the `AppServiceProvider.php` and add two lines
```php
...
use Pterodactyl\Models\Subuser;
use Illuminate\Support\Facades\URL; <- Add this
use Illuminate\Support\Facades\Schema;
...
    public function boot()
    {
        URL::forceScheme('https'); <- Add this
        Schema::defaultStringLength(191);
...
```
and the problem is solve.

I think Pterodactyl has no detection for https

---

For example, the function `boot` in `AppServiceProvider.php` can be extended as follows
```php
...
    public function boot()
    {
        if (!empty(env('APP_URL')) && str_starts_with(env('APP_URL'), 'https')) {
            URL::forceScheme('https');
        }
...
```

**Comment by matthewpi** [comment]
> > This is not a bug with this software.
> 
> But I think so
> 
> I have change the `AppServiceProvider.php` and add two lines
> 
> ```
> ...
> use Pterodactyl\Models\Subuser;
> use Illuminate\Support\Facades\URL; <- Add this
> use Illuminate\Support\Facades\Schema;
> ...
>     public function boot()
>     {
>         URL::forceScheme('https'); <- Add this
>         Schema::defaultStringLength(191);
> ...
> ```
> 
> and the problem is solve.
> 
> I think Pterodactyl has no detection for https
> 
> For example, the function `boot` in `AppServiceProvider.php` can be extended as follows
> 
> ```
> ...
>     public function boot()
>     {
>         if (!empty(env('APP_URL')) && str_starts_with(env('APP_URL'), 'https')) {
>             URL::forceScheme('https');
>         }
> ...
> ```

Well that value is what allows this to work, I've had the exact same problem https://github.com/pterodactyl/panel/issues/2289

Make sure you have cleared your config cache by running `php artisan config:clear`.

**Comment by hackmoore** [comment]
I seem to be having this issue as well. I've added the `TRUSTED_PROXIES='*'` to my `.env` file. I also ran the `php artisan config:clear` command which didn't seem to help. Any suggestions?

**Comment by thafer30** [comment]
I think this is a legitimate issue that deserves some attention. There are multiple closed issues that all boil down to this same problem and there is a solution that works given here by @zandercodes. The solution documented given here (https://pterodactyl.io/panel/0.7/configuration.html#reverse-proxy-setup) of supplying "TRUSTED_PROXIES=*" in a .env file simply does not work in many situations where a reverse proxy is used. 

#2938
#2289
#3500
#3623
#704
#277
#3371

**Comment by leytilera** [comment]
> ```
> if (!empty(env('APP_URL')) && str_starts_with(env('APP_URL'), 'https')) {
>             URL::forceScheme('https');
>         }
> ```

This should be included in the official releases

**Comment by birkhofflee** [comment]
We're hitting the same issue in a new installation (canary) setup behind Traefik. This breaks the panel entirely as settings cannot be changed.

**Comment by zandercodes** [comment]
@DaneEveritt Thanks for fixen
