### ISSUE TITLE
Discord.py 2.0

### ISSUE THREAD

**Issue by FroostySnoowman** [pterodactyl/panel#3628]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hello,

As some of you know discord.py is shutting their services down. This means they won’t update discord.py anymore. I would love to have a docker image with discord.py 2.0 instead of the other version, it would be so much help to a lot of people! Here’s the pip install command to download it: pip install -U git+https://github.com/Rapptz/discord.py

### Describe the solution you'd like.

I would love to see the docker image on the panel so myself along with a lot of other people can use this amazing panel!

### Additional context to this request.

N/A

**Comment by trenutoo** [comment]
There's egg for running python applications on the [Parkers egg repository.](https://github.com/parkervcp/eggs/tree/master/bots/discord/discord.py). 

You don't need a custom image for specific modules. The egg can install pip modules.

**Comment by FroostySnoowman** [comment]
Let’s say I install it, do I run the pip command like normal into the console?

**Comment by trenutoo** [comment]
> Let’s say I install it, do I run the pip command like normal into the console?

It contains startup variables to install different modules.
