### ISSUE TITLE
"no stop configuration detected for environment, using termination procedure container_id=" after wings restart

### ISSUE THREAD

**Issue by realkarmakun** [pterodactyl/panel#3629]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

For some reason some of my servers with stop-backup-start schedule happen to be terminated instead of stopping gracefully. This resulted in broken server state on backup. 
Specific lines in wings logs:
```
Sep 18 00:05:04 hades.rustme.ru wings[1016559]:  WARN: [Sep 18 00:05:04.499] no stop configuration detected for environment, using termination procedure container_id=ce15eb97-9086-4382-91d6-4524d93e0c75
Sep 18 00:05:04 hades.rustme.ru wings[1016559]:  WARN: [Sep 18 00:05:04.699] no stop configuration detected for environment, using termination procedure container_id=8c2ebb91-f617-4ecd-8f8a-5b76f1135a30
Sep 18 00:05:04 hades.rustme.ru wings[1016559]:  WARN: [Sep 18 00:05:04.796] no stop configuration detected for environment, using termination procedure container_id=c608e78f-c7ca-46f2-a4f4-7ae57fbcb2cb
```

### Expected Behavior

We expect server to start properly.

### Steps to Reproduce

Not sure. This server have been created since ancient versions of pterodactyl. Thinking 1.0. This could be contributing to the issue. 
Also updated to latest wings version and panel today. In paper egg `stop` command is under "Stop command". OOM is also disabled everywhere.
Could this be result of running containers while updating? 

### Panel Version

1.6.1

### Wings Version

1.5.1

### Error Logs

```bash
https://ptero.co/udibodutew.coffeescript
```

**Comment by realkarmakun** [comment]
Also on a note:
We have badly written plugin on them. It keeps all the data in RAM and saves is to the disk on the stop (yeah I'm aware of how bad this design is). It takes around 1-2 minutes to complete the stop procedure. Usually we add a big buffer after stop command on restart schedule before backup, so backups won't be "broken". But according to MC logs servers were just killed on the spot.

UPD: Also tried fetching panel logs but there was no logs to this date. 

UPD2: One of the engineers was updating the panel with self-update command. It didn't work at first (version in Admin Panel Overview was old). So he retyped it. Everything else went as expected

**Comment by DaneEveritt** [comment]
Sounds like the egg you're using is configured incorrectly.

https://github.com/pterodactyl/wings/blob/6b5b42ec58da1892c1ef09848a17672a1f207421/environment/docker/power.go#L142-L144

The type value should be `"signal"` (to send a signal, likely not what you want here), or `"command"` with `value` set to the command to send.

**Comment by realkarmakun** [comment]
> Sounds like the egg you're using is configured incorrectly.

I'm using official Paper egg. I guess it broke on the update for some reason (It works now though)

**Comment by realkarmakun** [comment]
@DaneEveritt Just got this again:
```
Oct 14 21:54:34 ns3192193 wings[2959056]:  INFO: [Oct 14 21:54:34.317] detected server is running, re-attaching to process... server=e325e831-528a-464b-b5f5-1eeb817593f4
Oct 14 21:54:34 ns3192193 wings[2959056]:  INFO: [Oct 14 21:54:34.318] starting resource polling for container container_id=ba26edd2-6505-4d51-bdd6-da5b9c9bed84 environment=docker
Oct 14 21:54:34 ns3192193 wings[2959056]:  INFO: [Oct 14 21:54:34.318] detected server is running, re-attaching to process... server=bb585fb5-6794-4662-96c1-37c1d994bb64
Oct 14 21:54:34 ns3192193 wings[2959056]:  INFO: [Oct 14 21:54:34.318] starting resource polling for container container_id=ad332323-e97e-477e-8a7b-7d91649aa0ee environment=docker
Oct 14 21:54:34 ns3192193 wings[2959056]:  INFO: [Oct 14 21:54:34.319] starting resource polling for container container_id=e325e831-528a-464b-b5f5-1eeb817593f4 environment=docker
Oct 14 21:54:34 ns3192193 wings[2959056]:  INFO: [Oct 14 21:54:34.319] starting resource polling for container container_id=bb585fb5-6794-4662-96c1-37c1d994bb64 environment=docker
Oct 14 21:54:34 ns3192193 wings[2959056]:  INFO: [Oct 14 21:54:34.320] configuring internal webserver host_address=0.0.0.0 host_port=8080 use_auto_tls=false use_ssl=true
Oct 14 21:54:34 ns3192193 wings[2959056]:  INFO: [Oct 14 21:54:34.320] updating server states on Panel: marking installing/restoring servers as normal
Oct 14 21:54:34 ns3192193 wings[2959056]:  INFO: [Oct 14 21:54:34.320] sftp server listening for connections listen=0.0.0.0:2022
Oct 14 21:54:47 ns3192193 wings[2959056]:  WARN: [Oct 14 21:54:47.265] no stop configuration detected for environment, using termination procedure container_id=ad332323-e97e-477e-8a7b-7d91649aa0ee
```
It happens specifically at their first stop/restart action after wings restart. One time for a each server on a machine.
This is how it looks like when I use stop button for a server.
![изображение](https://user-images.githubusercontent.com/20980281/137401314-77e9a103-5bc1-4546-83c0-8028a1b57e27.png)
As I said I use official Paper egg and I have `stop` command in stop configuration on the egg.

UPD: I can pretty much replicate it. I think so at least. Is there anything I can do to collect more info?

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/wings/commit/7899a7abdf063e0d0f2381ba26c9451e288e635a

**Comment by realkarmakun** [comment]
> 
> 
> [pterodactyl/wings@7899a7a](https://github.com/pterodactyl/wings/commit/7899a7abdf063e0d0f2381ba26c9451e288e635a)

When will it be in release?
