### ISSUE TITLE
I can't proxy HTTP/HTTPS data with WINGS.

### ISSUE THREAD

**Issue by snaildos** [pterodactyl/panel#3630]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Anyone using my host, can easily run 
`curl ifconfig.me`, this is where the problem starts.
We host down in Australia in a office, and having our IP leaked means, DDOS attacks and more.
All I want to do, is just easily route all HTTP and HTTPS data to a proxy up in the cloud with DDOS protection, advanced scaling and more.

### Expected Behavior

After following every guide, and every SINGLE possible way to proxy all containers, wings continues to still not like me, and not proxy any data.

![image](https://user-images.githubusercontent.com/46210117/133879392-62939d0f-68f9-48ff-9d4c-11b065ab7492.png)

As you can see, these are the 3 way to proxy with docker, I followed all 3, but I think wings uses some sort of different networking method.
The expected behavour is to show the proxy server IP, not the office.

Yes, the proxy server 100% works, I alerady set it up with the proxy conf file in ubuntu.

### Steps to Reproduce

- Setup a proxy server
- Connect to it with all 3 ways mentioned in the diagram
- Also setup enviroment values and .bashrc
- Run a container, and your IP will still be shown.

### Panel Version

1.4.0

### Wings Version

1.4.2

### Error Logs

```bash
None required.
```

**Comment by DaneEveritt** [comment]
"Setup a proxy server" is not a step that describes anything of what you're trying to do. Not to be curt, but I barely have time to work on this project as is it, so unless you're able to provide very clear and reproducible steps for me to use — and even understand if this is an issue with Wings or just Docker in general — this issue is likely just going to be ignored and eventually closed.

**Comment by snaildos** [comment]
I don't think it's going to work, I put so much time into it and it's not working
So I will end up using wiregaurd.
Thanks for your time!
