### ISSUE TITLE
Password SQL base KO with $ symbol

### ISSUE THREAD

**Issue by Allread** [pterodactyl/panel#3632]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Hello 

When installing the script, at the request of the SQL database password, I had a "$" symbol in the password.
I was unable to complete the installation.

It does not support "$"

### Expected Behavior

Password validation ko

### Steps to Reproduce

In "password SQL", type password with "$" symbol

### Panel Version

1.6

### Wings Version

1.4

**Comment by DaneEveritt** [comment]
Failure to provide error logs.

**Comment by EuleMitKeule** [comment]
I can confirm this for `ghcr.io/pterodactyl/panel:v1.11.2`.
When I had special characters in my SQL password, panel would fail to start (500 Server error) and the logs would say that the SQL login failed. After changing the password to just alphanumeric it worked fine.
