### ISSUE TITLE
Server Transfer API Endpoint

### ISSUE THREAD

**Issue by astrooom** [pterodactyl/panel#3633]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Exposing server transfer as an API endpoint would be very useful.  Currently, there seems to be no way of doing it without going on the panel and clicking a button.

### Describe the solution you'd like.

I think the best way to do it is by letting the API user input values for server_id (of which server to transfer), new_node_id, and new_allocation_id. Maybe a feature to let it automatically choose the allocation id of the same port as the existing primary allocation, but no more required, really.

**Comment by mason-rogers** [comment]
this would be possible once v2 releases because of the nature of SPA's - anything you can do in the new frontend will be possible via the api

**Comment by astrooom** [comment]
> this would be possible once v2 releases because of the nature of SPA's - anything you can do in the new frontend will be possible via the api

That's great news!

I'm in need for a way to call server transfers remotely, whether it can be called with the API, through the database, or in another other way, doesn't really matter. Please let me know if there is a way to do so right now as well until the V2 update is released :)

**Comment by matthewpi** [comment]
I'm just going to close this, adding an application endpoint for this is required for the new admin in v2 to have this feature which I plan to implement.  There is no point in tracking this, it will be implemented by the time v2 is released.
