### ISSUE TITLE
CPU usage broken in Liquorix kernel

### ISSUE THREAD

**Issue by sapphonie** [pterodactyl/panel#3637]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

CPU usage shows at %0 despite docker cpu usage:

![image](https://user-images.githubusercontent.com/15315481/133942513-64d7c98a-bd19-479e-a86a-f9ec129f1d38.png)

Cpu usage is perfectly visible in netdata, for example: 
![image](https://user-images.githubusercontent.com/15315481/133942489-8b43a4c9-51eb-4a80-8af3-9c9afc5bc134.png)

### Expected Behavior

CPU usage should be shown properly

### Steps to Reproduce

Install [Liqourix Kernel](https://liquorix.net/)

### Panel Version

1.6.1

### Wings Version

1.5.1

### Error Logs

https://ptero.co/ibogufeqis

**Comment by parkervcp** [comment]
Have you done a system update recently? If you have, did restarted docker?

**Comment by notAreYouScared** [comment]
Please also check `docker stats`, if that reports 0 CPU usage then it's an issue not related to pterodactyl/wings. As those stats are pulled directly from docker.

**Comment by sapphonie** [comment]
> 
> 
> Please also check `docker stats`, if that reports 0 CPU usage then it's an issue not related to pterodactyl/wings. As those stats are pulled directly from docker.

If that's the case, than this appears to be a bug with liq: 
![image](https://user-images.githubusercontent.com/15315481/134079661-1e3e8a4b-a2c3-478a-88ee-83fa61b104f8.png)
