### ISSUE TITLE
Exporting Database

### ISSUE THREAD

**Issue by Jelcoo** [pterodactyl/panel#3641]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be nice if there was a database export button. It creates a mysqldump of the database and the dump gets downloaded on your device.

### Describe the solution you'd like.

The download system can be the same as the backup download system. The export button can be located next to the "rotate password" button.

**Comment by notAreYouScared** [comment]
I was working on this. The issue arises of how big databases can be. It would put alot of load on either the panel or wings to export the database to a single file. 

Tools like phpmyadmin, mysql workbench, etc. Would be best to export the database with the credentials provided on the databases page.

**Comment by FoksVHox** [comment]
> I was working on this. The issue arises of how big databases can be. It would put alot of load on either the panel or wings to export the database to a single file.
> 
> Tools like phpmyadmin, mysql workbench, etc. Would be best to export the database with the credentials provided on the databases page.

@AreYouRlyScared Wouldn't it be possible to put it in a Laravel job?

**Comment by notAreYouScared** [comment]
It could yes, but where would this said sql file be stored? On the webserver for the panel? Or would it be shipped to wings and in the servers directory?. Databases can be HUGE. 

@DaneEveritt @matthewpi  we talked about this a while ago. Want to add your two cents?

**Comment by ItzKazuki** [comment]
looks like it will be impossible, I use the database for the Minecraft server, it's already 2gb just for the database😏

**Comment by skw359** [comment]
there could be a size limit exporting from the panel, say if anything over 2GBs, no you can't, but anything under, sure

**Comment by DaneEveritt** [comment]
@AreYouRlyScared really delayed on this, but my opinion is you should be using a dedicate tool to generate exports, not the Panel. All the Panel is doing is just providing a nice wrapper to manage creation of the database and seeing them — it was never designed to be a management UI for them.

Perhaps better handled in https://github.com/pterodactyl/panel/issues/2571 which would be a backup, rather than an on-demand export.
