### ISSUE TITLE
Mass transfer and delete servers from panel.

### ISSUE THREAD

**Issue by JimDude7404** [pterodactyl/panel#3642]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like an option to mass delete and/or transfer servers. This would make it so I could select all of the servers of a given node and transfer this. Add this to the Servers page under Nodes. This would make things soo much more easier instead going thru multiple clicks to just transfer a server. Just require that there be enough allocations for the amount of servers you wish to transfer.

### Describe the solution you'd like.

Like when you goto the nodes page you can checkmark servers to transfer/delete.

**Comment by DaneEveritt** [comment]
Won't implement, this software isn't designed for that type of infrastructure management.
