### ISSUE TITLE
Server runs in the background and cannot be restarted or stopped

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3643]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

With certain ports the server can no longer start, the server is still running on this port in the background. Restarting the server does not solve the problem.

```
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/core 
Digest: sha256:3265256f9d729a38cd73f64b2e0545699848a378bee0b15f7c7c6469f07a4d10 
Status: Image is up to date for quay.io/pterodactyl/core:source 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
container@pterodactyl~ Error Event [7f24f2c9-4546-4f07-84c2-15db9be63bed]: environment/docker: failed to start container: Error response from daemon: driver failed programming external connectivity on endpoint b64468ee-e0cf-4754-b83e-d9c565325573 (b7a2e4923ea2c92d2db3ba237d7641bd94edf4ade9c795328385bcbc69a72bf4): Bind for ****:25581 failed: port is already allocated
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 128
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
```
https://i.imgur.com/74tfbB7.png

### Expected Behavior

please find a solution how to stop the server in the background and that soon the error will not come again.

### Steps to Reproduce

idk

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

```bash
Wings: https://ptero.co/uquwumacub
Panel: http://bin.ptdl.co/37kv8
```

**Comment by parkervcp** [comment]
What server is this for?

**Comment by danny6167** [comment]
Pretty clear from the wings logs that no container is still running using that port.
Did you check the output of `` ss -plnt | grep 25581`` ?

**Comment by Felix5566** [comment]
> 
> 
> What server is this for?

Minecraft

**Comment by Felix5566** [comment]
> 
> 
> Pretty clear from the wings logs that no container is still running using that port.
> Did you check the output of ` ss -plnt | grep 25581` ?

https://i.imgur.com/EdbM3lD.png

**Comment by danny6167** [comment]
Suggests that docker-proxy didn't terminate for some reason?
I haven't seen that before, but doesn't look like a panel issue to me.

**Comment by Felix5566** [comment]
> 
> 
> Suggests that docker-proxy didn't terminate for some reason?
> I haven't seen that before, but doesn't look like a panel issue to me.

but it says that it is executed by docker

**Comment by DaneEveritt** [comment]
Not a bug with this software, likely a fluke or a bug with docker on your system.

**Comment by Felix5566** [comment]
this is no coincidence it has already happened very often.

> 
> 
> Not a bug with this software, likely a fluke or a bug with docker on your system.
