### ISSUE TITLE
Suspending the server does not shut down it

### ISSUE THREAD

**Issue by miniSpoXster777** [pterodactyl/panel#3644]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

The server does not shut down during server suspend. In order for the server to shutdown you need to unsuspend and it will then shutdown

### Expected Behavior

The server should shut down during suspend, not during unsuspend

### Steps to Reproduce

Enter the console of the running server

In the second window, enter the server administration section

Suspend server and check console (server should be still online)

Return to the server administration section

Unsuspend server and check console (at this moment server should shut down)

### Panel Version

1.6.2

### Wings Version

1.5.1

**Comment by danny6167** [comment]
Can confirm.

When suspending a server in the panel the container doesn't get stopped and the only log entry is this
``INFO: [Sep 24 21:00:15.271] performing server limit modification on-the-fly server=71249cba-b214-41d1-8ca1-04b1ede94c8a``

After un-suspending a server it logs this and then begins to shutdown.
``INFO: [Sep 24 21:02:32.708] server suspended with running process state, terminating now server=71249cba-b214-41d1-8ca1-04b1ede94c8a``

**Comment by matthewpi** [comment]
Closing due to it being linked to the same problem causing https://github.com/pterodactyl/panel/issues/3644

**Comment by danny6167** [comment]
For reference, I assume you mean #3639
