### ISSUE TITLE
Notification mails not sending

### ISSUE THREAD

**Issue by DarkObscurity** [pterodactyl/panel#3645]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When creating a new account, or when a user tries to reset a password or when I add a user to a server, no mails are send, instead a failed job is being logged in the database with the following error:

https://hastebin.ellermann.tech/bolomoreki.typescript

When using the test mail function in the panel, a test mail is successfully send, so the mail settings work.

### Expected Behavior

When creating an account or resetting a password or adding a user to a server, an email should be send to the specific user.

### Steps to Reproduce

N.A. (Since I didn't change anything, the only thing that changed was that I upgraded the panel to the latest version a few days ago using the self upgrade feature)

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

```bash
http://bin.ptdl.co/ccd7j
```

**Comment by parkervcp** [comment]
Please be sure to start the `pteroq` and if it is running restart it.

**Comment by DarkObscurity** [comment]
> Please be sure to start the `pteroq` and if it is running restart it.

I already tried that multiple times, I also tried rerunning the updater and setting the permissions again according to the documentation, but nothing works.

**Comment by danny6167** [comment]
you're missing one of the php modules, xml I think. if you installed it,  make sure you don't have multiple versions of php installed. for further support use discord.

**Comment by DarkObscurity** [comment]
> you're missing one of the php modules, xml I think. if you installed it, make sure you don't have multiple versions of php installed. for further support use discord.

Thank you! That was indeed the issue! Without noticing I had apparently somewhere along the line updated a part of PHP.
