### ISSUE TITLE
Replace Daemon Version with Wings Version

### ISSUE THREAD

**Issue by JimDude7404** [pterodactyl/panel#3646]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The Daemon version is quite confusing so make it less confusing by instead of it stating Deamon Version make it say Wings Version as Daemin is no longer used. Thanks!

### Describe the solution you'd like.

just change the name to Wings Version on the nodes page

**Comment by DaneEveritt** [comment]
Wings is a daemon.
