### ISSUE TITLE
Version Changer

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3648]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

One click server version changer (like minecraft). You can use your own jars, or just download it from a website. It support .zip (like forge) files, or use eggs as versions.
Like https://www.mc-market.org/resources/18489/

### Describe the solution you'd like.

Reprogram this software

**Comment by FoksVHox** [comment]
Already implemented

**Comment by ItzKazuki** [comment]
why not just buy the addon? simple right?

**Comment by Jelcoo** [comment]
He made 4 of these issues where he requested an addon inside Pterodactyl, just buy them from mc-market or pterodactylmarket.
