### ISSUE TITLE
Adding multiple ports during automatic server creation

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3649]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Description:
Automatic allocation creation when servers will be created.

Settings:
- Next available allocation
- Plus x allocation (For example: MTA: + 123 - Browser port)
- Minus x allocation

Like: https://www.mc-market.org/resources/13963/

### Describe the solution you'd like.

Reprogram this software

**Comment by trenutoo** [comment]
Duplicate of #1653 / #1204
