### ISSUE TITLE
Feature Request: User's associated subuser #209

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#365]
Figure I would update this since I applied this change myself. The formatting of the user itself on the Users > View page is missing some table fields for the subuser.

Because of this, "Subuser" shows in the "Nodes" column and the actual node gets moved to the right. Figured it was worth mentioning for aesthetics before the next full release.

**Comment by DaneEveritt** [comment]
#209

**Comment by DaneEveritt** [comment]
Looks fine on my end.

![](https://s3.kelp.in/ExeDa.png)
