### ISSUE TITLE
Schedule Doesn't work when the Server is in Offline State

### ISSUE THREAD

**Issue by Suryansh5545** [pterodactyl/panel#3651]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

The Schedule Works When the Server is in Running State. But When it is in a Offline State . The Power action Schedule doesn't work. I tried this on other panels and nodes too. The Schedule doesn't work when the Server is in Offline State. The Game is Holdfast . But the same thing is happening with all the other Servers

Also the Node2 Error is due to me trying to see if it is a node problem and removing the vm that is running it to make a new node. I have also tried restarting the machine and restarting the pteroq.service

I also tried the "Run Now Button" it changes its last ran date and for some sec it goes into processing and then again to active but the server doesn't start at all. Same with all the other Schedule When the Server is offline.(From Server i Mean the Game Server not the Node.)

### Expected Behavior

The Power Action Schedule Should have worked and started the offline Server.

### Steps to Reproduce

1. Install any Game Server.
2. Create a Schedule to Start it at specific time.
3. The Server Won't Start at Specific time then.

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

```bash
https://ptero.co/udefuhuzoj
https://bin.ptdl.co/7xouj/
```

**Comment by trenutoo** [comment]
I can't reproduce this unless you enable the "Only when server is online" option, which I assume you have enabled.

![image](https://user-images.githubusercontent.com/10975908/134796538-389eb275-de30-4cef-b258-b363c7f467cb.png)

**Comment by Suryansh5545** [comment]
i am so sorry i missed this thing
