### ISSUE TITLE
Container Uptime

### ISSUE THREAD

**Issue by Jelcoo** [pterodactyl/panel#3653]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I'd like to see an uptime timer of a container. This timer would be reset when you shutdown/restart the server.

### Describe the solution you'd like.

I think the best place for this would be inside the ServerDetailsBlock.

**Comment by anondev-sudo** [comment]
Good idea
