### ISSUE TITLE
Servers not autorestarting after crash

### ISSUE THREAD

**Issue by e-zhuravlev** [pterodactyl/panel#3655]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Server crashes, and does not get restarted by ptero, failing instead with Aborting automatic restart, crash detection is disabled for this instance, regardless of timeout or detect_clean_exit_as_crash values

Error
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Aborting automatic restart, crash detection is disabled for this instance.

### Expected Behavior

Auto start server

### Steps to Reproduce

Server crash or _restart type console

### Panel Version

1.6.2

### Wings Version

1.5.1

**Comment by trenutoo** [comment]
Timeout nor detect_clean_exit_as_crash are not there to enable or disable the crash detection. It's `system.crash_detection.enabled` aka `enabled:true`. Your wings are not on 1.5.1 if you don't have a global variable for it. If you still believe to be on 1.5.1, please post the Wings diagnostics as the issue template requests.

**Comment by e-zhuravlev** [comment]
redeploy the config for the node 
fixed this problem!

**Comment by trenutoo** [comment]
Happy to hear that
