### ISSUE TITLE
Ability to add Allocations to a specific server

### ISSUE THREAD

**Issue by JeremiahC27** [pterodactyl/panel#3657]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

So currently with the api it seems that you can change the allocation limit and change the primary allocation but you cant add allocations. 

### Describe the solution you'd like.

being able to add Allocations to servers based off of the ID of the allocation and UUID of the server

**Comment by trenutoo** [comment]
This is already possible as seen [here](https://github.com/pterodactyl/panel/blob/develop/app/Http/Requests/Api/Application/Servers/UpdateServerBuildConfigurationRequest.php#L40). It accepts `add_allocations`.

PATCH /api/application/servers/{server}/build

```
--data-raw '{
  "allocation": 13,
  "memory": 0,
  "swap": 0,
  "disk": 0,
  "io": 500,
  "cpu": 0,
  "threads": null,
  "feature_limits": {
    "databases": 5,
    "allocations": 5,
    "backups": 5
  },
  "add_allocations": ["33", "34"]
}'

**Comment by JeremiahC27** [comment]
Thanks, I did not notice that
