### ISSUE TITLE
If a server has been opened, can we keep it "active" until the user selects another server?

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#366]
This isn't really an issue but more of a functionality request.

Let's say I'm a user and I log into my panel. I'm really excited about my new server so I click "My Servers" to go find it. I select my server and am brought to the console. Yay! Then I realize I want to change my password, so I click "My Account". The entire section in the sidebar for "Server Management" then vanishes. I'm not saying this is really a bad thing - technically you're working on your account now and not the server, however, it would make things a lot easier and more intuitive for the user if the server they selected remains in an "active" state. That is, it doesn't close out the left pane for that particular server. If they selected another server from their "My Servers Server List", then this one would become active until they select another server. I've been clicking around so much lately and, for example, if I'm working on Startup Parameters and then go to change account settings, I have to click on "My Servers" to find the server I was working on again, find and select that server, click on Configuration, then click on Startup Configuration. Would be a lot more convenient to skip all that - kind of like it "caches" the server in the sidebar or something.

Not sure if it's even possible to keep the server open in the sidebar in an "active" state, but it certainly would be helpful. One thing I haven't thought of would be how to "close out" of the server if they no longer want to see that on the sidebar. Maybe some sort of option on the "Server Management" header that allows you to close out of Server Management completely?

**Comment by DaneEveritt** [comment]
Would require some re-engineering, and isn't really something I am wanting to do with the current theme and setup.
