### ISSUE TITLE
JSON Config Variables convert string to int if only numbers provided

### ISSUE THREAD

**Issue by thakyZ** [pterodactyl/panel#3662]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

So currently if I create an egg with a JSON config and set the config variable to be `required|string|max:20` and provide it only numbers it will write it as:
```json
{
  "var": 12345
}
```
and not
```json
{
   "var": "12345"
}
```
As it should.
There is a number validation, so this becomes very redundant.

### Expected Behavior

Writes a string with quotes even if only numbers are supplied.

### Steps to Reproduce

Create DIscord.js egg
Change the config box to have
```json
{
    "config.json": {
        "parser": "json",
        "find": {
            "var": "{{server.build.env.VAR}}"
        }
    }
}
```
Add a variable and point it to `VAR` and keep the validation properties default.
Create a server and make a file named `config.json`
Edit the server startup properties and make the `var` value `12345`
Then start the server and check the config.

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

```bash
https://ptero.co/nuxigegezi
No Panel errors from the provided command.
```

**Comment by trenutoo** [comment]
You can currently add double quotes yourself

`"var": "\"{{server.build.env.VAR}}\""`

**Comment by matthewpi** [comment]
As Software-Noob has stated, you will need to add the quotes yourself if you are using a variable and the value is an integer that needs to be a string.  This is because some configs need the variables to be integers but JSON requires that the variable string be quoted for obvious reasons.  While in a perfect world this would just work properly, manually adding the quotes is the simplest way to achieve this.

**Comment by thakyZ** [comment]
Escaping the Quotes just puts quotes and escaped quotes in the config.
Example:
```json
{
    "config.json": {
        "parser": "json",
        "find": {
            "guildId": "\"{{server.build.env.GUILD_ID}}\""
        }
    }
}
```
and
```json
{
    "guildId": "\"486289309310386196\""
}
```
