### ISSUE TITLE
Node not working SSL ERROR

### ISSUE THREAD

**Issue by tomlahaye** [pterodactyl/panel#3663]
### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.

### Current Behavior

My node is not working, my browser console gives me this:
`GET https://pterodactyl.tomlahaye.fr:8080/api/system net::ERR_SSL_PROTOCOL_ERROR`
But my certificate is valid, the config.yml file is normally well configured : https://ptero.co/raw/yojisizecu

### Expected Behavior

I wish I could run my node.

### Steps to Reproduce

I’m currently looking for help, I don’t have a solution yet.

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

```bash
Wings : https://ptero.co/uloyonejef
Panel : https://bin.ptdl.co/j7azr/
```

**Comment by parkervcp** [comment]
@tomlahaye First things first. You need to regenerate that token.

When loading that page I get `Error code: SSL_ERROR_RX_RECORD_TOO_LONG`
I have only seen that when a redirect tries to go to a port that is not allowed in a router.

If looks like you are trying to proxy wings through nginx.

**Comment by tomlahaye** [comment]
> @tomlahaye First things first. You need to regenerate that token.
Normally the token to was regenerated: https://ptero.co/raw/pipegiqeti

> If looks like you are trying to proxy wings through nginx.
I use CloudlFlare to generate my certificate and use apache for my web server, so I don’t understand why it would use nginx.

**Comment by trenutoo** [comment]
8080 is a HTTP port on Cloudflare. Use a HTTPS port such as 8443. This is also explained in the Wings additional documentation.

This is not a software bug. Use the Discord server for configuration issues, where our support bot would've replied to this right away.

**Comment by tomlahaye** [comment]
> 8080 is a HTTP port on Cloudflare. Use a HTTPS port such as 8443. This is also explained in the Wings additional documentation.

It works, thank you, I had not at all thought about the HTTP port listed in the config.yml

> This is not a software bug. Use the Discord server for configuration issues, where our support bot would've replied to this right away.

Sorry, I note for my next requests.
