### ISSUE TITLE
Red banner with an error is throwing 500 Server Error instead

### ISSUE THREAD

**Issue by kubo6472** [pterodactyl/panel#3665]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

It results in 500 │ Server Error

### Expected Behavior

It should display a small banner at the top saying: There was an error contacting daemon etc. instead.

### Steps to Reproduce

1. Shut off wings
2. Open a server on hosted there
3. Try to safely delete it

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs
https://bin.ptdl.co/sk3he/

**Comment by trenutoo** [comment]
You need to provide logs if you want us to understand your issue.

**Comment by kubo6472** [comment]
Added

**Comment by trenutoo** [comment]
You should open the issue when you have details to share, which are requested when opening one. Bug report without any information is of no use. Take your time to gather the details, explain your problem, and fill the requested forms.

**Comment by kubo6472** [comment]
Hey, so my thinking process was, that I will submit the issue with all the required fields asap I have a documentable problem. Then I will wait for anyone, that might have experienced something similar and possibly knows the solution. I had some issues contacting someone, who can actually send me the logs for the affected panel, since I lack direct access to it. Will let you know when I got the logs. ✌️

**Comment by DaneEveritt** [comment]
This issue makes no sense. Feel free to provide actual reproduction steps and it can be re-opened.

**Comment by kubo6472** [comment]
Added

**Comment by trenutoo** [comment]
Your logs indicates that you are missing the required dependencies, which are listed and installed in the documentation.

**Comment by kubo6472** [comment]
> Your logs indicates that you are missing the required dependencies, which are listed and installed in the documentation.

Please, can you point me to some? Bcs as I mentioned, I was just documenting an issue I am experiencing with a panel I am not hosting myself, but have a reach to the actual admin.

**Comment by DaneEveritt** [comment]
If you do not run the panel, please do not open issues since you cannot provide the information we require.

**Comment by kubo6472** [comment]
Then please ask what else do you now require. And I will get it back to you asap. I know it is ineffective, but the best I could do. Here I have recorded my screen of what is happening: https://wamis.ml/3uQrmwK

**Comment by kubo6472** [comment]
> If you do not run the panel, please do not open issues since you cannot provide the information we require.

And I do run one panel, but somewhere else and I am not getting any issues there.

**Comment by kubo6472** [comment]
New logs, installed GMP: https://bin.ptdl.co/wzum6/

**Comment by kubo6472** [comment]
Resolved, it was GMP, thanks & sorry.
https://github.com/pterodactyl/panel/issues/3666#issuecomment-939270028
