### ISSUE TITLE
Force deleting servers results in error

### ISSUE THREAD

**Issue by kubo6472** [pterodactyl/panel#3666]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When forcibly deleting a server from panel on dead wings, it throws 500 │ Server error

### Expected Behavior

Forcibly deleting a server should always work.

### Steps to Reproduce

Forcibly delete a server where wings are not running

### Panel Version

1.6.2

### Wings Version

1.5.1 - not applicable

### Error Logs
https://bin.ptdl.co/sk3he/

**Comment by Jelcoo** [comment]
Can you send the error logs?
```shell
tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99
```

**Comment by kubo6472** [comment]
Added

**Comment by DaneEveritt** [comment]
This is not a bug, your system is configured incorrectly.

```
RuntimeException: Missing BC Math or GMP extension
```

**Comment by kubo6472** [comment]
GMP is not listed here: https://pterodactyl.io/panel/1.0/getting_started.html#example-dependency-installation but I will get it installed and will let you know if it fixes something :)

**Comment by kubo6472** [comment]
New logs, installed GMP: https://bin.ptdl.co/wzum6/

**Comment by kubo6472** [comment]
Resolved, it was GMP. No idea why it was not installed, thank you & sorry. @DaneEveritt @Jelcoo
