### ISSUE TITLE
Server is showing as he is restoring from backup

### ISSUE THREAD

**Issue by Firestone82** [pterodactyl/panel#3670]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Server is showing as he is restoring from beckup even when hes not.

I found that, in database, when server has status empty.. Its showing that status.
But when I change it to NULL, server is showing as normal. NULL and "" should be same. Shouldnt it?

Even when there is empty status, server work as normall, console is doing commands, restarts start are possible.
Just to access any settings, thats unpossible.

![image](https://user-images.githubusercontent.com/57676764/136338280-050ece20-2b06-4fc6-a9d4-dcae8178507f.png)

### Expected Behavior

Server should be showing as normal. Its working, but I cant configurate it.

### Steps to Reproduce

Currently no idea how it happened. 
We were just trying out backups and this randomly happened.

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

```bash
https://ptero.co/geditopoze

http://bin.ptdl.co/1uuu0
```

**Comment by notAreYouScared** [comment]
I noticed this last night. didn't feel I should've reported it.

**Comment by DaneEveritt** [comment]
`""` and `null` are completely different values, so that is probably a bug. An empty string shouldn't be possible in that field.

**Comment by trenutoo** [comment]
Do you have any reproducible steps to narrow down what inserted empty string instead of NULL?

We could add a constraint check to prevent this, but it doesn't solve the issue of what inserted something else into the field.
