### ISSUE TITLE
Reinstallation success message not cleared when opening rename file modal

### ISSUE THREAD

**Issue by ok236449** [pterodactyl/panel#3673]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

If you reinstall a server and then go to file manager, click create new directory, there will be a green bar that the server has begun reinstalation. It is just a little visual bug, nothing serious. After refreshing the page, it goes away.
![Screenshot (697)](https://user-images.githubusercontent.com/89067167/136668237-73c5eb55-cc7b-4567-ab05-f824b73aa193.png)

### Expected Behavior

It shouldn´t be there

### Steps to Reproduce

1. reinstall server
2. DON´T REFRESH THE PAGE, go to file manager
3. try to create a dir
4. see the text

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

```bash
aren´t needed
```

**Comment by mrxbox98** [comment]
Whenever I try to reinstall I get this message on all pages. This might be my theme but it seems vanilla.

![](https://i.mrxbox98.me/2022/01/chrome_4xLzISe0EZ.png)

**Comment by trenutoo** [comment]
> Whenever I try to reinstall I get this message on all pages. This might be my theme but it seems vanilla.


The reported UX issue happens when you reinstall the server and without refreshing the page, visit the file manager once the installation has been completed

**Comment by mrxbox98** [comment]
> > Whenever I try to reinstall I get this message on all pages. This might be my theme but it seems vanilla.
> 
> The reported UX issue happens when you reinstall the server and without refreshing the page, visit the file manager once the installation has been completed

When I click reinstall and wait for the reinstall to complete I get no notification at the top.

Demo: https://i.mrxbox98.me/2022/01/chrome_HGuKenNRwe.mp4

**Comment by trenutoo** [comment]
I was able to reproduce it in 1.6.6, so whatever was touched in 1.7.0 appears to have fixed it.

 @ok236449 Can you still reproduce this issue?

**Comment by ok236449** [comment]
> I was able to reproduce it in 1.6.6, so whatever was touched in 1.7.0 appears to have fixed it.
> 
> @ok236449 Can you still reproduce this issue?

I also wasn´t able to reproduce on v1.7.0 anymore, so you can probably close this issue.
