### ISSUE TITLE
SSl certificates died

### ISSUE THREAD

**Issue by e-zhuravlev** [pterodactyl/panel#3681]
### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.

### Current Behavior

SSl certificates died on September 30th, you can remove them from the Docker image so that steamworks queries work
comment please SSL and rebuild docker image
https requests not work

![unknown](https://user-images.githubusercontent.com/35569496/136844754-917d5baa-6c6f-45a2-8b5c-c6aedb253287.png)
![unknown](https://user-images.githubusercontent.com/35569496/136844826-688a2fa2-12b1-4508-90ea-66d4bcda5a4b.png)

### Expected Behavior

ssl work or ssl off

### Steps to Reproduce

run server with def. image .../core

### Panel Version

1.6.2

### Wings Version

1.5.1

**Comment by parkervcp** [comment]
Can you specify what image you are talking about specifically. All our yolks rebuild weekly now.

**Comment by e-zhuravlev** [comment]
Good. Can you send a link where I can watch and download suitable images?
Your github branch is empty
