### ISSUE TITLE
Transfer backups with server

### ISSUE THREAD

**Issue by OpenSource03** [pterodactyl/panel#3682]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Please make sure backups are transferred as well on server transfer or link backups to the node the server was initially on.

### Describe the solution you'd like.

I don't really see much point in this field 😋

**Comment by Jelcoo** [comment]
Also add the databases to this

**Comment by matthewpi** [comment]
> Also add the databases to this

Databases are a completely separate thing to transfer.  https://github.com/pterodactyl/panel/issues/2786

---

Duplicate of https://github.com/pterodactyl/panel/issues/2623
