### ISSUE TITLE
Spigot installation script only running with Java 8

### ISSUE THREAD

**Issue by JacobHowell** [pterodactyl/panel#3683]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

The Spigot installation script has an if/else, which goes something like this:
IF Minecraft version >= 1.17, use Java 16. 
ELSE use Java 8. 

The problem is, when I use Minecraft Version 1.17 or 1.17.1, it still uses Java 8. 

My confirmation and workaround was to change the Java version it uses in the else to also be Java 16, so after applying my workaround it operates like so:
IF Minecraft version >= 1.17, use Java 16. 
ELSE use Java 16. 
Which of course isn't ideal if I want to use a different Minecraft version, but it will work for now. 

### Expected Behavior

Install script finds Minecraft version then chooses Java 16 for Minecraft 1.17 or greater or chooses Java 8 for anything else. 

### Steps to Reproduce

Update the Spigot egg. 
Attempt to reinstall/update a server to Java 16 and Minecraft 1.17.1. 

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

```bash
I didn't collect logs, but the evidence is the build of a 1.17 server failing and saying it requires Java 16/17 and that you're using Java 8.
```

**Comment by trenutoo** [comment]
Spigot egg is not shipped or part of the core panel eggs. You are looking for the parkers egg repository, where I have a fix for this in the PRs.

**Comment by JacobHowell** [comment]
> Spigot egg is not shipped or part of the core panel eggs. You are looking for the parkers egg repository, where I have a fix for this in the PRs.

[https://github.com/parkervcp/eggs/blob/master/game_eggs/minecraft/java/spigot/egg-spigot.json](https://github.com/parkervcp/eggs/blob/master/game_eggs/minecraft/java/spigot/egg-spigot.json)
^ So is this updated or is it somewhere else?

**Comment by trenutoo** [comment]
> > Spigot egg is not shipped or part of the core panel eggs. You are looking for the parkers egg repository, where I have a fix for this in the PRs.
> 
> https://github.com/parkervcp/eggs/blob/master/game_eggs/minecraft/java/spigot/egg-spigot.json ^ So is this updated or is it somewhere else?

In the pull requests https://github.com/parkervcp/eggs/pull/1356
