### ISSUE TITLE
Crashar ao compactar vários arquivos no painel

### ISSUE THREAD

**Issue by gustavooh11** [pterodactyl/panel#3685]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

There is a bug in pterodactyl that basically works like this, you compress several files, and there will come a time when the panel crashes, in my point of view there could be a solution basically like this: The pterodactyl adds an option when creating the server, to limit the amount of items that can be packed by the user.

### Expected Behavior

The pterodactyl adds an option when creating the server, to limit the amount of items that can be packed by the user.

### Steps to Reproduce

I had a client who was using this problem. Basically, it takes a folder that can be the "plugins" or "world" folder and makes several compressions with this file, and it is repeated like this, weighing the panel a lot and crashing it.

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

```bash
I can't logs, because I managed to suspend the service, but with a very slow panel to the point of crashing.
```

**Comment by Ferks-FK** [comment]
Did you check that this is not a lack of space for the crashed server?
Since when a compression is being done, the server can double in size depending on what is being compressed.
This results in a crash of some sort.

**Comment by DaneEveritt** [comment]
Can't reproduce, and there are no logs so not leaving this open.
