### ISSUE TITLE
SFTP file upload permissions

### ISSUE THREAD

**Issue by dennisrijsdijk** [pterodactyl/panel#3689]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When uploading a file, or a folder/directory containing files via SFTP, file permissions remain at root:root, which means applications running within the container only get read access to the files.

### Expected Behavior

When uploading a file, or a folder/directory containing files via SFTP, permissions should be set immediately, rather than next server startup to prevent write access issues.

### Steps to Reproduce

1. Connect to SFTP of a server
2. Upload  a file via SFTP
3. Use SSH to connect to the machine
4. Navigate to /var/lib/pterodactyl/volumes/[SERVER_UUID]
5. Run `ls -alh`
6. Look for the file you uploaded, and verify the user and group are both set to root

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

```bash
N/A
```

**Comment by playaz44** [comment]
I can confirm.

**Comment by nackerr** [comment]
Confirmed.
