### ISSUE TITLE
Auth0 for authentication

### ISSUE THREAD

**Issue by mrxbox98** [pterodactyl/panel#3690]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Auth0 is a free authentication service that includes email, SMS, and fingerprint authentication. It also allows users to sign in with third-party accounts like Google or Microsoft. It also has 2FA.

### Describe the solution you'd like.

I would like to see this as another option for authentication. The current auth method should still be an option since auth0 has a 7000 account maximum before you have to pay.

**Comment by matthewpi** [comment]
External auth providers like Auth0 won't be implemented.  I do plan on adding the ability to login via OAuth2/OIDC but there will not be specific integrations outside of that.
