### ISSUE TITLE
Unable to use dollar signs in registry username

### ISSUE THREAD

**Issue by clrxbl** [pterodactyl/panel#3692]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

I have a custom Docker registry that I want to set up in my Wings config. The username for this contains a dollar & plus sign.
A Wings restart will remove the dollar sign and the characters between the dollar sign and plus sign from the username. Enclosing the username in double quotes also doesn't work as Wings will simply remove those double quotes on restart.

Example:
```
username: "robot$bots+box12"
```

Turns into

```
username: "robot+box12
```

### Expected Behavior

I should be able to use whatever characters Docker supports.

### Steps to Reproduce

In your Wings config, add a Docker registry with a username containing a dollar sign.

### Panel Version

1.6.2

### Wings Version

1.5.1

**Comment by parkervcp** [comment]
A `$` is generally considered a variable in the cli world. I wouldn't see any console liking that at all.

**Comment by clrxbl** [comment]
> A `$` is generally considered a variable in the cli world. I wouldn't see any console liking that at all.

Yes but enclosing it in double quotes to use in a YAML config option should in theory prevent this from being an issue.
Escaping it with back/forwardslashes or double dollar signs $$ doesn't seem to work either.

Wings seems to be removing double quotes from the registry username aswell which is another weird thing it probably shouldn't be doing?

**Comment by matthewpi** [comment]
> > A `$` is generally considered a variable in the cli world. I wouldn't see any console liking that at all.
> 
> Yes but enclosing it in double quotes to use in a YAML config option should in theory prevent this from being an issue. Escaping it with back/forwardslashes or double dollar signs $$ doesn't seem to work either.
> 
> Wings seems to be removing double quotes from the registry username aswell which is another weird thing it probably shouldn't be doing?

This has nothing to do with the value being a registry username, the YAML file is reformatted on boot, making this either a feature or a bug with the YAML parser library we use.

**Comment by parkervcp** [comment]
can you try making it a single quote instead?

**Comment by clrxbl** [comment]
> can you try making it a single quote instead?

This has the same effect. It strips away the characters between the $ and +

**Comment by clrxbl** [comment]
So while the issue is sort of fixed, it breaks if you restart Wings twice.
The config goes from $$ to $ when you restart it, but if you restart it again it'll get rid of the $

**Comment by matthewpi** [comment]
The problem with this entire logic is that the YAML file is written to disk after replacing variables which allows us to populate missing keys and format the config file, but on the other hand will replace environment variables (or in your case escaped environment variables) with their actual values, which essentially defeats the entire purpose of using environment variables.
