### ISSUE TITLE
Unable to use a GitHub repository as a Docker image

### ISSUE THREAD

**Issue by oddmario** [pterodactyl/panel#3694]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Using a GitHub repository as a docker image fails during a server installation, it throws either "invalid reference format" or "404 Not Found" for the values I've tried, some of the values I tried are:
`https://github.com/name/yolks-java11.git`

`github.com/name/yolks-java11.git`

`https://github.com/name/yolks-java11.git#master`

### Expected Behavior

wings should pull the Dockerfile from the GitHub repository and proceed with the image installation like what the `docker build` command does

### Steps to Reproduce

1. Create a server and specify a GitHub repository as the docker image (as explained @ https://stackoverflow.com/a/39194765/8524395)

2. Let the server install, it should fail as stated before in this issue.

### Panel Version

1.6.2

### Wings Version

1.5.1

**Comment by notAreYouScared** [comment]
Wings isn't made to build docker images. You need to input a built docker image for it to use.
