### ISSUE TITLE
Automatic Server Deployment fails when using the api

### ISSUE THREAD

**Issue by Hadimhz** [pterodactyl/panel#3695]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

While trying to create a server using the API the panel returns 
```
{
  errors: [
    {
      code: 'NoViableNodeException',
      status: '400',
      detail: 'No nodes satisfying the requirements specified for automatic deployment could be found.'
    }
  ]
}
```

request body: 
```
{
  name: 'test',
  user: 1,
  egg: egg.id,
  // node: 1,

  limits: {
    memory: 0,
    swap: -1,
    disk: 0,
    io: 500,
    cpu: 0,
  },

  environment: { STARTUP_CMD: 'bash' },
  feature_limits: { databases: 0, backups: 0 },


  deploy: {
    locations: [1],
    dedicated_ip: false,
    port_range: []
  },
  
  startup: egg.startup,
  docker_image: egg.image,
  oom_disabled: true,
  start_on_completion: false,
}
```

Note: Creating a server using the panel works fine.

### Expected Behavior

Server to be created and for the server object to be returned.

### Steps to Reproduce

send a request to create a server using the API (/api/application/servers) while trying to use automatic server deployment 
```
deploy: {
    locations: [1],
    dedicated_ip: false,
    port_range: []
  },```


### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

_No response_

**Comment by PrivateGER** [comment]
Needs more info. What are your nodes? Do they have enough space/CPU/RAM? Are automatic allocations set up?

**Comment by trenutoo** [comment]
This can be caused from any of the following:

- Wrong location
- Not enough Disk Space/RAM on your Node allocation limits
- No available Node allocations matching the provided criteria  (automatic allocation creation is off)

**Comment by Hadimhz** [comment]
> * Not enough Disk Space/RAM on your Node allocation limits

Wait, so if I'm over allocating, but servers are offline it wouldn't work?

Yep, that was the problem. Is there a way to bypass that?
since if I'm using the panel I can bypass so can I do that using API.

**Comment by trenutoo** [comment]
@Hadimhz servers being offline or not does not matter. They still count towards the allocated resources. You can not exceed it, but there's over allocation % setting for the Node limits if you wish to over-allocate. 


This is not your issue if you are specifying 0 for the limits as it would count as 0, and instead your issue is instead with the location or allocations (available ip:port) .

**Comment by Hadimhz** [comment]
@Software-Noob if was breaking cause I had other servers on the node and it was 19GB/ 10GB, once I've changed the other servers to 0 it worked fine.

**Comment by trenutoo** [comment]
Glad to hear that.
