### ISSUE TITLE
Server Search Bar

### ISSUE THREAD

**Issue by Pankraz01** [pterodactyl/panel#3696]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to see a Search Bar to Search Servers existing on my Panel

### Describe the solution you'd like.

Search Bar for:
- Admin Panel Server List
- User Panel Server List (Own Servers & Other Peoples Servers)

### Additional context to this request.

If its Possible an advanced search for Name, Owner, Node, Gamemode. Something like filters

**Comment by yesBad** [comment]
Already exsists?
![Screenshot_20211021-214701_Chrome.jpg](https://user-images.githubusercontent.com/87938689/138338389-ecdd55c7-b28e-4135-8677-85f85fe276b9.jpg)

**Comment by yesBad** [comment]
From Admin Panel.
 ![Screenshot_20211021-214902_Chrome Dev.jpg](https://user-images.githubusercontent.com/87938689/138338670-ba166f67-48fd-417b-96f4-1ee867735b0a.jpg)

**Comment by yesBad** [comment]
People these days lmao.

**Comment by Pankraz01** [comment]
This only exists for admins, not for normal users…

**Comment by yesBad** [comment]
> This only exists for admins, not for normal users…

No it excists for both. I literally showed both of them
