### ISSUE TITLE
SSL Certificate Cached

### ISSUE THREAD

**Issue by IvMisticos** [pterodactyl/panel#3701]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Certificate seems to be cached and never updated in wings. Let's say certificate auto renewed, old one expired. Wings would still be using old one even though the file was updated. So the certificate is renewed, but requests are returning an expired certificate.

### Expected Behavior

Certificate in wings should be automatically updated with some FS watcher as a suggestion.

### Steps to Reproduce

1. Issue a certificate
2. Have wings use this certificate
3. Renew the certificate
4. Wait until previous certificate expires

### Panel Version

1.6.2

### Wings Version

1.5.1

**Comment by IvMisticos** [comment]
guess it's not specifically wings caching it but whichever webserver handler wings is using

**Comment by trenutoo** [comment]
You have to reload the service to apply the new certificate, similar to any other service, including any different web server, such as Nginx. This is not unique to Wings.

This is more of a feature suggestion for Wings to detect when the certificate is modified than a bug report.

**Comment by DaneEveritt** [comment]
Won't change, this is how everything works.
