### ISSUE TITLE
Live resource usage for nodes

### ISSUE THREAD

**Issue by Jelcoo** [pterodactyl/panel#3708]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I'd like to see a live resource usage for nodes just like with servers. This could be implemented on the node view page.

### Describe the solution you'd like.

This would not be allocated resources, but how much is used now. This would include cpu and ram, possibly disk.

**Comment by matthewpi** [comment]
This is out of scope of what this software should provide, if you would like to see node statistics you are much better off using a monitoring system.
