### ISSUE TITLE
Two Factor box overlapping

### ISSUE THREAD

**Issue by Jelcoo** [pterodactyl/panel#3711]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

<img src="https://cdn.jelco.xyz/biVi1/KIKEyIXe43.png/raw">

### Expected Behavior

I expect it to have the same spacing as update password and email

### Steps to Reproduce

Install any v1 version of the panel and go to your profile settings

Tested on a 14" laptop screen

### Panel Version

any v1 version

### Wings Version

-

**Comment by hwalker928** [comment]
I cannot replicate this.

**Comment by RealTriassic** [comment]
Are you sure you haven't modified the default Pterodactyl theme?

**Comment by QuintenQVD0** [comment]
I have panel version 1.6.3 and i have no theme and I also don't have that issue.

![pt](https://user-images.githubusercontent.com/67589015/138915011-d0f23bf7-33b5-417f-8ef4-7fa895037930.JPG)

**Comment by matthewpi** [comment]
If you resize the page it does overlap.

**Comment by hwalker928** [comment]
Oh yep.
![image](https://user-images.githubusercontent.com/63236817/138917960-32351136-5270-4476-a831-cd5b05b1f4aa.png)
