### ISSUE TITLE
Add support for interactive programs to server console

### ISSUE THREAD

**Issue by anondev-sudo** [pterodactyl/panel#3712]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add way to run command in console when another command is running and allow to use keyboard keys when you click on the console.

### Describe the solution you'd like.

When you run some command in console, you can't stop it, as you can't use CTRL + C in the console.

Allow us to do so, and to run any command while another command is running.
Also you can't use F keys on keyboard in pterodactyl console.

**Comment by notAreYouScared** [comment]
Why would you need to stop a command? The console is basically forwarding the commands to whatever program is running in the startup.

**Comment by Jelcoo** [comment]
There is litterly a `stop` button next to the console

**Comment by anondev-sudo** [comment]
Ik, but you can't use keyboard keys in console. Like normally when you write for example `node index.js` to console and then you want to stop the process, you can press CTRL + C keys on the keyboard. But inside pterodactyl console you can't do this.

Also you can't use arrow keys in pterodactyl console, so you can't make choice prompts using Inquirer.js

**Comment by Jelcoo** [comment]
You can use arrow key up and down to cycle through commands you used before
<img src="https://cdn.jelco.xyz/biVi1/NenoqeXO63.gif/raw">

**Comment by anondev-sudo** [comment]
Ok, but you can't use keyboard keys like F keys in console. And you can't use CTRL + letter in console too

**Comment by Jelcoo** [comment]
Pterodactyl Software is not designed to be interactive, it is designed to be easy to use. If you want to use keybinds, I recommend using a local terminal.

**Comment by DaneEveritt** [comment]
Correct, but @anondev-sudo is making a completely valid point that you cannot run interactive programs using the console right now, and there are a lot of programs you can run in Pterodactyl that would benefit from that.

**Comment by anondev-sudo** [comment]
You can't connect to pterodactyl container using ssh, so users can't do that. If it will be possible then it will solve the issue or make the console more interactive

**Comment by Marfjeh** [comment]
Maybe an idea to use xterm.js as a console?

**Comment by schrej** [comment]
@Marfjeh It's already using xterm.js: https://github.com/pterodactyl/panel/blob/develop/resources/scripts/components/server/Console.tsx

**Comment by Marfjeh** [comment]
> @Marfjeh It's already using xterm.js: https://github.com/pterodactyl/panel/blob/develop/resources/scripts/components/server/Console.tsx

Ah, I see, I thought it was using something else. my bad.

**Comment by anondev-sudo** [comment]
Maybe it should use some real typing, so no enter a command field. When you put mouse on console and press keys, it should be forwarded to console.

**Comment by DaneEveritt** [comment]
Due to the overarching complexity of this request and the extremely limited resources we can provide this project right now, I am closing this request.

There is just no way it ever happens in any reasonable amount of time.

**Comment by anondev-sudo** [comment]
This is sad, isn't it possible to forward F keys, CTRL + key and others to the console when you have cursor in the type a command field?

**Comment by anondev-sudo** [comment]
Isn't it possible to add just when you press CTRL + C, it will be forwarded to console for now?
