### ISSUE TITLE
Logout button in admin area no longer functions.

### ISSUE THREAD

**Issue by Mubeen142** [pterodactyl/panel#3717]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Due to the new logout button logic in panel area with the onClick method, the logout button in the admin area no longer functions.
https://github.com/pterodactyl/panel/blob/4dca4f0aa9ef55cf7046b2ab71c94ab7e7d0d579/resources/scripts/components/NavigationBar.tsx#L51

when trying to logout in admin panel, it redirects user back to homepage still logged in

### Expected Behavior

User is supposed to be logged out and redirected to /auth/login

### Steps to Reproduce

1. Ensure you are using version 1.6.3
2. Head to admin area
3. Top right, click the button to logout

### Panel Version

1.6.3

### Wings Version

1.5

**Comment by trenutoo** [comment]
Fixed by #3710
