### ISSUE TITLE
 An unexpected error was encountered while processing this request, please try again.

### ISSUE THREAD

**Issue by JordanDIG** [pterodactyl/panel#3719]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

After updating my panel from version 1.6.2 to 1.6.3 I get an error when I connect to my panel

### Expected Behavior

Display the list of servers

### Steps to Reproduce

Update your panel under plesk in SSH with the command 

### Panel Version

1.6.3

### Wings Version

1.5.1

### Error Logs

```bash
https://bin.oaka.xyz/wBw7Zj
```

**Comment by DaneEveritt** [comment]
You're not doing something right in the upgrade process, this code works fine and exists but your error seems to indicate that you're not properly running all of the steps.
