### ISSUE TITLE
Exit code: 0

### ISSUE THREAD

**Issue by baqjan** [pterodactyl/panel#3720]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...

### Describe the solution you'd like.

g

### Additional context to this request.

g

**Comment by Software-Noob** [comment]
This is not a feature request and also contains no information whatsoever. The actual reason for a crash would be above all of that.

Use the Discord server for configuration issues.
