### ISSUE TITLE
Auto update startup

### ISSUE THREAD

**Issue by Jelcoo** [pterodactyl/panel#3721]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

If you edit an egg's startup command, all of the servers will be updated with it.

### Describe the solution you'd like.

Maybe a toggle switch if you want to update servers or not

**Comment by matthewpi** [comment]
The only way I see this being implemented is if servers default to having their startup command being `null` and fallback to the egg's startup command.  This way, a server can override the egg's startup command without needing to add a weird "update servers" option when updating an egg that could be implemented 30 different ways each with different pros and cons; not to mention that this would require looping through every server on an egg (which is not indexed from my knowledge) to update the startup command.

**Comment by Jelcoo** [comment]
If that is the best way, so be it

**Comment by DaneEveritt** [comment]
I agree with that @matthewpi — don't set a startup value on the server if it isn't changed.
