### ISSUE TITLE
API doesn't want connect to WHMCS

### ISSUE THREAD

**Issue by FavoShane** [pterodactyl/panel#3724]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Every time I connect to WHMCS, the panel logs' says a error. WHMCS can not make servers on the panel.

### Expected Behavior

I connect the API to WHMCS and I get the error.

### Steps to Reproduce

1. Make an API key on the panel
2. Install the WHMCS addon on WHMCS.
3. Make a server on WHMCS and fill the API key in Password.
4. Click on Test Connection

### Panel Version

1.6.3

### Wings Version

1.5

### Error Logs

```bash
http://bin.ptdl.co/n9oi3
```

**Comment by TrixterTheTux** [comment]
The test connection button works fine, you'd need to provide an actual description of the issue you're having as the panel logs aren't relevant to WHMCS.
