### ISSUE TITLE
Minecraft server can't allocate full {{SERVER_MEMORY}} amount in XMX

### ISSUE THREAD

**Issue by Phoenix616** [pterodactyl/panel#3726]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When a Minecraft server allocates the full memory amount specified in the build configuration which gets included with the `{{SERVER_MEMORY}}` variable in the startup argument then it will crash/freeze before it can ever reach that amount making the settings shipped by default broken.

This was noticed by trying to use Aikar's suggested flags with a Paper server including the `-XX:+AlwaysPreTouch` in the startup argument (which should always be used to improve performance because no time needs to be wasted changing the allocation sizes and also to prevent crashes when the server can't allocate enough memory like it is the case here) then it will not start but be stuck on the java command in the panel console. (And memory usage goes above the displayed limit e.g. `5.87 GB / 5.86 GB`) Removing `-XX:+AlwaysPreTouch` allows it to start but this obviously means that it will then freeze/crash at a random point while online before it can ever reach the specified container memory limit.

My assumption is that this is caused by the JVM overhead not being properly accounted for. The only code regarding this I can find is [this](https://github.com/pterodactyl/wings/blob/3c54c1f840bfd7f12bac3d80a86e1f1dfd14adcd/environment/settings.go#L73-L89) which seems incredibly small seeing as I have 1.5GB JVM overhead on a different 6GB server of mine, from my experience it should at least be 1/4 to 1/3 of the assigned java application memory but how much exactly really depends on what the server application does and what kinds of java arguments are used to prioritise certain stuff. (Also imo. this should be subtracted from the memory assigned to java application instead of arbitrarily added to the container size without any note to the admin of the panel software. I would expect the container to have the max that is set in the admin interface, not randomly go above that (which could lead to the exact same issue that we have with the JVM overhead when using java applications))

If anything this overhead needs to be exposed to the panel admin/user, especially as different applications will handle this differently and assigning arbitrarily more memory than specified in the build configuration is really not ideal. Also possible would be some calculation of the overhead required based on the JVM flags provided but that would require a pretty deep understanding of how the JVM and the used garbage collector works and might be a bit too much when a simple field in the build configuration could offload this to some simple testing by the panel admin.

Also before anyone does this: Blaming this on the used flags itself is not the way to handle this issue as the panel should support any kind of java applications/JVM flags. The JVM can try to use more memory for a multitude of reasons (especially as more modern JVM versions will have differently behaving garbage collectors and use more memory by design in order to improve performance overall. From my personal experience running servers without containers I can say that not restricting the JVM memory size at all offers the best experience but that's obviously not the goal with using panels/containers)

### Expected Behavior

The server to start normally.

### Steps to Reproduce

Simplest way is to try to start a paper server with [Aikar's flags](https://startmc.sh/) or run a setup which increases the JVM usage beyond the hardcoded overhead.

### Panel Version

1.6.3

### Wings Version

1.5.3

### Error Logs

Wings diagnostics: https://gist.github.com/Phoenix616/eb121152134a3411965f054359d7d1f7

**Comment by Phoenix616** [comment]
Old issues that might be able to be solved properly by removing the hard coded overhead (but not all provided much info so I can't say that in detail):

https://github.com/pterodactyl/panel/issues/3581
https://github.com/pterodactyl/panel/issues/3568
https://github.com/pterodactyl/panel/issues/3437
https://github.com/pterodactyl/panel/issues/2127
https://github.com/pterodactyl/panel/issues/1765
https://github.com/pterodactyl/panel/issues/1601
https://github.com/pterodactyl/panel/issues/1472
https://github.com/pterodactyl/panel/issues/1351
https://github.com/pterodactyl/panel/issues/1351

Of course ideally ways to influence the JVM itself to not try to go beyond `{container memory limit} - {application memory}` would be a better solution for some of them but this might not be possible with how the JVM behaves in all cases. ([This docker post](https://www.docker.com/blog/improved-docker-container-integration-with-java-10/) comes to mind but this might be related to some underlying docker/JVM issues so if the detection doesn't work properly this might need to be escalated to them)

**Comment by DaneEveritt** [comment]
If you're going to pre-touch you need to explicitly set a limit that is _below_ the assigned server limit such that you're accounting for the overhead yourself. There is far too much guess work required to allow the software to actually handle this automatically. Giving a server 2GB of additional overhead just for Minecraft is asking for pain in environments where users expect that assigning 6GB means 6GB, not 8GB.

This isn't a bug, its just a limitation of running in strictly resource limited environments like this.

There is also a warning on that page about exactly this.

<img width="335" alt="Screen Shot 2021-11-03 at 09 24 02" src="https://user-images.githubusercontent.com/418376/140101090-c03d58de-8018-4bcd-acfb-56c1140b0c51.png">

**Comment by trenutoo** [comment]
You can manage this yourself by lowering the XmX with `-Xmx$(({{SERVER_MEMORY}}-1024))M` thus leaving something for the container and preventing such freezes.

**Comment by Phoenix616** [comment]
Please actually read everything what I wrote. The underlying issue isn't solved by modifying the flags or the memory amount.
