### ISSUE TITLE
Docker container memory limit is more than specified in the build configuration

### ISSUE THREAD

**Issue by Phoenix616** [pterodactyl/panel#3728]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When setting the memory amount that a server can at maximum allocate the container started by wings will go above the set amount even though the setting says `The maximum amount of memory allowed for this container.`. This will lead to issues when trying to use the max amount of memory possible on a system with multiple containers as you can not run the expected amount. (E.g. on a system with 20GB free you cannot run 5 servers with each 4GB allocated which one would expect to be mathematically possibe)

This is the docker stats for a container which had 6000MB (6GB, 5.588GiB) assigned:

```
> docker ps -q | xargs  docker stats --no-stream
CONTAINER ID   NAME                                   CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
54c13f7c1293   80946de4-64c0-48f2-8482-f16d39c141da   32.19%    5.822GiB / 5.867GiB   99.23%    121kB / 6.28kB    3.7GB / 1.43MB    49
```

As one can see it has a limit that is 0.279 GiB bigger than the amount specified in the admin panel.

The cause for this is [this code](https://github.com/pterodactyl/wings/blob/3c54c1f840bfd7f12bac3d80a86e1f1dfd14adcd/environment/settings.go#L73-L89) which intransparently to the panel admin applies some arbitrary overhead to the configured container memory limit. (This seems to be done to try to account for the overhead of some VMs like the JVM commonly used for Minecraft servers. The better solution for those would be to subtract the amount from the memory allocated for the java application itself or to at least expose the overhead/separate application and container memory in the build configuration)

### Expected Behavior

The container's memory being limited to the amount set in the build configuration.

### Steps to Reproduce

1. Start any server with a memory limit set in the build configuration.
2. Check the container memory limit e.g. with `docker ps -q | xargs  docker stats --no-stream`

### Panel Version

1.6.3

### Wings Version

1.5.3

### Error Logs

```bash
Wings diagnostics: https://gist.github.com/Phoenix616/eb121152134a3411965f054359d7d1f7
```

**Comment by parkervcp** [comment]
The extra ram is the container overhead for system services that are part of the container. This is to make sure that your  games get the full amount assigned to them.

**Comment by Phoenix616** [comment]
@parkervcp Yes, I mention that in my text.

**Comment by parkervcp** [comment]
I missed that the first time.

Subtracting the overhead from the game server is unfair to a user as they paid for the memory for their server to use.

The system has always been like this too.

Docket is known to have at least some overhead.

**Comment by Phoenix616** [comment]
I'm not sure if preventing a host violating their contract terms with a customers should play a role in fixing issues with the software itself.

Of course properly fixing it (which in my eyes would require the server application memory to go below the specified allocated container memory) would mean a breaking change in how the software behaves right now and could therefore only ever be done on a major version update to ensure users (as in people who deploy the panel) realise the change and can adjust based on their setups and contractural requirements.

So a fix to at least offer admins a way to control this behaviour on the current code base could be to expose the overhead multiplier in a server's build configuration, add a note about the allocated memory being the amount granted to the running server, not the container and additionally maybe displaying the resulting total container memory in the panel. This could even go a step further and offer the ability to ship different default overhead multipliers per server type depending on their need.

**Comment by trenutoo** [comment]
Alternative to Matthews PR to make this overhead configurable, we should use built-in JVM options `-XX:MaxRAMPercentage=90` to ensure it doesn't hog all the memory rather than increase the overhead behind the scenes. Of course, this would also work with "unlimited" 0 memory.
