### ISSUE TITLE
Minecraft Egg Server Update Button

### ISSUE THREAD

**Issue by Pankraz01** [pterodactyl/panel#3729]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A way that users themselves can change or update the Minecraft version. So that, for example, if they are running on 1.15, the user can update to 1.17 without contacting an administrator.

### Describe the solution you'd like.

I would solve this with a button that can be found under the Settings tab. There, the user can be given the option to independently change the Minecraft version.

### Additional context to this request.

In addition, there should also be a permission option for subusers. So that they can also change the version or not.

**Comment by jvvan** [comment]
This is already possible. First, in the Startup tab, you need to put the version you want, then go to the Settings tab and click Reinstall Server. And there is a permission to allow subusers to reinstall servers.
