### ISSUE TITLE
[Feature Request] Player management section for all server types that support it.

### ISSUE THREAD

**Issue by belldandu** [Pterodactyl/Panel#373]
The goal is to create a player management section for servers that is relatively easy to add new options to. 
This section should obviously not appear should the server type have no way of managing players via a cli or api while running inside the container.

# Currently known server types that have player management via cli or api:
- [ ] Minecraft (all versions including vanilla)

# Player management options:
### CLI:
- [ ] To list players type `/list`
- [ ] To ban type `/ban <player_name>`
- [ ] To kick type `/kick <player_name>`

The following are useful but only recommended if you plan to add a menu (full page) for player management in minecraft
- [ ] To unban type `/unban <player_name>` (same thing as deop)
- [ ] To op a player type `/op <player_name>`
- [ ] To deop a player type `/deop <player_name>` (most likely would require actually knowing who is opped otherwise you would just get a message saying they arent opped)
- [ ] To change game mode type `/gamemode <player_name> {0|1|2?}` (0 = survival, 1 = creative, 2 = adventure? Unsure if adventure still exists)

- [ ] The following only apply if the server has `/whitelist {on|off}` set to on
- [ ] To add a player to the whitelist type `/whitelist add <player_name>`
- [ ] To remove a player from the whitelist type `/whitelist remove <player_name>` 
- [ ] To view who all is in the whitelist type `/whitelist list`

This issue will be updated as i find more commands for player management per server type. 
I will try to implement this myself but everyone is welcome to pitch in if they want to.

**Comment by belldandu** [comment]
Please note that commands should only be added if they are in the base version of each server type (unmodded, unpatched, vanilla, etc.)

This is so that the page doesn't have to keep up with command conflicts from mods.
We could add a custom command option on the page (where people add their own commands), but people should also know that most likely the only help they may get from custom commands would be a doc.

**Comment by schrej** [comment]
We are currently trying to change the panel to be as universal as possible. We try to remove all code that is directly related to a specific game to make the panel universal so every kind of game server can be controlled using it.
We have different ideas to allow modification of the panel for different server types. The best idea at the moment is to allow to include extensions to the panel in the upcoming packs system.

**Comment by DaneEveritt** [comment]
I'm closing this as it is better suited as an external module added to the panel.
