### ISSUE TITLE
SFTP broken after 1.5.3

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3730]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

This doesn't happen on wings 1.5.0

### Expected Behavior

No error

### Steps to Reproduce

https://play.google.com/store/apps/details?id=lysesoft.andftp&hl=en&gl=US
wings 1.5.3 

When trying to connect to sftp I get

There was a problem while connecting to ip:2022
java.io.IOException: Key exchange was not finished, connection is closed.

### Panel Version

1.6.1

### Wings Version

1.5.3

**Comment by BenasPaulikas** [comment]
Related to https://github.com/pterodactyl/wings/commit/0cfd72e1d1fecbed8738345d7d43892aa9e754f6

**Comment by yesBad** [comment]
> Related to [pterodactyl/wings@0cfd72e](https://github.com/pterodactyl/wings/commit/0cfd72e1d1fecbed8738345d7d43892aa9e754f6)

I just tested the app you gave and I tried it on my own panel. It's latest panel and latest wings. I have no problems whatsoever

**Comment by BenasPaulikas** [comment]
> > Related to [pterodactyl/wings@0cfd72e](https://github.com/pterodactyl/wings/commit/0cfd72e1d1fecbed8738345d7d43892aa9e754f6)
> 
> I just tested the app you gave and I tried it on my own panel. It's latest panel and latest wings. I have no problems whatsoever

Strange. I've tried FileZilla and many other ftp client and everything works okay there. With AndFtp android app it's failing to connect + no console output in `wings --debug`

**Comment by DaneEveritt** [comment]
Sounds like that app isn't updated enough to support modern cipher protocols, not really concerning myself with that right now. Sorry.
