### ISSUE TITLE
Overallocating node did not throw error

### ISSUE THREAD

**Issue by anondev-sudo** [pterodactyl/panel#3732]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

I have node with automatic allocation disabled (tried with both enabled and disabled), I have set allocation limits like this for the node:
![image](https://user-images.githubusercontent.com/85408287/140610399-88f021eb-8b59-4fbb-bb39-4a54065fe715.png).

When I create server using panel or API, it didn't show me error message, server is normally created when I go over the resources limit on the node.
It allows me to overallocate the node
![image](https://user-images.githubusercontent.com/85408287/140610426-3a966213-6a12-4786-850d-e32688f3ad9b.png)

When I tried to transfer existing server to that node, it showed me error message
![image](https://user-images.githubusercontent.com/85408287/140610559-5beba1c3-3de5-4f79-8514-ab6d7aa534c9.png)

It should show error message also when you are creating new server and it will go over the node allocation limits.

### Expected Behavior

When you want to create server and it will go over allocation limits on node, display error message on panel and also when creating server using API,

### Steps to Reproduce

1. Create more servers until node allocation limits are over
2. It will still allow you to create servers after reaching allocation limits on the node

### Panel Version

1.6.5

### Wings Version

1.6.5

**Comment by Jelcoo** [comment]
When you use the api, you can't, but when you use the admin panel you can

**Comment by anondev-sudo** [comment]
It didn't throw error when I was creating server using pterodactyl admin panel too.

**Comment by TrixterTheTux** [comment]
The limit will only apply if you're telling the panel to choose a node for you (using the `deploy` array when creating the server through the API), otherwise you're explicitly saying that you want it to deploy on that node (and acknowledging that it may go over the limits).

**Comment by ok236449** [comment]
I know this is an old issue, but it is still up to date. What if you have two nodes, but one with a better CPU? That does not mean you wanted to over allocate it! It should throw an error saying that node is full. Including the API aswell.

**Comment by DaneEveritt** [comment]
As @TrixterTheTux stated, that is on you to make the determination, not the API. I'm not changing the well known behavior of such a critical endpoint, you just need to put some logic on your end before calling the API to make a server on a specific node to handle your over-allocation requirements.
