### ISSUE TITLE
JWT validation error from wings

### ISSUE THREAD

**Issue by itaquito** [pterodactyl/panel#3733]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Hello! When I try to open the console of any server, I get this error spammed on the console of my browser:

`JWT validation error from wings: Error Event [69638435-7ec3-4b65-8bc7-e911bbb10d42]: jwt: exp claim is invalid` (The UUID (or what I think its an UUID) shown on the error changes on every error)

When this error happens, the console, resource graphs, uptime, etc.. don't load. However, the stats that you can see on the servers list do load.

### Expected Behavior

The error doesn't show and we can access the console of the server.

### Steps to Reproduce

Just open the console of a server.
Since many people are reporting this issue, the only trigger I could think of is that it needs to be past midnight. (I know, it doesn't make sense)

### Panel Version

1.6.5

### Wings Version

1.5.3

### Error Logs

```bash
Wings: https://ptero.co/lunavohajy


There is an error that only appears once after you logging into the panel:
Failed to retrieve persisted value from store. SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at bundle.5c78cf51.js:1
    at Object.gi [as useState] (bundle.5c78cf51.js:1)
    at t.useState (bundle.5c78cf51.js:1)
    at i (bundle.5c78cf51.js:1)
    at t.default (console.d4e7fa69.js:1)
    at li (bundle.5c78cf51.js:1)
    at Ki (bundle.5c78cf51.js:1)
    at Cc (bundle.5c78cf51.js:1)
    at hu (bundle.5c78cf51.js:1)
```
```

**Comment by itaquito** [comment]
This error might be related to #3295, but in this case, we are getting `wt: exp claim is invalid` which I don't believe happens in that issue.

**Comment by itaquito** [comment]
Apparently changing APP_TIMEZONE to Etc/UTC in .env fixes the issue.

**Comment by Parsonswy** [comment]
Experienced the same issue, running Pterodactyl `1.6.5`, Wings `wings v1.5.3`. Changing the timezone setting did fix it. Seems like it was probably brought on by the DST change.

**Comment by DrPepperG** [comment]
> 
> 
> Experienced the same issue, running Pterodactyl `1.6.5`, Wings `wings v1.5.3`. Changing the timezone setting did fix it. Seems like it was probably brought on by the DST change.

That worked for me as well, funny how DST is already breaking stuff. Changed **APP_TIMEZONE** to Etc/UTC for now.

**Comment by matthewpi** [comment]
[![image](https://user-images.githubusercontent.com/26559841/140654094-3a163ec1-a6b7-43cc-ae0e-ec2fdcb53cef.png)](https://xkcd.com/673/)

**Comment by StarWeizz** [comment]
not working for me
