### ISSUE TITLE
User not prompted to create password

### ISSUE THREAD

**Issue by mrxbox98** [pterodactyl/panel#3734]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When creating a new user there is an option to not enter a password.
`Providing a user password is optional. New user emails prompt users to create a password the first time they login. If a password is provided here you will need to find a different method of providing it to the user.`
When logging in, if a password is not entered, it will not let you attempt to log in.

### Expected Behavior

The user should be prompted to create a new password.

### Steps to Reproduce

1. Create a new user and leave the password field blank.
2. Attempt to log into the panel with the correct email and leave the password field blank.

### Panel Version

1.6.5

### Wings Version

1.5.3

**Comment by iamkubi** [comment]
Users receive an email with a link to create their password.  If your mail isn't working then they will not receive the new user email.

You have to click the link in the email, not just try to login with the same email address.
