### ISSUE TITLE
Pteroignore support on backup restore.

### ISSUE THREAD

**Issue by Talhazzers** [pterodactyl/panel#3736]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When a backup is created, a backup is created by checking the pteroignore file and excluding them, but while restoring the backup, it deletes all files and restores the backup. While restoring the backup it should check the pteroignore file and not delete the files/folders in pteroignore.

### Describe the solution you'd like.

When a backup is created, a backup is created by checking the pteroignore file and excluding them, but while restoring the backup, it deletes all files and restores the backup. While restoring the backup it should check the pteroignore file and not delete the files/folders in pteroignore.

**Comment by DaneEveritt** [comment]
You can select not to delete all of the files when restoring the backup. I don't really want to make this system more confusing, and I think having it only delete files not in the ignore file would lead to that.

I'm not sure I see a scenario clearly where you'd have ignored files for a backup that you don't want to have deleted when restoring said backup? Or a scenario where you'd not accomplish the same thing by just un-checking the "delete all files when restoring" option.
