### ISSUE TITLE
Add button to delete the server after suspension

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3738]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The server would have to be deleted entirely so that no more disk space is consumed.

### Describe the solution you'd like.

If the server is canceled due to non-payment, it can be deleted by clicking the button with an additional warning where the server name must be entered: https://i.imgur.com/yi7WqPB.png

**Comment by trenutoo** [comment]
Your billing software should handle any automated deletions for non payment. Whmcs and blesta modules do this.

**Comment by Felix5566** [comment]
If the customer no longer pays, I do not want it to be automatically deleted.

**Comment by trenutoo** [comment]
Why not use the admin panel for this, which would be the correct place for administration tasks?

**Comment by FoksVHox** [comment]
This sounds like a very niche case. Also if a customer no longer pays then it should be handled by the billing software, you should also keep in mind when using WHMCS or Blesta, you can modify the suspension code, and then change how it should handle when a customer is no longer pays.

**Comment by DaneEveritt** [comment]
Won't be adding this, it doesn't match the way I see this software being used, and as mentioned above this is really better handled by a billing platform.
