### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#3739]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

None

### Describe the solution you'd like.

None

### Additional context to this request.

I am been banned from your discord server for mass advertising 

roguebros23#0232

**Comment by Jelcoo** [comment]
I don't think this is the way to appeal

**Comment by camwhi-te** [comment]
'Feature Request'

**Comment by ghost** [comment]
How do I appeal then

**Comment by iamkubi** [comment]
As you mentioned you were banned for DM advertising.  Why do you believe you should be unbanned?
