### ISSUE TITLE
Add ability to change docker network

### ISSUE THREAD

**Issue by cofob** [pterodactyl/panel#3741]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to host my minecraft server over IPv6 (Yggdrasil)[https://yggdrasil.link], but the docker does not have access to it. In a normal container, I would fix this with the --network host flag, but they are managed by Wings, not me. Also, containers do not have access to localhost (I have MySQL Server there), and because of this, I have to bind the necessary but unavailable services to the docker subnet, which is not comfort. How could I do that?

### Describe the solution you'd like.

Add the ability to select the network from which Wings to launch containers and bind to IPv6 addresses.

**Comment by trenutoo** [comment]
#1418 is a feature request for per-server configuration. You can enable host network mode for the entire Wings instance right now by reading [Wings additional configuration documentation](https://pterodactyl.io/wings/1.0/configuration.html#custom-network-interfaces).

Localhost in a container is the container itself. Pterodactyl0 interface IP can be used to access the host machine. For more, read  [MySQL database host documentation.](https://pterodactyl.io/tutorials/mysql_setup.html#allowing-external-database-access)
