### ISSUE TITLE
Add automatic opening of server ports according to the rules

### ISSUE THREAD

**Issue by cofob** [pterodactyl/panel#3742]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Greetings! When I create a server, it is not available because my ports are closed. I would like them to open automatically, according to commands template.

### Describe the solution you'd like.

Add the parameter responsible for this to the settings, and a line with the `iptables` or other commands. For example:
```
iptables -A INPUT -p {protocol} --dport {port} -j ACCEPT
ip6tables -A INPUT -p {protocol} --dport {port} -j ACCEPT
iptables-save /etc/iptables/rules.v4
ip6tables-save /etc/iptables/rules.v6
```

**Comment by trenutoo** [comment]
Docker would open the assigned allocations on the docker iptables chain when the server (container) is running.

**Comment by cofob** [comment]
> Docker would open the assigned allocations on the docker iptables chain when the server (container) is running.

Yes, but he opens them exactly at the addresses of the containers, and not publicly.

**Comment by parkervcp** [comment]
Docker allocates the port on the host ip and redirects it to the internal docker ip. I don't see how this is different than what you are asking for.

**Comment by cofob** [comment]
> 
> 
> Docker allocates the port on the host ip and redirects it to the internal docker ip. I don't see how this is different than what you are asking for.

docker does not open the ports itself, I open them through the console and firewall. In addition, I suggested adding the ability to customize these rights, because I have a pretty specific setup.

**Comment by parkervcp** [comment]
If your docker isn't opening ports then it's your system having issues.

**Comment by matthewpi** [comment]
Docker handles anything regarding firewall rules, this functionality works perfectly fine when using firewalld out of the box, however I have seen people running into trouble using iptables, especially if you are also using ufw.  Functionality like this is outside of the scope of what should be integrated into this software, touching firewall rules is only asking for problems, especially if the rules aren't required.
