### ISSUE TITLE
Improve API

### ISSUE THREAD

**Issue by 8mbe** [pterodactyl/panel#3743]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The admin API does not have the full features as the client API does.

### Describe the solution you'd like.

I suggest you add more options to admin API (/api/application/servers/ to be exactly) such as files methods, backup and etc.

**Comment by trenutoo** [comment]
They are different APIs. Your admin account client token can access all servers and use the client API. There's no reason to duplicate the endpoints

**Comment by 8mbe** [comment]
> They are different APIs. Your admin account client token can access all servers and use the client API. There's no reason to duplicate the endpoints

Well, then it is not in API documentation.

**Comment by trenutoo** [comment]
> > They are different APIs. Your admin account client token can access all servers and use the client API. There's no reason to duplicate the endpoints
> 
> Well, then it is not in API documentation.

Both client and application APIs are documented at [Dashflo's API documentation](https://dashflo.net/docs/api/pterodactyl/v1/) together with how and where to generate API tokens. There's no true official API documentation by Pterodactyl yet. You can suggest to Dashflo any changes you'd like to see.
