### ISSUE TITLE
ports less than 1024

### ISSUE THREAD

**Issue by dalandis** [pterodactyl/panel#3749]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Could you add an "I know what I'm doing" setting or something similar that allows to use the "system" ports.

### Describe the solution you'd like.

Allow to use system ports. Using a checkmark in the settings or just allow

### Additional context to this request.

The panel assumes that you have any knowledge of Linux for installation. But it does not allow using the "system" ports.

Because of this, there is no way to just make an image of a webserver with standard ports. Or use some minecraft plugins that need port 443.

I think that whoever installed the panel knows what he is doing.

**Comment by gOOvER** [comment]
Pterodactyl is not for hosting Webserver

**Comment by dalandis** [comment]
I understand. But any of the ports may be needed for the game server.

My example. The plan works on the bungee network and I cannot use it on port 443. You have to use port 1443 and because of this the address is not pretty.

Are there any good reasons to not use these ports?

**Comment by gOOvER** [comment]
you can use proxy from nginx to use 1443 pe with a nice url

i never see any gameserver which use http ports :)

**Comment by dalandis** [comment]
this is a plugin - https://www.spigotmc.org/resources/plan-player-analytics.32536/

it provides a web interface. For authorization to work on the page, a certificate is required.
Authorization won't work through nginx.

**Comment by parkervcp** [comment]
> it provides a web interface. For authorization to work on the page, a certificate is required.
> Authorization won't work through nginx.


Nginx can absolutely proxy to the internal ports and also serve the ssl cert you are complaining about.

**Comment by dalandis** [comment]
The plugin has authorization only when using a certificate. I tried to tune through nginx. It works, but without authorization.

I have covered with basic authorization for now. But if possible, I wanted to get the setting for using system ports.

**Comment by dalandis** [comment]
Logically, nginx is the same software installed as mysql, but default ports for mysql (3306) are available.

**Comment by trenutoo** [comment]
You can modify the [validator](https://github.com/pterodactyl/panel/blob/develop/app/Models/Allocation.php#L59) should you want to accomplish this. Ports below 1024 require escalated privileges that Pterodactyl doesn't offer for security reasons.

**Comment by alixplayz** [comment]
> You can modify the [validator](https://github.com/pterodactyl/panel/blob/develop/app/Models/Allocation.php#L59) should you want to accomplish this. Ports below 1024 require escalated privileges that Pterodactyl doesn't offer for security reasons.

How would I do that?

**Comment by fizzrepo** [comment]
> > You can modify the [validator](https://github.com/pterodactyl/panel/blob/develop/app/Models/Allocation.php#L59) should you want to accomplish this. Ports below 1024 require escalated privileges that Pterodactyl doesn't offer for security reasons.
> 
> How would I do that?

I know this is old, but here's step by step instructions for Ubuntu if anyone needs it in the future:

cd /var/www/pterodactyl/app/Models
nano Allocation.php
(Find that line and change it)
Press CTRL + x and then Y

**Comment by DaneEveritt** [comment]
Won't be changing this.

**Comment by AliceDoesStuff** [comment]
fuck u nigga
