### ISSUE TITLE
Adding Plugin Support via Folder

### ISSUE THREAD

**Issue by Marco15453** [pterodactyl/panel#3750]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to see a feature that will load modules (plugins) via a folder in the main root of pterodactyl

### Describe the solution you'd like.

Same as above.

**Comment by trenutoo** [comment]
Do you mean third-party modifications to the panel?

**Comment by gOOvER** [comment]
I think he mean this:

#2234

**Comment by Marco15453** [comment]
Yes, Duplicate of #2234
