### ISSUE TITLE
WHMCS errot

### ISSUE THREAD

**Issue by djiga88** [pterodactyl/panel#3751]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => DaemonConnectionException
                    [status] => 500
                    [detail] => There was an error while communicating with the machine running this server. This error has been logged, please try again. (code: 500) (request_id: 6b9a8c73-ca51-414b-9c54-956e8cf2c407)
                )

        )

    [status_code] => 500
)

### Describe the solution you'd like.

how to solve this problem

**Comment by yesBad** [comment]
wrong place

**Comment by djiga88** [comment]
what do you mean wrong place?
I put the module in vhmcs set up and this comes out as an error

**Comment by djiga88** [comment]
what do i have to do to fix it

**Comment by trenutoo** [comment]
This is not a feature request. Use the correct template, or alternatively use Discord server for support as you are having issues with connecting to wings.
