### ISSUE TITLE
Java 17 - Docker Image

### ISSUE THREAD

**Issue by lukemango** [pterodactyl/panel#3752]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

1.18 pre-release 2 came out today and includes Minecraft bumping to JDK 17 (https://www.minecraft.net/es-es/article/minecraft-1-18-pre-release-2)

### Describe the solution you'd like.

A docker image for Java 17 included in Pterodactyl's panel.

**Comment by Boy132** [comment]
This was already added with #3744 and will be included in the next release.

**Comment by trenutoo** [comment]
You can also add this right away with `ghcr.io/pterodactyl/yolks:java_17` that's from our [Yolks](https://github.com/pterodactyl/yolks) repository.
