### ISSUE TITLE
Session store not set on request

### ISSUE THREAD

**Issue by Craftzman7** [pterodactyl/panel#3754]
### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.

### Current Behavior

When making a POST request to the /api/application/users endpoint I get back the following JSON output
```json
{
    "errors": [
        {
            "code": "RuntimeException",
            "status": "500",
            "detail": "An unexpected error was encountered while processing this request, please try again."
        }
    ]
}
```

The following error is shown in the Laravel log file 
https://pastie.io/vdsdvn.tex

### Expected Behavior

A new user would be created and a 201 status code would be returned

### Steps to Reproduce

Simply make a post request with the needed request body to the /api/application/users

### Panel Version

1.6.6

### Wings Version

1.5.3

**Comment by FoksVHox** [comment]
Are you sure that you're on 1.6.6, as the tests for 1.6.6 passed for creating a user via the API
https://github.com/pterodactyl/panel/runs/4233948585?check_suite_focus=true#step:11:51

**Comment by Craftzman7** [comment]
> Are you sure that you're on 1.6.6, as the tests for 1.6.6 passed for creating a user via the API https://github.com/pterodactyl/panel/runs/4233948585?check_suite_focus=true#step:11:51

Yes I am sure. 

![Screenshot 2021-11-18 7 57 58 AM](https://user-images.githubusercontent.com/70068692/142450532-5f34486e-c973-4b31-8598-2128e68767ac.png)

**Comment by matthewpi** [comment]
What headers (and or cookies) are you sending when making that request?

**Comment by Craftzman7** [comment]
> What headers (and or cookies) are you sending when making that request?

No cookies. I am setting the `Accept` header to application/json as well as the `Content-Type` header. The authorization header is `Bearer myapikey`

**Comment by trenutoo** [comment]
I can't replicate this on 1.6.6. Do you have any third-party modifications that might've replaced middleware?

```
{
  object: 'user',
  attributes: {
    id: 2,
    external_id: null,
    uuid: 'f1bb6ec7-c1a6-418d-948f-e44ecf9f9b1b',
    username: 'test1234',
    email: 'example123@example.com',
    first_name: 'Example',
    last_name: 'User',
    language: 'en',
    root_admin: false,
    '2fa': false,
    created_at: '2021-11-18T17:04:29+00:00',
    updated_at: '2021-11-18T17:04:29+00:00'
  },
  meta: { resource: 'http://pterodactyl.panel.test/api/application/users/2' }
}
```

**Comment by Craftzman7** [comment]
> I can't replicate this on 1.6.6. Do you have any third-party modifications that might've replaced middleware?
> 
> ```
> {
>   object: 'user',
>   attributes: {
>     id: 2,
>     external_id: null,
>     uuid: 'f1bb6ec7-c1a6-418d-948f-e44ecf9f9b1b',
>     username: 'test1234',
>     email: 'example123@example.com',
>     first_name: 'Example',
>     last_name: 'User',
>     language: 'en',
>     root_admin: false,
>     '2fa': false,
>     created_at: '2021-11-18T17:04:29+00:00',
>     updated_at: '2021-11-18T17:04:29+00:00'
>   },
>   meta: { resource: 'http://pterodactyl.panel.test/api/application/users/2' }
> }
> ```

No. This is a fresh install of the panel.

**Comment by DaneEveritt** [comment]
Can you please include the full code example you're using to make this request (with a fake API key).

**Comment by Craftzman7** [comment]
> Can you please include the full code example you're using to make this request (with a fake API key).
```js
const ptrAccInfo = {
    email: req.session.email,
    username: req.session.username,
    first_name: req.session.username,
    last_name: user.discriminator
}
var pteracc = await fetch(
    "https://pterodactyl.test/api/application/users", {
        method: "POST",
        headers: {
            "Accept": "application/json",
            "Content-Type": "application/json",
            "Authorization": `Bearer ${process.env.PTRKEY}`,
        },
        body: ptrAccInfo
    }
);
```

The fetch function is imported from node-fetch https://npmjs.com/node-fetch

**Comment by trenutoo** [comment]
This is caused by your body encoding. It should be converted to JSON. `body: JSON.stringify(ptrAccInfo)`

**Comment by Craftzman7** [comment]
> This is caused by your body encoding. It should be converted to JSON. `body: JSON.stringify(ptrAccInfo)`

That did it! Thank you.
