### ISSUE TITLE
i have the same issue as described above, what do I have to do effectively to fix the null name thing ?

### ISSUE THREAD

**Issue by DrDirtyDevil** [pterodactyl/panel#3755]
i have the same issue as described above, what do I have to do effectively to fix the null name thing ? 

I have 2 servers with a backup task running every 6 hours but it doesn't do anything 
![Schermafbeelding 2021-11-17 om 13 12 11 PM](https://user-images.githubusercontent.com/60276285/142198397-431c610d-5d5f-4156-be2c-fe2b8a0faaea.png)

the run from 1:05 pm I did manually

_Originally posted by @DrDirtyDevil in https://github.com/pterodactyl/panel/issues/2609#issuecomment-971522218_

**Comment by trenutoo** [comment]
Please follow the issue template format. Most likely your queue worker is not setup, running or needs a restart.

**Comment by DrDirtyDevil** [comment]
where can i find the template ?

**Comment by trenutoo** [comment]
You see it when you try to open a new issue. First actually check the previously mentioned pteroq queue worker as mentioned in duplicate issue reports #3621 #3572 #3330
