### ISSUE TITLE
[Pterodactyl Daemon]: Exit code: 128

### ISSUE THREAD

**Issue by Eumanuel** [pterodactyl/panel#3757]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Right now, the server installed successfully, but when I try to start it, I get the following error:
![image](https://user-images.githubusercontent.com/44380634/142458134-760bc3d9-13a7-4996-b5b6-d8fac3fa9ec0.png)

The port is open both on my firewall and Iptables and this is indeed my ip adress since It would not connect if it wasn't

The platform is arm, my distro is ubuntu 20.04 installed using  "bash <(curl -s https://raw.githubusercontent.com/vilhelmprytz/pterodactyl-installer/master/install.sh)" and certificate manually installed. Wings was configured using automatic token and is online on the panel.

Machine is located at Oracle cloud and all Ports is opened there.

### Expected Behavior

The server to start without problems

### Steps to Reproduce

Install your machine using arm based processor

Install your certificate manually using an apache server on 80 port and certbot on webroot configuration

Install wings using bash <(curl -s https://raw.githubusercontent.com/vilhelmprytz/pterodactyl-installer/master/install.sh)

Use your panel provided token for configurate wings

Run "systemctl enable --now wings"

Create a server, wait until install is done

Try to start it.

Result:
![image](https://user-images.githubusercontent.com/44380634/142459313-e135e98e-4d1d-464f-828b-2ec0eda24256.png)

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/ijosivukot
```

**Comment by trenutoo** [comment]
Such IP is not bound to your network interface. Allocations are covered in the [wings install documentation](https://pterodactyl.io/wings/1.0/installing.html#node-allocations) together with commands on how to retrieve the IP and view all your available IPs.

**Comment by Eumanuel** [comment]
Indeed that was a problem, using "hostname -I | awk '{print $1}'" showed my local address and that was the address I needed to Allocate, not the public address. 

Thank you.

**Comment by SebastianRiquelmeM** [comment]
You must use the private IP when creating the node locations, and I recommend you put the public IP as an alias because you must connect to this in the game
