### ISSUE TITLE
Can't get nodes&server status

### ISSUE THREAD

**Issue by krfcm** [pterodactyl/panel#3758]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Hey, after updating my panel to the last version, i noticed that my panel can't get status from my node's and servers.
![image](https://user-images.githubusercontent.com/14114364/142519426-aa672451-70d3-43c1-bd93-0ab74db21f27.png)
I checked and node's have valid certyficats
![image](https://user-images.githubusercontent.com/14114364/142519505-2a10facc-8852-48a5-a68d-15081b43fdeb.png)

### Expected Behavior

help in fixing the error

### Steps to Reproduce

Update panel to the last version

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/qoqagysype
https://bin.ptdl.co/pgqua/
```

**Comment by DaneEveritt** [comment]
```
ERROR: [Nov 19 01:32:02.126] error processing websocket event "auth" error=jwt: HMAC verification failed error_identifier=b2456012-b820-4d16-918f-93b06721e52b event=auth server=5e0d450f-6ae9-4c42-9db5-22a3b02b6523

Stacktrace:
jwt: HMAC verification failed
github.com/apex/log.(*Entry).Errorf
	/home/runner/go/pkg/mod/github.com/apex/log@v1.9.0/entry.go:132
github.com/pterodactyl/wings/router/websocket.(*Handler).SendErrorJson
	/home/runner/work/wings/wings/router/websocket/websocket.go:240
github.com/pterodactyl/wings/router.getServerWebsocket.func3
	/home/runner/work/wings/wings/router/router_server_ws.go:86
runtime.goexit
	/opt/hostedtoolcache/go/1.17.2/x64/src/runtime/asm_amd64.s:1581
```

You do not have a proper configuration file setup for this node, copy it from the Panel again and it should begin working.

**Comment by krfcm** [comment]
I have this problem on all node's.
But for others users it works fine.

**Comment by Guevin1** [comment]
wao
