### ISSUE TITLE
Add CREATE VIEW to database user privileges

### ISSUE THREAD

**Issue by dootsi** [pterodactyl/panel#3761]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add CREATE VIEW to database user privileges. I frequently use a plugin on my servers that use views and having to manually grant permissions to each database user is a bit of a pain.

### Describe the solution you'd like.

Add CREATE VIEW to the list of privileges for database users. I think it would be on [this](https://github.com/pterodactyl/panel/blob/30bb629bad809eae48e8aee1271c7e6f940a0364/app/Repositories/Eloquent/DatabaseRepository.php#L110) line.

**Comment by FoksVHox** [comment]
Follow the template...

**Comment by gepron1x** [comment]
+1 for this

**Comment by A248** [comment]
Apparently this issue -- that pterodactyl does not grant adequate permissions -- is much more extensive than simply the `CREATE VIEW` permission.

Here are all the permissions it grants:
https://github.com/pterodactyl/panel/blob/b8bf537737d5ce7d30d95cbf12da6e3a54aa3a1b/app/Repositories/Eloquent/DatabaseRepository.php#L110

It should also grant the following permissions:
* CREATE TEMPORARY TABLE
* CREATE VIEW
* EVENT
* SHOW VIEW
* TRIGGER

Past PRs to pterodactyl have granted extra permissions only where their authors saw one or a handful of permissions fit to add:
- https://github.com/pterodactyl/panel/pull/3419
- https://github.com/pterodactyl/panel/pull/3389

It is about time that pterodactyl *truly* solved this issue and granted all of the appropriate permissions to the database user. A non-trivial SQL-using program might easily use one of these permissions not granted.

**Comment by DaneEveritt** [comment]
Its also been like that for 5 years and no one has complained, so you can understand why it might be a lower priority for me to look at. :)
