### ISSUE TITLE
No more support for yarn and npx

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#3765]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

After the command "yarn run build:production" the process ends only as an error, with the current npx browserslist@latest version: https://pastebin.com/fTWcz2iB

### Expected Behavior

please update the code so that it works with the current version: 1.0.30001282

### Steps to Reproduce

cd /var/www/pterodactyl
yarn install
npx browserslist@latest --update-db
yarn run build:production

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/ovaleruhex
http://bin.ptdl.co/wqx6y
```

**Comment by notAreYouScared** [comment]
Your error has nothing to do with browserslist.

If you read your error logs it states the following


Error: Can't resolve 'react-transition-group/CSSTransition'
Module not found: Error: Can't resolve 'react-dom'

**Comment by Felix5566** [comment]
> Your error has nothing to do with browserslist.
> 
> If you read your error logs it states the following
> 
> Error: Can't resolve 'react-transition-group/CSSTransition' Module not found: Error: Can't resolve 'react-dom'

How can i fix it?

**Comment by notAreYouScared** [comment]
> > Your error has nothing to do with browserslist.
> > If you read your error logs it states the following
> > Error: Can't resolve 'react-transition-group/CSSTransition' Module not found: Error: Can't resolve 'react-dom'
> 
> How can i fix it?

You need to run yarn install to install the required packages
