### ISSUE TITLE
IPv6 support for Wings

### ISSUE THREAD

**Issue by mctom987** [pterodactyl/panel#3768]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Wings does not listen on IPv6, even when explicitly configured to `::`

### Expected Behavior

Liste

### Steps to Reproduce

Have IPv6

### Panel Version

1.6.6

### Wings Version

1.5.3

**Comment by mctom987** [comment]
Why was this closed? IPv6 is still not working.

**Comment by FoksVHox** [comment]
Please look at the older issues @mctom987. IPv6 is supported to might require some additional configurations to docker to get it to work

**Comment by DaneEveritt** [comment]
It was closed because there are other open issues about this easily found by searching `ipv6`, and there is no detail in this report.
