### ISSUE TITLE
Error after  yarn && yarn build:production

### ISSUE THREAD

**Issue by DerMeso** [pterodactyl/panel#3771]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

After running yarn && yarn build:production the following error occurs:

`ERROR in resources/scripts/components/server/backups/BackupRow.tsx:24:23
TS2352: Conversion of type '`backup completed:${string}`' to type 'SocketEvent' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
    22 |     const { mutate } = getServerBackups();
    23 |
  > 24 |     useWebsocketEvent(`${SocketEvent.BACKUP_COMPLETED}:${backup.uuid}` as SocketEvent, data => {
       |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    25 |         try {
    26 |             const parsed = JSON.parse(data);
    27 |`

### Expected Behavior

That the update goes through successfully

### Steps to Reproduce

On the panel yarn && yarn build:production run

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://www.toptal.com/developers/hastebin/figovanaqe.yaml
```

**Comment by notAreYouScared** [comment]
Did you do yarn upgrade by chance?

**Comment by DerMeso** [comment]
correctly, i have a yarn and npm upgrade  performed

**Comment by notAreYouScared** [comment]
That might be the reason for the error. You most likely updated a package to a version that's not supported and it broke somthing. You should delete the node modules folder, package.json and yarn.lock

Then download the ones from github, for the version of the panel you're using, to replace them, run `yarn` then `yarn build:production`
