### ISSUE TITLE
Wings little bug

### ISSUE THREAD

**Issue by Rezanans-wow** [pterodactyl/panel#3772]
### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.

### Current Behavior

In short, there are two problems

First problem, when you create a server it starts up and the console starts spamming empty spaces (This can be seen in the side scrolling slider)

The second problem, the server does not respond correctly to shutdown, CPU and RAM statistics are not displayed (Probably disk)

### Expected Behavior

I have not been able to determine the cause of the problem, I have cleared cookies, cache and so on looked into the logs - but there is nothing there
**Wings restart (service wings restart) resolve issue, but its happens again,again,again**

### Steps to Reproduce

Prolonged use of the server or sudden restarts (Through the shutdown button, **NOT RESTART**!!!)

### Panel Version

1.6.5

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/metomijuto
```

**Comment by Ferks-FK** [comment]
This is not a problem with the wings, but with docker.
More specifically with `docker stats`.

**Comment by notAreYouScared** [comment]
The white spaces error I get randomly, but unable to reliably reproduce to track down the issue. 

As for the stats not showing, they're pulled directly from docker. What's the output of `docker stats`? If those are 0 as well that would be a issue outside of pterodactyls reach.

Edit: You say restarting wings fixes the stats? Do they only update if you refresh the page or do they show 0 unless wings is restarted?

**Comment by Rezanans-wow** [comment]
> The white spaces error I get randomly, but unable to reliably reproduce to track down the issue.
> 
> As for the stats not showing, they're pulled directly from docker. What's the output of `docker stats`? If those are 0 as well that would be a issue outside of pterodactyls reach.
> 
> Edit: You say restarting wings fixes the stats? Do they only update if you refresh the page or do they show 0 unless wings is restarted?

They fixing automatic, when restarting like page reloading as wings but not F5
![Screenshot_16](https://user-images.githubusercontent.com/49691442/143678592-ba6533e6-4e23-450d-9be4-32ace062e539.png)

**Comment by DaneEveritt** [comment]
Please open one issue per... issue. Combining multiple into one is difficult for us to track, and will likely result in no action occurring. You can edit this one to be whichever you prefer, but please open a second for the other issue.
