### ISSUE TITLE
Network Usage chart / summary.

### ISSUE THREAD

**Issue by crispyaus** [pterodactyl/panel#3780]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would love to see some sort of network receive & transmit chart on server page, and possibly even a dedicated page to view a log of connections to and from the allocated ip

**Example:** 
![image](https://user-images.githubusercontent.com/34707863/144218740-55bdf5d9-a91e-4e9a-bdc6-b658e3770a28.png)

You would be able to see large spikes in network usage, and possible relate them to other issues going on in the container, this could be useful for debugging and sorting out issues that users may come across.

### Describe the solution you'd like.

A network usage chart would be handy for glance, but also a more robust way to store not only the network usage data, but other charts like CPU and memory would be very helpful. Possibly Panel admins can decide how the information would store for on a per server basis.

A log/table of connections/pings would also be helpful.

**Comment by parkervcp** [comment]
Docker does not track live network usage like this. They track usage over the life of the container.

All you would get is a constantly growing value.

This has been requested tons of times.

**Comment by parkervcp** [comment]
#3310 and #3352 are examples of this you didn't find.

**Comment by trenutoo** [comment]
The container network RX and TX usage is collected and available in the API, but without some wild estimate calculation, all you'd get is the lifetime container usage, not a real-time representation

**Comment by DaneEveritt** [comment]
You can calculate real-time, it just requires some adjustments on Wings, seeing as Docker already displays this to you. Its just a matter of tracking previous value to next value and getting the delta.

You could probably do it on the front-end too, would be the same concept.

**Comment by crispyaus** [comment]
> This has been requested tons of times.

Far as I could see I looked for addons, and on the issues and could not find related resources. Along as in the discord.

> #3310 and #3352 are examples of this you didn't find.

How are these related?

**Comment by Prophet731** [comment]
I just created a PR that adds the current network traffic. See #3802

**Comment by BasToTheMax** [comment]
Please also add a monthly bandwidth limit!

**Comment by DaneEveritt** [comment]
Closed in 62b178ed0297549be9eb009c968d5d47d4fe8ffb
