### ISSUE TITLE
Spigot 1.18 compiling with Java 8 instead of Java 17

### ISSUE THREAD

**Issue by matteoscaringi** [pterodactyl/panel#3781]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Pterodactyl clones BuildTools installs Java 8 instead of 17 and then it aborts with a crash with a message that i need to use java 17.

### Expected Behavior

Spigot should be compiling with Java 17 with BuildTools instead of Java 8

### Steps to Reproduce

Use the spigot egg and use version 1.18 and then reinstall the server for it to install spigot 1.18.

### Panel Version

1.6.6

### Wings Version

1.5.3

**Comment by Boy132** [comment]
Spigot isn't a Stock egg. You should post that in https://github.com/parkervcp/eggs

**Comment by trenutoo** [comment]
The spigot egg from the egg repo was updated to support java 17 and 1.18 a while ago. Update the egg.
