### ISSUE TITLE
Allow ability to set values as MB/GB or MiB/GiB

### ISSUE THREAD

**Issue by Korgen1** [pterodactyl/panel#3784]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Currently the panel will ask you how many MB you want. If you were to put in 10000MB it will display as 9.77GB, which means it is asking for MB and displaying in GiB. I would like it to be able to display in GB properly.

### Describe the solution you'd like.

Some people do prefer MiB/GiB so maybe make it a toggle so you can choose what you prefer.

**Comment by YusufYaser** [comment]
You can multiply the GBs with 1024 instead of 1000 if you want it to display correctly.

So 1 GB would be 1024 MB and not 1000 MB

**Comment by Korgen1** [comment]
> You can multiply the GBs with 1024 instead of 1000 if you want it to display correctly.
> 
> So 1 GB would be 1024 MB and not 1000 MB

Then I have to calculate 1024x10. And it’s still not correct because 1024MiB is 1 GiB. 1000MB is 1GB.

**Comment by DaneEveritt** [comment]
Won't be changing this.
