### ISSUE TITLE
Wings little problem

### ISSUE THREAD

**Issue by Rezanans-wow** [pterodactyl/panel#3785]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Incorrect display of server status, or more precisely the status indicators (Server Status, RAM, CPU) including graphs

_I re-created issue, with only 1 problem. Its not duplicate no need close it_

### Expected Behavior

Everything should be fine, but for example RAM, CPU remains at values 0, 0. The server status is frozen on 'STARTING' although in the console the server starts fine, and after starting you can log in. I have attached a screensho
![Screenshot_463](https://user-images.githubusercontent.com/49691442/144603845-1ccc10cb-b741-4b08-ba8d-44435a00be77.png)
t

### Steps to Reproduce

This happens completely by accident, tested also on a completely clean OS with a clean pterodactyl installed same issue randomly without log error/warns

How fix problem? - service wings restart
**This is fix issue, and no need browser refresh, when wings restarted its automaticly fixing in realtime all monitors set to normal**
But its not resolve issue, future problems still and still

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/rulydobybu
```

**Comment by parkervcp** [comment]
What stats does docker show at the same time? Wings uses docker stats for those values.

**Comment by Rezanans-wow** [comment]
> 

After I was told to follow it up, the stats in the docker were normal. That is, the CPU was listed correctly and so on

**Comment by 641i130** [comment]
I'm getting this as well. It happened when I updated. All my servers appear this way.

**Comment by 641i130** [comment]
![image](https://user-images.githubusercontent.com/46945263/144728696-f12d92ac-be85-477b-a571-561984529367.png)
This must be related.

**Comment by 641i130** [comment]
https://ptero.co/owikubyzuz

**Comment by SocolSRT** [comment]
Same issue

**Comment by trenutoo** [comment]
This would be a WebSocket issue. There are multiple issues open for this, such as #3528 and #3508

Should you have more reproducible steps or helpful information, please post them to the issues above.
