### ISSUE TITLE
Discord Ban :'(

### ISSUE THREAD

**Issue by Todixys** [pterodactyl/panel#3786]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Hello, i get ban from discord when i put a log line with a link in the logs line ...
The bot ban me instantly ...

My Discord : Todixys#2110

Sorry if it's not the correct place to say that and i don't know how to use github ^^

Thanks ! 

### Expected Behavior

Nothing

### Steps to Reproduce

Nothing

### Panel Version

1.0

### Wings Version

1.0

**Comment by Software-Noob** [comment]
Your ban has been removed.
