### ISSUE TITLE
Network in my servers [Solved]

### ISSUE THREAD

**Issue by Doodke3** [pterodactyl/panel#3787]
### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.

### Current Behavior

Why when I try to view my servers (SHOWING YOUR SERVERS) I get the "Network Error", but when I am on SHOWING OTHERS' SERVERS, I can see it, and it's not just for me

### Expected Behavior

See my servers without 2nd admin account...

### Steps to Reproduce

I looked at Cloudflare apps, previewed some, (didn't install) and I got the error, from that point it broke, I'm not sure if it's because of this because when I tried to use a backup from 2 days ago, I still got the same error.
And the error is not only for me (my account)

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
Wings: https://ptero.co/evezixabat

Panel: http://bin.ptdl.co/cj7mm
Panel logs from 1 or 2 days ago: http://bin.ptdl.co/xfa60 and http://bin.ptdl.co/ymbd6
```

**Comment by seailz** [comment]
Hey, did you ever fix this?
