### ISSUE TITLE
Panel cannot connect to daemon

### ISSUE THREAD

**Issue by GoldElysium** [pterodactyl/panel#3789]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

On the nodes page it shows the node as online and can connect to it directly(looking at networks tab in devtools):
![image](https://user-images.githubusercontent.com/48455312/144748920-8f4862dc-acec-49aa-85a3-4d71684f0c7c.png)
But when I click on it or try to interact with the node(create a server etc.) it gives an error that it can't establish a connection with it:
![image](https://user-images.githubusercontent.com/48455312/144748945-a2de2ff5-4c68-49eb-b6fb-8821e4bf52aa.png)
![image](https://user-images.githubusercontent.com/48455312/144748958-a6252f67-eae7-4239-86db-41522e5de01f.png)

Snippet of error message:
```json
{
    "code": "DaemonConnectionException",
    "status": "504",
    "detail": "Could not establish a connection to the machine running this server. Please try again."
}
```

### Expected Behavior

It can connect to the node and create a server or give the expected information.

### Steps to Reproduce

Uncertain, only thing I can think of is that the IP address of the node has changed recently, but the DNS has been updated accordingly.

### Panel Version

1.6.6

### Wings Version

1.5.3

**Comment by trenutoo** [comment]
The heart is an indication of connection from your browser. It means that you can reach Wings, but not the panel. That'd be a network issue between the panel machine and wings, which would also show up in the panel logs you didn't provide and is not a bug

**Comment by GoldElysium** [comment]
> The heart is an indication of connection from your browser. It means that you can reach Wings, but not the panel. That'd be a network issue between the panel machine and wings, which would also show up in the panel logs you didn't provide and is not a bug

Took a bit of time, but here are the logs: http://bin.ptdl.co/xuqb0

But I might have figured it out already trying to get those logs uploaded, neither curl or nc can resolve hosts but nslookup does resolve correctly. Needed to copy the 100 lines to my machine and then upload it. So possibly a kubernetes dns issue again...

**Comment by GoldElysium** [comment]
Yeah, pretty sure it's kubernetes, the image I'm using is using alpine linux which has issues with kubernetes dns. Gonna close this then.
