### ISSUE TITLE
Wings HTTPS

### ISSUE THREAD

**Issue by 641i130** [pterodactyl/panel#3790]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When trying to start wings, it will not connect to the API via HTTPS and returns: 
```
context deadline exceeded (Client.Timeout exceeded while awaiting headers)
http: request creation failed
```

### Expected Behavior

Wings should start and connect to the API correctly.

### Steps to Reproduce

Update everything, switch to using SSL.

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/oxycydyryc

http://bin.ptdl.co/125tj
```

**Comment by parkervcp** [comment]
Wings is failing to load your panel properly/

per line 74: `failed to load server configurations error=http: request creation failed: Get "https:// ... i/o timeout`

So when it tries to reach your panel it fails

**Comment by 641i130** [comment]
How do I go about resolving it? Everything is configured correctly. Could it be DNS?

**Comment by parkervcp** [comment]
you need to be on the machine running wings and try reaching the panel.

**Comment by 641i130** [comment]
Ok, this is not working. I literally reinstalled the entire operating system and followed the install guide very carefully. The config is correct. I copied it from the panel. Its right!

`https://ptero.co/asujajoxyz`

Something is wrong. This shouldn't be happening. I port forwarded everything correctly.

**Comment by flugasak** [comment]
I just had the exact same problem. Turns out that when I copied the configuration from the panel and saved it into /etc/pterodactyl/config.yml - it missed the last line of the config. 

The last line of the config contains the URI to connect to the panel, so wings didn't know where to connect.

`remote: 'https://address.to.your.panel'`

Hope that helps others who end up here.
