### ISSUE TITLE
Wings diagnostics doesn't redact domain

### ISSUE THREAD

**Issue by 641i130** [pterodactyl/panel#3791]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When using `wings diagnostics` and saying `No` to including endpoints:
![image](https://user-images.githubusercontent.com/46945263/144756729-e2375955-f120-4e1c-baf2-3043be0f417a.png)

Results in the FQDN and public ip still being displayed:
![image](https://user-images.githubusercontent.com/46945263/144756740-c47a1031-9d6e-47bf-81d5-7b4429d016a6.png)

### Expected Behavior

The domain name in the DEBUG and Stacktrace section should be redacted.

### Steps to Reproduce

Use `wings diagnostics` normally.

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/oxycydyryc

http://bin.ptdl.co/125tj
```

**Comment by trenutoo** [comment]
This would be more of a feature request. Redaction is created only for the endpoints that are displayed at the top and not for regexing it out of stacktraces

**Comment by 641i130** [comment]
Then why would it be listed as an option to begin with if it does nothing?

**Comment by trenutoo** [comment]
> Then why would it be listed as an option to begin with if it does nothing?

It redacts endpoints that would be listed at the top of the diagnostics. Does not regex and try to match them from possible stacktraces

**Comment by 641i130** [comment]
Pretty misleading.
