### ISSUE TITLE
[1.5.3] Wings Can't Make HTTPS Requests

### ISSUE THREAD

**Issue by 641i130** [pterodactyl/panel#3792]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When trying to get wings 1.5.3 to work (with SSL) I configure it according to the documentation. Then when I run `wings --debug` it gives me the error that I've been dealing with for the past day. I re-installed the entire VPS operating system to test this. Still giving the same error. The certs were generated correctly. I think wings isn't able to make HTTPS requests.

### Expected Behavior

It should work out of the box. Wings should be able to connect to the service. But it doesn't. From the stacktrace I think its related to this [file](https://github.com/pterodactyl/wings/blob/develop/remote/http.go) (line 140) not allowing HTTPS requests.

### Steps to Reproduce

Configure the entire panel based on the documentation.

Ports I'm forwarding:
![image](https://user-images.githubusercontent.com/46945263/144775905-f4ed0d14-f4af-4a23-805d-04fa1d9ef3d9.png)

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/asujajoxyz

http://bin.ptdl.co/vv4o2
```

**Comment by parkervcp** [comment]
As previously stated your wings instance is getting blocked from reaching the panel.

**Comment by 641i130** [comment]
I don't understand why it can't because I have the config set up correctly:
![image](https://user-images.githubusercontent.com/46945263/144776631-40bb76de-25f0-4d3d-8d1a-abaf2c014789.png)
I triple checked the ports being forwarded. I can reach my domain and it resolves correctly. What else do I check??

**Comment by parkervcp** [comment]
can you run a curl command against your own domain there?

**Comment by 641i130** [comment]
Curling actually doesn't do anything. It hangs for some reason.

**Comment by 641i130** [comment]
It says it can't resolve host. Was it dns this whole time?! :weary:

**Comment by 641i130** [comment]
I give up. I'm going back to HTTP. This isn't worth fixing.

**Comment by dapillc** [comment]
Visit the wing URL with the daemon port in your browser using https://
i.e. per your image `https://mc.disdis.win:8080 `

- If it loads with no error, it's a network issue between Wings and Panel
- If it loads with an SSL error, you'll need to configure the proper ports.
- If it doesn't load: either the service isn't running, something else is running in-place of the service, the subdomain is pointing to the wrong server, or a handful of other things.
