### ISSUE TITLE
Limit Database Host to Location

### ISSUE THREAD

**Issue by dapillc** [pterodactyl/panel#3795]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

As of now the ability to select the default Node is available.
However, a database typically resides in a specific location that should only be used for nodes in that area.
This not only helps to prevent lag but can increase security by not allowing the database outside of the network.

### Describe the solution you'd like.

Location: LAN
Nodes: 1, 2, 3
Database should not be accessible from outside of the LAN network, but should be available for Node's 1, 2, and 3.

Location: US-EAST-1
Nodes: 4, 5, 6
Database should only be accessible for Node's 4, 5, and 6.

**Comment by trenutoo** [comment]
Implemented in V2 #1980
