### ISSUE TITLE
OCI runtime create faile

### ISSUE THREAD

**Issue by zendrique** [pterodactyl/panel#3797]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When creating a server the docker container has problems starting and crash

### Expected Behavior

at start-up and proper functioning of the container

### Steps to Reproduce

To reproduce the problem, you must install wings on a Raspberry Pi 4 4 GB and install the Raspberry Pi OS 11 Lite 64-bit operating system. Mount a storage space (hard drive or USB key) and configure wings to indicate that the storage location of the servers is on the storage medium. Once wings are configured and linked to the panel, all you have to do is try to create a server on the node in question

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/ukurumopej
```

**Comment by trenutoo** [comment]
This is an issue with your cgroups as seen by the stacktrace.

`sys/fs/cgroup/system.slice/docker-1c8789d684d7adf579da0018683a90d6118ce94ecd782c010f0f1d41651e5786.scope/io.weight: no such file or directory: unknown`
