### ISSUE TITLE
IP Address 

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#3798]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

None

### Describe the solution you'd like.

None

### Additional context to this request.

It would do cool to add additional IP address to the panel

**Comment by hwalker928** [comment]
You can? Are you talking about multiple panel URLs or multiple IPs on a single node?

**Comment by ghost** [comment]
I am talking about multiple IP Address for each Game Server

**Comment by ghost** [comment]
So I am banned from the Discord Server but it would be cool to add something where people still can get help if we need it

**Comment by trenutoo** [comment]
You are not limited to a single ip.  You can add multiple different IPs in Node allocations if your machine network interface has them available

**Comment by ghost** [comment]
How would I add IP Address to my machine

**Comment by trenutoo** [comment]
You would have to lease or purchase the IP and add it to your network interface. Contact your host provider for more assistance. That would fall under Linux administration

**Comment by ghost** [comment]
Okay,
