### ISSUE TITLE
Wings remote error: tls: expired certificate

### ISSUE THREAD

**Issue by TreeHD** [pterodactyl/panel#3799]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

NONE

### Expected Behavior

I've using v1.5.3 Wings on aarch64

When i visit `admin/nodes/view/{node_id}`  Panel will sent a request to Wings in order to get node status
And Always return 502 Error

Wings will display  `http: TLS handshake error from {Panel IP}:41702: remote error: tls: expired certificate`

I've trying visit `admin/nodes` to make sure node is GREEN HEART and browser F12 / OpenSSL Tool didn't return any ERROR about wings cert
Also I very sure that AutoTLS is working 

### Steps to Reproduce

visit `admin/nodes/view/{node_id}`

### Panel Version

1.6.6

### Wings Version

v1.5.3

**Comment by QuintenQVD0** [comment]
It looks like your SSL certificate has probably expired which is causing you some issues. Please double check that it is up-to-date and renew it if needed by following our guide https://pterodactyl.io/tutorials/creating_ssl_certificates.html

Additionally, not every service is able to automatically apply an updated certificate so you may need to restart Wings, NGINX, or Apache so that they will begin using the updated certificate.

come in the discord for support

**Comment by TreeHD** [comment]
> 

I using browser visit `https://wings.sfo.jamex.me:8080/api/system` 
cert is working well
and due date is correct ,didn't expired

Also from Panel curl to Wings:8080
Isn't return any SSL Error

So.. seems that isn't cert problem?

**Comment by mrxbox98** [comment]
What is the output of running ``wings diagnostics``?

**Comment by QuintenQVD0** [comment]
yea can you post here the wings and panel logs.


Panel: 
tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptero.sh 99

Wings: 
sudo wings diagnostics
@TreeHD

**Comment by DaneEveritt** [comment]
This is not a bug in the software, try restarting your services to make sure things propagate, but otherwise it is outside the control of Pterodactyl how your system handles and responds to certificates.

Especially when it complains that the certificate is expired.

**Comment by TreeHD** [comment]
Got the problem...
Panel side need to run `yum install -y ca-certificates`  to  update system cert
due to Let's Encrypt ROOT Cert expired...

**Comment by duckytutorials** [comment]
Not working tree

**Comment by LIADPRODUCTIONS** [comment]
Use the following command to fix the issue
`sudo ifconfig eth0 mtu 1350`
Or if you are on a modern version of linux that has depreceated the ifconfig command, use this:
`sudo ip link set dev eth0 mtu 1350`

**Comment by matthewpi** [comment]
> Use the following command to fix the issue `sudo ifconfig eth0 mtu 1350` Or if you are on a modern version of linux that has depreceated the ifconfig command, use this: `sudo ip link set dev eth0 mtu 1350`

Changing your network MTU has nothing to do with an expired TLS certificate.

Your issue was caused by a network mis-configuration, nothing to do with this software.
