### ISSUE TITLE
Password Reset feature not working

### ISSUE THREAD

**Issue by Celestialdeath99** [Pterodactyl/Panel#380]
I have been attempting to use the _"I've_ forgotten my _password!"_ feature and once I enter the email address with an account and press enter it brings me to a page that states _"Whoops, looks like something went wrong."_ That is about as much as I know...

System info:
PHP 7.0.18-1+deb.sury.org~xenial+1
4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Pterodactyl Panel 0.6.0-beta.2

**Comment by KasperFranz** [comment]
what does your laravel log say (it is in storage/logs)

**Comment by Celestialdeath99** [comment]
There are no files in that directory

**Comment by DaneEveritt** [comment]
Confirmed issue 👍🏼
