### ISSUE TITLE
 After update to 1.6.6 my variable APP_URL in the .env is not taken into consideration in the Back Office

### ISSUE THREAD

**Issue by steeven-th** [pterodactyl/panel#3806]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Aafter update 1.6.2 to 1.6.6 my variable APP_URL in the .env is not taken into consideration in the Back Office. All links point to the local IP. In front it's Ok.

If I connect with panel.domaine.fr, I have the problem.
If I connect with the public IP, I don't have the problem.
And with local IP, I don't have the problem.

![Capture_decran_2021-12-11_a_15 38 22](https://user-images.githubusercontent.com/82022828/145705140-8679e959-e547-443d-9778-6c936d9654c8.png)

![Capture_decran_2021-12-11_a_15 38 53](https://user-images.githubusercontent.com/82022828/145705141-65a8ac52-3603-4c07-8e29-d0c508989583.png)

### Expected Behavior

The links should all point to the domain name configured in the .env file.

### Steps to Reproduce

Update Panel since 1.6.2 to 1.6.6

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
Wings : https://ptero.co/eqequtekox
I have just this log : https://bin.ptdl.co/upx8z/
```

**Comment by DaneEveritt** [comment]
You either have your config cached (`php artisan config:clear`) or some other configuration issue. Please use the Discord server for further support, I do not believe this is a bug with Pterodactyl.

**Comment by steeven-th** [comment]
I already tried the cache several times without any success (php artisan config:clear)
I redid the update manually following the advice of Discord, still the same problem.
I did not change anything in my configuration between 1.6.2 before the update and 1.6.6
