### ISSUE TITLE
SMTP Test

### ISSUE THREAD

**Issue by MatusBoa** [pterodactyl/panel#3812]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When I try to test settings, it throws exception with

```
An error occurred while attempting to test mail settings: The POST method is not supported for this route. Supported methods: GET, HEAD.
```

### Expected Behavior

Just work

### Steps to Reproduce

Go to Settings > Mail > click on Test button

### Panel Version

1.6.6

### Wings Version

1.5.3

**Comment by danny6167** [comment]
Your theme isn't compatible with the current version of the panel. 
This isn't a bug with pterodactyl.

**Comment by yesBad** [comment]
^^, works for me

**Comment by trenutoo** [comment]
As mentioned above, your code modifications are conflicting and not up to date with the current release. The method has been changed to POST in the 1.6.6 security release.
