### ISSUE TITLE
VNC Accesss

### ISSUE THREAD

**Issue by BasToTheMax** [pterodactyl/panel#3815]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The most people here know the repl.it site. Replit uses docker to containerize the programms and supports VNC Access/Connections. It would be really cool if pterodactyl has this too! (this is very useful for apps with visual screens/windows)

### Describe the solution you'd like.

*I don't know how to implement it, so that is why I made this issue.*

### Additional context to this request.

It would also be nice if you could set a password in the `settings` tab

**Comment by yesBad** [comment]
Isn't the whole point of the panel to replace traditional GUIs....

**Comment by Jelcoo** [comment]
If you want such a thing install virtualizor on your server and enjoy!

**Comment by matthewpi** [comment]
I don't see how VNC would fit into this software or why it would be necessary.  The containers don't support any GUI functionality or graphical rendering and never will officially.  While this may be an interesting suggestion, it will likely never be implemented into this software.

**Comment by BasToTheMax** [comment]
> If you want such a thing install virtualizor on your server and enjoy!

My vps doesn't support virtualisation

**Comment by Jcodeerd** [comment]
Dedicated servers are always an option
