### ISSUE TITLE
Wings turns all uppercase letters in ssl certificate filename to lowercase

### ISSUE THREAD

**Issue by Laikar** [pterodactyl/panel#3816]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

The filename of my ssl certificate and key files contains an uppercase letter, but when staring wings, it complains that it didn't find the certificate file and logs the path all in lowercase.
This is my config
```
    cert: /etc/ssl/certs/domainDotCom_bundle.cer
    key: /etc/ssl/private/domainDotCom_private.key
```
And on the logs this appears
```
wings_1  | FATAL: [Dec 16 17:23:35.324] failed to configure HTTPS server auto_tls=false error=open cert: /etc/ssl/certs/domaindotcom_bundle.cer no such file or directory
wings_1  |
wings_1  | Stacktrace:
wings_1  | open /etc/ssl/certs/domaindotcom_bundle.cer: no such file or directory
wings_1  | github.com/pterodactyl/wings/cmd.rootCmdRun
wings_1  |      github.com/pterodactyl/wings/cmd/root.go:359
wings_1  | github.com/spf13/cobra.(*Command).execute
wings_1  |      github.com/spf13/cobra@v1.2.1/command.go:860
wings_1  | github.com/spf13/cobra.(*Command).ExecuteC
wings_1  |      github.com/spf13/cobra@v1.2.1/command.go:974
wings_1  | github.com/spf13/cobra.(*Command).Execute
wings_1  |      github.com/spf13/cobra@v1.2.1/command.go:902
wings_1  | github.com/pterodactyl/wings/cmd.Execute
wings_1  |      github.com/pterodactyl/wings/cmd/root.go:68
wings_1  | main.main
wings_1  |      ./wings.go:8
wings_1  | runtime.main
wings_1  |      runtime/proc.go:255
wings_1  | runtime.goexit
wings_1  |      runtime/asm_amd64.s:1581

```

### Expected Behavior

if the filename to my ssl certificate contains an uppercase letter, i would expect it to not be turned into lowercase

### Steps to Reproduce

Just have an uppercase letter on the filename of the ssl certificate path

### Panel Version

1.6.6 (i think, running in docker and says its canary)

### Wings Version

1.5.3

**Comment by DaneEveritt** [comment]
@mrxbox98 @TacticalCatto can you two work together to make a single PR combining both your fixes?
