### ISSUE TITLE
Allow hiding the port when showing the allocation alias on server page

### ISSUE THREAD

**Issue by embeddedt** [pterodactyl/panel#3817]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I'm using Pterodactyl privately. I use the alias to show myself the public address a specific allocation maps to. Since I'm using a reverse proxy, the local port number is actually irrelevant for the alias, so it'd be nice to be able to hide it. 

### Describe the solution you'd like.

I see two approaches:

* A global toggle to hide port numbers from allocation aliases.
* A toggle on each allocation that does the same.

### Additional context to this request.

I was able to accomplish this locally by making the following modification [here](https://github.com/pterodactyl/panel/blob/66c56b0da8a69f5ccaf1a0f975fa072b3d0c2487/resources/scripts/components/server/ServerDetailsBlock.tsx#L75):

```diff
-    allocation => (allocation.alias || allocation.ip) + ':' + allocation.port,
+    allocation => (allocation.alias ? allocation.alias : (allocation.ip + ':' + allocation.port)),
```

**Comment by DaneEveritt** [comment]
Thanks for the suggestion but I'm not going to be changing this/supporting it as a configuration option.
