### ISSUE TITLE
JWT validation error from wings: Error Event - jwt: exp claim is invalid

### ISSUE THREAD

**Issue by xMaZax** [pterodactyl/panel#3818]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Hello, after replacing the components on a dedicated server, except SSD/IP. I started getting this error. Can you tell me what the problem is? I tried to get an answer in a discord conversation and try to find a solution, I failed.

`bundle.5cdda223.js:1 JWT validation error from wings: Error Event [b5e8cd69-8f44-4797-9bb1-c0161073a274]: jwt: exp claim is invalid`

### Expected Behavior

Successful connection with the console.

### Steps to Reproduce

https://i.imgur.com/NCtwi7s.png

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash

```

**Comment by mrxbox98** [comment]
Try repasting the node config info and restarting wings.

**Comment by xMaZax** [comment]
> Try repasting the node config info and restarting wings.

I tried to reset daemon configuration file. I also tried to reset the daemon token. It didn't help

**Comment by matthewpi** [comment]
Check that your panel and node servers have the correct time and preferably are set to use the same timezone.

**Comment by xMaZax** [comment]
> Check that your panel and node servers have the correct time and preferably are set to use the same timezone.

Yes, I just tried to fix the time on a dedicated server. It helped after the restart of the car. I corrected the time and also synchronized the hwclock. ) Thanks anyway. 

(У кого такая проблема будет, просто убедитесь что время на вашем сервере корректное и так же в биосе)
(Who will have such a problem, just make sure that the time on your server is correct and also in the bios)

I have met many people who have been in a similar situation, but there were no solutions as such, I hope this will help someone in the future.
