### ISSUE TITLE
[Feature] Frontend validation

### ISSUE THREAD

**Issue by KasperFranz** [pterodactyl/panel#382]
It would be nice if there on server configuration was some frontend validation.

The reasons behind this is if you eg. forget to put in the swap then you have to input alot of the fields again (eg. owner, ports etc.)

another solution on this is to restore the visual part of the server owner, allocations (default and additional), service, option and service pack (all the fields there are using this fancy select box (not a bad thing 😃  )

**Comment by schrej** [comment]
As laravel handles validation really well I personally would keep all of it to the backend. We can try to restore the fields on invalid inputs properly though.

**Comment by MatthewSH** [comment]
@schrej I have the same issue with input. A lot of input is reset. Is this something to do with `redirect()->route()` instead of `redirect()->back()`? I haven't tested this myself. I tend to use `back()` when using validation.

**Comment by DaneEveritt** [comment]
It needs a `withInput()` on the redirect, but even then there are some things that just won't update if they're loaded dynamically.

**Comment by MatthewSH** [comment]
I was assuming `withInput()` was applied, I was really approaching `back()` vs `route()`; I see your point though.

**Comment by DaneEveritt** [comment]
I avoid `->back()` as much as possible, since who knows where the person is actually coming from, plus named routes ensure the user ends up on the correct page. I'm somewhat sure most pages kept the `{{ old('field') }}` placeholders, but I'm sure there a few without it.

**Comment by MatthewSH** [comment]
I'll have to test at some point to see if the fields are resetting on beta and I'll see if the fields shouldn't be resetting.

**Comment by DaneEveritt** [comment]
closed in #1909
