### ISSUE TITLE
Log4J Startup Arguments

### ISSUE THREAD

**Issue by NetlyLLC** [pterodactyl/panel#3820]
### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.

### Current Behavior

On a paper 1.8.8 server, if you download the Log4J Fix XML file from the Minecraft website, and upload it to the server, then add the required arguments to the startup command, the terminal on pterodactyl will say `Loading libraries, please wait...` then, it will stop displaying the terminal. Previous lines will be visible, but no new lines will appear. I do not know much about XML stuff, but I noticed that the XML file has some code about console gui, that I think is causing this issue.
![image](https://user-images.githubusercontent.com/46270991/146626352-a32624c4-2a6a-4227-9043-7f63199be13c.png)
![image](https://user-images.githubusercontent.com/46270991/146626362-f6a5b168-43a9-4e99-9785-14757628be21.png)

Note: The server starts normally, and you can join the server too, but the terminal does not update

### Expected Behavior

When starting the server with the XML file and the correct startup command arguments, the terminal should display all new lines normally, rather than not showing new lines.

### Steps to Reproduce

1. Create a new server on pterodactyl, with the Minecraft nest, and the Paper egg,.
2. Start the server and wait for the necessary files to be created.
3. Stop the server
4. Download the Paper 1.8.8 server jar
5. Replace the server jar that pterodactyl automatically creates, with the Paper 1.8.8 server jar
6. Download the XML file from the Minecraft website. In my case, I will use this one because it is the correct file for my server version
7. Upload the XML file to the /container directory in the server
8. Add the `-Dlog4j.configurationFile=log4j2_17-111.xml` argument to the startup command BEFORE the -jar argument
9. You should notice that the terminal only says "Loading Libraries", then stops showing new lines.

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
Wings: https://ptero.co/lapebikecu
Panel: https://bin.ptdl.co/40w27/
```

**Comment by parkervcp** [comment]
This is working for my servers I host. You need to restart wings.

**Comment by NetlyLLC** [comment]
I have tried rebooting the Node, Panel server, restarting wings, nothing seems to fix it. Please help

**Comment by mrxbox98** [comment]
I have used both XML patches for different versions of MC and I do not have any errors. Is there any large CPU or ram load when its loading libraries?

**Comment by NetlyLLC** [comment]
The CPU goes up to 700%

**Comment by mrxbox98** [comment]
> The CPU goes up to 700%

It is probably just taking some time to load the libraries.

**Comment by deveworld** [comment]
I’m dealing with the same problem.
The same issue happens in regular ssh.

**Comment by NetlyLLC** [comment]
> > The CPU goes up to 700%
> 
> It is probably just taking some time to load the libraries.

I left jt kn overnight and it still didn’t work. I said that the server would start normally and I can join, but I cannot see the console while it is running.

**Comment by DaneEveritt** [comment]
Is there output if you use the `docker logs -f` command on that container?

**Comment by trentonb18** [comment]
Only output in docker logs -f is 
Loading libraries, please wait...

Having the same issue
Restarted wings and still have the issue

**Comment by DaneEveritt** [comment]
Sounds more like an issue with the server itself, and not anything with Pterodactyl.

**Comment by matthewpi** [comment]
If Docker is not outputting any logs, then it is most likely a problem with your server and the log4j config you are using.
