### ISSUE TITLE
Minecraft containers stuck during startup with CPU limit 0 + specific fabric mods

### ISSUE THREAD

**Issue by robert-sokol** [pterodactyl/panel#3822]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

With CPU limit set to 0 for a Fabric 1.18 Minecraft egg container, when trying to start the server with Fabric-Discord link or Disfabric mods enabled server hangs, fails to start and needs to be killed to exit.

Stracing the java process shows repeating "Futex Resumed Etimedout Connection Timed Out" errors.

### Expected Behavior

Minecraft Fabric servers with Fabric-Discord link/ Disfabric should start normally when CPU limit=0.

### Steps to Reproduce

1. Create a new Minecraft server with Fabric egg(latest versions)
2. Leave CPU limit at 0
3. Install Fabric-Discord link with a valid configuration file ( the issue only happens when a valid bot token is added to fdlink.json; for disfabric to disfabric.json5)
4. Start the server: it fails to proceed after fdlink "saving config files" console entry
5. Kill the server and set CPU limit to any percentage.
6. Start the server again and it will start up normally.

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/ubahozalix
```

**Comment by trenutoo** [comment]
This appears to be more of an issue with Java rather than Pterodactyl. It's most likely consuming all the CPU if you check htop or it can't detect your available thread count

**Comment by robert-sokol** [comment]
> This appears to be more of an issue with Java rather than Pterodactyl. It's most likely consuming all the CPU if you check htop or it can't detect your available thread count

Most likely the latter - CPU utilization when the issue happens flatlines at 100% usage(1 core) for ~10-15 seconds, after which it drops to ~0.x%. Closing this issue then, thank you.
