### ISSUE TITLE
API > Create Server On Specific Node ID

### ISSUE THREAD

**Issue by JonathanDroogh** [pterodactyl/panel#3825]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I was wondering if the API could be modified to allow for it to create servers on a specific node.

### Describe the solution you'd like.

The solution I'd like to see would be being able to post something like "node_id": [Node's ID] in the POST API for Create Server as seen here: https://dashflo.net/docs/api/pterodactyl/v1/ (Application > Servers > Create Server).

### Additional context to this request.

I'm making a billing panel that displays current stock (CPU/RAM/Storage available) of Game Servers and which node the client's server will be deploying to before ordering. Right now it doesn't look like I can do this as I can't deploy to a specific node, but instead it just deploys automatically to the first found viable node.

If this is implemented I can store the node's ID in my database and then deploy a server on that specific node that's tied to my billing panel database's node/server list (which manages its own used/max resource limits).

Images of what I mean:
[https://i.gyazo.com/43e86f78f8ec2ef77b514a64f76eedd3.png](https://i.gyazo.com/43e86f78f8ec2ef77b514a64f76eedd3.png)
[https://i.gyazo.com/fb84804e525f993dc8351152fc4db874.png](https://i.gyazo.com/fb84804e525f993dc8351152fc4db874.png)
The highlighted node in this picture is what I'd want to deploy a server on: [https://i.gyazo.com/74067ed34945512706dd6b4702b4b638.png](https://i.gyazo.com/74067ed34945512706dd6b4702b4b638.png)

**Comment by DaneEveritt** [comment]
You can deploy to a specific node by providing a specific allocation rather than asking the API to do that for you.

**Comment by JonathanDroogh** [comment]
> You can deploy to a specific node by providing a specific allocation rather than asking the API to do that for you.

How would I do that exactly, if you don't mind me asking?

For example this is what the API shows for one of the supplied POST values as its example for Create Server:
`  "allocation": {
    "default": 17
  }`

And this is what I can see of some of my allocations: [https://i.gyazo.com/f21b7a942aef02b8cbca70d0cbcca222.png](https://i.gyazo.com/f21b7a942aef02b8cbca70d0cbcca222.png)

I don't see where I'd find the ID that's supplied to the POST field, unless it's the data-id field I can see on the allocation when inspecting the HTML. Alternatively I could just use the API to list the allocations along with their ID. I'm also not sure what the "default" value is for, I'm guessing that just doesn't need to be changed.

Finally, if this works the way I expect it to (creating on a specific node by allocation) then I'd have to manage allocation IDs on top of the node IDs in my own database, and then I'd have to make it check if that specific allocation is available before placing an order as well. Not that that's a problem, I can do it that way, it's just extra steps is all.

**Comment by lstefan1520** [comment]
@xRJx 
You are able to get the allocation ID via database or API. What I would do is search through the allocations for the node, then grab the ID from there.

**Comment by trenutoo** [comment]
>  Alternatively I could just use the API to list the allocations along with their ID. I'm also not sure what the "default" value is for, I'm guessing that just doesn't need to be changed.

Default would be the primary allocation of the server. Each allocation has an ID, which can be fetched using the API. It's not displayed on the admin panel because it's not relevant there.

You can insert your node into its own location should you want to auto-deploy to a specific node without managing the allocations. The node auto-deployment service is based on locations, and not node IDs.
