### ISSUE TITLE
File Manager Editor - BUG

### ISSUE THREAD

**Issue by MrWeyLand** [Pterodactyl/Panel#383]
Hallo when i try to edit a file it breaks the spaces in the file idk. exactly how to describe the problem but i can show a ss. 
![](https://i.gyazo.com/7ac406c218a2fd6c15dc00845a84a418.png)

And its seems like its only does it on windows because in safari it works
OS: Windows 10

**Comment by DaneEveritt** [comment]
Fixed in a307ff4 thanks for your patience!
