### ISSUE TITLE
500 | Server Error

### ISSUE THREAD

**Issue by NONPLAYT** [pterodactyl/panel#3831]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

after installation, I go to the site, and gives an error 500 | server error. I installed everything that was written in the documentation

### Expected Behavior

I expected the usual pterodactyl panel look

### Steps to Reproduce

1. Installed all from documentation
2. Configured all (like pteroq.service and etc.)
3. Visit site
4. Get error 500 | Server Error

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
Panel: https://bin.ptdl.co/nd1gr/
Wings: `/usr/local/bin/wings: 1: /usr/local/bin/wings: ELF���e@@8@��d��dff�O�Q�t�P��UPX!x: not found
/usr/local/bin/wings: 2: /usr/local/bin/wings: 8: not found
/usr/local/bin/wings: 4: /usr/local/bin/wings: Syntax error: ")" unexpected
*//���: not foundngs: 2: /usr/local/bin/wings:`
```

**Comment by gOOvER** [comment]
pls use for Support the Discord Server.

**Comment by trenutoo** [comment]
What is your web servers php and composer version? Your error indicates that it's not within the set requirements listed and installed in the documentation. 

As for wings, you have wrong binary for your cpu architecture. The wings install bash command should download a correct version unless you are on 32-bit or something else than AMD64/ARM64.

**Comment by NONPLAYT** [comment]
> What is your php and composer version?

Comoser 2.2.1
Php 8.0.14

**Comment by trenutoo** [comment]
> > What is your php and composer version?
> 
> Comoser 2.2.1
> Php 8.0.14

Is that your cli php version `php -v` or the php-fpm that the web server is using? Your error looks like the web server is not using php 7.4 or 8.0

**Comment by NONPLAYT** [comment]
> > > What is your php and composer version?
> > 
> > 
> > Comoser 2.2.1
> > Php 8.0.14
> 
> Is that your cli php version `php -v` or the php-fpm that the web server is using? Your error looks like the web server is not using php 7.4 or 8.0

cli

**Comment by NONPLAYT** [comment]
and I cant enable swap
i dont have `grub` file at /etc/default

**Comment by trenutoo** [comment]
> > > > What is your php and composer version?
> > > 
> > > 
> > > Comoser 2.2.1
> > > Php 8.0.14
> > 
> > Is that your cli php version `php -v` or the php-fpm that the web server is using? Your error looks like the web server is not using php 7.4 or 8.0
> 
> cli

Cli version is irrelevant. Your web server should be using 7.4 or 8.0, and from the looks of it it's not.

Most likely you have 7.3 or something a long those lines enabled.  It's not a bug in Pterodactyl. Please use the discord server or discussions for configuration issues.
