### ISSUE TITLE
Option to select if you would like the port exposed to the internet, or locally

### ISSUE THREAD

**Issue by Chronic-Reflexes** [pterodactyl/panel#3834]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

there could be an option where you can select if you would like to expose the port to the internet, or just local to other containers you/the person owns

### Describe the solution you'd like.

When viewing a server's port in the panel via the network tab, there would be options you can select (with checkbox)

A. Expose this port to the internet (Public)

B. Expose this port to other docker containers (Private)

( if B is chosen, open a dropdown and select servers to expose to)

### Additional context to this request.

Implementing this would provide the user a simple way to interact with IPtables, giving them access to a limited firewall

this would be very useful with bungee cord servers in particular and would eliminate most, if not all security issues with running it

**Comment by parkervcp** [comment]
You just assign 127.0.0.1 or 172.18.0.1 to the server to make it a private server.

**Comment by YusufYaser** [comment]
> You just assign 127.0.0.1 or 172.18.0.1 to the server to make it a private server.

That would make it exposed to all docker containers, and not just a specific one.

**Comment by DaneEveritt** [comment]
This is a duplicate/would be addressed by a combination of #1759, #1418, and #1486.

**Comment by Chronic-Reflexes** [comment]
Sorry to bring the closed issue back up up, but i had an idea/problem that can come from this.
In a production setting, wouldn't setting the connection address being local to the machine still leave it open to unwanted containers?

Meaning if someone malicious uses my services, they can attack via that way, because they already have an internal access
i run a side gig with hosting, and also run a minecraft network for my community

The idea was to have it expose to SPESIFIC containers only, and not the entire machine, hence the selection of what server you would want it exposed to in the OG Post

#1759 is about creating a new network per server, which is overkill to the solution, my suggestion was with ports only
#1418 does somewhat reference what i am describing, but looking at it, it kinda looks like slapping a bandaid on it
#1486 also describes their solution being IP based, and is not what i was getting at
