### ISSUE TITLE
CPU and RAM indicators at 0%

### ISSUE THREAD

**Issue by daronhudson** [pterodactyl/panel#3835]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Everything seems to work just fine on the server, it loads and communicates with the node just fine, as does the panel.
For some reason the CPU, Memory and Disk graphs are always 0 or Nan.

I have double checked this with a completely different node with the exact same cloudflare proxy on the SSL connection.

![Untitled](https://user-images.githubusercontent.com/26112933/147796442-431d4b1f-5c18-478b-9315-e47c6747cd6b.png)

### Expected Behavior

The graphs should work as expected like a server that's not proxied through cloudflare

### Steps to Reproduce

Install wings on ubuntu 20.04
configure it to run through cloudflare for the ssl connection with a cloudflare origin certificate on the node and the cloudflare edge certificate on the panel with full(strict) ssl mode on cloudflare
create a server
start the server

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
Wings: https://ptero.co/onogufiwyd
Panel: https://bin.ptdl.co/ipl73/
Game01 can be ignored in the panel log that was from me settings up the second server to double check the problem.
```

**Comment by trenutoo** [comment]
This would rather be an issue with your docker stats not working and not something caused by proxying. See if your docker stats display statistics.

**Comment by daronhudson** [comment]
I’m fairly new to docker how would I check that?

**Comment by trenutoo** [comment]
Type `docker stats`. That's from where the statistics for cpu and memory are retrieved.

Docker stats not working indicates cgroup issue or wrong docker version installed. You want docker-ce and not any snap versions.

**Comment by daronhudson** [comment]
You’re absolutely right it’s returning 0’s. I’ll try out docker-ce and come back!

**Comment by daronhudson** [comment]
It worked! Thank you very much for the quick help.
