### ISSUE TITLE
Allocate Servers on customer ID>server Id, rather than Server ID  

### ISSUE THREAD

**Issue by SuryaRajgor** [pterodactyl/panel#3837]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

current version when I create user EXAMPLE-1 and Allocate 2 or more servers to the same customer even same game or service For Example Minecraft.
Then panel Create Both Different Server ID  But its also Create Different FTP also
If Login From 1 FTP It's limited to 1 container only

### Describe the solution you'd like.

If user-created then Allocate FTP Root folder on his id, not server-id if all server on same IP or node
for example, I have a Minecraft server network with 6 servers (1- bungee, 2-lobby, 1-SMP, 1-bedwars 1-faction)
so I have to open 6 FTP  but it should open in 1

### Additional context to this request.

I use ZAP hosting And here is an example

![aaaaa](https://user-images.githubusercontent.com/9131487/147842635-2a12d3e6-917b-4cc4-850c-a6b17753c7f0.jpg)

**Comment by DaneEveritt** [comment]
While this is a neat idea, I don't want to take on the maintenance of such complexity at this time.
