### ISSUE TITLE
Wrong node Configuration File

### ISSUE THREAD

**Issue by LosBagros** [pterodactyl/panel#3839]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

![image](https://user-images.githubusercontent.com/45005533/147849689-b4a6fc3b-3573-443f-b301-a60b6d898aab.png)
![image](https://user-images.githubusercontent.com/45005533/147849702-4e63ccc1-3c2c-4ce2-9e46-1d991df3e285.png)

### Expected Behavior

in config fille should be  ssl enabled: true

### Steps to Reproduce

I created new node, tried to auto-deploy and it failed because this ssl enabled: false

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/ruqabyqiqo
http://bin.ptdl.co/l5kwv
```

**Comment by danny6167** [comment]
Have you enabled "Behind Proxy"? That will be why SSL gets set to false.
This also doesn't affect the auto-deployment. Please seek support on discord.

**Comment by trenutoo** [comment]
As Danny mentioned above, you enabled behind proxy option, which will disable checking for SSL and leave it up to your reverse proxy to manage it. 

You should reset your daemon token in node settings since you've leaked it.
