### ISSUE TITLE
Squished server console after updating to beta from pre-release 7

### ISSUE THREAD

**Issue by KasperFranz** [Pterodactyl/Panel#384]
reported by ShadowKitten#3809 on discord (doesn't have github)

![](http://image.prntscr.com/image/6a8c8f8a5fc348db8a218ce04841d47e.png)

cleared cache did nothing 

running Chrome on Arch Linux (also tested it on a clean Firefox installation that's never opened the panel before.)

**Comment by KasperFranz** [comment]
From Discord
>Alright, managed to fix it. So during the update you are told to php artisan view:clear, this works as intended. However when you login the console will be broken. If you close all instances of the panel, php artisan view:clear again AFTER you have the update done and have logged in and accessed the consle at least once it fixes it.
Including the pop-out console.
I did not have to clear my browser cache, and doing so did not work originally either.

**Comment by Hwiggy** [comment]
Viable solution exists through running the following commands (in order):
From the panel root:

php artisan down
php artisan view:clear
php artisan up
