### ISSUE TITLE
Set the outgoing IP correctly when using multiple IPs on one node

### ISSUE THREAD

**Issue by schrej** [pterodactyl/panel#3841]
### Describe the feature you would like to see.

By default docker always uses the first interface for outbound traffic. This can lead to issues with self-advertising servers like CS:GO as reported in #459.

### Describe the solution you'd like.

Docker has added support for a new label that allows to set the outbound IP of a docker network: https://github.com/moby/libnetwork/pull/2454

In order to support this we would need to create one docker network per IP address and assign the containers to the correct networks.

### Additional context to this request.

There is a hacky solution [here](https://github.com/pterodactyl/panel/issues/459#issuecomment-1003668331), but since it's now possible we should add support for the official one.

**Comment by parkervcp** [comment]
This can also be used for the server network idea where a server network gets it's own docker network.

**Comment by DaneEveritt** [comment]
Good lord, finally. This seems reasonable to accomplish, although I'll need to do a little more research on it first.

**Comment by HarrisonMayotte** [comment]
Has a PR for this gone out yet? If so, how do we interface with this? Would we need to setup the networks ourself or would Wings handle that for us?

**Comment by trenutoo** [comment]
> Has a PR for this gone out yet? If so, how do we interface with this? Would we need to setup the networks ourself or would Wings handle that for us?

Once it's implemented the issue would be closed.

**Comment by Synkstar** [comment]
Since we are on the topic of networking there is also a problem on source based servers #2062. Like is there anyway you think to get the servers to bind directly on the external ip without host networking or NAT?

**Comment by trenutoo** [comment]
> Since we are on the topic of networking there is also a problem on source based servers #2062. Like is there anyway you think to get the servers to bind directly on the external ip without host networking or NAT? 

This is exactly what this issue is about

**Comment by schrej** [comment]
No, I think those are actually two different issues. Even with this change, the container will still have a local IP that doesn't match the public IP allocated to the server. So CS:GO and other servers that try to detect the IP in use will still detect the wrong address.
I also don't think there is an alternative solution than using host networking.

**Comment by elitetheespeon** [comment]
CSGO doesn't use the given IP passed into +ip (0.0.0.0) to detect real IP - it runs a check against valve servers to determine public IP. Now with the above in mind, this specific issue is so that on a machine with many IPs, the correct IP gets used for outbound traffic inside the container (otherwise ALL IPs used in containers will show the outbound IP as the main IP of the machine.)

**Comment by schrej** [comment]
Ah, yeah, in the mentioned issue it was Gmod. With CS:GO it will probably work fine then. I even mentioned CS in the issue itself :facepalm:

**Comment by Synkstar** [comment]
> No, I think those are actually two different issues. Even with this change, the container will still have a local IP that doesn't match the public IP allocated to the server. So CS:GO and other servers that try to detect the IP in use will still detect the wrong address. I also don't think there is an alternative solution than using host networking.

Yeah these are two separate issues. I'm pretty sure this would still use docker NAT if you implement that and that problem I mentioned before would still be a thing. If your server doesnt crash or restart it wont happen. Only seems to happen if people join right when the server starts within like a minute or something. But it just looks messy. Plus then someone thats ip banned would technically be able to join and you wont know the players ip that joined anymore so you wouldnt be able to ban someone by their ip. Crident servers bind directly to the external ip some how( you can tell this by doing status in console and it will show the same ip twice ). I kind of wonder what they are doing. They probably arent doing host networking so I kind of wonder what they are doing.

**Comment by djzoneporro** [comment]
I have the same problem with a custom bridge but I want to assign static ip's to each docker container and in pterodactyl I can't set --ip. 
Is there a way to assign pterodactyl containers a static ip?
