### ISSUE TITLE
Usage of netmask for databases

### ISSUE THREAD

**Issue by Wunderharke** [pterodactyl/panel#3842]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When creating a new db for an exisiting server only numerical IPv4 adresses and % placeholder are allowed.

### Expected Behavior

Since 5.6 MSQL allows to use netmasks to define subnets from which a use can connect. See the doc [here](https://dev.mysql.com/doc/refman/5.6/en/account-names.html).
This is especially important in combination with non persistent docker-ips e.g. to limit accesse to 172.16.0.0/20 which is not internet routeable.

### Steps to Reproduce

Try to add a new db to any exisiting server using the offical netmask syntax e.g. 172.16.0.0/255.240.0.0 in the "Connections" field.

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
---not applicable---
```

**Comment by trenutoo** [comment]
At this moment, this can be achieved using a wildcard, e.g., 172.18.0.%

The regex to match both ipv4 and netmasks would be interesting. But, unfortunately, I couldn't come up with a reasonable one myself in the 10 minutes I've spent on this.
