### ISSUE TITLE
Ability to easily switch worlds on Bedrock Dedicated Server with button

### ISSUE THREAD

**Issue by Minionguyjpro** [pterodactyl/panel#3847]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Making it possible to easily switch worlds on Bedrock Dedicated Server. It would solve that you everytime have to open up the server.properties, change the level name and switch worlds like that.

### Describe the solution you'd like.

Like adding an button to check the server.properties and worlds folder. And then change the world by clicking on it and then get a list with all available worlds and then choosing the world, and for the last starting the server, and the world is changed. I would like to see it like that. It is the best to add this to the console page i think, to easily change before starting. Underneath the start, restart and stop buttons would be perfect.

### Additional context to this request.

Not really

**Comment by Jelcoo** [comment]
There won't be any egg/game specific feature added to Pterodactyl panel

**Comment by dapillc** [comment]
You can manually add this feature to your Startup Command using Variables.
