### ISSUE TITLE
Hiding server ip

### ISSUE THREAD

**Issue by DEPSTRCZ** [pterodactyl/panel#3848]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Make an feature that will hide the ip(Like in picture) and when u hover on it with mouse it will show the ip.

![image](https://user-images.githubusercontent.com/77269898/148232521-c7284ce3-4d44-48e8-bc41-e185a6df1ccf.png)

### Describe the solution you'd like.

Basicly on hover on ip alias show the ip.

**Comment by Jelcoo** [comment]
Why would this be useful?

**Comment by parkervcp** [comment]
The IP alias is supposed to be something like a display IP for when the external IP is different than the internal server ip.

house external ip -> server internal ip
