### ISSUE TITLE
Deleting a node with servers using API doesn't throws the Exception

### ISSUE THREAD

**Issue by LogischJo** [pterodactyl/panel#3849]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Currently the Nodes deletion api uses this way for throwing the exception in the node deletion service:
`throw new HasActiveServersException($this->translator->trans('exceptions.node.servers_attached'));`

After trying to send a delete request to the correct api endpoint it 500 errors it and shows this in logs:
`[2022-01-05 06:46:47] production.ERROR: Method Illuminate\Translation\Translator::trans does not exist. {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Translation\\Translator::trans does not exist. at /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:103)`

### Expected Behavior

It should just throw an correct Exception like for deleting locations.

### Steps to Reproduce

Send a delete request to the /application/nodes/{nodeID} endpoint while there are servers on the node.

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://pteropaste.com/ki37qh/
```

**Comment by Jelcoo** [comment]
This problem is located in https://github.com/pterodactyl/panel/blob/f973285e04556e08607ba5cd56bb751c29082cf9/app/Services/Nodes/NodeDeletionService.php#L65 and it should also exist in https://github.com/pterodactyl/panel/blob/f973285e04556e08607ba5cd56bb751c29082cf9/app/Services/Users/UserDeletionService.php#L65

**Comment by LogischJo** [comment]
Thanks for fixing it @Software-Noob 👍
