### ISSUE TITLE
Server deletion does not work exactly right

### ISSUE THREAD

**Issue by PadowYT2** [pterodactyl/panel#3853]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When you delete a server **on the panel**, it doesn't delete it in `/var/lib/docker/overlay2/`, just exists there

### Expected Behavior

It should delete the server folder

### Steps to Reproduce

1. Create a server
2. Delete a server
3. See that in `/var/lib/docker/overlay2/` the folder didn't delete

### Panel Version

1.6.6

### Wings Version

1.5.3

**Comment by parkervcp** [comment]
That is a docker issue if it's not deleting overlay layers.

**Comment by PadowYT2** [comment]
So, wings can't do anything about this?
