### ISSUE TITLE
Directory with strange name appears

### ISSUE THREAD

**Issue by Anarchist-byte** [pterodactyl/panel#3855]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

I have 1.6.6 version of panel and 1.5.1 version of Wings.
Maybe 2 weeks ago I mentioned directory with strange name in my server File Manager.
I tried to delete it, but when I refresh the page, it appeared again.
When I try to see this directory, I get error.
You can see pictures I uploaded.
![image](https://user-images.githubusercontent.com/70373707/148421681-352d8b85-84e0-49dd-a6c5-a5d6ac375e12.png)
![image](https://user-images.githubusercontent.com/70373707/148421839-83202ce6-94ee-4319-aac0-e445a3d2848f.png)

### Expected Behavior

I expected this directory will be deleted, but it appeared again when I refreshed the page.

### Steps to Reproduce

I don't know how to actually reproduce it, issue appeared suddenly.

### Panel Version

1.6.6

### Wings Version

1.5.1

**Comment by trenutoo** [comment]
This doesn't provide much information to identify or reproduce this. However, I bet your application is generating it. The panel doesn't create any files of its own will. Most likely it is a lib or save folder.

Check it using your terminal or SFTP and see what's the actual name and contents are to diagnose if it's a panel encoding issue or not.

**Comment by Anarchist-byte** [comment]
It cant be my software. I even tried to fully reinstall server(using Reinstall button) and after reinstall it appeared again.

**Comment by DaneEveritt** [comment]
Pterodactyl does not create files for you like this, it is either the software you're running or something in the specific egg you're using.
