### ISSUE TITLE
Functional for 'Mounts - user mountable'

### ISSUE THREAD

**Issue by Rezanans-wow** [pterodactyl/panel#3857]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I wanna suggest, add a working option.
Because now we have just for view checkbox 'User mountable?'
![Screenshot_509](https://user-images.githubusercontent.com/49691442/148444667-ece9eef9-d6be-4fc7-8005-a52c3cfb7542.png)
 
So, i think the developers know how it work. But if not lol xD
User can YOURSELF Mount a content what specified for game/egg (In control panel, without ADMIN account) → now its only in admin panel, and no sense user mountable or not.
![Screenshot_510](https://user-images.githubusercontent.com/49691442/148444868-69598d32-c5de-4f1f-bc03-3d836f9253be.png)
![Screenshot_511](https://user-images.githubusercontent.com/49691442/148444869-1386557d-3669-4581-b499-676a16acf547.png)

### Describe the solution you'd like.

In any tabs (bottom), maybe in Settings or Startup settings. Where user can mount or unmount content.

**Comment by DaneEveritt** [comment]
We build plenty of things that aren't always directly exposed to the user but exist to allow others to build more advanced functionality on top of.
