### ISSUE TITLE
SQL Database FQDN

### ISSUE THREAD

**Issue by DrLudicrous** [pterodactyl/panel#3861]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

On the database management, you cant use domain to connect to the databases.

There was an error while trying to connect to the host or while executing a query: "SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: update `database_hosts` set `host` = sqlp.gthosting.co.uk, `database_hosts`.`updated_at` = 2022-01-08 01:49:40 where `id` = 7)"

### Expected Behavior

Expected to say its saved and working fine

### Steps to Reproduce

go to "Management > Databases" try to setup a database using a fqdn 

in my instant i setup a subdomain - sql.gthosting.co.uk
I have tried both through cloudflare and without cloudflare

As soon as i setup using ip, it works as expected.

### Panel Version

1.6.6

### Wings Version

1.5

### Error Logs

```bash
http://bin.ptdl.co/he5pp
```

**Comment by broimsuperman** [comment]
same issue as well ^

**Comment by Craftzman7** [comment]
Cannot reproduce. Panel version 1.6.6.

**Comment by FrankSealover** [comment]
(Swift_IoException(code: 0): Connection to tcp://gator4166.hostgator.com:465 Timed Out

This doesn't really indicate anything wrong with the panel, gator4166.hostgator.com (108.167.133.22) resolves fine - you should probably look to see if you can even resolve that hostname

**Comment by DaneEveritt** [comment]
Those error logs are unrelated to the specific error being reported here — those are just mail send errors.

**Comment by DaneEveritt** [comment]
Can't reproduce this.
