### ISSUE TITLE
Renew SSL certificate on bin.ptdl.co

### ISSUE THREAD

**Issue by hinakumo** [pterodactyl/panel#3862]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The SSL certificate has not been updated, which is why an error occurs in the browser when trying to access it to view the uploaded logs.

![2022-01-08_16-51-13](https://user-images.githubusercontent.com/47789168/148646888-503fcfa5-e559-41e6-ae05-e3c8072747f4.png)

### Describe the solution you'd like.

Renew certificate manually or use certbot (with cronjob) for automatic renewal.

**Comment by trenutoo** [comment]
We're aware of it, and it'll be fixed when Dane has time. You can instead use pteropaste.com

`tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc pteropaste.com 99`

EDIT: Certificate has been renewed.
