### ISSUE TITLE
An endpoint to only return unused allocations

### ISSUE THREAD

**Issue by RyderAsKing** [pterodactyl/panel#3872]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Currently: to find a unused allocation we either have to loop through the allocations of the node and find one or create a allocation and obv that would be unused.

Requested: It would also be very nice to have a API that returns a unused allocation.

### Describe the solution you'd like.

Adding either a new endpoint to return only unused allocations or adding a param for the request such as filter[unused] which the users can set to true or false

### Additional context to this request.

This is just better instead of looping through all the allocations yk

**Comment by trenutoo** [comment]
(I don't disagree with this being a reasonable request). Right now [auto deployment ](https://github.com/pterodactyl/panel/blob/develop/app/Services/Deployment/FindViableNodesService.php) can do this for you. It will pick one free available allocation during server creation if that's what you're looking for.

Instead of specifying allocation, you will use deploy

```
    deploy: {
      locations: [1],
      dedicated_ip: false,
      port_range: [],
    },
```

**Comment by matthewpi** [comment]
In v2 (this change could easily be applied to v1) you can get unassigned allocations by using `filter[server_id]=0` in the query parameters with the `/api/application/nodes/{node_id}/allocations` endpoint.  That will filter out any allocations assigned to a server.  If you want just any unassigned allocation without selecting a node, that is not currently possible, but I don't see why you would need to just get a single unassigned allocation.
