### ISSUE TITLE
Can not start Pteroq service 

### ISSUE THREAD

**Issue by rafaelzgz** [pterodactyl/panel#3876]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Pteroq service fails to start. I used the default pteroq.service file except that I delete the **After=redis-server.service** line because I don´t use a local Redis database.

I am using: 
- PHP 8.0
- Ubuntu 21.10
- Lastest packages
- Apache

I should say that I´m running Pterodactyl panel since a lot of months ago, I get this failure after an update (couldn´t remember wich one). I still can access the panel, create, delete and manage servers as I always did. The only problem I notice but don´t know if it´s related is that the panel sometimes takes a lot of time to respond. 

### Expected Behavior

The Pteroq service to start normally.

### Steps to Reproduce

Follow the Panel and Wings gettings started guide. 

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
http://bin.ptdl.co/xreeb

× pteroq.service - Pterodactyl Queue Worker
     Loaded: loaded (/etc/systemd/system/pteroq.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-01-12 12:10:27 CET; 12min ago
    Process: 645821 ExecStart=/usr/bin/php /var/www/pterodactyl/artisan queue:work --queue=high,standard,low --sleep=3 >
   Main PID: 645821 (code=exited, status=1/FAILURE)
        CPU: 156ms

Jan 12 12:10:27 rab-devs.com systemd[1]: pteroq.service: Scheduled restart job, restart counter is at 30.
Jan 12 12:10:27 rab-devs.com systemd[1]: Stopped Pterodactyl Queue Worker.
Jan 12 12:10:27 rab-devs.com systemd[1]: pteroq.service: Start request repeated too quickly.
Jan 12 12:10:27 rab-devs.com systemd[1]: pteroq.service: Failed with result 'exit-code'.
Jan 12 12:10:27 rab-devs.com systemd[1]: Failed to start Pterodactyl Queue Worker.
```

**Comment by DaneEveritt** [comment]
You're missing some dependency, it isn't a bug with this software.

```
Call to undefined function Illuminate\Queue\pcntl_async_signals
```

**Comment by rafaelzgz** [comment]
> You're missing some dependency, it isn't a bug with this software.
> 
> ```
> Call to undefined function Illuminate\Queue\pcntl_async_signals
> ```

Wich one? I executed the install guide step by step and my panel was working before update it. Anything I can do to solve this?

**Comment by rafaelzgz** [comment]
I finally could solve it by comenting line 323 on my php.ini -> disable_functions = ...

**Comment by EVRS** [comment]
> 

where's located php.ini?

**Comment by EVRS** [comment]
> I finally could solve it by comenting line 323 on my php.ini -> disable_functions = ...

Wheres located php.ini file?

**Comment by rafaelzgz** [comment]
> 

The **php.ini** (on ubuntu at least) is on `/etc/php/8.0/{apache2/cli/...}`
