### ISSUE TITLE
A minor but very dangerous bug in files moving

### ISSUE THREAD

**Issue by ShreshthTiwari** [pterodactyl/panel#3878]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

There is a weird bug in the panel. 
If you select 2 or more files and one of them is directory and then try to move them out of the present directory, 
But.. If you by mistake put the location as `.. /` instead of `../`.
It will create a weird problem. 
If you try to open that moved directory now, it will show the content of parent directory and when you try to acces the content, it will show error. 
And all files actually in the directory is lost forever: for a long time. 
XD just lost all my server plugins. 
Please fix it. XD

### Expected Behavior

It should replace ".. /" With "../"
And move the content to parent directory. 

### Steps to Reproduce

Just a small code
I can just show it in js
pathName.replace(".. /", "../");

### Panel Version

1.6.0

### Wings Version

1.5.0

**Comment by parkervcp** [comment]
This would be standard linux behavior. While I get that you lost all your plugins, you should probably use the full path instead of the short hand to be safe.

**Comment by trenutoo** [comment]
The files or directories are not lost. However, the directory or file would be renamed to `'.. '` thus panel can't open it. This will occur for any file, but you can recover it from your machine

**Comment by DaneEveritt** [comment]
I can't stop every user from entering dumb strings.
