### ISSUE TITLE
Monthly bandwidth limit

### ISSUE THREAD

**Issue by BasToTheMax** [pterodactyl/panel#3884]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be cool if you could set a monthly bandwidth limit. And when you reach the limit, the server gets stopped. 

### Describe the solution you'd like.

.

**Comment by DaneEveritt** [comment]
Not interested in implementing such a solution, sorry.

**Comment by BasToTheMax** [comment]
👍
