### ISSUE TITLE
Error in GmodServer

### ISSUE THREAD

**Issue by ItJustFox** [pterodactyl/panel#3885]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

when he actually start he just keep crashing. with the exit code 139.

### Expected Behavior

When after the install of the server using the basic egg for garry's mod server, whe exceped that he will normally start but he just dont want.

### Steps to Reproduce

Go to 'Servers'
Click on 'Server'
Click create a gmod server
Start the Server after the install
Error will show in console.

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://pastebin.com/f3dBG18f
```

**Comment by Jelcoo** [comment]
Sounds like a problem with the egg, not the panel. Please create an issue on https://github.com/parkervcp/eggs

**Comment by ItJustFox** [comment]
No problem, I let you delete this one so (if you can.)

**Comment by parkervcp** [comment]
Garrys mod is a default egg.


> Sounds like a problem with the egg, not the panel. Please create an issue on https://github.com/parkervcp/eggs

Maybe before you go and point people at the wrong place you could check first.

**Comment by ItJustFox** [comment]
@parkervcp if your able to help me find the problem I would be very gratful eh... but I really dont understand why I have it or how fix it :$

**Comment by ItJustFox** [comment]
Ps : Here a little problem steam do not dowload a package 
https://pastebin.com/J7qT2zuQ - 63
