### ISSUE TITLE
Server has started but the status is still not started. 

### ISSUE THREAD

**Issue by xmyoard** [pterodactyl/panel#3888]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Server has started but the status doesn't shows that.
![image](https://user-images.githubusercontent.com/87631878/149657818-ef00ad08-18f8-4cdb-9a84-9e7b37feb3ef.png)

### Expected Behavior

It shd show the status correctly.

### Steps to Reproduce

...

### Panel Version

1.6.6

### Wings Version

1.5

### Error Logs

```bash
No errors.
```

**Comment by gOOvER** [comment]
Use Discord for support. It's not a bug.

https://pterodactyl.io/community/config/eggs/creating_a_custom_egg.html#start-configuration

**Comment by xmyoard** [comment]
okay i agree, but that is for custom egg, I didn't use a custom egg, then what's the problem
thanks for the response.

**Comment by gOOvER** [comment]
> okay i agree, but that is for custom egg, I didn't use a custom egg, then what's the problem thanks for the response.

you never wrote something about, which egg you use. It's not a Bug; use Discord

**Comment by xmyoard** [comment]
I use the paper egg, which is the default egg which is installed when installing pterodactyl.

**Comment by trenutoo** [comment]
Your start configuration for the egg does not match, or your WebSocket connection is not working properly for it to detect anything. E.g. need to refresh for new console logs. In that case, try restarting Wings.

**Comment by matthewpi** [comment]
~~This bug may actually exist, I am able to reproduce it in my dev environment, however I am re-doing the event bus and related code, so it could just be a bug I introduced.~~  It was an issue with my changes, I cannot reproduce this issue.

**Comment by xmyoard** [comment]
> Use Discord for support. It's not a bug.
> 
> https://pterodactyl.io/community/config/eggs/creating_a_custom_egg.html#start-configuration

I just changed the startup config and it was solved, but this shd be solved when it installs, a suggestion.
thanks to all helped.
