### ISSUE TITLE
Can't delete or force delete a failed installed server

### ISSUE THREAD

**Issue by IlPicasso** [Pterodactyl/Panel#389]
As the title says, I tried to install a SA:MP server and failed to do it, and I want to delete it 

It seems that the daemon did delete the files, but it is still on the panel
When I try to delete I get 
Client error: `DELETE http://node8.comugamers.com:8080/servers` resulted in a `403 Forbidden` response: { "error": "You do not have permission to perform that action on the system." }

when I try to force delete I get this 
http://f.cgm.rs/2017-04-17_13-34-00.txt

**Comment by KasperFranz** [comment]
It is fixed in #381 :) 
manually edit that file until it is in a release

**Comment by DaneEveritt** [comment]
#381 does not fix this issue.

**Comment by Hwiggy** [comment]
The overall error may not have been fixed however I believe this particular variant of the issue was fixed by using the fix from #381

**Comment by DaneEveritt** [comment]
Fixed in de923bb and https://github.com/Pterodactyl/Daemon/commit/df180a4a5eef232ab24ffae245669e7212f2af5b

Error should have been a 404 not a 403, so that is fixed in the Daemon, and the panel ignores a 404 and continues with deletion.
