### ISSUE TITLE
Java 17 crash - Minecraft 1.18.1 server 

### ISSUE THREAD

**Issue by 4b75726169736859** [pterodactyl/panel#3893]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Hi,
I have several Minecraft 1.18.1 paper servers but for a few weeks Java 17 crashes (ghcr.io/pterodactyl/yolks:java_17).

The error (problematic frame) is rarely the same with each crash.

To be sure that the problem is not from a plugin I created a new empty server, with only paper 1.18.1 and java 17, the errors continue.

If anyone has an idea where my problem comes from, it would help me a lot
[hs_err_pid1.log](https://github.com/pterodactyl/panel/files/7892900/hs_err_pid1.log)
[hs_err_pid2.log](https://github.com/pterodactyl/panel/files/7892901/hs_err_pid2.log)
[hs_err_pid3.log](https://github.com/pterodactyl/panel/files/7892902/hs_err_pid3.log)
![Capture d’écran 2022-01-18 233152](https://user-images.githubusercontent.com/32509744/150031535-ea552732-ffc6-404f-b5dd-d5b523d2ac6f.png)
.

### Expected Behavior

Java stop crashing

### Steps to Reproduce

Error when I play or very often when restarting the server

### Panel Version

1.6.6

### Wings Version

1.5

### Error Logs

```bash
Wings : https://ptero.co/xipyjajyro
Panel : http://bin.ptdl.co/z5zr3
```

**Comment by DaneEveritt** [comment]
Please use Discord for game specific support.
