### ISSUE TITLE
Pterodactyl Network Routing

### ISSUE THREAD

**Issue by FlaringPhoenix** [pterodactyl/panel#3894]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

I have two servers on the same pterodactyl node and they have two different IPs allocated. I noticed that discord bots were being rate-limited and I originally split the discord bots up into "IP Clusters" to prevent this. EX: 50 bots per ip. But I noticed that the entire node would be rate-limited at the same time. I ran curl on two different pterodactyl servers which have two different IPs allocated and it appears that all outgoing traffic is going through the "main" IP.

Server1 (104.255.230.250:4074)
![image](https://user-images.githubusercontent.com/30889474/150222989-55a18322-0d7b-4280-8fb2-8691815e9f55.png)

Server2 (104.255.230.251:4055)
![image](https://user-images.githubusercontent.com/30889474/150222997-011d3d75-ded4-423e-bea7-4aa706fd5092.png)

### Expected Behavior

I expected the outgoing traffic on both of these servers to be on the different allocated IPs. Maybe pterodactyl wasn't designed to be this way.

### Steps to Reproduce

1. Create two servers on pterodactyl
2. Allocate two different IPs to each one of the individual pterodactyl servers

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
Wings: https://ptero.co/digenyfogo
```

**Comment by matthewpi** [comment]
#3841
