### ISSUE TITLE
Please add upload progress on the coming version :)

### ISSUE THREAD

**Issue by xmyoard** [pterodactyl/panel#3901]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Please add upload progress on the coming version :)

### Describe the solution you'd like.

Just add it :)

**Comment by notAreYouScared** [comment]
If you look at the commits for the v2 branch. You can see it was added 6 months ago to the next major version 
 https://github.com/pterodactyl/panel/commit/c6dccc568d91d95e6b5fa4dcaad4dfd532b6a5f6

**Comment by xmyoard** [comment]
it means that it will come on the "next major version"
right?
