### ISSUE TITLE
"Startup Command" should allow empty (null) value

### ISSUE THREAD

**Issue by Stealthii** [pterodactyl/panel#3905]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Some docker images (provided by game developers or built by the community) include the files required to bootstrap or run the game. The "Install Script" section can be empty, however the "Startup Command" value is required.

In order to use entrypoints, or commands defined by the image when starting a container, this value should allow an empty (null) value to be set.

**Comment by trenutoo** [comment]
This is implemented in V2 https://github.com/pterodactyl/panel/commit/728adfe388941908e1db8f117233b0580a3a26c6, although for different reasons. I personally don't know any eggs that rely on the image itself, sounds like extra steps since the startup is versatile.
