### ISSUE TITLE
Panel in Docker - Certbot auto-renew not working

### ISSUE THREAD

**Issue by tim-van-dijkhuizen** [pterodactyl/panel#3907]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

A little while ago, my panel stopped working due to an expired SSL certificate. I had to recreate the docker container to get it working again. After a quick test, I found out that the renew command fails (inside the container) because it can't bind to port 80. I'm guessing this is the reason auto-renewal isn't working.

### Expected Behavior

The docker image should either use the [Nginx integration](https://eff-certbot.readthedocs.io/en/stable/using.html?highlight=renew#nginx) or [webroot](https://eff-certbot.readthedocs.io/en/stable/using.html?highlight=renew#webroot), so certbot can renew certificates while Nginx is running. This way, SSL certificates get automatically renewed by certbot inside the panel container.

### Steps to Reproduce

Run the panel inside a Docker container using the official image. Leave it running until the certificate expires. You now get an error when visiting the panel from your browser.

### Panel Version

1.7.0

### Wings Version

1.5.5

**Comment by trenutoo** [comment]
It only attempts to renew the certificate when you start the container. There's no schedule at this moment to try and renew it during runtime so this would be a feature request. 

You could right now add `0 23 * * * certbot certonly --webroot -w /app -d example-domain.com -m example@email.com --agree-tos -n` to `/var/spool/cron/crontabs/root`

The port 80 error is because you tried to run the certbot standalone command inside the container while container is using the port.

**Comment by parkervcp** [comment]
I have learned certbot added a `renew` function that just checks for new certs. We can probably add a cron job in to run that every 60 days.

**Comment by trenutoo** [comment]
Issue would still be with port 80 if using standalone temporary web server challenge method. Certbot renew uses the same method that was used to generate it

**Comment by parkervcp** [comment]
I ran mine with `certbot renew --nginx` which worked

**Comment by tim-van-dijkhuizen** [comment]
Pretty sure certbot automatically renews certificates without additional configuration. However, this process fails because the standalone webserver cannot bind to port 80. I think using the Nginx parameter might be enough to fix the issue.

**Comment by parkervcp** [comment]
> certbot automatically renews certificates without additional configuration

You are correct but this needs to be inside the container either way.
