### ISSUE TITLE
Google Analytics doesn't work

### ISSUE THREAD

**Issue by CodeyFree** [pterodactyl/panel#3908]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Google Analytics has not been updated. And is still on the old system.

### Expected Behavior

Google analytics should be updated.

### Steps to Reproduce

Update Google Analytics.

### Panel Version

1.7.0

### Wings Version

N/A

**Comment by notAreYouScared** [comment]
Please look at this issue... https://github.com/pterodactyl/panel/issues/3737

**Comment by trenutoo** [comment]
React-ga doesn't support V4, and in my opinion, it could be removed altogether

**Comment by DaneEveritt** [comment]
> To be honest I just don't care enough about Google and their ridiculous tracking to put any effort into keeping up with their spyware.

A PR removing it would be accepted.

**Comment by KaspianDev** [comment]
I agree, glad it was removed. We should all stay away from spyware.
