### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by WorkWolf2** [pterodactyl/panel#3909]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When you go to delete a server on the panel you get 404 error but the server is deleted

### Expected Behavior

The panel should have gone back to the server page

### Steps to Reproduce

Servers>NameofServer>Delete>safely delete server

### Panel Version

1.7.0

### Wings Version

1.5.0

**Comment by Jelcoo** [comment]
Your wings server is out of date by 6 versions, please update and test again.

**Comment by trenutoo** [comment]
I can't reproduce. Do you have any logs or errors to provide and is your panel without any code modifications?

**Comment by gOOvER** [comment]
i also can't reproduce. works as it should

**Comment by DaneEveritt** [comment]
Can't reproduce.
