### ISSUE TITLE
sqlite

### ISSUE THREAD

**Issue by crombiecrunch** [Pterodactyl/Panel#391]
having some issues with plugins giving the error 

failed to load native library:sqlite-3.14.2.1-432cc383-90c2-43a0-997b-d5891410b001-libsqlite jdbc.so. osinfo: Linux/x86_64

updating sqlite on the node doesnt solve it. 
---------------------

**Comment by parkervcp** [comment]
These are docker containers and thus the base system has nothing to do with it...

**Comment by DaneEveritt** [comment]
Going to need way more information to begin narrowing down this issue to fix it.

**Comment by Hwiggy** [comment]
It could also be noted that FlatronEZ was having a problem with a custom Docker image. I believe it contained SQLite libraries and failed to build a container, however when the SQLite libraries were removed by him, it had no issue. 

FlatronEZ claims to have been using this: https://hastebin.com/yigohihena.nginx

And received this error:
19:15:25.494Z ERROR wings: (HTTP code 400) unexpected - No command specified 
    Error: (HTTP code 400) unexpected - No command specified 
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:239:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:269:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:238:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:214:14)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by DaneEveritt** [comment]
That literally has nothing to do with the issue above.

**Comment by Hwiggy** [comment]
Both involve an error through SQLite which may cause them to be related in the future.

**Comment by DaneEveritt** [comment]
No, that is not anything related. One is clearly a daemon configuration error, the other is clearly a container error.

**Comment by schrej** [comment]
Does the image in question actually have sqlite installed? If not we should add it as it is pretty common for MC server plugins...

**Comment by MatthewSH** [comment]
@schrej I'm not too good with docker, but taking a quick glance through. I'm not seeing it. This would be something useful to add as a lot of plugins have SQLite as an option.
