### ISSUE TITLE
Folder size

### ISSUE THREAD

**Issue by Jelcoo** [pterodactyl/panel#3910]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I'd like to see the size of a folder, just like with files. This could help you determine if for example your logs folder is taking up too much space.

### Describe the solution you'd like.

Could work the same as the file size.

**Comment by DaneEveritt** [comment]
I won't be adding this support. Making sure the host OS doesn't topple over when determining the size of the entire server folder is hard enough, I don't want to add complexity to the code just to track folder sizes.

**Comment by Faboit1** [comment]
please add this though, its realy helpfull.
