### ISSUE TITLE
Wings cpu possible leak

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3911]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

![image](https://user-images.githubusercontent.com/6473565/150799709-58563271-5128-4921-adee-cd916ef9bca9.png)

* After wings restart CPU hovers at about 30% of one core(for about few hours)
* Then suddenly it rises to 100% of one core
* Then in some time rises again to 180% of one core

This was improved by a lot in this issue https://github.com/pterodactyl/panel/issues/3899
however it still persists.

In my opinion it should be cpu leak. Because after wings restart cpu is hovering at about 30% not drastically going up instantly.

I'm attaching .pprof after wings cpu rose 2x times to almost 200% core speed.
https://drive.google.com/file/d/1n7jEkuQrTBlf0Yh8qxrra41iIl61CgQ-/view?usp=sharing

Also I'm attaching .pprof which is fine(wings have been running for quite sime time and cpu usage is normal ~ 30% of the core)
I'm attaching this one so you would have .pprof to compare(when it's normal)
https://drive.google.com/file/d/1DDyY_9Z9I_bK0SeA0BwL6Bnqia_gd-m8/view?usp=sharing

### Expected Behavior

No cpu leak

### Steps to Reproduce

Unfortunately none I only have .pprof but it happens everyday so I can give more info just let me know what to do :)

### Panel Version

1.7.0

### Wings Version

1.5.6

**Comment by BenasPaulikas** [comment]
@DaneEveritt sorry to tag but maybe you had time to look at .pprof ? If yes do you know what's the issue ? Maybe I can do something on my side.

**Comment by DaneEveritt** [comment]
No, I'll get to it when I have time.

**Comment by lemehostcom** [comment]
Some love for this issue would be highly appreciated :+1: :100: :1st_place_medal:

**Comment by BenasPaulikas** [comment]
Some love for this card would be highly appreciated :+1:

**Comment by DaneEveritt** [comment]
@BenasPaulikas do you have `--debug` flag enabled logs for Wings corresponding to the minute before & after the CPU spike?

**Comment by BenasPaulikas** [comment]
@DaneEveritt I forgot already. It's happening every day so I can reproduce with or without --debug. Which one should I do ?

**Comment by DaneEveritt** [comment]
Give me a bit, fixing some debug build stuff so we can get better details.

**Comment by DaneEveritt** [comment]
Ok, @BenasPaulikas I have a new build that fixes nothing with the CPU, but should provide us better debug metrics.

Download the build from: https://github.com/pterodactyl/wings/actions/runs/1769600168

Note that the name is now different, feel free to rename it without the `_debug` suffix, it won't affect anything. To run with profiling, use `--pprof` (no arguments) and not `--profile`. This will spin up a second HTTP server accessible only over localhost, which we can use to selectively dump debug information.

When you begin seeing CPU usage issues, execute the following commands to generate some profiles to look at. Feel free to let it continue running for a bit and then execute them again, having one from the start and near the end would be useful.

```
curl http://localhost:6060/debug/pprof/profile?seconds=30 -o cpu.pprof
```

```
curl http://localhost:6060/debug/pprof/goroutine -o goroutines.pprof
```

**Comment by lemehostcom** [comment]
@DaneEveritt thank you for the build. Didn't took long to reproduce it hehe.

http://168.119.89.117/shit/

**Comment by BenasPaulikas** [comment]
@DaneEveritt thank you for the build. Didn't took long to reproduce it hehe.

http://168.119.89.117/debug/

**Comment by BenasPaulikas** [comment]
I'm also attaching two graphs. 
You can see correlation between sudden wings cpu increase usage and containers(docker* processes) ram increase

![image](https://user-images.githubusercontent.com/6473565/151716916-9239e2f9-eb11-4f38-8434-7e53b184de88.png)
![image](https://user-images.githubusercontent.com/6473565/151716932-38ee30c4-3fd9-4e90-b7f9-88f7681e3765.png)

**Comment by BenasPaulikas** [comment]
http://144.76.57.59/debug <- happened on other server.

**Comment by BenasPaulikas** [comment]
http://144.76.57.59/debug-2xcores second server now using 2x cores for wings(2x sharp increases in cpu usage) 

Let me know if you will need anything else. Thank you a lot.

**Comment by DaneEveritt** [comment]
@BenasPaulikas on the first instance (where http://168.119.89.117/debug/ is located), how many servers are you running? Also, can you provide a set of logs (with `--debug` flag) correlating to a minute before and a minute after the CPU spike starts (I don't need the whole period, it just appears there is a specific event causing it to go off the rails).

**Comment by BenasPaulikas** [comment]
> @BenasPaulikas on the first instance (where http://168.119.89.117/debug/ is located), how many servers are you running?

~3K servers but only ~70 online at a time.

**Comment by BenasPaulikas** [comment]
> Also, can you provide a set of logs

Ok will do. I'm using api and I'm also logging a lot of things in database. Should I focus on something specific maybe websockets/uploads e.t.c. ?

**Comment by DaneEveritt** [comment]
No, based on the volume of servers if you can just provide a few seconds of log on each side of the immediate point at which the CPU spikes that is sufficient.

**Comment by BenasPaulikas** [comment]
Sent logs to your email defined here https://github.com/pterodactyl @DaneEveritt

**Comment by BenasPaulikas** [comment]
After todays debuging session I found out that it was not related to console logging. 
Even with all servers offline cpu was still high. 
New release cut down cpu usage drastically. Let's put this issue on hold till I have more data.

**Comment by BenasPaulikas** [comment]
Newest .pprof with newst wigns version. This issue is same across multiple nodes.

![unknown](https://user-images.githubusercontent.com/6473565/151998261-3d8839ef-3062-435e-9c4e-101aabce9302.png)


https://drive.google.com/file/d/1Yqu3rsTOWdY8FhV9D77hOhFFSeAZiczr/view?usp=sharing

**Comment by BenasPaulikas** [comment]
I'm adding to this card. It might look that it's related to huge output from install container but it's not.

Checked every log file of install container and it's usually less than 0.25MB and few times ~1MB.

I had issue before where if I would delete server while it's still installing/reinstalling I would get cpu spike. But that was fixed by my system already.

I'm out of ideas how to reproduce this. Hopefully someone can help here :)

**Comment by BenasPaulikas** [comment]
![image](https://user-images.githubusercontent.com/6473565/152240163-6823bede-a605-42ba-a261-8fab699353a8.png)

Help would be highly appreciated. I have to restart wings periodically because cpu just spikes up quite often.. And it's never going down.

Would it be possible to implement --debug with --verbose to show each ReadLine call because it doesn't make sense. It's not receiving that many lines from install output.

Sorry for tag but maybe @parkervcp @Software-Noob @DaneEveritt

**Comment by BenasPaulikas** [comment]
Finally reproduced this. Anyone can crash linux servers running wings!

1 server delete while it's being installed = 1x core at 100% :fire: :fire: 
2x server deletes while it's being installed = 2x core usage
and so on :)))

@DaneEveritt @parkervcp @Software-Noob

**Comment by BenasPaulikas** [comment]
Even tho this is reproducable by deleting installing server in my case it's somehow different. But trace is exactly same.

**Comment by BenasPaulikas** [comment]
emotional damage here. No one reads such long issue I'm closing it in favor of https://github.com/pterodactyl/panel/issues/3939

**Comment by parkervcp** [comment]
> No one reads such long issue

Just because there was no response doesn't mean it's not getting worked on. This has been a huge issue that is getting constant debug builds. Along with the power and console issues.

**Comment by BenasPaulikas** [comment]
Woah the future is now. Thank you! Words can't express my gratitude for this fix. Ty a lot ill try this build soon

**Comment by HerrSammyDE** [comment]
Have you had any problems with the latest versions again in the last few months?

We recently updated from Wings version 1.7.2 to the latest version because we were experiencing CPU leaks in the previous version. I hope that updating has fixed the problem. However, if not, what could I do to find a solution?
