### ISSUE TITLE
[bug] Adding an User to a Server automatically adds all the permissions

### ISSUE THREAD

**Issue by IlPicasso** [Pterodactyl/Panel#392]
Hello, I normally give all the permissions for Power Management and Server Management but automatically it gives all permissions

http://f.cgm.rs/chrome_2017-04-17_20-19-36.png

**Comment by DaneEveritt** [comment]
Just checked, its a graphical bug, they can't do anything other than the permissions you first gave. Will fix now.

**Comment by DaneEveritt** [comment]
closed in 205a10c.
