### ISSUE TITLE
wings high cpu usage

### ISSUE THREAD

**Issue by bubobih** [pterodactyl/panel#3920]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

I have high wings usage on dedi. after restart wings its ok some time. then again he start to use extractly 400%.

### Expected Behavior

...

### Steps to Reproduce

...

### Panel Version

latest

### Wings Version

latest

### Error Logs

```bash
https://i.imgur.com/t3Au5z7.jpeg
```

**Comment by trenutoo** [comment]
You've provided no information for this to be a helpful bug report for someone to understand the issue

**Comment by bubobih** [comment]
ok what i need to provide i see only high cpu usage by wings (i assume maybe game console from panel make wings to goes so high).

**Comment by mrxbox98** [comment]
What happens before CPU usage increases? What are the Wings logs?

**Comment by parkervcp** [comment]
#3911 already exists for this issue.

**Comment by BenasPaulikas** [comment]
@bubobih you can run `wings --profiler cpu` wait for cpu to increase a lot. stop wings. And upload .pprof file to https://github.com/pterodactyl/panel/issues/3911

**Comment by BenasPaulikas** [comment]
@bubobih are you using API to manage servers?

**Comment by bubobih** [comment]
> @bubobih are you using API to manage servers?

Yes.

**Comment by bubobih** [comment]
> @bubobih you can run `wings --profiler cpu` wait for cpu to increase a lot. stop wings. And upload .pprof file to #3911

I will try to catch up, currently i set cron to reboot wings every 10min

**Comment by BenasPaulikas** [comment]
@bubobih maybe your CPU rises after you delete server that's still installing ?

**Comment by bubobih** [comment]
> @bubobih maybe your CPU rises after you delete server that's still installing ?

Actualy maybe u are right. in that period we transver some servers to that panel from old one.
