### ISSUE TITLE
Only one line of console output gets printed live

### ISSUE THREAD

**Issue by jellyton255** [pterodactyl/panel#3921]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When a message is printed to the console, only a single line of the full message is being sent to the console. However, if you refresh the page, the full message that was meant to be printed is shown.

### Expected Behavior

The full outputted message is printed into the console, rather than a single line of that message.

### Steps to Reproduce

1. Have anything that doesn't fit in one singular line printed into the console.

To Fix:
1. Refresh the page

### Panel Version

1.7.0

### Wings Version

1.5.6

### Error Logs

```bash
https://ptero.co/opymobisiz

Panel logs not working (tail: cannot open '/var/www/pterodactyl/storage/logs/laravel-2022-01-27.log' for reading: No such file or directory
Use netcat.)
```

**Comment by Prisma501** [comment]
Can confirm behaviour on panel 1.7.0 with wings 1.5.6.

Doing a server version command gives no output:
![image](https://user-images.githubusercontent.com/20812779/151365154-5fdbaf1d-b5ff-44c1-8f5d-c0d6d1f517a5.png)

After a browser refresh:
![image](https://user-images.githubusercontent.com/20812779/151365225-1cb7b3c5-db84-451d-951a-e3aaf1102270.png)

**Comment by Maelep** [comment]
I confirm but, like my reported issue (cf.: https://github.com/pterodactyl/panel/issues/3918 ), restarting wings resolve the one line bug but still bug for multiple lines. But starts to bug again after an amount of time.

**Comment by rafradek** [comment]
I can say it happens to me too, it may print one or more lines, but not all the lines it is supposed to print, until a page refresh

**Comment by NickCloudAT** [comment]
Same issue. I asked on Discord and they said this is meant to be to suppress eggs that spam the console..
This is freaking annoying and should be toggleable.

**Comment by DaneEveritt** [comment]
This was definitely not our intention (in terms of how it is currently working). We're looking into proper fixes while maintaining the performance improvements we were trying to implement.

**Comment by jellyton255** [comment]
I have an update to the issue.

Today, after a certain amount of time, the console will simply not receive any more live logs until a wings restart.

**Comment by DaneEveritt** [comment]
Hi guys, thanks for the report. I was able to narrow this down to some flawed logic when it comes to how data is passed around internally before being sent over the websocket.

If you want to try out the fix, you can manually download the artifact from this build and upload it, replacing your current Wings binary with it.

https://github.com/pterodactyl/wings/actions/runs/1769094167

Thanks. If you prefer to wait it should be released later this evening officially.
