### ISSUE TITLE
Call to undefined method Pterodactyl\Models\User::toVueObject() (View: /var/www/pterodactyl/resources/views/templates/wrapper.blade.php)

### ISSUE THREAD

**Issue by Thomascap** [pterodactyl/panel#3928]
### Current Behavior

I just did a v2 install only I ran into a bugg because the panel doesn't work when you turn on laravel debug mode which shows this error: Call to undefined method Pterodactyl\Models\User::toVueObject() (View: /var/www/pterodactyl/resources/views/templates/wrapper.blade.php).

### Expected Behavior

This error ensures that no page works, this ensures that you can no longer do anything on the panel

### Steps to Reproduce

This problem is very easy to solve by adding a piece of code from earlier versions:

you have to go under public static function getRules() { } 
and add this
/**
 * Return the user model in a format that can be passed over to Vue templates.
 */
 public function toVueObject(): array
{
  return (new Collection($this->toArray()))->except(['id', 'external_id'])->toArray();
}

### Panel Version

2

### Wings Version

 N/A

### Games and/or Eggs Affected

 N/A

### Docker Image

 N/A

### Error Logs

```bash
http://bin.ptdl.co/uf4j7
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jelcoo** [comment]
v2 isn't finished yet, so any error you encounter is not a problem since it will probably be fixed when Mathew continues development
