### ISSUE TITLE
Minecft Paper Scheduler not working.

### ISSUE THREAD

**Issue by NaGeL182** [pterodactyl/panel#3930]
### Current Behavior

Schedules never run, just set on Processing, no matter the amount of task, be it 1 or more. 

### Expected Behavior

That the schedules run successfully, or give back error, or anything.

### Steps to Reproduce

Create a Minecraft Server from an Paper  MC egg. 
change the start up command to

> java -Xms128M -Xmx10240M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dterminal.jline=false -Dterminal.ansi=true -jar {{SERVER_JARFILE}} nogui

Set a schedule with anything(send command, send power action, etc)
wait till the time to run it. 

### Panel Version

1.7.0

### Wings Version

1.6.0

### Games and/or Eggs Affected

Minecraft (paper)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
https://ptero.co/cofigamepe
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
This has nothing to do with paper but your pterodactyl queue worker probably not working properly.

**Comment by NaGeL182** [comment]
Oh for the Love of... i checked everything except the queue worker.
restarting that fixed it thank you.
