### ISSUE TITLE
this issues isn't solved?

### ISSUE THREAD

**Issue by xmyoard** [pterodactyl/panel#3935]
### Current Behavior

![image](https://user-images.githubusercontent.com/87631878/152097278-992f1f14-fa8f-40b8-91c6-191a2dee4312.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/87631878/152097525-3a60751c-ef30-41ec-ba5c-cfca38c09201.png)

### Steps to Reproduce

install wings 1.5.6 and see this thing,

### Panel Version

1.7.7

### Wings Version

1.5.6

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues before opening this issue.
> * [x]  I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.


you didn't look hard enough...

https://github.com/pterodactyl/panel/issues/3903

**Comment by Aadi-mone** [comment]
I am not a linux expert + its not fixed I guess?

**Comment by AV3RG** [comment]
The point is there is an existing issue for this, why are you making another one

**Comment by xmyoard** [comment]
oh right.

**Comment by schrej** [comment]
duplicate
