### ISSUE TITLE
Console gets spammed with ">" characters, if you run a command with the skull emoji

### ISSUE THREAD

**Issue by AngryCarrot789** [pterodactyl/panel#3937]
### Current Behavior

If you run a command with a skull emoji, e.g: `somecommand 💀`, it floods the console with `>` characters, and becomes extremely slow (the stats on the right are fine; cpu updates every second still)

This doesn't happen if you run the server in Intellij or in a normal windows console, it only seems to happen with pterodactyl

Here's what the console looks like:
![image](https://user-images.githubusercontent.com/32274404/152410733-979cdd8f-4d74-404e-bcd8-bb793596a665.png)

And this is another server running in Intellij IDEA (exact same MC version, same java version, etc, but just on my PC):
![image](https://user-images.githubusercontent.com/32274404/152410815-2dec455e-b488-4925-bbd0-39802bccd24c.png)

When i run it in Intellij, it doesn't get spammed. Also, the `server.log` file (on both the server running the panel/wings, and my pc) don't get spammed with anything either

### Expected Behavior

It should process the command normally, like it does with a lot of other characters

### Steps to Reproduce

Simply run any command with the skull emoji in it

### Panel Version

1.6.6

### Wings Version

1.6.6

### Games and/or Eggs Affected

Minecraft (Forge)

### Docker Image

`quay.io/pterodactyl/core:java`

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matteoscaringi** [comment]
I dont have this issue with my forge & Fabric server. ![image](https://user-images.githubusercontent.com/63752298/152412385-f032e66c-b867-41c9-9e34-43087ad24c8a.png)
![image](https://user-images.githubusercontent.com/63752298/152412448-e04ba68d-6661-47a7-9d62-1fc03adb8df6.png)

**Comment by camwhi-te** [comment]
Not having this issue with Forge, seems like it's related to what you're running / what egg you're using.

**Comment by AngryCarrot789** [comment]
It says i'm using the Paper egg, and the, but I setup the server manually (downloading the forge cauldron files, uploading them, etc) (`Skip Egg Install Script` is checked). This is for minecraft 1.6.4 too

**Comment by DaneEveritt** [comment]
I'm not fixing something for such an ancient version of MC.
