### ISSUE TITLE
How to crash any linux server running wings in no time.

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3939]
### Current Behavior

Deleting server while it's installing rises wings cpu usage by one core and it's never going down.

### Expected Behavior

No cpu leak..

![151998261-3d8839ef-3062-435e-9c4e-101aabce9302](https://user-images.githubusercontent.com/6473565/152504084-6b56ff93-2850-47bd-afb5-2f40bc152c1f.png)

https://drive.google.com/file/d/1Yqu3rsTOWdY8FhV9D77hOhFFSeAZiczr/view?usp=sharing
Based on .pprof above it might look that install container is sending a lot of output but it isn't I've checked all installer logs and it's usually <0.25mb with edge cases ~1mb

### Steps to Reproduce

1. Install any server
2. Quickly delete it while it's still installing
3. cpu usage of wings will rise up by 1 core!

### Panel Version

1.7.0

### Wings Version

1.6.0

### Games and/or Eggs Affected

all

### Error Logs

```bash
none.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
So as I am reading this, it's due to you spam installing servers. You could just install a bunch of servers to have this same issue. I don't think deleting them is causing any issues, it's just the installations running.

If anything we should implement a queue for installs that is based on the number of system threads or something.

**Comment by DaneEveritt** [comment]
Duplicate #3911
