### ISSUE TITLE
OOM Killer is set to: "OomKillDisable": null, despite disabled or enabled for the Docker container.

### ISSUE THREAD

**Issue by b-kneisel** [pterodactyl/panel#3943]
### Current Behavior

Since "OomKillDisable" is always set to null instead of true or false, the container will be killed by the OOM Killer in any case.

### Expected Behavior

That "OomKillDisable" is set to true when the OOM Killer is disabled.

### Steps to Reproduce

1. Create a server with OOM Killer disabled
2. Than you can look with docker inspect CONTAINER_NAME on your node for this attribute: "OomKillDisable" (It will always be null)

### Panel Version

1.7

### Wings Version

1.6

### Error Logs

```bash
/
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
Can you provide the output of the `docker info`? This sounds like you are on cgroup V2, which doesn't support it

**Comment by b-kneisel** [comment]
Yes, you are right. It is cgroup2. The big problem here is that servers get into a bootloop when they don't have enough RAM for the startup process.

**Comment by trenutoo** [comment]
> Yes, you are right. It is cgroup2. The big problem here is that servers get into a bootloop when they don't have enough RAM for the startup process.

OOM wouldn't help with the startup. Downgrade to cgroup V1 if you want to have it.

**Comment by b-kneisel** [comment]
Can i limit the restarts after an oom killed server?

**Comment by trenutoo** [comment]
Wings will not attempt to restart a server if it crashes more than once within 60 seconds. These values are also configurable in the wings config.

**Comment by b-kneisel** [comment]
I can't agree with that. One container therefore restarted continuously for one day.

**Comment by trenutoo** [comment]
That's the default Wings behavior, unless you have changed the crash detection config values or disabled the timeout.

**Comment by b-kneisel** [comment]
> 



> Wings will not attempt to restart a server if it crashes more than once within 60 seconds. These values are also configurable in the wings config.

Everything is on the default settings, like you said and yet I have this problem.

**Comment by trenutoo** [comment]
> > 
> 
> 
> 
> > Wings will not attempt to restart a server if it crashes more than once within 60 seconds. These values are also configurable in the wings config.
> 
> Everything is on the default settings, like you said and yet I have this problem.

I can't reproduce this nor is it relevant to oom killer issue. Delete your wings config file and recreate it.

**Comment by b-kneisel** [comment]
But this: 
overhead:
    override: false
    default_multiplier: 1.05

is also valid with cgroup v2, so servers still have a buffer before they are killed?

**Comment by dbunduc** [comment]
> > Yes, you are right. It is cgroup2. The big problem here is that servers get into a bootloop when they don't have enough RAM for the startup process.
> 
> OOM wouldn't help with the startup. Downgrade to cgroup V1 if you want to have it.



im having the same issue, even tho oom kill is disabled, the server process gets killed anyway, how can i downgrade to cgroup v1?

**Comment by flyncodes** [comment]
I am having this problem too. Using `docker container inspect <id>`, OomKillDisable always reports null and thus the container is killed once memory is maxed. Changing oom disabled to enabled/disabled in the panel doesn't change that value.
Using Wings v1.11.13, Docker 28.1.1 on Ubuntu
