### ISSUE TITLE
Disable page scroll while scrolling inside terminal

### ISSUE THREAD

**Issue by HexedHero** [pterodactyl/panel#3945]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Most of the time when you're scrolling up and down the terminal, you'll hit the bottom then annoyingly scroll down the outer page. My suggestion is to disable the outsider scroll while the mouse is scrolling on the terminal.

### Describe the solution you'd like.

Disable the outer page scroll while mouse/scrolling inside of the console/terminal. I found this JSFiddle as an example, not implementation http://jsfiddle.net/milanandfriends/yLk5E/

**Comment by HexedHero** [comment]
Overcomplicated it, you can just add **overscroll-behavior: contain;** to the **xterm-viewport**

**Comment by HexedHero** [comment]
Can be solved with
```
function preventScroll(e){
    e.preventDefault();
    e.stopPropagation();
    return false;
};

document.getElementsByClassName("xterm")[0].addEventListener('wheel', preventScroll);
```

**Comment by DaneEveritt** [comment]
Not interested in adding this behavior.

**Comment by JasonHorkles** [comment]
Now that @matthewpi is in charge of the project, is this something that could be reconsidered? It's a rather annoying thing and I don't see much of a reason _not_ to implement it
