### ISSUE TITLE
Archiving logic problem

### ISSUE THREAD

**Issue by Wepwawetcode** [pterodactyl/panel#3946]
### Current Behavior

Archiving the folder named: "map" doesn't only archive the folder "map" it archives the following folders as well map2, map3, map4, map5, map6, map7, map8, map10, map11

### Expected Behavior

That should only archive the folder called: Map

### Steps to Reproduce

Create the following file structure:

/map/test.txt
/map1/test.txt
/map2/test.txt

Put a file in every folder. For example, a file called test.txt with the content test.

After that archive the folder map,
Download the archive and check its content.
You now see it also archived map, map1, and map2

### Panel Version

1.7.0

### Wings Version

1.5.3

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by HexedHero** [comment]
Can confirm this issue, making a map and map2 folder, archiving map one gives me both.

**Comment by matthewpi** [comment]
<https://github.com/pterodactyl/wings/blob/develop/server/filesystem/archive.go#L133> just needs to append `/` to the end of `p` in the `HasPrefix` check.

**Comment by coco0325** [comment]
The problem still exists with wings 1.7.0.
