### ISSUE TITLE
MySQL creating Databases issue

### ISSUE THREAD

**Issue by IlPicasso** [Pterodactyl/Panel#395]
Since BETA release I have not been able to create new Databases for the servers which in 5.7 worked perfectly. The Message says the user is invalid, however I am completley sure it was valid before upgrading

 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1045] Access denied for user 'Node1'@'ns511015.ip-167-114-103.net' (using password: YES) (SQL: DRO$
Stack trace:
#0 /var/www/MPanel/vend

**Comment by DaneEveritt** [comment]
Are you sure that the user has enough permissions (e.g. `DROP`) to complete the necessary actions. Also, check that logins for `Node1` are allowed from `ns511015.ip-167-114-103.net`, you might have it set to `127.0.0.1` or `localhost`.

This isn't a panel issue, as I've throughly tested it, but rather appears to be a MySQL configuration issue.
