### ISSUE TITLE
Schledules are stuck on processing and dont work

### ISSUE THREAD

**Issue by kFxDaKing** [pterodactyl/panel#3952]
### Current Behavior

My schedules are stuck on processing, they got stuck propably after some update, cant remember exact date.

### Expected Behavior

Make them working again.

### Steps to Reproduce

Create any task, for example restart task for minecraft server.

### Panel Version

1.7.0

### Wings Version

1.6.0

### Games and/or Eggs Affected

every

### Docker Image

every

### Error Logs

```bash
https://ptero.co/rocanynoba

Somehow logs stopped working too, last log i have is from 2022-02-09
root@node1 /etc/pterodactyl # tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99
tail: cannot open '/var/www/pterodactyl/storage/logs/laravel-2022-02-09.log' for reading: No such file or directory

This is the last log i got, its from 2022-02-07 (but everything works, wings is okay, ports are opened, just schedules are stuck)
https://pteropaste.com/a7d806
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jelcoo** [comment]
Please restart your queue driver (`systemctl restart pteroq`)

**Comment by kFxDaKing** [comment]
Thank you it worked.
