### ISSUE TITLE
composer install fail 

### ISSUE THREAD

**Issue by goldeye-xor** [pterodactyl/panel#3953]
### Current Behavior

Bug on install:

# composer install --no-dev --optimize-autoloader

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? 
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires PHP extension ext-mbstring * but it is missing from your system. Install or enable PHP's mbstring extension.
  Problem 2
    - Root composer.json requires PHP extension ext-pdo_mysql * but it is missing from your system. Install or enable PHP's pdo_mysql extension.
  Problem 3
    - Root composer.json requires PHP extension ext-zip * but it is missing from your system. Install or enable PHP's zip extension.
  Problem 4
    - aws/aws-sdk-php is locked to version 3.184.6 and an update of this package was not requested.
    - aws/aws-sdk-php 3.184.6 requires ext-simplexml * -> it is missing from your system. Install or enable PHP's simplexml extension.
  Problem 5
    - hashids/hashids is locked to version 4.1.0 and an update of this package was not requested.
    - hashids/hashids 4.1.0 requires ext-mbstring * -> it is missing from your system. Install or enable PHP's mbstring extension.
  Problem 6
    - laravel/framework is locked to version v8.47.0 and an update of this package was not requested.
    - laravel/framework v8.47.0 requires ext-mbstring * -> it is missing from your system. Install or enable PHP's mbstring extension.
  Problem 7
    - lcobucci/jwt is locked to version 4.1.4 and an update of this package was not requested.
    - lcobucci/jwt 4.1.4 requires ext-mbstring * -> it is missing from your system. Install or enable PHP's mbstring extension.
  Problem 8
    - league/commonmark is locked to version 1.6.4 and an update of this package was not requested.
    - league/commonmark 1.6.4 requires ext-mbstring * -> it is missing from your system. Install or enable PHP's mbstring extension.
  Problem 9
    - s1lentium/iptools is locked to version v1.1.1 and an update of this package was not requested.
    - s1lentium/iptools v1.1.1 requires ext-bcmath * -> it is missing from your system. Install or enable PHP's bcmath extension.
  Problem 10
    - tijsverkoyen/css-to-inline-styles is locked to version 2.2.3 and an update of this package was not requested.
    - tijsverkoyen/css-to-inline-styles 2.2.3 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 11
    - aws/aws-sdk-php 3.184.6 requires ext-simplexml * -> it is missing from your system. Install or enable PHP's simplexml extension.
    - league/flysystem-aws-s3-v3 1.0.29 requires aws/aws-sdk-php ^3.20.0 -> satisfiable by aws/aws-sdk-php[3.184.6].
    - league/flysystem-aws-s3-v3 is locked to version 1.0.29 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.1/cli/php.ini
    - /etc/php/8.1/cli/conf.d/10-opcache.ini
    - /etc/php/8.1/cli/conf.d/10-pdo.ini
    - /etc/php/8.1/cli/conf.d/20-calendar.ini
    - /etc/php/8.1/cli/conf.d/20-ctype.ini
    - /etc/php/8.1/cli/conf.d/20-exif.ini
    - /etc/php/8.1/cli/conf.d/20-ffi.ini
    - /etc/php/8.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.1/cli/conf.d/20-ftp.ini
    - /etc/php/8.1/cli/conf.d/20-gettext.ini
    - /etc/php/8.1/cli/conf.d/20-iconv.ini
    - /etc/php/8.1/cli/conf.d/20-phar.ini
    - /etc/php/8.1/cli/conf.d/20-posix.ini
    - /etc/php/8.1/cli/conf.d/20-readline.ini
    - /etc/php/8.1/cli/conf.d/20-shmop.ini
    - /etc/php/8.1/cli/conf.d/20-sockets.ini
    - /etc/php/8.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.1/cli/conf.d/20-tokenizer.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-mbstring --ignore-platform-req=ext-pdo_mysql --ignore-platform-req=ext-zip --ignore-platform-req=ext-simplexml --ignore-platform-req=ext-mbstring --ignore-platform-req=ext-mbstring --ignore-platform-req=ext-mbstring --ignore-platform-req=ext-mbstring --ignore-platform-req=ext-bcmath --ignore-platform-req=ext-dom --ignore-platform-req=ext-simplexml` to temporarily ignore these required extensions.

### Expected Behavior

panel installation step

### Steps to Reproduce

this commande on Ubuntu 20.04 LTS:
root@server:/var/www/pterodactyl# composer install --no-dev --optimize-autoloader

### Panel Version

1.7

### Wings Version

1.5

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by gOOvER** [comment]
PHP 8.1 is not supported. Switch to PHP 8.0

**Comment by goldeye-xor** [comment]
I followed the doc:
`apt -y install php8.0 php8.0-{cli,gd,mysql,pdo,mbstring,tokenizer,bcmath,xml,fpm,curl,zip} mariadb-server nginx tar unzip git redis-server`

**Comment by gOOvER** [comment]
do a `php -v` on cli

**Comment by goldeye-xor** [comment]
yes...
`PHP 8.1.2 (cli) (built: Jan 24 2022 10:42:33) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies`

how i change ?

**Comment by goldeye-xor** [comment]
> PHP 8.1 is not supported. Switch to PHP 8.0

how i change ?
