### ISSUE TITLE
Loading forever Error: server misbehaving

### ISSUE THREAD

**Issue by Falcn8** [pterodactyl/panel#3955]
### Current Behavior

The stats are gone and everything is loading.
It says, "We're having some trouble connecting to your server, please wait..."
The error I think is this part: `server misbehaving`
Everything including my bots and mc servers are stopped.

### Expected Behavior

It should normally show stats on the main page and should not show loading page for more than 5 minutes.

### Steps to Reproduce

I was normally using Pterodactyl panel.
And then one day, suddenly, when I tried to access files, it said "Something went wrong. Could not establish a connection to the machine running this server. Please try again." 
So I restarted and now on the main page where it shows servers, the stats are gone.
It shows the loading gif instead of stats.
When I click on one of the servers, it says "We're having some trouble connecting to your server, please wait..."
Everything is on loading now.

### Panel Version

1.7.0

### Wings Version

1.5.x

### Error Logs

```bash
`sudo wings --debug`
: [Feb 10 23:31:34.384] failed to load server configurations error=http: request creation failed: Get "https://hexahost.ga/api/remote/servers?page=0&per_page=50": dial tcp: lookup hexahost.ga on 127.0.0.53:53: server misbehaving

Stacktrace:
Get "https://hexahost.ga/api/remote/servers?page=0&per_page=50": dial tcp: lookup hexahost.ga on 127.0.0.53:53: server misbehaving
http: request creation failed
github.com/pterodactyl/wings/remote.(*client).request.func1
        /home/runner/work/wings/wings/remote/http.go:139
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer
        /home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.1/retry.go:55
github.com/cenkalti/backoff/v4.RetryNotify
        /home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.1/retry.go:34
github.com/cenkalti/backoff/v4.Retry
        /home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.1/retry.go:28
github.com/pterodactyl/wings/remote.(*client).request
        /home/runner/work/wings/wings/remote/http.go:133
github.com/pterodactyl/wings/remote.(*client).Get
        /home/runner/work/wings/wings/remote/http.go:78
github.com/pterodactyl/wings/remote.(*client).getServersPaged
        /home/runner/work/wings/wings/remote/servers.go:189
github.com/pterodactyl/wings/remote.(*client).GetServers
        /home/runner/work/wings/wings/remote/servers.go:24
github.com/pterodactyl/wings/server.(*Manager).init
        /home/runner/work/wings/wings/server/manager.go:216
github.com/pterodactyl/wings/server.NewManager
        /home/runner/work/wings/wings/server/manager.go:36
github.com/pterodactyl/wings/cmd.rootCmdRun
        /home/runner/work/wings/wings/cmd/root.go:133
github.com/spf13/cobra.(*Command).execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860
github.com/spf13/cobra.(*Command).ExecuteC
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/pterodactyl/wings/cmd.Execute
        /home/runner/work/wings/wings/cmd/root.go:69
main.main

`sudo wings diagnostics`
https://ptero.co/nojiziwiru

`tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99`
https://bin.ptdl.co/v4gpe/
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
Your DNS is not working properly causing Wings failing to start. Trying to visit the panel itself fails as well, meaning you don't have either the panel or wings reachable. This is not a bug in the software.

**Comment by Clownonymous** [comment]
This is actually a problem. It happens to me frequently out of nowhere.

**Comment by Macinx10** [comment]
Same

**Comment by jz1k** [comment]
Same here, has anyone solved it?

**Comment by T1taniumF0rge** [comment]
same here

**Comment by DoseOfCode** [comment]
still an issue

**Comment by Miko0187** [comment]
same here

**Comment by CandleSuit** [comment]
on the console type:

sudo systemctl restart wings

**Comment by jz1k** [comment]
why am i cc on this?

**Comment by decknamec** [comment]
same here btw

**Comment by Exoticinurs** [comment]
No, for me it's working just fine on pc but not on my mobile. I'm on the same DNS though.
> Your DNS is not working properly causing Wings failing to start. Trying to visit the panel itself fails as well, meaning you don't have either the panel or wings reachable. This is not a bug in the software.

**Comment by DrewWuzHere** [comment]
still an issue

**Comment by DoseOfCode** [comment]
@DrewWuzHere Restarting wings fixes it most of the time for me, worth giving that a go if you haven't already

**Comment by DrewWuzHere** [comment]
> [@DrewWuzHere](https://github.com/DrewWuzHere) Restarting wings fixes it most of the time for me, worth giving that a go if you haven't already

I actually just ended up using pterodactyl in private browsing instead and that works for some reason. Cleared cookies, cache, used both on and off my home network. Private browsing is still the only way to get it to work. Weird, but at least that's one other solution

**Comment by MrDroetsch** [comment]
I had the same issue. Renewing the SSL cert for my node worked for me.
