### ISSUE TITLE
Yarn build workflow

### ISSUE THREAD

**Issue by Jelcoo** [pterodactyl/panel#3956]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I think it is a good idea to create a `yarn build:production` workflow on new pull requests. This would help with large pull requests that can possible cause problems with the UI.

### Describe the solution you'd like.

A new file in .github/workflows called `build.yml` that runs a build process.

**Comment by FoksVHox** [comment]
What would the benefits be of this?

**Comment by Jelcoo** [comment]
> What would the benefits be of this?
It would be a way to verify if something is working on a different machine
