### ISSUE TITLE
500 Internal Server Error @ Server overview

### ISSUE THREAD

**Issue by Hoerli1337** [pterodactyl/panel#3957]
### Current Behavior

On the server overview page I get the error in the red box:
An unexpected error was encountered while processing this request, please try again.

I cannot control the server as a user or administrator.

Everything else seems to work perfectly normal.
(https://panel.domain.com/api/client?page=1)
![grafik](https://user-images.githubusercontent.com/13108516/153716005-47d88582-de7c-4afd-b3e2-cad7b6f42df2.png)

### Expected Behavior

The page should present the overview of the servers so that they can be configured.

### Steps to Reproduce

Webserver: nginx
php: Tested with php7.4 + php8.0

- Cache cleared
- Restarted nginx + php-fpm + server
- Disabled Cloudflare cache and test again

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

-

### Docker Image

-

### Error Logs

```bash
http://bin.ptdl.co/olcm1
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
You should have come to the Discord! : 

![afbeelding](https://user-images.githubusercontent.com/67589015/153716228-9f779825-e319-4a1b-ba88-73746d6fa286.png)

**Comment by Hoerli1337** [comment]
Panel-Server:
- LXC Container
- Debian 10 (64bit)

Wings-Server
- Ubuntu 18.04 @ dedicated Server
- Debian 10 @ VMware

**Comment by QuintenQVD0** [comment]
> Panel-Server:
> 
>     * LXC Container
> 
>     * Debian 10 (64bit)
> 
> 
> Wings-Server
> 
>     * Ubuntu 18.04 @ dedicated Server
> 
>     * Debian 10 @ VMware

read my response above

**Comment by Hoerli1337** [comment]
@QuintenQVD0 Just saw your message when I sent my extended post :D
I'll try your solution.
And no, I don't use Discord.

**Comment by QuintenQVD0** [comment]
> And no, I don't use Discord.

there is a very hand bot there that nows like 95% off the errors and how to fix the errors

**Comment by Hoerli1337** [comment]
Thanks for the quick reply, has helped!

This may well be the case. But do not like Discord and their terms and conditions.
Therefore, here is my solution, which can be indexed by search engines:
`/usr/bin/php8.0 /usr/local/bin/composer install --no-dev --optimize-autoloader`
