### ISSUE TITLE
Bug with schedules.

### ISSUE THREAD

**Issue by ItJustFox** [pterodactyl/panel#3958]
### Current Behavior

When we make a schedules with multiple task in one, (send command + backup + send command) it does only the first after the schedules is keep on "processing" without do anything and we cant do anything.

### Expected Behavior

Make a schedules able to take multiple thing to do in one.

### Steps to Reproduce

- Install the pteropanel in a docker-compose (or in UnraidOS) 
- Install Minecraft server
- make a schedule with multiple thing in 
- run the schedules

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

minecraft

### Docker Image

ccarney16/pterodactyl-panel:latest
ccarney16/pterodactyl-daemon:latest

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
These are not the official images you are using.

**Comment by ItJustFox** [comment]
Eh ? 
Can you give the official so that I can fix it ?

**Comment by parkervcp** [comment]
https://github.com/pterodactyl/development/pkgs/container/development%2Fpanel
https://github.com/pterodactyl/wings/pkgs/container/wings
