### ISSUE TITLE
Failed to acquire exclusive lock for power actions: cannot acquire a lock on the power state: already locked

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [pterodactyl/panel#3959]
### Current Behavior

Server after stopping just dying (Happens only for Minecraft 1.17.1 server. Other servers on same node work fine)
@container@pterodactyl~ Error Event [fd2d6ff4-83b8-415b-ac70-97798e032342]: failed to acquire exclusive lock for power actions: cannot acquire a lock on the power state: already locked - When trying to start server
and at server status:  OFFLINE (1d 4h 50m)

### Expected Behavior

Server not dying

### Steps to Reproduce

Create Minecraft 1.17.1 server and stop it

### Panel Version

1.7

### Wings Version

1.5

### Games and/or Eggs Affected

Minecraft (Paper)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
container@pterodactyl~ Error Event [fd2d6ff4-83b8-415b-ac70-97798e032342]: failed to acquire exclusive lock for power actions: cannot acquire a lock on the power state: already locked
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
update your wings to V 1.6.1
