### ISSUE TITLE
New users are getting no password set link in email

### ISSUE THREAD

**Issue by nechtmarrie** [Pterodactyl/Panel#396]
When creating a new user in the panel (version 0.6.0-beta.2.1)
And leaving the password field empty, the new user should receive a link in the email he is sent to setup his password on the panel

The email contains no password related information or links to set it.
Only the users username and mail address used for his account.

System details below:
Linux vps363217 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.0.18-1+deb.sury.org~xenial+1 (cli) (built: Apr 11 2017 14:36:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-1+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies

Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 9
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 109
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-71-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.611 GiB
Name: vps363217
ID: A57S:ARHM:RV52:G7LT:32NT:URQL:TR3L:GVWA:FU4D:ILVU:3OQI:4QM4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by DaneEveritt** [comment]
This issue is fixed as of 1c37a8fe1a396416cdb8dfae736734bc5de277aa.

If you assign a password for an account they will not receive a link, so if you want them to get one, don't set a password.
