### ISSUE TITLE
Banned from the Discord server for *example* domain link to show how HTTPS/SSL should look like in the config.

### ISSUE THREAD

**Issue by NWEmil** [pterodactyl/panel#3960]
Username: Emilelele#8853

### Current Behavior

Maybe not have a permanent ban on links but just removal of the post?

### Expected Behavior

Didn't expect to be banned for being helpful. Haha!

### Steps to Reproduce

Have two links or something in your message.

I used links such as;
thepaneldomainname.xxx
and
thewingsdomainname.xxx

**Comment by TrixterTheTux** [comment]
I've unbanned you. The bot gets trigger-happy with `.xxx` TLD due to being associated with porn.
