### ISSUE TITLE
pls support windows localhost support

### ISSUE THREAD

**Issue by Bubbelwubbel** [pterodactyl/panel#3961]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would also be good if you could run this panel completely on Windows, you could try it, it would work somehow, but it would be very difficult. It would be good if you had direct Windows support

### Describe the solution you'd like.

yes idk Stop that you can run it on Windows.

**Comment by nikrozman21** [comment]
You can already do that using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install)

**Comment by Bubbelwubbel** [comment]
thx
