### ISSUE TITLE
S3 scheduled backup are producing broken backup state and ValidationException

### ISSUE THREAD

**Issue by realkarmakun** [pterodactyl/panel#3964]
### Current Behavior

Sometimes if you try to backup using S3 it can result in never completed backup, that would be marked as FAILED after a while.
wings logs returns following exception:
```
Feb 14 00:08:54 ns3186259 wings[502773]: DEBUG: [Feb 14 00:08:54.991] making request to external HTTP endpoint endpoint=https://panel.rustme.ru/api/remote/backups/208a934b-aba8-4799-91ab-e3706542a217 headers=map>Feb 14 00:08:55 ns3186259 wings[502773]:  INFO: [Feb 14 00:08:55.117] failed to notify panel of successful backup state error=Error response from Panel: ValidationException: The successful field is required. (HT>Feb 14 00:08:55 ns3186259 wings[502773]: Stacktrace:
Feb 14 00:08:55 ns3186259 wings[502773]: Error response from Panel: ValidationException: The successful field is required. (HTTP/422)
Feb 14 00:08:55 ns3186259 wings[502773]: github.com/pterodactyl/wings/server.(*Server).notifyPanelOfBackup
Feb 14 00:08:55 ns3186259 wings[502773]:         /home/runner/work/wings/wings/server/backup.go:31
Feb 14 00:08:55 ns3186259 wings[502773]: github.com/pterodactyl/wings/server.(*Server).Backup
Feb 14 00:08:55 ns3186259 wings[502773]:         /home/runner/work/wings/wings/server/backup.go:95
Feb 14 00:08:55 ns3186259 wings[502773]: github.com/pterodactyl/wings/router.postServerBackup.func1
Feb 14 00:08:55 ns3186259 wings[502773]:         /home/runner/work/wings/wings/router/router_server_backup.go:51
Feb 14 00:08:55 ns3186259 wings[502773]: runtime.goexit
Feb 14 00:08:55 ns3186259 wings[502773]:         /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581
```
I must note that manual backups are working fine. Also there is around 25 servers creating backups at the same time (not on the same wings instance though). It can be contributing to the issue. Also we use OVH S3 compatible Object Storage 

### Expected Behavior

Expect for backup to go as normal.

### Steps to Reproduce

Setup a schedule with Backup Action and make it run on some time Run Now doesn't seem to be affected by the issue. 
I wasn't able to reproduce this consistently, though we've been experiencing it for last 2 days. We have 25 servers backup up at the same time. 

### Panel Version

1.7.0

### Wings Version

1.6.1

### Error Logs

```bash
https://ptero.co/texykivake.sql
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by realkarmakun** [comment]
Okay I wasn't looking for existing issues good enough: This is duplicate of https://github.com/pterodactyl/panel/issues/3334
Can it be reopened please?

**Comment by DaneEveritt** [comment]
I don't know what to do for this issue — it isn't consistently reproducible and does not make sense given the code that exists on both Wings and the Panel. Given that _every_ person who runs into this is using CloudFlare I'm inclined to believe it is an issue with the proxy which isn't correctly passing the data through, or is mutilating the data for some reason.

Therefore, I'm closing it as I do not believe it would be a fruitful effort on my part to look into it more.
