### ISSUE TITLE
Artisan Migrating Error.

### ISSUE THREAD

**Issue by Hugytor09YT** [pterodactyl/panel#3965]
### Current Behavior

I dont liked some theme on pterodactyl, y correctly removed it, and i wanted to install another one, when migrating the database it show that error and dont does it.

### Expected Behavior

PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1443
Stack trace:
#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(13): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/pterodactyl/vendor/composer/ClassLoader.php(571): include('...')
#2 /var/www/pterodactyl/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(15): Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(89): collect()
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\Foundation\PackageManifest->config()
#6 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#7 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap()
#8 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith()
#9 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\Foundation\Console\Kernel->bootstrap()
#10 /var/www/pterodactyl/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#11 {main} in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/Collection.php on line 13
PHP Fatal error:  Uncaught Error: Class "Illuminate\Support\Collection" not found in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/helpers.php:15
Stack trace:
#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Traits/ReflectsClosures.php(24): collect()
#1 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Traits/ReflectsClosures.php(44): Illuminate\Foundation\Exceptions\ReportableHandler->closureParameterTypes()
#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/ReportableHandler.php(62): Illuminate\Foundation\Exceptions\ReportableHandler->firstClosureParameterType()
#3 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(234): Illuminate\Foundation\Exceptions\ReportableHandler->handles()
#4 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(88): Illuminate\Foundation\Exceptions\Handler->report()
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(130): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#6 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#7 {main}
  thrown in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Collections/helpers.php on line 15

### Steps to Reproduce

Migrate the Artisan Database.

### Panel Version

1.7.0

### Wings Version

N/A

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
.log | nc bin.ptdl.co 99

http://bin.ptdl.co/nmodv
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by FoksVHox** [comment]
I'm unable to reproduce this error. By the looks of the stack trace you put in the issue, it could be that you didn't fully let composer install the dependencies needed.

**Comment by trenutoo** [comment]
PHP 8.1 is not supported yet, which is why your artisan is not working.
