### ISSUE TITLE
no way to disable audit_log.

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#3967]
### Current Behavior

no way to disable audit_log. I have too many MB there

### Expected Behavior

be able to disable audit_log.

### Steps to Reproduce

Use panel for a long time heavily. Space grows there fast.

### Panel Version

latestx

### Wings Version

latest

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
I am not interested in adding functionality to trim or disable the audit logging. I'd recommend evaluating your personal needs for the table and creating a script that can be periodically executed to trim it down.

**Comment by BenasPaulikas** [comment]
Ok I can do with my own script thank you. Is it okay to completely wipe that table ? It isn't holding any critical data right ?
