### ISSUE TITLE
Assign a new allocation to an existing server with api

### ISSUE THREAD

**Issue by blankflo** [pterodactyl/panel#3968]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hi, 
I'm actually trying ton assign a new allocation to an existing server with ptero's api and i do not find any solutions.

The only way to do it is to delete the server and create a new  one with new allocation ? 

An example : Server1 is created and assigned with allocation on panel, i want to update build with api request to assign an new port (allocation) which is already available on the server's ip.

Ty in advance for any solutions ! 

Florian

### Describe the solution you'd like.

Assign new allocation with a build api request.

**Comment by trenutoo** [comment]
This is not a feature request and instead asks for support, which the Discord server and Discussions tab is for.
 
PATCH /api/application/servers/{server_id}/build

You can PATCH the server build to assign additional allocations and delete the primary one. To only change the primary allocation without deletion, you specify the ID in the allocation. The primary allocation can only be changed if there are other allocations assigned. [Here is the update request file.](https://github.com/pterodactyl/panel/blob/develop/app/Http/Requests/Api/Application/Servers/UpdateServerBuildConfigurationRequest.php)
 
 ```--data-raw '{
  "allocation": 2,
  "memory": 0,
  "swap": 0,
  "disk": 0,
  "io": 500,
  "cpu": 0,
  "threads": null,
  "feature_limits": {
    "databases": 5,
    "allocations": 5,
    "backups": 5
  },
  "add_allocations": ["3"],
  "remove_allocations": ["2"]
}'
```

This was also explained in #3657
