### ISSUE TITLE
Panel is not showing CPU and RAM usage

### ISSUE THREAD

**Issue by r4sas** [pterodactyl/panel#3969]
### Current Behavior

After updating to version 1.7.0 and wings to 1.6.1, panel stopped returning CPU and RAM usage.

### Expected Behavior

Correcty reporting CPU and RAM usage

### Steps to Reproduce

Use latest version of panel and wings.

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

Custom: HLDS (CS 1.6)

### Docker Image

ghcr.io/parkervcp/games:source (modified, see https://github.com/parkervcp/yolks/issues/13)

### Error Logs

No logs (even with APP_DEBUG=true). I can't gather any logs, so I tried to find any information in browser's developer console, and only thing which I found was API output:

> /api/client/servers/<id>/resources
```
attributes: {
  current_state: "running"
  is_suspended: false
  resources: {
    cpu_absolute: 0
    disk_bytes: 3710000111
    memory_bytes: 0
    network_rx_bytes: 0
    network_tx_bytes: 0
    uptime: 164374268
  }
  object: "stats"
}
```

As you can see, some resources returned as 0.

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
Please check the status of `docker stats`

If that is reporting 0, you will need to reinstall `docker-ce` via the official docker repo.

**Comment by r4sas** [comment]
That's strange, because everything work till yesterday. Thanks for a hint, I'll try to reinstall it.

**Comment by r4sas** [comment]
Looks like reinstall and reboot make things. Closing.
