### ISSUE TITLE
Start Issue daemon

### ISSUE THREAD

**Issue by DavidBrockway** [Pterodactyl/Panel#397]
Please describe your issue in full below. Include what products are affected, as well as what version(s) you are running. Please also include information about your system, such as `uname -a` and `php -v` and `docker info` if applicable.

If you're just making a suggestion, be descriptive, and link to any issues that might be releated as well.

You can delete from this line up.
---------------------

root@vps125492:~# npm run configure -- --panel-url https://mcpanel.vipercloudhosting.co.uk --token 2XXUMwYvyjJQanaqsLtq1V0CRS3kp9S9
npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "configure" "--" "--panel-url" "https://mcpanel.vipercloudhosting.co.uk" "--token" "2XXUMwYvyjJQanaqsLtq1V0CRS3kp9S9"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'configure',
1 verbose cli   '--',
1 verbose cli   '--panel-url',
1 verbose cli   'https://mcpanel.vipercloudhosting.co.uk',
1 verbose cli   '--token',
1 verbose cli   '2XXUMwYvyjJQanaqsLtq1V0CRS3kp9S9' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/root/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /root
7 error Linux 4.4.0-72-generic
8 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "configure" "--" "--panel-url" "https://mcpanel.vipercloudhosting.co.uk" "--token" "2XXUMwYvyjJQanaqsLtq1V0CRS3kp9S9"
9 error node v6.10.2

**Comment by parkervcp** [comment]
It looks like you are trying to start the daemon from /root/ folder and the usual install location is /srv/daemon/

**Comment by DavidBrockway** [comment]
Thank you
