### ISSUE TITLE
Can't connect through SMTP to Roundcube/cPanel webmail.

### ISSUE THREAD

**Issue by itsfranciscooli** [pterodactyl/panel#3970]
### Current Behavior

It doesn't connect
This is the error that the pterodactyl reports: 
An error occurred while attempting to test mail settings: Connection to tcp://mail.franciscooliveira.me:465 Timed Out
Can you help me ?

### Expected Behavior

Send email successfully 

### Steps to Reproduce

Set everything as reported by my cpanel websmail

### Panel Version

1.7.0

### Wings Version

1.5.5

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
This is not a bug in the software. As it informs you in the template, please use Discord or discussions for configuration issues.

You most likely have the port closed or using wrong encryption type.
