### ISSUE TITLE
Backups are not transferred on server transfer. 

### ISSUE THREAD

**Issue by snaildos** [pterodactyl/panel#3972]
### Current Behavior

Currently when transferring the server, backups will not get migrated to the new node and will still exist on the old node. 

### Expected Behavior

That the backup gets transferred, and the old one gets deleted.

### Steps to Reproduce

1. Transfer server with a backup
2. Download backup (wont work)

### Panel Version

1.4.0

### Wings Version

1.4.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
Please see issue #2623
