### ISSUE TITLE
starting more server at once on power up

### ISSUE THREAD

**Issue by 1Euro7Cent** [pterodactyl/panel#3975]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I just had a power outage for a few seconds. I was playing with my friends on one of the servers. The wings started up, but it is taking forever to start that one server back up.

It seems like wings is only starting one server at once. My suggestion would be to start multiple servers at once.

### Describe the solution you'd like.

I would think of in a value in the config. And start multiple servers within that amount.

Maybe also something like a check to start as many servers at once to not let the CPU go over some percent value

**Comment by parkervcp** [comment]
Starting too many servers all at once can cause the host to crash. starting them one at a time reduces that risk.

**Comment by DaneEveritt** [comment]
It starts 4 servers at a time, I'm not interested in changing that behavior. If you want your server to start back faster I'd recommend just opening the Panel and clicking 'Start' for that specific instance, it'll skip over the queue and move on.
