### ISSUE TITLE
cant login when 2fa is enabled

### ISSUE THREAD

**Issue by MCorange99** [pterodactyl/panel#3977]
### Current Behavior

cant login when 2fa is enabled

### Expected Behavior

i should be able to login to the panel with 2fa

### Steps to Reproduce

use firefox
run arch linux
use 2fa
try to login to panel
fail

i dont run the servers, im just a user

### Panel Version

unknown

### Wings Version

unknown

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
This is mostly a useless issue to open. You should contact whom ever is your hosting company.
