### ISSUE TITLE
Things i've installed (eggs) dont work

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [pterodactyl/panel#3978]
### Current Behavior

Things (Mindustry, Haste-server) not starting

### Expected Behavior

Mindustry and Haste-server start working

### Steps to Reproduce

Download egg from Parker's repo
Put it into panel
Create server
Start server

### Panel Version

1.7

### Wings Version

1.6.1

### Games and/or Eggs Affected

Mindustry, Haste-server

### Docker Image

quay.io/parkervcp/pterodactyl-images:debian_openjdk-11 (Mindustry), quay.io/parkervcp/pterodactyl-images:debian_nodejs-12 (Haste-server)

### Error Logs

```bash
standard_init_linux.go:228: exec user process caused: exec format error
(Same on both)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
This is not a bug in the panel software. The egg repo is a separate project, and the images are not built to support your cpu architecture, which I assume is ARM64.

You can replace them with newer multiarch [Yolks](https://github.com/pterodactyl/yolks) images or open an issue on the egg repo to do so.
