### ISSUE TITLE
Setting another Username in Containers

### ISSUE THREAD

**Issue by theredcmdcraft** [pterodactyl/panel#3979]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I think it would be nice to change the Container`s Username. At this Time the Username is fixed set to "container". I tried to run an custom satisfactory server (building own image, published it on Dockerhub, and created a new egg). If i will use the Docker Image without pterodactyl, it will be working without any problems. If i am using it with the pterodactyl panel, i will got an error, because the user that the image is using, must be root, so if i could change the user for the container in the egg, this issue would be solved, and i can run my satisfactory server.

### Describe the solution you'd like.

- Add an field "Container User" to the page: /admin/nests/egg/new
- I think a default value "container" will made it more userfriendlier.

**Comment by DaneEveritt** [comment]
Is this #3830?

**Comment by theredcmdcraft** [comment]
Yeah this is it.

**Comment by DaneEveritt** [comment]
Closing this in favor of that issue then, feel free to add context to that issue if you feel it needs anything more. :)
