### ISSUE TITLE
PocketMine Support?

### ISSUE THREAD

**Issue by DavidBrockway** [Pterodactyl/Panel#398]
Is it possible this software can support pocketmine, how do you upload custom jar files?

**Comment by schrej** [comment]
You can just upload custom jar files using sftp or the file manager.

**Comment by DavidBrockway** [comment]
where would you upload it / pockketmine is php7 and a .phar

**Comment by Hwiggy** [comment]
The support team in the pterodactyl discord might be able to help you.

**Comment by DaneEveritt** [comment]
Please use the [forums](https://forums.pterodactyl.io) or [Discord](https://pterodactyl.io/discord) for help with this.
