### ISSUE TITLE
Location option has no selected attribute after saving changes to a node

### ISSUE THREAD

**Issue by JRH-1997** [pterodactyl/panel#3980]
### Current Behavior

After saving changes to a node, it reloads the page, but after the reload the location is not selected anymore, because no option has the selected attribute anymore. 
![image](https://user-images.githubusercontent.com/65117490/154852960-112fc805-42cf-455e-9ff2-e8e298600845.png)

When you save this page again because you changed something else without looking to this field, you will save that the node is on the first location in the list. This causes that your nodes are on wrong locations. 

### Expected Behavior

The correct location to be selected after saving changes to a node. 

### Steps to Reproduce

Click the save button on the settings page of a node and wait until the page is reloaded. 
Then look to the locationlist, 

### Panel Version

1.7.0

### Wings Version

1.6.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Won't fix as V2 is far along and changes all of this.
