### ISSUE TITLE
Wings didnt work with cloudflare under attack mode (using cloudflare ssl port of wing 8443)

### ISSUE THREAD

**Issue by JAY200625** [pterodactyl/panel#3981]
### Current Behavior

when the cloudflare under attack mod is enable wings get down i also whitelisted ips of wings but same

### Expected Behavior

if i enter url of wings with http:// then it shows ( Client sent an HTTP request to an HTTPS server.)

### Steps to Reproduce

if i enter url of wings with https:// then it shows ( {"error":"The required authorization heads were not present in the request."}

### Panel Version

1.7.0

### Wings Version

1.6.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jelcoo** [comment]
Go to the nodes page and open the console page, what error is displayed?

**Comment by trenutoo** [comment]
You have provided no logs for anyone to assist. Sounds like you didn't whitelist the correct origin, which is not a bug in the software.
