### ISSUE TITLE
Restarting servers on the node several times a day

### ISSUE THREAD

**Issue by AndreyEremin02** [pterodactyl/panel#3983]
### Current Behavior

Several times a day, all servers located on the node start restarting due to this error.

### Expected Behavior

The absence of such random crashes and reboots.

### Steps to Reproduce

After installation, the error is reproduced automatically, several times a day.

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

counter-strike: global offensive

### Docker Image

ghcr.io/pterodactyl/games:source

### Error Logs

```bash
Wings - https://ptero.co/oqigebelog
Panel - http://bin.ptdl.co/4asy1
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Mutex21** [comment]
Check the ram & swap ram usage. I reverted back on 1.5.3 wings and now is fine. With default kernel or custom like xanmod recompiled, the results are the same. Wings 1.6.1 cause for me a lot of problems with srcds servers (half-life | counter-strike 1.6)), assuming the swap memory increase to 100% (memory leak). I tested on 3 gaming dedicated servers with the different docker versions, but the same version wings (1.6.1) and that's happened. With the 1.6.1 wings, a lot of ram/swap ram are allocated and with each hour increasing and when the swap usage is 100%, the docker is restarting with the same situation as yours. 

![memory](https://user-images.githubusercontent.com/63129033/155469910-3296ff05-82bd-4b5d-b98d-264b4201df1c.png)

**Comment by DaneEveritt** [comment]
Did you consider opening a bug report since that is _not_ intentional behavior, and in fact the default for 99% of users on 1.6.1 has been a significant _decrease_ in memory and CPU usage.

Please don't blindly encourage people to downgrade, it rolls back important security and performance fixes and a single user and graph are hardly conclusive indicators of an issue. We also provide profiling tools rather than just looking at a graph that only shows your system using swap.

**Comment by DaneEveritt** [comment]
There is no information in this bug report that is actionable, therefore I am closing it.
