### ISSUE TITLE
In the config category of en egg it's impossible to put an array to a yaml file

### ISSUE THREAD

**Issue by NhProGamer** [pterodactyl/panel#3985]
### Current Behavior

In the config category of en egg it's impossible to put an array to a yaml file
Wings just stop to give informations, wings just freeze

### Expected Behavior

json config:
"general-config.server.flags.list": ["Xms128M", "Xmx{{server.build.memory}}M"]

to yaml file:
general-config:
      server:
                flags:
                        list:
                        - Xms128M
                        - Xmx2048M
(2048 is correctly parsed but after start the server wings just freeze and the list is not created)

### Steps to Reproduce

create an egg and in the config category try something like this:
{
    "server.properties": {
        "parser": "properties",
        "find": {
            "server-ip": "0.0.0.0",
            "server-port": "{{server.build.default.port}}",
            "query.port": "{{server.build.default.port}}"
        }
    },
    "autoplug/backup-config.yml": {
        "parser": "yaml",
        "find": {
            "backup-config.enable": "false"
        }
    },
    "autoplug/general-config.yml": {
        "parser": "yaml",
        "find": {
            "general-config.server.key": "NO_KEY",
            "general-config.server.flags.list": ["Xms128M", "Xmx{{server.build.memory}}M"]
        }
    },
    "autoplug/updater-config.yml": {
        "parser": "yaml",
        "find": {
            "updater-config.java-updater.enable": "false",
            "updater-config.server-updater.enable": "true",
            "updater-config.server-updater.profile": "AUTOMATIC",
            "updater-config.server-updater.software": "paper",
            "updater-config.server-updater.version": "1.9.4",
            "updater-config.plugin-updater.enable": "true"
        }
    }
}

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

Personal egg

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
https://ptero.co/alyxicyvob
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by paTaNiNho** [comment]
Still present in **1.8.1**.
I'm not able to find and replace _json list_ (bounded by characters `[` `]`). It will finish by an error:
`production.ERROR: __clone method called on non-object {"exception":"[object] (Error(code: 0): __clone method called on non-object at /var/www/pterodactyl/app/Services/Eggs/EggConfigurationService.php:246)`

What I'm trying to replace:
```
{
    "ProjectZomboid64.json": {
        "parser": "json",
        "find": {
            "vmArgs": [
                "-Djava.awt.headless=true",
                "-Xmx{{server.build.memory}}m",
                "-Dzomboid.steam=1",
                "-Dzomboid.znetlog=1",
                "-Djava.library.path=linux64/:natives/",
                "-Djava.security.egd=file:/dev/urandom",
                "-XX:+UseZGC",
                "-XX:-OmitStackTraceInFastThrow"
            ]
        }
    }
}
```

Is there any changes with this bug? Thank you...

**Comment by paTaNiNho** [comment]
@matthewpi Thank you for your fix!
I tried to use it to my example. There is no any error, but the result looks like:
`"vmArgs": "\u003cinvalid\u003e"`

May I ask where this fix was verified? Thank you...

> Still present in **1.8.1**. I'm not able to find and replace _json list_ (bounded by characters `[` `]`). It will finish by an error: `production.ERROR: __clone method called on non-object {"exception":"[object] (Error(code: 0): __clone method called on non-object at /var/www/pterodactyl/app/Services/Eggs/EggConfigurationService.php:246)`
> 
> What I'm trying to replace:
> 
> ```
> {
>     "ProjectZomboid64.json": {
>         "parser": "json",
>         "find": {
>             "vmArgs": [
>                 "-Djava.awt.headless=true",
>                 "-Xmx{{server.build.memory}}m",
>                 "-Dzomboid.steam=1",
>                 "-Dzomboid.znetlog=1",
>                 "-Djava.library.path=linux64/:natives/",
>                 "-Djava.security.egd=file:/dev/urandom",
>                 "-XX:+UseZGC",
>                 "-XX:-OmitStackTraceInFastThrow"
>             ]
>         }
>     }
> }
> ```
> 
> Is there any changes with this bug? Thank you...

**Comment by paTaNiNho** [comment]
@matthewpi please... ☝️
