### ISSUE TITLE
There was an error while trying to connect to the host or while executing a query: "SQLSTATE[HY000] [2002] Connection refused (SQL: SELECT 1 FROM dual)"

### ISSUE THREAD

**Issue by haroldrc** [pterodactyl/panel#3986]
### Current Behavior

There was an error while trying to connect to the host or while executing a query: "SQLSTATE[HY000] [2002] Connection refused (SQL: SELECT 1 FROM dual)"

### Expected Behavior

creating the database

### Steps to Reproduce

create the DB from the panel

### Panel Version

1.7.0

### Wings Version

i dont know

### Games and/or Eggs Affected

minecraft (paper)

### Docker Image

java_17

### Error Logs

```bash
https://ptero.co/iluxyvobyr

https://bin.ptdl.co/40zqj/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
Connection refused is generally thrown when your sql server doesn't let your user sign in. Have you checked the sql logs too.

The wings logs are not helpful in this context.
