### ISSUE TITLE
Custom docker labels

### ISSUE THREAD

**Issue by AveryanAlex** [pterodactyl/panel#3987]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add support for specifying docker labels.
Fox example, I need to add com.centurylinklabs.watchtower.enable: "false" to disable watchtower on Pterodacyl managed servers

### Describe the solution you'd like.

Add config option for wings

**Comment by DaneEveritt** [comment]
Dupe #3100
