### ISSUE TITLE
Discard requests for server information in server list after selecting a server

### ISSUE THREAD

**Issue by rafradek** [pterodactyl/panel#3989]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Before the user can access a server in the server list, all requests for server information must be processed beforehand. This can produce a several seconds long delay when having multiple server nodes and some of them are offline. 

### Describe the solution you'd like.

When a user selects a server from the server list, it does not wait until all other servers are queried, it just goes into server page immediately

**Comment by DaneEveritt** [comment]
This sounds like a bug, not a feature request. There is nothing that should be stopping your navigation.

**Comment by parkervcp** [comment]
probably the cause behind #3936 honestly.

**Comment by OpenSource03** [comment]
> This sounds like a bug, not a feature request. There is nothing that should be stopping your navigation.

That's right. This is a bug, I'd say. If you have, for instance, 25 servers on one page, you'll not be able to refresh the page or proceed to the server until all getserverstats promises are fulfilled.
