### ISSUE TITLE
OAuth2 OIDC authentication

### ISSUE THREAD

**Issue by dorianim** [pterodactyl/panel#3990]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be nice to have OAuth2/Open ID connect authentication. It is supported by many providers and would simplify the signup process for many people (like me) who run a central identity provider like [authentik](https://goauthentik.io).

### Describe the solution you'd like.

An option to integrate OIDC

### Additional context to this request.

PR: #3774

Following up on:
- #594
- #2635

**Comment by Jelcoo** [comment]
Is already an open pr

**Comment by DaneEveritt** [comment]
I don't have the time or energy to look at implementing such functionality right now. In the interest of not leaving a PR danging that is realistically never going to be accomplished, I am closing this out.

**Comment by dbcaa** [comment]
Is this ever gonna be worked on I know you didnt have the energy then but do you now?

@DaneEveritt

**Comment by mempler** [comment]
> Is this ever gonna be worked on I know you didnt have the energy then but do you now?
> 
> @DaneEveritt 

Pelican has support for oidc, one of the reasons why i decided to switch

**Comment by dbcaa** [comment]
> > Is this ever gonna be worked on I know you didnt have the energy then but do you now?
> > 
> > @DaneEveritt 
> 
> Pelican has support for oidc, one of the reasons why i decided to switch

I love pelican and use it for my personal stuff but for my business install I use ptero since peli isnt 1.00 yet

**Comment by DaneEveritt** [comment]
Please see [this post](https://github.com/pterodactyl/panel/issues/5491) — the issue tracker is not the appropriate place for discussion regarding new feature anymore.
