### ISSUE TITLE
pteroq.service - Pterodactyl Queue Worker

### ISSUE THREAD

**Issue by IvensDias** [pterodactyl/panel#4001]
### Current Behavior

failed

### Expected Behavior

running

### Steps to Reproduce

systemctl status pteroq

### Panel Version

1.4.0

### Wings Version

1.4.2

### Games and/or Eggs Affected

Minecraft paper

### Docker Image

java 17

### Error Logs

```bash
https://pteropaste.com/ixor4b/

● pteroq.service - Pterodactyl Queue Worker
     Loaded: loaded (/etc/systemd/system/pteroq.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2022-03-12 23:12:32 -03; 45s ago
    Process: 229953 ExecStart=/usr/bin/php /var/www/pterodactyl/artisan queue:work --queue=high,sta>
   Main PID: 229953 (code=exited, status=255/EXCEPTION)

Mar 12 23:12:32 RedeLotus systemd[1]: pteroq.service: Scheduled restart job, restart counter is at >
Mar 12 23:12:32 RedeLotus systemd[1]: Stopped Pterodactyl Queue Worker.
Mar 12 23:12:32 RedeLotus systemd[1]: pteroq.service: Start request repeated too quickly.
Mar 12 23:12:32 RedeLotus systemd[1]: pteroq.service: Failed with result 'exit-code'.
Mar 12 23:12:32 RedeLotus systemd[1]: Failed to start Pterodactyl Queue Worker.

sorry if it doesn't open right, but the bot doesn't answer me this was my last hope
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by IvensDias** [comment]
I've been searching for 2 hours and I can't find it.

**Comment by parkervcp** [comment]
You are super out of date.

**Comment by IvensDias** [comment]
I don't remember the version so I put any

**Comment by IvensDias** [comment]
Unit service.service could not be found.
● pteroq.service - Pterodactyl Queue Worker
     Loaded: loaded (/etc/systemd/system/pteroq.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2022-03-12 23:55:04 -03; 1s ago
    Process: 231427 ExecStart=/usr/bin/php /var/www/pterodactyl/artisan queue:work --queue=high,sta>
   Main PID: 231427 (code=exited, status=255/EXCEPTION)
