### ISSUE TITLE
Disable processing scheduled tasks when server is suspended

### ISSUE THREAD

**Issue by argonaut-network** [pterodactyl/panel#4008]
### Current Behavior

When suspended, servers still process all scheduled actions, e.g. backups

### Expected Behavior

Suspended servers should consume no resources, this includes scheduled tasks like backups

### Steps to Reproduce

1. Create server with scheduled action such as a backup
2. Suspend server
3. Watch scheduled actions continue to be processed

### Panel Version

Container sha256:ec3aef332d56f5a6f1a7cbc51ef74dabc1da01dba8a24d509a2c91569bb57fc4

### Wings Version

Container sha256:55c91cadc818fe3263f648e2b6c4a531021561e2f0088142b5c6ac4669bdcbe1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Thanks, looks like we've never correctly checked if the server the schedule belongs to is suspended or not — surprised it took this long for someone to say anything.
