### ISSUE TITLE
Scrollbar in Console

### ISSUE THREAD

**Issue by JustinPooters** [pterodactyl/panel#4009]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Might be related to https://github.com/pterodactyl/panel/issues/3945

when a lot of errors are in the console, It's quite hard to scroll thru all of them.

### Describe the solution you'd like.

Add an option to bring back the console scrollbar. Possibly as a setting.

**Comment by notAreYouScared** [comment]
I don't think this is related to the the issue you mentioned... as you're asking to bring the scroll bar back... but it was never removed?

![Screenshot_20220318-153031_Chrome](https://user-images.githubusercontent.com/1757840/159071784-621bf60f-9f83-4265-b255-1832663c5c6e.jpg)

**Comment by matteoscaringi** [comment]
There litterally is a scrollbar for the console already.

**Comment by JustinPooters** [comment]
No panel has it on windows. 12 people i know found this issue

**Comment by notAreYouScared** [comment]
> No panel has it on windows. 12 people i know found this issue

![image](https://user-images.githubusercontent.com/1757840/159077445-fd93cc7c-6bbb-4c85-9d32-f5e970b0a0ba.png)


Are you using a third party theme?
