### ISSUE TITLE
API problem to create a server (403 error)

### ISSUE THREAD

**Issue by savalet** [pterodactyl/panel#4012]
### Current Behavior

Hello I have a problem with the API of my panel pterodactyl. When I want to interact with it, for example by creating a server, I get a 403 error: 
![image](https://user-images.githubusercontent.com/73446695/159132379-b6219baa-c9d8-441d-8bb5-31c3ee5fbcdb.png)

### Expected Behavior

That the API of my panel create well the server without worries.

### Steps to Reproduce

Use this code: 
![image](https://user-images.githubusercontent.com/73446695/159132556-670e44d0-ff69-4535-bc97-2408bd18107f.png)

### Panel Version

1.6.5

### Wings Version

1.6.1

### Games and/or Eggs Affected

Minecraft All

### Docker Image

quay.io/pterodactyl/core:java

### Error Logs

```bash
https://bin.ptdl.co/6fopz/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by yesBad** [comment]
Sounds like wrong API key :P

**Comment by savalet** [comment]
I didn't think so but recreating an api key partly solved the problem now I have this error: 
![image](https://user-images.githubusercontent.com/73446695/159132708-2ac94cd9-78d7-4812-8aba-aab3a29f96c7.png)

**Comment by Jelcoo** [comment]
You should remove the cookie header and replace `API KEY` inside Authorisation with your api key

**Comment by savalet** [comment]
I put my API key and I also removed the header cookie but I still have the same error.

**Comment by parkervcp** [comment]
You replace `API TOKEN` in your authorization header with the api token you got from the panel.

**Comment by savalet** [comment]
Yes I did:
![image](https://user-images.githubusercontent.com/73446695/159133023-6b43a0b7-48b3-4eff-a4ad-40a73bfc07a7.png)

**Comment by parkervcp** [comment]
a 422 is still you sending an invalid request to the panel. You are sending data it doesn't accept.

**Comment by savalet** [comment]
Ok but how do I fix this problem that it would be bad data? Here is the body that I send : 
![image](https://user-images.githubusercontent.com/73446695/159133223-cd7bec7a-a122-4155-82a8-543fcc6ae5ee.png)

**Comment by savalet** [comment]
Do you have an example?

**Comment by savalet** [comment]
I have found the problems ! Thank you for the helping. =)
![image](https://user-images.githubusercontent.com/73446695/159136132-96248784-74b0-4a87-8a69-d91c2977e748.png)
