### ISSUE TITLE
Panel not showing CPU or RAM

### ISSUE THREAD

**Issue by Artucuno** [pterodactyl/panel#4019]
### Current Behavior

Not showing CPU or Ram Usage for Docker. I have looked at the other issues related to this but have had no luck.

### Expected Behavior

Show CPU and Ram

### Steps to Reproduce

.

### Panel Version

1.7.0

### Wings Version

1.6.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
What host OS are you running? This has been an issue on Ubuntu hosts as they are upgraded as seen here https://github.com/pterodactyl/panel/issues/3999

**Comment by DaneEveritt** [comment]
<img width="1265" alt="Screen Shot 2022-03-22 at 08 19 36" src="https://user-images.githubusercontent.com/418376/159480512-1fb73257-2aac-4783-b3b4-2eb4e09686a2.png">

**Comment by WavingCatDevs** [comment]
> <img alt="Screen Shot 2022-03-22 at 08 19 36" width="1265" src="https://user-images.githubusercontent.com/418376/159480512-1fb73257-2aac-4783-b3b4-2eb4e09686a2.png">

ew github light theme

**Comment by GH05TYPLAYz** [comment]
same is happening with me with ubuntu 20.04 LTS

**Comment by WavingCatDevs** [comment]
> same is happening with me with ubuntu 20.04 LTS

#3999

**Comment by ShreshthTiwari** [comment]
https://github.com/pterodactyl/panel/issues/3999#issuecomment-1065855097
