### ISSUE TITLE
Add Pterodactyl Panel to SMTP Google secure apps

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/panel#4020]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Please make it so that Googel sees the pterodactyl panel as SMTP Secure Apps. Because otherwise Google SMTP can be used in the panel only until May 30, 2022.

### Describe the solution you'd like.

On this Site you can see the date: https://support.google.com/accounts/answer/6010255?p=less-secure-apps&hl=en&visit_id=637835737515039523-3318676108&rd=1#zippy=

I have to toggle this to On, to work with the Pterodactyl Panel: https://i.imgur.com/mXVgCLX.png

**Comment by WavingCatDevs** [comment]
I don't think its possible to add pterodactyl as a secure app, I'm not sure what lots of SMTP based things are going to do though.

**Comment by DaneEveritt** [comment]
Just use an app password, as is said in the link you provided? Otherwise I don't care to investigate this, seeing as there are plenty of other services to handle transactional email sending that are better supported.
