### ISSUE TITLE
Panel ram and cpu usage not working. 

### ISSUE THREAD

**Issue by Darkside247** [pterodactyl/panel#4021]
### Current Behavior

so the pannel, cpu and ram stopped displaying i know there is a fix regarding this issue, we followed the steps but we still seem to be having issues.  

### Expected Behavior

![pannel](https://user-images.githubusercontent.com/74486290/159739757-c6e40e4b-8866-45ab-a1b5-35fe9f562ce5.png)

this is a photo of the error 

### Steps to Reproduce

no idea, just started happening 

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

Minecraft, Minecraft modded 

### Docker Image

java 17 and java 16 

### Error Logs

```bash
no errors
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jelcoo** [comment]
See issue #3999 for a fix

**Comment by Darkside247** [comment]
We have done this "Fix" and the issue is still happening.

**Comment by Darkside247** [comment]
nether myself or my hosting company can figure it out, so i would please love some support on the issue as i am currently operating my servers blind
