### ISSUE TITLE
Send password reset email fails but test email works

### ISSUE THREAD

**Issue by diamkil** [pterodactyl/panel#4024]
### Current Behavior

When someone tries to reset their password the task fails in pteroq (when I click test on the mail page it works though)

### Expected Behavior

It sends the email correctly (obviously the email works since I receive it when I do test)

### Steps to Reproduce

Setup SMTP
Use the test button to verify it works
Try doing password reset and it doesn't send the mail

### Panel Version

1.7.0

### Wings Version

1.6.1

### Error Logs

```bash
https://bin.ptdl.co/ppt0o/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TrixterTheTux** [comment]
You need to restart pteroq after updating the SMTP details due to it caching the configuration on start.

**Comment by diamkil** [comment]
I did, multiple time.
I just tried it again and it failed again

**Comment by DaneEveritt** [comment]
Pull the error log for the failed email sending from the `failed_jobs` table. There should be a column with the error, otherwise it seems like an issue with your job queue not properly being restarted and continuing to use an older config.

The test email uses the exact same logic, there is no reason the queued ones would fail while the test works unless your queue is using a completely different environment or hasn't been restarted.

**Comment by diamkil** [comment]
> Pull the error log for the failed email sending from the `failed_jobs` table. There should be a column with the error, otherwise it seems like an issue with your job queue not properly being restarted and continuing to use an older config.
> 
> 
> 
> The test email uses the exact same logic, there is no reason the queued ones would fail while the test works unless your queue is using a completely different environment or hasn't been restarted.

Unfortunately it's more complicated then "you didn't restart pteroq". As I've stated, I did restart it. Every other pterodactyl email still sends properly, only the reset password fails. I'll be able to get the exact error when I get on the computer
