### ISSUE TITLE
incompatible versions of dependencies

### ISSUE THREAD

**Issue by VozDeOuro** [pterodactyl/panel#4028]
### Current Behavior

when i try to open a server console or the server list i got this error 
![Screenshot_1](https://user-images.githubusercontent.com/36045463/160486621-22a05577-d467-44eb-a831-a684fc5cb091.jpg)

possible solution 
i saw in league/fractal: 0.20 was added a type array for default includes, and on version 0.19.1 and i haven't saw that.
![Transformes abstract](https://user-images.githubusercontent.com/36045463/160487296-a64d4c42-3db2-4b61-87c3-9962e5a5947a.jpg)

in this namespace **(Pterodactyl\Transformers\Api\Client)** i didn't saw that.
![Screenshot_3](https://user-images.githubusercontent.com/36045463/160487584-4c64bccc-39ae-4f13-8f4c-e6beb955a6eb.jpg)

just the dependencies 
![update](https://user-images.githubusercontent.com/36045463/160487602-c853ad2c-0a78-4552-877c-2076260a0425.jpg)
 

### Expected Behavior

appears console and server list 

### Steps to Reproduce

a fresh install 

### Panel Version

1.7.0

### Wings Version

1.6.1

### Error Logs

```bash
wings : https://ptero.co/okysarowip
painel : https://bin.ptdl.co/f4nno/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Don't run `composer update` — our dependencies are already locked to compatible versions.

**Comment by trenutoo** [comment]
The existing `composer.lock` ensures the correct dependencies are installed. Attempt to manually upgrade the dependencies or add new ones would be in the area of "you're on your own" and potentially cause compatibility issues, which is **not** a bug in this software.

Revert your dependencies and composer files back, or specify `array` for all `availableIncludes` if you really want to upgrade.
