### ISSUE TITLE
Console is hard to use on mobile

### ISSUE THREAD

**Issue by schrej** [pterodactyl/panel#403]
Using the Webconsole on mobile (on iOS as well as Android) is difficult.
Once you close the keyboard it's hard/impossible to reopen.

Also it would be nice when the console switches into full screen as long as the console is open to make it easier to use.

**Comment by Derkades** [comment]
This seems to be fixed now with the new console

**Comment by schrej** [comment]
I'd still keep it as there is room for enhancement, e.g larger touch targets etc.
