### ISSUE TITLE
Completely containerized panel

### ISSUE THREAD

**Issue by RedstoneWizard08** [pterodactyl/panel#4030]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A version of Pterodactyl and Wings that is completely containerized with Docker.

### Describe the solution you'd like.

This version could be started with a container or docker-compose, but it has to include Wings, the Panel (using NGINX as a web server), and a database. All of this must be able to be persistent using Docker volumes. I am already working on a system for this, and it is pretty much working, except Wings will error every so often.

### Additional context to this request.

Here's the repo for my current solution: https://github.com/RedstoneWizard08/Pterodocker

**Comment by trenutoo** [comment]
This already exists. You can find the docker compose file in the panel and wings repositories.

**Comment by RedstoneWizard08** [comment]
oh ok.
