### ISSUE TITLE
Allow selfassigned TLS certificate for mail

### ISSUE THREAD

**Issue by lue30499** [pterodactyl/panel#4031]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to use a local mail server I use for notifications. It works with my truenas system. However it has a self assigned cert and gets the error below. I cbf to add a cert as I would need to change my networks domain to have a valid tld.

<img width="482" alt="Screen Shot 2022-04-02 at 6 05 00 am" src="https://user-images.githubusercontent.com/63104612/161326485-f46982a4-5d41-41fb-a2bf-d25370b9654f.png">

### Describe the solution you'd like.

A check box or something that allows for openssl to ignore certificate check.

**Comment by DaneEveritt** [comment]
If Laravel doesn't support it out of the box with the configuration file there isn't much I'm going to do about it. If they do support it, you can probably just pull those config values over to your own instance.

You could also update your local certificate trust store to accept that self-signed one as valid.
