### ISSUE TITLE
Problems distributing resources

### ISSUE THREAD

**Issue by kooomax** [pterodactyl/panel#4032]
### Current Behavior

The latest version of docker is unstable in some games
I have a counter-strike server and this problem always occurs to me

![image](https://user-images.githubusercontent.com/34810975/161388098-4755d344-498f-4976-aa14-68bd9a673938.png)

### Expected Behavior

I thought the problem was with the server
but its from docker 

### Steps to Reproduce

I searched for more reasons for this problem
I found that it might be from the server files and every day every day i disable my plugin and wait until the server is become full and check
I run server in cmd line direct on server I found the server is only used 4%-6% cpu and empty 

And when the server is running from the panel and is empty there is no players, it is used 40% and 50% from cpu

### Panel Version

7.4

### Wings Version

1.6.1

### Games and/or Eggs Affected

cs 1.6

### Docker Image

quay.io/pterodactyl/core:source

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
There is no actionable information or request in this issue.
