### ISSUE TITLE
Schedules not working

### ISSUE THREAD

**Issue by Koyorice** [pterodactyl/panel#4036]
### Current Behavior

The schedule doesn't work, the last run time is never unless I press run now

My schedule screenshot:
![Screenshot_2022-04-05-11-44-11-490_com android chrome](https://user-images.githubusercontent.com/87787929/161674692-2d406e38-c3b6-4bb4-95c6-26a67ac07dbe.jpg)
![Screenshot_2022-04-05-11-44-07-585_com android chrome](https://user-images.githubusercontent.com/87787929/161674706-4664fe12-9163-40c9-88c2-d2cb311fda9b.jpg)

### Expected Behavior

The task that I created is for auto-restart and run some command

### Steps to Reproduce

I find failed_jobs on MySQL:

`{"uuid":"bb795633-72a0-4292-9d3e-27ec261cfc97","displayName":"Pterodactyl\\Jobs\\Schedule\\RunTaskJob","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"maxExceptions":null,"failOnTimeout":false,"backoff":null,"timeout":null,"retryUntil":null,"data":{"commandName":"Pterodactyl\\Jobs\\Schedule\\RunTaskJob","command":"O:36:\"Pterodactyl\\Jobs\\Schedule\\RunTaskJob\":12:{s:4:\"task\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:23:\"Pterodactyl\\Models\\Task\";s:2:\"id\";i:17;s:9:\"relations\";a:2:{i:0;s:8:\"schedule\";i:1;s:14:\"schedule.tasks\";}s:10:\"connection\";s:5:\"mysql\";}s:9:\"manualRun\";b:0;s:10:\"connection\";N;s:5:\"queue\";s:8:\"standard\";s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:19:\"chainCatchCallbacks\";N;s:5:\"delay\";i:0;s:11:\"afterCommit\";N;s:10:\"middleware\";a:0:{}s:7:\"chained\";a:0:{}s:3:\"job\";N;}"}}`

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

Every on panel's server

### Error Logs

```bash
http://bin.ptdl.co/jbsbv
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
> 
This is what your cronjob means: 
![afbeelding](https://user-images.githubusercontent.com/67589015/161730738-279eea2f-1030-445a-840e-3b446311e597.png)

Is the queue worker running? `systemctl status pteroq` have you tryed restartting it?
and did you add the CRON on the OS to run the queue worker? if you run `sudo crontab -e` do you see: 
![afbeelding](https://user-images.githubusercontent.com/67589015/161730058-6c08e9bc-859d-497c-831c-9fe999f58e5e.png)

**Comment by Koyorice** [comment]
After I changed my storage method to redis-server, this problem was fixed
