### ISSUE TITLE
Pterodactyl and additional permission from the developer of games 

### ISSUE THREAD

**Issue by NordManer** [pterodactyl/panel#4037]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hello! 
We are hosting company and want to use Pterodactyl to create game servers with games ARK: Survival Evolved, ARMA 3, Counter-Strike: GO)
Can you advise on several issues? Do we need to get additional permission from the developer of these games to create game servers? Or is it enough if only end customers have licenses?
Thank you in advance!

### Describe the solution you'd like.

Only answer for my question

**Comment by trenutoo** [comment]
This is more fitting to be posted in the discussion or Discord server as it's not a new feature request.

Games that require account to own the game will have fields to provide the login credentials. Majority are anonymous and don't require an account. Any terms of service or licensing issues should be directed to the developers, e.g Fivem doesn't allow selling servers.
