### ISSUE TITLE
backup overwrite or option to set schedule for remove it

### ISSUE THREAD

**Issue by TheBeast2155** [pterodactyl/panel#4039]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be good to have a broken auto backup of the servers if one would offer automatic backup for x number of days that it would run automatically and delete backups over x number of days

### Describe the solution you'd like.

1 possibility is that we can put it as an option on the server and panel handle it
2 could be schedules that one can make to also remove it after x number of days

**Comment by yesBad** [comment]
It overwrites already.


Aka if you have 3/3 backups used, it removes oldest one & makes new one.
