### ISSUE TITLE
No nodes satisfying the requirements specified for automatic deployment could be found.

### ISSUE THREAD

**Issue by GeorgeV220** [pterodactyl/panel#4040]
### Current Behavior

When I'm trying to create a server through the API I get this errror:
[{"code":"NoViableNodeException","status":"400","detail":"No nodes satisfying the requirements specified for automatic deployment could be found."}]}
I have enabled `Allow Automatic Allocation` and set `-1` to `Overallocate` in order to have overallocation

### Expected Behavior

Create the server without errors

### Steps to Reproduce

Create a server from the API when you have exceed the `allocation limits`

### Panel Version

1.7.0

### Wings Version

1.6.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Please use Discord, this is not a bug in the software.
