### ISSUE TITLE
[FEATURE] Use SAWO as the authentication provider

### ISSUE THREAD

**Issue by Panquesito7** [pterodactyl/panel#4041]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Authentication is very crucial nowadays. With 2FA, it makes your account secure. However, not all users enable 2FA, and not all users use secure passwords. Most people use weak passwords such as `abc`, `123`, etc. etc..

I propose to use [**SAWO**](https://sawolabs.com) as our authentication provider.

SAWO Labs is an authentication service whose goal is to use passwordless authentication. No 2FA, no password: just a code that is sent to your mail that expires after around one minute.
It is very easy to integrate SAWO onto your platform. You can check the [**documentation**](https://docs.sawolabs.com/sawo/) for how to set up SAWO. It supports HTML, React.js, Node.js, Angular, Vue, and so many other frameworks.

### Describe the solution you'd like.

Use SAWO as our authentication provider to login into our panels. Instead of logging in with passwords, SAWO will just ask for a mail and will send a code to your mail to log in securely, without any passwords.
This would be needed to be used in all panels when logging in.

### Additional context to this request.

If you need/want more information about SAWO, don't hesitate to tell me! We have a Discord community as well. :)

**Comment by DaneEveritt** [comment]
Won't be implementing.
