### ISSUE TITLE
Can´t read machine-id from normal Java container for Java 17

### ISSUE THREAD

**Issue by BolverBlitz** [pterodactyl/panel#4043]
### Current Behavior

One of my Eggs requires a way to get a unique id, for this it reads a file thats pressent on most OSs and diffrent locations.
However it cant find the file in the normal [Java Yolk for java 17](https://github.com/pterodactyl/yolks/tree/master/java/17): `open /etc/machine-id: no such file or directory` it works as expected with the [J9](https://github.com/pterodactyl/yolks/tree/master/java/17j9) version.

Java 8,11 and 16 Yolks have this file aswell, only Java 17 is not working.

### Expected Behavior

Should be able to read /etc/machine-id from Java 17 Yolk like on most distros and the J9 yolks and older normal Java Yolks.

### Steps to Reproduce

Try to read /etc/machine-id file with the [Java Yolk](https://github.com/pterodactyl/yolks/tree/master/java/17)
Or use the [egg](https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg/blob/main/egg-paper-on-demand.json) thats not working.

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg/blob/main/egg-paper-on-demand.json

### Docker Image

ghcr.io\/pterodactyl\/yolks:java_17

### Error Logs

```bash
2022/04/09 18:42:14 [error *   ] main: LoadConfig: loadDefault: machineid: machineid: open /etc/machine-id: no such file or directory
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
This would be an issue for any docker container. It's even an issue on the machineid git repo.

https://github.com/denisbrodbeck/machineid/issues/5

**Comment by BolverBlitz** [comment]
Hm, but why is it specific the Java 17 yolk then. 

Yolks 8,11,16 and 8J9,11J9,16J9 and 17J9 all work fine. 
Any other solution to get a unique inside a container managed by pterodactyl maybe?

**Comment by parkervcp** [comment]
Every server has a uuid attached to it and is part of the env vars. 

If you passed in a machine id file they would all get the same id every time.

**Comment by BolverBlitz** [comment]
Could i not just use that env var to put into the file thats missing in the eggs install script?

**Comment by parkervcp** [comment]
No. The only files that are saved are the ones in `/mnt/server/`.

**Comment by DaneEveritt** [comment]
Closing this out, doesn't appear to be software specific.
