### ISSUE TITLE
No CPU and RAM usage data on mc java 16 server

### ISSUE THREAD

**Issue by Priidiusz** [pterodactyl/panel#4044]
### Current Behavior

When installing the server everything was fine and once it downloaded what it was supposed to download, the server starts successfully but the stats don't show anything.

### Expected Behavior

It should actually show CPU and ram usage.

### Steps to Reproduce

Just in my case, install minecraft server (paper) on java 16 on arm64 architecture (ghcr.io/software-noob/arm64:java_16) and start the server and the error should appear.

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

Minecraft (Paper)

### Docker Image

ghcr.io/software-noob/arm64:java_16

### Error Logs

```bash
https://ptero.co/gosezecesu
https://bin.ptdl.co/ytiy0/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by yesBad** [comment]
#3999
