### ISSUE TITLE
Ability to use self-signed certs on wings

### ISSUE THREAD

**Issue by Gaz492** [pterodactyl/panel#4046]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

While its possible to use a self signed cert with wings the panel has issues with communicating with wings due to Guzzlephp/libcurl being unable to verify the certificate.
```log
[2022-04-14 13:50:58] production.WARNING: GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.dedi:5080/api/system in /var/www/pterodactyl/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211
```

### Describe the solution you'd like.

It would be great if it were possible to set the `verify` flag on guzzle to false
```php
'verify' => false
```

**Comment by QuintenQVD0** [comment]
> ### Is there an existing feature request for this?
> * [x]  I have searched the existing issues before opening this feature request.
> 
> ### Describe the feature you would like to see.
> While its possible to use a self signed cert with wings the panel has issues with communicating with wings due to Guzzlephp/libcurl being unable to verify the certificate.
> 
> ```
> [2022-04-14 13:50:58] production.WARNING: GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.dedi:5080/api/system in /var/www/pterodactyl/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211
> ```
> 
> ### Describe the solution you'd like.
> It would be great if it were possible to set the `verify` flag on guzzle to false
> 
> ```
> 'verify' => false
> ```
> 
> ### Additional context to this request.
> _No response_

I think the option behind proxy disable that check.

**Comment by rugter100** [comment]
Using a feature that was not designed for this makes it confusing, also enabling this didn't work for me. I would appreciate if this feature can be added

**Comment by ChloeWinter** [comment]
This is also not working for me

**Comment by schrej** [comment]
I think the reason for not having a config option that allows this is, that users would need to trust the certificate in their browser in order to access the server console, as the browser will talk to wings directly to do so.
And there is probably no good way of triggering that browser check, unless maybe opening the wings endpoint in another tab. So either disable https, or get a letsencrypt certificate.

**Comment by DaneEveritt** [comment]
There is no way (currently) to run Wings in a configuration that would allow the Panel to communicate with a self-signed certificate without the user also having that certificate in _their_ trust store.

As a result, allowing a self-signed certificate only for the Panel to communicate is kind of... pointless. You can run Wings with `--ignore-certificate-errors` to have _Wings` skip validation of the certificate on the Panel.

But yeah, this is not really a configuration that makes sense to me outside of development environments. And even in the official development environment we just have the certificate that Wings runs with trusted by the CA of the Panel's VM.

That is done with:
```
sudo mkdir -p /usr/local/share/ca-certificates/mkcert
sudo cp /etc/certs/pterodactyl*.pem /usr/local/share/ca-certificates/mkcert/
sudo update-ca-certificates
```

Something like this may be feasible for your situation to have the Panel server trust the certificate used by Wings.
