### ISSUE TITLE
Remote timing attack possible on API HMAC middleware

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#405]
The [`validateContents()`](https://github.com/Pterodactyl/Panel/blob/develop/app/Http/Middleware/HMACAuthorization.php#L173) function should be using `hash_equals()` rather than `!==` to compare the two hashes to avoid a timing attack.

Thanks to @dansup for reporting this issue!

**Comment by MatthewSH** [comment]
@DaneEveritt I see this has had a PR, does this still need to be open?
