### ISSUE TITLE
Egg updater

### ISSUE THREAD

**Issue by TekExplorer** [pterodactyl/panel#4053]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I'm surprised I couldn't find an issue for this already...

Eggs currently have a seemingly unused `update_url`.
This, alongside `exported_at` can be used to indicate to admins that the egg is not up to date, and allow quick updates, without requiring downloading, then uploading the updated file, if they even realize it's outdated.

### Describe the solution you'd like.

I don't really have a specific idea of how it should be implemented, as long as it's reasonable to use and will hopefully avoid keeping super outdated eggs on the panel without realizing.

**Comment by gOOvER** [comment]
Would save some support, due to outdated Eggs :)

**Comment by gOOvER** [comment]
But i think, it a duplicate of: 

https://github.com/pterodactyl/panel/issues/3479

**Comment by TekExplorer** [comment]
> But i think, it a duplicate of:
> 
> #3479

Dang, you right.. searching is hard.
Well, now I will be able to find it again.
