### ISSUE TITLE
Linked Scripts not working

### ISSUE THREAD

**Issue by fragger1991** [pterodactyl/panel#4057]
### Current Behavior

I have created several eggs that should use the same script. I then removed the script from the other eggs and replaced it with a simple note. In the "Copy Script From" field I then specified the source egg. During installation, however, it does not access the linked script, but uses the stored one.

### Expected Behavior

I expect the linked script to run instead of the one provided. As the description of the function says (If selected, script above will be ignored and script from selected option will be used in place.).

### Steps to Reproduce

Take an egg and put an install script there. Then go to another egg and store e.g. "echo "Nothing here!"" in the install script and then select the previously edited egg under "Copy Script From". Now create a game server with the game that should use the linked script. The process cannot be completed and failed.

### Panel Version

1.7.0

### Wings Version

1.4.2

### Games and/or Eggs Affected

Counter-Strike: Global Offensive

### Docker Image

ghcr.io/pterodactyl/installers:debian

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
It's intended to copy the script at the time of creation, instead of being a syncing copy

**Comment by parkervcp** [comment]
"Copy From" does not mean "Always Use"

**Comment by fragger1991** [comment]
As it seems, there are still a few problems of understanding here. At least for me this function has a completely different meaning. I would generally like to see more inheritance of things in Pterodactly, which would make manual maintenance much easier. Here I had seen such an approach and therefore thought that it was a bug.

But thanks for the clarification!
