### ISSUE TITLE
Named pipe causes timeout for the file manager tab

### ISSUE THREAD

**Issue by Kebab11noel** [pterodactyl/panel#4059]
### Current Behavior

Listing a directory in the file manager which contains a named pipe causes a timeout.

### Expected Behavior

File manager should load and list the directory contents.

### Steps to Reproduce

Create a named pipe and try to open the folder in which is contained.

### Panel Version

1.7.0

### Wings Version

1.6.1

### Error Logs

```bash
https://bin.ptdl.co/i946q/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by mason-rogers** [comment]
Is there any errors in wings logs?

**Comment by Kebab11noel** [comment]
Latest log entry shown by `journalctl -u wings` is from 2021-06-27

**Comment by mason-rogers** [comment]
I doubt that, wings logs several things on startup and if you're on 1.6.1 you would've had to restart wings since then

Provide the link from `sudo wings diagnostics`

**Comment by Kebab11noel** [comment]
Well i checked the output of `wings diagnostics` but it only has info entries and altough they're more recent entries all of them are logged before attempting to access a folder with a named pipe, so no relevant logs from wings.
