### ISSUE TITLE
Integrate async-profiler & flamegraph viewer

### ISSUE THREAD

**Issue by TheMode** [pterodactyl/panel#4060]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Most people seems to use pterodactyl to interact with their Minecraft, and while having a CPU usage indicator is useful, it remains not enough to diagnose the issue at hand.

I am therefore suggesting a way to run a profiler and analyze its report as a flamegraph.

I am also aware that integrating such feature into pterodactyl is not mandatory, it would however be a huge conveniency and help avoiding random performance complaints lacking context.

### Describe the solution you'd like.

This suggestion could be implemented as a new `Profiler` tab allowing you to choose the process and the method (`perf`/`async-profiler`) and a flamegraph visualizer (or perhaps just a way to download it)

[async-profiler](https://github.com/jvm-profiling-tools/async-profiler) is a profiler specialized for the JVM and support generation of flamegraphs.

Obviously, not all servers use the JVM. `perf` can be used in combination with [FlameGraph](https://github.com/brendangregg/FlameGraph)

**Comment by DaneEveritt** [comment]
Won't be adding this, just way too specific and I have zero experience using any of these tools. As a result this would take ages for me to even figure out what I'm doing, and honestly my limited time is better spent working on more pressing tasks.

Thanks for the suggestion though. :)
