### ISSUE TITLE
Official Unraid Version Missing Write Permissions 

### ISSUE THREAD

**Issue by Tindog33** [pterodactyl/panel#4063]
### Current Behavior

The Official Unraid version of Pterodactyl has an issue where it can't write folders on Unraid, also can't edit some text documents, but it can install them just fine.

### Expected Behavior

Installation should be easy and it should be able to write folders and edit text files. The unofficial version by IBRACORP can do this with ease, but the official one can't do this at all.

### Steps to Reproduce

If you install the Offical Unraid version of Pterodactyl it installs just fine and when you put in the config.yml file to its remapped folder it works fine, however, this is where it stops working. What basically happens is if you try to install say a Minecraft server (vanilla) for instance, it will fail to download the files, the reason why is because when it creates (Example name 8001at) it should create a folder called 8001at, but it can't do this and so it refuses to download. Well if you go put a folder called 8001at where it should be located then it will install it to the folder. However certain files also can't be edited for example if you want the server to run on port 20009 (just an example) (Minecraft's default is 25565) the server will still load the server on 25565 even though Pterodactyl will say it's on 20009, this is because it can't edit the Minecraft text document. Also when accepting the EULA and you push ACCEPT it doesn't write the accept to the EULA file, so the game crashes, you have to go into the file and actually edit it to true, and then it works. So it appears that the Offical Unraid version of Pterodactyl can't write certain folders, or edit certain files. I tried several installations and the error was repeatable, I even had a software engineer look at it and agree that the Offical Unraid version seems to not have write permissions that it should have. Interestingly if you install the IBRACORP version (The Unofficial Version) it's installation and file remapping are almost identical to the official one, but it doesn't have these issues, so when you accept the EULA it actually write 'true' to the file. When you create a new server it creates the folder. When you edit the port in Pterodactyl it actually edits the port in the text document. The official version is newer than the unofficial one, so I'm sure that somewhere in the official version there is a line of code or a something that should give these permissions but doesn't. FYI IBRACORP has expressed interest in helping you with the official version if you want to contact him, so if you can't figure it out maybe have him look at it. But this is very annoying as you have to create all the files and edit the folders manually to get them to work, which makes a lot of Pterodactyl's features not work (like multiple users), and makes it a pain to use so this should be fixed. I tried it on multiple servers and multiple installations and it was the same issue every time so it is a repeatable bug.

### Panel Version

1.4.0

### Wings Version

1.4.2

### Games and/or Eggs Affected

Minecraft Vanilla

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
We didn't make anything official for unraid. They used our images and wrote their own documentation on using them. So far as I understand is there has been no communication between the teams.

**Comment by DaneEveritt** [comment]
This is not a bug with Pterodactyl.
