### ISSUE TITLE
Server doesn't transfer on customized egg

### ISSUE THREAD

**Issue by itsfranciscooli** [pterodactyl/panel#4065]
### Current Behavior

I am trying to move servers from one node to another and it doesn't make anything. It's just stuck. I think it's a bug in wings where it checks all fields before transferring and since i have more fields it's blocking and not transferring. 

### Expected Behavior

Transfer files and start server in new node

### Steps to Reproduce

Use this egg i've customized. It's the original egg but with additional fields.
https://srcb.in/bpAhJvvIHG
Try to transfer a cs server from one node to another and see the error. It doesn't report anything and stays like that for hours 

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

Counter Strike

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
Not sure how you expect us to assist when you've provided no logs...
