### ISSUE TITLE
Invalid Route Action 1.7.0

### ISSUE THREAD

**Issue by tahoward** [pterodactyl/panel#4068]
### Current Behavior

Pterodactyl Panel 1.7.0 does not successfully start after docker build.

Also see: https://github.com/pterodactyl/panel/issues/3262

### Expected Behavior

The application should start successfully. Instead, the application returns a 500 error page.

### Steps to Reproduce

Build docker image from v1.7.0 branch and run it.

### Panel Version

1.7.0

### Wings Version

1.6.1

### Docker Image

php:7.4-fpm-alpine

### Error Logs

```bash
external vars exist.
writing ssl config
cp: can't create '/etc/nginx/http.d/default.conf': File exists
updating ssl config for domain
sed: can't create temp file '/etc/nginx/http.d/default.confXXXXXX': Read-only file system
Checking database status.
panel-database (10.109.159.106:3306) open
Migrating and Seeding D.B
In RouteAction.php line 92:
                                                                               
  Invalid route action: [Pterodactyl\Http\Controllers\Api\Application\Nodes\N  
  odeDeploymentController].                                                    
                                                                               
Starting cron jobs.
Starting supervisord.
2022-05-07 19:25:21,161 CRIT Server 'unix_http_server' running without any HTTP authentication checking
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
How exactly did you build the image and have you tried using the existing image that's automatically built by Pterodactyl ci? I am unable to reproduce this.

```
panel-panel-1     | ln: /app/storage/logs/logs: File exists
panel-panel-1     | external vars exist.
panel-panel-1     | Checking if https is required.
panel-panel-1     | Checking if letsencrypt email is set.
panel-panel-1     | No letsencrypt email is set using http config.
panel-panel-1     | Removing the default nginx config
panel-panel-1     | DB_PORT not specified, defaulting to 3306
panel-panel-1     | Checking database status.
panel-panel-1     | Waiting for database connection...
panel-panel-1     | database (172.22.0.3:3306) open
panel-panel-1     | Migrating and Seeding D.B
<db egg seeding spam>
panel-panel-1     | Seeded:  Database\Seeders\EggSeeder (87.26ms)
panel-panel-1     | Database seeding completed successfully.
panel-panel-1     | Starting cron jobs.
panel-panel-1     | Starting supervisord.
panel-panel-1     | 2022-05-07 19:58:06,043 CRIT Server 'unix_http_server' running without any HTTP authentication checking

```

**Comment by tahoward** [comment]
I havn't tried using the CI image, didn't know it existed. Will give it a whirl. As for builds... I'm essentially cloning the repo, switching to release/v1.7.0 branch then executing `docker build -t tahoward/pterodactyl-panel:1.7.0 .` from root of the repo.

**Comment by tahoward** [comment]
CI image works :|

Not sure what the deal is then.

**Comment by NobleMajo** [comment]
Same problem:
```sh
Migrating and Seeding D.B
In AbstractConnection.php line 155:
  Address not available [tcp://localhost:6379]
Starting cron jobs.
Starting supervisord.
2022-05-31 11:32:42,309 CRIT Server 'unix_http_server' running without any HTTP authentication checking
```

**Comment by Krzywson** [comment]
Same problem from  image: ghcr.io/pterodactyl/panel:latest
