### ISSUE TITLE
Log output from process instead of reading log on page refresh

### ISSUE THREAD

**Issue by tenten8401** [Pterodactyl/Panel#407]
The title says it all, on page refresh can the panel start logging the output from the process itself instead of reading the log on a page refresh? It's strange to have the log change when you refresh and some important info could be missing.

**Comment by DaneEveritt** [comment]
There's no in memory buffer of logs, but I can look into it potentially. However most of these issues are just poor log implementations in the respective game.

**Comment by tenten8401** [comment]
@DaneEveritt Yea, I agree with you on the poor log implementation part, but we really should have it log the process output somewhere, maybe in the docker container at /home/container/console_log or something.

**Comment by DaneEveritt** [comment]
Certain games already do custom logging via the daemon (SRCDS for example). Honestly theres only so much I can do without simply rewriting the entire logging implementation for a game to be custom in the Daemon, which is not ideal as I try to keep everything as vanilla for the game as possible.

Do you have any examples of "data loss" that you see when refreshing the page (other than loss of color formatting)?

**Comment by belldandu** [comment]
Only pepev i have with custom logs that log console output is that the logs can get REALLY big. Granted that if we seperated logs by day and pruned them every week that would be cool. (because honestly its weird when i refresh the page or load the page and cant tell who all logged into minecraft or if minecraft threw a warning for some odd reason or another)

**Comment by parkervcp** [comment]
Several games already do log rotation (minecraft). Others do not (factorio afik).

Logging is an issue that from the panel shouldn't be our problem. Honestly it's the server creator who made that decision. Many may have the option but it would need to be looked into.

**Comment by tenten8401** [comment]
Believe this can be done with custom: true in the logging config now. Closing.
