### ISSUE TITLE
Cloudflare R2 Compatibility

### ISSUE THREAD

**Issue by FlaringPhoenix** [pterodactyl/panel#4074]
### Current Behavior

I have cloudflare r2 S3 fully configured in my .env. I try making a backup inside of a server but it just fails. I check the panel logs and no logs are created. I tested the exact same details in the S3 browser app and they work. 

Here is my env:
```
AWS_DEFAULT_REGION='auto'
AWS_ACCESS_KEY_ID='???'
AWS_SECRET_ACCESS_KEY='???'
AWS_BACKUPS_BUCKET='pterodactyl'
AWS_ENDPOINT='https://e77ad9bbbaa89c6c7705b6045d1e363b.r2.cloudflarestorage.com'
AWS_USE_PATH_STYLE_ENDPOINT=true
```

I contacted cloudflare's team and they checked logs and they responded to me: [Click-here](https://sharexhost.com/zIhi3/qOTumABu61.png)

### Expected Behavior

Server remotely backed up to cloudflare r2 via s3

### Steps to Reproduce

Configure your .env to use cloudflare r2 s3

### Panel Version

1.7.0

### Wings Version

1.6.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Please provide error logs or I'll be closing this issue, thanks. Even if the Panel isn't generating any logs it looks like you must have been providing something or seen logs somewhere to indicate there was a specific issue at play.

**Comment by DaneEveritt** [comment]
Presigned URLs are not supported for R2 at this time, so this is not going to work. Effectively, R2 is not supported.

**Comment by camjac251** [comment]
With R2 being supported now, is it possible for it to support the `Domain Access` access feature of R2 that sets the DNS for a domain/subdomain to point to the "bucket", for use with the signed download URLs?
https://developers.cloudflare.com/r2/data-access/public-buckets/#connect-your-bucket-to-a-custom-domain

**Comment by matthewpi** [comment]
> With R2 being supported now, is it possible for it to support the `Domain Access` access feature of R2 that sets the DNS for a domain/subdomain to point to the "bucket", for use with the signed download URLs? https://developers.cloudflare.com/r2/data-access/public-buckets/#connect-your-bucket-to-a-custom-domain

I'm not sure.  I haven't tested domain access with R2 yet, only the regular account id endpoint.

**Comment by TheLegendarySpark** [comment]
Any support on this?

**Comment by matthewpi** [comment]
> Any support on this?

Yes, R2 is supported without any additional configuration.
