### ISSUE TITLE
Wrong Dates on

### ISSUE THREAD

**Issue by DemonMartin** [pterodactyl/panel#4075]
### Current Behavior

When decompressing a .rar, the Dates in the panel say: "Dec 13th 1901 9:45PM"

### Expected Behavior

The Dates from the decompressed files should be normal, or at least the Date of when the decompressing happened.

### Steps to Reproduce

Using WinRAR, generate a maximum compressed .rar (not solid)
Upload the file to pterodactyl
Decompress it

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

Any

### Docker Image

Any

### Error Logs

```bash
https://ptero.co/yzucapyjeq // no error
https://bin.ptdl.co/itirz/ // not relevant error
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Ferks-FK** [comment]
I don't think this is a problem, it only shows the date of the last modification of the file, not when it was extracted.

**Comment by DemonMartin** [comment]
Don't think my File got created 1901

**Comment by parkervcp** [comment]
Winrar may not write dates to files properly.

**Comment by DaneEveritt** [comment]
I cannot reproduce this, but I don't have WinRAR. My guess would be that of @parkervcp — it is probably not setting the data correctly. We already have hacks in the code to handle `.rar` files as is, it is not a highly supported format in this software.

I won't be making any changes to try and support this specific condition.
