### ISSUE TITLE
Security Issue / Bug Report | SMTP TLS 1.2 support

### ISSUE THREAD

**Issue by Evesain** [pterodactyl/panel#4076]
### Current Behavior

SMTP TLS 1.0 & 1.1 are supported & work fine.

When I am trying to send emails using smtp.office365.com they always bounce back saying that it couldn't authenticate because it didn't meet security requirements.
New email server: smtp.office365.com

I am currently working around this issue by enabling legacy smtp support which allows TLS 1.0 & 1.1 to be used. 
Legacy email server: smtp-legacy.office365.com

This is incredibly insecure to use but there is sadly no other option.

===== UPDATE =====

I fixed this issue by doing the below changes
The way to allow it to support TLS1.2 is by changing the order of the return statement on line 94 of the following file
/var/www/pterodactyl/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php

Previously
```php
return stream_socket_enable_crypto($this->stream, true, STREAM_CRYPTO_METHOD_TLSv1_0_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT);
```

After
```php
return stream_socket_enable_crypto($this->stream, true, STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_0_CLIENT );
```

For some reasons this was returning the wrong version TLS Client even though the option was there so just changing the order works perfectly for me

DISCLAIMER: Please check the above and make sure this doesn't cause any issues with existing setups.

### Expected Behavior

Ideally smtp.office365.com (port 587) will send emails using a microsoft account

This should work
![image](https://user-images.githubusercontent.com/11574971/168449034-209c3e4b-9d55-4171-99be-511c9f24ed0d.png)

### Steps to Reproduce

REQUIREMENTS:

- Microsoft Tenant
- Microsoft Exchange Online License

use the below information
![image](https://user-images.githubusercontent.com/11574971/168449055-d68700a2-c6c0-4699-aece-8519e38567c2.png)

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
Not Valid
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Siftmailer is abandoned and replaced with `symfony/mailer` which is standard in Laravel 9. This will be addressed in the future but for now there is nothing specific within Pterodactyl that can be tweaked to address this at the immediate moment. A Laravel 9 upgrade is in the works but a significant breaking change given the changed PHP versioning requirements and some additional internal work.

I'm closing this issue out as a result — it will be fixed transitively in future releases.

In the mean time it looks like you figured out a solution that works for you for the time being though.
