### ISSUE TITLE
500 | Server Error on File Manager and Server Reinstallation

### ISSUE THREAD

**Issue by LeppyThe1st** [pterodactyl/panel#4077]
### Current Behavior

Currently getting an 500 error on GET for api/client/servers/{id}/resources and api/client/servers/{id}/settings/reinstall. I have looked into the laravel logs which I will paste below. It shows 1 issue with connecting to the Redis service however I have extensively troubleshot the connection between the services with both being able to talk to each other.

### Expected Behavior

I should have access to the File Manager tab and I should be able to use the Reinstall Button on the Settings tab.

### Steps to Reproduce

I am unable to put steps here to me just updating the Teamspeak 3 and Arma 3 servers. They worked through the updates and I was using the file manager for both to edit files. After about 5 minutes it stopped working.

### Panel Version

1.7.0

### Wings Version

1.6.1

### Error Logs

```bash
http://bin.ptdl.co/c06ju
Browser Console - File Manager:
  GET https://panel.example.com/api/client/servers/{id}/resources 500
  Error: Request failed with status code 500
    at e.exports (bundle.f57341e4.js:1:236137)
    at e.exports (bundle.f57341e4.js:1:482268)
    at XMLHttpRequest.p.onreadystatechange (bundle.f57341e4.js:1:235002)
Browser Console - Reinstall Server:
  POST https://panel.lt1.one/api/client/servers/f3139aca-cd53-4862-bd79-1310f3734992/settings/reinstall 
  500
  Error: Request failed with status code 500
    at e.exports (bundle.f57341e4.js:1:236137)
    at e.exports (bundle.f57341e4.js:1:482268)
    at XMLHttpRequest.p.onreadystatechange (bundle.f57341e4.js:1:235002)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devil38** [comment]
PHP version?

**Comment by LeppyThe1st** [comment]
PHP Version: PHP 7.4.27 (cli) (built: Dec 16 2021 22:42:18) ( NTS )

**Comment by devil38** [comment]
> PHP Version: PHP 7.4.27 (cli) (built: Dec 16 2021 22:42:18) ( NTS )

Upgrade to php 8.0

**Comment by devil38** [comment]
Panel logs?

**Comment by LeppyThe1st** [comment]
Referring to /var/www/pterodactyl/storage/logs/? They are here: [http://bin.ptdl.co/c06ju](http://bin.ptdl.co/c06ju)

**Comment by devil38** [comment]
Is redis running?

**Comment by LeppyThe1st** [comment]
> Is redis running?

Yes redis is running and I have verified that Panel can connect to it through redis-cli.

**Comment by DaneEveritt** [comment]
This is not a bug with this software, your logs indicate that your cache instance is not responding, or unreachable:

```
production.ERROR: Connection refused [tcp://cache:6379]
```
