### ISSUE TITLE
Scheduled tasks not executing

### ISSUE THREAD

**Issue by Stefanuk12** [pterodactyl/panel#4079]
### Current Behavior

The `Last run at` either stays on `never` or at the last time I manually ran the task. Once the time for the next run rolls around, the task is not executed.

I have tried `systemctl restart pteroq.service`, `systemctl restart wings` and `restart` to restart my entire VPS.

I do have multiple servers on one node.

### Expected Behavior

For the task to execute and restart my server.

### Steps to Reproduce

1. Make a task with the `restart` command
2. Set the time to be `*` for each field so it should restart every minute (for testing)

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

discord.py (generic)

### Docker Image

ghcr.io/parkervcp/yolks:python_3.10

### Error Logs

```bash
https://ptero.co/gyqokylone
(getting an error saying dir does not exist with panel)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Goksi** [comment]
Looks like you are using self signed cert, try making one according to docs

**Comment by Stefanuk12** [comment]
I'm not sure why that error occurred but I am using a cloud flare cert. Is that okay?

**Comment by Goksi** [comment]
Also this should be something you would like to ask on [discord server](https://discord.gg/Zby79vPM)

**Comment by Stefanuk12** [comment]
Alright, thanks for the help. I'll try it out, if it still does not work, I'll let you know
