### ISSUE TITLE
Simpler way of distributing custom themes

### ISSUE THREAD

**Issue by tenten8401** [Pterodactyl/Panel#408]
Can we have an easier way of distributing themes? Like a 1-folder solution instead of extracting to 2 different places and adding an entry to themes.php?

**Comment by MatthewSH** [comment]
It's not that complicated in my opinion. 

Layouts, modules, pages > `resources/themes/`
CSS, JS, etc > `public/themes/`

Then you allow people the use of the theme in the config. I'm trying to understand how this is complicated.

Maybe there's just a lack of tutorials out there. If this is the case, then maybe we can get something going for that.

**Comment by OzairP** [comment]
I don't think it's about complexity, but more of a single source of truth type deal.

For example, if you had removed a themes CSS but not it's pages. It would make sense if they stayed in one folder with each theme having its own style and markup subfolders.

**Comment by DaneEveritt** [comment]
Theres no other way to do this currently with the way Laravel works. The entire point of the public folder is that anything in there can be accessed by users, while the actual template files are stored privately since users should not be able to see them.

**Comment by OzairP** [comment]
Perhaps using a build tool like Laravel Mix/Elixir?

**Comment by MatthewSH** [comment]
@OzairP I'm not sure what you're trying to get at? That doesn't really make sense with the rest of the conversation thus far.

We're discussing theme distribution, not development of themes.

**Comment by OzairP** [comment]
@MatthewSH I meant using a build tool to move files, preprocess files, etc. Makes distribution easier.
