### ISSUE TITLE
Improper file name sanitization

### ISSUE THREAD

**Issue by nikrozman21** [pterodactyl/panel#4081]
### Current Behavior

A filename with a space in front of it will cause issues with many filesystem-related functions.

### Expected Behavior

A filename with a space in front of it should get properly sanitized to prevent issues such as this from cropping up.

### Steps to Reproduce

1) Create a file using the built-in file manager
2) Save it, but add a space in front of the filename (example " test")
3) Try deleting or moving the file

This bug might be reproducible when decompressing archives and over SFTP.

### Panel Version

1.7.0

### Wings Version

1.6.1

### Error Logs

```bash
https://bin.ptdl.co/rqizk/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by hwalker928** [comment]
Can replicate this issue as well.

**Comment by Ferks-FK** [comment]
I can replicate this as well.

**Comment by DaneEveritt** [comment]
It was actually sanitized fine, the panel was just being overzealous in it's trimming of string values...

Closed in https://github.com/pterodactyl/panel/commit/05f41a2ca8509c9867bd35613f8ec871eed1f441
