### ISSUE TITLE
Panel doesn't check for CNAME records (Argo Tunnel)

### ISSUE THREAD

**Issue by SpicyTakis** [pterodactyl/panel#4082]
### Current Behavior

The panel says the FQDN of a node will not resolve because it does not point to a valid IP Address when it is pointing to a CNAME address of Argo Tunnel.

### Expected Behavior

The panel creates the node without erroring out about not pointing to a address.

### Steps to Reproduce

- Start creating a new node
- Enter a FQDN that is a CNAME record pointing to a Argo Tunnel address
- Try to create the node, it will fail.

### Panel Version

canary (docker image)

### Wings Version

1.6

### Error Logs

```bash
http://bin.ptdl.co/ferlb
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
I have never used Argo Tunnels before and have no intention of going through the effort of figuring out how to set one up.

Please provide steps that I can use to setup a tunnel in order to confirm this bug, otherwise I'm just closing out this issue.

**Comment by SpicyTakis** [comment]
Sorry for the late response, here is the official setup guide for argo tunnel. This guide assumes you have a active domain routed through cloudflare. It's fairly straight forward to set one up. If you have any questions feel free to ask. https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/#set-up-a-tunnel-locally-cli-setup

**Comment by schrej** [comment]
The error you have provided indicates that tables are missing from the database. Did you run all migrations?

Also the panel doesn't do DNS resolution, that's handled by your OS. So if resolution is working fine on the host, the panel should have no issues either. I think it's using libcurl internally, so checking connectivity with `curl` is probably a good approach.

**Comment by SpicyTakis** [comment]
I don't know why the errors are there with the database, I have it setup with docker but I might have missed a command to set it up.

It eventually let me create the node after some time but I will see if it just lets me do it when i get off of school.

**Comment by DaneEveritt** [comment]
I'm closing out this issue due to a lack of actionable error logs.
