### ISSUE TITLE
Add Network Usage Meter

### ISSUE THREAD

**Issue by Sylvaeseel** [pterodactyl/panel#4083]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Network usage meter on server console page akin to the cpu and ram usage meters

### Describe the solution you'd like.

Read above

**Comment by trenutoo** [comment]
https://github.com/pterodactyl/panel/commit/62b178ed0297549be9eb009c968d5d47d4fe8ffb This has been implemented in develop branch and will be included in the next release.

**Comment by Sylvaeseel** [comment]
Awesome!
