### ISSUE TITLE
canary panel doesn't reflect latest canary wings changes

### ISSUE THREAD

**Issue by BlueTree242** [pterodactyl/panel#4084]
### Current Behavior

When you try to use the following endpoint: `api/client/servers/SERVER_ID/files/pull`

the panel completely ignores the `root` body key, and takes the `directory` instead, which is deprecated

Additionally, it ignores the `file_name` and `foreground` keys that canary wings is expecting, which makes usage of this endpoint with canary wings rlly bad

### Expected Behavior

Send those body keys (and their values ofc) to the wings, so wings can take care of them

### Steps to Reproduce

1. try do a post request to `api/client/servers/SERVER_ID/files/pull` endpoint with root instead of directory
2. file is not created, as panel never sends root to wings

4. if you use directory instead of root, and use canary wings, and use `file_name` and `foreground` wings doesn't receive them, so the file name is not applied nor foreground boolean

### Panel Version

canary

### Wings Version

canary & latest

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
I'm able to reproduce this with panel v1.7 / Wings v1.6.

**Comment by DaneEveritt** [comment]
closed in c14c7b436e760fb74f5dcde3685cd8a8eec78d40
