### ISSUE TITLE
User is undefined when not authenticated

### ISSUE THREAD

**Issue by camwhi-te** [pterodactyl/panel#4085]
### Current Behavior

When logging out (using the `develop` branch) I've run into issues with the page going blank (indicating a React error) with errors in the console such as (cannot read properties of undefined (reading 'rootAdmin')).

NOTE: This only affects the React side of the UI. Admin logouts are not affected.

[Image of error from browser console](https://cdn.discordapp.com/attachments/122902526751145984/978316796086083584/unknown.png)

### Expected Behavior

Able to logout with no errors.

### Steps to Reproduce

1) Use the latest commit from the `develop` branch
2) Login to your account, and then log back out
3) Blank // white screen is visible

### Panel Version

1.8.0 (Canary)

### Wings Version

1.6.1

### Error Logs

```bash
Specified in 'current behavior'
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by BlueTree242** [comment]
The user is undefined, not rootAdmin actually

**Comment by camwhi-te** [comment]
While that's likely the case, I've reported this issue using the root Admin property of the user as that's the error which was reported in the console.
I assume it is to do with the way the user data is sent over to the frontend in the Wrapper, as it uses the `Auth` library which I assume is being replaced with Sanctum

**Comment by Jelcoo** [comment]
Maybe it has something to do with https://github.com/pterodactyl/panel/blob/develop/app/Exceptions/Handler.php#L258 not executing

**Comment by camwhi-te** [comment]
Could be entirely wrong here, but I _believe_ it has something to do with this line:

https://github.com/pterodactyl/panel/blob/develop/resources/views/templates/wrapper.blade.php#L24

**Comment by BlueTree242** [comment]
it's related to fronted, user is fine being undefined, but what is not fine is not handling it properly, could be a fronted programming mistake tho
