### ISSUE TITLE
Cannot have a name below 5 characters in registration

### ISSUE THREAD

**Issue by TheoCGaming** [pterodactyl/panel#4086]
### Current Behavior

If I input "Ken" for example into the First Name field, it shows an error saying that the first name must be 5 characters or more.

### Expected Behavior

The name "Ken" is accepted as the first name.

### Steps to Reproduce

1. Attempt to register.
2. Input all needed info, but with a 3-letter first name (or last name). May also apply with other languages.
3. The error shows.

Extra Notes: This may show as "Working as Intended", but I can't register because of it. If it isn't fixed, I'll never be able to register with my real name or I'll only be able to register through panel invites.

### Panel Version

1.7.0

### Wings Version

1.6.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Ferks-FK** [comment]
This is really not a problem, it requires a name of 5 digits or more.

**Comment by notAreYouScared** [comment]
I'm not able to duplicate this issue... 

Are you running a theme? Or any plugins?

**Comment by Boy132** [comment]
> Attempt to register.

There is no way to register. An admin has to create an account for a user.
So you probably use a third party mod?

**Comment by DaneEveritt** [comment]
There is no registration logic in this software.

**Comment by FoksVHox** [comment]
@TheoCGaming @DaneEveritt
Actually there is in https://github.com/pterodactyl/panel/blob/develop/app/Http/Controllers/Admin/UserController.php#L146-L152. 
However, there is no validation rules, that would control the length of the first name.

**Comment by notAreYouScared** [comment]
That creates a user.... 

This doesn't allow the user to register for themselves, an admin has to create an account... 

There are also validation rules. See below

https://github.com/pterodactyl/panel/blob/b051718afe2cc69a7d395bfe27a628d7c36fa289/app/Models/User.php#L179

**Comment by TheoCGaming** [comment]
asking if the owner uses plugins, one second.

**Comment by TheoCGaming** [comment]
ah, "register addon" very specific.
