### ISSUE TITLE
Add Auto-Deploy token endpoint to Application API

### ISSUE THREAD

**Issue by krickler** [pterodactyl/panel#4089]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

In the panel, you can create an Auto-Deploy token. Having an endpoint with the same functionality in the application API would help with simplifying automated deployment of nodes, since you could just run a command to provision the node and don't have to mess with saving the API response to a file.

### Describe the solution you'd like.

Add an endpoint , for example 

`/api/application/nodes/${NODEID}/deploytoken`

that does the same thing as

`/admin/nodes/view/${NODEID}/settings/token`

**Comment by DaneEveritt** [comment]
If you have a token that can access nodes you can pull the configuration — the node deployment token is only created so that we can share the same underlying logic without having to tell the user to manually make a token.
