### ISSUE TITLE
ed25519_sk keys not accepted for SSH

### ISSUE THREAD

**Issue by mctom987** [pterodactyl/panel#4090]
### Current Behavior

Providing a ed25519_sk public key presents an error.
`The public key provided is not valid.`

### Expected Behavior

Key is accepted.

### Steps to Reproduce

Provide a public key generated from a security key, such as ed25519_sk

### Panel Version

1.8.0

### Wings Version

1.6.3

### Error Logs

```bash
None generated as a result of adding public key.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Can you provide an example public key of some sort I can use for testing purposes (and add as a test key in our suite). I have no such device that would generate one of these keys, so I had no way to test this instance.

**Comment by mctom987** [comment]
pub key looks like
```sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIBYNRlQBy5xS/Al2a05CNEEDthuCb1bV0fqSGF4qf17iAAAABHNzaDo=```

**Comment by DaneEveritt** [comment]
This looks like an issue with the library we use for parsing these keys, https://phpseclib.com/

As far as I can tell, it just isn't supported and so there isn't much I can really do on that front to help out unfortunately. I don't trust myself nearly enough to even consider building a custom parser for that key format.

Hopefully as it gains traction though we'll get some additional support down the road.

**Comment by tfinn345** [comment]
The issue is fixed in the libary [since](https://github.com/phpseclib/phpseclib/releases/tag/3.0.15), but still not working in the Panel with ed25519-sk but ed25519 without U2F is working.

Would be nice if you could still fix this.
