### ISSUE TITLE
add permission roles

### ISSUE THREAD

**Issue by Gaetann18** [pterodactyl/panel#4095]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

hello, I would like to have the possibility of doing predefined grades. So that when creating an account, you just have to add it to the rank so that it has access to the predefined functionality on several instances.

### Describe the solution you'd like.

Have the ability to create a rank, this one with specific permissions. When adding a user. He directly has his predefined permissions.

**Comment by Boy132** [comment]
Duplicate of #279

**Comment by Gaetann18** [comment]
sorry I didn't go further back in the tickets. I close it and wait impatiently
