### ISSUE TITLE
When updating wings all servers are stopped

### ISSUE THREAD

**Issue by ghostdevv** [pterodactyl/panel#4097]
### Current Behavior

Whenever I update wings and go back onto the panel all servers have stopped

### Expected Behavior

Restarting wings shouldn't interfere with the servers

### Steps to Reproduce

Have servers running
Update wings
servers stopped

### Panel Version

1.7.0

### Wings Version

1.6.3

### Games and/or Eggs Affected

all

### Docker Image

all

### Error Logs

```bash
https://ptero.co/oritadyjok
https://bin.ptdl.co/fnsfr/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
There is nothing that would cause all servers to stop unless you physically reboot the machine or restarted the docker service.

**Comment by ghostdevv** [comment]
Might have been a side effect of updating the system beforehand
