### ISSUE TITLE
Getting the FULL smtp logs

### ISSUE THREAD

**Issue by diamkil** [pterodactyl/panel#4098]
### Current Behavior

Here's the log I'm able to get:
[2022-05-30 12:16:57] production.ERROR: Expected response code 250 but got an empty response {"exception":"[object] (Swift_TransportException(code: 0): Expected response code 250 but got an empty response at /var/www/pterodactyl/cp/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:447)

### Expected Behavior

I would get a full error with the smtp response so that our smtp provider look into our issue

### Steps to Reproduce

Not exactly a bug

### Panel Version

1.7.0

### Wings Version

1.6.1

### Error Logs

```bash
Yeah those logs aren't enough for my need at the moment
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
I don't know what response you expect?

> got an empty response

I also do not control this dependency, it isn't something I'm going to put any time into addressing. Sorry.

**Comment by diamkil** [comment]
> I don't know what response you expect?
> 
> > got an empty response
> 
> I also do not control this dependency, it isn't something I'm going to put any time into addressing. Sorry.

I expect to be able to get the response that ptero is getting from the SMTP server. Google workspace support wants a message ID

**Comment by DaneEveritt** [comment]
Again, there is nothing to give you:

> Expected response code 250 but got an empty response
