### ISSUE TITLE
Uncaught Error: Call to undefined method Illuminate\\Foundation\\Exceptions\\ReportableHandler::firstClosureParameterTypes()

### ISSUE THREAD

**Issue by playaz44** [pterodactyl/panel#4099]
### Current Behavior

Error when updating the panel

### Expected Behavior

Correct panel update

### Steps to Reproduce

Just send in cli (update from 1.7.0 to 1.8.0) `php artisan p:upgrade`, follow [https://pterodactyl.io/panel/1.0/updating.html](url) or fresh install (with the same .env config) causes the same error:

`Uncaught Error: Call to undefined method Illuminate\\Foundation\\Exceptions\\ReportableHandler::firstClosureParameterTypes() in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/ReportableHandler.php:62\nStack trace:\n#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(234): Illuminate\\Foundation\\Exceptions\\ReportableHandler->handles()\n#1 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(414): Illuminate\\Foundation\\Exceptions\\Handler->report()\n#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(112): Illuminate\\Foundation\\Http\\Kernel->reportException()\n#3 /var/www/pterodactyl/public/index.php(68): Illuminate\\Foundation\\Http\\Kernel->handle()\n#4 {main}\n  thrown in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/ReportableHandler.php on line 62'`

System specs:

`Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye`

`PHP 8.0.19 (cli) (built: May 17 2022 18:49:03) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.19, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.19, Copyright (c), by Zend Technologies`

`[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
intl
json
libsmbclient
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
smbclient
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache`

`Composer version 2.3.5 2022-04-13 16:43:00`

`mariadb  Ver 15.1 Distrib 10.5.15-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper`

Do not close this bug report as always, more users have the same problem....

### Panel Version

1.8.0

### Wings Version

1.6.3

### Games and/or Eggs Affected

No

### Docker Image

No

### Error Logs

```bash
Uncaught Error: Call to undefined method Illuminate\\Foundation\\Exceptions\\ReportableHandler::firstClosureParameterTypes() in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/ReportableHandler.php:62\nStack trace:\n#0 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(234): Illuminate\\Foundation\\Exceptions\\ReportableHandler->handles()\n#1 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(414): Illuminate\\Foundation\\Exceptions\\Handler->report()\n#2 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(112): Illuminate\\Foundation\\Http\\Kernel->reportException()\n#3 /var/www/pterodactyl/public/index.php(68): Illuminate\\Foundation\\Http\\Kernel->handle()\n#4 {main}\n  thrown in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/ReportableHandler.php on line 62'
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
The guide you linked to doesn't show `php artisan p:upgrade` anywhere.

We also updated the guide to avoid running the self-update <https://pterodactyl.io/panel/1.0/updating.html#self-upgrade>

**Comment by parkervcp** [comment]
The also appears to be a duplicate of #3535 and it just needs a second run to fix.

**Comment by playaz44** [comment]
> The guide you linked to doesn't show `php artisan p:upgrade` anywhere.
> 
> We also updated the guide to avoid running the self-update https://pterodactyl.io/panel/1.0/updating.html#self-upgrade

Not working, the same error. I have done this update 20 times today with the same result, the error I gave earlier.

**Comment by playaz44** [comment]
I will add that the update commands themselves are without any problem, the entrance to the panel after the update generates this error.

**Comment by parkervcp** [comment]
Can you validate php versions.

```bash
## rhel based
yum list installed | grep php

## deb based
apt list --installed | grep php
```

**Comment by playaz44** [comment]
> Can you validate php versions.
> 
> ```shell
> ## rhel based
> yum list installed | grep php
> 
> ## deb based
> apt list --installed | grep php
> ```


```
root@vps15393:/var/www/pterodactyl# apt list --installed | grep php

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libapache2-mod-php8.0/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed,automatic]
php-common/bullseye,now 2:92+0~20220117.43+debian11~1.gbpe0d14e all [installed,automatic]
php-composer-ca-bundle/stable,now 1.2.9-1 all [installed,automatic]
php-composer-semver/stable,now 3.2.4-2 all [installed,automatic]
php-composer-spdx-licenses/stable,now 1.5.5-2 all [installed,automatic]
php-composer-xdebug-handler/stable,now 1.4.5-1 all [installed,automatic]
php-json-schema/stable,now 5.2.10-2 all [installed,automatic]
php-psr-container/stable,now 1.0.0-2 all [installed,automatic]
php-psr-log/stable,now 1.1.3-2 all [installed,automatic]
php-react-promise/stable,now 2.7.0-2 all [installed,automatic]
php-symfony-console/stable,now 4.4.19+dfsg-2+deb11u1 all [installed,automatic]
php-symfony-filesystem/stable,now 4.4.19+dfsg-2+deb11u1 all [installed,automatic]
php-symfony-finder/stable,now 4.4.19+dfsg-2+deb11u1 all [installed,automatic]
php-symfony-polyfill-php80/stable,now 1.22.1-1 all [installed,automatic]
php-symfony-process/stable,now 4.4.19+dfsg-2+deb11u1 all [installed,automatic]
php-symfony-service-contracts/stable,now 1.1.10-2 all [installed,automatic]
php8.0-bcmath/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0-bz2/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0-cli/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0-common/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0-curl/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0-fpm/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0-gd/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0-gmp/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0-igbinary/bullseye,now 3.2.6+2.0.8-6+0~20220131.33+debian11~1.gbp1d540e amd64 [installed,automatic]
php8.0-imagick/bullseye,now 3.6.0-4+0~20220117.35+debian11~1.gbp149f82 amd64 [installed]
php8.0-intl/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0-mbstring/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0-memcached/bullseye,now 3.2.0+2.2.0-1+0~20220421.38+debian11~1.gbp96ecac amd64 [installed]
php8.0-msgpack/bullseye,now 2.2.0~rc1+2.1.2+0.5.7-6+0~20220117.33+debian11~1.gbp304533 amd64 [installed,automatic]
php8.0-mysql/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0-opcache/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed,automatic]
php8.0-readline/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed,automatic]
php8.0-redis/bullseye,now 5.3.7+4.3.0-1+0~20220330.42+debian11~1.gbp6fe8b7 amd64 [installed]
php8.0-smbclient/bullseye,now 1.0.6-6+0~20220117.22+debian11~1.gbp04c19d amd64 [installed]
php8.0-xml/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0-zip/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b amd64 [installed]
php8.0/bullseye,now 1:8.0.19-1+0~20220517.33+debian11~1.gbpbb919b all [installed]
```

**Comment by playaz44** [comment]
New additional info:

![image](https://user-images.githubusercontent.com/9553500/171047921-ee9b2ea8-c418-4f6d-b675-fc9da6d8fb5b.png)
![image](https://user-images.githubusercontent.com/9553500/171047947-11b2d0fb-3f84-4300-b6d3-67cd354f3768.png)

**Comment by playaz44** [comment]
Solution is change php version from 8.0.x to 8.1.x.
