### ISSUE TITLE
404 on delete ssh keys on 1.8.1 panel

### ISSUE THREAD

**Issue by AgeraFly** [pterodactyl/panel#4100]
### Current Behavior

When trying to delete a newly created ssh key, I get the error **"Request failed with status code 404"**

### Expected Behavior

deleting a key

### Steps to Reproduce

1. Create a key in https://panel.urdomain.com/account/ssh
2. We are trying to delete the new key.
3. Nothing works

### Panel Version

1.8.1

### Wings Version

1.6.3

### Games and/or Eggs Affected

nothing to do with

### Docker Image

nothing to do with

### Error Logs

```bash
the error is not relevant
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Can confirm that on 1.8.1. No error in the logs, just `Request failed with status code 404`.

**Comment by camwhi-te** [comment]
Able to reproduce also.

**Comment by DaneEveritt** [comment]
I cannot reproduce this. My guess is there is something about the fingerprint for the key that is causing it to not parse correctly on lookup.

Does anyone have a public key they'd be willing to provide that I can use for testing this? None of the keys I've generated cause issues.

**Comment by EgoMaw** [comment]
Any SSH Key with a forward slash in the fingerprint will cause this.

I do have an SSH key I don't use with a slash in the fingerprint, I can share

**Comment by AgeraFly** [comment]
and in fact, there is a trait in my public key _/_ and this is a problem
