### ISSUE TITLE
[WINGS] Unexpected ZIP extraction behaviour: Dumps all files from the zip, including nested ones, effectively ignoring folders in the ZIP.

### ISSUE THREAD

**Issue by voyantt** [pterodactyl/panel#4101]
### Current Behavior

There is a wings bug that occurs when you unarchive a .zip in the file manager of your server. It basically dumps all the files in the .zip in the directory of the .zip in the .zip, effectively ignoring folders.
ex.
`example.zip`:
```
folder1
└── subfolder1
    ├── subfile1
    └── subfile2
folder2
├── file1
├── file2
└── file3
file4
file5
filen
```
When I use the unarchive function in the context menu in the `File Manager` tab the output is:
`/home/container`:
```
subfile1
subfile2
file1
file2
file3
file4
file5
filen
```

### Expected Behavior

The expected behaviour is given
`example.zip`:
```
folder1
└── subfolder1
    ├── subfile1
    └── subfile2
folder2
├── file1
├── file2
└── file3
file4
file5
filen
```
that the output would be
`/home/container`:
```
folder1
└── subfolder1
    ├── subfile1
    └── subfile2
folder2
├── file1
├── file2
└── file3
file4
file5
filen
```

### Steps to Reproduce

1. Verify the content of [example.zip](https://github.com/pterodactyl/panel/files/8800308/example.zip) on your local machine.
2. Create a server (panel 1.8.1, wings 1.6.3)
3. Upload [example.zip](https://github.com/pterodactyl/panel/files/8800308/example.zip) in the `File Manager` tab.
4. Extend [example.zip](https://github.com/pterodactyl/panel/files/8800308/example.zip)'s context menu and select Unarchive.
5. Compare content. The result should be as stated in `Expected Behavior` and `Current Behavior`.

### Panel Version

1.8.1

### Wings Version

1.6.3

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by volxymc** [comment]
Yo same.

**Comment by Antoine2lop** [comment]
I have the same bug.

**Comment by volxymc** [comment]
Ok so if youre self hosting pterodactyl you can unzip from ssh.
