### ISSUE TITLE
Add Networking Limitations

### ISSUE THREAD

**Issue by The-MG** [pterodactyl/panel#4105]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

With the new release of Pterodactyl v1.8.x and the introduction of the networking chart, there should be a way to configure how much a server can use at a time, and total through a month/year/day.

### Describe the solution you'd like.

In the admin panel it has an option for unlimited, and in the api, you can set it as well.

**Comment by notAreYouScared** [comment]
Docker itself has no way to enforce networking limitations.

**Comment by mrshadow-in** [comment]
Its Okay if limitation cant be implemented
but a meter can be added in console page will show how much bandwidth till time (not reset when restarting the server)

**Comment by notAreYouScared** [comment]
Total data usage was going to be added by a previous pr. But didn't make it. As in software noobs comment. Other tools are better for monitoring and logging stuff like that.

"In my opinion, trying to make Pterodactyl be a monitoring tool and manage all that data in a database is overkill. Should someone want this, they can use SNMP or Docker's own endpoints to collect it using dedicated monitoring tools like Grafana or LibreNMS which many hosts are doing right now."


https://github.com/pterodactyl/panel/pull/3802

**Comment by DaneEveritt** [comment]
Since Docker does not natively support this, I would have to build out custom logic within Wings to handle it, or use something like `tc` to manage the traffic.

Both of these seem like a nightmare for me, and the demand for this feature just doesn't line up with the effort required to make it work.
