### ISSUE TITLE
Eggs' docker images get automatically sorted

### ISSUE THREAD

**Issue by YusufYaser** [pterodactyl/panel#4106]
### Current Behavior

I set my docker images in an egg to this for example
```
Java 17|java-17:latest
Java 16|java-16:latest
Java 11|java-11:latest
Java 8|java-8:latest
```
Once I save the egg, it gets automatically sorted to this
```
Java 8|java-8:latest
Java 11|java-11:latest
Java 16|java-16:latest
Java 17|java-17:latest
```

It is not a huge deal, but it is a bit annoying.

### Expected Behavior

Docker images should not be automatically sorted by the panel as there is no reason to do that, the user can, just like how it acted before version 1.8.0 of the panel.

### Steps to Reproduce

Create an egg and put this in the docker images
```
Java 17|java-17:latest
Java 16|java-16:latest
Java 11|java-11:latest
Java 8|java-8:latest
```
Something like this could work too
```
something:latest
image:latest
abc:latest
test:latest
```

After you apply the changes, they will get automatically sorted.

### Panel Version

1.8.1

### Wings Version

1.6.3

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
That is numerical order 8 being the lowest and 17 being the highest. I don't see an issue here as most people probably expect them to be in that order.

**Comment by YusufYaser** [comment]
> That is numerical order 8 being the lowest and 17 being the highest. I don't see an issue here as most people probably expect them to be in that order.

I see that it's better to let the user order them the way they like

**Comment by Boy132** [comment]
I can't reproduce that. For me the images stay in the order I entered them.

**Comment by YusufYaser** [comment]
> I can't reproduce that. For me the images stay in the order I entered them.

What images did you test? Did you try the one I put in the issue? Which panel version are you using?
I’ve tested it on two different panel installations

**Comment by Boy132** [comment]
> > I can't reproduce that. For me the images stay in the order I entered them.
> 
> What images did you test? Did you try the one I put in the issue? I’ve tested it on two different panel installations

I used the examples you provided:
```
Java 17|java-17:latest
Java 16|java-16:latest
Java 11|java-11:latest
Java 8|java-8:latest
```
And they stayed in this order.

**Comment by YusufYaser** [comment]
> > > I can't reproduce that. For me the images stay in the order I entered them.
> > 
> > 
> > What images did you test? Did you try the one I put in the issue? I’ve tested it on two different panel installations
> 
> I used the examples you provided:
> 
> ```
> Java 17|java-17:latest
> Java 16|java-16:latest
> Java 11|java-11:latest
> Java 8|java-8:latest
> ```
> 
> And they stayed in this order.

How about the panel version? Just tested it again on 1.8.1 now and it still automatically get sorted

**Comment by YusufYaser** [comment]
I’m using the default panel too, I did not modify its code.

**Comment by Boy132** [comment]
> How about the panel version? Just tested it again on 1.8.1 now and it still automatically get sorted

I'm also on 1.8.1, no modifications.

**Comment by parkervcp** [comment]
Part of this may be your browser organizing the list.

**Comment by Boy132** [comment]
> Part of this may be your browser organizing the list.

Thought about that too. I tested with Opera GX, Firefox and Edge and can't reproduce it with any of these three.

**Comment by YusufYaser** [comment]
> Part of this may be your browser organizing the list.

I use the new Microsoft Edge (Chromium)

**Comment by YusufYaser** [comment]
Tried it also on my phone on Safari, it still sorts

**Comment by matthewpi** [comment]
This is because the images are stored as a JSON object, not text.  This may be addressed if we change the way eggs are stored and imported/exported, but I don't see why we should go out of our way to solve what some people would consider a feature.
