### ISSUE TITLE
Nodes\SystemInformationController

### ISSUE THREAD

**Issue by Hamsterliebe** [pterodactyl/panel#4107]
### Current Behavior

If i try to do ANYTHING, i get this Error...

In RouteAction.php line 92:
                                                              
  Invalid route action: [Nodes\SystemInformationController].

### Expected Behavior

I honestly wanted to install Addons and a Theme with an Automatic Installer (https://github.com/finnie2006/PteroFreeStuffinstaller/) and now i get this Error... The Author meant, that this is a Problem on my Side, not on the Installer Side

### Steps to Reproduce

https://github.com/finnie2006/PteroFreeStuffinstaller/ 
Run the Installer, install Addons and Themes and BAM! Your done :(

### Panel Version

Panel@1.8.0

### Wings Version

Wings@1.6.3

### Games and/or Eggs Affected

The whole Panel has a "500 | Server Error"

### Error Logs

```bash
https://ptero.co/bysacymaxi
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
This isn't an issue with the Panel, as far as I can see

**Comment by Hamsterliebe** [comment]
I can't go in the Panel at all and i honestly don't want to reboot the Server because i don't know if everything will work after that..

**Comment by Goksi** [comment]
Anyway, this is not panel related issue

**Comment by parkervcp** [comment]
So far as I can tell is that you ran their installer and it broke your panel install. I am unsure how this is a panel issue.

**Comment by Hamsterliebe** [comment]
After a reupgrade of the last Panel Update, it fixed everything. As it is now fixed, i can close this Issue
https://pterodactyl.io/panel/1.0/updating.html
