### ISSUE TITLE
Bug with displaying servers on dashboard

### ISSUE THREAD

**Issue by Futuraura** [pterodactyl/panel#4108]
### Current Behavior

It shows an error on dashboard Cannot read properties of undefined (reading 'pagination')

### Expected Behavior

Servers should display like normally they do

### Steps to Reproduce

Just install it on ubuntu 22.04 server and instead mariadb and ngnix use Mysql-server and apache2

### Panel Version

1.8.1

### Wings Version

1.6

### Games and/or Eggs Affected

None

### Docker Image

None

### Error Logs

```bash
wings: https://ptero.co/apijemufas
panel: http://bin.ptdl.co/j0hip
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Seeing as no one else has reported this issue I doubt this is a bug with the software — the only way this would happen is if something is sitting and modifying the response data between your browser and the server.
