### ISSUE TITLE
Delay to show the display name (alias) on docker images

### ISSUE THREAD

**Issue by AlexysSMC** [pterodactyl/panel#4109]
### Current Behavior

When I refresh the page on the Startup tab I can see for a second the docker image. (I am using display names)

### Expected Behavior

Must display instant the alias.

### Steps to Reproduce

Here is a video: https://cdn.discordapp.com/attachments/284416495189098498/981227739019374682/2022-05-31_19-07-59.mp4

### Panel Version

1.8.1

### Wings Version

1.6.3

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
This is just because the dropdown defaults to the server's current image while it waits for the other images to load in. I'm not blocking the UI render for that.
