### ISSUE TITLE
Database Deletion Error

### ISSUE THREAD

**Issue by ndisalvio3** [pterodactyl/panel#4114]
### Current Behavior

When a admin tries to delete a DB from the backend it errors out with an Error 404 in the web console.

### Expected Behavior

Database is deleted properly.

### Steps to Reproduce

Create a database.
Go to /admin/servers/view/4/database.
Click on the Delete button.

### Panel Version

1.8.1

### Wings Version

1.6.4

### Error Logs

```bash
Error does not appear in logs.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by PsyloZ** [comment]
Hello mate, i have same problem as you !

**Comment by Boy132** [comment]
Can confirm that on v1.8.1.
`Failed to load resource: the server responded with a status of 404 ()` in browser console.

**Comment by ghost** [comment]
Can confirm, same issue on v1.8.1
