### ISSUE TITLE
Invisible underscores on firefox in the console window

### ISSUE THREAD

**Issue by TsjipTsjip** [pterodactyl/panel#4115]
### Current Behavior

In firefox, the glyphs in the server console are cut off at the bottom, causing underscores to disappear outright.

I have been told this is not the case on other browsers, however do not have the means to confirm this.

### Expected Behavior

Glyphs display properly and fully.

### Steps to Reproduce

Go on firefox and open the "Console" tab of any server. Observe how any underscores that appear are not visible at all.

![image](https://user-images.githubusercontent.com/19798667/171893537-1ff8d015-219a-41e0-8e00-086fd1eac825.png)

On a last note: This appears to be exactly the same bug as https://github.com/pterodactyl/panel/issues/3449 . My firefox version is version 101.0, but this issue has been around for quite some time. I only just made a report about this now.

### Panel Version

1.8.1

### Wings Version

1.6.4 (Not relevant)

### Games and/or Eggs Affected

All eggs (Not an egg issue)

### Docker Image

All images (Not an image issue)

### Error Logs

```bash
No error logs relevant
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
I can confirm that
Firefox version: 101.0 (64-bits)

**Comment by parkervcp** [comment]
Is this only with three underscores or all underscores?

**Comment by TsjipTsjip** [comment]
Allow me to clarify: This is not an issue specific to underscores, but you notice it the most with underscores. All glyphs in the terminal are offset so that the bottom part is cut off. With an underscore, that's all there is to the glyph, but this is an issue with all glyphs. (Likely a font issue?)

I will attempt to get a side-by-side comparison.

**Comment by FC-FailCoder** [comment]
I'm using firefox 101.0 (64) - I am not having this issue and I don't think I have encountered it in other versions (could just be me though not realising it). However, your font looks slightly different to mine. So I'm guessing it is a font issue.

![image](https://user-images.githubusercontent.com/45609819/171905940-70ea4fc1-f9f2-418b-91ed-5520dbbe9790.png)

**Comment by TsjipTsjip** [comment]
At this point I am quite sure my own firefox installation is broken. I've noticed multiple issues with how fonts are displayed, many of which are not strictly limited to my panel. I'm happy to have this issue closed because of this, I'll likely be switching browsers sooner or later as the firefox snap for Ubuntu has had multiple issues for quite a while now (though never so severe as now, not sure what happened to trigger this).

Also can confirm that this is NOT an issue on Chromium Version 102.0.5005.61 (Official Build) snap (64-bit).

**Comment by DaneEveritt** [comment]
I was going to say, I just tried to reproduce this and cannot. It also looks like the font isn't even loading in correctly for you.
