### ISSUE TITLE
Disable autocapitalization on console input

### ISSUE THREAD

**Issue by kmecpp** [pterodactyl/panel#4116]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

On mobile console commands are autocapitalized which is fairly annoying

### Describe the solution you'd like.

Add the tag `autocapitalize="none"` to the console input form (https://stackoverflow.com/a/5171812/3476226)

**Comment by notAreYouScared** [comment]
Are you sure that's just not your keyboard on your phone?... as it doesn't auto capitalize on desktop... I feel setting that variable wouldn't help.

**Comment by DaneEveritt** [comment]
It does help — those target mobile devices usually.
