### ISSUE TITLE
Minor UI improvements for creating new eggs

### ISSUE THREAD

**Issue by kmecpp** [pterodactyl/panel#4117]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

1) Selecting a nest and then clicking new egg disregards the selected nest and defaults to putting it in Minecraft which is confusing.

2) Also, somewhat related, importing an egg defaults to using Minecraft, but even though I do use almost exclusively Minecraft eggs, I still think it would be better to not have a default nest for importing eggs. When importing an egg I usually am not thinking about the nest and upload the file and then click import. But then only later do I realize it's not in the right place and have to delete it and start over again. The nest field is "required" but this label is meaningless with one already selected because you can only change it to another nest. It makes the most sense to require the user to select a nest. As is, the user is not actually required to select a nest.

### Describe the solution you'd like.

1) Auto populate the "Associated Nest" field when creating a new egg with the nest the user had selected when they clicked the button

2) Don't auto select the Minecraft nest when importing a new egg

**Comment by notAreYouScared** [comment]
Will probably be closed due to v2 coming soon and it's a redesigned  admin area.

**Comment by matthewpi** [comment]
This entire flow is different in v2, I don't intend to spend time messing around with the current admin to fix issues that have already been resolved.
