### ISSUE TITLE
Add back the 0.7x statistics admin

### ISSUE THREAD

**Issue by Florin4226** [pterodactyl/panel#4118]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hi, I thought it would be a great idea to add back the statistics with the node to see how much ram  was consumed as well as storage and processor.
![image](https://user-images.githubusercontent.com/50134081/172018712-35a5fc23-1efa-45eb-9eae-cb2805728cfb.png)

### Describe the solution you'd like.

- Add to the admin a section as I said above if it could be great!

**Comment by DaneEveritt** [comment]
I'm not interested in re-building this screen given the upcoming changes to the admin area, and don't wish to leave an issue open that I'm realistically not going to ever focus on.

**Comment by zudsniper** [comment]
Not to re-open, but this would be really nice. I'm not a PHP developer, but I would be interested in this project. Commenting so I can remember this. Thank you for all the work you've done Ptero devs!
