### ISSUE TITLE
Schedules didnt trigger correctly

### ISSUE THREAD

**Issue by DJKenzoDE** [pterodactyl/panel#4119]
### Current Behavior

i have made a schedule to send command every 5 min but thay trigger 3/4 times every 5 minutes and then gives 1/2 times that triggers after 10 minutes

### Expected Behavior

trigger schedules every 5 minutes

### Steps to Reproduce

create the schedules in the web panel

### Panel Version

1.7.0

### Wings Version

1.6.1

### Games and/or Eggs Affected

Minecraft Paper

### Docker Image

java_17

### Error Logs

```bash
wings: https://ptero.co/fifofeqide

panel: http://bin.ptdl.co/57o12 - from 29-05-2022. is latest log in the directory
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DJKenzoDE** [comment]
screenshot from the console: https://prnt.sc/WNhaD4DCrHWU

**Comment by DaneEveritt** [comment]
The schedules run fine — either you have an issue that causes your Panel and Wings to be unable to connect to eachother, or you have multiple scheduler instances running. Either way there is not nearly enough information here for me to even begin guessing at your issue.
