### ISSUE TITLE
Adding new variable to service option without input rules results in 500 error

### ISSUE THREAD

**Issue by parkervcp** [Pterodactyl/Panel#412]
Development Build Testing

While adding a service option variable, and leaving it blank, the page 500's.

service > option > new variable to the panel 

See attached gif
[500 error while adding variable](http://i.imgur.com/ORhd7uV.gif)

**Comment by KasperFranz** [comment]
As i am not 100% sure what the meaning with this was (the problem origin) 
here is the problem: https://github.com/Pterodactyl/Panel/blob/develop/app/Repositories/VariableRepository.php#L60

**Comment by DaneEveritt** [comment]
I fixed the issue @KasperFranz mentioned which should fix the 500 error. All variables *must* have rules defined though, there is no getting around that.
