### ISSUE TITLE
FQDN error with an IPv4 adress

### ISSUE THREAD

**Issue by m1auch4t** [pterodactyl/panel#4122]
### Current Behavior

I basically cannot create a node because there's a "FQDN error", but it literally uses the same adress as my pterodactyl panel.

![image](https://user-images.githubusercontent.com/67514126/172048403-20d505d4-a27d-439a-bbd4-88dfbfc15cf7.png)

### Expected Behavior

I expected the site to create a node.

### Steps to Reproduce

Install pterodactyl panel and wings
Go to your website, for me its host.catlivid.xyz
Create a location (works fine for me)
Try to create a node (doesnt work for me)

### Panel Version

1.8.1

### Wings Version

1.6.4

### Games and/or Eggs Affected

None, i cannot create a node

### Docker Image

None, i cannot create a node

### Error Logs

```bash
Well, there are no wing logs because i cannot create a node, therefore wings do not have a config

Also cant get pterodactyl panel logs.
"tail: cannot open '/var/www/pterodactyl/storage/logs/laravel-2022-06-05.log' for reading: No such file or directory"
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jelcoo** [comment]
FQDN means Fully Qualified Domain Name, and an IPv4/6 address isn't a domain name. This means its intentional.

**Comment by Goksi** [comment]
> FQDN means Fully Qualified Domain Name, and an IPv4/6 address isn't a domain name. This means its intentional.

You can use ip as fqdn as long as you are not using ssl, also I think this kind of question is for [Discord server](https://discord.gg/CZgyjucX)

**Comment by trenutoo** [comment]
It means that the panel machine is unable to resolve the domain to any valid IP address. You have to make sure its DNS can resolve it, e.g use dig or nslookup to test. 

At the time of this comment, the domain points to two different Oracle IPs, which might suggest you are currently modifying them.
