### ISSUE TITLE
Server Freeze after Update

### ISSUE THREAD

**Issue by Domisiding** [pterodactyl/panel#4123]
### Current Behavior

The servers start and run without problems. After a while the server just goes into the fatal error below. In the meantime, the servers also freeze during a join.

### Expected Behavior

The server should not get a freeze / fatal error 

### Steps to Reproduce

Unfortunately, we have no evidence of possible reproducing. This problem has happened, but on several wings and with different images.

### Panel Version

1.8.1

### Wings Version

1.6.4

### Games and/or Eggs Affected

Minecraft (Paper)

### Docker Image

quay.io/pterodactyl/core:java-8-zulu

### Error Logs

```bash
https://paste.mykns.net/korecajalu.go
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
This is not a bug with Pterodactyl.
