### ISSUE TITLE
SFTP username remains the same after changing server ownership

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#4126]
### Current Behavior

When changing server ownership to another user via **/admin/servers/view/<server_id>/details**, the SFTP username remains the same.

Haven't checked this, but I wonder if the SFTP password remains the same, too.

### Expected Behavior

SFTP username (and password) should change to match the new owner's details on server ownership change.

### Steps to Reproduce

1. Create a server
2. Navigate to the admin server view (/admin/servers/view/<server_id>/details)
3. Click the 'Details' tab
4. Change the server ownership to someone else
5. Click 'Update Details'
6. Click the icon at the end of the menu (the external link icon) to open the server view
7. Click the 'Settings' tab
8. Observe SFTP details

### Panel Version

1.7.0

### Wings Version

N/A

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by yesBad** [comment]
SFTP username and password comes from the user logged in. 
Lets say both Bad & Dad have permission to use SFTP, if Bad views it it will show bad.xxxxxx and it will let use bad's password. But if Dad views it then he will see dad.xxxxxxx and it will let use dad's password.
bad example but u get point

**Comment by DaneEveritt** [comment]
This is not a bug — usernames are per user and server, not tied to the server owner.
