### ISSUE TITLE
Use generic value for Username

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#4128]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Since the Username is only really useful for SFTP, it would be nice if it was automatically generated using a format similar to the Short UUID format that is used on servers.

This would be most helpful for sub-user usernames, as they are currently automatically generated using the alias of an email address, followed by 3 random characters. Not the best implementation in my honest opinion.

Additionally, usernames shouldn't be able to login to the panel, only email addresses. And usernames should not be allowed to be set manually by users/admins or via the API.

### Describe the solution you'd like.

N/A

**Comment by DaneEveritt** [comment]
I don't plan on changing how usernames are generated at this time.
