### ISSUE TITLE
Wrong units used in console / wrong value conversion

### ISSUE THREAD

**Issue by LOENS2** [pterodactyl/panel#4133]
### Current Behavior

The values for memory, disk and network activity shown in the console are in mebibytes or kibibytes but are labeled with megabytes or kilobytes.

### Expected Behavior

The values should be converted according to the units shown in the console

### Steps to Reproduce

Get the byte value via ```https://pterodactyl.file.properties/api/client/servers/1a7ce997/resources``` and devide it by 1048576 to get the value in mebibytes. This value is shown in the console. If you devide the byte value by 1000000, you get the value in megabyte, but it doesn't match te value given in the console.

### Panel Version

1.8.1

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Goksi** [comment]
Pretty sure its intended to work like that as MB  also can  be interpreted as 2^20 bytes. Term mebibyte might be confusing to end user

**Comment by LOENS2** [comment]
It really confused me, because i had different values in Grafana (right megabyte conversion) and thought that my exporter made a wrong conversion, but upon realizing it was actually mebibytes in the panel, I now ask myself why it isn't converted correctly.

**Comment by DaneEveritt** [comment]
> This value is shown in the console

What does this mean? We don't output anything into the console like this.

**Comment by Clarkcj12** [comment]
I believe he is talking about the console graphs displayed on the servers console page.

**Comment by LOENS2** [comment]
@DaneEveritt 
I'm talking about the server console in the panel for the docker container. On the left side of that window are the server stats I'm referring to. 
Sorry for the miscommunication

**Comment by trenutoo** [comment]
[The math used for conversion is bytes / 1024](https://github.com/pterodactyl/panel/blob/develop/resources/scripts/helpers.ts#L3-L14), which indeed is a kilobyte (KiB) and mebibyte (MiB), and so forth. However, the values converted and displayed are something that is displayed to a human, and the majority of average users will not know the difference between KiB and kB as there's no acceptance in the industry for it, even though it's the accepted standard for base 2. 

The latter is usually always displayed to the end-user in many operating systems and software, even if 1024 is used in computer science to calculate it. Although, usually it's only used in disk space, can be seen a lot in memory too. It's a matter of decimal vs binary. Kilobyte is 1000 in decimal, but 1024 in binary. Programmers tend to use binary.

Dane either did it for the reasons of human-readable values as the function is called (heh) or forgot it himself.

**Comment by DaneEveritt** [comment]
This was changed in 1eb3ea2ee4ebf98ccc72a112ff5602670a28a130 to now use `1000` as the base for all conversions in the Panel.
