### ISSUE TITLE
Using slim.AI

### ISSUE THREAD

**Issue by 766974616c79** [pterodactyl/panel#4134]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

With the following solution, you can reduce the size of docker images

### Describe the solution you'd like.

Using slim.AI

### Additional context to this request.

https://portal.slim.dev/home

**Comment by DaneEveritt** [comment]
This appears to just be a drive-by request with a link to a service — if there is some specific actionable task you'd like to see performed you're welcome to open a new issue with sufficient detail, but I ask that we not have issues opened that are just links to random SaaS offerings.
