### ISSUE TITLE
Create Server - Better User Search

### ISSUE THREAD

**Issue by Maximilian1021** [pterodactyl/panel#4135]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to see an improved user search. Currently, no result is found when searching for the username. Only when I go to the mail, the user is found.

### Describe the solution you'd like.

When searching for users when creating a server, please also pay attention to the usernames!

### Additional context to this request.

You are doing a great job and I am looking forward to more updates!

**Comment by Jelcoo** [comment]
This will be probably fixed when v2 comes out

**Comment by DaneEveritt** [comment]
Won't be changing anything — V2 won't be released for quite some time but this is such a minor inconvenience in the grand scheme of things and I'm just not interested in dealing with that nightmarish old code right now.

Additionally, it is likely that usernames get dropped in the future anyways — I don't recommend trying to search using them.
