### ISSUE TITLE
Pull files endpoint returns no content

### ISSUE THREAD

**Issue by devnote-dev** [pterodactyl/panel#4140]
### Current Behavior

When requesting the `/api/client/servers/<id>/files/pull` endpoint, the API is supposed to return either a HTTP 202 response with the current download's identifier, or a HTTP 200 response with the path to the downloaded file in the server. Instead, the response from Wings is not returned at all, but a HTTP 204 response.

### Expected Behavior

The endpoint should return either a HTTP 200 response with the downloaded file path, or a HTTP 202 response with the download identifier.

### Steps to Reproduce

1. Make a POST request to `/api/client/servers/<id>/files/pull` with the following request body:
```json
{
  "url": "https://gist.githubusercontent.com/TekExplorer/11d81a3eea4a924c9332eea109995297/raw/9f3e0a791bc885248d00630e66bf351d25bfc72e/main.dart",
  "use_header": true,
  "foreground": true
}
```
2. The API will respond with a HTTP 204 response.

### Panel Version

1.8.1

### Wings Version

1.6.4

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
N/A
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
This works as intended.

https://github.com/pterodactyl/panel/blob/develop/app/Http/Controllers/Api/Client/Servers/FileController.php#L277

**Comment by Boy132** [comment]
I believe he misslabed this issue: it's a feature request and not a bug report.
