### ISSUE TITLE
API not working after updating panel to newest version (1.18.1)

### ISSUE THREAD

**Issue by sakulmore** [pterodactyl/panel#4147]
### Current Behavior

Hello, new API not working. [See image here](https://i.imgur.com/PI8wFir.png).

### Expected Behavior

After updating panel and wings to latest versions, the API no longer working. I tried generate new API, but the issue is same.

### Steps to Reproduce

Create your server (on any game, does not matter on game). Then create API and follow as in the API documentation (client -> server -> send command)

Then create in, for example, root file on your server file called for example "vip.sh". Then open it and write there that code which is in the api docs.

Then try type in putty (SSH) command "./vip.sh" and hit Enter. Then you should see the error that is in the image above.

### Panel Version

1.8.1

### Wings Version

1.6.4

### Games and/or Eggs Affected

All games (doesn't matter on game)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
This is not a bug, you're trying to use the API and sending along cookies which leads it to believe you're within the confines of a web browser, thus additional protections are used. You're welcome to use the API & Modding channel to figure out the correct approach, but this isn't a bug.
