### ISSUE TITLE
Wings won't start. HTTP error.

### ISSUE THREAD

**Issue by mrFavoslav** [pterodactyl/panel#4151]
- [X] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

### Current Behavior

When try to start wings it returns

`FATAL: [Jun 20 15:20:58.428] failed to load server configurations error=http: request creation failed: Get "https://panel.large-lands.tk/api/remote/servers?page=0&per_page=50": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

`Stacktrace:
Get "https://panel.large-lands.tk/api/remote/servers?page=0&per_page=50": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
http: request creation failed`

### Expected Behavior

Wings should start and connect to the API.

### Steps to Reproduce

Setup pterodactyl from https://pterodactyl.io/panel/1.0/getting_started.html and run wings.

### Panel Version

1.8.1

### Wings Version

1.6.4

### Error Logs

```bash
http://bin.ptdl.co/0qmpt
https://ptero.co/iryregaluj
```

### Is there an existing issue for this?

**Comment by parkervcp** [comment]
If your panel even running right now? That url is timing out.

**Comment by mrFavoslav** [comment]
It should be. It worked until yesterday just fine. This afternoon I tried to connect to my panel and.. nothing.. so i tried wings --debug cmd and it gived me this err.. nothing changed (i guess).. no files edited, nothing.. wings just don't want to start.. something similar has happened to me before but reboot has always solved it.. now I rebooted it about ten times..

**Comment by mrFavoslav** [comment]
every service I can remember has status running.. even wings...

everything should work fine.. but it still does not

**Comment by DaneEveritt** [comment]
This is not a bug with this software.
