### ISSUE TITLE
Unauthenticated error after boot of browser/pc

### ISSUE THREAD

**Issue by 1Euro7Cent** [pterodactyl/panel#4153]
### Current Behavior

When I start my pc and the browser a server is always poping up. Its always showing error Unauthenticated (Failed to load resource: the server responded with a status of 401 (Unauthorized))

![image](https://user-images.githubusercontent.com/67194495/174648436-b129aea6-68f5-4945-9740-33a0c451ee76.png)

after a site reload the error is gone, and I cannot reproduce it unless I restart my pc

### Expected Behavior

to go strait into the servers view

### Steps to Reproduce

Open a server (/server/id)
have in browser settings that all tabs get reopened
reboot pc (i only tested shutdown and start on the next day)

see the Unauthenticated error after starting browser

Opera Gx browser

it happened first after i installed the latest update

### Panel Version

1.8.1

### Wings Version

1.6.4

### Error Logs

```bash
wings(I don't think that is useful): https://ptero.co/ubygyquxiw

cannot get logs for panel
edit: there is actually a log folder. but the latest file is from 16.6


```
```
root@mrpanel:/home/thomas# tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99
tail: cannot open '/var/www/pterodactyl/storage/logs/laravel-2022-06-20.log' for reading: No such file or directory
Use netcat.
```
netcat is installed (support bot in dc's suggestion) https://discord.com/channels/122900397965705216/658550982975946762/988488666575933500

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Seems like an issue with your browser and/or server setup, it is highly unlikely this is an issue with Pterodactyl and I will not be investigating it further at this time.
