### ISSUE TITLE
Let urls take the scheme of the Document

### ISSUE THREAD

**Issue by joost00719** [pterodactyl/panel#4159]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When hosting Pterodactyl behind a reverse proxy it is a pain to use the Admin environment, especially in a .dev tld because you get prompted if you really want to send form-data over an insecure connection (http)
Since hosting on port 80 without https behind a reverse proxy very common, my suggestion is to let the browser decide whether or not to use http or https.

### Describe the solution you'd like.

Use //<FQDN>/ instead of Instead of using http://<FQDN>/ to build URI's so the browser decides whether to use http or https.
This way it does not conflict when running a reverse proxy on https only.

**Comment by TekExplorer** [comment]
I've never had an issue with using a reverse proxy

Just set the app_url in the .env to include https and proxy away

**Comment by matthewpi** [comment]
You may also need to set the `TRUSTED_PROXIES` environment variable.
