### ISSUE TITLE
Can No Remove Disconnected Servers

### ISSUE THREAD

**Issue by myxxmikeyxx** [pterodactyl/panel#4166]
### Current Behavior

When you try to remove a node that is offline it will not let you if it has any servers. Then when you try to remove a server from an offline node it will not let you because the node it offline. 

### Expected Behavior

A way to force remove a server and node. The force option does not work if the server is offline or not in use anymore.

### Steps to Reproduce

I had a server that I was paying for but wanted to switch to self-hosting my own server. I stopped paying for my cloud one but could not remove it from my panel because of the above problems. Can this feature be added, maybe under advance settings or something hidden. If not, what are the sql database commands to remove a server and a node? I trued googling for this but got nothing useful. I ended up just dropping the whole database for the panel and starting over but would not like to do this again/ help someone else who might be in the same boat as me.

### Panel Version

1.8

### Wings Version

1.6

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
You can already force delete a server.

**Comment by myxxmikeyxx** [comment]
The problem is I keep getting 500 Server Error
