### ISSUE TITLE
Panel Irresponsive for Mobile while server installation of while transferring to another node.

### ISSUE THREAD

**Issue by RTK23-dev** [pterodactyl/panel#4167]
### Current Behavior

When the server is installing or transferring it isn't responsive, texts are out of box.
![Screenshot_2022-06-27-09-25-31-120_com android chrome](https://user-images.githubusercontent.com/77203747/175857200-e304f0ad-faac-41bc-a277-f89ead663162.jpg)
![IMG_20220627_092328](https://user-images.githubusercontent.com/77203747/175857205-f24de6b7-3b15-404f-a643-22017c899e05.jpg)

But for desktop users it's fine.
This isn't a big deal for small eggs and servers which doesn't takes much time to install / transfer but for the people who are using this panel for their business, it could be a bit annoying.

### Expected Behavior

Texts should be in the box or the box should be in a rectangular condition for texts to fit in, some CSS should fix it.

### Steps to Reproduce

1. Be on mobile ( no desktop site ).
2. Create a server and go to it when it's installing it should he visible to you as well.
3. You can also transfer your server to any other node and go to console while it's transferring and texts would be out of box.

### Panel Version

1.9.0

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
Fixed in https://github.com/pterodactyl/panel/commit/bd278b2688d3a9422f0c1e1dd332b9b5a4e3c3f5
