### ISSUE TITLE
Problem with 1.9.0

### ISSUE THREAD

**Issue by jggunter** [pterodactyl/panel#4169]
### Current Behavior

When running `yarn build:production` it outputs:
```
root@panel-main:/var/www/pterodactyl# yarn build:production
yarn run v1.22.19
$ yarn run clean && cross-env NODE_ENV=production ./node_modules/.bin/webpack --mode production
$ cd public/assets && find . \( -name "*.js" -o -name "*.map" \) -type f -delete```
It stayed here for 15+ minutes, and did not move.

### Expected Behavior

It usually goes through but it did not this time.

### Steps to Reproduce

Fix whatever error is causing it to freeze at
```
root@panel-main:/var/www/pterodactyl# yarn build:production
yarn run v1.22.19
$ yarn run clean && cross-env NODE_ENV=production ./node_modules/.bin/webpack --mode production
$ cd public/assets && find . \( -name "*.js" -o -name "*.map" \) -type f -delete```.

### Panel Version

1.9.0

### Wings Version

1.6.0

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by HerrSammyDE** [comment]
same https://ptero.co/amiqewaxan.typescript

**Comment by gOOvER** [comment]
are you using a Mod?  Because i the upgrade Guide  nowhere yarn is used?

Ah, you both use the Docker Version of Ptero :)

**Comment by HerrSammyDE** [comment]
> are you using a Mod? Because i the upgrade Guide nowhere yarn is used?
> 
> Ah, you both use the Docker Version of Ptero :)

no, "yarn build:production" is required to build the project

**Comment by HerrSammyDE** [comment]
maybe fix:
> delete the "**resources**" folder once and paste it from the **1.9.0 version**.

**Comment by ghostdevv** [comment]
The guide here shows you how to update <https://pterodactyl.io/panel/1.0/updating.html> - it doesn't require yarn because you install the already built version of the panel
