### ISSUE TITLE
Profile icon

### ISSUE THREAD

**Issue by LilSadPanda** [pterodactyl/panel#4170]
### Current Behavior

At this moment the profile icon is only displayed in the user end and not the admin panel. 

### Expected Behavior

Profile icon is expected to be displayed in the admin panel as well. 

### Steps to Reproduce

Update panel to 1.9.0

### Panel Version

1.9.0

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jelcoo** [comment]
I would assume the admin icon will be replaced once v2 comes out, since that is written in React.

**Comment by DaneEveritt** [comment]
This is currently intentional and does not require an issue for tracking.
