### ISSUE TITLE
Don't show the blue line on graphs when data hasn't been measured yet

### ISSUE THREAD

**Issue by CayeOficial** [pterodactyl/panel#4176]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When you go into the panel to a server, it shows a blue line at y=0 on the graphs if the data was not measured yet.
![image](https://user-images.githubusercontent.com/73038322/175916976-420478b7-73b6-4d10-86c7-b78062dfb9df.png)
For example, in CPU usage, it can sometimes be confused with the cpu being at 0% (it has happened to me)
So if that line didn't show up, it would be a clear difference between "unmetered data" and "0% usage", and it would avoid a lot of confusion as well as aesthetically looking prettier.
Example:
![imagen_2022-06-27_115923998](https://user-images.githubusercontent.com/73038322/175917292-611280e0-c308-4ee0-a4ab-d3a7f272df90.png)

### Describe the solution you'd like.

I would like to remove the blue line if the data hasn't been measured yet.

**Comment by DaneEveritt** [comment]
closed in 5f156e193a16db00e25e116c4d36e4ca10923bce
