### ISSUE TITLE
Can't see console during install as admin

### ISSUE THREAD

**Issue by LukasW1337** [pterodactyl/panel#4177]
### Current Behavior

![image](https://user-images.githubusercontent.com/33436545/175917890-ed09142f-5f3c-4aec-a7bb-5d81a2db32d1.png)
Admins get shown the "installer running" screen as a normal user would.

### Expected Behavior

Admins can follow along in the install log, and monitor system usage. 

### Steps to Reproduce

Be an admin, reinstall or install a server. 

### Panel Version

1.9.0

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by LukasW1337** [comment]
This only happens when you click console on the top nav bar.

https://panel.wiwihosting.dk/server/6dcf11fd - Console is working , we can see it as usual
https://panel.wiwihosting.dk/server/6dcf11fd/ - Installer is running blocks

**Comment by LukasW1337** [comment]
This aparently only happens when your route isn't correct. 

https://panel.com/server/6dcf11fd - working as normal, can see console
https://panel.com/server/6dcf11fd/ - shows installing screen

When you click console in the top nav you get redirected to the one with /, and thefore it doesnt work

**Comment by gOOvER** [comment]
Can confirm; i have the same problem
