### ISSUE TITLE
Error when installing.

### ISSUE THREAD

**Issue by typad1** [Pterodactyl/Panel#418]
Hi there!

I am installing on a new machine. When I try to run

`sudo supervisorctl start pterodactyl-worker:*`

I get 

```
pterodactyl-worker:pterodactyl-worker_00: ERROR (spawn error)

pterodactyl-worker:pterodactyl-worker_01: ERROR (spawn error)
```

Also, I had to create the directory
 
`/var/www/pterodactyl/html/storage/logs/queue-worker.log `
 
by hand because the html folder was empty.

~~In addition, I set up NGINX and when I go to the domain I have set up, I just get `File not found.`~~
Fixed..

What am I doing wrong? I am using Ubuntu 16.04-LTS

**Comment by DaneEveritt** [comment]
Please use our [community forums](https://forums.pterodactyl.io) or [Discord](https://pterodactyl.io/discord) channel for assistance with panel installation. This issue tracker is for feature requests and bugs relating the use of the panel or daemon, not issues with installation.

Thanks.
