### ISSUE TITLE
In the emails send by the panel I get as a URL  https://localhost/...

### ISSUE THREAD

**Issue by BothimTV** [pterodactyl/panel#4180]
### Current Behavior

![Screenshot_20220627_144616](https://user-images.githubusercontent.com/50715457/175946528-42bd7982-ffee-4e7b-b8f8-f4b13ba28eeb.jpg)

In the email it says (and opens) https://localhost/panel.xxxxxx.com

### Expected Behavior

That it would say directly https://panel.xxxxxxy.com

### Steps to Reproduce

Send you an test email from the administration page.

### Panel Version

1.8.1

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
The value is retrieved from your APP_URL in the dotenv file. Check the value, fix it and restart the pteroq.service to apply new changes.

**Comment by BothimTV** [comment]
![Screenshot 2022-06-27 162908](https://user-images.githubusercontent.com/50715457/175965348-f53cd399-4afc-488f-8810-7b2ac1bd6805.png)
In the .env is the correct adress without localhost.

**Comment by Boy132** [comment]
It needs to start with `http://` or `https://` respectively.
