### ISSUE TITLE
Unexpected/unwanted permission behaviour change on server settings page

### ISSUE THREAD

**Issue by clrxbl** [pterodactyl/panel#4181]
### Current Behavior

![image](https://user-images.githubusercontent.com/28601081/175947521-bc91d940-f07f-468b-9f82-4cf68b5f7cdf.png)

The previous behaviour was that it would allow you to view the server settings page and show you your SFTP settings + Launch SFTP button. Since 1.9.0, the server settings page cannot be accessed by users that do not have permission for one of these two permissions
![image](https://user-images.githubusercontent.com/28601081/175947841-12db5259-2649-4838-8c7b-6aeb3059e17b.png)

### Expected Behavior

Access the server settings page without any settings permissions given under a subuser to access SFTP credentials.

### Steps to Reproduce

1. Add a subuser that has no permissions for "Settings"
2. Access the server settings page under said subuser

### Panel Version

1.9.0

### Wings Version

1.6.4 / https://github.com/clrxbl/wings/tree/feature/configurable-mtu

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Can confirm. A subuser needs the `file.sftp` _and_ one of the two `settings` permissions. (a subuser with just `settings.rename` permissions for example can't access the page either)
