### ISSUE TITLE
Option how much MB should convert into GB

### ISSUE THREAD

**Issue by LevM-A** [pterodactyl/panel#4183]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

In admin panel, there should be a button that can change how much MB should convert to GB. before 1.9v, 1024mb should be 1gb, but right now it's 1000mb = 1gb. If i want to have 1 gb as 1024mb then I must turn on button in admin area panel.

### Describe the solution you'd like.

mostly people who are using pterodactyl panel are setting for servers as full GB ( such as 3072mb = 3gb, 8192mb = 8gb), But others side most hosting providers are setting 1gb as 1000mb (such as 3000mb = 3gb, 8000mb = 8gb).

**Comment by TsjipTsjip** [comment]
This is wrong.
1 GB is and always will be 1000 MB. (Base 10 prefixes)
1 GiB is and always will be 1024 MiB. (Base 2 prefixes)

This is a common misconception and software adopting the options you are suggesting only add to the confusion. Perhaps you could make  a request to be able to change the unit to MiB if the places you want to use it in is managed by the panel.
