### ISSUE TITLE
[Activity] Logging user actions

### ISSUE THREAD

**Issue by statebyte** [pterodactyl/panel#4186]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hello, logs have appeared in version 1.9.0, but there are not enough logs, namely, it is not enough to use functions:
- Start
- Restart
- Stop
- Execute a command in the console

### Describe the solution you'd like.

I think it would be nice to add a record about the use of the above listed functions to the handler.

### Additional context to this request.

_It would also be nice to add a setting to enable / disable logging in the admin panel_

**Comment by maxcom1** [comment]
### That's not an issue. From announcement in Pterodactyl's Discord:
Activity logs now have a user viewable UI! This will allow you to monitor most changes to server entities, and also any changes to your own account. There are still a few areas I need to finish configuring, notably SFTP file actions, commands sent to the server, and power actions. **Expect these to roll out in future Wings updates.**

**Comment by statebyte** [comment]
Thanks for the answer
