### ISSUE TITLE
CPU Graph Covering Network Outbound Information (iPadOS)

### ISSUE THREAD

**Issue by MitchellPT** [pterodactyl/panel#4189]
### Current Behavior

The network out outbound information is behind the CPU Graph, making it unreadable
This happens when using on a iPad. (Works perfectly on phone)
This happens with all eggs.

The scaling also seems slightly to big.

![Haste Bin  Console-1](https://user-images.githubusercontent.com/24734120/176041978-a91bf307-91d3-4956-8139-17a14a08b2a6.png)

### Expected Behavior

To show all information
Possibly slightly smaller scaling?

### Steps to Reproduce

Using iPad OS 15.5 on 12.9inch iPad Pro.
Open GamePanel via Safari.

### Panel Version

1.90

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
What is your iPad resolution or version, as they all have different size?

**Comment by MitchellPT** [comment]
> What is your iPad resolution or version, as they all have different size?

2732x2048
iPad Pro Gen 4 12.9inch

This image attached is using the screen shot feature that will show a whole page at once, thats why its not the same resolution as image.

**Comment by DaneEveritt** [comment]
Its a bug in Safari in general.

**Comment by MitchellPT** [comment]
> Its a bug in Safari in general.

Could be... I use Andriod for my phone so unable to confirm *

**Comment by LevM-A** [comment]
Same things, Ipad Pro 3gen 11inches. 1668x2388 screen resolution. and I think it because of Safari.
![1B7BC106-179A-4537-99DF-31A57A79C9C8](https://user-images.githubusercontent.com/59459622/176065188-e0abc20a-0ba4-469f-bd03-2c377e3d6b0f.jpeg)
![2A06914E-417A-40FE-B8D6-919344222ADA](https://user-images.githubusercontent.com/59459622/176065197-c929b075-b98a-45a3-bad1-4e1257a447b1.jpeg)
