### ISSUE TITLE
Use Account Gravatar if found

### ISSUE THREAD

**Issue by SerenModz21** [pterodactyl/panel#4190]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

If the user has an accessible gravatar, I think the panel should display it for activity and for the account page hyperlink to keep consistency with the admin panel.

### Describe the solution you'd like.

Display a user's gravatar if they have one accessible to the panel.

**Comment by JordanDIG** [comment]
Since the 1.9 update, gravatars no longer seem to be managed by the client panel but only in the administration panel

**Comment by anondev-sudo** [comment]
I agree with this, because I hate those random generated annoying avatars. Use gravatar if user has it, or use default ptero logo if not, not those avatars

**Comment by anondev-sudo** [comment]
Or when its not possible, let users upload their own avatars if they are annoyed by that random generated avatar

**Comment by DaneEveritt** [comment]
Removing Gravatars was intentional, they will not be coming back. Over time the UI will be updated to be more consistent, but for now expect a few legacy spots to remain until they're updated.

**Comment by SerenModz21** [comment]
> Removing Gravatars was intentional, they will not be coming back. Over time the UI will be updated to be more consistent, but for now expect a few legacy spots to remain until they're updated.

oh, ok. thank u for explaining!

**Comment by anondev-sudo** [comment]
> Removing Gravatars was intentional, they will not be coming back. Over time the UI will be updated to be more consistent, but for now expect a few legacy spots to remain until they're updated.

Any specific reason why it was removed? What it will help to?

**Comment by anondev-sudo** [comment]
Do you plan to add option to let users upload their own avatar?

**Comment by JordanDIG** [comment]
> Do you plan to add option to let users upload their own avatar?

This could be a good option

**Comment by DaneEveritt** [comment]
No.

**Comment by anondev-sudo** [comment]
> No.

But why? Users hate that annoying random generated avatars

**Comment by anondev-sudo** [comment]
I know that then you would have to store it on the server and waste disk space, but why you removed gravatars? I liked that, no need to store uploaded avatars and it's global, any project can get user's avatar from it

**Comment by PoomsXP** [comment]
> > No.
> 
> But why? Users hate that annoying random generated avatars

GDPR Compliance.
Some user was annoying them about it and they just removed it because "nobody cared about it"
https://github.com/pterodactyl/panel/issues/4051
