### ISSUE TITLE
Check if X-Forwarded-For header exists and validate with a allowed proxy whitelist

### ISSUE THREAD

**Issue by Prophet731** [pterodactyl/panel#4191]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Check if the `X-Forwarded-For` header exists and validate with an allowed proxy whitelist. In version 1.9.1 under the activity log, if you have the site behind a proxy service (HAPROXY or CloudFlare for example) make sure to get the real user IP.

### Describe the solution you'd like.

Check if the `X-Forwarded-For` header exists and validate with an allowed proxy whitelist. In version 1.9.1 under the activity log, if you have the site behind a proxy service (HAPROXY or CloudFlare for example) make sure to get the real user IP.

**Comment by matthewpi** [comment]
The `TRUSTED_PROXIES` environment variable is what Pterodactyl uses for this exact functionality.

But more likely, you need to configure NGINX (or Apache) with `realip` to properly handle any upstream proxy ips (like Cloudflare, another webserver, or a load balancer)

**Comment by trenutoo** [comment]
Reference the documentation. 

https://pterodactyl.io/panel/1.0/additional_configuration.html#reverse-proxy-setup

**Comment by Prophet731** [comment]
Well, I feel stupid... Should have RTFM.

Thanks.
