### ISSUE TITLE
Hide activity

### ISSUE THREAD

**Issue by JordanDIG** [pterodactyl/panel#4192]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

On the admin panel to be able to hide an activity on the client's server

### Describe the solution you'd like.

On the server administration page, we would have an activities button allowing staff to delete one or more activities from the client view via buttons.

**Comment by anondev-sudo** [comment]
Yeah, when you make some changes to users servers and you dont want to let them know it

**Comment by JordanDIG** [comment]
When I looked at the code I realized that this option had already been created, I just need to add a variable in the .env file

**Comment by anondev-sudo** [comment]
Which variable?

**Comment by JordanDIG** [comment]
> Which variable?

APP_ACTIVITY_HIDE_ADMIN=true

**Comment by Shriy1556k** [comment]
how to do this can ihave screenshots

**Comment by JordanDIG** [comment]
This environment variable allows that when administrators perform an action on the server, this action does not appear in the client logs.

**Comment by anondev-sudo** [comment]
https://github.com/pterodactyl/panel/issues/4215
Can this be added too?
I have suggested that when this is enabled admins will be able to view their activity on user's servers but users won't be able to view activity that admins have performed on their server.

**Comment by JordanDIG** [comment]
> #4215 Can this be added too? I have suggested that when this is enabled admins will be able to view their activity on user's servers but users won't be able to view activity that admins have performed on their server.

Yes it could be good

**Comment by D33pakGanesh** [comment]
Does this work?
APP_ACTIVITY_HIDE_ADMIN=true
