### ISSUE TITLE
Purge activity logs when server deleted.

### ISSUE THREAD

**Issue by notAreYouScared** [pterodactyl/panel#4193]
### Current Behavior

When a server is deleted, activity logs are retained in the database. 

### Expected Behavior

Activity logs should be removed, when a server is deleted to assist in reducing database size. 

When a server is deleted the activity log should also be purged, the best way I can see is to get all the rows that match that server's internal id (104) in the 'subject_id' column, then delete the corresponding 'activity_log_id' from the 'activity_log'
![image](https://user-images.githubusercontent.com/1757840/176107517-c3516c8f-fb36-439a-87b8-3530e1709f5b.png)
![image](https://user-images.githubusercontent.com/1757840/176107728-2ed11c1a-c7ce-47c0-8192-497561e67a5b.png)

### Steps to Reproduce

Create a server
Spam the activity log
Delete server
View database activity log subject 

### Panel Version

1.9.1

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
I think I see more value in keeping the logs around than I do in purging them. We already automatically purge the logs after 30 or 90 days (can't remember), so it won't really be an issue in the end.

I can see scenarios where someone deletes a server and you still want to know potentially what values were there, or what happened previously on the server. I don't think deleting the model should be a reason to purge the logs.

Also, by this logic we'd be purging logs when other models are deleted, which doesn't make sense. So by then _not_ doing this with other models, and only doing it with servers we end up with really confusing behavior to save a few MB in an already tiny database. :)
