### ISSUE TITLE
Login as user

### ISSUE THREAD

**Issue by anondev-sudo** [pterodactyl/panel#4198]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add login as user feature for admins. This is good when you want to access some features that admins cant see, like user activity logs, ssh keys, ...

### Describe the solution you'd like.

When admin clicks on this link (from admin page), session cookie should be set that you are logged in as that user. When you logout from it, you should be logged in back as admin (not logged out completely), so you don't have to login again.

**Comment by yesBad** [comment]
I can see ssh keys & activity logs.... What do you mean...

**Comment by anondev-sudo** [comment]
You can see just yours ssh keys & activity logs, not of other users. This would be useful if you want to see what user sees when user is logged in

**Comment by DaneEveritt** [comment]
I'm not sure I see any reason why an admin would need to be signed in as a user? You can already do everything as an admin, and managing an account like that doesn't really seem to have any valid use case to me.

**Comment by anondev-sudo** [comment]
You cant see how users see it (activity logs, ssh keys, ...)

**Comment by DaneEveritt** [comment]
Why does an admin need to see and modify that information for a user? Those are security controls for their account.

**Comment by DaneEveritt** [comment]
Closing this out, won't be implementing such functionality at this time.

**Comment by Vanshgaming** [comment]
Hthgg
