### ISSUE TITLE
CPU percentage not rounding off to 0.001 or less

### ISSUE THREAD

**Issue by DemsarMa** [pterodactyl/panel#4200]
### Current Behavior

Sometimes, the CPU usage graph percentage is rounding to too many decimal units (too many zeros..) since the new update (1.9.1).

![image](https://user-images.githubusercontent.com/78916962/176192957-ebc65b0d-52f6-402f-9f60-a446960ac93c.png)

### Expected Behavior

Visual bug, too many decimal units.

### Steps to Reproduce

Latest version (1.9.1), running a container with an official BungeeCord egg.

### Panel Version

1.9.1

### Wings Version

1.6.4

### Games and/or Eggs Affected

Minecraft (BungeeCord)

### Docker Image

ghcr.io/software-noob/pterodactyl-images:java_17

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Bencor29** [comment]
Hi,
I've just updated my panel and have the same issue.
![Wrong decimal units](https://i.imgur.com/jvpRDxz.png)

Panel Version: 1.9.1
Wings Version: 1.6.4
Game: Minecraft - Cauldron 1.7.10 (Custom Egg)
Docker Image: quay.io/parkervcp/pterodactyl-images:debian_openjdk-8-jre

PS: This issue affect all my servers (Spigot 1.12.2 / Custom NPM Egg)

**Comment by EmmaKnijn** [comment]
all i can say is, computers suck at floating point math, not an excuse tho

**Comment by djohts** [comment]
can reproduce on v1.9.1
![image](https://user-images.githubusercontent.com/68508885/176740870-23a84aae-019e-4295-8149-83fa37c2b25e.png)
