### ISSUE TITLE
User languages

### ISSUE THREAD

**Issue by Bubbelwubbel** [pterodactyl/panel#4201]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Player Language, that every player can choose his own language, but an admin has to add a new language first, just over all texts and that over the panel

### Describe the solution you'd like.

If or top left next to the profile picture so a dropdown with the languages, or in user settings once in the admin panel and user panel and set there.

**Comment by Jelcoo** [comment]
Please review your choice on `I have searched the existing issues before opening this feature request.` again, and then come back...
