### ISSUE TITLE
Panel does not load on a Samsung Smart TV

### ISSUE THREAD

**Issue by EmmaKnijn** [pterodactyl/panel#4202]
### Current Behavior

The page does not load on a Samsung Smart TV (UE50RU7475U) , showing `An error was encountered by the application while rendering this view. Try refreshing this page` on the screen

### Expected Behavior

The page would load on version 1.8.1, but after updating to 1.9.1 the panel would not load on a Samsung UE50RU7475U

### Steps to Reproduce

1. Open the web browser on a Samsung UE50RU7475U or similar device
2. Go to the URL of a Pterodactyl 1.9.1 panel
3. View error

### Panel Version

1.9.1

### Wings Version

1.6.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by EmmaKnijn** [comment]
I got this from a person trying to use the panel.
![unknown](https://user-images.githubusercontent.com/64010592/176206415-8964946e-475b-460e-ae38-6b6c2a786b49.png)
l

**Comment by EmmaKnijn** [comment]
TV is on the latest version

**Comment by EmmaKnijn** [comment]
TizenBrowser 2.3.0.0423190 is the browser being used

**Comment by TsjipTsjip** [comment]
Just gonna drop this here: The developers are gonna need more information to locate the issue and patch it. Please provide error logs if any are generated, because not a lot of us have a Samsung Smart TV to test on, neither is it a platform that pterodactyl actively targets for development.

**Comment by EmmaKnijn** [comment]
This happens specifically with the TizenBrowser client, but I dont know how to get error logs from it.

**Comment by AndyIsHereBoi** [comment]
Mine is also loading blank. It just instantly finishes loading my browser version is below ![IMG_20220628_105920.jpg](https://user-images.githubusercontent.com/69745145/176226132-e11b3419-6990-4d0e-a8b9-41b96e18a3c5.jpg)
Checking for error logs now

**Comment by finnie2006** [comment]
😂😂 @DaneEveritt 
Pterodactyl on a tv is super important lmao

**Comment by DaneEveritt** [comment]
Don't use a TV.

_edit_: I should clarify — if there was a layout issue it might make sense to address, but I'm not going to purchase a smart TV just to test this bug, you're gonna have to do this debugging on your own and you're welcome to follow up with a fix PR if there is an actionable change we can make.

Otherwise, unfortunately a vendor specific TV browser is just not a target I view as important for supporting.

**Comment by AndyIsHereBoi** [comment]
i dont plan to use it on a tv, but here is error logs if anyone wanted it either to just see or to fix and make a pull request.
panel logs: https://pteropaste.com/kgmv4x
wings logs: https://ptero.co/upofygypuj

**Comment by ghost** [comment]
:thinking: What about a Samsung Smart Fridge?

**Comment by TimeFlow5** [comment]
> 🤔 What about a Samsung Smart Fridge?

Last time I tried was last January, did not work then. Maybe I need to update it?
