### ISSUE TITLE
Icon of Account on Dashboard wrong (small Bug)

### ISSUE THREAD

**Issue by Chraftingblock** [pterodactyl/panel#4203]
### Current Behavior

The Current Icon on the Dashboard for The Users is your test-icon
![grafik](https://user-images.githubusercontent.com/70597384/176214370-5eeb4827-babf-44fa-a4b2-869bad9bfda7.png)

### Expected Behavior

Should be the same icon as on the admin page
![grafik](https://user-images.githubusercontent.com/70597384/176214077-813bab03-f8b4-43a2-a90e-2df41a0a4f39.png)

(In the Past it was Correct)

### Steps to Reproduce

Setup basic Panel and Wings, Set username same as gmail, where you set a custom Profile Picture.

### Panel Version

1.9.1

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
This is correct. The new profile avatars were added in 1.9.0. When the new admin area comes out they will match

**Comment by Chraftingblock** [comment]
Are They going to be like the old (1.8.x) ones or completely new ones (like the 1.9.1)?

**Comment by TsjipTsjip** [comment]
The new ones. Pterodactyl is moving away from gravatar for a variety of reasons. If this answers your question, you can close this issue to keep the tracker clean :D
