### ISSUE TITLE
Admin Page Status of Server

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#4204]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

ENGLISH: Show homepage on admin status of the node.

GERMAN: Homepage auf Admin Status von dem Nodes anzeigen.

### Describe the solution you'd like.

ENGLISH: I find this feature very cool because you can see directly whether a server is offline or not.

GERMAN: Ich finde dieses Feature sehr cool, da man direkt sehen kann, ob ein Server offline ist oder nicht.

### Additional context to this request.

Btw. I'm not so good in English I'm using Translator from Google.

~ PVPMaster0001

**Comment by FoksVHox** [comment]
@PVPMaster0001 
Ich bin mir nicht sicher, ob ich Ihre Anfrage verstehe. Könnten Sie Ihre Anfrage bitte näher erläutern?

I'm not sure that I understand your request, could you please elaborate on your request?

**Comment by DaneEveritt** [comment]
Sorry, I don't understand what you're asking for here, even with translations.

**Comment by ghost** [comment]
> Sorry, I don't understand what you're asking for here, even with translations.

A Status for Nodes on pterodactyl in the Admin Page (panel.example.com/admin/

**Comment by ghost** [comment]
> @PVPMaster0001 Ich bin mir nicht sicher, ob ich Ihre Anfrage verstehe. Könnten Sie Ihre Anfrage bitte näher erläutern?
> 
> I'm not sure that I understand your request, could you please elaborate on your request?

A Status for Nodes on pterodactyl in the Admin Page (panel.example.com/admin/

Eine Status Anzeige für die Nodes im pterodactyl Admin page

**Comment by DaneEveritt** [comment]
You can already see if a node is connectable or not via the nodes listing in the admin area. Pterodactyl is not designed to be a monitoring solution, so I won't be adding anything else to monitor resource usage or uptown/downtime on nodes.
