### ISSUE TITLE
Force HTTPS on Settings Page

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#4205]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

ENGLISH: To the configuration in the admin page would be very cool where you can turn force https on or off. There a button with Force HTTPS on/off.

GERMAN: An die Konfiguration im Admin Page wäre sehr cool wo man Force https einschalten kann oder deaktivieren. Das Dort einen Button mit Force HTTPS on/off.

### Describe the solution you'd like.

ENGLISH: it would be cool to have a setting to enable Force HTTPS without having to rewrite the .env file. I hope this will be implemented.

GERMAN: es wäre Praktisch eine Einstellungsmöglichkeit zu haben eine Force HTTPS zu aktivieren ohne das man die .env datei umschreiben muss. Ich hoffe dies wird umgesetzt.

### Additional context to this request.

Btw. I'm not so good in English I'm using Translator from Google.

~ PvPMaster0001

**Comment by aalberrty** [comment]
what do you edit in the .env file, i keep getting redirected to https and cant find a solution in docs

**Comment by gOOvER** [comment]
German:

Wenn Du deinen Server richtig konfiguriert, braucht es das in keinster weise ;)

English:

when you configure your  server correct, its not needed

**Comment by DaneEveritt** [comment]
If you set the `APP_URL=` environment value correctly, or configure the proxy stuff this is not an issue. There is no reason for this setting to exist.

**Comment by ghost** [comment]
German: Das Problem ist ich habe einen vserver bei Goorm.
(http://cp01.run-eu-central1.goorm.io)

ENGLISH: The Problem is I have a vserver in goorm.
(http://cp01.run-eu-central1.goorm.io)

Amazon Certificate
