### ISSUE TITLE
Android / IOS App

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#4206]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

ENGLISH: Greate a App for the Pterodactyl Panel with the newest version.
GERMAN: Erstelle eine App für das Pterodactyl Panel mit der neusten Version.

### Describe the solution you'd like.

ENGLISH: I find it cool. Speed manage.
GERMAN: Ich find es cool. Schnell Verwalten.

### Additional context to this request.

I can not so good English.

~ PVPMaster0001

**Comment by gOOvER** [comment]
english:
read the official discord and you will find a solution ;)

German:
Es gibt bereits dafür was; eine externe Lösung. Wärst Du aber selber drauf gekommen, wenn Du mal den Discord angeschaut hättest. Also bitte nicht wegen allem ein Ticket erstellen und  die existierenden VORHER durchlesen. ;) Als Tip am rande

**Comment by DaneEveritt** [comment]
Not interested in building or maintaining a mobile app.

**Comment by OlekAleksander** [comment]
Use featherdactyl
