### ISSUE TITLE
bug for renamed file in Activity logs

### ISSUE THREAD

**Issue by valkam08** [pterodactyl/panel#4208]
### Current Behavior

the name of the file that was renamed is linked to the name of the folder

![unknown](https://user-images.githubusercontent.com/51866926/176318104-4babd38e-e5d0-4096-9e1b-69f9629ed451.png)

### Expected Behavior

add a space between file name and folder name

### Steps to Reproduce

on a server, in the file Manager tab, rename a file in a folder (/plugins for example) and look in the Activity Logs tab for the result

### Panel Version

1.9.1

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by FC-FailCoder** [comment]
![image](https://user-images.githubusercontent.com/45609819/176381744-b6bc3e35-6ba0-4196-9027-4ccd893d9c2e.png)
Tried on my own panel, running 1.9.1. Can also confirm this happens.

"giveyouup" > "giveyouup2" is the file name.
"nevergonna" is the directory
