### ISSUE TITLE
Free Hosting

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#4214]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Gibt es irgendwo einen Gratis Hosting für dieses Panel?

### Describe the solution you'd like.

Free Hosting for Pterodactyl Panel.

**Comment by gOOvER** [comment]
there is No. you must Install it on your own server

**Comment by finnie2006** [comment]
Lol, the issues keep getting wierder
