### ISSUE TITLE
TransferException Error

### ISSUE THREAD

**Issue by KadotyGamer** [Pterodactyl/Panel#422]
I am getting the following error when trying to increase the amount of RAM on a server and getting one similar when trying to delete a server. `A TransferException was encountered while trying to contact the daemon, please ensure it is online and accessible. This error has been logged. `  I have attached some of the entries in the error log.  The daemon is only and seems to be connecting fine other than these issues.
[May2-Errors.txt](https://github.com/Pterodactyl/Panel/files/972379/May2-Errors.txt)

**Comment by Zendrex** [comment]
#421 Deleting servers was noted and fixed.
