### ISSUE TITLE
Profile picture

### ISSUE THREAD

**Issue by Doncellup** [pterodactyl/panel#4223]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Use the gravatar api for the profile picture, particularly here:
![image](https://user-images.githubusercontent.com/90469321/177002473-13ba5116-62fb-4ca1-ba28-2e52b2a33712.png)

### Describe the solution you'd like.

.

### Additional context to this request.

I think it's simple and quick to implement!
Thanks in advance,
Doncellup

**Comment by Jelcoo** [comment]
We had that before, but Dane decided to change it due to the law in certain areas of the world.

**Comment by yesBad** [comment]
Just a heads up.
v1.9.0 Changelog:
> Begins the process of dropping the use of Gravatars for user avatars and replaces them with dynamically generated SVG images.

It's being dropped due to some law regulations (GDPR & whatever) in certain areas of the world, like @Jelcoo said above. 
Yet it could be entirely possible for it to comeback, or perhaps a place where you can manually put your own avatar without a need of a 3rd party.

**Comment by DaneEveritt** [comment]
I have no interest in continuing to use Garavatar or allow user's to set their own avatars. They're generally not used for much of anything in the Panel, other than in a few select user listing spots.

There is really no concept of a "profile" (in any public sense of the word), and thus I was just looking for a cute way to add some character to the Panel, and also help provide some visual distinction between accounts in row listings.
