### ISSUE TITLE
Using a node on two panels

### ISSUE THREAD

**Issue by Bobby99as** [pterodactyl/panel#4225]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hello me and my business partner thought it would be nice to be able to use and share our nodes together but use separate panels for different branding but we haven't found a way to do that so the feature I would like to see is a option to define extra panels in the wings configuration

### Describe the solution you'd like.

The ability to define and add extra panels that the wings installation should listen to and report to. So this is what I was thinking

Node 1 on panel 1
it would be nice if node 1 could exist on panel 2 and also show all installed servers on it to both panels but also say which panel the server belongs to

**Comment by DaneEveritt** [comment]
I'm not building in this complexity. If you want two Panel instances to share a single Node just run two instances of Wings.

**Comment by Bobby99as** [comment]
> I'm not building in this complexity. If you want two Panel instances to share a single Node just run two instances of Wings.

So will that even sink the resource usage graphs and logs or is it just gonna be a guessing game and make sharing a node hell

**Comment by parkervcp** [comment]
If you run 2 copies of wings then they will only show the servers they manage. You will not be able to control the servers from one panel with the other.

**Comment by Bobby99as** [comment]
> If you run 2 copies of wings then they will only show the servers they manage. You will not be able to control the servers from one panel with the other.

Cool that wont work for me

**Comment by iRazvan2745** [comment]
What if you put the same mysql database on both panels?

**Comment by joinasau** [comment]
I have the same problem...

**Comment by joinasau** [comment]
I want to make an emergency panel with loadbalance

**Comment by iRazvan2745** [comment]
well, thats stupid, then you can just have a mirrored database of pterodactyl and everything will work
