### ISSUE TITLE
Activity Logs from previously viewed server still in list on curernt viewed server

### ISSUE THREAD

**Issue by notAreYouScared** [pterodactyl/panel#4226]
### Current Behavior

View Server A's activity log with logs in it, Then go back to the main server list, pick another server, and view the activity log for that server. You'll notice that the previous servers' activity logs are mixed with the currently viewed server logs. 

The below gif visits 3 servers. all the activity logs from the previously viewed server and currently viewed server are conjoined. 

![chrome_jD3IXpg1aU](https://user-images.githubusercontent.com/1757840/177105226-66c50531-223a-4e26-be19-315511599027.gif)

### Expected Behavior

The previous state should be cleared before the activity logs are rendered. 

### Steps to Reproduce

View Server A's activity logs.
Click top left to go home
View Server B's activity logs.

### Panel Version

1.9.2

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Looks like SWR at work, does refreshing the screen fix it @AreYouRlyScared?

**Comment by notAreYouScared** [comment]
Yes.

**Comment by DaneEveritt** [comment]
Is this resolved by 26d7d7e0e0b52740ff8dbcebef641350acea87aa?

**Comment by notAreYouScared** [comment]
> Is this resolved by [26d7d7e](https://github.com/pterodactyl/panel/commit/26d7d7e0e0b52740ff8dbcebef641350acea87aa)?

Yes.
