### ISSUE TITLE
Activity Log paging not working as intended. Combines results into one long page.

### ISSUE THREAD

**Issue by notAreYouScared** [pterodactyl/panel#4227]
### Current Behavior

Activity log pages merge when viewed a second time. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1757840/177107566-ee8e81ba-361e-4dd2-8429-3cf20ac5d840.gif)

### Expected Behavior

Each page should show the next log entires, not add them to the bottom of the current page.entries

### Steps to Reproduce

View a server that has multiple pages of activity logs ( 73 results = 3 pages )
Starting on page 1, view page 2, then page 3. ( Assuming this does something with the current state)

Now view any of the pages in any order, you'll notice that the previous rows are not removed on the page, and the rows for whatever page you selected are added to the current set of rows. 

### Panel Version

1.9.2

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Is this resolved by 26d7d7e0e0b52740ff8dbcebef641350acea87aa?

**Comment by notAreYouScared** [comment]
> Is this resolved by [26d7d7e](https://github.com/pterodactyl/panel/commit/26d7d7e0e0b52740ff8dbcebef641350acea87aa)?

Negative. 

![Uploading chrome_NhIDG8xgaA.gif…]()

**Comment by mrxbox98** [comment]
I did some testing on the latest version and cannot replicate this issue.

**Comment by notAreYouScared** [comment]
This does appear to be fixed in the latest version.
#Closed.
