### ISSUE TITLE
AllocationServers Ideas

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#4228]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

For developer it´s better to have an API that can do all things like an Administrator. And with the ApplicationAPI i cant´t start, stop or get a status like Online or Offline for a server.

### Describe the solution you'd like.

Just made a way to control the Server, and get a Status with the ApplicationAPI.

### Additional context to this request.

Sorry, for my bad English, i am a 12 years old German developer.

**Comment by mason-rogers** [comment]
if you make an api key on the client side then you can access all servers to do anything the frontend can do (plus application API keys will be phased out afaik, as client API keys now work on both the client API and the application API)

**Comment by ghost** [comment]
OK, thx i didn´t know that.
