### ISSUE TITLE
Console lazy loading prevents access to the server when it's not reachable

### ISSUE THREAD

**Issue by Alanilily** [pterodactyl/panel#4230]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

this new theme of sort for pterodactyl is good but theres just one problem if a server goes offline or a node basically u cant click on anything on the panel anymore u have to retype the url to go back

### Describe the solution you'd like.

Well its pretty simple i would like for it to not do that like after the node is down it would be like it was the last time like only the console is loading and not the whole panel.
(sorry if my English was a bit broken there)

**Comment by parkervcp** [comment]
You have a gif of this somewhere?

**Comment by Alanilily** [comment]
> You have a gif of this somewhere?

Sorry I don't but if needed ill take one

**Comment by Software-Noob** [comment]
This is not a feature request and instead a bug. It's an issue with the lazy loading of the console that overlays the whole page instead of the console only, which is what I assume your report is about.

![image](https://user-images.githubusercontent.com/10975908/177225862-071f5e08-8f09-455c-9da0-108bcfc1d466.png)

**Comment by Alanilily** [comment]
> This is not a feature request and instead a bug. It's an issue with the lazy loading of the console that overlays the whole page instead of the console only, which is what I assume your report is about.
> 
> ![image](https://user-images.githubusercontent.com/10975908/177225862-071f5e08-8f09-455c-9da0-108bcfc1d466.png)

Yes thank you It is, I didn't know what to put it in.

**Comment by Thesam1798** [comment]
The problem of #4235 must surely be due to the same cause
