### ISSUE TITLE
UI Rendering issues 1.9.1 + 

### ISSUE THREAD

**Issue by DomiiBunn** [pterodactyl/panel#4232]
### Current Behavior

The UI seams to fail rendering if tab is left unattended(out of focus) for a longer period of time

![Capture](https://user-images.githubusercontent.com/51760394/177318464-935018cb-d222-43d3-a682-b384b6906e9e.PNG)

Once moving the mouse over a none rendered component it comes back into view

### Expected Behavior

When returning to a tab all content will apper visable

### Steps to Reproduce

Leave a tab open in the background for a while.

Currently only noticed in chrome `103.0.5060.114 (Official Build) (64-bit) (cohort: 103_Win_113)`

### Panel Version

1.9.2

### Wings Version

1.6.4

### Games and/or Eggs Affected

DiscordJS, Forge

### Error Logs

```bash
None
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
This seems more like an issue with your system and "leave it in the background for awhile" is something I do daily given that I just close my laptop when I'm done.

Also, that really isn't a viable step to reproduce with the amount of time I have available, this unless someone else is able to consistently reproduce this issue I'm closing it out.
