### ISSUE TITLE
Uploading multiple files

### ISSUE THREAD

**Issue by MrTimotys** [pterodactyl/panel#4234]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to add a feature where we can upload multiple files via webftp. I would also appreciate some kind of progressbar when uploading a file

### Describe the solution you'd like.

- II -

**Comment by notAreYouScared** [comment]
#4219 would take care of this. It's in v2 just not 1.9
