### ISSUE TITLE
Problem with auto-allocation

### ISSUE THREAD

**Issue by chredeur** [pterodactyl/panel#4239]
### Current Behavior

When you enable "Automatic Allocation Creation" on the panel and disable auto allocation on a Node you can still automatically allocate new ports on a server of the same type.

### Expected Behavior

We shouldn't have access to it. 

### Steps to Reproduce

You just have to activate "Automatic Allocation Creation" on the panel and deactivate it on the Node.

### Panel Version

1.9.2

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
`Allow automatic allocation` setting of a node is for provisioning servers to that node using the API deployment and toggles the public status of a node on and off. It does not have anything to do with the panel wide setting of `Automatic Allocation Creation`, which is for creating new allocations like mentioned in the description. 

> If enabled users will have the option to automatically create new allocations for their server via the frontend.

it might need a better name though, such as `Allow automatic server allocations` or `Enable automated server deployments`

**Comment by DaneEveritt** [comment]
Working as intended.

**Comment by amanthabin** [comment]
cant join server i used this The IP address you have assigned to your server is not actually available for use on your machine.

Execute the command hostname -I | awk '{print $1}' and change your Node allocations to use this IP. Yes, it can be your internal/local IP when you're behind NAT. When behind NAT you will allocate the internal IP and connect using the public IP.

If you have added multiple public IPs to your network interface, you can view all of them using the command ip a | grep "inet "
