### ISSUE TITLE
Source Install Issues / Panel Status Bug

### ISSUE THREAD

**Issue by Zendrex** [Pterodactyl/Panel#424]
2 issues in 1 report, fancy!

1) When a server is installing, for the ACP it shows the status of "installing", however for the regular user, it shows "error". Unsure which is correct information, would be appreciated if that could be in sync.

2) Source servers do NOT install, wing's stalls at "Pulling image <linux version> ... this could take a few minutes." It notes that in the logs however never follows up. No following errors are show, and the server can be deleted as normal (when applying the #421 fix).

**Comment by schrej** [comment]
Every issue should be in one issue -> not that fancy after all 😜

**Comment by Zendrex** [comment]
I found these bugs at the same time, thought about knocking out two birds with one stone.

**Comment by DaneEveritt** [comment]
Can you please provide actual error logs from #2. Preferably from the daemon.

**Comment by KasperFranz** [comment]
Oh I didn't even try it as a normal user so didn't even see it was an issue

**Comment by Zendrex** [comment]
@DaneEveritt Thats the thing, there is no error. It just says its pulling the image and nothing else. If there was more to give, I for sure would but sadly it just stops dead in its tracks.

**Comment by DaneEveritt** [comment]
Can you just provide the output for me so I can follow what is happening?

**Comment by Zendrex** [comment]
`{"name":"wings","hostname":"REMOVED","pid":2191,"level":30,"msg":"Pulling image ubuntu:16.04 ... this could take a few minutes.","time":"2017-05-03T08:20:05.070Z","v":0}`

**Comment by DaneEveritt** [comment]
I mean the output prior to that, like the 10 lines prior.

**Comment by Zendrex** [comment]
`{"name":"wings","hostname":"<removed>","pid":2191,"server":"06b5ec19-3951-41f6-939e-936a9924e6af","level":40,"msg":"Container was not found. Attempting to recreate it.","time":"2017-05-04T00:53:11.777Z","v":0}
{"name":"wings","hostname":"<removed>","pid":2191,"level":30,"msg":"Checking if we need to update image quay.io/pterodactyl/core:source, if so it will happen now.","time":"2017-05-04T00:53:11.777Z","v":0}
{"name":"wings","hostname":"<removed>","pid":2191,"level":30,"msg":"Pulling image quay.io/pterodactyl/core:source ... this could take a few minutes.","time":"2017-05-04T00:53:12.491Z","v":0}
{"name":"wings","hostname":"<removed>","pid":2191,"server":"06b5ec19-3951-41f6-939e-936a9924e6af","level":30,"msg":"Completed rebuild process for server container.","time":"2017-05-04T00:53:21.169Z","v":0}
{"name":"wings","hostname":"<removed>","pid":2191,"server":"06b5ec19-3951-41f6-939e-936a9924e6af","level":40,"msg":"Server booting is now BLOCKED.","time":"2017-05-04T00:53:21.170Z","v":0}
{"name":"wings","hostname":"<removed>","pid":2191,"server":"06b5ec19-3951-41f6-939e-936a9924e6af","level":30,"msg":"Blocking server boot until option installation process is completed.","time":"2017-05-04T00:53:21.171Z","v":0}
{"name":"wings","hostname":"<removed>","pid":2191,"server":"06b5ec19-3951-41f6-939e-936a9924e6af","level":30,"msg":"Writing output of installation process to file. { file: '/home/daemon/config/servers/06b5ec19-3951-41f6-939e-936a9924e6af/install.log' }","time":"2017-05-04T00:53:21.172Z","v":0}
{"name":"wings","hostname":"<removed>","pid":2191,"level":30,"msg":"Pulling image ubuntu:16.04 ... this could take a few minutes.","time":"2017-05-04T00:53:21.857Z","v":0}
`

**Comment by DaneEveritt** [comment]
Unable to replicate the SRCDS error.

```
21:20:59.301Z DEBUG wings: New container successfully created with ID 1b18dd3963ac (server=e6da753b-82fb-462a-8ca1-37896588aadf)
21:20:59.301Z DEBUG wings: Containers successfully rotated, updating stored configuration. (server=e6da753b-82fb-462a-8ca1-37896588aadf)
21:20:59.311Z  INFO wings: Completed rebuild process for server container. (server=e6da753b-82fb-462a-8ca1-37896588aadf)
21:20:59.324Z DEBUG wings: Loaded configuration and initalized server. (server=e6da753b-82fb-462a-8ca1-37896588aadf)
21:20:59.324Z  WARN wings: Server booting is now BLOCKED. (server=e6da753b-82fb-462a-8ca1-37896588aadf)
21:20:59.325Z  INFO wings: Blocking server boot until option installation process is completed. (server=e6da753b-82fb-462a-8ca1-37896588aadf)
21:20:59.326Z DEBUG wings: Contacting remote server to pull scripts to be used. (server=e6da753b-82fb-462a-8ca1-37896588aadf)
21:20:59.326Z DEBUG wings: Contacting panel to determine scripts to run for option processes. (server=e6da753b-82fb-462a-8ca1-37896588aadf)
21:20:59.328Z  INFO wings: Writing output of installation process to file. { file: '/srv/daemon/config/servers/e6da753b-82fb-462a-8ca1-37896588aadf/install.log' } (server=e6da753b-82fb-462a-8ca1-37896588aadf)
21:20:59.706Z DEBUG wings: Writing temporary file to be handed into the Docker container. (server=e6da753b-82fb-462a-8ca1-37896588aadf)
21:20:59.706Z DEBUG wings: Pulling ubuntu:16.04 image if it is not already on the system. (server=e6da753b-82fb-462a-8ca1-37896588aadf)
21:21:00.303Z  INFO wings: Pulling image ubuntu:16.04 ... this could take a few minutes.
21:21:02.304Z DEBUG wings: Pulling image ubuntu:16.04 ... this could take a few minutes.
21:21:04.305Z DEBUG wings: Pulling image ubuntu:16.04 ... this could take a few minutes.
21:21:06.306Z DEBUG wings: Pulling image ubuntu:16.04 ... this could take a few minutes.
21:21:08.306Z DEBUG wings: Pulling image ubuntu:16.04 ... this could take a few minutes.
21:21:10.307Z DEBUG wings: Pulling image ubuntu:16.04 ... this could take a few minutes.
21:21:12.307Z DEBUG wings: Pulling image ubuntu:16.04 ... this could take a few minutes.
21:21:12.468Z DEBUG wings: Running privileged docker container to perform the installation process. (server=e6da753b-82fb-462a-8ca1-37896588aadf)
```

**Comment by DaneEveritt** [comment]
Oh wait, I see the issue.

**Comment by Zendrex** [comment]
So is this issue still closed then?

**Comment by DaneEveritt** [comment]
Officially closed as of https://github.com/Pterodactyl/Panel/commit/ee309b095e819be300a241753c76245b639313ad
