### ISSUE TITLE
Added the possibility to add the port you want to a server from the Application side api.

### ISSUE THREAD

**Issue by chredeur** [pterodactyl/panel#4240]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

While playing with the Pterodactyl api, I noticed that you can create allocations on a Node but you can't add an existing allocation to a server with its id, the problem it caused me is that I wanted to add local allocations (127.0.0.1) with a specific port but I just can't.

### Describe the solution you'd like.

So for its operation it would be good to have an option at the time of the creation of an allocation which would make it possible to specify the server, the Node and if possible the alias for the ip because currently one cannot add alias at the time of its creation finally I believe or another way of making it would be to modify the api point there: "[ /{server}/build ] Update build" to add the secondary allocation what would be simpler for the users.

### Additional context to this request.

I have nothing to add except that it would just be useful.

**Comment by devnote-dev** [comment]
This is actually already possible in the application API with the build endpoint (see [UpdateServerBuildConfigurationRequest](https://github.com/pterodactyl/panel/blob/develop/app/Http/Requests/Api/Application/Servers/UpdateServerBuildConfigurationRequest.php)), as well as in the client API with the network endpoints. You can also specify the `alias` when creating an allocation.

**Comment by chredeur0** [comment]
> Ceci est en fait déjà possible dans l'API de l'application avec le point de terminaison de génération (voir [UpdateServerBuildConfigurationRequest](https://github.com/pterodactyl/panel/blob/develop/app/Http/Requests/Api/Application/Servers/UpdateServerBuildConfigurationRequest.php) ), ainsi que dans l'API client avec les points de terminaison du réseau. Vous pouvez également spécifier le `alias`lors de la création d'une allocation.

I had not found it in the api documentation.

**Comment by chredeur** [comment]
> This is actually already possible in the application API with the build endpoint (see [UpdateServerBuildConfigurationRequest](https://github.com/pterodactyl/panel/blob/develop/app/Http/Requests/Api/Application/Servers/UpdateServerBuildConfigurationRequest.php)), as well as in the client API with the network endpoints. You can also specify the `alias` when creating an allocation.

But if I understand correctly you want me to use the auto port generation option?

**Comment by devnote-dev** [comment]
I don't recall there being such an option, can you be more specific please?

**Comment by chredeur** [comment]
> I don't recall there being such an option, can you be more specific please?

On the client side there is this option " [ /allocations ] Assign allocation" which allows you to use auto allocation. What I want to do is create my own allocation on a Node and then add it to a server.

**Comment by devnote-dev** [comment]
You wouldn't need the client side for this, you can create the allocation then use the update build endpoint to add/set the allocation.

**Comment by chredeur** [comment]
> You wouldn't need the client side for this, you can create the allocation then use the update build endpoint to add/set the allocation.

So if I understand correctly, we can already add a secondary allowance from the api?

**Comment by chredeur** [comment]
I think you are talking about the main server allocation but I would like to add a secondary allocation in addition to the main one.

**Comment by devnote-dev** [comment]
> I think you are talking about the main server allocation but I would like to add a secondary allocation in addition to the main one.

No, there is an `add_allocations` property which takes an array of allocation IDs to be added to the server, it's just not documented.

**Comment by chredeur** [comment]
> > I think you are talking about the main server allocation but I would like to add a secondary allocation in addition to the main one.
> 
> No, there is an `add_allocations` property which takes an array of allocation IDs to be added to the server, it's just not documented.

ah I didn't know thank you I'm testing this now.

**Comment by chredeur0** [comment]
@devnote-dev I tried what you said but when I try the requests I get this error (https://pterodactyl.file.properties/api/application/servers/5/build)

`{'errors': [{'code': 'HttpException', 'status': '419', 'detail': 'CSRF token mismatch.'}]}`
