### ISSUE TITLE
Modify the operation of "[ /{server}/build ] Update build" in the api.

### ISSUE THREAD

**Issue by chredeur** [pterodactyl/panel#4242]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

After looking at the api and doing some testing I realized that the operation of "[ /{server}/build ] Update build" was not very comfortable when when you want to use it it is mandatory to put all its arguments: {"allocation": 1, "memory": 0, "swap": 0, "disk" : 0, "io" : 500, "cpu" : 0, "threads" : null, "feature_limits" : {"databases" : 0, "allocations" : 0, "backups" : 0} in the requests what I would propose would be to modify its operation so that we can put just the arguments we want to change.

### Describe the solution you'd like.

I do not really have a technical solution to propose but it would be really nice to be able to modify what we want is not to have the obligation to put arguments by default because it is necessary to know the basic state of the server and then modify what we want.

### Additional context to this request.

When I tried to use my Application api key it wouldn't work while with my client api key everything works fine I don't understand why and I think it's a bug but I'm not sure.

**Comment by AndyIsHereBoi** [comment]
nevermind didnt realise this wasnt a gui update

**Comment by DaneEveritt** [comment]
We do not maintain those docs.

**Comment by AndyIsHereBoi** [comment]
> We do not maintain those docs.

I think he means in the pterodactyl API be wants it to only have to modify the values he wants to change and not all of them when he wants to edit only one of the values

**Comment by chredeur** [comment]
> > We do not maintain those docs.
> 
> I think he means in the pterodactyl API be wants it to only have to modify the values he wants to change and not all of them when he wants to edit only one of the values

I meant exactly that. But that's okay.
