### ISSUE TITLE
Bot randomly kills itself

### ISSUE THREAD

**Issue by AlexTheGoat69** [pterodactyl/panel#4243]
### Current Behavior

Discord bot using python (pycord) randomly kills itself

### Expected Behavior

To not kill itself/ turn off

### Steps to Reproduce

N/A, unknown.

### Panel Version

1.9.2

### Wings Version

1.6

### Games and/or Eggs Affected

Discord.py egg 

### Docker Image

https://github.com/parkervcp/eggs/tree/master/bots/discord/discord.py

### Error Logs

```bash
https://ptero.co/ywoparexoj 

There's no panel logs today for 07/07. So what should I do?
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by mason-rogers** [comment]
If it's randomly dying then it might be OOMing (running out of memory), how much resources have you allocated? And do you have logs of the server itself at the time of it "killing itself"

**Comment by AlexTheGoat69** [comment]
So, Im guessing to check youd check the node itself? If so I only had 1gb set to it, but I have uped it to 4gb. I do not, how would I go get the logs of the server next time the panel say "killed" for I can update it here.
