### ISSUE TITLE
Server transfer issue

### ISSUE THREAD

**Issue by xF3d33** [pterodactyl/panel#4244]
### Current Behavior

I wanted to trasfer my geyser server to another node (i used this many time and it work well), so i started the transfer.

but geyser has a problem, you can't just stop it, you have to kill the process. 

So the panel to transfer it tried to stop it but it won't stop. so i had to restart wings and kill it manually, but the transfer process broke down.

so in the database manually i changed the succeful field to 1.
but also the location was broken. the server for the panel was in the old allocation and node, but the new allocation was occupied. 

i don't use the custom geyser egg.

### Expected Behavior

a normal transfer

### Steps to Reproduce

create a server, start a geyser jar
https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1140/
start a transfer

### Panel Version

1.9.2

### Wings Version

1.6.4

### Games and/or Eggs Affected

Geyser

### Docker Image

java 17

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by LevM-A** [comment]
I think fix for that will be just add a kill command, so, if server can't stop in 30 seconds to transfer, then panel will kill it and then transfer.

**Comment by mzrtamp** [comment]
How to kill it? I got same issue too

![image](https://user-images.githubusercontent.com/40928387/180270377-c359824d-3370-4995-84c0-537150b4660d.png)

I'm forget to turn off the server before doing transfer between node
I have restarted wings and rebooted both VPS and this still happens, it just stuck like this

![image](https://user-images.githubusercontent.com/40928387/180270580-94f07fa4-b4f3-42fb-901b-0445ee671437.png)

Asked it on Discord but no response

**Comment by mzrtamp** [comment]
The real bug is, it never ends and I can use the power action

**Comment by TheGamer3514** [comment]
I have this issue, anyone got a fix?

**Comment by AdamFortney** [comment]
I just ran into this same issue. I was transferring a server, but my internet died for an extended period and it stopped sending files. The banner is still there and the transfer button is disabled, but the power buttons are able to be used.

Is there any way I can manually disable the transfer state?
