### ISSUE TITLE
Domain name invalid

### ISSUE THREAD

**Issue by adamondr** [pterodactyl/panel#4247]
### Current Behavior

Trying to put "eu01.minost.eu" as a FQDN, but it says its not a valid FQDN or an IP Address.

### Expected Behavior

Trying to put "eu01.minost.eu" as a FQDN would work.

### Steps to Reproduce

Write "eu01.minost.eu" or anything to do with the word "minost" to the FQDN when making a node.

### Panel Version

1.9.2

### Wings Version

1.6.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
There are no DNS records for the domain. This is not a bug in the software.

https://dnschecker.org/#A/eu01.minost.eu
