### ISSUE TITLE
Bot kills itself

### ISSUE THREAD

**Issue by AlexTheGoat69** [pterodactyl/panel#4250]
### Current Behavior

In console it say "killed" and my bot goes offline.

### Expected Behavior

To not turn it off.

### Steps to Reproduce

Not sure

### Panel Version

1.9

### Wings Version

1.6

### Games and/or Eggs Affected

Discord.py

### Docker Image

unsure

### Error Logs

```bash
https://ptero.co/iqeqiloqan

used panel command but say -07-09.llog for reading no such file or directory
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
This is not a bug with this software, it is an issue with your bot.
