### ISSUE TITLE
Name for allocations

### ISSUE THREAD

**Issue by Boy132** [pterodactyl/panel#4256]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be nice if you could name allocations, e.g. as `Query` Port, and allow to easily access named allocations in the server startup, e.g. `PORTS_QUERY` for the query port instead of an extra startup variable.

### Describe the solution you'd like.

I made some mockups, based on the example of a Satisfactory Server.

Satisfactory needs 3 ports: game, query and beacon. The game port is the primary allocation, which is fine. But for the query and beacon port you currently need to make 2 additional (and kinda redundant) startup variables. So instead it would be nice to just give the allocations a name.

![node_allocations](https://user-images.githubusercontent.com/8203120/178445586-23c08dc6-2044-46ca-ba05-51d383c76cfb.PNG)
![startup_command](https://user-images.githubusercontent.com/8203120/178445614-84309ce0-7c0f-4f58-9cc1-b0020c2d26b9.PNG)

**Comment by parkervcp** [comment]
Pretty sure this is a duplicate of #1204

**Comment by Boy132** [comment]
> Pretty sure this is a duplicate of #1204

Isn't #1204 all about startup variables? The point of my idea is to get rid of port variables.

**Comment by parkervcp** [comment]
> > Pretty sure this is a duplicate of #1204
> 
> 
> 
> Isn't #1204 all about startup variables? The point of my idea is to get rid of port variables.

My idea was to bake them into the egg and have them show up in the server creation process.

**Comment by Boy132** [comment]
Closing this in favor of #1001 and #1204.
