### ISSUE TITLE
Double files overlay

### ISSUE THREAD

**Issue by AndyIsHereBoi** [pterodactyl/panel#4260]
### Current Behavior

Able to start deletion of files, and upload files at the same time. This this triggers both overlays to show as seen below.
![image](https://user-images.githubusercontent.com/69745145/179305595-a1d0edcf-80e4-4046-a32b-3a8d619c6e3e.png)

### Expected Behavior

It should only allow one at a time, add to queue, or block the user because files are currently being deleted.

### Steps to Reproduce

Drag files in to be uploaded as other files are deleted

### Panel Version

1.9.2

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.
-
edit: image broken

**Comment by trenutoo** [comment]
This would most likely be fixed with the backport of #4219

**Comment by AndyIsHereBoi** [comment]
Fixed in new release
