### ISSUE TITLE
Firefox compatibility with panel 1.9.2

### ISSUE THREAD

**Issue by Straikerinos** [pterodactyl/panel#4261]
### Current Behavior

After some reflesh of page i can't see anything. Just blank page

### Expected Behavior

That the page will work

### Steps to Reproduce

Using Firefox.

### Panel Version

1.9.2

### Wings Version

1.6.1

### Error Logs

```bash
When page is still working, browser console is spammed with this errors:
https://pastebin.com/4tCAgRx1

When page stop working:
https://pastebin.com/5tY2gQbs
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [ ] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
It appears you're using a theme, is that correct?

**Comment by Straikerinos** [comment]
Yup, we have custom theme

**Comment by DaneEveritt** [comment]
Unless you can reproduce this issue on the base theme I am closing this issue — take it up with the theme author.

If you're able to reproduce it on the base theme you're welcome to re-open and update this issue with the relevant details.
