### ISSUE TITLE
I need help, not too sure what's happened

### ISSUE THREAD

**Issue by Isaac-Cooper** [pterodactyl/panel#4263]
### Current Behavior

Can someone please help, here are my logs:
https://pteropaste.com/d8lr89/

Don't ask me to go check discord for help as I DO NOT HAVE DISCORD AND WILL NOT GET DISCORD.

### Expected Behavior

idk

### Steps to Reproduce

idk

### Panel Version

1.8.0

### Wings Version

idk

### Error Logs

```bash
https://pteropaste.com/d8lr89/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [ ] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TrixterTheTux** [comment]
If you're gonna refuse to use the official support channels for these types of issues, please at least include what you're doing and trying to do :/

**Comment by Isaac-Cooper** [comment]
So, I'm changing the domain that my panel uses since the old domain is messed up, and idk what im doing, I think I have changed the domain and got it working so then I can login but barley anything is working, I'm trying to change the domain of the node and its spitting out errors
![image](https://user-images.githubusercontent.com/79118702/179600249-1961692a-761f-408b-ad4d-3593a8e22e51.png)
![image](https://user-images.githubusercontent.com/79118702/179600304-1dc7697a-ed8b-4741-b55f-7a5df0e6e185.png)
![image](https://user-images.githubusercontent.com/79118702/179600336-f64c2295-736b-4d3f-b3c5-d441e212909b.png)
![image](https://user-images.githubusercontent.com/79118702/179600379-dafbe326-9c47-4fc3-8308-30817a19259e.png)

**Comment by DaneEveritt** [comment]
This is

a.) not a support forum
b.) not an issue with this software.

**Comment by Isaac-Cooper** [comment]
Rude.

**Comment by Ferks-FK** [comment]
> 


> Rude.

Not rude.

**Comment by Isaac-Cooper** [comment]
Can someone just help me please.
