### ISSUE TITLE
Add a button to control nodes status

### ISSUE THREAD

**Issue by Terrible-creeper** [pterodactyl/panel#4264]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

if you have a lot of nodes that is not usable, panel will try to connect to nodes and it will cause panel unstable
so if i have a button to enable and disable the node without delete it,and i think the problem that panel keep connect will fix

### Describe the solution you'd like.

just a button to enable and disable the node

### Additional context to this request.

if the node is not usable and it will keep connect
![image](https://user-images.githubusercontent.com/32015407/179769616-bfd3eb5e-2430-4d5c-a89d-25113670db5f.png)

**Comment by DaneEveritt** [comment]
I'm not adding this — if your node is offline you should be fixing that. You're probably running into #3936.
