### ISSUE TITLE
Schedules are ignoring delays

### ISSUE THREAD

**Issue by RealRunSpace** [pterodactyl/panel#4268]
### Current Behavior

Schedules that are above 20s delays in total they just ignore them and act as 1s delays instead of waiting the defined amount of seconds

### Expected Behavior

Commands/Actions should wait theirdefined delays

### Steps to Reproduce

I just hit "Run now" and everything executes without waiting and I also get a warning saying "ERROR
timeout of 20000ms exceeded" on top

### Panel Version

1.9.2

### Wings Version

1.6.4

### Games and/or Eggs Affected

Any

### Docker Image

Any

### Error Logs

```bash
https://ptero.co/ezejopobuc

No logs for panel
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RealRunSpace** [comment]
Still having issues in a new dedicated serevrs, delays are getting completely ignored and sometimes commands are getting even mixed

**Comment by RealRunSpace** [comment]
Still happening in new fresh installation

**Comment by Boy132** [comment]
What queue driver are you using? (`QUEUE_CONNECTION` or `QUEUE_DRIVER` in your .env file)

**Comment by RealRunSpace** [comment]
I'm using `file` as the cache driver

**Comment by Boy132** [comment]
> I'm using `file` as the cache driver

I meant the _queue_ driver, mb.

**Comment by RealRunSpace** [comment]
For queue I'm using `sync`

**Comment by Boy132** [comment]
That's the problem. `sync` basically means "no queue at all".
Use `redis` (recommended) or `database` as queue driver.

**Comment by RealRunSpace** [comment]
Oh okay, can I just change it to `mysql` in the config and that should just work or I should do something else before?

**Comment by Boy132** [comment]
`database` would be the driver for mysql. Change that in your .env file and restart pteroq afterwards.
(For further assistance you can visit the Discord.)

**Comment by RealRunSpace** [comment]
Great, I'll try it later on the day and I'll update (or close) the thread, thank you!

**Comment by RealRunSpace** [comment]
Working perfectly now, thanks you for the help @Boy132 !!

Closing issue now!
