### ISSUE TITLE
Add a sorting of the servers of minecraft by name

### ISSUE THREAD

**Issue by rejomy** [pterodactyl/panel#4269]
I want to see the sorting of servers, for example, somewhere at the top will be a small option in which you can select the sorting. I want servers starting with the letter A to be all together, not like this : 
HypixelNet
ApixelNet
CubeCraft
Acubic.org

I know that you can give a server a name, but it's not convenient to look for servers when there are a lot of them. I want to be able to give my 1st servers the name Grief1-10 and they were all together (tk.name), and some MiniGames 1-10 and they were also together.

**Comment by trenutoo** [comment]
Duplicate of #498
