### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by shlomi8801-2** [pterodactyl/panel#4271]
### Current Behavior

when im trying to create / delete / update something on the panel after i have installed 1.9.2 its allways give me 
your access is denied Access denied due to firewall policy violation
and issue id for support
![Screenshot 2022-07-22 092154](https://user-images.githubusercontent.com/89383732/180376212-ca3d6194-3bed-4d82-b2e9-97682fc80bd6.png)

also i checked the  I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system. box but im banned from the discord server for troling this is my username:"᲼᲼᲼#2395"

### Expected Behavior

allow me to update / delete / create things smoothly without access denied screen

### Steps to Reproduce

example going to the nests -> shlomi egg  -> code-server -> delete egg

### Panel Version

1.9.2

### Wings Version

1.6.1

### Docker Image

ghcr.io/parkervcp/yolks:nodejs_17

### Error Logs

```bash
http://bin.ptdl.co/cl00r
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by schrej** [comment]
Pterodactyl is not a firewall. Configure your firewall correctly.
