### ISSUE TITLE
Synology x2 Setup

### ISSUE THREAD

**Issue by flinthamm** [pterodactyl/panel#4272]
### Current Behavior

After a lot of  trial and error (and big thank you to @timothystewart6 for some pointers) I have the setup running over 2 physical Synology NAS systems but at the final hurdle feel I've missed the last piece of the puzzle (probably understanding!). The Nginx reverse proxy is setup on both systems to provide 443 port access to the HTTP port of both the panel and wings containers. The panel is running and has a green heart to confirm successful communication to the daemon. 

The problem is, I cannot create any servers (and I suspect this is because of both understanding or rather lack there of, and potentially compatibility with the docker and OS)? With wings debugging enabled the panel successfully communicates with the daemon and pulls the image from the egg config but then always fails at the next stage with a bind error? To be exact:

```
failed to create server environment during install process error=environment/docker: failed to create container: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /volume1/docker/pterodactyl/lib/volumes/1d22...etc etc...e3 server=1d22-etc-etc-be3

Stacktrace:
wings_1  | Error response from daemon: invalid mount config for type "bind": bind source path does not exist....etc, etc
```

Whenever this error is looked up in the Discord channel, it's stated that the volume config in docker-compose must be the same for both sides i.e. the docker host and internal container which to me is counter intuitive and obviously not normal? I'm hoping someone here can shed some light and more to the point if anyone else has a similar setup working or can state that this is never going to work, despite having come so far and only fallen at the VERY last hurdle - Thank you anyone listening.

### Expected Behavior

For the panel to communicate with the Wings daemon and download and setup a docker image that has been configured from the panel.

### Steps to Reproduce

Please see explanation is current behaviour.

Both Synology systems are running the latest DSM 7.1 and the Docker version reported is 20.10.3.

### Panel Version

canary

### Wings Version

1.6.1

### Games and/or Eggs Affected

Minecraft Bedrock

### Docker Image

ghcr.io/parkervcp/yolks:debian

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Supporting Synology (or any NAS for that matter) systems is not something I care to put any effort into figuring out, sorry.
