### ISSUE TITLE
Permission to disallow viewing of console

### ISSUE THREAD

**Issue by Pendred** [pterodactyl/panel#4273]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When giving start, stop and restart permissions, it always allows the user to see the console. And for the servers I run, there is a lot of sensitive information such as player IP addresses etc, it would be really useful to either remove console viewing by default, or have a separate permission for viewing console without being able to run commands.

### Describe the solution you'd like.

Literally just an additional permission that grants "View Console" access, instead of it being given by default with restart permissions.

**Comment by DaneEveritt** [comment]
Duplicate https://github.com/pterodactyl/panel/issues/3466
