### ISSUE TITLE
MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by Minc3** [pterodactyl/panel#4274]
### Current Behavior

I'm testing the API examples but when I do a post request I get this.

```
{
    "errors": [
        {
            "code": "MethodNotAllowedHttpException",
            "status": "405",
            "detail": "The POST method is not supported for this route. Supported methods: GET, HEAD."
        }
    ]
}
```

### Expected Behavior

well i guess for it to work.

### Steps to Reproduce

Just run a curl using the example.

```
curl "http://example.com/api/client/servers/0f8b3199/resources" \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer APIKEYHERE' \
  -X POST \
  -b 'pterodactyl_session'='eyJpdiI6InhIVXp5ZE43WlMxUU1NQ1pyNWRFa1E9PSIsInZhbHVlIjoiQTNpcE9JV3FlcmZ6Ym9vS0dBTmx>
  -d '{
  "signal": "stop"
}'
```

### Panel Version

1.9.2

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TrixterTheTux** [comment]
The `/resources` endpoint doesn't accept a signal, you're most likely looking for the `/power` endpoint instead.
