### ISSUE TITLE
Translation system

### ISSUE THREAD

**Issue by MrKubuS** [pterodactyl/panel#4276]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Translation system

### Describe the solution you'd like.

Translation system

**Comment by 0x7d8** [comment]
I dont think you did search for feature requests for this

**Comment by Jelcoo** [comment]
There is an open pr for this,  #2888

**Comment by trenutoo** [comment]
Duplicate of #2518
