### ISSUE TITLE
Two-Step Verification QR code fails to scan on some devices

### ISSUE THREAD

**Issue by danny6167** [pterodactyl/panel#4277]
### Current Behavior

The QR codes as rendered in the "Enable Two-Step Verification" dialog are extremely difficult (and maybe impossible) to scan on some devices.

### Expected Behavior

QR codes should scan reliably on all devices

### Steps to Reproduce

Scan a QR code from Enable Two-Step Verification dialog on some devices and see that it won't scan, or will take a lot of tries to get it to read.

Removing the ``bg-gray-800`` class from the parent div vastly improved the situation for me, and was further improved by un-rounding the corners of the QR code image.

Does not scan well for me
![QR-1](https://user-images.githubusercontent.com/388231/180647456-801db97f-bf2f-4bc9-8234-22706c3ac0c9.PNG)

Scans very well for me
![QR-2](https://user-images.githubusercontent.com/388231/180647472-c5855cfe-bdf6-464b-a77b-06fb99d47aa6.PNG)

### Panel Version

develop @ eb503c5 (Also reported on 1.9.2 by community)

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ghost** [comment]
It's working by me.

Closed!
