### ISSUE TITLE
File uploads being detected as folders

### ISSUE THREAD

**Issue by jcsnider** [pterodactyl/panel#4280]
### Current Behavior

When uploading a .db (sqlite database file) the panel returns a `Folder uploads are not supported at this time.` error.

![](https://cdn.discordapp.com/attachments/458962374737657857/1000918969819078746/unknown.png)

Files with other extensions work fine.

### Expected Behavior

Files with a .db file extension should upload like any other file.

### Steps to Reproduce

Attempt to upload a .db file, the above error should occur. If you rename the file to have a different extension (ie jpg) then the upload will succeed, 

A workaround for now is that after uploading with a different extension you can rename the file within the panel to restore the extension.

### Panel Version

1.10.0

### Wings Version

1.7.0

### Games and/or Eggs Affected

NA

### Docker Image

NA

### Error Logs

```bash
Wings: https://ptero.co/gigifovihu
Panel: NA -- Panel has not been creating logs since Jan 2021, probably an issue with my docker configuration/directory permissions, will attempt to resolve and append.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by james121op** [comment]
same issue here

**Comment by Doc94** [comment]
Confirmed since 1.10.0, the issue its here https://github.com/pterodactyl/panel/blob/1cfa4100adbd51102fc1afdbc581423fd5582fca/resources/scripts/components/server/files/UploadButton.tsx#L75 where type not handle for all type of files.. this also happen with many other file types..

**Comment by AlexTheGoat69** [comment]
when will this be fixed.

**Comment by GeekCornerGH** [comment]
Use SFTP as a workaround

**Comment by Rajdave69** [comment]
Yep, happened to me too since the last panel update!

**Comment by TheRealMothebad** [comment]
Currently having this issue with a file named "r.0.0.mca"

**Comment by Doc94** [comment]
> Currently having this issue with a file named "r.0.0.mca"

This was fixed but not already released.

**Comment by TheRealMothebad** [comment]
> > Currently having this issue with a file named "r.0.0.mca"
> 
> This was fixed but not already released.

Makes sense, thank you!

**Comment by DenishProfile** [comment]
> Currently having this issue with a file named "r.0.0.mca"

same
