### ISSUE TITLE
Can't update maintenance mode with application API

### ISSUE THREAD

**Issue by JoshNotWright** [pterodactyl/panel#4288]
### Current Behavior

Endpoint: /api/application/nodes/X
Object "maintenance_mode" is ignored on PATCH request

### Expected Behavior

The endpoint should accept "maintenance_mode" update

Solution: Add 'maintenance_mode' to /app/Http/Requests/Api/Application/Nodes/StoreNodeRequest.php

return collect($rules ?? Node::getRules())->only([
            'public',
            'name',
            'location_id',
            'fqdn',
            'scheme',
            'behind_proxy',
            **'maintenance_mode',**
            'memory',
            'memory_overallocate',
            'disk',
            'disk_overallocate',
            'upload_size',
            'daemonListen',
            'daemonSFTP',
            'daemonBase',
        ])->mapWithKeys(function ($value, $key) {
            $key = ($key === 'daemonSFTP') ? 'daemonSftp' : $key;

### Steps to Reproduce

Make a PATCH request to /api/application/nodes/x 

**Maintenance Mode will not change**

with: 

                {
                "name": "NODETEST",
                "description": "TESTEXX",
                "location_id": 1,
                "fqdn": "nodetest.domain.com",
                "scheme": "https",
                "behind_proxy": false,
                "maintenance_mode": false,
                "memory": 6144,
                "memory_overallocate": -1,
                "disk": 750000,
                "disk_overallocate": -1,
                "upload_size": 100,
                "daemon_listen": 443,
                "daemon_sftp": 2022
                }

### Panel Version

1.10.1

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Ferks-FK** [comment]
I can confirm the problem, all are updated except `maintenance_mode`.

**Comment by matthewpi** [comment]
If I remember correctly, maintenance mode doesn't even work since v1.  It's functionality was never implemented.  While this issue is about the field not updating, it still relates as there isn't really a reason to set that field if it doesn't do anything.
