### ISSUE TITLE
Split the read-content permission

### ISSUE THREAD

**Issue by Timtendo12** [pterodactyl/panel#4289]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to give a user permission to edit a file but not to download a file. This is to protect custom-coded executable files/plugins (for example) from being downloaded and leaked on the internet since they can't be edited in the panel text editor.

### Describe the solution you'd like.

Split the read-content permission into a "read-content" and "download-content" permission! 

### Additional context to this request.

It would be awesome and add extra security for your custom-coded executables and plugins.

**Comment by TrixterTheTux** [comment]
But being able to read a file means that can be just saved thus download it?

**Comment by yesBad** [comment]
> But being able to read a file means that can be just saved thus download it?

You can't read .jar's, archives etc.

**Comment by devnote-dev** [comment]
See issue #2917.

**Comment by Timtendo12** [comment]
I see that it's closed because of possible confusion between SFTP and downloading a file from the panel. However, I don't see the issue really. If the description of the permission is clear then it shouldn't cause any confusion. And people who don't want to allow downloads will not allow SFTP in the first place.

**Comment by Timtendo12** [comment]
Its just that one little button that needs to disappear xD

**Comment by TrixterTheTux** [comment]
> You can't read .jar's, archives etc.

This is only restricted on the frontend. Even if there was separate download permission, the file can still be read and thus saved. It simply doesn't make sense to be separate permission when reading files implies you can download them. Alternatively, they just shouldn't be able to edit those files at all which #2757 would solve properly.

**Comment by devnote-dev** [comment]
> I see that it's closed because of possible confusion between SFTP and downloading a file from the panel. However, I don't see the issue really. If the description of the permission is clear then it shouldn't cause any confusion. And people who don't want to allow downloads will not allow SFTP in the first place.

If you can read the file contents then you can just copy the contents, it makes the download permission redundant, hence the confusion.

**Comment by YusufYaser** [comment]
You can also just go to `https://pterodactyl.test/api/client/servers/[server uuid]/files/contents?file=/server.jar` to download a jar file or really any file, replacing the `/server.jar`, `pterodactyl.test`, and `[server uuid]` parts in the URL.

**Comment by devnote-dev** [comment]
> You can also just go to `https://pterodactyl.test/api/client/servers/[server uuid]/files/contents?file=/server.jar` to download a jar file or really any file, replacing the `/server.jar`, `pterodactyl.test`, and `[server uuid]` parts in the URL.

Not necessarily, the API also checks permissions beforehand (see [GetFileContentsRequest](https://github.com/pterodactyl/panel/blob/develop/app/Http/Requests/Api/Client/Servers/Files/GetFileContentsRequest.php) and [DownloadFileRequest](https://github.com/pterodactyl/panel/blob/develop/app/Http/Requests/Api/Client/Servers/Files/DownloadFileRequest.php)).

**Comment by YusufYaser** [comment]
> > You can also just go to `https://pterodactyl.test/api/client/servers/[server uuid]/files/contents?file=/server.jar` to download a jar file or really any file, replacing the `/server.jar`, `pterodactyl.test`, and `[server uuid]` parts in the URL.
> 
> Not necessarily, the API also checks permissions beforehand (see [GetFileContentsRequest](https://github.com/pterodactyl/panel/blob/develop/app/Http/Requests/Api/Client/Servers/Files/GetFileContentsRequest.php) and [DownloadFileRequest](https://github.com/pterodactyl/panel/blob/develop/app/Http/Requests/Api/Client/Servers/Files/DownloadFileRequest.php)).

The panel uses this API endpoint to view file contents (according to the Network tab in F12), and if file doesn't download after going to this URL then just CTRL+S

**Comment by devnote-dev** [comment]
> The panel uses this API endpoint to view file contents (according to the Network tab in F12), and if file doesn't download after going to this URL then just CTRL+S

Yeah, I thought you meant bypassing the permission check.

**Comment by Timtendo12** [comment]
> > The panel uses this API endpoint to view file contents (according to the Network tab in F12), and if file doesn't download after going to this URL then just CTRL+S
> 
> Yeah, I thought you meant bypassing the permission check.

I notice that you once made a pull request for the separation of the permission. Can you confirm that it still works?

**Comment by devnote-dev** [comment]
> I notice that you once made a pull request for the separation of the permission. Can you confirm that it still works?

I have never made such a PR.

**Comment by DaneEveritt** [comment]
This is an impossible condition — notably because as was mentioned above, if you can read a file you can therefore download a file. I don't do any advanced permissions checking against file types because it would be pointless complexity, and is also trivial to bypass with file header modification.

Additionally, it gets incredibly confusing for users when permissions are inconsistent. A "read only" permission would not apply correctly in a SFTP context because that would fall victim to the same issues as above.

You might be looking for file specific permissions like #2757.
