### ISSUE TITLE
Skip Service Option Install Script doesn't works

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#429]
Currently trying to install new servers with my own private image (based on old ptero image), I can't create a new csgo server even if i tick the `Skip Service Option Install Script` button.

Log: `"msg":"No installation script was defined for this service, skipping rest of process."`

All previously installed servers works like a charm.

Edit: v0.6.0

**Comment by jffz** [comment]
Tempfix (thanks to @schrej)

Create a dummy script for desired service
i.e: `true`

**Comment by DaneEveritt** [comment]
closed in https://github.com/Pterodactyl/Daemon/commit/5e8d21bccfd4831b1bed7bb2fc14bfaef60c14b7
