### ISSUE TITLE
Option to disable Checking server disk space usage"

### ISSUE THREAD

**Issue by MinecollYT** [pterodactyl/panel#4294]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I'm currently having the problem that one of my servers has a huge dynmap (more than 150 GB) and it's taking ages (about 10 minutes) for the "Checking server disk space usage" check. Having an option to disable this check would allow my server to start faster.

(I'm not talking about the file permission check. I've already disabled that.)

### Describe the solution you'd like.

Having an option to disable it in the wings configuration, same as the checking file permissions. E.g.:

```
  check_permissions_on_boot: false
  check_space_usage_on_boot: false
```

**Comment by DaneEveritt** [comment]
If we don't check it on boot it is just going to lock up the moment you try to do anything else that requires knowing the disk space. This seems more like an issue with your underlying disks being far too slow for the software running on them.

I honestly don't have any solutions for you, but we need to be able to calculate the disk space and have put an unholy amount of hours into trying to build that to be as performant as possible.

**Comment by parkervcp** [comment]
Volumes aren't part of the disk space check right?

**Comment by DaneEveritt** [comment]
Which volumes? Like for mounts? Correct, I suppose you could use one to hold all of the dynmap tiles, you'd have to update the path though since it cannot be mounted inside the `/home/container` directory.

**Comment by parkervcp** [comment]
That is what I meant yes.

**Comment by Jcodeerd** [comment]
Or you could use MySQL for dynmap

**Comment by MinecollYT** [comment]
But the tiles still have to be saved somewhere

**Comment by MinecollYT** [comment]
And thanks for the volume part idea, I'll try that out!
