### ISSUE TITLE
DNS error only between PANEL and NODE

### ISSUE THREAD

**Issue by infectedw** [pterodactyl/panel#4297]
### Current Behavior

Installed PANEL on host1 and NODE on host2, created server on NODE, when launching server.jar from PANEL getting error like `java.net.UnknownHostException: launcher.mojang.com` adding manually `mojang_1.18.2.jar` starts server but then I get errors where most of plugins cannot check for update or any link. 

Starting server directly from host2 where NODE is located starts server fine with no problems.

**DNS is configured correctly on both hosts since I can ping, update, wget and access those sites what server.jar from PANEL cannot access.**

So, **PANEL** or host1 have DNS configured correctly, (This is 100%, checked everything and I can access directly from `SSH` what panel can't.)
and, **NODE** or host2 have also DNS configured correctly. (This is 100%, checked everything and I can access directly from `SSH` what panel can't.)

Also to say, **NODE** is hosted on Hetzner Robot located in Falkenstein.

Tried these FORKS:

1. Spigot
2. Paper
3. Pufferfish
4. Petal
5. Purpur

None of FORKS above won't work since they cannot access `launcher.mojang.net`, adding `mojang_1.18.2.jar` don't fix the problem since again plugins can't check for updates since they cannot access sites for update check.

Spent more around 5 days fixing this problem no luck still, decided to try here and see if someone can help me. Thanks

![IMG_20220802_230249_001](https://user-images.githubusercontent.com/26207600/182476677-4e63c018-68ac-4569-9274-b4c789982010.jpg)
.

### Expected Behavior

Expected behavior should be,

PANEL on host1
NODE on host2

Normally creating/starting/stopping servers from **PANEL** to **NODE** without accessing some sites problem.

### Steps to Reproduce

Installing latest 1.9 version of PANEL on VPS and connecting it to latest 1.6 WINGS (NODE).

### Panel Version

1.9

### Wings Version

1.6

### Games and/or Eggs Affected

Minecraft (Paper)

### Docker Image

ghcr.io/pterodactyl/yolks/:java_17

### Error Logs

```bash
PANEL: http://bin.ptdl.co/6d15f
NODE/WINGS: https://ptero.co/alefahehur
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
Did you try to restart docker? That can sometimes fix it. Also, wings latest is 1.7.0

**Comment by DaneEveritt** [comment]
Thousands of other users run with this exact setup with no issues, myself included.

I'm not putting time into looking into this more, apologies but this really seems unlikely to be the fault of this software.

**Comment by BoryaGames** [comment]
Restarting docker helped, for anyone with the same problem: `systemctl restart docker`

**Comment by KornineQ** [comment]
same issue
