### ISSUE TITLE
unban on discord

### ISSUE THREAD

**Issue by dawixeuu** [pterodactyl/panel#4299]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

hello my discord adyz#1562 has ben hacked and i banned for advertising because i have hacked discord can you unban me? adyz#1562

### Describe the solution you'd like.

hello my discord adyz#1562 has ben hacked and i banned for advertising because i have hacked discord can you unban me? adyz#1562

**Comment by WavingCatDevs** [comment]
Nice feature request 👍

**Comment by schrej** [comment]
If you're unable to properly secure your account that's on you. In addition this is an issue tracker and not a support forum.
