### ISSUE TITLE
Srcds (csgo) status not showing

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#430]
No infos is gathered on CS:GO containers even if they works without any issue, see screenshot.

![image](https://cloud.githubusercontent.com/assets/8946360/25853605/b662d4fe-34cd-11e7-9ddc-44349f0d912b.png)

**Comment by KasperFranz** [comment]
have you just updated? 

if so try to clear your cache (ctrl + f5)

**Comment by ET-Bent** [comment]
Maybe related:

![selection_647](https://cloud.githubusercontent.com/assets/5788982/26174961/560f70f0-3b51-11e7-8431-82e861032514.png)

Panel makes requests to:

```/server/<serverid>/ajax/status``` is broken, yet

```/server/<serverid>/status``` works fine

**Comment by DaneEveritt** [comment]
I am unable to replicate this for any server. It appears you might have an old file cached.
