### ISSUE TITLE
Feature for panel

### ISSUE THREAD

**Issue by joaoespanhol** [pterodactyl/panel#4304]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

1. Addon - Discord OAuth2 Login
2. Addon - Register panel pterodactyl
3. Button for phpmyadmin
4. Addon - cloudflare for domain generator sub domain
5. Addon bot discord for restart server for discord
6. Addon - Ticket System

7. Addon mincrat:
  -    Addon - Minecraft Player Manager | Manage players from the panel - Op, Kick, Ban, IP Ban, Whitelist [1.2]
  -    Addon download plugin/mod curseforget and spigot

8. Addon - Player Counter
   - Supported Games:
      - Minecraft
      - MinecraftPE
      - Counter Strike: Global Offensive
      - Counter Strike 1.6
      - Counter Strike Source
      - Garry's Mod
      - Insurgency
      - Insurgency: Sandstorm
      - Team Fortress 2
      - Multi Theft Auto
      - San Andreas Multiplayer
      - Five:M
      - Call of Duty 2
      - Call of Duty 4
      - Unturned
      - Left 4 Dead 2
      - Arma 3
      - Mordhau
      - Rust
      - Hurtworld
      - Half Life
      - Conan Exiles
      - Seven Days to Die
      - Ark Survival Evolved
      - Battlefield 3
      - Mumble

### Describe the solution you'd like.

to help everyone manage the dashboard :)to help everyone manage the dashboard :)

**Comment by TrixterTheTux** [comment]
Please check existing issues first.

**Comment by joaoespanhol** [comment]
> 

i no find this feature request :(

**Comment by TrixterTheTux** [comment]
1. https://github.com/pterodactyl/panel/pull/3774#issuecomment-1081045180
2. #3408
3. #1170
4. #3647 
5. -, redoing the panel functionality inside Discord makes no sense and sounds painful to maintain (vs. just opening the panel?)
6. -, use actual support software made just for this?
7. #4029 
8. #3650
