### ISSUE TITLE
Long lua functions via console breaks 

### ISSUE THREAD

**Issue by rubiksw** [pterodactyl/panel#4307]
### Current Behavior

My experience with this issue is specific to source engine games like Garry's Mod, but maybe other games as well. 

Trying to run a lua function via the console using "lua_run <command/function>" will break if the function is longer than a certain number of characters, as if the console is adding a line break somewhere. 

### Expected Behavior

Being able to run long lua functions via the console with lua_run without erroring out.

### Steps to Reproduce

Try and run a Lua function via the console with lua_run. If the function is over a certain number of characters, it will break. 

### Panel Version

1.9.1

### Wings Version

1.9.1

### Games and/or Eggs Affected

Garry's Mod

### Docker Image

ghcr.io/pterodactyl/games:source

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
There is not enough information available here for me to try to reproduce this issue. You must provide an actual command that breaks. "If the function is over a certain number of characters" is not enough details.
