### ISSUE TITLE
Don't update local docker images

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#431]
Before automatically updating docker images with the daemon we should check if the image is actually published on a repository or not.

If the image name contains two slashes we always try to pull. If it has only one slash we should check if it actually exists on docker hub, if it doesn't, don't try to pull.

**Comment by xyeLz** [comment]
This would be very helpful for me since I am trying to run a Call of Duty 4 server that I built locally. The reason I built this locally is because the CoD4 installation files are about 5GB so I uploaded them to my host and built the image rather than uploading them elsewhere and having the daemon download multiple GB worth of files. After the image existed, I attempted to use this in the panel but, like @schrej mentioned above, it kept trying to pull from Docker Hub instead.

**Comment by DaneEveritt** [comment]
I was under the assumption that `docker pull` is smart enough to check locally before checking remote. All the daemon does is wrap that API call, so unless there is something missing (potentially true), it should work the same as a standard pull which will go local before remote.

**Comment by schrej** [comment]
Docker pull tries to update the image in question. If it is a local only image you would never pull. And if you pull without registry it assumes docker hub.

**Comment by Altegras** [comment]
Pretty old bug, here is a workaround if you really need to use a local image


```
# docker run -d -p 127.0.0.1:5000:5000 --name registry registry:2
# docker tag <local/image:tag> localhost:5000/my-awesome-image
# docker push localhost:5000/my-awesome-image
```

Now use in the panel for docker image:

> localhost:5000/my-awesome-image

It will try to pull corectly and setup as needed.

**Comment by DaneEveritt** [comment]
This is fixed now. To mark an image as local in the Panel simply prefix it with `~`.

**Comment by chelog** [comment]
This is happening to us now after updating panel to 1.0 and setting up new Wings. Can't run a server with local custom image
```
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as stopping...
container@pterodactyl~ Server marked as offline...
container@pterodactyl~ Error Event [9820182f-7a9f-47ff-b6b0-0c3ea6375586]: Error response from daemon: pull access denied for octoteam/gmod, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by DaneEveritt** [comment]
Please open a new issue, I won't re-open issues from 2018.
