### ISSUE TITLE
 controlled file access

### ISSUE THREAD

**Issue by LuftigerLuca** [pterodactyl/panel#4310]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be cool if you didn't always have to give a user who is added to a game server permissions to all files if he should be able to see a few, but only permissions to certain folders.

### Describe the solution you'd like.

When assigning rights to additional users on game servers, I would add another dialog box in which you can specify folders to which the user should have access

**Comment by trenutoo** [comment]
Duplicate of #2757
