### ISSUE TITLE
User search does not work

### ISSUE THREAD

**Issue by risingfish** [pterodactyl/panel#4312]
### Current Behavior

I have a user with the user name zac. When I try setting up a server for him, the 'Server Owner' field can't seem to find him. I have noticed other similar inconsistent behavior where users cannot be found even after spelling out their entire name.

![image](https://user-images.githubusercontent.com/1024515/184060460-cfe34412-b5c4-4149-ad45-9c4864505c52.png)

### Expected Behavior

When I search for the username 'zac', typing both 'za' and 'zac' will find the user.

### Steps to Reproduce

1. Add a user named 'zac'
2. Create a new server and try setting 'zac' as the owner.

### Panel Version

1.10.1

### Wings Version

1.7.0

### Games and/or Eggs Affected

None, affected the panel only

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
User search checks by email not by username or first/last name.

**Comment by trenutoo** [comment]
As mentioned above it's filtering by email. Username search is implemented in V2.

https://github.com/pterodactyl/panel/blob/v2/resources/scripts/components/admin/servers/OwnerSelect.tsx#L15
