### ISSUE TITLE
The panel takes a long time to load and gives Timed Out when one of the nodes is turned off

### ISSUE THREAD

**Issue by HellRayka** [pterodactyl/panel#4314]
### Current Behavior

When one of the nodes is turned off, the panel starts to load for a long time and gives timed out. I also found out that this problem occurs only when one of the users in the panel sees a server that is on this disabled node. On a clean node, I gave out 3 servers on my account, logged in from another account where there was a server from another working node, everything worked fine, as soon as I logged into the account where there were 3 servers on the disabled node, the panel immediately began to load long and gave timeout, when I left my account, the panel immediately worked. Im using cloudflare for this panel. Panel on vps, nodes on dedicated servers.

### Expected Behavior

Stable working panel.

### Steps to Reproduce

Reinstalling wings, reinstalling the panel, setting up cloudflare.

### Panel Version

1.10.1

### Wings Version

1.7.0

### Games and/or Eggs Affected

Minecraft (Paper), Minecraft (Bungeecord)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
Wings: https://ptero.co/nyhanuzexy
Panel: http://bin.ptdl.co/fedsd
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
For the love of all that is holy, please use the search before opening issues.

https://github.com/pterodactyl/panel/issues/3936

**Comment by HellRayka** [comment]
Ah, I'm sorry, but that hasn't been fixed in half a year

**Comment by DaneEveritt** [comment]
Opening new issues does not make things go any faster. :)
