### ISSUE TITLE
Cannot create MySQL Database on Web Panel

### ISSUE THREAD

**Issue by Trollol01** [pterodactyl/panel#4315]
### Current Behavior

Hi, I've tried to create a new database using web panel, but it's says "There was an error while trying to connect to the host or while executing a query SQLSTATE[HY000] [1044] Access denied for user to database". I have created another Database user, granting him all privileges using the commands in this official [guideline](https://pterodactyl.io/tutorials/mysql_setup.html), but after all it didn't work
![Screenshot_101](https://user-images.githubusercontent.com/62749150/184332967-4c6a18cb-0010-4d81-a558-9b950a4f1a46.jpg)
![Screenshot_102](https://user-images.githubusercontent.com/62749150/184332970-5680f5fe-097c-4948-b7e0-bd6a0db6cb96.jpg)
![Screenshot_103](https://user-images.githubusercontent.com/62749150/184332972-a76531eb-4409-4299-a3d8-fea8fe429365.jpg)
![Screenshot_104](https://user-images.githubusercontent.com/62749150/184332974-ddea15e4-4a64-47d8-8184-dc32b5ddaf22.jpg)
![Screenshot_105](https://user-images.githubusercontent.com/62749150/184332961-a8c767ce-7f23-4ed3-b1a2-ebe1e70dc4e7.jpg)
![Screenshot_106](https://user-images.githubusercontent.com/62749150/184334298-73f95136-7336-4e75-bac5-30f27a0d2b32.jpg)

### Expected Behavior

Create a new database on panel

### Steps to Reproduce

Open web panel, open the Database section on the left menu of the screen, click create new button, insert credentials and the ip host and click the green button to create.

### Panel Version

1.10.1

### Wings Version

1.7.0

### Games and/or Eggs Affected

Minecraft(Paper) Minecraft(Bungeecord) Minecraft(Sponge) Minecraft(Vanilla) Minecraft(Forge)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
Wings: https://ptero.co/yfibekyjub

Panel: tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99
tail: cannot open '/var/www/pterodactyl/storage/logs/laravel-2022-08-12.log' for reading: No such file or directory
Use netcat.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
> [x]  I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

Well well well.

Please use the discord for configuration problems. Your user has insufficient permissions.

**Comment by Trollol01** [comment]
Can you send me a command to fix the user permissions?

**Comment by Boy132** [comment]
Again, please ask on the discord.

**Comment by Trollol01** [comment]
Ok, thank you ✌️
