### ISSUE TITLE
Update html forms to remove the protocol and domain from the action attribute.

### ISSUE THREAD

**Issue by risingfish** [pterodactyl/panel#4316]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

For servers running behind proxies, or network setups using SSL offloading, including the protocol and server name causes problems. For example, when creating a new server the form looks like this:

`<form action="http://ptero.exaple.com/admin/servers/new" method="POST">`

If the server sits behind a reverse proxy that uses SSL ofloading, this causes the browser to throw a warning and then submit the page via not secure `http` instead of `https`. If the form action were to look like this:

`<form action="/admin/servers/new" method="POST">`

The form would inherit the server name and protocol and would correctly submit the form via https. There might be architectural reason I am not aware of, but I wanted to bring this up as a feature request to talk about.

### Describe the solution you'd like.

Remove the protool and FQDN from urls and form actions.

### Additional context to this request.

See my description above.

**Comment by DaneEveritt** [comment]
Not needed, is solved by setting up the proxy correctly. https://pterodactyl.io/panel/1.0/additional_configuration.html#reverse-proxy-setup

**Comment by risingfish** [comment]
That's fine if someone is using nginx as a proxy, but not everyone does.

**Comment by risingfish** [comment]
I should be more specific, I'm using haproxy as a proxy, not nginx. Your proxy configuration verbiage does not seem to work for that.

**Comment by DaneEveritt** [comment]
You'll have to configure it appropraitely based on the details there, again its not a bug or change in the software that is needed. The proxy just needs to be setup in such a way that Laravel can figure out it is indeed behind a proxy.

There should be guides for generic Laravel proxy support with haproxy that will work fine. Also as long as your `APP_URL` is set with `https` it should force everything to HTTPS anyways.

**Comment by risingfish** [comment]
It was surprisingly difficult to find but is anyone is finds this and you're running this is the haproxy backend directive you need to allow Laravel to use the correct protocol:

`http-request add-header X-Forwarded-Proto https if { ssl_fc }`

To view the Game Server console output you need to setup add separate haproxy backend for port 8080 and use this directive for it:
`http-request add-header X-Forwarded-Proto wss if { ssl_fc }`
