### ISSUE TITLE
Backup download feature not working S3-Minio

### ISSUE THREAD

**Issue by rainerstudios** [pterodactyl/panel#4317]
### Current Behavior

The download button doesn't work using Minio s3 for the backups 

![donwload](https://user-images.githubusercontent.com/21259511/184473782-661f6218-3d62-42c9-b97a-9b0ed27e818a.png)

### Expected Behavior

The server backup should initiate download but nothing happens 

### Steps to Reproduce

Add minio as S3 backup option 

### Panel Version

1.10.1

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.
-

**Comment by nikrozman21** [comment]
Works fine for many of us. Is your MinIO instance set up correctly?

**Comment by rainerstudios** [comment]
@nikrozman21 Yes, I believe minio is set up correctly, as we can backup and restore, but downloads are not working.  I have also reached out to a couple of users on discord and they too cannot download the backups 

What exactly do you mean by setting up correctly? and below is my env file
![env](https://user-images.githubusercontent.com/21259511/184493130-9eafb537-93a4-4b29-9bd1-bccc0c1c1c91.png)
?

**Comment by Romitou** [comment]
Make sure that the endpoint of your S3 server is an address accessible from your machine as Pterodactyl retrieves a pre-signed address from your S3 to access the object corresponding to your backup.

Alternatively, go to the developer menu of your browser and inspect the requests in the Network tab to see if the URL returned by Pterodactyl is correct.

**Comment by rainerstudios** [comment]
@Romitou so the url I get on the network is correct and can download the backup on another tab, can the issue be with the `UNSIGNED-PAYLOAD` part?
`Request URL: http://55.21.94.202:9000/mybacket/c1aae4ec-47ec-453f-84db-442db1ce67a9/9b85573f-08a4-4460-8fdf-413a4a8d3b22.tar.gz?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xadmin%2F20220814%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220814T061527Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Signature=4c5b86a1d27334d74f539367bbbc2fc111536fb2459d617e0703a63898ccf864
`

**Comment by Boy132** [comment]
Please post panel logs.
`tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc pteropaste.com 99`

**Comment by rainerstudios** [comment]
https://pteropaste.com/iqfpnz/ @Boy132

**Comment by rainerstudios** [comment]
I have found the issue 
I needed to add
AWS_USE_PATH_STYLE_ENDPOINT=true
and use Minio with SSL
