### ISSUE TITLE
add Application API to change server power status

### ISSUE THREAD

**Issue by 502647092** [pterodactyl/panel#4321]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I need develop whmcs addons to direct control pterodactyl servers
Client API have `/api/client/servers/1a7ce997/power` to change server power status but Application API not have

### Describe the solution you'd like.

add Application API `/api/application/servers/10/power` allow application to control

**Comment by TrixterTheTux** [comment]
Just use the client API instead, there's no point in having exact same endpoints in both of them.

**Comment by trenutoo** [comment]
As Trixter mentioned above; client key can access both APIs and the application api key is planned to be deprecated.

**Comment by 502647092** [comment]
emm https://github.com/pterodactyl/whmcs still use Application API. When will it be updated.

**Comment by trenutoo** [comment]
Application api is not being deprecated. The application api key is, because client key can access both APIs as mentioned in release notes.

The WHMCS module doesn't use anything that requires the client api, unlike your modifications.
