### ISSUE TITLE
Support `TRUSTED_PROXIES` in Wings

### ISSUE THREAD

**Issue by liorsl** [pterodactyl/panel#4324]
### Current Behavior

When viewing the activity logs, some of the action's IP addresses are included in the TRUSTED_PROXIES field, and thus does not indicate of the actual user IP.  Apparently, it happens on actions logged by wings. 

### Expected Behavior

Wings will pass the real (user) IP instead of the proxy IP.

### Steps to Reproduce

Setup panel & wings behind Cloudflare proxy, set TRUSTED_PROXIES with ips from cloudflare's website and perform an action on wings. 

### Panel Version

1.10.1

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by elitetheespeon** [comment]
Can confirm, I use Cloudflare and have the correct real IP from any action logged via the panel, but with wings being proxied, it does not get the IP of the client from any action logged via wings. As this feature was added recently, it seems like wings needs to have a similar config to use the IP passed in the X-Forwarded-For header if it matches one in TRUSTED_PROXIES

**Comment by matthewpi** [comment]
Wings should have it's own separate trusted proxies configuration, I don't think utilizing the Panel values is a wise idea, especially since Panel's and nodes will end up having different proxies in different configurations, or even none.

**Comment by danny6167** [comment]
I've thrown together something to fix this and can PR it soon for you to take a look at
