### ISSUE TITLE
Unattended user creation

### ISSUE THREAD

**Issue by nicotsx** [pterodactyl/panel#4327]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to be able to create a user as suggested with `php artisan p:user:make` but without having to do it manually.

### Describe the solution you'd like.

I'm using docker so there would be two solutions:
1. Allow environment variable for `username` and `password`  
2. Provide a way to run the command on startup

```
pterodactyl:
    image: ghcr.io/pterodactyl/panel:v1.10.1
    command: whatever && php artisan p:user:make --username anything --password hello
```

### Additional context to this request.

To give more context I'm building https://github.com/meienberger/runtipi which is a homeserver manager. Some of my users have requested me to add Pterodactyl panel as an app. Since my app is made to be usable for everyone I cannot ask them to enter in the docker container and create the user.

**Comment by hwalker928** [comment]
`--username` and `--password` are already parameters? https://pterodactyl.io/community/tutorials/artisan.html#create-user

**Comment by nicotsx** [comment]
Thanks @hwalker928 I missed that part from the docs! Closing as I managed to make it work
