### ISSUE TITLE
Panel using whatever ip/domain the client connects with.

### ISSUE THREAD

**Issue by ccarney16** [Pterodactyl/Panel#433]
I have a reverse proxy setup and I have noticed an odd bug with pterodactyl not enforcing the root URL with APP_URL. Within a test (using localhost as the primary server name), when I connect to http://localhost, it will use http://localhost. However when I use anything pointing to the host, it will use that instead. 

The webserver (nginx 1.12) uses the provided configuration from the docs mostly unaltered (the usual changes such as domain name, and php-fpm socket).

APP_URL: `http://localhost`
what is intended:  `<form id="loginForm" action="http://localhost/auth/login" method="POST">`

what is not intended: ` <form id="loginForm" action="http://127.0.0.1/auth/login" method="POST">`
`<form id="loginForm" action="http://c-vm/auth/login" method="POST">`

**Comment by schrej** [comment]
Try adding `TRUSTED_PROXIES` with the IP of your proxy (or a comma separated list if there are multiple) to your .env file.

Run `php artisan config:cache` afterwards to apply the settings and see if that does the trick.

**Comment by ccarney16** [comment]
`TRUSTED_PROXIES` doesnt seem to work, however I got the panel to work with a single server name now. Just wondering on what APP_URL is mainly for (other than the daemon configuration) since it doesn't look like its enforcing the front end setup.

**Comment by DaneEveritt** [comment]
It's used in emails and queues, not with anything users would be seeing front-end.

**Comment by DaneEveritt** [comment]
Are you sure you're passing the correct proxy headers with the requests @ccarney16? The proxy system in use does require that valid headers be passed. This isn't really a bug in the panel at all, its just a proxy configuration issue.
