### ISSUE TITLE
Saving node settings resets some configuration values to default

### ISSUE THREAD

**Issue by IvMisticos** [pterodactyl/panel#4333]
### Current Behavior

When saving settings in panel, it resets many configuration settings such as `api.host`, `api.port`

### Expected Behavior

It should not affect any settings other than the ones changed, especially if they are not even in panel

### Steps to Reproduce

1. Update the node settings in panel

### Panel Version

1.10.1

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danir-de** [comment]
Do you mean the part under the URL admin/nodes/view/NODEID/configuration ?
That configuration is just a generator for you to manually setup on the wings server node.

**Comment by IvMisticos** [comment]
/admin/nodes/view/X/settings, when saving this it automatically resets some values as mentioned above. Settings, not configuration

**Comment by DaneEveritt** [comment]
I do not understand the issue you are reporting, please provide screenshots or more detailed steps.

**Comment by IvMisticos** [comment]
```
1. Open node Settings: /admin/nodes/view/1/settings
2. Update description there
3. Click "Save Changes"
4. Open /etc/pterodactyl/config.yml
5. You can notice that api.host and few other settings have been modified once you update the settings with steps above
```
Hope this is clear, if not I could let you know and show it in Discord @matthewpi
