### ISSUE TITLE
TS3 Servers not properly installing on 0.6.0 panel/0.4.0 daemon

### ISSUE THREAD

**Issue by o355** [Pterodactyl/Panel#434]
As the title says, I'm trying to install a TS3 server (latest and 3.0.13.6), and I run into a huge snag when it installs.

None of the files are available to the user! However, the .ini configuration file does exist, so that's a thing...I guess.

I tried doing some script modifications, directly going into `/mnt/server` at first, and also using the `--strip-components=1` flag with tar, but the entire folder is empty, still. The only way I see getting around this is through an SFTP upload.

The node where things are going wrong is running Ubuntu Server 16.04.2 LTS, PHP 7.0.15, and Docker 17.05.0-ce. The panel is on 0.6.0, and the daemon is on 0.4.0.

Great software, by the way!

**Comment by parkervcp** [comment]
Need to fix the TS3 service.

update your service variable to look like this.

![image](https://cloud.githubusercontent.com/assets/1207679/26059476/e985b276-394f-11e7-888d-d94c8025bb61.png)

**Comment by DaneEveritt** [comment]
Fixed in #436

**Comment by o355** [comment]
I'll try out the fix suggested by @parkervcp when I get the chance.
