### ISSUE TITLE
Pterodactyl backuping in his installation folder.

### ISSUE THREAD

**Issue by TheIceMagmaCube** [pterodactyl/panel#4341]
### Current Behavior

Pterodactyl will backup servers into his installation folder. It can fill a full drive of his backup, and i've never seen this in previous versions.
On my installation, Pterodactyl is installed in a small SSD and docker run of big fat hard drives, backup used to be in these drive, not on the small SSD.

### Expected Behavior

Place backup in a docker volumes, not into pterodactyl panel files

### Steps to Reproduce

Backup your server

### Panel Version

1.10.1

### Wings Version

1.7

### Games and/or Eggs Affected

Minecraft (Paper)

### Docker Image

ghcr.io/pterodactyl/yolks:java_18

### Error Logs

```bash
#
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
Pterodactyl does NOT backup into the panel files.
If you're using local file backup (the default) it will backup into the specified backup location. By default that is ``/var/lib/pterodactyl/backups/`` on the node and can be changed by changing it in the config file.

Unless you can demonstrate that your nodes are for some reason putting the backups in the wrong place then there is no bug. And if so, you will need to provide logs.
