### ISSUE TITLE
panel reporting incorrect ram usage resultinn crashing server

### ISSUE THREAD

**Issue by jirka086** [pterodactyl/panel#4342]
### Current Behavior

the server is limited to 7gb of ram but i set it to 9gb of ram the ram usage is 3gb but it reports 8gb when it reaches 9gb it crasehes the server but in reality its just 4gb of ram What is this 
![image](https://user-images.githubusercontent.com/53871380/187078935-aff4d40a-868a-491f-bcbe-d190a882d252.png)

### Expected Behavior

say the correct ram usage and not crashing the server due to incorrect ram usage report

### Steps to Reproduce

just create a server with limited ram the glitch dosent happen every time
Ubuntu 20.04 hosted in VM on Oracle Cloud

### Panel Version

1.10.1

### Wings Version

1.7

### Games and/or Eggs Affected

minecraft (paper)

### Docker Image

java17

### Error Logs

```bash
server crashes: out of memory but the server is using less ram than panel reports and crashes it
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by jirka086** [comment]
it can be fixed by setting memory to unlimited but limiting it in startup command
but it will be bether if it was accuret in the program

**Comment by parkervcp** [comment]
When you check ram usage in java is shows what is used but not what they have reserved. If you have issues with this drop the allocated memory by 512m with something like `-Xmx$(({{SERVER_MEMORY}}-512))M` instead of the default one.

This is not default as some people will try to allocate much less than they really should and it would cause more issues.

If you edited the startup to have the AlwaysPreAllocate option you didn't read the aikars flag guide that says to not to that.

**Comment by jirka086** [comment]
the main problem is that the panel says it uses 8gb of ram but the server just uses 3gb then it crashes the server becuze it is using too much ram but it uses 2x less than panel reports

**Comment by danny6167** [comment]
You need to read parkers response again.
Pterodactyl is reporting exactly what it's supposed to be reporting. The memory used by the software running in the container.
Java has allocated all that memory.

**Comment by DaneEveritt** [comment]
This is not a bug.
