### ISSUE TITLE
Can't establish connection after JSON Array to YAML Sequence 

### ISSUE THREAD

**Issue by HBIDamian** [pterodactyl/panel#4344]
### Current Behavior

When adding square brackets into a property in Configuration Files whilst editing an egg, it causes the following error:

Could not establish a connection to the machine running this server. Please try again.

### Expected Behavior

Expected resource_packs/resource_packs.yml to show the following:
```yaml
force_resources: true
resource_stack:
  - Redacted.mcpack
```
![image](https://user-images.githubusercontent.com/10010369/187282461-5d27c73b-ca18-4ac5-b23d-5b7cb7642b65.png)

### Steps to Reproduce

Here is the JSON for the egg Configuration Files. Specifically the resource_stack key. Just add an array to it as displayed below
```json
{
    "resource_packs/resource_packs.yml": {
        "parser": "yaml",
        "find": {
            "force_resources": "true",
            "resource_stack": [
                "Redacted.mcpack"
            ]
        }
    }
}
```

### Panel Version

1.10.1

### Wings Version

1.7.0

### Games and/or Eggs Affected

PocketMineMP

### Error Logs

```bash
https://ptero.co/edubivetyt
https://bin.ptdl.co/s5pbt/
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
You cannot do this, you need `resource_stack.0` I believe. This is working as intended, although there are numerous issues with the whole YAML parsing thing in the first place, but these type of complex assignments are difficult to know about and handle in the first place.

That tweak above to the key it looks for should be sufficient though.
