### ISSUE TITLE
Activity log: limit text inside edge

### ISSUE THREAD

**Issue by jourambo** [pterodactyl/panel#4347]
### Current Behavior

It would be nice to have a limit on the edge and continue on the line below because otherwise it creates a very long line as it is in my case. it is longer than what you see in the screenshot https://cdn.discordapp.com/attachments/284416495189098498/1014645665416085555/kyuky.PNG

### Expected Behavior

which creates a new line inside the borders

### Steps to Reproduce

long startup parameters. for example the arma3 egg.

### Panel Version

1.10.1

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jelcoo** [comment]
Resolved in https://github.com/pterodactyl/panel/commit/be29fe1db21085848479482b4aafa48a12d85347
