### ISSUE TITLE
add a timeout to show the "kill" button

### ISSUE THREAD

**Issue by lollilol** [pterodactyl/panel#4348]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

when you stop a server, it instantly replaces the stop button with a kill button. I think its smart to wait 5-10 seconds and then show a kill button, so you don't click your mouse button twice and accidentally kill the server.

### Describe the solution you'd like.

When pressing the stop button, it gets greyed out and pterodactyl tries to stop the server gracefully. Then after 5 seconds the greyed out stop button gets replaced with the kill button.

**Comment by Jelcoo** [comment]
It already grants you with a popup asking if you want to kill your server.

**Comment by lollilol** [comment]
yea lol i just saw that. Nvm then.
