### ISSUE TITLE
don't make last name required

### ISSUE THREAD

**Issue by lollilol** [pterodactyl/panel#4349]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

make the last name when creating or editing a user NOT required. I don't always want to assign a lastname. 

### Describe the solution you'd like.

make the last name when creating or editing a user NOT required.

**Comment by Jcodeerd** [comment]
Just use some gibberish, or an empty character thing

**Comment by lollilol** [comment]
thats a workaround, not a fix

**Comment by DaneEveritt** [comment]
Won't change.

**Comment by lollilol** [comment]
Is it too much work? Does it depend on much in the backend?
I don't know the last name of every person

**Comment by lollilol** [comment]
![image](https://user-images.githubusercontent.com/38194372/219649083-6f459448-5d29-4871-9500-ef41ae6f3f43.png)
