### ISSUE TITLE
Default map name validation

### ISSUE THREAD

**Issue by Classes123** [pterodactyl/panel#4354]
### Current Behavior

Map name validation does not correspond to possible variants of the name of the map. For example, a `$2000$.bsp` in the `mymaps` folder:
![image](https://user-images.githubusercontent.com/64929923/188160223-be2018da-a188-4086-bc6e-44ec7d857cb1.png)

### Expected Behavior

The field must support folders and escape special characters. Output string should be +map  `mymaps/\$2000$`

### Steps to Reproduce

Enter any map name in subfolder or special characters in the field.

### Panel Version

1.10.1

### Wings Version

1.7.0

### Games and/or Eggs Affected

CS:GO (Source Engine)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
in llinux a `$` is a special character. Can you not rename the map to something that's not that?

**Comment by Classes123** [comment]
> in llinux a `$` is a special character. Can you not rename the map to something that's not that?

If I even rename the map, the validation will trigger on `/`. This map is also popular in cs go, so some people have already downloaded it.

UPD: I also didn't understand your message in Discord. Ordinary users do not have access to edit the line. We're trying to create a really good panel, not an assessment of your users' knowledge, aren't we?

**Comment by Classes123** [comment]
^ misclick, sorry

**Comment by DaneEveritt** [comment]
This isn't a bug, can you open new feature requests for this — you're asking for two different things:

1. The egg you're using to be updated to support special characters in the map name rather than just `alphanum`.
2. Support for escaping the value that is passed to the startup line.
