### ISSUE TITLE
websocket problem with api

### ISSUE THREAD

**Issue by savalet** [pterodactyl/panel#4355]
### Current Behavior

I would like to connect in websocket to pterodactyl so I retrieve the socket link of the token without worries but when trying to connect I have this error in the chrome console:
![image](https://user-images.githubusercontent.com/73446695/188282254-b3853f1a-487c-4471-8b41-6d1195cd0d1e.png)

### Expected Behavior

Here is my code to connect to the websocket: 
`                const socket = new WebSocket(json.data.websocket.websocket_url);
`

### Steps to Reproduce

Use this code: 
`                const socket = new WebSocket(json.data.websocket.websocket_url);
`

### Panel Version

1.10.1

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by savalet** [comment]
And I have change the wings port to 2021

**Comment by DaneEveritt** [comment]
This is not an API support channel.

**Comment by savalet** [comment]
then where I shloud post my issue ?
