### ISSUE TITLE
Banned from discord   (I think) (apologies for issue clogging)

### ISSUE THREAD

**Issue by SelynCatto** [pterodactyl/panel#4356]
### Current Behavior

Username:  Lynix#2025

Discord is never clear as to  why an invite cannot be accepted, but I have a slight memory of being immature and saying things I should not have said that got me banned,

I'd just like to say I've changed and found no other way to directly talk to someone, so I'm sorry if this clogs up your issues system.

Discord says "invite couldn't be accepted"  or so on.

### Expected Behavior

see current behavior section

### Steps to Reproduce

see current behavior section

### Panel Version

see current behavior section

### Wings Version

see current behavior section

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TrixterTheTux** [comment]
You should be unbanned - you were spamming phishing links which usually happens due to getting hacked.

**Comment by SelynCatto** [comment]
> You should be unbanned - you were spamming phishing links which usually happens due to getting hacked.

oh that is right, my account got compromised in december, the 21st I think? Anyhow thanks for the unban. I have recovered my account since then.
