### ISSUE TITLE
Cannot edit files over 70 bytes

### ISSUE THREAD

**Issue by RockinChaos** [pterodactyl/panel#4368]
### Current Behavior

I am unable to edit files over 70 bytes in the File Manager of the Pterodactyl Panel. This includes .txt .yml .json extensions. If I try to preview or edit a file over 70 bytes I get the following error;
![unknown](https://user-images.githubusercontent.com/10971577/189457779-ce416b50-9adf-4741-8d84-76e30f1ae925.png)

I have tried re-installing wings & the panel and I still have the same issue.
This also occurs if you create a new file via the File Manager and add enough characters to go over 70 bytes.
For example, the eula.txt works fine as it only contains `eula=true` inside.

However a large plugin config.yml file the error occurs as seen above.
I tried getting help via the Discord server but nobody knows why this is happening.

### Expected Behavior

To be able to edit all my files.

### Steps to Reproduce

1.) Log into the Panel.
2.) Go to a server.
3.) Click the File Manager tab.
4.) Locate a .yml .json or .txt file over 70 bytes (or create your own).
5.) Try to edit / preview the file.
6.) Error will immediately occur after clicking the file.

### Panel Version

1.10

### Wings Version

1.7

### Games and/or Eggs Affected

Minecraft (Paper)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
https://ptero.co/panofaloqo
http://bin.ptdl.co/lng90
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
This is an issue with your network, something is terminating the connection:

```
Stacktrace:
write tcp 172.16.22.3:443->172.16.10.2:53042: write: broken pipe
github.com/pterodactyl/wings/router.getServerFileContents
	/home/runner/work/wings/wings/router/router_server_files.go:73
github.com/gin-gonic/gin.(*Context).Next
```

This is not a bug with Pterodactyl.

**Comment by RockinChaos** [comment]
> ```shell
> https://ptero.co/panofaloqo
> ```

That error is in relation to the sftp program I am using, it appears that there is no error generated in correlation to the web File Manager.


Also again, this error only happens with files over 70 bytes and I can upload large files no problem, so I am highly doubting its a network issue.
Upon restarting wings and replicating the issue a error is not generated;
https://ptero.co/ujeluvujip

The specific files over the 70 byte limit reach an error via the browser console;
![unknow2n](https://user-images.githubusercontent.com/10971577/189460319-62b76473-4a6c-4761-b7d9-2575645a23ce.png)

**Comment by RockinChaos** [comment]
@DaneEveritt Okay so update, I think this is actually a bug with the panel itself--correct me if I am wrong.

So it looks like my error of not being able to edit files via the File Manager is directly correlated to;
`production.ERROR: Undefined array key 0 {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /var/www/pterodactyl/app/Repositories/Wings/DaemonFileRepository.php:38)`

If I try to edit a small file that I can normally edit, there is no error in the log files. However, once the error occurs this is the error that occurs for the specified files that I cannot edit.
I have no idea what this error means but after some tweaking with that file I can FINALLY edit ALL files.
It is something with line 38 in the DaemonFileRepository.php file.
I simply nano edited the file found line 38 which is `$length = (int) $response->getHeader('Content-Length')[0] ?? 0;` and I simply set it to `$length = (int) 0;` and everything works fine now.

Obviously, this isn't a perfect solution as I believe this will break each time I update the panel. From what I can tell this is a panel bug is it not? It seems it's either an issue with the response or the header, the response seems to return just fine but it cannot get the Content-Length from the header.

I have no other issues or bugs with the panel, sftp, or wings. Everything works flawlessly except for this single issue.

EDIT: I thought it may be something related to certain browsers but this seems to occur on all browsers. I tried Firefox, Brave, Chrome, Edge, and Chrome Nightlies with the same issue.

**Comment by DaneEveritt** [comment]
It looks like something in your network is stripping the Content-Length header, and that code doesn't expect that to even be something that is possible. I don't know what to tell you, but I don't really have the bandwidth to spend time looking into something that appears to only impact you. Sorry.
