### ISSUE TITLE
Wings does not respect docker MTU setting in config.yml when creating pterodactyl0 interface

### ISSUE THREAD

**Issue by argonaut-network** [pterodactyl/panel#4376]
### Current Behavior

Background:
Lots of things break on my server when an MTU of more than 1448 is set on any interface. This is something I have no control over, as it is in a data center being colocated.

Currently, every time I delete the pterodactyl_nw network along with the pterodactyl0 interface and force Wings to recreate it, it still uses an MTU of 1500 despite it being set in config.yml according to ifconfig.

### Expected Behavior

When running ifconfig, pterodactyl0 should show an MTU of 1448 per my explicit configuration.

### Steps to Reproduce

1. Create brand new Wings instance using docker-compose.
2. Set MTU using `network_mtu` option in /etc/pterodactyl/config.yml
3. 

### Panel Version

1.10.1

### Wings Version

1.7.0

### Games and/or Eggs Affected

All

### Docker Image

All

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
Covered in #2662 You can build a docker network and set wings to use that network.

**Comment by argonaut-network** [comment]
I'll accept that.
