### ISSUE TITLE
The panel does not exclude subusers that have been removed from a server

### ISSUE THREAD

**Issue by Ferks-FK** [pterodactyl/panel#4379]
### Current Behavior

When you create a sub-user for a server, the panel automatically creates him as a regular user, but when you remove this user from the server previously associated with him, the user still remains registered in the dashboard, which makes it possible for him to access the dashboard at some point.

### Expected Behavior

I think the subuser can simply be deleted, if it is not associated with any server.

### Steps to Reproduce

- Create a sub-user.
- Remove it from the server previously associated with it.
- See the user still registered in the system.

### Panel Version

1.10.1

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Not changing this — the user is associated with internal activity log events, and can be added to other servers down the line. There is no harm in maintaining an account.

Deleting the account every time introduces more emails, more password changes, and a more painful end user experience.
