### ISSUE TITLE
If Statements almost

### ISSUE THREAD

**Issue by expxx** [pterodactyl/panel#4380]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A new tab or system for `If Statements` almost, so for example:

`every 5 seconds if ram_usage > 80% restart server`

This could go with schedules as well as be an entirely new system. 

### Describe the solution you'd like.

As I explained in the previous question, something like an if statement. So every 5 seconds if the ram is more than 80% of max then restart the server or something, there could be things like:

#### Resources
if ram usage (>|<) (__%|__GB|__MB) then %action on server%
if disk usage (>|<) (__%|__GB|__MB) then %action on server%
if uptime (>|<) (__S|__M|__D|__MO) then %action on server%

##### Ports
create port
delete port

##### Files
delete file "file.txt"
create file [with (contents|text|data) ""]
delete directory "directory"
create directory "directory"

##### Databases
create new database named "name" [with allowed ips "", "", "",..]
delete database with name "name"
rotate password on database with name "name"

##### Users
delete subuser with email ""
create subuser with email "" [and permissions "", "", ""...]

##### Backups
create new backup with name "" [and ignored directories "", "", ""...] [and (is|is not) locked
delete backup with name ""
lock backup with name ""
unlock backup with name ""

##### Startup
set variable with name "" to value (""|true|false)

#### Server Power Action
stop server
start server
restart server
kill server

### Additional context to this request.

I do completely understand this is a **ginormous** task and will not be done for a WHILE, but it is still an idea worth thinking about.

### Formatting
The formatting I used is as follows
```
[] = optional
() = options
%% = expressions

**Comment by matthewpi** [comment]
While this would be an interesting feature, I can say without a doubt that something like this will never be implemented.  Because of that, there is no need to keep this issue open.
