### ISSUE TITLE
Rotated backups not deleted

### ISSUE THREAD

**Issue by ajgeiss0702** [pterodactyl/panel#4385]
### Current Behavior

When backups should be rotated (with scheduled backups and a server backup limit), they are removed from the panel but not deleted from S3.

(note that deleting them manually works as it should)

### Expected Behavior

When backups disappear from the panel, they should be removed from S3 too.

### Steps to Reproduce

1. Set a backup limit for a server
2. Schedule a backup
3. Wait for the backups to reach the server limit
4. Notice they disappear from the panel backup list, but not from S3

### Panel Version

1.10.1

### Wings Version

1.7.0

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
No error log (No such file or directory)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ajgeiss0702** [comment]
The closest I've found to my issue is #3221 however theirs didn't work even when manually deleting, however, mine are. They simply are not deleted automatically (and accumulate storage and costs)

**Comment by matthewpi** [comment]
Looking through the code, rotated backups are indeed deleted.

<https://github.com/pterodactyl/panel/blob/develop/app/Services/Backups/InitiateBackupService.php#L149>
<https://github.com/pterodactyl/panel/blob/develop/app/Services/Backups/DeleteBackupService.php#L70-L74>

If they aren't getting deleted then I'd make sure to check your logs, as the same logic is used when manually deleting backups.

**Comment by ajgeiss0702** [comment]
There was no error log, and the backup was not being deleted. They are deleted when manual deletion, so *something* must be different somewhere

**Comment by danny6167** [comment]
Some S3 providers will retain the file and just "flag" it as deleted. It's then up to retention policies to actually delete the file.
When you say deleting them manually works, do you mean in your S3 providers website, or in the panel?

**Comment by ajgeiss0702** [comment]
> Some S3 providers will retain the file and just "flag" it as deleted. It's then up to retention policies to actually delete the file.
> When you say deleting them manually works, do you mean in your S3 providers website, or in the panel?

Both. Manually deleting appears to remove it from both the panel and the aws console. Rotating only removes it from the panel

**Comment by matthewpi** [comment]
Have you tried restarting the queue worker?  It might be using old values for the environment variables if you modified them without restarting the queue worker after making your changes.

```bash
sudo systemctl restart pteroq.service
```

**Comment by ajgeiss0702** [comment]
> ```shell
> sudo systemctl restart pteroq.service
> ```

I *think* I did, but I’m not 100% sure. I’ll try that and see how it goes

initial testing shows that it appears to have been fixed. I’ll double check tonight, then close this issue as long as it’s fixed.

thank you @matthewpi 
Surprising that neither I, or anyone in the discord thought of that 😄

**Comment by ajgeiss0702** [comment]
Yep, that definitely fixed it. Thank you 😊
