### ISSUE TITLE
Schedule Delays

### ISSUE THREAD

**Issue by Marco15453** [pterodactyl/panel#4386]
### Current Behavior

A 1 Second Delay doesn't seems to be one second it seems to act like 2-3 seconds

### Expected Behavior

Wait 1 Second and not 2-5 seconds

### Steps to Reproduce

Look at those images and short video to reproduce:
- https://s.4eo.xyz/Marco/opera_ylKqIbMseF.png
- https://s.4eo.xyz/Marco/javaw_rYstMuYCau.gif

### Panel Version

1.10.1

### Wings Version

1.7.0

### Games and/or Eggs Affected

Minecraft (Forge)

### Docker Image

quay.io/pterodactyl/core:java

### Error Logs

```bash
https://ptero.co/xexaxideka

No recent Panel Logs
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
There is overhead when running the processes, and they are added to a queue with other internal systems. It is never going to be exactly a second delay, I'm not considering this a bug.
