### ISSUE TITLE
S3 backup can not be deleted from the panel if the object associated with it was removed beforehand

### ISSUE THREAD

**Issue by realkarmakun** [pterodactyl/panel#4389]
### Current Behavior

We have a S3 backup. When trying to delete it, and if it was removed from S3 storage by other means, panel will show 20000ms timeout and thrown an error in logs.

### Expected Behavior

For S3 backup to be deleted from the panel normally

### Steps to Reproduce

Make an S3 backup.
Remove backup object by hand
Try to delete backup from the panel and observe an error.

### Panel Version

1.10.1

### Wings Version

1.7.0

### Error Logs

```bash
https://pteropaste.com/vdmumo/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by realkarmakun** [comment]
Actually this issue appear in the wild with Failed backups, but can be recreated with not failed backups.

**Comment by realkarmakun** [comment]
This is still relevant. How about make the same logic for backups as for deleting servers? (e.g. safe delete and force delete, additional button for force delete would be fine)

**Comment by matthewpi** [comment]
I could not reproduce this.  The error you posted seems to point to either a connection issue or bug with OVH's object storage.

If you can reproduce this against Amazon S3 or Minio, then I'll look into this further, but as far as I can tell this is not a bug.
