### ISSUE TITLE
"Remember me" feature doesn't work with 2FA enabled

### ISSUE THREAD

**Issue by MrDienns** [Pterodactyl/Panel#439]
Hi

I'm using Pterodactyl panel 6.0.0 release. The "remember me" feature doesn't seem to work properly when having 2FA enabled. It remembers me for like an hour or so, maybe more, maybe less, I'm not entirely sure. It definitely doesn't remember me permanently as I have to log back in every day.

```
SESSION_DRIVER=database # DO NOT EDIT! set using pterodactyl:env
```

Thanks

**Comment by DaneEveritt** [comment]
self note:
```
SESSION_DRIVER=database # DO NOT EDIT! set using pterodactyl:env
```
