### ISSUE TITLE
I followed the guide for installation of Cent Os but it doesnt work

### ISSUE THREAD

**Issue by tga098** [pterodactyl/panel#4400]
### Current Behavior

I followed the guide : https://pterodactyl.io/community/installation-guides/wings/centos8.html and as said in the last follow the wings installation from here https://pterodactyl.io/wings/1.0/installing.html#enabling-swap and I did follow that and when running `sudo wings --debug` 

I get the following error : `/var/tmp/sclnh3Ata: line 2: 1835732 Segmentation fault      'wings' '--debug'`

### Expected Behavior

I expected it to run wings normally as it does always

### Steps to Reproduce

I followed the guide : https://pterodactyl.io/community/installation-guides/wings/centos8.html and as said in the last follow the wings installation from here https://pterodactyl.io/wings/1.0/installing.html#enabling-swap and I did follow that and when running `sudo wings --debug` 

I have selinux off

![image](https://user-images.githubusercontent.com/88242006/193734112-3b31b988-868a-4fbc-acab-4ac40157531d.png)

Output running `sudo ldd /usr/local/bin/wings`

![image](https://user-images.githubusercontent.com/88242006/193734194-7e4cb8d9-97a6-4506-99a4-521ed1ba4d73.png)

Output running `sudo head /usr/local/bin/wings`

![image](https://user-images.githubusercontent.com/88242006/193734307-3d9125d0-aea9-40a0-b072-078095062e06.png)

Output running `sudo file /usr/local/bin/wings `

![image](https://user-images.githubusercontent.com/88242006/193734383-9453b9fc-e1a5-45e1-abcd-75fad8c62213.png)

Output running `uname -a`

![image](https://user-images.githubusercontent.com/88242006/193734420-d1266ac9-1127-4236-a634-a072b749de7d.png)

Hope all this information I provided helps he/she viewing this to solve me issue

### Panel Version

1.10 (latest)

### Wings Version

1.7 (latest)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
So this is oracle linux and not centos. Those are very different operating systems.

**Comment by tga098** [comment]
> So this is oracle linux and not centos. Those are very different operating systems.

But according to the people i talked in the support server, they said oracle linux, red hat, cent os and fedora are almost the same and told me to follow the cent os, almalinux guide

**Comment by parkervcp** [comment]
So far as I can tell is that you are the only person to have this issue.

**Comment by matthewpi** [comment]
What does the output of `sestatus` show?  I had this exact problem with Rocky 9 specifically with SELinux enabled, there seems to be an issue with the policies in the newer version.

Another thing to consider is in order to fully disable SELinux, you need to edit the kargs for you system https://access.redhat.com/solutions/3176 this affects both Fedora and RHEL 9.  You could easily try this by running `setenforce 0` (which will set SELinux to permissive mode until you reboot).

**Comment by ccallahan** [comment]
Could you install the `sos` package, run `sos report --clean`, and upload the file it gives you? I'd like to poke around and check a few SELinux-related things.

**Comment by tga098** [comment]
> r

I already have selinux disbaled

**Comment by tga098** [comment]
> Could you install the `sos` package, run `sos report --clean`, and upload the file it gives you? I'd like to poke around and check a few SELinux-related things.

lemme try

**Comment by tga098** [comment]
> So far as I can tell is that you are the only person to have this issue.

No thats impossible

**Comment by tga098** [comment]
> `sestatus` s

![image](https://user-images.githubusercontent.com/88242006/194003852-6cfe4881-6739-4bc2-acc1-c2f95d5cb0b8.png)

**Comment by tga098** [comment]
> sos report --clean

doesnt work idk why

**Comment by tga098** [comment]
Oh wait I fixed it by using https://github.com/Kas-tle/wings-oci. I person from the pterodactyl support server dmed me saying use this for oracle linux and it does work now. Thanks guys for all of your help and spending your time for this report
