### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by Andriusyes** [pterodactyl/panel#4407]
### Current Behavior

SyntaxError: Unexpected token in JSON at position 0 in 
node_modules/petitio/dist/index.js:30:574
node_modules/petitio/dist/index.js:30:2499

### Expected Behavior

when type a music command it say SyntaxError: Unexpected token in JSON at position 0 in node_modules/petitio/dist/index.js:30:574
node_modules/petitio/dist/index.js:30:2499
this error

### Steps to Reproduce

i don't know

### Panel Version

1.4.0

### Wings Version

1.4.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
This is not a bug in the panel software and rather something wrong with your specific application
