### ISSUE TITLE
Compressed Wings binaries fail to run on RHEL 9 with SELinux enabled

### ISSUE THREAD

**Issue by matthewpi** [pterodactyl/panel#4410]
### Current Behavior

When running Wings on RHEL 9 (or a derivative) with SELinux enabled, Wings will fail to run, only logging a `Segmentation fault (core dumped)` error and an AVC violation.  However, when running a `_debug` artifact from our development CI pipeline, Wings works properly.  The only difference between the two artifacts is debug stripping and `upx` compressing the non-debug binaries.

AVC Log:
```
type=AVC msg=audit(1665026407.711:121): avc:  denied  { execmod } for  pid=1294 comm="wings" path="/usr/local/bin/wings" dev="dm-3" ino=92379351 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:object_r:bin_t:s0 tclass=file permissive=0
```

### Expected Behavior

It should work normally

### Steps to Reproduce

Run Wings on any SELinux enabled RHEL 9 host.

### Panel Version

N/A

### Wings Version

\>= 1

### Is there an existing issue for this?

Red Hat Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2132528

**Comment by ccallahan** [comment]
The UPX team is also [aware of this](https://github.com/upx/upx/issues/605). Since I suspect it will take a while for the SELinux and UPX maintainers to find a workaround, I'm going to write up some policy that way EL9 and FC36/37 users aren't dead in the water.

**Comment by lstefan1520** [comment]
> The UPX team is also [aware of this](https://github.com/upx/upx/issues/605). Since I suspect it will take a while for the SELinux and UPX maintainers to find a workaround, I'm going to write up some policy that way EL9 and FC36/37 users aren't dead in the water.

It appears the original issue was closed/resolved.

I just tested on the latest version of wings on RHEL 9 again. I am still seeing the core dumped error.

Has anyone had a second look at this again?

**Comment by ccallahan** [comment]
@matthewpi and I are working with Red Hat on this, we have opened [BZ#2132528](https://bugzilla.redhat.com/show_bug.cgi?id=2132528) for it. I think that'll be our best approach for getting a fix.

**Comment by matthewpi** [comment]
> It appears the original issue was closed/resolved.
> 
> I just tested on the latest version of wings on RHEL 9 again. I am still seeing the core dumped error.
> 
> Has anyone had a second look at this again?

Did you try to run the same version of Wings as before?  I believe they resolved the issue (or at least got it working) with the release of UPX 4.0.0.  I just downloaded UPX 4.0.0 and compressed a development build of wings and it runs both on Fedora 37 (after running `semanage boolean -m --off selinuxuser_execmod`) and RHEL 9 (where the older versions of UPX were failing).  I'm still not sure why this was failing in the first place, but the new version of UPX seems to work.

Do note that even if UPX resolved the issue, older builds of Wings still won't work, we will need to make sure binaries are compressed with the newer version in order for them to work.  For now, I removed the binary compression from our CI as it just seems to cause more headaches then it is worth.

---

I still think there might be an issue with SELinux or it's policies somewhere though as from what I can tell, the execmod violation should have never occurred.  But I'm glad to see that UPX 4.0.0 works now.

**Comment by matthewpi** [comment]
This was fixed by removing the binary compression in our release pipeline for Wings.  UPX 4.0.0 and above should also work, but I don't feel the binary compression is important and has just seemed to cause problems like this.

**Comment by lordofpipes** [comment]
For anyone searching this error and looking for a quick and dirty workaround, for RHEL9, AlmaLinux 9, RockyLinux 9, Oracle Linux 9, Amazon Linux, CentOS, Fedora 37, EuroLinux, etc. before the fix is fully released

Just run
```bash
sudo semanage boolean -m --on selinuxuser_execmod
```
to disable the SELinux restriction that causes this segmentation fault.

---

**Unrelated:** Another SELinux problem on RHEL9 based distros that you almost certainly will run into is that SELinux will prevent `nginx` from being able to write files needed for Pterodactyl panel to work. 

Possible symptoms of this:
```
#5 /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/View/...PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/pterodactyl/storage/framework/views/d2a18b0a6388f8225ad84d11536bfb18147a47a9.php): Failed to open stream: Permission denied in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187
[18-Nov-2022 00:59:03 UTC] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/pterodactyl/storage/framework/views/d2a18b0a6388f8225ad84d11536bfb18147a47a9.php): Failed to open stream: Permission denied in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187
```

This can be solved by configuring SELinux rules:

```bash
sudo setsebool -P httpd_can_network_connect 1
sudo setsebool -P httpd_execmem 1
sudo setsebool -P httpd_unified 1
```

on the panel server.
