### ISSUE TITLE
Bug with kernel and java

### ISSUE THREAD

**Issue by Lenoob50** [pterodactyl/panel#4425]
### Current Behavior

Hello i have an error when i'm trying to start some server on pterodactyl panel 
When i'm start server say
 Error Event [d2980bfc-bb1c-406f-908f-f371571409a8]: environment/docker: failed to start container: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to init seccomp: error loading seccomp filter into kernel: error loading seccomp filter: errno 524: unknown

### Expected Behavior

Error when start server

### Steps to Reproduce

I have try to do apt-update 
apt-upgrade 

### Panel Version

1.10.3

### Wings Version

1.7.2

### Games and/or Eggs Affected

Minecraft(Paper)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TrixterTheTux** [comment]
Please include logs as the bug report template requests - they contain various information about your environment that could possibly explain why you're getting that error.

**Comment by Lenoob50** [comment]
![image](https://user-images.githubusercontent.com/43789150/195113185-cda6a312-9c6e-49fc-9471-d08f4030c69a.png)
I have this but i don't know if it's this you need (sorry for my bad english)

**Comment by TrixterTheTux** [comment]
You'd need to run `sudo wings diagnostics` on the node having this issue.

**Comment by Lenoob50** [comment]
I have two node with this problem 
For the first node 
https://ptero.co/zuqyniheja
For the second node
https://ptero.co/cykanuhygu

**Comment by rshtishi-dexi** [comment]
I am facing the same issue `unable to start container process: unable to init seccomp: error loading seccomp filter into kernel: error loading seccomp filter: errno 524`. Were you able to solve this issue?

**Comment by rshtishi-dexi** [comment]
I implemented [this fix](https://askubuntu.com/questions/1438706/starting-container-process-caused-error-loading-seccomp-filter-into-kernel-loa) and solved the issue for me.

**Comment by matthewpi** [comment]
This is usually caused by an issue with the OS itself and a package.  If you are having issues you can disable seccomp, but if you are running any questionable software or hosting servers for other people, I'd highly recommend against it.  If this issue turns out to be Pterodactyl specific and is caused by some of the settings we use, I'll look into fixing it, but for now this issue will be closed.
