### ISSUE TITLE
Missing Language

### ISSUE THREAD

**Issue by cynthiagruben** [pterodactyl/panel#4435]
### Current Behavior

![image](https://user-images.githubusercontent.com/58784842/195952072-28a41b56-fa68-4c37-8740-79da00829e81.png)

 When you try to create a user over the API we get the following error `Could not save Pterodactyl\Models\User[]: failed to validate data: {"language":["The selected language is invalid."]}` we fixed it with the language parameter in the json.
In the official API guideline is the language parameter for the create user part missing

### Expected Behavior

Change the API guideline create user part to this
{
  "email": "example10@example.com",
  "username": "exampleuser",
  "first_name": "Example",
  "last_name": "User",
  "language": "en"
}

### Steps to Reproduce

Create a user over the API with the API Guideline

### Panel Version

1.10.x

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
The API documentation is **not** official as it is not maintained by the Pterodactyl team, and it is outdated by several versions.

This is also not a bug, you've most likely changed the `APP_LOCALE` environment variable to something other than "en" hence the error, since the panel does not have a translation system.
