### ISSUE TITLE
Block upload a file, if the file is too large

### ISSUE THREAD

**Issue by Bubbelwubbel** [pterodactyl/panel#4438]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Currently, the file is uploaded, and only at the end of it comes the message that the file is too large. I just wish that this message already comes at the beginning

### Describe the solution you'd like.

I have none, you could add a link in the message that connects directly to FTP if necessary

**Comment by Bubbelwubbel** [comment]
![image](https://user-images.githubusercontent.com/65186341/195991563-dbbc3ba0-6af0-4213-b21a-12d7d329bcc5.png)

**Comment by LeChatP** [comment]
yo, its only your issue, i can upload like 20GB via drag'n'drop without problems

**Comment by LeChatP** [comment]
check your webhost configuration
