### ISSUE TITLE
Panel doesn't like the REDIS_HOST value

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#444]
I was having difficulty specifying a REDIS_HOST in my .env file. I needed to manually go into the config/database.php file and specify the following values:

`    'redis' => [
        'client' => 'predis',
        'default' => [
            'host' => 'redis',
            'port' => 6379,
            'database' => 0,
        ],
    ],`

Leaving anything else in there would cause it to error out.

**Comment by topjor** [comment]
I did not have any issues setting this myself (using latest stable release) 
Did you re-cache the .env file after changing?

**Comment by schrej** [comment]
Well it looks like the config actually doesn't care for the `REDIS_HOST` variable. Unless laravel does that if you set the connection to `default` but i don't really think so.
(https://github.com/Pterodactyl/Panel/blob/develop/config/cache.php#L69)

@topjor what did you set your `REDIS_HOST` to? Localhost probably wouldn't change anything

**Comment by topjor** [comment]
If you look at config/database.php, the default connection is set there at the bottom, it uses localhost or the REDIS_HOST defined in the env file, 
But remember that the env file is cached, so you have to re-cache it after editing (or run the env setup command again)
I have set it successfully, and it works (I have a docker container for redis and it is linked to the docker for the panel, so it is set to redis, that resolves to the ip of the redis container)

**Comment by DaneEveritt** [comment]
I too am unable to replicate this and have redis running on a different server.

**Comment by schrej** [comment]
Ah, so we are talking about using Redis as the database, not for caching. Well in that case, that should definitely work.

**Comment by topjor** [comment]
If i am correct, this applies for both caching (how i use it) and as a database. 
the caching system uses the same connection settings as database

**Comment by schrej** [comment]
You probably are correct ;)

**Comment by DaneEveritt** [comment]
Closing unless someone else can confirm an issue.
