### ISSUE TITLE
Requesting non-existent files returns 500 error

### ISSUE THREAD

**Issue by devnote-dev** [pterodactyl/panel#4444]
### Current Behavior

Requesting the file contents of a file that does not exist returns a HTTP 500 error response (ref: [Discord: #api-and-modding](https://discord.com/channels/122900397965705216/936744899787784282/1031283440861065256)).
Response:
```json
{
  "errors": [
    {
      "code": "DaemonConnectionException",
      "status": "500",
      "detail": "There was an error while communicating with the machine running this server. This error has been logged, please try again. (code: 500) (request_id: b19ecc33-0b99-48fb-a12d-c78f868884e9)"
    }
  ]
}
```

### Expected Behavior

The API (Wings) should return the appropriate 404 error when a file is not found.

### Steps to Reproduce

Make a GET request to `/api/client/servers/<id>/files/contents?file=unknown` or whatever file name you want that doesn't exist in the server.

### Panel Version

1.10.1

### Wings Version

1.7.0

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
Currently unavailable.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Doc94** [comment]
i think currently not exits a exception for file not found in wings/panel then maybe can be added a new exception like [FileSizeTooLargeException](https://github.com/pterodactyl/panel/blob/f973285e04556e08607ba5cd56bb751c29082cf9/app/Exceptions/Http/Server/FileSizeTooLargeException.php)

**Comment by devnote-dev** [comment]
@Doc94 Most of the remote API errors are covered under `DaemonConnectionException` (or others depending on the status code).
