### ISSUE TITLE
Database passwords containing '@' break the JDBC connection string

### ISSUE THREAD

**Issue by MackenzieMolloy** [pterodactyl/panel#4448]
### Current Behavior

Services that use the JDBC connection string format to connect to a database are unable to connect as the '@' character is parsed as part of the JDBC connect string format.

### Expected Behavior

Services that use the JDBC connection string format to connect to a database should be able to connect.

### Steps to Reproduce

Get a database with a password that contains '@' in the password and attempt to use the JDBC connection string to connect to the database.

### Panel Version

1.10.4

### Wings Version

1.7.2

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
N/A
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
We need to run the password though urlencode()

**Comment by parkervcp** [comment]
The panel generates passwords for the db users. In theory we might need to build a valid char list. I have a pretty good one that is generally safe. I'll update this post in a bit with it.

**Comment by DaneEveritt** [comment]
This should not change how passwords are generated — it just needs to escape the characters properly.

**Comment by parkervcp** [comment]
This is specifically an issue with JDBC which is java specific as well.
