### ISSUE TITLE
The 25 character limit is too low for forge version

### ISSUE THREAD

**Issue by aykin** [pterodactyl/panel#4449]
### Current Behavior

Currently the user is not allowed to enter more than 25 characters by default which prevents some versions from being entered

### Expected Behavior

The user should be able to enter every existing version of forge minecraft

### Steps to Reproduce

Create new server, enter "1.7.10-10.13.4.1614-1.7.10" for forge version

### Panel Version

1.10.1

### Wings Version

1.7.2

### Games and/or Eggs Affected

Minecraft (Forge)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
Wouldn't the version just be `1.7.10-10.13.4.1614`?

Not sure why you include the mc version on both ends

**Comment by parkervcp** [comment]
the forge egg accounts for 1.7 and 1.10 and adds them where they need to be.

**Comment by notAreYouScared** [comment]
> the forge egg accounts for 1.7 and 1.10 and adds them where they need to be.

The download links changed... Without the version at the end it throws a 404. 

https://maven.minecraftforge.net/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar

**Comment by parkervcp** [comment]
I swear they do it on purpose.

**Comment by notAreYouScared** [comment]
Seems to change based on the version...

.../forge/1.15.2-31.2.57/forge-1.15.2-31.2.57-installer.jar
.../forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar

1.9/1.10 is even more jank...with both 1.9/1.9.0 & 1.10/1.10.0 in the URL
.../forge/1.9-12.16.1.1938-1.9.0/forge-1.9-12.16.1.1938-1.9.0-installer.jar
.../forge/1.10-12.18.0.2000-1.10.0/forge-1.10-12.18.0.2000-1.10.0-installer.jar

Then 1.8.8 is only in the front 
.../forge/1.8.8-11.15.0.1655/forge-1.8.8-11.15.0.1655-installer.jar

**Comment by matthewpi** [comment]
Why are there even length limits on these fields in the first place?  I'm pretty sure they all end up getting stored in a `VARCHAR(255)` or `TEXT` field in the DB anyways.  These fields should have validation that allows people to input any reasonable value.

**Comment by trenutoo** [comment]
The input rule string limit was there as that was more than a reasonable limit for any versions they used to have. It could be removed altogether. 

However, sounds like the whole URL format changed again and most likely needs fixing too? Don't have a setup to test right now while on the road.
