### ISSUE TITLE
An error occurs when maintenance mode is turned off

### ISSUE THREAD

**Issue by vlssu** [pterodactyl/panel#4456]
### Current Behavior

An error is reported when maintenance mode is turned on and then turned off, and an error is also reported when clearing cache during upgrade

### Expected Behavior

After enabling maintenance mode, then executing shutdown maintenance mode should work without error

### Steps to Reproduce

Executing `php artisan down` and then executing `php artisan up` gives an error

### Panel Version

develop

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by lancepioch** [comment]
I got a hotfix for you #4457

Note that your up command does work, it just inaccurately reports an error
