### ISSUE TITLE
[srcds] Workshop maps break ptero's status

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#446]
Using srcds with[ workshop maps](https://developer.valvesoftware.com/wiki/CSGO_Workshop_For_Server_Operators) seems to break ptero's status.

- Once started, there is noway to shutdown the server, only the kill button does a **restart** on the srcds.
- Server is always displayed as starting even once started.
- Manualy stopping the server through Docker also doesn't works, the container instantly restart.
- Kill the container through docker does recreate a new one with the same bug.

Launch Options i used
```
-game csgo -console -usercon -port 27019 +ip 0.0.0.0 +net_public_adr xx.xx.xx.xx -strictportbind -steamcmd_script /home/container/steamcmd/runscript_update -steam_dir /home/container/steamcmd +game_type 0 +game_mode 1 +host_workshop_collection 810773843 +workshop_start_map 858617188 -authkey xxxxxxxxxxxxxxxxxxxxxxxx+sv_pure 0 +fps_max 0 -maxplayers_override 11 -tickrate 128 +sv_setsteamaccount xxxxxxxxxxxxxxxxxxxxxxxxxx -autoupdate -norestart
```

I already checked `/srv/daemon/src/services/srcds/main.json` and the startup sequence is ok.

There is a 'known bug' about the -norestart option that has been discussed in #270 so maybe it's related, not sure.

I'll try to dig more about this but wasn't able to find any useful info atm.

**Comment by danrokzz** [comment]
we have the same bug/error using following startup-parameters for csgo with duels:

`./srcds_run -game csgo +hostname SERVERNAME +host_workshop_map 125438255 +workshop_start_map 125438255 +host_workshop_collection 76561198082857351 -maxplayers_override 12 -port 27015 -ip 0.0.0.0 -tickrate 128 -usercon -retry +game_type 0 +game_mode 1 +mapgroup mg_bomb +bot_quota 0 +sv_hibernate_when_empty 0 -strictportbind +sv_setsteamaccount XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -authkey YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY -steam_dir /home/container/steamcmd/ -steamcmd_script script_autoupdate.txt -autoupdate -norestart`

if we use the parameters for csgo with retake, its working:

`./srcds_run -game csgo +hostname SERVERNAME +map de_dust2 -maxplayers_override 7 -port 27017 -ip 0.0.0.0 -tickrate 128 -usercon -retry +game_type 0 +game_mode 1 +mapgroup mg_bomb +bot_quota 0 +sv_hibernate_when_empty 0 -strictportbind +sv_setsteamaccount XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -autoupdate -steam_dir /home/container/steamcmd/ -steamcmd_script script_autoupdate.txt -autoupdate -norestart`

**Comment by lancepioch** [comment]
@danrokzz Does this still happen with the latest stable or beta versions?

**Comment by danrokzz** [comment]
@lancepioch Currently i have no panel runnig. But I think it was already fixed. 

At the end of march we will run a large part of our lanparty servers with Pterodactyl-Panel where I can check this and would report if there is still an issue.

**Comment by lancepioch** [comment]
Thanks @danrokzz comment or reopen the issue if it's still happening.
