### ISSUE TITLE
Error when creating new user

### ISSUE THREAD

**Issue by vlssu** [pterodactyl/panel#4463]
### Current Behavior

I get a 500 error when creating a new user
![image](https://user-images.githubusercontent.com/43847794/197349110-bdc2ec69-582c-48ea-8c9c-57e9aaa377e0.png)

Creating a new user by a sub-user is performed normally

### Expected Behavior

Create new user normally

### Steps to Reproduce

Create a new user as usual

### Panel Version

develop

### Wings Version

1.7.2

### Error Logs

```bash
http://bin.ptdl.co/iz5h0
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by vlssu** [comment]
Oh, to add, the email can't be sent normally, and I have checked the configuration is normal, but there is really no way to send the email automatically

Also under the develop branch.

**Comment by lancepioch** [comment]
@vlssu Thank you, nice catch! I've got a fix for both of these issues: #4464

**Comment by vlssu** [comment]
> @vlssu Thank you, nice catch! I've got a fix for both of these issues: #4464

I tried it, but it doesn't seem to be fixed?
