### ISSUE TITLE
[Pterodactyl Daemon]: Exit code: 128

### ISSUE THREAD

**Issue by AveOriginals** [pterodactyl/panel#4487]
### Current Behavior

The port is open both on my firewall and Iptables and this is indeed my ip adress since It would not connect if it wasn't

The platform is arm, my distro is ubuntu 22.04 installed using bash <(curl -L -o /usr/local/bin/wings "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")") and certificate manually installed. Wings was configured using automatic token and is online on the panel.

Machine is located at Oracle cloud and all Ports is opened there.

### Expected Behavior

The server to start without problems

### Steps to Reproduce

Install your machine using arm based processor

Install your certificate manually using an nginx server on 80 port and certbot on webroot configuration

Install wings using 
bash <(curl -L -o /usr/local/bin/wings "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")")

Use your panel provided token for configurate wings

Run "systemctl enable --now wings"

Try to start server

![obraz_2022-10-25_020527214](https://user-images.githubusercontent.com/75853477/197652669-30af4010-4120-4d6a-a178-41127974c7ee.png)
![obraz_2022-10-25_020625322](https://user-images.githubusercontent.com/75853477/197652762-af7063cb-037f-4849-919e-e4ca83d4e7bb.png)

### Panel Version

1.10.4

### Wings Version

1.7.2

### Games and/or Eggs Affected

Minecraft Mohist, Garry's Mod

### Docker Image

ghcr.io/pterodactyl/yolks:java_8 and ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
https://ptero.co/utarowikej
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
This looks like your server is not configured correctly as docker is reporting that there is no `pterodactyl_nw` network 

That network should be created when wings is started.

**Comment by AveOriginals** [comment]
> This looks like your server is not configured correctly as docker is reporting that there is no `pterodactyl_nw` network
> 
> That network should be created when wings is started.

Here's the problem: I did everything according to the tutorial, even made sure there were no errors, and did everything anew once again, but to no avail

**Comment by AveOriginals** [comment]
I found something interesting. In the documentation it says that Wings supports Ubuntu up to version 20.04, while I have version 22.04. Could this be a problem of misconfigured files?

**Comment by trenutoo** [comment]
Restart docker as you've deleted the pterodactyl network. This is not a bug in the software.
