### ISSUE TITLE
Curseforge generic egg exit code 1

### ISSUE THREAD

**Issue by rcpro69** [pterodactyl/panel#4492]
### Current Behavior

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

This happens because when the script runs it doesnt download the server.jar
And when server.jar is added manually it skips the script and generates the world with out downloading any mods

### Expected Behavior

Expected to use script to download everything once starting the server

### Steps to Reproduce

Use "curseforge generic" egg 
add modpack id (i used 585046)
api key (mine)
Create server, let it run and about 30sec after it crashes

### Panel Version

1.10.4

### Wings Version

1.7.2

### Games and/or Eggs Affected

Minecraft(nest) Curseforge generic(egg)

### Docker Image

ghcr:io/pterodactyl/yolks:java_16

### Error Logs

```bash
https://ptero.co/owasyzaqiz
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
This is an issue you should open on my eggs repo
