### ISSUE TITLE
Mail not sent normally

### ISSUE THREAD

**Issue by vlssu** [pterodactyl/panel#4506]
### Current Behavior

Create new users, reset passwords, etc., and they are not sending emails normally.
When clicking reset password, the panel says success, but it doesn't actually send.
But the test mail is sent normally,I'm sure all settings are normal

### Expected Behavior

The email should be sent correctly when clicking reset password

### Steps to Reproduce

Use the version built with develop 548affba84f3478186fb926dd122d9060dc3bcbd branch, configure the mail settings, I use the Microsoft365 outlook mailbox

### Panel Version

548affba84f3478186fb926dd122d9060dc3bcbd

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
So you are running a development version of the panel and expecting it to work.

You have offered no logs or configuration information either. All you have is that you use outlook 365.

**Comment by vlssu** [comment]
> So you are running a development version of the panel and expecting it to work.
> 
> You have offered no logs or configuration information either. All you have is that you use outlook 365.

Oh sorry, the re-edited content was not submitted due to network issues.

` [31/Oct/2022:22:07:59 +0800] ＂POST /auth/password HTTP/1.1＂ 200 96 ＂https://web/auth/password＂ ＂Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.24＂`

No logs are being generated under `storage/logs`

![image](https://user-images.githubusercontent.com/43847794/199028848-630f894b-c64b-4390-837a-c09666fb642f.png)

![image](https://user-images.githubusercontent.com/43847794/199028271-0c0271f2-67f2-45fc-89f7-81c261e294fb.png)

**Comment by matthewpi** [comment]
Actually, this works properly.  What changed was the name of the queue being used.  If you just use `queue:work` (optionally with the sleep and tries flags), email is sent properly.

I changed it so we will use the `standard` queue if the environment variable is set, otherwise we will fallback to `default` which is what new installs will use once these changes are released.

**Comment by vlssu** [comment]
I see. Thank you for your explanation.
