### ISSUE TITLE
Creating server through API fails in daemon

### ISSUE THREAD

**Issue by TrixterTheTux** [Pterodactyl/Panel#451]
Whenever I use the POST /api/admin/servers to create server, the installation fails. Manually creating the server works fine.

/srv/daemon/logs/wings.log:
```
[2017-05-23T14:21:03.712Z] ERROR: wings/25735 on CENSORED:
    (HTTP code 500) server error - {"message":"Get http://: http: no Host in request URL"}

    --
    Error: (HTTP code 500) server error - {"message":"Get http://: http: no Host in request URL"}

     at /srv/daemon/node_modules/docker-modem/lib/modem.js:239:17
     at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:266:9)
     at emitNone (events.js:91:20)
     at IncomingMessage.emit (events.js:185:7)
     at endReadableNT (_stream_readable.js:974:12)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Data sent to the API: `{"name":"QQx99ihq_42","owner":"EMAIL","auto_deploy":true,"service_id":"2","memory":"0","swap":"-1","cpu":"250","io":"500","disk":"50000","pack_id":"0","location_id":"1","option_id":"12","startup":"","description":"ANY DESC","user_id":"45"}`

I'm using the Custom Source Engine Game service with Garry's Mod (appid 4020), only additions are variables for startup parameters, all are optional so it shouldn't matter.

**Comment by SnowboiTheGr8** [comment]
getting this

**Comment by DaneEveritt** [comment]
I'm going to need more context to the error in order to actually track down the issue. Please provide the lines of log leading up to this.

**Comment by DaneEveritt** [comment]
The data you're passing to the API is in an invalid format, and I'm surprised it was even allowing the data to be passed.

**Comment by DaneEveritt** [comment]
```
POST /api/admin/servers HTTP/1.1
Authorization: Bearer JkAFq7M47kLN0xVD.J7KPsok+K7jf0qvtVP4/p+NfqbwT3amrbmdy45Frh1o=
Content-Type: application/json; charset=utf-8
Host: pterodactyl.app
Connection: close
User-Agent: Paw/3.1.1 (Macintosh; OS X/10.12.5) GCDHTTPRequest
Content-Length: 305

{"name":"QQx99ihq_42","owner":"dane@daneeveritt.com","auto_deploy":"true","service_id":"6","option_id":"18","memory":"0","swap":"-1","cpu":"100","io":"500","disk":"10000","pack_id":"0","location_id":"1","startup":"","description":"Something","user_id":"1","env_SRCDS_APPID":"4020","env_SRCDS_GAME":"gmod"}
```

Unable to replicate this issue using the following data.

**Comment by TrixterTheTux** [comment]
Daemon logs: `03:57:43.623Z  INFO wings: Pterodactyl Daemon is now listening for insecure conn                                                                                                            ections on 0.0.0.0:8080
03:57:54.344Z  WARN wings: Container was not found. Attempting to recreate it. (server=63bb2265-afbf-4fbd-a1fc-a720897b20ee)
03:57:54.345Z  INFO wings: Checking if we need to update image , if so it will happen now.
03:57:54.349Z ERROR wings:
    (HTTP code 500) server error - {"message":"Get http://: http: no Host in request URL"}

    --
    Error: (HTTP code 500) server error - {"message":"Get http://: http: no Host in request URL"}

        at /srv/daemon/node_modules/docker-modem/lib/modem.js:239:17
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:266:9)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickDomainCallback (internal/process/next_tick.js:128:9)
03:57:54.438Z  INFO wings: Notified remote panel of server install status.`
Do you need any other logs? Also tried deploying on another node, but the issue still seems to exist.

**Comment by DaneEveritt** [comment]
I am not able to replicate this on my end using the API, and the error you get doesn't even seem to be related to the panel.

The API and Panel both send the data to the daemon using the exact same function and verification, thus there is no reason one would work and one wouldn't.
