### ISSUE TITLE
Panel being slow all of a sudden.

### ISSUE THREAD

**Issue by aidanw-dev** [pterodactyl/panel#4515]
### Current Behavior

 panel was slow. I got bombed with 700gb of shit in a server. I deleted that sever nothing happened panel was still slow
<img width="1440" alt="Screen_Shot_2022-10-29_at_9 27 33_AM" src="https://user-images.githubusercontent.com/61997640/199344939-72a9bb95-be84-4e5f-81ca-bce4f034d4d5.png">

### Expected Behavior

Not be slow

### Steps to Reproduce

Not really any steps. 

### Panel Version

1.10.4

### Wings Version

1.7.2

### Error Logs

```bash
panel logs https://pteropaste.com/oubrm6

wings https://ptero.co/ydifokadig
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
Well cloudflare is telling you the host is down...

So first step would be to check to make sure your webserver is running...

**Comment by matthewpi** [comment]
Issues are not for support, they are for reporting bugs and requesting features.  The error you are seeing from Cloudflare is pretty clear, the request is timing out when going from Cloudflare's edge to the server running your panel.

First check that everything is running and that your server still has disk space available.  This software works for everybody else perfectly fine.
