### ISSUE TITLE
Distribution of nodes on machines

### ISSUE THREAD

**Issue by lootoos** [pterodactyl/panel#4518]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

the ability to run servers on dedic 1 and dedic 2 if there are not enough resources on dedic 1

### Describe the solution you'd like.

if this already exists, where is the guide about it?

**Comment by parkervcp** [comment]
I am fairly certain this is already done if you use the API to create servers. Manually created servers overrides that.

**Comment by matthewpi** [comment]
I'm not quite sure what you are asking.  You pick what node a server will run on when it is created.  Our Application API supports automatically assigning new servers to a node based off of resources as well.  If you are looking for servers to run on different nodes depending on resource usage after they are created, that is not currently possible and will not be implemented.  You can transfer a server between nodes, but that process is manual.
