### ISSUE TITLE
curl verbose not refreshing with big file during installation

### ISSUE THREAD

**Issue by leonardopessoa** [pterodactyl/panel#4525]
### Current Behavior

My installation script downloads a ~17GB .tar.gz file via curl but verbose won't refresh timely with the progress:
![image](https://user-images.githubusercontent.com/2722788/200127990-13832e30-99f1-4526-b2b6-ae279a00445e.png)

It refreshed once after ~13min:
![image](https://user-images.githubusercontent.com/2722788/200128006-bacd36b6-6480-4f7f-b42a-dea45b074d18.png)

### Expected Behavior

Show real time updates to curl verbose to be able to accurately track progress.

### Steps to Reproduce

1. Create a custom egg with a custom install script
2. Use curl to download a big file (my case, 17Gb) using the verbose mode
3. Watch immediately the server installation console

### Panel Version

1.10.4

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment]
The server console doesn't work well with interactive applications, every line is printed sequentially and text cannot be overwritten, causing the behavior you see here.  There is not an easy solution to this and I don't intend on fixing this problem specifically.
