### ISSUE TITLE
File Management - Unable to create new files

### ISSUE THREAD

**Issue by gibbonsjohnm** [Pterodactyl/Panel#453]
I'm currently unable to create new files in any server using the file management panel. They are all using the custom source engine service. No error is thrown and no log is recorded. The Create File button just doesn't seem to be executing anything. This does not apply to folder creation as that works just fine. 

Update ---

Found the following error when viewing the chrome console upon accessing file management:

Uncaught TypeError: Cannot read property 'commands' of undefined
    at editor.js:48
    at editor.js:131

**Comment by schrej** [comment]
Works fine for me. What version are you on?

**Comment by gibbonsjohnm** [comment]
0.6.0 as well.

**Comment by DaneEveritt** [comment]
You need to provide more of the error please, it is not helpful just providing the single error with no other context.

**Comment by gibbonsjohnm** [comment]
That's literally all I've got. Another user in the panel reported it. It's not giving me much to work with.

**Comment by DaneEveritt** [comment]
What console is that error displaying in?

Can you provide a picture of it?

**Comment by gibbonsjohnm** [comment]
Sure thing. I believe it's just called the Google Developer Console. It throws as soon as I enter the Create File screen.

![image](https://cloud.githubusercontent.com/assets/28908862/26381241/592bfafc-3ff1-11e7-9d46-0035f4c8e071.png)

**Comment by schrej** [comment]
I'm sorry, happens for me as well, I only went until the create screen as I thought it failed for you before.
This is what fails:
```js
Editor.commands.addCommands(Whitespace.commands);
```

`Whitespace` should be loaded by
```js
var Whitespace = ace.require('ace/ext/whitespace');
```
but it isn't as it seems.
