### ISSUE TITLE
Remember me login option not working

### ISSUE THREAD

**Issue by nechtmarrie** [Pterodactyl/Panel#454]
When checking the "remember me" option during the login process.
The user is not logged in next time the panel is opened and needs to authenticate again.
Running panel v0.6.0

**Comment by parkervcp** [comment]
@nechtmarrie If you are using 2FA then it's a known bug and has a fix in place for the next update.

See #439

**Comment by nechtmarrie** [comment]
I am indeed using 2FA.
Thnx for the info.
