### ISSUE TITLE
Servers with forced outgoing IP do not update outgoing IP when allocated IP address is changed

### ISSUE THREAD

**Issue by danny6167** [pterodactyl/panel#4547]
### Current Behavior

If you change the IP address of a server that uses and egg with **Force Outgoing IP** the outgoing IP address doesn't change.

Appears to be due to the fact the docker network that forces the IP address is created on first startup and is never recreated or updated when the servers allocated IP address changes.

Workaround is to stop the server, delete the docker network for that server, then restart the server.

### Expected Behavior

Docker network should be updated or recreated so that the new IP address is used.

### Steps to Reproduce

1. Create a server with an egg that uses **Force Outgoing IP**
2. Allow that server to start up.
3. Change the allocation to an allocation on a different IP address
4. Restart server and see that the traffic is still going out the original IP address (i.e Steam still detects server as the old IP address)

### Panel Version

1.10.3

### Wings Version

1.7.2

### Games and/or Eggs Affected

Any game with Force Outgoing IP

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment]
I thought I changed this to use the IP for the network name, guess not.
