### ISSUE TITLE
Cannot type in node seletion in Databases and Server Transfer

### ISSUE THREAD

**Issue by IvMisticos** [pterodactyl/panel#4549]
### Current Behavior

When trying to create a new database server or transfer a server, you cannot type to search for a node:
![image](https://user-images.githubusercontent.com/21005901/201284086-94aed1d2-bff2-4e00-aced-8eb4a87196b9.png)

### Expected Behavior

You should be able to type there like in all other cases, i.e when creating a new server.

### Steps to Reproduce

1. Enter the menu of database server creation or server transfer
2. Try to type in the node selection field

### Panel Version

1.10.4

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment]
Not going to bother fixing this.  The entire admin area is being rebuilt and all dynamic dropdowns will support searching where applicable.
