### ISSUE TITLE
Creating a new service configuration without variables

### ISSUE THREAD

**Issue by Sapd** [Pterodactyl/Panel#455]
Creating a new sub-service (like in source-engine) without adding any variables works.

However, when installing a gameserver with this service, it just says "Whoops, something went wrong".

This is the corresponding laravel log: https://gist.github.com/Sapd/a6c456d1a0dad1893f7a0b089176a0ba

Adding a dummy variable fixes the problem.

**Comment by DaneEveritt** [comment]
Is this on 0.6.0 or 0.6.1?

**Comment by Sapd** [comment]
It looks like it was just updated while I wrote this issue. I tested it now on 0.6.1 and the problem is gone, thank you.
