### ISSUE TITLE
Always restart container option

### ISSUE THREAD

**Issue by Prophet731** [pterodactyl/panel#4552]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I wasn't able to find anything with this in the existing issues. If I missed it, please close this and reference the other issue. 

Could we have a configuration option for a server where if the server is stopped it'll auto-restart it using docker "unless-stopped" restart option?

### Describe the solution you'd like.

Configurable option to enable auto restart unless stopped.

**Comment by parkervcp** [comment]
Wings already restarts servers that stop unless it restarts too many times in a short period then it stops trying.

**Comment by Prophet731** [comment]
It doesn't always. Essentially, what I'm asking is that we could be allowed to say "always keep this up no matter what".

**Comment by parkervcp** [comment]
The back on restarts is to keep a server from constantly restarting when they fail.

This could break a server worse than it was or could also cause a lot of cpu usage depending on the server.

**Comment by trenutoo** [comment]
> It doesn't always. Essentially, what I'm asking is that we could be allowed to say "always keep this up no matter what".

Setting crash detection timeout to 0 will do this. It's for the whole node though.

**Comment by Prophet731** [comment]
> > It doesn't always. Essentially, what I'm asking is that we could be allowed to say "always keep this up no matter what".
> 
> Setting crash detection timeout to 0 will do this. It's for the whole node though.

Is there not a way to make it `container` only? Maybe on the wings side when it starts up said container?

**Comment by trenutoo** [comment]
Not right now, there's #1565 #4583 #714

What you've listed in the feature request itself is already possible on a per-node basis with the use of crash detection. Feature requests for per-server options are above.
