### ISSUE TITLE
[Docker - Wings] Console acces.

### ISSUE THREAD

**Issue by ItJustFox** [pterodactyl/panel#4558]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Make in the **Docker version of Wings** an acces to the **console** for System Administrator 

### Describe the solution you'd like.

Create a variable that enable or not the console acces to the Wings.

### Additional context to this request.

We did use the Docker version of Wings for lot of thing, we wanted to add an addons to our Panel who requier to edit some files inside of the Wings has we are on docker, we wanted to acces to the console, but we are not able to because everything is locked.
![image](https://user-images.githubusercontent.com/42358087/202535410-d900d397-c54c-44d0-ad00-8f52de25ffc6.png)

**Comment by parkervcp** [comment]
This clearly states that the command `bash` doesn't exist. Depending on the image that is used it may be `ash`

**Comment by ItJustFox** [comment]
> This clearly states that the command `bash` doesn't exist. Depending on the image that is used it may be `ash`

![image](https://user-images.githubusercontent.com/42358087/202536404-050c4ca4-4f19-460a-b7a3-d76d0c687f40.png)
![image](https://user-images.githubusercontent.com/42358087/202536434-a94e586b-74e2-4f9a-8311-38e91c0a1d52.png)

We did aleadry tried everything, we only got Acces Denied or the error just above.

**Comment by parkervcp** [comment]
The docker version of wings has no terminal access in it. It's built to only run wings and no other executables are there to run.

If you want to replace files you will need to use a volume mount, or build your own image.

**Comment by ItJustFox** [comment]
> The docker version of wings has no terminal access in it. It's built to only run wings and no other executables are there to run.
> 
> If you want to replace files you will need to use a volume mount, or build your own image.

I never said to add other exec, it was for editing some files to add new button on panel because we wanted to add a Mod manager, and it require to edit two file in docker of wing, that we cant even mount or look where it is, because path between docker version / normal version same to not be the same.

**Comment by trenutoo** [comment]
It's a distroless image of the Wings binary. There's nothing for you to edit or do inside the container.

Should you wish to modify the Wings source code, you need to build it together with a new custom image.
