### ISSUE TITLE
Searching for Username instead of only email

### ISSUE THREAD

**Issue by LunaticWasTaken** [pterodactyl/panel#4560]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When creating servers and assigning the corresponding user, when typing it searches for email only.
This leads to having search-issues when searching for a username, which isn't present in the email-string.

### Describe the solution you'd like.

Search for either both, or only the Username instead of the Email-Address.

### Additional context to this request.

![Screenshot_2](https://user-images.githubusercontent.com/80840951/202880707-8935b449-394b-484f-83b3-af1a5a29914d.png)
![Screenshot_3](https://user-images.githubusercontent.com/80840951/202880711-71a23da5-b932-4a23-b0bd-c0b63fb76faa.png)

**Comment by devnote-dev** [comment]
https://github.com/pterodactyl/panel/issues/2366#issuecomment-695846582

**Comment by trenutoo** [comment]
Username filtering is implemented in V2.
