### ISSUE TITLE
Interacting with console on mobile makes it unreadable

### ISSUE THREAD

**Issue by JasonHorkles** [pterodactyl/panel#4561]
### Current Behavior

When scrolling in the console output or when text is printed, most if not all of the characters in the console window will disappear on mobile.
![image](https://user-images.githubusercontent.com/51760372/202917079-44392e16-7c06-4b98-913d-54bce15eb3a2.png)
I'm currently using Chrome on Android 13 on a Pixel 7 Pro

### Expected Behavior

None of the output should vanish

### Steps to Reproduce

1. Open the panel's mobile site
2. Try scrolling thru console or have the program print something

### Panel Version

1.10.4

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by hwalker928** [comment]
Unable to reproduce on Chrome, Android 13, Pixel 6

**Comment by MegaTKC** [comment]
![Screenshot_20221120-214444~2](https://user-images.githubusercontent.com/59368582/202974848-038413ea-0680-4787-9eed-93ebb603898f.png)

This is an issue for me too. Google pixel 6a, Android 13. Also the latest version of chrome for mobile.

**Comment by JasonHorkles** [comment]
I can't seem to reproduce the issue on the chrome beta app, so I'm thinking it may be something to do with a setting in the main app - will look into it further

**Comment by JasonHorkles** [comment]
Even after clearing all data and reinstalling chrome as best as I can, it still occurs on the normal chrome version
Best workaround for now I'd say is use the beta app instead

**Comment by not-pyroman** [comment]
I have been able to reproduce it as as well on Pixel 7, LineageOS 20 (Android 13), with the version of chrome being version 113.0.5672.132
