### ISSUE TITLE
Pterodactyl working under suburl does not work

### ISSUE THREAD

**Issue by JeremyStarTM** [pterodactyl/panel#4566]
### Current Behavior

Website not loading (Index page is loaded, but the bundle.js and other assets are going 404)

### Expected Behavior

Pterodactyl loading without any issues.

### Steps to Reproduce

1. Install Pterodactyl
2. Append "/panel" to "APP_URL" in the .env file
3. Access Pterodactyl under the suburl ("/panel")

### Panel Version

1.10.4

### Wings Version

not installed

### Error Logs

```bash
("Use netcat" was the output. I checked the log and nothing was there)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by yesBad** [comment]
I don't think it's ever meant for Ptero to work in a suburl.

**Comment by QuintenQVD0** [comment]
Ptero does not support running on a domain.com/ptero, it needs it own subdomain

**Comment by matthewpi** [comment]
You will need to run the Panel on a dedicated domain, not a subpath.  While there is the possibility of trying to modify this software to work with a subpath, there are too many moving parts to deal with for such a minor problem.
