### ISSUE TITLE
Add api key to user from application api

### ISSUE THREAD

**Issue by nottisa** [pterodactyl/panel#4571]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to see an application API call that allows a User API key to be added to a specified user. This would be useful for completely redone management systems, where the panel is provided, and the pterodactyl is used.

### Describe the solution you'd like.

I would like to see an application API call to make a client API key for a specified client.

**Comment by nottisa** [comment]
To be clear, I know I could just make a singular admin user account with access to every server, but that requires extra effort to see what people are paying for.

**Comment by devnote-dev** [comment]
Application API keys* are deprecated and will be removed in v2. As for the main part of this request, creating API keys on behalf of other users has been denied before simply because a user can easily create client keys by logging in. It wouldn't make sense that a user has an API key for an account they cannot access.

**Comment by nottisa** [comment]
That's unfortunate to hear. I'm creating a whole frontend for the panel and simply using backend API calls. My users can't exactly log in if there is nowhere to login. The purpose of having this API call would be to be able to integrate the console into the website, but in this case, I guess I could easily switch over to Openstack or something along those lines, as creating a single admin user in my opinion would be difficult. What would you recommend I do? Besides making a skin.

**Comment by devnote-dev** [comment]
You can still use a key from a single admin user for your frontend including server websockets, your only restriction is certain account-specific actions like creating/deleting API keys and 2FA. If you _really_ want to have those features then you can try wrapping requests around the admin API using session tokens, but this is not recommended and you are not likely to get support for this in the Discord server.

**Comment by nottisa** [comment]
Yeah, I was looking at my very slim options and wanted to confirm, at this point, I might just learn OpenStack as it's more universally accepted/developed... Thanks for your help!
