### ISSUE TITLE
Please support redis ACL

### ISSUE THREAD

**Issue by raflymln** [pterodactyl/panel#4576]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Redis ACL allow user to connect through redis with username and password, however i find that this features isn't implemented yet so that i've tried it and can't seems to connect to the external redis server with acl

### Describe the solution you'd like.

Allow this configs
```env
REDIS_HOST="localhost"
REDIS_PORT=6379
REDIS_USERNAME="user"
REDIS_PASSWORD="userpassword"
REDIS_DATABASE=69
```

**Comment by Boy132** [comment]
Pterodactyl doesn't change or "restrict" redis. This most likely is a configuration problem with your redis-server.

EDIT: I misread your request. I thought that you thought pterodactyl disabled redis' acl. :D

**Comment by raflymln** [comment]
> Pterodactyl doesn't change or "restrict" redis. This most likely is a configuration problem with your redis-server.

Nope, i have other apps which using laravel too, and other which using predis, all working fine, but not with pterodactyl

**Comment by raflymln** [comment]
Pterodactyl doesnt seem to recognize the username, it only attempts to auth using password only, even when i tried to connect with REDIS_URL, it still doesn't work

**Comment by trenutoo** [comment]
This is supported in the RC/develop versions. You can use them or wait for a future full release. 

https://github.com/pterodactyl/panel/blob/develop/config/database.php#L96-L102

**Comment by raflymln** [comment]
awesome, i hope the new version can be published soon, thank you
