### ISSUE TITLE
Transfer doesn't resume after wings restart

### ISSUE THREAD

**Issue by Jelcoo** [pterodactyl/panel#4578]
### Current Behavior

When the wings of the target node goes offline, the transfer gets stuck at the progress it last updated to. When the target node goes back online, the transfer does not resume, despite the console still printing the progress bar.

### Expected Behavior

The transfer should resume when the target node goes offline. Alternatively, the transfer could be cancelled altogether.

### Steps to Reproduce

Start a transfer from 1 node to another

### Panel Version

1.11-rc.2

### Wings Version

1.11-rc.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment]
The transfer should be canceled, not resumed.   I'd like to look into potentially seeing about resuming a transfer and other tasks in v2, but that requires a lot of other supporting features that aren't implemented yet.

Do you have any logs from the nodes?  I'm pretty sure both nodes sent a failure status whenever an error occurs and I'd like to see exactly what happens.

**Comment by Jelcoo** [comment]
![chrome_EQXntssfmL](https://user-images.githubusercontent.com/53396500/204048649-badc5fc4-4f63-4fc4-8ee0-24ed455d05ca.png)
**Source**
DEBUG: [Nov 25 20:38:03.656] POST /api/servers/1b4bc179-c284-49fa-ac5f-d3b1183f692d/transfer client_ip=169.254.234.1 latency=434.271µs request_id=76646b49-df34-4318-b69d-891b2e6825d7 status=202
DEBUG: [Nov 25 20:38:03.656] sending archive to destination server=1b4bc179-c284-49fa-ac5f-d3b1183f692d subsystem=transfer
DEBUG: [Nov 25 20:38:03.659] closing connection to server websocket connection=bbbfb462-ab3c-49a1-987c-66e369e39cd1 server=1b4bc179-c284-49fa-ac5f-d3b1183f692d subsystem=websocket
DEBUG: [Nov 25 20:38:03.659] GET /api/servers/1b4bc179-c284-49fa-ac5f-d3b1183f692d/ws client_ip=169.254.234.226 latency=6.268732429s request_id=c6bf8513-3ed2-47f9-bfb8-8fea54356b6e status=200
DEBUG: [Nov 25 20:38:03.726] opening connection to server websocket connection=38f8be99-c966-4bde-b7e6-c4cb6d48726e server=1b4bc179-c284-49fa-ac5f-d3b1183f692d subsystem=websocket
DEBUG: [Nov 25 20:38:03.730] registering event listeners for connection connection=38f8be99-c966-4bde-b7e6-c4cb6d48726e server=1b4bc179-c284-49fa-ac5f-d3b1183f692d subsystem=websocket
DEBUG: [Nov 25 20:38:39.927] waiting for stream to complete server=1b4bc179-c284-49fa-ac5f-d3b1183f692d subsystem=transfer
DEBUG: [Nov 25 20:38:57.216] sending internal activity events to Panel cron=activity subsystem=cron
DEBUG: [Nov 25 20:38:57.216] sending sftp events to Panel cron=sftp subsystem=cron
DEBUG: [Nov 25 20:39:57.216] sending sftp events to Panel cron=sftp subsystem=cron
DEBUG: [Nov 25 20:39:57.216] sending internal activity events to Panel cron=activity subsystem=cron

**Destination**
DEBUG: [Nov 25 20:38:03.657] making request to external HTTP endpoint endpoint=http://169.254.234.1/api/remote/servers/1b4bc179-c284-49fa-ac5f-d3b1183f692d headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[(redacted)] Content-Type:[application/json] User-Agent:[Pterodactyl Wings/v1.8.0 (id:gMq7IkVEUEi3sFGF)]] method=GET
DEBUG: [Nov 25 20:38:03.684] registering event listeners: console, state, resources... server=1b4bc179-c284-49fa-ac5f-d3b1183f692d
DEBUG: [Nov 25 20:38:03.684] received archive          server=1b4bc179-c284-49fa-ac5f-d3b1183f692d subsystem=transfer
DEBUG: [Nov 25 20:38:03.684] server: creating root directory and setting permissions server=1b4bc179-c284-49fa-ac5f-d3b1183f692d
^C
