### ISSUE TITLE
Servers stuck on starting state

### ISSUE THREAD

**Issue by wdhdev** [pterodactyl/panel#4581]
### Current Behavior

Quite a few of my servers show starting up when the server is online already.

### Expected Behavior

The status to switch to online once the server has started

### Steps to Reproduce

I'm not sure.

### Panel Version

1.10.4

### Wings Version

1.7.2

### Games and/or Eggs Affected

Node.js, Nginx

### Docker Image

ghcr.io/parkervcp/yolks:nodejs_18, ghcr.io/parkervcp/yolks:nodejs_17, ghcr.io/finnie2006/nginx-ptero

### Error Logs

```bash
N/A
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
You have not provided any logs for a valid bug report.

Your egg start configuration is most likely wrong for wings to detect it as running. The node egg contains huge readme with fancy pictures and instructions about this.

**Comment by wdhdev** [comment]
Turns out it was the startup configuration on my eggs.
If there is no `done` key in the JSON it'll never show online, only ever starting up.

Startup Configuration:
```json
{
    "done": ""
}
```

**Comment by trenutoo** [comment]
You should actually use the feature by providing a valid string for it to know when it has started, rather than leave it empty and always forcefully change the state.

**Comment by wdhdev** [comment]
> You should actually use the feature by providing a valid string for it to know when it has started, rather than leave it empty and always forcefully change the state.

What does it even do? Print to the console?

**Comment by trenutoo** [comment]
https://github.com/parkervcp/eggs/tree/master/generic/nodejs#configuration

It's explained in the egg README. Wings must somehow know that your application has started. This is accomplished by configuring string(s) in the egg Start configuration that the application prints once it is running for Wings to change the power state to running. 

Existing eggs have this already configured. In the case of custom bots, you'd make it print something or look for some kind of stdout to detect.

**Comment by wdhdev** [comment]
Thank you
