### ISSUE TITLE
Issue with panel (blank page, 403, 500 error)

### ISSUE THREAD

**Issue by JackobStuard** [pterodactyl/panel#4582]
### Current Behavior

Hello,

I was adding addons and theme to panel and after that I see white page (also 403 error) I see that yarn is not working, also after I run command:

`yarn build:production`

In discord I see some ongoing issue that I need to update panel so I start with this article https://pterodactyl.io/panel/1.0/updating.html but on this command:

`php artisan migrate --seed --force`

I get this error:

`In Migrator.php line 507:                                                  
Class "AddVersionFieldToServersTable" not found`

I search everywhere that error but no one get that type of issue?

### Expected Behavior

It's expected to not get this error 

`In Migrator.php line 507:                                                  
Class "AddVersionFieldToServersTable" not found`

### Steps to Reproduce

In discord I see some ongoing issue that I need to update panel so I start with this article https://pterodactyl.io/panel/1.0/updating.html but on this command:

`php artisan migrate --seed --force`

I get this error:

`In Migrator.php line 507:                                                  
Class "AddVersionFieldToServersTable" not found`

### Panel Version

1.10.4

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
Contact the authors of the addons/themes, this is not an issue with Pterodactyl.

**Comment by JackobStuard** [comment]
> Contact the authors of the addons/themes, this is not an issue with Pterodactyl.

Hi, thank you for replay.
This is now issue with migration for pterodactyl side? as now I am upgrading panel? and I see issue on this command

`php artisan migrate --seed --force`

**Comment by trenutoo** [comment]
Remove the modifications that you've installed or contact the author. This is not a bug in the Pterodactyl software.

**Comment by JackobStuard** [comment]
is possible somehow to reinstall that changes?

**Comment by devnote-dev** [comment]
If you mean restoring the panel to its original state then yes, please direct your questions to the [support server](https://discord.gg/pterodactyl) for more information.
