### ISSUE TITLE
Backups limit can be exceeded by bad cron schedule

### ISSUE THREAD

**Issue by diamkil** [pterodactyl/panel#4590]
### Current Behavior

If a user that doesn't know cron (this is what happened for us) makes a backup task run every minute it allows them to exceed the backups limit somehow (older backups not getting deleted)
[Image of the cron schedule](https://i.dkil.ca/20221130211952.png) (we are helping them fix it, */168 makes it run everyday at 12 am for some reason). I know this is now an actually valid cron schedule, however hosting services such as us have clients that don't understand cron so the panel should take that into account.

[Image of all the created backups](https://i.dkil.ca/20221130212243.png)

### Expected Behavior

The backup limits at least gets applied and the oldest backup gets deleted

### Steps to Reproduce

Create a backup schedule that runs every minute (make it exactly like the one in the screen shot, may be a bug from the */168, I'm not sure at the moment)

### Panel Version

1.10.2

### Wings Version

1.7.2

### Error Logs

```bash
Logs don't include mention of the backups
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Paddidox** [comment]
0 */4 * * *

That's my Cron which is every 4 hours. I've configured a maximum of 10 backups for this server. I've got in my Cloudflare R2 around 50 objects.

Let me know if I can provide any data to debug.
