### ISSUE TITLE
Quotation marks in egg startup command

### ISSUE THREAD

**Issue by k0ka** [pterodactyl/panel#4591]
### Current Behavior

The startup command doesn't accept quotations (symbol `"`) as argument separator.
For example, command 
`java -jar mca.jar --query "InhabitedTime < 30s"`

will be parsed as running executable `java` with arguments:
`-jar`, `mca.jar`, `--query`, `"InhabitedTime`, `<`, `30s"`

### Expected Behavior

The same as running this command in bash:
`java` executable with arguments:
`-jar`, `mca.jar`, `--query`, `InhabitedTime < 30s`

### Steps to Reproduce

1) set startup command to `echo "test test"` on any Minecraft egg
2) run it
3) it must show `echo test test` as the running command because quotation marks will be used for argument separation. It is showing `echo "test test"` at the moment so there are 2 arguments for echo: `"test` and `test"`

### Panel Version

1.10.4

### Wings Version

1.7.2

### Games and/or Eggs Affected

Minecraft (I guess others too)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by k0ka** [comment]
See also: https://github.com/Querz/mcaselector/issues/394

**Comment by k0ka** [comment]
As I traced the problem, the `startup` string goes to the `entrypoint.sh` as is. 
It is ran there https://github.com/pterodactyl/yolks/blob/master/java/entrypoint.sh#L49 as a simple string. 

We might change the entrypoint.sh so use 
`exec env /bin/bash -c "${PARSED}"`
in this case the string will be passed to bash and arguments are parsed correctly.

**Comment by parkervcp** [comment]
> exec

using exec would be better but won't work with the way containers are currently started.

**Comment by trenutoo** [comment]
> > exec
> 
> using exec would be better but won't work with the way containers are currently started.

It's already using it as seen in the linked entrypoint. The issue is with how the startup parameters are parsed in it.
