### ISSUE TITLE
Wings version incorrect?

### ISSUE THREAD

**Issue by cosmii02** [pterodactyl/panel#4593]
### Current Behavior

![image](https://user-images.githubusercontent.com/27782168/205591197-16a6d1c9-0871-400b-aa5b-8074b4a601db.png)

### Expected Behavior

It should show latest 1.11.0

### Steps to Reproduce

Look at an un-upgraded wings installation from the panel

### Panel Version

1.11.0

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
The CDN can take a little time to update. Nothing to worry about, give it a little time.

**Comment by matthewpi** [comment]
I haven't updated the latest version yet as the release took longer then expected due to a bunch of CI changes that needed to take place.  This is not a bug, just an external file not being updated.
