### ISSUE TITLE
Commands not passing through when using Wine image

### ISSUE THREAD

**Issue by Lycol50** [pterodactyl/panel#4594]
### Current Behavior

When executing commands using console, the command is not passing through.

### Expected Behavior

Commands will pass through using console.

### Steps to Reproduce

1. Import and use this egg: https://gist.github.com/Lycol50/703b679913e33b3aeb4500a6b8c492f3/raw/1421d52dc1d64f7a3aa5d929680aacc547430c08/egg-liteloader-b-d-s.json
2. Start the server (initial setup)
3. Kill Server (if console stuck at bedrock_server_mod is created)
4.  Start Server again
5.  Type some commands (e.g., help, version, list)
6.  None of these are passed through from console :(

### Panel Version

canary

### Wings Version

1.11.0

### Games and/or Eggs Affected

Minecraft (Bedrock)

### Docker Image

ghcr.io/parkervcp/yolks:wine_latest

### Error Logs

```bash
https://ptero.co/xociwucoqi
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Lycol50** [comment]
similar to #2937

**Comment by parkervcp** [comment]
This is a wine issue and not the panel
