### ISSUE TITLE
Docker versioning adds character to version string

### ISSUE THREAD

**Issue by DrPepperG** [pterodactyl/panel#4596]
### Current Behavior

Panel version has a rouge "v" in the configured app version causing a false outdated version message.
![](https://i.imgur.com/zQQOrhS.png)

Docker is using latest image published.
![](https://i.imgur.com/kHZn6b1.png)

Config is showing wrong version
![](https://i.imgur.com/IvWhVNt.png)

### Expected Behavior

Panel to be up to date.

### Steps to Reproduce

Pull latest version of docker panel image, and run it.

### Panel Version

1.11.1

### Wings Version

1.11.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/commit/3432cadd4af095a769912aaca5aaab90b4b47146
