### ISSUE TITLE
Alert Box Offset

### ISSUE THREAD

**Issue by DDynamic** [Pterodactyl/Panel#46]
![screen shot 2016-01-24 at 11 49 55 am 2](https://cloud.githubusercontent.com/assets/2935060/12537892/e627e43c-c290-11e5-983d-c71829f40ecb.png)

**Comment by jboy1234** [comment]
cool

On Sun, Jan 24, 2016 at 12:52 PM, Dylan Seidt <notifications@github.com>
wrote:

> [image: screen shot 2016-01-24 at 11 49 55 am 2]
> <https://cloud.githubusercontent.com/assets/2935060/12537892/e627e43c-c290-11e5-983d-c71829f40ecb.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Pterodactyl/Panel/issues/46>.
>



-- 
John, Jboy
