### ISSUE TITLE
Mail settings will not be saved

### ISSUE THREAD

**Issue by InvalidPandaa** [pterodactyl/panel#4602]
Hey, since the new update of the Ptero panel, the mail settings will not be saved anymore :( I tried it multiple times, the default settings will be restored anytime. Please fix that!

**Comment by Boy132** [comment]
As a workaround you can use `php artisan p:environment:mail` to change the settings.

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/commit/63a179d7f3e80e9c4c930fbaada7ea42d9467022
