### ISSUE TITLE
Mail Sending Issues

### ISSUE THREAD

**Issue by lisaaqt** [pterodactyl/panel#4604]
Hey,

first of, a notice that this it NOT connected to any "**Mail Settings not Saving**" or anything related to that issue, issue.

I updated the Panel and Wings when the new versions came out, shortly after moving everything to my new server (completely reinstalled the panel and everything else) I noticed that the "queue" mails were not sending at all. When I register a user myself he does not get an e-mail, when someone wants to reset his password he does not get a mail, the test mail works fine, no issues. I have also looked if the mail configuration in the .env is wrong, it's not. I have looked if the DNS entry for mail settings are wrong in CloudFlare, also isn't the case. It's just that automatic mails are apparently not storing in database or sending out at all, The log in mysql does say "sending password reset e-mail" but I never receive any mail. The ptereoq service is working fine, its online and no issues in any log files or whatsoever.
I hope someone can help me out here since I am not the only one facing this issue!

Sincerly,
Lisa

**Comment by VarChar42** [comment]
I have the same issue. After a fresh install emails except the test email dont work.

I used the official "Getting Started" guide.
OS: Debian 11
PHP Version: 8.1

**Comment by SneakyHub** [comment]
You can navigate to your .env file and update your mail settings in there. I personally use mailgun for my mail and it works just fine even on their free plan.

**Comment by SneakyHub** [comment]
> Hey,
> 
> first of, a notice that this it NOT connected to any "**Mail Settings not Saving**" or anything related to that issue, issue.
> 
> I updated the Panel and Wings when the new versions came out, shortly after moving everything to my new server (completely reinstalled the panel and everything else) I noticed that the "queue" mails were not sending at all. When I register a user myself he does not get an e-mail, when someone wants to reset his password he does not get a mail, the test mail works fine, no issues. I have also looked if the mail configuration in the .env is wrong, it's not. I have looked if the DNS entry for mail settings are wrong in CloudFlare, also isn't the case. It's just that automatic mails are apparently not storing in database or sending out at all, The log in mysql does say "sending password reset e-mail" but I never receive any mail. The ptereoq service is working fine, its online and no issues in any log files or whatsoever. I hope someone can help me out here since I am not the only one facing this issue!
> 
> Sincerly, Lisa

My discord is " Sneaky#9999 " if you wanna reach out I can help you with fixing your mail issues. Since the mail functionality for pterodactyl works just fine. It may be better if we communicate via discord to find the solution to your problem.

**Comment by skippybossx** [comment]
> 

I do have a same problem after upgrade to 1.11.1 (also settings does not save, but you can edit .env or use "php artisan p:environment:mail" to save them)

Installed new 1.11.1 and have same problem there. Tried new outlook account, and same problem. So its not email account related. It also worked like a charm before upgrade.

**Comment by SneakyHub** [comment]
Updating from the previous version with no modifications to 1.11. I can confirm that this is an issue. The test mailer works just fine but when the server is created. There is no email being sent confirming that the pterodactyl server has been installed.

It did work flawlessly before the 1.11 update.

**Comment by SneakyHub** [comment]
Forgot password and creating new user emails don't work properly either.

**Comment by skippybossx** [comment]
yeah, with mail using no encryption nothing works (did before upgrade) i found its laravel 9 related, made some changes and i can send test mail now but.. new server installed, new acc created , password reset etc email is not sending at all
all those things worked without problem before upgrade

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/commit/63a179d7f3e80e9c4c930fbaada7ea42d9467022
