### ISSUE TITLE
E-Mails not categorised in the correct queue, emails not sending to default pteroq service config.

### ISSUE THREAD

**Issue by Xeravax** [pterodactyl/panel#4610]
### Current Behavior

Currently, email are not sending to clients as visible in #4604 and **maybe** #4602 is related, but that would have to be checked.
Anyways, I found a way to (temporary) resolve this. 

1. Run `nano /etc/systemd/system/pteroq.service`
2. Go to the line where it says: 
    `ExecStart=/usr/bin/php /var/www/pterodactyl/artisan queue:work --queue=high,standard,low --sleep=3 --tries=3`
3. Modify the `--queue=high,standard,low` by adding `,default` at the end. (Making it `--queue=high,standard,low,default`)
4. Then run `service pteroq restart`
5. Check if your (pending) emails have sent, or by requesting a password reset. 

### Expected Behavior

Ptero is supposed to send emails to the email adresses used to register, the queue is supposed to send out.
If I ask for a password reset, an account gets created for me it should send an email with the password (re)set link. 

### Steps to Reproduce

1. Be on panel version `1.11.1`
2. Have SMTP setup
3. Try to send a password reset email, a account and/or server creation email '
4. See your emails not being sent

### Panel Version

1.11.1

### Wings Version

1.11.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Xeravax** [comment]
In the Discord server, I've talked to vitaminion, and he experienced the exact same issue: 
![image](https://user-images.githubusercontent.com/25939526/207158369-f63c1c8e-9579-4f39-8d62-084f3e481693.png)

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/commit/6377e3309ad104852209c5f2bbc33a61bd083ce4

**Comment by Xeravax** [comment]
thank you @matthewpi, that was bloody quick.
![image](https://user-images.githubusercontent.com/25939526/207158614-0971a320-22f9-4fc6-b070-3399e3dd8130.png)

**Comment by Xteri08** [comment]
are you sure the problem is fixed i am getting same problem and i tried fresh installs many times too i applied the pteroq fix and it fixed the issue temp but it started to come automatically
