### ISSUE TITLE
"Forgot Password" email not sending

### ISSUE THREAD

**Issue by rasm945i** [pterodactyl/panel#4612]
### Current Behavior

No "forgot password" email is being sent. I cannot find anything in the panel logs.
Test email works for me.
Another user on Discord confirmed that test email and server creation emails works for him, but forgot password email didn't.

### Expected Behavior

I expect an email to be sent to the registered users email when they forget their password and request a reset link.

### Steps to Reproduce

- Go to panel website
- "Forgot Password"
- Enter email of a registered user
- Wait and realize the email isn't being sent/delivered

### Panel Version

1.11.2

### Wings Version

1.11.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Loki-101** [comment]
I am the other user. I tested from a panel instance running on Fedora Server 37. Mail was successfully sent via the test feature and the notification mail upon creating a new server. The forgot password option shows no errors but the email does not go through. Panel Version is 1.11.2 and Wings Version 1.11.0

**Comment by matthewpi** [comment]
Unable to reproduce, make sure you have restarted your queue worker and that it is running.  `systemctl restart pteroq.service`.  Check for any errors as well.

**Comment by Loki-101** [comment]
I rebooted the VPS I was testing with before testing the email functions. With that being said, after restarting pteroq right now the forgot password function is working again and the email made it through.

These are the errors from earlier today in case anyone finds them useful, but I'd chalk this up to "random one time things that go wrong and fix themselves": https://pteropaste.com/szhwbx/
