### ISSUE TITLE
500 error when updating node settings when offline

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#4613]
### Current Behavior

When you update an offline nodes configuration you will get a 500 error..

### Expected Behavior

The configuration updates and an alert that the configuration will need to be manually adjusted will appear

### Steps to Reproduce

Create a new node with any values.
Do not start wings
Edit Any value

You will get a 500 error

### Panel Version

1.11.2

### Wings Version

1.11.0

### Error Logs

```bash
No logs are generated by this error
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
I cannot reproduce this and [Panel will update the settings whether it's reachable or not.](https://github.com/pterodactyl/panel/blob/develop/app/Services/Nodes/NodeUpdateService.php#L56-L69) The fact that no exceptions are written indicates there are permission issues for it to write them and is what's triggering internal errors.

**Comment by x-x6n** [comment]
> I cannot reproduce this and [Panel will update the settings whether it's reachable or not.](https://github.com/pterodactyl/panel/blob/develop/app/Services/Nodes/NodeUpdateService.php#L56-L69) The fact that no exceptions are written indicates there are permission issues for it to write them and is what's triggering internal errors.

I'm getting this error now.

**Comment by ALameLlama** [comment]
Getting this error when trying to change any settings on a newly create node that isn't connected yet

**Comment by Shykaruu** [comment]
same error

**Comment by Shykaruu** [comment]
i've just enable "Reset Daemon Master Key" when saving and it fix this error
