### ISSUE TITLE
Failing To Install Steam Based Games

### ISSUE THREAD

**Issue by metallicgloss** [Pterodactyl/Panel#462]
Hello.

I have recently come across an issue whereby on an attempt to install a Custom Source Game, Insurgency or Ark. 

After stopping the daemon and starting NPM manually, I noted that it very quickly went from 'Server has been suspended.' to 'Completed installation process for server.'. I then went to have a look at the logs, and noted an error at the very end which has started appearing.

```
 [----] Update complete, launching %appname%...
./steamcmd.sh: line 30:  3219 Segmentation fault      (core dumped) $DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
'linux32/steamclient.so' -> '../.steam/sdk32/steamclient.so'
```

If I run the install script listed in the database manually, it works fine and is able to download the SteamCMD and game perfectly. I haven't modified any aspect of the script so am not too sure where this issue would be coming from. Any assistance resolving this would be appreciated.

That appears just after it started running the steam script and finishes updating, and this causes the install process to finish, and on a couple times crashed the NPM process. 

My daemon is currently installed on Ubuntu 16.04, 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux. 
My docker info for my test system: https://pastebin.com/4z2nhMzK

**Comment by DaneEveritt** [comment]
Is this issue still occurring?

**Comment by metallicgloss** [comment]
Hello.

This issue hasn't caused a problem for a while since the last two updates have been dropped, there is an intermittent problem with it occasionally occurring however that is more than likely due to Steam Servers being slow.

**Comment by ET-Bent** [comment]
I can also confirm that this error has not occurred again. It seems to have been some strange thing with steam itself.
