### ISSUE TITLE
can't upload files

### ISSUE THREAD

**Issue by gokraptor** [pterodactyl/panel#4620]
### Current Behavior

I'm trying to upload a file to the panel but it errors after 2-3 seconds and no matter how many times i try, it still doesn't work.

### Expected Behavior

it should upload the file even though it is slow.

### Steps to Reproduce

I'm trying to upload a file that is 170 mbs to the server panel and i can't upload it. I thought i can't upload it because of its big size but no, i can't upload a 40mb jar file too. 

### Panel Version

i really don't know

### Wings Version

i really don't know

### Games and/or Eggs Affected

Minecraft

### Error Logs

```bash
ERROR The requested resource was not found on this server.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by yesBad** [comment]
Do you even own/host the Panel?

**Comment by gokraptor** [comment]
> Do you even own/host the Panel?

i bought the panel for the Minecraft Server.

**Comment by yesBad** [comment]
What host is this is? As it is their problem, not ours. Anyone can host their own Pterodactyl.

**Comment by danny6167** [comment]
> > Do you even own/host the Panel?
> 
> i bought the panel for the Minecraft Server.

This isn't a place to report issues with your hosting. Contact who ever you purchased your Minecraft server from.

**Comment by gokraptor** [comment]
sorry.
