### ISSUE TITLE
Schedule don't delete oldest backup

### ISSUE THREAD

**Issue by Leon-JavaScript** [pterodactyl/panel#4625]
### Current Behavior

If a schedule attempts to create a backup and the backup limit has already been reached, the schedule remains in the processing state indefinitely.

### Expected Behavior

I think it's an error with deleting the oldest backup.

### Steps to Reproduce

1. Create a schedule in a server where backups have already reached the backup limit.
2. Add the task to the schedule to create a backup.
3. Execute the schedule and it remains infinitely on the processing state

### Panel Version

1.11.2

### Wings Version

1.11.0

### Games and/or Eggs Affected

TeamSpeak3 Server

### Docker Image

ghcr.io/pterodactyl/yolks:debian

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
What storage system are you using for backups? Was the server running when you executed the schedule? Please get the panel logs so we can check.

**Comment by FreddieDK** [comment]
I believe i'm having the same issue.

**Comment by devnote-dev** [comment]
@FreddieDK Please provide the information requested above.

**Comment by alexgn100** [comment]
> @FreddieDK Please provide the information requested above.

Hello, i have the same problem. I have S3 Backups.
