### ISSUE TITLE
Deleting a file which begins with a space does not work 

### ISSUE THREAD

**Issue by mason-rogers** [pterodactyl/panel#4627]
### Current Behavior

The issue is also partially responsible to copy function as it's how I discovered this. The copy function attempts to suffix " copy {x}" before the file extension, but dotfiles do not have anything before the extension meaning the file name now begins with a space.

If you try to delete a file which begins with a space in the name, it will disappear from the UI (because of state management) but will be there on the filesystem and also on refresh.

Some investigation goes down to the TrimStrings middleware in Kernel.php, as it's trimming the space before it even reaches the controller so Wings receives the file name with no spaces at the start.

### Expected Behavior

Deleting the file should remove it from the filesystem properly

### Steps to Reproduce

- Create a file beginning with `.` (eg .gitignore)
- Copy the file through the context menu
- Attempt to delete the copied file
- Refresh and see the file is still there

### Panel Version

1.11.2

### Wings Version

1.11.0

### Error Logs

```bash
N/A
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
Related: #4539
