### ISSUE TITLE
Pterodactyl not working

### ISSUE THREAD

**Issue by Stephan69** [pterodactyl/panel#4631]
This is the error

FATAL: [Dec 21 16:04:30.104] failed to load server configurations error=http: request creation failed: Get "http://192.122.54.27/api/remote/servers?page=0&per_page=50": dial tcp 192.122.54.27:80: connect: connection refused

The ip that is used above is fake for security!

**Comment by devnote-dev** [comment]
Please use the [Discord server](https://discord.gg/pterodactyl) for this or the [discussions section](https://github.com/pterodactyl/panel/discussions) at the very least. This is not an issue with Pterodactyl.

**Comment by FoksVHox** [comment]
As mentioned, this isn't an issue with the software, it's an issue with the configuration of your panel. However, next time you submit an issue to the repo, please follow the template. They are there for a reason.

**Comment by mckzstudios** [comment]
Fuck you
