### ISSUE TITLE
Incorrect server status screen

### ISSUE THREAD

**Issue by MinerPL** [pterodactyl/panel#4633]
### Current Behavior

The panel after a reinstallation error sets the status of the server in the database to `reinstall_failed` () which results in a screen about restoring the backup instead of information about reinstallation/reinstallation error

![msedge_KrPKwu9P53](https://user-images.githubusercontent.com/37021230/209192139-84eb42c2-32a4-40e8-9817-12b570552fab.png)
![image](https://user-images.githubusercontent.com/37021230/209192162-2b42d672-070c-4d20-ad07-ce4de63e1d91.png)

### Expected Behavior

Information on erroneous reinstallation/further information on server installation

### Steps to Reproduce

In my case, wings throw an error 
```
ERROR: [Dec 22 17:31:15.201] failed to complete server re-install process error=Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: openat2 /sys/fs/cgroup/system.slice/docker-559896a6858c86fb739259a3589a2eb68767c957825c7f9cb42cbe2bd5d8b071.scope/io.bfq.weight: no such file or directory: unknown server=f5d259b7-de28-47c0-951d-4bbaedcbcf2e

Stacktrace:
Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: openat2 /sys/fs/cgroup/system.slice/docker-559896a6858c86fb739259a3589a2eb68767c957825c7f9cb42cbe2bd5d8b071.scope/io.bfq.weight: no such file or directory: unknown
```

I haven't yet found the cause of this problem so I don't have exact instructions on how to replicate it - I might add that the problem occurred after a server transfer from an ARM server to an AMD server.

### Panel Version

1.11.2

### Wings Version

1.11.2

### Error Logs

```bash
Wings: https://ptero.co/yretowonaw
Pterodactyl: http://bin.ptdl.co/sgrqz
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/commit/fbdac5b63f4222588c0ba8cfe85ffca38872daf1
