### ISSUE TITLE
Pterodactyl panel: error 500

### ISSUE THREAD

**Issue by jetfilou** [pterodactyl/panel#4636]
### Current Behavior

Hello, I have install the pterodactyl panel + wings on my vps server to create my garry's mod server but after 1 day, when I create my 3rd backups my panel : (https://server.gmod2life.fr) show an error 500 .. :(

after giving my logs to the discord bot: https://pteropaste.com/x58moc

it say to me to do this : `systemctl status mysql`
and the status of my mysql is : MariaDB server is down (exit-code)

### Expected Behavior

I would like to have help because I can't access to my panel.. and don't wan't to reinstall my vps. I already search on google, looking the existing issues and giving my logs to the discord bot before opening this issue.

### Steps to Reproduce

Just do backups..

all return to a problem of: `systemctl status mysql`
https://pteropaste.com/x58moc

### Panel Version

1.11

### Wings Version

1.11

### Games and/or Eggs Affected

Source Engine : Garry's Mod

### Error Logs

```bash
http://bin.ptdl.co/8p07d
https://ptero.co/wyjyvyqevy
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
This is not a bug in the software. Please use Discord or Github discussions for configuration support.
