### ISSUE TITLE
Cannot download file from file manager

### ISSUE THREAD

**Issue by idkw** [Pterodactyl/Panel#464]
I am running panel v0.6.1 and daemon v0.4.1.
When I try to download a file from the file manager of a minecraft server it does this : 

It opens a tab pointing to the panel url and gets a 302 Redirect to the node url
![1](https://cloud.githubusercontent.com/assets/7012331/26647238/f247ca42-463e-11e7-9aaa-7778960d46d2.png)

The browser then follows the Redirect to the node and gets a 500 error with the following error :

```
{
    "error": "An error occured while attempting to authenticate with an upstream provider.",
    "res_code": 403,
    "res_body": {
        "error": "An invalid request token was recieved with this request."
    }
}

```
 
![2](https://cloud.githubusercontent.com/assets/7012331/26647300/353ff248-463f-11e7-9a2b-73fbd8df4e96.png)

The request to the node seems indeed to be missing a cookie or something to authenticate it.
Did I configured something wrong or is it a panel bug ?

Thank you

**Comment by DaneEveritt** [comment]
Sorry for the super late response, but this issue is due to a misconfigured Node Token causing communication between the two services to fail.

**Comment by idkw** [comment]
Ok, but what do I have to do to fix it ? How to get the correct token and where to put it ?
