### ISSUE TITLE
Problem with tar.xz and wings 1.11.0

### ISSUE THREAD

**Issue by bagou4502** [pterodactyl/panel#4640]
### Current Behavior

Wings 1.11.0 seem to can't check the available space for file decompression when the file is a tar.xz

For example if i try to decompress a 100mb file on a server with 10gb of storage wings are going to do show only this and nothing after:
`DEBUG: [Dec 26 19:47:26.756] checking if space is available for file decompression file=RLCraft.tar.xz request_id=174ddd18-0c5e-47fa-b9bd-46fb9a5245eb root_path=/ server_id=36a2e614-d165-44d6-b219-226c71c66d3d`

But if i set to this server a unlimited disk space the file is decompressed successfully 

### Expected Behavior

The file need to be decompressed 

### Steps to Reproduce

Upload a tar.xz file on pterodactyl server where there are a space limit and try to decompress it

Do same with a server with unlimited space for see the problem 

Example of tar.xz : https://cdn.bagou450.com/versions/minecraft/forge/1.19.2.tar.xz

### Panel Version

1.11.2

### Wings Version

1.11.0

### Games and/or Eggs Affected

All eggs are affected (But here minecraft paper and vanilla)

### Docker Image

All docker image are affected (but here java 8)

### Error Logs
There are no error in logs i have only
```bash


`DEBUG: [Dec 26 19:47:26.756] checking if space is available for file decompression file=RLCraft.tar.xz request_id=174ddd18-0c5e-47fa-b9bd-46fb9a5245eb root_path=/ server_id=36a2e614-d165-44d6-b219-226c71c66d3d`
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by mattpursuit** [comment]
I can confirm this is happening.

**Comment by Kicpro** [comment]
I can also confirm that.

**Comment by VibeGAMESNL** [comment]
This might be related to https://github.com/pterodactyl/panel/pull/4568 and https://github.com/pterodactyl/panel/issues/4415
