### ISSUE TITLE
Cloning GitHub Repo discord.py Egg

### ISSUE THREAD

**Issue by FroostySnoowman** [pterodactyl/panel#4642]
### Current Behavior

The GitHub repository is not being cloned when I have put it in the variables.

### Expected Behavior

When I click start, it should automatically pull files from the GitHub repo and put them in the Files.

### Steps to Reproduce

Discord.py egg and using the Git Repo Address or Git Branch. Neither do anything.

### Panel Version

1.10.4

### Wings Version

no idea- not the sys admin.

### Games and/or Eggs Affected

Discord.py Egg

### Docker Image

ghcr.io/parkervcp/yolks:python_3.10

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by yesBad** [comment]
Use parker's egg repo for issues as its from there.. Not from the panel.


Plus the git works fine last I used.

**Comment by devnote-dev** [comment]
This isn't an issue with the panel/Wings/egg, you just need to configure it properly for it to work...

**Comment by parkervcp** [comment]
If anything this needs to go to my repo if. More so that you should take it to discord for faster help.
