### ISSUE TITLE
Too many requests showing all servers (showing others' servers)

### ISSUE THREAD

**Issue by PrometheusDevs1** [pterodactyl/panel#4643]
### Current Behavior

If you have an admin on a panel and you have several servers within node/nodes, and clicking on show all servers, you will make so many requests that the machine will not be able to process it and it may become very slow or even crash. 

No, it doesn't have much to do with the machine's resources since even with high quality machines, Pterodactyl and wings stay very slow or crash. 

I think you should put a kind of cooldown to not try to make the requests all at once to show all the servers. I no longer use this feature for that reason.

### Expected Behavior

Make the requests one at a time to each server without doing everything at once. So it would be, if this server/wings is available to make the request, it makes the request and goes on to the next one, if it is not available it goes on to the next one too but this with waiting time between requests so that what I said above doesn't occur.

### Steps to Reproduce

It is enough to be an administrator of a panel, to have node/nodes with several servers (+30), depending on the machine this error can cause different problems. Then, just click on show the servers of others (all servers) and the panel will be very slow or it will crash almost everything on the machine (or even go off).

I use cloudflare proxy just on daemon port of the node (8443) I did everything you say to do for the cloudflare proxy to work correctly.
I use the wings and the panel on the same machine (Before there were 2 machines, one for the wings and the other for the panel and this still happened.)

### Panel Version

1.11.2

### Wings Version

1.11.0

### Games and/or Eggs Affected

Discord (node.js generic), Discord (python generic) and all can be affected

### Docker Image

ghcr.io/parkervcp/yolks:nodejs_17, Python 3.8|ghcr.io/parkervcp/yolks:python_3.8 and all can be affected

### Error Logs

```bash
![bug report ptero](https://user-images.githubusercontent.com/101600574/209948781-2faab2a2-4169-455a-bc08-af56f2799c8d.png)

Wings: https://ptero.co/weheqewoku
Panel: http://bin.ptdl.co/4ojhr
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by PrometheusDevs1** [comment]
When I disabled that option and cleared the cache and cookies, it stopped making requests and everything went back to normal super fast.

**Comment by Carloz2er** [comment]
with me is happening exactly the same thing

**Comment by parkervcp** [comment]
I wonder if the way to do this is to have a single endpoint that returns the data that is requested for all servers on a node. One that is filtered before returning it.

If wings caches that data regularly and just returns it from memory it could be returned nearly instantly.

**Comment by PrometheusDevs1** [comment]
> I wonder if the way to do this is to have a single endpoint that returns the data that is requested for all servers on a node. One that is filtered before returning it.
> 
> If wings caches that data regularly and just returns it from memory it could be returned nearly instantly.

The problem is the bulk requests that affect all machines, no matter what resources they have. Even though machines not consuming anything by making these requests, something affects it because the panel drops or becomes very slow
