### ISSUE TITLE
Compressing methods enchantment

### ISSUE THREAD

**Issue by HLF-Raideer** [Pterodactyl/Panel#465]
Our new idea is the following:
Ability to compress the server at all from the panel with a given button (such as compressing directories)

(++)
If it is added, it also coud be also a great idea to make backups and restore them from the panel.

**Comment by schrej** [comment]
You want to be able to compress all the server files at once with the click of a button, is that correct?

The backup and restore feature is already on our list: #114

**Comment by HLF-Raideer** [comment]
Sorry. I haven't seen it.
