### ISSUE TITLE
Banned from discord

### ISSUE THREAD

**Issue by reashetyrr** [pterodactyl/panel#4650]
### Current Behavior

sorry, i would do this over discord but im banned there,

i have no clue why can anyone find out why? the discord info is: reashetyr#5143

i know im banned because when i use the discord web interface with network tab of developer tools open i get the message back the user has been banned

### Expected Behavior

N/A

### Steps to Reproduce

N/A

### Panel Version

N/A

### Wings Version

N/A

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TrixterTheTux** [comment]
No one by that name has been banned from the Discord, perhaps you had an alt account that got banned?

**Comment by reashetyrr** [comment]
i only used reashetyr :thinking:

**Comment by parkervcp** [comment]
You have been unbanned
