### ISSUE TITLE
unable to connect with the websocket

### ISSUE THREAD

**Issue by reashetyrr** [pterodactyl/panel#4651]
### Current Behavior

currently whenever i start my wings instance i get the following stacktrace:
```
Stacktrace:
EvalSymlinks: too many links
server/filesystem: failed to evaluate symlink
github.com/pterodactyl/wings/server/filesystem.(*Filesystem).SafePath
        github.com/pterodactyl/wings/server/filesystem/path.go:45
github.com/pterodactyl/wings/server/filesystem.(*Filesystem).DirectorySize.func1
        github.com/pterodactyl/wings/server/filesystem/disk_space.go:176
github.com/karrick/godirwalk.walk
        github.com/karrick/godirwalk@v1.17.0/walk.go:277
github.com/karrick/godirwalk.walk
        github.com/karrick/godirwalk@v1.17.0/walk.go:338
github.com/karrick/godirwalk.walk
        github.com/karrick/godirwalk@v1.17.0/walk.go:338
github.com/karrick/godirwalk.walk
        github.com/karrick/godirwalk@v1.17.0/walk.go:338
github.com/karrick/godirwalk.walk
        github.com/karrick/godirwalk@v1.17.0/walk.go:338
github.com/karrick/godirwalk.Walk
        github.com/karrick/godirwalk@v1.17.0/walk.go:258
github.com/pterodactyl/wings/server/filesystem.(*Filesystem).DirectorySize
        github.com/pterodactyl/wings/server/filesystem/disk_space.go:169
github.com/pterodactyl/wings/server/filesystem.(*Filesystem).updateCachedDiskUsage
        github.com/pterodactyl/wings/server/filesystem/disk_space.go:145
github.com/pterodactyl/wings/server/filesystem.(*Filesystem).DiskUsage.func1
        github.com/pterodactyl/wings/server/filesystem/disk_space.go:116
runtime.goexit
        runtime/asm_amd64.s:1571

server/filesystem: directorysize: failed to walk directory
```

this started happening after scaling down the ram and cpu, ive set them in the panel config properly

### Expected Behavior

no stacktraces and a fully fine running wings instance

### Steps to Reproduce

no clue, happened after scaling down the vm the wings instance is running on

### Panel Version

1.11.2

### Wings Version

1.11.0

### Error Logs

```bash
wings: https://ptero.co/ypanucidah
panel: http://bin.ptdl.co/ovdho
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by reashetyrr** [comment]
as additional small information, i have several nodes setup, only one node (which i scaled down) has this issue

**Comment by devnote-dev** [comment]
Looking into your Wings logs, it seems there is a server that has a recursive symbolic link causing the function to error. I don't believe this is websocket specific as Wings does regular file system checks for other purposes.

```
EvalSymlinks: too many links root=/srv/daemon-data/30d74aff-0074-484e-ac2d-9ce7d8b4ee30
```
