### ISSUE TITLE
Disable mails

### ISSUE THREAD

**Issue by legabi** [pterodactyl/panel#4659]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be nice if we could disable the panel mails when we don't have a mail server

### Describe the solution you'd like.

A simple button in the admin area and a check in the controller

**Comment by devnote-dev** [comment]
Setting the `MAIL_DRIVER` variable to "log" should do this.

**Comment by legabi** [comment]
oh ok thanks

**Comment by legabi** [comment]
![image](https://user-images.githubusercontent.com/69119038/213809507-4dcec591-fc92-49b5-813d-c8974edad948.png)
log

**Comment by devnote-dev** [comment]
~~Seems to be an issue with [outdated code](https://github.com/pterodactyl/panel/tree/develop/app/Notifications) as Laravel 9 supports this: https://stackoverflow.com/questions/71156385/laravel-9-symfonymailer-error-an-email-must-have-a-to-cc-or-bcc-header~~

Assumed you fixed your error, please close this issue.

**Comment by modpotato** [comment]
> Setting the `MAIL_DRIVER` variable to "log" should do this.

could i do that with MAIL_MAILER or does this not work anymore?
