### ISSUE TITLE
How to disable the login captcha

### ISSUE THREAD

**Issue by Tom-III** [Pterodactyl/Panel#466]
---------------------
Is it possible to disable the login captcha?  If yes then how, I can't find it in the control panel, if not can it be added?

**Comment by DaneEveritt** [comment]
Set `RECAPTCHA_ENABLED=false` in `.env` and then run `php artisan config:cache`.

**Comment by VeryLongNicknameSuchWow** [comment]
Modifying the .env file didn't disable it.
I had to go into the 'settings' table in pterodactyl database and there set 'settings::recaptcha:enabled' to false.
