### ISSUE TITLE
add some already created v2 features into v1

### ISSUE THREAD

**Issue by LoaiDev** [pterodactyl/panel#4661]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

some of the already done features in v2 to be used in v1 releases. something like direct downloads #165 implemented about 15 months ago but it won't get added to releases unless everything is done in v2.

### Describe the solution you'd like.

if a feature is already done and can work in the current version, why do we need to wait for it?

**Comment by matthewpi** [comment]
Some features have already been backported.  Based off of my limited time already, it's going to be faster to finish v2 than add anything into v1.

I don't have a timeline for anything, but I'm not going to spend time moving anything else back.
