### ISSUE TITLE
State of documentation

### ISSUE THREAD

**Issue by kylhuk** [pterodactyl/panel#4662]
Pterodactyl just has too many undocumented values. There should be some effort to expose all possible configuration with a description and valid values.

I had two major issues while setting up Pterodactyl.

1) There is not mentioned that Pterodactyl is not working in a sub-path. When setting up a reverse proxy, this information is quite essential.
2) I had issues with CORS. I found two undocumented config settings, one in the Panel (`APP_CORS_ALLOWED_ORIGINS`) and one inside Wings (`allowed_origins`). The first one I only found because I was looking at the source code. The second one was mentioned in an issue over a year ago (https://github.com/pterodactyl/panel/issues/3599#issuecomment-912995176_). Ironically, @xorinzor also said this should be documented, but the issue was closed and forgotten.

So, can we please update the docs? This should be mainly done by those devs who implemented those config settings.

Thanks

--
kylhuk

**Comment by devnote-dev** [comment]
Please refer to https://github.com/pterodactyl/documentation.

**Comment by kylhuk** [comment]
Thanks @devnote-dev. Opened a new issue in the appropriate repo. Closing this one now.

New issue https://github.com/pterodactyl/documentation/issues/516
