### ISSUE TITLE
Error launching minecraft server via egg

### ISSUE THREAD

**Issue by NoahPodcast** [pterodactyl/panel#4664]
### Current Behavior

This error is launched at each start and I do not understand because it worked on other mc servers.
Here is the console error:

`[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/yolks 
Digest: sha256:ba880156e2489988f637d10860388201a9b003e46b68e53767c0158d354b94a3 
Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
Error: Unable to access jarfile server.jar
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/yolks 
Digest: sha256:ba880156e2489988f637d10860388201a9b003e46b68e53767c0158d354b94a3 
Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
Error: Unable to access jarfile server.jar
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
`
![Capture d’écran 2023-01-24 à 14 18 57](https://user-images.githubusercontent.com/93767601/214305279-b40c5cc2-3161-4ba2-b28d-e2a7bdd73c0c.png)

### Expected Behavior

I want the server to start without a hitch

### Steps to Reproduce

When I try to load a backup from other servers not related to Pterodactyl. The server simply refuses to launch even though it has the same files as on a working host.

### Panel Version

1.11.2

### Wings Version

wings v1.11.0

### Games and/or Eggs Affected

Minacraft (Paper)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
https://ptero.co/gapyxyguqi
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
This is not a bug in the software. Please use the Discord server or Github discussions for configuration support.

Your install can't locate a jar file it's configured to look for in the startup variables, which indicates the install has failed or not all files were uploaded from a backup. Reinstall would pull the necessary files.
