### ISSUE TITLE
Problem During SSL The Node

### ISSUE THREAD

**Issue by gabricocche** [pterodactyl/panel#4665]
### Current Behavior

Hi, I'm trying to SSL my node address during installation of panel and wings, but I have this error: https://ptero.co/ynojyjiviv.html

### Expected Behavior

The SSL works fine

### Steps to Reproduce

Trying to SSL the Node address.

### Panel Version

/

### Wings Version

/

### Error Logs

```bash
https://ptero.co/ynojyjiviv.html
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug but a issue with your configuration. Please visit the discord to get support.
