### ISSUE TITLE
I am not able to pull the logs via API

### ISSUE THREAD

**Issue by XDukeHD** [pterodactyl/panel#4666]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

How do I get the logs from a specific server and return them to the console? I'm not getting it at all, could you tell me if there is a route in the api to deliver the logs from a specific server?

### Describe the solution you'd like.

I wanted a route to pull the logs from a specific server to return in our code

**Comment by trenutoo** [comment]
You have to pull them from the websocket of the server.

[See the API documentation](https://dashflo.net/docs/api/pterodactyl/v1/)  on how to retrieve the necessary details for the connection.
