### ISSUE TITLE
No folders are created when unarchiving .rar files

### ISSUE THREAD

**Issue by Boy132** [pterodactyl/panel#4668]
### Current Behavior

When unarchiving a .rar file via the file browser folders are ignored and all files are created in the root folder.

Example:
![image](https://user-images.githubusercontent.com/8203120/215086315-62944f26-3ce5-4d8c-8abe-216c2b21e09e.png)

### Expected Behavior

Create the folders when unarchiving and put the files in their respective folder.

Correct example with .zip instead of .rar:
![image](https://user-images.githubusercontent.com/8203120/215087985-4bd93e28-c4d1-462c-99f4-37252230c9d4.png)

### Steps to Reproduce

1. Create a rar that contains folder and files.
2. Upload that rar file to a server.
3. Unarchive the rar in the file browser.

### Panel Version

1.11.2

### Wings Version

1.11.0

### Error Logs

No errors in the panel or wings logs. Wings log show that the decompressing was successfull.

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by gOOvER** [comment]
https://github.com/pterodactyl/panel/issues/3267#issuecomment-821856421

**Comment by Boy132** [comment]
> [#3267 (comment)](https://github.com/pterodactyl/panel/issues/3267#issuecomment-821856421)

If its really unsupported the option to unarchive .rars should be removed. But tbh I see no reason to not support it.
Basically this: https://github.com/pterodactyl/panel/issues/3267#issuecomment-821868063

**Comment by matthewpi** [comment]
> [#3267 (comment)](https://github.com/pterodactyl/panel/issues/3267#issuecomment-821856421)

I don't see a reason not to support rars, the libraries we use support it.  This issue is about when the file is extracted the contents get flattened, which is a bug either in Wings or in the rar library, which should be fixed.

**Comment by polokidupa** [comment]
> > [#3267 (comment)](https://github.com/pterodactyl/panel/issues/3267#issuecomment-821856421)
> 
> I don't see a reason not to support rars, the libraries we use support it. This issue is about when the file is extracted the contents get flattened, which is a bug either in Wings or in the rar library, which should be fixed.

It's simply executing the wrong parameter of unzip. If i recall correctly, there were two unzip parameters which i mainly used. It might be using "unzip -e", instead of "unzip -x" although im not sure.
