### ISSUE TITLE
Default values for variables sometimes can't be changed

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#467]
This is an odd one and I haven't done enough testing to accurately determine why this occurs, but it definitely happens:

When I create certain variables _without_ specifying the default value, if I come back later and try to create a default value, sometimes it will say that it saved my changes but then I check the variable and it's still blank. Likewise, there are many times when I create a default value and go to remove it and it says that it saved the changes, but the old value is still in there.

One thing I did notice is that if the latter situation occurs (where I can't completely remove the value), I _can_ still change the value to something else, I just can't completely remove it (even if it's not required).

**Comment by DaneEveritt** [comment]
Most likely related to #470

**Comment by DaneEveritt** [comment]
Fixed in https://github.com/Pterodactyl/Panel/commit/65957e7ea51f5ed9826e960d8469bf3b270ac056 and https://github.com/Pterodactyl/Panel/commit/1c5f89204981b840e300f81111fbc84240b17ea7
