### ISSUE TITLE
Docker image reinstalls on every boot

### ISSUE THREAD

**Issue by etoiledefeu** [pterodactyl/panel#4672]
### Current Behavior

Hi ! Since v1.11.3, when I boot or start a pterodactyl container it reinstalls the dockee image; like an update but on every boot, which consumes resources and lengthens the start/restart time

### Expected Behavior

How to disable this because it consumes more resources and lengthens the restart time?

### Steps to Reproduce

Create a pterodactyl server (egg nodejs)
start/restart it
At each restart the docker image will redownload and reinstall

### Panel Version

1.11.3

### Wings Version

1.11.1

### Games and/or Eggs Affected

Nodejs

### Docker Image

ghcr.io/parkervcp/yolks:nodejs_18

### Error Logs

```bash
No error log is returned
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
Pterodactyl tells docker to check for an updated image but should only pull an image when there is an update.

The images in both the pterodactyl repo and my own rebuild on Mondays.

**Comment by fytage** [comment]
I have the same issue and i don't really understand what you meant by the last sentence @parkervcp mind helping me out here? also only happens on nodejs here.
