### ISSUE TITLE
Cannot assign my wireguard IP to Pterodactyl servers (bind: cannot assign requested address)

### ISSUE THREAD

**Issue by xMonologue** [pterodactyl/panel#4674]
### Current Behavior

When I try to launch most servers with the wireguard IP I setup for my pterodactyl servers in the panel, all game servers from all kinds do not start, in my case for the minecraft pocketmine server it just says:

```Error Event [6caf027f-8567-4765-b803-1c84d7e1c083]: environment/docker: failed to start container: Error response from daemon: driver failed programming external connectivity on endpoint 8fb78845-da42-4cef-8ae9-f8a080be9024 (293593a39cb42ed67d4043d5e2c584570546fd065e078dc5bf97e53d1ce673ee): Error starting userland proxy: listen tcp4 198.251.88.92:10002: bind: cannot assign requested address```

Here is my wings diagnostic. I do not know how to post logs for other types of wings services, if you need help let me know

Wings:
https://ptero.co/uhizeqasoh
Pterodactyl:
https://pteropaste.com/8ij51p

### Expected Behavior

The server should launch normally and works

### Steps to Reproduce

I personally use a wireguard tunnel from two different servers, my main machine is where pterodactyl is hosted but all data must come on the wireguard server before coming into the main server where pterodactyl is hosted, no ideas how to fix this anyones can help?

### Panel Version

All in the logs

### Wings Version

all in the logs

### Games and/or Eggs Affected

Minecraft Bedrock Pocket MIne

### Docker Image

https://github.com/parkervcp/eggs/tree/master/game_eggs/minecraft/bedrock/pocketmine_mp

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
I run wings behind wireguard perfectly fine.

Is wireguard running on the server you are trying to host from?

**Comment by xMonologue** [comment]
> I run wings behind wireguard perfectly fine.
> 
> Is wireguard running on the server you are trying to host from?

Its not, I run my wireguard server in a KVM (which is the IP of the main server too), I run pterodactyl on a separe server which is the main server where I host the game servers. But to login to the main server, you need the wireguard IP, This why im so confused why it does not works

**Comment by xMonologue** [comment]
Basically before the wireguard linking from the kvm to the main server (The main server is where I host pterodactyl) it was a different IP but now it use the KVM's IP so it should works but it doesn't apparently
