### ISSUE TITLE
Lacking information about install proccess

### ISSUE THREAD

**Issue by njalooo** [pterodactyl/panel#4678]
Hey, i've found it troublesome that there is no information about the install proccess of a server node at all. Please consider adding a small console window into the panel, where one can check on it and see if there are any errors, or if it just naturally takes hours for it to finish. Becuase for some reason a minecraft installation takes about 30minutes for me (if it happens at all), and there is no discernable reason why.

**Comment by devnote-dev** [comment]
If you are the server owner or an administrator on the panel then you can view the install progress from the server console. While it would make sense to have some kind of documentation on server installs, the fact of the matter is that install scripts (the thing actually running/setting things up) is specific to the egg it was created for, so if you want more specific information then just refer to the egg's install script.
