### ISSUE TITLE
Can't open file when <svg is inside the file

### ISSUE THREAD

**Issue by JRH-1997** [pterodactyl/panel#4679]
### Current Behavior

When someone adds <svg in a file, it is not possible to open it anymore from the file manager. 
That's correct handling when it's an SVG file, but not when it's a JS file for example. 

This will happen when someone uses the SVG directly inside the code.

### Expected Behavior

Be able to open the file from the file manager when it's not a .svg file. 

### Steps to Reproduce

Create a file
Add somewhere in the file <svg
Save it as test.js
return to the file manager
Try to open the file

### Panel Version

1.11.2

### Wings Version

1.11.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
Can reproduce, although I'm not so sure if this is a bug or intended functionality. Image MIME types are [disallowed here](https://github.com/pterodactyl/panel/blob/1.0-develop/resources/scripts/api/transformers.ts#L50), so there's a chance that this is preventing another issue, or it was an oversight.

**Comment by matthewpi** [comment]
> Can reproduce, although I'm not so sure if this is a bug or intended functionality. Image MIME types are [disallowed here](https://github.com/pterodactyl/panel/blob/1.0-develop/resources/scripts/api/transformers.ts#L50), so there's a chance that this is preventing another issue, or it was an oversight.

Binary image formats should be ignored, however text based formats such as SVG should be allowed.

**Comment by devnote-dev** [comment]
> Binary image formats should be ignored, however text based formats such as SVG should be allowed.

The `mimetype` package used by Wings identifies the file as `image/svg+xml` which isn't wrong, I guess the panel just needs an additional check for that type.

**Comment by JRH-1997** [comment]
The regex could be updated to: `/^image\/(?!svg\+xml)/`. It will exclude the `image/svg+xml` mime type
