### ISSUE TITLE
Friendly names for servers?

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#468]
Obviously just a feature request but one of my users has 6 Call of Duty servers that they run and they accidentally restarted one that was in use since they weren't sure which "ID" or "Server Name" it was using since they're obviously assigned by either Docker or by me and can't be changed. Would it be possible to implement a friendly name feature where users can add a name of their own to the servers? It may also be helpful to sort servers by this.

**Comment by DaneEveritt** [comment]
They should be giving you the server UUID or sUUID which can be found in the URL on the front-end. Take that and search for it in the Admin CP and it will return the specific server that it is, and in the admin CP when viewing a server it will show the Docker ID and associated user ID of the server, which can be used to locate the process and handle it as needed.
