### ISSUE TITLE
Panel cannot connect to my node correctly

### ISSUE THREAD

**Issue by HACKED210** [pterodactyl/panel#4682]
### Current Behavior

Error connecting to node! Check browser console for details.what the problem??

### Expected Behavior

P

### Steps to Reproduce

P

### Panel Version

1.11.3

### Wings Version

1.11.3

### Games and/or Eggs Affected

Nodejs

### Error Logs

```bash
Error connecting to node! Check browser console for details.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jelcoo** [comment]
Well maybe check your browser console?

**Comment by HACKED210** [comment]
> Well maybe check your browser console?

share the tutorial please

**Comment by HACKED210** [comment]
![Uploading Screenshot_2023-02-05-12-07-27-408_com.android.chrome.jpg…]()
