### ISSUE TITLE
Panel Upgrade - Database Migration issue (1.10.4 ->1.11.3)

### ISSUE THREAD

**Issue by nidark** [pterodactyl/panel#4683]
Hello,
I am trying to upgrade the panel from 1.10.4 to the latest version (1.11.3)
When I run `php artisan migrate --seed --force`

I get the following error:
```
root@vmi1065978:/var/www/pterodactyl# php artisan migrate --seed --force
 
   INFO  Running migrations.
 
  2021_07_17_211512_create_user_ssh_keys_table ............................................................................................ 3ms FAIL
 
In Connection.php line 760:
 
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'user_ssh_keys' already exists (SQL: create table `user_ssh_keys` (`id` int unsigned not null auto_increment primary key, `user_id` int unsigned not null, `name` varchar(191) not
  null, `fingerprint` varchar(191) not null, `public_key` text not null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
 
 
In Connection.php line 545:
 
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'user_ssh_keys' already exists
```
The discord bot proposed a fresh db, but this will delete all my data.
Any other options ?

Thank You!

PS: I restored from the VM snapshot for now.

**Comment by Boy132** [comment]
This is not a bug with the software. Please use the [discord](https://discord.gg/pterodactyl) for configuration specific issues.

**Comment by nidark** [comment]
If we know is not a bug , do we know when is happening and why / how can I solve it ?
PS: I will retry discord as well.

**Comment by nidark** [comment]
Closed. I deleted that table and 2 others and resume the upgrade.
