### ISSUE TITLE
Container wont start

### ISSUE THREAD

**Issue by siconic** [pterodactyl/panel#4684]
### Current Behavior

container@pterodactyl~ Server marked as starting...
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
crash_20230207003431_5.dmp[19]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230207003431_5.dmp

[----] Verifying installation...
[  0%] Downloading Update...
[  0%] Checking for available update...
crash_20230207003431_5.dmp[19]: Finished uploading minidump (out-of-process): success = no

crash_20230207003431_5.dmp[19]: error: libcurl.so: cannot open shared object file: No such file or directory

crash_20230207003431_5.dmp[19]: file ''/tmp/dumps/crash_20230207003431_5.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''

KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] !!! Fatal Error: Steamcmd needs to be online to update.   Please confirm your network connection and try again.
threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x58432af0/0x0xf7c26b'
:/home/container$ ./RustDedicated -batchmode +server.port 28005 +server.queryport 28009 +server.identity rust +rcon.port 28007 +rcon.web true +server.hostname "A Rust Server" +server.level "Procedural Map" +server.description "Powered by Pterodactyl" +server.url "http://pterodactyl.io" +server.headerimage "" +server.logoimage "" +server.maxplayers 40 +rcon.password "jamesdeanisaboss" +server.saveinterval 60 +app.port 28008 +server.worldsize "3000" +server.seed ""
Starting Rust...
/bin/sh: 1: ./RustDedicated: not found

Main game process exited with code 127
Waiting for RCON to come up...
Waiting for RCON to come up...
Waiting for RCON to come up...

### Expected Behavior

Expect download and start

### Steps to Reproduce

No idea

### Panel Version

1.11.3

### Wings Version

1.11.2

### Games and/or Eggs Affected

Rust

### Docker Image

quay.io/pterodactyl/core:rust

### Error Logs

```bash
https://ptero.co/dyqehulere
http://bin.ptdl.co/c1wex
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug with the software. Please use the [discord](https://discord.gg/pterodactyl) for configuration specific issues.

**Comment by trenutoo** [comment]
Your game installation has failed for one reason or another, view the install logs to find out why. Refer to the Discord support channels for support.

**Comment by siconic** [comment]
> This is not a bug with the software. Please use the [discord](https://discord.gg/pterodactyl) for configuration specific issues.

Things were working fine until earlier this week. Earlier this week two things happened:
1. Rust added a Query Game Port
2. You guys updated Wings and Ptero

Now, existing instances work fine, but new ones do not. Not sure what the heck is going on, and I tried discord, nothing on my errors. From what I can gather you are right, its failing to install. But at what part? The initial, or the secondary?

**Comment by trenutoo** [comment]
Neither of these has anything to do with your game instance missing the necessary files. Use the #custom-game-hep support channel if you are unable to understand your logs.

Install logs are located in `/var/log/pterodactyl/install` by default.

The command below will fetch the most recent install logs

```tail -n 1000 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc pteropaste.com 99```
