### ISSUE TITLE
Fresh wings install fails to run any server

### ISSUE THREAD

**Issue by AndyIsHereBoi** [pterodactyl/panel#4687]
### Current Behavior

I just installed wings onto my existing panel and it all was running fine until i tried to start any server and get this error in the console: 
```
container@pterodactyl~ Error Event [b5d4e900-11b4-4e57-95c0-a62479ad9905]: environment/docker: failed to start container: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown
```

### Expected Behavior

Server should start and run as usual

### Steps to Reproduce

Install wings, start any server

### Panel Version

1.11.3

### Wings Version

1.11.4

### Games and/or Eggs Affected

all

### Error Logs

```bash
https://ptero.co/iverarymek
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
What is your Docker version?

**Comment by parkervcp** [comment]
You may need to install apparmor

**Comment by AndyIsHereBoi** [comment]
> What is your Docker version?
Docker version 23.0.1, build a5ee5b1

**Comment by AndyIsHereBoi** [comment]
> You may need to install apparmor

tried these:
sudo apt install apparmor-profiles apparmor
didnt work, same error

**Comment by AndyIsHereBoi** [comment]
im ganna try to reinstall the dedicated server and see if that works... is there any known issues with ubuntu 20.04 base from hetzner?

**Comment by Boy132** [comment]
This is not a bug in the software, please use the Discord for problems with your configuration.
Make sure apparmor is installed and [configured for docker](https://docs.docker.com/engine/security/apparmor/).

**Comment by AndyIsHereBoi** [comment]
had to add systemd.unified_cgroup_hierarchy=0 to the grub linux default
