### ISSUE TITLE
Add mount support when installing server

### ISSUE THREAD

**Issue by statebyte** [pterodactyl/panel#4688]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

At the moment, the mount point is only available when the server is started (egg container). 
And in the installation container (ghcr.io/pterodactyl/installers:debian) there are no mounted folders.

### Describe the solution you'd like.

it would be nice to add this feature

**Comment by trenutoo** [comment]
Duplicate of #4520
