### ISSUE TITLE
DNS settings in *_installer container are ignore

### ISSUE THREAD

**Issue by BenasPaulikas** [pterodactyl/panel#4689]
### Current Behavior

In docker config I changed DNS to cloudflare IP's
![image](https://user-images.githubusercontent.com/6473565/218311969-1a0fbae3-591b-4e14-9870-5a30dec1801d.png)

In installation script I do
```
cat /etc/resolv.conf
```
It returns
```
nameserver 127.0.0.11
```

### Expected Behavior

Correct DNS servers would be used/ ` /etc/resolv.conf` would return 1.1.1.1

It's strange that DNS is being set here 
https://github.com/pterodactyl/wings/blob/develop/server/install.go#L454
But it's not being used.

### Steps to Reproduce

Change docker network config
```
    dns:
    - 1.1.1.1
    - 1.0.0.1
```

In egg installation do
```
cat /etc/resolv.conf
```

### Panel Version

1.11.3

### Wings Version

1.11.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by MaximumWoahverdrive** [comment]
Did you remove the docker network and restart wings on the node as documented? https://pterodactyl.io/wings/1.0/configuration.html#example-of-usage-2

The process to change DNS for the containers is:

1. Stop all pterodactyl managed containers running on the node (through the panel)
2. Stop wings on the node `systemctl stop wings`
3. Edit the network config in /etc/pterodactyl/config.yml
4. Remove the network on the node `docker network rm pterodactyl_nw` (if you get an error stating "[...] has active endpoints" there are still containers with that network running)
5. Start wings `systemctl start wings`

resolv.conf containing `nameserver 127.0.0.11` is expected
