### ISSUE TITLE
Can't delete server 

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#4690]
### Current Behavior

<img width="678" alt="image" src="https://user-images.githubusercontent.com/28255085/218316325-f59fb429-d19b-4d4b-b5fe-f8117eb85b9d.png">

### Expected Behavior

I can delete server

### Steps to Reproduce

1. Go to Admin
2. https://panel.test.com/admin/servers/2
3. Delete server

### Panel Version

v1.11.3

### Wings Version

v1.11.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
Please include your error logs.

**Comment by Boy132** [comment]
You are on v2/ develop branch and not 1.11.3.
v2 is still work in progress and you should use 1.x until it's done.

**Comment by zKoz210** [comment]
@Boy132 thx. my bad
