### ISSUE TITLE
Server Freezing / Unresponsive to input

### ISSUE THREAD

**Issue by Lorenc95** [pterodactyl/panel#4693]
When running the Rust egg with some plugins, the server after a while (Randomly it seems)
Stops being responsive and kicks out every member, when i then try to restart the server, it wont respond either, i'll have to kill the power and then force a restart on the "Node".

when this all happens i can see the traffic on the node go crazy, goes from megabytes to gigabytes.
I've been trying everything and i just can't seem to find the issue.
please ask for additional information so i can share.

**Comment by Lorenc95** [comment]
This is a screenshot of the server going in to crashed state.

No error logging, but user ips etc so i blurred it.
As u can see theres no error however everyone just loses connection, and the traffic goes insane.
https://i.imgur.com/hNDQX2M.png

**Comment by Sharktheone** [comment]
I don't think this is an issue with the pterodactyl or docker. As you can see the logs, an entity is spawning below -500 and this is causing this error. I've found an post on umod, maybe this helps you.  (They say it could be an error with a custom map / a plugin on the server) For me it also makes no sense  it could be Pterodactyl. So i think it is a a problem on the Rust side.

https://umod.org/community/rust/43282-invalid-position-chicken-corpse

**Comment by Lorenc95** [comment]
even without the entity or ANY plugins loaded this still occurs, seems like daemon is getting stuck.,
The server will stop displaying any updates except for input values from console I.e Scheduled jobs will print to it, but the server is hanging.

the only way to fix the issue is to kill the server instance and then restart wings because killing the server instance gets stuck. 

This issue seems to occur every hour and is getting quite frustrating to deal with.
