### ISSUE TITLE
Assign ip node

### ISSUE THREAD

**Issue by nsn95** [pterodactyl/panel#4694]
### Current Behavior

I have a dedicated server with 2 ips, if I assign to ip 2 for another csgo server, after starting the server to public ip, it shows me the main ip to dedicated, you can't connect to the added ip by me.

I mention that the 2nd ip is visible on dedicated, only that I cannot create game servers on it.

### Expected Behavior

-

### Steps to Reproduce

-

### Panel Version

1.11.2

### Wings Version

1.11.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
You can check this box in the panel for the egg

![image](https://user-images.githubusercontent.com/1207679/218891048-c901afc4-31f9-4350-a1d6-5dd56433c261.png)

**Comment by nsn95** [comment]
> You can check this box in the panel for the egg
> 
> ![image](https://user-images.githubusercontent.com/1207679/218891048-c901afc4-31f9-4350-a1d6-5dd56433c261.png)

Thanks its working.
