### ISSUE TITLE
Forcibly deleting a server where the node is down results in a 500 error

### ISSUE THREAD

**Issue by LinusOP** [pterodactyl/panel#4697]
### Current Behavior

If you have a node where wings is down/stopped (in our case the entire physical box is gone) and you try to forcibly delete a server on it, you end up with a 500 server error.

### Expected Behavior

I would expect that since I am using the force deletion and not the safe delete, the panel will simply continue and delete it. In our case so that we can then delete the node from the panel.

### Steps to Reproduce

1. Create a server on a node
2. Stop wings/Take the node down
3. Try to forcibly delete a server

### Panel Version

1.11.3

### Wings Version

N/A

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
None generated
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jcodeerd** [comment]
Maybe there should be a way to also forcibly delete the server from the database (when using the forcibly delete option)

**Comment by matthewpi** [comment]
> Maybe there should be a way to also forcibly delete the server from the database (when using the forcibly delete option)

That is what the forcibly delete option is designed to do, but it also sends a request to the node and should just ignore the error, which it is not doing here.

---

Are you sure that there are no error logs?  Almost always a 500 error logs something unless we respond with it manually which I don't believe we are in this case.

**Comment by LinusOP** [comment]
> Are you sure that there are no error logs? Almost always a 500 error logs something unless we respond with it manually which I don't believe we are in this case.

This is what I have in my log folder, so nothing from 2023
![bild](https://user-images.githubusercontent.com/32105232/219788460-85385b5b-c720-45f3-874a-bafda5e1ea39.png)

PS. Running this in docker, have the log folder mounted to that location, also attached to the container directly and went into `/app/storage/logs` which does indeed show the same files. Similarly the symlinked `/var/log/panel/logs` folder is empty in the container as well.

**Comment by Boy132** [comment]
Can't reproduce that. Like Matthew said a 500 error should normally create a log, so this might be a problem with your setup.

**Comment by LinusOP** [comment]
> Can't reproduce that. Like Matthew said a 500 error should normally create a log, so this might be a problem with your setup.

Hmmm, not sure what the problem would be with my setup in that case, it's the standard ptero image and has been working without issues or weirdness up until this point. Got any idea of what I can look for that might be causing this? Alternatively what might be causing me not to get logs (odd that I have some tho)

**Comment by Boy132** [comment]
> Hmmm, not sure what the problem would be with my setup in that case, it's the standard ptero image and has been working without issues or weirdness up until this point. Got any idea of what I can look for that might be causing this? Alternatively what might be causing me not to get logs (odd that I have some tho)

I don't know if that applies for dockerized panel too but for a non-dockerized panel it normally means a problem with file permissions/ ownership when no log is created.

Also, setting the `APP_DEBUG` env variable to true could give more information.

**Comment by LinusOP** [comment]
> I don't know if that applies for dockerized panel too but for a non-dockerized panel it normally means a problem with file permissions/ ownership when no log is created.
> 
> Also, setting the `APP_DEBUG` env variable to true could give more information.

Ahh, the `APP_DEBUG` env variable came to the rescue, yea it's a permission error when writing the error log. Which is probably why the deletion fails as in force mode it still tries to log the exceptions, which ofc will be raised considering the node is down. Now to figuring out what's wrong with my logs, but that's definitely a me issue :P Thanks for the help!
