### ISSUE TITLE
Allocation delete

### ISSUE THREAD

**Issue by Bubbelwubbel** [pterodactyl/panel#4698]
### Current Behavior

If I create an allocation via the admin area and then want to delete it, this does not work.

### Expected Behavior

That I can remove the 2 port or the allocation

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/65186341/219977784-95290672-34f5-48aa-a9f6-4b6554c7b410.png)

### Panel Version

1.11.3

### Wings Version

1.11.2

### Games and/or Eggs Affected

/

### Docker Image

/

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Bubbelwubbel** [comment]
And when I want to use the port, it comes up with the:
```shell
Error Event [5f321c0c-bd47-4739-94eb-f159cdc4e10b]: environment/docker: failed to start container: Error response from daemon: driver failed programming external connectivity on endpoint 3607c2fa-729d-49e8-8b00-9ab7795701da (b8edbc3fca4c83a9556a8d6c6842446b69fdc3c34e858714c2edaba3a700c55a): Bind for IP:19132 failed: port is already allocated
```

**Comment by devnote-dev** [comment]
This is not a bug, it is caused by https://github.com/pterodactyl/panel/issues/3703. Reverting this would conflict with the mentioned issue, so I think that there should be a better error message to clarify this.
