### ISSUE TITLE
Email sending not functional: 'Expected response code "250" but got code "501"'

### ISSUE THREAD

**Issue by Aterfax** [pterodactyl/panel#4700]
### Current Behavior

Sending email / a test email fails with the following error message:

```
Whoops!

An error occurred while attempting to test mail settings: Expected response code "250" but got code "501", with message "501 HELO requires domain/address - see RFC-2821 4.1.1.1".
```

![image](https://user-images.githubusercontent.com/8648058/219983068-2972f140-017b-44a8-8411-7ffc988494db.png)

This is despite setting the SERVER_NAME env var as per https://github.com/pterodactyl/panel/pull/3110

This was also not fixed by forcing the docker container's hostname to a hostname with `--hostname myhost.domain.com` or fudging with https://github.com/pterodactyl/panel/issues/3216 adding the line as per.

Image: ccarney16/pterodactyl-panel:latest

### Expected Behavior

Test email / normal emails should send correctly.

### Steps to Reproduce

Use the Docker version of pteropanel (ccarney16/pterodactyl-panel:latest) and attempt to send an email via an account on a [Poste2 ](https://poste.io/)email server.

### Panel Version

v1.11.3

### Wings Version

v1.11.4

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
I found nothing relevant in the logs with debug on or off unfortunately.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
The env variable is now called `MAIL_EHLO_DOMAIN` afaik.

Side note: `ccarney16/pterodactyl-panel:latest` is a third party image and _not_ the official one.

**Comment by Aterfax** [comment]
Yep, setting `MAIL_EHLO_DOMAIN` resolved this. Might be worth the documentation having a panel page that includes the current .env.example / all env vars as I suspect I was looking at older copies locally / at the online docs and drawing a blank.

**Comment by Boy132** [comment]
> Might be worth the documentation having a panel page that includes the current .env.example / all env vars 

FYI: https://github.com/pterodactyl/documentation/issues/471 (& https://github.com/pterodactyl/documentation/pull/492)
