### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by FlanZCode** [pterodactyl/panel#4708]
### Current Behavior

When I try to add an egg on my pterodactyl panel I simply get a 500 error, I only get this error on my phone not on my computer. On my phone I tested on all my internet browsers, Google, Chrome and Opera and none worked :/

### Expected Behavior

There's not much to say other than I wanted my egg to work

### Steps to Reproduce

Go in Admin Panel > Nets and import an egg

### Panel Version

1.11.3

### Wings Version

1.11.2

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by FlanZCode** [comment]
![Screenshot_20230225_012729_Opera GX](https://user-images.githubusercontent.com/108761778/221325009-d01ce07d-54b8-48ce-b282-ab4ea0c2c5a8.jpg)
![Screenshot_20230225_014457_Chrome.jpg](https://user-images.githubusercontent.com/108761778/221326167-4a582900-b18c-4df9-afd0-09f6145f7fef.jpg)

**Comment by FlanZCode** [comment]
I also tried the "webtop" mode, the mode to see as if it were a computer, on the phone, I'm not sure it's called the "webtop" in English at least not it is like that that it translated it to me (I speak basic French)

**Comment by EnzoGH0001** [comment]
"webtop" not "desktop site"

**Comment by EnzoGH0001** [comment]
"webtop" not "site desktop"

**Comment by trenutoo** [comment]
You must provide the error logs from the panel as requested in the issue template. 500 error by itself only informs us that something went wrong.
