### ISSUE TITLE
Regular consistent CPU utilisation spikes by Wings process

### ISSUE THREAD

**Issue by Undeadllama** [pterodactyl/panel#4712]
### Current Behavior

I've noticed regular bursts of CPU utilisation by the wings process (v1.11.4 but also observed on other 1.11.x versions) when in theory nothing should be happening on the node other than running a few low-load minecraft servers running in the background.

Most of the time the wings process is very idle using <0.5 %CPU, however every 10-15 mins it'll jump up to ~80-100 %CPU and sit there chewing up CPU cycles for 2-3 mins before dropping back down again for a while.
Even with debug logging enabled in /etc/pterodactyl/config.yml (or by launching with --debug) I don't see anything of interest in the wings.log file during the CPU spikes.

Found the following similar github issue however isn't an exact match as in that issue report the %CPU keeps increasing until wings is restarted and doesn't return to <1% on its own.
https://github.com/pterodactyl/panel/issues/3911

Yesterday I performed OS patching and updated the panel + wings to the latest versions but observed no change in behaviour.
As can be seen from the 'top' output attached, the wings process has used more CPU time over the last ~24 hours than an MC server that usually has 5-10 players on it.

![image](https://user-images.githubusercontent.com/3908975/221652744-384ecdec-8010-47da-a0ec-1f21e7f89fa2.png)

Seems excessive, is this normal background tasks/processing?
Any clue what the wings process is doing during this time, is there any additional logging I can enable to investigate further?
I've pulled out some pprof files from the wings process but don't really know what I'm looking at when it comes down to syscalls - in not a go programmer.

### Expected Behavior

Would realistically expect wings process that should be idle to not use more CPU time than game servers.

### Steps to Reproduce

Simply start wings service and observe top output, every 10-15 mins there will be a burst of CPU utilisation pegged at ~80-100 %CPU by the wings process for 2-3 mins.
After that CPU utilisation of wings process will drop back down to <0.5 %CPU again for another 10-15 mins when the issue repeats.

### Panel Version

1.11.3

### Wings Version

1.11.4

### Games and/or Eggs Affected

n/a

### Docker Image

n/a

### Error Logs

```bash
https://ptero.co/apypusepos

pprof files attached below.

Happy to collect and provide anything more that may be helpful.
```

[pprof.zip](https://github.com/pterodactyl/panel/files/10842904/pprof.zip)
[cpu.pprof.pdf](https://github.com/pterodactyl/panel/files/10842905/cpu.pprof.pdf)
[goroutines.pprof.pdf](https://github.com/pterodactyl/panel/files/10842906/goroutines.pprof.pdf)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment]
Assuming the `cpu.pprof.pdf` you attached ran for long enough during the CPU usage spike, the issue is definitely related to the directory size calculator.  For reference, in order to calculate server disk usage we have to recursively walk and add up the size of all the files.  I hate this design but it's seems to be the only way to actually calculate disk usage, however we can try to optimize it.

I'd recommend changing `system.disk_check_interval` to either a higher value (the problem will likely persist but it will occur less often) or to `0` if you want to fully disable it.

**Comment by Undeadllama** [comment]
Interesting, so it's effectively doing the equivalent of recursive 'du -s' against /var/lib/pterodactyl/* periodically?

That did indeed do the the trick, many thanks for the suggestion.
Have temporarily set the disk check interval to 0 for now just to test, haven't seen a reoccurrence since and wings %CPU is consistently staying below 0.5 utilisation.

Will experiment with setting the disk check interval to a higher value than default over the next few days to find some middle ground that I'm happy with.
Presumably its a tradeoff as to how quickly/frequently the disk usage reported for each game server in the Ptero panel is updated.

Thanks again for the very quick response and explanation!
