### ISSUE TITLE
update admin ui

### ISSUE THREAD

**Issue by BlackRandomCraft** [pterodactyl/panel#4716]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

it would be good if the administrative interface was updated in the style of the client interface

### Describe the solution you'd like.

I would like to see an interface similar to http://pterodactyl/account/

like the admin interface has not changed globally since version 0.x

**Comment by BlackRandomCraft** [comment]
It would also be cool to see automatic backup of servers and databases to (S)FTP servers and change captcha services

**Comment by Jcodeerd** [comment]
Sorry what, this likely isnt gonna happen soon (if not already in V2). for backups you'd be on your own doing that via the host OS.

**Comment by BlackRandomCraft** [comment]
okay..closed
