### ISSUE TITLE
Allow Wings to run as a non-root user.

### ISSUE THREAD

**Issue by ZacharyDuBois** [pterodactyl/panel#4718]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Allow the Wings daemon to run as a non-root user. I have attempted this but it appears it tried to make files throughout the system which just causes non-stop permissions issues. It would be nice to have the daemon locked down and not running as room.

### Describe the solution you'd like.

Allow running wings as an unprivileged system user. It is possible to control Docker not being root (utilizing the `docker` system group).

Since wings is trying to make a bunch of files on initial start, it might be worth it to make that a "setup" command you initially run as a privileged user and the daemon itself can run as a unprivileged user.

It would also be possible to package wings to make all the setup and management handled by the package manager.

**Comment by ZacharyDuBois** [comment]
Disregard! It wasn't documented that it automatically creates a system user. Sorry for bugging!

**Comment by matthewpi** [comment]
Wings itself runs as root regardless, I have added some recent changes in preparation for a full rootless setup with Podman though.

Part of the reason why Wings runs as root is to always ensure file ownership is set correctly, however it should definitely be supported to run as a non-root user even if the container runtime runs as root.

Containers are always ran as an unprivileged user regardless, only Wings and the container runtime themselves will ever be ran as root.
