### ISSUE TITLE
can't upload eggs on ipad

### ISSUE THREAD

**Issue by Jcodeerd** [pterodactyl/panel#4720]
### Current Behavior

You can't select any (json) file to upload from ipad to the nests/egg system.

### Expected Behavior

Being able to upload json egg files to the nests/egg system.

### Steps to Reproduce

Download any egg json file,
Attempt to upload; all files are darkened out, which means you can't select any to upload.

- happens in both safari and firefox
- tried with the file on iCloud downloads and regular local downloads folder
- panel 1.11.3
- ipadOS 16.3.1
![image](https://media.discordapp.net/attachments/376449434654998539/1082804605148213248/image.png)

### Panel Version

1.11.3

### Wings Version

n/a

### Games and/or Eggs Affected

all

### Docker Image

n/a

### Error Logs

```bash
n/a
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RooRay** [comment]
Can confirm that I also experience this issue on a different iPad and different installation of Pterodactyl, also on iOS 16.3.1
