### ISSUE TITLE
Missing required fields for create/update schedule

### ISSUE THREAD

**Issue by devnote-dev** [pterodactyl/panel#4721]
### Current Behavior

Creating and/or updating a schedule via the API can cause a 500 error response to be returned if the `month` field is missing from the request body (this may also be reproduceable with the `only_when_online` field). This is because neither of the fields are included in the request body validation rules.

### Expected Behavior

The `month` and `only_when_online` fields for creating/updating schedules should be required for the request validation rules.

### Steps to Reproduce

Make a POST request to `/api/client/servers/<id>/schedules` with the `month` field missing from the body.

### Panel Version

1.11.3

### Wings Version

1.11.4

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
Unavailable
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by cdevoogd** [comment]
I just ran into this as well when working with the API on v1.11.3 of the panel and was extremely confused. I wasn't able to find any logs from the panel explaining the issue, but luckily found this issue and added `month` and `only_when_online` which fixed the errors for me.

Side note: Why is the panel returning 500 instead of 400?

**Comment by devnote-dev** [comment]
The main culprit here is the `month` field which cannot be `null` according to the schedule database schema. However, because the field isn't checked by request validation it will become `null` when missing, which causes a database exception. The reason why `only_when_online` doesn't do this is because the value is cast to a boolean in all cases, meaning that `null` gets cast to `false`.

https://github.com/pterodactyl/panel/blob/d3c65685223633ec250db5939843cb0542ad5ca4/app/Http/Controllers/Api/Client/Servers/ScheduleController.php#L109-L114
