### ISSUE TITLE
Creating a file with the same name as an existing file will overwrite it

### ISSUE THREAD

**Issue by Jelcoo** [pterodactyl/panel#4722]
### Current Behavior

You can overwrite files if you name them as an existing file.

### Expected Behavior

File should not be overwritten, instead thorw error 403. Adding a dialog asking if you want to overwrite it would also be a viable option, although not preferred by me.

### Steps to Reproduce

Create a file called text.txt with content test.
Create a new file called text.txt with contect oops.
You will see the text.txt file has been replaced with your new file.

### Panel Version

1.11.3

### Wings Version

1.11.5

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
I don't see any bug/issue here? This seems more like a feature request which would require either a change to the existing API endpoint to accommodate for this, or a new endpoint with specific "create-only" functionality. Either way, there's no need for this change as it will just complicate things. At the very most, having a modal (as you've also suggested) to prompt the user before overwriting may be useful.
