### ISSUE TITLE
Ark server not starting?

### ISSUE THREAD

**Issue by StrafeSmurf01** [pterodactyl/panel#4725]
Hello,

Yesterday i installed a ark server. But the server say the same thing over and over again.
Does anyknow this issue?
![image](https://user-images.githubusercontent.com/127998410/225453250-48ab4fd8-5d1d-4cb3-93de-2a17fab78fdc.png)
I let the server on for around 8 hours but nothing happend.
![Knipsel](https://user-images.githubusercontent.com/127998410/225453386-fd8a69a5-8017-411f-84a7-7de65fb59822.PNG)
I used the ports above. Pterodactyl is installed on a ubuntu dekstop. The ports for the ark server are allowed on the firewall.

**Comment by parkervcp** [comment]
You need to wait longer for the server to start.

**Comment by trenutoo** [comment]
Your install has failed as you are missing the ark binary. Check your install logs to see why

**Comment by StrafeSmurf01** [comment]
> Your install has failed as you are missing the ark binary. Check your install logs to see why
I found this in a log file. Is it familiar?
![image](https://user-images.githubusercontent.com/127998410/225645120-607842d7-e844-4b70-b93f-c68176b1a8a4.png)

**Comment by StrafeSmurf01** [comment]
> You need to wait longer for the server to start.

I dont think i have to wait longer?
![image](https://user-images.githubusercontent.com/127998410/225645409-1c85e0a9-0002-46d5-a92d-52ef0f23fd86.png)

**Comment by trenutoo** [comment]
> > I found this in a log file. Is it familiar?

Install logs of the container by default are located in `/var/log/pterodactyl/install/`. Reinstall the server and use the command below to get the latest install logs.

```
tail -n 1000 $(ls -Alrt /var/log/pterodactyl/install/*.log | tail -1 | sed 's/  */ /g' | cut -s -d' ' -f9) | nc pteropaste.com 99
```

**Comment by StrafeSmurf01** [comment]
> 

The logs say this.
<img width="499" alt="image" src="https://user-images.githubusercontent.com/127998410/225904811-1081c540-bd40-4c8e-94eb-8433dedb1701.png">

**Comment by trenutoo** [comment]
You don't have enough disk space to install the game.

**Comment by StrafeSmurf01** [comment]
> You don't have enough disk space to install the game.

I upgraded the disk space and ram.
<img width="230" alt="image" src="https://user-images.githubusercontent.com/127998410/225910558-68b1d1ee-f49d-4818-8ef9-fa2262cc1d9b.png">

But i got the same error.

**Comment by trenutoo** [comment]
The error states there's not enough disk space. Check your system partitions and use Discord for configuration issues as this is not a bug in the Pterodactyl software

**Comment by StrafeSmurf01** [comment]
> 

Okay, thanks for your help!

**Comment by taazo** [comment]
> You need to wait longer for the server to start.

yeah no..... waited 19 hours now so i dont think thats it

**Comment by gOOvER** [comment]
> > You need to wait longer for the server to start.
> 
> yeah no..... waited 19 hours now so i dont think thats it

Then Server crashed. how many RAM is allocated?

**Comment by taazo** [comment]
> > > You need to wait longer for the server to start.
> > 
> > 
> > yeah no..... waited 19 hours now so i dont think thats it
> 
> Then Server crashed. how many RAM is allocated?

Still says ''starting'' and i have 8gb for a little ark server with normaly uses 4/5gb... no mods

**Comment by Arawwsi** [comment]
![IMG-20240322-WA0623](https://github.com/pterodactyl/panel/assets/164519492/79c614a1-12bc-44f3-9c3a-8bba92fcb8f5)

Why the cpu not load

**Comment by Arawwsi** [comment]
![IMG-20240322-WA0530](https://github.com/pterodactyl/panel/assets/164519492/bec8b75e-75e3-4abf-88e4-0bb1de461800)

Why cpu not load

**Comment by Boy132** [comment]
> ![IMG-20240322-WA0530](https://private-user-images.githubusercontent.com/164519492/316046146-bec8b75e-75e3-4abf-88e4-0bb1de461800.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTc4OTksIm5iZiI6MTcxMTExNzU5OSwicGF0aCI6Ii8xNjQ1MTk0OTIvMzE2MDQ2MTQ2LWJlYzhiNzVlLTc1ZTMtNGFiZi04OGU0LTBiYjFkZTQ2MTgwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNDI2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzIzMmE1N2Q4OWY4ODE0NGM4MzcwMmEwOGYxMjU0NjI2MTU5YmM5NzRhZDQzN2I0NjlhOWQwMzgxMzY5NTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w8feief1nzrEOJUPT956j8sQjITWhom8t0Ude21M6Pc)
> 
> Why cpu not load

Make sure you didn't enable cpu pinning by accident. (the field needs to be empty and _not_ set to `0`)
For further help please visit the [Discord](https://discord.gg/pterodactyl).
