### ISSUE TITLE
[Feature] Button for Updating the Minecraft Server Jar to Latest / Specified Version without Reinstall

### ISSUE THREAD

**Issue by Jayryn** [pterodactyl/panel#4726]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I am updating my mc server manually every once in a while by going to the publisher, downloading it, uploading it and having to rename it, which I find extremely inconvenient. This is why I thought of a better way to do it. PurpurMC for instance offers an api where you can download the latest published version (also for specific mc versions such as 1.19.3) which can already grab the jar that is needed. 

For these reasons, a more convenient option inside the panel would be quite useful for less techy / rather lazy people and would  be even some kind of necessary I would say. Having to reinstall in order to get a newer version without having to leave the panel is a bit counterproductive for server operators. 

### Describe the solution you'd like.

What I am suggesting is a simple button inside the startup tab of the panel to update the server jar to the specified / latest version without having to reinstall the server in order to do it in the panel based on the specified startup variables.

### Additional context to this request.

If any additional context is needed, please let me know by a ping in this thread.

**Comment by QuintenQVD0** [comment]
Not all hosted servers are minecraft. The install script uses the api to get the latest build of your selected version and downloading it. So thay button is useless as it would just rerun the install script. You should never manual upload a .jar. just hit reinstall and it will get the latest build.

**Comment by Boy132** [comment]
What you suggest is exactly what the "Reinstall server" button and startup variables do, like Quinten already mentioned.

**Comment by Doc94** [comment]
also you can use the API for make reinstall in specific changes... also its not recommended update to latest with not checks.. (if consider the latest can be update from 1.19.3 to 1.19.4)

**Comment by expxx** [comment]
There are plenty of eggs out there that do what you're looking for. Well, sorta. I'm actively developing one now.
