### ISSUE TITLE
Schedules ignore onlyWhenOnline flag

### ISSUE THREAD

**Issue by austinv900** [pterodactyl/panel#4727]
### Current Behavior

Schedules with the checkbox 'ONLY WHEN SERVER IS ONLINE' set to false will run regardless of the server being in a **Offline** state.

### Expected Behavior

Schedules with the checkbox 'ONLY WHEN SERVER IS ONLINE' set to false should only run when the server is in a **Offline** state

### Steps to Reproduce

Create a schedule that runs at any interval with the 'ONLY WHEN SERVER IS ONLINE' set to false.

Start the server and wait for the server to enter a **Running** state

Enable the schedule

Schedule will execute at the set interval.

### Panel Version

1.11.3

### Wings Version

1.11.4

### Games and/or Eggs Affected

Rust

### Docker Image

ghcr.io/pterodactyl/installers:debian

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by mason-rogers** [comment]
Unticking "Only when server is online" doesn't necessarily mean it will now only run when server is offline - it means it will run regardless of power state, the feature is working as expected
