### ISSUE TITLE
about:blank#blocked

### ISSUE THREAD

**Issue by BreadCatto** [pterodactyl/panel#4728]
### Current Behavior

whenever I click a button on admin page it redirects me to about:blank#blocked

### Expected Behavior

it should open the requested tab

### Steps to Reproduce

idk, that's why I'm here 

### Panel Version

1.11.3

### Wings Version

can't install that

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
Your browser redirects to about:blank#blocked when it's asked to load something it considers a security issue.
You should check your APP_URL to ensure it's correct, as well as check your browsers dev tools to find out where it's being redirected to, as well as why your browser doesn't like it.

**Comment by GalaxyToy** [comment]
_@GalaxyToy🇧🇩###_ 

> __

Kids toys****__
