### ISSUE TITLE
How to disable activity logs for a server? My Activity Logs DB grew to 282gb

### ISSUE THREAD

**Issue by EliteScouter** [pterodactyl/panel#4729]
Is there a way to disable Activity Logs on a single server (At this point I would be ok with disabling it completely).

I noticed my Pterodactyl server started going out of space, thought maybe backups were not writing to my SMB share but instead started writing to the local drive. Nope, after doing some investigation, I found my DB file Activity_Logs to be 282GB! I quickly logged into the DB and deleted everything from it. Now it's starting to climb up again.

I have a few Minecraft servers and every time a user logs in, it makes a .bak file that it then deletes next time user logs in and replaces it. However, that is all being logged and I am now showing this even after clearing the whole log the night before. 

Showing 137450 to 137475 of 137516 results.

Is there a way to put in "Keep activity logs for X amount of days", or just disable it for 1 server. If that's not possible, can I disable activity logs period. If neither of those are possible, I might just have to script it to run daily and purge the activity logs database.

**Comment by Jcodeerd** [comment]
282GB?! Something's majorly wrong. 

 The default is every 90 days iirc but can be changed in /var/www/pterodactyl/.env with the Environment Variable `APP_ACTIVITY_PRUNE_DAYS`.

**Comment by Jelcoo** [comment]
You can prune the activity logs database every x days by setting `APP_ACTIVITY_PRUNE_DAYS` in your env. This is defaulted to 90 days.

**Comment by EliteScouter** [comment]
Thank you! I will check that out. Now that you mention it, there is definitely something wrong and it seems like it's an issue with 1 server so I will just re-create that one and move all the data over to it, When I posted this, it was up to 137,516 results, I am now up to 139,193

**Comment by PatchedNotFixed** [comment]
I have also stared having this issue out of nowhere, after being reset table is 202G with after two weeks of use. I had to reset it once it had filled up my MySQL server with a table that was 494GB !. 

(Link too pterodactyl discord, of when this happend to me) https://discord.com/channels/122900397965705216/658550982975946762/1092093652228112464

the "300mb ish to 490GB over 1 hour" is no joke.

**Comment by funnycubeguy** [comment]
> I have also stared having this issue out of nowhere, after being reset table is 202G with after two weeks of use. I had to reset it once it had filled up my MySQL server with a table that was 494GB !.
> 
> (Link too pterodactyl discord, of when this happend to me) https://discord.com/channels/122900397965705216/658550982975946762/1092093652228112464
> 
> the "300mb ish to 490GB over 1 hour" is no joke.

I just experienced this exact issue...

**Comment by matthewpi** [comment]
As previously stated you can use the `APP_ACTIVITY_PRUNE_DAYS` to control the retention of activity logs, outside of that there are no built-in controls for changing per-server retention, max size of entries, etc.

Please make sure that your queue worker (`systemctl status pteroq.service`) is running, and that your crontab is configured to queue scheduled tasks (https://pterodactyl.io/panel/1.0/getting_started.html#crontab-configuration)
