### ISSUE TITLE
Auto-deployment bug

### ISSUE THREAD

**Issue by cate776** [Pterodactyl/Panel#473]
I got this message when adding a server when there were no allocations added on the node:
An unhandled exception occured while attemping to add this server. Please try again.

Stack trace:
https://pastebin.com/raw/GEeABTUt

**Comment by DaneEveritt** [comment]
Your stack trace has disappeared, can you please provide a new one otherwise I will have to close this bug report.

**Comment by schrej** [comment]
Please use https://hastebin.com so it doesn't disappear.

**Comment by cate776** [comment]
Sorry, I don't have it anymore. 

I'm sure it could be reproduced though.

Regards.

---- On Sun, 18 Jun 2017 10:48:59 +0200 notifications@github.com wrote ----

Please use https://hastebin.com so it doesn't disappear.
