### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#4735]
### Current Behavior

Good morning,
My machine is hosted in France and I live in France so UTC+2 At home when it is 8 p.m. on my pterodactyl panel it is 6 p.m. And when I look for how to change the time so that it can show me the correct time, I can't find anything

### Expected Behavior

Let it set the right time for where I live

### Steps to Reproduce

Normally install Pterodactyl and make a Minecraft server

### Panel Version

1.10.4

### Wings Version

1.7.2

### Games and/or Eggs Affected

Minecraft (paper)

### Docker Image

ghrc.io/pterodactul/yolks:java_17

### Error Logs

```bash
https://ptero.co/onelusohat
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jcodeerd** [comment]
Its in the wings configuration file

**Comment by FoksVHox** [comment]
This doesn't seem like an issue with the software, rather an issue with the configuration of it. 

Please make sure that you've set the `APP_TIMEZONE` to `Europe/Paris` in your `.env` file of the panel. To set the time of Wings, you need to set the `Timezone`, which defaults to UTC, if wings can't detect a timezone.

**Comment by ghost** [comment]
![Capture](https://user-images.githubusercontent.com/103952963/227902845-c287948a-856c-4e18-883c-071917416eb9.PNG)

I checked in the .env file that I had correctly put Europe/Paris and it is well put, I am attaching the screenshot of what I see
Maybe there are other files to edit?

**Comment by Sharktheone** [comment]
I think the issue you describe has nothing to to with the panel configuration. As [Jcodeerd](https://github.com/Jcodeerd) wrote already you have to change your Timezone in your wings configuration and not in the panel, when your servers (logging in things like a minecraft server) are showing the wrong time. So you need to change the `timezone` option in the  `/etc/pterodactyl/config.yml` file. For you it would look like this: 
![image](https://user-images.githubusercontent.com/105171995/227910426-aaac7ea0-3887-4baf-a46a-ff694b010b20.png)

**Comment by ghost** [comment]
I just restarted everything and it's on time Thank you very much

**Comment by HELPY4** [comment]
> I think the issue you describe has nothing to to with the panel configuration. As [Jcodeerd](https://github.com/Jcodeerd) wrote already you have to change your Timezone in your wings configuration and not in the panel, when your servers (logging in things like a minecraft server) are showing the wrong time. So you need to change the `timezone` option in the `/etc/pterodactyl/config.yml` file. For you it would look like this: ![image](https://user-images.githubusercontent.com/105171995/227910426-aaac7ea0-3887-4baf-a46a-ff694b010b20.png)

Thanks! It worked!

**Comment by Oratorian** [comment]
Why cant this be set while adding the node in the panel? that would make configuration easier and more streamlined.

**Comment by freyzamarshall02** [comment]
> I think the issue you describe has nothing to to with the panel configuration. As [Jcodeerd](https://github.com/Jcodeerd) wrote already you have to change your Timezone in your wings configuration and not in the panel, when your servers (logging in things like a minecraft server) are showing the wrong time. So you need to change the `timezone` option in the `/etc/pterodactyl/config.yml` file. For you it would look like this: ![image](https://user-images.githubusercontent.com/105171995/227910426-aaac7ea0-3887-4baf-a46a-ff694b010b20.png)

finally i found this works
