### ISSUE TITLE
ARK Survival Evolved Mount issue

### ISSUE THREAD

**Issue by TePMuHaToP** [pterodactyl/panel#4737]
### Current Behavior

I created my four servers of ARK. Made a Mount, linked it and connected to servers all by tutorial.
So the issue is that I can see my servers, I can jump between them but I can't transfer any data to another server in cluster.
All servers are located on the same local PC and same SSD.

The ARK's clusters are working as a Copy/Paste character (dino's/items) files to /var/lib/pterodactyl/mounts/ark/My_CLUSTER and then get them from here to another server in My_Cluster.

But it doesn't even creating My_CLUSTER in /var/lib/pterodactyl/mounts/ark so it is always empty there.

I tried to create it manually but it didn't helped.

Please tell me how to fix this issue so my servers could be able to transfer characters/dinos/items using Pterodactyl

### Expected Behavior

I need to transfer my Character/Dino/Item between my servers in My_Cluster so they could be readed between servers with Cross-ARK transfering

### Steps to Reproduce

ARK Cluster Setup w/ Pterodactyl

1. Create a dir on the host, for example:
    mkdir /var/lib/pterodactyl/mounts

2. Create a dir for the game:
   mkdir /var/lib/pterodactyl/mounts/ark
   chmod -R 775 /var/lib/pterodactyl/mounts

3. Create the mount in the panel, and attach it to the servers
    source: /var/lib/pterodactyl/mounts/ark
    target: /ark

4. Add the allow mount to your wings config:

allowed_mounts:
- /var/lib/pterodactyl/mounts

5. Restart wings service.

6. Add to your server startup params:
    ?AltSaveDirectoryName=UNIQUE_SAVE_NAME_PER_SERVER
    -NoTransferFromFiltering -ClusterDirOverride=/ark/ -clusterid=My_CLUSTER

7. Connect to ARK server from My_CLUSTER
8. Create character
9. Open Obelisk
10. Press Transfer Character (or put items or upload dinos into Obelisk)
11. Choose another available server in My_CLUSTER
12. Wait for it to be connected to Targeter Server
13. See that it's empty at Load Character((((

### Panel Version

1.11.3

### Wings Version

1.11.4

### Games and/or Eggs Affected

ARK

### Error Logs

```bash
no errors
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by D4N131P4YN3** [comment]
Try chmod -R 777 /var/lib/pterodactyl/mounts.

**Comment by gOOvER** [comment]
Thats not an issue of Ptero. for others it works; use Discord for Support

**Comment by SpartaWarsec** [comment]
I have the same problem :(
a full tutorial for this would be good because I think I missed something

**Comment by SpartaWarsec** [comment]
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:9127081aaf80e38544b183d96d06cf610d865e1b67606f1173ba5f7737d4f1c9 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_source 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
Not updating game server as auto update was set to 0. Starting Server
:/home/container$ ls /ark
ls: cannot access '/ark': No such file or directory
container@pterodactyl~ Server marked as offline...

**Comment by gOOvER** [comment]
> container@pterodactyl~ Server marked as starting... [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete... Pulling from parkervcp/pterodactyl-images Digest: sha256:9127081aaf80e38544b183d96d06cf610d865e1b67606f1173ba5f7737d4f1c9 Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_source [Pterodactyl Daemon]: Finished pulling Docker container image steam user is not set. Using anonymous user. Not updating game server as auto update was set to 0. Starting Server :/home/container$ ls /ark ls: cannot access '/ark': No such file or directory container@pterodactyl~ Server marked as offline...

you are using a really old egg; quay images are old as hell

**Comment by SpartaWarsec** [comment]
that's exactly what you get when you install it fresh my system is 5 days old

**Comment by SpartaWarsec** [comment]
the servers are running 

only the mount does not work I have tried everything and I have followed everything 

the panel also says that the mount has worked but when I enter the command to check it says clearly that it is not so

and how do I replace the quay images and against which ?

**Comment by SpartaWarsec** [comment]
so now i have looked at the docker stuff with a friend and we have come to the conclusion that the mount is shown in the panel but just does not arrive in docker and so the whole mount does not work.

and yes i sent the settings to the wing and also restarted we even reinstalled the whole wing.


MY FIX at the HOST system  

in data /etc/fstab 


#ARK server verbindung fur cluster    FOR CONNECTION ON NODES (LOCAL)
/var/lib/pterodactyl/volumes/17ac73b2-1b94-4cac-b54a-aa49b08fd4c8/Cluster /var/lib/pterodactyl/volumes/e30af49f-7b53-4ab3-9762-9580fcf4ccaa/Cluster none bind 0 0
/var/lib/pterodactyl/volumes/e30af49f-7b53-4ab3-9762-9580fcf4ccaa/Cluster /var/lib/pterodactyl/volumes/da334410-c417-4e8d-bc4d-ae885f88b689/Cluster none bind 0 0 
/var/lib/pterodactyl/volumes/da334410-c417-4e8d-bc4d-ae885f88b689/Cluster /var/lib/pterodactyl/volumes/38aea96c-72d9-4e09-88c9-58a1e28f9e18/Cluster none bind 0 0
#
#
#Netzlaufwerk ark   FOR CONNECTION OVER NODES (NETWORK)
YOUR IP MOUNT:/mnt/Data/Games/ARK /var/lib/pterodactyl/volumes/17ac73b2-1b94-4cac-b54a-aa49b08fd4c8/Cluster/nas nfs defaults 0 0



work very very good

**Comment by SpartaWarsec** [comment]
The whole thing could be implemented as an addition in which one provides a container with its own hosted network drive and the possibility of external IP or domain's to include and mount.


It would make sense to implement this also in the backup function because I want to store backups on my storage server and do not want to load my NVME SSD with the data garbage.

**Comment by Scaff31** [comment]
> so now i have looked at the docker stuff with a friend and we have come to the conclusion that the mount is shown in the panel but just does not arrive in docker and so the whole mount does not work.
> 
> and yes i sent the settings to the wing and also restarted we even reinstalled the whole wing.
> 
> MY FIX at the HOST system
> 
> in data /etc/fstab
> 
> #ARK server verbindung fur cluster FOR CONNECTION ON NODES (LOCAL) /var/lib/pterodactyl/volumes/17ac73b2-1b94-4cac-b54a-aa49b08fd4c8/Cluster /var/lib/pterodactyl/volumes/e30af49f-7b53-4ab3-9762-9580fcf4ccaa/Cluster none bind 0 0 /var/lib/pterodactyl/volumes/e30af49f-7b53-4ab3-9762-9580fcf4ccaa/Cluster /var/lib/pterodactyl/volumes/da334410-c417-4e8d-bc4d-ae885f88b689/Cluster none bind 0 0 /var/lib/pterodactyl/volumes/da334410-c417-4e8d-bc4d-ae885f88b689/Cluster /var/lib/pterodactyl/volumes/38aea96c-72d9-4e09-88c9-58a1e28f9e18/Cluster none bind 0 0
> 
> #Netzlaufwerk ark FOR CONNECTION OVER NODES (NETWORK) YOUR IP MOUNT:/mnt/Data/Games/ARK /var/lib/pterodactyl/volumes/17ac73b2-1b94-4cac-b54a-aa49b08fd4c8/Cluster/nas nfs defaults 0 0
> 
> work very very good

Can u please explain (or write a guide) how you create your cluster i tried with your modification but i never show my other server

**Comment by SpartaWarsec** [comment]
Surely you the servers must be the same ("AND THEY MUST HAVE THE SAME CLUSTER ID") .
they must run on the same machine and in the same wing everything else will only work with a network drive 


(my docker run on debian host system)
Then you have to edit the fstab file on the host system where the docker is running on and see if they synchronize the folders you can test this with a file you copy it in there and see if it shows up everywhere 

And then it's just a setting thing from ark itself that the settings are the same the parameters are in the same order and also the cluster ids match

**Comment by SpartaWarsec** [comment]
Surely you the servers must be the same ("AND THEY MUST HAVE THE SAME CLUSTER ID") .
they must run on the same machine and in the same wing everything else will only work with a network drive 


(my docker run on debian host system)
Then you have to edit the fstab file on the host system where the docker is running on and see if they synchronize the folders you can test this with a file you copy it in there and see if it shows up everywhere 

And then it's just a setting thing from ark itself that the settings are the same the parameters are in the same order and also the cluster ids match 


And the fstab file are the internal folders via UUID 


/var/lib/pterodactyl/volumes/17ac73b2-1b94-4cac-b54a-aa49b08fd4c8 <---Docker disk ID
/Cluster <---Came from


/var/lib/pterodactyl/volumes/e30af49f-7b53-4ab3-9762-9580fcf4ccaa <--Docker disks 
/cluster <---- target

 none bind 0 0 <----setting

**Comment by Scaff31** [comment]
> Surely you the servers must be the same ("AND THEY MUST HAVE THE SAME CLUSTER ID") . they must run on the same machine and in the same wing everything else will only work with a network drive
> 
> (my docker run on debian host system) Then you have to edit the fstab file on the host system where the docker is running on and see if they synchronize the folders you can test this with a file you copy it in there and see if it shows up everywhere
> 
> And then it's just a setting thing from ark itself that the settings are the same the parameters are in the same order and also the cluster ids match
> 
> And the fstab file are the internal folders via UUID
> 
> /var/lib/pterodactyl/volumes/17ac73b2-1b94-4cac-b54a-aa49b08fd4c8 <---Docker disk ID /Cluster <---Came from
> 
> /var/lib/pterodactyl/volumes/e30af49f-7b53-4ab3-9762-9580fcf4ccaa <--Docker disks /cluster <---- target
> 
> none bind 0 0 <----setting

Everything works fine. Thanks mate for your Time ;)

**Comment by ghost** [comment]
> Surely you the servers must be the same ("AND THEY MUST HAVE THE SAME CLUSTER ID") . they must run on the same machine and in the same wing everything else will only work with a network drive
> 
> (my docker run on debian host system) Then you have to edit the fstab file on the host system where the docker is running on and see if they synchronize the folders you can test this with a file you copy it in there and see if it shows up everywhere
> 
> And then it's just a setting thing from ark itself that the settings are the same the parameters are in the same order and also the cluster ids match
> 
> And the fstab file are the internal folders via UUID
> 
> /var/lib/pterodactyl/volumes/17ac73b2-1b94-4cac-b54a-aa49b08fd4c8 <---Docker disk ID /Cluster <---Came from
> 
> /var/lib/pterodactyl/volumes/e30af49f-7b53-4ab3-9762-9580fcf4ccaa <--Docker disks /cluster <---- target
> 
> none bind 0 0 <----setting

I have the same a little bit the same issue, but I dont understand your soulution comepletely

**Comment by ghost** [comment]
> > Surely you the servers must be the same ("AND THEY MUST HAVE THE SAME CLUSTER ID") . they must run on the same machine and in the same wing everything else will only work with a network drive
> > (my docker run on debian host system) Then you have to edit the fstab file on the host system where the docker is running on and see if they synchronize the folders you can test this with a file you copy it in there and see if it shows up everywhere
> > And then it's just a setting thing from ark itself that the settings are the same the parameters are in the same order and also the cluster ids match
> > And the fstab file are the internal folders via UUID
> > /var/lib/pterodactyl/volumes/17ac73b2-1b94-4cac-b54a-aa49b08fd4c8 <---Docker disk ID /Cluster <---Came from
> > /var/lib/pterodactyl/volumes/e30af49f-7b53-4ab3-9762-9580fcf4ccaa <--Docker disks /cluster <---- target
> > none bind 0 0 <----setting
> 
> Everything works fine. Thanks mate for your Time ;)

Or can you help me?
