### ISSUE TITLE
Container fails to start after installing docker-compose

### ISSUE THREAD

**Issue by e2489** [pterodactyl/panel#4741]
### Current Behavior

I installed docker-compose as a prerequisite for [Filestash](https://github.com/mickael-kerjean/filestash), however as soon as it's installed, my container no longer starts.

This is the error I get in the console:
```
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/core 
Digest: sha256:e56cec4056138ea6e6c3b59a5ec343f62b24948400deed6d61186c9e928bb7a8 
Status: Image is up to date for quay.io/pterodactyl/core:rust 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
container@pterodactyl~ Error Event [4b7ea2a5-ba32-4632-ac2a-4a76d27618d6]: environment/docker: failed to start container: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: openat2 /sys/fs/cgroup/system.slice/docker-2b578781c7cbfade3593c8c88718d8c59fc6e40e7861dcf7ee1f2bc9dae33115.scope/io.bfq.weight: no such file or directory: unknown
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 128
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/core 
Digest: sha256:e56cec4056138ea6e6c3b59a5ec343f62b24948400deed6d61186c9e928bb7a8 
Status: Image is up to date for quay.io/pterodactyl/core:rust 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Server crash was detected but an error occurred while handling it.
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 128
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

Even after uninstalling docker-compose and restarting, I still receive this error. The only way I was able to get my server to start back up was by completely removing and re-installing Docker _and_ the server. Deleting the server alone and trying a re-install just hangs.

### Expected Behavior

The Rust container should start without issue

### Steps to Reproduce

Install everything as normal, install docker-compose, attempt to start the Rust server.

### Panel Version

1.11.3

### Wings Version

1.11.5

### Games and/or Eggs Affected

Rust

### Docker Image

quay.io/pterodactyl/core:rust

### Error Logs

```bash
https://ptero.co/zuhiruqiti
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug but an issue with your configuration. Please visit the Discord and post your logs there. The Bot will have a response for you.

**Comment by e2489** [comment]
> Looks like you are missing mounts for cgroup V2. Enable the controllers for your system

I added systemd.unified_cgroup_hierarchy=1 to grub to enable cgroup2, but it didn't fix it. Do I need to do something else? There does not seem to be much information about this specific issue, and this is all the bot said.

**Comment by BrianRonin** [comment]
> > Parece que estão faltando montagens para o cgroup V2. Habilite os controladores para o seu sistema
> 
> Eu adicionei systemd.unified_cgroup_hierarchy=1 ao grub para habilitar o cgroup2, mas isso não resolveu. Preciso fazer mais alguma coisa? Não parece haver muita informação sobre esse problema específico, e isso foi tudo o que o bot disse.

we're in the same boat ._.
