### ISSUE TITLE
Wrong Permission Check for File WriteFileContentRequest

### ISSUE THREAD

**Issue by Verox001** [pterodactyl/panel#4742]
### Current Behavior

The WriteFileContentRequest checks if the User has the permission to create files and directories, like described here:
"Allows a user to create additional files and folders via the Panel or direct upload."

### Expected Behavior

WriteFileContentRequest should actually check the file.update permission instead of file.create, since it's like described for file.update:
"Allows a user to update the contents of an existing file or directory."

### Steps to Reproduce

1. Set file.upload for a Subuser to true.
2. Login with the subuser.
3. Change file content and save the file
4. Action will be unsuccessful, since he doesn't have the file.create permission, which shouldn't be necessary to update a file.

### Panel Version

1.11.3

### Wings Version

1.11.5

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
The write file endpoint will create the file if it does not exist before writing the contents, that's why it checks for the `files.create` permission. In order to fix this, the endpoint would need to check that the file exists first, then validate that the user has the `files.update` permission, which isn't currently possible (maybe with v2 though).

**Comment by Verox001** [comment]
Thanks for your reply. That's understandable.

**Comment by YusufYaser** [comment]
Why did you close this?
