### ISSUE TITLE
supporting stable diffusion webui

### ISSUE THREAD

**Issue by hanabi1314** [pterodactyl/panel#4746]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

supporting stable diffusion webui
run it on panel
may be add a egg

### Describe the solution you'd like.

supporting stable diffusion webui

**Comment by devnote-dev** [comment]
Please make egg requests in [Parker's egg repo](https://github.com/parkervcp/eggs/issues), not here.

**Comment by yesBad** [comment]
> Please make egg requests in [Parker's egg repo](https://github.com/parkervcp/eggs/issues), not here.

This egg is simply not possible anyways.

**Comment by parkervcp** [comment]
This is not a panel related issue honestly
