### ISSUE TITLE
Websocket is already in CLOSING or CLOSED state

### ISSUE THREAD

**Issue by Alexciao** [pterodactyl/panel#4755]
### Current Behavior

When I create a server, the management page with console/start-stop etc. doesn't work, and I see a red stripe on top of the screen that says `We're having some trouble connecting to your server, please wait...`
Upon further investigation in the browser console, I found that I am getting some websocket issues.

WebSocket connection to 'ws://_(my domain)_/api/servers/c2faaaaf-36e7-4f09-b5c0-9759c2c16c83/ws' failed: 
WebSocket is already in CLOSING or CLOSED state.

### Expected Behavior

The server installs correctly and I am able to control it.

### Steps to Reproduce

Configure a location and node, then crate a server.

### Panel Version

1.11.3

### Wings Version

1.11.5

### Games and/or Eggs Affected

Minecraft Paper

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
Wings: https://ptero.co/fasyfoqequ
Panel: http://bin.ptdl.co/fgsl5

NOTES: I have checked an existing issue with the same problem, however it has been linked as a duplicate of another issue that doesn't seem to be the same as mine. If I'm wrong, I'm sorry in advance.
I have also got no answers on Discord.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug but an issue with your configuration. Please visit the Discord.

**Comment by Alexciao** [comment]
> This is not a bug but an issue with your configuration. Please visit the Discord.

Ok, closing the issue
