### ISSUE TITLE
Error when creating file and folder with same name

### ISSUE THREAD

**Issue by ItzCrazyKns** [pterodactyl/panel#4756]
### Current Behavior

If we try to make a folder with the same name as a file, and vice versa, it returns the following error: `There was an error while communicating with the machine running this server. This error has been logged. Please try again. (Code: 500).` Some operating systems don't allow the user to make a file and folder with the same name, so that can be an issue related to this.

### Expected Behavior

I believe that there should be some error handling in place to prevent this error from occurring. For example, the panel could check if a file or folder with the same name already exists before attempting to create a new one, and display a user-friendly error message if necessary.

### Steps to Reproduce

- Create A File With Random Name For Example `test`
- After Creating The File Make A Folder Named Same As The Name Of The File. For Example `test`

### Panel Version

1.11.3

### Wings Version

1.11.5

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
This is not a wings or pterodactyl issue but a linux issue. You cannot have a file and a folder with the same name in the same directory, as you called out yourself.

```
[parker@desktop ~]$ mkdir test
mkdir: cannot create directory ‘test’: File exists
```

**Comment by ItzCrazyKns** [comment]
Yep I know but I believe that there should be some error handling in place to prevent this error from occurring. For example, the panel could check if a file or folder with the same name already exists before attempting to create a new one, and display a user-friendly error message if necessary.

**Comment by devnote-dev** [comment]
The fact that Wings is returning a 500 error suggests that it's doing something wrong here, especially since it's meant to check for this specific scenario:

https://github.com/pterodactyl/wings/blob/c76d68bc96d35c4f871b3efbc65f28a6f34cf8e9/router/router_server_files.go#L244-L246

https://github.com/pterodactyl/wings/blob/c76d68bc96d35c4f871b3efbc65f28a6f34cf8e9/router/router_server_files.go#L377-L379

Could you provide the Wings logs? I'll see if I can reproduce this too.

**Comment by ItzCrazyKns** [comment]
I Am curious https://github.com/pterodactyl/wings/blob/develop/router/router_server_files.go#L245

**Comment by ItzCrazyKns** [comment]
https://ptero.co/zohysygety

**Comment by ItzCrazyKns** [comment]
The issue should be fixed in https://github.com/pterodactyl/wings/pull/167
