### ISSUE TITLE
Server transfer

### ISSUE THREAD

**Issue by arthurbarret0** [pterodactyl/panel#4760]
### Current Behavior

I have 2 nodes with Cloudflare and active proxy. When transferring a server from node "Node01", to node "Node02", Pterodactyl does the transfer using the FQDN, i.e. the transfer always goes through the Cloudflare network unnecessarily.

### Expected Behavior

Checkbox to use an alternative address (such as a FQDN without proxy or even the numeric IP) for server transfers and/or internal communication. Even though the nodes are all working on the same network, and can transfer locally without consuming bandwidth, Pterodactyl transfers through Cloudflare, consuming bandwidth unnecessarily.

### Steps to Reproduce

1. Activate Cloudflare on 2 nodes
2. Transfer a server from one node to another

### Panel Version

1.11.3

### Wings Version

1.11.5

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
Some would argue this is expected behaviour: if you're proxying both nodes then you'd expect all the traffic to go via the proxy, not for specific internal communication.

Then again, I think it's unnecessary to proxy Wings so ¯\\\_(ツ)\_/¯

**Comment by FoksVHox** [comment]
This sounds more like a feature request than a bug report to me. 
I would also agree with @devnote-dev that the current behavior is expected.
