### ISSUE TITLE
Mail Test won't work

### ISSUE THREAD

**Issue by crackscout123** [pterodactyl/panel#4763]
### Current Behavior

When I try to send a test mail it loads about 3min. and then retruns to me with 

> "An error occurred while attempting to test mail settings: Connection could not be established with host "mail.your-server.de:25": stream_socket_client(): Unable to connect to mail.your-server.de:25 (Connection timed out)"

My mail server works, I checked everything doubble ports, password, usernames, ssl and so on everything should work, the mail server it selfs work perfectly in other programs 

### Expected Behavior

It should send a test mail, I guess.

### Steps to Reproduce

Click "Test" in Settings -> Mail

### Panel Version

1.11.3

### Wings Version

1.11.5

### Games and/or Eggs Affected

none

### Error Logs

```bash
http://bin.ptdl.co/foi7x
(the error at 2023-04-22 06:15:35 is fixed it was missing php-xml)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug but an issue with your configuration. Please visit the [Discord](https://discord.gg/pterodactyl).
Your panel server can't reach your mail server, most likely because port 25 is blocked.

**Comment by crackscout123** [comment]
I checked the ports, I can reach the server from my desktop pc, a cloud server and the ports of my machine running the panel and wings the port is also open.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by crackscout123** [comment]
I updated the panel & wings so I could reinstall it while keeping all files and it worked!
