### ISSUE TITLE
I keep getting this error "failed to load server configurations error=http: request creation failed"

### ISSUE THREAD

**Issue by ReallyCreativeDev** [pterodactyl/panel#4766]
### Current Behavior

I keep you there I've searched everywhere online I cannot find it to fix it

### Expected Behavior

it should run the node

### Steps to Reproduce

I do "sudo wings" but i get this
![2023_04_24_0xc_Kleki](https://user-images.githubusercontent.com/117539840/234156005-63c3d992-1945-45e3-b684-b024ea953afe.png)

### Panel Version

1.11.3

### Wings Version

 1.11.5

### Error Logs

```bash
https://ptero.co/bivocejopu.typescript
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
This is generally because your wings server cannot reach your panel.

**Comment by Boy132** [comment]
This is not a bug but an issue with your configuration. Please visit the [Discord](https://discord.gg/pterodactyl).
