### ISSUE TITLE
Allow commands to be executed when the server is offline

### ISSUE THREAD

**Issue by cashlycash** [pterodactyl/panel#4776]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When the server is offline. You can execute commands in the console which would just start the server, run that command, and then stop the server once its done. 

### Describe the solution you'd like.

Just replace the default startup command with the command typed and run the server (ofc the startup command wont actually change)

**Comment by devnote-dev** [comment]
- Start the server
- Run the command
- Stop the server

There's no reason have this extra layer of functionality.

**Comment by nullure** [comment]
its technically not possible as when the server is running then its possible to run servers. When the server is offline its 100% control is with pterodactyl and the server software is not running, but when the server if online the 80% of the control is with the server software and the server software is running so its possible to run commands and the server software can read it and write it too.

**Comment by raflymln** [comment]
I think what you wanted is just like shell command is that right? You wanted to interact with the application by using command?

If so, the only solution for this is by creating a new variable and just put the variable on the startup script, so every time you need to execute different command each the application start, you only need to change the variable.

However, interactive shell is actually available, it's the same as the egg that FalixNodes used long ago in their multiegg egg.

But if you wanted to actually execute command while to server is offline, that's just not gonna work, like how you even send a command to a dead server?

**Comment by matthewpi** [comment]
Not gonna happen for all of the reasons listed by others.  If you want to execute commands, start the server yourself.
