### ISSUE TITLE
S3 Objects are not deleted when backups are deleted from panel

### ISSUE THREAD

**Issue by TechnicallySky** [pterodactyl/panel#4777]
### Current Behavior

I am currently using StorJ  for backups on S3, when a backup is deleted, it is removed from the panel but the S3 Object hangs around 

### Expected Behavior

When backup is deleted the object is also deleted 

### Steps to Reproduce

Create New Backup 
Delete Backup 
Login into storage provider and notice the object still there 

### Panel Version

1.11.3

### Wings Version

11.11.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by hwalker928** [comment]
This seems like your S3 provider's file retention causes it. Have you checked #4385?

**Comment by matthewpi** [comment]
This has been tested before and backups are deleted properly.  Please check the issue linked by hwalker for some troubleshooting steps.
