### ISSUE TITLE
bind address already in use wings error

### ISSUE THREAD

**Issue by wandersonbrazdf** [pterodactyl/panel#4778]
Hello friends, how are you? I have an error on my panel apparently since the 21/04th, when accessing it, it presents this message:

We're having some trouble connecting to your server, please wait...

the problem is that I was not responsible for installing the VPS where the panel is and I do not have access data to the panel administrator.

looking to respond within linux, wings are complaining that they cannot bind the address 0.0.0.0:8080 the port is already in use because there is nothing using the port except wings itself.

Does anyone know what I can do to try to recover the panel?

**Comment by ozoromo** [comment]
That means something is already running on that port, check what services are listening on what ports with `sudo netstat -tunlp` in the vps servers console

**Comment by wandersonbrazdf** [comment]
i checked the united thing running on port 8080 and the wings

**Comment by danny6167** [comment]
There is no bug here - You're trying to start wings when it's already running.
Please use the Discord for support

**Comment by matthewpi** [comment]
This is not a bug.  It is clearly telling you that another service (or instance of Wings) is already listening on that port.

If you already see Wings running it is likely running through systemd (`systemctl status wings`).  If trying to start through systemd gives you a `port already in use` error, when use `ss -plnt` to check for anything using the port.

**Comment by RIFQIBOTZ** [comment]
Ya saya juga mengalaminya saat menggunakan vps dari aws amazon

**Comment by KiroFyzu** [comment]
Problem
---
maybe we experience the same thing, namely **only installing wings** we should have to install the panel first and that works for me

**Comment by M3kanoDev** [comment]
fixed just restart your server
`reboot`

**Comment by RIFQIBOTZ** [comment]
> ## Masalah
> mungkin kita juga mengalami hal yang sama yaitu **hanya memasang sayap** harusnya kita harus memasang panel terlebih dahulu dan itu berhasil bagi saya



> diperbaiki, cukup restart server Anda `reboot`

the result is failure, sir
