### ISSUE TITLE
Wings doesn't send log output that only contains new lines

### ISSUE THREAD

**Issue by danny6167** [pterodactyl/panel#4782]
### Current Behavior

When following a game servers console, if the application outputs blank lines theses are not sent down the websocket to the panel by wings

### Expected Behavior

Wings should sent a ConsoleOutputEvent with an empty string to make the panel display a new line

### Steps to Reproduce

Any server that ouputs empy lines.

Simple bash test case
 ```
#!/bin/bash
while true ; do

	echo "Three Lines"
    echo
    echo
    sleep 1
 done
```

### Panel Version

1.11.3

### Wings Version

1.11.6

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by redthirten** [comment]
Bump; can confirm issue on my end as well.

**Comment by parkervcp** [comment]
I believe the reason this is done was due to some weird issue with minecraft and sending misc new lines when it's not really useful. Is there a reason these newlines are needed beyond readability?

**Comment by AreuaWitchOfLightning** [comment]
Bump, can confirm issue on my end as well. Readability would be nice for mod manager I'm making (it runs before game starts), but yeah its just readability for me.

**Comment by Huguitis** [comment]
Also happening on my side.
