### ISSUE TITLE
context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by sfdsfdsr8u657657** [pterodactyl/panel#4784]
### Current Behavior

With random frequency, an error of exceeding the timeout appears in the panel when trying to manage server power. At the same time, I can manage the server files and everything else. The error may not appear for several hours, and then appear for no reason. And it will only go away if you wait 5-10 minutes or restart wings. Also ping and curl (panel -> node and node -> panel) works fine while this error shows.

IMPORTANT!
I looked at the cloudflare and nginx logs and it turns out that requests from the node do not even come to the panel during this error. It feels like wings just doesn't send them.

ALSO important!
- I have standard network panel and node settings
- I installed the panel and node myself without any scripts
- Node IP in the cloudflare added to whitelist and it does not block requests
- The panel and node are on different servers. This is not a local network
- I tried different DNS settings: 1.1.1.1 1.0.0.1 and 8.8.8.8 8.8.4.4
- The panel and node are not overloaded at the time of the error
- Ping and curl (panel -> node and node -> panel) works fine while this error shows.

I'm already really desperate and I don't have any guesses left what the problem might be. I really hope for your help.

### Expected Behavior

Server power management should work but it doesnt

### Steps to Reproduce

I found a regularity how to reproduce this bug: restart wings, immediately start an empty server so that it gives a crash error and try to manage of power. Often a timeout error appears when the server tries to restart itself after a crash:
![2023-05-21_21-05-57](https://github.com/pterodactyl/panel/assets/93942196/e80e79e8-aa16-4f47-a671-f386aae5d4a7)

It doesn't always work out the first time and you need to try to repeat it several times

### Panel Version

1.11.3

### Wings Version

1.11.5

### Error Logs

```bash
https://ptero.co/soxapusida
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug with the software. Please use the [Discord](https://discord.gg/pterodactyl) for configuration problems.

**Comment by sfdsfdsr8u657657** [comment]
> This is not a bug with the software. Please use the [Discord](https://discord.gg/pterodactyl) for configuration problems.

I have read dozens if not hundreds of messages about this error in your discord and all the answers are the same:
![2023-05-21_22-46-52](https://github.com/pterodactyl/panel/assets/93942196/34f570c6-afac-45a7-a334-f867d0db657b)

But if you read my report carefully, I wrote that the node and the panel are not on the local network and this bug can be reproduced artificially. I also read a lot of threads about this error on github and this problem was encountered in older versions of wings and this was confirmed by the developers themselves

**Comment by dan0sss** [comment]
I also read a lot of threads about this error on github and this problem was encountered in older versions of wings and this was confirmed by the developers themselves

**Comment by Boy132** [comment]
> I have read dozens if not hundreds of messages about this error in your discord and all the answers are the same: ![2023-05-21_22-46-52](https://user-images.githubusercontent.com/93942196/239764687-34f570c6-afac-45a7-a334-f867d0db657b.png)
> 
> But if you read my report carefully, I wrote that the node and the panel are not on the local network and this bug can be reproduced artificially.

Yes. So you already know that it's a network problem with your configuration. Probably caused by Cloudflare and/ or some sort of misconfguration.

> I also read a lot of threads about this error on github and this problem was encountered in older versions of wings and this was confirmed by the developers themselves

You are confusing your `context deadline exceeded` error with the `another power action is currently being processed for this server` errors. Those are two separate things.

**Comment by sfdsfdsr8u657657** [comment]
> > I have read dozens if not hundreds of messages about this error in your discord and all the answers are the same: ![2023-05-21_22-46-52](https://user-images.githubusercontent.com/93942196/239764687-34f570c6-afac-45a7-a334-f867d0db657b.png)
> > But if you read my report carefully, I wrote that the node and the panel are not on the local network and this bug can be reproduced artificially.
> 
> Yes. So you already know that it's a network problem with your configuration. Probably caused by Cloudflare and/ or some sort of misconfguration.

![image](https://github.com/pterodactyl/panel/assets/93942196/b9aa09ff-c569-46d5-8cb0-944dce1fb4ad)

I'm sorry if I may seem insistent, but I've already really spent weeks searching for the problem and debug, and now I don't even have an idea where the problem might be.
The problem is that requests from the node do not even reach the cloudflare. They are simply not in the list of cloudflare requests. Even if the requests were blocked by the cloudflare, it would still be shown in the list of requests. When the timeout error disappears, requests from the node are shown again in the cloudflare. From here you can understand that the problem is not in the panel, but in the node. But there is a clean wings with a standard network configuration on the node

**Comment by OverNodes-net** [comment]
The same thing happened to me, and it was produced by a user, I don't know how.
