### ISSUE TITLE
Problem with first start wings

### ISSUE THREAD

**Issue by StarGate88** [pterodactyl/panel#4785]
### Current Behavior

Hi, 

i have docker server with other applications, but now i need install pterodactyl panel. Problem is trough run wings, it´s write me error

Where cann i specify network address space in pterodactil or wings for docker?

Thank you for response.

### Expected Behavior

Run with other applications in docker with choice IP network

### Steps to Reproduce

After first installation

### Panel Version

1.11.3

### Wings Version

1.11.6

### Error Logs

```bash
FATAL: [May 23 14:43:45.166] failed to configure docker environment error=Error response from daemon: Pool overlaps with other one on this address space

Stacktrace:
Error response from daemon: Pool overlaps with other one on this address space
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
You need to edit the config.yml to use an address other than `172.18.0.1`. This has been covered many times

This is the section you want to edit.

```yml
docker:
  network:
    interfaces:
      v4:
        subnet: 172.18.0.0/16
        gateway: 172.18.0.1
```

**Comment by treverehrfurth** [comment]
I'm getting this same issue, only I have verified I am not using any other subnet and it is available. 
I have also tried adding a gateway with no luck

**Comment by treverehrfurth** [comment]
Although my issue doesn't say when i run the docker compose, it says it runs fine but in portainer it shows the issue in the logs

**Comment by lologaby** [comment]
Well, ive tried multiple subnets and still get this error

**Comment by August7337** [comment]
@lologaby @treverehrfurth  Did you find something, I have the same issue

`FATAL: [Sep 17 17:28:59.182] failed to configure docker environment error=Error response from daemon: invalid pool request: Pool overlaps with other one on this address space

Stacktrace:
Error response from daemon: invalid pool request: Pool overlaps with other one on this address space`

**Comment by August7337** [comment]
> @lologaby @treverehrfurth Did you find something, I have the same issue
> 
> `FATAL: [Sep 17 17:28:59.182] failed to configure docker environment error=Error response from daemon: invalid pool request: Pool overlaps with other one on this address space
> 
> Stacktrace: Error response from daemon: invalid pool request: Pool overlaps with other one on this address space`

I find something on discord




If you can't boot because of overlapping subnet to expand the config, then here's a boilerplate for you to edit
Default wings network docker config template if you are having overlapping networks and can't generate it. Copy it into your config.yml and change the occurrences of 172.18.0.x to something that's not already in use by your other networks. For example, 172.20.0.1

docker:
  network:
    interface: 172.18.0.1
    dns:
    - 1.1.1.1
    - 1.0.0.1
    name: pterodactyl_nw
    ispn: false
    driver: bridge
    network_mode: pterodactyl_nw
    is_internal: false
    enable_icc: true
    interfaces:
      v4:
        subnet: 172.18.0.0/16
        gateway: 172.18.0.1
      v6:
        subnet: fdba:17c8:6c94::/64
        gateway: fdba:17c8:6c94::1011
  domainname: ""
  registries: {}
  tmpfs_size: 100
