### ISSUE TITLE
How to use the administrator's key to operate a user's server？

### ISSUE THREAD

**Issue by Jovesong1** [pterodactyl/panel#4791]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I am using translation software to communicate. Recently, I am developing a project that aims to integrate pterosaur into the project to achieve self-service creation, sales, and management. However, I encountered a challenge during the development process. I consulted the official interface documentation and found that if I need to manage a user's server, I need to use the user's key (including managing files, establishing connections with the console using Websockets, network allocation, etc.), I am unable to use the administrator's key for management, so I tried to find a method for the administrator to create user keys, but I did not receive any results. Is there any way to manage the server through the administrator's key? Or how to use the administrator's key to create a user key.

### Describe the solution you'd like.

Recently, we are developing an integrated program that requires the management of pterosaur resources within the project. We hope to solve the problem of administrators creating user keys or directly managing servers.

### Additional context to this request.

![QQ截图20230528130205](https://github.com/pterodactyl/panel/assets/49064211/3f1dc764-fa7e-47eb-8c03-fd06e7145e03)

**Comment by Boy132** [comment]
An user api key created with an admin account will have access to both the client api and the application api.

**Comment by notwasabi1** [comment]
> An user api key created with an admin account will have access to both the client api and the application api.

Thanks for thiss...

**Comment by trenutoo** [comment]
Unfortunately, it is not possible to create client API tokens on behalf of other users. However, as stated above any Administrator user account's client token will grant you access to all endpoints.
