### ISSUE TITLE
cURL timeout problem

### ISSUE THREAD

**Issue by infectedw** [pterodactyl/panel#4798]
### Current Behavior

Since yesterday, the Pterodactyl panel has started acting weird. All wing hypervisors appear to be offline, even though they are online, and the game servers are still up and running.

Customers are unable to control servers that are assigned to them but are able to join servers since they are online.

All 10 wings are instantly hit with this problem, no one touched anything this setup worked for last almost 2 years with no error.

For some reason, cURL fails to reach all of the domains/IPs.

### Expected Behavior

Pterodactyl see nodes online and customers are able to control game servers from the panel.

### Steps to Reproduce

Sadly there isn't. The panel was working for 2 years with no problem, with casual updates, this behavior started happening yesterday randomly.

### Panel Version

1.11.3

### Wings Version

1.11.6

### Games and/or Eggs Affected

All of them affected.

### Docker Image

All of them affected.

### Error Logs

```bash
http://bin.ptdl.co/klt0b
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by infectedw** [comment]
Just a quick note, I tried migrating the panel to the second machine with Debian 11 (the current one is on Ubuntu 22.04), and still same error.

**Comment by TrixterTheTux** [comment]
If you visit your domain you’ll notice that it’s parked due to being expired. The discord should be used for configuration issues as this isn’t really a bug with the software.
