### ISSUE TITLE
Make the editor look like HasteBin

### ISSUE THREAD

**Issue by Qasimmodo** [Pterodactyl/Panel#480]
Could you make the editor look like HasteBin, it looks much cleaner or make a dark option that looks like it.

**Comment by parkervcp** [comment]
Look at the editor file - https://github.com/Pterodactyl/Panel/blob/7f48b757cd8d2c8c724b769d499a09ee6c976287/public/themes/pterodactyl/js/frontend/files/editor.js#L25

Then set it from `Editor.setTheme('ace/theme/chrome');` to `Editor.setTheme('ace/theme/twilight');`

**Comment by Yann151924** [comment]
Can you make this as a ".env" variable, can be good to switch directly in this config file. Or in the administration->settings ?

**Comment by Qasimmodo** [comment]
@parkervcp How do I restart the panel or apply the changes, the panel still looks the same.

**Comment by Qasimmodo** [comment]
Isn't working still.

**Comment by schrej** [comment]
There is no other theme then chrome available as far as i see it:
https://github.com/Pterodactyl/Panel/tree/7f48b757cd8d2c8c724b769d499a09ee6c976287/public/themes/pterodactyl/vendor/ace

**Comment by Qasimmodo** [comment]
@schrej Will this be a future feature, @parkervcp said it's working for him.

**Comment by DaneEveritt** [comment]
This is not an issue with the panel. You are more than welcome to modify the look and feel of the editor by manually editing files and looking at the [Ace](http://ace.c9.io) documentation.
