### ISSUE TITLE
Console Very Slow

### ISSUE THREAD

**Issue by BreadCatto** [pterodactyl/panel#4803]
### Current Behavior

The console seems very slow, it works fine for pterodactyl default eggs, but when i try to use any other egg, the console becomes very slow, its not because of the egg btw, it works fine on other nodes..

### Expected Behavior

the console should work normal, it dosent work for a specific node..

### Steps to Reproduce

idk, thats why im here

### Panel Version

1.11.3

### Wings Version

1.11.6

### Games and/or Eggs Affected

catactyl

### Docker Image

quay.io/devil38/catactyl:amd64

### Error Logs

```bash
there isnt any error logs, the console is very slow for a specific node any egg other than default..
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
This is a multi egg. Not supported! Try with an offical image and egg.

**Comment by Deauthorized** [comment]
Having the same issue. It was fine before, but then started unprompted.

**Comment by BreadCatto** [comment]
the issue comes while using wireguard while it only allows 1420 MTU and Pterodactyl containers use 1500 MTU, it could be fixed by changing the MTU/using wireguard alternatives
