### ISSUE TITLE
node usage (cpu,ram,disk)

### ISSUE THREAD

**Issue by topredyt** [pterodactyl/panel#4808]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

CPU / RAM / DISK system usage should be displayed at nodes

### Describe the solution you'd like.

under  "At-a-Glance" at node information, CPU / RAM / DISK usage should be displayed insteed of allocated ram / disk

**Comment by topredyt** [comment]
network traffic (inbound / outbound ) would also be usefull

**Comment by Boy132** [comment]
Duplicate of #3708

**Comment by parkervcp** [comment]
Going to close this as a duplicate
