### ISSUE TITLE
uninstall script or unistall documentation

### ISSUE THREAD

**Issue by WolffyTheReal** [pterodactyl/panel#4809]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

just a simple script or documentation for uninstalling the software when reimaging the server isn't feasable.

### Describe the solution you'd like.

Just simple in the Documentation as additional info.

**Comment by Jcodeerd** [comment]
https://pterodox.com/guides/uninstall-pterodactyl.html

**Comment by WolffyTheReal** [comment]
Closing the issue because it got solved in the comment above even though it maybe should be merged into the official documentation.
