### ISSUE TITLE
Add ability to clone/duplicate an existing server to current or other node

### ISSUE THREAD

**Issue by Byteflux** [pterodactyl/panel#481]
I think being able to spool up a development server by cloning an existing production server would be an extremely useful and powerful tool. Maybe something can be done with rsync between the containers?

**Comment by schrej** [comment]
As soon as #18 is implemented we could just locally clone the server by copying the files and then transfer it to another node if required.

**Comment by ericscott-uk** [comment]
Firstly, **sorry to bump this**

But could this be looked into? Would be incredibly useful.

**Comment by parkervcp** [comment]
#18 is already included in 1.0. So really this only needs a slight shift to actually impliment now

**Comment by DaneEveritt** [comment]
Closing, preferring newer #2148 in favor.
