### ISSUE TITLE
Incosistent server status

### ISSUE THREAD

**Issue by satoufuyuki** [pterodactyl/panel#4810]
### Current Behavior

Server is started and running well, yet the status is stopped
![image](https://github.com/pterodactyl/panel/assets/45705890/4c7ea5f3-8886-42cf-971e-1ca8ffb9b847)

### Expected Behavior

We can manage the server as running state (stop/kill/restart)

### Steps to Reproduce

Open the server in panel

### Panel Version

1.11.3

### Wings Version

1.11.6

### Games and/or Eggs Affected

Minecraft (Paper)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
https://bin.ptdl.co/33htb/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by mzrtamp** [comment]
The same thing also happen to me :)

**Comment by gOOvER** [comment]
looks more as a problem with a mod. Please use Discord for support

**Comment by satoufuyuki** [comment]
> looks more as a problem with a mod. Please use Discord for support

What mod? I used the official docker image without any modification. Both wings and panel
