### ISSUE TITLE
Allow Server Port Allocation to change UFW rules

### ISSUE THREAD

**Issue by CostcoFanboy** [pterodactyl/panel#4814]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A mechanism that allows Ptero to turn on and off ports on UFW from the UI. 

So, basically, any port in Admin Config -> Nodes -> Allocation that are assigned, or upon assignment, are allowed through the Firewall.

Let's say I assign 15000, 15777 to Satisfactory, this would trigger a command to ufw allow both those ports directly (15000->15000 no forwarding).

I realize this feature is somewhat dangerous and gives ptero a disproportionate power on the instance it runs on though. But it would be really useful to have for some of us sharing ptero with less technologically adept people.

### Describe the solution you'd like.

I want there to be a checkbox that allows the port to be forwarded through ufw when I assign it to a specific server.

**Comment by Boy132** [comment]
That's already the case, docker will open the ports via iptables.

**Comment by parkervcp** [comment]
docker already interfaces with `iptables` directly which `firewalld` and `ufw` are wrappers for.

**Comment by CostcoFanboy** [comment]
> That's already the case, docker will open the ports via iptables.

Oh. I guess it's a bug on my side then. The ports are closed until I explicitly open them.
Thanks I'll look into it.

**Comment by danny6167** [comment]
If you're using host mode networking, that would explain your issue.
