### ISSUE TITLE
Excessive overhead

### ISSUE THREAD

**Issue by matipoirierg** [pterodactyl/panel#4816]
### Current Behavior

I have a minecraft server with the following flags: 

java -Xms11264M -Xmx11264M --add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs/ -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -jar server.jar --nogui

The problem is that after a while the overhead is excessive high, as you can see in the flags the ram limit is 11gb for the server, but it ends taking up to 18gb and even more.

Server usage:
![Screenshot 2023-07-08 145715](https://github.com/pterodactyl/panel/assets/97362850/68e68b7e-acd4-4573-a8b0-e6e953aba74a)
Server usage + overhead:
![Screenshot 2023-07-05 130842](https://github.com/pterodactyl/panel/assets/97362850/9f018954-f5c2-47ff-989f-2af74a16ad80)
 7gb for overhead just don't make sense and I can confirm it's actually using that. (free -h)

### Expected Behavior

Overhead should be 3gb at max.

### Steps to Reproduce

I'm just using aikar flags.

### Panel Version

1.11.3

### Wings Version

1.11.5

### Games and/or Eggs Affected

Minecraft (Paper)

### Docker Image

ghcr.io/software-noob/pterodactyl-images:java_17

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
Never give java unlimited ram. It can not handle it that well.

**Comment by matipoirierg** [comment]
> Never give java unlimited ram. It can not handle it that well.

I set the limit to 13gb and decreased xmx and xms to 10gb, started crashing.

**Comment by Boy132** [comment]
> > Never give java unlimited ram. It can not handle it that well.
> 
> I set the limit to 13gb and decreased xmx and xms to 10gb, started crashing.

That's because of the AlwaysPreTouch flag. Overall your "problem" has nothing to do with Pterodactyl itself. If any it's a Minecraft/ Java problem. (You can use the Discord for additional help, this is not a bug)

**Comment by matipoirierg** [comment]
> > > Never give java unlimited ram. It can not handle it that well.
> > 
> > 
> > I set the limit to 13gb and decreased xmx and xms to 10gb, started crashing.
> 
> That's because of the AlwaysPreTouch flag. Overall your "problem" has nothing to do with Pterodactyl itself. If any it's a Minecraft/ Java problem. (You can use the Discord for additional help, this is not a bug)

I removed the pre touch flag and it's still an issue, server uses up to 4 gb for overhead.

**Comment by Boy132** [comment]
> > > > Never give java unlimited ram. It can not handle it that well.
> > > 
> > > 
> > > I set the limit to 13gb and decreased xmx and xms to 10gb, started crashing.
> > 
> > 
> > That's because of the AlwaysPreTouch flag. Overall your "problem" has nothing to do with Pterodactyl itself. If any it's a Minecraft/ Java problem. (You can use the Discord for additional help, this is not a bug)
> 
> I removed the pre touch flag and it's still an issue, server uses up to 4 gb for overhead.

Again, this is not a bug. That's just how Minecraft/ Java handles memory. For additional help please visit the [Discord](https://discord.gg/pterodactyl).

**Comment by PatchedNotFixed** [comment]
You will most likely find this is related https://github.com/pterodactyl/panel/issues/4635

@matipoirierg

**Comment by matipoirierg** [comment]
Ended up being a plugin called pl3xmap, it was leaking the server memory.
