### ISSUE TITLE
Your panel is no longer working

### ISSUE THREAD

**Issue by gokusan92** [pterodactyl/panel#4818]
### Current Behavior

It just does no longer working i tried to install it into my server and when i try to login i get this annoying error

The POST method is not supported for this route. Supported methods: GET, HEAD.

and even if i clear cache of artisan it just does not work, why did you created that project in artisan? it's trash using artisan it would be better in vuejs or so php is for trash.

### Expected Behavior

Log me in normally? As every application does?

### Steps to Reproduce

Installed, setup the nginx tried to login after that and i got the problem.

### Panel Version

latest

### Wings Version

latest

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Did you install a theme? If yes that theme was outdated.
You can run the [panel update steps](https://pterodactyl.io/panel/1.0/updating.html#manual-upgrade) to remove the theme.

PS: "latest" is not a version.

**Comment by gokusan92** [comment]
no i did not
https://*/auth/login
i just installed it.

**Comment by Boy132** [comment]
What's your panel version? Either you installed an old version or somehow have mixed files from different versions.
Try the before mentioned update steps to make sure you have the correct files.

**Comment by gokusan92** [comment]
imagine, i had extracted the panel correctly as of your tutorial wget etc, i didn't mix anything and i don't get any error. I did not mix this control panel version with anything, just this time i use CloudPanel V2 in order to combine those two together.

**Comment by gokusan92** [comment]
I tried with the latest version of yours once again removing all the files then try this again, it is not working once again.

**Comment by gokusan92** [comment]
I fixed it. Nginx configuration your documentation says otherwise but i findout that i didn't needed to add it in my case.
