### ISSUE TITLE
Access API. 

### ISSUE THREAD

**Issue by zKoz210** [Pterodactyl/Panel#482]
Hello. I don’t understand how use API and public, secret key. Will be nice, if you help me :)

My link: `https://localhost/api/user/server/1`

**Comment by DaneEveritt** [comment]
This is not a bug with the panel, please use our support options such as [Discord](https://pterodactyl.io/discord) or [our Forums](https://forums.pterodactyl.io).

The API endpoints in the documentation are also wrong right now.

You likely want to be hitting `/api/user` and `/api/user/server/<uuid>`

**Comment by zKoz210** [comment]
Hmm... How test API in browser?
