### ISSUE TITLE
tv_port and clientport not change

### ISSUE THREAD

**Issue by BlagoYar** [pterodactyl/panel#4820]
### Current Behavior

If I prescribe my tv_port and clientportin the startup line, then they do not change to the given ones.

### Expected Behavior

When the server is launched and subsequently entered the tv_port and clientport game server to the console, the ports I assigned, and not by default, must be displayed.

### Steps to Reproduce

In "Allocation" I added port ranges (22000-22050; 27000-27050; 27100-27150), created the server, in the "Assign Additional Ports" added 22013, 27013, 27113,
Corrected the launch line for such
./srcds_run -game csgo -console -port {{SERVER_PORT}} -clientport 22013 +ip 0.0.0.0 +map {{SRCDS_MAP}} -strictportbind -norestart +sv_setsteamaccount {{STEAM_ACC}} -net_port_try 1 +tv_enable 1 +tv_port 27115 -usercon +game_type 0 +game_mode 0 +mapgroup mbgdust2 -maxplayers_override 40 -tickrate 64

launch the server, enter "tv_port" to the game console server, I get
"tv_port" = "27118" ( def. "27020" )                                             - Host GOTV[0] port

enter "clientport" I get
"clientport" = "27005"                                                           - Host game client port

### Panel Version

1.11.3

### Wings Version

1.11.6

### Games and/or Eggs Affected

740

### Docker Image

ghcr.io/pterodactyl/games:source

### Error Logs

```bash
https://ptero.co/jijubihobi
http://bin.ptdl.co/tazx0

the log for today's number does not exist, only for 11.07.2023 and 12.07.2023, этот за 12.07
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
You need to make those variables that you set. The way you have them right now is just hard coding them in the start config.

**Comment by BlagoYar** [comment]
> 

How to do it?

**Comment by BlagoYar** [comment]
> You need to make those variables that you set. The way you have them right now is just hard coding them in the start config.

How to do it?

**Comment by parkervcp** [comment]
You already have examples in the startup.

**Comment by BlagoYar** [comment]
> You already have examples in the startup.

You mean this {{SERVER_PORT}} etc.?
But it was not me that I created a variable and in general all the variables in the line were not created by me.
These are the actions of the panel, as I understand it.

**Comment by parkervcp** [comment]
That is a variable and it is in the start command. You can add variables to any egg and start command.

**Comment by BlagoYar** [comment]
> That is a variable and it is in the start command. You can add variables to any egg and start command.

OK, I added to EGG Counter Strike Global Offensive a variable Srcds_clientport, preserved, prescribed the value of this variable in the Startup server tab, prescribed in the launch line:
./srcds_run -game csgo -console -port {{SERVER_PORT}} +ip 0.0.0.0 +map {{SRCDS_MAP}} -clientport {{SRCDS_CLIENTPORT}} -strictportbind -norestart +sv_setsteamaccount {{STEAM_ACC}} -net_port_try 1 +tv_enable 1 +tv_port 27113 -usercon +game_type 0 +game_mode 0 +mapgroup mbgdust2 -maxplayers_override 40 -tickrate 125

When starting the server:
container@pterodactyl~ ./srcds_run -game csgo -console -port 27013 +ip 0.0.0.0 +map awp_lego_2_nd -clientport 22013 -strictportbind -norestart +sv_setsteamaccount XXXXXXXXXXXXXXXXXXXXXXXXX -net_port_try 1 +tv_enable 1 +tv_port 27113 -usercon +game_type 0 +game_mode 0 +mapgroup mbgdust2 -maxplayers_override 40 -tickrate 125

But when entering the Clientport command console, I get the same as before
clientport
"clientport" = "27005"                                                           - Host game client port

**Comment by parkervcp** [comment]
You need to add a variable to the egg such as `TV_PORT` and in the startup you make it `+tv_port {{TV_PORT}}`

**Comment by BlagoYar** [comment]
> You need to add a variable to the egg such as `TV_PORT` and in the startup you make it `+tv_port {{TV_PORT}}`

I went to NESTS -> Source Engine -> Counter Strike: Global Offensive -> Variables -> Create New Variable

And introduced such parameters
![ScreenShot - 3](https://github.com/pterodactyl/panel/assets/3672314/ea4156df-4c51-4260-a05c-1d9e47feaa5d)

Saved and added directly to the server itself -> `-clientport {{SRCDS_CLIENTPORT}}`
![ScreenShot - 4](https://github.com/pterodactyl/panel/assets/3672314/e687e110-bd30-47f3-8201-c3c56b2d4f53)
![ScreenShot - 5](https://github.com/pterodactyl/panel/assets/3672314/f8c707d7-791a-46d5-acbf-b597d94c1003)

What am I doing wrong?

**Comment by parkervcp** [comment]
The start command gets parsed when applied to a server. It doesn't show up in the command modification area.

**Comment by BlagoYar** [comment]
> The start command gets parsed when applied to a server. It doesn't show up in the command modification area.

I don’t understand what I still need to do so that сlientport 27005 changes to my 22013?

**Comment by BlagoYar** [comment]
It just needed to not -clientport but +clientport
