### ISSUE TITLE
Incorrect Job Execution in Schedules with UTC+X:30 Timezone/Multiple Backups when using schedules.

### ISSUE THREAD

**Issue by DebarghaXD** [pterodactyl/panel#4821]
### Current Behavior

When using Pterodactyl Schedules with timezones that have a UTC+X:30 offset, such as Asia/Kolkata (UTC+5:30) or Asia/Kabul (UTC+4:30), the schedule doesn't work as expected. Instead of running at the specified time, the jobs start executing 30 minutes earlier than intended time and continue to run every minute until the expected time. I have also tested this issue with a timezone without the +30-minute offset, such as Asia/Oral (UTC+5), the scheduled jobs execute correctly at the specified time.

For example, I set a schedule to make a backup at 10:00 AM. At 9:30AM the schedule starts making 2 backups every 10 minutes due to the backup limit of pterodactyl hence making 6 backups in total within 30 mintues. In the schedule, the last run changes every mintue.

There is a similar issue #3351

### Expected Behavior

Scheduled jobs should execute at the precise time set in the selected timezone (UTC+X:30). For example, if a job is scheduled for 10:00 AM in Asia/Kolkata (UTC+5:30), it should begin at exactly 10:00 AM and not initiate 30 minutes earlier.

### Steps to Reproduce

Set the timezone to any UTC+X:30 timezone, like Asia/Kolkata (UTC+5:30).
Create a scheduled job for a specific time, e.g., 10:00 AM.

### Panel Version

1.11.3

### Wings Version

1.11.6

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by zvikasdongre** [comment]
I have this exact same issue (https://discord.com/channels/122900397965705216/658550982975946762/1130019544405115001).

I noticed this when I wanted to rollback to backup of previous day (the schedule is set to backup every midnight), but I found that all 3 backups are generated almost at the same time (~some minutes apart).

And I think this is only happening for Asia/Kolkata TZ and some other Asian timezones, because me and most of the other people who have reported this issue are using some Asian Timezone.

**Comment by DebarghaXD** [comment]
I tried Australia/Darwin timezone now, which is (UTC+9:30) it also showed same results which Asia/Kolkata showed. I dont think its only for Asian timezones.

**Comment by danny6167** [comment]
Alright I've figured out why this happens. Ill produce a patch.

**Comment by DebarghaXD** [comment]
@danny6167 its works! but there is one problem i.e. the 'last run at' shows 30 minutes before the execution time. 
![image](https://github.com/pterodactyl/panel/assets/82307576/10ddb269-be66-4376-b604-fca7a1f03011)
![image](https://github.com/pterodactyl/panel/assets/82307576/a8a79716-c429-427a-b778-d8a8fd50bbf8)

**Comment by danny6167** [comment]
It all works fine for me. If that's an existing job you might have some data calculated with the wrong offset still in the database. It would resolve its self after the next run.

![image](https://github.com/pterodactyl/panel/assets/388231/c6957ba5-01f3-41f6-8c65-f083a4c4cddf)
![image](https://github.com/pterodactyl/panel/assets/388231/00d32fe2-9674-42e0-9683-7a8c77d9fa23)

**Comment by danny6167** [comment]
If you're talking about the "Backup at" time, that is the servers local time where as the "Last run at" time is in your browsers timezone.
Always been that way, this patch doesn't touch that.

**Comment by DebarghaXD** [comment]
restarted the system and now it works completely fine. Finally this got fixed after 2 years lol. Thank you very much.

**Comment by danny6167** [comment]
Ah yes. Not restarting pteroq would be an issue.

Issue should stay open until my PR is actually pulled.

**Comment by matthewpi** [comment]
Fixed in https://github.com/pterodactyl/panel/commit/04d83edd361475087ee6e24b317e5be4d03f08b1
