### ISSUE TITLE
Schedules not working

### ISSUE THREAD

**Issue by ycoskun41** [pterodactyl/panel#4822]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

does not work automatically. When I do run now, it sends a command to the console.

### Describe the solution you'd like.

automatic processing should occur

### Additional context to this request.

![image](https://github.com/pterodactyl/panel/assets/83180501/c9ff6d31-08a4-46dc-b3c5-ec252afd9a74)

![image](https://github.com/pterodactyl/panel/assets/83180501/c3ab5534-da4b-43f2-bcdf-77ca81cd60fe)

![image](https://github.com/pterodactyl/panel/assets/83180501/ca40433d-d440-44d9-a4ff-286f989b7be8)

**Comment by hwalker928** [comment]
This is an issue with your configuration, please ensure that the Pterodactyl Queue Worker is running on your panel host system.

**Comment by ycoskun41** [comment]
Where should I check?

**Comment by ycoskun41** [comment]
@hwalker928 the problem still continues.

**Comment by ycoskun41** [comment]
![image](https://github.com/pterodactyl/panel/assets/83180501/01dede40-3a5b-4f9b-98b0-a9ce426c3932)

My apologies, friends. But I can't solve the problem. and there are not enough resources.

@hwalker928 @gOOvER @youanden @KasperFranz

**Comment by ycoskun41** [comment]
![image](https://github.com/pterodactyl/panel/assets/83180501/3f02f797-f427-49dd-a00d-0ad47f9c016f)

**Comment by danny6167** [comment]
Why did you file this as a feature request?

My best guess is that you did not setup the cron job, or wrong PHP version
