### ISSUE TITLE
WebDashboardPort not opening. + Schedules not working. 

### ISSUE THREAD

**Issue by ycoskun41** [pterodactyl/panel#4823]
### Current Behavior

**serverconfig.xml file.**
WebDashboardEnabled  true
WebDashboardPort 	8080

![image](https://github.com/pterodactyl/panel/assets/83180501/b23ca5e3-bd47-49a5-b6c2-9e1ba5aa0981)

**console output.**
2023-07-17T20:07:56 172.937 INF [Web] Serving basic webserver files from /home/container/7DaysToDieServer_Data/../Mods/TFP_WebServer/webroot
2023-07-17T20:07:56 172.959 INF Started thread SSE-Processing_/sse/1
2023-07-17T20:07:56 173.072 INF [Web] **Started Webserver on port 8080**

![image](https://github.com/pterodactyl/panel/assets/83180501/da6ee6d5-9aee-402d-9583-977787aefb35)

**Browser** 
SERVERIP:8080
print
{"error":"The required authorization heads were not present in the request."}

![image](https://github.com/pterodactyl/panel/assets/83180501/9c288d5b-749c-40c8-86d1-0044029bdf2c)

Schedules does not work automatically.

![image](https://github.com/pterodactyl/panel/assets/83180501/29da21f2-e610-4f90-a396-39ad745b758a)

**crontab is configured.**

![image](https://github.com/pterodactyl/panel/assets/83180501/4e1aba8b-3b77-404b-87b2-732e2188a496)

**Created Queue Worker**

![image](https://github.com/pterodactyl/panel/assets/83180501/826fd825-1091-4220-b9fd-d81f3aa774b7)

**Status pteroq.service**

![image](https://github.com/pterodactyl/panel/assets/83180501/dd9f1288-a0a8-4ae7-a67c-57051861fa49)

### Expected Behavior

Web Dashboard opening up
Schedules Auto run.

### Steps to Reproduce

a

### Panel Version

1.11.3

### Wings Version

v1.11.6

### Games and/or Eggs Affected

7 Days To Die

### Docker Image

ghcr.io/parkervcp/steamcmd:debian

### Error Logs

```bash
https://ptero.co/edygixicun

http://bin.ptdl.co/22tfg
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
You can not use port 8080 as it is default wings port. Allocated 1 diffrend port.

**Comment by ycoskun41** [comment]
Schedules does not work automatically.?

**Comment by hwalker928** [comment]
> I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

Please join the Discord and ask for help there as this is a configuration issue with your system (at least with schedules)

**Comment by ycoskun41** [comment]
> > I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.
> 
> Please join the Discord and ask for help there as this is a configuration issue with your system (at least with schedules)

I couldn't get support from discord for 2 days. That's why I felt compelled to post it here. I didn't want to spam on discord with multiple messages.

**Comment by QuintenQVD0** [comment]
@hwalker928 what is your php version? `php -v`
