### ISSUE TITLE
[Feature Request] Fail2ban support?

### ISSUE THREAD

**Issue by AE720** [pterodactyl/panel#4829]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I looked through the docs and issues but I couldn't find anything similar so sorry in advance if this is also implemented or requested. 

I'd like the ability to react to console logs in the OS itself and possibly handle situations depending on what the console says. For example banning scanners via fail2ban. 

### Describe the solution you'd like.

I'm not to savvy in Docker to know if it's possible to even output logs to /var/logs for example in order to keep isolation, but alternatively, maybe have the ability to point to a logging server that fail2ban has a jail setup for. I know it's mild if you have a whitelist, but it would be a really nice QOL to keep the console cleaned up.

**Comment by devnote-dev** [comment]
Documentation queries usually go in the documentation repository, but there is one for fail2ban already: https://github.com/pterodactyl/documentation/pull/468.
