### ISSUE TITLE
SFTP username is using current user's session

### ISSUE THREAD

**Issue by yibfozzy** [pterodactyl/panel#4831]
### Current Behavior

The SFTP username from server page - 'Settings' - 'SFTP DETAILS' - 'USERNAME' obtains username from current session (e.g. admin.SHORT_SERVER_UUID if you are logged in with admin account), so it's not shown correctly if you are logged under any other user with administrative privileges.

### Expected Behavior

The SFTP username should contain the owner's Pterodactyl username instead.

### Steps to Reproduce

- create a regular user and an active server for it
- login under any other user with admin permissions
- navigate to the original user's server - 'Settings' - 'SFTP DETAILS'

### Panel Version

1.11.3

### Wings Version

1.11.7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jelcoo** [comment]
This is intended behavior.

**Comment by danny6167** [comment]
This is exactly how it's supposed to work.

No point showing you someone elses username, you can't login using it as you wouldn't (shouldn't) know the password anyway.

**Comment by yibfozzy** [comment]
Isn't it confusing to be shown an obviously wrong username? Especially for admin user, which could be debugging something and has an ability to reset the regular user's password.

**Comment by Jelcoo** [comment]
What is wrong with the username? It is supposed to work like this.

**Comment by yibfozzy** [comment]
SFTP username shown while logged under 'testuser123':
<img width="609" alt="Screenshot 2023-07-27 at 15 32 27" src="https://github.com/pterodactyl/panel/assets/27290430/9b6694b7-c0dc-4496-87ac-3fd5035b8a83">

SFTP username on the same server shown while logged under 'admin':
<img width="630" alt="Screenshot 2023-07-27 at 15 31 28" src="https://github.com/pterodactyl/panel/assets/27290430/712e4162-f01e-4ba7-b821-818c0e3882a5">

**Comment by parkervcp** [comment]
Each user can access to files of servers they have permissions on

**Comment by parkervcp** [comment]
the logins shown there is in the `username.serverid`. That is how it identifies the user and the server.

There is no single user as that would be a shared credential or a single user with multiple passwords that would work. Tracking that either way would be difficult and potentially a security issue.

The way the sftp server uses this format now is fast a simple to validate.

**Comment by trenutoo** [comment]
This is not a bug and rather the intended behavior. Each Panel user has their own credentials and the displayed SFTP details for that reason are for the current user. They are not shared nor should be.

There are subusers as well besides the server owner and admins. Your proposal would have everyone share the same account credentials.
