### ISSUE TITLE
504 gateway timeout

### ISSUE THREAD

**Issue by lintanxai** [pterodactyl/panel#4832]
### Current Behavior

I was successfully install pterodactyl panel and run wings daemon but when i open browser console i saw error message when try to fetching system information to panel domain it appears and give 504 gateway timeout response from https://panel.mydomain/.../system-information
It is internal problem or i have miss configuration on my system such forwarding port etc.

### Expected Behavior

I expect when i done with wings daemon and my panel i can do something such create server but it always result an error like when to load system info

### Steps to Reproduce

I following the documentation for installing them step by step not using script installer because when i using installer i always get unmet dependencies with ea4 yes i have whm in system.

### Panel Version

1.11.3

### Wings Version

1.11.7

### Games and/or Eggs Affected

Custom

### Docker Image

Alpine

### Error Logs

```bash
{}
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
[X] I have provided all relevant details,   @#including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific 

> `system.[
/](url)`

**Comment by trenutoo** [comment]
Please use the Discord server for configuration issues and try to provide more information, such as the logs requested in this issue template
