### ISSUE TITLE
Important info missing from API reference

### ISSUE THREAD

**Issue by repeater64** [pterodactyl/panel#4835]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

In the API reference (https://dashflo.net/docs/api/pterodactyl/v1/)

There is an important bit of info missing. For the `api/client/` request (which is the request that lists servers), it doesn't mention the fact that this will only list the servers on page 1 (ie the first 50). 

### Describe the solution you'd like.

It should be mentioned that the request has a page parameter, ie `api/client/?page=2`

**Comment by TrixterTheTux** [comment]
We don't have any control over the provided documentation, as it mentions:
> This documentation is unofficial and provided by Dashflo.

**Comment by devnote-dev** [comment]
There are efforts to maintain updated and open-source documentation (see [ptero-notes](https://github.com/devnote-dev/ptero-notes) and [Pterodactyl-API](https://github.com/TekExplorer/Pterodactyl-API)). Feel free to contribute to either as these are the ones being recommended in the Discord server.

**Comment by repeater64** [comment]
My bad, I didn't realize this was unnoficial!
