### ISSUE TITLE
Panel inside Docker not writing to log file

### ISSUE THREAD

**Issue by davemsh** [pterodactyl/panel#4838]
### Current Behavior

I've got Panel running using the official Docker image (`ghcr.io/pterodactyl/panel:v1.11.3`) on Ubuntu Server 22.04 host system, but there seems to be an issue with how the provided [Docker Compose yml](https://github.com/pterodactyl/panel/blob/develop/docker-compose.example.yml) is mounting the logs path.

The problem is that nothing gets logged. Nothing at all. The Laravel log file gets created, but nothing gets written to it, aside from a single message that only occurs on initial container creation that says the following:
``[2023-08-12 03:12:25] production.NOTICE: A query exception was encountered while trying to load settings from the database: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.settings' doesn't exist (SQL: select * from `settings`)``

After this message, nothing ever gets logged afterward, so long as the logs folder is mounted in Docker.

If I comment out the line where the logs folder gets mounted (`/srv/pterodactyl/logs/:/app/storage/logs`), it works fine, but then the logs aren't visible without going into the container's terminal.

### Expected Behavior

Logs are properly written to the mounted folder path.

### Steps to Reproduce

Run a fresh instance of Panel on Docker using the example Docker Compose.

### Panel Version

1.11.3

### Wings Version

N/A, haven't set that up yet

### Docker Image

ghcr.io/pterodactyl/panel:v1.11.3

### Error Logs

```bash
There are no logs being written due to this issue.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Loki-101** [comment]
This is a known issue with the image. Until it's addressed the suggested fix is ``docker compose exec panel chown -R nginx: /app/storage/logs/``

**Comment by davemsh** [comment]
The workaround worked, thanks!

**Comment by parkervcp** [comment]
I'll have a pr to fix this today
