### ISSUE TITLE
Schedules ignore delay (TIME OFFSET (IN SECONDS))

### ISSUE THREAD

**Issue by BearLeonLight** [pterodactyl/panel#4841]
### Current Behavior

When I run the schedule (as shown in the picture), he will not wait (TIME OFFSET (IN SECONDS)), and will execute immediately without any delay.
![image](https://github.com/pterodactyl/panel/assets/52900334/715949aa-9825-4fd7-9a3b-0d796a3e52e6)

### Expected Behavior

It will run sequentially and respect the delay settings

### Steps to Reproduce

As above question.

### Panel Version

1.11.3

### Wings Version

1.11.6 

### Games and/or Eggs Affected

Minecraft(Paper)，Minecraft(Vanilla)

### Error Logs

```bash
https://ptero.co/atygofosan
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by yesBad** [comment]
Never had an issue myself.

**Comment by Boy132** [comment]
What is your queue driver set to? (`QUEUE_DRIVER` or `QUEUE_CONNECTION` in your `/var/www/pterodactyl/.env` file)

Also, "latest" is not a version.

**Comment by danny6167** [comment]
What is your panels (not wings) timezone set to?

**Comment by BearLeonLight** [comment]
> What is your queue driver set to? ( or in your file)`QUEUE_DRIVER``QUEUE_CONNECTION``/var/www/pterodactyl/.env`
> 
> Also, "latest" is not a version.

CACHE_DRIVER=file
QUEUE_CONNECTION=sync

**Comment by BearLeonLight** [comment]
> What is your panels (not wings) timezone set to?

APP_TIMEZONE=Asia/Taipei

**Comment by Boy132** [comment]
> QUEUE_CONNECTION=sync

That is the problem. You need to use a different option. (e.g. `redis`)
`sync` is basically the option for "no queue at all".

**Comment by BearLeonLight** [comment]
I'll run a tuning test later.
