### ISSUE TITLE
Pterodactyl panel always wants to use https

### ISSUE THREAD

**Issue by Novampr** [pterodactyl/panel#4847]
### Current Behavior

When navigating between webpages in the panel it switches to https, I do not have https set up and would like to continue to use http instead

### Expected Behavior

I expect the panel to always use http

### Steps to Reproduce

Setup a panel with http
Attempt to change webpages

### Panel Version

1.11.3

### Wings Version

No wings

### Error Logs

```bash
https://pteropaste.com/j3t32x2a7vbt
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
show the line off the app_url in the .env file located in /var/www/pterodactyl

**Comment by Novampr** [comment]
i feel so stupid, i forgot to change that to the ip with http, sorry for the bother
