### ISSUE TITLE
The configuration file function in egg is missing

### ISSUE THREAD

**Issue by vlssu** [pterodactyl/panel#4849]
### Current Behavior

Writing the following in the config file just doesn't work
```
{
    "koishi.yml": {
        "parser": "yaml",
        "find": {
            "port": "{{server.build.default.port}}",
            "host": "0.0.0.0",
            "plugins.puppeteer.args[0]": "--no-sandbox",
            "plugins.puppeteer.args[1]": "--disable-setuid-sandbox"
        }
    }
}
```

### Expected Behavior

Normally it should run normally and output
```
plugins:
  puppeteer:
    args:
      - '--no-sandbox'
      - '--disable-setuid-sandbox'
```

### Steps to Reproduce

When writing an egg, write the following in the configuration file column
```
{
    "koishi.yml": {
        "parser": "yaml",
        "find": {
            "port": "{{server.build.default.port}}",
            "host": "0.0.0.0",
            "plugins.puppeteer.args[0]": "--no-sandbox",
            "plugins.puppeteer.args[1]": "--disable-setuid-sandbox"
        }
    }
}
```

### Panel Version

1.11.3

### Wings Version

1.11.7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
The configuration parser is for replacing values. Not adding ones to a file.

**Comment by vlssu** [comment]
I understand that what you said can only be used to replace the value, but the problem now is that according to my writing above, he will not work. The problem lies in [1], which seems to be not supported, but it is supported in my other software.

**Comment by vlssu** [comment]
> The configuration parser is for replacing values. Not adding ones to a file.

I understand that what you said can only be used to replace the value, but the problem now is that according to my writing above, he will not work. The problem lies in [1], which seems to be not supported, but it is supported in my other software.
