### ISSUE TITLE
500 | SERVER ERROR

### ISSUE THREAD

**Issue by progedaystreamer** [pterodactyl/panel#4851]
### Current Behavior

PHP is the latest version.
OS: Ubuntu 22.04

### Expected Behavior

Description of the error: I didn't do anything and the next day I get the error "500 | SERVER ERROR"

### Steps to Reproduce

 INFO: [Aug 27 08:18:15.144] writing log files to disk path=/var/log/pterodactyl/wings.log
 INFO: [Aug 27 08:18:15.144] loading configuration from file config_file=/etc/pterodactyl/config.yml
 INFO: [Aug 27 08:18:15.144] configured wings with system timezone timezone=Europe/Moscow
 INFO: [Aug 27 08:18:15.144] checking for pterodactyl system user username=pterodactyl
 INFO: [Aug 27 08:18:15.144] configured system user successfully gid=998 uid=999 username=pterodactyl
 INFO: [Aug 27 08:18:15.145] fetching list of servers from API
FATAL: [Aug 27 08:18:36.496] failed to load server configurations error=manager: failed to retrieve server configurations: Error response from Panel: UnexpectedValueException: An unexpected error was encountered while processing this request, please try again. (HTTP/500)

Stacktrace:
Error response from Panel: UnexpectedValueException: An unexpected error was encountered while processing this request, please try again. (HTTP/500)
github.com/pterodactyl/wings/remote.(*client).request.func1
	github.com/pterodactyl/wings/remote/http.go:163
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer.func1
	github.com/cenkalti/backoff/v4@v4.2.1/retry.go:18
github.com/cenkalti/backoff/v4.doRetryNotify[...]
	github.com/cenkalti/backoff/v4@v4.2.1/retry.go:88
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer
	github.com/cenkalti/backoff/v4@v4.2.1/retry.go:61
github.com/cenkalti/backoff/v4.RetryNotify
	github.com/cenkalti/backoff/v4@v4.2.1/retry.go:49
github.com/cenkalti/backoff/v4.Retry
	github.com/cenkalti/backoff/v4@v4.2.1/retry.go:38
github.com/pterodactyl/wings/remote.(*client).request
	github.com/pterodactyl/wings/remote/http.go:136
github.com/pterodactyl/wings/remote.(*client).Get
	github.com/pterodactyl/wings/remote/http.go:81
github.com/pterodactyl/wings/remote.(*client).getServersPaged
	github.com/pterodactyl/wings/remote/servers.go:201
github.com/pterodactyl/wings/remote.(*client).GetServers
	github.com/pterodactyl/wings/remote/servers.go:26
github.com/pterodactyl/wings/server.(*Manager).init
	github.com/pterodactyl/wings/server/manager.go:235
github.com/pterodactyl/wings/server.NewManager
	github.com/pterodactyl/wings/server/manager.go:36
github.com/pterodactyl/wings/cmd.rootCmdRun
	github.com/pterodactyl/wings/cmd/root.go:138
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/pterodactyl/wings/cmd.Execute
	github.com/pterodactyl/wings/cmd/root.go:71
main.main
	github.com/pterodactyl/wings/wings.go:17
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1594

manager: failed to retrieve server configurations

### Panel Version

1.11.3

### Wings Version

1.11.7

### Games and/or Eggs Affected

Minecraft, SCPSL

### Docker Image

Lost

### Error Logs

```bash
https://ptero.co/onuzopogys.yaml
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [ ] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
Your Panel is returning errors and you didn't provide the requested Panel logs. Without logs there's nothing indicating a bug in the software.

**Comment by Julicraft44** [comment]
As @Software-Noob already mentioned, more logs would be great.
Personal information from me: This happened once as my storage got too full and Pterodactyl couldn't write to the OS anymore.
