### ISSUE TITLE
500 | Server Error when trying to enter /admin/nodes page

### ISSUE THREAD

**Issue by Dandraghas** [pterodactyl/panel#4855]
### Current Behavior

i trying to migrate my pterodactyl apache server to docker, i dumped 'panel' database and imported it into docker container, now i wan't to change Nodes to point to correct ip address, but when i try to enter Nodes page it just give 500 error:
![image](https://github.com/pterodactyl/panel/assets/91272905/17d59a44-3a16-46ff-b086-73248125b46c)

i checked storage/logs, i found nothing in here.

### Expected Behavior

when entering 'Nodes' page it work normaly

### Steps to Reproduce

1. Go to domain.com/admin/nodes
2. See error

### Panel Version

1.11.3

### Wings Version

1.11.7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
Your .env file must also match as the ley is used to encrypt and load the db.

**Comment by Dandraghas** [comment]
> Your .env file must also match as the ley is used to encrypt and load the db.

Thanks. It seems to work now.
