### ISSUE TITLE
Auto Delete and reinstall server

### ISSUE THREAD

**Issue by CutieAshlynn** [pterodactyl/panel#4857]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add a feature in the servers where the admins and the users can delete and reinstall their server so what it does is when pressed the server will shutdown or if its offline it will stop then delete all server files such as plugins, world files, ops files, bans, and all other imported worlds and things then after everything that was needing deleted it will start a reinstall proccess where it will auto start the server and it will create things like a normal new minecraft server does.

This would resolve the issue of having the admins of the web panel needing to go delete and re create a new server for them and it can also be accessed by the user in the Settings tab and for the Admins in the Manage tab this would help out a lot.

### Describe the solution you'd like.

So it would be in both the settings tab for the user who owns the server under the reinstall server button and for the admin in the Manage tab in the servers admin page next to the Transfer server tab.

It would be used for helping people not needing to go into their files constantly when they want to fully delete everything and restart and with a click of 1 button it will stop all proccesses of the minecraft server and auto delete the files such as plugins, world files, ops files, bans, server.properties, usercache, whitelist, and then after its done it will auto start the server then the user can have a new clean server without needing to go through the hassal of deleting all files manually then starting it.

**Comment by parkervcp** [comment]
A user with access to the file browser can already delete their files, then run a reinstall. It's 2 steps instead of one. There is even a "select all" toggle in the file manager.

Admins are not required for this process.
