### ISSUE TITLE
Auto-deploy of node configuration not working

### ISSUE THREAD

**Issue by Linrador** [pterodactyl/panel#4859]
### Current Behavior

Executing `cd /etc/pterodactyl && sudo wings configure --panel-url http://panel.example.com --token <ptla_key> --node 1`
leads to the following error: `The authentication credentials provided were not valid.`

### Expected Behavior

Valid credentials, configuration will be applied automatically.

### Steps to Reproduce

1. Select a node
2. go to "Configuration"
3. Click on "Auto-Deploy" > "Generate Token"
4. Insert the command shown on screen into the console

### Panel Version

1.11.3

### Wings Version

1.11.7

### Error Logs

```bash
https://ptero.co/nokocaxedo
https://pteropaste.com/8ffk8owwnapt
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jcodeerd** [comment]
Fid you change your domain to http://panel.example.com?

**Comment by danny6167** [comment]
As your panel is over https your panel url in the command must be https.
If your panel is generating the command with http instead of https, please correct your APP_URL in your .env file

**Comment by Linrador** [comment]
Sorry for the late reply. This was indeed the issue. Thanks!
