### ISSUE TITLE
Adding an Rsync to a remote server on server deletion

### ISSUE THREAD

**Issue by TheFonix** [Pterodactyl/Panel#486]
So I've been trying to build this for quite a while and am slightly getting closer and closer.

Ive been inside the `delete.js` file on the daemon side for a while to try and integrate a zip and rsync to remote server but am having issues as I'm not sure how to define the path due to it being in variables I'm un familiar with, for example 

Here is what I've been trying to work on:

```
             delete_folder: ['delete_sftp', (r, callback) => {
              this.log.info('Attempting to Backup to the cloud');
              exec('"zip -r"  [ sftp.path ].zip /srv/daemon-data/);
                exec('rsync" -avz [ sftp.path ].zip dh-fs-01:/fs-data/backups);
                Fs.remove(Path.join(Config.get('sftp.path', '/srv/daemon-data'), this.json.user), callback);
            }],
```

Im not sure how i should use the `[sftp.path]` or if i should be using the `this.json.user` 

Any help would be great!

**Comment by TheFonix** [comment]
Just realised this should of probably been posted in the daemon repository not the Panel, my apologies

**Comment by schrej** [comment]
We handle both daemon and panel in this repo's issues, so no worries ;)

**Comment by DaneEveritt** [comment]
Please use the forums for this type of modification question as it is not a bug in the software or a feature request.

Thanks.
