### ISSUE TITLE
Get resources of all servers

### ISSUE THREAD

**Issue by LOENS2** [pterodactyl/panel#4863]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I'd like to have an API endpoint, that serves me all resources of all servers, so that i don't have to request the the '/resources' endoint of each server individually. That would save a lot of traffic.

### Describe the solution you'd like.

I imagine having a '/servers/resources' part that responds something like:

```
{
    "object": "list",
    "data": [
      {
        "object": "stats",
        "attributes": {
          "identifier": "1a7ce997",
          "uuid": "1a7ce997-259b-452e-8b4e-cecc464142ca",
          "name": "Gaming",
          "node": "Test",
          "current_state": "starting",
          "is_suspended": false,
          "resources": {
            "memory_bytes": 588701696,
            "cpu_absolute": 0,
            "disk_bytes": 130156361,
            "network_rx_bytes": 694220,
            "network_tx_bytes": 337090
          }
        }
      }
    ]
}
```

**Comment by devnote-dev** [comment]
The panel would be doing what you're describing anyway which wouldn't be useful for people who don't need that information on demand. This also leaves the Wings API susceptible to unintentional DDOS by the panel if you have a substantial number of active users.

**Comment by LOENS2** [comment]
Ok, that makes sense. I didn't look into how the panel request data from the nodes, but I assume that it's proxied based on what you told me.

**Comment by matthewpi** [comment]
Yeah, this is gonna create more problems not less.  I could see supporting a bulk resources per node to reduce the total amount of RTs to each node, but it gets very complicated to handle in the front-end as each server could be on a separate node.

I can say that we will not add a resources endpoint to get the status of multiple servers across multiple individual nodes.
