### ISSUE TITLE
Content Deadline exceeded! 

### ISSUE THREAD

**Issue by Coderbot4321** [pterodactyl/panel#4865]
### Current Behavior

When I run the config token for wings, it pause then says content deadline exceeded. The wings and panel are on the same machine and I am using a domain, but I see no request to my domain from wings. I also have tried pasting in the config file but, when I start wings it just freeze, and doesn't  connect then crashes. 

### Expected Behavior

Wings to connect and config, then a green heart on panel

### Steps to Reproduce

I have a domain for the panel  and node  set for there public Ip and the panel domain works just fine.

### Panel Version

1.11.3

### Wings Version

1.11.7

### Games and/or Eggs Affected

NA

### Docker Image

NA

### Error Logs

```bash
Unable to since it wont configure.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug in the software, please visit the Discord for configuration specific issues.
