### ISSUE TITLE
Unexpected Error!

### ISSUE THREAD

**Issue by YashrajTheDev** [pterodactyl/panel#4867]
When Opening Panel:
![IMG_20230922_113022](https://github.com/pterodactyl/panel/assets/128779095/74810f06-5c77-4ede-8606-8a53bcbd3a88)

Wings logs: https://ptero.co/mazytujowy
Panel Logs: https://pteropaste.com/ibftimhzfni8

Im getting this issue can anyone help me out please!

**Comment by Boy132** [comment]
This is not a bug in the software, please visit the Discord for configuration specific issues.
