### ISSUE TITLE
Delete account button (client-side)

### ISSUE THREAD

**Issue by wdhdev** [pterodactyl/panel#4870]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like a delete account button in the user settings page so if a client doesn't want their account any more they can delete it without having to contact a panel admin.

### Describe the solution you'd like.

The button should have a toggle in the admin settings so panel admins can decide whether or not they want to allow users to have access to the button. It should also be disabled if the user has servers attached to their account.

**Comment by alexevladgabriel** [comment]
I really like the idea of this feature, the only problem would be how can a user delete his account if he has servers too. 
Should him contact the administrator to delete his servers?

**Comment by wdhdev** [comment]
> It should also be disabled if the user has servers attached to their account.

**Comment by alexevladgabriel** [comment]
> > It should also be disabled if the user has servers attached to their account.

What I mean, is that I'm a client who wants to delete his account, but there are servers too and I can't delete the servers as client. I would like to delete my account and also that action to delete my servers.

**Comment by wdhdev** [comment]
> What I mean, is that I'm a client who wants to delete his account, but there are servers too and I can't delete the servers as client. I would like to delete my account and also that action to delete my servers.

Maybe add a button to the settings of a server so a client can delete the server, but maybe not a bulk delete button.

**Comment by lokerhp** [comment]
I think this approach can cause issues for hosting providers, eg a client deleting their account on the panel while the payment systems etc. still think its active, imho a nice feature but it will cause more problems than just contacting an A to disable your account i think.

**Comment by wdhdev** [comment]
There could be a setting on the admin panel so the button can be turned off if needed.
