### ISSUE TITLE
Wrong server requirements

### ISSUE THREAD

**Issue by xyronexus** [Pterodactyl/Panel#488]
There is first the curl command in # Add additional PHP packages.
And then in # Install Dependencies installed curl
i think you should install curl with # Add "add-apt-repository" command
like that
# Add "add-apt-repository" command
apt-get -y install software-properties-common curl

# Add additional PHP packages.
add-apt-repository -y ppa:ondrej/php
curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash

# Update APT
apt update

# Install Dependencies
apt-get -y install php7.1 php7.1-cli php7.1-gd php7.1-mysql php7.1-pdo php7.1-mbstring php7.1-tokenizer php7.1-bcmath php7.1-xml php7.1-curl php7.1-memcached php7.1-zip mariadb-server libapache2-mod-php apache2 tar unzip git memcached

**Comment by schrej** [comment]
Curl should be installed on your system already. It comes with nearly every Linux distribution by default.

**Comment by xyronexus** [comment]
Assumption is bad, especially when u want the minimal image system :)
Nonetheless i think that is important that everything is in right order.

**Comment by DaneEveritt** [comment]
This documentation is not meant to act as a replacement for basic linux administration skills. If curl is missing the person installing this panel is assumed to have enough knowledge to install it themselves based on the error thrown.
