### ISSUE TITLE
Console infinitely loads

### ISSUE THREAD

**Issue by USawesome** [pterodactyl/panel#4881]
### Current Behavior

All the server stats are available on the servers page, file manager works, and everything is normal, but when I go to a server's page, the console never loads
![image](https://github.com/pterodactyl/panel/assets/96547758/9165cd4b-e038-4a5b-9bd1-7f06ee93807f)
Unlike other issues similar, the file manager and all other functions work. I get this error in JS console repeatedly: 
<img width="476" alt="image" src="https://github.com/pterodactyl/panel/assets/96547758/26856e58-85a9-4de7-847b-3844a417c31e">
The docker container is running, but I can't view the console at all. The stats, including ram cpu, and other stats, do not appear.

### Expected Behavior

The console is supposed to load in <5 seconds and let my run commands

### Steps to Reproduce

1. Restart your node
2. Run a server
3. ~12 hrs later, the console is broken

### Panel Version

1.11.3

### Wings Version

1.11.7

### Games and/or Eggs Affected

All

### Docker Image

All

### Error Logs

```bash
https://ptero.co/xyfivahuza
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [ ] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug in the software, please visit the Discord for configuration specific issues.
