### ISSUE TITLE
 failed to load server configurations error=manager:

### ISSUE THREAD

**Issue by Withorcool** [pterodactyl/panel#4885]
### Current Behavior

after server restart i got error

### Expected Behavior

after server restart i got error

### Steps to Reproduce

idk

### Panel Version

1.4.0

### Wings Version

1.4.2

### Error Logs

```bash
https://ptero.co/xojavoxygi
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by gOOvER** [comment]
You Version is fucking old: 1.4.0
So i bet its not an issue with Ptero

Update to latest version

**Comment by Withorcool** [comment]
> You Version is fucking old: 1.4.0 So i bet its not an issue with Ptero
> 
> Update to latest version
i trped my incorect verison 
wings 1.11.6
and it happend after downloading mysql server

**Comment by Withorcool** [comment]
https://pteropaste.com/24pfljeljm6f/

**Comment by gOOvER** [comment]
> https://pteropaste.com/24pfljeljm6f/

not an issue with ptero:

`[2023-10-09 20:54:02] production.NOTICE: A query exception was encountered while trying to load settings from the database: SQLSTATE[HY000] [2002] Connection refused`

**Comment by Boy132** [comment]
Please use the Discord for configuration specific issues, this is not a bug.
Also, please put some effort into describing your problem...
