### ISSUE TITLE
Panel is not reading the server status after 10.10.2023

### ISSUE THREAD

**Issue by AlphineGhost** [pterodactyl/panel#4888]
### Current Behavior

The panel is not reading the servers on the main page of the panel and the wings is not reachable due to a ERR_SSL_PROTOCOL_ERROR and the Cloudflare + Lets Encrypt is all updated to the latest SSL version of the panel FQDN. 

### Expected Behavior

Should be able to work without any updates or patches.

### Steps to Reproduce

Use cloudflare and have SSL Connection enabled

### Panel Version

1.11.4

### Wings Version

1.11.8

### Games and/or Eggs Affected

Minecraft (Paper)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
https://pteropaste.com/b0a2cjlynj9l/
https://ptero.co/enecuvuhik
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
This is a mis-configuration on your part and not an issue with the software.
Please read https://pterodactyl.io/wings/1.0/configuration.html#enabling-cloudflare-proxy and use the discord for support
