### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by soyDaddy** [pterodactyl/panel#4891]
### Current Behavior

I'm trying to compile the update to 1.11.5 and it sais the console that has unsupported thing.

### Expected Behavior

Start the panel, it don't show anything

### Steps to Reproduce

I just was executing this command
``sudo yarn build:production``

### Panel Version

1.11.5

### Wings Version

1.11.8

### Error Logs

```bash
https://pteropaste.com/k9vba57u8mgs/
https://ptero.co/dynitepoki
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment]
If you are going to report an issue relating to development/building of the panel, please include more information other than "it doesn't work".

Please refer to <https://pterodactyl.io/community/customization/panel.html#build-panel-assets> for more information.
