### ISSUE TITLE
Get ssl certificate from let's encrypt for servers

### ISSUE THREAD

**Issue by haruki-py** [pterodactyl/panel#4892]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Automatically get an ssl certificate from lets encrypt when creating a server. Like https://optiklink.com when we create a web server, we automatically get an ssl certificate with that. I recently got an email that the certificate for that website is gonna expire from lets encrypt

### Describe the solution you'd like.

add a way where I can install a certbot or something like auto certificate when server is created like optiklink.com

### Additional context to this request.

Nothijg

**Comment by Boy132** [comment]
That would be a webhosting specific feature and Pterodactyl is _not_ meant for webhosting.

**Comment by haruki-py** [comment]
> That would be a webhosting specific feature and Pterodactyl is _not_ meant for webhosting.

I agree that pterodactyl isnt meant for web hosting but there is already a feature to use a specific ip or website. So why not add this too?

**Comment by matthewpi** [comment]
I don't see how we can easily do this.  Servers cannot complete an ACME challenge unless they are exposed on a domain.

if you want certificates get them yourself, there is no need for Pterodactyl to do this for you.

**Comment by haruki-py** [comment]
> I don't see how we can easily do this. Servers cannot complete an ACME challenge unless they are exposed on a domain.
> 
> if you want certificates get them yourself, there is no need for Pterodactyl to do this for you.

Yeah, that's correct. But it is completly possible as in https://optiklink.com. signup there and create a web server with whatever subdomain. after about 90 days I got an email from lets encrypt saying certificate for that website is gonna expire.

**Comment by haruki-py** [comment]
> I don't see how we can easily do this. Servers cannot complete an ACME challenge unless they are exposed on a domain.
> 
> if you want certificates get them yourself, there is no need for Pterodactyl to do this for you.

Also, it is not possible to get certificate from a trusted company in pterodactyl as it is read-only in some places.

**Comment by haruki-py** [comment]
I'll ask them if they can share it and send it in this issue if they tell

**Comment by haruki-py** [comment]
Another way would be to make system fully writable as then we can install the certbot and use it
