### ISSUE TITLE
Arbitrary data on Servers and Users

### ISSUE THREAD

**Issue by TekExplorer** [pterodactyl/panel#4895]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be nice to be able to store arbitrary json for users and servers via the API.

This could allow external services to store data relating to their own functions without needing to store them in the service itself.

### Describe the solution you'd like.

Create an api endpoint that allows updating json tied to a specific server or the current user, ideally with a `root` keyword so that other services using this api dont conflict, and i dont need to upload the *entire* json every time i update something (ie: `root: "featherdactyl.plugin_manager"`)

### Additional context to this request.

For example, if i wanted to implement server re-ordering in my Featherdactyl app, (without needing to modify every panel) i would need to store that order locally, which does not sync up with other instances of the app.

Additionally, I could implement a Plugin or Mod downloader with the ability to store where the plugin came from, and what the version downloaded was. Alongside #4894 I could confidently manage those files knowing no-one else has touched them. (or handle it if they have) This could be weakly worked around by creating a file on the server handling the data, but users can mess with that in the web panel or through sftp so i would like to avoid that.

**Comment by devnote-dev** [comment]
We already have external identifiers for users and servers, this feels like an unnecessary extra step and an excuse to offload information that should be handled by the end-user onto the panel.

> For example, if i wanted to implement server re-ordering in my Featherdactyl app, (without needing to modify every panel) i would need to store that order locally, which does not sync up with other instances of the app.

This is definitely doable with just the external identifier, and there are even ways to do so without it (but that's irrelevant to this issue).

**Comment by TekExplorer** [comment]
> We already have external identifiers for users and servers, this feels like an unnecessary extra step and an excuse to offload information that should be handled by the end-user onto the panel.

Not really the same. Identifiers are not the same as stored data.

Essentially what i'm asking for is a way to store data in the database without the need of an addon.
This would allow my app to do fancy stuff like a plugin/mod manager (instead of just a downloader) without needing panel admin interaction.

Its technically possible to store data per-server by just having a `.featherdactyl` file or something, but a. that kind of sucks - but its manageable i suppose, (if unreliable and bad UX) and b. no way to store per-user

That means if i wanted to have a user's preferences synced, or their (encrypted of course) api keys for say, Polymart, i just cant.

> This is definitely doable with just the external identifier, and there are even ways to do so without it (but that's irrelevant to this issue).

I dont think that identifier can be altered by the user? (and if it can be, i would assume its disabled on many panels)

I also really dont want to screw with the external identifier, as that's usually used by billing systems, and i'm not about to go and make them all use a massive shared json string.

**Comment by devnote-dev** [comment]
> Essentially what i'm asking for is a way to store data in the database without the need of an addon.
This would allow my app to do fancy stuff like a plugin/mod manager (instead of just a downloader) without needing panel admin interaction.

Why should that be the job of the panel? The app having full responsibility over the data removes the need to have panel admin interaction entirely. Also, what if someone decides to change said data via the API?

> Its technically possible to store data per-server by just having a `.featherdactyl` file or something, but a. that kind of sucks - but its manageable i suppose, (if unreliable and bad UX) and b. no way to store per-user

A. The only way it could be unreliable or bad UX is if you make it like that. Large scale applications like VSCode manage just fine.
B. That is down to how you structure your code and stateful information in your app, but there is definitely a way.

> I dont think that identifier can be altered by the user? (and if it can be, i would assume its disabled on many panels)

Not via the client API, no. I'm sure a workaround could be done using the application API too, but if not then as I said it's not the only way to handle such data for your app.

**Comment by TekExplorer** [comment]
> Why should that be the job of the panel? The app having full responsibility over the data removes the need to have panel admin interaction entirely. Also, what if someone decides to change said data via the API?

The app having full responsibility over the data would then result in desyncs if you, say, did something in the desktop app, and then went to the mobile app and the change just isnt there (such as reordering the server list)

Not without then needing me to implement my own sync accounts, which for the sake of trust and convenience, i would rather avoid.

If someone changed the data, then that's the risk. why would someone go in and alter anything under the `featherdactyl` (for instance) key? if they did, then the user will quickly find that, either it broke and they can complain to whoever did that, or you'll discover that, perhaps it was an addon making use of the re-ordered server list to sync with the app's setup, or a plugin manager using my app's data, working together in ways that otherwise wouldnt be possible.

Addon compatibility would also not be possible if the app had to store the data elsewhere without the addons then needing to implement my accounts

Its data about the user/server in relation to the panel, so it should be _on_ the panel

> A. The only way it could be unreliable or bad UX is if you make it like that. Large scale applications like VSCode manage just fine.
B. That is down to how you structure your code and stateful information in your app, but there is definitely a way.

I suppose. i just dont really like the idea of putting a file on people's servers, since other users might see it, not know what it is, and delete it.

Then again, i suppose thats acceptable for a workaround. That still begs the question of user-specific data across the panel

**Comment by devnote-dev** [comment]
> The app having full responsibility over the data would then result in desyncs if you, say, did something in the desktop app, and then went to the mobile app and the change just isnt there (such as reordering the server list)

This is the case with most apps with decentralised syncing capabilities, unless you're Apple or Microsoft and decide to force device syncing.

> Not without then needing me to implement my own sync accounts, which for the sake of trust and convenience, i would rather avoid.

This isn't relevant to this issue, but your app has customisable themes which would also be affected by syncing unless you were to store such information in the panel too, which again is not a good idea.

> If someone changed the data, then that's the risk. why would someone go in and alter anything under the `featherdactyl` (for instance) key?

It doesn't matter why, just the fact that it's possible means that there will be people that will try and inevitably succeed. There is also no regard for whether users would like their preferences publicly available via the API, nor is there any consideration for scalability. How large can this arbitrary data be before it's too large? What effect would that have on businesses using the panel for their hosting services? What prevents a malicious actor from simply purging all user data that they have access to via server relationships?

> Its data about the user/server in relation to the panel, so it should be on the panel

It's data about the user/server in relation to the panel _that it does not need nor does it benefit from_, so it should be on the app.

> I suppose. i just dont really like the idea of putting a file on people's servers, since other users might see it, not know what it is, and delete it.

Then don't, it's not your only option. If you're looking for ideas then I suggest you research how other large scale applications and CLI tools handle such data, but this really isn't the way.

**Comment by matthewpi** [comment]
I understand why you would want something like this, but it seems like a very bad idea.  Providing a way for users to just store any amount of data alongside their server or user just seems like a nightmare waiting to happen.  It seems like a lot of the things you are trying to do are better served by building an addon for the panel, or implementing official APIs and fields for.

In your example of server sorting, the sort order should be stored with or related to individual users and then will need to be taken into account when fetching servers, otherwise sorting wouldn't work when pagination is used.  This is again something that would be better to implement officially (even if it's just in the backend) then resulting to some janky arbitrary data storage that results in you needing to manually find a way to sort servers.

Unless you have specific suggestions, it seems like a lot of this is going to be used to store large amounts of data on a server without it being structured or validated.  I will not be adding the ability to store arbitrary information like this, as least not for use by non-admin users.
