### ISSUE TITLE
HTTP authentication checking

### ISSUE THREAD

**Issue by Krzywson** [pterodactyl/panel#4896]
### Current Behavior

I run docker-compose up -d, all goes fine.
In log i receive CRIT Server 'unix_http_server' running without any HTTP authentication checking
Tried 
- add username and password in etc/supervisord.conf
- changed to inet_http_server

When I add username and password to unix_http_server i see only "Starting supervisord.", but after 1 hour i dont get anything

Did anyone have that problem to?

### Expected Behavior

Working

### Steps to Reproduce

I run docker-compose up -d, all goes fine.

### Panel Version

latest

### Wings Version

latest

### Error Logs

```bash
CRIT Server 'unix_http_server' running without any HTTP authentication checking
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment]
That message is expected, you can ignore it.  If you have any issues it's unrelated to that message.
