### ISSUE TITLE
FossBilling Extension (I don't know if this is appropriate)

### ISSUE THREAD

**Issue by MrCerise** [pterodactyl/panel#4899]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add a pterodactyl module to FossBilling

### Describe the solution you'd like.

Idk what else

**Comment by PadowYT2** [comment]
FossBilling should be the one to make a module, not they way around

**Comment by MrCerise** [comment]
But why Pterodacty did the whmcs module ?

**Comment by PadowYT2** [comment]
> But why Pterodacty did the whmcs module ?

I don't know the actual reason, but WHMCS is really popular. For example, Pterodactyl cannot make a module, that isn't that popular. If FossBilling is really in need for a connection, they must make it

**Comment by MCrashCraft** [comment]
This is what FOSSBilling has to say "FOSSBilling does not support Pterodactyl. The FOSSBilling team currently has no plans to provide official support for Pterodactyl, and they are focusing on improving the stability and usability of FOSSBilling. However, the community is welcome to build an integration of their own for FOSSBilling"

**Comment by PadowYT2** [comment]
> This is what FOSSBilling has to say "FOSSBilling does not support Pterodactyl. The FOSSBilling team currently has no plans to provide official support for Pterodactyl, and they are focusing on improving the stability and usability of FOSSBilling. However, the community is welcome to build an integration of their own for FOSSBilling"

This means that someone that can and wants to make FOSSBilling integration can do it. Pterodactyl isn't required to and no one probably wants to make the integration

**Comment by matthewpi** [comment]
Unless someone in the community or FossBilling themselves makes one, it isn't going to happen.

The WHMCS module started as a community project but was adopted as official, only one of the project team members is responsible for it.

**Comment by SuperHori** [comment]
Hello! I started development of a Pterodactyl module for FossBilling. Although I don't have advanced PHP experience, I'm doing my best to build it as well as possible, also with the help of someone who has more advanced knowledge. In the next few days we will carry out some tests, and then we will officially announce the progress made.
