### ISSUE TITLE
Disk Space Overallocate is equal

### ISSUE THREAD

**Issue by cynthiagruben** [pterodactyl/panel#4900]
### Current Behavior

You can allocate more disk space via Api than the server actually has. Even if the overallocate is set to 0, see the pictures.

<img width="841" alt="image" src="https://github.com/pterodactyl/panel/assets/58784842/f4d96c3d-8e95-46d7-b341-2e722a284f62">
<img width="558" alt="image" src="https://github.com/pterodactyl/panel/assets/58784842/e9661b90-1762-4f83-b008-0929c332b165">

### Expected Behavior

It should be the case that you get an error back as soon as the maximum is reached.

### Steps to Reproduce

Create a few servers via Api that have more disk space than the node has.

### Panel Version

1.11.5/1.11.3

### Wings Version

1.11.8/1.11.7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TrixterTheTux** [comment]
The overallocation limit is only checked when using `deploy` (which behind the scenes chooses allocations from nodes that have enough resources), otherwise, this behavior matches manually creating the server directly in the panel
