### ISSUE TITLE
network_mtu config causes "docker OCI failed to add interface to sandbox"

### ISSUE THREAD

**Issue by Legendary4226** [pterodactyl/panel#4902]
### Current Behavior

Error Event [b7b6024d-5b98-4856-8d74-e3a61001c69f]: environment/docker: failed to start container: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: failed to add interface veth32cd1c7 to sandbox: error setting interface "veth32cd1c7" IPv6 to fdba:17c8:6c94::1/64: invalid argument: unknown

### Expected Behavior

The container should start with an MTU of XXXX.

### Steps to Reproduce

Do a fresh install of Ubuntu 20.04 then a fresh install of Docker (with the official manual installation or the pterodactyl one) and then a fresh install of Wings.

Edit /etc/pterodactyl/config.yml, change 'network_mtu' to something different than the default value (1500), in my case I was using 1250.

To be sure of what i'm saying, I created a VM on my computer with VMWare, on Ubuntu 22.04 this time. Did the same installation process plus the setup of the Panel (so the panel is also at the latest version). And I got the same error after modifying this MTU setting !

### Panel Version

1.11.3

### Wings Version

1.11.8

### Games and/or Eggs Affected

All

### Error Logs

```bash
https://ptero.co/guwadodiva
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
An MTU of 1500 is the most common standard globally. The number of people who are on a different MTU has been extremely small. The fact that there are other MTU's is why it's configurable.

**Comment by Legendary4226** [comment]
In my case I need to lower the MTU, else the network does not work at all.

**Comment by Legendary4226** [comment]
Hi, do you think you gonna patch this bug ? Or do I need to find an alternative by myself ?

**Comment by parkervcp** [comment]
@Legendary4226 You can change the network mtu for the containers by updating the wings `config.yml`. You would replace the 1500 here with the value you need. 

```
docker:
  network:
    network_mtu: 1500
```

As I stated. This is not a bug. That is just a default value that you can change.

**Comment by Legendary4226** [comment]
That's exactly what I've done and this setting is the cause of the error "failed to add interface veth32cd1c7 to sandbox: error setting interface "veth32cd1c7" IPv6 to fdba:17c8:6c94::1/64: invalid argument: unknown"

**Comment by parkervcp** [comment]
You may need to remove the pterodactyl_nw that was initially created by wings when it started.

**Comment by Legendary4226** [comment]
I done that.
What I exactly do is :

- *Install docker with official instructions
- *Install wings with official instructions
- After setting up wings, I edit /etc/pterodactyl/config.yml to adjust the MTU
- Then I use docker network remove pterodactyl_nw
- Then I start wings, it starts without error, but I get the error when I start a container with the panel

**Comment by Legendary4226** [comment]
Hi, did you tried to reproduce the bug ?

**Comment by parkervcp** [comment]
I can't reproduce this bug. None of my systems are on an MTU that isn't 1500. We have seen this issue before and setting the mtu in config resolved the issue for those others.

You might be able to check which MTU you have on your system by running `ip addr | grep mtu`

**Comment by Legendary4226** [comment]
No, I know what MTU I exactly need, but there is a bug with WINGS that does not allow me to set the MTU.
I don't understand where I'm not clear.
So on your system, try to set this MTU setting, stop wings, remove the network with docker and restart wings. If the bug is confirmed, your containers shouldn't be able to start.

**Comment by Legendary4226** [comment]
Hi, any update ?
