### ISSUE TITLE
Add an API endpoint for adding sub users

### ISSUE THREAD

**Issue by OddDevelopment** [pterodactyl/panel#4904]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A way to add sub users to a server using the pterodactyl API

### Describe the solution you'd like.

Add an API endpoint to add sub users to a server

**Comment by trenutoo** [comment]
Already exists in the client API `POST /api/client/servers/:server/users` and is documented in the [dashflo API docs.](https://dashflo.net/docs/api/pterodactyl/v1/)
