### ISSUE TITLE
Timezone is an hour off (perhaps daylight saving)

### ISSUE THREAD

**Issue by IvMisticos** [pterodactyl/panel#4906]
### Current Behavior

When timezone is set to one that changes for daylight saving/not, i.e `America/New_York`, schedules seem to run an hour later, and activity log is off as well.

When using schedules that run every minute (`* * * * *`), they don't run at all for an hour, and only then fire in an hour. The run now button seems to work fine. When using schedule with a set hour it also runs an hour off.

Activity log also shows actions performed right now as 1 hour ago.

`pteroq` and `redis-server` are running, tried restarting pteroq and running php artisan thing to process the queue.

### Expected Behavior

Actions performed now should be stored as performed now, and schedules must run on times specified.

### Steps to Reproduce

1. Set timezone in `.env` to `APP_TIMEZONE=America/New_York`
2. Create a schedule that runs every minute `* * * * *`
3. Wait for a few minutes to see nothing happens
4. Try doing some changes such as run a reinstall
5. Note that the action above in Activity log is an hour ago
6. After waiting for an hour, the schedule begins working fine

### Panel Version

1.11.3

### Wings Version

1.11.4

### Error Logs

```bash
- (nothing in laravel, wings diagnostics spams with no logs and only [redacted]r[redacted]e (etc) inside)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by IvMisticos** [comment]
Worth mentioning that panel server has timezone set to `Etc/UTC` but this should not matter since we are using the one from `.env`.

**Comment by Boy132** [comment]
Please update your [panel](https://pterodactyl.io/panel/1.0/updating.html) (and [wings](https://pterodactyl.io/wings/1.0/upgrading.html)) to the latest version and see if the problem persists.
