### ISSUE TITLE
panel won't connect to external mysql database

### ISSUE THREAD

**Issue by OfficialShinu** [pterodactyl/panel#4907]
### Current Behavior

random ips for privacy

mysql server ip; 192.168.0.1
panel server ip; 192.168.0.2

testing the connection with defined userinfo from mysql i can succesfully connect from the panel server with a telnet request

when trying from the panel i get an error 
There was an error while trying to connect to the host or while executing a query: "SQLSTATE[HY000] [1044] Access denied for user 'pterodactyluser'@'192.168.0.2' to database 'mysql' (SQL: SELECT 1 FROM dual)"

i entered the external mysql ip but in the error it states the panel ip

### Expected Behavior

panel should connect to the external sql server

### Steps to Reproduce

both servers have freshly been installed run the latest software firewalls are configured 
try access external sql server on another server with the panel

### Panel Version

1.11.3

### Wings Version

1.11.7

### Games and/or Eggs Affected

/

### Docker Image

/

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Sharktheone** [comment]
This is not a bug. It is most likely, you just entered a wrong password / used another user. Please visit the [discord](https://discord.gg/pterodactyl) for help.
