### ISSUE TITLE
Backup file is in chrome a malware

### ISSUE THREAD

**Issue by Bubbelwubbel** [pterodactyl/panel#4909]
### Current Behavior

If there is no SSL certificate, the file will show up as malware in Chrome and Chrome will scan it.

### Expected Behavior

File downloads normally and Chrome has no problem

### Steps to Reproduce

Images is in german.
![image](https://github.com/pterodactyl/panel/assets/65186341/0b74551a-3efc-4df2-b5f9-344a79ce6481)
![image](https://github.com/pterodactyl/panel/assets/65186341/3c701425-e165-4c26-b894-5e6cd07801e5)

English text:
1 Picture: Check for Malware - Suspicious
2 Picture: Scanning...

### Panel Version

1.11.5

### Wings Version

1.11.8

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by PadowYT2** [comment]
Probably because you don't have an SSL and chrome thinks it is a virus, not a Pterodactyl problem
