### ISSUE TITLE
Server Transfer

### ISSUE THREAD

**Issue by MxLNinjaz** [pterodactyl/panel#4914]
### Current Behavior

Server transfer is no longer working on latest update 1.11.5, it says server is transferring and does nothing.

### Expected Behavior

Server Transfers to another node.

### Steps to Reproduce

Create a server and try and transfer to another node.

### Panel Version

1.11.5

### Wings Version

1.11.8

### Games and/or Eggs Affected

All

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jcodeerd** [comment]
How are we supposed to help you without logs

**Comment by Xeravax** [comment]
@MxLNinjaz 
Your wings (`wings debug`) should be able to give us logs, without them we're unable to even see "Oh hey! It's an issue with XYZ"

**Comment by Boy132** [comment]
Please see https://github.com/pterodactyl/panel/issues/4696#issuecomment-1809727958
