### ISSUE TITLE
Custom maintenance messages screen

### ISSUE THREAD

**Issue by CutieAshlynn** [pterodactyl/panel#4923]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

So currently when you want to take the panel down for maintenace you need to go into the command line and use the command to turn it offline but, what i was thinking of is keeping all admins of the panel allowed to still see it and have full control and all regular users who has servers will get a screen with a custom message from what the admins inputed in the admin panel and get rid of the 503 service unavaliable.

### Describe the solution you'd like.

So for the admins they get to still have full control, access to the panel even when under maintenance and all regular users get a screen with the custom maintenance message that the admins set and have a section in the admin dashboard where the admins of the panel can configure the maintenance time and the message and wheather to turn it on or off.

For the users with what they see on the maintenance page is a title that says 

Under Maintenance!
(Custom message here from what the admins set)
(Time when we will be back online)

For the time im thinking add a option in the maintenance config page wheather we want to set a start time and a end time for the maintenance to auto enable and auto disable or we do not want to use the timer option and have it unknown to users when the panel will be back online.

Users see this below if the timer is not set or not turned on for use

Under Maintenance!
(Custom message here from what the admins set)

This will make it super easy for the admins and users to understand whats going on. mainly the users.

For updating the panel keep the same way it needs to be for the command line.

### Additional context to this request.

I want to see this feature added so badly, if you want to work something out with this feature ill comment below and we can do our best on the feature.

**Comment by expxx** [comment]
You can use `php artisan down --secret="some_secret"` to bypass maintenance, just go to yourpanel.com/some_secret and you'll be through.

Error message, you can put in /var/www/pterodactyl/resource/errors/<code>.blade.php iirc, just put the html you want visible there and the screen will read from that

**Comment by CutieAshlynn** [comment]
> You can use `php artisan down --secret="some_secret"` to bypass maintenance, just go to yourpanel.com/some_secret and you'll be through.
> 
> Error message, you can put in /var/www/pterodactyl/resource/errors/`.blade.php iirc, just put the html you want visible there and the screen will read from that`

I went to that file location i only got to /var/www/pterodactyl/ and did not see the other 2 directories you were saying 
resource/errors/ they are not there at all i see the resources directory but, nothing inside there says anything about errors
also what is .blade.php iirc? I have never heard or have seen that before.

**Comment by Boy132** [comment]
> > You can use `php artisan down --secret="some_secret"` to bypass maintenance, just go to yourpanel.com/some_secret and you'll be through.
> > Error message, you can put in /var/www/pterodactyl/resource/errors/`.blade.php iirc, just put the html you want visible there and the screen will read from that`
> 
> I went to that file location i only got to /var/www/pterodactyl/ and did not see the other 2 directories you were saying resource/errors/ they are not there at all i see the resources directory but, nothing inside there says anything about errors also what is .blade.php iirc? I have never heard or have seen that before.

The file path is `/var/www/pterodactyl/resources/views/errors/503.blade.php`. It doesn't exist by default, you'll have to create it.
For more info google "laravel custom 503 page".

**Comment by CutieAshlynn** [comment]
Thank you this worked for me.
