### ISSUE TITLE
[Wings] Memory unit convert : 1000 ? 1024 ?

### ISSUE THREAD

**Issue by shugen002** [pterodactyl/panel#4925]
### Current Behavior

It convert 4096MiB into 4096000000 B

### Expected Behavior

It convert 4096MiB into 4294967296 B

### Steps to Reproduce

create a server with 4096MiB memory and check the reservation memory of the container with `docker inspect` `HostConfig.MemoryReservation`

### Panel Version

1.11.5

### Wings Version

1.11.8

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by shugen002** [comment]
Related Code:

https://github.com/pterodactyl/panel/blob/v1.11.5/resources/views/admin/servers/new.blade.php#L171-L174
https://github.com/pterodactyl/panel/blob/v1.11.5/resources/scripts/lib/formatters.spec.ts#L32


https://github.com/pterodactyl/wings/blob/develop/environment/settings.go#L82
https://github.com/pterodactyl/wings/blob/develop/environment/settings.go#L93
https://github.com/pterodactyl/wings/blob/develop/environment/settings.go#L108

**Comment by danny6167** [comment]
Fixed by https://github.com/pterodactyl/wings/pull/190 and will be included in the next release of wings.
