### ISSUE TITLE
Issue with daemons not being able to contact

### ISSUE THREAD

**Issue by nelupet** [Pterodactyl/Panel#493]
I'm getting a huge issue on all my nodes connected to Pterodactyl, and them not being able to start up.

The log from systemctl is this. I tried my best to copy and paste everything given my remote connection setup:

> pteronode@0.4.2 start /srv/daemon
> node src/index.js | node_modules/bunyan/bin/bunyan -o short

18:07:48.054Z  INFO wings: + ------------------------------------ +
18:07:48.057Z  INFO wings: | Running Pterodactyl Daemon v0.4.2    |
18:07:48.058Z  INFO wings: |        https://pterodactyl.io        |
18:07:48.058Z  INFO wings: |  Copyright 2015 - 2017 Dane Everitt  |
18:07:48.058Z  INFO wings: + ------------------------------------ +
18:07:48.058Z  INFO wings: Loading modules, this could take a few seconds.
18:07:48.617Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
18:07:48.632Z  INFO wings: Checking container networking environment...
18:07:48.642Z  INFO wings: Attempting to start SFTP service container...
18:07:48.664Z  INFO wings: Contacting panel to retrieve a list of currrent services available to the node.
18:07:48.712Z  INFO wings: Found network interface for daemon: pterodactyl_nw
18:07:48.728Z FATAL wings: A fatal error caused the daemon to abort the startup. (additional={})
    SyntaxError: Unexpected token < in JSON at position 0
        at Object.parse (native)
        at Request.ex [as _callback] (/srv/daemon/src/controllers/service.js:97:40)
        at Request.self.callback (/srv/daemon/node_modules/request/request.js:188:22)
        at emitTwo (events.js:106:13)
        at Request.emit (events.js:191:7)
        at Request.<anonymous> (/srv/daemon/node_modules/request/request.js:1171:10)
        at emitOne (events.js:96:13)
        at Request.emit (events.js:188:7)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/request/request.js:1091:12)
        at IncomingMessage.g (events.js:292:16)
18:07:48.728Z ERROR wings: You should forcibly quit this process and attempt to fix the issue.
18:07:48.733Z  INFO wings: SFTP container successfully booted.
18:07:48.912Z  INFO wings: Pterodactyl Daemon is up-to-date!

**Comment by schrej** [comment]
Did you run `php artisan db:seed` when setting up the panel?

**Comment by nelupet** [comment]
php artisan db:seed
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Seeding: MinecraftServiceTableSeeder
Seeding: SourceServiceTableSeeder
Seeding: TerrariaServiceTableSeeder
Seeding: VoiceServiceTableSeeder

**Comment by DaneEveritt** [comment]
Re-download the files, chances are one of the files got corrupted.
