### ISSUE TITLE
Upgrading Wings moves the default location back to /var/lib/pterodactyl/volumes and not whatever was set.

### ISSUE THREAD

**Issue by VanillaChan6571** [pterodactyl/panel#4931]
### Current Behavior

When upgrading wings. The volume location if set custom like `/panel/volumes` it will revert back to the default location volumes of `/var/lib/pterodactyl/volumes` because configuration believes its always located `/var/lib/pterodactyl/volumes` and not whatever the config says and no way to overwrite `admin/nodes/view/XYZ/configuration`

### Expected Behavior

It should never reset or move the default location of volumes when upgrading.

### Steps to Reproduce

1. Upgrade Wings
2. All files go missing
3. Get Confused because wings should never move location of volumes.
4. Check the /etc/pterodactyl/config.yml
5. Sure enough it moved the location back to `/var/lib/pterodactyl/volumes`

### Panel Version

1.11.3

### Wings Version

1.11.8

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
N/A due to a wings config issue not a log issue.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
You need to set the data path in the database if you didn't set it right when you created the node, or moved it after the fact. 

Wings will update parts of its configuration from the panel when it restarts. it's not defaulting, it's using the value you have set for the node in the database

**Comment by VanillaChan6571** [comment]
@danny6167 what? There is no database for "nodes"

**Comment by danny6167** [comment]
> @danny6167 what? There is no database for "nodes"

Of course there is. How else do you think the panel keeps a record of its nodes.

**Comment by VanillaChan6571** [comment]
> > @danny6167 what? There is no database for "nodes"
> 
> Of course there is. How else do you think the panel keeps a record of its nodes.

The panel keeps the nodes records in the config.yml, the nodes have no database connection except api calls to the master webhost. YOU have no idea what your talking about.

**Comment by danny6167** [comment]
> > > @danny6167 what? There is no database for "nodes"
> > 
> > 
> > Of course there is. How else do you think the panel keeps a record of its nodes.
> 
> The panel keeps the nodes records in the config.yml, the nodes have no database connection except api calls to the master webhost. YOU have no idea what your talking about.

Actually you have no idea what you are talking about.

The config.yml is there to store the basic settings for the wings service to start up. But the panel doesn't read it at all, it stores all of it's information in the panels database.

**Comment by danny6167** [comment]
![image](https://github.com/pterodactyl/panel/assets/388231/ba7c7c8d-8b7b-4afc-a79d-24bdbceb15de)

**Comment by VanillaChan6571** [comment]
> > > > @danny6167 what? There is no database for "nodes"
> > > 
> > > 
> > > Of course there is. How else do you think the panel keeps a record of its nodes.
> > 
> > 
> > The panel keeps the nodes records in the config.yml, the nodes have no database connection except api calls to the master webhost. YOU have no idea what your talking about.
> 
> Actually you have no idea what you are talking about.
> 
> The config.yml is there to store the basic settings for the wings service to start up. But the panel doesn't read it at all, it stores all of it's information in the panels database.

No I do as you didnt even read what I posted. "/var/lib/pterodactyl/volumes" is located in config.yml and NO WHERE in any database. Your talking about something else.

**Comment by VanillaChan6571** [comment]
> ![image](https://private-user-images.githubusercontent.com/388231/285641627-ba7c7c8d-8b7b-4afc-a79d-24bdbceb15de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTE2NzMsIm5iZiI6MTcwMDk5MTM3MywicGF0aCI6Ii8zODgyMzEvMjg1NjQxNjI3LWJhN2M3YzhkLThiN2ItNGFmYy1hNzlkLTI0YmRiY2ViMTVkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQwOTM2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWI5Y2I5M2ZiZTBlZTE4OGI0YzYzZjBiYjZjNWRhMGQxNGE2ZWQ1MmQ5OTAyOWU0YjBkYjhhOTUwYTc5NTQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KN47OGDg2FSIz7XF8EqK8CpccatKR306myLtO_8lI6Q)

I do not have a "demonBase" as it marked as - for every node.

**Comment by danny6167** [comment]
I just showed you where it is in the database. 

As I explained before, when wings pulls updated config data from the panel it will update your config.yml with details from the panel database.

At no point did I ever say wings had a direct connection to the panels database. It is done when wings calls the panels API for settings.

**Comment by VanillaChan6571** [comment]
So basically editing the config is useless and needs to be updated via database which has a one way talking point which in the dumbest way to store volume locations as it should be called on the config when requesting wings. or when wings restarts it should send a updated copy to the database no matter what

**Comment by danny6167** [comment]
For some values, yes. you need to update them in the panels database.

You can also set `ignore_panel_config_updates` to true in your wings config and it will ignore config updates from the panel.
