### ISSUE TITLE
Panel crashes when making a new database

### ISSUE THREAD

**Issue by CutieAshlynn** [pterodactyl/panel#4932]
### Current Behavior

When i go to add a database to the panel in the admin menu i input everything correctly then i click create and the page will get stuck on loading then everything becomes fully unresponsive to the point your requiered to restart your system that you host the panel on just to get it to respond again.

### Expected Behavior

to create a data base without the panel crashing and not needing to restart my main system

### Steps to Reproduce

1. make a database 
2. go to the admin menu
3. click databases
4. click the create button 
5. enter in the info for the database
6. then click create
7. it should get stuck on loading the panel and need a full system restart to make the panel respond

### Panel Version

1.11.5

### Wings Version

1.11.8

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug in the software, please visit the [Discord](https://discord.gg/pterodactyl) for configuration specific issues.
