### ISSUE TITLE
Conflict with plesk during installation 

### ISSUE THREAD

**Issue by Raayann** [pterodactyl/panel#4934]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hi, I have a conflict with apache when installing panel, I would like to use plesk and pterodactyl, is this possible?

Plesk for the web and mysql

Ptero for vm and game server

### Describe the solution you'd like.

The ideal solution would be to use a specific port for pterodactyl and redirect with proxymod.

**Comment by QuintenQVD0** [comment]
Pterodactyl needs its own vm and can never run togheter with something like plesk as it rakes over the whole webserver.

**Comment by Boy132** [comment]
Yes, it is possible to use pterodactyl and plesk. But you are on your own figuring out how and generally we advise against that.

> Ptero for vm [...]

Also keep in mind that Pterodactyl is _not_ a hypervisor and you should not use it to host virtual servers.
