### ISSUE TITLE
Seperate permission for download

### ISSUE THREAD

**Issue by LucidAPs** [pterodactyl/panel#4935]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like for users to be able to read the files and their contents but I dont want them to be able to download them, so please make it a separete permission so we can have control over that.

### Describe the solution you'd like.

Explained.

**Comment by parkervcp** [comment]
Being able to read a file is essentially downloading them.

**Comment by Jcodeerd** [comment]
Copy paste and you've "downloaded" it
