### ISSUE TITLE
P_SERVER_ALLOCATION_LIMIT always 0.000000

### ISSUE THREAD

**Issue by shanecaf** [pterodactyl/panel#4936]
### Current Behavior

P_SERVER_ALLOCATION_LIMIT is always set to 0.000000, even though there may be multiple ports on a server.

### Expected Behavior

Expected it to be the current number of ports available for a server.

### Steps to Reproduce

- Create a server
- Change the startup command to printenv
- Start the server

### Panel Version

1.11.5, 1.11.3

### Wings Version

1.11.8, 1.11.6

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
`P_SERVER_ALLOCATION_LIMIT` is the allocation limit you set in the build configuration of the server. It's not the actual amount of allocations.
![image](https://github.com/pterodactyl/panel/assets/8203120/c3e5c347-c5f5-4e58-b916-e7d89c0c98b5)
![image](https://github.com/pterodactyl/panel/assets/8203120/7027ea50-8c20-4c48-9463-ab6c9b4a598d)

**Comment by shanecaf** [comment]
Sorry about this, I need to learn how to read again, lol.

**Comment by matthewpi** [comment]
That value however should be an integer, not a float
