### ISSUE TITLE
Console not rendering properly, can only see unreadable rainbow colour chatacters

### ISSUE THREAD

**Issue by GroupXyz1** [pterodactyl/panel#4948]
### Current Behavior

Console shows just as unreadable Rainbow Characters (see picture) in LibreWolf browser.
![Screenshot (795)](https://github.com/pterodactyl/panel/assets/122233274/64ab1c0b-460a-40ea-b8c9-923f497867ac)

### Expected Behavior

properly vievable Console 

### Steps to Reproduce

Open a Pterodactyl Console on the Librewolf Browser

### Panel Version

idk (am not the hoster, sorry, they dont answer)

### Wings Version

idk (am not the hoster, sorry, they dont answer)

### Games and/or Eggs Affected

Minecraft (Any Version)

### Docker Image

java 17

### Error Logs

```bash
Don't need/have Logs cause its a rendering issue/incompatability with the Browser
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Sharktheone** [comment]
I had this problem once. This is not a problem with the panel itself, but with your browser configuration. Not sure, what the exact setting was, but I think it had something to do with the fingerprinting.

**Comment by Boy132** [comment]
That's a problem with your browser, not a bug with pterodactyl. You need to enable canvas.
For further help please visit the [Discord](https://discord.gg/pterodactyl).

_PS: Also, if you're not the panel owner then please contact your hoster first. If they haven't answered yet you wait._

**Comment by GroupXyz1** [comment]
ok i try to contact the hoster, think he wont answer but if its a setting theres nothing y'all can do for me :(

**Comment by Boy132** [comment]
> ok i try to contact the hoster, think he wont answer but if its a setting theres nothing y'all can do for me :(

In this case it's a setting in your browser. Google "firefox enable canvas"/ "librewolf enable canvas".
