### ISSUE TITLE
Ban on discord

### ISSUE THREAD

**Issue by Stuk3y** [pterodactyl/panel#4949]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hello first i want to apologize for my action i didnt know  thath i cant send thath i will like to get unban if its possible

### Describe the solution you'd like.

Hello first i want to apologize for my action i didnt know  thath i cant send thath i will like to get unban if its possible

**Comment by TrixterTheTux** [comment]
What’s your Discord username?

**Comment by Stuk3y** [comment]
@stuk3y

**Comment by Stuk3y** [comment]
can i get the unban?

**Comment by Stuk3y** [comment]
@TrixterTheTux

**Comment by Pvpsmash** [comment]
lol
