### ISSUE TITLE
Can't change default language

### ISSUE THREAD

**Issue by IkonoDim** [pterodactyl/panel#4955]
### Current Behavior

Hello. Today I made uploaded a translation for pterodactyl to the German language to my panel. But when I try to change it and hit save it says "Panel settings have been updated successfully and the queue worker was restarted to apply these changes." but instantly changes the default language to English again.

### Expected Behavior

I excpected the panel to change the default language to German and display German as the default language.

### Steps to Reproduce

I uploaded my german translation to "/var/www/pterodactyl/resources/lang/de". Then i logged in into my panel and got to the admin settings. From there i navigated to the "Default Language" setting and changed its value to German/Deutsch.

### Panel Version

1.11.5

### Wings Version

1.11.8

### Error Logs

```bash
https://pteropaste.com/l23wmzomallk/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by yesBad** [comment]
Not an issue, the panel does not have any translation features. Only old scraps of v0.7.
