### ISSUE TITLE
Error: Command failed: php senja.php  /bin/sh: 1: php: not found

### ISSUE THREAD

**Issue by RyuGameDev** [pterodactyl/panel#4957]
I use node js to execute javascript via pterodactyl when I exec php with child process there is an Error: Command failed: php senja.php  /bin/sh: 1: php: not  found 
Even though I have installed PHP on my VPS, am I configuring Egg wrong? Here is the Egg file https://pastelink.net/hpsdfrvt Please help me to correct it.
![Screenshot_20231229-121838](https://github.com/pterodactyl/panel/assets/127178263/9729ea2e-1253-4587-b0a7-2a225ce82280)
![Uploading LongScreenshot_20231229-122726.png…]()

**Comment by QuintenQVD0** [comment]
You are in a docker container. 
So it does not care about the host os pacakges. 
So build your own custom docker image.
And Webhosting is not supported!

**Comment by RyuGameDev** [comment]
So what should i do? do i have to edit egg? how to edit it? can you teach me? i am sorry i am still a beginner

**Comment by QuintenQVD0** [comment]
> So what should i do? do i have to edit egg? how to edit it? can you teach me? i am sorry i am still a beginner

Not the place. You need a custom docker image what is not supported. You can try the discord but you will be turn away as it is not supported. Not a bug in the Software.
