### ISSUE TITLE
other server path to backup

### ISSUE THREAD

**Issue by ItzAndriss** [pterodactyl/panel#4958]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Store backups on another server machine, or even on multiple servers for the same backup.

### Describe the solution you'd like.

Make a tar.gz file on the main server and copy it to the server(s)

**Comment by matthewpi** [comment]
You have two options for backup storage, S3 or Local.  If you want backups stored off of the local node use S3 object storage. <https://pterodactyl.io/panel/1.0/additional_configuration.html#using-s3-backups>
