### ISSUE TITLE
Hide "Launch SFTP" button on Firefox and Firefox-based browsers.

### ISSUE THREAD

**Issue by prplwtf** [pterodactyl/panel#4967]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Firefox and Firefox-based browsers currently reject the `sftp://` URL scheme, which ends up in the "Launch SFTP" button doing nothing. ([bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=39714))

In my opinion, the best way to face this issue is to hide the "Launch SFTP" on Firefox and Firefox-based browsers as shown below.
![preview](https://github.com/pterodactyl/panel/assets/103201875/7c819231-0b88-4645-af7a-6a8b682c307d)

### Describe the solution you'd like.

Pterodactyl could check the browser headers, and then take appropriate actions to hide/show this button.

### Additional context to this request.

[(39714) Add support for secure protocols SSH and SFTP](https://bugzilla.mozilla.org/show_bug.cgi?id=39714)

**Comment by TrixterTheTux** [comment]
Firefox does support SFTP links - though I think the actual condition is if there's an application registered to handle opening `sftp://` scheme which will decide if it'll work or not (and if you previously set it to remember your choice which could do it on the wrong application).

**Comment by prplwtf** [comment]
> Firefox does support SFTP links - though I think the actual condition is if there's an application registered to handle opening `sftp://` scheme which will decide if it'll work or not (and if you previously set it to remember your choice which could do it on the wrong application).

![image](https://github.com/pterodactyl/panel/assets/103201875/a84025f7-ca15-4a9e-acbb-5fce29e5b2c6)
Source: [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=39714)

**Comment by QuintenQVD0** [comment]
It works just fine on firefox. But will not show anything if no sftp client like winescp is not installed.

**Comment by TrixterTheTux** [comment]
You're referring to a 24-year-old issue as a source. I can currently confirm that SFTP works on Firefox with WinSCP installed.

**Comment by prplwtf** [comment]
I've tried to check this as well as possible, but I kept running into the same result on multiple devices. If this is not happening for you all, I'll close this. Sorry.
