### ISSUE TITLE
PostgreSQL not present in releases

### ISSUE THREAD

**Issue by thibaultjunin** [pterodactyl/panel#4968]
### Current Behavior

PostgreSQL is not configured in `config/database.php` for releases

### Expected Behavior

PostgreSQL should be present and configured in `config/database.php` as #4486 added this feature

### Steps to Reproduce

The configuration for PostgreSQL is present in branch `develop` but not in `1.0-develop` (or other versions branches).

### Panel Version

1.11.5

### Wings Version

N/A

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
`develop` is the branch for v2. v2 is not released yet and unfinished. There is no ETA.
So you'll have to wait for postgresql support.
