### ISSUE TITLE
Notification don't work

### ISSUE THREAD

**Issue by zKoz210** [Pterodactyl/Panel#497]
I'm use mailtrap. 

php artisan pterodactyl:user

Success created user, but email not send

**Comment by DaneEveritt** [comment]
Mailtrap is not a SMTP relay service, it catches any emails it gets and doesn't do anything with them, so you're never going to get emails.

This is not a bug with the panel.

**Comment by zKoz210** [comment]
Hmm... I'm remove `implements ShouldQueue` and it work perfectly.

**Comment by DaneEveritt** [comment]
Then your queue workers aren't running. Its not a bug with this software, its a configuration issue on your end.

**Comment by zKoz210** [comment]
Hmm.... 

Config
```
QUEUE_DRIVER=database
QUEUE_HIGH=high
QUEUE_STANDARD=standard
QUEUE_LOW=low
```

Database
![image](https://user-images.githubusercontent.com/28255085/27250717-7bd85e6e-533e-11e7-9a00-25c4c4110b2e.png)

**Comment by schrej** [comment]
https://docs.pterodactyl.io/docs/queue-listeners
