### ISSUE TITLE
More wings

### ISSUE THREAD

**Issue by PixelcraftX** [pterodactyl/panel#4971]
### Current Behavior

When i need to start 2 wings i cant 

### Expected Behavior

When i try to start wings i cant i have 3 vps 
Vps 1 panel
Vps 2 wings 
3 wings

### Steps to Reproduce

I go add location 
Go nodes creating node 1 .... 
Conecting systemctl ...
Start and green but 
I go to create wings 2 .... 
Start and Red node 1 and 2 

### Panel Version

I think 1.4.4 

### Wings Version

I think 1.4.3

### Games and/or Eggs Affected

Wings && panel

### Docker Image

Ubuntu 22.04

### Error Logs

```bash
https://pteropaste.com/ccy17slualp4
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug, please visit the [Discord](https://discord.gg/pterodactyl) for configuration related issues.

Also, if you really are still using panel/ wings 1.4.x you should update as soon as possible.
