### ISSUE TITLE
panel returns a connecting error even though it has obtained node information

### ISSUE THREAD

**Issue by jhondoue** [pterodactyl/panel#4976]
### Current Behavior

panel returns a connecting error even though it has obtained node information
![git02](https://github.com/pterodactyl/panel/assets/152584081/d2372a94-3fad-499f-8439-1ac98048a6b2)
![git01](https://github.com/pterodactyl/panel/assets/152584081/1c7301f4-5f20-47fd-b862-38e17295e3b8)

### Expected Behavior

green heart symbol is displayed
can deploy the server to the added nodes.

### Steps to Reproduce

Install Wing using Ubuntu 22
I installed it using the same steps as the first node, which had no issues.

i checked the network and found no problems.
and checked the listening port of the node which returns an error and it is listening to the daemon port.

### Panel Version

1.11.5

### Wings Version

1.11.8

### Error Logs

```bash
https://ptero.co/ehyjevoruk
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
Your symptoms tell us the panel can connect to wings but your browser can't.
This is a configuration issue and not a bug with the software.

Please use the Discord for support.

**Comment by jhondoue** [comment]
I've got it.
Thank you for your reply.
