### ISSUE TITLE
Node resolving but Panel showing red heart

### ISSUE THREAD

**Issue by Skorrr** [pterodactyl/panel#4980]
### Current Behavior

Wings daemon is running without issue reported by systemctl, its FQDN resolves correctly in my browser, but the panel shows a red heart with "error connecting to the node".

### Expected Behavior

The Panel page should recognize that the wings server is reachable through its FQDN and show a green heart.

### Steps to Reproduce

Panel listening to 8080
Wings listening to 8081

Both behind a Caddy reverse Proxy forwarding the subdomains to their respective ports, listening to 80 and 443, and providing https.
Ports 80 and 443 forwarded (also tried 8080 and 8081 even if it shouldn't matter in this setup). Firewall Allows all the ports involved.

### Panel Version

1.11

### Wings Version

1.11

### Error Logs

```bash
 INFO: [Jan 21 01:28:23.084] writing log files to disk path=/var/log/pterodactyl/wings.log
 INFO: [Jan 21 01:28:23.087] loading configuration from file config_file=/etc/pterodactyl/config.yml
 INFO: [Jan 21 01:28:23.087] configured wings with system timezone timezone=Europe/Paris
 INFO: [Jan 21 01:28:23.087] checking for pterodactyl system user username=pterodactyl
 INFO: [Jan 21 01:28:23.088] configured system user successfully gid=996 uid=998 username=pterodactyl
 INFO: [Jan 21 01:28:23.094] fetching list of servers from API
 INFO: [Jan 21 01:28:23.421] processing servers returned by the API total_configs=0
 INFO: [Jan 21 01:28:23.422] finished processing server configurations duration=1.092131ms
 INFO: [Jan 21 01:28:23.432] configuring system crons  interval=1m0s subsystem=cron
 INFO: [Jan 21 01:28:23.433] starting cron processes   subsystem=cron
 INFO: [Jan 21 01:28:23.435] configuring internal webserver host_address=0.0.0.0 host_port=8081 use_auto_tls=false use_ssl=false
 INFO: [Jan 21 01:28:23.437] updating server states on Panel: marking installing/restoring servers as normal
 INFO: [Jan 21 01:28:23.454] sftp server listening for connections listen=0.0.0.0:2022 public_key=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAuiGzBJKG7U6f7F6FvvtuF8F7CVCC7C5

#Everything looks normal, tell me if there are other logs that can be usefull
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by PadowYT2** [comment]
Please open the browser console (F12 > Console) and show it

**Comment by Skorrr** [comment]
I think it fails because it insists on specifying the port for the query, whereas if it used only the FQDN it seems it would work fine.
So I wonder if the problem may only be graphical and it shouldn't pose problems? Or is there a real problem here?

Here is the node beeing reached through its domain name
![node2](https://github.com/pterodactyl/panel/assets/125159165/b6f66daa-5491-4c2c-a2de-db18f2a48ebe)

Here is the console of the panel page trying to reach the node with domain-name:8081
![nodeconsole](https://github.com/pterodactyl/panel/assets/125159165/a23860a9-592e-46ec-a146-298b89cbe061)

**Comment by PadowYT2** [comment]
The problem is with CORS, you must not be opening an issue on GitHub though. Response from Discord:

Your Panel remote URL in the Wings `config.yml` does not match with the URL from which you're making the request. Make sure that they match for the connection to work.


If you know what you are doing and are intentionally trying to use a different origin, make sure to add it to your Wings `config.yml` allowed origins as shown in the example below. Use correct HTTP or HTTPS scheme. Wildcard `'*'` can be used to allow all origins. 
```
allowed_origins:
- https://test.source.com
- http://another.panel.com
```

Restart Wings `systemctl restart wings` to apply the change.

**Comment by Skorrr** [comment]
I tried that, still doesn't work, still daemon not reporting anything wrong, and still red heart.

At first I also thought I had configured something wrong and sought help on discord. But everything seems to be working!

So tell me if I'm wrong but in my mind if the software reports a problem where there is none, there is a bug in the software. Otherwise what's the problem in this setup?

**Comment by Huguitis** [comment]
> I tried that, still doesn't work, still daemon not reporting anything wrong, and still red heart.
> 
> At first I also thought I had configured something wrong and sought help on discord. But everything seems to be working!
> 
> So tell me if I'm wrong but in my mind if the software reports a problem where there is none, there is a bug in the software. Otherwise what's the problem in this setup?

The red heart also appears on other devices?

**Comment by Skorrr** [comment]
@Huguitis yes, evrything behaves the same both through my pc on lan, through another pc on lan, and through a vpn.

**Comment by Boy132** [comment]
You need to set the daemon port in the node configuration to 443. (and leave the port as 8081 in the wings config file)

This is not a bug, please visit the [Discord](https://discord.gg/pterodactyl) again for further help.

**Comment by fazlangg** [comment]
Halo

**Comment by Blizzardo1** [comment]
I have the following in my config:

```
panel.domain {
	encode gzip

	header Cache-Control "public, max-age=3600"

	reverse_proxy /api/* {
		header_up X-Real-IP {remote_host}
		transport http {
			tls_server_name daemon.domain
			resolvers 1.1.1.1 1.0.0.1
			versions 2
		}
		to daemon.domain:8443
	}

	reverse_proxy internal.ip:443 {
		header_up X-Real-IP {remote_host}

		@error status 400 401 403 404 500 502 503 504 524
		handle_response @error {
			root * /var/www/html/errors
			file_server
			rewrite * /{rp.status_code}.html
		}
		transport http {
			tls_server_name panel.domain
			resolvers 1.1.1.1 1.0.0.1
			versions 2
		}
	}
}
```

But I get NS_BINDING_ERROR and an error code 522. What am I missing? :(
