### ISSUE TITLE
Build configuration blank page

### ISSUE THREAD

**Issue by WareZ57** [pterodactyl/panel#4981]
### Current Behavior

Pterodactyl under the latest available version, Wings as well, Ubuntu 20.04.

Everything works perfectly, except for the "build configuration" page, which displays a blank page with a line of characters. 
No errors in logs.

![Capture](https://github.com/pterodactyl/panel/assets/7504466/867b4cf7-2303-4cb8-b7d5-4fccd55e66f4)

### Expected Behavior

The page should display the configuration of the game server.

### Steps to Reproduce

Just click on "build configuration"

### Panel Version

1.11

### Wings Version

1.11

### Games and/or Eggs Affected

Palword

### Error Logs

```bash
https://ptero.co/edigiviheg
https://pteropaste.com/4iazsfxuzw5x/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Please visit the [Discord](https://discord.gg/pterodactyl) for configuration issues.
