### ISSUE TITLE
More Translations

### ISSUE THREAD

**Issue by Poseidon281** [pterodactyl/panel#4983]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

At the moment Pterodactyl is only available in 1 language, namely English, but I would like to see several translations for the Panel in any case

### Describe the solution you'd like.

We could solve this by working with a platform like Crowdin and having people translate the panel into all kinds of languages and make it possible to do it in more have languages

**Comment by alexevladgabriel** [comment]
Duplicate of #2518, there is an open PR for this, #2888
