### ISSUE TITLE
Wings do not connect properly. SFTP Error

### ISSUE THREAD

**Issue by cynthiagruben** [pterodactyl/panel#4986]
### Current Behavior

The servers are all displayed in the panel, but you cannot access the server.

### Expected Behavior

You should be able to access the individual servers from this node in the panel.

### Steps to Reproduce

I simply bought a server and installed Wings on it.

### Panel Version

1.11.3

### Wings Version

1.11.8

### Error Logs

```bash
https://ptero.co/coxaqiqyxo
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by AndyIsHereBoi** [comment]
Not a issue with pterodactyl. Stuff randomly scans the Internet for open ssh or sftp servers. This is just logs saying they provided no authentication when trying to connect.
