### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by zansen000** [pterodactyl/panel#4987]
### Current Behavior

The issue of this is when I want to up the node there is a error "FATAL: [Jan 24 12:39:11.552] failed to load server configurations error=remote: could not unmarshal response: invalid character '<' looking for beginning of value" when I type 'wings --debug'. All Config is clear but just suddenly.

### Expected Behavior

I expected is the respond at panel is green heart not red heart

### Steps to Reproduce

The config.yml seems fine when I check for twice and should be not respond with Fatal. If I have this simple debugger ofc I not open this new issue and seems fine

### Panel Version

1.11.5

### Wings Version

1.11.8

### Games and/or Eggs Affected

-

### Docker Image

-

### Error Logs

```bash
https://ptero.co/bepytuhuqy
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug, please visit the [Discord](https://discord.gg/pterodactyl) for configuration issues.

**Comment by matthewpi** [comment]
This happens if the panel errors or is behind a proxy that is returning HTML, it's not a bug.
