### ISSUE TITLE
Restart every hour

### ISSUE THREAD

**Issue by MPoteto** [pterodactyl/panel#4989]
### Current Behavior

My panel reboots every hour

### Expected Behavior

*working*

### Steps to Reproduce

Reboots itself

### Panel Version

1.11.5

### Wings Version

1.11.8

### Error Logs

```bash
https://pteropaste.com/cwd7ccc6yydu/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
The panel itself doesn't restart anything. You have provided nearly no information as well.

- Where are you seeing it restart? 
- Are you running the docker version of the panel? 
  If not
  - What webserver are you using?
  - What version of php is installed

**Comment by Boy132** [comment]
You should visit the [Discord](https://discord.gg/pterodactyl) and explain your problem (with a bit more details) there.
