### ISSUE TITLE
API Documentation Error

### ISSUE THREAD

**Issue by Volxz** [Pterodactyl/Panel#499]
I am currently working on a wrapper for the pterodactyl panel API in Node.In the documentation you show this example for authentication:
`<?php

$public = 'JkAFq7M47kLN0xVD';
$private = 'E6X9FyZvMFeJbqtq.IwjlTuR.MKDoicB';

$url = 'https://pterodactyl.local/api/admin/users';
$body = '';

$hmac = hash_hmac('sha256', $url . $body, $private, true);

return $public . '.' . base64_encode($hmac);

// Should return the string below:
//
// JkAFq7M47kLN0xVD.wgIxj+V8RHgIetcQg2lRM0PRSH/y5M21cPz9zVhfFaQ=`

funny enough it doesnt actually return that string. It returns the following string:
`JkAFq7M47kLN0xVD./RKZS3U2FKfEt7/tEks4vWwyS+89lL+k8aEGO8NJWuo=`

Am I doing something wrong or is this actually a mistake?

My NodeJS code is as follows: `
        hmac = crypto.createHmac('sha256', private_key);
        hmac.write(url+body);
        hmac.end();
        hash = hmac.read().toString('base64');`
`

Thanks!

**Comment by Yann151924** [comment]
Test with a real key and a panel :) and you know if the key is good :)

**Comment by parkervcp** [comment]
The code is good. I have updated my endpoints in my api application and there was no change. I think the docs are just our of date.

**Comment by Volxz** [comment]
What I'm asking is wither the value they claim it should return is accurate. They say that it should return from the provided PHP code is JkAFq7M47kLN0xVD.wgIxj+V8RHgIetcQg2lRM0PRSH/y5M21cPz9zVhfFaQ= is that accurate or am I drunk?

**Comment by DaneEveritt** [comment]
My bad, it was actually correct, the URL listed was just the wrong one. All fixed. 👍
