### ISSUE TITLE
Mounts are not added to the game

### ISSUE THREAD

**Issue by Archydea** [pterodactyl/panel#4990]
### Current Behavior

Hello, half a year ago I tried using mounts, but it did not lead to any success. Today I tried to use them again and still don't understand what the problem is.
Mounts are visible through the ls command, but when the server starts, I see that the folder is not added to the game..
![firefox_aDOoe7vF3f](https://github.com/pterodactyl/panel/assets/66128712/d6a566e4-4ed5-44c3-9968-d28c8a0ea3a7)
But...
![изображение](https://github.com/pterodactyl/panel/assets/66128712/1c6f26a1-c79d-4c5a-ae20-d2241a9baffe)

### Expected Behavior

I should see the folder being added to the game and the result of running the script

### Steps to Reproduce

1. I edited /etc/pterodactyl/config.yml adding there:
```
allowed_mounts:
- /var/lib/pterodactyl/mounts
```
2. I restarted the wings using `systemctl restart wings`
3. Added the required source and destination folder to the mounts, assigned the required egg and node, and added the mount to the server.
![изображение](https://github.com/pterodactyl/panel/assets/66128712/4b0e4231-477f-4204-b152-906a03c3bd51)
4. Turned on the server and checked if the script was executed

### Panel Version

1.11.5

### Wings Version

1.11.8

### Games and/or Eggs Affected

Garrys Mod

### Docker Image

ghcr.io/pterodactyl/games:source

### Error Logs

```bash
https://ptero.co/puqizevavy
https://pteropaste.com/zj006kil63yo
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
`/garrysmod/addons` and `/home/container/garrysmod/addons` are not the same paths.
You can't mount into `/home/container`, see https://pterodactyl.io/guides/mounts.html

If you need any further help please visit the [Discord](https://discord.gg/pterodactyl).

**Comment by Archydea** [comment]
Oops, apparently I've been misunderstanding this whole time, sorry. But is it still possible to mount it inside a container? If yes, how difficult is it..?)

**Comment by QuintenQVD0** [comment]
> Oops, apparently I've been misunderstanding this whole time, sorry. But is it still possible to mount it inside a container? If yes, how difficult is it..?)

You can indeed do it but it will cause a lot of issues.

**Comment by Archydea** [comment]
It’s just that I saw a working version from one person a long time ago, but okay, thank you very much)
