### ISSUE TITLE
Time offset feature in tasks turns 1 second into 3 seconds

### ISSUE THREAD

**Issue by purejosh** [pterodactyl/panel#4991]
### Current Behavior

If using a task with time offsets of 1 second, the tasks will execute 3 seconds apart. 

### Expected Behavior

Actually follow the time offset value. 

### Steps to Reproduce

![image](https://github.com/pterodactyl/panel/assets/70633949/ea6bddf7-2a44-4ed6-90dd-1aba8023461c)

### Panel Version

1.11.8

### Wings Version

1.11.8

### Error Logs

```bash
[18:57:27] [Server thread/INFO]: Played sound minecraft:item.lodestone_compass.lock to 2 players
title @a subtitle {"text":"in 8 seconds...","color":"green", "bold": true}
[18:57:30] [Server thread/INFO]: Showing new subtitle for 2 players
title @a subtitle {"text":"in 7 seconds...","color":"green", "bold": true}
[18:57:33] [Server thread/INFO]: Showing new subtitle for 2 players
title @a subtitle {"text":"in 6 seconds...","color":"green", "bold": true}
[18:57:36] [Server thread/INFO]: Showing new subtitle for 2 players
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
`3.7.3` is not a valid panel version.

**Comment by Boy132** [comment]
This is because the [queue worker](https://pterodactyl.io/panel/1.0/getting_started.html#create-queue-worker) is setup with "[--sleep 3](https://laravel.com/docs/10.x/queues#worker-sleep-duration)" by default. Meaning the effective minimal delay is 3 seconds.
Removing the sleep flag from pteroq.service (or setting sleep duration to `1`) and restarting pteroq should resolve the issue.

**Comment by purejosh** [comment]
Thanks! Good to know.
