### ISSUE TITLE
Can't create new database

### ISSUE THREAD

**Issue by IkonoDim** [pterodactyl/panel#4994]
### Current Behavior

When I try to create a new database it sends me a 500 Error back.
![image](https://github.com/pterodactyl/panel/assets/81419606/2a746065-2eb8-4eff-8225-941d7615945a)
![image](https://github.com/pterodactyl/panel/assets/81419606/b8fca876-0870-46b7-ac25-b3ef0fa33ad0)
![image](https://github.com/pterodactyl/panel/assets/81419606/2933e3d7-21b3-45f7-b639-521c7317a78f)

Furthermore I've noticed that when I **manually** create a database and then try to send the request from pterodactyl to create a db with the exact same name the db gets deleted.

### Expected Behavior

I excpected it to create the database with the specifications i gave it.

### Steps to Reproduce

go to admin panel. navigate to the databases tab and create a new database.

### Panel Version

1.11.5

### Wings Version

1.11.8

### Error Logs

```bash
https://pteropaste.com/2t29oij0irs1/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug, please visit the [Discord](https://discord.gg/pterodactyl) for configuration issues.
Your database host user doesn't have [GRANT permissions](https://pterodactyl.io/tutorials/mysql_setup.html#assigning-permissions-2).

**Comment by IkonoDim** [comment]
> This is not a bug, please visit the [Discord](https://discord.gg/pterodactyl) for configuration issues. Your database host user doesn't have [GRANT permissions](https://pterodactyl.io/tutorials/mysql_setup.html#assigning-permissions-2).

Yes it has got GRANT permissions. I double checked already

**Comment by Boy132** [comment]
> > This is not a bug, please visit the [Discord](https://discord.gg/pterodactyl) for configuration issues. Your database host user doesn't have [GRANT permissions](https://pterodactyl.io/tutorials/mysql_setup.html#assigning-permissions-2).
> 
> Yes it has got GRANT permissions. I double checked already

According to the logs you posted it doesn't. But, again, please visit the Discord.

**Comment by vermium** [comment]
Same issue, AND I have GRANT permission. It works on v1.11.3 but not v1.11.4.
