### ISSUE TITLE
Dont block Application API on maintenance

### ISSUE THREAD

**Issue by expxx** [pterodactyl/panel#4998]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

As the title states, don't block the Application API when the program is in maintenance mode.

### Describe the solution you'd like.

Just uh, don't block the api in maintenance 🤷

**Comment by matthewpi** [comment]
Maintenance mode is designed for use when you are modifying the database or upgrading a Laravel app, hence if you need any access to the API you shouldn't be in maintenance mode.

If you need a separate mode that blocks regular users but allows admins (including the application api for privileged tokens) then that should be added separately, but modifying the behaviour of the existing maintenance mode is not an option.

**Comment by matthewpi** [comment]
Already possible with Laravel, just need to use a special "bypass token"

<https://laravel.com/docs/10.x/configuration#bypassing-maintenance-mode>
