### ISSUE TITLE
Cannot transfer servers

### ISSUE THREAD

**Issue by skyy-codes** [pterodactyl/panel#5001]
### Current Behavior

On the panel, in logs, it says "Transfer failed..." and when looking at node logs, I get "failed to set transfer status error=Error response from Panel: ConflictHttpException: Server is not being transferred. (HTTP/409) server=43aa8bec-45df-4a81-859a-e2ab1bb1c22c status=false subsystem=transfer" and "failed to push archive to target error=unexpected status code from destination: 500 server=43aa8bec-45df-4a81-859a-e2ab1bb1c22c subsystem=transfer"

### Expected Behavior

The server is supposed to just transfer.

### Steps to Reproduce

1. Transfer a server.

### Panel Version

3.7.3 (Jexactyl)

### Wings Version

1.11.8 (from daemon information)

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
https://pastebin.com/vfjngdxf
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
> [Feb  9 00:16:00.127] failed to push archive to target error=unexpected status code from destination: 500 server

You need to check the wings logs from the destination around that timestamp.

**Also, since you are using Jexactyl you should ask their support first.** Jexactyl is a different software and we can't know if this is a problem with Pterodactyl itself or with a modification made by Jexactyl.
Chances are it's a problem with your configuration and/ or Jexactyl rather than Pterodactyl.

**Comment by skyy-codes** [comment]
> > [Feb  9 00:16:00.127] failed to push archive to target error=unexpected status code from destination: 500 server
> 
> You need to check the wings logs from the destination around that timestamp.
> 
> **Also, since you are using Jexactyl you should ask their support first.** Jexactyl is a different software and we can't know if this is a problem with Pterodactyl itself or with a modification made by Jexactyl. Chances are it's a problem with your configuration and/ or Jexactyl rather than Pterodactyl.

Hi,
Thanks, I'll check that and send that over real quick.

**Comment by AndyIsHereBoi** [comment]
any update from them?

**Comment by skyy-codes** [comment]
Nah, it seemed like a glitched node. It’s fixed now
