### ISSUE TITLE
SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client

### ISSUE THREAD

**Issue by panicco** [pterodactyl/panel#5010]
### Current Behavior

During Install Process Found on Getting Started Guide, Install Fails at:
**php artisan migrate --seed --force**

### Expected Behavior

Install to Complete as Expected. Import the Database

### Steps to Reproduce

1- Install Ubuntu 22.4
2- Run updates
3- Follow the Getting Started Guide

### Panel Version

1.11.5

### Wings Version

none

### Error Logs

```bash
https://pteropaste.com/x2e6zqakulii
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by PadowYT2** [comment]
Known problem. You must downgrade your MySQL/MariaDB version

**Comment by panicco** [comment]
I have attempted this but started receiving connection refused issues. 
I'm currently starting with a fresh OS and will attempt the setup process with this change. 

Will update shortly.

**Comment by panicco** [comment]
Solution Found:

- sudo apt purge mariadb-server
- wget https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
- chmod +x mariadb_repo_setup
- sudo ./mariadb_repo_setup --mariadb-server-version="mariadb-10.5"
- sudo apt update -y
- sudo apt install mariadb-server
- rm mariadb_repo_setup

**Comment by Boy132** [comment]
For future reference, this is a problem with php/ mariadb: https://jira.mariadb.org/browse/MDEV-32975

A proper fix is to set `character-set-collations` in `/etc/mysql/mariadb.conf.d/50-server.cnf` to `utf8mb4=utf8mb4_general_ci`. Restart MariaDB after editing the config.
There is no need to downgrade to 10.5

**Comment by FatalMerlin** [comment]
@Boy132 life-saver! Could this be added to the getting started docs?

**Comment by PadowYT2** [comment]
> @Boy132 life-saver! Could this be added to the getting started docs?

That is kinda pointless, I'm sure MariaDB will publish a follow-up version to fix (maybe they already did it)

**Comment by FatalMerlin** [comment]
> > @Boy132 life-saver! Could this be added to the getting started docs?
> 
> That is kinda pointless, I'm sure MariaDB will publish a follow-up version to fix (maybe they already did it)

Well, right now it could help as it is causing a headache if you follow the current installation guide.
