### ISSUE TITLE
Unfixable Problem with Database Hosts (for eggs)

### ISSUE THREAD

**Issue by weselben** [pterodactyl/panel#5012]
### Current Behavior

I can add my Database Hosts into the Database Hosts that works fine! When im trying to create a Database even as im switching into the Database Tab in my Server i get an API Error Screenshot.
![Screenshot](https://github.com/pterodactyl/panel/assets/50115212/38e88c3a-33a8-49cd-9c6e-269d61a4819d)

If i now create a Database regarding this Error, the Panel creates the Table aswell as the User but doesnt gives any responses to the Users-frontend.
![NVIDIA_Share_Ka1neMluvj](https://github.com/pterodactyl/panel/assets/50115212/ea6b7002-9dab-4a4a-bdc1-013a09b62f6d)

It also creates the Users accordingly (See Screenshots below).
![image](https://github.com/pterodactyl/panel/assets/50115212/e9657c8c-1c7e-4872-bf00-6e86dc016793)
![image](https://github.com/pterodactyl/panel/assets/50115212/1fbaec1c-591d-40c4-8f5e-e6f200d2d5b8)

### Expected Behavior

Seeing Database in Overview and getting Database-User Password.

### Steps to Reproduce

Add Database Host with root User.
Create Database in Frontend-UI inside a Server, then getting 500 API Error.

### Panel Version

1.11.5

### Wings Version

1.11.8

### Error Logs

```bash
https://pteropaste.com/3d1uvdpxuike/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by weselben** [comment]
I've been looking at my screen for the last 5 hours, please help me, I can't seem to find the problem :(

**Comment by danny6167** [comment]
Sounds like you're missing HASHIDS_LENGTH and/or HASHIDS_SALT  from your environment file.
If you are using panel in docker, then add the values to your compose file, otherwise add them to your .env file.
Use discord for any further support request.

HASHIDS_SALT=AnyRandom20CharacterString
HASHIDS_LENGTH=8

**Comment by weselben** [comment]
![image](https://github.com/pterodactyl/panel/assets/50115212/7bb08e81-7965-4952-933c-8d624511acd3)
It frckn works!! Thanks, maybe write this Into the Setup Docs too ? 👍

**Comment by Boy132** [comment]
> [...] maybe write this Into the Setup Docs too ? 👍

That issue only occurs when using the panel in docker. And there are currently no docs for that.

Next time you should actually visit the [Discord](https://discord.gg/pterodactyl) and check the `#panel-in-docker` channel. That would have saved you from looking 5 hours at your screen. :D

**Comment by danny6167** [comment]
Of if you go off-book and edit your .env file manually instead of running `php artisan p:environment:setup`
I've seen that edge case happen, but obviously there's no need for additional documentation for that.
