### ISSUE TITLE
service option startup command

### ISSUE THREAD

**Issue by 2300206764** [Pterodactyl/Panel#502]
Hello,i have a problem when i run my server.i custom a new service and try to run it in my composer.
It seems like work well when begin,but after install ,it can not work.After i do some check,i found the option startup command have not been run.
So i want now if i have a wrong understand about it.Could you tell me where it is logic in the daemon or where is code about the daemon run the command .
Thanks.

**Comment by adamxp12** [comment]
Hey I see you closed this issue so you must have found a solution?

Ripping my hair out here as I have set a startup command. I click start in the panel and it connects me to the container where nothing happens. if I manually type the command it works flawlessly. but I might as well ditch the whole panel and start them manually if it cant do a simple startup cmd

**Comment by DaneEveritt** [comment]
Can’t help you if you don’t provide more information. Either way I know for a fact that startup commands work fine, so hit up our forums or discord and we can help debug it a little more.

**Comment by adamxp12** [comment]
Problem solved. only works on certain docker containers. I was using a bare OpenJDK container. switched to the pterodactyl-java-glibc container and it works fine now

**Comment by DaneEveritt** [comment]
Great to hear, glad it is resolved.
