### ISSUE TITLE
SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers

### ISSUE THREAD

**Issue by pumathepuma** [pterodactyl/panel#5020]
### Current Behavior

While trying to install Pterodactyl Panel on Debian 12 the setup fails at step "php artisan p:environment:database"
- 6.1.0-18-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
- 11.3.2-MariaDB, client 15.2 for debian-linux-gnu

Getting this error while following the quick start guide

```
 [ERROR] Unable to connect to the MySQL server using the provided credentials. The error returned was "SQLSTATE[HY000]
         [2054] Server sent charset (0) unknown to the client. Please, report to the developers".

 [ERROR] Your connection credentials have NOT been saved. You will need to provide valid connection information before
         proceeding.
```

### Expected Behavior

To be able to setup the mysql database.

### Steps to Reproduce

1. Install a clean version of debian 12
2. Follow the install guide https://pterodactyl.io/panel/1.0/getting_started.html#picking-a-server-os

### Panel Version

1.11.5

### Wings Version

None yet

### Error Logs

```bash
https://pteropaste.com/3hmp7yyoiuji
Ignore the "No application encryption key has been specified.", was my mistake.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Duplicate of #5010

**Comment by pumathepuma** [comment]
Ah yes, indeed sorry.
