### ISSUE TITLE
Pterodactyl v1 API - Field for Server Uptime

### ISSUE THREAD

**Issue by nkoske** [pterodactyl/panel#5021]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

i would like to get the information since when a server is running

### Describe the solution you'd like.

an implementation into the data of Resource usage, since current_state is there it would be great if there were a field added 
"uptime" which contains a unix timestamp

### Additional context to this request.

current 
'`{
  "object": "stats",
  "attributes": {
    "current_state": "starting",
    "is_suspended": false,
    "resources": {
      "memory_bytes": 588701696,
      "cpu_absolute": 0,
      "disk_bytes": 130156361,
      "network_rx_bytes": 694220,
      "network_tx_bytes": 337090
    }
  }
}`

suggestion
`{
  "object": "stats",
  "attributes": {
    "current_state": "starting",
    "uptime":"1709802941",
    "is_suspended": false,
    "resources": {
      "memory_bytes": 588701696,
      "cpu_absolute": 0,
      "disk_bytes": 130156361,
      "network_rx_bytes": 694220,
      "network_tx_bytes": 337090
    }
  }
}`

**Comment by yesBad** [comment]
/resources endpoint for server gives uptime already.

**Comment by nkoske** [comment]
my fault sorry
