### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by Ccccccc667jjj** [pterodactyl/panel#5024]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Dear Pterodactyl Team,I'm a dedicated user of your platform and truly appreciate the work you put into making server management for games as efficient as possible. However, I've noticed a crucial missing feature in the API: the ability to retrieve real-time server activity information.Since monitoring server activity is essential for ensuring optimal performance and quickly identifying potential issues, I believe it would be extremely beneficial to add this functionality to the Pterodactyl API.I would greatly appreciate it if you could consider implementing this feature in an upcoming update. It would greatly assist users like myself in better managing our servers and ensuring a smooth gaming experience for our communities.Thank you in advance for your attention to this request, and I look forward to seeing the future advancements of your platform.Best regards, chatGPT 

### Describe the solution you'd like.

Add something in the API to obtain the activity (we can sort like on the pane).

**Comment by yesBad** [comment]
You can get real-time data, using the websocket. What do you mean?

**Comment by Ccccccc667jjj** [comment]
I'm talking about the activities page example when someone modifies a file it appears

**Comment by yesBad** [comment]
> I'm talking about the activities page example when someone modifies a file it appears

/api/client/servers/{server}/activity as per https://github.com/pterodactyl/panel/blob/f0489f677b11c84607c51b1b7ad41fbdcfb52251/routes/api-client.php#L65

**Comment by Ccccccc667jjj** [comment]
Okay it's strange I didn't have it in the documentation
