### ISSUE TITLE
Archiving specific files/folders doesn't work (Wings 1.11.9)

### ISSUE THREAD

**Issue by MattTek** [pterodactyl/panel#5027]
### Current Behavior

When archiving specific files/folders via the file manager, the archive is created, but is occasionally empty. If you select all files/folders however, the archive is created with the included files/folders as expected. The behavior where the archive is not created properly with specific folders/files does not occur on Wings 1.11.8. 

UPDATE: Archiving a full server also doesn't work as expected. Some folders/files will be missing. See ConsulHosting's post.

### Expected Behavior

The selected files/folders should be included inside of the created archive if you aren't trying to archive an entire server. 

### Steps to Reproduce

Select a couple files/folders inside of the file manager and archive them. The archive will be created inside the server, but the files/folders you selected will not be included. I recommend testing with just folders as it seems like the archive will never create properly with just a couple folders selected.

### Panel Version

1.11.5

### Wings Version

1.11.9

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ConsulHosting** [comment]
I can confirm that we have the same problem.

https://github.com/pterodactyl/panel/assets/64953256/501883e0-f2bc-4587-a50b-2c10679e55f4

**Comment by Jcodeerd** [comment]
Can confirm too

**Comment by TheGamer3514** [comment]
Same here

**Comment by astrooom** [comment]
Bump

**Comment by ccallahan** [comment]
@MattTek @ConsulHosting What is the OS and release? Also version of Docker?

If you can upload a sanitized sosreport that would be useful as well.

**Comment by ConsulHosting** [comment]
> @MattTek @ConsulHosting What is the OS and release? Also version of Docker?
> 
> If you can upload a sanitized sosreport that would be useful as well.

OS: Ubuntu 22.04
Panel version: 1.11.5
Wings version: 1.11.9
Docker version: 25.0.4, build 1a576c5
