### ISSUE TITLE
Archiving of files not working as of 1.11.9 (wings)

### ISSUE THREAD

**Issue by Hellaweird** [pterodactyl/panel#5029]
### Current Behavior

When selecting multiple files to archive, the archived file will be empty, and it will not contain any of the selected files. When questioning in the discord some other people have noticed the same issue. 

![Archive](https://github.com/pterodactyl/panel/assets/47821586/b3853b2b-75b8-40c1-89e6-5292163ccf15)
 

### Expected Behavior

When selecting multiple files the archive file should contain all of the selected files. In this case it contains none.

### Steps to Reproduce

Select a list of files, and archive them. The created .tar.gz file will be empty, and not contain any file data. 

### Panel Version

1.11.5

### Wings Version

1.11.9

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ssh-sysadmin** [comment]
You are not on the latest version of wings

**Comment by Hellaweird** [comment]
> You are not on the latest version of wings

Thanks for letting me know, i have updated now and the issue seems to be fixed. I will close the issue 👍

**Comment by AndyIsHereBoi** [comment]
buddy read about it in discord and still checked all of the issue duplication checkboxes
