### ISSUE TITLE
API Delete returns 204 when user does not exist

### ISSUE THREAD

**Issue by Volxz** [Pterodactyl/Panel#503]
Just curious as to if it was purposeful that the API returns a 204 when deleting a user even when a user is not existent on /api/admin/users/*. It would be handy if it returned a different code if the user was non existent. Thanks :)

**Comment by DaneEveritt** [comment]
Ah yes, this isn't necessarily an error in my code, but rather the functions I am using to delete the user don't throw any exceptions because they are all technically valid queries, just on a non-existant user. I will fix that up and push a fix.

**Comment by Volxz** [comment]
Awesome thanks!
