### ISSUE TITLE
Creation of archives in nested direcories leads to empty archives. (Wings 1.11.10)

### ISSUE THREAD

**Issue by MrSoulPenguin** [pterodactyl/panel#5030]
### Current Behavior

Creating an archive inside of a directory results in an empty archive. Unlike when creating an archive inside of the container root, which works properly.

### Expected Behavior

Archives created inside of directories should result in an archive containing the selected files.

### Steps to Reproduce

- Create a folder in the root of the server.
- Go into newly created folder. 
- Create a new file within folder.
- Attempt to archive newly created file.

### Panel Version

1.11.5

### Wings Version

1.11.10

### Games and/or Eggs Affected

NA

### Docker Image

NA

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jcodeerd** [comment]
Just checked, this also happens when archiving a subdirectory, it creates a 34 bytes tar.gz

**Comment by DicoSky** [comment]
also happened just when i update wing

**Comment by BlueTree242** [comment]
Can confirm, Same issue on current latest wings.

**Comment by danny6167** [comment]
It appears that the value of `relative` that is being passed to the `WalkDiratFunc` includes the name of the base directory we are walking over. This is causing the issue.

Not sure what the best way of fixing this is though as I'm still a little lost in the new FS code.
