### ISSUE TITLE
Server Databases not working properly after 1.11.3

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#5031]
### Current Behavior

On a fresh setup, with everything configured, when trying to open the Databases tab an error is occurring saying:
An unexpected error was encountered while processing this request, please try again.
The request /databases?include=password receives response 500 with this content:
{
    "errors": [
        {
            "code": "UnexpectedValueException",
            "status": "500",
            "detail": "An unexpected error was encountered while processing this request, please try again."
        }
    ]
}

The problem is actual on 1.11.4 and higher versions. Rolling back to 1.11.3 fixes it.

### Expected Behavior

The tab should work properly just like in 1.11.3.

### Steps to Reproduce

Fresh setup, create a server, open Databases tab.

### Panel Version

1.11.5

### Wings Version

1.11.9

### Error Logs

```bash
Empty logs
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by AndyIsHereBoi** [comment]
logs?

**Comment by AndyIsHereBoi** [comment]
i dont see any errors on your post so no errors here

**Comment by ghost** [comment]
> logs?

Those are just empty, at first I thought it was a problem with file permissions, checked it, and it was not the case

**Comment by ghost** [comment]
I even thought that was related to my server's state, so I reinstalled the OS, tried on Ubuntu, Debian, same problem

**Comment by parkervcp** [comment]
Are you using the docker container?

**Comment by ghost** [comment]
> Are you using the docker container?

Yes, I am running it in a docker container (both panel, and wings each in own container)

**Comment by PadowYT2** [comment]
Really known problem, refer to the Discord Server (#panel-in-docker)

**Comment by devnote-dev** [comment]
~~@PadowYT2 What exactly is the issue?~~

Found it, this should be fixed as it is still technically a bug.
