### ISSUE TITLE
requets with php 

### ISSUE THREAD

**Issue by Ccccccc667jjj** [pterodactyl/panel#5035]
### Current Behavior

{
    "errors": [
        {
            "code": "HttpException",
            "status": "419",
            "detail": "CSRF token mismatch."
        }
    ]
}    

### Expected Behavior

200

### Steps to Reproduce

$curl = curl_init();
    
            curl_setopt_array($curl, array(
              CURLOPT_URL => $url."api/client/servers/".$_GET["uuid"]."/power",
              CURLOPT_RETURNTRANSFER => true,
              CURLOPT_ENCODING => "",
              CURLOPT_MAXREDIRS => 10,
              CURLOPT_TIMEOUT => 30,
              CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
              CURLOPT_CUSTOMREQUEST => "POST",
              CURLOPT_POSTFIELDS => "{\n\t\"signal\": \"stop\"\n}",
              CURLOPT_COOKIE => 'pterodactyl_session=eyJpdiI6InhIVXp5ZE43WlMxUU1NQ1pyNWRFa1E9PSIsInZhbHVlIjoiQTNpcE9JV3FlcmZ6Ym9vS0dBTmxXMGtST2xyTFJvVEM5NWVWbVFJSnV6S1dwcTVGWHBhZzdjMHpkN0RNdDVkQiIsIm1hYyI6IjAxYTI5NDY1OWMzNDJlZWU2OTc3ZDYxYzIyMzlhZTFiYWY1ZjgwMjAwZjY3MDU4ZDYwMzhjOTRmYjMzNDliN2YifQ%253D%253D',
              CURLOPT_HTTPHEADER => array(
                "Accept: application/json",
                "Authorization: Bearer " . $_SESSION["token"]
              )
            ));
    
            $response = curl_exec($curl);

### Panel Version

1.11.5

### Wings Version

1.11.10

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
This is not a bug, just the docs been old, come to the discord for that (or just remove pterodactyl_session) 

These are unofficial docs but way better and up to date: https://github.com/devnote-dev/ptero-notes
