### ISSUE TITLE
Download options > Files tab

### ISSUE THREAD

**Issue by barbabarros** [pterodactyl/panel#5037]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Please, I would like to be able to download files from the Files tab of my game server!
thank you a lot for Pterodactyl and Wings.

### Describe the solution you'd like.

We could select one or more folders and a download button would become available to backup my servers :)

**Comment by yesBad** [comment]
File:

![chrome_PNvVMMCxcV](https://github.com/pterodactyl/panel/assets/87938689/72d29436-cca7-48a9-9b74-18c09f0d1063)

Folder:

https://github.com/pterodactyl/panel/assets/87938689/e406dac5-d011-4994-94e6-7372ae8d8051

Multiple folders/files:

https://github.com/pterodactyl/panel/assets/87938689/627bd3b3-ceb2-4715-892f-34bd4e045f21

**Comment by barbabarros** [comment]
Oh... thank you, yesBad.

**Comment by yesBad** [comment]
> Oh... thank you, yesBad.

No problem, goodluck! :)
