### ISSUE TITLE
Cannot write an empty file

### ISSUE THREAD

**Issue by Caily-E** [pterodactyl/panel#5038]
### Current Behavior

When I try to create a new file and name it it shows the error:
![image](https://github.com/pterodactyl/panel/assets/73819748/eb010c1c-f451-43e0-9092-c7b4c24d893e)

### Expected Behavior

It should create the new file with the name we put in.

### Steps to Reproduce

1. Click New File button
2. Click Create File button and name it anything
3. Click Create File button again

![image](https://github.com/pterodactyl/panel/assets/73819748/8380d96c-1d9f-4adb-806f-c26da290cdeb)

### Panel Version

1.11.5

### Wings Version

1.11.11

### Games and/or Eggs Affected

Minecraft (Paper)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
Wings: https://ptero.co/laxocalugi
Panel: https://pteropaste.com/a2kupaghj98f/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Jelcoo** [comment]
https://github.com/pterodactyl/wings/blob/develop/router/router_server_files.go#L242
