### ISSUE TITLE
DaemonConnectionError on server creation

### ISSUE THREAD

**Issue by Verox001** [pterodactyl/panel#5039]
### Current Behavior

When trying to create a server on a node, I receive this error from the API:
`"errors":[{"code":"DaemonConnectionException","status":"504","detail":"Could not establish a connection to the machine running this server. Please try again."}`

In Wings I got these logs:

```
WARN: [Mar 19 20:06:24.461] failed to validate user credentials (invalid format) ip=193.201.9.104:42951 method=password subsystem=sftp username=admin
Mar 19 20:06:24 cc0 wings[5396]: ERROR: [Mar 19 20:06:24.493] sftp: failed to accept inbound connection error=read tcp 192.168.0.1:2022->193.201.9.104:42951: read: connection reset by peer ip=193.201.9.104:42951
Mar 19 20:06:24  wings[5396]: Stacktrace:
Mar 19 20:06:24  wings[5396]: read tcp 192.168.0.1:2022->193.201.9.104:42951: read: connection reset by peer
Mar 19 20:06:24  wings[5396]: github.com/pterodactyl/wings/sftp.(*SFTPServer).AcceptInbound
Mar 19 20:06:24  wings[5396]:         github.com/pterodactyl/wings/sftp/server.go:123
Mar 19 20:06:24  wings[5396]: github.com/pterodactyl/wings/sftp.(*SFTPServer).Run.func3
Mar 19 20:06:24  wings[5396]:         github.com/pterodactyl/wings/sftp/server.go:109
Mar 19 20:06:24  wings[5396]: runtime.goexit
Mar 19 20:06:24  wings[5396]:         runtime/asm_amd64.s:1650
```

My machine is fully reachable from the panel and there are no other errors in the JS console:
![image](https://github.com/pterodactyl/panel/assets/47862641/cec63b14-e0a6-4572-b6b1-6c58ca844480)

### Expected Behavior

It should create the server without any problems.

### Steps to Reproduce

My system is running on a private network with Docker compose.

### Panel Version

1.11.5

### Wings Version

1.11.9

### Error Logs

```bash
Panel:
https://pteropaste.com/13wy9r6vo827

Wings:
https://ptero.co/lityhasata
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Verox001** [comment]
Fixed by setting the SFTP Host to the private IP address and not 0.0.0.0.

**Comment by Boy132** [comment]
For future reference: the SFTP error from the wings logs is unrelated. That's from a random internet bot trying to get into SFTP.

`Could not establish a connection to the machine running this server. Please try again.` is a connection issue with Wings, in this case the Panel <-> Wings connection. What fixed that issue was probably overwriting the wings config and/ or restarting wings.

(Also, fyi this should have been posted on the [Discord](https://discord.gg/pterodactyl).)

**Comment by Verox001** [comment]
I'm really sorry for the confusion. This was a general issue with my networking / NAT, but I'm glad that it didn't have to do with Pterodactyl.

**Comment by LordKackroellchen** [comment]
Yesterday i add a new vm to my panel. All new installed and got the same error on Panel: Could not establish a connection to the machine running this server. Please try again.

I don't find any solution to fix this problem. After many hour i copy an older wings-file from another gameserver and replace it in /usr/local/bin/wings. Now it's running.

I'm pretty sure thats a problem with the new wings file. Can someone confirm this?
