### ISSUE TITLE
client version 1.44 is too new. Maximum supported API version is 1.43

### ISSUE THREAD

**Issue by joveaaron** [pterodactyl/panel#5045]
### Current Behavior

Server installation or starting won't work, checked logs to find:
`Mar 26 22:27:04 srvx99 wings[1509]: Error response from daemon: client version 1.44 is too new. Maximum supported API version is 1.43`

### Expected Behavior

Server installs and runs fine

### Steps to Reproduce

Install using pterodactyl-installer
Set up node, location and server
Wait for installation to start or start server

### Panel Version

1.11.5

### Wings Version

1.11.11

### Error Logs

```bash
https://ptero.co/rinewinywu
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
We don't support installs that use an installer script.

My best guess here is that your docker version is out of date.

**Comment by joveaaron** [comment]
you think it could do with docker being installed through snap rather than apt?

**Comment by joveaaron** [comment]
confirmed, snap version of docker is very outdated, 24.0.x
for future reference: don't install docker through snap/when installing ubuntu
