### ISSUE TITLE
Auto-Deploy not working under configuration

### ISSUE THREAD

**Issue by Hellmanx** [pterodactyl/panel#5046]
### Current Behavior

I attempted to use Discord to try and resolve this issue, but I seem to be getting ghosted.

When pasting the generated token, I will get:

map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[Bearer <Maybe I'm not supposed to share this?>] Content-Type:[application/json]]http://panel.example.com/api/application/nodes/5/configurationFailed to fetch configuration from the panel.
 Get "http://panel.example.com/api/application/nodes/5/configuration": dial tcp: lookup panel.example.com on 127.0.0.53:53: no such host

Wings is confirmed running

### Expected Behavior

I expected the node to work after pasting token

### Steps to Reproduce

Just create a node and generate a token

### Panel Version

1.11

### Wings Version

1.11

### Error Logs

```bash
map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[Bearer <Maybe I'm not supposed to share this?>] Content-Type:[application/json]]http://panel.example.com/api/application/nodes/5/configurationFailed to fetch configuration from the panel.
 Get "http://panel.example.com/api/application/nodes/5/configuration": dial tcp: lookup panel.example.com on 127.0.0.53:53: no such host



● wings.service - Pterodactyl Wings Daemon
     Loaded: loaded (/etc/systemd/system/wings.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-03-26 06:42:33 UTC; 17h ago
   Main PID: 4923 (wings)
      Tasks: 16 (limit: 50434)
     Memory: 11.8M
        CPU: 6.860s
     CGroup: /system.slice/wings.service
             └─4923 /usr/local/bin/wings
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ConsulHosting** [comment]
In our experience, Auto-Deploy doesn't work either. However, in your case, the host cannot be found.

**Comment by Hellmanx** [comment]
Odd..  I'd assume It's looking for 127.0.0.53 on port 53 but I never set anything on that port.  I'll have to assume its supposed to be something automatic that never got applied.

**Comment by danny6167** [comment]
127.0.0.53 port 53 is your DNS server that it's using to resolve the domain.
The domain it's attempting to resolve according to your error message is `panel.example.com` and that doesn't exist.

**Comment by Boy132** [comment]
> I attempted to use Discord to try and resolve this issue, but I seem to be getting ghosted.

You are not getting ghosted, you just have to wait. The Discord was the right place to ask - this is not a bug.

**Comment by Hellmanx** [comment]
> > I attempted to use Discord to try and resolve this issue, but I seem to be getting ghosted.
> 
> You are not getting ghosted, you just have to wait. The Discord was the right place to ask - this is not a bug.

You're right, not a bug.  But I was timed out for no reason it seems.  Not like I was spamming or anything.  I'm assuming its because I posted the contents of Bearer.  But I'm not sure, no explanation was provided

**Comment by Ducorits** [comment]
I was just using auto deploy and there was a typo in the command itself. The ip had https//: instead of https://. you didn't share the ip within the issue so I cannot be sure what is going on nor if this is even relevant. I am thinking of making a bug report.
