### ISSUE TITLE
Wings: sqlite version retracted

### ISSUE THREAD

**Issue by Jelcoo** [pterodactyl/panel#5047]
### Current Behavior

Currently the wings go.mod has a indirect requirement of modernc.org/sqlite v1.29.4, which was retracted by the authors.
https://github.com/pterodactyl/wings/blob/develop/go.mod#L135
<img width="707" alt="Code_3MEkPFG0yc" src="https://github.com/pterodactyl/panel/assets/53396500/8f0c926a-a186-4c9a-b406-95b2d9fadca0">

### Expected Behavior

The go.mod should reference a existing version of sqlite.

### Steps to Reproduce

Clone the latest version of https://github.com/pterodactyl/wings and run `go get`

### Panel Version

1.11.5

### Wings Version

1.11.11

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by matthewpi** [comment]
Should be fixed by https://github.com/pterodactyl/wings/commit/5b0422d7561dd7f28ab54415c2c92b45c435eb36
