### ISSUE TITLE
bind: cannot assign requested address.

### ISSUE THREAD

**Issue by BuBing13** [pterodactyl/panel#5049]
### Current Behavior

[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
container@pterodactyl~ Error Event [fd38c002-a353-417a-892d-576874517212]: environment/docker: failed to start container: Error response from daemon: driver failed programming external connectivity on endpoint 16272eca-e2ac-4ac9-abb3-edf1b6632558 (001ae6e1e629b283a93c8fba16b94ebac24bbe7113fe3597721453ea68cff11e): Error starting userland proxy: listen tcp4 00.00.00.00:9876: bind: cannot assign requested address
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------

-------game:vrising---------------------------
tcp4 00.00.00.00:9876  Hidden actual IP,,,,,,,,,,,The port is not occupied, but the game server cannot start, and this error always occurs

### Expected Behavior

I installed the panels and wings on the server and ran the vrising server-side on the same server. There was no problem with the image file, but when everything was ready, the above problem occurred. The server could not be turned on

### Steps to Reproduce

There were no issues with the same steps on other servers, and this was the issue with one of the servers

### Panel Version

1.11.5

### Wings Version

1.11.11

### Games and/or Eggs Affected

vrising

### Docker Image

egg-v-rising-bep-in-ex.json

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
since when is 00.00.00.00 a valid allocation

it should be 0.0.0.0 or even better a real public or local ip (must be present on an host network interface)

**Comment by BuBing13** [comment]
> 从什么时候开始 00.00.00.00 是有效分配
> 
> 它应该是 0.0.0.0 甚至更好是真实的公共或本地 IP（必须存在于主机网络接口上）

I just didn't write the real IP address, but replaced it with 00.

**Comment by QuintenQVD0** [comment]
> > 从什么时候开始 00.00.00.00 是有效分配
> > 它应该是 0.0.0.0 甚至更好是真实的公共或本地 IP（必须存在于主机网络接口上）
> 
> I just didn't write the real IP address, but replaced it with 00.

Then that ip is not present on a network interface on the wings host. Not a panel or wings bug.
You should have came to the discord where the bot would have told you this:
![afbeelding](https://github.com/pterodactyl/panel/assets/67589015/7749bb10-ed0f-493f-a4a7-63e2d4cb72d1)

**Comment by trenutoo** [comment]
This is not a bug. There's no such IP available on your machine. See the [Node allocations](https://pterodactyl.io/wings/1.0/installing.html#node-allocations) documentation for more details.
