### ISSUE TITLE
Trying to get property of non-object when going to startup parameters

### ISSUE THREAD

**Issue by tenten8401** [Pterodactyl/Panel#505]
Getting this when trying to go to the startup parameters w/ my custom service.
![image](https://user-images.githubusercontent.com/6174343/27358878-b27e2822-55e6-11e7-91ee-09031c578410.png)

Here are my variables:
![image](https://user-images.githubusercontent.com/6174343/27358895-c6039cf6-55e6-11e7-8339-d49feab06f69.png)

And here's the file it's talking about with line 42: https://hastebin.com/ubewoxevuz.bash

**Comment by DaneEveritt** [comment]
This was fixed somewhere in 0.7. No clue what commit, but haven't seen it crop up.
