### ISSUE TITLE
FTP server won't perverse timestamp when uploading

### ISSUE THREAD

**Issue by SettingDust** [pterodactyl/panel#5050]
### Current Behavior

Modify timestamp changed to copying time

### Expected Behavior

Keep the local timestamp if possible

### Steps to Reproduce

Upload a file to server through ftp client(WinSCP here)

### Panel Version

1.11.3.0

### Wings Version

1.11.6.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
wings 1.11.6 is not even latest and has a sequrity issue.

**Comment by parkervcp** [comment]
Is the timestamp important? Do you have winscp set to preserve timestamps?

**Comment by QuintenQVD0** [comment]
![afbeelding](https://github.com/pterodactyl/panel/assets/67589015/829ad08c-926b-42d8-afa0-099ec5a89e77)

**Comment by SettingDust** [comment]
> Is the timestamp important? Do you have winscp set to preserve timestamps?

Have set since it's the default value
I'm syncing files with freefilesync that using timestamp and size. Only size may cause problem

**Comment by SettingDust** [comment]
> wings 1.11.6 is not even latest and has a sequrity issue.

I've read the changelog and haven't noticed any relate to FTP. So, I've not updated.
If updating is helpful. I'll do

**Comment by matthewpi** [comment]
Please re-test the latest version of Wings.  Changes were made to core internals of the filesystem and this issue may have been resolved.
