### ISSUE TITLE
Allow users to add to the startup command

### ISSUE THREAD

**Issue by andy01745** [pterodactyl/panel#5056]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Just want user to be able to add onto the startup command 
![image](https://github.com/pterodactyl/panel/assets/84942293/bdae9a93-4683-4460-a5b7-5329bbec453c)

### Describe the solution you'd like.

I do not have one. I have seen it added to other panels. So I know it is a thing. 

### Additional context to this request.

Just want user to be able to add onto the startup command. If there is a way let me know. Do not close this without letting me know how it is done if there is a way to do it

**Comment by parkervcp** [comment]
I disagree with letting general users change their own commands in many ways beyond the variables made available.

**Comment by andy01745** [comment]
Not letting user add on to it? I have seen hosts do it. Allowing users to edit the startup command.

**Comment by parkervcp** [comment]
I didn't say you can't do it. You would add a variable to the egg and the startup.

I said I am against it because you are putting a lot of trust in users being able to change their own commands and exposing yourself to more risk.

It's the easiest way to escape the server and having it run things it's not supposed to.

**Comment by AsheX1** [comment]
this is fucking dum so you are telling me i cant edit the startup command to add something that is needed to boot minecraft 1.7.10 with java 24 

for a bullshit reason that the user to dum and they wil break it blablabla
