### ISSUE TITLE
Wings is not compressing all passed files

### ISSUE THREAD

**Issue by Verox001** [pterodactyl/panel#5057]
### Current Behavior

I tried to archive some files after upgrading to wings and it just archived like 50% of them. I can't really tell what was the criteria there.

### Expected Behavior

It should add all files and directories to the archive.

### Steps to Reproduce

I've setup a minecraft server, marked all content in the directory and hit "Archive". The files were:
(
  0 => '?',
  1 => 'command_data',
  2 => 'java-lib',
  3 => 'libs',
  4 => 'logs',
  5 => 'players',
  6 => 'plugins',
  7 => 'resource_packs',
  8 => 'services',
  9 => 'worlds',
  10 => 'banned-ips.json',
  11 => 'banned-players.json',
  12 => 'nukkit.yml',
  13 => 'ops.txt',
  14 => 'powernukkitx.jar',
  15 => 'server.properties',
  16 => 'start.sh',
  17 => 'white-list.txt',
)  (I debugged them in Ptero to verify that Ptero was passing all files to Wings)

But I received an archive with the following content:
- command_data
- worlds
- banned-players.json
- nukkit.yml
- ops.txt
- white-list.txt

### Panel Version

1.11.5

### Wings Version

1.11.9

### Games and/or Eggs Affected

Tested with PowerNukkitX, but this probably affects all of them

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
No errors
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Update wings. This has been fixed in 1.11.10

(Duplicate of #5027)

**Comment by QuintenQVD0** [comment]
Update to wings v1.11.11, it was fixt their.

**Comment by Verox001** [comment]
Ah, thanks. I thought you'd always put new versions in the discord announcements.
Great to hear!

**Comment by QuintenQVD0** [comment]
> Ah, thanks. I thought you'd always put new version in the discord announcements. Great to hear!

Only major changes, small fixes like this not.

**Comment by Verox001** [comment]
Alright, I'll better keep an eye on it.
