### ISSUE TITLE
Egg delete button missing font

### ISSUE THREAD

**Issue by ari-party** [pterodactyl/panel#5058]
### Current Behavior

![image](https://github.com/pterodactyl/panel/assets/49074962/c6aa7fc7-f334-48e2-80af-99e52ed917d9)
Delete egg button has no font

### Expected Behavior

Delete egg button should have a font

### Steps to Reproduce

Go to a nest's egg and scroll to the bottom left to see the button and hover over it to expand

### Panel Version

1.11.5

### Wings Version

1.11.11

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
v2 will rework the admin area anyways. IMO there is no need to fix this small bug in 1.x

**Comment by matthewpi** [comment]
Just a minor UI issue that affects nothing.  A PR to fix this is welcome (make sure it targets the `1.0-develop` branch).
