### ISSUE TITLE
Please help , I can't figure out the problem

### ISSUE THREAD

**Issue by Truyn** [pterodactyl/panel#5060]
### Current Behavior

The node constantly falls off, after restarting wings everything works.

### Expected Behavior

I can't figure out the reason to fix the error.

### Steps to Reproduce

Don't know

### Panel Version

1.11.5

### Wings Version

1.11.11

### Games and/or Eggs Affected

CS2

### Docker Image

(ghcr.io/1zc/steamrt3-pterodactyl:latest)

### Error Logs

```bash
https://ptero.co/ykuwezibol
https://pteropaste.com/5843eubbwao1
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Please visit the Discord and describe your actual problem there.

**Comment by Truyn** [comment]
> Please visit the Discord and describe your actual problem there.

Unfortunately, I can’t, I’ve been blocked by a very strange moderator.

**Comment by QuintenQVD0** [comment]
Normally you do not get blocked for doing nothing wrong, so you did something real bad to make that mod ban you

maybe post your discord here, and if a mods see it he may unban you.

**Comment by Truyn** [comment]
![image](https://github.com/pterodactyl/panel/assets/53527324/8e0983dc-f2c7-4840-9666-396b9f980fd2)
![image](https://github.com/pterodactyl/panel/assets/53527324/2bd3dc71-7598-4890-8fb1-4d55a94dc1fa)

**Comment by Truyn** [comment]
restart wings >>> ok 
![image](https://github.com/pterodactyl/panel/assets/53527324/84c1e9eb-38aa-4292-8c3e-f9bc9709957d)

**Comment by Truyn** [comment]
> Normally you do not get blocked for doing nothing wrong, so you did something real bad to make that mod ban you
> 
> maybe post your discord here, and if a mods see it he may unban you.

I think it’s enough for me to be given a solution to the problem here, I will be very grateful.
I turned to discord for help, to which the moderator simply trolled and that’s all

**Comment by Truyn** [comment]
> Normally you do not get blocked for doing nothing wrong, so you did something real bad to make that mod ban you

English is simply not everyone’s native language, but apparently not all people realize this.
I won’t deny that,i think I deservedly received a ban for my phrase, but I would still like to solve the problem.

**Comment by Boy132** [comment]
> I think it’s enough for me to be given a solution to the problem here, I will be very grateful. I turned to discord for help, to which the moderator simply trolled and that’s all


> English is simply not everyone’s native language, but apparently not all people realize this. I won’t deny that,i think I deservedly received a ban for my phrase, but I would still like to solve the problem.

You know this reads as "I don't care about your rules or about my ban. I just want fix"? (also I highly doubt that a mod "trolled" you)

Anyways, it's most likely a Cloudflare issue.

**Comment by Truyn** [comment]
Thx,Sorry, I may not convey the meaning correctly since I communicate through a translator.
I tried to explain to the moderator that I only know how the panel works at the user level, but I am still the owner.

Messages began in the spirit of, and you should know/do you know how the panel works, etc.
I just asked for help because I don’t know.
If I had known, I would have figured it out myself.

**Comment by Truyn** [comment]
![image](https://github.com/pterodactyl/panel/assets/53527324/64e4a851-33ef-4f54-a89a-8f2b2c83104b)
This also confuses me a lot, how can I fix this error?

**Comment by Truyn** [comment]
Solved, the problem was spam via tcp on pptp server microtik.

I also say hello to the moderator Jolty, who would do well to gain experience himself before advising and trolling and interfering with other users.
P.s pm Jolty,
To drive a car, you don’t have to know how it works and works; to use a computer, you don’t have to know its design; to know how a social network works, you don’t have to know the language in which it’s written.

I hope you haven’t banned anyone else like that because of your incompetence.
