### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by blackstormlab** [pterodactyl/panel#5061]
### Current Behavior

I attempted to create an issue in the discord but it was just closed.

When running a forge minecraft server version 1.20.1-47.2.0 I ran into an issue which i think is related to the container, container image or docker. docker version 26.0.0 in case it matters

Why do i think this?

Running the exact same copy of the server on a windows VM running java 17 succesfully starts the server.

error log file incase pastebin link is broken: 
[hs_err_pid1.log](https://github.com/pterodactyl/panel/files/14891038/hs_err_pid1.log)

### Expected Behavior

Server starts succesfully.

### Steps to Reproduce

Docker Version 26.0.0
Panel 1.11.5
Wings 1.11.9
Create a Minecraft Forge Server Version 1.20.1-47.2.0
use these mods: https://drive.google.com/file/d/1AZ7zgIOEwWbICFDA0uJEJoOegUVtXAzv/view?usp=sharing

### Panel Version

1.11.5

### Wings Version

1.11.9

### Games and/or Eggs Affected

Minecraft (Forge)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17,18 & 19

### Error Logs

```bash
https://pastebin.com/eYm0Be4n
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by blackstormlab** [comment]
i even went out of my way making a container image with ubuntu22.04 and openjdk-18-jdk

**Comment by Boy132** [comment]
This is not a bug with Pterodactyl. Please stay on the Discord and ask there.

**Comment by blackstormlab** [comment]
then with what docker itself java ?

**Comment by blackstormlab** [comment]
i got help in the discord after asking for the 3rd time and turned out this was related to the pods pid limit increasing the pid limit fixed the problem. https://pterodactyl.io/wings/1.0/configuration.html#container-pid-limit
