### ISSUE TITLE
"Daemon Server File Directory" has no effect when making a new node

### ISSUE THREAD

**Issue by ReactiveSlime** [pterodactyl/panel#5064]
### Current Behavior

"Daemon Server File Directory" does not get set when making a node
when looking at the mysql database the "daemonBase" is also set to the default path

### Expected Behavior

for "Daemon Server File Directory" to stay set when making a node

### Steps to Reproduce

make a new node with a custom volume directory

### Panel Version

1.11.5

### Wings Version

1.11.11

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ReactiveSlime** [comment]
doing a manual mysql edit works
UPDATE nodes SET daemonBase = 'VOLUME_LOCATION' WHERE id = NODE_ID;
replacing VOLUME_LOCATION and NODE_ID with the real info

**Comment by danny6167** [comment]
Hi,

I just tried this and could not reproduce. Could you test it again ?

**Comment by ReactiveSlime** [comment]
Only just saw the reply. I'm out of town for a few days, but I can do it once home. I was able to reproduce it when I set up a third node.. when I can, I'll also provide a shirt video

**Comment by BallisticOK** [comment]
I just tried to reproduce this and its the same for me. Custom locations to not persist
