### ISSUE TITLE
Confirm screen on Node deletion

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#5069]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to see a popup screen, for you to confirm after you press "Yes, Delete This Node"

### Describe the solution you'd like.

A nice popup screen on deletion would show the node name with common yes or no options like "Delete This Node" or "Cancel"

### Additional context to this request.

I open this FR because, when I deleted a node it felt it happend to fast, and can see how a simple mistake where someone open the wrong node before deletion, and then accidently deleted the wrong node, a popup screen before deletion asking for confirmation, would probably make most of us double check.

**Comment by hwalker928** [comment]
You can only delete a node when it has no servers on it anyways.

**Comment by matthewpi** [comment]
As previously stated, you can only delete a node that has no servers associated with it.  If a node has no servers then I see no reason to make the deletion more difficult as it doesn't end-up deleting any data.
