### ISSUE TITLE
Cant Delete Servers

### ISSUE THREAD

**Issue by Volxz** [Pterodactyl/Panel#507]
This is a similar issue to #320 . My client is on the latest version of the panel and daemon. Everything is setup in compliance with the documentation. When I attempt to delete a server with MySQL databases associated with it an error is given saying "An unhandled exception **occured** while **attemping** to delete this server".  By the way, there are two spelling errors there man :/ It should have been spelt "occurred" and "attempting". 

I talked to your shmexy support staff and they were all like "That sucks! make an issue saying that it doesn't state that you have to delete databases first!" (here is the log at that point) https://gist.github.com/Volxz/1a507e0fef3c18b4a3394232f41cbea8 

Then I was all like "this makes me sad but ya gotta do what ya gotta do!" and I went to go delete the databases. when I did so it said " unhandled exception occurred while attempting to drop this database. This error has been logged." IN A BIG RED SCARY BOX. Now I'm not a fan of big scary red boxes so I decided to look into it and I found that the databases were dropped successfully in MySQL but the panel was obviously drunk and thought the databases existed. 

Anyways please fix or I will cry. <3 u @DaneEveritt

**Comment by DaneEveritt** [comment]
The SQL error is because you're not using a new enough version of MariaDB, please update it to 10.1.

I will look into the second issue.

**Comment by DaneEveritt** [comment]
Actually I'm almost positive your first issue is because of the second.

**Comment by Volxz** [comment]
Alright well close the issue and I'll create another if it happens again
