### ISSUE TITLE
"Stopped" alongside "done" for eggs

### ISSUE THREAD

**Issue by ari-party** [pterodactyl/panel#5070]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The ability to use console logs to determine if a server is able to be killed.

### Describe the solution you'd like.

Setting a value for "stopped" alongside "done", when the value is detected in the console logs, it will kill the server.

### Additional context to this request.

E.g.: Satisfactory servers currently do not exit and you have to kill them manually. The same console message gets logged whenever you're able to kill it.

**Comment by parkervcp** [comment]
This is such a rare reason to potentially need this.

**Comment by Boy132** [comment]
> E.g.: Satisfactory servers currently do not exit and you have to kill them manually. The same console message gets logged whenever you're able to kill it.

That sounds more like a problem with the Satisfactory egg and its stop signal. (or with Satisfactory itself)

**Comment by MinerPL** [comment]
> E.g.: Satisfactory servers currently do not exit and you have to kill them manually. The same console message gets logged whenever you're able to kill it.

I have a satisfactory server on the panel and I have no problem with the stop button, normally the server turns off and is available for restart
