### ISSUE TITLE
Create client api wtih Aplication api

### ISSUE THREAD

**Issue by Ccccccc667jjj** [pterodactyl/panel#5071]
### Is there an existing feature request for this?

- [ ] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Create client api wtih Aplication api

### Describe the solution you'd like.

I make a systeme for login with email but I need token after and I can't create token

**Comment by Captain-Arnab** [comment]
Hi 
Will you please explain the feature you want exactly? Is it otp verification or something else?
