### ISSUE TITLE
Error starting userland proxy

### ISSUE THREAD

**Issue by manzxy** [pterodactyl/panel#5072]
### Current Behavior

Error Event [872af23c-4e78-45a2-9f85-8e892e3a74ff]: environment/docker: failed to start container: Error response from daemon: driver failed programming external connectivity on endpoint e954d30d-a39f-4b19-bf92-50d2d6ee068e (616d97923c2fb5378a71828572b5e4f17dc1448fd8819c62106e7421d180711c): Error starting userland proxy: listen tcp4 **My_IP:PORT**: bind: cannot assign requested address

### Expected Behavior

-

### Steps to Reproduce

After Install panel and Wings

### Panel Version

1.11.5

### Wings Version

1.11.11

### Games and/or Eggs Affected

Minecraft Paper

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is not a bug, please visit the Discord.
