### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by thewanderingtraderm** [pterodactyl/panel#5073]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to have windows support

### Describe the solution you'd like.

Port the software to windows

### Additional context to this request.

Also before you ask me to use WSL or a VM is because VMs are too slow and WSL is a VM

**Comment by matthewpi** [comment]
No.

**Comment by yesBad** [comment]
Panel already has unofficial Windows support.

Wings doesn't have any kind of support and has been requested a billion times by now.

**Comment by thewanderingtraderm** [comment]
how do I install panel on windows

**Comment by PadowYT2** [comment]
> how do I install panel on windows

There are no tutorials, it is unofficial. You can't do anything with a Panel with no nodes
