### ISSUE TITLE
Allow local file selection

### ISSUE THREAD

**Issue by ChaOsRul3z** [Pterodactyl/Panel#508]
An option to select a jar file for example from local storage instead of giving up a url to download it from

**Comment by Volxz** [comment]
Do you mean like using your own jar? That is an option in the server startup section called "Server Jar file" at /admin/servers/view/*/startup. If you mean something similar to multicraft then why not just make your own packages?

**Comment by Qasimmodo** [comment]
You can just upload the file yourself after it's build the container via SFTP.  But I agree it'd be useful to be able to do it when creating a server.

**Comment by DaneEveritt** [comment]
If you want to do that you can just use the pack system. Right now this feature is back-burnered until daemon updates, and it has been requested enough that theres already another issue covering it so I'm going to close this one.
