### ISSUE TITLE
Startup Fails (using magmanode)

### ISSUE THREAD

**Issue by hiii532** [pterodactyl/panel#5081]
### Current Behavior

![image_2024-04-27_135117182](https://github.com/pterodactyl/panel/assets/70169777/fe98cc1d-fd53-4dc6-b4b2-5a1cf58b2b34)

When i start the server it pulls the docker image sets the server to offline and says "Error Event [da93b73e-c4ee-42c2-9da7-39608c8611ca]: an unexpected error was encountered while handling this request"

### Expected Behavior

Start the minecraft server

### Steps to Reproduce

Start the server

### Panel Version

1.11.5

### Wings Version

1.11.11

### Games and/or Eggs Affected

Minecraft Forge 1.12.2

### Docker Image

ghcr.io/software-noob/pterodactyl-images:java_19

### Error Logs

```bash
nothing happens
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
Please contact magmanode for support - There is nothing we can do to help you.
