### ISSUE TITLE
Please add STUN server support

### ISSUE THREAD

**Issue by hasirciogluhq** [pterodactyl/panel#5085]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Please add STUN server to plan. Cause i was used on AWS then i cant connect to server. İ know after 5 hour works. Now work with aws. panel gave me a local network private address when i add the NODE. You can fix if use a STUN server.

### Describe the solution you'd like.

Please add STUN server to plan. Cause i was used on AWS then i cant connect to server. İ know after 5 hour works. Now work with aws. panel gave me a local network private address when i add the NODE. You can fix if use a STUN server.

**Comment by matthewpi** [comment]
I have no idea what you are asking for.  I don't see how something like STUN would solve any problems related to Pterodactyl.

Any nodes on the panel **MUST** be publicly accessible, even if it is through a reverse-proxy.  You can't hide nodes on an internal network while expecting the panel to proxy all requests from a public network over a private network
