### ISSUE TITLE
Configuration auto-deploy issue

### ISSUE THREAD

**Issue by Syifan00** [pterodactyl/panel#5087]
### Current Behavior

When im using Pterodactyl Auto-Deploy Configuration, its showing this error

![image](https://github.com/pterodactyl/panel/assets/110280929/67db1600-19b4-47dc-bce1-77cf8cd4cdb6)

I think that is API problem?

### Expected Behavior

Using Auto-Deploy Configuration its can shortcut our time. If we can't using that feature, nothing have big problem, But. this feature will only be a display if it can't be used. 

Using Auto-Deploy is very shortcut the time than typing and making new file config.

### Steps to Reproduce

Installing Docker with `curl -sSL https://get.docker.com/ | CHANNEL=stable bash`

Then starting the docker `sudo systemctl enable --now docker`.

And continue to installing wings system.

`sudo mkdir -p /etc/pterodactyl`
`curl -L -o /usr/local/bin/wings "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")"`
`sudo chmod u+x /usr/local/bin/wings`

The problem start from here:

When im using pterodactyl auto-deploy configuration it will shown the error.
but when im using configuration file:
![image](https://github.com/pterodactyl/panel/assets/110280929/ff1769e2-6cc7-4a45-9830-a2e4c7065670)

. Its working:
![image](https://github.com/pterodactyl/panel/assets/110280929/df17eb6d-13c9-4643-a3ce-877c6fa06e72)

### Panel Version

1.11.5

### Wings Version

1.11.12

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by JasmeowTheCat** [comment]
I can reproduce this also - Happens on a autodeploy using the panel.

![N7CQhR 1](https://github.com/pterodactyl/panel/assets/81937080/834a8221-8518-42cb-9dff-131dc33cf1da)
