### ISSUE TITLE
Backup statuses never get updated by a node

### ISSUE THREAD

**Issue by Partymann2000** [pterodactyl/panel#5088]
### Current Behavior

When I want to create a backup, it takes an infinitely long time to load

### Expected Behavior

That it also finishes loading the backup

### Steps to Reproduce

...

### Panel Version

1.11.6

### Wings Version

1.11.12

### Games and/or Eggs Affected

All

### Docker Image

All

### Error Logs

```bash
Wings: https://ptero.co/yuvujifopi
Panel: https://pteropaste.com/2qw1/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Fistawka56** [comment]
I confirm I have the same problem

**Comment by Jcodeerd** [comment]
After downgrading the panel backups work as intended, confirming that it's indeed an issue with the panel.
A temporary solution to the backup problem could be to downgrade back to v1.11.5
I haven't tried testing whether it's caused by one of the patches / which one it is
