### ISSUE TITLE
ERROR: [May  6 02:43:04.637] failed to reset server states on Panel: some instances may be stuck in an installing/restoring state unexpectedly error=remote: failed to reset server state on Panel: Error response from Panel: RecordNotFoundException:  (HTTP/404)

### ISSUE THREAD

**Issue by RealmiRoblox** [pterodactyl/panel#5091]
### Current Behavior

idk

### Expected Behavior

just connect to panel and reset server states successfully

### Steps to Reproduce

sudo wings --debug

### Panel Version

1.11.6

### Wings Version

1.11.12

### Error Logs

```bash
https://ptero.co/diwerahayo
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
Could be related to the cloudflare page you have in front of your panel.
Also could be related to your panel url being wrong in the wings config. You have http:// where you should have https://

**Comment by danny6167** [comment]
As I've identified a number of problems with your configuration, and this is working fine for everyone else, I'm going to close this for now.

Please drop by the discord if you require further support.

**Comment by Braekpo1nt** [comment]
It should be noted that I experienced this error when using the "generate token" button to configure a new node. My panel and my wings node both used fully qualified public domain names, configured with SSL, but the "generate token" button gave me an "http://<panel url>" instead of "https://<panel url>". Adding the missing "s" made everything work.

**Comment by ash-development** [comment]
^^^ same here, this should be addressed
