### ISSUE TITLE
Discord unban 

### ISSUE THREAD

**Issue by masterhacka** [pterodactyl/panel#5092]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hi my Discord token got hacked so someone spammed some trash with my account. I am sorry for that but changed the password so everything should be fine now. Is there any way you can unblock me?

### Describe the solution you'd like.

Unban

**Comment by masterhacka** [comment]
Discord tag: xxcyanidexx

**Comment by danny6167** [comment]
I've unbanned you - Please be sure it doesn't happen again
