### ISSUE TITLE
Impossible to create a server from the API

### ISSUE THREAD

**Issue by Volxz** [Pterodactyl/Panel#510]
I try to post the following JSON data to the endpoint /api/admin/servers but every time i do it says "An unhandled exception occured while attemping to add this server. Please try again."

Here is the JSON data:
`{
    "name": "api test",
    "user_id": "1",
    "location_id": "1",
    "memory": "1024",
    "swap": "0",
    "node_id":"0",
    "allocation_id":"2",
    "disk": "5000",
    "cpu": "0",
    "io": "500",
    "service_id": "1",
    "option_id": "1",
    "auto_deploy": "true",
    "startup": "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}",
    "env_SERVER_JARFILE":"server.jar",
    "env_VANILLA_VERSION":"latest"
}`

EDIT: If you need my code let me know and I will be glad to push my latest to my repo.

https://hastebin.com/awezoniyam.tex there are my logs

**Comment by DaneEveritt** [comment]
You need to actually provide the error logs, not the data you're passing. I can't possibly guess what is wrong without a log.

**Comment by Volxz** [comment]
It was missing a description key and value in the JSON. It is not documented in the API.
