### ISSUE TITLE
docker_image validation prevents local images

### ISSUE THREAD

**Issue by danny6167** [pterodactyl/panel#5101]
### Current Behavior

"The image format is invalid." error is received when attempting to use an image starting with ~ (local image)

### Expected Behavior

Image names beginning with ~ should be accepted

### Steps to Reproduce

Enter a docker image starting with ~

### Panel Version

1.11.7

### Wings Version

N/A

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
If you build a local image with the -t flag it still works as you can then just use `dev:latest`?

**Comment by stive101** [comment]
with quintens soution it will work, u need to tag dev:latest to your image, and after that dev:latest is your new image name, 
with that u can start you custom image, thanks again Quinten, i try to figure out what i can do here for hours now ;=)

**Comment by danny6167** [comment]
> If you build a local image with the -t flag it still works as you can then just use `dev:latest`?

It throws a tantrum because wings tries and fails to pull the image.

**Comment by danny6167** [comment]
Yeah it still needs to be fixed though as this isn't going to work for all cases.

I'll submit a fix in a few hours.

**Comment by danny6167** [comment]
I've submitted a PR.
If you need to fix this before the next release you can apply the patch as such
```bash
cd /var/www/pterodactyl
curl https://patch-diff.githubusercontent.com/raw/pterodactyl/panel/pull/5103.patch | patch -p1
```

**Comment by danny6167** [comment]
Closing as PR to fix was merged
