### ISSUE TITLE
Error with Connector.php when executing php artisan migrate --seed --force

### ISSUE THREAD

**Issue by stormyark** [pterodactyl/panel#5104]
### Current Behavior

I followed along the documentation to install pterodactyl on my server until I came up this command: `php artisan migrate --seed --force`

My Error output is this:

```
 root@vps:/var/www/pterodactyl# php artisan migrate --seed --force

In Connection.php line 760:

  SQLSTATE[HY000] [2054] Server sent charset (0) unknown to th
![error pterodactyl](https://github.com/pterodactyl/panel/assets/81960990/8fcff4e0-04f8-41fd-9978-f022d5cc60ae)
e client. Please, report to the developers (Connection:
   mysql, SQL: select * from information_schema.tables where table_schema = panel and table_name = migrations and tab
  le_type = 'BASE TABLE')


In Connector.php line 65:

  SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers
```

### Expected Behavior

This command should setup the database tables and then add all of the Nests & Eggs that power Pterodactyl.

### Steps to Reproduce

Follow along all steps of the documentation exept of "php artisan p:environment:mail"

### Panel Version

1.11

### Wings Version

1.11

### Error Logs

```bash
https://pteropaste.com/h276/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
As you were told on Discord, this is not a bug with Pterodactyl.
You've also already been given the solution.

Please keep support requests in the Discord.

**Comment by stormyark** [comment]
> As you were told on Discord, this is not a bug with Pterodactyl. You've also already been given the solution.

Where can I find the solution in Discord?

**Comment by stormyark** [comment]
Even after editing `character-set-collations` in `/etc/mysql/mariadb.conf.d/50-server.cnf` from `utf8mb4=uca1400_ai_ci` to `utf8mb4=utf8mb4_general_ci` and restarting mariadb with `sudo service mariadb restart`, I still get an error which contains:

```
root@vmd140420:/var/www/pterodactyl# php artisan migrate --seed --force

In Connection.php line 760:

  SQLSTATE[HY000] [1045] Access denied for user 'pterodactyl'@'localhost' (using password: YES) (Connection: mysql, S
  QL: select * from information_schema.tables where table_schema = panel and table_name = migrations and table_type =
   'BASE TABLE')


In Connector.php line 65:

  SQLSTATE[HY000] [1045] Access denied for user 'pterodactyl'@'localhost' (using password: YES)


```
![error pterodactyl2](https://github.com/pterodactyl/panel/assets/81960990/72bf22d7-5f71-4975-8fb3-10e161c37eb8)

**Comment by QuintenQVD0** [comment]
Access denied so that is you wrong configuring it.

**Comment by danny6167** [comment]
Once again, please use the discord for support.
None of these are bugs with Pterodactyl
