### ISSUE TITLE
Allow services variable in pterodactyl module WHMCS

### ISSUE THREAD

**Issue by soren33322** [pterodactyl/panel#5107]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Please add the possibility to use the services variables in WHMCS.

### Describe the solution you'd like.

Add additional field to WHMCS pterodactyl module from egg service variables
F.x.

Minecraft Paper that the customer can select the version they want in the WHMCS when ordering.

**Comment by danny6167** [comment]
This ability already exists in the WHMCS module and is documented in the FAQ.
This is also the wrong repo.
