### ISSUE TITLE
Cannot delete new lines

### ISSUE THREAD

**Issue by blender-dev** [pterodactyl/panel#5109]
### Current Behavior

On **mobile devices** it is not possible to delete new lines in the file content editor.

### Expected Behavior

Deleting new lines in the file content editor should be possible on mobile devices.

### Steps to Reproduce

Use a mobile device (I'm using Oppo) and open the panel in a Google Chrome browser.

### Panel Version

Don't know

### Wings Version

Don't know

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
Hi,

Unfortunately this report is missing a lot of information, and I wasn't able to reproduce this at all.
Pressing backspace on every mobile device I had on hand correctly removed a new line.

If you have more information, including steps to reproduce it, what happens when you try to remove the new line, or even the panel version, please let us know.

**Comment by blender-dev** [comment]
Hey, sorry for the late response. The panel version is 1.11.5 (latest). Also, I'm using the latest version of Google Chrome. Here's a video of the problem: https://media.discordapp.net/attachments/886203329787617320/1251653184137465856/Record_2024-06-15-22-17-23.mp4?ex=666f5c5d&is=666e0add&hm=0e45d2e9b7ab71be6e449420fef66500f7958ada931b64b3b9f1a90fd5d6e60f&

**Comment by danny6167** [comment]
Are you able to reproduce this on a vanilla Pterodactyl install? You appear to be using Nebula and it has a few bugs of it's own with the text input.

**Comment by blender-dev** [comment]
It's actually not my hosting, I just asked the owner which version of Pterodactyl they're using. Although, the issue appears in other hostings too (which I believe use the vanilla pterodactyl): https://media.discordapp.net/attachments/886203329787617320/1251850292069400626/Record_2024-06-16-12-44-25.mp4?ex=667013ef&is=666ec26f&hm=8ae079dd0b2f4503ad7adfb52d5de67948e683865690f8617b1e2caf3b23606a&

**Comment by danny6167** [comment]
Thanks. I really appreciate you reproducing this for us and providing the videos.
Unfortunately since we can't reproduce it and nobody else has ever reported anything like this I don't think we can reopen this report. Seems like an issue specific to the software on your device.

**Comment by blender-dev** [comment]
My device is like 3 years old, maybe that's why. Anyway, I really appreciate your help.
