### ISSUE TITLE
Console output broken

### ISSUE THREAD

**Issue by Commodore64x** [Pterodactyl/Panel#511]
Ok so I think console output for minecraft is a little broken here is a little comparison:

The first issue is that messages with the dark gray color do not display
How it shows in console:
https://i.imgur.com/gxfaCye.png
How it looks ingame:
https://i.imgur.com/CZQXR23.png
Additionally, 
If the whole prefix is dark gray it will not show at all

Also, the last color gets removed in console:
How it shows in console:
https://i.imgur.com/4tDDEGz.png
Ingame:
https://i.imgur.com/KVOCMsS.png

I am running the latest version of the panel and daemon with Ubuntu 16.04.2 LTS installed.

**Comment by Commodore64x** [comment]
Also, adding to this, if you have something like telnet console on your server, the same lines that have this problem:
This: > [22:53:54 INFO]: [+ ]Commodore64x(edited)
Comes out as: :[22:53:54 INFO]: [0;30;1m[[0;32;1m+[0;30;1m] [0;37;1mCommodore64x[m
In telnet consoles of servers than run ptero

**Comment by DaneEveritt** [comment]
Its a bug in the renderer we use, and not something I can control.
