### ISSUE TITLE
500 Server Error when clicking nodes in admin menu

### ISSUE THREAD

**Issue by CutieAshlynn** [pterodactyl/panel#5112]
### Current Behavior

When i go to the admin menu and clock nodes i get a white screen with 500 server error and at the main home screen with all servers i have none of them will load beacause the panel seems to not be contacting the wings nodes.

### Expected Behavior

To be able to go into my admin and click nodes and to be able to manage servers without issues.

### Steps to Reproduce

Click admin
then go to nodes
you should get a 500 server error
Not sure if this is going to happen to everyone.

### Panel Version

1.11.7

### Wings Version

1.11.13

### Error Logs

```bash
https://pteropaste.com/w04e/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by MackenzieMolloy** [comment]
It looks like you've probably edited the Panel's encryption keys.

If you have a backup of your Panel, please locate and restore the .env file from that backup. However, if you do not have a backup, your information is — unfortunately — toast, and cannot be recovered.

Please check out the following resource for more information on this: https://pterodactyl.io/panel/1.0/troubleshooting.html#invalid-mac-exception

**Comment by CutieAshlynn** [comment]
Panel was restored with a database but, we did loose the old .env file and encryption key so we will be making a new panel and database.
