### ISSUE TITLE
Wings does not connect.

### ISSUE THREAD

**Issue by mrFavoslav** [pterodactyl/panel#5118]
### Current Behavior

When I run wings the heart is still red and browser says "Access to XMLHttpRequest at 'https://node.favoslav.cz:8443/api/system' from origin 'https://panel.favoslav.cz' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource." I tried to find help at discord.. they told me to reinstall my whole os which how to frick am I supposed to do if I have like 200GB of data on the server.

### Expected Behavior

Wings connect, heart is green.

### Steps to Reproduce

Just install ptero and wings and run everything. Browser says CORS policy error.

### Panel Version

1.11.7

### Wings Version

1.11.3

### Error Logs

```bash
wings https://ptero.co/rexahineta
panel https://pteropaste.com/tyk1
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
As discussed in the Discord, your wings port is not open.
There is no bug here.
