### ISSUE TITLE
Issue with SQLite

### ISSUE THREAD

**Issue by Mahid102938** [Pterodactyl/Panel#512]
So its giving me this error in console: https://hastebin.com/gijoyovasi.pas
Not sure what to do, I think it needs Xerial SQLite driver. Its on version v3.8.12

**Comment by Polarcraft** [comment]
This is a known issue within ChestShop, and is in no way related to pterodactyl.

**Comment by parkervcp** [comment]
The Xerial SQLite driver is know to have alpine issues. 

Infact there is a issue on their own repo (here)[https://github.com/xerial/sqlite-jdbc/issues/209]
