### ISSUE TITLE
Panal 500 Server Error after Updating the Panel

### ISSUE THREAD

**Issue by Ste3et** [pterodactyl/panel#5122]
### Current Behavior

500 Server error i mean "auth.session" is missing

### Expected Behavior

Reaching the Panel

### Steps to Reproduce

I upgradet the panel to the newest version from 1.11.3

### Panel Version

1.11.7

### Wings Version

1.11.13

### Error Logs

```bash
https://ptero.co/efabimihas
https://pteropaste.com/0ewk/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
Please use the discord for support.
