### ISSUE TITLE
502 BAD Gateway error

### ISSUE THREAD

**Issue by gamingwithjohn18** [pterodactyl/panel#5123]
### Current Behavior

I updated my panel and after i did I am getting 502 bad gateway error. 

### Expected Behavior

not 502 bad gateway error

### Steps to Reproduce

update the panel, and and get 502 bad gateway error

### Panel Version

1.11.7

### Wings Version

1.11.7

### Games and/or Eggs Affected

All

### Error Logs

```bash
Wings: https://ptero.co/peqinifutu
Panel: https://pteropaste.com/jm3y
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
You were banned from our Discord for spamming and ban evading - Don't come here and try to pull this nonsense.
