### ISSUE TITLE
I can't enter the manage menu on the server panel, when I try to enter it just displays blank white

### ISSUE THREAD

**Issue by OvExeR** [pterodactyl/panel#5129]
I can't enter the manage menu on the server panel, when I try to enter it just displays blank white

![image](https://github.com/pterodactyl/panel/assets/44639216/5f14eb14-e888-4797-9d2b-6fa8b1c1469d)

https://github.com/pterodactyl/panel/assets/44639216/3dad8e13-1115-47b5-8023-bb60d2e5bace

**Comment by danny6167** [comment]
Please use the discord for support questions.
