### ISSUE TITLE
Suggestion - Automaticly start MC servers on daemon on reboot

### ISSUE THREAD

**Issue by MrDienns** [Pterodactyl/Panel#513]
Grettings

Title says it. I would love to see my Minecraft servers automaticly start up again after I fully rebooted the server. The daemon does automaticly start, so why not the MC servers too? We could possibly make this configurable too.

Yours sincerely,

MrDienns

**Comment by jordan308** [comment]
I would like to add I would recommend this suggestion to include all types of gameservers, not just minecraft! it will make peoples lives so much easier!

**Comment by parkervcp** [comment]
Already requested in #136 

So this really doesn't need to exist. Do some searching first.

**Comment by MrDienns** [comment]
thanks @parkervcp, I couldn't find it last time.
