### ISSUE TITLE
Panel doesn't load on fresh install

### ISSUE THREAD

**Issue by F1zzyD** [pterodactyl/panel#5155]
### Current Behavior

Ran the compose.yml file from [here](https://github.com/pterodactyl/panel/blob/1.0-develop/docker-compose.example.yml) and I do not have access to the panel. I've reinstalled several times (and using docker system prune -a), yet I always get an error with the network (even though I change it) or the panel is just inaccessible.

### Expected Behavior

1. run docker compose up -d
2. finishes with no errors
3. can access panel at the specified url

### Steps to Reproduce

1. run docker compose up -d
2. may or may not see network error
3. try to access panel at specified url
4. cant

### Panel Version

1.4.0

### Wings Version

N/A can't install it yet

### Games and/or Eggs Affected

None, cause I cant get past the panel

### Docker Image

https://github.com/pterodactyl/panel/blob/1.0-develop/docker-compose.example.yml

### Error Logs
[Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.0.0.4' (This connection closed normally without authentication)

Note, i have changed it from '172.20.0.0/16 to the any other alternative because apparently "pool overlaps with other one on this address space", making the compose not run at all. Useless

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by XceptDev** [comment]
Hello, it is not panel's issue. You didn't configure everything correctly. Please join pterodactyl discord server.

**Comment by F1zzyD** [comment]
> You didn't configure everything correctly.

Using the linked compose file, the issue at hand appears to be `networks` which is below the commented line stating:
"The remainder of this file likely does not need to be changed. Please only make modifications below if you understand what you are doing." 

On a fresh install, there shouldn't be any need to mess with the network, especially if the dev states don't edit these values. I don't understand how I "didn't configure everything correctly" in a section that pretty much states "don't mess with this". Not user error....

**Comment by danny6167** [comment]
There's no usable information in this issue report. This appears to be an issue with your systems configuration.

I run the panel in docker using the example `docker-compose.example.yml` and it works perfectly fine.
This also works just fine for everyone else.
