### ISSUE TITLE
Problem with creating Database in panel

### ISSUE THREAD

**Issue by FlyUltra** [pterodactyl/panel#5160]
### Current Behavior

When I try to create Database in databases on server I get to error, the database Is created in the list in databases host

Im using docker

![image](https://github.com/user-attachments/assets/68729643-ac0f-46c8-b6ba-6de03523d3df)

### Expected Behavior

Creating database in the list in the server

### Steps to Reproduce

Creating new docker panel, and adding database host, then trying to create database

### Panel Version

3.8

### Wings Version

3.8

### Games and/or Eggs Affected

Every

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
You're missing some required environment variables. Please come to the Discord for support. You'll want to look in the #panel-in-docker channel
