### ISSUE TITLE
500 SERVER ERROR 

### ISSUE THREAD

**Issue by LegendaHluPa** [pterodactyl/panel#5169]
### Current Behavior

After updating the panel to version 1.11.5, I started getting the 500 Server ERROR 
I wrote to discord and they couldn't help me.

### Expected Behavior

as I understand auth.service is missing

### Steps to Reproduce

Update panel and take 500 error

### Panel Version

1.11.5

### Wings Version

1.11.13

### Error Logs

```bash
https://pteropaste.com/iius/
https://ptero.co/tebahumece
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
This pretty much always ends up being either an issue with a theme, or you made a mistake during the upgrade process, such as not setting permissions correctly.
Either way, Discord is the place for support requests.
