### ISSUE TITLE
Don't allow a user to use localhost as a connection address

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#518]
Tons of issues with people using `localhost` and then being unable to connect to the SQL socket, require using an IP which avoids that issue.

**Comment by Doc94** [comment]
this is only force localhost to 127.0.0.1 in assing config or block this parameter? (question for.. know?)

**Comment by Polarcraft** [comment]
Technically if it is set by a plugin I don't think there is much you can do there, though making a huge warning stating you must use the external ip instead of localhost on the docs should make a difference.

**Comment by DaneEveritt** [comment]
This is for panel DB connections, not plugins.

**Comment by DaneEveritt** [comment]
For now I've put a warning on the environment setup for database connections, and the command will also test connections, so I think I'm going to close this as 8722571 addresses it for now.
