### ISSUE TITLE
Close server upon enabling maintenance mode

### ISSUE THREAD

**Issue by LucaBarbaLata** [pterodactyl/panel#5184]
### Current Behavior

If some servers are running and i activate the maintenance mode on the node the server wont stop. Can tell by looking in htop

### Expected Behavior

Servers to stop when enabling maintenance mode on a specific node

### Steps to Reproduce

Activate maintenance mode on a node while some servers are running

### Panel Version

1.11.7

### Wings Version

1.11.13

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
Maintenance mode has never stopped the servers, I think it only prevents new servers from being created via the API.

**Comment by LucaBarbaLata** [comment]
Then i think it should add this feature as an option, as i enable maintenance mode when im working and i need all resources that are used by the servers and its a pain to close all servers for one node as there is not a filter option on the panel

**Comment by danny6167** [comment]
This is working as intended.

If you want to mass-stop servers on a node, you can use the artisan bulk power commands https://pterodactyl.io/community/tutorials/artisan.html#server-bulk-power
