### ISSUE TITLE
Panel is incorrectly reporting disc usage for servers

### ISSUE THREAD

**Issue by tobywhiting10** [pterodactyl/panel#5186]
### Current Behavior

The panel is drastically under reporting the storage usage of game servers, specifically a modded Minecraft server in this case.
The panel says it's using ~9 GB when in fact the server is using closer to 40gb. 

therefore any limits set in the panel become useless and twice now as the server filled the hard disc and crashed.

Almost identical issues to the problem described in [#2445](https://github.com/pterodactyl/panel/issues/2445), however the solution seemed to be an update which is not applicable in this situation.

### Expected Behavior

The panel should correctly report the amount of storage used by the container and the disc utilisation limits should be functional.

### Steps to Reproduce

instal the latest version of the panel and wings following the documentation 
setup a fabric Minecraft server 
observer utilisation vs the file size of the container volume

### Panel Version

1.11.7

### Wings Version

1.11.13

### Games and/or Eggs Affected

MC (fabric)

### Docker Image

Java 18 (ghcr.io/pterodacty/yolks:java_18)

### Error Logs

```bash
wings: https://ptero.co/nocikucujo
panel: No such file or directory ):
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by MackenzieMolloy** [comment]
When you restart the Fabric server, does the Disk Usage get updated to the actual usage?

**Comment by tobywhiting10** [comment]
No, rebooting has no change.
The disc usage does seem to steadily increase as the server gets bigger so it is reading something, however, it is still several gigabytes below the container.

**Comment by danny6167** [comment]
How are you measuring the actual size of the server ?

**Comment by tobywhiting10** [comment]
A combination of:
- Looking at the total system utilisation (wings and this game server are the only things installed)
- Looking at the size of the volume for the game server (/var/lib/pterodactyl/volumes) 

There are no databases or anything additional on the server aside from two backups made within the panel which I have accounted for

As the panel itself does not show the sizes of folders within the server and folder permissions are preventing me from drilling into the docker volume I cannot see exactly what is using the storage outside of 'the docker volume is massive compared to what pterodactyl reports'

**Comment by danny6167** [comment]
Total system utilization isn't really a reliable metric for this.

Running something like this (as root) should get you some better numbers you can compare to what the panel reports.

```bash
cd /var/lib/pterodactyl/volumes/
du -d1 -h
 ```

**Comment by tobywhiting10** [comment]
It seems like I've got to the bottom of it!

Thanks to you informing me of the 'DU' Command, I was able to locate what was using the space.
As it turns out, the volume for the game server is being reported correctly.
For some reason, there were 48 gigabytes in the archives folder. I am completely unsure how it got there as the server has only been up for a week. I have now rectified this and, in the meantime at least, everything seems normal. 

```root@pt-server:/var/lib/pterodactyl# du -cha --max-depth=2
48G    ./archives
64K     ./wings.db
8.0K    ./volumes/.sftp
229M    ./volumes/633d278c-cd9f-4f2a-b0a6-d8f30bd93c89
9.4G    ./volumes/b1614965-072b-45c9-9833-fac09f84f46a
9.6G    ./volumes
4.0K    ./states.json
7.8G    ./backups/942e666a-da4b-4b02-8f33-e7e2ed37503d.tar.gz
7.8G    ./backups/2b5a2a95-386a-42da-b8c2-32e9c98b39c9.tar.gz
7.8G    ./backups/2fa61d36-dccf-4780-b3f4-7847f6a7f2ef.tar.gz
7.8G    ./backups/2df71c3b-11ef-426c-96d3-34dd0d89de8a.tar.gz
7.8G    ./backups/873fe759-749c-460b-b1ad-02a2bf494c13.tar.gz
39G     ./backups
49G     .
49G     total
```


Thank you very much for your help, apologise it ended up being so simple!
I will let you know if something goes wrong again, at this rate the disc will be full again tomorrow if there is ;-)
