### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Bobbbe** [pterodactyl/panel#5188]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hello, I apologize for contacting you through the github ticket but I couldn't find anywhere else where I could write to you.

### Describe the solution you'd like.

I am banned from the pterodactyl discord for posting pornographic links, I had several accounts, games, server and several personal things stolen (irl). I had a lot of trouble getting back what is most important to me but I got there.
I would like to be unbanned from the server please, the pterodactyl is very important to me, updates, help, etc. I have added several security features to my accounts (cell, authenticators, etc.) so that this does not happen again. Thank you in advance and hope to see you again on the discord soon. (Bobbber Id - 440568918478946315)

**Comment by danny6167** [comment]
Ban cleared - Welcome back @Bobbbe

**Comment by Bobbbe** [comment]
Thank you so much :)
