### ISSUE TITLE
ResourceUtilizationCache is hardcoded for 20 seconds

### ISSUE THREAD

**Issue by beckylemesmash** [pterodactyl/panel#5221]
### Current Behavior

ResourceUtilizationCache is hardcoded for 20 seconds

### Expected Behavior

https://github.com/pterodactyl/panel/blob/1.0-develop/app/Http/Controllers/Api/Client/Servers/ResourceUtilizationController.php#L33
This line to use config from .env

### Steps to Reproduce

Query server resource utilization API
Get real response only every 20 seconds

### Panel Version

1.11.7

### Wings Version

1.11.13

### Games and/or Eggs Affected

na

### Docker Image

na

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
This doesn't appear to be a bug. This is by design

**Comment by beckylemesmash** [comment]
Could ResourceUtilizationCache get `use_cache`=true/false param please. Or something like that?

**Comment by danny6167** [comment]
I don't see us adding anything like that.
If you need more realtime stats you can connect to the websocket and read the stats data from there.
