### ISSUE TITLE
Can't connect Velocity to Paper Server

### ISSUE THREAD

**Issue by Veyzn** [pterodactyl/panel#5223]
### Current Behavior

I'm trying to connect a Velocity Proxy to a Paper 1.20.4 Spigot. Which all worked on Localhost but doesn't work with pterodactyl

I used this installer to install Pterodactyl: https://github.com/pterodactyl-installer/pterodactyl-installer

### Expected Behavior

Normally you should connect to the lobby which does not work at the moment.

### Steps to Reproduce

Just create a velocity and a paper server. 

### Panel Version

Latest

### Wings Version

Latest

### Games and/or Eggs Affected

Minecraft Paper 

### Docker Image

Java 21

### Error Logs

```bash
https://pastebin.com/p3bJkNyC
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
- We do not provide support for third party installation methods 
- You didn't fill out the template with the requested info (latest is not a version)
- This is not a bug with Pterodactyl, this is a configuration issue on your end
