### ISSUE TITLE
Changed Wings Volumes location and now having issues

### ISSUE THREAD

**Issue by SoNotMC** [pterodactyl/panel#5227]
### Current Behavior

I changed the volumes directory location, moved all of the files and updated permissions to be fully correct and files do not show at all on the panel and the panel is saying 0 bytes used for all servers. However, servers start just fine and can access all of their files respectively, showing files are copied.

### Expected Behavior

For the panel to report correct usage and show files in the "Files" tab.

### Steps to Reproduce

Move the volumes directory
Restart wings and panel
Check sizes and files tab

### Panel Version

1.11.7 (In Docker)

### Wings Version

1.11.13 (In Docker)

### Error Logs

```bash
Does not apply, no errors.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by SoNotMC** [comment]
I did look into something that danny suggested a year ago in another issue (https://github.com/pterodactyl/panel/issues/4931) but I was unable to list anything in my DB. As apparently panel.nodes does not exist? My pterodactyl has been working perfectly until I decided to change the volumes location. I just want a quick solve of some kind.

**Comment by SoNotMC** [comment]
Okay with the panel.nodes not existing I forgot that as I am in docker I need to use the docker DB container.. sorry! still need to change the daemonBase tho..

**Comment by SoNotMC** [comment]
Okay changed it all correctly yet still the same issue. I can see the changes have applied because I can see the change in the copyable configuration for the node.

**Comment by danny6167** [comment]
Did you remember to add the new server location to the mounts in the wings docker compose file?

**Comment by SoNotMC** [comment]
Oh. Yeh, thanks Danny. HAHA
