### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state

### ISSUE THREAD

**Issue by IvanNovR** [pterodactyl/panel#5230]
### Current Behavior

I have installed pterodactyl panel on my home lab and pterodactyl panel on my VPS. In order to connect these two servers I am using netbird. When I try to navigate to the server page I get the following error:
WebSocket connection to 'ws://100.104.129.85:8080/api/servers/b1d608ae-637a-442e-a4b1-27df01156c59/ws' failed: WebSocket is closed before the connection is established.

![image](https://github.com/user-attachments/assets/817cca7b-2b51-47be-ba9f-30a67d6613d6)

### Expected Behavior

Ability to work with the created server and launch it

### Steps to Reproduce

1. Install panel and wings on two different servers
2. Create 2 netbird peers 
3. Allow peers to access each other
4. Create a node in the panel and a server

### Panel Version

1.11.7

### Wings Version

1.11.13

### Games and/or Eggs Affected

Minecraft paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
This is an issue with your setup and not a bug. Please keep support questions to the Discord
