### ISSUE TITLE
Fix docker image build & release for 1.11.8 release

### ISSUE THREAD

**Issue by jameskitt616** [pterodactyl/panel#5235]
### Current Behavior

The Pipeline failed building the latest Tag
https://github.com/pterodactyl/panel/actions/runs/11504795853

### Expected Behavior

It should successfully build and publish the latest version.

### Steps to Reproduce

-

### Panel Version

1.11.8

### Wings Version

-

### Docker Image

ghcr.io/pterodactyl/panel:latest

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
The build was fixed after release. 1.11.9 was released to resolve this because there isn't a good way to fix and rebuild the existing release.
