### ISSUE TITLE
Incorrect URL on all /admin endpoints using reverse proxy with local DNS

### ISSUE THREAD

**Issue by TheSainEyereg** [pterodactyl/panel#5241]
### Current Behavior

When the external domain and pterodactyl itself are kept on different machines, all links in https://ptero.mydomain.tld/admin lead to the domain that the reverse proxy accesses within the local network. Other pages in the panel work fine
![image](https://github.com/user-attachments/assets/d0d966a6-c1a3-4a1e-b152-b48c626faec7)

The only workaround I found is specifying Host header in reverse proxy
![image](https://github.com/user-attachments/assets/4946d793-6bcf-464e-86af-733dfeaf8542)

### Expected Behavior

In exactly the same configuration, all links on all sections of the panel have the domain ptero.mydomain.tld

### Steps to Reproduce

Background: 
By some coincidence I have several devices at home that work as servers and about a year ago I decided to distribute different tasks between them. For example, an Orange Pi with a fast SSD in it holds all the databases, an old weak Raspberry Pi is responsible for network-related stuff (reverse proxy, local DNS, VPN to home), and another Raspberry Pi is for self-hosted resources like Hoppscotch. Well, now you see what a mess is going on here... I recently bought an x86 server for everything that doesn't run on ARM and decided to put Wigs on it while hosting panel itself on a second Raspberry Pi and that's where I ran into trouble.
<img width="1126" alt="Untitled" src="https://github.com/user-attachments/assets/aa54414a-9a18-4d97-952f-a806f391909c">

So...

0. Install pterodactyl and nginx that exposes website to the internet to different machines
1. Set up external domain with reverse proxy that points to another server in your network
99. Visit /admin and try to navigate using sidebar

### Panel Version

1.11.9

### Wings Version

1.11.13

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue. #4984 is not a good solution
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
Set the panel app_url to the right value in the .env

**Comment by TheSainEyereg** [comment]
> Set the panel app_url to the right value in the .env

Already done, that's not the case

**Comment by TheSainEyereg** [comment]
I made it hard for myself. The only thing I needed to do was to add `proxy_set_header Host $host;` (which is recommended in all reverse proxy configuration guides). After that everything worked so **it was** configuration issue and #4984 **did** help

And btw I also forgot to specify settings for WebSocket to work with reverse proxy
