### ISSUE TITLE
Failed  to configure HTTPS || Pterodactyl failed install wings

### ISSUE THREAD

**Issue by NiviXstudio** [pterodactyl/panel#5243]
### Current Behavior

Cant install wings 

### Expected Behavior

I have followed the tutorial from YT, but it didn't work. I changed to another video tutorial but the result was the same. When I installed Wings manually/alternatively, it still didn't work.

### Steps to Reproduce

Idc

### Panel Version

latest

### Wings Version

latest

### Games and/or Eggs Affected

None

### Error Logs

```bash
EBUG: [Nov  7 21:10:03.184] making request to external HTTP endpoint endpoint=https://panel.nivix.my.id/api/remote/servers/reset headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[(redacted)] Content-Type:[application/json] User-Agent:[Pterodactyl Wings/v1.11.13 (id:Q3NOiciTMCWBgEFu)]] method=POST
 INFO: [Nov  7 21:10:03.185] sftp server listening for connections listen=0.0.0.0:2022 public_key=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9sF++jfcpI1NH61VAVLEzD42i2kCjdSQoW23Tal30L
FATAL: [Nov  7 21:10:03.185] failed to configure HTTPS server auto_tls=false error=open /etc/letsencrypt/live/node2.nivix.my.id/fullchain.pem: no such file or directory

Stacktrace:
open /etc/letsencrypt/live/node2.nivix.my.id/fullchain.pem: no such file or directory
github.com/pterodactyl/wings/cmd.rootCmdRun
        github.com/pterodactyl/wings/cmd/root.go:369
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.0/command.go:987
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/pterodactyl/wings/cmd.Execute
        github.com/pterodactyl/wings/cmd/root.go:71
main.main
        github.com/pterodactyl/wings/wings.go:17
runtime.main
        runtime/proc.go:267
runtime.goexit
        runtime/asm_amd64.s:1650
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Red-Banana-Official** [comment]
You are missing the SSL certificate for that domain.

**Comment by Red-Banana-Official** [comment]
> ### Current Behavior
> 
> Cant install wings
> ### Expected Behavior
> 
> I have followed the tutorial from YT, but it didn't work. I changed to another video tutorial but the result was the same. When I installed Wings manually/alternatively, it still didn't work.
> ### Steps to Reproduce
> 
> Idc
> ### Panel Version
> 
> latest
> ### Wings Version
> 
> latest
> ### Games and/or Eggs Affected
> 
> None
> ### Docker Image
> 
> _No response_
> ### Error Logs
> 
> ```shell
> EBUG: [Nov  7 21:10:03.184] making request to external HTTP endpoint endpoint=https://panel.nivix.my.id/api/remote/servers/reset headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[(redacted)] Content-Type:[application/json] User-Agent:[Pterodactyl Wings/v1.11.13 (id:Q3NOiciTMCWBgEFu)]] method=POST
>  INFO: [Nov  7 21:10:03.185] sftp server listening for connections listen=0.0.0.0:2022 public_key=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9sF++jfcpI1NH61VAVLEzD42i2kCjdSQoW23Tal30L
> FATAL: [Nov  7 21:10:03.185] failed to configure HTTPS server auto_tls=false error=open /etc/letsencrypt/live/node2.nivix.my.id/fullchain.pem: no such file or directory
> 
> Stacktrace:
> open /etc/letsencrypt/live/node2.nivix.my.id/fullchain.pem: no such file or directory
> github.com/pterodactyl/wings/cmd.rootCmdRun
>         github.com/pterodactyl/wings/cmd/root.go:369
> github.com/spf13/cobra.(*Command).execute
>         github.com/spf13/cobra@v1.8.0/command.go:987
> github.com/spf13/cobra.(*Command).ExecuteC
>         github.com/spf13/cobra@v1.8.0/command.go:1115
> github.com/spf13/cobra.(*Command).Execute
>         github.com/spf13/cobra@v1.8.0/command.go:1039
> github.com/pterodactyl/wings/cmd.Execute
>         github.com/pterodactyl/wings/cmd/root.go:71
> main.main
>         github.com/pterodactyl/wings/wings.go:17
> runtime.main
>         runtime/proc.go:267
> runtime.goexit
>         runtime/asm_amd64.s:1650
> ```
> 
> ### Is there an existing issue for this?
> 
>     * [x]  I have searched the existing issues before opening this issue.
> 
>     * [x]  I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
> 
>     * [x]  I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

You are missing the SSL certificate for that domain.
Also, don't follow any YT tutorials, or anything unofficial really..
Follow the official docs on https://pterodactyl.io/

So saying you checked the discord server etc.. well, is obviously a lie, as you would've known what the actual issue is.

**Comment by NiviXstudio** [comment]
> > ### Current Behavior
> > Cant install wings
> > ### Expected Behavior
> > I have followed the tutorial from YT, but it didn't work. I changed to another video tutorial but the result was the same. When I installed Wings manually/alternatively, it still didn't work.
> > ### Steps to Reproduce
> > Idc
> > ### Panel Version
> > latest
> > ### Wings Version
> > latest
> > ### Games and/or Eggs Affected
> > None
> > ### Docker Image
> > _No response_
> > ### Error Logs
> > ```shell
> > EBUG: [Nov  7 21:10:03.184] making request to external HTTP endpoint endpoint=https://panel.nivix.my.id/api/remote/servers/reset headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[(redacted)] Content-Type:[application/json] User-Agent:[Pterodactyl Wings/v1.11.13 (id:Q3NOiciTMCWBgEFu)]] method=POST
> >  INFO: [Nov  7 21:10:03.185] sftp server listening for connections listen=0.0.0.0:2022 public_key=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9sF++jfcpI1NH61VAVLEzD42i2kCjdSQoW23Tal30L
> > FATAL: [Nov  7 21:10:03.185] failed to configure HTTPS server auto_tls=false error=open /etc/letsencrypt/live/node2.nivix.my.id/fullchain.pem: no such file or directory
> > 
> > Stacktrace:
> > open /etc/letsencrypt/live/node2.nivix.my.id/fullchain.pem: no such file or directory
> > github.com/pterodactyl/wings/cmd.rootCmdRun
> >         github.com/pterodactyl/wings/cmd/root.go:369
> > github.com/spf13/cobra.(*Command).execute
> >         github.com/spf13/cobra@v1.8.0/command.go:987
> > github.com/spf13/cobra.(*Command).ExecuteC
> >         github.com/spf13/cobra@v1.8.0/command.go:1115
> > github.com/spf13/cobra.(*Command).Execute
> >         github.com/spf13/cobra@v1.8.0/command.go:1039
> > github.com/pterodactyl/wings/cmd.Execute
> >         github.com/pterodactyl/wings/cmd/root.go:71
> > main.main
> >         github.com/pterodactyl/wings/wings.go:17
> > runtime.main
> >         runtime/proc.go:267
> > runtime.goexit
> >         runtime/asm_amd64.s:1650
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Is there an existing issue for this?
> > ```
> > * [x]  I have searched the existing issues before opening this issue.
> > 
> > * [x]  I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
> > 
> > * [x]  I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.
> > ```
> 
> You are missing the SSL certificate for that domain. Also, don't follow any YT tutorials, or anything unofficial really.. Follow the official docs on https://pterodactyl.io/
> 
> So saying you checked the discord server etc.. well, is obviously a lie, as you would've known what the actual issue is.

Can I install wings without SSL certificate?

**Comment by Jcodeerd** [comment]
Don’t bother asking for support when you’re unable to read the error and use google to look up what it means. Additionally you also didn’t follow the official documentation, so this one is on you. Good luck in the future with such an attitude.
