### ISSUE TITLE
bump unarchiver from v4.0.0-alpha.8 to atleast v4.0.0-alpha.9

### ISSUE THREAD

**Issue by beckylemesmash** [pterodactyl/panel#5253]
### Current Behavior

v4.0.0-alpha.9
Alpha 9 introduces some new features, and also important fixes and optimizations, especially related to FileSystems and tar archives.
Using fs.WalkDir() is now much faster when walking large tar archives.

https://github.com/pterodactyl/wings/blob/v1.11.13/go.mod#L37

### Expected Behavior

walking .tar.xz 28mb would take much less than 15mins+ in wings(when unarchiving) I expect it to be much faster after version bump

### Steps to Reproduce

Try to unarchive node-v22.11.0-linux-arm64.tar.xz (28mb) (https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-arm64.tar.xz)
It will take 15 mins of CPU burning.
After further debugging it's because slow file walk (not wings code) but underlying archiver code.

### Panel Version

1.11.10

### Wings Version

1.11.13

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

P.S. This should resolve https://github.com/pterodactyl/panel/issues/4415

**Comment by beckylemesmash** [comment]
Reproducable test
```
func TestFilesystem_SpaceAvailableForDecompression(t *testing.T) {
	g := Goblin(t)
	fs, rfs := NewFs()

	g.Describe("test", func() {

				// copy the file to the new FS
				c, err := os.ReadFile("./testdata/test.tar.xz")
				g.Assert(err).IsNil()//ignore
				err = rfs.CreateServerFile("./test.tar.xz", c)

	    fs.SpaceAvailableForDecompression(context.Background(), "./", "test.tar.xz")//<-- issue is here.
	})
}
```

**Comment by beckylemesmash** [comment]
@DaneEveritt @matthewpi thank you in advance.

**Comment by yesBad** [comment]
> @DaneEveritt @matthewpi thank you in advance.

Dane doesn't work on the project anymore and why not make this a pull request in the Wings repo?

**Comment by beckylemesmash** [comment]
Understood. 

I'm afraid PR isn't as simple as changing version from v4.0.0-alpha.8 to atleast v4.0.0-alpha.9
It has small breaking changes that break tests and my go knowledge is limited. Started reading it yesterday only.

@yesBad

**Comment by beckylemesmash** [comment]
@matthewpi thank you. I'm keen to try this.
Could you let me know which branch could I use to compile and try it?
Or there will be official release?

P.S. I'm afraid to try `develop` because it has more commits.

**Comment by Koyorice** [comment]
After testing, an error will occur when restoring the backup
Using S3 backup, I guess the same is true for local backup
```
Stacktrace:
no extraction format
github.com/pterodactyl/wings/server.(*Server).RestoreBackup
        github.com/pterodactyl/wings/server/backup.go:167
github.com/pterodactyl/wings/router.postServerRestoreBackup.func3
        github.com/pterodactyl/wings/router/router_server_backup.go:161
runtime.goexit
        runtime/asm_amd64.s:1695

github.com/pterodactyl/wings/router.postServerRestoreBackup.func3
        github.com/pterodactyl/wings/router/router_server_backup.go:162
runtime.goexit
        runtime/asm_amd64.s:1695
```
Appears when decompressing an archive
```
Stacktrace:
invalid argument
github.com/pterodactyl/wings/router.postServerDecompressFiles
        github.com/pterodactyl/wings/router/router_server_files.go:458
github.com/gin-gonic/gin.(*Context).Next
        github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/pterodactyl/wings/router.Configure.ServerExists.func9
        github.com/pterodactyl/wings/router/middleware/middleware.go:158
github.com/gin-gonic/gin.(*Context).Next
        github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/pterodactyl/wings/router.Configure.RequireAuthorization.func8
        github.com/pterodactyl/wings/router/middleware/middleware.go:186
github.com/gin-gonic/gin.(*Context).Next
        github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/pterodactyl/wings/router.Configure.RequireAuthorization.func7
        github.com/pterodactyl/wings/router/middleware/middleware.go:186
```

**Comment by Koyorice** [comment]
About restoring the backup
from https://github.com/mholt/archives#create-archive
```
// we can use the CompressedArchive type to gzip a tarball
// (since we're writing, we only set Archival, but if you're
// going to read, set Extraction)
format := archives.CompressedArchive{
	Compression: archives.Gz{},
	Archival:    archives.Tar{},
}
```
https://github.com/pterodactyl/wings/blob/develop/server/backup/backup.go#L24
I think `Extraction` should be used here when reading

**Comment by beckylemesmash** [comment]
I'm so keen to try this in new release?

**Comment by beckylemesmash** [comment]
When could we try this in a release? This it the only missing thing 👍 🦾

**Comment by beckylemesmash** [comment]
@matthewpi @danny6167 by any chance do you know when/how to try this fix? There was no new release?

**Comment by yesBad** [comment]
> [@matthewpi](https://github.com/matthewpi) [@danny6167](https://github.com/danny6167) by any chance do you know when/how to try this fix? There was no new release?

You could just build the wings yourself with this guide: https://pterodactyl.io/community/customization/wings.html

**Comment by beckylemesmash** [comment]
@yesBad Thank you. 
I'm afraid to build production build from `develop` branch as it contains other stuff.

**Comment by beckylemesmash** [comment]
I know this PR has been open a while, but is there anything that could be contributed from the community to bring this into a release?
