### ISSUE TITLE
Request for User Friendly Resource Usage Graphs

### ISSUE THREAD

**Issue by BassManMike73** [pterodactyl/panel#526]
The current memory and CPU graphs, while descriptive, are easy to misunderstand for novice users, such as those who will rent server space from a provider using this software. 

I would suggest the graphs have an option to switch between a dynamic view (current method) and a static view showing 0% to 100% where 100% is the allocated amount of memory and CPU for the server. 

Adding a storage graph to the console page and section on the My Servers page would also be helpful in monitoring backup file sizes.

**Comment by Qasimmodo** [comment]
Don't think there's a need for a graph for the storage, maybe just a number something in the corner or something indicating how much space that container is using with a percentage. Agree with the rest 👍

**Comment by DaneEveritt** [comment]
Resource graphs are fixed in 0.8 to show min to max, and not keep scaling around.
