### ISSUE TITLE
The file you are attempting to open is too large to view in the file editor.

### ISSUE THREAD

**Issue by coderypro** [pterodactyl/panel#5266]
### Current Behavior

The file you are attempting to open is too large to view in the file editor.
![

### Expected Behavior

The file you are attempting to open is too large to view in the file editor.
![

### Steps to Reproduce

The file you are attempting to open is too large to view in the file editor.
![Screenshot_2024-12-31-14-36-44-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/8680ca7a-e124-48da-bb0d-f1ad0346a2d0)

### Panel Version

1.1.10

### Wings Version

1.1.7

### Games and/or Eggs Affected

All

### Docker Image

All

### Error Logs

```bash
https://ptero.co/tavibicuca
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by danny6167** [comment]
The error message is clear.
This is working as intended. There is no bug here.
