### ISSUE TITLE
Error running `composer install --no-dev`

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#528]
I've mentioned this before in Discord but never formally posted my error. When upgrading my panel and getting to the `composer install --no-dev` stage, I receive the following error:

```
> php artisan optimize


  [Predis\Connection\ConnectionException]
  Connection refused [tcp://redis:tcp://172.17.0.2:6379]


Script php artisan optimize handling the post-install-cmd event returned with error code 1
```

First off, I'm not sure why the connection refused message seems to include an appended second URL with the port. Second, it's worth noting that my redis instance is in a separate Docker container which is linked.

By default, these are the redis settings in the config/database.php file:

```    'redis' => [
        'client' => 'predis',
        'default' => [
            'host' => env('REDIS_HOST', 'localhost'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],
    ],
```

Within my .env file, I have the following:

```CACHE_DRIVER=redis # DO NOT EDIT! set using pterodactyl:env
SESSION_DRIVER=database # DO NOT EDIT! set using pterodactyl:env
REDIS_HOST=redis
```

The only way for me to get around this is to replace the values in the config/database.php file with the following:

```    'redis' => [
        'client' => 'predis',
        'default' => [
            'host' => 'redis',
            'port' => 6379,
            'database' => 0,
        ],
    ],
```

Once I make this change, I'm able to run the commands and proceed with the upgrade normally.

**Comment by DaneEveritt** [comment]
This is not an issue with the panel, and is most likely because your docker container is overriding some environment variable listed in the config file with its own, which is then causing that strange display and connection issue.

I am using defaults set by Laravel, nothing special, so if you truly believe this is a bug with the software it should be reported to the Laravel project.
