### ISSUE TITLE
Password updated change password incorrectly

### ISSUE THREAD

**Issue by parkervcp** [Pterodactyl/Panel#53]
In the /admin/accounts/view/<number> pages when you change a password it updates but no to the correct password.

It updated the passwords in plaintext and not encrypting the passwords in the db.

**Comment by DaneEveritt** [comment]
Issue is due to the code on [this line](https://github.com/Pterodactyl/Panel/blob/b63fc02cef6e61253ee2ae918a0c7f144666fdf3/app/Repositories/UserRepository.php#L127). `$user['password']` should actually be `$data['password']`.
