### ISSUE TITLE
Feature Request: Hide servers from your server list.

### ISSUE THREAD

**Issue by Qasimmodo** [Pterodactyl/Panel#531]
Would be nice if you could hide servers from your server list and unhide them. Makes it look cleaner and is individual to each user. If you're a administrator you by default see all servers.

**Comment by Qasimmodo** [comment]
Also being able to label the servers with a tag.

**Comment by DaneEveritt** [comment]
This is not something I will be building into the core of this application.

The best solution would be create a second non-admin account for your personal servers for organization so that your admin account is not directly tied to them.
