### ISSUE TITLE
Editable News section above the server overview

### ISSUE THREAD

**Issue by DoNotSpamPls** [Pterodactyl/Panel#533]
I think it would be a good idea to have a way to push out news to customers 
E.G. if there is going to be a planned maintenance, or that we updated something, etc.
And yes, I know there are websites for that, but people are more likely to notice if it's in the panel itself.

**Comment by Stannies** [comment]
A little thing to add to this, maybe also a per-user notification thing, so we can let specific people know specific stuff.

**Comment by Volxz** [comment]
Meh it seems a little overkill. That is what the WHMCS gods are for this is the panel not the helpdesk.

**Comment by schrej** [comment]
In my opinion, we could agree on an info box above the server page that can be edited to show some little information like planned maintenance and such. That would be reasonable and actually useful. Pushing emails/messages to specific or groups of users is overkill and not the purpose of this panel.

**Comment by DoNotSpamPls** [comment]
Yeah, I think I was a bit vague on the wording. I meant exactly what schrej said - an info box above the server list.

**Comment by DaneEveritt** [comment]
This is related to #142

**Comment by DaneEveritt** [comment]
Closing this in favor of #142

**Comment by DoNotSpamPls** [comment]
Well, #142 was closed with PR #1129, but that PR never added the feature requested here, so I'm reopening the issue.

**Comment by DaneEveritt** [comment]
No, #1129 is simply the beginning and will be expanded over time. 

You should be using other systems to get information out to customers for the cases you are mentioning.
