### ISSUE TITLE
Server create error

### ISSUE THREAD

**Issue by Bennyboy1695** [Pterodactyl/Panel#539]
When trying to create a server i get this error - "A TransferException was encountered while trying to contact the daemon, please ensure it is online and accessible. This error has been logged."
Heres the log file containing the full thing - https://gist.github.com/Bennyboy1695/905df77d7a476c88bb902844f670312d

**Comment by Polarcraft** [comment]
Issue can be resolved following: https://vps3.parkervcp.com/troubleshooting/connection-error
