### ISSUE TITLE
HMAC response authentication

### ISSUE THREAD

**Issue by BenjaminSchaaf** [pterodactyl/panel#545]
According to the reference [here](https://docs.pterodactyl.io/v0.6/reference) the HMAC for API requests is only sent by the client and validated by the server. It should be made clear that unless TLS is used, the HMAC of any responses also need to be validated or else an MITM attack is possible.

**Comment by CameronLonsdale** [comment]
[Web server configuration](https://docs.pterodactyl.io/docs/webserver-configuration) does seem to promote  using TLS by presenting the NGINX configuration first. However it is still possible to setup insecurely with Apache. Ideally, setting up TLS should be a mandatory step to ensure that the setup is secure by default. In that circumstance the HMAC may then be modified to accomodate for the integrity garunteed by TLS.
