### ISSUE TITLE
Use SweetAlert for logout message

### ISSUE THREAD

**Issue by Derkades** [Pterodactyl/Panel#546]
![image](https://user-images.githubusercontent.com/15892014/28031698-6b927afe-65a8-11e7-8adf-6afa0d806441.png)
Should be a very simple thing to do

**Comment by KasperFranz** [comment]
Why is it you want that?  - it is very rare to see that on a panel or any software

**Comment by schrej** [comment]
@KasperFranz It appears whenever you click the Logout button.

**Comment by Derkades** [comment]
The panel uses SweetAlert for all other alerts, so it makes sense to use it for the logout alert as well

**Comment by DaneEveritt** [comment]
closed by #634
