### ISSUE TITLE
Memory Usage Much Higher in Alpine Container than on Dedicated Machine for MC Server

### ISSUE THREAD

**Issue by BassManMike73** [Pterodactyl/Panel#549]
I'm running several modded Minecraft servers and am seeing larger than normal memory usage for them. One server is running at around 1-1.5GB RAM usage on a dedicated machine and 6GB+ in the container.

**Comment by DaneEveritt** [comment]
You will need to provide way more information for this to be an issue we can look into, as there is nothing in this issue I can work with. Things such as machine specs, server configuration, all of the info that was asked for when you made this issue, logs and metrics showing this usage.

**Comment by BassManMike73** [comment]
This can probably be closed. I'm still doing some more testing on my end. One of the mods on the Discord asked me to submit the GitHub report, but I'm not convinced it's a Ptero issue yet.
