### ISSUE TITLE
core.json Pink Block Code doesn't exist

### ISSUE THREAD

**Issue by Infernus00** [Pterodactyl/Panel#550]
https://daemon.pterodactyl.io/docs/configuration

I can't see the core.json example file, could you please solve this bug? I need that file in order to complete the installing of the panel.

**Comment by jffz** [comment]
It's not a bug, core.json is created when you add a node into the panel.

**Comment by Infernus00** [comment]
My Panel is fully without .css, it can't read the css files because the locations are different. How could i resolve this?

**Comment by Infernus00** [comment]
http://93.113.102.155/pterodactyl/server.php/auth/login
I don't get it how to make the template work.
I'm new in this kind of thing, what logs do you need?

**Comment by jffz** [comment]
```bash
chown -R www-data:www-data *
```

**Comment by Infernus00** [comment]
Done. Still nothing...

**Comment by DaneEveritt** [comment]
This is not an issue with the software itself, rather a configuration issue. Please use our discord or forums for more assistance.
