### ISSUE TITLE
[Feature Request] Assign Custom Ports

### ISSUE THREAD

**Issue by SnowBlinderYT** [Pterodactyl/Panel#551]
It might be useful to Assign Custom Ports to Server(Docker) Ports 
Because some Plugins for Bungeecord and Bukkit need to open some Ports ( Vote Plugin or Socket Plugins for example)

Can this be done with Pterodactyl?

**Comment by Derkades** [comment]
This can already be done

Edit server > Build configuration > Assign additional ports

**Comment by Polarcraft** [comment]
As Derkades said you can just simply assign any additional ports you would need, though next time for any questions please use the discord or the forums instead of github. Discord and Forums can be located on the site (http://pterodactyl.io).

**Comment by SnowBlinderYT** [comment]
@Derkades @Polarcraft Aren't they then pointing to 25565 of the Container?

**Comment by parkervcp** [comment]
They are not pointing 25565 at the containers. It on;y opens up ports you put in and each port needs to be different.

**Comment by SnowBlinderYT** [comment]
Hmm | Ok | Thanks for the Info @parkervcp :P

**Comment by Strike1031** [comment]
Is there any API to do that?
api/application/servers/{id}/build  is not working in the latest version.
