### ISSUE TITLE
Host shared folders on servers

### ISSUE THREAD

**Issue by F0x06** [pterodactyl/panel#552]
Hi, I have 8 Garry's Mod servers, and I'm thinking to switch to Pterodactyl to manage my servers, this panel is amazing! Excellent work!. But I need one last thing, shared folders, typically in Garry's Mod you can mount other source games content with the file `garrysmod/cfg/mount.cfg`

```
"mountcfg"
{
        "cstrike"       "/home/container/SHARED_SRCDS_CONTENT/cstrike"
        "tf"            "/home/container/SHARED_SRCDS_CONTENT/tf"
... etc
```

For all contents i have a 27G folder, which solution i have to allow server's docker's to access that folder without copying it every time ?

Thank you !

**Comment by Derkades** [comment]
Or you could create a cron job that copies the file from one server to the other every few minutes. Server files are stored in /srv/daemon-data/

**Comment by F0x06** [comment]
I don't want to copy 27G every time, 216G for 8 servers is not good, I want to mount the 27G contents folder in servers dockers. So they can access it to mount shared contents.

**Comment by F0x06** [comment]
As a temporary solution I edited the server creation function to add the read-only host shared folder `/srv/daemon-shared`

```diff
diff --git a/src/controllers/docker.js b/src/controllers/docker.js
index ce35e14..742a15f 100644
--- a/src/controllers/docker.js
+++ b/src/controllers/docker.js
@@ -369,12 +369,18 @@ class Docker {
                             Destination: Config.get('docker.timezone_path'),
                             RW: false,
                         },
+                        {
+                            Source: "/srv/daemon-shared",
+                            Destination: "/shared",
+                            RW: false,
+                        },
                     ],
                     Env: environment,
                     ExposedPorts: exposed,
                     HostConfig: {
                         Binds: [
                             Util.format('%s:/home/container', this.server.path()),
+                            Util.format('%s:/shared', "/srv/daemon-shared"),
                             Util.format('%s:%s:ro', Config.get('docker.timezone_path'), Config.get('docker.timezone_path')),
                         ],
                         Tmpfs: {
```

So, now on my Garry's Mod servers i can use
```
"mountcfg"
{
        "cstrike"       "/shared/source_contents/cstrike"
...
}
```

It would be awesome if we can have a setting on the server creation page to add custom mounts,

for example, a list with **\<host path\>** **\<server path\>** **\<read-only 1\|0\>**

In my case:

* `/srv/daemon-shared /shared 1`

**Comment by DaneEveritt** [comment]
We have this on the radar for the next daemon release. 👍🏼

**Comment by F0x06** [comment]
@DaneEveritt 
Awesome thank you ! :)

I'm verry happy to see a game panel so powerful, beautiful, and free ! will support you on patreon, and after migration of my game servers, i will also publish my service/packs

**Comment by DaneEveritt** [comment]
Reopening this because I don't believe we have another issue tracking this feature currently.

**Comment by F0x06** [comment]
@DaneEveritt
Oh sorry.

**Comment by Latouth** [comment]
Fun fact... A couple months ago I mentioned in the Discord server for a shared folder!

**Comment by xion87** [comment]
this is will be implemented on 0.7.x?

**Comment by danrokzz** [comment]
*push* one of the most missed features which prevent us to replace our current panel with pterodactyl  :/

**Comment by xion87** [comment]
+1 shared folder is one of limitation using dockers and it prevent me to use some tools

**Comment by DaneEveritt** [comment]
I am aware that you want this, commenting the same `+1` on it every week does not make it happen any quicker.

**Comment by rouing** [comment]
It would be nice to see docker volume support for this.

**Comment by F0x06** [comment]
Any update on this :) ?

**Comment by Blamo27** [comment]
@F0x06 Yes could be great

**Comment by xaviergmail** [comment]
If anyone is still looking to achieve this until we get an official solution, the following has worked for me (Syntax has changed a bit since F0x06's answer)
```
{
    Target: "/shared",
    Source: "/srv/daemon-shared",
    Type: 'bind',
    ReadOnly: true,
},
```

Also, #714 is related

**Comment by Forge-Media** [comment]
I'm thinking of implementing @xaviergmail suggestion to try solve duplicate source game data for multiple instances of CSGO, if each server can access a shared mount which contains the files. I've only got 50GB of storage on my VPS.

1. If the mount is read-only what happens when CSGO (or another source game) starts and checks for updates? It can't write to the mount, would this not cause problems? 
2. Simply change the mount to allow writing or have a CRON script on the host to update the game in the shared mount?
3. Would there be any advantage to using a Docker Volume over a simple folder on the host?

**Comment by xaviergmail** [comment]
My suggestion mainly pertains to Garry's Mod where it pulls in content from other source games (e.g mounting CS:S, CS:GO,  Ep1, Ep2, TF2, ZPS, Portal 1 + Portal 2, the list goes on and on) using `cfg/mount.cfg` Where this uses up easily 50GB+ per install.

For your use case I'd instead recommend just using a folder on the host (which the host itself would update) and editing the csgo egg to remove the auto updater on restart.

**Comment by parkervcp** [comment]
> I'm thinking of implementing @xaviergmail suggestion to try solve duplicate source game data for multiple instances of CSGO, if each server can access a shared mount which contains the files. I've only got 50GB of storage on my VPS.
> 
> 1. If the mount is read-only what happens when CSGO (or another source game) starts and checks for updates? It can't write to the mount, would this not cause problems?
This would cause updates to error out.

> 2. Simply change the mount to allow writing or have a CRON script on the host to update the game in the shared mount?
If every server is trying to adjust files at the same time it will most likely cause lots of issues.

> 3. Would there be any advantage to using a Docker Volume over a simple folder on the host?
No advantage of a volume over the bind mount that we already do. Volumes are also in the /var/lib/docker folder which can cause issues of its own.

**Comment by Forge-Media** [comment]
@xaviergmail thanks, I've created a custom CSGO egg for this.

@parkervcp I will keep the mount read-only for safety and shedule updates on the host. I have successfully run multiple instances of CSGO with separate start scripts, server.cfg and ports, though I was using an alternative Linux game manager to do this, so it should technically be possible, I hope with Pterodactyl.

**Comment by Forge-Media** [comment]
@xaviergmail thanks, I've created a custom CSGO egg for this. Though I would still need to mount the host (CSGO) folder for the containers to access it, correct?

@parkervcp I will keep the mount read-only for safety and shedule updates on the host. I have successfully run multiple instances of CSGO with separate start scripts, server.cfg and ports, though I was using an alternative Linux game manager to do this, so it should technically be possible, I hope with Pterodactyl.

I should have asked, when a server is currently created using Pterodactyl, the `HOME` variable is set to `/home/container`. This allows the start script to simply reference `./srcds_run`.

- Would it be possible to alter the start script in Pterodactyl to: `./srv/daemon-shared/srcds_run`?
- Or best to alter the `HOME` variable to `/srv/daemon-shared`?

**Comment by parkervcp** [comment]
That is again more of a #714 then. As I completely understand what you were looking for.

**Comment by kgns** [comment]
@Forge-Media for CS:GO, you can create a master server using ptero, then create a symbolic link at /srv/shared/csgo folder pointing to the master server folder (i.e. /srv/daemon-data/xxx-xxx-xxx-xx-xx/csgo) with ln -s command. Then use the above configuration to load /srv/shared/csgo folder as a bind mount. And lastly on your install script (or somewhere else), overwrite all the bulky .vpk files with symbolic links pointing to the actual data stored in /srv/shared/csgo/ mount (ln -sf command). This will save you 16-18 GB per server. You can apply a similar logic for maps if you wanted to. It is tedious to maintain, but better than having to waste 20gb per server.

Since the .vpk files will be symbolic links that are writable in the docker container, when the game auto updates, it will delete the symbolic link (just the link), and download the new version of that vpk file which should be 100 MB each. You can then have a cron job to reapply the symbolic links (deleting updated vpk files, instead linking them again to the master server's updated vpk files).

**Comment by LubricantJam** [comment]
Does anyone have a custom CS:GO egg for this?

**Comment by igortomiatti** [comment]
I tried to do it this way, but the container is unable to access symbolic link outside his scope.

How did you make it work?

I created a base server at /home/steamcmd/base_csgo and made symbolic links pointing to all files in the server folder created by pterodactyl in /srv/daemon-data/"server id"

Then I changed the owner of the files to the pterodactyl user and group.

**Comment by kgns** [comment]
mount your base installation folder using things discussed above, like: https://github.com/pterodactyl/panel/issues/552#issuecomment-522169995

if you set your target the same as your source, then your symlink will function both on the host machine and in the container

**Comment by igortomiatti** [comment]
@kgns Now it worked, I had forgotten that step.

Thank you!

**Comment by sebackend** [comment]
> If anyone is still looking to achieve this until we get an official solution, the following has worked for me (Syntax has changed a bit since F0x06's answer)
> 
> ```
> {
>     Target: "/shared",
>     Source: "/srv/daemon-shared",
>     Type: 'bind',
>     ReadOnly: true,
> },
> ```
> 
> Also, #714 is related

Where does this configuration go? I need to share the base installation from csgo across all my servers

**Comment by dodoflix** [comment]
> > If anyone is still looking to achieve this until we get an official solution, the following has worked for me (Syntax has changed a bit since F0x06's answer)
> > ```
> > {
> >     Target: "/shared",
> >     Source: "/srv/daemon-shared",
> >     Type: 'bind',
> >     ReadOnly: true,
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, #714 is related
> 
> Where does this configuration go? I need to share the base installation from csgo across all my servers

Did you find where this config goes? Or anybody knows where to put this config piece?

**Comment by zag1024** [comment]
> > > If anyone is still looking to achieve this until we get an official solution, the following has worked for me (Syntax has changed a bit since F0x06's answer)
> > > ```
> > > {
> > >     Target: "/shared",
> > >     Source: "/srv/daemon-shared",
> > >     Type: 'bind',
> > >     ReadOnly: true,
> > > },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also, #714 is related
> > 
> > 
> > Where does this configuration go? I need to share the base installation from csgo across all my servers
> 
> Did you find where this config goes? Or anybody knows where to put this config piece?

This is no longer necessary, as mounts are built into the current versions of Wings and the panel. You can find the instructions for configuring this feature here: [https://pterodactyl.io/guides/mounts.html](https://pterodactyl.io/guides/mounts.html)
