### ISSUE TITLE
Spigot BuildTools implementation idea / feature request

### ISSUE THREAD

**Issue by Derkades** [Pterodactyl/Panel#554]
Automatic building of spigot has been removed, because of high cpu usage. This is a possible solution:

1. Build in a docker container in some directory e.g. /srv/daemon-data/buildtools
2. Delete everything except the server jar
3. Copy server jar to server and rename to server.jar

Next time a spigot jar is needed:
If server jar in directory is newer than x days, just copy the file. Otherwise, build then copy.
(x would be the number of days until spigot gives the build outdated warning)

**Comment by DaneEveritt** [comment]
This can be resolved with a PR to the repository seeder. Until such time I will not be going in and adding spigot building support.
