### ISSUE TITLE
Daemon won't start up just crashes when command is sent or rebooted.

### ISSUE THREAD

**Issue by Sans-Skelly** [Pterodactyl/Panel#556]
When i do wings service start or npm start in the directory /srv/daemon here's what i get:

`
20:34:05.681Z  INFO wings: + ------------------------------------ +

20:34:05.683Z  INFO wings: | Running Pterodactyl Daemon v0.4.3    |

20:34:05.684Z  INFO wings: |        https://pterodactyl.io        |

20:34:05.684Z  INFO wings: |  Copyright 2015 - 2017 Dane Everitt  |

20:34:05.684Z  INFO wings: + ------------------------------------ +

20:34:05.684Z  INFO wings: Loading modules, this could take a few seconds.

20:34:06.033Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...

20:34:06.042Z  INFO wings: Checking container networking environment...

20:34:06.048Z  INFO wings: Attempting to start SFTP service container...

20:34:06.082Z  INFO wings: Contacting panel to retrieve a list of currrent services available to the node.

20:34:06.138Z  INFO wings: Found network interface for daemon: pterodactyl_nw

20:34:06.165Z  INFO wings: SFTP container successfully booted.

20:34:06.165Z  INFO wings: Checking pterodactyl0 interface and setting configuration values.

20:34:06.166Z  INFO wings: Checking gateway for pterodactyl0

20:34:06.194Z  INFO wings: Gateway detected as ###.##.#.## for pterodactyl0.

20:34:06.203Z FATAL wings: A fatal error caused the daemon to abort the startup. (additional={})

    Error: Error while attempting to fetch list of services (HTTP/521)

        at Request.ex [as _callback] (/srv/daemon/src/controllers/service.js:93:29)

        at Request.self.callback (/srv/daemon/node_modules/request/request.js:188:22)

        at emitTwo (events.js:106:13)

        at Request.emit (events.js:191:7)
        at Request.<anonymous> (/srv/daemon/node_modules/request/request.js:1171:10)

        at emitOne (events.js:96:13)

        at Request.emit (events.js:188:7)

        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/request/request.js:1091:12)

        at IncomingMessage.g (events.js:292:16)

        at emitNone (events.js:91:20)
`

Any fixes for this?

**Comment by DaneEveritt** [comment]
This is not a bug with this software.

https://support.cloudflare.com/hc/en-us/articles/200171916-Error-521-Web-server-is-down
