### ISSUE TITLE
Re: Previously fixed security flaw

### ISSUE THREAD

**Issue by ryantheleach** [Pterodactyl/Panel#557]
https://github.com/Pterodactyl/Panel/commit/829453f805590486ca3a608226ad40e36ed51772

Just stops using jquery.terminal and instead uses an inhouse solution.

Was the issue with [[]] upstream? If so, has upstream been alerted, or was this by design?

**Comment by DaneEveritt** [comment]
It was by design and documented on their site, I just did not notice it initially.
