### ISSUE TITLE
SFTP problem (connection refused) 

### ISSUE THREAD

**Issue by tommylee464** [Pterodactyl/Panel#560]
![capture du 2017-07-23 10-50-45](https://user-images.githubusercontent.com/29803716/28500357-d9e0a2c4-6f94-11e7-98e1-4df8f817e98c.png)

step 1 open 2022 port
step 2 start the daemon
step3 systemctl status wings (no error)
step4 open filezilla 
step5 sftp://user@host:2022
step6 connection refused

**Comment by tommylee464** [comment]
i send a screenshot

**Comment by tommylee464** [comment]
here it's my firewall script 

![capture du 2017-07-23 09-56-45](https://user-images.githubusercontent.com/29803716/28499862-60467bca-6f8d-11e7-8669-951f42acdb3b.png)

**Comment by parkervcp** [comment]
Wouldn't it be stfp://user@host:2022

**Comment by tommylee464** [comment]
yes i have tested to

**Comment by tommylee464** [comment]
its just an error in my issue i edit this

**Comment by tommylee464** [comment]
the ftp work good on the website its just on filezilla say connection refused

**Comment by parkervcp** [comment]
My filezilla looks like this. Now it should be said I am using sftp://vps5.parkervcp.com without the :2022. instead the port gets put later.

![screen shot 2017-07-23 at 10 56 23 am](https://user-images.githubusercontent.com/1207679/28500401-9ee297da-6f95-11e7-9c82-9163d1931b3f.png)

**Comment by tommylee464** [comment]
i test it

**Comment by tommylee464** [comment]
connection refused when open "user@host" 2022

**Comment by tommylee464** [comment]
i have a rule to redirect port 2022 to an other ip or interface?

**Comment by parkervcp** [comment]
Where are you putting user@host.

**Comment by parkervcp** [comment]
get on discord if possible

**Comment by tommylee464** [comment]
no minecraft@railfaction.tk

**Comment by tommylee464** [comment]
open "link_e012cafd@railfaction.tk" 2022
Erreur :	Connection refused

**Comment by tommylee464** [comment]
ok im bad in english i write english and not talk english

**Comment by DaneEveritt** [comment]
This is not a bug with our software, but sounds more like a networking issue. Please use our Discord or forums for further assistance.
