### ISSUE TITLE
Ability to rename (or nickname) servers for normal users

### ISSUE THREAD

**Issue by stanjg** [pterodactyl/panel#563]
I think it would be handy if users would be able to rename their own servers, or give them a nickname if renaming isn't possible. As a hosting provider using Pterodactyl this would prevent a lot of customers having complaints about not knowing which server is which, it will also help our support team as they have to rename all the servers a lot.

I hope you could take this suggestion into consideration :)

**Comment by Esity** [comment]
+1

**Comment by Qasimmodo** [comment]
I don't really think that needs to be build into the core of pterodactyl.

**Comment by schrej** [comment]
How about allowing users to change the description?

**Comment by Stannies** [comment]
@schrej That would be sufficient, but the name (or a nickname that would display next to the name, just as big) would be even better.
