### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by lllllIll** [Pterodactyl/Panel#568]
Hi, 
I make an fresh install of Pterodactyl on server and i have an error 500 All time 
I have this folder
![screen](https://user-images.githubusercontent.com/28443695/28736627-026362c2-73eb-11e7-8f92-c7f5e4806a09.png)
And when i go in public folder i always go on public/auth/login
![croquis 1](https://user-images.githubusercontent.com/28443695/28736682-4b6cf596-73eb-11e7-91a7-5ff59232a010.png)

Can you help me ?
Thank for help me

---------------------
uname -a : Linux game 2.6.32-042stab108.5 #1 SMP Wed Jun 17 20:20:17 MSK 2015 x86_64 GNU/Linux
php -v : PHP 7.1.7-1+0~20170711133844.5+jessie~1.gbp5284f4 (cli) (built: Jul 11 2017 14:13:18) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.7-1+0~20170711133844.5+jessie~1.gbp5284f4, Copyright (c) 1999-2017, by Zend Technologies

**Comment by schrej** [comment]
If you don't have another server with a newer linux kernel you won't be able to run our daemon and therefore can't use the panel I'm afraid. Also, please use our forums at https://forums.pterodactyl.io or our discord server https://pterodactyl.io/discord for support please.
