### ISSUE TITLE
Add file blacklist for Services

### ISSUE THREAD

**Issue by alukar4eg** [pterodactyl/panel#569]
I use gsp-panel and want migrate to Pterodactyl.

But i need block for users upload or download (in web or in sftp ) some files for example  .dll .so .exe  etc 
in gsp-panel tеhis is implemented like this  
https://image.prntscr.com/image/3kopo4nKQoCAUs4Uo37pyw.png

**Comment by schrej** [comment]
This is pretty useless. Users can simply change the file extension after up/download. We only support linux at the moment as well, so .exe or .dll files cannot be exectued anyways.

**Comment by alukar4eg** [comment]
@schrej  Rust or Hurtworld  or some unity (C#) game work in linux .  Lot of users chenge or add some hooks  add fakeOnline.
In gsp or tc admin if file in blacklist you cant rename it or create  or upload.

**Comment by schrej** [comment]
Why would you want to prevent server owners from modifying their server? Also, are those blacklist global or per server/service?

**Comment by ET-Bent** [comment]
@KasperFranz some steam games also use DLLs on Linux.

**Comment by alukar4eg** [comment]
@schrej  
1. Some Users modify in unity game Assambly-cSharp.dll. He can make fake online\or change status(Modding or Community) and change  any parameters of server.
As result Developers ban ip of this server and all server on this ip gone from server lists. This is a big problem for hosting.
2. On Ark \Unreal Servers same problems.

3. Paid plugins for servers . When user rent server he can rent for it some  unique plugin. Plugins in .dll )
 
Black listed file extensions is very necessary function for the control panel. 
The function is present in the panels TcAdmin Gsp-Panel GameAP . And it will be greate integrate it in Pterodactyl

**Comment by schrej** [comment]
Ok then, let's reopen this.
I would do it on a per-service basis.
What do you think, @DaneEveritt ?

**Comment by ET-Bent** [comment]
Per service basis sounds good. SFTP restrictions will be a bit more complicated.

**Comment by schrej** [comment]
As this will only be implemented in the new daemon (if at all) it might not be that difficult, depending on wether thats possible with sftp and the library we use allows it

**Comment by alukar4eg** [comment]
Great News!!! )))  Thx!  @ET-Bent  @schrej

**Comment by alukar4eg** [comment]
@schrej @ET-Bent  Hi friends when you add this feature???
I whant migrate from gsp to ptero)))

**Comment by schrej** [comment]
We have loads of other stuff to do at the moment as we are rewriting huge parts of the panel and are doing a complete rewrite of the daemon. It will take some time to get implemented and was therefore marked as a backburner.

**Comment by AkumuRu** [comment]
Hello. 
Any updates on this feature request? This is exactly what we are missing on Pterodactyl at this moment.

**Comment by DaneEveritt** [comment]
Basic concept for this is implemented now. I would strongly recommend not 100% relying on the logic for security purposes, but it should handle most basic use cases. Specifically nothing is stopping a malicious process from being able to modify these files, not much I can do about that right now (or am interested in doing honestly).

It'll try to stop users from writing to these files (directly, or via uploads/unarchive/copy) as best it can via the API.

This is implemented as a hidden feature in Eggs for the time being, it'll show up in the UI once we have admin stuff setup for it.

**Comment by alukar4eg** [comment]
Nice function but can you add hide function for this files for all users by `file_denylist `
And add function for block some files for subusers (For example subuser must have access for configs but not for client plugins it very useful for rust \ mincraft\unturned etc games. )
