### ISSUE TITLE
Drop-down list of values for variables

### ISSUE THREAD

**Issue by alukar4eg** [pterodactyl/panel#570]
Make it possible to preset several values ​​for variables . 
And allow users to select from the drop-down list this values.

Like : http://prntscr.com/g2w13o

**Comment by tenten8401** [comment]
Just wanted to poke this issue as I think it might be something good to sneak into 0.7

**Comment by fo0** [comment]
I currently also using the great ptero system and its very nice.
Every time I am adding a value from the variables at the games (tab: startup), I would wish there would be a drop-down to select them from the list 👍
