### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by Dyceman** [Pterodactyl/Panel#571]
I am getting this when trying to call to the API.
https://gist.github.com/Dyceman/1704c13553053568ff43124f78a213f7

**Comment by DaneEveritt** [comment]
Did you change your `APP_KEY` at some point?

**Comment by Dyceman** [comment]
No I didn't but, I updated the panel to the latest version and that is when that error started occuring.

**Comment by DaneEveritt** [comment]
I think (only way this happens) that you somehow updated that APP_KEY which causes anything previously encrypted using it to fail to decrypt with this error. It isn't specific to the API and likely happens with the SFTP passwords for servers that existed prior to the update.

**Comment by Dyceman** [comment]
I didn't update the APP_KEY. I even created a new APP_KEY and tried that and it still doesn't work. What do I need to do to get this working?

**Comment by DaneEveritt** [comment]
Creating a new APP_KEY is absolutely not the fix, and likely just broke it even more. The only fix is to either find a backup of the .env and replace that APP_KEY, or to delete all existing API keys from the DB and re-create them.

**Comment by Dyceman** [comment]
Removing all api keys worked! Thank you for your excellent support, Dane!!!!
