### ISSUE TITLE
Custom DNS in container 

### ISSUE THREAD

**Issue by alukar4eg** [Pterodactyl/Panel#572]
Hi all! 

if i start container from console  by
```
docker run --rm -it alukar/host /bin/bash
container@0407b52ac07c:~$ cat /etc/resolv.conf
search XXXX.org
nameserver 91.XX.XX.XX
nameserver 91.XX.XX.XX
```
And all ok for me

If i start contaner from panel  by Pterodactyl daemon i get this in resolv.conf/
```
I have no name!@container:~$ cat /etc/resolv.conf
search XXXX.org
nameserver 127.0.0.11
options ndots:0
```
And container can't reslove any host . Pls help with this problem. I need use my custom dns server.

I think by default it use google dns . But my ddos protection are block it.

**Comment by ET-Bent** [comment]
How did you set your DNS server to Docker?

**Comment by alukar4eg** [comment]
@ET-Bent i try add my dns to /etc/docker/daemon.json

{
 "dns": ["91.XX.XX.XX","91.XX.XX.XX"]
}
But Pterodactyl daemon start container with own rules

**Comment by alukar4eg** [comment]
@ET-Bent 
I change dns servers in  
https://github.com/Pterodactyl/Daemon/blob/35d65b5eecf9361b0b2fba41868b92888385173b/src/controllers/docker.js#L391
and all start working for me.

But last problem how change dns in pterodactyl SFTP container ?

For futher may by you can add dns setting while installing deamon??

**Comment by ET-Bent** [comment]
We also figured this issue out. Editing these lines https://github.com/Pterodactyl/Daemon/blob/43b0dea759527e152cc4eee86f1a6aa023d97fad/src/controllers/sftp.js#L102 and removing the sftp container + restarting the daemon lead to the expected behavior.

@schrej please close this ticket. RESOLVED

**Comment by alukar4eg** [comment]
finde sftp and change it for me
https://github.com/Pterodactyl/Daemon/blob/43b0dea759527e152cc4eee86f1a6aa023d97fad/src/controllers/sftp.js#L102
thx  FlatronEZ from support in discord )

**Comment by schrej** [comment]
@alukar4eg as you opened the issue you can close it yourself btw ;)

**Comment by CaptAintHere** [comment]
IMHO it is a solution to modify the code itself... It would be nice to have a setting in Pterodactyl to specify custom DNS servers.

**Comment by parkervcp** [comment]
It appears that for most people this isn't an issue though.
