### ISSUE TITLE
Scheduler Unusual Behavior

### ISSUE THREAD

**Issue by GhotiMayo** [Pterodactyl/Panel#573]
Last week, I had upgraded from v0.6.0-beta2.1 of the panel to the latest version on Ubuntu 16.04. This broke my scheduler as the version I was running was still using Supervisor. I switched over to the newer pteroq service instead, but the I could not get the panel's scheduler to do anything. I have tried everything from re-entering all the scheduled commands to flat-out rebooting the machine. Cron appears to be running normally, and the panel sends emails just fine too. I check the logs and failed_jobs and cannot find any useful/relevant information. Running **php artisan schedule:run** runs all of the scheduled commands once. A support team member looked into my problem and could not figure out what is going wrong, so I am thinking I am experiencing a bug.

**Comment by DaneEveritt** [comment]
Seems to be related to #258 but even that issue was unable to be solved.

**Comment by GhotiMayo** [comment]
Actually no, this seems to be different, because I am still able to trigger tasks with php artisan schedule:run. At least to me this appears to be different in that regard.

**Comment by GhotiMayo** [comment]
So I reinstalled the panel and reconnected it to my databases. I also ran **php artisan pterodactyl:tasks** which changed "Queued" from no to yes, but still did not make a difference with the scheduler running tasks. However, php artisan schedule:run no longer runs the tasks once. Since this is now like #258 I will close this one
