### ISSUE TITLE
Add Query Cheker to server

### ISSUE THREAD

**Issue by alukar4eg** [Pterodactyl/Panel#574]
May be you can add  GameQuery Cherker in service options. 
And some monitoring for cheking online or offline server. And if server 5 or more minutes not answer by query Restart it

You can use this project :
https://github.com/Austinb/GameQ

**Comment by DaneEveritt** [comment]
This would have to be done via the daemon, and not the panel itself to be viable, closing this as it is a known limitation and on the list for daemon improvements.
