### ISSUE TITLE
Add game update\game addons installer \Pre-Start scripts

### ISSUE THREAD

**Issue by alukar4eg** [pterodactyl/panel#578]
Hi i try this panel more then one weak . All grete but need more functional for service

 Running pre start server scripts . For example user whant update server or install pre-set addons (If rust - oxidemod , if unturned rocket mod etc...) Need some  choose preset-scripts run befor server start. Maybe add some scripts editor in service options. (For example add some virebel to entrypoint.sh and replace it with custom scripts, it give opportunity more flexible controll any service)
For example preset and update Ark Mods . Update and additional putching oxidemod-games(Unity)/one click install/ remove old logs/make autowipe on servers. Work with external  service (Like firewall or ddos protection sistems/ or nginx proxy for some oxide plugins) 
Install diferent version of game servers .For example service minecraft  for now we can sell only option from service but if add scripting and system  for choose preset script user he can select any version of server\modification etc.. 

like this  http://prntscr.com/g5bk0j

and pre start scrript for rust http://prntscr.com/g5bty9

If you add this it will be grate  and i will migrate all my service to this panel)))

**Comment by DaneEveritt** [comment]
Closing in favor of https://github.com/pterodactyl/panel/issues/1705
