### ISSUE TITLE
Admin-only options are shown on the "Create API Key" page

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#580]
When logged in as a standard (non-admin) user, I noticed while creating an API key that I had a bunch of administrator options (such as create server, add node, etc). These options shouldn't be available to a non-admin user.

**Comment by KasperFranz** [comment]
This is fixed in https://github.com/Pterodactyl/Panel/commit/cb62e6a96da6f02cd2e692108bed3c4601661229
