### ISSUE TITLE
API Get Console 

### ISSUE THREAD

**Issue by Dieterfu** [Pterodactyl/Panel#586]
Hello,
it would be very nice If you could add add a endpoint to get the console Output a specific Minecraft Server.
With best regards
Dieter Fugger

**Comment by DaneEveritt** [comment]
This already exists in the daemon but is not documented.

You can hit [`/server/log`](https://github.com/Pterodactyl/Daemon/blob/develop/src/http/routes.js#L149) for the log file, or [`/server/file/f/<name>`](https://github.com/Pterodactyl/Daemon/blob/develop/src/http/routes.js#L199) for a specific named file and directory.

**Comment by TheSilentPro** [comment]
Sorry for opening again, but what would the full endpoint look like?
Also can this be accessed with the client api
