### ISSUE TITLE
Dropdown Variable Type

### ISSUE THREAD

**Issue by tenten8401** [Pterodactyl/Panel#588]
Title says it all basically.
Can we have a dropdown variable type?
Something that could be controlled by a script preferably too, like for example, a script to check the minecraft version updater and be able to select a minecraft version from the dropdown.

**Comment by DaneEveritt** [comment]
Do you want more than text fields for environment variables basically?

**Comment by tenten8401** [comment]
@DaneEveritt That would be correct.

**Comment by alukar4eg** [comment]
@tenten8401 @DaneEveritt 

Like this post )) https://prnt.sc/g2w13o

**Comment by DaneEveritt** [comment]
Duplicate of #570
