### ISSUE TITLE
Live installation status

### ISSUE THREAD

**Issue by tenten8401** [Pterodactyl/Panel#589]
Can we possibly have a live view at what the install's doing when creating a new server through the admin panel, instead of a simple "Installing". Or, even better than that, a variable we could set in the install script or something that would update the status and % complete. Maybe have something parse the log and look for status/% updates?

Something possibly like this in the logs:
```25/"Downloading SteamCMD..."```
![image](https://user-images.githubusercontent.com/6174343/29325809-139726d0-81b7-11e7-886e-17126240293c.png)

**Comment by DaneEveritt** [comment]
This would be incredibly hard to implement in a way that supports every game out there, not to mention it would require more API endpoints to communicate with the panel views rendering that status.

Thanks for the suggestion, but I'm going to close this as I do not foresee it happening in any reasonable amount of time.
