### ISSUE TITLE
SFTP container needs to be rebuilt on port change

### ISSUE THREAD

**Issue by tenten8401** [Pterodactyl/Panel#592]
Title says it all. The SFTP container isn't rebuilt and continues to use the old port when changing it in the core.json, until you `docker rm <id>` for the container.

**Comment by DaneEveritt** [comment]
Tagging this for the new Daemon 👍

**Comment by schrej** [comment]
I thought we wanted to ditch the container with the new Daemon anyways?

**Comment by DaneEveritt** [comment]
Well, yeah I guess that is also correct here.
