### ISSUE TITLE
[BUG] cancelling a new folder makes a folder named "false"

### ISSUE THREAD

**Issue by zwamdurkel** [Pterodactyl/Panel#598]
**Panel:** 0.6.4 | **OS:** Ubuntu 16.04 | **Daemon:** 0.4.5
**Potential bug:** 
I just noticed when you create a folder on the panel for a server and then press "Cancel" it creates a folder named "false"

**Image:** http://imgur.com/kquPNJy

**Comment by KasperFranz** [comment]
This is fixed on the develop branch so it will be in the next release :) 

as far as i can see it is fixed with #544

**Comment by schrej** [comment]
@KasperFranz Did you test that on the develop branch?

**Comment by KasperFranz** [comment]
Yep
