### ISSUE TITLE
Console doesn't work for commands

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#600]
I'm not sure if the console was designed as a place for users to enter commands (if even just basic commands) but it seems to have limited functionality. Many users seem to be having issues entering commands. This has been reported with both Minecraft and Rust servers.

**Comment by DaneEveritt** [comment]
I have no idea what you're trying to report, can you please provide more details. The console is obviously designed to function as a basic console, sending commands is a core component of that.

**Comment by xyeLz** [comment]
Was reported by a couple users over the past couple weeks so I'll get you more information today.

**Comment by schrej** [comment]
Did you gather more information yet or has this been resolved?

**Comment by DaneEveritt** [comment]
I am closing this as no additional information has been provided.
