### ISSUE TITLE
Ability to execute scripts on Docker Container creation.

### ISSUE THREAD

**Issue by Azoraqua** [Pterodactyl/Panel#602]
I was thinking of a feature about being able to execute scripts on Docker Container creation, for example:
I have a script on my machine ``/home/install-my-own-dependencies.sh`` and I want to copy/execute that in/on the docker container.

Is there any possibility to that?
Take note this is a low priority request to me.

**Comment by DaneEveritt** [comment]
Is this different from #578 and/or the current installation scripts?
