### ISSUE TITLE
Server continued to download even though it was marked to stop

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#603]
This was an interesting one I haven't seen yet...

I was working on a custom CS:GO image. As it was downloading the game files, I exceeded the server disk space. The console reported this from the daemon which said it was violating and that the server would be stopped, but it kept going:

```Update state (0x61) downloading, progress: 71.93 (11423056901 / 15881769594)
 Update state (0x61) downloading, progress: 72.66 (11539912577 / 15881769594)
 Update state (0x61) downloading, progress: 73.58 (11685983576 / 15881769594)
 Update state (0x61) downloading, progress: 74.28 (11796954433 / 15881769594)
 Update state (0x61) downloading, progress: 75.01 (11913574738 / 15881769594)
(Daemon) Server is violating disk space limits. Stopping process.
(Daemon) Server marked as STOPPING
quit
 Update state (0x61) downloading, progress: 75.76 (12032493469 / 15881769594)
 Update state (0x61) downloading, progress: 76.50 (12149533200 / 15881769594)
 Update state (0x61) downloading, progress: 77.32 (12279776194 / 15881769594)
```

Eventually it completed and then the server turned off. I did confirm that it violated the disk space limitation of 10240 MB, as it was about 15000.

**Comment by DaneEveritt** [comment]
That is because the daemon sends a normal stop command, not a kill so that a user's server data doesn't get destroyed by a kill. I can look into changing that in the future, but this is currently working as intended.
