### ISSUE TITLE
Internal server error 500 on ubuntu 14.04 server

### ISSUE THREAD

**Issue by GhostHacks** [Pterodactyl/Panel#611]
I started the setup and finally go through with the panel set up went to test it and all i get is a internal server error. it looks like its a helper error 
`Php Parse error: syntax error, unexpected "." expecting "&" or variable (T_VARIABLE) in /var/html/panel/vendor/laravel/framework/src/Illuminate/Foundations/helpers.php on line 444 '

any suggestions?

**Comment by DaneEveritt** [comment]
That component is not a part of our software, but I'm guessing your PHP version is very out-of-date.

**Comment by GhostHacks** [comment]
no im on php7 im gana do a wipe and start over
