### ISSUE TITLE
So clean install and still not working

### ISSUE THREAD

**Issue by GhostHacks** [Pterodactyl/Panel#612]
ive wiped my server with a clean install of just the panel and its dependencies, the panel wont come up it only shows its files until you navigate to the public directory and then it shows 
 is currently unable to handle this request.
HTTP ERROR 500
any suggestions?

**Comment by DaneEveritt** [comment]
This is not a bug, please use either our Discord (preferred) or forums for further assistance.

**Comment by tenten8401** [comment]
Contact me in #support if you need help with this, willing to bet your webserver wasn't configured correctly.
https://discord.gg/bAcTUrX

**Comment by tenten8401** [comment]
Issue resolved. PHP CLI 7.1 was installed, while PHP 5 was on the webserver. Simply deleted everything PHP5 related and re-ran the dependency command for apache on the docs.
