### ISSUE TITLE
Debian 9 (Stretch)

### ISSUE THREAD

**Issue by kaal-1** [Pterodactyl/Panel#618]
I'm trying to setup the panel and everything worked just fine until the moment I had to install Docker.
I'm using Debian 9 (Stretch) on a OVH server, and when I type docker info, I don't get all the warnings shown in this page:
https://daemon.pterodactyl.io/docs/installing-docker-on-debian-8
I only get:
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Should I ignore it?

**Comment by XxCoolGamesxX** [comment]
You need to update the kernel of OVH.
Here Info to update it for Debian 9:

First:
`apt-get install linux-image-4.9.0-3-amd64`


Then you must edit the grup with:
`nano /etc/default/grub`

And edit the value:
`GRUB_DEFAULT=0`

To:
`GRUB_DEFAULT=1`


Finally:
`update-grub && reboot`

**Comment by kaal-1** [comment]
Thank you!
But now when I type docker info I get another warning:
WARNING: No swap limit support

**Comment by XxCoolGamesxX** [comment]
Edit the grup:

Add the "swapaccount=1 cgroup_enable=memory" on the GRUB_CMDLINE_LINUX_DEFAULT.

GRUB_CMDLINE_LINUX_DEFAULT="swapaccount=1 cgroup_enable=memory"

**Comment by kaal-1** [comment]
Ok, there were some commands there already
my GRUB_CMDLINE_LINUX_DEFAULT is as follows:
GRUB_CMDLINE_LINUX_DEFAULT="noquiet nosplash net.ifnames=0 biosdevname=0 swapaccount=1 cgroup_enable=memory"
after running update-grub and docker info, still the same: WARNING: No swap limit support

**Comment by XxCoolGamesxX** [comment]
Do a:
reboot

**Comment by DaneEveritt** [comment]
This is not a bug with this software.
