### ISSUE TITLE
(Feature Request) User Service Reinstall (Multiple installation scripts)

### ISSUE THREAD

**Issue by yerktoyn** [Pterodactyl/Panel#626]
For example Minecraft has several server cores, Bukkit, Vanilla, Spigot, PaperSpigot and others.
I would very much like that the user could easily select the server core and version necessary for him.

To reinstall, the user navigates to the main page of the server and presses "Reinstall", then selects from the drop-down list the possible options that were added by the panel administrator. After that, all files are deleted and the necessary installation script is launched.

**Comment by yerktoyn** [comment]
Very similar to:
https://github.com/Pterodactyl/Panel/issues/597

**Comment by schrej** [comment]
rather a duplicate of #597
