### ISSUE TITLE
Daemon Broke

### ISSUE THREAD

**Issue by SethGecko28** [Pterodactyl/Panel#636]
Hello i have a issue with Daemon causing a problem which stops me from installing new Servers i have done nothing wrong. [Image](https://www.elhspowered.com/sfritsche/9ssaa43j7.png)

**Comment by ScarletWolf275** [comment]
You probably have set the panel URL wrong in pterodactyl:env than the actual panel, make sure it EXACTLY matches

**Comment by SethGecko28** [comment]
Where can i find it to edit pterodactyl:env

**Comment by ScarletWolf275** [comment]
The command, you used to setup the panel environment... pterodactyl:env.
`php artisan pterodactyl:env`
It should have been that...

**Comment by ScarletWolf275** [comment]
Also, check your node's config on the panel, it should say the IP or the URL of the machine the daemon is hosted on. And then redeploy the config

**Comment by ScarletWolf275** [comment]
In the FQDN field I mean

**Comment by SethGecko28** [comment]
Sorry for me being so stupid but i have no idea how to access pterodactyl:env do i need to go on PuTTY?

**Comment by SethGecko28** [comment]
Also on the Panel the URL is set right

**Comment by ScarletWolf275** [comment]
You sure it is set right? The FQDN must be the same IP/URL as the machine the DAEMON is hosted on, the panel and the daemon must be BOTH HTTPS or BOTH HTTP. You can't mix and match them

**Comment by DaneEveritt** [comment]
This is a configuration issue, not a bug with his software.
