### ISSUE TITLE
Issue with C style brackets in file manager

### ISSUE THREAD

**Issue by decryptedchaos** [Pterodactyl/Panel#646]
There appears to be a bug in the file manager,  or to be precise,  an oversight in its security checks. 

I'm seeing an issue editing .cfg files  if they contain  C style config brackets  e.x

```
{
OPTION=value;
};
```

It seems that the file manager check the file contents and allows or disallows editing based on its contents. 

The result of this is is if you try to edit/create a file with this type of content,  the panel refuses with a red error  banner which says something along the lines of 

you cannot edit file type xapp/c++  in the panel  

Not sure the exact error,  it disappears before i can get my screenshot app open.  

This may be a known issue and may already have a fix planned for 0.70,  but i looked through the issues here and didn't see anything similar.  

 
---------------------

**Comment by DaneEveritt** [comment]
Those checks are based on the content of the files, so theres not really much I can do about that other than having C++ files be editable in the panel.

**Comment by decryptedchaos** [comment]
Hmm,  would it be possible to allow the edit only if the extension is .txt|.cfg|.conf  etc?   It's a dirty workaround but maybe?  

Or is this more an laravel/plugin/library issue?

**Comment by DaneEveritt** [comment]
It is an issue with the fact that the C library we use to read headers thinks that file is a C file.

**Comment by decryptedchaos** [comment]
i see,  well it's not a absolute show stopper issue.  

Though it does pose an interesting predicament for production use.  

A technically minded person like us (any anyone else who installs pterodactyl / docker and/or works with linux systems)  will understand and know they can just go to sftp and edit the file manually,  although inconvenient, it's doable.

But for an average user,  this is probably not the case,  so this produces problems most definitely in the GSP space. 

But it also produces problems for end users who are perhaps less technically inclined.  

I'm not gonna sit here and tell you what to do, programing is a pain,  it's the one thing i never mastered (much to my regret) if i was a better coder i would probably contribute but i'm not that great, so i know the implications.  

I did just want to put this out there,  as a potential problem for some users where simplicity and just plain working are key.

also,  well i like the community here,  i've spoken to you guys on discord and i like the atmosphere,  FOSS communities these days are generally rather hostile when it comes to issues and suggestions or even bug reports. I'm happy to not see much of that here.

**Comment by DaneEveritt** [comment]
Luckily in the next version there is an editable list of file types, so this can be resolved by the administrator pretty easily.

Would that be an okay solution for you?

**Comment by decryptedchaos** [comment]
Yes,  in fact i was going to suggest it,  but when you said it was a hard coded check i redacted the suggestion from my original comment.  

P.S  can't wait to see 0.7.0 sounds like it'll solve a lot of headaches.

**Comment by DaneEveritt** [comment]
Cool, I'm going to close this then since that change is already merged.
