### ISSUE TITLE
Unable to send emails

### ISSUE THREAD

**Issue by lay295** [Pterodactyl/Panel#648]
I am unable to send emails with this panel, I have tried via SMTP, the built in PHP mail and Mailgun. Checking the service status shows that the mail part has failed, are there any more additional logs so I can see why exactly they failed? When I create an account the creation works, just not the welcome email.

This is on a freshly installed panel on Ubuntu 16.04 with PHP 7.1 and 0.6.4 of the panel.
![3jdgm8a](https://user-images.githubusercontent.com/1060681/30879866-b6382b40-a2ce-11e7-84d4-c3c5a9d566ac.png)

**Comment by LewisBelton** [comment]
Same issues. My Log is here:

- https://hastebin.com/sufakeqowe.tex

**Comment by metallicgloss** [comment]
I'm aware responding to these is normally part of the project team's jobs, but doesn't hurt to ask general things.

Do either of you have SMTP blocks on your machine? I know that some datacentres block the sending of emails using SMTP on port 465 or 25 to help prevent spam. That may be why it is timing out attempting to send it - not 100% sure.

The second general question to ask - does it log to the database as well (in the jobs_failed table), if so, do the errors there match what is in the panel logs or do they point to something different such as SwiftMailer or a permission issue.

**Comment by LewisBelton** [comment]
To be fair, mine was once working. I'm not sure what changed, in fact i'm 95% sure nothing has changed. My dedi is long overdue a re-boot so I will do that shortly and see if it changes the odds.

**Comment by metallicgloss** [comment]
Very strange. Double check to see if there are any logs in the database for failed jobs which differs to that in the file logs.

**Comment by lay295** [comment]
Ahhhh thanks for the laravel log location, yeah seems to be a configuration issue on my end.

I'll close this as my original issue was resolved, you can open another issue if you'd like to continue yours as it seems different.
