### ISSUE TITLE
'0' is not available as a service variable

### ISSUE THREAD

**Issue by Mechtecs** [Pterodactyl/Panel#649]
As described above, if you create a service variable, '0' is not available as a default variable.

![image](https://user-images.githubusercontent.com/5622125/31037015-19fdb77e-a56f-11e7-8deb-71af3ae03b84.png)

You can set it to '0' though, if you edit the variable. Idiot me just pressed enter to update, which just deletes the service variable.

**Comment by DaneEveritt** [comment]
I'm confused as to what the exact issue here is?

**Comment by decryptedchaos** [comment]
I have used 0 as the default value of a variable before (automatic update)  and it works as expected.  

Where are you trying to use this variable?

**Comment by DaneEveritt** [comment]
I'm closing this as there has been no response. Feel free to respond if you can provide more info.
