### ISSUE TITLE
If server is stopping for X amount of time, kill it.

### ISSUE THREAD

**Issue by Time6628** [pterodactyl/panel#650]
If a Minecraft server stalls and the panel tries to restart it, it gets stuck "stopping".
Multicraft has a nice feature where if a server is stopping for too long, it will kill it and start it up again, would love to see this in Pterodactyl.

**Comment by AnthonyGriffith** [comment]
Having switched off of Multicraft to Pterodactyl this is definitely a feature that would I love having available.

**Comment by schrej** [comment]
Could be added as a config option on services as different game servers need different amounts of time to shut down.

**Comment by DaneEveritt** [comment]
Implemented in the new wings daemon. :)
