### ISSUE TITLE
Add built-in handler for Bugsnag.

### ISSUE THREAD

**Issue by DaneEveritt** [pterodactyl/panel#651]
It is already quite easy to setup Bugsnag, but it might be nice to make this configurable from the CLI so that people running on production machines can easy link to their Bugsnag account and monitor errors from there.

I'm imagining some `.env` setting, but maybe we can do this via the Admin CP and access the settings in the exception handler?

**Comment by lancepioch** [comment]
If the BUGSNAG credentials are set in the environment, then bind the bugsnag logger in the AppServiceProvider (for unhandled exceptions): https://docs.bugsnag.com/platforms/php/laravel/#reporting-unhandled-exceptions
