### ISSUE TITLE
Issue when create new server

### ISSUE THREAD

**Issue by TheGamin93** [Pterodactyl/Panel#652]
Hi! i installed for first time this panel with version Pterodactyl Panel version 0.6.4, and when i go to create a new server (ex: insurgency, or any ) i get this error:

> {"name":"wings","hostname":"myhostname.com","pid":2199,"level":40,"msg":"An error occurred while attempting to check the latest daemon release version.","time":"2017-09-30T20:33:21.975Z","v":0}
> {"name":"wings","hostname":"myhostname.com","pid":2199,"level":30,"msg":"Pterodactyl Daemon is now listening for insecure connections on 0.0.0.0:8080","time":"2017-09-30T20:33:21.979Z","v":0}
> {"name":"wings","hostname":"myhostname.com","pid":2199,"server":"e652006a-a721-4b18-9ae8-a7f0010601ec","level":40,"msg":"Container was not found. Attempting to recreate it.","time":"2017-09-30T20:36:32.159Z","v":0}
> {"name":"wings","hostname":"myhostname.com","pid":2199,"level":30,"msg":"Checking if we need to update image quay.io/pterodactyl/core:source, if so it will happen now.","time":"2017-09-30T20:36:32.166Z","v":0}
> {"name":"wings","hostname":"myhostname.com","pid":2199,"level":30,"msg":"Pulling image quay.io/pterodactyl/core:source ... this could take a few minutes.","time":"2017-09-30T20:36:34.083Z","v":0}
> {"name":"wings","hostname":"myhostname.com","pid":2199,"server":"e652006a-a721-4b18-9ae8-a7f0010601ec","level":30,"msg":"Completed rebuild process for server container.","time":"2017-09-30T20:36:35.270Z","v":0}
> {"name":"wings","hostname":"myhostname.com","pid":2199,"level":60,"err":{"message":"Cannot read property 'R_OK' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'R_OK' of undefined\n    at /srv/daemon/src/controllers/server.js:91:60\n    at /srv/daemon/node_modules/async/dist/async.js:3853:24\n    at replenish (/srv/daemon/node_modules/async/dist/async.js:946:17)\n    at /srv/daemon/node_modules/async/dist/async.js:950:9\n    at eachOfLimit (/srv/daemon/node_modules/async/dist/async.js:975:24)\n    at /srv/daemon/node_modules/async/dist/async.js:980:16\n    at _parallel (/srv/daemon/node_modules/async/dist/async.js:3852:5)\n    at Object.series (/srv/daemon/node_modules/async/dist/async.js:4708:5)\n    at /srv/daemon/src/controllers/server.js:89:19\n    at /srv/daemon/src/controllers/server.js:636:24"},"msg":"A fatal error occured during an operation.","time":"2017-09-30T20:36:35.275Z","v":0}

**uname:**
`Linux myhostname.com 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`

**php -v**
`PHP 7.1.10-1+ubuntu17.04.1+deb.sury.org+1 (cli) (built: Sep 29 2017 17:04:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.10-1+ubuntu17.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
`

**Docker info:**

`Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-35-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.845GiB
Name: server.top10games.es
ID: BH7W:V6CQ:A6DZ:MFS3:3HRX:ZXG2:QBHH:CROS:HFTJ:BDFF:V2XZ:NLUP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`

Thanks!!

**Comment by DaneEveritt** [comment]
Update Nodejs to the required version.
