### ISSUE TITLE
Grant execute privileges to database accounts

### ISSUE THREAD

**Issue by jdlovins** [Pterodactyl/Panel#654]
New database accounts arent granted execute privileges which is required for stored procedures. Would be really helpful and an easy fix.

**Comment by DaneEveritt** [comment]
Seems like a good task for someone to handle for [Hacktoberfest](https://hacktoberfest.digitalocean.com).

**Comment by KasperFranz** [comment]
@DaneEveritt  to get people to notice the issues here can you label it with Hacktoberfest then it get noticed on the [global Hacktoberfest search](https://github.com/search?q=label:hacktoberfest+state:open+type:issue)

**Comment by schrej** [comment]
Seems like Trixter wants a T-Shirt :D

**Comment by jdlovins** [comment]
Also need to add ``Grant Trigger`` as well!
