### ISSUE TITLE
Potential to use ssh keys for sftp

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#656]
Per a request in the #feedback channel using ssh keys could be a good enhancement for the new daemon.

Back burner for now as daemon equality takes precedence.

**Comment by DaneEveritt** [comment]
Should be possible to store these more easily too since we can utilize the Panel API with the new SFTP setup.

**Comment by LeCodeCo** [comment]
I think there are two ways this could easily be done. 
- Either supporting just one SSH key and storing it in the users table as a column 
- Ideally supporting multiple SSH keys in its own table stored that links to a user

The keys could be shown on its own page under the account page, and display the key nickname, public key fingerprint, date added, last authenticated with, and a delete button.

I don't think it would be *too* hard to add, just updating /api/remote/sftp/auth require either a password or the required public key.

**Comment by galexrt** [comment]
What about allowing / reading `.ssh/authorized_keys` file in the servers directory for a start?

So basically implementing `PublicKeyCallback` for the `ssh.ServerConfig` in some way, see https://godoc.org/golang.org/x/crypto/ssh#ServerConfig and https://github.com/golang/crypto/blob/master/ssh/client_auth.go#L170-L327

**Comment by LockedThread** [comment]
If we could get this on a medium priority list of some sort that would be very appreciated.

**Comment by matthewpi** [comment]
> If we could get this on a medium priority list of some sort that would be very appreciated.

Priorities are assigned based off of necessity and importance.  This feature is very niche as most people using SFTP for the panel have no idea what SSH keys even are.  While I would love for this feature to be added, it is not a higher priority than anything else.

**Comment by matthewpi** [comment]
https://github.com/pterodactyl/panel/commit/790f109e66a72e5b5f82936479ca8850ea3e160e
https://github.com/pterodactyl/wings/commit/06c92c276bf953a6068eff6e0ab7db786192be5a
