### ISSUE TITLE
Curl error upon creating server

### ISSUE THREAD

**Issue by ET-Bent** [Pterodactyl/Panel#66]
When creating a server I get this error:

`An error occured while attempting to create the server: cURL error 7: Failed to connect to node.example.com port 5800: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

The reason for this is that curl is allowed to use ipv6 which ends in no connection to the daemon which is listening on ipv4. Please make sure to force ipv4 in **all** curl requests that the panel sends.

Testing from cmd on the same server :

Using `curl node.example.com:5800` instead:
```
* Rebuilt URL to: node.example.com:5800/
*   Trying someIPv6...
* connect to someIPv6 port 5800 failed: Connection refused
* Failed to connect to node.example.com port 5600: Connection refused
* Closing connection 0
curl: (7) Failed to connect to node.example.com port 5800: Connection refused
```

Using `curl -4 node.example.com:5800` instead:
```
* Rebuilt URL to: node.example.com:5800/
*   Trying someIPv4...
* Connected to node.example.com (someIPv4) port 5800 (#0)
> GET / HTTP/1.1
> Host: node.example.com:5800
> User-Agent: curl/7.43.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host node.example.com left intact
curl: (52) Empty reply from server
```

**Comment by ET-Bent** [comment]
For me the issue was that the `/etc/hosts` file contained an entry for the hostname which resolved to an ipv6. But as long as the daemon does not accept ipv6 I think forcing ipv4 shall be the way to go.

**Comment by DaneEveritt** [comment]
This seems more like a cURL/PHP/Host configuration issue more so than something the panel should be dealing with.
