### ISSUE TITLE
Error in API for create new node

### ISSUE THREAD

**Issue by Doc94** [Pterodactyl/Panel#663]
Hello, i have a error when try to create a new node using the api.
i set the request.
`POST https://PANELURL/api/admin/nodes
Authorization: Bearer SECRET
Content-Type: application/x-www-form-urlencoded
name=TEST&location_id=1&public=1&fqdn=test.go.cl&behind_proxy=0&scheme=http&memory=10&memory_overallocate=100&disk=100&disk_overallocate=110&daemonBase=/home/servers&daemonListen=9090&daemonSFTP=5550`

but return
`{"error":{"behind_proxy":["The behind proxy field is required."]}}`

and this parameter has been set in the body and the Authorization.

PD: The docs for api not mention any for the parameter. https://pterodactyl.readme.io/v0.6.0/reference#create-node

**Comment by DaneEveritt** [comment]
The API uses JSON, not x-www-form-urlencoded.

**Comment by Doc94** [comment]
Test with json and same error.
![imagen](https://user-images.githubusercontent.com/3602279/31300981-21008714-aacd-11e7-9521-6646638526fc.png)

**Comment by karatemaccie** [comment]
Can confirm this error, my output is exactly the same when testing the API to create a node. The worst part about this is that this field isn't even mentioned, let alone documented, in the apidocs.

**Comment by DaneEveritt** [comment]
This will be fixed as part of 0.7's new API.
