### ISSUE TITLE
New User Password Doesn't Work First Time

### ISSUE THREAD

**Issue by TechGuyAnthony** [Pterodactyl/Panel#674]
OS Info:
OS: Ubuntu 16.04.3 LTS
Output from uname -a: 
`Linux c29 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
Output from php -v:
`PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep 29 2017 17:04:25) ( NTS )`
Pterodactyl Version: 0.6.4
Pterodactyl Daemon Version: 0.4.5

Getting a issue where new user accounts using the password first input into the create user menu does not work, even after verifying that I typed in the right password. Meaning for every new user account I need to input a password when creating the account and then also change it after the account is made for it to work.

Not entirely sure what causes this to happen but its a bit annoying.

**Comment by DaneEveritt** [comment]
I'm pretty sure this is fixed mostly because that system was re-written in the latest stuff. I'll confirm before release though.

**Comment by DaneEveritt** [comment]
This is resolved and working fine on the latest development branch.
