### ISSUE TITLE
[0.7] Fix test suite to not mock UUID or Carbon

### ISSUE THREAD

**Issue by DaneEveritt** [pterodactyl/panel#677]
The UUID and Carbon classes should not be mocked as they have test helpers available for use. Carbon::setTestNow() can be used in tests, and functions currently dependency injecting Carbon should be changed to just use the static call.

In addition, any test currently mocking the UUID class should be changed to use the `MocksUuids` trait in tests, and then just call `$this->getKnownUuid()` to get the mocked UUID.

**Comment by arcdigital** [comment]
This was implemented already.
