### ISSUE TITLE
Composer Setup error

### ISSUE THREAD

**Issue by Aphex124** [Pterodactyl/Panel#68]
Recently I've been trying to setup Pterodactyl and every time I've been getting this same error... I've tried installing it in its own directory, running as a non-root user, running as a root user, restarting the server, and the list goes on.. 

I don't know if this was the error that was mentioned on the Installing wiki page, but I still dont really know what to do if it don't think the files exist. Hopefully this is a very simple fix. Thank you, and I look forward to being able to use the panel.

Console log: http://pastebin.com/RkDNYQhX

**Comment by parkervcp** [comment]
what version of php do you have? I just want to be sure php -v will give you probably what I need

**Comment by Aphex124** [comment]
```
PHP 5.5.9-1ubuntu4.16 (cli) (built: Apr 20 2016 14:31:27)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

```

**Comment by Aphex124** [comment]
@DaneEveritt @DDynamic Anyone know of how to fix this? I would really like to use this panel, but the panel doesn't like me back

**Comment by DDynamic** [comment]
Try running this command:
`chown -R www-data:www-data /var/www/html`

**Comment by Aphex124** [comment]
I don't know if this is the same error as before, but this is the output of trying to install on a clean VM with the command you mentioned. I did notice something odd although, whenever I tried to do the command to download the zip file as a normal user or even with Sudo, it automatically spat out 'Permission Denied' before I could even enter the sudo password.

> `Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

                                                                                                                                                                                          
  [RuntimeException]                                                                                                                                                                      
  Error Output: PHP Warning:  require(/var/www/html/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/bootstrap/autoload.php on line 17
  PHP Fatal error:  require(): Failed opening required '/var/www/html/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/bootstrap/autoload.php on line 17
                                                                                                                                                                                          

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

Script composer install --ansi --no-dev handling the setup event returned with an error


  [RuntimeException]
  Error Output: Running composer as root/super user is highly discouraged as packa
  ges, plugins and scripts cannot always be trusted
  > php artisan clear-compiled
  Script php artisan clear-compiled handling the pre-update-cmd event returned wit
  h an error



    [RuntimeException]


    Error Output: PHP Warning:  require(/var/www/html/bootstrap/../vendor/autoload
  .php): failed to open stream: No such file or directory in /var/www/html/bootstrap/autol
  oad.php on line 17
    PHP Fatal error:  require(): Failed opening required '/var/www/html/bootstrap/
  ../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/ht
  ml/bootstrap/autoload.php on line 17



  install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-cust
  om-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-
  o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [
  39m<packages>]...


setup [--dev] [--no-dev] [--] [<args>]...

`

**Comment by Aphex124** [comment]
@DDynamic I don't know if this is the same error as before, but this is the output of trying to install on a clean VM with the command you mentioned. I did notice something odd although, whenever I tried to do the command to download the zip file as a normal user or even with Sudo, it automatically spat out 'Permission Denied' before I could even enter the sudo password.

`
Script php artisan clear-compiled handling the pre-update-cmd event returned with an error
[RuntimeException]

Error Output: PHP Warning: require(/var/www/html/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/bootstrap/autoload.php on line 17
PHP Fatal error: require(): Failed opening required '/var/www/html/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/bootstrap/autoload.php on line 17

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] []...

Script composer install --ansi --no-dev handling the setup event returned with an error

[RuntimeException]
Error Output: Running composer as root/super user is highly discouraged as packa
ges, plugins and scripts cannot always be trusted

php artisan clear-compiled
Script php artisan clear-compiled handling the pre-update-cmd event returned wit
h an error
[RuntimeException]


Error Output: PHP Warning:  require(/var/www/html/bootstrap/../vendor/autoload
.php): failed to open stream: No such file or directory in /var/www/html/bootstrap/autol
oad.php on line 17
PHP Fatal error: require(): Failed opening required '/var/www/html/bootstrap/
../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/ht
ml/bootstrap/autoload.php on line 17

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-cust
om-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-
o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [
39m]...

setup [--dev] [--no-dev] [--] []...

`

**Comment by Aphex124** [comment]
I hate bumping, but I mean... Someoone has to know the reason for this right? @parkervcp @DDynamic @DaneEveritt

**Comment by DDynamic** [comment]
Are you using Nginx or Apache? By the way, I hate to say it but this project is pretty much dead, or at least on hold.

**Comment by DaneEveritt** [comment]
This is/was a bug in Laravel. Workaround is to simply manually run the commands listed under `composer setup` in the `composer.json` file.

**Comment by cynicalmax** [comment]
attach `--ignore-platform-req=ext-bcmath` to your command was my fix
