### ISSUE TITLE
Ability to disable / lock nodes in a location

### ISSUE THREAD

**Issue by LegendaryHosts** [Pterodactyl/Panel#683]
Can we have the ability to lock a node from having additional servers allocated to it without having to delete the node?

**Comment by DaneEveritt** [comment]
Completely disabled? Or just not able to be auto-deployed to?

**Comment by LegendaryHosts** [comment]
The inability to auto-deploy to it would probably be better than to outright disable it. That way current servers can still run fine.

**Comment by DaneEveritt** [comment]
You can already block auto-deployment by setting the node to `Private` and not `Public`.
