### ISSUE TITLE
Admin API

### ISSUE THREAD

**Issue by LegendaryHosts** [Pterodactyl/Panel#684]
Can we get an admin API to automatically create / pull new services and packs from places like packer.io, docker and gitlab?

**Comment by DaneEveritt** [comment]
You're going to need to be way more specific about what you want.

**Comment by LegendaryHosts** [comment]
Say I have a repo (or multiple) in a private git server which can have one or more mc modpacks inside. I would like to be able to setup a CI job that when I update the repo, I can call api’s within the admin panel to upload/create the pack (with zipped files) automatically.

Currently you need to manually upload and add the packs which slows down the process of updating/adding multiple packs greatly.

**Comment by DaneEveritt** [comment]
Packs are already a very poorly implemented system, and not something I'm putting any effort into for the next release. If/when they are improved there will be appropriate APIs added for management.
