### ISSUE TITLE
Server Console should report NodeIP:Port rather than 0.0.0.0:Port

### ISSUE THREAD

**Issue by LegendaryHosts** [Pterodactyl/Panel#685]
I feel as if it would be better for the console to report that a server is running on the actual nodes IP rather than 0.0.0.0 to reduce confusion for some people.

**Comment by TechGuyAnthony** [comment]
This is not at fault of the panel as far as i'm aware. Docker is the one that changes the ip to 0.0.0.0 the panel is just reporting what it has available to it.

**Comment by BrainStone** [comment]
I mean the server hast to listen to `0.0.0.0` inside the container. Else it won't work.  
Only thing would be replacing the 0.0.0.0 in the panel console.

**Comment by LegendaryHosts** [comment]
I'm well aware that the server listens on 0.0.0.0, although if the server was to alias and replace the 0.0.0.0, it would be much more presentable.

**Comment by LegendaryHosts** [comment]
@DaneEveritt A simple fix for this would to be to add:

`    "network": {
        "name": "host"
    }`

into the core.json of the daemon under the docker section.

**Comment by schrej** [comment]
No, setting the network mode to host is not an option. The network virtualization is one of the nice features of docker and why we are using it. How is it that relevant what IP is shown in the server log?

**Comment by kaganus** [comment]
tell that to people running multiple srcds servers with multiple external IPs on single dedicated machine. you have to use host network and use {{SERVER_IP}} in the startup command for valve to register your servers using the correct ip.

**Comment by DaneEveritt** [comment]
There’s another flag you can use that is pinned in the discord support channel. It’ll be added to 0.7 by default, and I can post it here when I’m not on mobile.

**Comment by kaganus** [comment]
that doesn't work, are you running multiple srcds servers on a single dedi with multiple IPs assigned? if its working can i inspect the machine and the config?

**Comment by DaneEveritt** [comment]
I'm not adding a bunch of JS to catch this line across different game types just so that it displays a specific IP and not 0.0.0.0 in the console.
