### ISSUE TITLE
Stick Service and Configured Options ID in table

### ISSUE THREAD

**Issue by LegendaryHosts** [Pterodactyl/Panel#687]
Can we add a column in the table to display the ID of the Service / Container similar to Packs, I see it's in the domain, but Packs have a column and it'll be more fluid.

**Comment by schrej** [comment]
In which table would you like to have what exactly added? Please try to be more specific in the future.

**Comment by LegendaryHosts** [comment]
https://gyazo.com/c2ab5f26a16a571df025b6908157e6d0?token=ca3c6776698b57f31855b5e22d1cffcf Just inbetween the name and the description would be fine, my apologies for being vague, I'm a little tired :>
