### ISSUE TITLE
Ability to copy a service

### ISSUE THREAD

**Issue by MadnessExpress** [Pterodactyl/Panel#689]
I think pterodactyl should have the ability to copy an existing service, so that if you need to run two different versions of a service, you could do so without having to do a whole new setup, and then you could simply adjust the name and variables.

**Comment by DaneEveritt** [comment]
This is possible now using egg export and import. :)

**Comment by schrej** [comment]
Shouldn't it also be possible to just clone it directly without first exporting and then importing it again?
