### ISSUE TITLE
Modal dialogs not working in panel (success is not a function)

### ISSUE THREAD

**Issue by adamxp12** [Pterodactyl/Panel#690]
Just installed the latest version of Pterodactyl panel and all is going good but it seems that none of the modal dialog's are working. they put a jquery error about success not being a function

https://img.bluntlab.space/image/F2lz

.success has been replaced with .done in jquery so should be a simple fix but thought I would mention it as no one else has reported it.

**Comment by DaneEveritt** [comment]
That shouldn't be happening on the latest stable builds as we reference a specific version of jQuery that it is working on. You've also provided very little information to work off. Which specific modal is this occurring on? What browser are you using?

**Comment by DaneEveritt** [comment]
I'm closing this due to lack of information. We can reopen this when more information is provided.
