### ISSUE TITLE
CS:GO IP ERROR

### ISSUE THREAD

**Issue by selim995** [Pterodactyl/Panel#691]
Hi,

 

The server has 2 ip.

1 : 185.81.154.162
2 : 185.132.127.25

[http://i.epvpimg.com/xVh7eab.png](url)

cs works at first ip address. But the second ip address does not enter the game

[http://i.epvpimg.com/D83caab.png](url)

[http://i.epvpimg.com/5WVGdab.png](url) 

start command : ./srcds_run -game {{SRCDS_GAME}} -usercon +ip 185.132.127.25 -port  ......    causing the fault
start command : ./srcds_run -game {{SRCDS_GAME}} -usercon -port  ...... no ip command. The server does not receive the address 185.132.127.25. The server receives the address 185.81.154.162.

 

This error is only in cs game.How can I solve it.

**Comment by DaneEveritt** [comment]
User is being helped at https://forums.pterodactyl.io/topic/109-csgo-server-error/#comment-288
