### ISSUE TITLE
Teamspeak downloading doesn't work & Ability to reinstall servers if installation failed.

### ISSUE THREAD

**Issue by HexDevOfficial** [Pterodactyl/Panel#697]
So I tried installing Teamspeak on the server, and it failed. I have no clue how to fix this :P. Here is the error code: A fatal error was encountered while attempting to create a server. { Error: (HTTP code 500) server error - json: cannot unmarshal number 65099999.99999999 into Go struct field HostConfig.Memory of type int64

Also I was wondering if you can add the ability to reinstall servers if it failed.

Cheers.

**Comment by lancepioch** [comment]
Please post the full error.

**Comment by DaneEveritt** [comment]
What value did you enter for the server memory?

**Comment by HexDevOfficial** [comment]
60 mb. It shouldn't need much?

**Comment by HexDevOfficial** [comment]
Fixed it. I changed a bit of the script to download the latest version, and removed the variable.
