### ISSUE TITLE
http and https comparability issue

### ISSUE THREAD

**Issue by tomgie** [Pterodactyl/Panel#704]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.6.4
* Server's OS: Ubuntu 16.04 LTS
* Your Computer's OS & Browser: Windows 10, Chrome

When I try to access the file manager for any of the servers I setup it throws an error saying "An error occured while attempting to process this request. Please try again."

I check the developer tools and see in the console that its trying to request from a http url instead of https when in fact, my panel was setup for https. I go and check the source and all the href tags only contain http and not https. Not sure if I set it up wrong or its an issue.
https://gyazo.com/e2e0d353b222018370f494d46b551278

**Comment by parkervcp** [comment]
check you .env file in the panel and make sure it's https://

**Comment by tomgie** [comment]
Yes I checked it and its https://

**Comment by parkervcp** [comment]
clear the cache with 
```
php artisan view:clear
php artisan cache:clear
```

**Comment by tomgie** [comment]
its still http

**Comment by DaneEveritt** [comment]
You're running behind a reverse proxy. Set `TRUSTED_PROXIES=*` in your `.env` file and reload it using `php artisan config:cache`.
