### ISSUE TITLE
Documentation update request for CentOS 7 + selinux enforcing

### ISSUE THREAD

**Issue by dorsey** [Pterodactyl/Panel#705]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.6.4
* Server's OS: CentOS 7.4
* Your Computer's OS & Browser: CentOS 7.4

## Add Details Below:
Not a technical request, just a documentation update request.

The server I installed the panel on has SELinux running.  I had to do the following to get SELinux to play nice with the panel:
```
cd /var/www/html/pterodactyl/storage/
chcon -R -t httpd_sys_rw_content_t app/ debugbar/ framework/
chcon -R -t httpd_log_t logs/

setsebool httpd_can_network_connect=1
```

I figured I'd provide this info in case anyone else needed it - maybe it could be added to the docs?

**Comment by lancepioch** [comment]
Please use the **Suggest Edits** at the top right of the docs, thank you.

**Comment by DaneEveritt** [comment]
@parkervcp might add this to the CentOS specific docs in the guides.

**Comment by dorsey** [comment]
I actually ended up disabling SELinux entirely.  Even in permissive mode, I couldn't start any servers - Docker kept giving me permission denied errors.

So, it might be better to make a note about disabling SELinux entirely, rather than the original steps I proposed.
