### ISSUE TITLE
Performance Problems with JS Console

### ISSUE THREAD

**Issue by kaganus** [Pterodactyl/Panel#706]
* Panel or Daemon: Panel
* Version of Panel: 0.6.4
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 PC with Google Chrome, Mozilla Firefox, Opera and Windows 7 laptop with Google Chrome
* uname -a: Linux 4.4.0-97-generic # 120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* php -v: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.0.3, Copyright (c) 2002-2017, by ionCube Ltd.
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

## Details:

There are a few problems with the new custom made js console since 0.6.4. Talked about this before on discord with Dane, and he confirmed there was a lack of optimization in console code.

~~Problem # 1: Whole page is frozen/unresponsive until the console fully loads. 
Every time a user clicks on one of his servers, as the server console page is the default page to be shown, browser tab becomes unresponsive for a few seconds (depending on the size of the log) until console is loaded up with all the logs and is rendered. Cannot click on other links on the menu or buttons while browser is in this unresponsive state. (Happens on Chrome, Firefox, Opera)~~

~~Problem # 2: Text selection does not work correctly
When you want to use your mouse cursor to select some text from the console log, the selection disappears as soon as you release the mouse button. It is the same with double clicking on a word in console, the selection is canceled immediately. To copy text, you have to click CTRL + C without releasing the mouse left button as it cancels the selection.~~

~~On Firefox, if you select text on multiple lines, the selection is not cancelled and it works correctly, although if you select text from a single line, selection is cancelled immediately. On Chrome and Opera, it doesn't matter if you select text from a single line or multiple lines, it is cancelled immediately after mouse button release.~~

Problem # 3: Command history sometimes do not work
On the console command input area, if you click UP or DOWN arrow buttons on your keyboard, it cycles through previously sent commands normally. This works as intended sometimes; but most of the time, it will only show the last command entered, and not go back more in command history. (Only tested it on Google Chrome so far)

**Comment by jasoryeh** [comment]
I think I can fix Problem #2 
![image](https://user-images.githubusercontent.com/13290941/32202976-b02de700-bd9d-11e7-8cd9-531a90843591.png)
Those changes seem to fix the highlighting problemo.

**Comment by jasoryeh** [comment]
In case you dont see the change, its the `//` on line 50

**Comment by kaganus** [comment]
instead of commenting it out, removing #terminal, is working too while allowing others to focus on click

**Comment by jasoryeh** [comment]
Im just keeping it in case its needed in the future.

**Comment by DaneEveritt** [comment]
Issue 2 is solved by #709

**Comment by kaganus** [comment]
Problem 1 is solved by #715

**Comment by kaganus** [comment]
did you send a fix for the problem #3?

**Comment by DaneEveritt** [comment]
I can not reproduce #3 reliably. Itll get touched again when things are transitioned to vuejs as well.

**Comment by kaganus** [comment]
i cant reproduce it on will either yeah. ok then thanks
