### ISSUE TITLE
"Suggested IPs" on allocations page only shows what's in that table

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#712]
Another interesting bug here:

When I go to add an IP address as an allocation, it drops down a list of suggestions. The suggestions shown are only the suggestions that currently show up on that page of the table. If there's a page 2 or 3, it doesn't show whatever IP addresses are on that page. It's really not a big deal, but super misleading since I added .202 and .203 (each of which had about 50 ports that I added for each) which pushed me into a couple of pages. I added .204 and then when I went to add .205, I didn't see .204 (making me think it never got added). When I scrolled to page 3, I saw .204. Then I tried to add .205 again and this time, I didn't see .202 and .203, leading me to the conclusion that it's only showing what's on the table on that particular page. Hope this makes sense.

Since ports don't show "suggested ports", it's not an issue there.

**Comment by lancepioch** [comment]
Panel version?

**Comment by xyeLz** [comment]
0.6.4
