### ISSUE TITLE
Panel configuration help

### ISSUE THREAD

**Issue by jsProj** [Pterodactyl/Panel#717]
* Panel or Daemon: panel
* Version of Panel/Daemon: v0.6
* Server's OS: Ubuntu 16.04.3
* Your Computer's OS & Browser: Win 10, chrome

## Add Details Below:
Everything installed and went smoothly, yet I get, `Whoops, looks like something went wrong.` when visiting, https://panel.lighthost.ga/ its working with nginx, all services are set and enabled, along with cron set.

**Comment by DRSchlaubi** [comment]
could you give me the output of `php -v` and the panel logs
`cat /var/www/html/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99|

**Comment by schrej** [comment]
As this is probably human error and not a bug I'll close this. Use Discord or the forums for support please.
