### ISSUE TITLE
[0.7] Error Daemon

### ISSUE THREAD

**Issue by CraftYourWay** [Pterodactyl/Panel#726]
Please describe your issue in full below. Include what products are affected, as well as what version(s) you are running. Please also include information about your system, such as `uname -a` and `php -v` and `docker info` if applicable.

If you're just making a suggestion, be descriptive, and link to any issues that might be releated as well.

You can delete from this line up.
---------------------

* Panel or Daemon: 
Daemon
* Version of Panel/Daemon: 
5.0
* Server's OS: 
Linux Ubuntu latest
* Your Computer's OS & Browser: 
Windows 10

## Add Details Below:
getting the following error:

04:04:32.039Z  INFO wings: + ------------------------------------ +
04:04:32.042Z  INFO wings: | Running Pterodactyl Daemon v0.5.0-beta.1    |
04:04:32.043Z  INFO wings: |        https://pterodactyl.io        |
04:04:32.043Z  INFO wings: |  Copyright 2015 - 2017 Dane Everitt  |
04:04:32.043Z  INFO wings: + ------------------------------------ +
04:04:32.043Z  INFO wings: Loading modules, this could take a few seconds.
04:04:32.543Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
04:04:32.618Z  INFO wings: Configuring user p.dactyl (id: 999) as the owner of all server files.
04:04:32.625Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
04:04:32.627Z  INFO wings: Checking container networking environment...
04:04:32.640Z  INFO wings: Found network interface for daemon: pterodactyl_nw
04:04:32.640Z  INFO wings: Configuring timezone file location...
04:04:32.640Z  INFO wings: Checking pterodactyl0 interface and setting configuration values.
04:04:32.641Z  INFO wings: Checking gateway for pterodactyl0
04:04:32.654Z  INFO wings: Gateway detected as 172.18.0.1 for pterodactyl0.
04:04:32.672Z  INFO wings: Checking current files aganist panel response.
04:04:32.675Z  INFO wings: Attempting to load servers and initialize daemon...
04:04:32.698Z FATAL wings: A fatal error caused the daemon to abort the startup. (additional={})
    Error: No service type was passed to the server configuration, unable to select a service.
        at Server.initContainer.err (/srv/daemon/src/controllers/server.js:86:29)
        at docker.Docker (/srv/daemon/src/controllers/server.js:116:24)
        at Object.inspect [as callback] (/srv/daemon/src/controllers/docker.js:90:24)
        at /srv/daemon/node_modules/dockerode/lib/container.js:72:12
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:270:7)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
04:04:32.698Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.

**Comment by DaneEveritt** [comment]
Whatever server is throwing that error has an invalid configuration file. I've added a change to show the server UUID in the error, but this isn't a bug.

**Comment by DaneEveritt** [comment]
Turns out this is actually a bug... my bad.
