### ISSUE TITLE
Feature Request: Auto-Deploy Script

### ISSUE THREAD

**Issue by DoNotSpamPls** [Pterodactyl/Panel#728]
It would be very convenient to have a (semi)-automatic deploy script, when you have to put the Panel and/or Daemon on many nodes.

**Comment by schrej** [comment]
We are planning on releasing a official docker container with 0.7, that should be enough and is easier than an install script for us to create and maintain

**Comment by DoNotSpamPls** [comment]
Okay then, closing the issue.
