### ISSUE TITLE
Something odd with panel timeout

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#734]
I'm running 0.6.3 and have noticed this a few times but never actually tested it.

Basically, when you're logged into the panel and then go idle, after a certain period of time it seems like the session is supposed to "time out" and require you to log back in again. For example, if I'm logged in as user X and I go into my server startup settings, then I disappear for a couple hours and come back and click on My Account, it requires me to log back in. This happens _most_ of the time.

However, this is inconsistent as I noticed that sometimes it doesn't time out like it should. Based on my testing today, it seems like after multiple hours of being idle, if I'm still logged in and then click on My Servers, it doesn't actually time out. So far I've only been able to successfully verify this by clicking on My Servers. After this, I'm able to access everything else without logging in again as well (like My Account, Admin settings, etc).

**Comment by DaneEveritt** [comment]
The session timeout is set to more than a few hours, this isn't a bug and is likely your browser being strange.
