### ISSUE TITLE
Deamon version isn't displayed

### ISSUE THREAD

**Issue by MelcomX** [Pterodactyl/Panel#742]
* Panel or Daemon: Both (Communication)
* Version of Panel/Daemon: 0.7 & 0.5 --> Both downloades 4PM Berlintime
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 Chrome and Edge

## Add Details Below:

When I go to the nodes page  and choose a server (admin/nodes/view/1) I get the Daemonversion: 0.0.0-canary. I tried this in the Edge Browser and in the Google Chrome Browser...

**Comment by parkervcp** [comment]
It shows 0.0.0-canary because it's a testing build. This is normal. Ask in the Beta Support chat first.
