### ISSUE TITLE
Restart Script

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#744]
What's about a restart script
On every restart a script will be executed like the install script.

standard content would be:
`${STARTUP_PARAMETER}`

it would also maybe replace the Configuration Block

![](https://image.prntscr.com/image/zAZPSwPVRMmFtqiGhguOlQ.png)

For my purpose it would be a git clone command:
```
mkdir /tmp/git_download/
git clone http://github.com/xx/serverfiles-configs.git /tmp/git_download
cp -r /tmp/git_download/* /mnt/server/csgo/
rm -rf /tmp/git_download/  
${STARTUP_PARAMETER}
```
This repo e.g.  just contains some cfg files

**Comment by ProJaCore** [comment]
If you wonder: I use git to experiment on my dev servers via dev and push it to all my master servers via the master branch. the struggle is when i have to reinstall the server everytime when i do a commit.

**Comment by parkervcp** [comment]
Discussed in Discord.

This can already be handled by the current panel. With a customer service and customer game container you can do what you want here.
