### ISSUE TITLE
Lack of documentation after initial setup

### ISSUE THREAD

**Issue by skluthe** [Pterodactyl/Panel#745]
There seems to be a severe lack of documentation after the instillation of the panel is finished. I'm not able to find any tutorials for how to setup a node that aren't outdated. I'm just trying to run pterodactyl and run a game server on that same server but cannot find any info on how to do that. Is there anywhere that this documentation is living that I'm missing or is there none?

**Comment by schrej** [comment]
Documentation on doing that is going to be living here: https://guides.pterodactyl.io/
There doesn't seem to be documentation on how to do that currently.

**Comment by DaneEveritt** [comment]
This isn't really a GitHub issue, but I'll admit there isn't a ton of documentation after the installation part. However, that comes down to time and resources available, and neither of those are in high quantity for a lot of the core team currently.
