### ISSUE TITLE
Console Scroll Speed

### ISSUE THREAD

**Issue by tenten8401** [Pterodactyl/Panel#746]
Is there any way we could get a faster receiving speed for console text? Modded servers fall super far behind when starting up because they print out tons of logs at once.

**Comment by kaganus** [comment]
config/pterodactyl.php:
    'console' => [
        'count' => env('CONSOLE_PUSH_COUNT', 50), <=== change to 100
        'frequency' => env('CONSOLE_PUSH_FREQ', 200), <=== change to 50
    ],

**Comment by schrej** [comment]
Rather set those values in your .env file.
```
CONSOLE_PUSH_COUNT=100
CONSOLE_PUSH_FREQ=50
```
and `php artisan config:cache`
