### ISSUE TITLE
Node Appears as offline, even though it is online.

### ISSUE THREAD

**Issue by ScarletWolf275** [Pterodactyl/Panel#749]
Title says it all
---------------------

* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.7-beta.1
* Server's OS: Ubuntu 16.04 x64
* Your Computer's OS & Browser: Safari on MacOS High Sierra

## Add Details Below:
http://prntscr.com/h8sqjv
http://prntscr.com/h8sqng

**Comment by DaneEveritt** [comment]
closed in https://github.com/Pterodactyl/Panel/commit/25694c851ac85ec233b0236cf5052c1dbebac757
