### ISSUE TITLE
Default Allocation Dropdown for creating a server is not working

### ISSUE THREAD

**Issue by ScarletWolf275** [Pterodactyl/Panel#750]
Title. And yes, I did add the allocations
---------------------

* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.7-beta.1
* Server's OS: Ubuntu 16.04 x64
* Your Computer's OS & Browser: Safari on MacOS High Sierra

## Add Details Below:
http://prntscr.com/h8stqc

**Comment by DaneEveritt** [comment]
Please check the changelog and previous issues before creating new ones. 

https://github.com/Pterodactyl/Panel/blob/develop/CHANGELOG.md

This was fixed earlier this week.

**Comment by ScarletWolf275** [comment]
Well really, if your docs are not saying anything about a beta.2 and it is not in the releases then you can't really expect anyone to guess that you released a fix for it but did not care to make a release since this is a very important issue fix.

**Comment by DaneEveritt** [comment]
I'm just letting you know that the Changelog tracks changes that are made, including changes to un-released versions, and there was already an issue relating to this. There are tags for `Beta/RC Build` that can help narrow down the issue list for easier skimming.

**Comment by ScarletWolf275** [comment]
Well if it is unreleased how on earth do I update to it :/

**Comment by DaneEveritt** [comment]
Use git, if you're unsure how to do that you'll just have to wait.
