### ISSUE TITLE
Empty allocation dropdown on server creation page with Chrome 

### ISSUE THREAD

**Issue by F0x06** [Pterodactyl/Panel#751]
* Panel
* Version of Panel/Daemon: 952d8d154c21ff525ec4f44751e8b34352e00cb6 (develop)
* Server's OS: Ubuntu 14.04.5 LTS x64
* Your Computer's OS & Browser: Windows 10 x64 Chrome

EDIT: i tested with firefox and it works, its a Chrome issue

Empty allocation dropdown on server creation page, and yes i correctly added allocations

Thanks in advance :)

**Comment by stanjg** [comment]
https://github.com/Pterodactyl/Panel/issues/750

**Comment by F0x06** [comment]
Is this fix pushed to develop ? Because on the latest develop branch commit the bug is present.

**Comment by DaneEveritt** [comment]
Clear your cache. If it works fine in one browser and not in another thats generally the problem.
