### ISSUE TITLE
[0.7] Change Server to another User fails.

### ISSUE THREAD

**Issue by npwfox** [Pterodactyl/Panel#753]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7 canary (latest from git)
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 & Chrome 

Change Server to another User fails. When i try to change the user comes this https://cdn.npw.ovh/screen/bj9ao8dX5a.gif .

**Comment by DaneEveritt** [comment]
I'm not seeing this in my local environment. I'm able to change the user without a problem.

Can you please provide the error log, the picture of the error page is not very helpful.

**Comment by npwfox** [comment]
Um, this is i test this again on other Servers. On these works great, but on the two first created Server didn't works. I deleted the Servers.

**Comment by DaneEveritt** [comment]
Interesting 🤔
