### ISSUE TITLE
CPU Graph Doesn't Scale by CPU Limit [+ Suggested Fix]

### ISSUE THREAD

**Issue by jcsnider** [Pterodactyl/Panel#758]
* Panel or Daemon: Panel
* Version of Panel/Daemon: All (Suggested fix is for the latest development branch)
* Server's OS: Centos 7 (But this bug affects all)
* Your Computer's OS & Browser: Win10 + Chrome

## Add Details Below:
This affects all versions of the Panel... I fixed it in my copy of 0.6.4. I'll include a suggested fix in this issue report.

Just giving an example, let's say I have a server with a CPU limit of 50, and I have it running an infinite loop maxing out cpu usage.  On the [server list](http://www.ascensiongamedev.com/resources/filehost/7f49c1943d81d89216805dea04a00390.png), my users would see 100% CPU usage as expected, but on [the console page](http://www.ascensiongamedev.com/resources/filehost/fc8cae53b56d4fd5a3b94b719c9be5f3.png) it would sit around 50%.

The code is in the javascript to scale appropriately but the 'Pterodactyl.server.cpu' was undefined.

**My suggested fix (for the development branch):**
Modify app/Traits/Controllers/JavascriptInjection.php
After
 `'daemonSecret' => $token, on line 57`

Add
`'cpu' => $server->cpu;`

**Comment by lancepioch** [comment]
Made a PR with your suggested fix, thanks.
