### ISSUE TITLE
Allow on-the-fly server rebuild

### ISSUE THREAD

**Issue by jffz** [pterodactyl/panel#759]
It could be interesting to be able to force a server rebuild through cli or api in order to update an image on multiple servers / nodes.

**Comment by DaneEveritt** [comment]
I'm pretty sure the CLI in 0.7 supports this already with the rebuild command which can do a single server, entire node, or all servers.

I'm leaving this issue so we can also add an API end point.

**Comment by jffz** [comment]
What is the way to trigger it then ?

**Comment by DaneEveritt** [comment]
You'd need to be on 0.7 and use `p:server:rebuild`.

```
    protected $signature = 'p:server:rebuild
                            {server? : The ID of the server to rebuild.}
                            {--node= : ID of the node to rebuild all servers on. Ignored if server is passed.}';
```

**Comment by DaneEveritt** [comment]
This is complete in the API and UI, as well as through the CLI.
