### ISSUE TITLE
Silent unauthenticated redirection bug resulting in no error message.

### ISSUE THREAD

**Issue by DaneEveritt** [pterodactyl/panel#760]
There seems to be a persistent bug affecting a small sub-set of individuals that causes no error message to be rendered on the login form when they attempt to login. The application silently attempts a login, and fails with an `AuthenticationException`, but does not display the message.

Previously I assumed this was a session issue, but I was able to partially reproduce it locally, and it seems there are cases where no error message gets displayed.

**Comment by schrej** [comment]
This issue exists since a long time and affects not only the beta but some previous versions as well. We just never found the actual bug.

**Comment by DaneEveritt** [comment]
Yeah, I knew this had been around for awhile. I think I know what might be causing it, but reproducing it consistently is still a pain.

**Comment by lancepioch** [comment]
I don't think this is an issue anymore with the latest Laravel version.

The only things that seem to block logins (besides wrong passwords) is Recaptcha and CSRF checking and they both show properly.

**Comment by schrej** [comment]
As there hasn't been any reports on this in a long time I'm going to close it, we can reopen if it reoccurs.

**Comment by TheDutchMC04** [comment]
Issue just happened to me, I think because my reCaptcha keys are invalid, however I need to login to fix this
