### ISSUE TITLE
How to translate the panel to Chinese？

### ISSUE THREAD

**Issue by gzzchh** [Pterodactyl/Panel#762]
I try to translate some php files in resources/lang, but when I refresh the page ,I found the text are not the Chinese I want ,they are '???'
Shall I do something to the files? Or I should translate them in another way?(I use omegaT for translate.)

**Comment by lancepioch** [comment]
https://pterodactyl-guides.readme.io/docs/contributing-to-pterodactylpanel#section-adding-new-languages

**Comment by gzzchh** [comment]
The problem has solved, I install the panel on another machine with LNMPA,and all Chinese can show correctly. I test my translate on the testing VM(Pterodactyl-DEV) before and I think the test VM dose not have the Chinese support.
