### ISSUE TITLE
[0.7] Can't create Source server

### ISSUE THREAD

**Issue by DoNotSpamPls** [Pterodactyl/Panel#769]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.0-beta2
* Server's OS: Ubuntu 16.04 LTS
* Your Computer's OS & Browser: Windows 10 Pro x64, Opera 49

## Add Details Below:
Panel Logs: https://bin.ptdl.co/mf0hr/
Daemon Logs; https://hastebin.com/egoxequhap

When creating a Source server (I tried with CS:GO, but I think it happens with all of them), I get a "Whoops, something went wrong!" page.

**Comment by DaneEveritt** [comment]
This isn’t a bug with this software, the error is saying connection refuses indicating an issue with your SQL setup.

**Comment by DoNotSpamPls** [comment]
@DaneEveritt I forgot to say that the SQL errors are from before (me trying to setup databases), just included the panel log incase there was anything else that could be useful.

**Comment by DaneEveritt** [comment]
You've still provided nothing that I can use to diagnose the issue. You need to provide an actual, up-to-date log that includes the error, not a random log containing unrelated errors.

Theres nothing in the Panel that throws an error like that without logging it somewhere.

**Comment by DoNotSpamPls** [comment]
The thing is, I am sure it doesn't give an error in the logs. I just wiped them so they can be fresh. Did the same procedure, still got the `Whoops, something went wrong` error. The panel didn't even create a log, and the daemon gave this one - https://hastebin.com/ugenebexug - which is just telling me that it started correctly.

**Comment by lancepioch** [comment]
You need to post the error from your panel.

**Comment by DoNotSpamPls** [comment]
@lancepioch the only thing it gives me is that `Whoops, something went wrong!` message, logs give me nothing
