### ISSUE TITLE
Enabling 2FA throws a "Payload is Invalid"

### ISSUE THREAD

**Issue by tenten8401** [Pterodactyl/Panel#770]
Running latest git, and when enabling 2FA I'm getting a response like the following: https://hastebin.com/tonipolile.json

**Comment by lancepioch** [comment]
I’ll check this out.

**Comment by DaneEveritt** [comment]
Curious as to what page this is happening on. That error response seems to indicate an API or AJAX based request, which makes no sense for the login.

**Comment by tenten8401** [comment]
@DaneEveritt It's happening when enabling 2FA for an account and when that dialog comes up with the QR and you scan it and enter the code.

**Comment by lancepioch** [comment]
I was able to reproduce the issue by not migrating the latest migration. What happens is that the totp_secret is now encrypted and takes up more space in the DB. The encrypted secret was getting cut off and wasn't matching any new combinations.

    php artisan migrate
