### ISSUE TITLE
Running artisan command twice gives you a error

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#773]
After i mistyped a value in the configuration: 
`php artisan p:environment:setup `
i tried to rerun but it throw an error:
![error](https://user-images.githubusercontent.com/12472791/33091998-0a04289a-cef9-11e7-83f1-ac5a84342583.png)

this will happen on every rerun. 
plz fix - with regards

**Comment by lancepioch** [comment]
Why did you go to the trouble of ignoring and deleting all that filler text we wrote with our instructions on how to submit an issue with helpful information to us?

Reply with that information so we can help you.
