### ISSUE TITLE
Database Hosts (node id is invalid.)

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#774]
As i installed the panel (commit version 1fcad8d8) successfully, i tried to insert my database credentials.
Due to the fact that I dont have any nodes, i did just left the setting "Linked Nodes" default.
![](https://image.prntscr.com/image/pCVXyBiMTa2mU-cip_xLUA.png)
As you can see the Option "Linked Node" is not important.

When i press "Create" the following error will throw:
![](https://image.prntscr.com/image/9d_qpmC7SCeM_GhrFJEfOw.png)

With regards

**Comment by lancepioch** [comment]
As a workaround, simply create and select a node first.

**Comment by DaneEveritt** [comment]
I would assume this `@todo` might be the problem... whoops.

![http://i.kumquat.io/1J072G2s061P](https://d1ax1i5f2y3x71.cloudfront.net/items/0V3x3U2B0F0E3O432D0P/Image%202017-11-25%20at%2013.26.32.png?X-CloudApp-Visitor-Id=2847162&v=719a28ca)
