### ISSUE TITLE
On Egg Import Egg does not get validated.

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#779]
If i import an Egg with a variable that is required but doesnt have a standard value its ignoring it.
A docker image check would be also good.

Panel: 1fcad8d
Server's OS: Ubuntu 16.04
Your Computer's OS & Browser: Firefox 58.0b5 (64-Bit) Developer Edition, Windows 10 latest

**Comment by lancepioch** [comment]
Can you upload the file so we can test, thanks

**Comment by ProJaCore** [comment]
@lancepioch well i cooked some egg to give you a better taste, have a great lunch:
[https://hastebin.com/ititukumot.json](https://hastebin.com/ititukumot.json)

import the given egg
![](https://image.prntscr.com/image/rTbvNtCKRfie7mtjEtMMAQ.png)

then press import aaand:
![](https://image.prntscr.com/image/YOT5DLSKR6Ot_NF5KM-CYg.png)

even if i save the complete egg
![](https://image.prntscr.com/image/pu8F7NxtTeW8jDzC7Raklw.png)

![](https://image.prntscr.com/image/WwlMB9yET2Ows1ay46gnIA.png)

---
## it will not check for the docker image 
well i will create a seperate issue for this https://github.com/Pterodactyl/Panel/issues/782
but its also passing it without checking for the input value.
![](https://image.prntscr.com/image/OyFUvkm1Qjq0F2hUK9S9ZA.png)

As you can see it saved my invalid standard values:
![](https://image.prntscr.com/image/ZVYK5QBpRu_tSMVX6YRlqA.png)
But atleast on this Site Lavarel Validation does work correctly:

![](https://image.prntscr.com/image/jylqKLwGTcGwMHrt1eiuJg.png)

with regards

**Comment by DaneEveritt** [comment]
I do not see a bug here, and your docker issue is not a bug, as I mentioned in the linked issue.

Can you please clarify exactly what you think the problem here is.

**Comment by ProJaCore** [comment]
The problem is that it will not check the egg on import;
but thats more a P:low thread so

**Comment by DaneEveritt** [comment]
I'm sorry, I do not understand what you're trying to say is broken here. "will not check on egg-import" does not make sense to me.

What is not checked, what is not erring that you believe should be, because all of your screenshots appear completely normal.

**Comment by ProJaCore** [comment]
Okay well the topic is about->
on Egg import the given variables in the json file have standard values.

and these standard variables must not match with the validation. i think this is kinda invalid.

![](https://image.prntscr.com/image/fMg4H7SyS_aZ8jX5PuxDBw.png)

**Comment by DaneEveritt** [comment]
The same thing as I said in the other issue about docker applies here. Setting a default value that doesn't meet the requirements of that field is an administrative user issue, not the fault of the Panel.
