### ISSUE TITLE
Lavarel Validation: On not valid situation i get a error page instead of a message

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#780]
If i try to enter a invalid char and Lavarel jumps on it, its not notifiying me, 
instead its forwarding me to this page:

![](https://image.prntscr.com/image/WT8llc5vRBGYrCYGt1b7ew.png)

strangee...

* Panel: 1fcad8d8
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Firefox 58.0b5 (64-Bit) Developer Edition, Windows 10 latest

**Comment by lancepioch** [comment]
Which page and action?

**Comment by DaneEveritt** [comment]
Please include the logs as well. This error by itself is completely useless to us for debugging.

**Comment by ProJaCore** [comment]
I will do when i am available.
The error occurrs everytime when you try to update a invalid value for a server in the startup tab.
Just paste something into one of the fields that will not match the given lavarel validation; like leave a required field blank or paste some special character into the Steam account field

**Comment by ProJaCore** [comment]
@DaneEveritt I tried to catch the log but it seems like it does not output any log.
I tested and so far this error will only occur on the administrative site and not on the user only interface:
![](https://image.prntscr.com/image/V858R-ayQs2MWbbc3tgUYA.png)

its easy to reproduce the error. just go via the admin panel to the startup tab:
![](https://image.prntscr.com/image/t-eczY4iS3eVGNu2IBdE9g.png)

and break the lavarel rules:
![](https://image.prntscr.com/image/L1dnRgndTT6PcqEC8QLO1g.png)

after saving here we are:
![](https://image.prntscr.com/image/xZ1cKSHAT1Gc9YOCEZEW-A.png)

with regardos santos

**Comment by DaneEveritt** [comment]
The whoops page writes a log, you need to provide that log for us to actually see what is going on there. It is in `storage/logs/laravel-<date>.log`

**Comment by ProJaCore** [comment]
No logs will be shown. i tried first with tail -f * to make sure and afterwards i deleted and rebooted the server

**Comment by DaneEveritt** [comment]
Okay, should be enough information to reproduce locally, will let you know if I can't find the source.
