### ISSUE TITLE
Egg: Docker Image does not get validated

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#782]
From the other https://github.com/Pterodactyl/Panel/issues/779#issuecomment-346958997 i just found another PoP (Point of Pain^^)
On Egg creation or update theres no check for the given docker image.
![](https://image.prntscr.com/image/OyFUvkm1Qjq0F2hUK9S9ZA.png)
I think ur already using lavarel validation (required) on the docker input but you should also validate that its a valid url or better check if the requested image does even exist

**Comment by DaneEveritt** [comment]
There are so many different ways that a docker image can exist that it would be unreasonable to attempt to validate that it does exist. It is possible to use local images that do not exist on the machine running the panel, and hitting an API to determine if the image exists publicly is a poor validation solution, and leads to problems if that API were to go down or become slow.

It is up to the administrator of the Panel to make sure they are using the correct images and handle that as needed. Features like these are simply sprinkles on the software, require additional development time and testing, and don't really solve anything that can't be solved by validating your own values. Realistically servers will not have individual images, so when you're making the egg you should be ensuring that you're entering the correct values.
