### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by ProJaCore** [pterodactyl/panel#784]
Adding a Plugin System for Runtime/Panel modifications.

Thats a hell long way but maybe it will make things possible:
In this way we don't need to fork the panel and modify it until the next update will come;

Pterodactyl makes a great step towards flexibility with custom eggs, import and export support;
with custom images and else;
But it should also make this step towards into the modification world where you can create a plugin which will bring you and other people with the same interest closer to the wanted state. 

As an example: Adding a Pinboard to the site or shoutbox for chatting;
I thinked about some wordpress magic... like with shortcodes [shoutbox id=1]

wordpress is also in PHP so it would be a mixture of Copy,Paste and modify.

**Comment by ProJaCore** [comment]
@lancepioch  why did you close it?

**Comment by DaneEveritt** [comment]
I'm closing this issue as I don't see this happening at any point in the foreseeable future.
