### ISSUE TITLE
Schedule Manager

### ISSUE THREAD

**Issue by Tyler-Burr** [Pterodactyl/Panel#786]
* Panel : v0.7.0-beta.2
* Daemon: v0.5.0-beta.3
* Ubuntu 16.04
* Google Chrome

==============================

Whoops!
An error occured while attempting to delete this schedule.

<img width="958" alt="scheduledtask" src="https://user-images.githubusercontent.com/33735005/33291561-7a66f6f6-d383-11e7-8fea-0bfceeed64bf.PNG">

**Comment by DaneEveritt** [comment]
Please provide the relevant error logs. This is not enough information to work with.

**Comment by Faicu** [comment]
Errors from Browser Console:
![image](https://user-images.githubusercontent.com/16672714/33434856-3b718160-d5e9-11e7-8688-d24649d1b1f7.png)

**Comment by lancepioch** [comment]
The relevant error logs are from the panel, not the browser.

**Comment by DaneEveritt** [comment]
Those logs are fine, shows it’s probably Auth logic that’s broken.

**Comment by schrej** [comment]
@lancepioch In this case (as this is Ajax) those are the first logs you can get. As this is just getting an unauthorized error there probably won't be anything in the panel logs anyways. I told him to upload that screenshot here.
