### ISSUE TITLE
Reinstall: No service type was passed to the server configuration

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#788]
Reinstallation process was successfully but the installation failed and the following error came up:
```
INFO wings: Completed installation process for server. (server=xxxxx-xxx)
ERROR wings: No service type was passed to the server configuration, unable to select a service.
```
Here the hastebin: https://hastebin.com/apuvajuzip.js

edit: i use my own Docker image `quay.io/cply/docker:csgo` ([GITHUB source](https://github.com/ProJaCore/docker/tree/csgo))
    - Daemon:  0.5.0-beta.3
    - Node.js: v6.11.4
    - Docker:  Docker version 17.09.0-ce, build afdb6d4

**Comment by ProJaCore** [comment]
@DaneEveritt Well the error does still occur when i try to reinstall the server; btw. theres another error you can see( no config ) what does that mean ? hmmh

**Comment by DaneEveritt** [comment]
You need to actually pull down the correct files to fix this, there isn't a tagged release, and I can see from your output that you're still on 0.5.0-beta.3.
