### ISSUE TITLE
Error while trying to connect panel with daemon (Error: xhr poll error)

### ISSUE THREAD

**Issue by MichlPlay** [Pterodactyl/Panel#791]
### uname -a:
Linux [DOMAIN1] 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.30-2+deb9u5~bpo8+1 (2017-09-28) x86_64 GNU/Linux

### php -v:
PHP 7.1.12-1+0~20171129100725.11+jessie~1.gbp8ded15 (cli) (built: Nov 29 2017 11:00:32) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.1.12-1+0~20171129100725.11+jessie~1.gbp8ded15, Copyright (c) 1999-2017, by Zend Technologies

### docker-info:
Containers: 2
Running: 1
Paused: 0
Stopped: 1
Images: 3
Server Version: 17.11.0-ce
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Kernel Version: 4.9.0-0.bpo.3-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 29.46GiB
Name: [DOMAIN1]
ID: 4CPI:MFV2:VAIG:D2TD:AJV5:VWHE:WSDL:AOFE:TYS5:RLVQ:OVET:JXEF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

### Additional system-informations
I'm running a VPS, controlled with VestaCP, I upgraded php to version 7.1 and followed the install documentation for the panel and the daemon. I changed my snginx.conf and nginx.conf to the suggestions under: https://docs.pterodactyl.io/docs/webserver-configuration and now it's looking something like that:

server {
listen 173.249.11.142:443 ssl http2;
server_name [DOMAIN2];

root /pterodactyl/public;
index index.php;

access_log /var/log/nginx/pterodactyl.app-access.log;
error_log /var/log/nginx/pterodactyl.app-error.log error;

// allow larger file uploads and longer script runtimes
client_max_body_size 100m;
client_body_timeout 120s;

sendfile off;

// strengthen ssl security
ssl_certificate /home/admin/conf/web/ssl.[DOMAIN2].pem;
ssl_certificate_key /home/admin/conf/web/ssl.[DOMAIN2].key;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_session_cache shared:SSL:10m; (I must delete the ciphers entries because i got an error with them)

// See the link below for more SSL information:
// https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
//
// ssl_dhparam /etc/ssl/certs/dhparam.pem;

// Add headers to serve security related headers
add_header Strict-Transport-Security "max-age=15768000; preload;";
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
add_header X-Robots-Tag none;
add_header Content-Security-Policy "frame-ancestors 'self'";

location / {
try_files $uri $uri/ /index.php?$query_string;
}

location ~ \.php$ {
fastcgi_split_path_info ^(.+\.php)(/.+)$;
// the fastcgi_pass path needs to be changed accordingly when using CentOS
fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
fastcgi_index index.php;
include fastcgi_params;
fastcgi_param PHP_VALUE "upload_max_filesize = 100M \n post_max_size=100M";
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
fastcgi_param HTTP_PROXY "";
fastcgi_intercept_errors off;
fastcgi_buffer_size 16k;
fastcgi_buffers 4 16k;
fastcgi_connect_timeout 300;
fastcgi_send_timeout 300;
fastcgi_read_timeout 300;
include /etc/nginx/fastcgi_params;
}

location ~ /\.ht {
deny all;
}
}
### daemon-config:
My daemon-config is from the create node page with changed ssl certificate paths (I changed the port beacause VestaCP already uses 8080):
{
"web": {
"host": "0.0.0.0",
"listen": 7777,
"ssl": {
"enabled": true,
"certificate": "/home/admin/conf/web/ssl.[DOMAIN2].pem",
"key": "/home/admin/conf/web/ssl.[DOMAIN2].key"
}
},
"docker": {
"socket": "/var/run/docker.sock",
"autoupdate_images": true,
"timezone_path": "/etc/timezone",
"interface": "172.18.0.1"
},
"sftp": {
"path": "/srv/daemon-data",
"port": 2022,
"container": "5c2d907a57bbd89bd62dc128d8058f253af747ab55b35c4b790dd39d9d0c7505"
},
"logger": {
"path": "logs/",
"src": false,
"level": "info",
"period": "1d",
"count": 3
},
"remote": {
"base": "https://[DOMAIN2]"
},
"uploads": {
"size_limit": "100"
},
"keys": [
"[THE SECRET KEY]"
]
}

# My Error:
My node gets in the node list just a red lined heart and I think I heard it must be green. And when create a server its check the status very long and after that I get the error:
"There was an error attempting to establish a WebSocket connection to the Daemon. This panel will not work as expected.

Error: xhr poll error"

Now is my question how to fix this. 🤔
PS: I hope my english was understandable.

**Comment by DaneEveritt** [comment]
Please see https://guides.pterodactyl.io/docs/debugging-transferexception-and-socketio-issues for ways to resolve this.

**Comment by katubug** [comment]
Sorry for the necromancy, but I am having this same issue and came here via google. The link that Dane so kindly provided is no longer valid. I asked at the Discord server and the auto-responder sent me to this link: https://pterodactyl.io/panel/troubleshooting.html#transfer-exceptions-xhr-poll-error

So I thought I would comment in order to save future googlers a step or two.

**Comment by parkervcp** [comment]
An updated link would be - https://pterodactyl.io/panel/troubleshooting.html#transfer-exceptions-xhr-poll-error

**Comment by VaasKahnGrim** [comment]
@katubug 
https://pterodactyl.io/panel/troubleshooting.html#transfer-exceptions-xhr-poll-error

**Comment by parnexcodes** [comment]
The link doesn't work (both of them) , Can someone post a new link!

**Comment by M-AlNoaimi** [comment]
@parnexcodes @katubug https://pterodactyl.io/panel/0.7/troubleshooting.html
_Although this link is for the 0.7 version of the panel... Unsure if this is still valid, but it's what's available._
