### ISSUE TITLE
Arma 3 Nest Egg

### ISSUE THREAD

**Issue by ryan1161** [Pterodactyl/Panel#792]
Panel: 0.7.0-beta.2
Daemon: 0.5.0-beta.3
Ubuntu 16.04

I'm needing help on getting this to run I have got other steam games running but this one keeps giving me this error and when I send the command ls when starting it shows that file that is says is missing.

![image](https://user-images.githubusercontent.com/2374149/33528327-f1b1df06-d823-11e7-8ee6-8d14721818a4.png)

egg.arma3.json

{
    "_comment": "DO NOT EDIT: FILE GENERATED AUTOMATICALLY BY PTERODACTYL PANEL - PTERODACTYL.IO",
    "meta": {
        "version": "PTDL_v1"
    },
    "exported_at": "2017-12-03T12:21:32-06:00",
    "name": "Arma 3",
    "author": "GamePanael@tafaricraft.com",
    "description": "Starting with the successful Arma: Cold War Assault (originally titled Operation Flashpoint*: Cold War Crisis) in 2001, Arma 3 is the latest installment in Bohemia Interactive\u2019s award-winning tactical military shooter series for PC. Set in a massive Mediterranean sandbox of over 290 km\u00b2, featuring 40+ weapons and 20+ vehicles, Arma 3 provides an authentic, diverse and open combat experience \u2013 supported by a wide variety of singleplayer and multiplayer gameplay. Together with the brand new Real Virtuality\u21224 engine, limitless opportunities for content creation and a passionate community, the PC\u2019s premier military simulation game series is back. Arma 3 \u2013 This Is War.",
    "image": "quay.io\/nerdism\/pterodactyl:rvr4",
    "startup": ".\/arma3server -config=server.cfg -port=2302 -maxplayers=32",
    "config": {
        "files": "{}",
        "startup": "{\r\n    \"done\": \"gameserver Steam ID\",\r\n    \"userInteraction\": []\r\n}",
        "logs": "{\r\n    \"custom\": true,\r\n    \"location\": \"logs\/latest.log\"\r\n}",
        "stop": "^C"
    },
    "scripts": {
        "installation": {
            "script": "#!\/bin\/bash\r\n# Arma3: Installation Script\r\n#\r\n# Server Files: \/mnt\/server\r\napt -y update\r\napt -y --no-install-recommends install curl lib32gcc1 ca-certificates\r\n\r\ncd \/tmp\r\ncurl -sSL -o steamcmd.tar.gz http:\/\/media.steampowered.com\/installer\/steamcmd_linux.tar.gz\r\n\r\nmkdir -p \/mnt\/server\/steamcmd\r\nmkdir -p \/mnt\/server\/Engine\/Binaries\/ThirdParty\/SteamCMD\/Linux\r\n\r\ntar -xzvf steamcmd.tar.gz -C \/mnt\/server\/steamcmd\r\ntar -xzvf steamcmd.tar.gz -C \/mnt\/server\/Engine\/Binaries\/ThirdParty\/SteamCMD\/Linux\r\n\r\ncd \/mnt\/server\/steamcmd\r\n\r\n# SteamCMD fails otherwise for some reason, even running as root.\r\n# This is changed at the end of the install process anyways.\r\nchown -R root:root \/mnt\r\n\r\nexport HOME=\/mnt\/server\r\n.\/steamcmd.sh +login username 12345 +force_install_dir \/mnt\/server +app_update 233780 +quit\r\n\r\nmkdir -p \/mnt\/server\/.steam\/sdk32\r\ncp -v linux32\/steamclient.so ..\/.steam\/sdk32\/steamclient.so",
            "container": "ubuntu:16.04",
            "entrypoint": "bash"
        }
    },
    "variables": [
        {
            "name": "Steam Username",
            "description": "You steam account username.",
            "env_variable": "STEAM_USER",
            "default_value": "",
            "user_viewable": 0,
            "user_editable": 1,
            "rules": "string"
        },
        {
            "name": "Steam Password",
            "description": "",
            "env_variable": "STEAM_PASS",
            "default_value": "",
            "user_viewable": 0,
            "user_editable": 1,
            "rules": "string"
        }
    ]
}

**Comment by DaneEveritt** [comment]
This is not the place to ask for help with eggs, please use Discord or the forums. But, from first glance, I'm guessing your install script isn't working correctly because it is looking for a file that doesn't exist.

**Comment by ryan1161** [comment]
I have asked multiple times in the discord but no help or response. Well having it send the command ls seems to show it installed into the correct directory.

**Comment by ryan1161** [comment]
After copying the Garrys mod install script I get this now.

![image](https://user-images.githubusercontent.com/2374149/33530666-c58a981c-d848-11e7-96fa-c9446bddf157.png)
