### ISSUE TITLE
Pterodactyl doesn't automatically set BungeeCord's port (until the first restart)

### ISSUE THREAD

**Issue by DoNotSpamPls** [pterodactyl/panel#793]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.0-beta2 (panel) 0.7.0-beta3 (daemon)
* Server's OS: Ubuntu 16.04 LTS Minimal
* Your Computer's OS & Browser: Opera 49, Windows 10 Pro x64

## Add Details Below:
When I install BungeeCord on the panel, it starts on port 25577 (the default BungeeCord port), even though I've assigned it to 25565 (or any other port)

**Comment by Headhunterzpw** [comment]
Docker forwards the 25577 port to the external IP with that port that you assigned

**Comment by DaneEveritt** [comment]
Restart the server, does that fix it? Bungeecord is super weird about setting the ports. Also are you using the Bungeecord service we shipped with the Panel?

**Comment by DoNotSpamPls** [comment]
It works after a restart, just the initial startup uses the incorrect port

**Comment by parkervcp** [comment]
I might have a fox for this. Let me work on it this weekend (Thurs-Sat) if anything it will hit me eggs repo.

**Comment by DoNotSpamPls** [comment]
@parkervcp what happened 👀

**Comment by parkervcp** [comment]
@DoNotSpamPls was busy with other things.

**Comment by arcdigital** [comment]
Looks like this was fixed in the egg update, closing.
