### ISSUE TITLE
Waterfall (Bungee fork) Causing Console To Be Unusable

### ISSUE THREAD

**Issue by GiansCode** [Pterodactyl/Panel#801]
* Panel or Daemon: Panel
* Version of Panel: 0.6.4 
* Server's OS: CentOS
* Your Computer's OS & Browser: macOS High Sierra and Google Chrome

When starting our proxy server using Waterfall, it all works. However, if we leave the server running, the console page will become non-existant/unusable until the next restart. The server will function perfectly, nonetheless.

On first start, we can use the panel just as we would and it'll all work fine (executing commands, restarting, etc), it's just if we close the tab/navigate away. We need to stop it then by executing /end in game or by suspending it.

Steps to reproduce:

- Setup normal BungeeCord server in the panel
- Change the BungeeCord JAR to that of Waterfall
- Modify the startup flags to make sure it's using all memory
`java -Xms{{SERVER_MEMORY}}M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}`
- Restart server and let it load
- Close tab and come back

At the time of writing this issue, I noticed the following in Console

> 2017-12-08 11:04:04,167 main WARN Disabling terminal, you're running in an unsupported environment.

So, I've deduced that the panel does not support Waterfall. I have tried this on 3 seperate installations on different OS' and had the same result.

So, rather than an issue, I think this is more suited as a feature request, add Waterfall support, or treat all "bungee" servers the same.

Waterfall information can be found [here](https://github.com/WaterfallMC/Waterfall/)

Thanks.

**Comment by BrainStone** [comment]
This issue is related to this: #686 

The bug can be fixed by chosing the correct log path.

In the service configuration set `Log Configuration` for Bungeecord to:

```
{
    "custom": false,
    "location": "logs/latest.log"
}
```
