### ISSUE TITLE
Upgrade to Font Awesome 5 and use it everywhere

### ISSUE THREAD

**Issue by schrej** [pterodactyl/panel#805]
We should upgrade to Font Awesome 5 because why not.

We are currently using ion icons on the node overview page. As far as i know this is the only place we use those icons and we are including a whole icon library for it. I recommend replacing those icons with similar fontawesome icons instead and removing ion icons.

* [`hdd-o`](http://fontawesome.io/icon/hdd-o/) for disk usage
* [`microchip`](http://fontawesome.io/icon/microchip/) for ram
* [`server`](http://fontawesome.io/icon/server/) for servers

**Comment by DaneEveritt** [comment]
Should we loop this in with upgrading to FA5?

**Comment by schrej** [comment]
Yes, good idea.

**Comment by DiscoveryOV** [comment]
On the topic of replacing icons, I recommend swapping `fa-download` for `fa-export` on the Egg configuration export buttons.

That, or update the language to Download over Export.

**Comment by schrej** [comment]
During the rewrite of the frontend we're switching to a different icon set, closing.
