### ISSUE TITLE
Enforce https on the node configs when the panel is using it

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#806]
As browsers won't load http resources on a https website all connected daemons will have to use https as well. We should add a warning or directly enforce using https in the node configuration when the panel has https enabled. A warning could easily be done using client-side javascript.

This might prevent some user-issues that fall in the "socket.io error" category.

**Comment by DaneEveritt** [comment]
I'll add a warning since there are cases where the node should not use SSL (proxies for example).

**Comment by DaneEveritt** [comment]
![](https://dha4w82d62smt.cloudfront.net/items/2m3o392Z3q2W342f2B0a/Image%202017-12-30%20at%2016.52.53.png?X-CloudApp-Visitor-Id=88393a862061e221af0ef8a3f3b26135&v=839de480)
