### ISSUE TITLE
Add server console shortcut on every server list on the admin panel

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#807]
In the list of associated servers on the detail page of users we have shortcuts to the console of the servers. We should add that shortcut to all server lists and also replace the link to the console on the server admin page with the same icon ([`tachometer`](http://fontawesome.io/icon/tachometer/)) for consitency.

![bildschirmfoto 2017-12-13 um 16 54 24](https://user-images.githubusercontent.com/1710904/33948253-b79a3844-e026-11e7-9b38-c9ac330232be.png)

**Comment by DaneEveritt** [comment]
We should also consider adding a second icon (or using just one) that opens the console in the popup window for very quick and dirty console management of the server rather than loading the whole page and leaving the ACP.
