### ISSUE TITLE
Cant delete Users

### ISSUE THREAD

**Issue by TheFonix** [Pterodactyl/Panel#808]
Hello, i am having an issue deleting users off of my panel, panel logs can be found here.. 
https://hastebin.com/ufoqimigev.tex

- This issue is occurring on the panel
- Latest Stable Version (0.6.4)
- Ubuntu 16.04

```
Linux PANEL-PROD 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul  7 2017 09:41:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.7-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
```

Thanks!

**Comment by DaneEveritt** [comment]
This should never happen as it appears you have a subuser referencing a server that does not exist, and the database has FK requirements on those columns.

This logic is also not present in 0.7, so I'm closing this issue currently as it is "fixed."
