### ISSUE TITLE
Pteroq starting before redis server

### ISSUE THREAD

**Issue by primaxius** [pterodactyl/panel#810]
* Panel or Daemon:  Panel
* Version of Panel/Daemon: v0.7.0-beta.2
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser:  Windows & Chrome

## Add Details Below:

Pteroq starting before redis causing it to fail before reboot.

Solution was to add `After=redis-server.service`  to the [Unit] part of  pteroq.service

**Comment by bnussman** [comment]
![8989](https://user-images.githubusercontent.com/6440455/34086354-223cc94c-e369-11e7-9163-65ab7f7ff596.PNG)

**Comment by schrej** [comment]
@bnussman No, this is only relevant for the service configuration for wings. But we could make include a note that redis needs to be running in the docs.
