### ISSUE TITLE
pteroq service should use the QUEUE_DRIVER setting.

### ISSUE THREAD

**Issue by primaxius** [Pterodactyl/Panel#811]
* Panel or Daemon:  Panel
* Version of Panel/Daemon: v0.7.0-beta.2
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser:  Windows & Chrome

## Add Details Below:
`ExecStart=/usr/bin/php /var/www/html/pterodactyl/artisan queue:work database --queue=high,standard,low --sleep=3 --tries=3`

As per the doc's it says to use this exactly however  should be

`ExecStart=/usr/bin/php /var/www/html/pterodactyl/artisan queue:work redis --queue=high,standard,low --sleep=3 --tries=3`

it should be able to detect what you have set and run with that however manually changing it to the above solved the issues.

**Comment by DaneEveritt** [comment]
Can you merge this with your other issue? I think they can go together as they're the same file that needs to be fixed.
