### ISSUE TITLE
[0.7] can not change the Google Recaptcha settings

### ISSUE THREAD

**Issue by npwfox** [Pterodactyl/Panel#813]
* Panel or Daemon: Panel
* Version of Panel/Daemon: latest develop
* Server's OS: Ubuntu 16.04 
* Your Computer's OS & Browser: Windows 10 & Chrome 

Can not change the Google Recaptcha settings. When i change form "Enable" to "Disable" and i reload is there "Enable". Same with the "Website Key" and "Secret Key" when i change and reload, its there the old one.

**Comment by DaneEveritt** [comment]
Are they updating in the DB settings table at all?

**Comment by npwfox** [comment]
Nothing is changed in the DB. There is always the same key there.

**Comment by DaneEveritt** [comment]
Try clearing the view template cache, and lets just be safe and clear the cache as well: `php artisan view:clear` and `php artisan cache:clear` should accomplish that.

**Comment by npwfox** [comment]
Okay, i think this is my fault. I installed the Panel new, but you need to change the Key from Google Recaptcha change in the mySQL otherwise you can not log in.

**Comment by DaneEveritt** [comment]
I fixed that bug in my upgrade for Laravel 5.5, theres an issue with how the config values were being set and checked later on. I am seeing a bug with things not updating, so I'll fix that as well.

**Comment by DaneEveritt** [comment]
This should be resolved now. I missed a checkbox on Google's end that allowed any domain to use the keys.
