### ISSUE TITLE
File Manager only detecting some files as editable

### ISSUE THREAD

**Issue by eddynetweb** [Pterodactyl/Panel#815]
* Panel or Daemon: Panel.
* Version of Panel/Daemon: Running canary release (commit https://github.com/Pterodactyl/Panel/commit/f9df463d323fef7e884d11f39cfb7c3c4760008f)
* Server's OS: Debian Stretch 
* Your Computer's OS & Browser: Windows 10 with Google Chrome 63

Hey, it seems there's an issue with the File Manager detecting certain files as editable while others as not. This is the case with both the same file extensions and nearly same file sizes. 

![image](https://user-images.githubusercontent.com/7884281/34075470-7574085a-e28d-11e7-959b-aef94ccce595.png)

**Comment by DaneEveritt** [comment]
This isn't really something I can fix as it is an issue with `mmmagic` detecting the wrong type of file based on the headers.
