### ISSUE TITLE
[7.0] Server Sub-User Issues.

### ISSUE THREAD

**Issue by odddellarobbia** [Pterodactyl/Panel#816]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 7.0 
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Chrome, Win 10

## Add Details Below:

Adding a sub-user to a server is non-functional, unsure about deleting a sub-user from a server. Adding a deleting sub-users/users from the panel itself is fine though.

**Comment by DaneEveritt** [comment]
Can you please clarify what the issue here is @odddellarobbia?

**Comment by MStruntze** [comment]
I'm not sure this is entirely related but after the most recent beta upgrade to 0.7.0-beta.3, creating users through the admin panel ( https://mysite.com/admin/users/new ), pressing "Create User" refreshes the page without creating anything (no apache2 errors).

**Comment by DaneEveritt** [comment]
Since there has been no follow up to this issue I am closing it. @MStruntze I cannot replicate your issue on the latest development branch, but the beta.3 release has had a bunch of issues that have been fixed subsequently.
