### ISSUE TITLE
Server created don't match server configuration startup tab

### ISSUE THREAD

**Issue by primaxius** [Pterodactyl/Panel#824]
Created a CSGO server and when I go to server management startup tab it says its a garry's mod server. see https://gyazo.com/ce6f05e4d54723a057400b52c7816f7c
---------------------

* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser:  Windows 10, Chrome

**Comment by DaneEveritt** [comment]
What version of the beta is this. “0.7” isn’t an actual version and people running the beta and reporting issues all have different versions. As far as I’m aware this is already fixed.

**Comment by primaxius** [comment]
v0.7.0-beta.2

**Comment by DaneEveritt** [comment]
This is already fixed in `develop`, for future reference I track those fixes in the [changelog](https://github.com/Pterodactyl/Panel/blob/develop/CHANGELOG.md). :)
