### ISSUE TITLE
Main Page looks messed up

### ISSUE THREAD

**Issue by cloudleek** [Pterodactyl/Panel#826]
So I tried to install pterodactyl and got stuck at https://daemon.pterodactyl.io/docs/configuration.
I have no clue how to open that panel as my main page looks really weird, I have no clue how to fix this and I dont want to break anything i will provide screenshots down below.

```
uname -a: 
Linux node2 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
php -v:
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

```
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.11.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-72-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 17.61GiB
Name: node2
ID: QLHU:YOLM:DF4B:OEXP:42OZ:MKPA:5B5R:Y43D:OHRA:X6OS:Z2V3:OKXT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
---------------------

* Panel or Daemon: Panel
* Version of Panel/Daemon: 814
* Server's OS: uBuntu 16.04
* Your Computer's OS & Browser: Windows 10 & Mozilla Firefox

## Add Details Below:
https://imgur.com/a/0suYv

**Comment by parkervcp** [comment]
Your panel is fine. You Ned to change good config to point to the public folder I the pterodactyl install folder. Your css isn't loading

**Comment by lancepioch** [comment]
You need to completely and correctly install the panel before you install the daemon.
(it doesn't look like you're experiencing any errors or bugs with the software, which is what the Github issues help address)

For help installing, join us on our Discord where we have volunteers that can help you. Please be mindful that as the holidays near, people are more and more busy though.
