### ISSUE TITLE
Problem with ? folder

### ISSUE THREAD

**Issue by Tarka-Dhal** [Pterodactyl/Panel#827]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.6.4
* Server's OS: Ubuntu 16.04.3 LTS
* Your Computer's OS & Browser: Windows 10 / Opera 49.0

## Add Details Below:
If I delete subfolder called '?' in parent folder (without quotes), it will delete parent folder too.

**Comment by lancepioch** [comment]
That directory is made by Java. It should also be safe to delete. Are you using `rm` or another method to delete?

**Comment by schrej** [comment]
I assume he is using the file manager, otherwise he probably wouldn't have added it as an issue

**Comment by DaneEveritt** [comment]
I cannot reproduce this.
