### ISSUE TITLE
Configuration Button is not working

### ISSUE THREAD

**Issue by kubo6472** [Pterodactyl/Panel#830]
* Panel or Daemon: Panel (Probably HTML error)
* Version of Panel/Daemon: Panel : 0.6.4 Daemon : 0.4.5
* Server's OS: Ubuntu Server 16.04 [Linux(x64) 4.4.0-104-generic]
* Your Computer's OS & Browser: Windows 10 Pro; Google Chrome | 63.0.3239.108 (Official Build) (64-bit) (cohort: Stable)
## Add Details Below:
Clicking on Configuration should open up dropdown menu as I remember, but it only redirects to /#
![image](https://user-images.githubusercontent.com/26146502/34361286-e8e60d14-ea68-11e7-84ee-9c01493f2d99.png)
I need that to get database password. I reinstalled the panel at least three times cause of errors. Of course I reinstalled OS too. (By formatting drive so nothing should be wrong) I don´t know if I only made some installation error, but terminal does not thrown any errors on me. So I think error is somewhere else. Please fix.

**Comment by schrej** [comment]
This should work. Make sure there are no errors related to the javascript not getting loaded.

**Comment by DaneEveritt** [comment]
I've never heard of anyone else having this issue on the stable build and the information provided leads me to believe it is an issue with your browser caching something wrongly, or you're using a plugin that is blocking JS from being executed.
