### ISSUE TITLE
Nest Configuration Not Populating

### ISSUE THREAD

**Issue by Exonical** [Pterodactyl/Panel#831]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.2
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 / Google Chrome

## Add Details Below:
When creating a server, Under Nest Configuration, "Eggs, Docker Image and Startup Command" isn't populated. Server therefore cannot be created.
![661d533b184f2b52712726b3ade4caea](https://user-images.githubusercontent.com/22120706/34362819-c63789a6-ea44-11e7-8506-74f1870faeec.png)

**Comment by DaneEveritt** [comment]
The panel version you have listed does not exist.

**Comment by Exonical** [comment]
Version was type incorrectly, issue updated.

**Comment by Exonical** [comment]
This my personal fault - issue with Browser and or Browser Cache was discovered.
