### ISSUE TITLE
Allow server owners to reset/reinstall server

### ISSUE THREAD

**Issue by HexDevv** [pterodactyl/panel#832]
Users should be allowed to reset their server, without an admin doing it for them.

**Comment by Yomanz** [comment]
This is something that could be made if you know what your are doing.

**Comment by schrej** [comment]
This would also enable automatic version switching for users by using a version variable that the user can modify (as in the Vanilla Minecraft egg for example).
`P: High` as this is a very frequently requested feature.

**Comment by Sergzy** [comment]
While you are at it, please also put Pack selector somewhere around as it is currently missing from user side. Admin side of the panel evidences that user's are supposed to be able to access Pack selection, since permissions such as selectable, visible and locked are already implemented.

**Comment by schrej** [comment]
Can you please stop spamming that below every issue here? @Sergzy

**Comment by ayan4m1** [comment]
We would likely need to add an item under the "Configuration" dropdown, which needs a new route and view. There we can take the existing admin UI code - by "reset/reinstall" do you mean "rebuild/reinstall" or just "reinstall"? That determines what elements to pull from the admin manage view. Also, these elements would have to be disabled if `server.installed === 2`. Then, we need non-admin routes to handle verifying that the user in question is in fact the server owner and then performing one of the two actions we could be talking about.

**Comment by Sir3lit** [comment]
This would be added with https://github.com/pterodactyl/panel/pull/1516

**Comment by Sir3lit** [comment]
This is currently added in 0.8

https://discordapp.com/channels/122900397965705216/418956651346001921/695750714357579796
