### ISSUE TITLE
Request: Ability to organize servers order

### ISSUE THREAD

**Issue by ThienNTran73** [Pterodactyl/Panel#834]
Hi, 
I have noticed this when I was using pterodactyl is that there is no way to organize the orders of server. 
It would be really awesome if you guys could make it so that we can organize the servers, either my manually arranging them or sorting them using names/ram usage/services, etc.
This idea is also upvoted on Discord so I hope you guys would consider it!
https://imgur.com/a/F0wmg

**Comment by DaneEveritt** [comment]
Duplicate #498
