### ISSUE TITLE
Custom Logging by Default

### ISSUE THREAD

**Issue by tenten8401** [Pterodactyl/Panel#835]
Could we have custom logging by default on all services?

Advantages:

- Colors don't explode all over the place when refreshing
- Logs don't differ when refreshing
- Online detection regardless of whether it's printed to logs or not (I see minecraft servers failing a lot here)

**Comment by parkervcp** [comment]
You want to explain what custom logging is?

**Comment by tenten8401** [comment]
custom: true in the logging properties of a service.
Having the daemon do the logs instead of the games, since they may differ from console output

**Comment by DaneEveritt** [comment]
No. That doubles the amount of space being used for log storage, and puts additional unnecessary IO and memory pressure on the daemon.

It is up to the person making an egg to determine if they need to use custom logging or not.

**Comment by tenten8401** [comment]
Perhaps have a limited 1000 line log?

I really think the IO and memory trade-offs are worth not having logs explode in color codes or completely differ from what I was just looking at before I pressed F5, most of the time both of which happen & it's annoying as hell.

Or, we could just use the non-custom log for console output, which would also be a solution that I've seen some other panels use.

**Comment by schrej** [comment]
Just manually set it to custom logging whenever it explodes with color codes. Because if we turn it on by default we can just remove the switch all together because noone is ever going to touch it.

**Comment by tenten8401** [comment]
Okay, so I've done some testing and cannot really see a huge performance impact at all...
I've created 10 servers on a VPS on the latest beta, all running a simple golang program through the minecraft container (didn't know what else to use) that prints 5 timestamps per second.
![image](https://user-images.githubusercontent.com/6174343/34642630-4f03f89e-f2e4-11e7-9608-7ece4c921dd8.png)
![image](https://user-images.githubusercontent.com/6174343/34642718-d7fc5b86-f2e5-11e7-8383-0c33927ec5d5.png)
Go Script: [timer.tar.gz](https://github.com/Pterodactyl/Panel/files/1609080/timer.tar.gz)

I simply converted the go script to a binary with go install, set the startup command to run `./logger` on the minecraft container, and began my testing.

I observed almost no disk I/O at all with `custom: false`:
![no_custom](https://user-images.githubusercontent.com/6174343/34642674-0cf397d8-f2e5-11e7-9ca5-965e54167f90.gif)

I observed some occasional I/O with `custom: true`:
![custom](https://user-images.githubusercontent.com/6174343/34642687-483be4c6-f2e5-11e7-99c5-c08286ba13af.gif)

I personally don't see this as a real performance impact that would be noticed at all, and do think we should potentially just remove the custom option altogether as @schrej suggested, along with potentially storing server logs in `/srv/daemon/servers`, that way it doesn't interfere with any files we have in the server directory.
If you see any flaws in my testing methodology, please let me know.

**Comment by DaneEveritt** [comment]
So this has been implemented into the daemon. I'm leaving the logging stuff in the eggs for now, but it will be removed down the road since it does nothing currently.
