### ISSUE TITLE
Descriptions being left empty

### ISSUE THREAD

**Issue by Yomanz** [Pterodactyl/Panel#842]
--------

* Panel
* Version of Panel: Latest Beta.3
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Firefox win10 64x

## Add Details Below:
From what I gathered regarding the whoops error it seems that we can't leave the description blank upon making a new server.

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'description' cannot be null (SQL: insert into `servers` (`uuid`, `uuidShort`, `node_id`, `name`, `description`, `skip_scripts`, `suspended`, `owner_id`, `memory`, `swap`, `disk`, `io`, `cpu`, `oom_disabled`, `allocation_id`, `nest_id`, `egg_id`, `pack_id`, `startup`, `image`, `updated_at`, `created_at`) values (fdfabcd4-9073-4307-a35e-cc9df7c72c20, 4fkBE0mT, 1, Meincraft, , 0, 0, 1, 0, 0, 0, 500, 0, 1, 2, 1, 1, , java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}, quay.io/pterodactyl/core:java, 2017-12-31 14:15:15, 2017-12-31 14:15:15))

https://aaa.daleaave.me/u/c22aa4.png

**Comment by DaneEveritt** [comment]
Can you try this using the latest development branch please? There was a commit that should have fixed this across the Panel.

**Comment by Yomanz** [comment]
The error persists
