### ISSUE TITLE
Can't create user.

### ISSUE THREAD

**Issue by Yomanz** [Pterodactyl/Panel#846]
---------------------

* Panel: 
* Version of Panel: develop
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Firefox Win10 64x

## Add Details Below:

https://aaa.daleaave.me/u/66d7bc.png

**Comment by DaneEveritt** [comment]
I really need you to provide more information than just a picture of the exception please. I have no idea what flow you used to reach this point, and therefore the testing I've done is unable to reproduce this issue.

**Comment by yomanz51** [comment]
I tried to make an admin account via the panel which is what gave me that error. I also tried to create a user with the same command only to have an error which reflects the same information.

**Comment by DaneEveritt** [comment]
closed in https://github.com/Pterodactyl/Panel/commit/4457634127180bbfdfbaf99a0c9cb2fadfb5ce7b
