### ISSUE TITLE
Rust Server Creation

### ISSUE THREAD

**Issue by Tyler-Burr** [Pterodactyl/Panel#847]
* Panel or Daemon: Panel
* Version of Panel/Daemon: canary
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Google Chrome

## Add Details Below:

When creating a source engine or Rust server after you click "Create Server" the fields reset and the page refreshes

**Comment by parkervcp** [comment]
Are you absolutely sure you have filled out all information you need on this? I know the setup pages it annoying due to that.

**Comment by Tyler-Burr** [comment]
I am 100% sure

**Comment by DaneEveritt** [comment]
I found the problem causing this issue by the way, not sure exactly why you closed it. I'm aware of the problem and working to fix it. Seems there is a validation exception that doesn't get caught, and since its a validation exception it also doesn't get logged.

**Comment by Tyler-Burr** [comment]
Sorry i just closed the ticket because i managed to get the server to create.

**Comment by DaneEveritt** [comment]
This should be fixed and working correctly now.
