### ISSUE TITLE
Toggle Schedule 

### ISSUE THREAD

**Issue by Tyler-Burr** [Pterodactyl/Panel#848]
* Panel or Daemon: Panel
* Version of Panel/Daemon: canary
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Google Chrome

![bug](https://user-images.githubusercontent.com/33735005/34503995-f6f6a556-efd8-11e7-9e74-cc428a6ed627.PNG)

**Comment by DaneEveritt** [comment]
closed in 036bea2
