### ISSUE TITLE
See console while installing

### ISSUE THREAD

**Issue by schrej** [pterodactyl/panel#851]
There should be a way for panel admins to see the install process and the log output that comes with it. Maybe allow admins to access all servers, even when they are not installed yet but show a banner at the top indicating it's still installing. Then we can show the install output in the normal console window.

**Comment by Yomanz** [comment]
Would be a nice feature because at the moment we have to SSH into the server running the daemon and cat the file.

**Comment by matthewpi** [comment]
This was implemented in https://github.com/pterodactyl/wings/commit/c6fcd8cabbf67c2abc2ddf6d548ee71ac31771b1 a long time ago.
