### ISSUE TITLE
Cant download files via file manager

### ISSUE THREAD

**Issue by Yomanz** [Pterodactyl/Panel#854]
---------------------

* Panel
* Version of Panel: develop
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Firefox win10 64x

## Add Details Below:
Doesn't seem to matter what type of file
When you click download it instantly errors using the file  #manager: 

 BadMethodCallException
This cache store does not support tagging.

https://aaa.daleaave.me/u/7290ef.png

**Comment by DaneEveritt** [comment]
You need to use either redis or memcache as the cache store.
