### ISSUE TITLE
Text editor seem to dont' work correct with chrome browser of android

### ISSUE THREAD

**Issue by xion87** [pterodactyl/panel#855]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.64
* Server's OS:  Ubuntu16.04.2 LTS 
* Your Computer's OS & Browser:  Android 6.0.1 and Chrome 63.0.3239.111

## Add Details Below:

I am using the latest release of panel and daemon.
The issue is when i connect to file manager from android chrome, and try to edit some yml editor, it keep to replace the worlds and going back like i am using back-delete. I think is related to yml color viewer

**Comment by parkervcp** [comment]
Can you get us exact version numbers please? We have a beta and the current stable released.

**Comment by xion87** [comment]
i am using stable build  0.6.4

**Comment by DaneEveritt** [comment]
All of that information in the issue template that you ignored is needed, so I need you to provide it.

**Comment by xion87** [comment]
Updated the info

**Comment by DaneEveritt** [comment]
I'm not planning to address this as I have no Android device to test with and it really comes down to the dependency we are using.
