### ISSUE TITLE
Can't create Nests anymore on Fresh install

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#859]
* Version of Panel: d1806d9d 
* Server's OS: Windows 10 
* Your Computer's OS & Browser:  FFDE 58.0b14 (64-Bit)

I am unable to create a nest:
![](https://image.prntscr.com/image/JzSNDMeCQeaEvWiTu_f71g.png)
it says:
There was an error with one or more fields in the request.

    The author must be a valid email address.

**Comment by arcdigital** [comment]
Did you run `p:environment:setup` and set your author to a valid email address? If you ran the setup command already, you should be able to find it in your .env file under `APP_SERVICE_AUTHOR`.

**Comment by DaneEveritt** [comment]
This is an issue with the environment setup as mentioned by @arcdigital
