### ISSUE TITLE
Invalid server URL causes error.

### ISSUE THREAD

**Issue by victionn** [Pterodactyl/Panel#860]
Place: Panel
Panel: develop // Daemon: develop
OS: Ubuntu 16.04 

## Add Details Below:

When navigating to a invalid server via its ID, such as the url being: PanelURL/server/woahidhere

It returns an error: https://image.viction.co.uk/CRqLJ rather than just returning the 404 screen like it does on the stable version of pterodactyl.

**Comment by arcdigital** [comment]
This is because you have debug mode turned on in your .env file (APP_DEBUG)
