### ISSUE TITLE
SFTP Service Stopping

### ISSUE THREAD

**Issue by xtechgamer735** [Pterodactyl/Panel#862]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.4.5
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Safari

*Docker Info: https://hastebin.com/inujowusag.go

Hello!

I have this issue that the SFTP service randomly stops accepting connections, I have to restart the daemon to re enable this. I am unable to find any errors except this in the wings.log which happens a few times, Im un sure whether this is related. 

`{"name":"wings","hostname":"subzeronetwork.net","pid":14034,"level":60,"err":{"message":"Cannot read property 'length' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'length' of undefined\n    at Timeout.process [as _onTimeout] (/srv/daemon/src/controllers/server.js:491:86)\n    at ontimeout (timers.js:479:15)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)"},"msg":"A fatal error occured during an operation.","time":"2018-01-08T20:50:06.132Z","v":0}`

I am, however, having an issue where servers have to be killed rather than stopped, and sometimes not even that works so again I have to restart daemon or manually kill via docker (which doesn't always work) so could it be related to that?

Many thanks!

**Comment by vipesz** [comment]
A easy fix for this is to remove the SFTP container and recreate it. I don't really know why this occurs...iirc, it's to do with the server name.

**Comment by schrej** [comment]
As we have SFTP integrated in the daemon with 0.7/0.5 this will be resolved when that gets released (there is no date). In the meantime try to fully remove the sftp container and restart the daemon afterwards.
That error you posted is related to reading the cpu usage of the docker container, not sure what's causing that. Is docker up to date on your system?

**Comment by DaneEveritt** [comment]
I'm going to close this because SFTP issues have been addressed in the next release, and theres no much we can currently do about the existing system acting up on users systems. As mentioned above, the easiest quick-fix is to stop the daemon, remove the scrappy SFTP container, and then start the daemon and let it re-create the instance.

The other error is unrelated and doesn't cause any problems using the Panel or SFTP.
