### ISSUE TITLE
From "New File": The immediate parent folder is visible in the text area

### ISSUE THREAD

**Issue by FerusGrim** [Pterodactyl/Panel#865]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.6.4 - Newest Beta 
* Server's OS: Ubuntu 16.0.4, but likely unrelated.
* Your Computer's OS & Browser: Windows 10/Chrome, but likely unrelated.

## Add Details Below:

As you can see from [this screenshot](https://i.imgur.com/CS2gxdO.png), the immediate parent folder is modifiable from the text area, which doesn't particularly make sense. It seems as though the desired state would to have it be with the rest of the folder path.

**Comment by lancepioch** [comment]
This is intended behavior in order to allow users to specify a separate directory if desired.

**Comment by FerusGrim** [comment]
I can live with this. It was really just the other one that gets to me - this was just something along the same vein.
