### ISSUE TITLE
Editing a sub-option that have feature "copy config from" it mess the configuration

### ISSUE THREAD

**Issue by xion87** [Pterodactyl/Panel#866]
-     Panel or Daemon: Panel/Daemon
-     Version of Panel/Daemon: 0.64
-     Server's OS: Ubuntu16.04.2 LTS
-     Your Computer's OS & Browser: Windows 10 and Firefox

**Add Details Below:**
I am using the latest stable release of panel and daemon.
The issue if i create some new suboption and use the "Copy Settings From" and editing the script or some edit, and restarting the daemon, it seem to don't "read" the copied setitng and read instead the current configuration (empy).
Using "none" in "copy config" and copy manually the settings, it fix the issue.
For example here in the logs stopped to recognize "start status" (copy settings by vanilla minecraft server service):

**Panel logs:**
https://hastebin.com/ipexanumog.tex
https://hastebin.com/lejilicunu.tex

**Daemon logs fresh restarted:**
https://hastebin.com/lujanehuqi.json

**Comment by DaneEveritt** [comment]
I'm not seeing any issues here. That is probably just a confusing UI issue. It does not auto-populate those fields with the values from the copied setting, but in the background it is happening.
