### ISSUE TITLE
my minecraft server automatically killed

### ISSUE THREAD

**Issue by Agrain** [Pterodactyl/Panel#868]
its has been 2 weeks iam using pterodactyl panels, which mean i have an issues to tell, (sry for my english).

my minecraft server has been often automatically stopped by itself, the issues is.

>/entrypoint.sh: line 15: 28 Killed java -Xms1024M -Xmx1024M -jar spigot.jar
(Daemon) Server marked as OFF
(Daemon) Server detected as crashed! Attempting to reboot server now.

pls anyone help me with this error.

**Comment by DaneEveritt** [comment]
You're likely running out of memory because you're not allocating the proper amount of resources to the server. This is not a bug with the panel.
