### ISSUE TITLE
xhr poll error

### ISSUE THREAD

**Issue by Untuned** [Pterodactyl/Panel#869]
Please describe your issue in full below. Include what products are affected, as well as what version(s) you are running. Please also include information about your system, such as `uname -a` and `php -v` and `docker info` if applicable.

If you're just making a suggestion, be descriptive, and link to any issues that might be releated as well.

You can delete from this line up.
---------------------

* Panel or Daemon: Both? If not then the daemon.
* Version of Panel/Daemon: 0.6.4/0.4.5
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10, Google Chrome.

## Add Details Below:

There was an error attempting to establish a WebSocket connection to the Daemon. This panel will not work as expected.  Error: xhr poll error

Screenshot of my node configuration:

![](https://i.imgur.com/4B5kQiu.png)

Screenshot of the daemon core.js file:

![](https://i.imgur.com/BdLVbqd.png)

**Comment by parkervcp** [comment]
The following command should get the logs we want for this issue.

`cd /srv/daemon/ && npm run diagnostics`

**Comment by DaneEveritt** [comment]
This is not a bug with this software specifically.

https://guides.pterodactyl.io/docs/debugging-transferexception-and-socketio-issues
