### ISSUE TITLE
Add API Feature to Callback Server ID

### ISSUE THREAD

**Issue by vipesz** [pterodactyl/panel#873]
- [x] Add a API feature to easily callback the server ID of a service created via WHMCS for easy management.
- [x] Add API feature to callback server IP address (primary allocation)
- [x] Another API feature I would find to be very useful is a overhaul of the auto deployment system to define a certain port range of available allocations on the node to be used with auto deployment. 
- [x] Ability to auto deploy more then one allocation with two different ranges.

Example: I have ports 25565-25700 available, along with 8000-8200 - enable a feature to only allow 25565-25700 be provisioned.

- [x] Ability to have the panel predetermine the IP address (via the FDQN) and allocate predefined ports.

If google.com resolves to 8.8.8.8, the panel would automatically add the allocation 8.8.8.8 with ports predefined in the admin panel.

**Comment by DaneEveritt** [comment]
The third bullet is completed, the fourth probably won't happen until more changes are made to the auto-deploy system. Can you clarify what you mean by the first two things.

For the auto-deployment things, please create a new issue so we can have one thing specifically tied to auto-deployments since this issue is trying to do two things.

**Comment by vipesz** [comment]
> The third bullet is completed, the fourth probably won't happen until more changes are made to the auto-deploy system. Can you clarify what you mean by the first two things.

_Add an API feature to callback the server IP address (Primary Allocation)_

Example:
Server A has two allocations.
Primary Allocation - 8.8.8.8:25565
Secondary Allocation 8.8.8.8:8020

Have the API feature search the allocations, determine the primary allocation, and call back that allocation along with the server IP address to be used in a WHMCS module. 

Allocation being port, the IP being the IP address.

_Add a API feature to easily callback the server ID of a service created via WHMCS for easy management_

For an example, if a user under the email address admin@google.com **owns** 2 or more servers, it can in the current state become rather tedious to narrow down a individual service created via WHMCS

To resolve this, having a API feature to callback the server ID alot like is said above would give the unique identifier for each server. 

Example:

admin@google.com **owns**
AAAAA - Server 1
BBBBB - Server 2
CCCCC - Server 3

A api feature incorporated to read and print these back for each server -- so, i would query for admin@google.com for the servers he owns, and instead of printing everything, it would just come back with those IDs.

**Comment by DaneEveritt** [comment]
Your callback for users can be done by hitting the users API and including the servers.

`GET /api/application/users/<id>?include=servers`

**Comment by DaneEveritt** [comment]
Closing this out, I believe everything is already accounted for based on the checkboxes. Servers can be looked up using external IDs, allocations can be retrieved using the `?include=allocations` flag on most endpoints.
