### ISSUE TITLE
[BUG] Startup parameters not editable

### ISSUE THREAD

**Issue by JanDevDE** [Pterodactyl/Panel#877]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.6.4
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 / Google Chrome

## Details:

It is not possible to edit the startup command of a server as user / as administrator. (Tested only in source engine games.) However, you can edit it in the admin panel under the "Startup" tab.

(The screenshot was taken with the root administrator user.)

![capture](https://user-images.githubusercontent.com/11154004/34921086-b2467c2a-f97d-11e7-8fca-29f49bcb2557.JPG)

**Comment by JanDevDE** [comment]
(Not a bug, you cannot edit the startup command in the front-end.)

**Comment by kaganus** [comment]
navigate to Services in admin panel and find the service variables, you can set if its editable by users for all variables. these variables you send the screenshot of are markes as non-editable as it means changing the game the server is hosting, which should be made by an admin only in ideal circumstances
