### ISSUE TITLE
Ram changing error

### ISSUE THREAD

**Issue by Alisdair-Cunningham** [Pterodactyl/Panel#879]
* Panel or Daemon: Panel (I'm not sure if it's also a Daemon problem)
* Version of Panel/Daemon: Panel 0.6.4 @ Daemon 0.4.5 (if needed)
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 and Chrome

## Add Details Below:
While editing a servers configuration to up the Ram that the server was allowed to use I noticed the writing below the input box say "Setting this to 0 will allow unlimited memory in a container." I attempted to do so and clicked "Update Build Configuration." The value however did not change once the page had refreshed and the server was still running with the original value of Ram.

Before editing the value:
![value 1](https://user-images.githubusercontent.com/15881211/35033446-cb0b76be-fbbe-11e7-9698-9d6b63d47ee1.PNG)

Before attempting hitting the "Update Build Configuration" value:
![value 2](https://user-images.githubusercontent.com/15881211/35033447-cb69f914-fbbe-11e7-96ab-e71db24337b2.PNG)

Final output:
![value 3](https://user-images.githubusercontent.com/15881211/35033488-f44ac192-fbbe-11e7-8429-36bbec07d837.PNG)

**Comment by DaneEveritt** [comment]
This is already fixed in the beta releases, but thank you for reporting it.
