### ISSUE TITLE
Symfony Problem with command "php artisan pterodactyl:env"

### ISSUE THREAD

**Issue by H4nSolo** [Pterodactyl/Panel#880]
* Panel or Daemon: Latest release Version from Github [v0.7.0-beta.4]
* Version of Panel/Daemon: v0.7.0-beta.4
* Server's OS: Uuntu 16.04 LTS with Apache2.4 PHP7.1
* Your Computer's OS & Browser: 

## Add Details Below:

I want to install the webpanel but after i want to run the step "php artisan pterodactyl:env"
i´get a red Box in putty with the Message:

>   [Symfony\Component\Console\Exception\CommandNotFoundException]
>   There are no commands defined in the "pterodactyl" namespace.

How can i fix them?

**Comment by lancepioch** [comment]
The commands have been shortened to `php artisan p:env`

Run `php artisan` to see all the new syntax for the new commands in the beta.
