### ISSUE TITLE
Editing Nests: Lavarel Validation fails while editing Variables

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#881]
I edit egg variables through the Admin panel (https://example.com/admin/nests/egg/1/variables)
![](https://image.prntscr.com/image/4wLaSprMTtWFntWDc9TYpQ.png)
If I try to save the following variable with no Lavarel rules and an empty default variable field then:
![](https://image.prntscr.com/image/0JmgcRoJT1yIRF9Y05_x9A.png)

If I try the same but with nullable as a Lavarel rule:
![](https://image.prntscr.com/image/JiywcTuVSTW2BvyNUgdzYg.png)
I will get following error:
![](https://image.prntscr.com/image/CYmh63CvSpiZWgTLeLl4ew.png)

Nullable and empty lavarel settings are not working.
I just wanted to have the following sweet lavarel rule but only if the variable is not empty:
![](https://image.prntscr.com/image/J78d8iSPTsykWM5IYhvXdg.png)

# ALSO
## There should be only 1 save button for all Variables. Its more Time saving
---
* Panel: 0ec5a4e0
* Server's OS: Windows 10
* Your Computer's OS & Browser: FFDE

**Comment by ProJaCore** [comment]
notice: This is reproducible with a fresh install.

**Comment by DaneEveritt** [comment]
closed in 2212f28

Rules are always required for a field, the default is not required though (unless your rules state that a value is required).
