### ISSUE TITLE
Zip bomb protection

### ISSUE THREAD

**Issue by stanjg** [pterodactyl/panel#883]
**Problem**
I noticed pterodactyl does not take any steps to prevent a zip bomb attack, this might cause serious trouble for some people.

**Possible Solution**
Pterodactyl unzips zip files using 'unzip', unzip has a feature to list all files along with their uncompressed size. 
Command: `unzip -l file.zip`, the final line of the output contains the total uncompressed size.

I think it would be possible to get the total uncompressed size and check it against the total available storage on the specific server, then abort if it's bigger than allowed.

**Comment by lancepioch** [comment]
Isn't the Docker instance already setup with the disk space constraint?

**Comment by parkervcp** [comment]
No. It's checked with du on startup

**Comment by DaneEveritt** [comment]
This command is also running outside of the docker instances @lancepioch

**Comment by Sergzy** [comment]
Was just wondering, is there a special reason why the space is not limited with docker's native function? Because in current case, there are also other ways to achieve the "bomb" effect, not only unzip function.

**Comment by BrainP4in** [comment]
Is this still a thing, or have I missed something?

**Comment by DaneEveritt** [comment]
If it is still open it isn't dealt with.

**Comment by BrainP4in** [comment]
Okay, i will take a look at it the next view days.
