### ISSUE TITLE
[Beta] Sub User Panel Issue

### ISSUE THREAD

**Issue by xtechgamer735** [Pterodactyl/Panel#885]
* Panel or Daemon: Panel
* Version of Panel/Daemon: Panel 0.7.0-beta.4, Daemon 0.5.0-beta.5
* Server's OS: Ubuntu 16.04 Xenian Xerus
* Your Computer's OS & Browser: macOS 10.13.2 / Safari 11.0.2

## Add Details Below:

Following stack trace appears when sub users try to access a server they have been assigned to:
https://hastebin.com/adotogasas.tex

They are able to view them in the list but the Laravel error page shows when they try to load the console view.

**Comment by DaneEveritt** [comment]
I believe this was fixed in 62fd299
