### ISSUE TITLE
Creating a server with an invalid field resets the service- and start configuration

### ISSUE THREAD

**Issue by hugil** [pterodactyl/panel#889]
---------------------

* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.6.4
* Server's OS:  CentOS Linux 7 (4.13.13)
* Your Computer's OS & Browser: Windows 10, Google Chrome

## Add Details Below:
Just installed a clean 0.6.4 pterodactyl panel on a Centos 7 KVM Virtual machine right from the docs guide.

I was creating a server and filling in all the input in the form such as Name, Allocation etc.
Once I clicked create it said I had an invalid field and it reset everything below Service Configuration. This means you have to input everything again.

For an optimal and consistent experience it should be retained and saved just like the other input above Service Configuration..

Thanks for taking time looking into this.

**Comment by DaneEveritt** [comment]
This is a known issue that I believe has come up a few times before. Unfortunately right now the code on that page is a, uh, disaster and makes it very difficult to set those values back correctly. I agree though, it sucks when that happens. I hope to address down the road with significantly better JS and error handling.

**Comment by DaneEveritt** [comment]
Closed in #1909
