### ISSUE TITLE
Toggle Reinstall doesn't work

### ISSUE THREAD

**Issue by Exonical** [Pterodactyl/Panel#891]
* Panel or Daemon: Panel
* Version of Panel/Daemon: canary (Beta pulled from git as of 1/21)
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 / Firefox

## Add Details Below:
When I toggle the reinstall of a server, it doesn't actually reinstall. The status of the server stays the same instead of going to the 'Installing' status.

GIF
https://gyazo.com/a9fdbc621baae2d7541cac1fb7f2fedf

**Comment by DaneEveritt** [comment]
Does it actually reinstall on the daemon though (specifically, is this just a UI bug)?
