### ISSUE TITLE
Remove function for own User

### ISSUE THREAD

**Issue by MadddinTribleD** [Pterodactyl/Panel#893]
There should be a way to disable/remove your own account.
Currently you can only remove an account as an admin.
You cann't remove your own account.

Would appreciate it if this would be implemented.

**Comment by DaneEveritt** [comment]
What is the reasoning for wanting to remove your own account?

**Comment by MadddinTribleD** [comment]
Could be anything.
Could have got in trouble with the team.
Set up a server for a person so u got an account there and don't need it anymore. 
Didn't do anything for a long time so you figured out you want to delete it.
You get used as a ownere for multiple servers so you always get the 'server created' mail

**Comment by schrej** [comment]
What should we do with assigned servers? Reassign them to a random admin? To nobody (admins can still access them)? Or delete them along with the account?

**Comment by parkervcp** [comment]
If you got in trouble with the team why are you removing/disabling your own account... An owner can edit and remove their sub-users. That person should be the one who manages that.

The permissions also let you tune if a sub-user can edit or modify other users.

**Comment by DaneEveritt** [comment]
@schrej it would not let you delete your account if that was the case.

**Comment by MadddinTribleD** [comment]
@schrej GitLab moves the projects a user has to an `Ghost User`. So thei can still be interacted with or even moved to one later but history ist still functional.    

@parkervcp its not about sub-user its about user in general. In like every website/service/anything i can delete my own account. It should not be the responsability of someone else do delete my stuff for me.

**Comment by parkervcp** [comment]
Generally speaking the users are managed by a billing system and a user that has their own api key. You can't create your own user there is no reason to be able to delete your own user.

**Comment by DaneEveritt** [comment]
I will not be implementing this at this time. Accounts on the Panel are often linked to external services and allowing the user to delete them through the Panel could result in integrity issues with those services.

This is something that can easily be implemented as a custom addon, or implemented into an external service such as WHMCS.
