### ISSUE TITLE
Connection issues caused by Pterodactyl

### ISSUE THREAD

**Issue by bajansam** [Pterodactyl/Panel#894]
* Panel or Daemon: Pterodactyl
* Version of Panel/Daemon: 0.6.4
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Mac OS High Sierra - Chrome/Safari

## Add Details Below:

I have set up the server in Pterodactyl, and at first glance, it runs absolutely perfectly! However, some players (including myself) regularly have issues when trying to connect to the minecraft server. (play.brutal.network) When connecting it will load the player into the game for a *split* second, and then kick then out again with the error: 'Internal Exception: java.io.IOEception: Connection reset by peer’ http://prntscr.com/i5rc0l

At first i thought it may be bad plugins, outdated or something causing it, so removed all plugins, still happened. Then i thought it may be an issue with Spigot, so i ran a clean install of the latest spigot, yet the error still happened. There is no errors in console what so ever. 

Then after a day or so i realised the issue only started when we started using Pterodactyl. So i tried moving the entire server (plugins and all) to the root directory and using a start script and running from there. Hey presto! It worked!

This has narrowed the error down to Pterodactyl.

So, i got Pterodactyl completely uninstalled, then reinstalled. Set up the server etc all over again, and bam. The issue is still there.

Please help me here! I dont want to go back to multicraft...

**Comment by Zort3x** [comment]
Yeah, no this is not a pterodactyl error, if anything it's the machine you set it up on or anything else that would give connection issues

**Comment by lancepioch** [comment]
This isn't enough unique detail to go on. Please at least provide the full context for the errors you're receiving in MC.

**Comment by schrej** [comment]
Also please provide your docker version and your OS (including version)

**Comment by DaneEveritt** [comment]
Closing due to lack of information.
