### ISSUE TITLE
Compress entire server

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#897]
* Panel or Daemon: Panel 

As the title states. Have a way to compress the entire server.

Add a button to compress the whole server. An extension on the compress feature for folders.  
![image](https://user-images.githubusercontent.com/1207679/35463566-469aba4a-02bf-11e8-8721-63f9bc2eca8d.png)

**Comment by ShadowKitten** [comment]
Wouldn't a better place for this compress action be under "Mass Actions" allowing you to select some or all folders on a server to be compressed into a single file?

**Comment by DaneEveritt** [comment]
I think this would be better handled as part of the backup system.
