### ISSUE TITLE
Ark server not starting

### ISSUE THREAD

**Issue by exwizzard** [Pterodactyl/Panel#899]
With a fresh install of the pterodactyl panel version 0.6 the ark server is stuck on installing.
With a fresh install of pterodactly beta version the ark server will install but unable to start, its stuck on "starting" and here is the console output:

```
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 7148M / 10000M
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server container started. Attaching...
[Pterodactyl Daemon] Attached to server container.
4.5.1-0+UE4 7038 3077 403 9
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
```
---------------------

* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7 / 0.5 beta 5
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: windows 10 & firefox

## Add Details Below:
```
Linux ubuntu 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep 29 2017 17:04:25) ( NTS )
```

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-97-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.533GiB
Name: ubuntu
ID: LKPP:2J7W:75HR:FWO3:B3FJ:OC7J:ZAHX:CX7D:WXVN:ZAMD:KT27:SEB2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by lancepioch** [comment]
Where does it say it hasn't started or is still starting?

**Comment by exwizzard** [comment]
On the server page:

https://i.imgur.com/fSVS3fm.png

**Comment by lancepioch** [comment]
It looks like the server is running but it didn't post back to the panel. Can you post the daemon logs, I suspect that there's an error there regarding this.

**Comment by exwizzard** [comment]
Here are the logs:

https://hastebin.com/kegiqaruko

**Comment by DaneEveritt** [comment]
This isn't a bug with the software, but rather an issue with the egg where the line it is looking for to determine if the server is started is not output.

**Comment by lancepioch** [comment]
For your daemon you've got the panel configured as: http://198.50.189.232 which doesn't load and is your current issue.

**Comment by exwizzard** [comment]
@lancepioch The daemon and panel work fine, that's just an old line on the top of the log if you are referring to that, the only issue is the ark egg that comes by default with the panel.

**Comment by WintopPVP** [comment]
i have a save problem . how to sovle this problem. thank you very mach!

**Comment by KasperFranz** [comment]
You should make a new threaad or ask on discord

**Comment by exwizzard** [comment]
@WintopPVP You cant solve the problem, even if you start ark without the panel it will behave the same way, the people who made this egg need to write in some other way to check if the server is online like a query tool.

**Comment by WintopPVP** [comment]
thank you for answering me ，did you sovle this provblem？only wait for developer ？
