### ISSUE TITLE
Wrong error highlighting of overallocate fields on Node creation

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#90]
This should be self explanatory. Happened while trying to add a new node.
<img width="710" alt="bildschirmfoto 2016-09-25 um 23 25 24" src="https://cloud.githubusercontent.com/assets/1710904/18818679/7f4664d4-8377-11e6-8acb-40ed7687ff64.png">
<img width="709" alt="bildschirmfoto 2016-09-25 um 23 25 30" src="https://cloud.githubusercontent.com/assets/1710904/18818680/7f52f528-8377-11e6-83ff-a3fc7597f327.png">
(Derp: i filled the fields before taking the screenshots, were empty when i clicked Create Node, sorry.)

**Comment by DaneEveritt** [comment]
So if I am understanding this correctly you didn't enter anything into the over-allocation fields, it  produced an error as expected, but the only issue here is that it highlighted the wrong fields?

Thanks for the bug report, let me know if I got that wrong. I'll probably set those fields to default to 0 on the view. Expect some changes to creation as well as we move forward for better API support (so more default stuff that you don't necessarily have to enter on creation).

**Comment by schrej** [comment]
Yes you got that right. Default value would be even better. Usually one would enter 0 anyways i guess.
