### ISSUE TITLE
Add server resource utilization to the API

### ISSUE THREAD

**Issue by ronaldreagan4prez** [pterodactyl/panel#900]
It would be really useful for billing and logging systems to have access to resource utilization of each game server via the API.  CPU, memory, disk, and potentially database utilization would be really useful to have exposed via the API.

**Comment by DaneEveritt** [comment]
Will be out in the next release cycle for the Panel.

```json
{
  "object": "stats",
  "attributes": {
    "state": "on",
    "memory": {
      "current": 728.0,
      "limit": 1024.0
    },
    "cpu": {
      "current": 0.694,
      "cores": [
        0.562,
        0.132
      ],
      "limit": 0.0
    },
    "disk": {
      "current": 88.0,
      "limit": 200.0
    }
  }
}
```
