### ISSUE TITLE
FTP upload/permissions

### ISSUE THREAD

**Issue by primaxius** [Pterodactyl/Panel#901]
* Panel or Daemon: Both 
* Version of Panel/Daemon: Panel (dev 0.7.0) Daemon v0.5.0-beta.5
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10, fillezilla

## Add Details Below:
Created a CSGO server, used the SFTP settings to upload the files for metamod and sourcemod.
Booted the server, errors with permissions/crashed when player joins.
checked the files in /srv/daemon-data/SERVERID and noticed that instead of pterodactyl:ssh being the file owner (like the rest of the files) for what I just uploaded they were root:root
https://gyazo.com/91d50168e8e59e59bb856a3ab3ae1e4a

**Comment by primaxius** [comment]
Tested again using filezilla, created a folder 
![4ac9659ae3f8d0b3499f12c04d8c4093-png](https://user-images.githubusercontent.com/20571191/35550749-16e3583e-0549-11e8-9f4e-b116ec326e63.jpg)
and then checked the ownership of the folder...
![bbdcf2628088bf440c715c8b72e655bd-png](https://user-images.githubusercontent.com/20571191/35550769-2a96c2f8-0549-11e8-9d95-2973cc5cb569.jpg)

**Comment by DaneEveritt** [comment]
Cannot reproduce.
