### ISSUE TITLE
Searching users in the Create server wont proceed

### ISSUE THREAD

**Issue by Milbodoe** [Pterodactyl/Panel#902]
Please describe your issue in full below. Include what products are affected, as well as what version(s) you are running. Please also include information about your system, such as `uname -a` and `php -v` and `docker info` if applicable.

If you're just making a suggestion, be descriptive, and link to any issues that might be releated as well.

You can delete from this line up.
---------------------

* Panel or Daemon: 
* Version of Panel/Daemon: 
* Server's OS: 
* Your Computer's OS & Browser: 

## Add Details Below:

only issues i have (Just installed today on Ubuntu 16.04, every works, except when creating a server, the usernames wont pop up)

`/admin/users/accounts.json?q=we 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by DaneEveritt** [comment]
Please provide the Panel error logs and all of the information that you did not provide in the issue template above.

**Comment by Milbodoe** [comment]
Panel
0.6.4
Ubuntu 16.04
Windows 10 Pro, Google Chrome

Log : https://pastebin.com/mJWPjqpG

**Comment by DaneEveritt** [comment]
PHP 7.2 is not supported, please downgrade or upgrade the Panel to 0.7 beta.

**Comment by Milbodoe** [comment]
The results could not be loaded. (is what it shows me in the dropdown)

**Comment by Milbodoe** [comment]
Thanks worked like a charm :)
