### ISSUE TITLE
Auto - Suspend Server

### ISSUE THREAD

**Issue by ReconV** [Pterodactyl/Panel#909]
I suggest you add the auto - Suspend Server, in order to automatically block the server after a set time by the administrator or api.

**Comment by parkervcp** [comment]
Can you give a reason why this would be needed?

**Comment by DaneEveritt** [comment]
If you really need this functionality you can build it into your billing system or build something that utilizes the API.

I’m not putting this in the core.

**Comment by ReconV** [comment]
can I ask for some pattern?

**Comment by GigaByte-X** [comment]
> Can you give a reason why this would be needed?

Because some of us own hosting companies and don't want to be on 24/7 monitoring the servers saying "OH! ITS A SECOND PASSED WHEN I WAS SUPPOSED TO SUSPEND THE SERVER! I AM SO UPSET!"...
