### ISSUE TITLE
Update PHP socket in the webserver configuration

### ISSUE THREAD

**Issue by stanjg** [Pterodactyl/Panel#913]
* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.7 RC
* Server's OS: Ubuntu
* Your Computer's OS & Browser: Not relevant

## Add Details Below:

In the documentation PHP 7.2 gets installed. However in the nginx webserver configuration the php 7.1 socket still gets used, resulting in a 502 bad gateway error.

## Fix

Change `fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;` to `fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;`

**Comment by DaneEveritt** [comment]
Done, thanks
