### ISSUE TITLE
Invalid mount config for bind

### ISSUE THREAD

**Issue by Exonical** [Pterodactyl/Panel#916]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v0.5.0-rc.1
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 / Firefox

## Add Details Below:

Daemon installed fine when first setting it up, made the core.json and connected it to the panel. After a restart of the server I got an error when starting wings.
```20:16:57.222Z FATAL wings: A fatal error caused the daemon to abort the startup.
    Error: (HTTP code 400) unexpected - invalid mount config for type "bind": bind source path does not exist
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1055:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    --
    additional: {
      "statusCode": 400,
      "json": {
        "message": "invalid mount config for type \"bind\": bind source path does not exist"
      }
    }
20:16:57.223Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.
```

**Comment by DaneEveritt** [comment]
Please provide more than just the line with the error. Its hard for me to figure out the context with only the information provided.

Please also provide the output of `docker info`

**Comment by Exonical** [comment]
`root@us1:~# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-32-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.605GiB
Name: us1.rapidnetworks.org
ID: KR4N:HADJ:7KRN:S5K7:QB4A:O6WM:R4OD:YNKQ:3N4R:5PP6:EB5X:DPAT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
`

Full `sudo npm start` output
`22:56:03.127Z  INFO wings: + ------------------------------------ +
22:56:03.133Z  INFO wings: | Running Pterodactyl Daemon v0.5.0-rc.1    |
22:56:03.134Z  INFO wings: |        https://pterodactyl.io        |
22:56:03.134Z  INFO wings: |  Copyright 2015 - 2017 Dane Everitt  |
22:56:03.134Z  INFO wings: + ------------------------------------ +
22:56:03.134Z  INFO wings: Loading modules, this could take a few seconds.
22:56:04.057Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
22:56:04.191Z  INFO wings: Configuring user pterodactyl (id: 111) as the owner of all server files.
22:56:04.208Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
22:56:04.211Z  INFO wings: Checking container networking environment...
22:56:04.242Z  INFO wings: Found network interface for daemon: pterodactyl_nw
22:56:04.244Z  INFO wings: Configuring timezone file location...
22:56:04.245Z  INFO wings: Checking pterodactyl0 interface and setting configuration values.
22:56:04.246Z  INFO wings: Checking gateway for pterodactyl0
22:56:04.269Z  INFO wings: Gateway detected as 172.18.0.1 for pterodactyl0.
22:56:04.804Z  INFO wings: Checking current files aganist panel response.
22:56:04.814Z  INFO wings: Attempting to load servers and initialize daemon...
22:56:04.840Z  WARN wings: Container was not found. Attempting to recreate it. (server=3988e3c1-9b3c-455d-bd44-6b21ce49ab19)
22:56:04.845Z  INFO wings: Checking if we need to update image exonical/pterodactyl-fivem, if so it will happen now.
22:56:06.457Z  INFO wings: Pulling image exonical/pterodactyl-fivem ... this could take a few minutes.
22:56:06.476Z FATAL wings: A fatal error caused the daemon to abort the startup.
    Error: (HTTP code 400) unexpected - invalid mount config for type "bind": bind source path does not exist
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1055:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    --
    additional: {
      "statusCode": 400,
      "json": {
        "message": "invalid mount config for type \"bind\": bind source path does not exist"
      }
    }
22:56:06.479Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.
`

**Comment by DaneEveritt** [comment]
Is there a folder for `3988e3c1-9b3c-455d-bd44-6b21ce49ab19` in `/srv/daemon-data`?

**Comment by DaneEveritt** [comment]
@Exonical any follow up on this?

**Comment by JzJad** [comment]
Seems to be an issue that occurs when re-installing a server, if It happens again ill grab all logs possible. Quick fix was to mkdir in daemon-data of the container eg mkdir 3988e3c1-9b3c-455d-bd44-6b21ce49ab19
