### ISSUE TITLE
Changing email prevents login with 2fa enabled

### ISSUE THREAD

**Issue by Willsr71** [Pterodactyl/Panel#917]
Changing a user's email prevents them from logging in with 2fa enabled. Changing the email back to the original allows the user to log in again. Disabling 2fa for the user also allows them to log in again.

* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.0-rc.2
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows 10 / Chrome 66.0.3334.2

**Comment by NEXUS2345** [comment]
It appears that the panel is using the email to generate the auth token for 2FA, and when the email is changed, it is then regenerating this token. This token should not be regenerated unless the user explicitly requests it to be.

**Comment by DaneEveritt** [comment]
@NEXUS2345 it is not using the email to generate a secret, that would be highly insecure. It uses a defined number to generate a random string which is then used. The email is only used when generating a QR code which allow you to easily know what account belongs to what in your 2FA app.

https://github.com/Pterodactyl/Panel/blob/e49c739bde33242c6f07443f67c554fe104e86dc/app/Services/Users/TwoFactorSetupService.php#L72

**Comment by DaneEveritt** [comment]
I am unable to reproduce this behavior using the steps below:

1. Login as user and enabled 2FA in account.
2. Logout
3. Login as user using 2FA, navigate to account settings, change email.
4. Logout
5. Login using new email and 2FA

**Comment by DaneEveritt** [comment]
Appears this only happens if you change the users email through the Admin CP.

**Comment by DaneEveritt** [comment]
I believe I fixed the issue here. It had nothing to do with 2FA and was being caused by a null password being inserted. Let me know if this doesn't fix your issue, but I've been unable to otherwise replicate anything being caused by 2FA specifically.
