### ISSUE TITLE
Server creation failing due to $node fields being null

### ISSUE THREAD

**Issue by stanjg** [Pterodactyl/Panel#919]
* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.7-rc2
* Server's OS: Ubuntu 16.04
* Your Computer's OS & Browser: Windows, Google Chrome (Using postman to make API requests)

## Add Details Below:

I was playing with server creation in the API, I am quite sure my request is right, I have looked in the StoreServerRequest class and all my fields are correctly validated, so that's not the problem.

However when I then make a request I get:
```
{
    "errors": [
        {
            "code": "NoViableNodeException",
            "status": "400",
            "detail": "No nodes satisfying the requirements specified for automatic deployment could be found."
        }
    ]
}
```
However with the deployment settings I am passing on with the request there should definitely be a node viable. So I went to investigate.

I figured out the error was thrown from the `FindViableNodesService` class. I then changed a couple things so the if statement in the for loop in the `handle` method looked like this:
``` 
if (($node->sum_memory + $this->memory) > $memoryLimit || ($node->sum_disk + $this->disk) > $diskLimit) {
    throw new NoViableNodeException($node->sum_memory + $this->memory . ' | ' . $memoryLimit . ' | ' . $node->memory);
    continue;
}
```
But then the result was:
```
{
    "errors": [
        {
            "code": "NoViableNodeException",
            "status": "400",
            "detail": "256 | 0 | "
        }
    ]
}
```

Which made me curious, so I went ahead and put this above the original if statement.
```
if (is_null($node->memory)) {
  throw new NoViableNodeException('test');
}
```
Result:
```
{
    "errors": [
        {
            "code": "NoViableNodeException",
            "status": "400",
            "detail": "test"
        }
    ]
}
```

I did one more test and found out that `$node->disk` is also null.

Is this a bug, or am I missing something?

**Comment by DaneEveritt** [comment]
What are the allocation limits on that node for disk and memory?

**Comment by stanjg** [comment]
These are my allocation limits:
![Allocation Limits](http://this-picture.is-really.cool/i/DIw.png)

The request I was sending:
```JSON
Endpoint: /api/application/servers
Method: POST

{
	"name":"testwithapi",
	"user": 1,
	"egg": 1,
	"docker_image": "quay.io/pterodactyl/core:java",
	"startup": "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}",
	"environment": {
		"SERVER_JARFILE": "server.jar",
		"VANILLA_VERSION": "latest"
	},
	"limits": {
		"memory": 256,
		"swap": 0,
		"disk": 256,
		"io": 500,
		"cpu": 400
	},
	"deploy": {
		"locations":[1],
		"dedicated_ip": false,
		"port_range": ["25565"]
	}
}
```

**Comment by DaneEveritt** [comment]
Is there an open port `25565` on any node in location 1?

**Comment by stanjg** [comment]
Yes, there is.

Also if there wouldn't be one it makes no sense for those to be null.

**Comment by DaneEveritt** [comment]
I cannot reproduce this at all, and it makes no sense how it could be getting null back unless there is some type of data-integrity issue in the database.

Can you manually run this command for me and let me know what it outputs?
```
select `nodes`.`id`, `nodes`.`memory`, `nodes`.`disk`, `nodes`.`memory_overallocate`, `nodes`.`disk_overallocate`, IFNULL(SUM(servers.memory), 0) as sum_memory, IFNULL(SUM(servers.disk), 0) as sum_disk from `nodes` inner join `servers` on `servers`.`node_id` = `nodes`.`id` where `nodes`.`public` = 1 and `nodes`.`location_id` in (1)```

**Comment by stanjg** [comment]
```
+----+--------+------+---------------------+-------------------+------------+----------+
| id | memory | disk | memory_overallocate | disk_overallocate | sum_memory | sum_disk |
+----+--------+------+---------------------+-------------------+------------+----------+
| NULL |   NULL | NULL |                NULL |              NULL | 0          | 0        |
+----+--------+------+---------------------+-------------------+------------+----------+
1 row in set (0.00 sec)
```
This probably explains why the fields are null, but I don't get why it would properly display on the webpage.

**Comment by DaneEveritt** [comment]
Can you show your nodes and locations table for me (stripping out sensitive info as needed).

**Comment by stanjg** [comment]
Nodes:
https://hastebin.com/ufitiqudim.sm

Locations:
```
MariaDB [ptero]> select * from locations;
+----+-------+------+---------------------+---------------------+
| id | short | long | created_at          | updated_at          |
+----+-------+------+---------------------+---------------------+
|  1 | Test  | Test | 2017-12-06 19:20:53 | 2017-12-06 19:20:53 |
+----+-------+------+---------------------+---------------------+
1 row in set (0.00 sec)
```

**Comment by DaneEveritt** [comment]
And are there any servers on this node?

**Comment by stanjg** [comment]
No, not currently.

Here you can see the allocations and that there are no servers assigned to them.
![Allocations](http://this-picture.is-really.cool/i/J6N.png)
