### ISSUE TITLE
php artisan down leads to exception

### ISSUE THREAD

**Issue by samyratchet** [Pterodactyl/Panel#920]
This error occurs during the upgrade process to 0.7:
https://pastebin.com/raw/23Zdq5MD

The panel uses php7.1 from plesk.

```
$ uname -a
Linux ve701.venus.fastwebserver.de 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ php -v
PHP 5.4.16 (cli) (built: Nov  6 2016 00:29:02) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.0.18, Copyright (c) 2002-2015, by ionCube Ltd.
(Panel was working before the upgrade, i think it was using php 7.1 from plesk (located at /opt/plesk/php/7.1/bin/php).
```

* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.6 -> 0.7 rc2
* Server's OS: CentOS 7
* Your Computer's OS & Browser: windows 10, google chrome

This issue has been requested by @parkervcp on GitHub.

**Comment by Exonical** [comment]
You’re using Plesk which isn’t supported, more than likely won’t get support for this

**Comment by samyratchet** [comment]
Hello,

I know from the support on discord, they said i can try on github and find someone that has experience with it.

**Comment by schrej** [comment]
We usually don't provide support via GitHub but as @parkervcp requested you to open that issue I'll keep it open for now. I also cleaned up some stuff.

**Comment by samyratchet** [comment]
Thanks, hope someone could help me to fix it ;)

**Comment by lancepioch** [comment]
1. Your version of PHP is 5.4 in the console, this app requires PHP 7.0+.
2. Once you've fixed that, make sure to run `composer install`

**Comment by schrej** [comment]
Very good call, that's probably the issue. If it isn't please reopen the issue.
