### ISSUE TITLE
Problem with Server Owner Creating Subusers

### ISSUE THREAD

**Issue by lordweatherman** [Pterodactyl/Panel#927]
* Panel or Daemon:  Panel
* Version of Panel/Daemon:  7.0 RC-2
* Server's OS:  CENTOS 7 
* Your Computer's OS & Browser:  Windows 10 64x Chrome

## Add Details Below:
Found a problem when creating a new subuser as the server owner where it would fail if the email addressed used contained a period before the @ symbol. It would direct you to a page showing something went wrong. If the email did not contain a period then it would create the new subuser just fine.

I was able to create the user account with the email that contained periods before the @ symbol just fine as an administrator, as a work around. Which leads me to think it is related to the username been created from the email address.

**Comment by KasperFranz** [comment]
Do you have any information in your laravel.log file about this?

**Comment by lordweatherman** [comment]
I have attached the error that is shown in the laravel.log file.

[Subuser creation error - laravel.log](https://github.com/Pterodactyl/Panel/files/1712166/Subuser.creation.error.-.laravel.log)
