### ISSUE TITLE
Add labels to buttons on top right of file management

### ISSUE THREAD

**Issue by NEXUS2345** [pterodactyl/panel#937]
I was looking at file manager, and attempting to copy a file. I clicked the button that looks like a document, and all of a sudden I am creating a new file. The lack of buttons causes major issues regarding user experience, especially for people new to the panel. This would be a simple fix, either include labels in the buttons themselves or create hover-over tooltips.

**Comment by DaneEveritt** [comment]
I finished this in a previous commit, forgot to link it to this.

3a5d21f
