### ISSUE TITLE
Unable to set ownership of files properly

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#938]
Everytime i try to start my existing server, i get following error:
```
{"name":"wings","hostname":"srv01","pid":29632,"server":"2cb21377-797f-4f86-a704-b2d4793ba128","level":50,"err":{"message":"Unable to set ownership of files properly, exited with code 1 signal null.","name":"Error","stack":"Error: Unable to set ownership of files properly, exited with code 1 signal null.\n    at ChildProcess.Exec.on (/srv/daemon/src/controllers/fs.js:107:29)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)"},"msg":"{ errorId: 'MMA2bxurgCAbK4R9zlui' }","time":"2018-02-14T16:03:32.708Z","v":0}
```
---------------------
* Version of Panel/Daemon: LATEST (BOTH)
* Server's OS: Ubuntu 16.04.3

**Comment by DaneEveritt** [comment]
Does `/srv/daemon-data/2cb21377-797f-4f86-a704-b2d4793ba128` exist?

**Comment by ProJaCore** [comment]
I dont use `/srv/daemon-data`, i use `/srv/server`:
![grafik](https://user-images.githubusercontent.com/12472791/36218340-4fb40222-11b4-11e8-84fb-9508285c0fda.png)
i checked the core.json: 
![grafik](https://user-images.githubusercontent.com/12472791/36218401-859ecfa2-11b4-11e8-9a33-686c894f7522.png)
Theres something not using the given path ^^

**Comment by DaneEveritt** [comment]
Do `userdel pterodactyl` and restart the daemon letting it generate a new user.

**Comment by ProJaCore** [comment]
Worked! thank you

**Comment by DaneEveritt** [comment]
Cool, there was a bit of a hiccup in the user creation stuff in the betas, so this tends to happen occasionally for people when updating. Should be all resolved now, let me know if it occurs again.
