### ISSUE TITLE
Moving the Entrypoint.sh to the Panel

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#939]
I have a wonderful idea that may not work but here is it:

Custom images for every game are kind of unnecessary if we can install all the dependencies over the install script and if we can simply fetch the start script (entrypoint.sh) script from the panel.

### e.g. let's edit an egg and go to the install script
we could have a second text box under the install script named: `start script` where we just simply put in the entrypoint script. So it will get executed on every start.(so it represents the entrypoint.sh)

In this way, we could use the stock pterodactyl ubuntu image for several different games.
We would also only use trusted images and there would be no more need for custom images.

One more pro is: We could import eggs and use them without using external images from untrusted sources.

edit: @parkervcp would also not need to create an image for every approved egg.

**Comment by parkervcp** [comment]
I don't need to create an image for every one. I have literally just been adding packages to the base ones.

I had 2 things added to the glibc one for FiveM and sqlite or something added to another. I am not using a "new container, not adding on to the ones that are there.

**Comment by ProJaCore** [comment]
@parkervcp Yeah but to provide e.g. an update on every restart, we need to create custom images for that. so if the image is already stock, why can't it fetch the start script from the panel? that would allow a lot of possibilities without creating a custom image.

**Comment by parkervcp** [comment]
Auto updates work with a simple variable most of the time as far as it comes to srcds things. 

For the others the reinstall should be use for updates. But people can still manually update.

**Comment by ProJaCore** [comment]
Well, I don't see any point why the start script should not be on the panel as well.
I cant run commands before every start without creating a custom image.

Why is that not a good idea?

**Comment by DaneEveritt** [comment]
This won't happen. The entrypoint script serves solely as a means to execute the startup command and setup some environment variables. Letting this be edited only introduces more potential issues. The point of containers is that they act as an environment for the process, they shouldn't be working as a VM where an entire script gets executed every time you are starting the server.
