### ISSUE TITLE
Cannot send emails with Mailgun (Incorrectly named .env parameter?)

### ISSUE THREAD

**Issue by TehTotalPwnage** [Pterodactyl/Panel#942]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.6.4
* Server's OS: Ubuntu 16.04 (64-bit)
* Your Computer's OS & Browser: Ubuntu 16.04 (64-bit), Mozilla Firefox 58.01 (64-bit)

## Add Details Below:
I used the `php artisan pterodactyl:mail` command in order to set up Mailgun for sending out my Panel emails, but I failed to get the Panel to send the emails properly. I was using password reset emails as a test to see if emails were working. Upon checking the logs, I noted that the `Pterodactyl\Notifications\SendPasswordReset` job was failing. Upon further inspection of the logs, I noticed that GuzzleHttp (which I assume Laravel's Mailgun API uses internally for sending emails) was returning a `401: Unauthorized` error.

At first, I couldn't figure out why the Panel would possibly return a 401: Unauthorized error for the Mailgun requests. I checked the `.env` file, recached the configuration with `php artisan config:cache`, and ran a request to the Mailgun servers using cURL, and nothing seemed to suggest that anything was wrong. The cURL request ran fine and the credentials were fine: it was just Guzzle returning an error.

After reading through various articles and questions regarding Laravel's implementation of Mailgun online, I noticed that all of the configurations online noted that the `config/services.php` file had a block of code that looked similar to this:
```
'mailgun' => [
'domain' => env('MAILGUN_DOMAIN'),
'secret' => env('MAILGUN_SECRET'),
],
```
I checked this repository's `services.php` file and noticed it had the same thing. Then it dawned on me that the Mailgun Private API Key is stored as `MAILGUN_KEY` rather than `MAILGUN_SECRET` inside of the `.env` file. When I added the `MAILGUN_SECRET` line myself and recached the configuration, my Panel was able to send out emails properly.

I'm not sure if this is an actual issue for anyone else, because to me it seems like a ridiculous idea that the Panel would have an issue with Mailgun not working that would go unnoticed for God knows how long. It's probably more likely that this bug report is the result of me not doing something properly when setting up the Panel. The code does seem to suggest that it's an issue though, and it seems intuitive enough to change the variable to either `MAILGUN_SECRET` or `MAILGUN_KEY` throughout the code to fix this issue.

**Comment by DaneEveritt** [comment]
Thats a bug in both versions, you're correct it is looking for `MAILGUN_SECRET` but I am passing in `MAILGUN_KEY`.

Thanks for finding that. 👍
