### ISSUE TITLE
Could not load results

### ISSUE THREAD

**Issue by Alontrle** [Pterodactyl/Panel#944]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.6.4 
* Server's OS: 16.04
* Your Computer's OS & Browser: Windows 10, Firefox Quantum

## Add Details Below:
Whenever I try and create a server and add the user it says "The results could not be loaded" when I put a real user in.

**Comment by ProJaCore** [comment]
You should also do some screenshots and add some logs

**Comment by Alontrle** [comment]
There are no panel logs. 
Screenshot: https://cdn.discordapp.com/attachments/122903114423599104/414269184499777537/unknown.png

**Comment by metallicgloss** [comment]
Make sure you're using PHP 7.1 rather than 7.2.

`php -v`

If that shows 7.2, run:

`sudo a2dismod php7.2 ; sudo a2enmod php7.1 ; sudo service apache2 restart`

**Comment by Alontrle** [comment]
Thank you! I followed the documentation from start to finish every command but I guess it installed 7.2 instead, well that works thansk man
