### ISSUE TITLE
Bug relating to 2FA and Logging out of the panel

### ISSUE THREAD

**Issue by m4rkey** [Pterodactyl/Panel#950]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.0
* Server's OS: Debian 9
* Your Computer's OS & Browser: Firefox, Windows 10

I reported this in discord as well, but when trying to enable 2FA on my account I get this error. [2FA Error](https://gyazo.com/84b35ef2b346c1801b8c08d46770864b)

After that, I started to investigate to see if there was additional problems and upon trying to logout of the panel it redirects me to the [Whoops, Looks like something went wrong page](https://gyazo.com/3d50cb3a110a43705f51e4132904fc14 ) and this is happening on the /auth/logout page

Here are my logs from the panel. https://bin.ptdl.co/yazhi/

**Comment by ElliotGluck** [comment]
I’m having a similar issue except it’s also occurring on /auth/login in addition to /auth/logout.

When I refresh the page however, it seems that the authentication works.
