### ISSUE TITLE
Bug relating to not finding .jar files

### ISSUE THREAD

**Issue by max-glbvps** [Pterodactyl/Panel#951]
I recently uninstalled old version of Pterodactyl and installed the new version and cleared my database, before installing 7.0 of the panel. Suddenly, when I attempted to start the server I got an error stating that it couldn't find the .jar files in any type of game server or voice server. I contacted multiple people and they couldn't figure out the issue.

Docker information: https://hastebin.com/zohucayoco.js
Uname and PHP information: Linux ns538395 4.9.58-xxxx-std-ipv6-64 #1 SMP Mon Oct 23 11:35:59 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux (CentOS 7.4)

Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2, Copyright (c) 1999-2018, by Zend Technologies

--

* Panel or Daemon: Issue with locating files on the panel (.jar) files and all file permissions of some sort.
* Version of Panel/Daemon: Latest version of panel and the daemon (Daemon Logs: https://hastebin.com/ixeyadufit.json)
* Server's OS: CentOS 7.4
* Your Computer's OS & Browser: Windows 10 & Chrome
* Screenshots: Listed below is a list of screenshots that I have taken to provide some insight into what is happening.
https://dbl.is-killing.me/n5aey.png
https://dbl.is-killing.me/qhb8q.png
https://dbl.is-killing.me/rp67v.png

**Comment by DoNotSpamPls** [comment]
Just a heads-up, in the `Panel or Daemon:` section, you should say whether your issue is related to the Panel or Daemon.

**Comment by max-glbvps** [comment]
I believe it is with the panel not locating the files- it's not the daemon for sure.

**Comment by mputkowski** [comment]
@max-glbvps It's not the Panel (even Daemon). You assigned not enough memory to your server, Daemon tries to build BungeeCord but it fails due out of memory. I had the same issue with Spigot but in that case I could enter "download link" so I setup server to download compiled binary and that worked.

I'm not sure about this, it's just my observations.

**Comment by max-glbvps** [comment]
@mputkowski That isn't true, I put 2000 memory and RAM and it still doesn't work.

**Comment by max-glbvps** [comment]
to a bungeecord server

**Comment by DoNotSpamPls** [comment]
@mputkowski Spigot needs to be built, but BungeeCord is freely distributed as binaries. That's not the issue.

**Comment by DaneEveritt** [comment]
Cannot reproduce with a fresh Bungeecord server created through the Panel.
