### ISSUE TITLE
Cannot kill Server & further issues

### ISSUE THREAD

**Issue by StealWonders** [Pterodactyl/Panel#955]
Hey I have alot of console output and the server started getting timeouts at some point and the console was 20 minutes behinde the actual real time. I tried stopping the server with it doing something but I can't kill the docker container via panel or commandline. After waiting 5 minutes I still can't seem to be able to kill it but the log (in console) keeps flowing
---------------------

* Panel version: 7.0.0
* Version of /Daemon: 5.0.0
* Server's OS: Ubuntu 16.04 LTS
* Your Computer's OS & Browser: Windows 10 & Firefox

**Comment by DoNotSpamPls** [comment]
Panel version 7.0.0? Wow, you're really into the future 🤔 
On a serious note, that should be 0.7.0, right?

**Comment by StealWonders** [comment]
Yeah sorry I didnt copy it from the website: wrote it down from my head :)

**Comment by DaneEveritt** [comment]
This should now be fixed and will be released shortly.
