### ISSUE TITLE
Database Management

### ISSUE THREAD

**Issue by ki2007** [Pterodactyl/Panel#957]
---------------------

* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.0 / 0.5.0
* Server's OS: Ubuntu 16.04.3 LTS
* Your Computer's OS & Browser: Windows 10 Pro, Google Chrome 63

## Add Details Below:

- [x] So after updating to the new Panel and Daemon Version, I tried to add a database host. I have not done that before the update so I do not know whether or not something changed.
When trying to add a new database host it says "IP address or FQDN" underneath the Host field.
Anyway a FQDN is not allowed because "The host must be a valid IP address.".
![ip_error](https://user-images.githubusercontent.com/1445217/36355037-30409528-14dd-11e8-9993-312f192efda5.png)
(There is also a spelling mistake in the German translation above.)

- [x] When adding a new database, the prefix says "s1_" but instead the database is named "d1_" when being created.
![db_name](https://user-images.githubusercontent.com/1445217/36355091-09af92be-14de-11e8-87d2-095448f00f0a.png)

- [x] ~~And lastly those two buttons do not do anything.~~ (Chrome Cache problem)
![buttons](https://user-images.githubusercontent.com/1445217/36355106-51d0777a-14de-11e8-918f-dadd24e8d623.png)
They only show these two messages:
![errors](https://user-images.githubusercontent.com/1445217/36355114-9845ebae-14de-11e8-8112-a3158a877c83.png)

**Comment by DaneEveritt** [comment]
Can you please provide the error logs for those two error messages at the bottom?

**Comment by ki2007** [comment]
There is no error generated in the laravel.log.
But here is the access log of nginx maybe that helps because it shows 404 status:
http://bin.ptdl.co/c6k4b

**Comment by DaneEveritt** [comment]
Are you looking in the `laravel.log` file, or the `laravel-<date>.log` file?

**Comment by ki2007** [comment]
This one: laravel-2018-02-18.log

**Comment by DaneEveritt** [comment]
Interesting, I'll see what I can find, thanks for the info and pictures!

**Comment by DaneEveritt** [comment]
I am unable to replicate the behavior on the last checkbox above.
