### ISSUE TITLE
Display PID on Admin Panel

### ISSUE THREAD

**Issue by vipesz** [pterodactyl/panel#958]
* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.7
* Server's OS: CentOS 7.4 & Debian 9
* Your Computer's OS & Browser: N/A

## Add Details Below:

Having the ability for the panel to display servers process ID for easier management

**Comment by DaneEveritt** [comment]
Closing, docker can provide this information if needed as containers use the server UUID as their name.
