### ISSUE TITLE
Global Hidden Subusers

### ISSUE THREAD

**Issue by vipesz** [Pterodactyl/Panel#959]
* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.7.0
* Server's OS: CentOS 7.4/Debian 9
* Your Computer's OS & Browser: N/A

## Add Details Below:

Ability to add hidden subusers for easier commercial use. (Ability to allow staff members to have subuser access to all servers without being displayed or able to be removed by the end user)

This enables a fine grain permission system that I imagine would not require **too** much work.

**Comment by DaneEveritt** [comment]
I think this falls under admin permissions which already have an issue on here to be made. 👍
