### ISSUE TITLE
Team Fortress named 'Insurgency' in panel.

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#96]
Appears I was doing too much copy and paste in the seeder and ended up setting Team Fortress to be named Insurgency, so now the only thing to distinguish them is the game name after selecting it.

💯

**Comment by MeltedLux** [comment]
https://github.com/Pterodactyl/Panel/pull/97

**Comment by DaneEveritt** [comment]
This was fixed in a previous commit.
