### ISSUE TITLE
Allow direct Allocation from the Server creation Tab

### ISSUE THREAD

**Issue by ProJaCore** [Pterodactyl/Panel#961]
Every time I create a Server I forget to allocate the port.
So I have to add these and reload the Server creation Site...
I hope we could have some shortcut in terms of "if the given port could not found just create it."

**Comment by DaneEveritt** [comment]
I'm not going to change this behavior, you should have allocations already created before you start creating servers and assigning them to an allocation.

**Comment by ProJaCore** [comment]
Does this behavior have any special reason? Maybe reserving?

**Comment by DaneEveritt** [comment]
It becomes a confusing UI and introduces more code that can break down the road. I don't really see why you wouldn't pre-allocate a block of IPs and ports that might be needed. This behavior you're suggesting allows external services to hit the API with invalid ports and ranges potentially creating allocations and assigning servers to them when they should not be.
