### ISSUE TITLE
Shell Scripts editable by default

### ISSUE THREAD

**Issue by planeguy98765** [Pterodactyl/Panel#962]
* Panel or Daemon:  Panel
* Version of Panel/Daemon: v.0.6.4+ 
* Server's OS: CentOS 7.4
* Your Computer's OS & Browser: Windows 10, Chrome

## Add Details Below:
`text/x-shellscript` is editable by default in `Pterodactyl\Repositories\HelperRepository`.

Allows users to run shell commands within the executable files.

**Comment by parkervcp** [comment]
I have already called out things like this in - https://github.com/Pterodactyl/Panel/issues/895

**Comment by DaneEveritt** [comment]
This is not a bug and is known and intended behavior.
