### ISSUE TITLE
Daemon randomly creates /srv/data 

### ISSUE THREAD

**Issue by vipesz** [pterodactyl/panel#964]
---------------------

* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.4.5
* Server's OS: CentOS 7.4/Debian 9
* Your Computer's OS & Browser: N/A

The Daemon randomly creates a directory in /srv/, and places the server data in a folder named data. This happens particularly when the server is symlinked.

There is no substantial log output. I will post it however incase I miss something.

It's worth noting that this is only for when users connect via SFTP with a ftp program. The web based FTP works just fine.

```
{"name":"wings","hostname":"na24","pid":3785,"server":"725167a9-88d9-4765-8a08-fcf17247e921","level":30,"msg":"Blocking server boot until option installation process is completed.","time":"2018-02-19T23:17:46.379Z","v":0}
{"name":"wings","hostname":"na24","pid":3785,"server":"725167a9-88d9-4765-8a08-fcf17247e921","level":30,"msg":"Writing output of installation process to file. { file: /srv/daemon/config/servers/725167a9-88d9-4765-8a08-fcf17247e921/install.log' }","time":"2018-02-19T23:17:46.608Z","v":0}
{"name":"wings","hostname":"na24","pid":3785,"level":30,"msg":"Pulling image alpine:3.4 ... this could take a few minutes.","time":"2018-02-19T23:17:46.843Z","v":0}
{"name":"wings","hostname":"na24","pid":3785,"server":"725167a9-88d9-4765-8a08-fcf17247e921","level":30,"msg":"Temporarily suspending server to avoid mishaps...","time":"2018-02-19T23:17:47.468Z","v":0}
```

**Comment by vipesz** [comment]
Additional Note:

The steps to fix require me to move all the data from /srv/data to /srv/daemon-data and remove the old directory. Here's the core.json configuration:

```{
  "web": {
    "host": "0.0.0.0",
    "listen": 8080,
    "ssl": {
      "enabled": true,
      "certificate": "/etc/letsencrypt/live/na24.pebblehost.com/fullchain.pem",
      "key": "/etc/letsencrypt/live/na24.pebblehost.com/privkey.pem"
    }
  },
  "docker": {
    "socket": "/var/run/docker.sock",
    "autoupdate_images": true,
    "interface": "172.18.0.1",
    "timezone_path": "/etc/localtime"
  },
  "sftp": {
    "path": "/srv/daemon-data",
    "port": 2022,
    "container": "96976bebf0c07fc9dab683e18b92a22bf5a92b209d1440b22cd49f5811832835"
  },
  "logger": {
    "path": "logs/",
    "src": false,
    "level": "info",
    "period": "1d",
    "count": 3
  },
  "remote": {
    "base": "https://panel.pebblehost.com"
  },
  "uploads": {
    "size_limit": 100
  },
  "keys": [
    "OMITTED"
  ]
}
```

**Comment by schrej** [comment]
You are talking about the daemon, not the panel, correct?
You are actually using Daemon 0.4.5, not 0.5.x?
Did you recently change the daemon data directory?

**Comment by vipesz** [comment]
Yes, it is the daemon. Sorry about that.

No - this was a vanilla installation. Regular deployment.

We are using 0.4.5 - we have not updated to v0.5.x yet.

**Comment by DaneEveritt** [comment]
I'm closing this since we've gotten you upgraded and I haven't heard about this happening from you since, nor anyone else.
