### ISSUE TITLE
Variables in Install Script and entrypoint.sh

### ISSUE THREAD

**Issue by GwtLabs** [pterodactyl/Panel#965]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.5.1
* Server's OS: Ubuntu 16.04.3 LTS
* Your Computer's OS & Browser: Win10, Chrome
* Version of Panel: 0.7.1

## Add Details Below:
There is no access to environment variables (SERVER_PORT) in install script. There are only variables created additionally in panel. For example, Ts3 install script is not working properly. The default_voice_port and query_port is inserted using "Configuration Files", and not as if it indicated using the installation script.

Is it possible to get into these all variables in entrypoint.sh?

**Comment by parkervcp** [comment]
You would use ${SERVER_PORT} in the install script.

**Comment by GwtLabs** [comment]
It does not work. For example, I made the installation script:
`#!/bin/ash
cd /mnt/server
echo 'TS_VERSION: '${TS_VERSION} >> variables.txt
echo 'SERVER_MEMORY: '${SERVER_MEMORY} >> variables.txt
echo 'SERVER_PORT: '${SERVER_PORT} >> variables.txt
echo 'SERVER_IP: '${SERVER_IP} >> variables.txt
`
I received in file variables.txt:
`TS_VERSION: 3.0.13.8
SERVER_MEMORY: 
SERVER_PORT: 
SERVER_IP: 
`

**Comment by mpavel27** [comment]
Do you know what's the variable for server uuid?

**Comment by K4ryuu** [comment]
> Do you know what's the variable for server uuid?

If anyone is still looking for an answer to similar question like this, then you can add this to any egg entrypoint:
`env >> variables.txt`

With this you can list what variables are available in the given Egg.
