### ISSUE TITLE
Issues Migrating Database

### ISSUE THREAD

**Issue by KadotyGamer** [pterodactyl/Panel#972]
---------------------

* Panel or Daemon: Panel
* Version of Panel/Daemon: Upgraded to 0.7.1
* Server's OS: CentOS 7
* Your Computer's OS & Browser: Windows 10, Mozilla Firefox

## Add Details Below:
I am trying to migrate the database over from 0.6.4 to 0.7.1 and I get the following errors: https://hastebin.com/fogitofozo.coffeescript

**Comment by ET-Bent** [comment]
´´´
[root@panel pterodactyl]# php artisan migrate --force

In Connection.php line 664:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'schedules'
  already exists (SQL: create table `schedules` (`id` int unsigned not null a
  uto_increment primary key, `server_id` int unsigned not null, `name` varcha
  r(191) null, `cron_day_of_week` varchar(191) not null, `cron_day_of_month`
  varchar(191) not null, `cron_hour` varchar(191) not null, `cron_minute` var
  char(191) not null, `is_active` tinyint(1) not null, `is_processing` tinyin
  t(1) not null, `last_run_at` timestamp null, `next_run_at` timestamp null,
  `created_at` timestamp null, `updated_at` timestamp null) default character
   set utf8mb4 collate utf8mb4_unicode_ci)


In PDOStatement.php line 107:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'schedules'
  already exists


In PDOStatement.php line 105:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'schedules'
  already exists


[root@panel pterodactyl]# php artisan migrate:refresh --force

In Connection.php line 664:

  SQLSTATE[HY000]: General error: 1005 Can't create table `panel`.`#sql-1a1_d
  8` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter
  table `node_configuration_tokens` add constraint `node_configuration_tokens
  _node_id_foreign` foreign key (`node_id`) references `nodes` (`id`))


In PDOStatement.php line 107:

  SQLSTATE[HY000]: General error: 1005 Can't create table `panel`.`#sql-1a1_d
  8` (errno: 150 "Foreign key constraint is incorrectly formed")


In PDOStatement.php line 105:

  SQLSTATE[HY000]: General error: 1005 Can't create table `panel`.`#sql-1a1_d
  8` (errno: 150 "Foreign key constraint is incorrectly formed")
```

*just expanding the hastebin here*

**Comment by KadotyGamer** [comment]
After dropping the table I get this error:
```
[root@panel pterodactyl]# php artisan migrate --force

In Connection.php line 664:

  SQLSTATE[HY000]: General error: 1005 Can't create table `panel`.`#sql-1a1_35b` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `schedules` add constraint `schedules_server_id_foreign` foreign key (`serv
  er_id`) references `servers` (`id`) on delete cascade)


In PDOStatement.php line 107:

  SQLSTATE[HY000]: General error: 1005 Can't create table `panel`.`#sql-1a1_35b` (errno: 150 "Foreign key constraint is incorrectly formed")


In PDOStatement.php line 105:

  SQLSTATE[HY000]: General error: 1005 Can't create table `panel`.`#sql-1a1_35b` (errno: 150 "Foreign key constraint is incorrectly formed")
```

**Comment by KadotyGamer** [comment]
After dropping the `schedules` table, I did the following:
```
USE panel;
SET GLOBAL FOREIGN_KEY_CHECKS=0;
```
and the migration seemed to work fine. No longer having issues migrating.

**Comment by DaneEveritt** [comment]
That is not a fix to this problem and will lead to more and more issues moving forward. 

From the errors initially it looks like you had migrated but nothing got saved so the migration system didn't know where it was supposed to start at.

**Comment by KadotyGamer** [comment]
@DaneEveritt I did re-enable it Global Foreign Key Checks after the migration was successful, more of a temporary fix if problems persist.
