### ISSUE TITLE
API endpoint /nests/<nest id>/eggs/<egg id> broken

### ISSUE THREAD

**Issue by TrixterTheTux** [pterodactyl/Panel#973]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.0 (Though broken on dev according to Dane) 
* Server's OS: Ubuntu 16.04.3 LTS
* Your Computer's OS & Browser: Ubuntu 16.04.3 LTS, Firefox Quantum 58.0.2 (64-bit)

## Add Details Below:

The API endpoint ``/nests/<nest id>/eggs/<egg id>`` responds with:
```
{
	"errors": [
		{
			"code": "ErrorException",
			"status": "500",
			"detail": "An error was encountered while processing this request."
		}
	]
}
```

And in panel logs this error: https://bin.ptdl.co/6so6u/

**Comment by DaneEveritt** [comment]
closed in 620c624
