### ISSUE TITLE
Enable export/import of entire nests

### ISSUE THREAD

**Issue by AevumDecessus** [pterodactyl/Panel#977]
---------------------

* Panel or Daemon:  Panel
* Version of Panel/Daemon:  any
* Server's OS:  n/a
* Your Computer's OS & Browser: n/a

## Add Details Below:
Enable the ability to export entire nests with their eggs, and to import the whole stack onto another panel to make sharing easier.

**Comment by DaneEveritt** [comment]
The plan is still to only support export/import of individual eggs as nests were never designed to be exported, and basically just serve as, excuse the terminology, a nest. They're just a container to hold your eggs, and you can put eggs in whatever nest you like, regardless of if it makes logical sense.

We're working on an egg sharing service that will allow browsing and installation of eggs directly from the Panel that should make sharing even easier.
