### ISSUE TITLE
Add alias to Database Host

### ISSUE THREAD

**Issue by ki2007** [pterodactyl/panel#982]
Currently when adding a new Database Host, providing a FQDN is possible.
When adding with an FQDN the System translates said name to the corresponding IP address and saves it to the Database.

Great would be to add the possibility to either do not translate to the IP and use the FQDN instead or add an additional field as kind of an alias.
This alias will be distributed to the end user on the server database page.

Background: With this change the end users will use the FQDN or alias instead of the IP address which makes it easy to eventually change the database host, while not requiring end users to change their configuration. Only the admin has to change the corresponding DNS entry.

**Comment by DaneEveritt** [comment]
Closed awhile back in https://github.com/pterodactyl/panel/commit/540cc82e3dc28e983fba3388cc942ef9d6217ee9
