### ISSUE TITLE
The external_id field on server creation is being ignored

### ISSUE THREAD

**Issue by TrixterTheTux** [pterodactyl/panel#983]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.2

The external_id field is ignored on POST ``/api/application/servers``
![Image](https://my-cat.is-going-to.space/9768fc.png)

**Comment by DaneEveritt** [comment]
closed inhttps://github.com/pterodactyl/panel/commit/6a4b5e04e28ca91b454e8302018d49a3d24fbe10
