### ISSUE TITLE
Updating server details through api requires allocation field to be set

### ISSUE THREAD

**Issue by TrixterTheTux** [pterodactyl/panel#984]
* Panel or Daemon: Panel
* Version of Panel/Daemon: 0.7.2

The API endpoint PATCH ``/api/application/servers/<server id>/build`` requires allocation field to be set. (I don't know if its intended behaviour, but ALL server detail fields are required)

**Comment by DaneEveritt** [comment]
The `allocation: <id>` field should be passed, that is intended behavior. Sorry I misunderstood in Discord.
