### ISSUE TITLE
Error when trying to add an Unturned server with my egg.

### ISSUE THREAD

**Issue by megoesrawr** [pterodactyl/panel#986]
* Panel or Daemon: panel
* Version of Panel/Daemon: 0.7.2
* Server's OS: Centos 7
* Your Computer's OS & Browser: windows 10, Google Chrome

Error when trying to add an Unturned server with my egg. 
Log: https://pastebin.com/2F6sbjmv
Github of egg: https://github.com/megoesrawr/pterodactyl-unturned

**Comment by DaneEveritt** [comment]
Can you provide the specific egg configuration you're using?

**Comment by megoesrawr** [comment]
https://pastebin.com/1JbCkxN5

**Comment by DaneEveritt** [comment]
`aplha_num` is not a rule, you probably were looking for `alpha_num`.

**Comment by schrej** [comment]
Should we maybe validate the validation rules (so meta)
