### ISSUE TITLE
Does the panel require outbound access?

### ISSUE THREAD

**Issue by xyeLz** [pterodactyl/panel#987]
Currently on 7.2 of the panel and was curious why it requires outbound access? Only reason I discovered this was because I had disabled it. I was able to reach the login page but couldn't login:

[2018-02-25` 14:10:57] production.ERROR: GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 150000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /mnt/efs1/var/www/html/pterodactyl/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186

**Comment by DaneEveritt** [comment]
Well it needs outbound access on the login page for cURL, outbound on Admin pages to get versioning information, and outbound on most everything else to communicate with the daemon.

**Comment by schrej** [comment]
Yes, ReCaptcha needs to contact Google APIs on the login page.

**Comment by xyeLz** [comment]
Are there particular ports that can be opened to allow this communication? I assume the cURL and versioning information would be HTTP/HTTPS, but what about the daemon communication? AFAIK, this was only 8080?

**Comment by schrej** [comment]
If you are using the default port it is 8080, yes.
