### ISSUE TITLE
Better task system

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#99]
Would like to see support for things like:
- Action when a certain line is said (or goes though the console). This would be regex based to allow a lot of flexibility.
- Restart or other action if server cpu, memory, etc. passes a certain threshold.
- Restart/Stop at time, but only if server is empty.

Comment with additional suggestions if you have any.

**Comment by DaneEveritt** [comment]
Can you give an example of how you would be using file editing @ET-Bent ?

**Comment by ET-Bent** [comment]
'Edit' might be the wrong term, more like file modification.

Something like that, but with the possibility to add multiple of these. Also something like one modification in one line would be better usage of space:

![auswahl_817](https://cloud.githubusercontent.com/assets/5788982/19006533/41614a52-8760-11e6-8a62-93648e48a5b7.png)

**Comment by DaneEveritt** [comment]
Interesting idea, just wondering what the specific use cases might be?

**Comment by ET-Bent** [comment]
as stated, you have a config change but cannot reboot a server (let it be Minecraft) right away as plenty of users are online. You could reboot it at 04:30 AM but who wants to stay up just for that? Other possibility you want to enable a special feature for a server at a specific time but don't want to enable it early on as the server may reboot before the desired time (in case of crash), so you can queue it up and just go to bed.

**Comment by DaneEveritt** [comment]
I understand now. For something like that, maybe it would be worth letting the user upload the modified file, and then when the tme comes read the file and send those contents, rather than going through the whole `sed` process, especially for less advanced users.

Looks like the task manager should also support one-time-sending or queued actions.

**Comment by ET-Bent** [comment]
It would be more of a convenience feature. The features you already stated are essential. (ofc. all this could be done via API at any time, but if some common tasks would be point and click, nobody would complain, right?)

**Comment by ET-Bent** [comment]
(hope you see the +1 at your comment above ;) )

**Comment by scalda** [comment]
Also, the ability to edit already made tasks would be nice.

**Comment by DaneEveritt** [comment]
This issue is _finally_ able to be closed. A new schedule system has been implemented in `v0.7.0` that will allow for much better control over tasks and provide more flexibility.
