### ISSUE TITLE
Deamon error /api/remote/eggs 404

### ISSUE THREAD

**Issue by MGoossens1998** [pterodactyl/panel#990]
Dear Pterodactyl,

When I want to start the deamon on my server 'Ubuntu 14.04' It will give this error
https://gyazo.com/fc8914c4925e6f01f3842947a8a533f6

PHP version: 7.2.1-1

Uname -a
Linux vmi161037.contaboserver.net 3.13.0-141-generic #190-Ubuntu SMP Fri Jan 19 12:52:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Docker info

Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 18.01.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 19
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-141-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.74GiB
Name: vmi161037.contaboserver.net
ID: 7OUM:MD3D:G3SX:JJNU:33DO:LZCT:LCW7:6OHR:GIWA:ASPE:ZKMS:4DSF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by schrej** [comment]
Nice, you successfully removed the most important information from the template. What is your daemon and panel version?
I assume you are trying to use Daemon 0.5.x with Panel 0.6.x? If that's the case: You need to update both as Daemon 0.5.x only works with Panel 0.7.x

**Comment by DaneEveritt** [comment]
Feel free to re-open this issue when you can provide the required information that is asked for when first making the issue.

**Comment by lancepioch** [comment]
I'm assuming a mismatch between versions.
