### ISSUE TITLE
Feature Request: Possibility for the daemon to automatically open allocated/in-use ports?

### ISSUE THREAD

**Issue by xyeLz** [pterodactyl/panel#994]
Just a thought here since I have no clue if this is possible due to user account restrictions, OS distribution differences, and/or anything else I'm not aware of on the development side, but it would be really awesome feature if the panel could actually open/close ports on the host based on assigned allocations.

The best case scenario would be if the daemon opens the port once it's actually assigned to a server. However, I would also be happy with the daemon opening the ports once they're allocated to the node within the panel.

The reason I ask for this is because it would simplify the process and would allow my host to be more secure. Currently I just open a giant range of ports and then add whatever I want to the panel. It would be pretty cool if the panel opened only what was explicitly assigned or in-use.

**Comment by parkervcp** [comment]
That is what already happens. 

It uses docker. Docker only opens ports as the container starts.

**Comment by parkervcp** [comment]
The ports aren't open unless they are in use "server is started"

**Comment by xyeLz** [comment]
Let me clarify:

I'm more referring to the firewall layer of the OS, not the Docker container itself. I know that the deployment of a new server will deploy a new container exposing only that particular point. What I was referring to was also allowing that port at the host firewall level.

**Comment by parkervcp** [comment]
You need to have a firewall installed to have it work with the firewall. iptables isn't a firewall.
