### ISSUE TITLE
Fields Reset on Error

### ISSUE THREAD

**Issue by rouing** [pterodactyl/panel#997]
On the Panel (CentOS 7.4, PHP 7.2, Latest Panel/Daemon), whilst creating a Server, if the validation for one field fails; all the fields reset to their default value. This is **EXTREMELY** annoying. I would expect them to cache. 

I propose that the fields should be cached/saved until the page either reloads or is closed.

**Comment by DaneEveritt** [comment]
duplicate of https://github.com/pterodactyl/panel/issues/889
